executor.master: ActivityManager.hpp File Reference
ActivityManager.hpp File Reference
#include <deque>
Classes
class ActivityManager
class UnsafeBlock
class CalloutBlock
class NativeContextBlock
Functions
void reportCondition (RexxString *condition, RexxString *description)
void reportNovalue (RexxString *description)
void reportNostring (RexxString *description)
void reportException (wholenumber_t error)
void reportException (wholenumber_t error, RexxArray *args)
void reportException (wholenumber_t error, RexxObject *a1)
void reportException (wholenumber_t error, wholenumber_t a1)
void reportException (wholenumber_t error, wholenumber_t a1, wholenumber_t a2)
void reportException (wholenumber_t error, wholenumber_t a1, RexxObject *a2)
void reportException (wholenumber_t error, RexxObject *a1, wholenumber_t a2)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2)
void reportException (wholenumber_t error, RexxObject *a1, const char *a2)
void reportException (wholenumber_t error, const char *a1)
void reportException (wholenumber_t error, const char *a1, const char *a2)
void reportException (wholenumber_t error, const char *a1, const char *a2, wholenumber_t a3)
void reportException (wholenumber_t error, const char *a1, wholenumber_t a2)
void reportException (wholenumber_t error, const char *a1, wholenumber_t a2, RexxObject *a3)
void reportException (wholenumber_t error, RexxObject *a1, wholenumber_t a2, RexxObject *a3)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2, wholenumber_t a3)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2, wholenumber_t a3, RexxObject *a4)
void reportException (wholenumber_t error, RexxObject *a1, const char *a2, wholenumber_t a3)
void reportException (wholenumber_t error, RexxObject *a1, RexxObject *a2)
void reportException (wholenumber_t error, RexxObject *a1, RexxObject *a2, wholenumber_t a3)
void reportException (wholenumber_t error, RexxObject *a1, RexxObject *a2, const char *a3)
void reportException (wholenumber_t error, RexxObject *a1, RexxObject *a2, RexxObject *a3)
void reportException (wholenumber_t error, RexxObject *a1, RexxObject *a2, RexxObject *a3, RexxObject *a4)
void reportException (wholenumber_t error, RexxObject *a1, RexxObject *a2, RexxObject *a3, RexxObject *a4, RexxObject *a5)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2, const char *a3, RexxObject *a4)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2, RexxObject *a3)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2, RexxObject *a3, RexxObject *a4)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2, RexxObject *a3, RexxObject *a4, RexxObject *a5)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2, RexxObject *a3, const char *a4, RexxObject *a5)
void reportException (wholenumber_t error, const char *a1, RexxObject *a2, RexxObject *a3, wholenumber_t a4)
void reportNomethod (RexxErrorCodes error, RexxString *message, RexxObject *receiver)
void missingArgument (RexxString *kind, size_t argumentPosition)
void missingArgument (RexxString *kind, const char *argumentPosition)
RexxActivity * new_activity ()
RexxActivity * new_activity (RexxActivity *parent)
RexxString * lastMessageName ()
RexxMethod * lastMethod ()
Function Documentation
lastMessageName()
RexxString* lastMessageName () inline
Definition at line 316 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::getLastMessageName().
Referenced by RexxClass::defineMethod(), RexxClass::deleteMethod(), RexxClass::inherit(), and RexxClass::uninherit().
lastMethod()
RexxMethod* lastMethod () inline
Definition at line 324 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::getLastMethod().
Referenced by RexxObject::objectName(), and RexxObject::objectNameEquals().
missingArgument() [1/2]
void missingArgument (RexxString * kind, const char * argumentPosition) inline
Definition at line 306 of file ActivityManager.hpp.
References Error_Invalid_argument_noarg, and reportException().
missingArgument() [2/2]
void missingArgument (RexxString * kind, size_t argumentPosition) inline
Definition at line 299 of file ActivityManager.hpp.
References Error_Incorrect_method_noarg, and reportException().
Referenced by arrayArgument(), RexxArray::createMultidimensional(), lengthArgument(), positionArgument(), RexxArray::putRexx(), requiredArgument(), AttributeSetterCode::run(), RexxObject::run(), RexxObject::send(), RexxObject::start(), and stringArgument().
new_activity() [1/2]
RexxActivity* new_activity () inline
Definition at line 312 of file ActivityManager.hpp.
References ActivityManager::createNewActivity().
new_activity() [2/2]
RexxActivity* new_activity (RexxActivity * parent) inline
Definition at line 313 of file ActivityManager.hpp.
References ActivityManager::createNewActivity().
reportCondition()
void reportCondition (RexxString * condition, RexxString * description) inline
Definition at line 135 of file ActivityManager.hpp.
References ActivityManager::currentActivity, OREF_NULL, and RexxActivity::raiseCondition().
Referenced by RexxNumberString::addSub(), RexxNumberString::comp(), RexxNumberString::prepareOperatorNumber(), reportNostring(), and reportNovalue().
reportException() [1/30]
void reportException (wholenumber_t error) inline
Definition at line 139 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
Referenced by RexxString::abs(), RexxList::add(), RexxNumberString::adjustPrecision(), APIRaiseException(), RexxArray::appendRexx(), arrayArgument(), ArrayAt(), ArrayPut(), RexxExpressionMessage::assign(), RexxStem::bracketEqual(), SystemInterpreter::buildEnvlist(), RexxActivity::buildMessage(), BUILTIN(), BaseCode::call(), RexxActivity::callExit(), RexxActivity::callFunctionExit(), RexxActivity::callObjectFunctionExit(), RexxNativeActivation::callRegisteredRoutine(), RexxActivity::callScriptingExit(), SecurityManager::callSecurityManager(), RoutineClass::callWithRexx(), RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxMutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), RexxString::ceiling(), RexxClass::checkAbstract(), RexxActivity::checkDeadLock(), checkPadArgument(), RexxActivity::checkStackSpace(), RexxContext::checkValid(), classArgument(), RexxList::classOf(), WithSortComparator::compare(), RexxObject::compareTo(), RexxString::concatBlank(), RexxString::concatRexx(), RexxInstructionDo::controlSetup(), RexxEnvelope::copyBuffer(), RexxBlock::copyRexx(), RexxContext::copyRexx(), Unicode::copyRexx(), SysActivity::create(), RexxActivity::createExceptionObject(), RexxArray::createMultidimensional(), MemorySegmentPool::createPool(), RexxString::d2c(), RexxString::d2x(), RexxNumberString::d2xD2c(), StringUtil::dataType(), RexxActivation::debugSkip(), RexxString::decodeBase64(), RexxObject::decodeMessageName(), RexxObject::defMethod(), RexxArray::deleteRexx(), RexxNumberString::divide(), RexxString::divide(), RexxNumberString::Division(), RexxClass::enhanced(), RexxArray::ensureSpace(), RexxExpressionFunction::evaluate(), RexxExpressionMessage::evaluate(), RexxInstructionDo::execute(), RexxInstructionEnd::execute(), RexxInstructionExpose::execute(), RexxInstructionForward::execute(), RexxInstructionGuard::execute(), RexxInstructionMessage::execute(), RexxInstructionNumeric::execute(), RexxInstructionOtherwise::execute(), RexxInstructionRaise::execute(), RexxInstructionReply::execute(), RexxInstructionSignal::execute(), RexxInstructionUseStrict::executeNamedArguments(), RexxInstructionUseStrict::executePositionalArguments(), RexxActivation::exitFrom(), expandArgs(), RexxActivation::externalCall(), RexxString::floor(), RexxString::format(), RexxNumberString::formatInternal(), RexxActivation::forward(), RoutineClass::fromFile(), RexxNativeActivation::getDoubleValue(), RexxList::getEntry(), PackageManager::getLibrary(), RexxActivation::getRandomSeed(), NormalSegmentSet::handleAllocationFailure(), LargeSegmentSet::handleAllocationFailure(), RexxString::hash(), RexxSupplier::index(), RexxClass::inherit(), RexxSource::initFile(), RexxSupplier::initRexx(), RexxList::insert(), RexxQueue::insert(), RexxArray::insertRexx(), ClassDirective::install(), ExtensionDirective::install(), RexxNativeActivation::int64Value(), integer(), RexxInteger::integerDivide(), RexxNumberString::integerDivide(), RexxString::integerDivide(), integerRange(), RexxTrigger::integerTrigger(), InvalidRoutine(), RexxClass::isEqual(), RexxInteger::isEqual(), RexxNumberString::isEqual(), RexxObject::isEqual(), RexxString::isEqual(), RexxActivation::iterate(), RexxActivation::leaveLoop(), lengthArgument(), RexxVariableReference::list(), RexxMethod::loadExternalMethod(), RoutineClass::loadExternalRoutine(), LibraryPackage::loadPackage(), InterpreterInstance::loadRequires(), RexxSource::loadRequires(), RexxQueue::locateEntry(), RexxClass::makeAbstract(), RexxMutableBuffer::match(), RexxString::match(), NamedArguments::match(), RexxMutableBuffer::matchChar(), RexxString::matchChar(), RexxNumberStringBase::mathRound(), RexxInteger::Max(), RexxString::Max(), RexxNumberString::maxMin(), Interpreter::messageNumber(), RexxClass::method(), RexxInteger::Min(), RexxString::Min(), RexxNumberString::minus(), RexxString::minus(), missingArgument(), RexxNumberString::multiply(), RexxString::multiply(), nameCollision(), RexxMethod::newMethodObject(), RexxMessage::newRexx(), RexxMethod::newRexx(), RoutineClass::newRexx(), Unicode::newRexx(), RexxBlock::newRexx(), RexxBuffer::newRexx(), RexxContext::newRexx(), RexxPointer::newRexx(), StackFrameClass::newRexx(), RexxClass::newRexx(), RoutineClass::newRoutineObject(), RexxSupplier::next(), RexxList::next(), RexxQueue::next(), RexxMessage::notify(), RexxQueue::ofRexx(), MemorySegmentPool::operator new(), RexxArray::operator new(), optionalBigIntegerArg(), optionalIntegerArg(), RexxSource::optionsDirective(), padArgument(), RexxNumberString::plus(), RexxString::plus(), RexxNativeActivation::pointerString(), RexxSource::position(), positionArgument(), RexxNumberString::power(), RexxString::power(), RexxList::previous(), RexxQueue::previous(), RexxActivation::procedureExpose(), RexxNativeActivation::processArguments(), RexxActivation::processClauseBoundary(), RexxList::put(), RexxQueue::put(), RexxArray::putApi(), RexxActivation::raise(), raiseError(), RaiseException0(), RaiseException1(), RaiseException2(), RaiseException3(), RaiseException4(), RaiseException5(), RexxActivation::random(), ProgramMetaData::read(), RexxInteger::remainder(), RexxNumberString::remainder(), RexxString::remainder(), RexxActivation::reply(), reportNomethod(), RexxNativeActivation::reportSignatureError(), RexxNativeActivation::reportStemError(), RexxObject::requestString(), requiredBigIntegerArg(), RexxObject::requiredInteger(), requiredIntegerArg(), RexxObject::requiredNonNegative(), RexxObject::requiredNumber(), RexxObject::requiredPositive(), RexxObject::requiredString(), requiredStringArg(), requiredTextArg(), LibraryPackage::resolveMethodEntry(), PackageManager::resolveMethodEntry(), LibraryPackage::resolveRegisteredRoutineEntry(), PackageManager::resolveRegisteredRoutineEntry(), LibraryPackage::resolveRoutineEntry(), PackageManager::resolveRoutineEntry(), RoutineClass::restore(), SystemInterpreter::restoreEnvironment(), RexxActivation::returnFrom(), RexxInstructionUseStrict::RexxInstructionUseStrict(), RexxString::round(), RexxStartDispatcher::run(), CallProgramDispatcher::run(), TranslateDispatcher::run(), TranslateInstoreDispatcher::run(), BaseCode::run(), CPPCode::run(), AttributeGetterCode::run(), AttributeSetterCode::run(), ConstantGetterCode::run(), AbstractCode::run(), RexxObject::run(), RoutineClass::save(), RexxList::section(), RexxQueue::section(), RexxArray::sectionRexx(), RexxMessage::send(), RexxObject::sendWith(), RexxContext::setArgs(), RexxObject::setMethod(), RexxActivation::setTrace(), RexxString::sign(), RexxActivation::signalValue(), RexxNativeActivation::signedIntegerValue(), RexxArray::stableSortRexx(), RexxArray::stableSortWithRexx(), RexxMessage::start(), RexxObject::startWith(), stringArgument(), RexxNumberString::stringValue(), RexxString::strip(), RexxClass::subclass(), RexxMemory::temporaryObject(), RexxArray::toString(), RexxInstructionSignal::trap(), RexxString::trunc(), RexxInteger::truthValue(), RexxNumberString::truthValue(), RexxInternalObject::truthValue(), RexxString::truthValue(), RexxClass::uninherit(), RexxDirectory::unknown(), RexxStem::unknown(), RexxNativeActivation::unsignedInt64Value(), RexxNativeActivation::unsignedIntegerValue(), SystemInterpreter::validateAddressName(), RexxArray::validateIndex(), StringUtil::validateSet(), RexxActivity::validateThread(), RexxSupplier::value(), StringUtil::verify(), and RexxString::x2dC2d().
reportException() [2/30]
void reportException (wholenumber_t error, const char * a1) inline
Definition at line 184 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [3/30]
void reportException (wholenumber_t error, const char * a1, const char * a2) inline
Definition at line 189 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [4/30]
void reportException (wholenumber_t error, const char * a1, const char * a2, wholenumber_t a3) inline
Definition at line 194 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [5/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2) inline
Definition at line 174 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [6/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2, const char * a3, RexxObject * a4) inline
Definition at line 259 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [7/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2, RexxObject * a3) inline
Definition at line 264 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [8/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2, RexxObject * a3, const char * a4, RexxObject * a5) inline
Definition at line 279 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [9/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2, RexxObject * a3, RexxObject * a4) inline
Definition at line 269 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [10/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2, RexxObject * a3, RexxObject * a4, RexxObject * a5) inline
Definition at line 274 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [11/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2, RexxObject * a3, wholenumber_t a4) inline
Definition at line 284 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [12/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2, wholenumber_t a3) inline
Definition at line 214 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [13/30]
void reportException (wholenumber_t error, const char * a1, RexxObject * a2, wholenumber_t a3, RexxObject * a4) inline
Definition at line 219 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [14/30]
void reportException (wholenumber_t error, const char * a1, wholenumber_t a2) inline
Definition at line 199 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [15/30]
void reportException (wholenumber_t error, const char * a1, wholenumber_t a2, RexxObject * a3) inline
Definition at line 204 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [16/30]
void reportException (wholenumber_t error, RexxArray * args) inline
Definition at line 144 of file ActivityManager.hpp.
References ActivityManager::currentActivity, OREF_NULL, and RexxActivity::raiseException().
reportException() [17/30]
void reportException (wholenumber_t error, RexxObject * a1) inline
Definition at line 149 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [18/30]
void reportException (wholenumber_t error, RexxObject * a1, const char * a2) inline
Definition at line 179 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [19/30]
void reportException (wholenumber_t error, RexxObject * a1, const char * a2, wholenumber_t a3) inline
Definition at line 224 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [20/30]
void reportException (wholenumber_t error, RexxObject * a1, RexxObject * a2) inline
Definition at line 229 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [21/30]
void reportException (wholenumber_t error, RexxObject * a1, RexxObject * a2, const char * a3) inline
Definition at line 239 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [22/30]
void reportException (wholenumber_t error, RexxObject * a1, RexxObject * a2, RexxObject * a3) inline
Definition at line 244 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [23/30]
void reportException (wholenumber_t error, RexxObject * a1, RexxObject * a2, RexxObject * a3, RexxObject * a4) inline
Definition at line 249 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [24/30]
void reportException (wholenumber_t error, RexxObject * a1, RexxObject * a2, RexxObject * a3, RexxObject * a4, RexxObject * a5) inline
Definition at line 254 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [25/30]
void reportException (wholenumber_t error, RexxObject * a1, RexxObject * a2, wholenumber_t a3) inline
Definition at line 234 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [26/30]
void reportException (wholenumber_t error, RexxObject * a1, wholenumber_t a2) inline
Definition at line 169 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [27/30]
void reportException (wholenumber_t error, RexxObject * a1, wholenumber_t a2, RexxObject * a3) inline
Definition at line 209 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [28/30]
void reportException (wholenumber_t error, wholenumber_t a1) inline
Definition at line 154 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [29/30]
void reportException (wholenumber_t error, wholenumber_t a1, RexxObject * a2) inline
Definition at line 164 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportException() [30/30]
void reportException (wholenumber_t error, wholenumber_t a1, wholenumber_t a2) inline
Definition at line 159 of file ActivityManager.hpp.
References ActivityManager::currentActivity, and RexxActivity::reportAnException().
reportNomethod()
void reportNomethod (RexxErrorCodes error, RexxString * message, RexxObject * receiver) inline
Definition at line 289 of file ActivityManager.hpp.
References ActivityManager::currentActivity, OREF_NULL, and reportException().
Referenced by RexxClass::defineMethod(), RexxClass::deleteMethod(), RexxClass::inherit(), RexxObject::processUnknown(), and RexxClass::uninherit().
reportNostring()
void reportNostring (RexxString * description) inline
Definition at line 137 of file ActivityManager.hpp.
References reportCondition().
reportNovalue()
void reportNovalue (RexxString * description) inline
Definition at line 136 of file ActivityManager.hpp.
References reportCondition().
Referenced by RexxActivation::handleNovalueEvent().