executor.master: ArgumentParser.h File Reference
ArgumentParser.h File Reference
Functions
const char * nextArgument (BOOL getprog, const char *argptr, PULONG ndx, PULONG len, BOOL allocate)
PCONSTRXSTRING getArguments (const char **program, const char *argptr, size_t *count, PCONSTRXSTRING retarr)
void freeArguments (const char *program, PCONSTRXSTRING arguments)
PCHAR * CommandLineToArgvA (PCHAR CmdLine, int32_t *_argc)
Function Documentation
CommandLineToArgvA()
PCHAR* CommandLineToArgvA (PCHAR CmdLine, int32_t * _argc)
Definition at line 179 of file ArgumentParser.h.
Referenced by WinMain().
freeArguments()
void freeArguments (const char * program, PCONSTRXSTRING arguments)
Definition at line 169 of file ArgumentParser.h.
Referenced by main().
getArguments()
PCONSTRXSTRING getArguments (const char ** program, const char * argptr, size_t * count, PCONSTRXSTRING retarr)
Definition at line 129 of file ArgumentParser.h.
References nextArgument().
Referenced by main(), and WinMain().
nextArgument()
const char* nextArgument (BOOL getprog, const char * argptr, PULONG ndx, PULONG len, BOOL allocate)
Definition at line 39 of file ArgumentParser.h.
Referenced by getArguments().