executor.master: ArrayClass.hpp File Reference
ArrayClass.hpp File Reference
Classes
struct copyElementParm
class PartitionBounds
class BaseSortComparator
class WithSortComparator
class RexxArray
Macros
#define RaiseBoundsNone 0x00000000
#define RaiseBoundsUpper 0x00000001
#define RaiseBoundsInvalid 0x00000002
#define RaiseBoundsTooMany 0x00000004
#define RaiseBoundsAll 0x0000000F
#define ExtendUpper 0x00000010
Typedefs
typedef struct copyElementParm COPYELEMENTPARM
Functions
RexxArray * new_externalArray (size_t s, RexxClass *c)
RexxArray * new_array (size_t s)
RexxArray * new_array ()
RexxArray * new_array (size_t s, RexxObject **o)
RexxArray * new_array (RexxObject *o1)
RexxArray * new_array (RexxObject *o1, RexxObject *o2)
RexxArray * new_array (RexxObject *o1, RexxObject *o2, RexxObject *o3)
RexxArray * new_array (RexxObject *o1, RexxObject *o2, RexxObject *o3, RexxObject *o4)
RexxArray * new_array (RexxObject *o1, RexxObject *o2, RexxObject *o3, RexxObject *o4, RexxObject *o5)
Macro Definition Documentation
ExtendUpper
#define ExtendUpper 0x00000010
Definition at line 52 of file ArrayClass.hpp.
RaiseBoundsAll
#define RaiseBoundsAll 0x0000000F
Definition at line 51 of file ArrayClass.hpp.
RaiseBoundsInvalid
#define RaiseBoundsInvalid 0x00000002
Definition at line 49 of file ArrayClass.hpp.
RaiseBoundsNone
#define RaiseBoundsNone 0x00000000
Definition at line 47 of file ArrayClass.hpp.
RaiseBoundsTooMany
#define RaiseBoundsTooMany 0x00000004
Definition at line 50 of file ArrayClass.hpp.
RaiseBoundsUpper
#define RaiseBoundsUpper 0x00000001
Definition at line 48 of file ArrayClass.hpp.
Typedef Documentation
COPYELEMENTPARM
typedef struct copyElementParm COPYELEMENTPARM
Function Documentation
new_array() [1/8]
RexxArray* new_array () inline
Make a zero-length array item.
Returns
A new array.
Definition at line 270 of file ArrayClass.hpp.
References new_array().
new_array() [2/8]
RexxArray* new_array (RexxObject * o1) inline
Create a new array with one item.
Parameters
o1 The object to add to the array.
Returns
A new array object.
Definition at line 297 of file ArrayClass.hpp.
new_array() [3/8]
RexxArray* new_array (RexxObject * o1, RexxObject * o2) inline
Create a new array with two items.
Parameters
o1 The first object to add to the array.
o2 The second object to add
Returns
A new array object.
Definition at line 311 of file ArrayClass.hpp.
new_array() [4/8]
RexxArray* new_array (RexxObject * o1, RexxObject * o2, RexxObject * o3) inline
Create a new array with three items.
Parameters
o1 The first object to add to the array.
o2 The second object to add
o3 The third object to add.
Returns
A new array object.
Definition at line 326 of file ArrayClass.hpp.
new_array() [5/8]
RexxArray* new_array (RexxObject * o1, RexxObject * o2, RexxObject * o3, RexxObject * o4) inline
Create a new array with four items.
Parameters
o1 The first object to add to the array.
o2 The second object to add
o3 The third object to add.
o4 The fourth object to add.
Returns
A new array object.
Definition at line 342 of file ArrayClass.hpp.
new_array() [6/8]
RexxArray* new_array (RexxObject * o1, RexxObject * o2, RexxObject * o3, RexxObject * o4, RexxObject * o5) inline
Create a new array with five items.
Parameters
o1 The first object to add to the array.
o2 The second object to add
o3 The third object to add.
o4 The fourth object to add.
o5 The fifth object to add.
Returns
A new array object.
Definition at line 359 of file ArrayClass.hpp.
new_array() [7/8]
RexxArray* new_array (size_t s) inline
Create an array with a given size.
Parameters
s The size of the array.
Returns
The new array item.
Definition at line 259 of file ArrayClass.hpp.
References RexxArray::ARRAY_MIN_SIZE, and TheArrayClass.
Referenced by RexxHashTable::allIndex(), RexxDirectory::allIndexes(), RexxList::allIndexes(), RexxQueue::allIndexes(), RexxHashTable::allIndexes(), RexxArray::allIndexes(), RexxDirectory::allIndexesItems(), RexxDirectory::allItems(), RexxList::allItems(), RexxStem::allItems(), RexxHashTable::allItems(), RexxArray::allItems(), RexxSource::argArray(), ArrayOfFive(), ArrayOfFour(), ArrayOfOne(), ArrayOfThree(), ArrayOfTwo(), RexxActivity::createExceptionObject(), RexxArray::createInstance(), RexxArray::createMultidimensional(), InternalActivationFrame::createStackFrame(), RexxNativeActivation::createStackFrame(), RexxSource::error(), RexxSource::errorLine(), RexxSource::errorPosition(), RexxSource::errorToken(), RexxExpressionList::evaluate(), RexxInstructionForward::execute(), RexxInstructionRaise::execute(), RexxArray::extend(), RexxArray::extendMulti(), RexxSource::extractSource(), RexxActivation::formatSourcelessTraceLine(), RexxActivity::generateStackFrames(), RexxHashTable::getAll(), StackFrameClass::getArguments(), RexxActivation::getArguments(), RexxArray::getDimensions(), PackageManager::getImageData(), PackageClass::getImportedPackages(), RexxBehaviour::getMethods(), RexxCode::getSource(), RexxArray::indexToArray(), RexxNativeActivation::int64Value(), RexxSource::interpret(), RexxArray::join(), StringUtil::makearray(), RexxList::makeArrayIndices(), RexxInstructionSelect::matchEnd(), RexxInstructionDo::matchLabel(), new_array(), NewArray(), RexxMethod::newMethodObject(), RexxMemory::newObjects(), RexxClass::newRexx(), RoutineClass::newRoutineObject(), RexxArray::of(), RexxArray::operator new(), RexxHashTable::primitiveGetAll(), RexxSource::processInstall(), RexxObject::processUnknown(), RexxHashTable::removeAll(), RexxActivity::reportAnException(), RexxStartDispatcher::run(), RexxObject::run(), RexxMemory::saveImage(), RexxMemory::saveStrings(), RexxArray::section(), RexxArray::sectionRexx(), RexxObject::sendMessage(), RexxClass::setMetaClass(), RexxNativeActivation::signedIntegerValue(), RexxStem::sort(), RexxArray::stableSortRexx(), RexxArray::stableSortWithRexx(), RexxHashTable::stringGetAll(), RexxClass::subclass(), RexxClass::subClassable(), StringUtil::subWords(), RexxStem::supplier(), RexxHashTable::supplier(), RexxRelation::supplier(), RexxArray::supplier(), RexxStem::tailArray(), RexxSource::traceBack(), RexxActivation::traceEntry(), RexxActivation::trapOn(), RexxNativeActivation::unsignedInt64Value(), RexxNativeActivation::unsignedIntegerValue(), RexxNativeActivation::valuesToObject(), RexxList::weakReferenceArray(), StringUtil::words(), and RexxSource::words().
new_array() [8/8]
RexxArray* new_array (size_t s, RexxObject ** o) inline
Create an array populated with objects from another source.
Parameters
s The number of objects.
o The pointer to the set of objects.
Returns
A new array object.
Definition at line 284 of file ArrayClass.hpp.
new_externalArray()
RexxArray* new_externalArray (size_t s, RexxClass * c) inline
Definition at line 247 of file ArrayClass.hpp.
References RexxArray::ARRAY_DEFAULT_SIZE.
Referenced by RexxArray::createMultidimensional(), and RexxArray::operator new().