executor.master: BuiltinFunctions.cpp File Reference
BuiltinFunctions.cpp File Reference
#include <stdlib.h>
#include <ctype.h>
#include "RexxCore.h"
#include "StringClass.hpp"
#include "DirectoryClass.hpp"
#include "ArrayClass.hpp"
#include "RexxVariableDictionary.hpp"
#include "RexxActivation.hpp"
#include "RexxActivity.hpp"
#include "ExpressionBaseVariable.hpp"
#include "SourceFile.hpp"
#include "BuiltinFunctions.hpp"
#include "RexxDateTime.hpp"
#include "Numerics.hpp"
#include "ProtectedObject.hpp"
#include "PackageManager.hpp"
#include "SystemInterpreter.hpp"
#include "SysFileSystem.hpp"
#include "TextClass.hpp"
Macros
#define TEXT_BIF_TARGET1(x, n)
#define TEXT_BIF_TARGET2(x, n1, n2)
#define CENTER_MIN 2
#define CENTER_MAX 3
#define CENTER_string 1
#define CENTER_length 2
#define CENTER_pad 3
#define CENTRE_MIN 2
#define CENTRE_MAX 3
#define CENTRE_string 1
#define CENTRE_length 2
#define CENTRE_pad 3
#define DELSTR_MIN 2
#define DELSTR_MAX 3
#define DELSTR_string 1
#define DELSTR_n 2
#define DELSTR_length 3
#define DELWORD_MIN 2
#define DELWORD_MAX 3
#define DELWORD_string 1
#define DELWORD_n 2
#define DELWORD_length 3
#define INSERT_MIN 2
#define INSERT_MAX 5
#define INSERT_new 1
#define INSERT_target 2
#define INSERT_n 3
#define INSERT_length 4
#define INSERT_pad 5
#define LEFT_MIN 2
#define LEFT_MAX 3
#define LEFT_string 1
#define LEFT_length 2
#define LEFT_pad 3
#define OVERLAY_MIN 2
#define OVERLAY_MAX 5
#define OVERLAY_new 1
#define OVERLAY_target 2
#define OVERLAY_n 3
#define OVERLAY_length 4
#define OVERLAY_pad 5
#define POS_MIN 2
#define POS_MAX 4
#define POS_needle 1
#define POS_haystack 2
#define POS_start 3
#define POS_range 4
#define LASTPOS_MIN 2
#define LASTPOS_MAX 4
#define LASTPOS_needle 1
#define LASTPOS_haystack 2
#define LASTPOS_start 3
#define LASTPOS_range 4
#define REVERSE_MIN 1
#define REVERSE_MAX 1
#define REVERSE_string 1
#define RIGHT_MIN 2
#define RIGHT_MAX 3
#define RIGHT_string 1
#define RIGHT_length 2
#define RIGHT_pad 3
#define STRIP_MIN 1
#define STRIP_MAX 3
#define STRIP_string 1
#define STRIP_option 2
#define STRIP_char 3
#define SPACE_MIN 1
#define SPACE_MAX 3
#define SPACE_string 1
#define SPACE_n 2
#define SPACE_pad 3
#define SUBSTR_MIN 2
#define SUBSTR_MAX 4
#define SUBSTR_string 1
#define SUBSTR_n 2
#define SUBSTR_length 3
#define SUBSTR_pad 4
#define LOWER_MIN 1
#define LOWER_MAX 3
#define LOWER_string 1
#define LOWER_n 2
#define LOWER_length 3
#define UPPER_MIN 1
#define UPPER_MAX 3
#define UPPER_string 1
#define UPPER_n 2
#define UPPER_length 3
#define SUBWORD_MIN 2
#define SUBWORD_MAX 3
#define SUBWORD_string 1
#define SUBWORD_n 2
#define SUBWORD_length 3
#define WORD_MIN 2
#define WORD_MAX 2
#define WORD_string 1
#define WORD_n 2
#define WORDINDEX_MIN 2
#define WORDINDEX_MAX 2
#define WORDINDEX_string 1
#define WORDINDEX_n 2
#define WORDLENGTH_MIN 2
#define WORDLENGTH_MAX 2
#define WORDLENGTH_string 1
#define WORDLENGTH_n 2
#define COPIES_MIN 2
#define COPIES_MAX 2
#define COPIES_string 1
#define COPIES_n 2
#define WORDPOS_MIN 2
#define WORDPOS_MAX 3
#define WORDPOS_phrase 1
#define WORDPOS_string 2
#define WORDPOS_start 3
#define WORDS_MIN 1
#define WORDS_MAX 1
#define WORDS_string 1
#define ABBREV_MIN 2
#define ABBREV_MAX 3
#define ABBREV_information 1
#define ABBREV_info 2
#define ABBREV_length 3
#define BITAND_MIN 1
#define BITAND_MAX 3
#define BITAND_string1 1
#define BITAND_string2 2
#define BITAND_pad 3
#define BITOR_MIN 1
#define BITOR_MAX 3
#define BITOR_string1 1
#define BITOR_string2 2
#define BITOR_pad 3
#define BITXOR_MIN 1
#define BITXOR_MAX 3
#define BITXOR_string1 1
#define BITXOR_string2 2
#define BITXOR_pad 3
#define B2X_MIN 1
#define B2X_MAX 1
#define B2X_string 1
#define X2B_MIN 1
#define X2B_MAX 1
#define X2B_string 1
#define C2X_MIN 1
#define C2X_MAX 1
#define C2X_string 1
#define X2C_MIN 1
#define X2C_MAX 1
#define X2C_string 1
#define C2D_MIN 1
#define C2D_MAX 2
#define C2D_string 1
#define C2D_n 2
#define TRUNC_MIN 1
#define TRUNC_MAX 2
#define TRUNC_number 1
#define TRUNC_n 2
#define X2D_MIN 1
#define X2D_MAX 2
#define X2D_string 1
#define X2D_n 2
#define D2X_MIN 1
#define D2X_MAX 2
#define D2X_string 1
#define D2X_n 2
#define D2C_MIN 1
#define D2C_MAX 2
#define D2C_string 1
#define D2C_n 2
#define COMPARE_MIN 2
#define COMPARE_MAX 3
#define COMPARE_string1 1
#define COMPARE_string2 2
#define COMPARE_pad 3
#define LENGTH_MIN 1
#define LENGTH_MAX 1
#define LENGTH_string 1
#define TRANSLATE_MIN 1
#define TRANSLATE_MAX 6
#define TRANSLATE_string 1
#define TRANSLATE_tableo 2
#define TRANSLATE_tablei 3
#define TRANSLATE_pad 4
#define TRANSLATE_start 5
#define TRANSLATE_range 6
#define VERIFY_MIN 2
#define VERIFY_MAX 5
#define VERIFY_string 1
#define VERIFY_reference 2
#define VERIFY_option 3
#define VERIFY_start 4
#define VERIFY_range 5
#define DATATYPE_MIN 1
#define DATATYPE_MAX 2
#define DATATYPE_string 1
#define DATATYPE_type 2
#define ADDRESS_MIN 0
#define ADDRESS_MAX 0
#define DIGITS_MIN 0
#define DIGITS_MAX 0
#define FUZZ_MIN 0
#define FUZZ_MAX 0
#define FORM_MIN 0
#define FORM_MAX 0
#define USERID_MIN 0
#define USERID_MAX 0
#define ERRORTEXT_MIN 1
#define ERRORTEXT_MAX 1
#define ERRORTEXT_n 1
#define ARG_MIN 0
#define ARG_MAX 2
#define ARG_n 1
#define ARG_option 2
#define DATE_MIN 0
#define DATE_MAX 5
#define DATE_option 1
#define DATE_indate 2
#define DATE_option2 3
#define DATE_osep 4
#define DATE_isep 5
#define TIME_MIN 0
#define TIME_MAX 3
#define TIME_option 1
#define TIME_intime 2
#define TIME_option2 3
#define RANDOM_MIN 0
#define RANDOM_MAX 3
#define RANDOM_minimum 1
#define RANDOM_maximum 2
#define RANDOM_seed 3
#define XRANGE_MIN 0
#define XRANGE_MAX 2
#define XRANGE_start 1
#define XRANGE_end 2
#define SYMBOL_MIN 1
#define SYMBOL_MAX 1
#define SYMBOL_name 1
#define VAR_MIN 1
#define VAR_MAX 1
#define VAR_name 1
#define VALUE_MIN 1
#define VALUE_MAX 3
#define VALUE_name 1
#define VALUE_newValue 2
#define VALUE_selector 3
#define ABS_MIN 1
#define ABS_MAX 1
#define ABS_n 1
#define SIGN_MIN 1
#define SIGN_MAX 1
#define SIGN_n 1
#define FORMAT_MIN 1
#define FORMAT_MAX 5
#define FORMAT_number 1
#define FORMAT_before 2
#define FORMAT_after 3
#define FORMAT_expp 4
#define FORMAT_expt 5
#define ORXMAX_MIN 1
#define ORXMAX_MAX argcount
#define ORXMAX_target 1
#define ORXMIN_MIN 1
#define ORXMIN_MAX argcount
#define ORXMIN_target 1
#define SOURCELINE_MIN 0
#define SOURCELINE_MAX 1
#define SOURCELINE_n 1
#define TRACE_MIN 0
#define TRACE_MAX 1
#define TRACE_setting 1
#define LINEIN_MIN 0
#define LINEIN_MAX 3
#define LINEIN_name 1
#define LINEIN_line 2
#define LINEIN_count 3
#define CHARIN_MIN 0
#define CHARIN_MAX 3
#define CHARIN_name 1
#define CHARIN_start 2
#define CHARIN_count 3
#define LINEOUT_MIN 0
#define LINEOUT_MAX 3
#define LINEOUT_name 1
#define LINEOUT_string 2
#define LINEOUT_line 3
#define CHAROUT_MIN 0
#define CHAROUT_MAX 3
#define CHAROUT_name 1
#define CHAROUT_string 2
#define CHAROUT_start 3
#define LINES_MIN 0
#define LINES_MAX 2
#define LINES_name 1
#define LINES_option 2
#define CHARS_MIN 0
#define CHARS_MAX 1
#define CHARS_name 1
#define STREAM_MIN 1
#define STREAM_MAX 3
#define STREAM_name 1
#define STREAM_operation 2
#define STREAM_command 3
#define STREAM_STATUS 'S'
#define STREAM_DESCRIPTION 'D'
#define STREAM_COMMAND 'C'
#define QUEUED_MIN 0
#define QUEUED_MAX 0
#define CONDITION_MIN 0
#define CONDITION_MAX 1
#define CONDITION_option 1
#define CHANGESTR_MIN 3
#define CHANGESTR_MAX 4
#define CHANGESTR_needle 1
#define CHANGESTR_haystack 2
#define CHANGESTR_newneedle 3
#define CHANGESTR_count 4
#define COUNTSTR_MIN 2
#define COUNTSTR_MAX 2
#define COUNTSTR_needle 1
#define COUNTSTR_haystack 2
#define RXFUNCADD_MIN 2
#define RXFUNCADD_MAX 3
#define RXFUNCADD_name 1
#define RXFUNCADD_module 2
#define RXFUNCADD_proc 3
#define RXFUNCDROP_MIN 1
#define RXFUNCDROP_MAX 1
#define RXFUNCDROP_name 1
#define RXFUNCQUERY_MIN 1
#define RXFUNCQUERY_MAX 1
#define RXFUNCQUERY_name 1
#define QUEUEEXIT_MIN 1
#define QUEUEEXIT_MAX 1
#define QUEUEEXIT_name 1
#define SETLOCAL_MIN 0
#define SETLOCAL_MAX 0
#define ENDLOCAL_MIN 0
#define ENDLOCAL_MAX 0
#define QUALIFY_MIN 0
#define QUALIFY_MAX 1
#define QUALIFY_name 1
Functions
void expandArgs (RexxObject **arguments, size_t argcount, size_t min, size_t max, const char *function)
RexxString * requiredStringArg (size_t position, RexxObject **arguments, size_t argcount, const char *function)
RexxString * optionalStringArg (size_t position, RexxObject **arguments, size_t argcount, const char *function)
RexxText * requiredTextArg (size_t position, RexxObject **arguments, size_t argcount, const char *function)
RexxInteger * requiredIntegerArg (size_t position, RexxObject **arguments, size_t argcount, const char *function)
RexxInteger * optionalIntegerArg (size_t position, RexxObject **arguments, size_t argcount, const char *function)
RexxObject * requiredBigIntegerArg (size_t position, RexxObject **arguments, size_t argcount, const char *function)
RexxObject * optionalBigIntegerArg (size_t position, RexxObject **arguments, size_t argcount, const char *function)
void checkPadArgument (const char *pFuncName, RexxObject *position, RexxString *pad)
BUILTIN (CENTER)
BUILTIN (CENTRE)
BUILTIN (DELSTR)
BUILTIN (DELWORD)
BUILTIN (INSERT)
BUILTIN (LEFT)
BUILTIN (OVERLAY)
BUILTIN (POS)
BUILTIN (LASTPOS)
BUILTIN (REVERSE)
BUILTIN (RIGHT)
BUILTIN (STRIP)
BUILTIN (SPACE)
BUILTIN (SUBSTR)
BUILTIN (LOWER)
BUILTIN (UPPER)
BUILTIN (SUBWORD)
BUILTIN (WORD)
BUILTIN (WORDINDEX)
BUILTIN (WORDLENGTH)
BUILTIN (COPIES)
BUILTIN (WORDPOS)
BUILTIN (WORDS)
BUILTIN (ABBREV)
BUILTIN (BITAND)
BUILTIN (BITOR)
BUILTIN (BITXOR)
BUILTIN (B2X)
BUILTIN (X2B)
BUILTIN (C2X)
BUILTIN (X2C)
BUILTIN (C2D)
BUILTIN (TRUNC)
BUILTIN (X2D)
BUILTIN (D2X)
BUILTIN (D2C)
BUILTIN (COMPARE)
BUILTIN (LENGTH)
BUILTIN (TRANSLATE)
BUILTIN (VERIFY)
BUILTIN (DATATYPE)
BUILTIN (ADDRESS)
BUILTIN (DIGITS)
BUILTIN (FUZZ)
BUILTIN (FORM)
BUILTIN (USERID)
BUILTIN (ERRORTEXT)
BUILTIN (ARG)
BUILTIN (DATE)
BUILTIN (TIME)
BUILTIN (RANDOM)
BUILTIN (XRANGE)
BUILTIN (SYMBOL)
BUILTIN (VAR)
BUILTIN (VALUE)
BUILTIN (ABS)
BUILTIN (SIGN)
BUILTIN (FORMAT)
BUILTIN (ORXMAX)
BUILTIN (ORXMIN)
BUILTIN (SOURCELINE)
BUILTIN (TRACE)
bool check_queue (RexxString *name)
BUILTIN (LINEIN)
BUILTIN (CHARIN)
BUILTIN (LINEOUT)
BUILTIN (CHAROUT)
BUILTIN (LINES)
BUILTIN (CHARS)
BUILTIN (STREAM)
BUILTIN (QUEUED)
BUILTIN (CONDITION)
BUILTIN (CHANGESTR)
BUILTIN (COUNTSTR)
BUILTIN (RXFUNCADD)
BUILTIN (RXFUNCDROP)
BUILTIN (RXFUNCQUERY)
BUILTIN (QUEUEEXIT)
BUILTIN (SETLOCAL)
BUILTIN (ENDLOCAL)
BUILTIN (QUALIFY)
Macro Definition Documentation
ABBREV_info
#define ABBREV_info 2
Definition at line 845 of file BuiltinFunctions.cpp.
ABBREV_information
#define ABBREV_information 1
Definition at line 844 of file BuiltinFunctions.cpp.
ABBREV_length
#define ABBREV_length 3
Definition at line 846 of file BuiltinFunctions.cpp.
ABBREV_MAX
#define ABBREV_MAX 3
Definition at line 843 of file BuiltinFunctions.cpp.
ABBREV_MIN
#define ABBREV_MIN 2
Definition at line 842 of file BuiltinFunctions.cpp.
ABS_MAX
#define ABS_MAX 1
Definition at line 2077 of file BuiltinFunctions.cpp.
ABS_MIN
#define ABS_MIN 1
Definition at line 2076 of file BuiltinFunctions.cpp.
ABS_n
#define ABS_n 1
Definition at line 2078 of file BuiltinFunctions.cpp.
ADDRESS_MAX
#define ADDRESS_MAX 0
Definition at line 1155 of file BuiltinFunctions.cpp.
ADDRESS_MIN
#define ADDRESS_MIN 0
Definition at line 1154 of file BuiltinFunctions.cpp.
ARG_MAX
#define ARG_MAX 2
Definition at line 1226 of file BuiltinFunctions.cpp.
ARG_MIN
#define ARG_MIN 0
Definition at line 1224 of file BuiltinFunctions.cpp.
ARG_n
#define ARG_n 1
Definition at line 1227 of file BuiltinFunctions.cpp.
ARG_option
#define ARG_option 2
Definition at line 1228 of file BuiltinFunctions.cpp.
B2X_MAX
#define B2X_MAX 1
Definition at line 918 of file BuiltinFunctions.cpp.
B2X_MIN
#define B2X_MIN 1
Definition at line 917 of file BuiltinFunctions.cpp.
B2X_string
#define B2X_string 1
Definition at line 919 of file BuiltinFunctions.cpp.
BITAND_MAX
#define BITAND_MAX 3
Definition at line 864 of file BuiltinFunctions.cpp.
BITAND_MIN
#define BITAND_MIN 1
Definition at line 863 of file BuiltinFunctions.cpp.
BITAND_pad
#define BITAND_pad 3
Definition at line 867 of file BuiltinFunctions.cpp.
BITAND_string1
#define BITAND_string1 1
Definition at line 865 of file BuiltinFunctions.cpp.
BITAND_string2
#define BITAND_string2 2
Definition at line 866 of file BuiltinFunctions.cpp.
BITOR_MAX
#define BITOR_MAX 3
Definition at line 882 of file BuiltinFunctions.cpp.
BITOR_MIN
#define BITOR_MIN 1
Definition at line 881 of file BuiltinFunctions.cpp.
BITOR_pad
#define BITOR_pad 3
Definition at line 885 of file BuiltinFunctions.cpp.
BITOR_string1
#define BITOR_string1 1
Definition at line 883 of file BuiltinFunctions.cpp.
BITOR_string2
#define BITOR_string2 2
Definition at line 884 of file BuiltinFunctions.cpp.
BITXOR_MAX
#define BITXOR_MAX 3
Definition at line 900 of file BuiltinFunctions.cpp.
BITXOR_MIN
#define BITXOR_MIN 1
Definition at line 899 of file BuiltinFunctions.cpp.
BITXOR_pad
#define BITXOR_pad 3
Definition at line 903 of file BuiltinFunctions.cpp.
BITXOR_string1
#define BITXOR_string1 1
Definition at line 901 of file BuiltinFunctions.cpp.
BITXOR_string2
#define BITXOR_string2 2
Definition at line 902 of file BuiltinFunctions.cpp.
C2D_MAX
#define C2D_MAX 2
Definition at line 972 of file BuiltinFunctions.cpp.
C2D_MIN
#define C2D_MIN 1
Definition at line 971 of file BuiltinFunctions.cpp.
C2D_n
#define C2D_n 2
Definition at line 974 of file BuiltinFunctions.cpp.
C2D_string
#define C2D_string 1
Definition at line 973 of file BuiltinFunctions.cpp.
C2X_MAX
#define C2X_MAX 1
Definition at line 942 of file BuiltinFunctions.cpp.
C2X_MIN
#define C2X_MIN 1
Definition at line 941 of file BuiltinFunctions.cpp.
C2X_string
#define C2X_string 1
Definition at line 943 of file BuiltinFunctions.cpp.
CENTER_length
#define CENTER_length 2
Definition at line 365 of file BuiltinFunctions.cpp.
CENTER_MAX
#define CENTER_MAX 3
Definition at line 363 of file BuiltinFunctions.cpp.
CENTER_MIN
#define CENTER_MIN 2
Definition at line 362 of file BuiltinFunctions.cpp.
CENTER_pad
#define CENTER_pad 3
Definition at line 366 of file BuiltinFunctions.cpp.
CENTER_string
#define CENTER_string 1
Definition at line 364 of file BuiltinFunctions.cpp.
CENTRE_length
#define CENTRE_length 2
Definition at line 386 of file BuiltinFunctions.cpp.
CENTRE_MAX
#define CENTRE_MAX 3
Definition at line 384 of file BuiltinFunctions.cpp.
CENTRE_MIN
#define CENTRE_MIN 2
Definition at line 383 of file BuiltinFunctions.cpp.
CENTRE_pad
#define CENTRE_pad 3
Definition at line 387 of file BuiltinFunctions.cpp.
CENTRE_string
#define CENTRE_string 1
Definition at line 385 of file BuiltinFunctions.cpp.
CHANGESTR_count
#define CHANGESTR_count 4
Definition at line 2794 of file BuiltinFunctions.cpp.
CHANGESTR_haystack
#define CHANGESTR_haystack 2
Definition at line 2792 of file BuiltinFunctions.cpp.
CHANGESTR_MAX
#define CHANGESTR_MAX 4
Definition at line 2790 of file BuiltinFunctions.cpp.
CHANGESTR_MIN
#define CHANGESTR_MIN 3
Definition at line 2789 of file BuiltinFunctions.cpp.
CHANGESTR_needle
#define CHANGESTR_needle 1
Definition at line 2791 of file BuiltinFunctions.cpp.
CHANGESTR_newneedle
#define CHANGESTR_newneedle 3
Definition at line 2793 of file BuiltinFunctions.cpp.
CHARIN_count
#define CHARIN_count 3
Definition at line 2317 of file BuiltinFunctions.cpp.
CHARIN_MAX
#define CHARIN_MAX 3
Definition at line 2314 of file BuiltinFunctions.cpp.
CHARIN_MIN
#define CHARIN_MIN 0
Definition at line 2313 of file BuiltinFunctions.cpp.
CHARIN_name
#define CHARIN_name 1
Definition at line 2315 of file BuiltinFunctions.cpp.
CHARIN_start
#define CHARIN_start 2
Definition at line 2316 of file BuiltinFunctions.cpp.
CHAROUT_MAX
#define CHAROUT_MAX 3
Definition at line 2411 of file BuiltinFunctions.cpp.
CHAROUT_MIN
#define CHAROUT_MIN 0
Definition at line 2410 of file BuiltinFunctions.cpp.
CHAROUT_name
#define CHAROUT_name 1
Definition at line 2412 of file BuiltinFunctions.cpp.
CHAROUT_start
#define CHAROUT_start 3
Definition at line 2414 of file BuiltinFunctions.cpp.
CHAROUT_string
#define CHAROUT_string 2
Definition at line 2413 of file BuiltinFunctions.cpp.
CHARS_MAX
#define CHARS_MAX 1
Definition at line 2518 of file BuiltinFunctions.cpp.
CHARS_MIN
#define CHARS_MIN 0
Definition at line 2517 of file BuiltinFunctions.cpp.
CHARS_name
#define CHARS_name 1
Definition at line 2519 of file BuiltinFunctions.cpp.
COMPARE_MAX
#define COMPARE_MAX 3
Definition at line 1045 of file BuiltinFunctions.cpp.
COMPARE_MIN
#define COMPARE_MIN 2
Definition at line 1044 of file BuiltinFunctions.cpp.
COMPARE_pad
#define COMPARE_pad 3
Definition at line 1048 of file BuiltinFunctions.cpp.
COMPARE_string1
#define COMPARE_string1 1
Definition at line 1046 of file BuiltinFunctions.cpp.
COMPARE_string2
#define COMPARE_string2 2
Definition at line 1047 of file BuiltinFunctions.cpp.
CONDITION_MAX
#define CONDITION_MAX 1
Definition at line 2691 of file BuiltinFunctions.cpp.
CONDITION_MIN
#define CONDITION_MIN 0
Definition at line 2690 of file BuiltinFunctions.cpp.
CONDITION_option
#define CONDITION_option 1
Definition at line 2692 of file BuiltinFunctions.cpp.
COPIES_MAX
#define COPIES_MAX 2
Definition at line 789 of file BuiltinFunctions.cpp.
COPIES_MIN
#define COPIES_MIN 2
Definition at line 788 of file BuiltinFunctions.cpp.
COPIES_n
#define COPIES_n 2
Definition at line 791 of file BuiltinFunctions.cpp.
COPIES_string
#define COPIES_string 1
Definition at line 790 of file BuiltinFunctions.cpp.
COUNTSTR_haystack
#define COUNTSTR_haystack 2
Definition at line 2817 of file BuiltinFunctions.cpp.
COUNTSTR_MAX
#define COUNTSTR_MAX 2
Definition at line 2815 of file BuiltinFunctions.cpp.
COUNTSTR_MIN
#define COUNTSTR_MIN 2
Definition at line 2814 of file BuiltinFunctions.cpp.
COUNTSTR_needle
#define COUNTSTR_needle 1
Definition at line 2816 of file BuiltinFunctions.cpp.
D2C_MAX
#define D2C_MAX 2
Definition at line 1028 of file BuiltinFunctions.cpp.
D2C_MIN
#define D2C_MIN 1
Definition at line 1027 of file BuiltinFunctions.cpp.
D2C_n
#define D2C_n 2
Definition at line 1030 of file BuiltinFunctions.cpp.
D2C_string
#define D2C_string 1
Definition at line 1029 of file BuiltinFunctions.cpp.
D2X_MAX
#define D2X_MAX 2
Definition at line 1014 of file BuiltinFunctions.cpp.
D2X_MIN
#define D2X_MIN 1
Definition at line 1013 of file BuiltinFunctions.cpp.
D2X_n
#define D2X_n 2
Definition at line 1016 of file BuiltinFunctions.cpp.
D2X_string
#define D2X_string 1
Definition at line 1015 of file BuiltinFunctions.cpp.
DATATYPE_MAX
#define DATATYPE_MAX 2
Definition at line 1140 of file BuiltinFunctions.cpp.
DATATYPE_MIN
#define DATATYPE_MIN 1
Definition at line 1139 of file BuiltinFunctions.cpp.
DATATYPE_string
#define DATATYPE_string 1
Definition at line 1141 of file BuiltinFunctions.cpp.
DATATYPE_type
#define DATATYPE_type 2
Definition at line 1142 of file BuiltinFunctions.cpp.
DATE_indate
#define DATE_indate 2
Definition at line 1361 of file BuiltinFunctions.cpp.
DATE_isep
#define DATE_isep 5
Definition at line 1364 of file BuiltinFunctions.cpp.
DATE_MAX
#define DATE_MAX 5
Definition at line 1359 of file BuiltinFunctions.cpp.
DATE_MIN
#define DATE_MIN 0
Definition at line 1358 of file BuiltinFunctions.cpp.
DATE_option
#define DATE_option 1
Definition at line 1360 of file BuiltinFunctions.cpp.
DATE_option2
#define DATE_option2 3
Definition at line 1362 of file BuiltinFunctions.cpp.
DATE_osep
#define DATE_osep 4
Definition at line 1363 of file BuiltinFunctions.cpp.
DELSTR_length
#define DELSTR_length 3
Definition at line 408 of file BuiltinFunctions.cpp.
DELSTR_MAX
#define DELSTR_MAX 3
Definition at line 405 of file BuiltinFunctions.cpp.
DELSTR_MIN
#define DELSTR_MIN 2
Definition at line 404 of file BuiltinFunctions.cpp.
DELSTR_n
#define DELSTR_n 2
Definition at line 407 of file BuiltinFunctions.cpp.
DELSTR_string
#define DELSTR_string 1
Definition at line 406 of file BuiltinFunctions.cpp.
DELWORD_length
#define DELWORD_length 3
Definition at line 428 of file BuiltinFunctions.cpp.
DELWORD_MAX
#define DELWORD_MAX 3
Definition at line 425 of file BuiltinFunctions.cpp.
DELWORD_MIN
#define DELWORD_MIN 2
Definition at line 424 of file BuiltinFunctions.cpp.
DELWORD_n
#define DELWORD_n 2
Definition at line 427 of file BuiltinFunctions.cpp.
DELWORD_string
#define DELWORD_string 1
Definition at line 426 of file BuiltinFunctions.cpp.
DIGITS_MAX
#define DIGITS_MAX 0
Definition at line 1164 of file BuiltinFunctions.cpp.
DIGITS_MIN
#define DIGITS_MIN 0
Definition at line 1163 of file BuiltinFunctions.cpp.
ENDLOCAL_MAX
#define ENDLOCAL_MAX 0
Definition at line 2924 of file BuiltinFunctions.cpp.
ENDLOCAL_MIN
#define ENDLOCAL_MIN 0
Definition at line 2923 of file BuiltinFunctions.cpp.
ERRORTEXT_MAX
#define ERRORTEXT_MAX 1
Definition at line 1201 of file BuiltinFunctions.cpp.
ERRORTEXT_MIN
#define ERRORTEXT_MIN 1
Definition at line 1200 of file BuiltinFunctions.cpp.
ERRORTEXT_n
#define ERRORTEXT_n 1
Definition at line 1202 of file BuiltinFunctions.cpp.
FORM_MAX
#define FORM_MAX 0
Definition at line 1182 of file BuiltinFunctions.cpp.
FORM_MIN
#define FORM_MIN 0
Definition at line 1181 of file BuiltinFunctions.cpp.
FORMAT_after
#define FORMAT_after 3
Definition at line 2128 of file BuiltinFunctions.cpp.
FORMAT_before
#define FORMAT_before 2
Definition at line 2127 of file BuiltinFunctions.cpp.
FORMAT_expp
#define FORMAT_expp 4
Definition at line 2129 of file BuiltinFunctions.cpp.
FORMAT_expt
#define FORMAT_expt 5
Definition at line 2130 of file BuiltinFunctions.cpp.
FORMAT_MAX
#define FORMAT_MAX 5
Definition at line 2125 of file BuiltinFunctions.cpp.
FORMAT_MIN
#define FORMAT_MIN 1
Definition at line 2124 of file BuiltinFunctions.cpp.
FORMAT_number
#define FORMAT_number 1
Definition at line 2126 of file BuiltinFunctions.cpp.
FUZZ_MAX
#define FUZZ_MAX 0
Definition at line 1173 of file BuiltinFunctions.cpp.
FUZZ_MIN
#define FUZZ_MIN 0
Definition at line 1172 of file BuiltinFunctions.cpp.
INSERT_length
#define INSERT_length 4
Definition at line 449 of file BuiltinFunctions.cpp.
INSERT_MAX
#define INSERT_MAX 5
Definition at line 445 of file BuiltinFunctions.cpp.
INSERT_MIN
#define INSERT_MIN 2
Definition at line 444 of file BuiltinFunctions.cpp.
INSERT_n
#define INSERT_n 3
Definition at line 448 of file BuiltinFunctions.cpp.
INSERT_new
#define INSERT_new 1
Definition at line 446 of file BuiltinFunctions.cpp.
INSERT_pad
#define INSERT_pad 5
Definition at line 450 of file BuiltinFunctions.cpp.
INSERT_target
#define INSERT_target 2
Definition at line 447 of file BuiltinFunctions.cpp.
LASTPOS_haystack
#define LASTPOS_haystack 2
Definition at line 545 of file BuiltinFunctions.cpp.
LASTPOS_MAX
#define LASTPOS_MAX 4
Definition at line 543 of file BuiltinFunctions.cpp.
LASTPOS_MIN
#define LASTPOS_MIN 2
Definition at line 542 of file BuiltinFunctions.cpp.
LASTPOS_needle
#define LASTPOS_needle 1
Definition at line 544 of file BuiltinFunctions.cpp.
LASTPOS_range
#define LASTPOS_range 4
Definition at line 547 of file BuiltinFunctions.cpp.
LASTPOS_start
#define LASTPOS_start 3
Definition at line 546 of file BuiltinFunctions.cpp.
LEFT_length
#define LEFT_length 2
Definition at line 474 of file BuiltinFunctions.cpp.
LEFT_MAX
#define LEFT_MAX 3
Definition at line 472 of file BuiltinFunctions.cpp.
LEFT_MIN
#define LEFT_MIN 2
Definition at line 471 of file BuiltinFunctions.cpp.
LEFT_pad
#define LEFT_pad 3
Definition at line 475 of file BuiltinFunctions.cpp.
LEFT_string
#define LEFT_string 1
Definition at line 473 of file BuiltinFunctions.cpp.
LENGTH_MAX
#define LENGTH_MAX 1
Definition at line 1067 of file BuiltinFunctions.cpp.
LENGTH_MIN
#define LENGTH_MIN 1
Definition at line 1066 of file BuiltinFunctions.cpp.
LENGTH_string
#define LENGTH_string 1
Definition at line 1068 of file BuiltinFunctions.cpp.
LINEIN_count
#define LINEIN_count 3
Definition at line 2267 of file BuiltinFunctions.cpp.
LINEIN_line
#define LINEIN_line 2
Definition at line 2266 of file BuiltinFunctions.cpp.
LINEIN_MAX
#define LINEIN_MAX 3
Definition at line 2264 of file BuiltinFunctions.cpp.
LINEIN_MIN
#define LINEIN_MIN 0
Definition at line 2263 of file BuiltinFunctions.cpp.
LINEIN_name
#define LINEIN_name 1
Definition at line 2265 of file BuiltinFunctions.cpp.
LINEOUT_line
#define LINEOUT_line 3
Definition at line 2357 of file BuiltinFunctions.cpp.
LINEOUT_MAX
#define LINEOUT_MAX 3
Definition at line 2354 of file BuiltinFunctions.cpp.
LINEOUT_MIN
#define LINEOUT_MIN 0
Definition at line 2353 of file BuiltinFunctions.cpp.
LINEOUT_name
#define LINEOUT_name 1
Definition at line 2355 of file BuiltinFunctions.cpp.
LINEOUT_string
#define LINEOUT_string 2
Definition at line 2356 of file BuiltinFunctions.cpp.
LINES_MAX
#define LINES_MAX 2
Definition at line 2451 of file BuiltinFunctions.cpp.
LINES_MIN
#define LINES_MIN 0
Definition at line 2450 of file BuiltinFunctions.cpp.
LINES_name
#define LINES_name 1
Definition at line 2452 of file BuiltinFunctions.cpp.
LINES_option
#define LINES_option 2
Definition at line 2453 of file BuiltinFunctions.cpp.
LOWER_length
#define LOWER_length 3
Definition at line 675 of file BuiltinFunctions.cpp.
LOWER_MAX
#define LOWER_MAX 3
Definition at line 672 of file BuiltinFunctions.cpp.
LOWER_MIN
#define LOWER_MIN 1
Definition at line 671 of file BuiltinFunctions.cpp.
LOWER_n
#define LOWER_n 2
Definition at line 674 of file BuiltinFunctions.cpp.
LOWER_string
#define LOWER_string 1
Definition at line 673 of file BuiltinFunctions.cpp.
ORXMAX_MAX
#define ORXMAX_MAX argcount
Definition at line 2151 of file BuiltinFunctions.cpp.
ORXMAX_MIN
#define ORXMAX_MIN 1
Definition at line 2150 of file BuiltinFunctions.cpp.
ORXMAX_target
#define ORXMAX_target 1
Definition at line 2152 of file BuiltinFunctions.cpp.
ORXMIN_MAX
#define ORXMIN_MAX argcount
Definition at line 2174 of file BuiltinFunctions.cpp.
ORXMIN_MIN
#define ORXMIN_MIN 1
Definition at line 2173 of file BuiltinFunctions.cpp.
ORXMIN_target
#define ORXMIN_target 1
Definition at line 2175 of file BuiltinFunctions.cpp.
OVERLAY_length
#define OVERLAY_length 4
Definition at line 497 of file BuiltinFunctions.cpp.
OVERLAY_MAX
#define OVERLAY_MAX 5
Definition at line 493 of file BuiltinFunctions.cpp.
OVERLAY_MIN
#define OVERLAY_MIN 2
Definition at line 492 of file BuiltinFunctions.cpp.
OVERLAY_n
#define OVERLAY_n 3
Definition at line 496 of file BuiltinFunctions.cpp.
OVERLAY_new
#define OVERLAY_new 1
Definition at line 494 of file BuiltinFunctions.cpp.
OVERLAY_pad
#define OVERLAY_pad 5
Definition at line 498 of file BuiltinFunctions.cpp.
OVERLAY_target
#define OVERLAY_target 2
Definition at line 495 of file BuiltinFunctions.cpp.
POS_haystack
#define POS_haystack 2
Definition at line 522 of file BuiltinFunctions.cpp.
POS_MAX
#define POS_MAX 4
Definition at line 520 of file BuiltinFunctions.cpp.
POS_MIN
#define POS_MIN 2
Definition at line 519 of file BuiltinFunctions.cpp.
POS_needle
#define POS_needle 1
Definition at line 521 of file BuiltinFunctions.cpp.
POS_range
#define POS_range 4
Definition at line 524 of file BuiltinFunctions.cpp.
POS_start
#define POS_start 3
Definition at line 523 of file BuiltinFunctions.cpp.
QUALIFY_MAX
#define QUALIFY_MAX 1
Definition at line 2934 of file BuiltinFunctions.cpp.
QUALIFY_MIN
#define QUALIFY_MIN 0
Definition at line 2933 of file BuiltinFunctions.cpp.
QUALIFY_name
#define QUALIFY_name 1
Definition at line 2935 of file BuiltinFunctions.cpp.
QUEUED_MAX
#define QUEUED_MAX 0
Definition at line 2670 of file BuiltinFunctions.cpp.
QUEUED_MIN
#define QUEUED_MIN 0
Definition at line 2669 of file BuiltinFunctions.cpp.
QUEUEEXIT_MAX
#define QUEUEEXIT_MAX 1
Definition at line 2891 of file BuiltinFunctions.cpp.
QUEUEEXIT_MIN
#define QUEUEEXIT_MIN 1
Definition at line 2890 of file BuiltinFunctions.cpp.
QUEUEEXIT_name
#define QUEUEEXIT_name 1
Definition at line 2892 of file BuiltinFunctions.cpp.
RANDOM_MAX
#define RANDOM_MAX 3
Definition at line 1864 of file BuiltinFunctions.cpp.
RANDOM_maximum
#define RANDOM_maximum 2
Definition at line 1866 of file BuiltinFunctions.cpp.
RANDOM_MIN
#define RANDOM_MIN 0
Definition at line 1863 of file BuiltinFunctions.cpp.
RANDOM_minimum
#define RANDOM_minimum 1
Definition at line 1865 of file BuiltinFunctions.cpp.
RANDOM_seed
#define RANDOM_seed 3
Definition at line 1867 of file BuiltinFunctions.cpp.
REVERSE_MAX
#define REVERSE_MAX 1
Definition at line 567 of file BuiltinFunctions.cpp.
REVERSE_MIN
#define REVERSE_MIN 1
Definition at line 566 of file BuiltinFunctions.cpp.
REVERSE_string
#define REVERSE_string 1
Definition at line 568 of file BuiltinFunctions.cpp.
RIGHT_length
#define RIGHT_length 2
Definition at line 584 of file BuiltinFunctions.cpp.
RIGHT_MAX
#define RIGHT_MAX 3
Definition at line 582 of file BuiltinFunctions.cpp.
RIGHT_MIN
#define RIGHT_MIN 2
Definition at line 581 of file BuiltinFunctions.cpp.
RIGHT_pad
#define RIGHT_pad 3
Definition at line 585 of file BuiltinFunctions.cpp.
RIGHT_string
#define RIGHT_string 1
Definition at line 583 of file BuiltinFunctions.cpp.
RXFUNCADD_MAX
#define RXFUNCADD_MAX 3
Definition at line 2834 of file BuiltinFunctions.cpp.
RXFUNCADD_MIN
#define RXFUNCADD_MIN 2
Definition at line 2833 of file BuiltinFunctions.cpp.
RXFUNCADD_module
#define RXFUNCADD_module 2
Definition at line 2836 of file BuiltinFunctions.cpp.
RXFUNCADD_name
#define RXFUNCADD_name 1
Definition at line 2835 of file BuiltinFunctions.cpp.
RXFUNCADD_proc
#define RXFUNCADD_proc 3
Definition at line 2837 of file BuiltinFunctions.cpp.
RXFUNCDROP_MAX
#define RXFUNCDROP_MAX 1
Definition at line 2860 of file BuiltinFunctions.cpp.
RXFUNCDROP_MIN
#define RXFUNCDROP_MIN 1
Definition at line 2859 of file BuiltinFunctions.cpp.
RXFUNCDROP_name
#define RXFUNCDROP_name 1
Definition at line 2861 of file BuiltinFunctions.cpp.
RXFUNCQUERY_MAX
#define RXFUNCQUERY_MAX 1
Definition at line 2875 of file BuiltinFunctions.cpp.
RXFUNCQUERY_MIN
#define RXFUNCQUERY_MIN 1
Definition at line 2874 of file BuiltinFunctions.cpp.
RXFUNCQUERY_name
#define RXFUNCQUERY_name 1
Definition at line 2876 of file BuiltinFunctions.cpp.
SETLOCAL_MAX
#define SETLOCAL_MAX 0
Definition at line 2914 of file BuiltinFunctions.cpp.
SETLOCAL_MIN
#define SETLOCAL_MIN 0
Definition at line 2913 of file BuiltinFunctions.cpp.
SIGN_MAX
#define SIGN_MAX 1
Definition at line 2101 of file BuiltinFunctions.cpp.
SIGN_MIN
#define SIGN_MIN 1
Definition at line 2100 of file BuiltinFunctions.cpp.
SIGN_n
#define SIGN_n 1
Definition at line 2102 of file BuiltinFunctions.cpp.
SOURCELINE_MAX
#define SOURCELINE_MAX 1
Definition at line 2196 of file BuiltinFunctions.cpp.
SOURCELINE_MIN
#define SOURCELINE_MIN 0
Definition at line 2195 of file BuiltinFunctions.cpp.
SOURCELINE_n
#define SOURCELINE_n 1
Definition at line 2197 of file BuiltinFunctions.cpp.
SPACE_MAX
#define SPACE_MAX 3
Definition at line 625 of file BuiltinFunctions.cpp.
SPACE_MIN
#define SPACE_MIN 1
Definition at line 624 of file BuiltinFunctions.cpp.
SPACE_n
#define SPACE_n 2
Definition at line 627 of file BuiltinFunctions.cpp.
SPACE_pad
#define SPACE_pad 3
Definition at line 628 of file BuiltinFunctions.cpp.
SPACE_string
#define SPACE_string 1
Definition at line 626 of file BuiltinFunctions.cpp.
STREAM_command
#define STREAM_command 3
Definition at line 2542 of file BuiltinFunctions.cpp.
STREAM_COMMAND
#define STREAM_COMMAND 'C'
Definition at line 2546 of file BuiltinFunctions.cpp.
STREAM_DESCRIPTION
#define STREAM_DESCRIPTION 'D'
Definition at line 2545 of file BuiltinFunctions.cpp.
STREAM_MAX
#define STREAM_MAX 3
Definition at line 2539 of file BuiltinFunctions.cpp.
STREAM_MIN
#define STREAM_MIN 1
Definition at line 2537 of file BuiltinFunctions.cpp.
STREAM_name
#define STREAM_name 1
Definition at line 2540 of file BuiltinFunctions.cpp.
STREAM_operation
#define STREAM_operation 2
Definition at line 2541 of file BuiltinFunctions.cpp.
STREAM_STATUS
#define STREAM_STATUS 'S'
Definition at line 2544 of file BuiltinFunctions.cpp.
STRIP_char
#define STRIP_char 3
Definition at line 606 of file BuiltinFunctions.cpp.
STRIP_MAX
#define STRIP_MAX 3
Definition at line 603 of file BuiltinFunctions.cpp.
STRIP_MIN
#define STRIP_MIN 1
Definition at line 602 of file BuiltinFunctions.cpp.
STRIP_option
#define STRIP_option 2
Definition at line 605 of file BuiltinFunctions.cpp.
STRIP_string
#define STRIP_string 1
Definition at line 604 of file BuiltinFunctions.cpp.
SUBSTR_length
#define SUBSTR_length 3
Definition at line 649 of file BuiltinFunctions.cpp.
SUBSTR_MAX
#define SUBSTR_MAX 4
Definition at line 646 of file BuiltinFunctions.cpp.
SUBSTR_MIN
#define SUBSTR_MIN 2
Definition at line 645 of file BuiltinFunctions.cpp.
SUBSTR_n
#define SUBSTR_n 2
Definition at line 648 of file BuiltinFunctions.cpp.
SUBSTR_pad
#define SUBSTR_pad 4
Definition at line 650 of file BuiltinFunctions.cpp.
SUBSTR_string
#define SUBSTR_string 1
Definition at line 647 of file BuiltinFunctions.cpp.
SUBWORD_length
#define SUBWORD_length 3
Definition at line 721 of file BuiltinFunctions.cpp.
SUBWORD_MAX
#define SUBWORD_MAX 3
Definition at line 718 of file BuiltinFunctions.cpp.
SUBWORD_MIN
#define SUBWORD_MIN 2
Definition at line 717 of file BuiltinFunctions.cpp.
SUBWORD_n
#define SUBWORD_n 2
Definition at line 720 of file BuiltinFunctions.cpp.
SUBWORD_string
#define SUBWORD_string 1
Definition at line 719 of file BuiltinFunctions.cpp.
SYMBOL_MAX
#define SYMBOL_MAX 1
Definition at line 1939 of file BuiltinFunctions.cpp.
SYMBOL_MIN
#define SYMBOL_MIN 1
Definition at line 1938 of file BuiltinFunctions.cpp.
SYMBOL_name
#define SYMBOL_name 1
Definition at line 1940 of file BuiltinFunctions.cpp.
TEXT_BIF_TARGET1
#define TEXT_BIF_TARGET1 (x, n)
Value:
    if (hasRexxTextArguments(arguments, argcount, named_argcount)) \
    { \
        RexxText *text = required_text(x, n); \
        ProtectedObject p_text(text); \
        return text->sendMessage(OREF_##x, &arguments[1], argcount-1, named_argcount); \
    }
Definition at line 344 of file BuiltinFunctions.cpp.
TEXT_BIF_TARGET2
#define TEXT_BIF_TARGET2 (x, n1, n2)
Value:
    if (hasRexxTextArguments(arguments, argcount, named_argcount)) \
    { \
        RexxText *text = required_text(x, n1); \
        ProtectedObject p_text(text); \
        set_arg(x,n1,n2); \
        return text->sendMessage(OREF_##x, &arguments[x##_##n1 - 1], argcount-1, named_argcount); \
    }
Definition at line 352 of file BuiltinFunctions.cpp.
TIME_intime
#define TIME_intime 2
Definition at line 1642 of file BuiltinFunctions.cpp.
TIME_MAX
#define TIME_MAX 3
Definition at line 1640 of file BuiltinFunctions.cpp.
TIME_MIN
#define TIME_MIN 0
Definition at line 1639 of file BuiltinFunctions.cpp.
TIME_option
#define TIME_option 1
Definition at line 1641 of file BuiltinFunctions.cpp.
TIME_option2
#define TIME_option2 3
Definition at line 1643 of file BuiltinFunctions.cpp.
TRACE_MAX
#define TRACE_MAX 1
Definition at line 2228 of file BuiltinFunctions.cpp.
TRACE_MIN
#define TRACE_MIN 0
Definition at line 2227 of file BuiltinFunctions.cpp.
TRACE_setting
#define TRACE_setting 1
Definition at line 2229 of file BuiltinFunctions.cpp.
TRANSLATE_MAX
#define TRANSLATE_MAX 6
Definition at line 1082 of file BuiltinFunctions.cpp.
TRANSLATE_MIN
#define TRANSLATE_MIN 1
Definition at line 1081 of file BuiltinFunctions.cpp.
TRANSLATE_pad
#define TRANSLATE_pad 4
Definition at line 1086 of file BuiltinFunctions.cpp.
TRANSLATE_range
#define TRANSLATE_range 6
Definition at line 1088 of file BuiltinFunctions.cpp.
TRANSLATE_start
#define TRANSLATE_start 5
Definition at line 1087 of file BuiltinFunctions.cpp.
TRANSLATE_string
#define TRANSLATE_string 1
Definition at line 1083 of file BuiltinFunctions.cpp.
TRANSLATE_tablei
#define TRANSLATE_tablei 3
Definition at line 1085 of file BuiltinFunctions.cpp.
TRANSLATE_tableo
#define TRANSLATE_tableo 2
Definition at line 1084 of file BuiltinFunctions.cpp.
TRUNC_MAX
#define TRUNC_MAX 2
Definition at line 986 of file BuiltinFunctions.cpp.
TRUNC_MIN
#define TRUNC_MIN 1
Definition at line 985 of file BuiltinFunctions.cpp.
TRUNC_n
#define TRUNC_n 2
Definition at line 988 of file BuiltinFunctions.cpp.
TRUNC_number
#define TRUNC_number 1
Definition at line 987 of file BuiltinFunctions.cpp.
UPPER_length
#define UPPER_length 3
Definition at line 698 of file BuiltinFunctions.cpp.
UPPER_MAX
#define UPPER_MAX 3
Definition at line 695 of file BuiltinFunctions.cpp.
UPPER_MIN
#define UPPER_MIN 1
Definition at line 694 of file BuiltinFunctions.cpp.
UPPER_n
#define UPPER_n 2
Definition at line 697 of file BuiltinFunctions.cpp.
UPPER_string
#define UPPER_string 1
Definition at line 696 of file BuiltinFunctions.cpp.
USERID_MAX
#define USERID_MAX 0
Definition at line 1192 of file BuiltinFunctions.cpp.
USERID_MIN
#define USERID_MIN 0
Definition at line 1191 of file BuiltinFunctions.cpp.
VALUE_MAX
#define VALUE_MAX 3
Definition at line 2002 of file BuiltinFunctions.cpp.
VALUE_MIN
#define VALUE_MIN 1
Definition at line 2001 of file BuiltinFunctions.cpp.
VALUE_name
#define VALUE_name 1
Definition at line 2003 of file BuiltinFunctions.cpp.
VALUE_newValue
#define VALUE_newValue 2
Definition at line 2004 of file BuiltinFunctions.cpp.
VALUE_selector
#define VALUE_selector 3
Definition at line 2005 of file BuiltinFunctions.cpp.
VAR_MAX
#define VAR_MAX 1
Definition at line 1976 of file BuiltinFunctions.cpp.
VAR_MIN
#define VAR_MIN 1
Definition at line 1975 of file BuiltinFunctions.cpp.
VAR_name
#define VAR_name 1
Definition at line 1977 of file BuiltinFunctions.cpp.
VERIFY_MAX
#define VERIFY_MAX 5
Definition at line 1112 of file BuiltinFunctions.cpp.
VERIFY_MIN
#define VERIFY_MIN 2
Definition at line 1111 of file BuiltinFunctions.cpp.
VERIFY_option
#define VERIFY_option 3
Definition at line 1115 of file BuiltinFunctions.cpp.
VERIFY_range
#define VERIFY_range 5
Definition at line 1117 of file BuiltinFunctions.cpp.
VERIFY_reference
#define VERIFY_reference 2
Definition at line 1114 of file BuiltinFunctions.cpp.
VERIFY_start
#define VERIFY_start 4
Definition at line 1116 of file BuiltinFunctions.cpp.
VERIFY_string
#define VERIFY_string 1
Definition at line 1113 of file BuiltinFunctions.cpp.
WORD_MAX
#define WORD_MAX 2
Definition at line 738 of file BuiltinFunctions.cpp.
WORD_MIN
#define WORD_MIN 2
Definition at line 737 of file BuiltinFunctions.cpp.
WORD_n
#define WORD_n 2
Definition at line 740 of file BuiltinFunctions.cpp.
WORD_string
#define WORD_string 1
Definition at line 739 of file BuiltinFunctions.cpp.
WORDINDEX_MAX
#define WORDINDEX_MAX 2
Definition at line 755 of file BuiltinFunctions.cpp.
WORDINDEX_MIN
#define WORDINDEX_MIN 2
Definition at line 754 of file BuiltinFunctions.cpp.
WORDINDEX_n
#define WORDINDEX_n 2
Definition at line 757 of file BuiltinFunctions.cpp.
WORDINDEX_string
#define WORDINDEX_string 1
Definition at line 756 of file BuiltinFunctions.cpp.
WORDLENGTH_MAX
#define WORDLENGTH_MAX 2
Definition at line 772 of file BuiltinFunctions.cpp.
WORDLENGTH_MIN
#define WORDLENGTH_MIN 2
Definition at line 771 of file BuiltinFunctions.cpp.
WORDLENGTH_n
#define WORDLENGTH_n 2
Definition at line 774 of file BuiltinFunctions.cpp.
WORDLENGTH_string
#define WORDLENGTH_string 1
Definition at line 773 of file BuiltinFunctions.cpp.
WORDPOS_MAX
#define WORDPOS_MAX 3
Definition at line 806 of file BuiltinFunctions.cpp.
WORDPOS_MIN
#define WORDPOS_MIN 2
Definition at line 805 of file BuiltinFunctions.cpp.
WORDPOS_phrase
#define WORDPOS_phrase 1
Definition at line 807 of file BuiltinFunctions.cpp.
WORDPOS_start
#define WORDPOS_start 3
Definition at line 809 of file BuiltinFunctions.cpp.
WORDPOS_string
#define WORDPOS_string 2
Definition at line 808 of file BuiltinFunctions.cpp.
WORDS_MAX
#define WORDS_MAX 1
Definition at line 828 of file BuiltinFunctions.cpp.
WORDS_MIN
#define WORDS_MIN 1
Definition at line 827 of file BuiltinFunctions.cpp.
WORDS_string
#define WORDS_string 1
Definition at line 829 of file BuiltinFunctions.cpp.
X2B_MAX
#define X2B_MAX 1
Definition at line 930 of file BuiltinFunctions.cpp.
X2B_MIN
#define X2B_MIN 1
Definition at line 929 of file BuiltinFunctions.cpp.
X2B_string
#define X2B_string 1
Definition at line 931 of file BuiltinFunctions.cpp.
X2C_MAX
#define X2C_MAX 1
Definition at line 957 of file BuiltinFunctions.cpp.
X2C_MIN
#define X2C_MIN 1
Definition at line 956 of file BuiltinFunctions.cpp.
X2C_string
#define X2C_string 1
Definition at line 958 of file BuiltinFunctions.cpp.
X2D_MAX
#define X2D_MAX 2
Definition at line 1000 of file BuiltinFunctions.cpp.
X2D_MIN
#define X2D_MIN 1
Definition at line 999 of file BuiltinFunctions.cpp.
X2D_n
#define X2D_n 2
Definition at line 1002 of file BuiltinFunctions.cpp.
X2D_string
#define X2D_string 1
Definition at line 1001 of file BuiltinFunctions.cpp.
XRANGE_end
#define XRANGE_end 2
Definition at line 1898 of file BuiltinFunctions.cpp.
XRANGE_MAX
#define XRANGE_MAX 2
Definition at line 1896 of file BuiltinFunctions.cpp.
XRANGE_MIN
#define XRANGE_MIN 0
Definition at line 1895 of file BuiltinFunctions.cpp.
XRANGE_start
#define XRANGE_start 1
Definition at line 1897 of file BuiltinFunctions.cpp.
Function Documentation
BUILTIN() [1/80]
BUILTIN (ABBREV)
Definition at line 848 of file BuiltinFunctions.cpp.
References RexxString::abbrev(), fix_args, optional_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [2/80]
BUILTIN (ABS)
Definition at line 2080 of file BuiltinFunctions.cpp.
References RexxString::abs(), fix_args, get_arg, isOfClass, and required_string.
BUILTIN() [3/80]
BUILTIN (ADDRESS)
Definition at line 1157 of file BuiltinFunctions.cpp.
References check_args.
BUILTIN() [4/80]
BUILTIN (ARG)
Definition at line 1230 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_list, Error_Incorrect_call_noarg, fix_args, RexxString::getChar(), RexxInteger::getValue(), IntegerOne, IntegerTwo, new_integer(), optional_integer, optional_string, OREF_NULL, positive_integer, reportException(), TheFalseObject, TheNullArray, and TheTrueObject.
BUILTIN() [5/80]
BUILTIN (B2X)
Definition at line 921 of file BuiltinFunctions.cpp.
References fix_args, and required_string.
BUILTIN() [6/80]
BUILTIN (BITAND)
Definition at line 869 of file BuiltinFunctions.cpp.
References RexxString::bitAnd(), checkPadArgument(), fix_args, IntegerThree, optional_string, and required_string.
BUILTIN() [7/80]
BUILTIN (BITOR)
Definition at line 887 of file BuiltinFunctions.cpp.
References RexxString::bitOr(), checkPadArgument(), fix_args, IntegerThree, optional_string, and required_string.
BUILTIN() [8/80]
BUILTIN (BITXOR)
Definition at line 905 of file BuiltinFunctions.cpp.
References RexxString::bitXor(), checkPadArgument(), fix_args, IntegerThree, optional_string, and required_string.
BUILTIN() [9/80]
BUILTIN (C2D)
Definition at line 976 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, and required_string.
BUILTIN() [10/80]
BUILTIN (C2X)
Definition at line 945 of file BuiltinFunctions.cpp.
References fix_args, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [11/80]
BUILTIN (CENTER)
Definition at line 368 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, IntegerThree, optional_string, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [12/80]
BUILTIN (CENTRE)
Definition at line 389 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, IntegerThree, optional_string, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [13/80]
BUILTIN (CHANGESTR)
Definition at line 2796 of file BuiltinFunctions.cpp.
References RexxString::changeStr(), fix_args, optional_integer, required_string, and TEXT_BIF_TARGET2.
BUILTIN() [14/80]
BUILTIN (CHARIN)
Definition at line 2319 of file BuiltinFunctions.cpp.
References check_queue(), Error_Incorrect_call_queue_no_char, fix_args, optional_big_integer, optional_string, reportException(), and RexxObject::sendMessage().
BUILTIN() [15/80]
BUILTIN (CHAROUT)
Definition at line 2416 of file BuiltinFunctions.cpp.
References check_queue(), Error_Incorrect_call_queue_no_char, fix_args, optional_big_integer, optional_string, reportException(), and RexxObject::sendMessage().
BUILTIN() [16/80]
BUILTIN (CHARS)
Definition at line 2521 of file BuiltinFunctions.cpp.
References check_queue(), Error_Incorrect_call_queue_no_char, fix_args, optional_string, reportException(), and RexxObject::sendMessage().
BUILTIN() [17/80]
BUILTIN (COMPARE)
Definition at line 1050 of file BuiltinFunctions.cpp.
References checkPadArgument(), RexxString::compare(), fix_args, IntegerThree, optional_string, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [18/80]
BUILTIN (CONDITION)
Definition at line 2694 of file BuiltinFunctions.cpp.
References RexxDirectory::at(), RexxDirectory::copy(), RexxObject::copy(), Error_Incorrect_call_list, fix_args, RexxString::getChar(), RexxString::getLength(), IntegerOne, optional_string, OREF_NULL, reportException(), and TheNilObject.
BUILTIN() [19/80]
BUILTIN (COPIES)
Definition at line 793 of file BuiltinFunctions.cpp.
References fix_args, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [20/80]
BUILTIN (COUNTSTR)
Definition at line 2819 of file BuiltinFunctions.cpp.
References RexxString::countStrRexx(), fix_args, required_string, and TEXT_BIF_TARGET2.
BUILTIN() [21/80]
BUILTIN (D2C)
Definition at line 1032 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [22/80]
BUILTIN (D2X)
Definition at line 1018 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, and required_string.
BUILTIN() [23/80]
BUILTIN (DATATYPE)
Definition at line 1144 of file BuiltinFunctions.cpp.
References fix_args, optional_string, required_string, and type.
BUILTIN() [24/80]
BUILTIN (DATE)
Definition at line 1366 of file BuiltinFunctions.cpp.
References ALPHANUM, RexxDateTime::clear(), RexxDateTime::day, Error_Incorrect_call_format_incomp_sep, Error_Incorrect_call_format_invalid, Error_Incorrect_call_list, Error_Incorrect_call_noarg, Error_Incorrect_call_parm_wrong_sep, fix_args, RexxDateTime::formatBaseDate(), RexxDateTime::formatBaseTime(), RexxDateTime::formatDays(), RexxDateTime::formatEuropeanDate(), RexxDateTime::formatMonthName(), RexxDateTime::formatNormalDate(), RexxDateTime::formatOrderedDate(), RexxDateTime::formatStandardDate(), RexxDateTime::formatUnixTime(), RexxDateTime::formatUsaDate(), RexxDateTime::formatWeekDay(), RexxString::getChar(), RexxString::getLength(), SystemInterpreter::getMessageText(), RexxString::getStringData(), RexxDateTime::getTimeZoneOffset(), IntegerFive, IntegerFour, IntegerOne, IntegerThree, IntegerTwo, LeapYear, Message_Translations_January, RexxDateTime::month, new_string(), RexxString::numberValue(), Numerics::objectToInt64(), optional_string, OREF_NULL, RexxDateTime::parseEuropeanDate(), RexxDateTime::parseNormalDate(), RexxDateTime::parseOrderedDate(), RexxDateTime::parseStandardDate(), RexxDateTime::parseUsaDate(), reportException(), RexxDateTime::setBaseDate(), RexxDateTime::setBaseTime(), RexxDateTime::setDate(), RexxDateTime::setTimeZoneOffset(), RexxDateTime::setUnixTime(), work, RexxDateTime::year, and YEAR_DAYS.
BUILTIN() [25/80]
BUILTIN (DELSTR)
Definition at line 410 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [26/80]
BUILTIN (DELWORD)
Definition at line 430 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [27/80]
BUILTIN (DIGITS)
Definition at line 1166 of file BuiltinFunctions.cpp.
References check_args, and new_integer().
BUILTIN() [28/80]
BUILTIN (ENDLOCAL)
Definition at line 2926 of file BuiltinFunctions.cpp.
References check_args, and SystemInterpreter::popEnvironment().
BUILTIN() [29/80]
BUILTIN (ERRORTEXT)
Definition at line 1204 of file BuiltinFunctions.cpp.
References check_args, Error_Incorrect_call_range, SystemInterpreter::getMessageText(), IntegerOne, OREF_NULL, reportException(), and required_integer.
BUILTIN() [30/80]
BUILTIN (FORM)
Definition at line 1184 of file BuiltinFunctions.cpp.
References check_args, and Numerics::FORM_SCIENTIFIC.
BUILTIN() [31/80]
BUILTIN (FORMAT)
Definition at line 2132 of file BuiltinFunctions.cpp.
References fix_args, RexxString::format(), optional_integer, and required_string.
BUILTIN() [32/80]
BUILTIN (FUZZ)
Definition at line 1175 of file BuiltinFunctions.cpp.
References check_args, and new_integer().
BUILTIN() [33/80]
BUILTIN (INSERT)
Definition at line 452 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, RexxString::insert(), IntegerFour, optional_integer, optional_string, required_string, and TEXT_BIF_TARGET2.
BUILTIN() [34/80]
BUILTIN (LASTPOS)
Definition at line 549 of file BuiltinFunctions.cpp.
References fix_args, RexxString::lastPosRexx(), optional_integer, required_string, and TEXT_BIF_TARGET2.
BUILTIN() [35/80]
BUILTIN (LEFT)
Definition at line 477 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, IntegerThree, optional_integer, optional_string, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [36/80]
BUILTIN (LENGTH)
Definition at line 1070 of file BuiltinFunctions.cpp.
References fix_args, RexxString::lengthRexx(), required_string, and TEXT_BIF_TARGET1.
BUILTIN() [37/80]
BUILTIN (LINEIN)
Definition at line 2269 of file BuiltinFunctions.cpp.
References check_queue(), fix_args, line, optional_big_integer, optional_string, and RexxObject::sendMessage().
BUILTIN() [38/80]
BUILTIN (LINEOUT)
Definition at line 2359 of file BuiltinFunctions.cpp.
References check_queue(), fix_args, IntegerZero, line, optional_big_integer, optional_string, OREF_NULL, QUEUE_FIFO, and RexxObject::sendMessage().
BUILTIN() [39/80]
BUILTIN (LINES)
Definition at line 2455 of file BuiltinFunctions.cpp.
References check_queue(), Error_Incorrect_call_list, fix_args, RexxString::getChar(), IntegerOne, IntegerTwo, IntegerZero, RexxObject::numberValue(), optional_string, OREF_NULL, reportException(), and RexxObject::sendMessage().
BUILTIN() [40/80]
BUILTIN (LOWER)
Definition at line 678 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [41/80]
BUILTIN (ORXMAX)
Definition at line 2154 of file BuiltinFunctions.cpp.
References check_args, get_arg, isOfClass, RexxString::Max(), and required_string.
BUILTIN() [42/80]
BUILTIN (ORXMIN)
Definition at line 2177 of file BuiltinFunctions.cpp.
References check_args, get_arg, isOfClass, RexxString::Min(), and required_string.
BUILTIN() [43/80]
BUILTIN (OVERLAY)
Definition at line 500 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, IntegerFive, optional_integer, optional_string, RexxString::overlay(), required_string, and TEXT_BIF_TARGET2.
BUILTIN() [44/80]
BUILTIN (POS)
Definition at line 526 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, RexxString::posRexx(), required_string, and TEXT_BIF_TARGET2.
BUILTIN() [45/80]
BUILTIN (QUALIFY)
Qualify a stream name.
Definition at line 2940 of file BuiltinFunctions.cpp.
References check_args, RexxString::getStringData(), SysFileSystem::MaximumFileNameLength, new_string(), optional_string, and SysFileSystem::qualifyStreamName().
BUILTIN() [46/80]
BUILTIN (QUEUED)
Definition at line 2672 of file BuiltinFunctions.cpp.
References check_args, and RexxObject::sendMessage().
BUILTIN() [47/80]
BUILTIN (QUEUEEXIT)
Definition at line 2897 of file BuiltinFunctions.cpp.
References fix_args, OREF_NULL, and required_string.
BUILTIN() [48/80]
BUILTIN (RANDOM)
Definition at line 1869 of file BuiltinFunctions.cpp.
References arg_omitted, fix_args, IntegerZero, new_integer(), and optional_integer.
BUILTIN() [49/80]
BUILTIN (REVERSE)
Definition at line 570 of file BuiltinFunctions.cpp.
References fix_args, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [50/80]
BUILTIN (RIGHT)
Definition at line 587 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, IntegerThree, optional_integer, optional_string, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [51/80]
BUILTIN (RXFUNCADD)
Definition at line 2839 of file BuiltinFunctions.cpp.
References PackageManager::addRegisteredRoutine(), fix_args, optional_string, OREF_NULL, and required_string.
BUILTIN() [52/80]
BUILTIN (RXFUNCDROP)
Definition at line 2863 of file BuiltinFunctions.cpp.
References PackageManager::dropRegisteredRoutine(), fix_args, and required_string.
BUILTIN() [53/80]
BUILTIN (RXFUNCQUERY)
Definition at line 2878 of file BuiltinFunctions.cpp.
References fix_args, PackageManager::queryRegisteredRoutine(), and required_string.
BUILTIN() [54/80]
BUILTIN (SETLOCAL)
Definition at line 2916 of file BuiltinFunctions.cpp.
References check_args, and SystemInterpreter::pushEnvironment().
BUILTIN() [55/80]
BUILTIN (SIGN)
Definition at line 2104 of file BuiltinFunctions.cpp.
References fix_args, get_arg, isOfClass, required_string, and RexxString::sign().
BUILTIN() [56/80]
BUILTIN (SOURCELINE)
Definition at line 2199 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_sourceline, fix_args, RexxSource::get(), IntegerOne, new_integer(), positive_integer, reportException(), required_integer, and RexxSource::sourceSize().
BUILTIN() [57/80]
BUILTIN (SPACE)
Definition at line 631 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, IntegerThree, optional_integer, optional_string, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [58/80]
BUILTIN (STREAM)
Definition at line 2548 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_list, Error_Incorrect_call_maxarg, Error_Incorrect_call_minarg, Error_Incorrect_call_stream_name, fix_args, RexxString::getChar(), RexxString::getLength(), RexxInteger::getValue(), IntegerThree, IntegerTwo, new_string(), optional_string, OREF_NULL, reportException(), required_string, RexxObject::sendMessage(), RexxString::strCompare(), STREAM_COMMAND, STREAM_DESCRIPTION, STREAM_STATUS, RexxString::upper(), and RexxString::wordPos().
BUILTIN() [59/80]
BUILTIN (STRIP)
Definition at line 608 of file BuiltinFunctions.cpp.
References fix_args, optional_string, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [60/80]
BUILTIN (SUBSTR)
Definition at line 653 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, IntegerFour, optional_integer, optional_string, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [61/80]
BUILTIN (SUBWORD)
Definition at line 723 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [62/80]
BUILTIN (SYMBOL)
Definition at line 1942 of file BuiltinFunctions.cpp.
References RexxVariableBase::exists(), fix_args, RexxVariableDictionary::getVariableRetriever(), isOfClass, new_string(), OREF_NULL, and required_string.
BUILTIN() [63/80]
BUILTIN (TIME)
Definition at line 1645 of file BuiltinFunctions.cpp.
References RexxDateTime::adjustTimeZone(), RexxDateTime::clear(), Error_Incorrect_call_format_invalid, Error_Incorrect_call_invalid_conversion, Error_Incorrect_call_list, Error_Incorrect_call_noarg, fix_args, RexxDateTime::formatBaseTime(), RexxDateTime::formatCivilTime(), RexxDateTime::formatHours(), RexxDateTime::formatLongTime(), RexxDateTime::formatMinutes(), RexxDateTime::formatNormalTime(), RexxDateTime::formatSeconds(), RexxDateTime::formatTimeZone(), RexxDateTime::formatUnixTime(), RexxString::getChar(), RexxString::getLength(), RexxString::getStringData(), RexxDateTime::getTimeZoneOffset(), RexxDateTime::getUTCBaseTime(), IntegerOne, IntegerThree, IntegerTwo, MICROSECONDS, new_string(), RexxString::numberValue(), Numerics::objectToInt64(), optional_string, OREF_NULL, RexxDateTime::parseCivilTime(), RexxDateTime::parseLongTime(), RexxDateTime::parseNormalTime(), reportException(), RexxDateTime::setBaseTime(), RexxDateTime::setHours(), RexxDateTime::setMinutes(), RexxDateTime::setSeconds(), RexxDateTime::setTimeZoneOffset(), RexxDateTime::setUnixTime(), and work.
BUILTIN() [64/80]
BUILTIN (TRACE)
Definition at line 2231 of file BuiltinFunctions.cpp.
References fix_args, optional_string, and OREF_NULL.
BUILTIN() [65/80]
BUILTIN (TRANSLATE)
Definition at line 1090 of file BuiltinFunctions.cpp.
References checkPadArgument(), fix_args, IntegerFour, optional_integer, optional_string, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [66/80]
BUILTIN (TRUNC)
Definition at line 990 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, required_string, and RexxString::trunc().
BUILTIN() [67/80]
BUILTIN (UPPER)
Definition at line 701 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [68/80]
BUILTIN (USERID)
Definition at line 1194 of file BuiltinFunctions.cpp.
References check_args, and SystemInterpreter::getUserid().
BUILTIN() [69/80]
BUILTIN (VALUE)
Definition at line 2007 of file BuiltinFunctions.cpp.
References RexxVariableBase::assign(), Error_Incorrect_call_selector, Error_Incorrect_call_symbol, fix_args, RexxString::getLength(), RexxInternalObject::getValue(), RexxVariableDictionary::getVariableRetriever(), IntegerOne, RexxString::isSymbol(), optional_argument, optional_string, OREF_NULL, reportException(), required_string, STRING_COMPOUND_NAME, STRING_NAME, STRING_STEM, TheEnvironment, RexxString::upper(), and SystemInterpreter::valueFunction().
BUILTIN() [70/80]
BUILTIN (VAR)
Definition at line 1979 of file BuiltinFunctions.cpp.
References RexxVariableBase::exists(), fix_args, RexxVariableDictionary::getVariableRetriever(), isOfClass, OREF_NULL, required_string, TheFalseObject, and TheTrueObject.
BUILTIN() [71/80]
BUILTIN (VERIFY)
Definition at line 1119 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, optional_string, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [72/80]
BUILTIN (WORD)
Definition at line 742 of file BuiltinFunctions.cpp.
References fix_args, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [73/80]
BUILTIN (WORDINDEX)
Definition at line 759 of file BuiltinFunctions.cpp.
References fix_args, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [74/80]
BUILTIN (WORDLENGTH)
Definition at line 776 of file BuiltinFunctions.cpp.
References fix_args, required_integer, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [75/80]
BUILTIN (WORDPOS)
Definition at line 811 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, required_string, and TEXT_BIF_TARGET2.
BUILTIN() [76/80]
BUILTIN (WORDS)
Definition at line 831 of file BuiltinFunctions.cpp.
References fix_args, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [77/80]
BUILTIN (X2B)
Definition at line 933 of file BuiltinFunctions.cpp.
References fix_args, and required_string.
BUILTIN() [78/80]
BUILTIN (X2C)
Definition at line 960 of file BuiltinFunctions.cpp.
References fix_args, required_string, and TEXT_BIF_TARGET1.
BUILTIN() [79/80]
BUILTIN (X2D)
Definition at line 1004 of file BuiltinFunctions.cpp.
References fix_args, optional_integer, and required_string.
BUILTIN() [80/80]
BUILTIN (XRANGE)
Definition at line 1900 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_pad, fix_args, RexxString::getChar(), RexxString::getLength(), IntegerOne, IntegerTwo, optional_string, OREF_NULL, RexxString::putChar(), raw_string(), and reportException().
check_queue()
bool check_queue (RexxString * name)
Definition at line 2248 of file BuiltinFunctions.cpp.
References OREF_NULL, and RexxString::strCaselessCompare().
Referenced by BUILTIN().
checkPadArgument()
void checkPadArgument (const char * pFuncName, RexxObject * position, RexxString * pad)
Definition at line 332 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_pad, RexxString::getLength(), OREF_NULL, and reportException().
Referenced by BUILTIN().
expandArgs()
void expandArgs (RexxObject ** arguments, size_t argcount, size_t min, size_t max, const char * function)
Verify that a function has received all of its required arguments, and did not receive extras.
Parameters
argcount The number of arguments passed to the function.
min The minimum required arguments
max The maximum required arguments
function The function name
Returns
Nothing.
Definition at line 76 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_maxarg, Error_Incorrect_call_minarg, Error_Incorrect_call_noarg, min, OREF_NULL, and reportException().
optionalBigIntegerArg()
RexxObject* optionalBigIntegerArg (size_t position, RexxObject ** arguments, size_t argcount, const char * function)
Process an optional argument and ensure it is a valid integer that can be expressed as a 64-bit value.
Parameters
position The argument position for any error messages (1 to argcount).
argcount The number of arguments passed to the function.
function The function name
Returns
An object that can be converted to a 64-bit value for pass-on to a native function.
Definition at line 309 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_whole, Numerics::int64Object(), OREF_NULL, and reportException().
optionalIntegerArg()
RexxInteger* optionalIntegerArg (size_t position, RexxObject ** arguments, size_t argcount, const char * function)
Process an optional argument and ensure it is a valid integer
Parameters
position The argument position for any error messages (1 to argcount).
argcount The number of arguments passed to the function.
function The function name
Returns
An object that can be converted to an integer argument.
Definition at line 242 of file BuiltinFunctions.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_call_whole, isOfClass, new_integer(), OREF_NULL, reportException(), and RexxObject::requestNumber().
optionalStringArg()
RexxString* optionalStringArg (size_t position, RexxObject ** arguments, size_t argcount, const char * function)
Process an optional argument and potentially convert it into a string argument
Parameters
position The argument position for any error messages (1 to argcount).
argcount The number of arguments passed to the function.
function The function name
Returns
The string representation of the argument.
Definition at line 156 of file BuiltinFunctions.cpp.
References isOfClass, OREF_NULL, and RexxObject::requestString().
requiredBigIntegerArg()
RexxObject* requiredBigIntegerArg (size_t position, RexxObject ** arguments, size_t argcount, const char * function)
Process a required argument and ensure it is a valid integer that can be expressed as a 64-bit value.
Parameters
position The argument position for any error messages (1 to argcount).
argcount The number of arguments passed to the function.
function The function name
Returns
An object that can be converted to a 64-bit value for pass-on to a native function.
Definition at line 278 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_noarg, Error_Incorrect_call_whole, Numerics::int64Object(), OREF_NULL, and reportException().
requiredIntegerArg()
RexxInteger* requiredIntegerArg (size_t position, RexxObject ** arguments, size_t argcount, const char * function)
Process a required argument and ensure it is a valid integer
Parameters
position The argument position for any error messages (1 to argcount).
argcount The number of arguments passed to the function.
function The function name
Returns
An object that can be converted to an integer argument.
Definition at line 210 of file BuiltinFunctions.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_call_noarg, Error_Incorrect_call_whole, isOfClass, new_integer(), OREF_NULL, reportException(), and RexxObject::requestNumber().
requiredStringArg()
RexxString* requiredStringArg (size_t position, RexxObject ** arguments, size_t argcount, const char * function)
Process a required argument and potentially convert it into a string argument
Parameters
position The argument position for any error messages (1 to argcount).
argcount The number of arguments passed to the function.
function The function name
Returns
The string representation of the argument.
Definition at line 129 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_noarg, isOfClass, OREF_NULL, reportException(), and RexxObject::requestString().
requiredTextArg()
RexxText* requiredTextArg (size_t position, RexxObject ** arguments, size_t argcount, const char * function)
Process a required argument and potentially convert it into a text argument
Parameters
position The argument position for any error messages (1 to argcount).
argcount The number of arguments passed to the function.
function The function name
Returns
The text representation of the argument.
Definition at line 185 of file BuiltinFunctions.cpp.
References Error_Incorrect_call_noarg, isOfClass, OREF_NULL, reportException(), and RexxObject::requestText().