executor.master: ListClass.hpp File Reference
ListClass.hpp File Reference
#include "RexxListTable.hpp"
Classes
class RexxList
Macros
#define INITIAL_LIST_SIZE 5 /* initial list allocation */
#define EXTEND_LIST_SIZE 5 /* amount to extend by each time */
#define TABLE_SIZE(n) ((n)*sizeof(LISTENTRY))
#define ENTRY_COUNT(n) ((n)/sizeof(LISTENTRY))
#define ENTRY_POINTER(n) (this->table->getData() + n)
#define ENTRY_INDEX(p) (p - this->table->getData())
#define LIST_END ((size_t)-1) /* end of list marker */
#define NOT_ACTIVE ((size_t)-2) /* free element marker */
Functions
RexxList * new_list ()
Macro Definition Documentation
ENTRY_COUNT
#define ENTRY_COUNT (n) ((n)/sizeof(LISTENTRY))
Definition at line 56 of file ListClass.hpp.
ENTRY_INDEX
#define ENTRY_INDEX (p) (p - this->table->getData())
Definition at line 59 of file ListClass.hpp.
ENTRY_POINTER
#define ENTRY_POINTER (n) (this->table->getData() + n)
Definition at line 58 of file ListClass.hpp.
EXTEND_LIST_SIZE
#define EXTEND_LIST_SIZE 5 /* amount to extend by each time */
Definition at line 50 of file ListClass.hpp.
INITIAL_LIST_SIZE
#define INITIAL_LIST_SIZE 5 /* initial list allocation */
Definition at line 49 of file ListClass.hpp.
LIST_END
#define LIST_END ((size_t)-1) /* end of list marker */
Definition at line 60 of file ListClass.hpp.
NOT_ACTIVE
#define NOT_ACTIVE ((size_t)-2) /* free element marker */
Definition at line 61 of file ListClass.hpp.
TABLE_SIZE
#define TABLE_SIZE (n) ((n)*sizeof(LISTENTRY))
Definition at line 53 of file ListClass.hpp.
Function Documentation
new_list()
RexxList* new_list () inline
Definition at line 147 of file ListClass.hpp.
Referenced by ProtectedSet::add(), ClassDirective::addInherits(), ExtensionDirective::addInherits(), RexxSource::addPackage(), RexxActivity::generateProgramInformation(), RexxSource::globalSetup(), ActivityManager::init(), Interpreter::init(), InterpreterInstance::initialize(), RexxVariableReference::list(), RexxClass::newRexx(), RexxActivation::pushEnvironment(), RexxVariableDictionary::reserve(), RexxSource::resolveDependencies(), RexxMessage::result(), Interpreter::startInterpreter(), RexxClass::subClassable(), RexxSource::translate(), and RexxSource::translateBlock().