executor.master: NumberStringClass.cpp File Reference
NumberStringClass.cpp File Reference
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "RexxCore.h"
#include "StringClass.hpp"
#include "BufferClass.hpp"
#include "RexxActivation.hpp"
#include "NumberStringMath.hpp"
#include "Numerics.hpp"
#include "StringUtil.hpp"
#include "DirectoryClass.hpp"
Macros
#define string_forwarder(method)
Functions
bool numberStringScan (const char *number, size_t length)
void fill_digits (char *outPtr, const char *number, size_t count)
Macro Definition Documentation
string_forwarder
#define string_forwarder (method)
Value:
RexxObject *RexxNumberString::##method(RexxObject *operand)\
 {\
     return (RexxObject *)this->stringValue()->##method(operand);\
 }
Definition at line 74 of file NumberStringClass.cpp.
Function Documentation
fill_digits()
void fill_digits (char * outPtr, const char * number, size_t count)
Definition at line 1282 of file NumberStringClass.cpp.
Referenced by RexxNumberString::formatInternal(), and RexxNumberString::truncInternal().
numberStringScan()
bool numberStringScan (const char * number, size_t length)
Definition at line 1148 of file NumberStringClass.cpp.
References ch_BLANK, ch_MINUS, ch_NINE, ch_PERIOD, ch_PLUS, ch_TAB, and ch_ZERO.
Referenced by RexxNumberString::newInstance().