executor.master: RexxHashTable.cpp File Reference
RexxHashTable.cpp File Reference
#include "RexxCore.h"
#include "RexxHashTable.hpp"
#include "ArrayClass.hpp"
#include "SupplierClass.hpp"
#include "ProtectedObject.hpp"
Functions
bool EQUAL_VALUE (RexxObject *value, RexxObject *other)
Variables
const HashLink NO_MORE = 0
const HashLink NO_LINK = ~((HashLink)0)
Function Documentation
EQUAL_VALUE()
bool EQUAL_VALUE (RexxObject * value, RexxObject * other) inline
Definition at line 68 of file RexxHashTable.cpp.
References RexxObject::isEqual().
Referenced by RexxHashTable::allIndex(), RexxHashTable::countAll(), RexxHashTable::get(), RexxHashTable::getAll(), RexxHashTable::getIndex(), RexxHashTable::hasItem(), RexxHashTable::put(), RexxHashTable::putNodupe(), RexxHashTable::remove(), RexxHashTable::removeAll(), and RexxHashTable::removeItem().
Variable Documentation
NO_LINK
const HashLink NO_LINK = ~((HashLink)0)
Definition at line 64 of file RexxHashTable.cpp.
Referenced by RexxHashTable::primitiveRemove(), RexxHashTable::primitiveRemoveItem(), RexxHashTable::remove(), RexxHashTable::removeAll(), and RexxHashTable::removeItem().
NO_MORE
const HashLink NO_MORE = 0
Definition at line 62 of file RexxHashTable.cpp.
Referenced by RexxHashTable::countAll(), RexxHashTable::emptySlot(), RexxHashTable::get(), RexxHashTable::getAll(), RexxHashTable::hasItem(), RexxHashTable::nextItem(), RexxHashTable::primitiveGet(), RexxHashTable::primitiveGetAll(), RexxHashTable::primitiveHasItem(), RexxHashTable::primitiveNextItem(), RexxHashTable::primitivePut(), RexxHashTable::primitiveRemove(), RexxHashTable::primitiveRemoveItem(), RexxHashTable::put(), RexxHashTable::putNodupe(), RexxHashTable::remove(), RexxHashTable::removeAll(), RexxHashTable::removeItem(), RexxHashTable::stringGet(), RexxHashTable::stringGetAll(), and RexxHashTable::stringPut().