executor.master: RexxHashTable.hpp File Reference
RexxHashTable.hpp File Reference
Classes
struct tabentry
class RexxHashTable
Typedefs
typedef size_t HashLink
typedef struct tabentry TABENTRY
Functions
RexxTable * new_hashCollection (size_t s, size_t s2, size_t t)
RexxHashTable * new_hashtab (size_t s)
Typedef Documentation
HashLink
typedef size_t HashLink
Definition at line 49 of file RexxHashTable.hpp.
TABENTRY
typedef struct tabentry TABENTRY
Function Documentation
new_hashCollection()
RexxTable* new_hashCollection (size_t s, size_t s2, size_t t) inline
Definition at line 156 of file RexxHashTable.hpp.
References RexxHashTable::newInstance().
Referenced by RexxDirectory::newInstance(), RexxRelation::newInstance(), RexxTable::newInstance(), RexxIdentityTable::newInstance(), and RexxVariableDictionary::newInstance().
new_hashtab()
RexxHashTable* new_hashtab (size_t s) inline
Definition at line 157 of file RexxHashTable.hpp.
References RexxHashTable::newInstance().
Referenced by RexxHashTable::insert(), RexxHashTable::reHash(), and RexxTable::reset().