executor.master: RexxActivation.cpp File Reference
RexxActivation.cpp File Reference
#include <ctype.h>
#include <string.h>
#include "RexxCore.h"
#include "StringClass.hpp"
#include "BufferClass.hpp"
#include "DirectoryClass.hpp"
#include "RexxVariableDictionary.hpp"
#include "RexxActivation.hpp"
#include "RexxActivity.hpp"
#include "MethodClass.hpp"
#include "MessageClass.hpp"
#include "RexxCode.hpp"
#include "SourceFile.hpp"
#include "RexxInstruction.hpp"
#include "CallInstruction.hpp"
#include "DoBlock.hpp"
#include "DoInstruction.hpp"
#include "ProtectedObject.hpp"
#include "ActivityManager.hpp"
#include "Interpreter.hpp"
#include "SystemInterpreter.hpp"
#include "RexxInternalApis.h"
#include "PackageManager.hpp"
#include "RexxCompoundTail.hpp"
#include "CommandHandler.hpp"
#include "ActivationFrame.hpp"
#include "StackFrameClass.hpp"
#include "InterpreterInstance.hpp"
#include "PackageClass.hpp"
Classes
class ConcurrencyInfosCollectorInitializer
Macros
#define MAX_INSTRUCTIONS 100
#define DEFAULT_MIN 0 /* default random minimum value */
#define DEFAULT_MAX 999 /* default random maximum value */
#define MAX_DIFFERENCE 999999999 /* max spread between min and max */
#define TRACE_OVERHEAD 15
#define INSTRUCTION_OVERHEAD 11
#define LINENUMBER 6 /* size of a line number */
#define PREFIX_OFFSET (LINENUMBER + 1) /* location of the prefix field */
#define PREFIX_LENGTH 3 /* length of the prefix flag */
#define INDENT_SPACING 2 /* spaces per indentation amount */
#define QUOTES_OVERHEAD 2
Functions
void GetConcurrencyInfos (ConcurrencyInfos &infos)
Variables
static ActivationSettings activationSettingsTemplate
static ConcurrencyInfosCollectorInitializer initializer
static const char * trace_prefix_table []
Macro Definition Documentation
DEFAULT_MAX
#define DEFAULT_MAX 999 /* default random maximum value */
Definition at line 3280 of file RexxActivation.cpp.
DEFAULT_MIN
#define DEFAULT_MIN 0 /* default random minimum value */
Definition at line 3279 of file RexxActivation.cpp.
INDENT_SPACING
#define INDENT_SPACING 2 /* spaces per indentation amount */
Definition at line 3428 of file RexxActivation.cpp.
INSTRUCTION_OVERHEAD
#define INSTRUCTION_OVERHEAD 11
Definition at line 3424 of file RexxActivation.cpp.
LINENUMBER
#define LINENUMBER 6 /* size of a line number */
Definition at line 3425 of file RexxActivation.cpp.
MAX_DIFFERENCE
#define MAX_DIFFERENCE 999999999 /* max spread between min and max */
Definition at line 3281 of file RexxActivation.cpp.
MAX_INSTRUCTIONS
#define MAX_INSTRUCTIONS 100
Definition at line 82 of file RexxActivation.cpp.
PREFIX_LENGTH
#define PREFIX_LENGTH 3 /* length of the prefix flag */
Definition at line 3427 of file RexxActivation.cpp.
PREFIX_OFFSET
#define PREFIX_OFFSET (LINENUMBER + 1) /* location of the prefix field */
Definition at line 3426 of file RexxActivation.cpp.
QUOTES_OVERHEAD
#define QUOTES_OVERHEAD 2
Definition at line 3430 of file RexxActivation.cpp.
TRACE_OVERHEAD
#define TRACE_OVERHEAD 15
Definition at line 3420 of file RexxActivation.cpp.
Function Documentation
GetConcurrencyInfos()
void GetConcurrencyInfos (ConcurrencyInfos & infos)
Definition at line 138 of file RexxActivation.cpp.
References ConcurrencyInfos::activation, ConcurrencyInfos::activity, ActivityManager::currentActivity, Utilities::currentThreadId(), RexxActivation::getVariableDictionary(), RexxActivation::isObjectScopeLocked(), ConcurrencyInfos::lock, ConcurrencyInfos::reserveCount, ConcurrencyInfos::threadId, and ConcurrencyInfos::variableDictionary.
Referenced by ConcurrencyInfosCollectorInitializer::ConcurrencyInfosCollectorInitializer().
Variable Documentation
activationSettingsTemplate
ActivationSettings activationSettingsTemplate static
Definition at line 87 of file RexxActivation.cpp.
Referenced by RexxActivation::RexxActivation().
initializer
ConcurrencyInfosCollectorInitializer initializer static
Definition at line 158 of file RexxActivation.cpp.
trace_prefix_table
const char* trace_prefix_table[] static
Initial value:
= {
  "*-*",
  "+++",
  ">>>",
  ">.>",
  ">V>",
  ">E>",
  ">L>",
  ">F>",
  ">P>",
  ">O>",
  ">C>",
  ">M>",
  ">A>",
  ">=>",
  ">I>",
  ">N>",
}
Definition at line 3394 of file RexxActivation.cpp.
Referenced by RexxActivation::traceCompoundValue(), RexxActivation::traceEntry(), RexxActivation::traceOperatorValue(), RexxActivation::traceSourceString(), RexxActivation::traceTaggedValue(), and RexxActivation::traceValue().