executor.master: RexxActivity.hpp File Reference
RexxActivity.hpp File Reference
#include "ListClass.hpp"
#include "RexxInternalStack.hpp"
#include "RexxActivationStack.hpp"
#include "ExpressionStack.hpp"
#include "RexxLocalVariables.hpp"
#include "SourceLocation.hpp"
#include "ExitHandler.hpp"
#include "ActivationApiContexts.hpp"
#include "SysActivity.hpp"
Classes
class RexxActivity
Macros
#define QUEUE_FIFO 1
#define QUEUE_LIFO 2
#define VALUE_MARKER " => "
#define ASSIGNMENT_MARKER " <= "
#define MAX_TRACEBACK_LIST 80 /* 40 messages are displayed */
#define MAX_TRACEBACK_INDENT 20 /* 10 messages are indented */
#define LAST_EXIT (RXNOOFEXITS - 1) /* top bound of the exits */
Enumerations
enum TracePrefixes {
TRACE_PREFIX_CLAUSE , TRACE_PREFIX_ERROR , TRACE_PREFIX_RESULT , TRACE_PREFIX_DUMMY ,
TRACE_PREFIX_VARIABLE , TRACE_PREFIX_DOTVARIABLE , TRACE_PREFIX_LITERAL , TRACE_PREFIX_FUNCTION ,
TRACE_PREFIX_PREFIX , TRACE_PREFIX_OPERATOR , TRACE_PREFIX_COMPOUND , TRACE_PREFIX_MESSAGE ,
TRACE_PREFIX_ARGUMENT , TRACE_PREFIX_ASSIGNMENT , TRACE_PREFIX_INVOCATION , TRACE_PREFIX_NAMED_ARGUMENT
}
enum ActivityException { RecursiveStringError , FatalError , UnhandledCondition }
Functions
RexxNativeActivation * contextToActivation (RexxThreadContext *c)
RexxNativeActivation * contextToActivation (RexxCallContext *c)
RexxNativeActivation * contextToActivation (RexxExitContext *c)
RexxNativeActivation * contextToActivation (RexxMethodContext *c)
Macro Definition Documentation
ASSIGNMENT_MARKER
#define ASSIGNMENT_MARKER " <= "
Definition at line 102 of file RexxActivity.hpp.
LAST_EXIT
#define LAST_EXIT (RXNOOFEXITS - 1) /* top bound of the exits */
Definition at line 117 of file RexxActivity.hpp.
MAX_TRACEBACK_INDENT
#define MAX_TRACEBACK_INDENT 20 /* 10 messages are indented */
Definition at line 106 of file RexxActivity.hpp.
MAX_TRACEBACK_LIST
#define MAX_TRACEBACK_LIST 80 /* 40 messages are displayed */
Definition at line 105 of file RexxActivity.hpp.
QUEUE_FIFO
#define QUEUE_FIFO 1
Definition at line 72 of file RexxActivity.hpp.
QUEUE_LIFO
#define QUEUE_LIFO 2
Definition at line 73 of file RexxActivity.hpp.
VALUE_MARKER
#define VALUE_MARKER " => "
Definition at line 100 of file RexxActivity.hpp.
Enumeration Type Documentation
ActivityException
enum ActivityException
Enumerator
RecursiveStringError
FatalError
UnhandledCondition
Definition at line 109 of file RexxActivity.hpp.
TracePrefixes
enum TracePrefixes
Enumerator
TRACE_PREFIX_CLAUSE
TRACE_PREFIX_ERROR
TRACE_PREFIX_RESULT
TRACE_PREFIX_DUMMY
TRACE_PREFIX_VARIABLE
TRACE_PREFIX_DOTVARIABLE
TRACE_PREFIX_LITERAL
TRACE_PREFIX_FUNCTION
TRACE_PREFIX_PREFIX
TRACE_PREFIX_OPERATOR
TRACE_PREFIX_COMPOUND
TRACE_PREFIX_MESSAGE
TRACE_PREFIX_ARGUMENT
TRACE_PREFIX_ASSIGNMENT
TRACE_PREFIX_INVOCATION
TRACE_PREFIX_NAMED_ARGUMENT
Definition at line 79 of file RexxActivity.hpp.
Function Documentation
contextToActivation() [1/4]
RexxNativeActivation* contextToActivation (RexxCallContext * c) inline
Convert an API context to into the top native activation context associated with the thread.
Parameters
c The source API context.
Returns
A Native activation context that is the anchor point for the API activity.
Definition at line 439 of file RexxActivity.hpp.
contextToActivation() [2/4]
RexxNativeActivation* contextToActivation (RexxExitContext * c) inline
Convert an API context to into the top native activation context associated with the thread.
Parameters
c The source API context.
Returns
A Native activation context that is the anchor point for the API activity.
Definition at line 454 of file RexxActivity.hpp.
contextToActivation() [3/4]
RexxNativeActivation* contextToActivation (RexxMethodContext * c) inline
Convert an API context to into the top native activation context associated with the thread.
Parameters
c The source API context.
Returns
A Native activation context that is the anchor point for the API activity.
Definition at line 469 of file RexxActivity.hpp.
contextToActivation() [4/4]
RexxNativeActivation* contextToActivation (RexxThreadContext * c) inline
Convert an API context to into the top native activation context associated with the thread.
Parameters
c The source API context.
Returns
A Native activation context that is the anchor point for the API activity.
Definition at line 424 of file RexxActivity.hpp.
References contextToActivity(), and RexxActivity::getApiContext().
Referenced by ApiContext::ApiContext().