executor.master: SourceFile.cpp File Reference
SourceFile.cpp File Reference
#include <ctype.h>
#include <string.h>
#include "RexxCore.h"
#include "StringClass.hpp"
#include "ArrayClass.hpp"
#include "DirectoryClass.hpp"
#include "BufferClass.hpp"
#include "RexxActivity.hpp"
#include "RexxActivation.hpp"
#include "MethodClass.hpp"
#include "RexxNativeCode.hpp"
#include "RexxCode.hpp"
#include "RexxVariableDictionary.hpp"
#include "RexxSmartBuffer.hpp"
#include "SourceFile.hpp"
#include "ExpressionFunction.hpp"
#include "ExpressionMessage.hpp"
#include "ExpressionOperator.hpp"
#include "ExpressionLogical.hpp"
#include "ExpressionList.hpp"
#include "ExpressionBaseVariable.hpp"
#include "ExpressionCompoundVariable.hpp"
#include "ExpressionDotVariable.hpp"
#include "ExpressionVariable.hpp"
#include "IndirectVariableReference.hpp"
#include "ExpressionStem.hpp"
#include "RexxInstruction.hpp"
#include "SelectInstruction.hpp"
#include "ElseInstruction.hpp"
#include "EndIf.hpp"
#include "DoInstruction.hpp"
#include "CallInstruction.hpp"
#include "ProtectedObject.hpp"
#include "CPPCode.hpp"
#include "SystemInterpreter.hpp"
#include "PackageClass.hpp"
#include "InterpreterInstance.hpp"
#include "ClassDirective.hpp"
#include "ExtensionDirective.hpp"
#include "LibraryDirective.hpp"
#include "RequiresDirective.hpp"
#include "PackageManager.hpp"
#include "SysFileSystem.hpp"
#include "RoutineClass.hpp"
#include "ActivationFrame.hpp"
#include "StackFrameClass.hpp"
#include "BlockClass.hpp"
Classes
struct _LINE_DESCRIPTOR
Macros
#define HOLDSIZE 60 /* room for 60 temporaries */
#define line_delimiters "\r\n" /* stream file line end characters */
#define ctrl_z 0x1a
#define dumpClause(from, source, clause)
#define dumpTokens(from, source, clause)
#define TRACE_OVERHEAD 16
#define INSTRUCTION_OVERHEAD 11
#define LINENUMBER 6 /* size of a line number */
#define PREFIX_OFFSET (LINENUMBER + 1) /* location of the prefix field */
#define PREFIX_LENGTH 3 /* length of the prefix flag */
#define INDENT_SPACING 2 /* spaces per indentation amount */
#define ATTRIBUTE_BOTH 0
#define ATTRIBUTE_GET 1
#define ATTRIBUTE_SET 2
Typedefs
typedef struct _LINE_DESCRIPTOR LINE_DESCRIPTOR
Functions
void dumpClauseImpl (const char *from, RexxSource *source, RexxClause *clause)
void dumpTokensImpl (const char *from, RexxSource *source, RexxClause *clause)
Macro Definition Documentation
ATTRIBUTE_BOTH
#define ATTRIBUTE_BOTH 0
Definition at line 2899 of file SourceFile.cpp.
ATTRIBUTE_GET
#define ATTRIBUTE_GET 1
Definition at line 2900 of file SourceFile.cpp.
ATTRIBUTE_SET
#define ATTRIBUTE_SET 2
Definition at line 2901 of file SourceFile.cpp.
ctrl_z
#define ctrl_z 0x1a
Definition at line 103 of file SourceFile.cpp.
dumpClause
#define dumpClause (from, source, clause)
Definition at line 862 of file SourceFile.cpp.
dumpTokens
#define dumpTokens (from, source, clause)
Definition at line 894 of file SourceFile.cpp.
HOLDSIZE
#define HOLDSIZE 60 /* room for 60 temporaries */
Definition at line 95 of file SourceFile.cpp.
INDENT_SPACING
#define INDENT_SPACING 2 /* spaces per indentation amount */
Definition at line 1014 of file SourceFile.cpp.
INSTRUCTION_OVERHEAD
#define INSTRUCTION_OVERHEAD 11
Definition at line 1010 of file SourceFile.cpp.
line_delimiters
#define line_delimiters "\r\n" /* stream file line end characters */
Definition at line 102 of file SourceFile.cpp.
LINENUMBER
#define LINENUMBER 6 /* size of a line number */
Definition at line 1011 of file SourceFile.cpp.
PREFIX_LENGTH
#define PREFIX_LENGTH 3 /* length of the prefix flag */
Definition at line 1013 of file SourceFile.cpp.
PREFIX_OFFSET
#define PREFIX_OFFSET (LINENUMBER + 1) /* location of the prefix field */
Definition at line 1012 of file SourceFile.cpp.
TRACE_OVERHEAD
#define TRACE_OVERHEAD 16
Definition at line 1006 of file SourceFile.cpp.
Typedef Documentation
LINE_DESCRIPTOR
typedef struct _LINE_DESCRIPTOR LINE_DESCRIPTOR
Function Documentation
dumpClauseImpl()
void dumpClauseImpl (const char * from, RexxSource * source, RexxClause * clause)
Definition at line 865 of file SourceFile.cpp.
References ConcurrencyInfos::activation, RexxClause::clauseLocation, CONCURRENCY_TRACE, dbgprintf(), RexxSource::extract(), Utilities::GetConcurrencyInfos(), RexxString::getStringData(), ConcurrencyInfos::lock, ConcurrencyInfos::reserveCount, ConcurrencyInfos::threadId, Utilities::traceConcurrency(), Utilities::traceParsing(), and ConcurrencyInfos::variableDictionary.
dumpTokensImpl()
void dumpTokensImpl (const char * from, RexxSource * source, RexxClause * clause)
Definition at line 897 of file SourceFile.cpp.
References ConcurrencyInfos::activation, RexxToken::classId, RexxToken::codeText(), CONCURRENCY_TRACE, dbgprintf(), RexxClause::free, RexxArray::get(), Utilities::GetConcurrencyInfos(), SourceLocation::getEndLine(), SourceLocation::getEndOffset(), SourceLocation::getLineNumber(), SourceLocation::getOffset(), RexxString::getStringData(), ConcurrencyInfos::lock, RexxToken::numeric, ConcurrencyInfos::reserveCount, RexxToken::subclass, ConcurrencyInfos::threadId, TOKEN_EOC, RexxToken::tokenLocation, RexxClause::tokens, Utilities::traceConcurrency(), Utilities::traceParsing(), RexxToken::value, and ConcurrencyInfos::variableDictionary.