executor.master: StemClass.cpp File Reference
StemClass.cpp File Reference
#include "RexxCore.h"
#include "StringClass.hpp"
#include "ArrayClass.hpp"
#include "RexxActivation.hpp"
#include "RexxNativeActivation.hpp"
#include "RexxVariableDictionary.hpp"
#include "RexxVariable.hpp"
#include "SupplierClass.hpp"
#include "DirectoryClass.hpp"
#include "StemClass.hpp"
#include "RexxCompoundTail.hpp"
Functions
int compare_asc_i (SortData *sd, RexxString *arg1, RexxString *arg2)
int compare_asc_i_cols (SortData *sd, RexxString *arg1, RexxString *arg2)
int compare_asc (SortData *sd, RexxString *arg1, RexxString *arg2)
int compare_asc_cols (SortData *sd, RexxString *arg1, RexxString *arg2)
int compare_desc (SortData *sd, RexxString *arg1, RexxString *arg2)
int compare_desc_cols (SortData *sd, RexxString *arg1, RexxString *arg2)
int compare_desc_i (SortData *sd, RexxString *arg1, RexxString *arg2)
int compare_desc_i_cols (SortData *sd, RexxString *arg1, RexxString *arg2)
Function Documentation
compare_asc()
int compare_asc (SortData * sd, RexxString * arg1, RexxString * arg2)
Definition at line 1239 of file StemClass.cpp.
References RexxString::sortCompare().
Referenced by RexxStem::sort().
compare_asc_cols()
int compare_asc_cols (SortData * sd, RexxString * arg1, RexxString * arg2)
Definition at line 1244 of file StemClass.cpp.
References SortData::columnLength, RexxString::sortCompare(), and SortData::startColumn.
Referenced by RexxStem::sort().
compare_asc_i()
int compare_asc_i (SortData * sd, RexxString * arg1, RexxString * arg2)
Definition at line 1229 of file StemClass.cpp.
References RexxString::sortCaselessCompare().
Referenced by RexxStem::sort().
compare_asc_i_cols()
int compare_asc_i_cols (SortData * sd, RexxString * arg1, RexxString * arg2)
Definition at line 1234 of file StemClass.cpp.
References SortData::columnLength, RexxString::sortCaselessCompare(), and SortData::startColumn.
Referenced by RexxStem::sort().
compare_desc()
int compare_desc (SortData * sd, RexxString * arg1, RexxString * arg2)
Definition at line 1249 of file StemClass.cpp.
References RexxString::sortCompare().
Referenced by RexxStem::sort().
compare_desc_cols()
int compare_desc_cols (SortData * sd, RexxString * arg1, RexxString * arg2)
Definition at line 1254 of file StemClass.cpp.
References SortData::columnLength, RexxString::sortCompare(), and SortData::startColumn.
Referenced by RexxStem::sort().
compare_desc_i()
int compare_desc_i (SortData * sd, RexxString * arg1, RexxString * arg2)
Definition at line 1259 of file StemClass.cpp.
References RexxString::sortCaselessCompare().
Referenced by RexxStem::sort().
compare_desc_i_cols()
int compare_desc_i_cols (SortData * sd, RexxString * arg1, RexxString * arg2)
Definition at line 1264 of file StemClass.cpp.
References SortData::columnLength, RexxString::sortCaselessCompare(), and SortData::startColumn.
Referenced by RexxStem::sort().