executor.master: TextClass.cpp File Reference
TextClass.cpp File Reference
#include "RexxCore.h"
#include "ProtectedObject.hpp"
#include "TextClass.hpp"
#include "m17n/utf8proc/utf8proc.h"
#include <sstream>
#include <string>
#include "m17n/uni-algo/include/uni_algo/version.h"
Functions
ssize_t integerRange (RexxObject *obj, ssize_t min, ssize_t max, wholenumber_t error, const char *errorMessage)
ssize_t integer (RexxObject *obj, const char *errorMessage)
bool isLittleEndian ()
void raiseError (utf8proc_ssize_t errcode)
RexxString * normalize (RexxString *string, utf8proc_option_t options)
Function Documentation
integer()
ssize_t integer (RexxObject * obj, const char * errorMessage)
Definition at line 289 of file TextClass.cpp.
References Error_Invalid_argument_user_defined, OREF_NULL, reportException(), REQUEST_INTEGER(), and TheNilObject.
Referenced by RexxNumberString::formatInt64(), Numerics::formatInt64(), RexxNumberString::formatNumber(), Numerics::formatStringSize(), RexxNumberString::formatUnsignedInt64(), Numerics::formatUnsignedInt64(), RexxNumberString::formatUnsignedNumber(), Numerics::formatWholeNumber(), integerRange(), RexxNumberString::newInstanceFromInt64(), RexxNumberString::newInstanceFromStringsize(), RexxNumberString::newInstanceFromUint64(), RexxNumberString::newInstanceFromWholenumber(), Numerics::normalizeWholeNumber(), RexxTrigger::parse(), RexxActivity::reportAnException(), Unicode::utf8proc_codepointBidiClass(), Unicode::utf8proc_codepointBidiMirrored(), Unicode::utf8proc_codepointBoundClass(), Unicode::utf8proc_codepointCategory(), Unicode::utf8proc_codepointCharWidth(), Unicode::utf8proc_codepointCombiningClass(), Unicode::utf8proc_codepointControlBoundary(), Unicode::utf8proc_codepointDecompositionType(), Unicode::utf8proc_codepointIgnorable(), Unicode::utf8proc_codepointIsLower(), Unicode::utf8proc_codepointIsUpper(), Unicode::utf8proc_codepointToLowerSimple(), Unicode::utf8proc_codepointToTitleSimple(), and Unicode::utf8proc_codepointToUpperSimple().
integerRange()
ssize_t integerRange (RexxObject * obj, ssize_t min, ssize_t max, wholenumber_t error, const char * errorMessage)
Definition at line 273 of file TextClass.cpp.
References integer(), min, OREF_NULL, reportException(), REQUEST_INTEGER(), and TheNilObject.
Referenced by Unicode::utf8proc_graphemeBreak(), and Unicode::utf8proc_transform().
isLittleEndian()
bool isLittleEndian ()
Definition at line 301 of file TextClass.cpp.
Referenced by Unicode::systemIsLittleEndian().
normalize()
RexxString* normalize (RexxString * string, utf8proc_option_t options)
Definition at line 663 of file TextClass.cpp.
References ARG_ONE, RexxString::getLength(), RexxString::getStringData(), new_string(), raiseError(), and stringArgument().
Referenced by Unicode::utf8proc_transform().
raiseError()
void raiseError (utf8proc_ssize_t errcode)
Definition at line 374 of file TextClass.cpp.
References Error_Invalid_argument_user_defined, Error_Invalid_character_string_user_defined, Error_System_resources_user_defined, Error_System_service_user_defined, and reportException().
Referenced by normalize().