executor.master: callrxwn.h File Reference
callrxwn.h File Reference
Macros
#define IDI_APP_ICON 1
#define IDD_CALLREXX_DLG 100
#define IDC_LISTBOX 200
Functions
LRESULT CALLBACK MainDlgProc (HWND hwnd, WORD msg, WPARAM wParam, LPARAM lParam)
int CallRexx (HWND hwnd)
int REXXENTRY RexxIOExit (int ExitNumber, int Subfunction, PEXIT ParmBlock)
Variables
HWND gHwnd
CHAR chTxtBuffer [128]
Macro Definition Documentation
IDC_LISTBOX
#define IDC_LISTBOX 200
Definition at line 53 of file callrxwn.h.
IDD_CALLREXX_DLG
#define IDD_CALLREXX_DLG 100
Definition at line 52 of file callrxwn.h.
IDI_APP_ICON
#define IDI_APP_ICON 1
Definition at line 51 of file callrxwn.h.
Function Documentation
CallRexx()
int CallRexx (HWND hwnd)
Definition at line 147 of file callrxwn.c.
References chTxtBuffer, IDC_LISTBOX, MAKERXSTRING, RexxDeregisterExit(), RexxFreeMemory(), RexxIOExit(), RexxRegisterExitExe(), RexxStart(), RXENDLST, RXSIO, RXSUBROUTINE, _RXSTRING::strlength, _RXSTRING::strptr, _CONSTRXSTRING::strptr, _RXSYSEXIT::sysexit_code, and _RXSYSEXIT::sysexit_name.
Referenced by MainDlgProc().
MainDlgProc()
LRESULT CALLBACK MainDlgProc (HWND hwnd, WORD msg, WPARAM wParam, LPARAM lParam)
Definition at line 97 of file callrxwn.c.
References CallRexx(), and gHwnd.
Referenced by WinMain().
RexxIOExit()
int REXXENTRY RexxIOExit (int ExitNumber, int Subfunction, PEXIT ParmBlock)
Definition at line 236 of file callrxwn.c.
References gHwnd, IDC_LISTBOX, RXEXIT_HANDLED, _RXSIOSAY_PARM::rxsio_string, _RXSIOTRC_PARM::rxsio_string, RXSIODTR, RXSIOSAY, RXSIOTRC, and RXSIOTRD.
Referenced by CallRexx().
Variable Documentation
chTxtBuffer
CHAR chTxtBuffer[128]
Definition at line 48 of file callrxwn.h.
Referenced by CallRexx().
gHwnd
HWND gHwnd
Definition at line 45 of file callrxwn.h.
Referenced by MainDlgProc(), and RexxIOExit().