executor.master: callrxwn.c File Reference
callrxwn.c File Reference
#include <rexx.h>
#include <stdio.h>
#include <string.h>
#include "callrxwn.h"
Functions
int REXXENTRY WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
LRESULT CALLBACK MainDlgProc (HWND hwnd, WORD msg, WPARAM wParam, LPARAM lParam)
int CallRexx (HWND hwnd)
int REXXENTRY RexxIOExit (int ExitNumber, int Subfunction, PEXIT parmblock)
Function Documentation
CallRexx()
int CallRexx (HWND hwnd)
Definition at line 147 of file callrxwn.c.
References chTxtBuffer, IDC_LISTBOX, MAKERXSTRING, RexxDeregisterExit(), RexxFreeMemory(), RexxIOExit(), RexxRegisterExitExe(), RexxStart(), RXENDLST, RXSIO, RXSUBROUTINE, _RXSTRING::strlength, _RXSTRING::strptr, _CONSTRXSTRING::strptr, _RXSYSEXIT::sysexit_code, and _RXSYSEXIT::sysexit_name.
Referenced by MainDlgProc().
MainDlgProc()
LRESULT CALLBACK MainDlgProc (HWND hwnd, WORD msg, WPARAM wParam, LPARAM lParam)
Definition at line 97 of file callrxwn.c.
References CallRexx(), and gHwnd.
Referenced by WinMain().
RexxIOExit()
int REXXENTRY RexxIOExit (int ExitNumber, int Subfunction, PEXIT parmblock)
Definition at line 236 of file callrxwn.c.
References gHwnd, IDC_LISTBOX, RXEXIT_HANDLED, _RXSIOSAY_PARM::rxsio_string, _RXSIOTRC_PARM::rxsio_string, RXSIODTR, RXSIOSAY, RXSIOTRC, and RXSIOTRD.
Referenced by CallRexx().
WinMain()
int REXXENTRY WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Definition at line 74 of file callrxwn.c.
References IDD_CALLREXX_DLG, and MainDlgProc().