executor.master: RexxMutableBuffer Class Reference
RexxMutableBuffer Class Reference
#include <MutableBufferClass.hpp>
Public Member Functions
void * operator new (size_t size, void *ptr)
void * operator new (size_t size, RexxClass *bufferClass)
void * operator new (size_t size)
RexxMutableBuffer ()
RexxMutableBuffer (sizeB_t, sizeB_t)
RexxMutableBuffer (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *envelope)
RexxObject * copy ()
void ensureCapacity (sizeB_t addedLength)
RexxObject * lengthRexx ()
RexxMutableBuffer * append (RexxObject *)
RexxMutableBuffer * appendCstring (const char *, sizeB_t blength)
RexxMutableBuffer * insert (RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxMutableBuffer * overlay (RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxMutableBuffer * replaceAt (RexxObject *str, RexxObject *pos, RexxObject *len, RexxObject *pad)
RexxMutableBuffer * mydelete (RexxObject *, RexxObject *)
RexxString * substr (RexxInteger *startPosition, RexxInteger *len, RexxString *pad)
RexxInteger * lastPos (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxInteger * posRexx (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxInteger * caselessLastPos (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxInteger * caselessPos (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxString * subchar (RexxInteger *startPosition)
RexxInteger * getBufferSize ()
RexxObject * setBufferSize (RexxInteger *)
RexxArray * makeArrayRexx (RexxString *div)
RexxArray * makeArray ()
RexxString * makeString ()
RexxString * primitiveMakeString ()
RexxInteger * countStrRexx (RexxString *needle)
RexxInteger * caselessCountStrRexx (RexxString *needle)
RexxMutableBuffer * changeStr (RexxString *needle, RexxString *newNeedle, RexxInteger *countArg)
RexxMutableBuffer * caselessChangeStr (RexxString *needle, RexxString *newNeedle, RexxInteger *countArg)
RexxMutableBuffer * upper (RexxInteger *_start, RexxInteger *_length)
RexxMutableBuffer * lower (RexxInteger *_start, RexxInteger *_length)
RexxMutableBuffer * translate (RexxString *tableo, RexxString *tablei, RexxString *pad, RexxInteger *, RexxInteger *)
RexxInteger * match (RexxInteger *start_, RexxString *other, RexxInteger *offset_, RexxInteger *len_)
RexxInteger * caselessMatch (RexxInteger *start_, RexxString *other, RexxInteger *offset_, RexxInteger *len_)
bool primitiveMatch (stringsizeB_t start, RexxString *other, stringsizeB_t offset, stringsizeB_t len)
bool primitiveCaselessMatch (stringsizeB_t start, RexxString *other, stringsizeB_t offset, stringsizeB_t len)
RexxInteger * matchChar (RexxInteger *position_, RexxString *matchSet)
RexxInteger * caselessMatchChar (RexxInteger *position_, RexxString *matchSet)
RexxInteger * verify (RexxString *, RexxString *, RexxInteger *, RexxInteger *)
RexxString * subWord (RexxInteger *, RexxInteger *)
RexxArray * subWords (RexxInteger *, RexxInteger *)
RexxString * word (RexxInteger *)
RexxInteger * wordIndex (RexxInteger *)
RexxInteger * wordLength (RexxInteger *)
RexxInteger * words ()
RexxInteger * wordPos (RexxString *, RexxInteger *)
RexxInteger * caselessWordPos (RexxString *, RexxInteger *)
RexxMutableBuffer * delWord (RexxInteger *position, RexxInteger *plength)
RexxMutableBuffer * space (RexxInteger *space_count, RexxString *pad)
const char * getStringData ()
sizeB_t getBLength ()
void setBLength (sizeB_t l)
sizeB_t getBufferLength ()
RexxObject * setBufferLength (sizeB_t)
char * getData ()
void copyData (sizeB_t offset, const char *string, sizeB_t l)
void openGap (sizeB_t offset, sizeB_t _size, sizeB_t tailSize)
void closeGap (sizeB_t offset, sizeB_t _size, sizeB_t tailSize)
void adjustGap (sizeB_t offset, sizeB_t _size, sizeB_t _newSize)
void setData (sizeB_t offset, char character, sizeB_t l)
char getCharB (sizeB_t offset)
sizeB_t setDataLength (sizeB_t l)
sizeB_t getCapacity ()
char * setCapacity (sizeB_t newLength)
Public Member Functions inherited from RexxObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *, void *)
void operator delete (void *)
void operator delete (void *, RexxClass *)
void operator delete (void *, RexxClass *, RexxObject **, size_t)
RexxObject * newRexx (RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxObject * newObject ()
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
virtual RexxObject * defMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
virtual RexxString * defaultName ()
virtual RexxObject * unknown (RexxString *msg, RexxArray *args, RexxDirectory *named_args)
virtual RexxInteger * hasMethod (RexxString *msg)
bool hasUninitMethod ()
RexxObject * init ()
void uninit ()
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
RexxObject * copy ()
HashCode hash ()
bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
RexxNumberString * numberString ()
RexxInteger * integerValue (size_t)
RexxString * makeString ()
RexxString * primitiveMakeString ()
void copyIntoTail (RexxCompoundTail *buffer)
RexxArray * makeArray ()
RexxString * stringValue ()
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (size_t)
bool requestNumber (wholenumber_t &, size_t)
bool requestUnsignedNumber (stringsize_t &, size_t)
RexxArray * requestArray ()
RexxDirectory * requestDirectory ()
RexxString * requiredString (RexxString *kind, size_t)
RexxString * requiredString (RexxString *kind, const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (RexxString *kind, size_t, size_t)
wholenumber_t requiredNumber (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredPositive (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredNonNegative (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
bool isEqual (RexxObject *)
bool isInstanceOf (RexxClass *)
RexxObject * isInstanceOfRexx (RexxClass *)
RexxMethod * instanceMethod (RexxString *)
RexxSupplier * instanceMethods (RexxClass *)
RexxMethod * instanceMethodRexx (RexxString *)
RexxSupplier * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
RexxMessage * start (RexxObject **, size_t, size_t)
RexxMessage * startWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxObject * send (RexxObject **, size_t, size_t)
RexxObject * sendWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxMessage * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxString * oref ()
RexxObject * pmdict ()
RexxObject * run (RexxObject **, size_t, size_t)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, ProtectedObject &, bool processUnknown=true)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, RexxObject *, ProtectedObject &, bool processUnknown=true)
RexxMethod * checkPrivate (RexxMethod *)
void processUnknown (RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
void processProtectedMethod (RexxString *, RexxMethod *, RexxObject **, size_t, size_t, ProtectedObject &)
void sendMessage (RexxString *, RexxArray *, RexxDirectory *, ProtectedObject &)
void sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount, ProtectedObject &result)
void sendMessage (RexxString *message, ProtectedObject &result)
void sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
void sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxArray *, RexxDirectory *=OREF_NULL)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount)
RexxObject * sendMessage (RexxString *message)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * defMethods (RexxDirectory *)
void setObjectVariable (RexxString *, RexxObject *, RexxObject *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxObject *)
void addObjectVariables (RexxVariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxObject * superScope (RexxObject *)
RexxMethod * superMethod (RexxString *, RexxObject *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
const char * idString ()
RexxString * id ()
RexxMethod * methodLookup (RexxString *name)
RexxVariableDictionary * getObjectVariables (RexxObject *)
void guardOn (RexxActivity *activity, RexxObject *scope)
void guardOff (RexxActivity *activity, RexxObject *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
RexxObject * unknownRexx (RexxString *, RexxArray *, RexxObject **, size_t)
RexxObject * hasMethodRexx (RexxString *)
void * getCSelf ()
void * getCSelf (RexxObject *scope)
bool equalValue (RexxObject *other)
virtual wholenumber_t compareTo (RexxObject *)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) RexxVariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, RexxString *&messageName, RexxObject *&startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
sizeB_t bufferLength
sizeB_t defaultSize
sizeB_t dataBLength
RexxBuffer * data
Friends
class RexxMutableBufferClass
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 61 of file MutableBufferClass.hpp.
Constructor & Destructor Documentation
RexxMutableBuffer() [1/3]
RexxMutableBuffer::RexxMutableBuffer ()
Default constructor.
Definition at line 127 of file MutableBufferClass.cpp.
References bufferLength, data, dataBLength, DEFAULT_BUFFER_LENGTH, defaultSize, new_buffer(), OREF_NULL, and RexxBufferBase::setDataLength().
RexxMutableBuffer() [2/3]
RexxMutableBuffer::RexxMutableBuffer (sizeB_t l, sizeB_t d)
Constructor with explicitly set size and default.
Parameters
l Initial length.
d The explicit default size.
Definition at line 147 of file MutableBufferClass.cpp.
References bufferLength, data, defaultSize, new_buffer(), OREF_NULL, and setBLength().
RexxMutableBuffer() [3/3]
RexxMutableBuffer::RexxMutableBuffer (RESTORETYPE restoreType) inline
Definition at line 69 of file MutableBufferClass.hpp.
Member Function Documentation
adjustGap()
void RexxMutableBuffer::adjustGap (sizeB_t offset, sizeB_t _size, sizeB_t _newSize) inline
Definition at line 133 of file MutableBufferClass.hpp.
References RexxBufferBase::adjustGap(), and data.
Referenced by replaceAt().
append()
RexxMutableBuffer * RexxMutableBuffer::append (RexxObject * obj)
Definition at line 333 of file MutableBufferClass.cpp.
References ARG_ONE, copyData(), dataBLength, ensureCapacity(), RexxString::getBLength(), RexxString::getStringData(), setBLength(), and stringArgument().
Referenced by RexxMemory::createImage(), and RexxArray::toString().
appendCstring()
RexxMutableBuffer * RexxMutableBuffer::appendCstring (const char * _data, sizeB_t blength)
Definition at line 349 of file MutableBufferClass.cpp.
References RexxBufferBase::copyData(), data, dataBLength, ensureCapacity(), and setBLength().
caselessChangeStr()
RexxMutableBuffer * RexxMutableBuffer::caselessChangeStr (RexxString * needle, RexxString * newNeedle, RexxInteger * countArg)
Do an inplace caseless changeStr operation on a mutablebuffer.
Parameters
needle The search needle.
newNeedle The replacement string.
countArg The number of occurrences to replace.
Returns
The target MutableBuffer
Definition at line 977 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessCountStr(), StringUtil::caselessPos(), copyData(), ensureCapacity(), getBLength(), RexxString::getBLength(), getStringData(), RexxString::getStringData(), Numerics::MAX_WHOLENUMBER, openGap(), optionalPositive(), setBLength(), and stringArgument().
Referenced by RexxMemory::createImage().
caselessCountStrRexx()
RexxInteger * RexxMutableBuffer::caselessCountStrRexx (RexxString * needle)
Definition at line 814 of file MutableBufferClass.cpp.
References ARG_ONE, StringUtil::caselessCountStr(), getBLength(), getStringData(), new_integer(), and stringArgument().
Referenced by RexxMemory::createImage().
caselessLastPos()
RexxInteger * RexxMutableBuffer::caselessLastPos (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Perform a caseless search for the last position of a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
Returns
The index of the located string. Returns 0 if no matches are found.
Definition at line 755 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessLastPos(), getBLength(), getStringData(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by RexxMemory::createImage().
caselessMatch()
RexxInteger * RexxMutableBuffer::caselessMatch (RexxInteger * start_, RexxString * other, RexxInteger * offset_, RexxInteger * len_)
Test if regions within two strings match.
Parameters
start_ The starting compare position within the target string. This must be within the bounds of the string.
other The other compare string.
offset_ The starting offset of the compare string. This must be within the string bounds. The default start postion is 1.
len_ The length of the compare substring. The length and the offset must specify a valid substring of other. If not specified, this defaults to the substring from the offset to the end of the string.
Returns
True if the two regions match, false for any mismatch.
Definition at line 1326 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, Error_Incorrect_method_length, Error_Incorrect_method_position, getBLength(), RexxString::getBLength(), optionalLengthArgument(), optionalPositionArgument(), positionArgument(), primitiveCaselessMatch(), reportException(), size_v, stringArgument(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
caselessMatchChar()
RexxInteger * RexxMutableBuffer::caselessMatchChar (RexxInteger * position_, RexxString * matchSet)
Compare a single character at a give position against a set of characters to see if any of the characters is a match.
Parameters
position_ The character position
matchSet The set to compare against.
Returns
true if the character at the give position is any of the characters, false if none of them match.
Definition at line 1456 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, Error_Incorrect_method_position, getBLength(), RexxString::getBLength(), getCharB(), RexxString::getCharB(), positionArgument(), reportException(), size_v, stringArgument(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
caselessPos()
RexxInteger * RexxMutableBuffer::caselessPos (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Perform a caseless search for a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
Returns
The index of the located string. Returns 0 if no matches are found.
Definition at line 729 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessPos(), getBLength(), getStringData(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by RexxMemory::createImage().
caselessWordPos()
RexxInteger * RexxMutableBuffer::caselessWordPos (RexxString * phrase, RexxInteger * pstart)
Perform a caseless wordpos search on a string object.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 1616 of file MutableBufferClass.cpp.
References StringUtil::caselessWordPos(), getBLength(), and getStringData().
Referenced by RexxMemory::createImage().
changeStr()
RexxMutableBuffer * RexxMutableBuffer::changeStr (RexxString * needle, RexxString * newNeedle, RexxInteger * countArg)
Do an inplace changeStr operation on a mutablebuffer.
Parameters
needle The search needle.
newNeedle The replacement string.
countArg The number of occurrences to replace.
Returns
The target MutableBuffer
Definition at line 836 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, copyData(), StringUtil::countStr(), ensureCapacity(), getBLength(), RexxString::getBLength(), getStringData(), RexxString::getStringData(), Numerics::MAX_WHOLENUMBER, openGap(), optionalPositive(), StringUtil::pos(), setBLength(), and stringArgument().
Referenced by RexxMemory::createImage().
closeGap()
void RexxMutableBuffer::closeGap (sizeB_t offset, sizeB_t _size, sizeB_t tailSize) inline
Definition at line 132 of file MutableBufferClass.hpp.
References RexxBufferBase::closeGap(), and data.
Referenced by delWord(), and mydelete().
copy()
RexxObject * RexxMutableBuffer::copy (void) virtual
Reimplemented from RexxInternalObject.
Definition at line 222 of file MutableBufferClass.cpp.
References bufferLength, RexxInternalObject::clone(), copyData(), data, dataBLength, defaultSize, RexxBuffer::getData(), new_buffer(), and setBLength().
copyData()
void RexxMutableBuffer::copyData (sizeB_t offset, const char * string, sizeB_t l) inline
Definition at line 130 of file MutableBufferClass.hpp.
References RexxBufferBase::copyData(), and data.
Referenced by append(), caselessChangeStr(), changeStr(), copy(), insert(), RexxMutableBufferClass::newRexx(), overlay(), replaceAt(), and space().
countStrRexx()
RexxInteger * RexxMutableBuffer::countStrRexx (RexxString * needle)
Definition at line 801 of file MutableBufferClass.cpp.
References ARG_ONE, StringUtil::countStr(), getBLength(), getStringData(), new_integer(), and stringArgument().
Referenced by RexxMemory::createImage().
createInstance()
void RexxMutableBuffer::createInstance () static
Create initial class object at bootstrap time.
Definition at line 63 of file MutableBufferClass.cpp.
References CLASS_CREATE.
Referenced by RexxMemory::createImage().
delWord()
RexxMutableBuffer * RexxMutableBuffer::delWord (RexxInteger * position, RexxInteger * plength)
Perform a delword operation on a mutable buffer
Parameters
position The position to delete.
plength The number of words to delete
Returns
Always returns the target mutable buffer.
Definition at line 1631 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, closeGap(), dataBLength, getBLength(), getStringData(), Numerics::MAX_WHOLENUMBER, StringUtil::nextWord(), optionalLengthArgument(), positionArgument(), setBLength(), sizeB_v, and StringUtil::skipBlanks().
Referenced by RexxMemory::createImage().
ensureCapacity()
void RexxMutableBuffer::ensureCapacity (sizeB_t addedLength)
Definition at line 241 of file MutableBufferClass.cpp.
References bufferLength, RexxBufferBase::copyData(), data, dataBLength, RexxBuffer::getData(), RexxBufferBase::getDataLength(), new_buffer(), OrefSet, and RexxBufferBase::setDataLength().
Referenced by append(), appendCstring(), caselessChangeStr(), changeStr(), insert(), overlay(), replaceAt(), setCapacity(), and space().
flatten()
void RexxMutableBuffer::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 209 of file MutableBufferClass.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
getBLength()
sizeB_t RexxMutableBuffer::getBLength () inline
Definition at line 125 of file MutableBufferClass.hpp.
References dataBLength.
Referenced by caselessChangeStr(), caselessCountStrRexx(), caselessLastPos(), caselessMatch(), caselessMatchChar(), caselessPos(), caselessWordPos(), changeStr(), countStrRexx(), delWord(), lastPos(), lengthRexx(), lower(), makeArrayRexx(), match(), matchChar(), posRexx(), primitiveCaselessMatch(), primitiveMatch(), setDataLength(), space(), subchar(), substr(), subWord(), subWords(), translate(), upper(), verify(), word(), wordIndex(), wordLength(), wordPos(), and words().
getBufferLength()
sizeB_t RexxMutableBuffer::getBufferLength () inline
Definition at line 127 of file MutableBufferClass.hpp.
References bufferLength.
getBufferSize()
RexxInteger* RexxMutableBuffer::getBufferSize () inline
Definition at line 93 of file MutableBufferClass.hpp.
References bufferLength, and new_integer().
Referenced by RexxMemory::createImage().
getCapacity()
sizeB_t RexxMutableBuffer::getCapacity () inline
Definition at line 137 of file MutableBufferClass.hpp.
References bufferLength.
Referenced by setDataLength().
getCharB()
char RexxMutableBuffer::getCharB (sizeB_t offset) inline
Definition at line 135 of file MutableBufferClass.hpp.
References getData(), and size_v.
Referenced by caselessMatchChar(), and matchChar().
getData()
char* RexxMutableBuffer::getData () inline
Definition at line 129 of file MutableBufferClass.hpp.
References data, and RexxBuffer::getData().
Referenced by getCharB(), lower(), setCapacity(), translate(), and upper().
getStringData()
const char* RexxMutableBuffer::getStringData () inline
Definition at line 124 of file MutableBufferClass.hpp.
References data, and RexxBuffer::getData().
Referenced by caselessChangeStr(), caselessCountStrRexx(), caselessLastPos(), caselessPos(), caselessWordPos(), changeStr(), countStrRexx(), delWord(), lastPos(), makeArrayRexx(), posRexx(), primitiveCaselessMatch(), primitiveMatch(), space(), subchar(), substr(), subWord(), subWords(), verify(), word(), wordIndex(), wordLength(), wordPos(), and words().
insert()
RexxMutableBuffer * RexxMutableBuffer::insert (RexxObject * str, RexxObject * pos, RexxObject * len, RexxObject * pad)
Definition at line 364 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, copyData(), dataBLength, ensureCapacity(), RexxString::getBLength(), RexxString::getStringData(), Numerics::minVal(), openGap(), optionalLengthArgument(), optionalNonNegative(), optionalPadArgument(), setBLength(), setData(), and stringArgument().
Referenced by RexxMemory::createImage().
lastPos()
RexxInteger * RexxMutableBuffer::lastPos (RexxString * needle, RexxInteger * _start, RexxInteger * _range)
Perform a search for the last position of a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
Returns
The index of the located string. Returns 0 if no matches are found.
Definition at line 713 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::lastPosRexx().
Referenced by RexxMemory::createImage().
lengthRexx()
RexxObject * RexxMutableBuffer::lengthRexx ()
Return the length of the data in the buffer currently.
Returns
The current length, as an Integer object.
Definition at line 326 of file MutableBufferClass.cpp.
References getBLength(), and new_integer().
Referenced by RexxMemory::createImage().
live()
void RexxMutableBuffer::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 190 of file MutableBufferClass.cpp.
References data, and memory_mark.
liveGeneral()
void RexxMutableBuffer::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 199 of file MutableBufferClass.cpp.
References data, and memory_mark_general.
lower()
RexxMutableBuffer * RexxMutableBuffer::lower (RexxInteger * _start, RexxInteger * _length)
Rexx exported method stub for the lower() method.
Parameters
start The optional starting location. Defaults to the first character if not specified.
length The length to convert. Defaults to the segment from the start position to the end of the string.
Returns
A new string object with the case conversion applied.
Definition at line 1119 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, getBLength(), getData(), Numerics::minVal(), optionalLengthArgument(), and optionalPositionArgument().
Referenced by RexxMemory::createImage().
makeArray()
RexxArray * RexxMutableBuffer::makeArray (void) virtual
Baseclass optimization for handling request array calls.
Returns
The string object converted to an array using default arguments.
Reimplemented from RexxInternalObject.
Definition at line 650 of file MutableBufferClass.cpp.
References RexxObject::makeArrayRexx(), and OREF_NULL.
makeArrayRexx()
RexxArray * RexxMutableBuffer::makeArrayRexx (RexxString * div)
Definition at line 791 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::makearray().
makeString()
RexxString * RexxMutableBuffer::makeString () virtual
Reimplemented from RexxInternalObject.
Definition at line 637 of file MutableBufferClass.cpp.
References data, RexxBuffer::getData(), and new_string().
Referenced by primitiveMakeString(), and RexxArray::toString().
match()
RexxInteger * RexxMutableBuffer::match (RexxInteger * start_, RexxString * other, RexxInteger * offset_, RexxInteger * len_)
Test if regions within two strings match.
Parameters
start_ The starting compare position within the target string. This must be within the bounds of the string.
other The other compare string.
offset_ The starting offset of the compare string. This must be within the string bounds. The default start postion is 1.
len_ The length of the compare substring. The length and the offset must specify a valid substring of other. If not specified, this defaults to the substring from the offset to the end of the string.
Returns
True if the two regions match, false for any mismatch.
Definition at line 1282 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, Error_Incorrect_method_length, Error_Incorrect_method_position, getBLength(), RexxString::getBLength(), optionalLengthArgument(), optionalPositionArgument(), positionArgument(), primitiveMatch(), reportException(), size_v, stringArgument(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
matchChar()
RexxInteger * RexxMutableBuffer::matchChar (RexxInteger * position_, RexxString * matchSet)
Compare a single character at a give position against a set of characters to see if any of the characters is a match.
Parameters
position_ The character position
matchSet The set to compare against.
Returns
true if the character at the give position is any of the characters, false if none of them match.
Definition at line 1419 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, Error_Incorrect_method_position, getBLength(), RexxString::getBLength(), getCharB(), RexxString::getCharB(), positionArgument(), reportException(), size_v, stringArgument(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
mydelete()
RexxMutableBuffer * RexxMutableBuffer::mydelete (RexxObject * _start, RexxObject * len)
Definition at line 563 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, closeGap(), dataBLength, optionalLengthArgument(), positionArgument(), and setBLength().
Referenced by RexxMemory::createImage().
openGap()
void RexxMutableBuffer::openGap (sizeB_t offset, sizeB_t _size, sizeB_t tailSize) inline
Definition at line 131 of file MutableBufferClass.hpp.
References data, and RexxBufferBase::openGap().
Referenced by caselessChangeStr(), changeStr(), insert(), and space().
operator new() [1/3]
void * RexxMutableBuffer::operator new (size_t size)
Create a new mutable buffer object from a potential subclass.
Parameters
size The size of the buffer object.
Returns
A new instance of a mutable buffer, with the default class behaviour.
Definition at line 167 of file MutableBufferClass.cpp.
References new_object(), and T_MutableBuffer.
operator new() [2/3]
void * RexxMutableBuffer::operator new (size_t size, RexxClass * bufferClass)
Create a new mutable buffer object from a potential subclass.
Parameters
size The size of the buffer object.
bufferClass The class of the buffer object.
Returns
A new instance of a mutable buffer, with the target class behaviour.
Definition at line 182 of file MutableBufferClass.cpp.
References new_object(), RexxInternalObject::setBehaviour(), and T_MutableBuffer.
operator new() [3/3]
void* RexxMutableBuffer::operator new (size_t size, void * ptr) inline
Definition at line 64 of file MutableBufferClass.hpp.
overlay()
RexxMutableBuffer * RexxMutableBuffer::overlay (RexxObject * str, RexxObject * pos, RexxObject * len, RexxObject * pad)
Definition at line 432 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, copyData(), dataBLength, ensureCapacity(), RexxString::getBLength(), RexxString::getStringData(), Numerics::minVal(), optionalLengthArgument(), optionalPadArgument(), optionalPositionArgument(), setBLength(), setData(), and stringArgument().
Referenced by RexxMemory::createImage().
posRexx()
RexxInteger * RexxMutableBuffer::posRexx (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Perform a search for a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
Returns
The index of the located string. Returns 0 if no matches are found.
Definition at line 696 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::posRexx().
Referenced by RexxMemory::createImage().
primitiveCaselessMatch()
bool RexxMutableBuffer::primitiveCaselessMatch (stringsizeB_t _start, RexxString * other, stringsizeB_t offset, stringsizeB_t len)
Perform a caselesee compare of regions of two string objects. Returns true if the two regions match, returns false for mismatches.
Parameters
start The starting offset within the target string.
other The source string for the compare.
offset The offset of the substring of the other string to use.
len The length of the substring to compare.
Returns
True if the regions match, false otherwise.
Definition at line 1392 of file MutableBufferClass.cpp.
References StringUtil::caselessCompare(), getBLength(), getStringData(), and RexxString::getStringData().
Referenced by caselessMatch().
primitiveMakeString()
RexxString * RexxMutableBuffer::primitiveMakeString () virtual
Handle the primitive class makeString optimization. This is required because MutableBuffer implements a STRING method.
Returns
The string value of the buffer
Reimplemented from RexxInternalObject.
Definition at line 663 of file MutableBufferClass.cpp.
References makeString().
primitiveMatch()
bool RexxMutableBuffer::primitiveMatch (stringsizeB_t _start, RexxString * other, stringsizeB_t offset, stringsizeB_t len)
Perform a compare of regions of two string objects. Returns true if the two regions match, returns false for mismatches.
Parameters
start The starting offset within the target string.
other The source string for the compare.
offset The offset of the substring of the other string to use.
len The length of the substring to compare.
Returns
True if the regions match, false otherwise.
Definition at line 1365 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and RexxString::getStringData().
Referenced by match().
replaceAt()
RexxMutableBuffer * RexxMutableBuffer::replaceAt (RexxObject * str, RexxObject * pos, RexxObject * len, RexxObject * pad)
Replace a target substring within a string with a new string value. This is similar overlay, but replacing might cause the characters following the replacement position to be shifted to the left or right.
Parameters
str The replacement string.
pos The target position (required).
len The target length (optional). If not specified, the length of the replacement string is used, and this is essentially an overlay operation.
pad A padding character if padding is required. The default pad is a ' '. Padding only occurs if the replacement position is beyond the current data length.
Returns
The target mutablebuffer object.
Definition at line 492 of file MutableBufferClass.cpp.
References adjustGap(), ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, copyData(), dataBLength, ensureCapacity(), RexxString::getStringData(), optionalLengthArgument(), optionalPadArgument(), positionArgument(), setBLength(), setData(), and stringArgument().
Referenced by RexxMemory::createImage().
setBLength()
void RexxMutableBuffer::setBLength (sizeB_t l) inline
Definition at line 126 of file MutableBufferClass.hpp.
References data, dataBLength, RexxBufferBase::setDataLength(), and size_v.
Referenced by append(), appendCstring(), caselessChangeStr(), changeStr(), copy(), delWord(), insert(), mydelete(), RexxMutableBufferClass::newRexx(), overlay(), replaceAt(), RexxMutableBuffer(), and setBufferLength().
setBufferLength()
RexxObject * RexxMutableBuffer::setBufferLength (sizeB_t newsize)
Definition at line 591 of file MutableBufferClass.cpp.
References bufferLength, RexxBufferBase::copyData(), data, dataBLength, defaultSize, RexxBuffer::getData(), Numerics::minVal(), new_buffer(), OrefSet, and setBLength().
Referenced by setBufferSize().
setBufferSize()
RexxObject * RexxMutableBuffer::setBufferSize (RexxInteger * size)
Definition at line 627 of file MutableBufferClass.cpp.
References ARG_ONE, lengthArgument(), and setBufferLength().
Referenced by RexxMemory::createImage().
setCapacity()
char * RexxMutableBuffer::setCapacity (sizeB_t newLength)
Set the capacity of the buffer.
Parameters
newLength The new buffer length
Returns
The pointer to the data area in the buffer.
Definition at line 307 of file MutableBufferClass.cpp.
References bufferLength, ensureCapacity(), and getData().
setData()
void RexxMutableBuffer::setData (sizeB_t offset, char character, sizeB_t l) inline
Definition at line 134 of file MutableBufferClass.hpp.
References data, and RexxBufferBase::setData().
Referenced by insert(), overlay(), replaceAt(), setDataLength(), and space().
setDataLength()
sizeB_t RexxMutableBuffer::setDataLength (sizeB_t newLength)
Set the length of the data in the buffer. The limit is the current capacity of the buffer. If the length is extended beyond the current length, the extra characters of the buffer will be filled with nulls.
Parameters
newLength The new datalength. This is capped to the capacity of the buffer.
Returns
The actual length the data has been set to. If the target length is greater than the capacity, the capacity value is returned.
Definition at line 279 of file MutableBufferClass.cpp.
References dataBLength, getBLength(), getCapacity(), and setData().
space()
RexxMutableBuffer * RexxMutableBuffer::space (RexxInteger * space_count, RexxString * pad)
Do an inplace space() operation on a mutable buffer.
Parameters
space_count The number of pad characters between each word
pad The pad character
Returns
The target MutableBuffer
Definition at line 1693 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, copyData(), dataBLength, ensureCapacity(), getBLength(), getStringData(), StringUtil::nextWord(), openGap(), optionalLengthArgument(), optionalPadArgument(), and setData().
Referenced by RexxMemory::createImage().
subchar()
RexxString * RexxMutableBuffer::subchar (RexxInteger * positionArg)
Extract a single character from a string object. Returns a null string if the specified position is beyond the bounds of the string.
Parameters
positionArg The position of the target character. Must be a positive whole number.
Returns
Returns the single character at the target position. Returns a null string if the position is beyond the end of the string.
Definition at line 784 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::subchar().
Referenced by RexxMemory::createImage().
substr()
RexxString * RexxMutableBuffer::substr (RexxInteger * startPosition, RexxInteger * len, RexxString * pad)
Definition at line 678 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::substr().
Referenced by RexxMemory::createImage().
subWord()
RexxString * RexxMutableBuffer::subWord (RexxInteger * position, RexxInteger * plength)
Perform a subword extraction from a mutable buffer.
Parameters
position The first word to be extracted.
plength The number of words to extract.
Returns
The substring containing the extacted words.
Definition at line 1509 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::subWord().
Referenced by RexxMemory::createImage().
subWords()
RexxArray * RexxMutableBuffer::subWords (RexxInteger * position, RexxInteger * plength)
Returns an array of all words contained in the given range of the string, using the same extraction rules used for subWord() and word().
Parameters
position The optional starting position. If not provided, extraction starts with the first word.
plength The number of words to extract. If omitted, will extract from the starting postion to the end of the string.
Returns
An array containing the extracted words. If no words are available within the given range, this returns an empty array.
Definition at line 1529 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::subWords().
Referenced by RexxMemory::createImage().
translate()
RexxMutableBuffer * RexxMutableBuffer::translate (RexxString * tableo, RexxString * tablei, RexxString * pad, RexxInteger * _start, RexxInteger * _range)
translate characters in the buffer using a translation table.
Parameters
tableo The output table specification
tablei The input table specification
pad An optional padding character (default is a space).
_start The starting position to translate.
_range The length to translate
Returns
The target mutable buffer.
Definition at line 1202 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, getBLength(), RexxString::getBLength(), getData(), RexxString::getStringData(), StringUtil::memPos(), Numerics::minVal(), optionalLengthArgument(), optionalPadArgument(), optionalPositionArgument(), optionalStringArgument(), OREF_NULL, and upper().
Referenced by RexxMemory::createImage().
upper()
RexxMutableBuffer * RexxMutableBuffer::upper (RexxInteger * _start, RexxInteger * _length)
Rexx exported method stub for the upper() method.
Parameters
start The optional starting location. Defaults to the first character if not specified.
length The length to convert. Defaults to the segment from the start position to the end of the string.
Returns
A new string object with the case conversion applied.
Definition at line 1160 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, getBLength(), getData(), Numerics::minVal(), optionalLengthArgument(), and optionalPositionArgument().
Referenced by RexxMemory::createImage(), and translate().
verify()
RexxInteger * RexxMutableBuffer::verify (RexxString * ref, RexxString * option, RexxInteger * _start, RexxInteger * range)
Perform a character verify operation on a mutable buffer.
Parameters
ref The reference string.
option The match/nomatch option.
_start The start position for the verify.
range The range to search
Returns
The offset of the first match/mismatch within the buffer.
Definition at line 1494 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::verify().
Referenced by RexxMemory::createImage().
word()
RexxString * RexxMutableBuffer::word (RexxInteger * position)
Extract a given word from a mutable buffer.
Parameters
position The target word position.
Returns
The extracted word, as a string.
Definition at line 1543 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::word().
Referenced by RexxMemory::createImage().
wordIndex()
RexxInteger * RexxMutableBuffer::wordIndex (RexxInteger * position)
return the index of a given word position in a mutable buffer
Parameters
position The target word position.
Returns
The position of the target word.
Definition at line 1558 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::wordIndex().
Referenced by RexxMemory::createImage().
wordLength()
RexxInteger * RexxMutableBuffer::wordLength (RexxInteger * position)
return the length of a given word position in a mutable buffer
Parameters
position The target word position.
Returns
The length of the target word.
Definition at line 1574 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::wordLength().
Referenced by RexxMemory::createImage().
wordPos()
RexxInteger * RexxMutableBuffer::wordPos (RexxString * phrase, RexxInteger * pstart)
Perform a wordpos search on a mutablebuffer object.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 1601 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), and StringUtil::wordPos().
Referenced by RexxMemory::createImage().
words()
RexxInteger * RexxMutableBuffer::words ()
Return the count of words in the buffer.
Returns
The buffer word count.
Definition at line 1585 of file MutableBufferClass.cpp.
References getBLength(), getStringData(), new_integer(), and StringUtil::wordCount().
Referenced by RexxMemory::createImage().
Friends And Related Function Documentation
RexxMutableBufferClass
friend class RexxMutableBufferClass friend
Definition at line 62 of file MutableBufferClass.hpp.
Member Data Documentation
bufferLength
sizeB_t RexxMutableBuffer::bufferLength protected
Definition at line 146 of file MutableBufferClass.hpp.
Referenced by copy(), ensureCapacity(), getBufferLength(), getBufferSize(), getCapacity(), RexxMutableBuffer(), setBufferLength(), and setCapacity().
classInstance
RexxClass * RexxMutableBuffer::classInstance = OREF_NULL static
Definition at line 143 of file MutableBufferClass.hpp.
data
RexxBuffer* RexxMutableBuffer::data protected
Definition at line 149 of file MutableBufferClass.hpp.
Referenced by adjustGap(), appendCstring(), closeGap(), copy(), copyData(), ensureCapacity(), getData(), getStringData(), live(), liveGeneral(), makeString(), openGap(), RexxMutableBuffer(), setBLength(), setBufferLength(), and setData().
dataBLength
sizeB_t RexxMutableBuffer::dataBLength protected
Definition at line 148 of file MutableBufferClass.hpp.
Referenced by append(), appendCstring(), copy(), delWord(), ensureCapacity(), getBLength(), insert(), mydelete(), overlay(), replaceAt(), RexxMutableBuffer(), setBLength(), setBufferLength(), setDataLength(), and space().
defaultSize
sizeB_t RexxMutableBuffer::defaultSize protected
Definition at line 147 of file MutableBufferClass.hpp.
Referenced by copy(), RexxMutableBuffer(), and setBufferLength().
The documentation for this class was generated from the following files:
MutableBufferClass.hpp
MutableBufferClass.cpp