executor.master: RexxInstructionCall Class Reference
RexxInstructionCall Class Reference
#include <CallInstruction.hpp>
Public Types
enum {
call_nointernal = 0x01 , call_type_mask = 0x0e , call_internal = 0x02 , call_builtin = 0x06 ,
call_external = 0x0e , call_dynamic = 0x10 , call_on_off = 0x20
}
Public Member Functions
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxInstructionCall (RexxObject *, RexxString *, size_t, RexxQueue *, size_t, RexxQueue *, size_t, size_t)
RexxInstructionCall (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
void execute (RexxActivation *, RexxExpressionStack *)
void resolve (RexxDirectory *)
void trap (RexxActivation *, RexxDirectory *)
Public Member Functions inherited from RexxInstructionCallBase
RexxInstructionCallBase ()
Public Member Functions inherited from RexxInstruction
void * operator new (size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *)
void operator delete (void *, void *)
RexxInstruction (RexxClause *clause, int type)
RexxInstruction (RESTORETYPE restoreType)
RexxInstruction ()
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
const SourceLocation & getLocation ()
void setLocation (SourceLocation &l)
void setNext (RexxInstruction *next)
void setStart (size_t line, sizeB_t off)
void setEnd (size_t line, sizeB_t off)
void setType (size_t type)
size_t getType ()
bool isType (size_t type)
size_t getLineNumber ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Protected Attributes
RexxObject * arguments [1]
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInstructionCallBase
RexxObject * name
RexxInstruction * target
RexxString * condition
uint16_t argumentCount
uint16_t namedArgumentCount
uint16_t builtinIndex
Public Attributes inherited from RexxInstruction
uint16_t instructionType
uint16_t instructionFlags
SourceLocation instructionLocation
RexxInstruction * nextInstruction
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 64 of file CallInstruction.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
call_nointernal
call_type_mask
call_internal
call_builtin
call_external
call_dynamic
call_on_off
Definition at line 66 of file CallInstruction.hpp.
Constructor & Destructor Documentation
RexxInstructionCall() [1/2]
RexxInstructionCall::RexxInstructionCall (RexxObject * _name, RexxString * _condition, size_t argCount, RexxQueue * argList, size_t namedArgCount, RexxQueue * namedArgList, size_t flags, size_t builtin_index)
Definition at line 56 of file CallInstruction.cpp.
References RexxInstructionCallBase::argumentCount, arguments, RexxInstructionCallBase::builtinIndex, RexxInstructionCallBase::condition, RexxInstruction::instructionFlags, RexxInstructionCallBase::name, RexxInstructionCallBase::namedArgumentCount, OrefSet, and RexxQueue::pop().
RexxInstructionCall() [2/2]
RexxInstructionCall::RexxInstructionCall (RESTORETYPE restoreType) inline
Definition at line 82 of file CallInstruction.hpp.
Member Function Documentation
execute()
void RexxInstructionCall::execute (RexxActivation * context, RexxExpressionStack * stack) virtual
Reimplemented from RexxInstruction.
Definition at line 179 of file CallInstruction.cpp.
References RexxInstructionCallBase::argumentCount, RexxExpressionStack::arguments(), arguments, RexxDirectory::at(), RexxInstructionCallBase::builtinIndex, RexxSource::builtinTable, call_builtin, call_dynamic, call_external, call_internal, call_on_off, call_type_mask, RexxActivity::checkStackSpace(), RexxInstructionCallBase::condition, ActivityManager::currentActivity, RexxActivation::dropLocalVariable(), RexxInternalObject::evaluate(), RexxActivation::externalCall(), RexxActivation::getLabels(), RexxInstruction::instructionFlags, RexxActivation::internalCall(), RexxInstructionCallBase::name, RexxInstructionCallBase::namedArgumentCount, NO_BUILTIN, OREF_NULL, RexxActivation::pauseInstruction(), RexxExpressionStack::push(), REQUEST_STRING(), RexxSource::resolveBuiltin(), RexxActivation::setLocalVariable(), RexxInstructionCallBase::target, RexxExpressionStack::toss(), TRACE_PREFIX_ARGUMENT, TRACE_PREFIX_NAMED_ARGUMENT, RexxActivation::traceInstruction(), RexxActivation::traceIntermediate(), RexxActivation::traceResult(), RexxActivation::trapOff(), RexxActivation::trapOn(), type, and VARIABLE_RESULT.
flatten()
void RexxInstructionCall::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 130 of file CallInstruction.cpp.
References RexxInstructionCallBase::argumentCount, cleanUpFlatten, flatten_reference, RexxInstructionCallBase::namedArgumentCount, and setUpFlatten.
live()
void RexxInstructionCall::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 93 of file CallInstruction.cpp.
References RexxInstructionCallBase::argumentCount, arguments, RexxInstructionCallBase::condition, memory_mark, RexxInstructionCallBase::name, RexxInstructionCallBase::namedArgumentCount, RexxInstruction::nextInstruction, and RexxInstructionCallBase::target.
liveGeneral()
void RexxInstructionCall::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 111 of file CallInstruction.cpp.
References RexxInstructionCallBase::argumentCount, arguments, RexxInstructionCallBase::condition, memory_mark_general, RexxInstructionCallBase::name, RexxInstructionCallBase::namedArgumentCount, RexxInstruction::nextInstruction, and RexxInstructionCallBase::target.
operator delete() [1/2]
void RexxInstructionCall::operator delete (void *) inline
Definition at line 78 of file CallInstruction.hpp.
operator delete() [2/2]
void RexxInstructionCall::operator delete (void * , void *) inline
Definition at line 79 of file CallInstruction.hpp.
operator new()
void* RexxInstructionCall::operator new (size_t size, void * ptr) inline
Definition at line 77 of file CallInstruction.hpp.
resolve()
void RexxInstructionCall::resolve (RexxDirectory * labels) virtual
Reimplemented from RexxInstructionCallBase.
Definition at line 150 of file CallInstruction.cpp.
References RexxDirectory::at(), RexxInstructionCallBase::builtinIndex, call_builtin, call_dynamic, call_external, call_internal, call_nointernal, RexxInstruction::instructionFlags, RexxInstructionCallBase::name, NO_BUILTIN, OREF_NULL, OrefSet, and RexxInstructionCallBase::target.
trap()
void RexxInstructionCall::trap (RexxActivation * context, RexxDirectory * conditionObj) virtual
Reimplemented from RexxInstructionCallBase.
Definition at line 322 of file CallInstruction.cpp.
References RexxInstructionCallBase::builtinIndex, RexxSource::builtinTable, call_builtin, call_external, call_internal, call_type_mask, RexxInstructionCallBase::condition, RexxActivation::externalCall(), RexxActivation::getStack(), RexxInstruction::instructionFlags, RexxActivation::internalCallTrap(), RexxInstructionCallBase::name, RexxInstructionCallBase::target, RexxActivation::trapDelay(), and RexxActivation::trapUndelay().
Member Data Documentation
arguments
RexxObject* RexxInstructionCall::arguments[1] protected
Definition at line 94 of file CallInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxInstructionCall().
The documentation for this class was generated from the following files:
CallInstruction.hpp
CallInstruction.cpp