executor.master: BaseSortComparator Class Reference
BaseSortComparator Class Reference
#include <ArrayClass.hpp>
Public Member Functions
BaseSortComparator ()
virtual wholenumber_t compare (RexxObject *first, RexxObject *second)
Detailed Description
Definition at line 84 of file ArrayClass.hpp.
Constructor & Destructor Documentation
BaseSortComparator()
BaseSortComparator::BaseSortComparator () inline
Definition at line 86 of file ArrayClass.hpp.
Member Function Documentation
compare()
wholenumber_t BaseSortComparator::compare (RexxObject * first, RexxObject * second) virtual
Reimplemented in WithSortComparator.
Definition at line 2834 of file ArrayClass.cpp.
References RexxObject::compareTo().
Referenced by RexxArray::find(), RexxArray::merge(), and RexxArray::mergeSort().
The documentation for this class was generated from the following files:
ArrayClass.hpp
ArrayClass.cpp