executor.master: MemoryStats Class Reference
MemoryStats Class Reference
#include <MemoryStats.hpp>
Public Member Functions
MemoryStats ()
void logObject (RexxObject *obj)
void printSavedImageStats ()
void printMemoryStats ()
void clear ()
Public Attributes
SegmentStats normalStats
SegmentStats largeStats
ObjectStats objectStats [T_Last_Class_Type+1]
Detailed Description
Definition at line 97 of file MemoryStats.hpp.
Constructor & Destructor Documentation
MemoryStats()
MemoryStats::MemoryStats () inline
Definition at line 99 of file MemoryStats.hpp.
Member Function Documentation
clear()
void MemoryStats::clear ()
Definition at line 149 of file MemoryStats.cpp.
References ObjectStats::clear(), SegmentStats::clear(), largeStats, normalStats, objectStats, and T_Last_Class_Type.
Referenced by RexxMemory::dumpImageStats(), and RexxMemory::saveImage().
logObject()
void MemoryStats::logObject (RexxObject * obj)
Definition at line 164 of file MemoryStats.cpp.
References RexxInternalObject::getObjectTypeNumber(), ObjectStats::logObject(), and objectStats.
Referenced by RexxMemory::logObjectStats(), and SegmentStats::recordObject().
printMemoryStats()
void MemoryStats::printMemoryStats ()
Definition at line 105 of file MemoryStats.cpp.
References largeStats, normalStats, objectStats, SegmentStats::printStats(), ObjectStats::printStats(), and T_Last_Class_Type.
Referenced by RexxMemory::dumpImageStats().
printSavedImageStats()
void MemoryStats::printSavedImageStats ()
Definition at line 90 of file MemoryStats.cpp.
References objectStats, ObjectStats::printStats(), and T_Last_Class_Type.
Referenced by RexxMemory::saveImage().
Member Data Documentation
largeStats
SegmentStats MemoryStats::largeStats
Definition at line 109 of file MemoryStats.hpp.
Referenced by clear(), RexxMemory::dumpImageStats(), and printMemoryStats().
normalStats
SegmentStats MemoryStats::normalStats
Definition at line 108 of file MemoryStats.hpp.
Referenced by clear(), RexxMemory::dumpImageStats(), and printMemoryStats().
objectStats
ObjectStats MemoryStats::objectStats[T_Last_Class_Type+1]
Definition at line 111 of file MemoryStats.hpp.
Referenced by clear(), logObject(), printMemoryStats(), and printSavedImageStats().
The documentation for this class was generated from the following files:
MemoryStats.hpp
MemoryStats.cpp