executor.master: RexxInstructionForward Class Reference
RexxInstructionForward Class Reference
#include <ForwardInstruction.hpp>
Public Member Functions
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxInstructionForward (void)
RexxInstructionForward (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
void execute (RexxActivation *, RexxExpressionStack *)
Public Member Functions inherited from RexxInstruction
void * operator new (size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *)
void operator delete (void *, void *)
RexxInstruction (RexxClause *clause, int type)
RexxInstruction (RESTORETYPE restoreType)
RexxInstruction ()
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
const SourceLocation & getLocation ()
void setLocation (SourceLocation &l)
void setNext (RexxInstruction *next)
void setStart (size_t line, size_t off)
void setEnd (size_t line, size_t off)
void setType (size_t type)
size_t getType ()
bool isType (size_t type)
size_t getLineNumber ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxText * makeText ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxText * textValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Public Attributes
RexxObject * target
RexxObject * message
RexxObject * superClass
RexxObject * arguments
RexxArray * array
RexxObject * namedArgumentsExpression
RexxArray * namedArgumentsArray
Public Attributes inherited from RexxInstruction
uint16_t instructionType
uint16_t instructionFlags
SourceLocation instructionLocation
RexxInstruction * nextInstruction
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 51 of file ForwardInstruction.hpp.
Constructor & Destructor Documentation
RexxInstructionForward() [1/2]
RexxInstructionForward::RexxInstructionForward (void) inline
Definition at line 57 of file ForwardInstruction.hpp.
RexxInstructionForward() [2/2]
RexxInstructionForward::RexxInstructionForward (RESTORETYPE restoreType) inline
Definition at line 58 of file ForwardInstruction.hpp.
Member Function Documentation
execute()
void RexxInstructionForward::execute (RexxActivation * context, RexxExpressionStack * stack) virtual
Reimplemented from RexxInstruction.
Definition at line 103 of file ForwardInstruction.cpp.
References RexxArray::append(), RexxDirectory::appendAllIndexesItemsTo(), arguments, array, RexxArray::data(), RexxActivation::dropLocalVariable(), Error_Execution_forward, Error_Execution_forward_arguments, Error_Execution_user_defined, RexxInternalObject::evaluate(), RexxActivation::forward(), forward_continue, RexxArray::get(), RexxArray::getDimension(), RexxActivation::getMethodArgumentCount(), RexxActivation::getMethodArgumentList(), RexxActivation::getMethodNamedArgumentCount(), RexxActivation::inMethod(), RexxInstruction::instructionFlags, message, namedArgumentsArray, namedArgumentsExpression, new_array(), OREF_NULL, RexxActivation::pauseInstruction(), RexxExpressionStack::replace(), reportException(), REQUEST_ARRAY(), REQUEST_STRING(), RexxObject::requestDirectory(), RexxActivation::setLocalVariable(), RexxArray::size(), superClass, target, TheNilObject, RexxExpressionStack::toss(), RexxActivation::traceInstruction(), RexxActivation::traceResult(), RexxString::upper(), and VARIABLE_RESULT.
flatten()
void RexxInstructionForward::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 84 of file ForwardInstruction.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
live()
void RexxInstructionForward::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 53 of file ForwardInstruction.cpp.
References arguments, array, memory_mark, message, namedArgumentsArray, namedArgumentsExpression, RexxInstruction::nextInstruction, superClass, and target.
liveGeneral()
void RexxInstructionForward::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 68 of file ForwardInstruction.cpp.
References arguments, array, memory_mark_general, message, namedArgumentsArray, namedArgumentsExpression, RexxInstruction::nextInstruction, superClass, and target.
operator delete() [1/2]
void RexxInstructionForward::operator delete (void *) inline
Definition at line 54 of file ForwardInstruction.hpp.
operator delete() [2/2]
void RexxInstructionForward::operator delete (void * , void *) inline
Definition at line 55 of file ForwardInstruction.hpp.
operator new()
void* RexxInstructionForward::operator new (size_t size, void * ptr) inline
Definition at line 53 of file ForwardInstruction.hpp.
Member Data Documentation
arguments
RexxObject* RexxInstructionForward::arguments
Definition at line 67 of file ForwardInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxSource::RexxInstructionForwardCreate().
array
RexxArray* RexxInstructionForward::array
Definition at line 68 of file ForwardInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxSource::RexxInstructionForwardCreate().
message
RexxObject* RexxInstructionForward::message
Definition at line 65 of file ForwardInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxSource::RexxInstructionForwardCreate().
namedArgumentsArray
RexxArray* RexxInstructionForward::namedArgumentsArray
Definition at line 70 of file ForwardInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxSource::RexxInstructionForwardCreate().
namedArgumentsExpression
RexxObject* RexxInstructionForward::namedArgumentsExpression
Definition at line 69 of file ForwardInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxSource::RexxInstructionForwardCreate().
superClass
RexxObject* RexxInstructionForward::superClass
Definition at line 66 of file ForwardInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxSource::RexxInstructionForwardCreate().
target
RexxObject* RexxInstructionForward::target
Definition at line 64 of file ForwardInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxSource::RexxInstructionForwardCreate().
The documentation for this class was generated from the following files:
ForwardInstruction.hpp
ForwardInstruction.cpp