executor.master: RexxInstructionDo Class Reference
RexxInstructionDo Class Reference
#include <DoInstruction.hpp>
Public Member Functions
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxInstructionDo (void)
RexxInstructionDo (RESTORETYPE restoreType)
void matchEnd (RexxInstructionEnd *, RexxSource *)
bool isLabel (RexxString *name)
RexxString * getLabel ()
bool isLoop ()
void terminate (RexxActivation *, RexxDoBlock *)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
void execute (RexxActivation *, RexxExpressionStack *)
void controlSetup (RexxActivation *, RexxExpressionStack *, RexxDoBlock *)
bool checkOver (RexxActivation *, RexxExpressionStack *, RexxDoBlock *)
bool checkControl (RexxActivation *, RexxExpressionStack *, RexxDoBlock *, bool)
void reExecute (RexxActivation *, RexxExpressionStack *, RexxDoBlock *)
bool whileCondition (RexxActivation *, RexxExpressionStack *)
bool untilCondition (RexxActivation *, RexxExpressionStack *)
RexxInstruction * getEnd ()
void matchLabel (RexxInstructionEnd *end, RexxSource *source)
Public Member Functions inherited from RexxBlockInstruction
RexxBlockInstruction ()
RexxBlockInstruction (RESTORETYPE restoreType)
Public Member Functions inherited from RexxInstruction
void * operator new (size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *)
void operator delete (void *, void *)
RexxInstruction (RexxClause *clause, int type)
RexxInstruction (RESTORETYPE restoreType)
RexxInstruction ()
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
const SourceLocation & getLocation ()
void setLocation (SourceLocation &l)
void setNext (RexxInstruction *next)
void setStart (size_t line, sizeB_t off)
void setEnd (size_t line, sizeB_t off)
void setType (size_t type)
size_t getType ()
bool isType (size_t type)
size_t getLineNumber ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Public Attributes
RexxObject * initial
RexxObject * to
RexxObject * by
RexxVariableBase * control
RexxString * label
RexxObject * conditional
RexxInstruction * end
RexxObject * forcount
uint8_t type
uint8_t expressions [3]
Public Attributes inherited from RexxInstruction
uint16_t instructionType
uint16_t instructionFlags
SourceLocation instructionLocation
RexxInstruction * nextInstruction
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 67 of file DoInstruction.hpp.
Constructor & Destructor Documentation
RexxInstructionDo() [1/2]
RexxInstructionDo::RexxInstructionDo (void) inline
Definition at line 76 of file DoInstruction.hpp.
RexxInstructionDo() [2/2]
RexxInstructionDo::RexxInstructionDo (RESTORETYPE restoreType) inline
Definition at line 77 of file DoInstruction.hpp.
Member Function Documentation
checkControl()
bool RexxInstructionDo::checkControl (RexxActivation * context, RexxExpressionStack * stack, RexxDoBlock * doblock, bool increment)
Definition at line 608 of file DoInstruction.cpp.
References callOperatorMethod(), control, forcount, RexxDoBlock::getBy(), RexxDoBlock::getCompare(), RexxDoBlock::getTo(), RexxInternalObject::getValue(), OPERATOR_PLUS, OREF_NULL, RexxVariableBase::set(), RexxDoBlock::testFor(), TheTrueObject, to, and RexxActivation::traceResult().
Referenced by execute(), and reExecute().
checkOver()
bool RexxInstructionDo::checkOver (RexxActivation * context, RexxExpressionStack * stack, RexxDoBlock * doblock)
Definition at line 575 of file DoInstruction.cpp.
References RexxVariableBase::assign(), control, RexxArray::get(), RexxDoBlock::getFor(), RexxDoBlock::getTo(), OREF_NULL, RexxDoBlock::setFor(), RexxArray::size(), TheNilObject, and RexxActivation::traceResult().
Referenced by execute(), and reExecute().
controlSetup()
void RexxInstructionDo::controlSetup (RexxActivation * context, RexxExpressionStack * stack, RexxDoBlock * doblock)
Definition at line 454 of file DoInstruction.cpp.
References RexxVariableBase::assign(), by, callOperatorMethod(), control, Numerics::DEFAULT_DIGITS, RexxActivation::digits(), Error_Invalid_whole_number_for, RexxInternalObject::evaluate(), EXP_BY, EXP_FOR, EXP_TO, expressions, forcount, RexxInternalObject::getValue(), initial, IntegerOne, RexxObject::integerValue(), IntegerZero, isOfClass, number_digits(), OPERATOR_GREATERTHAN, OPERATOR_LESSTHAN, OPERATOR_PLUS, OREF_NULL, reportException(), REQUEST_STRING(), RexxObject::requestNumber(), RexxDoBlock::setBy(), RexxDoBlock::setCompare(), RexxDoBlock::setFor(), RexxDoBlock::setTo(), TheNilObject, TheTrueObject, to, and RexxActivation::traceResult().
Referenced by execute().
execute()
void RexxInstructionDo::execute (RexxActivation * context, RexxExpressionStack * stack) virtual
Reimplemented from RexxInstruction.
Definition at line 210 of file DoInstruction.cpp.
References RexxActivation::addBlock(), callOperatorMethod(), checkControl(), checkOver(), RexxActivation::conditionalPauseInstruction(), CONTROLLED_DO, CONTROLLED_UNTIL, CONTROLLED_WHILE, controlSetup(), Numerics::DEFAULT_DIGITS, RexxActivation::digits(), DO_COUNT, DO_COUNT_UNTIL, DO_COUNT_WHILE, DO_FOREVER, DO_OVER, DO_OVER_UNTIL, DO_OVER_WHILE, DO_UNTIL, DO_WHILE, Error_Execution_noarray, Error_Invalid_whole_number_repeat, RexxInternalObject::evaluate(), forcount, RexxActivation::getIndent(), getLabel(), RexxInternalObject::getValue(), initial, isOfClass, RexxArray::makeArray(), RexxActivation::newDo(), number_digits(), OPERATOR_PLUS, OREF_NULL, RexxActivation::removeBlock(), reportException(), REQUEST_ARRAY(), REQUEST_STRING(), RexxObject::requestNumber(), RexxDoBlock::setFor(), RexxActivation::setNext(), RexxDoBlock::setTo(), SIMPLE_DO, terminate(), RexxDoBlock::testFor(), TheNilObject, RexxActivation::traceInstruction(), RexxActivation::traceResult(), type, and whileCondition().
flatten()
void RexxInstructionDo::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 177 of file DoInstruction.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
getEnd()
RexxInstruction* RexxInstructionDo::getEnd ()
getLabel()
RexxString * RexxInstructionDo::getLabel () virtual
Get the label for this block instruction.
Returns
The label for the loop. Returns OREF_NULL if there is no label.
Reimplemented from RexxBlockInstruction.
Definition at line 128 of file DoInstruction.cpp.
References label.
Referenced by execute(), matchEnd(), and matchLabel().
isLabel()
bool RexxInstructionDo::isLabel (RexxString * name) virtual
Check for a label match on a block instruction.
Parameters
name The target block name.
Returns
True if this is a name match, false otherwise.
Reimplemented from RexxBlockInstruction.
Definition at line 118 of file DoInstruction.cpp.
References label.
isLoop()
bool RexxInstructionDo::isLoop () virtual
Tests to see if this is a loop instruction.
Returns
True if this is a repetitive loop, false otherwise.
Reimplemented from RexxBlockInstruction.
Definition at line 138 of file DoInstruction.cpp.
References SIMPLE_DO, and type.
live()
void RexxInstructionDo::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 144 of file DoInstruction.cpp.
References by, conditional, control, end, forcount, initial, label, memory_mark, RexxInstruction::nextInstruction, and to.
liveGeneral()
void RexxInstructionDo::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 160 of file DoInstruction.cpp.
References by, conditional, control, end, forcount, initial, label, memory_mark_general, RexxInstruction::nextInstruction, and to.
matchEnd()
void RexxInstructionDo::matchEnd (RexxInstructionEnd * partner, RexxSource * source) virtual
Reimplemented from RexxBlockInstruction.
Definition at line 83 of file DoInstruction.cpp.
References DO_BLOCK, end, getLabel(), LABELED_DO_BLOCK, LOOP_BLOCK, matchLabel(), OREF_NULL, OrefSet, RexxInstructionEnd::setStyle(), SIMPLE_DO, and type.
matchLabel()
void RexxInstructionDo::matchLabel (RexxInstructionEnd * end, RexxSource * source)
Definition at line 57 of file DoInstruction.cpp.
References RexxSource::error(), Error_Unexpected_end_control, Error_Unexpected_end_nocontrol, getLabel(), RexxInstruction::getLineNumber(), RexxInstruction::getLocation(), RexxInstructionEnd::name, new_array(), new_integer(), and OREF_NULL.
Referenced by matchEnd().
operator delete() [1/2]
void RexxInstructionDo::operator delete (void *) inline
Definition at line 72 of file DoInstruction.hpp.
operator delete() [2/2]
void RexxInstructionDo::operator delete (void * , void *) inline
Definition at line 73 of file DoInstruction.hpp.
operator new()
void* RexxInstructionDo::operator new (size_t size, void * ptr) inline
Definition at line 71 of file DoInstruction.hpp.
reExecute()
void RexxInstructionDo::reExecute (RexxActivation * context, RexxExpressionStack * stack, RexxDoBlock * doblock)
Definition at line 650 of file DoInstruction.cpp.
References checkControl(), checkOver(), CONTROLLED_DO, CONTROLLED_UNTIL, CONTROLLED_WHILE, DO_COUNT, DO_COUNT_UNTIL, DO_COUNT_WHILE, DO_FOREVER, DO_OVER, DO_OVER_UNTIL, DO_OVER_WHILE, DO_UNTIL, DO_WHILE, end, RexxActivation::indent(), RexxInstruction::nextInstruction, RexxActivation::popBlock(), RexxActivation::removeBlock(), RexxActivation::setNext(), RexxDoBlock::testFor(), RexxActivation::traceInstruction(), type, RexxActivation::unindent(), untilCondition(), and whileCondition().
terminate()
void RexxInstructionDo::terminate (RexxActivation * context, RexxDoBlock * doblock) virtual
Reimplemented from RexxBlockInstruction.
Definition at line 197 of file DoInstruction.cpp.
References end, RexxDoBlock::getIndent(), RexxInstruction::nextInstruction, RexxActivation::setNext(), and RexxActivation::terminateBlock().
Referenced by execute().
untilCondition()
bool RexxInstructionDo::untilCondition (RexxActivation * context, RexxExpressionStack * stack)
Definition at line 768 of file DoInstruction.cpp.
References conditional, Error_Logical_value_until, RexxInternalObject::evaluate(), TheFalseObject, TheTrueObject, RexxActivation::traceResult(), and RexxObject::truthValue().
Referenced by reExecute().
whileCondition()
bool RexxInstructionDo::whileCondition (RexxActivation * context, RexxExpressionStack * stack)
Definition at line 795 of file DoInstruction.cpp.
References conditional, Error_Logical_value_while, RexxInternalObject::evaluate(), TheFalseObject, TheTrueObject, RexxActivation::traceResult(), and RexxObject::truthValue().
Referenced by execute(), and reExecute().
Member Data Documentation
by
RexxObject* RexxInstructionDo::by
Definition at line 100 of file DoInstruction.hpp.
Referenced by controlSetup(), RexxSource::createDoLoop(), live(), and liveGeneral().
conditional
RexxObject* RexxInstructionDo::conditional
Definition at line 103 of file DoInstruction.hpp.
Referenced by RexxSource::createDoLoop(), live(), liveGeneral(), untilCondition(), and whileCondition().
control
RexxVariableBase* RexxInstructionDo::control
Definition at line 101 of file DoInstruction.hpp.
Referenced by checkControl(), checkOver(), controlSetup(), RexxSource::createDoLoop(), live(), and liveGeneral().
end
RexxInstruction* RexxInstructionDo::end
Definition at line 104 of file DoInstruction.hpp.
Referenced by live(), liveGeneral(), matchEnd(), reExecute(), and terminate().
expressions
uint8_t RexxInstructionDo::expressions[3]
Definition at line 107 of file DoInstruction.hpp.
Referenced by controlSetup(), and RexxSource::createDoLoop().
forcount
RexxObject* RexxInstructionDo::forcount
Definition at line 105 of file DoInstruction.hpp.
Referenced by checkControl(), controlSetup(), RexxSource::createDoLoop(), execute(), live(), and liveGeneral().
initial
RexxObject* RexxInstructionDo::initial
Definition at line 98 of file DoInstruction.hpp.
Referenced by controlSetup(), RexxSource::createDoLoop(), execute(), live(), and liveGeneral().
label
RexxString* RexxInstructionDo::label
Definition at line 102 of file DoInstruction.hpp.
Referenced by RexxSource::createDoLoop(), getLabel(), isLabel(), live(), and liveGeneral().
to
RexxObject* RexxInstructionDo::to
Definition at line 99 of file DoInstruction.hpp.
Referenced by checkControl(), controlSetup(), RexxSource::createDoLoop(), live(), and liveGeneral().
type
uint8_t RexxInstructionDo::type
Definition at line 106 of file DoInstruction.hpp.
Referenced by RexxSource::createDoLoop(), execute(), isLoop(), matchEnd(), and reExecute().
The documentation for this class was generated from the following files:
DoInstruction.hpp
DoInstruction.cpp