executor.master: RexxActivationBase Class Reference
RexxActivationBase Class Reference abstract
#include <ObjectClass.hpp>
Public Member Functions
RexxActivationBase ()
RexxActivationBase (RESTORETYPE restoreType)
virtual RexxObject * dispatch ()
virtual size_t digits ()
virtual size_t fuzz ()
virtual bool form ()
virtual NumericSettings * getNumericSettings ()
virtual RexxActivation * getRexxContext ()
virtual RexxActivation * findRexxContext ()
virtual void setDigits (size_t)
virtual void setFuzz (size_t)
virtual void setForm (bool)
virtual bool trap (RexxString *, RexxDirectory *)
virtual void setObjNotify (RexxMessage *)
virtual void termination ()
virtual SecurityManager * getSecurityManager ()=0
virtual bool isForwarded ()
virtual bool isStackBase ()
virtual bool isRexxContext ()
virtual RexxObject * getReceiver ()
virtual PackageClass * getPackage ()
void setPreviousStackFrame (RexxActivationBase *p)
RexxActivationBase * getPreviousStackFrame ()
BaseExecutable * getExecutable ()
RexxObject * getExecutableObject ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxText * makeText ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxText * textValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual void live (size_t)
virtual void liveGeneral (int reason)
virtual void flatten (RexxEnvelope *)
virtual RexxObject * unflatten (RexxEnvelope *)
Protected Attributes
RexxActivationBase * previous
BaseExecutable * executable
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 619 of file ObjectClass.hpp.
Constructor & Destructor Documentation
RexxActivationBase() [1/2]
RexxActivationBase::RexxActivationBase () inline
Definition at line 621 of file ObjectClass.hpp.
RexxActivationBase() [2/2]
RexxActivationBase::RexxActivationBase (RESTORETYPE restoreType) inline
Definition at line 622 of file ObjectClass.hpp.
Member Function Documentation
digits()
virtual size_t RexxActivationBase::digits () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 624 of file ObjectClass.hpp.
References Numerics::DEFAULT_DIGITS.
Referenced by RexxNumberString::maxMin().
dispatch()
virtual RexxObject* RexxActivationBase::dispatch () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 623 of file ObjectClass.hpp.
Referenced by RexxActivity::runThread().
findRexxContext()
virtual RexxActivation* RexxActivationBase::findRexxContext () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 629 of file ObjectClass.hpp.
References OREF_NULL.
Referenced by RexxNativeActivation::findRexxContext(), and RexxActivity::updateFrameMarkers().
form()
virtual bool RexxActivationBase::form () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 626 of file ObjectClass.hpp.
References Numerics::DEFAULT_FORM.
fuzz()
virtual size_t RexxActivationBase::fuzz () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 625 of file ObjectClass.hpp.
References Numerics::DEFAULT_FUZZ.
Referenced by RexxNumberString::maxMin().
getExecutable()
BaseExecutable* RexxActivationBase::getExecutable () inline
Definition at line 645 of file ObjectClass.hpp.
References executable.
Referenced by GetCurrentMethod(), GetCurrentRoutine(), RexxContext::getExecutable(), RexxNativeActivation::getRexxContextExecutable(), RexxActivation::RexxActivation(), and RexxActivation::traceEntry().
getExecutableObject()
RexxObject* RexxActivationBase::getExecutableObject () inline
Definition at line 646 of file ObjectClass.hpp.
References executable.
Referenced by RexxActivation::createStackFrame(), RexxNativeActivation::createStackFrame(), RexxActivationFrame::method(), and NativeActivationFrame::method().
getNumericSettings()
virtual NumericSettings* RexxActivationBase::getNumericSettings () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 627 of file ObjectClass.hpp.
References Numerics::getDefaultSettings().
Referenced by RexxActivity::updateFrameMarkers().
getPackage()
virtual PackageClass* RexxActivationBase::getPackage () inline virtual
Reimplemented in RexxActivation.
Definition at line 641 of file ObjectClass.hpp.
References OREF_NULL.
Referenced by RexxObject::checkPackage().
getPreviousStackFrame()
RexxActivationBase* RexxActivationBase::getPreviousStackFrame () inline
Definition at line 644 of file ObjectClass.hpp.
References previous.
Referenced by RexxNativeActivation::accessCallerContext(), RexxNativeActivation::checkConditions(), RexxActivation::getStreams(), RexxActivation::senderActivation(), and RexxActivation::trap().
getReceiver()
virtual RexxObject* RexxActivationBase::getReceiver () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 640 of file ObjectClass.hpp.
References OREF_NULL.
Referenced by RexxObject::checkPrivate(), and RexxObject::decodeMessageName().
getRexxContext()
virtual RexxActivation* RexxActivationBase::getRexxContext () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 628 of file ObjectClass.hpp.
References OREF_NULL.
getSecurityManager()
virtual SecurityManager* RexxActivationBase::getSecurityManager () pure virtual
Implemented in RexxActivation, and RexxNativeActivation.
Referenced by RexxActivity::getEffectiveSecurityManager().
isForwarded()
virtual bool RexxActivationBase::isForwarded () inline virtual
Reimplemented in RexxActivation.
Definition at line 637 of file ObjectClass.hpp.
Referenced by RexxActivation::trap().
isRexxContext()
virtual bool RexxActivationBase::isRexxContext () inline virtual
Reimplemented in RexxActivation.
Definition at line 639 of file ObjectClass.hpp.
Referenced by RexxActivation::getStreams().
isStackBase()
virtual bool RexxActivationBase::isStackBase () inline virtual
Reimplemented in RexxNativeActivation.
Definition at line 638 of file ObjectClass.hpp.
Referenced by RexxActivity::error(), RexxActivity::popStackFrame(), RexxActivity::pushStackFrame(), RexxActivity::raiseCondition(), RexxActivity::raisePropagate(), and RexxActivity::unwindStackFrame().
setDigits()
virtual void RexxActivationBase::setDigits (size_t) inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 630 of file ObjectClass.hpp.
setForm()
virtual void RexxActivationBase::setForm (bool) inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 632 of file ObjectClass.hpp.
setFuzz()
virtual void RexxActivationBase::setFuzz (size_t) inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 631 of file ObjectClass.hpp.
Referenced by RexxNumberString::maxMin().
setObjNotify()
virtual void RexxActivationBase::setObjNotify (RexxMessage *) inline virtual
Reimplemented in RexxActivation.
Definition at line 634 of file ObjectClass.hpp.
Referenced by RexxMessage::send(), and RexxMessage::sendNotification().
setPreviousStackFrame()
void RexxActivationBase::setPreviousStackFrame (RexxActivationBase * p) inline
Definition at line 643 of file ObjectClass.hpp.
References previous.
Referenced by RexxActivity::pushStackFrame().
termination()
virtual void RexxActivationBase::termination () inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 635 of file ObjectClass.hpp.
Referenced by RexxActivity::cleanupStackFrame(), RexxActivity::error(), and RexxActivity::unwindToFrame().
trap()
virtual bool RexxActivationBase::trap (RexxString * , RexxDirectory *) inline virtual
Reimplemented in RexxActivation, and RexxNativeActivation.
Definition at line 633 of file ObjectClass.hpp.
Referenced by RexxNativeActivation::checkConditions(), RexxActivity::raisePropagate(), and RexxActivation::trap().
Member Data Documentation
executable
BaseExecutable* RexxActivationBase::executable protected
Definition at line 650 of file ObjectClass.hpp.
Referenced by RexxNativeActivation::callNativeRoutine(), RexxNativeActivation::callRegisteredRoutine(), RexxNativeActivation::cself(), RexxNativeActivation::dispatch(), RexxNativeActivation::findClass(), RexxActivation::getEffectivePackageObject(), RexxActivation::getEffectiveSourceObject(), getExecutable(), getExecutableObject(), RexxActivation::getPackage(), RexxNativeActivation::getScope(), RexxNativeActivation::getSourceObject(), RexxNativeActivation::getSuper(), RexxNativeActivation::guardOn(), RexxActivation::live(), RexxNativeActivation::live(), RexxActivation::liveGeneral(), RexxNativeActivation::liveGeneral(), RexxNativeActivation::methodVariables(), RexxActivation::RexxActivation(), and RexxNativeActivation::run().
previous
RexxActivationBase* RexxActivationBase::previous protected
Definition at line 649 of file ObjectClass.hpp.
Referenced by RexxNativeActivation::findRexxContext(), getPreviousStackFrame(), RexxActivation::live(), RexxNativeActivation::live(), RexxActivation::liveGeneral(), RexxNativeActivation::liveGeneral(), and setPreviousStackFrame().
The documentation for this class was generated from the following file:
ObjectClass.hpp