executor.master: InternalActivationFrame Class Reference
InternalActivationFrame Class Reference
#include <ActivationFrame.hpp>
Public Member Functions
InternalActivationFrame (RexxActivity *a, RexxString *n, RexxObject *t, RexxMethod *m, RexxObject **args, size_t c, size_t nc)
virtual RexxString * messageName () override
virtual RexxMethod * method () override
virtual StackFrameClass * createStackFrame () override
virtual RexxSource * getSource () override
Public Member Functions inherited from ActivationFrame
ActivationFrame (RexxActivity *a)
~ActivationFrame ()
Protected Attributes
RexxString * name
RexxMethod * frameMethod
RexxObject * target
RexxObject ** argPtr
size_t count
size_t named_count
Protected Attributes inherited from ActivationFrame
ActivationFrame * next
RexxActivity * activity
Detailed Description
Definition at line 119 of file ActivationFrame.hpp.
Constructor & Destructor Documentation
InternalActivationFrame()
InternalActivationFrame::InternalActivationFrame (RexxActivity * a, RexxString * n, RexxObject * t, RexxMethod * m, RexxObject ** args, size_t c, size_t nc) inline
Definition at line 122 of file ActivationFrame.hpp.
Member Function Documentation
createStackFrame()
StackFrameClass * InternalActivationFrame::createStackFrame () override virtual
Implements ActivationFrame.
Definition at line 109 of file ActivationFrame.cpp.
References ActivationFrame::activity, argPtr, RexxActivity::buildMessage(), count, FRAME_METHOD, frameMethod, RexxClass::getId(), RexxMethod::getScope(), Message_Translations_compiled_method_invocation, name, new_array(), RexxObject::requestString(), SIZE_MAX, target, and TheNilObject.
getSource()
RexxSource * InternalActivationFrame::getSource () override virtual
Implements ActivationFrame.
Definition at line 130 of file ActivationFrame.cpp.
References OREF_NULL.
messageName()
RexxString * InternalActivationFrame::messageName () override virtual
Implements ActivationFrame.
Definition at line 99 of file ActivationFrame.cpp.
References name.
method()
RexxMethod * InternalActivationFrame::method () override virtual
Implements ActivationFrame.
Definition at line 104 of file ActivationFrame.cpp.
References frameMethod.
Member Data Documentation
argPtr
RexxObject** InternalActivationFrame::argPtr protected
Definition at line 137 of file ActivationFrame.hpp.
Referenced by createStackFrame().
count
size_t InternalActivationFrame::count protected
Definition at line 138 of file ActivationFrame.hpp.
Referenced by createStackFrame().
frameMethod
RexxMethod* InternalActivationFrame::frameMethod protected
Definition at line 135 of file ActivationFrame.hpp.
Referenced by createStackFrame(), and method().
name
RexxString* InternalActivationFrame::name protected
Definition at line 134 of file ActivationFrame.hpp.
Referenced by createStackFrame(), and messageName().
named_count
size_t InternalActivationFrame::named_count protected
Definition at line 139 of file ActivationFrame.hpp.
target
RexxObject* InternalActivationFrame::target protected
Definition at line 136 of file ActivationFrame.hpp.
Referenced by createStackFrame().
The documentation for this class was generated from the following files:
ActivationFrame.hpp
ActivationFrame.cpp