executor.master: StemManager Class Reference
StemManager Class Reference
#include <rxsock.h>
Public Member Functions
StemManager (RexxCallContext *c)
~StemManager ()
bool resolveStem (RexxObjectPtr source)
void setValue (const char *name, RexxObjectPtr value)
void setValue (size_t index, RexxObjectPtr value)
RexxObjectPtr getValue (const char *name)
RexxObjectPtr getValue (size_t index)
Protected Attributes
RexxCallContext * context
RexxStemObject stem
char * prefix
Detailed Description
Definition at line 114 of file rxsock.h.
Constructor & Destructor Documentation
StemManager()
StemManager::StemManager (RexxCallContext * c) inline
Definition at line 117 of file rxsock.h.
~StemManager()
StemManager::~StemManager () inline
Definition at line 118 of file rxsock.h.
References prefix.
Member Function Documentation
getValue() [1/2]
RexxObjectPtr StemManager::getValue (const char * name) inline
Retrieve a value from an argument stem.
Parameters
name The argument stem name.
Returns
The retrieved object, if any.
Definition at line 232 of file rxsock.h.
References context, prefix, and stem.
Referenced by getStemElement(), and stemToIntArray().
getValue() [2/2]
RexxObjectPtr StemManager::getValue (size_t index) inline
Definition at line 246 of file rxsock.h.
References context, prefix, and stem.
resolveStem()
bool StemManager::resolveStem (RexxObjectPtr source) inline
Resolve the stem object that was passed as an argument.
Parameters
source The source argument object.
Returns
true if the stem could be resolved, false for any errors resolving the stem object.
Definition at line 134 of file rxsock.h.
References context, prefix, and stem.
Referenced by intArrayToStem(), RexxRoutine2(), RexxRoutine3(), RexxRoutine4(), RexxRoutine5(), and stemToIntArray().
setValue() [1/2]
void StemManager::setValue (const char * name, RexxObjectPtr value) inline
Set a value in the argument stem.
Parameters
name The name to set.
value
Definition at line 191 of file rxsock.h.
References context, prefix, and stem.
Referenced by hostEntToStem(), intArrayToStem(), and sockAddrToStem().
setValue() [2/2]
void StemManager::setValue (size_t index, RexxObjectPtr value) inline
Set a value in the argument stem.
Parameters
index The index to set.
value
Definition at line 211 of file rxsock.h.
References context, prefix, and stem.
Member Data Documentation
context
RexxCallContext* StemManager::context protected
Definition at line 262 of file rxsock.h.
Referenced by getValue(), resolveStem(), and setValue().
prefix
char* StemManager::prefix protected
Definition at line 264 of file rxsock.h.
Referenced by getValue(), resolveStem(), setValue(), and ~StemManager().
stem
RexxStemObject StemManager::stem protected
Definition at line 263 of file rxsock.h.
Referenced by getValue(), resolveStem(), and setValue().
The documentation for this class was generated from the following file:
rxsock.h