executor.master: RexxInstructionParse Class Reference
RexxInstructionParse Class Reference
#include <ParseInstruction.hpp>
Public Member Functions
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxInstructionParse (RexxObject *, unsigned short, size_t, size_t, RexxQueue *)
RexxInstructionParse (RESTORETYPE restoreType)
void execute (RexxActivation *, RexxExpressionStack *)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
Public Member Functions inherited from RexxInstruction
void * operator new (size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *)
void operator delete (void *, void *)
RexxInstruction (RexxClause *clause, int type)
RexxInstruction (RESTORETYPE restoreType)
RexxInstruction ()
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
const SourceLocation & getLocation ()
void setLocation (SourceLocation &l)
void setNext (RexxInstruction *next)
void setStart (size_t line, sizeB_t off)
void setEnd (size_t line, sizeB_t off)
void setType (size_t type)
size_t getType ()
bool isType (size_t type)
size_t getLineNumber ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Public Attributes
int stringSource
RexxObject * expression
size_t trigger_count
RexxTrigger * triggers [1]
Public Attributes inherited from RexxInstruction
uint16_t instructionType
uint16_t instructionFlags
SourceLocation instructionLocation
RexxInstruction * nextInstruction
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 57 of file ParseInstruction.hpp.
Constructor & Destructor Documentation
RexxInstructionParse() [1/2]
RexxInstructionParse::RexxInstructionParse (RexxObject * _expression, unsigned short string_source, size_t flags, size_t templateCount, RexxQueue * parse_template)
Definition at line 58 of file ParseInstruction.cpp.
References expression, RexxInstruction::instructionFlags, OrefSet, RexxQueue::pop(), stringSource, trigger_count, and triggers.
RexxInstructionParse() [2/2]
RexxInstructionParse::RexxInstructionParse (RESTORETYPE restoreType) inline
Definition at line 64 of file ParseInstruction.hpp.
Member Function Documentation
execute()
void RexxInstructionParse::execute (RexxActivation * context, RexxExpressionStack * stack) virtual
Reimplemented from RexxInstruction.
Definition at line 80 of file ParseInstruction.cpp.
References ActivityManager::currentActivity, RexxInternalObject::evaluate(), expression, RexxActivation::getMethodArgumentCount(), RexxActivation::getMethodArgumentList(), Interpreter::getVersionNumber(), RexxTarget::init(), RexxInstruction::instructionFlags, RexxActivity::lineIn(), RexxTarget::next(), OREF_NULL, RexxTrigger::parse(), parse_translate, RexxActivation::pauseInstruction(), RexxActivity::pullInput(), RexxExpressionStack::push(), RexxActivation::sourceString(), stringSource, SUBKEY_ARG, SUBKEY_LINEIN, SUBKEY_PULL, SUBKEY_SOURCE, SUBKEY_VALUE, SUBKEY_VAR, SUBKEY_VERSION, RexxActivation::traceInstruction(), trigger_count, and triggers.
flatten()
void RexxInstructionParse::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 206 of file ParseInstruction.cpp.
References cleanUpFlatten, flatten_reference, setUpFlatten, and trigger_count.
live()
void RexxInstructionParse::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 173 of file ParseInstruction.cpp.
References expression, memory_mark, RexxInstruction::nextInstruction, trigger_count, and triggers.
liveGeneral()
void RexxInstructionParse::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 189 of file ParseInstruction.cpp.
References expression, memory_mark_general, RexxInstruction::nextInstruction, trigger_count, and triggers.
operator delete() [1/2]
void RexxInstructionParse::operator delete (void *) inline
Definition at line 60 of file ParseInstruction.hpp.
operator delete() [2/2]
void RexxInstructionParse::operator delete (void * , void *) inline
Definition at line 61 of file ParseInstruction.hpp.
operator new()
void* RexxInstructionParse::operator new (size_t size, void * ptr) inline
Definition at line 59 of file ParseInstruction.hpp.
Member Data Documentation
expression
RexxObject* RexxInstructionParse::expression
Definition at line 71 of file ParseInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxInstructionParse().
stringSource
int RexxInstructionParse::stringSource
Definition at line 70 of file ParseInstruction.hpp.
Referenced by execute(), and RexxInstructionParse().
trigger_count
size_t RexxInstructionParse::trigger_count
Definition at line 72 of file ParseInstruction.hpp.
Referenced by execute(), flatten(), live(), liveGeneral(), and RexxInstructionParse().
triggers
RexxTrigger* RexxInstructionParse::triggers[1]
Definition at line 73 of file ParseInstruction.hpp.
Referenced by execute(), live(), liveGeneral(), and RexxInstructionParse().
The documentation for this class was generated from the following files:
ParseInstruction.hpp
ParseInstruction.cpp