executor.master: RexxList Class Reference
RexxList Class Reference
#include <ListClass.hpp>
Public Member Functions
void * operator new (size_t)
void * operator new (size_t size, void *objectPtr)
RexxList (RESTORETYPE restoreType)
RexxList ()
void init ()
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
RexxObject * copy ()
RexxArray * makeArray ()
RexxArray * allItems ()
RexxArray * allIndexes ()
RexxArray * requestArray ()
RexxObject * value (RexxObject *)
RexxObject * remove (RexxObject *)
RexxObject * primitiveRemove (LISTENTRY *)
size_t firstIndex ()
size_t lastIndex ()
size_t nextIndex (size_t i)
size_t previousIndex (size_t i)
RexxObject * getValue (size_t i)
RexxObject * firstRexx ()
RexxObject * lastRexx ()
RexxObject * next (RexxObject *)
RexxObject * previous (RexxObject *)
RexxObject * hasIndex (RexxObject *)
RexxSupplier * supplier ()
RexxObject * itemsRexx ()
size_t items ()
RexxObject * insert (RexxObject *, RexxObject *)
RexxObject * put (RexxObject *, RexxObject *)
RexxObject * section (RexxObject *, RexxObject *)
RexxObject * sectionSubclass (LISTENTRY *, size_t)
RexxObject * firstItem ()
RexxObject * lastItem ()
RexxObject * insertRexx (RexxObject *, RexxObject *)
void partitionBuffer (size_t, size_t)
RexxArray * makeArrayIndices ()
size_t getFree ()
RexxObject * add (RexxObject *, RexxObject *)
RexxObject * removeFirst ()
RexxObject * removeLast ()
RexxObject * removeFirstItem ()
RexxObject * removeLastItem ()
RexxObject * removeIndex (size_t i)
LISTENTRY * getEntry (RexxObject *, RexxObject *)
LISTENTRY * getEntry (size_t)
RexxObject * indexOfValue (RexxObject *)
RexxObject * empty ()
RexxObject * isEmpty ()
RexxObject * index (RexxObject *)
RexxObject * hasItem (RexxObject *)
RexxObject * removeItem (RexxObject *)
RexxObject * removeObject (RexxObject *)
void addLast (RexxObject *value)
void addFirst (RexxObject *value)
size_t getSize ()
RexxObject * append (RexxObject *)
RexxArray * weakReferenceArray ()
RexxList * newRexx (RexxObject **, size_t, size_t)
RexxList * classOf (RexxObject **, size_t, size_t)
Public Member Functions inherited from RexxObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *, void *)
void operator delete (void *)
void operator delete (void *, RexxClass *)
void operator delete (void *, RexxClass *, RexxObject **, size_t)
RexxObject * newRexx (RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxObject * newObject ()
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
virtual RexxObject * defMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
virtual RexxString * defaultName ()
virtual RexxObject * unknown (RexxString *msg, RexxArray *args, RexxDirectory *named_args)
virtual RexxInteger * hasMethod (RexxString *msg)
bool hasUninitMethod ()
RexxObject * init ()
void uninit ()
HashCode hash ()
bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
RexxNumberString * numberString ()
RexxInteger * integerValue (size_t)
RexxString * makeString ()
RexxText * makeText ()
void copyIntoTail (RexxCompoundTail *buffer)
RexxString * stringValue ()
RexxText * textValue ()
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxText * requestText ()
RexxInteger * requestInteger (size_t)
bool requestNumber (wholenumber_t &, size_t)
bool requestUnsignedNumber (stringsize_t &, size_t)
RexxArray * requestArray ()
RexxDirectory * requestDirectory ()
RexxString * requiredString (RexxString *kind, size_t)
RexxString * requiredString (RexxString *kind, const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (RexxString *kind, size_t, size_t)
wholenumber_t requiredNumber (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredPositive (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredNonNegative (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
bool isEqual (RexxObject *)
bool isInstanceOf (RexxClass *)
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
RexxMethod * instanceMethod (RexxString *)
RexxSupplier * instanceMethods (RexxClass *)
RexxMethod * instanceMethodRexx (RexxString *)
RexxSupplier * instanceMethodsRexx (RexxClass *)
RexxObject * dynamicTargetRexx (RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
RexxMessage * start (RexxObject **, size_t, size_t)
RexxMessage * startWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxObject * send (RexxObject **, size_t, size_t)
RexxObject * sendWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxMessage * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxString * oref ()
RexxObject * pmdict ()
RexxObject * run (RexxObject **, size_t, size_t)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, ProtectedObject &, bool processUnknown=true, bool dynamicTarget=true)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, RexxObject *, ProtectedObject &, bool processUnknown=true, bool dynamicTarget=true)
RexxMethod * checkPrivate (RexxMethod *, RexxErrorCodes &)
RexxMethod * checkPackage (RexxMethod *, RexxErrorCodes &)
void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
void processProtectedMethod (RexxString *, RexxMethod *, RexxObject **, size_t, size_t, ProtectedObject &)
void sendMessage (RexxString *, RexxArray *, RexxDirectory *, ProtectedObject &)
void sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount, ProtectedObject &result)
void sendMessage (RexxString *message, ProtectedObject &result)
void sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
void sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxArray *, RexxDirectory *=OREF_NULL)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount)
RexxObject * sendMessage (RexxString *message)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * defMethods (RexxDirectory *)
void setObjectVariable (RexxString *, RexxObject *, RexxObject *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxObject *)
void addObjectVariables (RexxVariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxObject * superScope (RexxObject *)
RexxMethod * superMethod (RexxString *, RexxObject *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
const char * idString ()
RexxString * id ()
RexxMethod * methodLookup (RexxString *name)
RexxVariableDictionary * getObjectVariables (RexxObject *)
void guardOn (RexxActivity *activity, RexxObject *scope)
void guardOff (RexxActivity *activity, RexxObject *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
RexxObject * unknownRexx (RexxString *, RexxArray *, RexxObject **, size_t)
RexxObject * hasMethodRexx (RexxString *)
void * getCSelf ()
void * getCSelf (RexxObject *scope)
bool equalValue (RexxObject *other)
virtual wholenumber_t compareTo (RexxObject *)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) RexxVariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, RexxString *&messageName, RexxObject *&startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
RexxListTable * table
size_t first
size_t last
size_t count
size_t size
size_t free
Friends
class RexxListTable
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 63 of file ListClass.hpp.
Constructor & Destructor Documentation
RexxList() [1/2]
RexxList::RexxList (RESTORETYPE restoreType) inline
Definition at line 68 of file ListClass.hpp.
RexxList() [2/2]
RexxList::RexxList () inline
Definition at line 69 of file ListClass.hpp.
Referenced by classOf(), newRexx(), and section().
Member Function Documentation
add()
RexxObject * RexxList::add (RexxObject * _value, RexxObject * _index)
Definition at line 381 of file ListClass.cpp.
References count, ENTRY_INDEX, ENTRY_POINTER, Error_Incorrect_method_index, first, getEntry(), getFree(), IntegerOne, last, LIST_END, new_integer(), listentry::next, OrefSet, listentry::previous, reportException(), table, TheNilObject, and listentry::value.
addFirst()
void RexxList::addFirst (RexxObject * value)
Definition at line 486 of file ListClass.cpp.
References count, ENTRY_POINTER, first, getFree(), last, LIST_END, listentry::next, OrefSet, listentry::previous, table, and listentry::value.
Referenced by RexxClass::addSubClass(), RexxQueue::push(), and RexxActivation::pushEnvironment().
addLast()
void RexxList::addLast (RexxObject * value)
Definition at line 455 of file ListClass.cpp.
References count, ENTRY_POINTER, first, getFree(), last, LIST_END, listentry::next, OrefSet, listentry::previous, table, and listentry::value.
Referenced by RexxSource::addReference(), classOf(), RexxVariableReference::list(), RexxActivation::mergeTraps(), RexxMessage::notify(), RexxQueue::ofRexx(), RexxActivation::processTraps(), RexxQueue::queue(), RexxVariableDictionary::reserve(), RexxMessage::result(), section(), RexxQueue::section(), and RexxActivation::trap().
allIndexes()
RexxArray * RexxList::allIndexes (void)
Return an array containing all elements contained in the list, in sorted order.
Returns
An array with the list elements.
Definition at line 938 of file ListClass.cpp.
References count, ENTRY_POINTER, first, new_array(), new_integer(), listentry::next, and RexxArray::put().
Referenced by RexxMemory::createImage().
allItems()
RexxArray * RexxList::allItems (void)
Return an array containing all elements contained in the list, in sorted order.
Returns
An array with the list elements.
Definition at line 888 of file ListClass.cpp.
References count, ENTRY_POINTER, first, new_array(), listentry::next, RexxArray::put(), and listentry::value.
Referenced by RexxMemory::createImage(), and makeArray().
append()
RexxObject * RexxList::append (RexxObject * _value)
Append an item after the last item in the list.
Parameters
value The value to append.
Returns
The index of the appended item.
Definition at line 538 of file ListClass.cpp.
References ARG_ONE, insert(), OREF_NULL, and requiredArgument().
Referenced by ProtectedSet::add(), ClassDirective::addInherits(), ExtensionDirective::addInherits(), RexxSource::addPackage(), SysInterpreterInstance::addSearchExtension(), RexxSource::addText(), InterpreterInstance::attachThread(), RexxSource::classDirective(), ActivityManager::createCurrentActivity(), RexxMemory::createImage(), Interpreter::createInterpreterInstance(), ActivityManager::createNewActivity(), RexxSource::extensionDirective(), RexxActivity::generateProgramInformation(), InterpreterInstance::initialize(), RexxSource::libraryDirective(), ActivityManager::poolActivity(), InterpreterInstance::processOptions(), InterpreterInstance::removeInactiveActivities(), RexxSource::requiresDirective(), RexxSource::resolveDependencies(), InterpreterInstance::spawnActivity(), and InterpreterInstance::terminate().
classOf()
RexxList * RexxList::classOf (RexxObject ** args, size_t argCount, size_t named_argCount)
Definition at line 1261 of file ListClass.cpp.
References addLast(), Error_Incorrect_method_noarg, OREF_NULL, reportException(), RexxList(), RexxObject::sendMessage(), and TheListClass.
Referenced by RexxMemory::createImage().
copy()
RexxObject * RexxList::copy (void) virtual
Reimplemented from RexxObject.
Definition at line 78 of file ListClass.cpp.
References RexxInternalObject::copy(), RexxObject::copy(), OrefSet, and table.
createInstance()
void RexxList::createInstance () static
Create initial class object at bootstrap time.
Definition at line 60 of file ListClass.cpp.
References CLASS_CREATE.
Referenced by RexxMemory::createImage().
empty()
RexxObject * RexxList::empty ()
Empty all of the items from a list.
Returns
No return value.
Definition at line 908 of file ListClass.cpp.
References ENTRY_POINTER, first, LIST_END, OREF_NULL, and primitiveRemove().
Referenced by RexxMemory::createImage().
firstIndex()
size_t RexxList::firstIndex () inline
Definition at line 84 of file ListClass.hpp.
References first.
Referenced by ClassDirective::addDependencies(), Interpreter::haltAllActivities(), InterpreterInstance::haltAllActivities(), ClassDirective::install(), ExtensionDirective::install(), RexxSource::processInstall(), RexxClass::removeSubclass(), RexxSource::resolveDependencies(), SysInterpreterInstance::resolveProgramName(), RexxMessage::sendNotification(), InterpreterInstance::traceAllActivities(), and weakReferenceArray().
firstItem()
RexxObject * RexxList::firstItem (void)
Definition at line 682 of file ListClass.cpp.
References ENTRY_POINTER, first, LIST_END, and TheNilObject.
Referenced by RexxMemory::createImage(), and RexxQueue::peek().
firstRexx()
RexxObject * RexxList::firstRexx (void)
Definition at line 712 of file ListClass.cpp.
References first, LIST_END, new_integer(), and TheNilObject.
Referenced by RexxMemory::createImage(), and indexOfValue().
flatten()
void RexxList::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxObject.
Definition at line 171 of file ListClass.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
getEntry() [1/2]
LISTENTRY * RexxList::getEntry (RexxObject * _index, RexxObject * position)
Definition at line 184 of file ListClass.cpp.
References ENTRY_POINTER, Error_Incorrect_method_index, Error_Incorrect_method_noarg, RexxInteger::getValue(), NOT_ACTIVE, OREF_NULL, listentry::previous, reportException(), REQUEST_INTEGER(), size, and TheNilObject.
Referenced by add(), getValue(), hasIndex(), insert(), next(), nextIndex(), previous(), previousIndex(), put(), remove(), section(), and value().
getEntry() [2/2]
LISTENTRY * RexxList::getEntry (size_t item_index)
Resolve a low-level index into a list entry value.
Parameters
item_index The target index.
Returns
A LISTENTRY value, or NULL if not found.
Definition at line 230 of file ListClass.cpp.
References ENTRY_POINTER, NOT_ACTIVE, listentry::previous, and size.
getFree()
size_t RexxList::getFree (void)
Definition at line 115 of file ListClass.cpp.
References ENTRY_POINTER, free, RexxListTable::getData(), RexxInternalObject::isOldSpace(), LIST_END, OrefSet, partitionBuffer(), size, table, TABLE_SIZE, and listentry::value.
Referenced by add(), addFirst(), addLast(), insert(), and RexxQueue::insert().
getSize()
size_t RexxList::getSize () inline
Definition at line 126 of file ListClass.hpp.
References count.
Referenced by build(), RexxVariableDictionary::buildCompoundVariable(), RexxActivation::mergeTraps(), RexxActivation::run(), RexxMessage::sendNotification(), and RexxActivation::termination().
getValue()
RexxObject * RexxList::getValue (size_t _index)
Primitive level getValue() for a list item.
Parameters
_index The decoded index item.
Returns
The value associated with the index. Returns OREF_NULL if not there.
Definition at line 276 of file ListClass.cpp.
References getEntry(), OREF_NULL, and listentry::value.
Referenced by ClassDirective::addDependencies(), InterpreterInstance::findActivity(), ActivityManager::findActivity(), Interpreter::haltAllActivities(), InterpreterInstance::haltAllActivities(), ClassDirective::install(), ExtensionDirective::install(), RexxSource::processInstall(), RexxClass::removeSubclass(), RexxSource::resolveDependencies(), SysInterpreterInstance::resolveProgramName(), RexxMessage::sendNotification(), and InterpreterInstance::traceAllActivities().
hasIndex()
RexxObject * RexxList::hasIndex (RexxObject * _index)
Definition at line 845 of file ListClass.cpp.
References getEntry(), IntegerOne, TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
hasItem()
RexxObject * RexxList::hasItem (RexxObject * target)
Tests whether there is an object with the given value in the list.
Parameters
target The target value.
Returns
.true if there is a match, .false otherwise.
Definition at line 994 of file ListClass.cpp.
References ARG_ONE, count, ENTRY_POINTER, RexxObject::equalValue(), first, listentry::next, requiredArgument(), TheFalseObject, TheTrueObject, and listentry::value.
Referenced by RexxSource::addPackage(), SysInterpreterInstance::addSearchExtension(), RexxSource::argList(), and RexxMemory::createImage().
index()
RexxObject * RexxList::index (RexxObject * target)
Return the index of the first item with a matching value in the list. Returns .nil if the object is not found.
Parameters
target The target object.
Returns
The index of the item, or .nil.
Definition at line 964 of file ListClass.cpp.
References ARG_ONE, count, ENTRY_POINTER, RexxObject::equalValue(), first, new_integer(), listentry::next, requiredArgument(), TheNilObject, and listentry::value.
Referenced by RexxMemory::createImage().
indexOfValue()
RexxObject * RexxList::indexOfValue (RexxObject * _value)
Definition at line 1082 of file ListClass.cpp.
References firstRexx(), lastRexx(), next(), OREF_NULL, TheNilObject, and value().
init()
void RexxList::init (void)
Definition at line 66 of file ListClass.cpp.
References first, INITIAL_LIST_SIZE, last, LIST_END, partitionBuffer(), and size.
Referenced by operator new(), and RexxQueue::operator new().
insert()
RexxObject * RexxList::insert (RexxObject * _value, RexxObject * _index)
Definition at line 546 of file ListClass.cpp.
References count, ENTRY_INDEX, ENTRY_POINTER, Error_Incorrect_method_index, first, getEntry(), getFree(), IntegerOne, last, LIST_END, new_integer(), listentry::next, OREF_NULL, OrefSet, listentry::previous, reportException(), table, TheNilObject, and listentry::value.
Referenced by append(), and insertRexx().
insertRexx()
RexxObject * RexxList::insertRexx (RexxObject * _value, RexxObject * _index)
Definition at line 518 of file ListClass.cpp.
References ARG_ONE, insert(), and requiredArgument().
Referenced by RexxMemory::createImage().
isEmpty()
RexxObject * RexxList::isEmpty ()
Test if a list is empty.
Returns
True if the list is empty, false otherwise
Definition at line 926 of file ListClass.cpp.
References count, TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
items()
size_t RexxList::items (void) inline
Definition at line 97 of file ListClass.hpp.
References count.
Referenced by ActivityManager::activityEnded(), RexxQueue::allIndexes(), InterpreterInstance::detachThread(), Interpreter::lastInstance(), RexxQueue::lastRexx(), ActivityManager::poolActivity(), InterpreterInstance::poolActivity(), RexxSource::processInstall(), InterpreterInstance::removeInactiveActivities(), RexxSource::resolveDependencies(), InterpreterInstance::terminate(), and Interpreter::terminateInterpreter().
itemsRexx()
RexxObject * RexxList::itemsRexx (void)
Definition at line 1148 of file ListClass.cpp.
References count, and new_integer().
Referenced by RexxMemory::createImage().
lastIndex()
size_t RexxList::lastIndex () inline
Definition at line 85 of file ListClass.hpp.
References last.
Referenced by InterpreterInstance::findActivity(), and ActivityManager::findActivity().
lastItem()
RexxObject * RexxList::lastItem (void)
Definition at line 697 of file ListClass.cpp.
References ENTRY_POINTER, last, LIST_END, and TheNilObject.
Referenced by RexxMemory::createImage(), and RexxActivation::termination().
lastRexx()
RexxObject * RexxList::lastRexx (void)
Definition at line 728 of file ListClass.cpp.
References last, LIST_END, new_integer(), and TheNilObject.
Referenced by RexxMemory::createImage(), and indexOfValue().
live()
void RexxList::live (size_t liveMark) virtual
Reimplemented from RexxObject.
Definition at line 153 of file ListClass.cpp.
References memory_mark, and table.
liveGeneral()
void RexxList::liveGeneral (int reason) virtual
Reimplemented from RexxObject.
Definition at line 162 of file ListClass.cpp.
References memory_mark_general, and table.
makeArray()
RexxArray * RexxList::makeArray (void) virtual
Reimplemented from RexxObject.
Definition at line 873 of file ListClass.cpp.
References allItems().
Referenced by RexxActivity::display(), PackageClass::getImportedPackages(), StringUtil::makearray(), requestArray(), supplier(), and RexxQueue::supplier().
makeArrayIndices()
RexxArray * RexxList::makeArrayIndices ()
Definition at line 1112 of file ListClass.cpp.
References count, ENTRY_POINTER, first, new_array(), new_integer(), listentry::next, and RexxArray::put().
Referenced by supplier().
newRexx()
RexxList * RexxList::newRexx (RexxObject ** init_args, size_t argCount, size_t named_argCount)
Definition at line 1226 of file ListClass.cpp.
References RexxClass::checkAbstract(), RexxClass::getInstanceBehaviour(), RexxInternalObject::hasUninit(), RexxClass::hasUninitDefined(), RexxList(), RexxObject::sendMessage(), and RexxInternalObject::setBehaviour().
Referenced by RexxMemory::createImage().
next()
RexxObject * RexxList::next (RexxObject * _index)
Definition at line 744 of file ListClass.cpp.
References Error_Incorrect_method_index, getEntry(), IntegerOne, LIST_END, new_integer(), listentry::next, reportException(), and TheNilObject.
Referenced by RexxMemory::createImage(), and indexOfValue().
nextIndex()
size_t RexxList::nextIndex (size_t _index)
A low-level next() method for internal usage. This works directly off the index values without needing to create object instances. This is critical for some of the internal data structures implemented as lists.
Parameters
_index The target item index.
Returns
The index of the next item, or LIST_END if there is no next item.
Definition at line 804 of file ListClass.cpp.
References getEntry(), LIST_END, and listentry::next.
Referenced by ClassDirective::addDependencies(), Interpreter::haltAllActivities(), InterpreterInstance::haltAllActivities(), ClassDirective::install(), ExtensionDirective::install(), RexxSource::processInstall(), RexxClass::removeSubclass(), RexxSource::resolveDependencies(), SysInterpreterInstance::resolveProgramName(), RexxMessage::sendNotification(), and InterpreterInstance::traceAllActivities().
operator new() [1/2]
void* RexxList::operator new (size_t size, void * objectPtr) inline
Definition at line 67 of file ListClass.hpp.
operator new() [2/2]
void * RexxList::operator new (size_t size)
Definition at line 1213 of file ListClass.cpp.
References init(), INITIAL_LIST_SIZE, RexxInternalObject::setBehaviour(), and TheListBehaviour.
partitionBuffer()
void RexxList::partitionBuffer (size_t first_entry, size_t entry_count)
Definition at line 92 of file ListClass.cpp.
References ENTRY_POINTER, free, LIST_END, listentry::next, NOT_ACTIVE, OREF_NULL, OrefSet, listentry::previous, table, and listentry::value.
Referenced by getFree(), and init().
previous()
RexxObject * RexxList::previous (RexxObject * _index)
Definition at line 769 of file ListClass.cpp.
References Error_Incorrect_method_index, getEntry(), IntegerOne, LIST_END, new_integer(), listentry::previous, reportException(), and TheNilObject.
Referenced by RexxMemory::createImage().
previousIndex()
size_t RexxList::previousIndex (size_t _index)
A low-level previous() method for internal usage. This works directly off the index values without needing to create object instances. This is critical for some of the internal data structures implemented as lists.
Parameters
_index The target item index.
Returns
The index of the previous item, or LIST_END if there is no previous item.
Definition at line 830 of file ListClass.cpp.
References getEntry(), LIST_END, and listentry::previous.
Referenced by InterpreterInstance::findActivity(), and ActivityManager::findActivity().
primitiveRemove()
RexxObject * RexxList::primitiveRemove (LISTENTRY * element)
Definition at line 640 of file ListClass.cpp.
References count, ENTRY_INDEX, ENTRY_POINTER, first, free, last, LIST_END, listentry::next, NOT_ACTIVE, listentry::previous, TheNilObject, and listentry::value.
Referenced by empty(), remove(), RexxQueue::remove(), removeFirst(), removeFirstItem(), removeIndex(), removeItem(), removeLast(), removeLastItem(), removeObject(), and weakReferenceArray().
put()
RexxObject * RexxList::put (RexxObject * _value, RexxObject * _index)
Definition at line 289 of file ListClass.cpp.
References ARG_ONE, Error_Incorrect_method_index, getEntry(), IntegerTwo, OREF_NULL, OrefSet, reportException(), requiredArgument(), table, and listentry::value.
Referenced by RexxMemory::createImage().
remove()
RexxObject * RexxList::remove (RexxObject * _index)
Definition at line 630 of file ListClass.cpp.
References getEntry(), IntegerOne, and primitiveRemove().
Referenced by RexxMemory::createImage().
removeFirst()
RexxObject* RexxList::removeFirst () inline
Definition at line 109 of file ListClass.hpp.
References ENTRY_POINTER, first, LIST_END, primitiveRemove(), and TheNilObject.
Referenced by RexxVariableReference::drop(), RexxVariableReference::expose(), RexxQueue::pop(), RexxActivation::popEnvironment(), RexxVariableReference::procedureExpose(), RexxVariableDictionary::release(), RexxMessage::sendNotification(), RexxSource::translateBlock(), and RexxVariableReference::upper().
removeFirstItem()
RexxObject* RexxList::removeFirstItem () inline
Definition at line 111 of file ListClass.hpp.
References ENTRY_POINTER, first, LIST_END, OREF_NULL, and primitiveRemove().
Referenced by ActivityManager::clearActivityPool(), ActivityManager::createNewActivity(), and InterpreterInstance::removeInactiveActivities().
removeIndex()
RexxObject* RexxList::removeIndex (size_t i) inline
Definition at line 113 of file ListClass.hpp.
References ENTRY_POINTER, and primitiveRemove().
Referenced by RexxClass::removeSubclass(), and RexxSource::resolveDependencies().
removeItem()
RexxObject * RexxList::removeItem (RexxObject * target)
Removes an item from the collection.
Parameters
target The target value.
Returns
The target item.
Definition at line 1023 of file ListClass.cpp.
References ARG_ONE, count, ENTRY_POINTER, RexxObject::equalValue(), first, listentry::next, primitiveRemove(), requiredArgument(), TheNilObject, and listentry::value.
Referenced by ActivityManager::activityEnded(), RexxMemory::createImage(), InterpreterInstance::detachThread(), ActivityManager::poolActivity(), InterpreterInstance::poolActivity(), ActivityManager::returnActivity(), ActivityManager::returnRootActivity(), InterpreterInstance::terminate(), and Interpreter::terminateInterpreterInstance().
removeLast()
RexxObject* RexxList::removeLast () inline
Definition at line 110 of file ListClass.hpp.
References ENTRY_POINTER, last, LIST_END, primitiveRemove(), and TheNilObject.
removeLastItem()
RexxObject* RexxList::removeLastItem () inline
Definition at line 112 of file ListClass.hpp.
References ENTRY_POINTER, last, LIST_END, OREF_NULL, and primitiveRemove().
removeObject()
RexxObject * RexxList::removeObject (RexxObject * target)
Removes an item from the collection using Object identity comparisons. This is used in some special circumstances when we don't want to have the equals method called, which can cause some exceptions or false positives. This is used primarily for managing the local reference save lists.
Parameters
target The target value.
Returns
The target item.
Definition at line 1058 of file ListClass.cpp.
References ARG_ONE, count, ENTRY_POINTER, first, listentry::next, primitiveRemove(), requiredArgument(), TheNilObject, and listentry::value.
requestArray()
RexxArray * RexxList::requestArray ()
Definition at line 857 of file ListClass.cpp.
References isOfClass, makeArray(), and RexxObject::sendMessage().
section()
RexxObject * RexxList::section (RexxObject * _index, RexxObject * _count)
Definition at line 309 of file ListClass.cpp.
References addLast(), ARG_TWO, ENTRY_POINTER, Error_Incorrect_method_index, getEntry(), IntegerOne, isOfClass, LIST_END, listentry::next, OREF_NULL, reportException(), RexxObject::requiredNonNegative(), RexxList(), sectionSubclass(), and listentry::value.
Referenced by RexxMemory::createImage().
sectionSubclass()
RexxObject * RexxList::sectionSubclass (LISTENTRY * element, size_t counter)
Definition at line 354 of file ListClass.cpp.
References RexxInternalObject::behaviour, ENTRY_POINTER, RexxBehaviour::getOwningClass(), LIST_END, listentry::next, RexxObject::sendMessage(), and listentry::value.
Referenced by section().
supplier()
RexxSupplier * RexxList::supplier (void)
Definition at line 1131 of file ListClass.cpp.
References makeArray(), makeArrayIndices(), and new_supplier().
Referenced by RexxMemory::createImage().
value()
RexxObject * RexxList::value (RexxObject * _index)
Definition at line 246 of file ListClass.cpp.
References getEntry(), IntegerOne, OREF_NULL, TheNilObject, and listentry::value.
Referenced by RexxMemory::createImage(), and indexOfValue().
weakReferenceArray()
RexxArray * RexxList::weakReferenceArray ()
Not really part of normal list operation, but classes maintain their subclasses as a list of weak references so that subclasses can get garbage collected when no longer needed. When the class needs to iterate over the subclasses, it needs to resolve which weak references are still valid. This method will check the weak references and remove any stale entries. Then it will return an array of the dereferenced objects.
Returns
An array of the dereferenced objects.
Definition at line 1170 of file ListClass.cpp.
References RexxArray::append(), count, ENTRY_POINTER, firstIndex(), WeakReference::get(), if(), new_array(), listentry::next, OREF_NULL, primitiveRemove(), and listentry::value.
Referenced by RexxClass::getSubClasses().
Friends And Related Function Documentation
RexxListTable
friend class RexxListTable friend
Definition at line 64 of file ListClass.hpp.
Member Data Documentation
classInstance
RexxClass * RexxList::classInstance = OREF_NULL static
Definition at line 134 of file ListClass.hpp.
count
size_t RexxList::count protected
Definition at line 141 of file ListClass.hpp.
Referenced by add(), addFirst(), addLast(), allIndexes(), allItems(), RexxQueue::append(), getSize(), hasItem(), index(), RexxQueue::index(), insert(), RexxQueue::insert(), isEmpty(), items(), itemsRexx(), makeArrayIndices(), primitiveRemove(), removeItem(), removeObject(), and weakReferenceArray().
first
size_t RexxList::first protected
Definition at line 139 of file ListClass.hpp.
Referenced by add(), addFirst(), addLast(), allIndexes(), allItems(), empty(), RexxQueue::entryToIndex(), firstIndex(), firstItem(), firstRexx(), RexxQueue::firstRexx(), hasItem(), index(), RexxQueue::index(), init(), insert(), RexxQueue::insert(), RexxQueue::locateEntry(), makeArrayIndices(), primitiveRemove(), removeFirst(), removeFirstItem(), removeItem(), and removeObject().
free
size_t RexxList::free protected
Definition at line 143 of file ListClass.hpp.
Referenced by getFree(), partitionBuffer(), and primitiveRemove().
last
size_t RexxList::last protected
Definition at line 140 of file ListClass.hpp.
Referenced by add(), addFirst(), addLast(), init(), insert(), RexxQueue::insert(), lastIndex(), lastItem(), lastRexx(), RexxQueue::lastRexx(), primitiveRemove(), removeLast(), and removeLastItem().
size
size_t RexxList::size protected
Definition at line 142 of file ListClass.hpp.
Referenced by getEntry(), getFree(), and init().
table
RexxListTable* RexxList::table protected
Definition at line 138 of file ListClass.hpp.
Referenced by add(), addFirst(), addLast(), copy(), getFree(), insert(), RexxQueue::insert(), live(), liveGeneral(), RexxListTable::operator new(), partitionBuffer(), put(), and RexxQueue::put().
The documentation for this class was generated from the following files:
ListClass.hpp
ListClass.cpp