executor.master: CallRoutineDispatcher Class Reference
CallRoutineDispatcher Class Reference
#include <RexxStartDispatcher.hpp>
Public Member Functions
CallRoutineDispatcher (RoutineClass *r, RexxArray *a)
virtual ~CallRoutineDispatcher ()
virtual void run ()
Public Member Functions inherited from ActivityDispatcher
ActivityDispatcher ()
virtual ~ActivityDispatcher ()
virtual void handleError (wholenumber_t, RexxDirectory *)
virtual void handleError (RexxDirectory *)
virtual void invoke ()
virtual void invoke (RexxOption *)
virtual void invoke (PRXSYSEXIT exits, const char *env)
void setContext (RexxActivity *act, RexxNativeActivation *a)
Public Attributes
ProtectedObject result
Public Attributes inherited from ActivityDispatcher
wholenumber_t rc
RexxDirectory * conditionData
Protected Attributes
RoutineClass * routine
RexxArray * arguments
Protected Attributes inherited from ActivityDispatcher
RexxActivity * activity
RexxNativeActivation * activation
Detailed Description
Definition at line 66 of file RexxStartDispatcher.hpp.
Constructor & Destructor Documentation
CallRoutineDispatcher()
CallRoutineDispatcher::CallRoutineDispatcher (RoutineClass * r, RexxArray * a) inline
Definition at line 69 of file RexxStartDispatcher.hpp.
~CallRoutineDispatcher()
virtual CallRoutineDispatcher::~CallRoutineDispatcher () inline virtual
Definition at line 70 of file RexxStartDispatcher.hpp.
Member Function Documentation
run()
void CallRoutineDispatcher::run () virtual
Run a routine for a thread context API call.
Reimplemented from ActivityDispatcher.
Definition at line 200 of file RexxStartDispatcher.cpp.
References ActivityDispatcher::activity, arguments, RoutineClass::call(), RexxArray::data(), OREF_NULL, result, routine, and RexxArray::size().
Member Data Documentation
arguments
RexxArray* CallRoutineDispatcher::arguments protected
Definition at line 78 of file RexxStartDispatcher.hpp.
Referenced by run().
result
ProtectedObject CallRoutineDispatcher::result
Definition at line 74 of file RexxStartDispatcher.hpp.
Referenced by CallRoutine(), and run().
routine
RoutineClass* CallRoutineDispatcher::routine protected
Definition at line 77 of file RexxStartDispatcher.hpp.
Referenced by run().
The documentation for this class was generated from the following files:
RexxStartDispatcher.hpp
RexxStartDispatcher.cpp