executor.master: Unicode Class Reference
Unicode Class Reference
#include <TextClass.hpp>
Public Member Functions
void * operator new (size_t, void *ptr)
void operator delete (void *, void *)
void * operator new (size_t)
void operator delete (void *)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
Unicode ()
Unicode (RESTORETYPE restoreType)
RexxObject * newRexx (RexxObject **, size_t, size_t)
RexxObject * copyRexx ()
RexxInteger * systemIsLittleEndian ()
RexxString * utf8proc_version ()
RexxInteger * utf8proc_graphemeBreak (RexxArray *)
RexxInteger * utf8proc_codepointCategory (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointCombiningClass (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointBidiClass (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointBidiMirrored (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointDecompositionType (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointIgnorable (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointControlBoundary (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointCharWidth (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointBoundClass (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointToLowerSimple (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointToUpperSimple (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointToTitleSimple (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointIsLower (RexxObject *rexxCodepoint)
RexxInteger * utf8proc_codepointIsUpper (RexxObject *rexxCodepoint)
RexxObject * utf8proc_transform (RexxString *str, RexxObject **named_arglist, size_t named_argcount)
RexxString * unialgo_version ()
Public Member Functions inherited from RexxObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *, void *)
void operator delete (void *)
void operator delete (void *, RexxClass *)
void operator delete (void *, RexxClass *, RexxObject **, size_t)
RexxObject * newRexx (RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxObject * newObject ()
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
virtual RexxObject * defMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
virtual RexxString * defaultName ()
virtual RexxObject * unknown (RexxString *msg, RexxArray *args, RexxDirectory *named_args)
virtual RexxInteger * hasMethod (RexxString *msg)
bool hasUninitMethod ()
RexxObject * init ()
void uninit ()
RexxObject * copy ()
HashCode hash ()
bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
RexxNumberString * numberString ()
RexxInteger * integerValue (size_t)
RexxString * makeString ()
RexxText * makeText ()
void copyIntoTail (RexxCompoundTail *buffer)
RexxArray * makeArray ()
RexxString * stringValue ()
RexxText * textValue ()
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxText * requestText ()
RexxInteger * requestInteger (size_t)
bool requestNumber (wholenumber_t &, size_t)
bool requestUnsignedNumber (stringsize_t &, size_t)
RexxArray * requestArray ()
RexxDirectory * requestDirectory ()
RexxString * requiredString (RexxString *kind, size_t)
RexxString * requiredString (RexxString *kind, const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (RexxString *kind, size_t, size_t)
wholenumber_t requiredNumber (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredPositive (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredNonNegative (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
bool isEqual (RexxObject *)
bool isInstanceOf (RexxClass *)
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
RexxMethod * instanceMethod (RexxString *)
RexxSupplier * instanceMethods (RexxClass *)
RexxMethod * instanceMethodRexx (RexxString *)
RexxSupplier * instanceMethodsRexx (RexxClass *)
RexxObject * dynamicTargetRexx (RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
RexxMessage * start (RexxObject **, size_t, size_t)
RexxMessage * startWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxObject * send (RexxObject **, size_t, size_t)
RexxObject * sendWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxMessage * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxString * oref ()
RexxObject * pmdict ()
RexxObject * run (RexxObject **, size_t, size_t)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, ProtectedObject &, bool processUnknown=true, bool dynamicTarget=true)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, RexxObject *, ProtectedObject &, bool processUnknown=true, bool dynamicTarget=true)
RexxMethod * checkPrivate (RexxMethod *, RexxErrorCodes &)
RexxMethod * checkPackage (RexxMethod *, RexxErrorCodes &)
void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
void processProtectedMethod (RexxString *, RexxMethod *, RexxObject **, size_t, size_t, ProtectedObject &)
void sendMessage (RexxString *, RexxArray *, RexxDirectory *, ProtectedObject &)
void sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount, ProtectedObject &result)
void sendMessage (RexxString *message, ProtectedObject &result)
void sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
void sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxArray *, RexxDirectory *=OREF_NULL)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount)
RexxObject * sendMessage (RexxString *message)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * defMethods (RexxDirectory *)
void setObjectVariable (RexxString *, RexxObject *, RexxObject *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxObject *)
void addObjectVariables (RexxVariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxObject * superScope (RexxObject *)
RexxMethod * superMethod (RexxString *, RexxObject *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
const char * idString ()
RexxString * id ()
RexxMethod * methodLookup (RexxString *name)
RexxVariableDictionary * getObjectVariables (RexxObject *)
void guardOn (RexxActivity *activity, RexxObject *scope)
void guardOff (RexxActivity *activity, RexxObject *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
RexxObject * unknownRexx (RexxString *, RexxArray *, RexxObject **, size_t)
RexxObject * hasMethodRexx (RexxString *)
void * getCSelf ()
void * getCSelf (RexxObject *scope)
bool equalValue (RexxObject *other)
virtual wholenumber_t compareTo (RexxObject *)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) RexxVariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, RexxString *&messageName, RexxObject *&startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 128 of file TextClass.hpp.
Constructor & Destructor Documentation
Unicode() [1/2]
Unicode::Unicode () inline
Definition at line 140 of file TextClass.hpp.
Unicode() [2/2]
Unicode::Unicode (RESTORETYPE restoreType) inline
Definition at line 141 of file TextClass.hpp.
Member Function Documentation
copyRexx()
RexxObject * Unicode::copyRexx ()
Definition at line 330 of file TextClass.cpp.
References Error_Unsupported_copy_method, reportException(), and TheNilObject.
Referenced by RexxMemory::createImage().
createInstance()
void Unicode::createInstance () static
Definition at line 318 of file TextClass.cpp.
References CLASS_CREATE.
Referenced by RexxMemory::createImage().
flatten()
void Unicode::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxObject.
Definition at line 352 of file TextClass.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
live()
void Unicode::live (size_t liveMark) virtual
Reimplemented from RexxObject.
Definition at line 342 of file TextClass.cpp.
References memory_mark.
liveGeneral()
void Unicode::liveGeneral (int reason) virtual
Reimplemented from RexxObject.
Definition at line 347 of file TextClass.cpp.
References memory_mark_general.
newRexx()
RexxObject * Unicode::newRexx (RexxObject ** init_args, size_t argCount, size_t named_argCount)
Definition at line 323 of file TextClass.cpp.
References Error_Unsupported_new_method, reportException(), and TheNilObject.
Referenced by RexxMemory::createImage().
operator delete() [1/2]
void Unicode::operator delete (void *) inline
Definition at line 134 of file TextClass.hpp.
operator delete() [2/2]
void Unicode::operator delete (void * , void *) inline
Definition at line 132 of file TextClass.hpp.
operator new() [1/2]
void * Unicode::operator new (size_t size)
Definition at line 337 of file TextClass.cpp.
References new_object(), and T_Unicode.
operator new() [2/2]
void* Unicode::operator new (size_t , void * ptr) inline
Definition at line 131 of file TextClass.hpp.
systemIsLittleEndian()
RexxInteger * Unicode::systemIsLittleEndian ()
Definition at line 359 of file TextClass.cpp.
References isLittleEndian(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
unialgo_version()
RexxString * Unicode::unialgo_version ()
Definition at line 800 of file TextClass.cpp.
References new_string().
Referenced by RexxMemory::createImage().
utf8proc_codepointBidiClass()
RexxInteger * Unicode::utf8proc_codepointBidiClass (RexxObject * rexxCodepoint)
Definition at line 473 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_codepointBidiMirrored()
RexxInteger * Unicode::utf8proc_codepointBidiMirrored (RexxObject * rexxCodepoint)
Definition at line 509 of file TextClass.cpp.
References integer(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
utf8proc_codepointBoundClass()
RexxInteger * Unicode::utf8proc_codepointBoundClass (RexxObject * rexxCodepoint)
Definition at line 585 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_codepointCategory()
RexxInteger * Unicode::utf8proc_codepointCategory (RexxObject * rexxCodepoint)
Definition at line 422 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_codepointCharWidth()
RexxInteger * Unicode::utf8proc_codepointCharWidth (RexxObject * rexxCodepoint)
Definition at line 573 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_codepointCombiningClass()
RexxInteger * Unicode::utf8proc_codepointCombiningClass (RexxObject * rexxCodepoint)
Definition at line 465 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_codepointControlBoundary()
RexxInteger * Unicode::utf8proc_codepointControlBoundary (RexxObject * rexxCodepoint)
Definition at line 565 of file TextClass.cpp.
References integer(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
utf8proc_codepointDecompositionType()
RexxInteger * Unicode::utf8proc_codepointDecompositionType (RexxObject * rexxCodepoint)
Definition at line 517 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_codepointIgnorable()
RexxInteger * Unicode::utf8proc_codepointIgnorable (RexxObject * rexxCodepoint)
Definition at line 557 of file TextClass.cpp.
References integer(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
utf8proc_codepointIsLower()
RexxInteger * Unicode::utf8proc_codepointIsLower (RexxObject * rexxCodepoint)
Definition at line 646 of file TextClass.cpp.
References integer(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
utf8proc_codepointIsUpper()
RexxInteger * Unicode::utf8proc_codepointIsUpper (RexxObject * rexxCodepoint)
Definition at line 654 of file TextClass.cpp.
References integer(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
utf8proc_codepointToLowerSimple()
RexxInteger * Unicode::utf8proc_codepointToLowerSimple (RexxObject * rexxCodepoint)
Definition at line 625 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_codepointToTitleSimple()
RexxInteger * Unicode::utf8proc_codepointToTitleSimple (RexxObject * rexxCodepoint)
Definition at line 639 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_codepointToUpperSimple()
RexxInteger * Unicode::utf8proc_codepointToUpperSimple (RexxObject * rexxCodepoint)
Definition at line 632 of file TextClass.cpp.
References integer(), and new_integer().
Referenced by RexxMemory::createImage().
utf8proc_graphemeBreak()
RexxInteger * Unicode::utf8proc_graphemeBreak (RexxArray * array)
Given a pair of consecutive codepoints, return whether a grapheme break is permitted between them.
Parameters
array An array of 3 items: codepoint1 [IN] The first codepoint. codepoint2 [IN] The second codepoint. state [IN OUT] Initial value must be 0.
Returns
.true if a grapheme break is permitted, .false otherwise.
Definition at line 410 of file TextClass.cpp.
References ARG_ONE, arrayArgument(), Error_Invalid_argument_user_defined, RexxArray::get(), integerRange(), new_integer(), RexxArray::put(), SSIZE_MAX, TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
utf8proc_transform()
RexxObject * Unicode::utf8proc_transform (RexxString * str, RexxObject ** named_arglist, size_t named_argcount)
Definition at line 681 of file TextClass.cpp.
References ARG_ONE, Error_Invalid_argument_user_defined, Error_Logical_value_user_defined, integerRange(), IntegerZero, NamedArguments::match(), normalize(), stringArgument(), and TheFalseObject.
Referenced by RexxMemory::createImage().
utf8proc_version()
RexxString * Unicode::utf8proc_version ()
Definition at line 393 of file TextClass.cpp.
References new_string().
Referenced by RexxMemory::createImage().
Member Data Documentation
classInstance
RexxClass * Unicode::classInstance = OREF_NULL static
Definition at line 146 of file TextClass.hpp.
The documentation for this class was generated from the following files:
TextClass.hpp
TextClass.cpp