executor.master: AttributeGetterCode Class Reference
AttributeGetterCode Class Reference
#include <CPPCode.hpp>
Public Member Functions
void * operator new (size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
AttributeGetterCode (RexxVariableBase *a)
AttributeGetterCode (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
void run (RexxActivity *, RexxMethod *, RexxObject *, RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
BaseCode * setSourceObject (RexxSource *s)
RexxSource * getSourceObject ()
Public Member Functions inherited from BaseCode
virtual void call (RexxActivity *, RoutineClass *, RexxString *, RexxObject **, size_t, size_t, RexxString *, RexxString *, int, ProtectedObject &)
virtual void call (RexxActivity *, RoutineClass *, RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
virtual RexxArray * getSource ()
virtual RexxObject * setSecurityManager (RexxObject *manager)
virtual RexxClass * findClass (RexxString *className)
virtual PackageClass * getPackage ()
bool isSamePackage (PackageClass *p)
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxText * makeText ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxText * textValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Protected Attributes
RexxVariableBase * attribute
RexxSource * source
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Class for an attribute getter method
Definition at line 77 of file CPPCode.hpp.
Constructor & Destructor Documentation
AttributeGetterCode() [1/2]
AttributeGetterCode::AttributeGetterCode (RexxVariableBase * a) inline
Definition at line 84 of file CPPCode.hpp.
References attribute.
AttributeGetterCode() [2/2]
AttributeGetterCode::AttributeGetterCode (RESTORETYPE restoreType) inline
Definition at line 85 of file CPPCode.hpp.
Member Function Documentation
flatten()
void AttributeGetterCode::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 298 of file CPPCode.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
getSourceObject()
RexxSource* AttributeGetterCode::getSourceObject () inline virtual
Retrieve the source object associated with a code object.
Returns
Reimplemented from BaseCode.
Definition at line 92 of file CPPCode.hpp.
References source.
live()
void AttributeGetterCode::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 275 of file CPPCode.cpp.
References attribute, memory_mark, and source.
liveGeneral()
void AttributeGetterCode::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 284 of file CPPCode.cpp.
References attribute, memory_mark_general, SAVINGIMAGE, RexxInternalObject::setInRexxPackage(), and source.
operator delete() [1/2]
void AttributeGetterCode::operator delete (void *) inline
Definition at line 82 of file CPPCode.hpp.
operator delete() [2/2]
void AttributeGetterCode::operator delete (void * , void *) inline
Definition at line 83 of file CPPCode.hpp.
operator new() [1/2]
void* AttributeGetterCode::operator new (size_t size, void * ptr) inline
Definition at line 81 of file CPPCode.hpp.
operator new() [2/2]
void * AttributeGetterCode::operator new (size_t size)
Allocate a new attribute getter code object.
Parameters
size the allocation size.
Returns
A pointer to the newly allocated object.
Definition at line 269 of file CPPCode.cpp.
References new_object(), and T_AttributeGetterCode.
run()
void AttributeGetterCode::run (RexxActivity * activity, RexxMethod * method, RexxObject * receiver, RexxString * messageName, RexxObject ** argPtr, size_t count, size_t named_count, ProtectedObject & result) virtual
Execute an attribute-get operation.
Parameters
activity The current activity.
method The method we're invoking.
receiver The receiver object.
messageName The name of the message used to invoke the method.
argPtr The pointer to the arguments.
count The argument count.
result The returned result.
Reimplemented from BaseCode.
Reimplemented in AttributeSetterCode.
Definition at line 324 of file CPPCode.cpp.
References attribute, Error_Incorrect_method_maxarg, RexxObject::getObjectVariables(), RexxMethod::getScope(), RexxInternalObject::getValue(), RexxMethod::isGuarded(), RexxVariableDictionary::release(), reportException(), and RexxVariableDictionary::reserve().
setSourceObject()
BaseCode* AttributeGetterCode::setSourceObject (RexxSource * s) inline virtual
Set a source object into a code context. The default implementation is just to return the same object without setting a source. This is used mostly for attaching a source context to native code methods and routines defined on directives.
Parameters
s The new source object.
Returns
Either the same object, or a new copy of the code object.
Reimplemented from BaseCode.
Definition at line 91 of file CPPCode.hpp.
References source.
Member Data Documentation
attribute
RexxVariableBase* AttributeGetterCode::attribute protected
Definition at line 95 of file CPPCode.hpp.
Referenced by AttributeGetterCode(), live(), liveGeneral(), run(), and AttributeSetterCode::run().
source
RexxSource* AttributeGetterCode::source protected
Definition at line 96 of file CPPCode.hpp.
Referenced by getSourceObject(), live(), liveGeneral(), and setSourceObject().
The documentation for this class was generated from the following files:
CPPCode.hpp
CPPCode.cpp