executor.master: ContextCommandHandlerDispatcher Class Reference
ContextCommandHandlerDispatcher Class Reference
#include <CommandHandler.hpp>
Public Member Functions
ContextCommandHandlerDispatcher (REXXPFN e, RexxString *a, RexxString *c, ProtectedObject &r, ProtectedObject &co)
virtual ~ContextCommandHandlerDispatcher ()
virtual void run ()
virtual void handleError (RexxDirectory *)
Public Member Functions inherited from CallbackDispatcher
CallbackDispatcher ()
virtual ~CallbackDispatcher ()
virtual void handleError (wholenumber_t, RexxDirectory *)
void setContext (RexxActivity *act, RexxNativeActivation *a)
Public Attributes
REXXPFN entryPoint
RexxString * address
RexxString * command
ProtectedObject & result
ProtectedObject & condition
Public Attributes inherited from CallbackDispatcher
wholenumber_t rc
Additional Inherited Members
Protected Attributes inherited from CallbackDispatcher
RexxActivity * activity
RexxNativeActivation * activation
RexxDirectory * conditionData
Detailed Description
Definition at line 101 of file CommandHandler.hpp.
Constructor & Destructor Documentation
ContextCommandHandlerDispatcher()
ContextCommandHandlerDispatcher::ContextCommandHandlerDispatcher (REXXPFN e, RexxString * a, RexxString * c, ProtectedObject & r, ProtectedObject & co) inline
Definition at line 104 of file CommandHandler.hpp.
~ContextCommandHandlerDispatcher()
virtual ContextCommandHandlerDispatcher::~ContextCommandHandlerDispatcher () inline virtual
Definition at line 106 of file CommandHandler.hpp.
Member Function Documentation
handleError()
void ContextCommandHandlerDispatcher::handleError (RexxDirectory * c) virtual
Default handler for any error conditions. This just sets the condition information in the dispatch unit.
Parameters
c The condition information for the error.
Reimplemented from CallbackDispatcher.
Definition at line 216 of file CommandHandler.cpp.
References CallbackDispatcher::activation, RexxDirectory::at(), RexxNativeActivation::checkConditions(), condition, OREF_NULL, and RexxString::strCompare().
run()
void ContextCommandHandlerDispatcher::run () virtual
Process a callout to a system exit function.
Reimplemented from CallbackDispatcher.
Definition at line 197 of file CommandHandler.cpp.
References CallbackDispatcher::activation, CallbackDispatcher::activity, address, command, RexxActivity::createExitContext(), entryPoint, result, and ExitContext::threadContext.
Member Data Documentation
address
RexxString* ContextCommandHandlerDispatcher::address
Definition at line 112 of file CommandHandler.hpp.
Referenced by run().
command
RexxString* ContextCommandHandlerDispatcher::command
Definition at line 113 of file CommandHandler.hpp.
Referenced by run().
condition
ProtectedObject& ContextCommandHandlerDispatcher::condition
Definition at line 115 of file CommandHandler.hpp.
Referenced by handleError().
entryPoint
REXXPFN ContextCommandHandlerDispatcher::entryPoint
Definition at line 111 of file CommandHandler.hpp.
Referenced by run().
result
ProtectedObject& ContextCommandHandlerDispatcher::result
Definition at line 114 of file CommandHandler.hpp.
Referenced by run().
The documentation for this class was generated from the following files:
CommandHandler.hpp
CommandHandler.cpp