executor.master: DeadObject Class Reference
DeadObject Class Reference
#include <DeadObject.hpp>
Public Member Functions
void * operator new (size_t size, void *address)
void operator delete (void *, void *)
void addEyeCatcher (const char *string)
DeadObject (size_t objectSize)
DeadObject ()
void setObjectSize (size_t newSize)
size_t getObjectSize ()
void insertAfter (DeadObject *newDead)
void insertBefore (DeadObject *newDead)
void remove ()
bool isReal ()
bool isHeader ()
void reset ()
DeadObject * end ()
bool overlaps (DeadObject *o)
Protected Attributes
char VFT [sizeof(void *)]
ObjectHeader header
DeadObject * next
DeadObject * previous
Friends
class DeadObjectPool
Detailed Description
Definition at line 59 of file DeadObject.hpp.
Constructor & Destructor Documentation
DeadObject() [1/2]
DeadObject::DeadObject (size_t objectSize) inline
Definition at line 67 of file DeadObject.hpp.
References addEyeCatcher(), header, and ObjectHeader::setObjectSize().
DeadObject() [2/2]
DeadObject::DeadObject () inline
Definition at line 76 of file DeadObject.hpp.
References addEyeCatcher(), header, next, previous, and ObjectHeader::setObjectSize().
Member Function Documentation
addEyeCatcher()
void DeadObject::addEyeCatcher (const char * string) inline
Definition at line 66 of file DeadObject.hpp.
References VFT.
Referenced by DeadObject().
end()
DeadObject* DeadObject::end () inline
Definition at line 116 of file DeadObject.hpp.
References getObjectSize().
Referenced by overlaps().
getObjectSize()
size_t DeadObject::getObjectSize () inline
Definition at line 85 of file DeadObject.hpp.
References ObjectHeader::getObjectSize(), and header.
Referenced by DeadObjectPool::addSortedBySize(), DeadObjectPool::checkObjectOverlap(), end(), DeadObjectPool::findBestFit(), DeadObjectPool::findFit(), DeadObjectPool::findSmallestFit(), MemorySegmentSet::mergeSegments(), and RexxMemory::reSize().
insertAfter()
void DeadObject::insertAfter (DeadObject * newDead) inline
Definition at line 87 of file DeadObject.hpp.
References next, and previous.
Referenced by DeadObjectPool::add().
insertBefore()
void DeadObject::insertBefore (DeadObject * newDead) inline
Definition at line 94 of file DeadObject.hpp.
References next, and previous.
Referenced by DeadObjectPool::addSortedByLocation(), and DeadObjectPool::addSortedBySize().
isHeader()
bool DeadObject::isHeader () inline
Definition at line 107 of file DeadObject.hpp.
References ObjectHeader::getObjectSize(), and header.
isReal()
bool DeadObject::isReal () inline
Definition at line 106 of file DeadObject.hpp.
References ObjectHeader::getObjectSize(), and header.
Referenced by DeadObjectPool::addSortedByLocation(), DeadObjectPool::addSortedBySize(), DeadObjectPool::checkObjectOverlap(), DeadObjectPool::findSmallestFit(), DeadObjectPool::getFirst(), and DeadObjectPool::isEmpty().
operator delete()
void DeadObject::operator delete (void * , void *) inline
Definition at line 64 of file DeadObject.hpp.
operator new()
void* DeadObject::operator new (size_t size, void * address) inline
Definition at line 63 of file DeadObject.hpp.
overlaps()
bool DeadObject::overlaps (DeadObject * o) inline
Definition at line 117 of file DeadObject.hpp.
References end().
Referenced by DeadObjectPool::checkObjectOverlap().
remove()
void DeadObject::remove () inline
Definition at line 101 of file DeadObject.hpp.
References next, and previous.
Referenced by MemorySegmentSet::combineEmptySegments(), DeadObjectPool::findBestFit(), DeadObjectPool::findFit(), DeadObjectPool::findSmallestFit(), DeadObjectPool::getFirst(), MemorySegmentSet::mergeSegments(), MemorySegment::removeAll(), and MemorySegmentSet::splitSegment().
reset()
void DeadObject::reset () inline
Definition at line 109 of file DeadObject.hpp.
References next, and previous.
Referenced by DeadObjectPool::empty().
setObjectSize()
void DeadObject::setObjectSize (size_t newSize) inline
Definition at line 84 of file DeadObject.hpp.
References header, and ObjectHeader::setObjectSize().
Referenced by MemorySegmentSet::mergeSegments().
Friends And Related Function Documentation
DeadObjectPool
friend class DeadObjectPool friend
Definition at line 60 of file DeadObject.hpp.
Member Data Documentation
header
ObjectHeader DeadObject::header protected
Definition at line 123 of file DeadObject.hpp.
Referenced by DeadObject(), getObjectSize(), isHeader(), isReal(), and setObjectSize().
next
DeadObject* DeadObject::next protected
Definition at line 124 of file DeadObject.hpp.
Referenced by DeadObjectPool::addSingle(), DeadObjectPool::addSortedByLocation(), DeadObjectPool::addSortedBySize(), DeadObjectPool::checkObjectOverlap(), DeadObject(), DeadObjectPool::emptySingle(), DeadObjectPool::findBestFit(), DeadObjectPool::findFit(), DeadObjectPool::findSmallestFit(), DeadObjectPool::firstBlock(), DeadObjectPool::getFirst(), DeadObjectPool::getFirstSingle(), insertAfter(), insertBefore(), DeadObjectPool::isEmpty(), DeadObjectPool::isEmptySingle(), remove(), and reset().
previous
DeadObject* DeadObject::previous protected
Definition at line 125 of file DeadObject.hpp.
Referenced by DeadObject(), insertAfter(), insertBefore(), DeadObjectPool::lastBlock(), remove(), and reset().
VFT
char DeadObject::VFT[sizeof(void *)] protected
Definition at line 121 of file DeadObject.hpp.
Referenced by addEyeCatcher().
The documentation for this class was generated from the following file:
DeadObject.hpp