executor.master: SysLocalAPIManager Class Reference
SysLocalAPIManager Class Reference
#include <SysLocalAPIManager.hpp>
Static Public Member Functions
static void startServerProcess ()
static bool getActiveSessionQueue (QueueHandle &sessionQueue)
static void setActiveSessionQueue (QueueHandle sessionQueue)
static void startServerProcess ()
static bool getActiveSessionQueue (QueueHandle &sessionQueue)
static void setActiveSessionQueue (QueueHandle sessionQueue)
Detailed Description
Definition at line 44 of file unix/SysLocalAPIManager.hpp.
Member Function Documentation
getActiveSessionQueue() [1/2]
bool SysLocalAPIManager::getActiveSessionQueue (QueueHandle & sessionQueue) static
Check to see if we've inherited a session queue from a calling process. This shows up as an environment variable value.
Parameters
sessionQueue The returned session queue handle, if it exists.
Returns
true if the session queue is inherited, false if a new once needs to be created.
Definition at line 101 of file unix/SysLocalAPIManager.cpp.
Referenced by LocalQueueManager::initializeSessionQueue().
getActiveSessionQueue() [2/2]
static bool SysLocalAPIManager::getActiveSessionQueue (QueueHandle & sessionQueue) static
setActiveSessionQueue() [1/2]
void SysLocalAPIManager::setActiveSessionQueue (QueueHandle sessionQueue) static
Set the active session queue as an environment variable.
Parameters
sessionQueue The session queue handle.
Definition at line 120 of file unix/SysLocalAPIManager.cpp.
References MAX_QUEUE_NAME_LENGTH.
Referenced by LocalQueueManager::initializeSessionQueue().
setActiveSessionQueue() [2/2]
static void SysLocalAPIManager::setActiveSessionQueue (QueueHandle sessionQueue) static
startServerProcess() [1/2]
void SysLocalAPIManager::startServerProcess () static
Definition at line 52 of file unix/SysLocalAPIManager.cpp.
References API_FAILURE.
Referenced by LocalAPIManager::establishServerConnection().
startServerProcess() [2/2]
static void SysLocalAPIManager::startServerProcess () static
The documentation for this class was generated from the following files:
unix/SysLocalAPIManager.hpp
windows/SysLocalAPIManager.hpp
unix/SysLocalAPIManager.cpp
windows/SysLocalAPIManager.cpp