executor.master: RexxActivationFrameBuffer Class Reference
RexxActivationFrameBuffer Class Reference
#include <RexxActivationStack.hpp>
Public Member Functions
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxActivationFrameBuffer ()
RexxActivationFrameBuffer (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
bool hasCapacity (size_t entries)
RexxObject ** allocateFrame (size_t entries)
bool contains (RexxObject **frame)
void releaseFrame (RexxObject **frame)
void push (RexxActivationFrameBuffer *p)
void reset ()
RexxActivationFrameBuffer * getPrevious ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxText * makeText ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxText * textValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Static Public Member Functions
static RexxActivationFrameBuffer * newInstance (size_t)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Attributes
size_t size
size_t next
RexxActivationFrameBuffer * previous
RexxObject * buffer [1]
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 49 of file RexxActivationStack.hpp.
Constructor & Destructor Documentation
RexxActivationFrameBuffer() [1/2]
RexxActivationFrameBuffer::RexxActivationFrameBuffer () inline
Definition at line 55 of file RexxActivationStack.hpp.
RexxActivationFrameBuffer() [2/2]
RexxActivationFrameBuffer::RexxActivationFrameBuffer (RESTORETYPE restoreType) inline
Definition at line 56 of file RexxActivationStack.hpp.
Member Function Documentation
allocateFrame()
RexxObject** RexxActivationFrameBuffer::allocateFrame (size_t entries) inline
Definition at line 62 of file RexxActivationStack.hpp.
References buffer, and next.
Referenced by RexxActivationStack::allocateFrame().
contains()
bool RexxActivationFrameBuffer::contains (RexxObject ** frame) inline
Definition at line 69 of file RexxActivationStack.hpp.
References buffer, and size.
Referenced by RexxActivationStack::releaseFrame().
flatten()
void RexxActivationFrameBuffer::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 74 of file RexxActivationStack.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
getPrevious()
RexxActivationFrameBuffer* RexxActivationFrameBuffer::getPrevious () inline
Definition at line 87 of file RexxActivationStack.hpp.
References previous.
Referenced by RexxActivationStack::releaseFrame().
hasCapacity()
bool RexxActivationFrameBuffer::hasCapacity (size_t entries) inline
Definition at line 61 of file RexxActivationStack.hpp.
References next, and size.
Referenced by RexxActivationStack::ensureCapacity(), and RexxActivationStack::expandCapacity().
live()
void RexxActivationFrameBuffer::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 56 of file RexxActivationStack.cpp.
References memory_mark, and previous.
liveGeneral()
void RexxActivationFrameBuffer::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 66 of file RexxActivationStack.cpp.
References memory_mark_general, and previous.
newInstance()
RexxActivationFrameBuffer * RexxActivationFrameBuffer::newInstance (size_t entries) static
Definition at line 145 of file RexxActivationStack.cpp.
References new_object(), next, OREF_NULL, previous, size, and T_ActivationFrameBuffer.
Referenced by new_activationFrameBuffer().
operator delete() [1/2]
void RexxActivationFrameBuffer::operator delete (void *) inline
Definition at line 52 of file RexxActivationStack.hpp.
operator delete() [2/2]
void RexxActivationFrameBuffer::operator delete (void * , void *) inline
Definition at line 53 of file RexxActivationStack.hpp.
operator new()
void* RexxActivationFrameBuffer::operator new (size_t size, void * ptr) inline
Definition at line 51 of file RexxActivationStack.hpp.
push()
void RexxActivationFrameBuffer::push (RexxActivationFrameBuffer * p) inline
Definition at line 79 of file RexxActivationStack.hpp.
References previous.
Referenced by RexxActivationStack::expandCapacity().
releaseFrame()
void RexxActivationFrameBuffer::releaseFrame (RexxObject ** frame) inline
Definition at line 74 of file RexxActivationStack.hpp.
References buffer, and next.
Referenced by RexxActivationStack::releaseFrame().
reset()
void RexxActivationFrameBuffer::reset (void) inline
Definition at line 85 of file RexxActivationStack.hpp.
References next.
Referenced by RexxActivationStack::releaseFrame().
Member Data Documentation
buffer
RexxObject* RexxActivationFrameBuffer::buffer[1] protected
Definition at line 97 of file RexxActivationStack.hpp.
Referenced by allocateFrame(), contains(), and releaseFrame().
next
size_t RexxActivationFrameBuffer::next protected
Definition at line 95 of file RexxActivationStack.hpp.
Referenced by allocateFrame(), hasCapacity(), newInstance(), releaseFrame(), and reset().
previous
RexxActivationFrameBuffer* RexxActivationFrameBuffer::previous protected
Definition at line 96 of file RexxActivationStack.hpp.
Referenced by getPrevious(), live(), liveGeneral(), newInstance(), and push().
size
size_t RexxActivationFrameBuffer::size protected
Definition at line 94 of file RexxActivationStack.hpp.
Referenced by contains(), hasCapacity(), and newInstance().
The documentation for this class was generated from the following files:
RexxActivationStack.hpp
RexxActivationStack.cpp