executor.master: RexxVariableDictionary Class Reference
RexxVariableDictionary Class Reference
#include <RexxVariableDictionary.hpp>
Public Member Functions
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxVariableDictionary (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *envelope)
RexxObject * copy ()
void copyValues ()
RexxObject * realValue (RexxString *name)
void add (RexxVariable *, RexxString *)
void put (RexxVariable *, RexxString *)
RexxStem * getStem (RexxString *stemName)
RexxVariable * createStemVariable (RexxString *stemName)
RexxVariable * createVariable (RexxString *stemName)
RexxVariable * resolveVariable (RexxString *name)
RexxVariable * getVariable (RexxString *name)
RexxVariable * getStemVariable (RexxString *stemName)
void setCompoundVariable (RexxString *stemName, RexxObject **tail, size_t tailCount, RexxObject *value)
void dropCompoundVariable (RexxString *stemName, RexxObject **tail, size_t tailCount)
RexxDirectory * getAllVariables ()
void remove (RexxString *n)
RexxVariable * nextVariable (RexxNativeActivation *)
void set (RexxString *, RexxObject *)
void drop (RexxString *)
void dropStemVariable (RexxString *)
void reserve (RexxActivity *)
unsigned short getReserveCount ()
void release (RexxActivity *)
bool transfer (RexxActivity *)
RexxCompoundElement * getCompoundVariable (RexxString *stemName, RexxObject **tail, size_t tailCount)
RexxObject * getCompoundVariableValue (RexxString *stemName, RexxObject **tail, size_t tailCount)
RexxObject * getCompoundVariableRealValue (RexxString *stem, RexxObject **tail, size_t tailCount)
RexxObject * realStemValue (RexxString *stemName)
bool isScope (RexxObject *otherScope)
RexxVariableDictionary * getNextDictionary ()
RexxActivity * getReservingActivity ()
void setNextDictionary (RexxVariableDictionary *next)
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxText * makeText ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxText * textValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Static Public Member Functions
static RexxVariableBase * getVariableRetriever (RexxString *variable)
static RexxVariableBase * getDirectVariableRetriever (RexxString *variable)
static RexxObject * buildCompoundVariable (RexxString *variable_name, bool direct)
static RexxVariableDictionary * newInstance (size_t)
static RexxVariableDictionary * newInstance (RexxObject *)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Attributes
RexxActivity * reservingActivity
RexxHashTable * contents
RexxList * waitingActivities
unsigned short flags
unsigned short reserveCount
RexxVariableDictionary * next
RexxObject * scope
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 55 of file RexxVariableDictionary.hpp.
Constructor & Destructor Documentation
RexxVariableDictionary()
RexxVariableDictionary::RexxVariableDictionary (RESTORETYPE restoreType) inline
Definition at line 61 of file RexxVariableDictionary.hpp.
Member Function Documentation
add()
void RexxVariableDictionary::add (RexxVariable * variable, RexxString * name)
Definition at line 222 of file RexxVariableDictionary.cpp.
References contents, OREF_NULL, OrefSet, and RexxHashTable::stringAdd().
buildCompoundVariable()
RexxObject * RexxVariableDictionary::buildCompoundVariable (RexxString * variable_name, bool direct) static
Definition at line 741 of file RexxVariableDictionary.cpp.
References RexxString::extract(), RexxString::getChar(), RexxString::getLength(), RexxList::getSize(), new_queue(), and RexxQueue::push().
Referenced by getDirectVariableRetriever(), RexxSource::getRetriever(), and getVariableRetriever().
copy()
RexxObject * RexxVariableDictionary::copy (void) virtual
Reimplemented from RexxInternalObject.
Definition at line 64 of file RexxVariableDictionary.cpp.
References RexxInternalObject::behaviour, contents, RexxInternalObject::copy(), copyValues(), RexxHashTable::mainSlotsSize(), new_variableDictionary(), OrefSet, and scope.
Referenced by RexxObject::copyObjectVariables().
copyValues()
void RexxVariableDictionary::copyValues ()
Definition at line 82 of file RexxVariableDictionary.cpp.
References contents, RexxObject::copy(), RexxHashTable::first(), RexxHashTable::replace(), RexxHashTable::totalSlotsSize(), and RexxHashTable::value().
Referenced by copy(), and RexxObject::copyObjectVariables().
createStemVariable()
RexxVariable * RexxVariableDictionary::createStemVariable (RexxString * stemName)
Definition at line 257 of file RexxVariableDictionary.cpp.
References contents, new_variable(), OREF_NULL, OrefSet, RexxVariable::set(), and RexxHashTable::stringAdd().
Referenced by getStemVariable().
createVariable()
RexxVariable * RexxVariableDictionary::createVariable (RexxString * stemName)
Definition at line 280 of file RexxVariableDictionary.cpp.
References contents, new_variable(), OREF_NULL, OrefSet, and RexxHashTable::stringAdd().
Referenced by getVariable().
drop()
void RexxVariableDictionary::drop (RexxString * name)
Drop the value of a named variable in the method dictionary.
Parameters
name The string name of the variable.
Definition at line 119 of file RexxVariableDictionary.cpp.
References RexxVariable::drop(), OREF_NULL, and resolveVariable().
dropCompoundVariable()
void RexxVariableDictionary::dropCompoundVariable (RexxString * stemName, RexxObject ** tail, size_t tailCount)
Drop a compound variable in the dictionary.
Parameters
stemName The name of the stem.
tail The tail elements.
tailCount The count of tail elements.
value The value to set.
Definition at line 576 of file RexxVariableDictionary.cpp.
References RexxStem::dropCompoundVariable(), and getStem().
Referenced by RexxCompoundVariable::drop().
dropStemVariable()
void RexxVariableDictionary::dropStemVariable (RexxString * name)
Drop the value of a named variable in the method dictionary.
Parameters
name The string name of the variable.
Definition at line 135 of file RexxVariableDictionary.cpp.
References RexxVariable::drop(), OREF_NULL, resolveVariable(), and RexxVariable::set().
Referenced by RexxStemVariable::drop().
flatten()
void RexxVariableDictionary::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 491 of file RexxVariableDictionary.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
getAllVariables()
RexxDirectory * RexxVariableDictionary::getAllVariables ()
Get all of the variables in the local context. This returns just the top-level variables (i.e., simple variables and stems).
Returns
A supplier for iterating the variable sset.
Definition at line 468 of file RexxVariableDictionary.cpp.
References contents, RexxHashTable::first(), RexxVariable::getName(), RexxVariable::getVariableValue(), new_directory(), OREF_NULL, RexxDirectory::put(), RexxHashTable::totalSlotsSize(), and RexxHashTable::value().
Referenced by RexxActivation::getAllLocalVariables().
getCompoundVariable()
RexxCompoundElement * RexxVariableDictionary::getCompoundVariable (RexxString * stemName, RexxObject ** tail, size_t tailCount)
Definition at line 148 of file RexxVariableDictionary.cpp.
References RexxStem::getCompoundVariable(), and getStem().
getCompoundVariableRealValue()
RexxObject * RexxVariableDictionary::getCompoundVariableRealValue (RexxString * stem, RexxObject ** tail, size_t tailCount)
Retrieve the "real" value of a compound variable. This return OREF_NULL for any situation where the compound variable name would be returned.
Parameters
stem The name of the stem.
tail The set of tails used for the lookup.
tailCount The number of tail elements.
Returns
Either the variable value, or OREF_NULL for unassigned variables.
Definition at line 197 of file RexxVariableDictionary.cpp.
References RexxStem::getCompoundVariableRealValue(), and getStem().
Referenced by RexxCompoundVariable::getRealValue().
getCompoundVariableValue()
RexxObject * RexxVariableDictionary::getCompoundVariableValue (RexxString * stemName, RexxObject ** tail, size_t tailCount)
Definition at line 166 of file RexxVariableDictionary.cpp.
References RexxStem::evaluateCompoundVariableValue(), getStem(), and OREF_NULL.
Referenced by RexxCompoundVariable::getValue().
getDirectVariableRetriever()
RexxVariableBase * RexxVariableDictionary::getDirectVariableRetriever (RexxString * variable) static
Definition at line 638 of file RexxVariableDictionary.cpp.
References buildCompoundVariable(), RexxString::getChar(), RexxString::getLength(), RexxSource::isSymbolCharacter(), MAX_SYMBOL_LENGTH, OREF_NULL, and RexxSource::translateChar().
Referenced by RexxNativeActivation::variablePoolGetVariable().
getNextDictionary()
RexxVariableDictionary* RexxVariableDictionary::getNextDictionary () inline
Definition at line 128 of file RexxVariableDictionary.hpp.
References next.
Referenced by RexxObject::copyObjectVariables(), RexxObject::getObjectVariable(), and RexxObject::getObjectVariables().
getReserveCount()
unsigned short RexxVariableDictionary::getReserveCount () inline
Definition at line 117 of file RexxVariableDictionary.hpp.
References reserveCount.
Referenced by RexxActivation::getReserveCount().
getReservingActivity()
RexxActivity* RexxVariableDictionary::getReservingActivity () inline
Definition at line 129 of file RexxVariableDictionary.hpp.
References reservingActivity.
getStem()
RexxStem* RexxVariableDictionary::getStem (RexxString * stemName) inline
Definition at line 72 of file RexxVariableDictionary.hpp.
References getStemVariable(), and RexxVariable::getVariableValue().
Referenced by dropCompoundVariable(), RexxCompoundVariable::expose(), getCompoundVariable(), getCompoundVariableRealValue(), getCompoundVariableValue(), RexxStemVariable::getRealValue(), RexxStemVariable::getValue(), realStemValue(), and setCompoundVariable().
getStemVariable()
RexxVariable* RexxVariableDictionary::getStemVariable (RexxString * stemName) inline
Definition at line 94 of file RexxVariableDictionary.hpp.
References createStemVariable(), OREF_NULL, and resolveVariable().
Referenced by RexxStemVariable::expose(), getStem(), RexxLocalVariables::lookupStemVariable(), and RexxStemVariable::set().
getVariable()
RexxVariable* RexxVariableDictionary::getVariable (RexxString * name) inline
Definition at line 81 of file RexxVariableDictionary.hpp.
References createVariable(), OREF_NULL, and resolveVariable().
Referenced by RexxParseVariable::drop(), RexxParseVariable::expose(), RexxParseVariable::getRealValue(), RexxParseVariable::getValue(), RexxLocalVariables::lookupVariable(), set(), and RexxParseVariable::set().
getVariableRetriever()
RexxVariableBase * RexxVariableDictionary::getVariableRetriever (RexxString * variable) static
Definition at line 587 of file RexxVariableDictionary.cpp.
References buildCompoundVariable(), RexxString::extract(), RexxString::getChar(), RexxString::getLength(), RexxString::isSymbol(), OREF_NULL, STRING_BAD_VARIABLE, STRING_COMPOUND_NAME, STRING_LITERAL, STRING_LITERAL_DOT, STRING_NAME, STRING_NUMERIC, STRING_STEM, type, and RexxString::upper().
Referenced by BUILTIN(), RexxNativeActivation::dropContextVariable(), RexxNativeActivation::dropObjectVariable(), RexxInstructionUseStrict::executeNamedArguments(), RexxNativeActivation::getContextStem(), RexxNativeActivation::getContextVariable(), RexxNativeActivation::getObjectVariable(), RexxVariableReference::list(), RexxNativeActivation::setContextVariable(), RexxNativeActivation::setObjectVariable(), RexxNativeActivation::stemSort(), and RexxNativeActivation::variablePoolGetVariable().
isScope()
bool RexxVariableDictionary::isScope (RexxObject * otherScope) inline
Definition at line 127 of file RexxVariableDictionary.hpp.
References scope.
Referenced by RexxObject::getObjectVariables().
live()
void RexxVariableDictionary::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 437 of file RexxVariableDictionary.cpp.
References contents, memory_mark, next, reservingActivity, scope, and waitingActivities.
liveGeneral()
void RexxVariableDictionary::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 449 of file RexxVariableDictionary.cpp.
References contents, memory_mark_general, next, reservingActivity, scope, and waitingActivities.
newInstance() [1/2]
RexxVariableDictionary * RexxVariableDictionary::newInstance (RexxObject * scope) static
Definition at line 526 of file RexxVariableDictionary.cpp.
References DEFAULT_OBJECT_DICTIONARY_SIZE, new_hashCollection(), scope, and T_VariableDictionary.
newInstance() [2/2]
RexxVariableDictionary * RexxVariableDictionary::newInstance (size_t looksize) static
Definition at line 507 of file RexxVariableDictionary.cpp.
References new_hashCollection(), and T_VariableDictionary.
Referenced by new_objectVariableDictionary(), and new_variableDictionary().
nextVariable()
RexxVariable * RexxVariableDictionary::nextVariable (RexxNativeActivation * activation)
Definition at line 297 of file RexxVariableDictionary.cpp.
References contents, RexxHashTable::first(), RexxVariable::getVariableValue(), RexxHashTable::index(), RexxHashTable::next(), RexxNativeActivation::nextVariable(), OREF_NULL, RexxNativeActivation::setNextVariable(), SIZE_MAX, and RexxHashTable::value().
Referenced by RexxNativeActivation::fetchNext().
operator delete() [1/2]
void RexxVariableDictionary::operator delete (void *) inline
Definition at line 58 of file RexxVariableDictionary.hpp.
operator delete() [2/2]
void RexxVariableDictionary::operator delete (void * , void *) inline
Definition at line 59 of file RexxVariableDictionary.hpp.
operator new()
void* RexxVariableDictionary::operator new (size_t size, void * ptr) inline
Definition at line 57 of file RexxVariableDictionary.hpp.
put()
void RexxVariableDictionary::put (RexxVariable * variable, RexxString * name)
Definition at line 239 of file RexxVariableDictionary.cpp.
References contents, OREF_NULL, OrefSet, and RexxHashTable::stringPut().
Referenced by RexxLocalVariables::createDictionary(), RexxLocalVariables::putVariable(), and RexxLocalVariables::updateVariable().
realStemValue()
RexxObject * RexxVariableDictionary::realStemValue (RexxString * stemName)
Definition at line 210 of file RexxVariableDictionary.cpp.
References getStem().
realValue()
RexxObject * RexxVariableDictionary::realValue (RexxString * name)
Definition at line 98 of file RexxVariableDictionary.cpp.
References RexxVariable::getVariableValue(), OREF_NULL, and resolveVariable().
Referenced by RexxObject::getObjectVariable().
release()
void RexxVariableDictionary::release (RexxActivity * activity)
Definition at line 379 of file RexxVariableDictionary.cpp.
References OREF_NULL, OrefSet, RexxActivity::postDispatch(), RexxList::removeFirst(), reserveCount, reservingActivity, TheNilObject, and waitingActivities.
Referenced by RexxActivation::guardOff(), RexxNativeActivation::guardOff(), RexxObject::guardOff(), RexxActivation::guardWait(), AttributeGetterCode::run(), AttributeSetterCode::run(), and transfer().
remove()
void RexxVariableDictionary::remove (RexxString * n) inline
Definition at line 110 of file RexxVariableDictionary.hpp.
References contents, and RexxHashTable::remove().
reserve()
void RexxVariableDictionary::reserve (RexxActivity * activity)
Definition at line 343 of file RexxVariableDictionary.cpp.
References RexxList::addLast(), RexxActivity::checkDeadLock(), new_list(), OREF_NULL, OrefSet, reserveCount, reservingActivity, and waitingActivities.
Referenced by RexxActivation::getObjectVariables(), RexxActivation::guardOn(), RexxNativeActivation::guardOn(), RexxObject::guardOn(), RexxActivation::guardWait(), RexxNativeActivation::methodVariables(), AttributeGetterCode::run(), AttributeSetterCode::run(), and RexxActivation::run().
resolveVariable()
RexxVariable* RexxVariableDictionary::resolveVariable (RexxString * name) inline
Definition at line 76 of file RexxVariableDictionary.hpp.
References contents, and RexxHashTable::stringGet().
Referenced by drop(), dropStemVariable(), RexxLocalVariables::findVariable(), getStemVariable(), getVariable(), and realValue().
set()
void RexxVariableDictionary::set (RexxString * name, RexxObject * value)
Definition at line 330 of file RexxVariableDictionary.cpp.
References getVariable(), and RexxVariable::set().
Referenced by RexxObject::setObjectVariable().
setCompoundVariable()
void RexxVariableDictionary::setCompoundVariable (RexxString * stemName, RexxObject ** tail, size_t tailCount, RexxObject * value)
Set a compound variable in the dictionary.
Parameters
stemName The name of the stem.
tail The tail elements.
tailCount The count of tail elements.
value The value to set.
Definition at line 557 of file RexxVariableDictionary.cpp.
References getStem(), and RexxStem::setCompoundVariable().
Referenced by RexxCompoundVariable::set().
setNextDictionary()
void RexxVariableDictionary::setNextDictionary (RexxVariableDictionary * next)
Definition at line 429 of file RexxVariableDictionary.cpp.
References next, and OrefSet.
Referenced by RexxObject::addObjectVariables(), and RexxObject::getObjectVariables().
transfer()
bool RexxVariableDictionary::transfer (RexxActivity * activity)
Definition at line 409 of file RexxVariableDictionary.cpp.
References OrefSet, release(), reserveCount, and reservingActivity.
Referenced by RexxActivation::run().
Member Data Documentation
contents
RexxHashTable* RexxVariableDictionary::contents protected
Definition at line 143 of file RexxVariableDictionary.hpp.
Referenced by add(), copy(), copyValues(), createStemVariable(), createVariable(), getAllVariables(), live(), liveGeneral(), nextVariable(), put(), remove(), and resolveVariable().
flags
unsigned short RexxVariableDictionary::flags protected
Definition at line 145 of file RexxVariableDictionary.hpp.
next
RexxVariableDictionary* RexxVariableDictionary::next protected
Definition at line 147 of file RexxVariableDictionary.hpp.
Referenced by getNextDictionary(), live(), liveGeneral(), and setNextDictionary().
reserveCount
unsigned short RexxVariableDictionary::reserveCount protected
Definition at line 146 of file RexxVariableDictionary.hpp.
Referenced by getReserveCount(), release(), reserve(), and transfer().
reservingActivity
RexxActivity* RexxVariableDictionary::reservingActivity protected
Definition at line 142 of file RexxVariableDictionary.hpp.
Referenced by getReservingActivity(), live(), liveGeneral(), release(), reserve(), and transfer().
scope
RexxObject* RexxVariableDictionary::scope protected
Definition at line 148 of file RexxVariableDictionary.hpp.
Referenced by copy(), isScope(), live(), liveGeneral(), and newInstance().
waitingActivities
RexxList* RexxVariableDictionary::waitingActivities protected
Definition at line 144 of file RexxVariableDictionary.hpp.
Referenced by live(), liveGeneral(), release(), and reserve().
The documentation for this class was generated from the following files:
RexxVariableDictionary.hpp
RexxVariableDictionary.cpp