executor.master: ServiceException Class Reference
ServiceException Class Reference
#include <ServiceException.hpp>
Public Member Functions
ServiceException (ErrorCode c, const char *m)
~ServiceException ()
ErrorCode getErrorCode ()
const char * getMessage ()
Protected Attributes
ErrorCode errCode
const char * message
Detailed Description
Definition at line 67 of file ServiceException.hpp.
Constructor & Destructor Documentation
ServiceException()
ServiceException::ServiceException (ErrorCode c, const char * m) inline
Definition at line 70 of file ServiceException.hpp.
References errCode, and message.
~ServiceException()
ServiceException::~ServiceException () inline
Definition at line 77 of file ServiceException.hpp.
Member Function Documentation
getErrorCode()
ErrorCode ServiceException::getErrorCode () inline
Definition at line 79 of file ServiceException.hpp.
References errCode.
Referenced by LocalMacroSpaceManager::processServiceException(), LocalQueueManager::processServiceException(), LocalRegistrationManager::processServiceException(), and ServiceMessage::setExceptionInfo().
getMessage()
const char* ServiceException::getMessage () inline
Definition at line 81 of file ServiceException.hpp.
References message.
Referenced by ServiceMessage::setExceptionInfo().
Member Data Documentation
errCode
ErrorCode ServiceException::errCode protected
Definition at line 83 of file ServiceException.hpp.
Referenced by getErrorCode(), and ServiceException().
message
const char* ServiceException::message protected
Definition at line 84 of file ServiceException.hpp.
Referenced by getMessage(), and ServiceException().
The documentation for this class was generated from the following file:
ServiceException.hpp