executor.master: RexxSmartBuffer Class Reference
RexxSmartBuffer Class Reference
#include <RexxSmartBuffer.hpp>
Public Member Functions
void * operator new (size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxSmartBuffer (size_t)
RexxSmartBuffer (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
size_t copyData (void *, size_t)
size_t getCurrent ()
size_t getDataLength ()
RexxBuffer * getBuffer ()
void setBuffer (RexxBuffer *b)
size_t space ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxText * makeText ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxText * textValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Protected Attributes
size_t current
RexxBuffer * buffer
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 47 of file RexxSmartBuffer.hpp.
Constructor & Destructor Documentation
RexxSmartBuffer() [1/2]
RexxSmartBuffer::RexxSmartBuffer (size_t startSize)
Definition at line 50 of file RexxSmartBuffer.cpp.
References buffer, new_buffer(), and OrefSet.
RexxSmartBuffer() [2/2]
RexxSmartBuffer::RexxSmartBuffer (RESTORETYPE restoreType) inline
Definition at line 55 of file RexxSmartBuffer.hpp.
Member Function Documentation
copyData()
size_t RexxSmartBuffer::copyData (void * start, size_t length)
Definition at line 87 of file RexxSmartBuffer.cpp.
References buffer, RexxBufferBase::copyData(), current, RexxBuffer::expand(), OrefSet, and space().
Referenced by RexxEnvelope::copyBuffer(), and RexxSource::initBuffered().
flatten()
void RexxSmartBuffer::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 75 of file RexxSmartBuffer.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
getBuffer()
RexxBuffer* RexxSmartBuffer::getBuffer () inline
Definition at line 63 of file RexxSmartBuffer.hpp.
References buffer.
Referenced by RexxEnvelope::bufferStart(), RexxEnvelope::copyBuffer(), RexxSource::initBuffered(), and RexxEnvelope::pack().
getCurrent()
size_t RexxSmartBuffer::getCurrent () inline
Definition at line 61 of file RexxSmartBuffer.hpp.
References current.
getDataLength()
size_t RexxSmartBuffer::getDataLength () inline
Definition at line 62 of file RexxSmartBuffer.hpp.
References current.
Referenced by RexxEnvelope::pack().
live()
void RexxSmartBuffer::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 60 of file RexxSmartBuffer.cpp.
References buffer, and memory_mark.
liveGeneral()
void RexxSmartBuffer::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 67 of file RexxSmartBuffer.cpp.
References buffer, and memory_mark_general.
operator delete() [1/2]
void RexxSmartBuffer::operator delete (void *) inline
Definition at line 51 of file RexxSmartBuffer.hpp.
operator delete() [2/2]
void RexxSmartBuffer::operator delete (void * , void *) inline
Definition at line 52 of file RexxSmartBuffer.hpp.
operator new() [1/2]
void* RexxSmartBuffer::operator new (size_t size, void * ptr) inline
Definition at line 50 of file RexxSmartBuffer.hpp.
operator new() [2/2]
void * RexxSmartBuffer::operator new (size_t size)
Definition at line 110 of file RexxSmartBuffer.cpp.
References new_object(), and T_SmartBuffer.
setBuffer()
void RexxSmartBuffer::setBuffer (RexxBuffer * b) inline
Definition at line 64 of file RexxSmartBuffer.hpp.
References buffer.
space()
size_t RexxSmartBuffer::space ()
Definition at line 118 of file RexxSmartBuffer.cpp.
References buffer, current, and RexxBufferBase::getBufferSize().
Referenced by copyData().
Member Data Documentation
buffer
RexxBuffer* RexxSmartBuffer::buffer protected
Definition at line 69 of file RexxSmartBuffer.hpp.
Referenced by copyData(), getBuffer(), live(), liveGeneral(), RexxSmartBuffer(), setBuffer(), and space().
current
size_t RexxSmartBuffer::current protected
Definition at line 68 of file RexxSmartBuffer.hpp.
Referenced by copyData(), getCurrent(), getDataLength(), and space().
The documentation for this class was generated from the following files:
RexxSmartBuffer.hpp
RexxSmartBuffer.cpp