executor.master: RexxSourceLiteral Class Reference
RexxSourceLiteral Class Reference
#include <BlockClass.hpp>
Public Member Functions
void * operator new (size_t, void *ptr)
void operator delete (void *, void *)
void * operator new (size_t)
void operator delete (void *)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
RexxSourceLiteral (RexxString *, PackageClass *, size_t)
RexxSourceLiteral (RESTORETYPE restoreType)
RexxArray * getSource ()
PackageClass * getPackage ()
RexxString * getKind ()
RexxObject * getRawExecutable ()
bool isClosure ()
RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Private Attributes
RexxArray * source
PackageClass * package
RexxString * kind
RexxObject * rawExecutable
bool closure
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 52 of file BlockClass.hpp.
Constructor & Destructor Documentation
RexxSourceLiteral() [1/2]
RexxSourceLiteral::RexxSourceLiteral (RexxString * s, PackageClass * p, size_t startLine)
Definition at line 105 of file BlockClass.cpp.
References closure, RexxArray::copy(), RexxString::getStringData(), kind, RexxString::makeArrayRexx(), new_string(), package, rawExecutable, RexxObject::sendMessage(), source, TheEnvironment, and TheTrueObject.
RexxSourceLiteral() [2/2]
RexxSourceLiteral::RexxSourceLiteral (RESTORETYPE restoreType) inline
Definition at line 65 of file BlockClass.hpp.
Member Function Documentation
evaluate()
RexxObject * RexxSourceLiteral::evaluate (RexxActivation * context, RexxExpressionStack * stack) virtual
Reimplemented from RexxInternalObject.
Definition at line 142 of file BlockClass.cpp.
References RexxActivation::getContextObject(), RexxExpressionStack::push(), TRACE_PREFIX_LITERAL, and RexxActivation::traceIntermediate().
flatten()
void RexxSourceLiteral::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 89 of file BlockClass.cpp.
References cleanUpFlatten, OREF_NULL, and setUpFlatten.
getKind()
RexxString* RexxSourceLiteral::getKind () inline
Definition at line 69 of file BlockClass.hpp.
References kind.
Referenced by RexxBlock::getKind().
getPackage()
PackageClass* RexxSourceLiteral::getPackage () inline
Definition at line 68 of file BlockClass.hpp.
References package.
Referenced by RexxBlock::getPackage().
getRawExecutable()
RexxObject* RexxSourceLiteral::getRawExecutable () inline
Definition at line 70 of file BlockClass.hpp.
References rawExecutable.
Referenced by RexxBlock::getRawExecutable().
getSource()
RexxArray* RexxSourceLiteral::getSource () inline
Definition at line 67 of file BlockClass.hpp.
References source.
Referenced by RexxBlock::getSource().
isClosure()
bool RexxSourceLiteral::isClosure () inline
Definition at line 71 of file BlockClass.hpp.
References closure.
Referenced by RexxBlock::RexxBlock().
live()
void RexxSourceLiteral::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 67 of file BlockClass.cpp.
References kind, memory_mark, package, rawExecutable, and source.
liveGeneral()
void RexxSourceLiteral::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 78 of file BlockClass.cpp.
References kind, memory_mark_general, package, rawExecutable, and source.
operator delete() [1/2]
void RexxSourceLiteral::operator delete (void *) inline
Definition at line 58 of file BlockClass.hpp.
operator delete() [2/2]
void RexxSourceLiteral::operator delete (void * , void *) inline
Definition at line 56 of file BlockClass.hpp.
operator new() [1/2]
void * RexxSourceLiteral::operator new (size_t size)
Allocate a new RexxSourceLiteral object
Parameters
size The size of the object.
Returns
The newly allocated object.
Definition at line 60 of file BlockClass.cpp.
References new_object(), and T_SourceLiteral.
operator new() [2/2]
void* RexxSourceLiteral::operator new (size_t , void * ptr) inline
Definition at line 55 of file BlockClass.hpp.
Member Data Documentation
closure
bool RexxSourceLiteral::closure private
Definition at line 80 of file BlockClass.hpp.
Referenced by isClosure(), and RexxSourceLiteral().
kind
RexxString* RexxSourceLiteral::kind private
Definition at line 78 of file BlockClass.hpp.
Referenced by getKind(), live(), liveGeneral(), and RexxSourceLiteral().
package
PackageClass* RexxSourceLiteral::package private
Definition at line 77 of file BlockClass.hpp.
Referenced by getPackage(), live(), liveGeneral(), and RexxSourceLiteral().
rawExecutable
RexxObject* RexxSourceLiteral::rawExecutable private
Definition at line 79 of file BlockClass.hpp.
Referenced by getRawExecutable(), live(), liveGeneral(), and RexxSourceLiteral().
source
RexxArray* RexxSourceLiteral::source private
Definition at line 76 of file BlockClass.hpp.
Referenced by getSource(), live(), liveGeneral(), and RexxSourceLiteral().
The documentation for this class was generated from the following files:
BlockClass.hpp
BlockClass.cpp