executor.master: AutoClose Class Reference
AutoClose Class Reference
Public Member Functions
AutoClose ()
AutoClose (int fd)
~AutoClose ()
AutoClose & operator= (int fd)
operator int () const
int operator== (int fd)
int close (bool returnError=true)
Private Attributes
int value
Detailed Description
Definition at line 5395 of file unix/rexxutil.cpp.
Constructor & Destructor Documentation
AutoClose() [1/2]
AutoClose::AutoClose () inline
Definition at line 5398 of file unix/rexxutil.cpp.
AutoClose() [2/2]
AutoClose::AutoClose (int fd) inline
Definition at line 5399 of file unix/rexxutil.cpp.
~AutoClose()
AutoClose::~AutoClose () inline
Definition at line 5400 of file unix/rexxutil.cpp.
References close().
Member Function Documentation
close()
int AutoClose::close (bool returnError = true)
Definition at line 5410 of file unix/rexxutil.cpp.
References value.
Referenced by CopyFile_DereferenceSymbolicLinks(), operator=(), and ~AutoClose().
operator int()
AutoClose::operator int () const inline
Definition at line 5402 of file unix/rexxutil.cpp.
References value.
operator=()
AutoClose& AutoClose::operator= (int fd) inline
Definition at line 5401 of file unix/rexxutil.cpp.
References close(), and value.
operator==()
int AutoClose::operator== (int fd) inline
Definition at line 5403 of file unix/rexxutil.cpp.
References value.
Member Data Documentation
value
int AutoClose::value private
Definition at line 5406 of file unix/rexxutil.cpp.
Referenced by close(), operator int(), operator=(), and operator==().
The documentation for this class was generated from the following file:
unix/rexxutil.cpp