executor.master: SysMutex Class Reference
SysMutex Class Reference
#include <SysSemaphore.hpp>
Public Member Functions
SysMutex (const char *variable)
SysMutex (const char *, bool)
~SysMutex ()
void create ()
void open ()
void close ()
void request (const char *ds, int di)
void release (const char *ds, int di)
bool requestImmediate (const char *ds, int di)
SysMutex (const char *variable)
SysMutex (const char *, bool)
~SysMutex ()
void create ()
void close ()
void request (const char *ds, int di)
void release (const char *ds, int di)
bool requestImmediate (const char *ds, int di)
Protected Attributes
const char * mutexVariable
pthread_mutex_t mutexMutex
bool created
HANDLE mutexMutex
Detailed Description
Definition at line 78 of file unix/SysSemaphore.hpp.
Constructor & Destructor Documentation
SysMutex() [1/4]
SysMutex::SysMutex (const char * variable) inline
Definition at line 80 of file unix/SysSemaphore.hpp.
SysMutex() [2/4]
SysMutex::SysMutex (const char * variable, bool createSem)
Create a semaphore with potential creation-time initialization.
Parameters
create Indicates whether the semaphore should be created now.
Definition at line 266 of file unix/SysSemaphore.cpp.
References create(), and mutexVariable.
~SysMutex() [1/2]
SysMutex::~SysMutex () inline
Definition at line 82 of file unix/SysSemaphore.hpp.
SysMutex() [3/4]
SysMutex::SysMutex (const char * variable) inline
Definition at line 142 of file windows/SysSemaphore.hpp.
SysMutex() [4/4]
SysMutex::SysMutex (const char * , bool)
~SysMutex() [2/2]
SysMutex::~SysMutex () inline
Definition at line 144 of file windows/SysSemaphore.hpp.
Member Function Documentation
close() [1/2]
void SysMutex::close ()
Definition at line 324 of file unix/SysSemaphore.cpp.
References created, and mutexMutex.
Referenced by ActivityManager::closeLocks(), RexxMemory::closeLocks(), and Interpreter::closeLocks().
close() [2/2]
void SysMutex::close ()
create() [1/2]
void SysMutex::create ()
Definition at line 275 of file unix/SysSemaphore.cpp.
References created, and mutexMutex.
Referenced by ActivityManager::createLocks(), RexxMemory::createLocks(), Interpreter::createLocks(), APIServer::initServer(), ServerMacroSpaceManager::ServerMacroSpaceManager(), ServerQueueManager::ServerQueueManager(), ServerRegistrationManager::ServerRegistrationManager(), and SysMutex().
create() [2/2]
void SysMutex::create ()
open()
void SysMutex::open () inline
Definition at line 84 of file unix/SysSemaphore.hpp.
release() [1/2]
void SysMutex::release (const char * ds, int di) inline
Definition at line 106 of file unix/SysSemaphore.hpp.
References ConcurrencyInfos::activation, CONCURRENCY_TRACE, dbgprintf(), Utilities::GetConcurrencyInfos(), ConcurrencyInfos::lock, mutexMutex, mutexVariable, ConcurrencyInfos::reserveCount, ConcurrencyInfos::threadId, Utilities::traceConcurrency(), and ConcurrencyInfos::variableDictionary.
Referenced by APIServer::releaseLock(), Interpreter::releaseResourceLock(), RexxMemory::returnFlattenStack(), RexxMemory::setEnvelope(), RexxMemory::setObjectOffset(), ActivityManager::unlockKernel(), and Lock::~Lock().
release() [2/2]
void SysMutex::release (const char * ds, int di) inline
Definition at line 168 of file windows/SysSemaphore.hpp.
References ConcurrencyInfos::activation, CONCURRENCY_TRACE, dbgprintf(), Utilities::GetConcurrencyInfos(), ConcurrencyInfos::lock, mutexMutex, mutexVariable, ConcurrencyInfos::reserveCount, ConcurrencyInfos::threadId, Utilities::traceConcurrency(), and ConcurrencyInfos::variableDictionary.
request() [1/2]
void SysMutex::request (const char * ds, int di) inline
Definition at line 86 of file unix/SysSemaphore.hpp.
References ConcurrencyInfos::activation, CONCURRENCY_TRACE, dbgprintf(), Utilities::GetConcurrencyInfos(), ConcurrencyInfos::lock, mutexMutex, mutexVariable, ConcurrencyInfos::reserveCount, ConcurrencyInfos::threadId, Utilities::traceConcurrency(), and ConcurrencyInfos::variableDictionary.
Referenced by RexxMemory::getFlattenStack(), Interpreter::getResourceLock(), Lock::Lock(), ActivityManager::lockKernel(), APIServer::requestLock(), RexxMemory::setEnvelope(), and RexxMemory::setObjectOffset().
request() [2/2]
void SysMutex::request (const char * ds, int di) inline
Definition at line 147 of file windows/SysSemaphore.hpp.
References ConcurrencyInfos::activation, CONCURRENCY_TRACE, dbgprintf(), Utilities::GetConcurrencyInfos(), ConcurrencyInfos::lock, mutexMutex, mutexVariable, ConcurrencyInfos::reserveCount, ConcurrencyInfos::threadId, Utilities::traceConcurrency(), ConcurrencyInfos::variableDictionary, and waitHandle().
requestImmediate() [1/2]
bool SysMutex::requestImmediate (const char * ds, int di) inline
Definition at line 126 of file unix/SysSemaphore.hpp.
References ConcurrencyInfos::activation, CONCURRENCY_TRACE, dbgprintf(), Utilities::GetConcurrencyInfos(), ConcurrencyInfos::lock, mutexMutex, mutexVariable, ConcurrencyInfos::reserveCount, ConcurrencyInfos::threadId, Utilities::traceConcurrency(), and ConcurrencyInfos::variableDictionary.
Referenced by RexxMemory::getFlattenStack(), ActivityManager::lockKernelImmediate(), RexxMemory::setEnvelope(), and RexxMemory::setObjectOffset().
requestImmediate() [2/2]
bool SysMutex::requestImmediate (const char * ds, int di) inline
Definition at line 189 of file windows/SysSemaphore.hpp.
References ConcurrencyInfos::activation, CONCURRENCY_TRACE, dbgprintf(), Utilities::GetConcurrencyInfos(), ConcurrencyInfos::lock, mutexMutex, mutexVariable, ConcurrencyInfos::reserveCount, ConcurrencyInfos::threadId, Utilities::traceConcurrency(), and ConcurrencyInfos::variableDictionary.
Member Data Documentation
created
bool SysMutex::created protected
Definition at line 151 of file unix/SysSemaphore.hpp.
Referenced by close(), and create().
mutexMutex [1/2]
pthread_mutex_t SysMutex::mutexMutex protected
Definition at line 150 of file unix/SysSemaphore.hpp.
Referenced by close(), create(), release(), request(), and requestImmediate().
mutexMutex [2/2]
HANDLE SysMutex::mutexMutex protected
Definition at line 213 of file windows/SysSemaphore.hpp.
mutexVariable
const char * SysMutex::mutexVariable protected
Definition at line 149 of file unix/SysSemaphore.hpp.
Referenced by release(), request(), requestImmediate(), and SysMutex().
The documentation for this class was generated from the following files:
unix/SysSemaphore.hpp
windows/SysSemaphore.hpp
unix/SysSemaphore.cpp
windows/SysSemaphore.cpp