executor.master: RexxNilObject Class Reference
RexxNilObject Class Reference
#include <ObjectClass.hpp>
Public Member Functions
void * operator new (size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *)
void operator delete (void *, void *)
RexxNilObject ()
RexxNilObject (RESTORETYPE restoreType)
virtual ~RexxNilObject ()
virtual HashCode getHashValue ()
Public Member Functions inherited from RexxObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *, void *)
void operator delete (void *)
void operator delete (void *, RexxClass *)
void operator delete (void *, RexxClass *, RexxObject **, size_t)
RexxObject * newRexx (RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxObject * newObject ()
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
virtual RexxObject * defMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
virtual RexxString * defaultName ()
virtual RexxObject * unknown (RexxString *msg, RexxArray *args, RexxDirectory *named_args)
virtual RexxInteger * hasMethod (RexxString *msg)
bool hasUninitMethod ()
RexxObject * init ()
void uninit ()
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
RexxObject * copy ()
HashCode hash ()
bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
RexxNumberString * numberString ()
RexxInteger * integerValue (size_t)
RexxString * makeString ()
RexxString * primitiveMakeString ()
void copyIntoTail (RexxCompoundTail *buffer)
RexxArray * makeArray ()
RexxString * stringValue ()
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (size_t)
bool requestNumber (wholenumber_t &, size_t)
bool requestUnsignedNumber (stringsize_t &, size_t)
RexxArray * requestArray ()
RexxDirectory * requestDirectory ()
RexxString * requiredString (RexxString *kind, size_t)
RexxString * requiredString (RexxString *kind, const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (RexxString *kind, size_t, size_t)
wholenumber_t requiredNumber (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredPositive (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredNonNegative (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
bool isEqual (RexxObject *)
bool isInstanceOf (RexxClass *)
RexxObject * isInstanceOfRexx (RexxClass *)
RexxMethod * instanceMethod (RexxString *)
RexxSupplier * instanceMethods (RexxClass *)
RexxMethod * instanceMethodRexx (RexxString *)
RexxSupplier * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
RexxMessage * start (RexxObject **, size_t, size_t)
RexxMessage * startWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxObject * send (RexxObject **, size_t, size_t)
RexxObject * sendWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxMessage * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxString * oref ()
RexxObject * pmdict ()
RexxObject * run (RexxObject **, size_t, size_t)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, ProtectedObject &, bool processUnknown=true)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, RexxObject *, ProtectedObject &, bool processUnknown=true)
RexxMethod * checkPrivate (RexxMethod *)
void processUnknown (RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
void processProtectedMethod (RexxString *, RexxMethod *, RexxObject **, size_t, size_t, ProtectedObject &)
void sendMessage (RexxString *, RexxArray *, RexxDirectory *, ProtectedObject &)
void sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount, ProtectedObject &result)
void sendMessage (RexxString *message, ProtectedObject &result)
void sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
void sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxArray *, RexxDirectory *=OREF_NULL)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount)
RexxObject * sendMessage (RexxString *message)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * defMethods (RexxDirectory *)
void setObjectVariable (RexxString *, RexxObject *, RexxObject *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxObject *)
void addObjectVariables (RexxVariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxObject * superScope (RexxObject *)
RexxMethod * superMethod (RexxString *, RexxObject *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
const char * idString ()
RexxString * id ()
RexxMethod * methodLookup (RexxString *name)
RexxVariableDictionary * getObjectVariables (RexxObject *)
void guardOn (RexxActivity *activity, RexxObject *scope)
void guardOff (RexxActivity *activity, RexxObject *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
RexxObject * unknownRexx (RexxString *, RexxArray *, RexxObject **, size_t)
RexxObject * hasMethodRexx (RexxString *)
void * getCSelf ()
void * getCSelf (RexxObject *scope)
bool equalValue (RexxObject *other)
virtual wholenumber_t compareTo (RexxObject *)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) RexxVariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
HashCode identityHash ()
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Static Public Attributes
static RexxObject * nilObject = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
HashCode hashValue
Additional Inherited Members
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, RexxString *&messageName, RexxObject *&startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 577 of file ObjectClass.hpp.
Constructor & Destructor Documentation
RexxNilObject() [1/2]
RexxNilObject::RexxNilObject ()
Create the NIL object instance.
Definition at line 2781 of file ObjectClass.cpp.
References hashValue, and RexxInternalObject::identityHash().
RexxNilObject() [2/2]
RexxNilObject::RexxNilObject (RESTORETYPE restoreType) inline
Definition at line 584 of file ObjectClass.hpp.
~RexxNilObject()
virtual RexxNilObject::~RexxNilObject () inline virtual
Definition at line 585 of file ObjectClass.hpp.
Member Function Documentation
getHashValue()
HashCode RexxNilObject::getHashValue () virtual
Override of the default hash value method.
Reimplemented from RexxInternalObject.
Definition at line 2790 of file ObjectClass.cpp.
References hashValue.
operator delete() [1/2]
void RexxNilObject::operator delete (void *) inline
Definition at line 581 of file ObjectClass.hpp.
operator delete() [2/2]
void RexxNilObject::operator delete (void * , void *) inline
Definition at line 582 of file ObjectClass.hpp.
operator new() [1/2]
void* RexxNilObject::operator new (size_t size, void * objectPtr) inline
Definition at line 580 of file ObjectClass.hpp.
operator new() [2/2]
void * RexxNilObject::operator new (size_t size)
new operator for creating a RexxNilObject
Definition at line 2865 of file ObjectClass.cpp.
References new_object(), RexxInternalObject::setVirtualFunctions(), T_NilObject, T_Object, and RexxMemory::virtualFunctionTable.
Member Data Documentation
hashValue
HashCode RexxNilObject::hashValue protected
Definition at line 594 of file ObjectClass.hpp.
Referenced by getHashValue(), and RexxNilObject().
nilObject
RexxObject * RexxNilObject::nilObject = OREF_NULL static
Definition at line 589 of file ObjectClass.hpp.
The documentation for this class was generated from the following files:
ObjectClass.hpp
ObjectClass.cpp