executor.master: TrigFormatter Class Reference
TrigFormatter Class Reference
Public Member Functions
TrigFormatter (RexxCallContext *c, bool explicitPrecision, uint32_t p, const char *u)
RexxObjectPtr evaluate (double angle, int function)
RexxObjectPtr evaluateArc (double x, int function)
Public Member Functions inherited from NumericFormatter
NumericFormatter (RexxCallContext *c, bool explicitPrecision, uint32_t p)
RexxObjectPtr format (double x)
Protected Types
enum Units { DEGREES , RADIANS , GRADES }
Protected Attributes
Units units
Protected Attributes inherited from NumericFormatter
uint32_t precision
RexxCallContext * context
bool optionError
Detailed Description
Definition at line 178 of file rxmath.cpp.
Member Enumeration Documentation
Units
enum TrigFormatter::Units protected
Enumerator
DEGREES
RADIANS
GRADES
Definition at line 361 of file rxmath.cpp.
Constructor & Destructor Documentation
TrigFormatter()
TrigFormatter::TrigFormatter (RexxCallContext * c, bool explicitPrecision, uint32_t p, const char * u) inline
Definition at line 182 of file rxmath.cpp.
References NumericFormatter::context, DEGREES, GRADES, NumericFormatter::optionError, RADIANS, and units.
Member Function Documentation
evaluate()
RexxObjectPtr TrigFormatter::evaluate (double angle, int function) inline
Definition at line 212 of file rxmath.cpp.
References COSINE, COTANGENT, DEGREES, NumericFormatter::format(), GRADES, MAXTRIG, NULLOBJECT, NumericFormatter::optionError, pi, RADIANS, SINE, TANGENT, and units.
Referenced by RexxRoutine3().
evaluateArc()
RexxObjectPtr TrigFormatter::evaluateArc (double x, int function) inline
Definition at line 321 of file rxmath.cpp.
References ARCCOSINE, ARCSINE, ARCTANGENT, DEGREES, NumericFormatter::format(), GRADES, NULLOBJECT, NumericFormatter::optionError, pi, and units.
Referenced by RexxRoutine3().
Member Data Documentation
units
Units TrigFormatter::units protected
Definition at line 368 of file rxmath.cpp.
Referenced by evaluate(), evaluateArc(), and TrigFormatter().
The documentation for this class was generated from the following file:
rxmath.cpp