executor.master: MemorySegmentPool Class Reference
MemorySegmentPool Class Reference
#include <RexxMemory.hpp>
Public Member Functions
void * operator new (size_t size, size_t minSize)
void * operator new (size_t size, void *pool)
void operator delete (void *)
void operator delete (void *, size_t)
void operator delete (void *, void *)
MemorySegmentPool ()
MemorySegment * newSegment (size_t minSize)
MemorySegment * newLargeSegment (size_t minSize)
void freePool (void)
MemorySegmentPool * nextPool ()
void setNext (MemorySegmentPool *nextPool)
Static Public Member Functions
static MemorySegmentPool * createPool ()
Private Attributes
char state [8]
Friends
bool SysAccessPool (MemorySegmentPool **)
Additional Inherited Members
Protected Attributes inherited from MemorySegmentPoolHeader
MemorySegmentPool * next
MemorySegment * spareSegment
char * nextAlloc
char * nextLargeAlloc
size_t uncommitted
size_t reserved
Detailed Description
Definition at line 140 of file RexxMemory.hpp.
Constructor & Destructor Documentation
MemorySegmentPool()
MemorySegmentPool::MemorySegmentPool ()
Definition at line 172 of file unix/MemorySupport.cpp.
References MemorySegmentPoolHeader::next.
Member Function Documentation
createPool()
MemorySegmentPool * MemorySegmentPool::createPool () static
Create a the initial memory pool for the interpreter.
Parameters
pool pointer for the returned pool.
Returns
Definition at line 80 of file unix/MemorySupport.cpp.
References Error_System_resources, MemorySegmentPoolOverhead, MEMSIZE, MemorySegmentPoolHeader::nextAlloc, MemorySegmentPoolHeader::nextLargeAlloc, PAGESIZE, reportException(), MemorySegmentPoolHeader::reserved, RXROUNDUP, SegmentSize, MemorySegmentPoolHeader::spareSegment, and MemorySegmentPoolHeader::uncommitted.
Referenced by RexxMemory::initialize().
freePool()
void MemorySegmentPool::freePool (void)
Definition at line 276 of file unix/MemorySupport.cpp.
Referenced by RexxMemory::shutdown().
newLargeSegment()
MemorySegment * MemorySegmentPool::newLargeSegment (size_t minSize)
Definition at line 227 of file unix/MemorySupport.cpp.
References memoryObject, RexxMemory::memoryPoolAdded(), newLargeSegment(), MemorySegmentPoolHeader::next, MemorySegmentPoolHeader::nextLargeAlloc, PAGESIZE, RXROUNDUP, MemorySegment::size(), MemorySegmentPoolHeader::spareSegment, and MemorySegmentPoolHeader::uncommitted.
Referenced by newLargeSegment(), and RexxMemory::newLargeSegment().
newSegment()
MemorySegment * MemorySegmentPool::newSegment (size_t minSize)
Definition at line 182 of file unix/MemorySupport.cpp.
References memoryObject, RexxMemory::memoryPoolAdded(), newSegment(), MemorySegmentPoolHeader::next, MemorySegmentPoolHeader::nextAlloc, PAGESIZE, RXROUNDUP, MemorySegment::size(), MemorySegmentPoolHeader::spareSegment, and MemorySegmentPoolHeader::uncommitted.
Referenced by newSegment(), and RexxMemory::newSegment().
nextPool()
MemorySegmentPool* MemorySegmentPool::nextPool () inline
Definition at line 159 of file RexxMemory.hpp.
References MemorySegmentPoolHeader::next.
Referenced by RexxMemory::dump(), and RexxMemory::shutdown().
operator delete() [1/3]
void MemorySegmentPool::operator delete (void *) inline
Definition at line 149 of file RexxMemory.hpp.
operator delete() [2/3]
void MemorySegmentPool::operator delete (void * , size_t) inline
Definition at line 150 of file RexxMemory.hpp.
operator delete() [3/3]
void MemorySegmentPool::operator delete (void * , void *) inline
Definition at line 151 of file RexxMemory.hpp.
operator new() [1/2]
void * MemorySegmentPool::operator new (size_t size, size_t minSize)
Definition at line 124 of file unix/MemorySupport.cpp.
References Error_System_resources, MemorySegmentPoolOverhead, MEMSIZE, MemorySegmentPoolHeader::nextAlloc, MemorySegmentPoolHeader::nextLargeAlloc, PAGESIZE, reportException(), MemorySegmentPoolHeader::reserved, RXROUNDUP, SegmentSize, MemorySegmentPoolHeader::spareSegment, and MemorySegmentPoolHeader::uncommitted.
operator new() [2/2]
void* MemorySegmentPool::operator new (size_t size, void * pool) inline
Definition at line 148 of file RexxMemory.hpp.
setNext()
void MemorySegmentPool::setNext (MemorySegmentPool * nextPool)
Definition at line 285 of file unix/MemorySupport.cpp.
References MemorySegmentPoolHeader::next.
Friends And Related Function Documentation
SysAccessPool
bool SysAccessPool (MemorySegmentPool **) friend
Member Data Documentation
state
char MemorySegmentPool::state[8] private
Definition at line 163 of file RexxMemory.hpp.
The documentation for this class was generated from the following files:
RexxMemory.hpp
unix/MemorySupport.cpp
windows/MemorySupport.cpp