executor.master: FlagSet< TEnum, TMaxFlags > Class Template Reference
FlagSet< TEnum, TMaxFlags > Class Template Reference
#include <FlagSet.hpp>
Classes
class FlagSetReference
Public Member Functions
FlagSet ()
FlagSet (const TEnum f1)
FlagSet (const TEnum f1, const TEnum f2)
FlagSet (const TEnum f1, const TEnum f2, const TEnum f3)
FlagSet (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4)
FlagSet (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4, const TEnum f5)
FlagSet (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4, const TEnum f5, const TEnum f6)
void set (const TEnum flag, bool val=true)
void set ()
void set (const TEnum f1, const TEnum f2)
void set (const TEnum f1, const TEnum f2, const TEnum f3)
void set (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4)
void reset ()
void reset (const TEnum flag)
void reset (const TEnum f1, const TEnum f2)
void reset (const TEnum f1, const TEnum f2, const TEnum f3)
void reset (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4)
void flip (const TEnum flag)
void flip ()
bool test (const TEnum flag)
bool operator[] (const TEnum flag) const
FlagSetReference operator[] (const TEnum flag)
bool any () const
bool any (const TEnum flag1, const TEnum flag2)
bool any (const TEnum flag1, const TEnum flag2, const TEnum flag3)
bool all () const
bool all (const TEnum flag1, const TEnum flag2)
bool all (const TEnum flag1, const TEnum flag2, const TEnum flag3)
bool none () const
Private Attributes
BitSet< TMaxFlags > flags
Detailed Description
template<typename TEnum, int TMaxFlags = 8>
class FlagSet< TEnum, TMaxFlags >
Definition at line 53 of file FlagSet.hpp.
Constructor & Destructor Documentation
FlagSet() [1/7]
template<typename TEnum , int TMaxFlags = 8> FlagSet< TEnum, TMaxFlags >::FlagSet () inline
Definition at line 89 of file FlagSet.hpp.
FlagSet() [2/7]
template<typename TEnum , int TMaxFlags = 8> FlagSet< TEnum, TMaxFlags >::FlagSet (const TEnum f1) inline
Definition at line 92 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::set().
FlagSet() [3/7]
template<typename TEnum , int TMaxFlags = 8> FlagSet< TEnum, TMaxFlags >::FlagSet (const TEnum f1, const TEnum f2) inline
Definition at line 97 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::set().
FlagSet() [4/7]
template<typename TEnum , int TMaxFlags = 8> FlagSet< TEnum, TMaxFlags >::FlagSet (const TEnum f1, const TEnum f2, const TEnum f3) inline
Definition at line 103 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::set().
FlagSet() [5/7]
template<typename TEnum , int TMaxFlags = 8> FlagSet< TEnum, TMaxFlags >::FlagSet (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4) inline
Definition at line 110 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::set().
FlagSet() [6/7]
template<typename TEnum , int TMaxFlags = 8> FlagSet< TEnum, TMaxFlags >::FlagSet (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4, const TEnum f5) inline
Definition at line 118 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::set().
FlagSet() [7/7]
template<typename TEnum , int TMaxFlags = 8> FlagSet< TEnum, TMaxFlags >::FlagSet (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4, const TEnum f5, const TEnum f6) inline
Definition at line 127 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::set().
Member Function Documentation
all() [1/3]
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::all () const inline
Definition at line 272 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
all() [2/3]
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::all (const TEnum flag1, const TEnum flag2) inline
Definition at line 280 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
all() [3/3]
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::all (const TEnum flag1, const TEnum flag2, const TEnum flag3) inline
Definition at line 286 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
any() [1/3]
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::any () const inline
Definition at line 253 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
any() [2/3]
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::any (const TEnum flag1, const TEnum flag2) inline
Definition at line 259 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
any() [3/3]
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::any (const TEnum flag1, const TEnum flag2, const TEnum flag3) inline
Definition at line 265 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
flip() [1/2]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::flip () inline
Definition at line 226 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
flip() [2/2]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::flip (const TEnum flag) inline
Definition at line 219 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
none()
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::none () const inline
Definition at line 292 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
operator[]() [1/2]
template<typename TEnum , int TMaxFlags = 8> FlagSetReference FlagSet< TEnum, TMaxFlags >::operator[] (const TEnum flag) inline
Definition at line 246 of file FlagSet.hpp.
operator[]() [2/2]
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::operator[] (const TEnum flag) const inline
Definition at line 240 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
reset() [1/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::reset (void) inline
Definition at line 179 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
reset() [2/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::reset (const TEnum f1, const TEnum f2) inline
Definition at line 192 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
reset() [3/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::reset (const TEnum f1, const TEnum f2, const TEnum f3) inline
Definition at line 200 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
reset() [4/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::reset (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4) inline
Definition at line 209 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
reset() [5/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::reset (const TEnum flag) inline
Definition at line 185 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
set() [1/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::set () inline
Definition at line 145 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
Referenced by FlagSet< TEnum, TMaxFlags >::FlagSet().
set() [2/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::set (const TEnum f1, const TEnum f2) inline
Definition at line 152 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
set() [3/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::set (const TEnum f1, const TEnum f2, const TEnum f3) inline
Definition at line 160 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
set() [4/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::set (const TEnum f1, const TEnum f2, const TEnum f3, const TEnum f4) inline
Definition at line 169 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
set() [5/5]
template<typename TEnum , int TMaxFlags = 8> void FlagSet< TEnum, TMaxFlags >::set (const TEnum flag, bool val = true) inline
Definition at line 138 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
test()
template<typename TEnum , int TMaxFlags = 8> bool FlagSet< TEnum, TMaxFlags >::test (const TEnum flag) inline
Definition at line 233 of file FlagSet.hpp.
References FlagSet< TEnum, TMaxFlags >::flags.
Member Data Documentation
flags
template<typename TEnum , int TMaxFlags = 8> BitSet<TMaxFlags> FlagSet< TEnum, TMaxFlags >::flags private
Definition at line 299 of file FlagSet.hpp.
Referenced by FlagSet< TEnum, TMaxFlags >::all(), FlagSet< TEnum, TMaxFlags >::any(), FlagSet< TEnum, TMaxFlags >::flip(), FlagSet< TEnum, TMaxFlags >::none(), FlagSet< TEnum, TMaxFlags >::operator[](), FlagSet< TEnum, TMaxFlags >::reset(), FlagSet< TEnum, TMaxFlags >::set(), and FlagSet< TEnum, TMaxFlags >::test().
The documentation for this class was generated from the following file:
FlagSet.hpp