executor.master: ActivityDispatcher Class Reference
ActivityDispatcher Class Reference
#include <ActivityDispatcher.hpp>
Public Member Functions
ActivityDispatcher ()
virtual ~ActivityDispatcher ()
virtual void run ()
virtual void handleError (wholenumber_t, RexxDirectory *)
virtual void handleError (RexxDirectory *)
virtual void invoke ()
virtual void invoke (RexxOption *)
virtual void invoke (PRXSYSEXIT exits, const char *env)
void setContext (RexxActivity *act, RexxNativeActivation *a)
Public Attributes
wholenumber_t rc
RexxDirectory * conditionData
Protected Attributes
RexxActivity * activity
RexxNativeActivation * activation
Detailed Description
Definition at line 47 of file ActivityDispatcher.hpp.
Constructor & Destructor Documentation
ActivityDispatcher()
ActivityDispatcher::ActivityDispatcher () inline
Definition at line 50 of file ActivityDispatcher.hpp.
~ActivityDispatcher()
virtual ActivityDispatcher::~ActivityDispatcher () inline virtual
Definition at line 51 of file ActivityDispatcher.hpp.
Member Function Documentation
handleError() [1/2]
void ActivityDispatcher::handleError (RexxDirectory * c) virtual
Default handler for any error conditions. This just sets the condition information in the dispatch unit.
Parameters
c The condition information for the error.
Definition at line 76 of file ActivityDispatcher.cpp.
References activity, RexxActivity::errorNumber(), handleError(), and OREF_NULL.
handleError() [2/2]
void ActivityDispatcher::handleError (wholenumber_t r, RexxDirectory * c) virtual
Default handler for any error conditions. This just sets the condition information in the dispatch unit.
Parameters
c The condition information for the error.
Reimplemented in MessageDispatcher, RexxStartDispatcher, TranslateDispatcher, and TranslateInstoreDispatcher.
Definition at line 62 of file ActivityDispatcher.cpp.
References conditionData, and rc.
Referenced by handleError(), MessageDispatcher::handleError(), RexxStartDispatcher::handleError(), TranslateDispatcher::handleError(), TranslateInstoreDispatcher::handleError(), RexxNativeActivation::run(), and RexxActivity::run().
invoke() [1/3]
void ActivityDispatcher::invoke () virtual
Invoke the dispatcher on a newly created interpreter instance.
Definition at line 89 of file ActivityDispatcher.cpp.
References InstanceBlock::activity, and RexxActivity::run().
Referenced by RexxStart(), RexxTranslateInstoreProgram(), and RexxTranslateProgram().
invoke() [2/3]
void ActivityDispatcher::invoke (PRXSYSEXIT exits, const char * env) virtual
Invoke the dispatcher on a newly created interpreter instance.
Definition at line 115 of file ActivityDispatcher.cpp.
References InstanceBlock::activity, and RexxActivity::run().
invoke() [3/3]
void ActivityDispatcher::invoke (RexxOption * options) virtual
Invoke the dispatcher on a newly created interpreter instance.
Definition at line 102 of file ActivityDispatcher.cpp.
References InstanceBlock::activity, and RexxActivity::run().
run()
void ActivityDispatcher::run () virtual
Default virtual method for handling a run() methods on an activity dispatcher.
Reimplemented in MessageDispatcher, RexxStartDispatcher, CallRoutineDispatcher, CallProgramDispatcher, TranslateDispatcher, and TranslateInstoreDispatcher.
Definition at line 50 of file ActivityDispatcher.cpp.
Referenced by RexxNativeActivation::run().
setContext()
void ActivityDispatcher::setContext (RexxActivity * act, RexxNativeActivation * a) inline
Definition at line 60 of file ActivityDispatcher.hpp.
References activation, and activity.
Referenced by RexxNativeActivation::run().
Member Data Documentation
activation
RexxNativeActivation* ActivityDispatcher::activation protected
Definition at line 68 of file ActivityDispatcher.hpp.
Referenced by MessageDispatcher::handleError(), RexxStartDispatcher::handleError(), TranslateDispatcher::handleError(), and setContext().
activity
RexxActivity* ActivityDispatcher::activity protected
Definition at line 67 of file ActivityDispatcher.hpp.
Referenced by handleError(), MessageDispatcher::handleError(), RexxStartDispatcher::handleError(), TranslateDispatcher::handleError(), RexxStartDispatcher::run(), CallRoutineDispatcher::run(), CallProgramDispatcher::run(), TranslateDispatcher::run(), and setContext().
conditionData
RexxDirectory* ActivityDispatcher::conditionData
Definition at line 63 of file ActivityDispatcher.hpp.
Referenced by handleError(), MessageDispatcher::handleError(), RexxStartDispatcher::handleError(), TranslateDispatcher::handleError(), and RexxActivity::run().
rc
wholenumber_t ActivityDispatcher::rc
Definition at line 62 of file ActivityDispatcher.hpp.
Referenced by handleError(), RexxStartDispatcher::handleError(), TranslateDispatcher::handleError(), TranslateInstoreDispatcher::handleError(), RexxStart(), RexxTranslateInstoreProgram(), RexxTranslateProgram(), and RexxStartDispatcher::run().
The documentation for this class was generated from the following files:
ActivityDispatcher.hpp
ActivityDispatcher.cpp