executor.master: ClientMessage Class Reference
ClientMessage Class Reference
#include <ClientMessage.hpp>
Public Member Functions
ClientMessage (ServerManager target, ServerOperation op)
ClientMessage (ServerManager target, ServerOperation op, uintptr_t p1)
ClientMessage (ServerManager target, ServerOperation op, const char *p1)
ClientMessage (ServerManager target, ServerOperation op, uintptr_t p1, const char *name)
~ClientMessage ()
void send ()
void send (SysClientStream *pipe)
Public Member Functions inherited from ServiceMessage
ServiceMessage ()
~ServiceMessage ()
void setResult (ServiceReturn code)
void setExceptionInfo (ErrorCode error, const char *message)
void setExceptionInfo (ServiceException *e)
void clearExceptionInfo ()
void raiseServerError ()
char * getArgumentName ()
void clearMessageData ()
void * getMessageData ()
size_t getMessageDataLength ()
void transferMessageData (RXSTRING &data)
void setMessageData (void *data, size_t length)
void * allocateMessageData (size_t length)
void freeMessageData ()
void readMessage (SysServerConnection *server)
void writeResult (SysServerConnection *server)
void writeMessage (SysClientStream &server)
void readResult (SysClientStream &server)
Additional Inherited Members
Public Types inherited from ServiceMessage
enum { NAMESIZE = 256 }
Static Public Member Functions inherited from ServiceMessage
static void * allocateResultMemory (size_t length)
static void releaseResultMemory (void *mem)
Public Attributes inherited from ServiceMessage
ServerManager messageTarget
ServerOperation operation
SessionID session
uintptr_t parameter1
uintptr_t parameter2
uintptr_t parameter3
uintptr_t parameter4
uintptr_t parameter5
ServiceReturn result
ErrorCode errorCode
void * messageData
size_t messageDataLength
bool retainMessageData
char nameArg [NAMESIZE]
char userid [MAX_USERID_LENGTH]
Detailed Description
Definition at line 47 of file ClientMessage.hpp.
Constructor & Destructor Documentation
ClientMessage() [1/4]
ClientMessage::ClientMessage (ServerManager target, ServerOperation op) inline
Definition at line 50 of file ClientMessage.hpp.
References ServiceMessage::messageTarget, and ServiceMessage::operation.
ClientMessage() [2/4]
ClientMessage::ClientMessage (ServerManager target, ServerOperation op, uintptr_t p1) inline
Definition at line 56 of file ClientMessage.hpp.
References ServiceMessage::messageTarget, ServiceMessage::operation, and ServiceMessage::parameter1.
ClientMessage() [3/4]
ClientMessage::ClientMessage (ServerManager target, ServerOperation op, const char * p1) inline
Definition at line 63 of file ClientMessage.hpp.
References ServiceMessage::messageTarget, ServiceMessage::nameArg, ServiceMessage::NAMESIZE, and ServiceMessage::operation.
ClientMessage() [4/4]
ClientMessage::ClientMessage (ServerManager target, ServerOperation op, uintptr_t p1, const char * name) inline
Definition at line 77 of file ClientMessage.hpp.
References ServiceMessage::messageTarget, ServiceMessage::nameArg, ServiceMessage::NAMESIZE, ServiceMessage::operation, and ServiceMessage::parameter1.
~ClientMessage()
ClientMessage::~ClientMessage () inline
Definition at line 92 of file ClientMessage.hpp.
References ServiceMessage::freeMessageData().
Member Function Documentation
send() [1/2]
void ClientMessage::send ()
Send a message to the rxapi server, and wait for a reply.
Definition at line 47 of file ClientMessage.cpp.
References LocalAPIManager::getConnection(), LocalAPIManager::getInstance(), LocalAPIManager::getSession(), LocalAPIManager::getUserID(), LocalAPIManager::returnConnection(), ServiceMessage::session, and ServiceMessage::userid.
Referenced by LocalMacroSpaceManager::addMacro(), LocalQueueManager::addToNamedQueue(), LocalQueueManager::addToSessionQueue(), LocalMacroSpaceManager::clearMacroSpace(), LocalQueueManager::clearNamedQueue(), LocalQueueManager::clearSessionQueue(), LocalQueueManager::createNamedQueue(), LocalQueueManager::createSessionQueue(), LocalQueueManager::deleteNamedQueue(), LocalQueueManager::deleteSessionQueue(), LocalRegistrationManager::dropCallback(), LocalAPIManager::establishServerConnection(), LocalMacroSpaceManager::getMacro(), LocalQueueManager::getQueueCount(), LocalQueueManager::getSessionQueueCount(), LocalMacroSpaceManager::loadMacroSpace(), LocalQueueManager::nestSessionQueue(), LocalQueueManager::openNamedQueue(), LocalQueueManager::pullFromQueue(), LocalRegistrationManager::queryCallback(), LocalMacroSpaceManager::queryMacro(), LocalQueueManager::queryNamedQueue(), LocalRegistrationManager::registerCallback(), LocalMacroSpaceManager::removeMacro(), LocalMacroSpaceManager::reorderMacro(), LocalRegistrationManager::resolveCallback(), LocalMacroSpaceManager::saveMacroSpace(), and LocalAPIManager::shutdown().
send() [2/2]
void ClientMessage::send (SysClientStream * pipe)
Send a message to the server using a supplied connection.
Parameters
pipe The connection to use.
Definition at line 78 of file ClientMessage.cpp.
References ServiceMessage::readResult(), and ServiceMessage::writeMessage().
The documentation for this class was generated from the following files:
ClientMessage.hpp
ClientMessage.cpp