executor.master: MessageDispatcher Class Reference
MessageDispatcher Class Reference
#include <MessageDispatcher.hpp>
Public Member Functions
MessageDispatcher (RexxMessage *m)
virtual ~MessageDispatcher ()
virtual void run ()
virtual void handleError (wholenumber_t, RexxDirectory *)
Public Member Functions inherited from ActivityDispatcher
ActivityDispatcher ()
virtual ~ActivityDispatcher ()
virtual void handleError (RexxDirectory *)
virtual void invoke ()
virtual void invoke (RexxOption *)
virtual void invoke (PRXSYSEXIT exits, const char *env)
void setContext (RexxActivity *act, RexxNativeActivation *a)
Protected Attributes
RexxMessage * message
Protected Attributes inherited from ActivityDispatcher
RexxActivity * activity
RexxNativeActivation * activation
Additional Inherited Members
Public Attributes inherited from ActivityDispatcher
wholenumber_t rc
RexxDirectory * conditionData
Detailed Description
Definition at line 47 of file MessageDispatcher.hpp.
Constructor & Destructor Documentation
MessageDispatcher()
MessageDispatcher::MessageDispatcher (RexxMessage * m) inline
Definition at line 50 of file MessageDispatcher.hpp.
~MessageDispatcher()
virtual MessageDispatcher::~MessageDispatcher () inline virtual
Definition at line 51 of file MessageDispatcher.hpp.
Member Function Documentation
handleError()
void MessageDispatcher::handleError (wholenumber_t r, RexxDirectory * c) virtual
Default handler for any error conditions. This just sets the condition information in the dispatch unit.
Parameters
c The condition information for the error.
Reimplemented from ActivityDispatcher.
Definition at line 63 of file MessageDispatcher.cpp.
References ActivityDispatcher::activation, ActivityDispatcher::activity, ActivityDispatcher::conditionData, RexxActivity::error(), RexxMessage::error(), ActivityDispatcher::handleError(), and message.
run()
void MessageDispatcher::run () virtual
Virtual method for handling invocation of a Message object on a new activity.
Reimplemented from ActivityDispatcher.
Definition at line 50 of file MessageDispatcher.cpp.
References message, and RexxObject::sendMessage().
Member Data Documentation
message
RexxMessage* MessageDispatcher::message protected
Definition at line 57 of file MessageDispatcher.hpp.
Referenced by handleError(), and run().
The documentation for this class was generated from the following files:
MessageDispatcher.hpp
MessageDispatcher.cpp