executor.master: RexxTrigger Class Reference
RexxTrigger Class Reference
#include <ParseTrigger.hpp>
Public Member Functions
void * operator new (size_t, int)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, int)
void operator delete (void *, void *)
RexxTrigger (int, RexxObject *, size_t, RexxQueue *)
RexxTrigger (RESTORETYPE restoreType)
stringsize_t integerTrigger (RexxObject *)
RexxString * stringTrigger (RexxObject *)
void parse (RexxActivation *, RexxExpressionStack *, RexxTarget *)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
int getType ()
void setType (int v)
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
void setInRexxPackage ()
bool isInRexxPackage ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxText * makeText ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxText * primitiveMakeText ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxText * textValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
virtual RexxObject * dynamicTarget (RexxObject **arguments, size_t count, size_t named_count)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Protected Attributes
int triggerType
size_t variableCount
RexxObject * value
RexxVariableBase * variables [1]
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 59 of file ParseTrigger.hpp.
Constructor & Destructor Documentation
RexxTrigger() [1/2]
RexxTrigger::RexxTrigger (int type, RexxObject * _value, size_t _variableCount, RexxQueue * _variables)
Definition at line 53 of file ParseTrigger.cpp.
References OrefSet, RexxQueue::pop(), setType(), value, variableCount, and variables.
RexxTrigger() [2/2]
RexxTrigger::RexxTrigger (RESTORETYPE restoreType) inline
Definition at line 68 of file ParseTrigger.hpp.
Member Function Documentation
flatten()
void RexxTrigger::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 270 of file ParseTrigger.cpp.
References cleanUpFlatten, flatten_reference, setUpFlatten, and variableCount.
getType()
int RexxTrigger::getType () inline
Definition at line 75 of file ParseTrigger.hpp.
References triggerType.
Referenced by parse().
integerTrigger()
stringsize_t RexxTrigger::integerTrigger (RexxObject * trigger)
Definition at line 73 of file ParseTrigger.cpp.
References Error_Invalid_whole_number_parse, number_digits(), reportException(), and RexxObject::requestUnsignedNumber().
Referenced by parse().
live()
void RexxTrigger::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 240 of file ParseTrigger.cpp.
References memory_mark, value, variableCount, and variables.
liveGeneral()
void RexxTrigger::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 255 of file ParseTrigger.cpp.
References memory_mark_general, value, variableCount, and variables.
operator delete() [1/3]
void RexxTrigger::operator delete (void *) inline
Definition at line 63 of file ParseTrigger.hpp.
operator delete() [2/3]
void RexxTrigger::operator delete (void * , int) inline
Definition at line 64 of file ParseTrigger.hpp.
operator delete() [3/3]
void RexxTrigger::operator delete (void * , void *) inline
Definition at line 65 of file ParseTrigger.hpp.
operator new() [1/2]
void* RexxTrigger::operator new (size_t size, void * ptr) inline
Definition at line 62 of file ParseTrigger.hpp.
operator new() [2/2]
void * RexxTrigger::operator new (size_t size, int variableCount)
Definition at line 289 of file ParseTrigger.cpp.
References new_object(), and T_ParseTrigger.
parse()
void RexxTrigger::parse (RexxActivation * context, RexxExpressionStack * stack, RexxTarget * target)
Definition at line 103 of file ParseTrigger.cpp.
References RexxTarget::absolute(), RexxVariableBase::assign(), RexxTarget::backward(), RexxTarget::backwardLength(), RexxTarget::caselessSearch(), RexxInternalObject::evaluate(), RexxTarget::forward(), RexxTarget::forwardLength(), getType(), RexxTarget::getWord(), integer(), integerTrigger(), RexxTarget::moveToEnd(), OREF_NULL, RexxExpressionStack::pop(), RexxTarget::remainder(), RexxTarget::search(), RexxTarget::skipRemainder(), RexxTarget::skipWord(), stringTrigger(), TRACE_PREFIX_DUMMY, RexxActivation::traceIntermediate(), RexxActivation::traceResult(), RexxActivation::tracingIntermediates(), RexxActivation::tracingResults(), TRIGGER_ABSOLUTE, TRIGGER_END, TRIGGER_MINUS, TRIGGER_MINUS_LENGTH, TRIGGER_MIXED, TRIGGER_PLUS, TRIGGER_PLUS_LENGTH, TRIGGER_STRING, value, variableCount, and variables.
Referenced by RexxInstructionParse::execute().
setType()
void RexxTrigger::setType (int v) inline
Definition at line 76 of file ParseTrigger.hpp.
References triggerType.
Referenced by RexxTrigger().
stringTrigger()
RexxString * RexxTrigger::stringTrigger (RexxObject * trigger)
Definition at line 91 of file ParseTrigger.cpp.
References REQUEST_STRING().
Referenced by parse().
Member Data Documentation
triggerType
int RexxTrigger::triggerType protected
Definition at line 80 of file ParseTrigger.hpp.
Referenced by getType(), and setType().
value
RexxObject* RexxTrigger::value protected
Definition at line 82 of file ParseTrigger.hpp.
Referenced by live(), liveGeneral(), parse(), and RexxTrigger().
variableCount
size_t RexxTrigger::variableCount protected
Definition at line 81 of file ParseTrigger.hpp.
Referenced by flatten(), live(), liveGeneral(), parse(), and RexxTrigger().
variables
RexxVariableBase* RexxTrigger::variables[1] protected
Definition at line 83 of file ParseTrigger.hpp.
Referenced by live(), liveGeneral(), parse(), and RexxTrigger().
The documentation for this class was generated from the following files:
ParseTrigger.hpp
ParseTrigger.cpp