executor.master: SysLibrary Class Reference
SysLibrary Class Reference
#include <SysLibrary.hpp>
Public Member Functions
SysLibrary ()
void * getProcedure (const char *name)
bool load (const char *name)
bool unload ()
void reset ()
SysLibrary ()
void * getProcedure (const char *name)
bool load (const char *name)
bool unload ()
void reset ()
Protected Attributes
void * libraryHandle
HMODULE libraryHandle
Detailed Description
Definition at line 50 of file unix/SysLibrary.hpp.
Constructor & Destructor Documentation
SysLibrary() [1/2]
SysLibrary::SysLibrary ()
Definition at line 59 of file unix/SysLibrary.cpp.
References libraryHandle.
SysLibrary() [2/2]
SysLibrary::SysLibrary ()
Member Function Documentation
getProcedure() [1/2]
void * SysLibrary::getProcedure (const char * name)
Definition at line 65 of file unix/SysLibrary.cpp.
References libraryHandle.
Referenced by LibraryPackage::getPackageTable(), LocalRegistrationManager::resolveCallback(), and LocalMacroSpaceManager::translateRexxProgram().
getProcedure() [2/2]
void* SysLibrary::getProcedure (const char * name)
load() [1/2]
bool SysLibrary::load (const char * name)
Load a named library in this process.
Parameters
name Character string name of the library.
Returns
True if able to load the library ok, false otherwise.
Definition at line 75 of file unix/SysLibrary.cpp.
References LIBARY_NAME_BUFFER_LENGTH, libraryHandle, and MAX_LIBRARY_NAME_LENGTH.
Referenced by LibraryPackage::getPackageTable(), LocalRegistrationManager::locateTable(), LocalRegistrationManager::resolveCallback(), and LocalMacroSpaceManager::translateRexxProgram().
load() [2/2]
bool SysLibrary::load (const char * name)
reset() [1/2]
void SysLibrary::reset (void) inline
Definition at line 57 of file unix/SysLibrary.hpp.
References libraryHandle.
Referenced by LibraryPackage::getPackageTable().
reset() [2/2]
void SysLibrary::reset (void) inline
Definition at line 57 of file windows/SysLibrary.hpp.
References libraryHandle.
unload() [1/2]
bool SysLibrary::unload ()
Free a loaded library if the library is still loaded.
Returns
True if we unloaded ok, false otherwise.
Definition at line 111 of file unix/SysLibrary.cpp.
References libraryHandle.
Referenced by LibraryPackage::unload().
unload() [2/2]
bool SysLibrary::unload ()
Member Data Documentation
libraryHandle [1/2]
void* SysLibrary::libraryHandle protected
Definition at line 60 of file unix/SysLibrary.hpp.
Referenced by getProcedure(), load(), reset(), SysLibrary(), and unload().
libraryHandle [2/2]
HMODULE SysLibrary::libraryHandle protected
Definition at line 60 of file windows/SysLibrary.hpp.
The documentation for this class was generated from the following files:
unix/SysLibrary.hpp
windows/SysLibrary.hpp
unix/SysLibrary.cpp
windows/SysLibrary.cpp