executor.master: RexxNativeRoutine Class Reference
RexxNativeRoutine Class Reference
#include <RexxNativeCode.hpp>
Public Member Functions
void * operator new (size_t size, void *ptr)
void * operator new (size_t size)
void operator delete (void *)
void operator delete (void *, void *)
RexxNativeRoutine (RESTORETYPE restoreType)
RexxNativeRoutine (RexxString *p, RexxString *n, PNATIVEROUTINE e)
void liveGeneral (int reason)
void flatten (RexxEnvelope *envelope)
PNATIVEROUTINE getEntry ()
virtual void call (RexxActivity *, RoutineClass *, RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
Public Member Functions inherited from RexxRoutine
RexxRoutine ()
RexxRoutine (RexxString *p, RexxString *n)
Public Member Functions inherited from RexxNativeCode
RexxNativeCode ()
RexxNativeCode (RexxString *p, RexxString *n)
void live (size_t)
virtual RexxSource * getSourceObject ()
virtual RexxClass * findClass (RexxString *className)
virtual BaseCode * setSourceObject (RexxSource *s)
SecurityManager * getSecurityManager ()
Public Member Functions inherited from BaseCode
virtual void run (RexxActivity *, RexxMethod *, RexxObject *, RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
virtual void call (RexxActivity *, RoutineClass *, RexxString *, RexxObject **, size_t, size_t, RexxString *, RexxString *, int, ProtectedObject &)
virtual RexxArray * getSource ()
virtual RexxObject * setSecurityManager (RexxObject *manager)
virtual PackageClass * getPackage ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Protected Attributes
PNATIVEROUTINE entry
Protected Attributes inherited from RexxNativeCode
RexxString * package
RexxString * name
RexxSource * source
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 107 of file RexxNativeCode.hpp.
Constructor & Destructor Documentation
RexxNativeRoutine() [1/2]
RexxNativeRoutine::RexxNativeRoutine (RESTORETYPE restoreType) inline
Definition at line 115 of file RexxNativeCode.hpp.
RexxNativeRoutine() [2/2]
RexxNativeRoutine::RexxNativeRoutine (RexxString * p, RexxString * n, PNATIVEROUTINE e) inline
Definition at line 116 of file RexxNativeCode.hpp.
Member Function Documentation
call()
void RexxNativeRoutine::call (RexxActivity * activity, RoutineClass * routine, RexxString * functionName, RexxObject ** argPtr, size_t count, size_t named_count, ProtectedObject & result) virtual
Run a method call (vs a straight program call).
Parameters
activity The current activity.
functionName The name of the message used to invoke the method.
argPtr The pointer to the arguments.
count The count of positional arguments.
named_count The count of named arguments.
result The protected object used to return the result.
Implements RexxRoutine.
Definition at line 304 of file RexxNativeCode.cpp.
References RexxNativeActivation::callNativeRoutine(), entry, RexxNativeCode::name, ActivityManager::newNativeActivation(), RexxNativeCode::package, RexxActivity::pushStackFrame(), and PackageManager::resolveRoutineEntry().
flatten()
void RexxNativeRoutine::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxNativeCode.
Definition at line 214 of file RexxNativeCode.cpp.
References cleanUpFlatten, RexxNativeCode::flatten(), and setUpFlatten.
getEntry()
PNATIVEROUTINE RexxNativeRoutine::getEntry () inline
Definition at line 121 of file RexxNativeCode.hpp.
References entry.
Referenced by RexxNativeActivation::callNativeRoutine().
liveGeneral()
void RexxNativeRoutine::liveGeneral (int reason) virtual
Reimplemented from RexxNativeCode.
Definition at line 200 of file RexxNativeCode.cpp.
References entry, RexxNativeCode::liveGeneral(), and SAVINGIMAGE.
operator delete() [1/2]
void RexxNativeRoutine::operator delete (void *) inline
Definition at line 112 of file RexxNativeCode.hpp.
operator delete() [2/2]
void RexxNativeRoutine::operator delete (void * , void *) inline
Definition at line 113 of file RexxNativeCode.hpp.
operator new() [1/2]
void * RexxNativeRoutine::operator new (size_t size)
Definition at line 321 of file RexxNativeCode.cpp.
References new_object(), and T_NativeRoutine.
operator new() [2/2]
void* RexxNativeRoutine::operator new (size_t size, void * ptr) inline
Definition at line 110 of file RexxNativeCode.hpp.
Member Data Documentation
entry
PNATIVEROUTINE RexxNativeRoutine::entry protected
Definition at line 126 of file RexxNativeCode.hpp.
Referenced by call(), getEntry(), and liveGeneral().
The documentation for this class was generated from the following files:
RexxNativeCode.hpp
RexxNativeCode.cpp