executor.master: NamedArguments Class Reference
NamedArguments Class Reference
#include <RexxCore.h>
Public Member Functions
NamedArguments (size_t count)
~NamedArguments ()
NamedArgument & operator[] (size_t index)
void match (RexxObject **namedArglist, size_t namedArgCount, bool strict, bool extraAllowed, size_t minimumRequired=0)
bool match (RexxString *name, RexxObject *value, bool strict=true, size_t from=0, bool parse_time=false)
bool match (const char *name, size_t nameLength, RexxObject *value, bool strict=true, size_t from=0, bool parse_time=false)
Public Attributes
const size_t count
Private Member Functions
bool checkNameMatching (const char *name, size_t nameLength, size_t i, bool parse_time)
Private Attributes
NamedArgument * namedArguments
Detailed Description
Definition at line 519 of file RexxCore.h.
Constructor & Destructor Documentation
NamedArguments()
NamedArguments::NamedArguments (size_t count) inline
Definition at line 522 of file RexxCore.h.
References count, and namedArguments.
~NamedArguments()
NamedArguments::~NamedArguments () inline
Definition at line 529 of file RexxCore.h.
References namedArguments.
Member Function Documentation
checkNameMatching()
bool NamedArguments::checkNameMatching (const char * name, size_t nameLength, size_t i, bool parse_time) private
Definition at line 589 of file UseStrictInstruction.cpp.
References NamedArgument::name, and namedArguments.
Referenced by match().
match() [1/3]
bool NamedArguments::match (const char * name, size_t nameLength, RexxObject * value, bool strict = true, size_t from = 0, bool parse_time = false)
Definition at line 548 of file UseStrictInstruction.cpp.
References NamedArgument::assigned, checkNameMatching(), count, Error_Invalid_argument_general, nameCollision(), namedArguments, new_string(), OREF_NULL, reportException(), and NamedArgument::value.
match() [2/3]
void NamedArguments::match (RexxObject ** namedArglist, size_t namedArgCount, bool strict, bool extraAllowed, size_t minimumRequired = 0)
Definition at line 459 of file UseStrictInstruction.cpp.
References NamedArgument::assigned, count, Error_Incorrect_method_maxarg, Error_Incorrect_method_minarg, Error_Incorrect_method_noarg, NamedArgument::name, OREF_NULL, reportException(), and NamedArgument::value.
Referenced by RoutineClass::callWithRexx(), RexxInstructionUseStrict::checkNamedArguments(), RexxInstructionUseStrict::executeNamedArguments(), match(), RexxObject::run(), RexxObject::sendWith(), RexxContext::setArgs(), RexxObject::startWith(), RexxObject::unknownRexx(), and Unicode::utf8proc_transform().
match() [3/3]
bool NamedArguments::match (RexxString * name, RexxObject * value, bool strict = true, size_t from = 0, bool parse_time = false)
Definition at line 517 of file UseStrictInstruction.cpp.
References RexxString::getLength(), RexxString::getStringData(), and match().
operator[]()
NamedArgument& NamedArguments::operator[] (size_t index) inline
Definition at line 535 of file RexxCore.h.
References count, and namedArguments.
Member Data Documentation
count
const size_t NamedArguments::count
Definition at line 552 of file RexxCore.h.
Referenced by match(), NamedArguments(), and operator[]().
namedArguments
NamedArgument* NamedArguments::namedArguments private
Definition at line 557 of file RexxCore.h.
Referenced by checkNameMatching(), match(), NamedArguments(), operator[](), and ~NamedArguments().
The documentation for this class was generated from the following files:
RexxCore.h
UseStrictInstruction.cpp