executor.master: NumericFormatter Class Reference
NumericFormatter Class Reference
Public Member Functions
NumericFormatter (RexxCallContext *c, bool explicitPrecision, uint32_t p)
RexxObjectPtr format (double x)
Protected Attributes
uint32_t precision
RexxCallContext * context
bool optionError
Detailed Description
Definition at line 112 of file rxmath.cpp.
Constructor & Destructor Documentation
NumericFormatter()
NumericFormatter::NumericFormatter (RexxCallContext * c, bool explicitPrecision, uint32_t p) inline
Definition at line 115 of file rxmath.cpp.
References context, MAX_PRECISION, optionError, and precision.
Member Function Documentation
format()
RexxObjectPtr NumericFormatter::format (double x) inline
Definition at line 141 of file rxmath.cpp.
References context, NULLOBJECT, optionError, and precision.
Referenced by TrigFormatter::evaluate(), TrigFormatter::evaluateArc(), RexxRoutine1(), RexxRoutine2(), and RexxRoutine3().
Member Data Documentation
context
RexxCallContext* NumericFormatter::context protected
Definition at line 154 of file rxmath.cpp.
Referenced by format(), NumericFormatter(), and TrigFormatter::TrigFormatter().
optionError
bool NumericFormatter::optionError protected
Definition at line 156 of file rxmath.cpp.
Referenced by TrigFormatter::evaluate(), TrigFormatter::evaluateArc(), format(), NumericFormatter(), and TrigFormatter::TrigFormatter().
precision
uint32_t NumericFormatter::precision protected
Definition at line 153 of file rxmath.cpp.
Referenced by format(), and NumericFormatter().
The documentation for this class was generated from the following file:
rxmath.cpp