executor.master: rexxasp3.c File Reference
rexxasp3.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <rexx.h>
Macros
#define INVALID_ROUTINE 40 /* Raise Rexx error */
#define VALID_ROUTINE 0 /* Successful completion */
Functions
RexxReturnCode REXXENTRY AspiLoadFuncs3 (const char *name, size_t numargs, CONSTRXSTRING args[], const char *queuename, PRXSTRING retstr)
RexxReturnCode REXXENTRY AspiDeregFunc3 (const char *name, size_t numargs, CONSTRXSTRING args[], const char *queuename, PRXSTRING retstr)
RexxReturnCode REXXENTRY Aspi_Read_All_Variables_From_REXX_VP (const char *name, size_t numargs, CONSTRXSTRING args[], const char *queuename, PRXSTRING retstr)
RexxReturnCode REXXENTRY Aspi_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP (const char *name, size_t numargs, CONSTRXSTRING args[], const char *queuename, PRXSTRING retstr)
Variables
static const char * AspiFncTable []
Macro Definition Documentation
INVALID_ROUTINE
#define INVALID_ROUTINE 40 /* Raise Rexx error */
Definition at line 58 of file rexxasp3.c.
VALID_ROUTINE
#define VALID_ROUTINE 0 /* Successful completion */
Definition at line 59 of file rexxasp3.c.
Function Documentation
Aspi_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP()
RexxReturnCode REXXENTRY Aspi_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP (const char * name, size_t numargs, CONSTRXSTRING args[], const char * queuename, PRXSTRING retstr)
Definition at line 265 of file rexxasp3.c.
References INVALID_ROUTINE, RexxFreeMemory(), RexxVariablePool(), RXSHV_LVAR, RXSHV_MEMFL, RXSHV_SYFET, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnext, _SHVBLOCK::shvvalue, _RXSTRING::strlength, _RXSTRING::strptr, and VALID_ROUTINE.
Aspi_Read_All_Variables_From_REXX_VP()
RexxReturnCode REXXENTRY Aspi_Read_All_Variables_From_REXX_VP (const char * name, size_t numargs, CONSTRXSTRING args[], const char * queuename, PRXSTRING retstr)
Definition at line 165 of file rexxasp3.c.
References INVALID_ROUTINE, RexxFreeMemory(), RexxVariablePool(), RXSHV_LVAR, RXSHV_MEMFL, RXSHV_NEXTV, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _RXSTRING::strlength, _RXSTRING::strptr, and VALID_ROUTINE.
AspiDeregFunc3()
RexxReturnCode REXXENTRY AspiDeregFunc3 (const char * name, size_t numargs, CONSTRXSTRING args[], const char * queuename, PRXSTRING retstr)
Definition at line 121 of file rexxasp3.c.
References AspiFncTable, INVALID_ROUTINE, RexxDeregisterFunction(), _RXSTRING::strlength, and VALID_ROUTINE.
AspiLoadFuncs3()
RexxReturnCode REXXENTRY AspiLoadFuncs3 (const char * name, size_t numargs, CONSTRXSTRING args[], const char * queuename, PRXSTRING retstr)
Definition at line 90 of file rexxasp3.c.
References AspiFncTable, RexxRegisterFunctionDll(), and VALID_ROUTINE.
Variable Documentation
AspiFncTable
const char* AspiFncTable[] static
Initial value:
=
   {
      "Aspi_Exchange_Data",
      "AspiDeregFunc3",
      "Aspi_Read_All_Variables_From_REXX_VP",
      "Aspi_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP"
   }
Definition at line 71 of file rexxasp3.c.
Referenced by AspiDeregFunc3(), and AspiLoadFuncs3().