executor.master: rexx.cpp File Reference
unix/rexx.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "oorexxapi.h"
Macros
#define SYSINITIALADDRESS "bash"
Functions
int main (int argc, char **argv)
Macro Definition Documentation
SYSINITIALADDRESS
#define SYSINITIALADDRESS "bash"
Definition at line 54 of file unix/rexx.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 57 of file unix/rexx.cpp.
References MAKERXSTRING, RexxCreateInterpreter(), RexxFreeMemory(), RexxGetVersionInformation(), RexxStart(), RXCOMMAND, _RXSTRING::strlength, _RXSTRING::strptr, and SYSINITIALADDRESS.