executor.master: PlatformDefinitions.h File Reference
unix/PlatformDefinitions.h File Reference
#include "APIDefinitions.h"
Macros
#define AIXREXX_H /* against multiple includes */
#define MIN_C_STACK 1024*16
#define TOTAL_STACK_SIZE 1024*512
#define C_STACK_SIZE TOTAL_STACK_SIZE
#define SysCall
#define RXTRACE_SUPPORT
#define STACKCHECK
#define NOTIMER
#define _POSIX_THREADS_
#define SYSINITIALADDRESS "bash"
#define BASEIMAGE "rexx.img"
#define BASEIMAGELOAD "CoreClasses.orx" /* MHES 29122004 */
#define REXXMESSAGEFILE "rexx.cat"
#define delimiter '/'
#define line_end "\n"
#define line_end_size 1
#define DEFRXSTRING 256 /* Default RXSTRING return size */
#define REXXTIMESLICE 100 /* 100 milliseconds (1/10 second) */
Functions
char ** getEnvironment ()
Macro Definition Documentation
_POSIX_THREADS_
#define _POSIX_THREADS_
Definition at line 111 of file unix/PlatformDefinitions.h.
AIXREXX_H
#define AIXREXX_H /* against multiple includes */
Definition at line 52 of file unix/PlatformDefinitions.h.
BASEIMAGE
#define BASEIMAGE "rexx.img"
Definition at line 144 of file unix/PlatformDefinitions.h.
BASEIMAGELOAD
#define BASEIMAGELOAD "CoreClasses.orx" /* MHES 29122004 */
Definition at line 151 of file unix/PlatformDefinitions.h.
C_STACK_SIZE
#define C_STACK_SIZE TOTAL_STACK_SIZE
Definition at line 60 of file unix/PlatformDefinitions.h.
DEFRXSTRING
#define DEFRXSTRING 256 /* Default RXSTRING return size */
Definition at line 172 of file unix/PlatformDefinitions.h.
delimiter
#define delimiter '/'
Definition at line 163 of file unix/PlatformDefinitions.h.
line_end
#define line_end "\n"
Definition at line 164 of file unix/PlatformDefinitions.h.
line_end_size
#define line_end_size 1
Definition at line 165 of file unix/PlatformDefinitions.h.
MIN_C_STACK
#define MIN_C_STACK 1024*16
Definition at line 58 of file unix/PlatformDefinitions.h.
NOTIMER
#define NOTIMER
Definition at line 90 of file unix/PlatformDefinitions.h.
REXXMESSAGEFILE
#define REXXMESSAGEFILE "rexx.cat"
Definition at line 156 of file unix/PlatformDefinitions.h.
REXXTIMESLICE
#define REXXTIMESLICE 100 /* 100 milliseconds (1/10 second) */
Definition at line 178 of file unix/PlatformDefinitions.h.
RXTRACE_SUPPORT
#define RXTRACE_SUPPORT
Definition at line 75 of file unix/PlatformDefinitions.h.
STACKCHECK
#define STACKCHECK
Definition at line 82 of file unix/PlatformDefinitions.h.
SysCall
#define SysCall
Definition at line 63 of file unix/PlatformDefinitions.h.
SYSINITIALADDRESS
#define SYSINITIALADDRESS "bash"
Definition at line 122 of file unix/PlatformDefinitions.h.
TOTAL_STACK_SIZE
#define TOTAL_STACK_SIZE 1024*512
Definition at line 59 of file unix/PlatformDefinitions.h.
Function Documentation
getEnvironment()
char** getEnvironment () inline
Definition at line 133 of file unix/PlatformDefinitions.h.
Referenced by SystemInterpreter::buildEnvlist(), SystemInterpreter::restoreEnvironment(), and sys_process_export().