executor.master: RexxCompiler.cpp File Reference
unix/RexxCompiler.cpp File Reference
#include <limits.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "rexx.h"
#include "RexxMessageNumbers.h"
Macros
#define REXXMESSAGEFILE "rexx.cat"
#define BUFFERLEN 256 /* Length of message bufs used */
#define SECOND_PARAMETER 0 /* 0 for no NL_CAT_LOCALE */
#define CATD_ERR ((nl_catd)-1) /* Duplicate for AIX */
Functions
void DisplayError (int msgid)
int main (int argc, char **argv)
Macro Definition Documentation
BUFFERLEN
#define BUFFERLEN 256 /* Length of message bufs used */
Definition at line 67 of file unix/RexxCompiler.cpp.
CATD_ERR
#define CATD_ERR ((nl_catd)-1) /* Duplicate for AIX */
Definition at line 75 of file unix/RexxCompiler.cpp.
REXXMESSAGEFILE
#define REXXMESSAGEFILE "rexx.cat"
Definition at line 65 of file unix/RexxCompiler.cpp.
SECOND_PARAMETER
#define SECOND_PARAMETER 0 /* 0 for no NL_CAT_LOCALE */
Definition at line 71 of file unix/RexxCompiler.cpp.
Function Documentation
DisplayError()
void DisplayError (int msgid)
Definition at line 78 of file unix/RexxCompiler.cpp.
References CATD_ERR, REXXMESSAGEFILE, and SECOND_PARAMETER.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 132 of file unix/RexxCompiler.cpp.
References DisplayError(), Error_REXXC_cmd_parm_incorrect_msg, Error_REXXC_outDifferent_msg, Error_REXXC_SynCheckInfo_msg, Error_REXXC_wrongNrArg_unix_msg, RexxFreeMemory(), RexxGetVersionInformation(), and RexxTranslateProgram().