executor.master: ExternalFunctions.cpp File Reference
unix/ExternalFunctions.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <limits.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/types.h>
#include <pwd.h>
#include "RexxCore.h"
#include "StringClass.hpp"
#include "ArrayClass.hpp"
#include "RexxActivity.hpp"
#include "RexxActivation.hpp"
#include "MethodClass.hpp"
#include "SourceFile.hpp"
#include "RexxInternalApis.h"
#include "ActivityManager.hpp"
#include "ProtectedObject.hpp"
#include "StringUtil.hpp"
#include "SystemInterpreter.hpp"
#include "PackageManager.hpp"
#include "BufferClass.hpp"
Classes
struct _ENVENTRY
Macros
#define CMDBUFSIZE 1024 /* Max size of executable cmd */
#define CMDDEFNAME "/bin/bash" /* Default unix sys cmd handler */
#define COMSPEC "bash" /* unix cmd handler env name */
#define SYSENV "bash" /* Default AIX cmd environment */
#define DRVNUM 0x40 /* drive number subtractor */
#define DIRLEN 256 /* length of a directory */
#define FULLSEG 65536L /* ^4K constant */
#define FILESPEC_PATH 'P'
#define FILESPEC_NAME 'N'
#define FILESPEC_LOCATION 'L'
#define FILESPEC_EXTENSION 'E'
#define FILESPEC_DRIVE 'D'
#define KIOCSOUND 0x4B2F /* start sound generation (0 for off) */
Typedefs
typedef struct _ENVENTRY ENVENTRY
Functions
RexxRoutine2 (CSTRING, sysBeep, OPTIONAL_wholenumber_t, Frequency, OPTIONAL_wholenumber_t, Duration)
char * resolve_tilde (const char *path)
RexxRoutine1 (RexxStringObject, sysDirectory, OPTIONAL_CSTRING, dir)
RexxRoutine2 (RexxStringObject, sysFilespec, CSTRING, option, CSTRING, name)
Variables
int putflag = 0
Macro Definition Documentation
CMDBUFSIZE
#define CMDBUFSIZE 1024 /* Max size of executable cmd */
Definition at line 85 of file unix/ExternalFunctions.cpp.
CMDDEFNAME
#define CMDDEFNAME "/bin/bash" /* Default unix sys cmd handler */
Definition at line 95 of file unix/ExternalFunctions.cpp.
COMSPEC
#define COMSPEC "bash" /* unix cmd handler env name */
Definition at line 96 of file unix/ExternalFunctions.cpp.
DIRLEN
#define DIRLEN 256 /* length of a directory */
Definition at line 101 of file unix/ExternalFunctions.cpp.
DRVNUM
#define DRVNUM 0x40 /* drive number subtractor */
Definition at line 100 of file unix/ExternalFunctions.cpp.
FILESPEC_DRIVE
#define FILESPEC_DRIVE 'D'
Definition at line 108 of file unix/ExternalFunctions.cpp.
FILESPEC_EXTENSION
#define FILESPEC_EXTENSION 'E'
Definition at line 107 of file unix/ExternalFunctions.cpp.
FILESPEC_LOCATION
#define FILESPEC_LOCATION 'L'
Definition at line 106 of file unix/ExternalFunctions.cpp.
FILESPEC_NAME
#define FILESPEC_NAME 'N'
Definition at line 105 of file unix/ExternalFunctions.cpp.
FILESPEC_PATH
#define FILESPEC_PATH 'P'
Definition at line 104 of file unix/ExternalFunctions.cpp.
FULLSEG
#define FULLSEG 65536L /* ^4K constant */
Definition at line 102 of file unix/ExternalFunctions.cpp.
KIOCSOUND
#define KIOCSOUND 0x4B2F /* start sound generation (0 for off) */
Definition at line 110 of file unix/ExternalFunctions.cpp.
SYSENV
#define SYSENV "bash" /* Default AIX cmd environment */
Definition at line 97 of file unix/ExternalFunctions.cpp.
Typedef Documentation
ENVENTRY
typedef struct _ENVENTRY ENVENTRY
Function Documentation
resolve_tilde()
char* resolve_tilde (const char * path)
Definition at line 144 of file unix/ExternalFunctions.cpp.
Referenced by getFileSpecFromArg(), RexxRoutine1(), SysFileDelete(), SysFileSearch(), SysGetFileDateTime(), SysMkDir(), SysRmDir(), and SysSetFileDateTime().
RexxRoutine1()
RexxRoutine1 (RexxStringObject , sysDirectory , OPTIONAL_CSTRING , dir)
Definition at line 228 of file unix/ExternalFunctions.cpp.
References SystemInterpreter::getCurrentWorkingDirectory(), NO_CSTRING, and resolve_tilde().
RexxRoutine2() [1/2]
RexxRoutine2 (CSTRING , sysBeep , OPTIONAL_wholenumber_t , Frequency , OPTIONAL_wholenumber_t , Duration)
Definition at line 128 of file unix/ExternalFunctions.cpp.
RexxRoutine2() [2/2]
RexxRoutine2 (RexxStringObject , sysFilespec , CSTRING , option , CSTRING , name)
Definition at line 266 of file unix/ExternalFunctions.cpp.
References FILESPEC_DRIVE, FILESPEC_EXTENSION, FILESPEC_LOCATION, FILESPEC_NAME, FILESPEC_PATH, NULLOBJECT, and Rexx_Error_Incorrect_call_list.
Variable Documentation
putflag
int putflag = 0
Definition at line 116 of file unix/ExternalFunctions.cpp.
Referenced by SystemInterpreter::restoreEnvironment(), and sys_process_export().