executor.master: APIService.cpp File Reference
unix/mac/APIService.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <signal.h>
#include <pwd.h>
#include "APIServer.hpp"
Macros
#define OOREXX_PIDFILE "/tmp/ooRexx.pid"
Functions
void Run (bool asService)
void Stop (int signo)
int main (int argc, char *argv[])
Variables
APIServer apiServer
Macro Definition Documentation
OOREXX_PIDFILE
#define OOREXX_PIDFILE "/tmp/ooRexx.pid"
Definition at line 52 of file unix/mac/APIService.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 105 of file unix/mac/APIService.cpp.
References OOREXX_PIDFILE, Run(), and Stop().
Run()
void Run (bool asService)
Definition at line 67 of file unix/mac/APIService.cpp.
References apiServer, APIServer::initServer(), APIServer::listenForConnections(), and APIServer::terminateServer().
Referenced by main().
Stop()
void Stop (int signo)
Definition at line 89 of file unix/mac/APIService.cpp.
References apiServer, and APIServer::terminateServer().
Referenced by main().
Variable Documentation
apiServer
APIServer apiServer
Definition at line 54 of file unix/mac/APIService.cpp.
Referenced by Run(), and Stop().