executor.master: rxsubcom.cpp File Reference
unix/rxsubcom.cpp File Reference
#include <limits.h>
#include <string.h>
#include <stdio.h>
#include "rexx.h"
#include "RexxInternalApis.h"
#include "RexxErrorCodes.h"
#include "RexxMessageNumbers.h"
Macros
#define REXXMESSAGEFILE "rexx.cat"
#define BUFFERLEN 256 /* Length of message bufs used*/
#define CASE(x) if(!strcasecmp(x,argv[1]))
#define SECOND_PARAMETER 0 /* 0 for no NL_CAT_LOCALE */
#define CATD_ERR ((nl_catd)-1) /* Duplicate for AIX */
Functions
void parmerr (int)
int main (int argc, char *argv[], char *envp[])
Macro Definition Documentation
BUFFERLEN
#define BUFFERLEN 256 /* Length of message bufs used*/
Definition at line 66 of file unix/rxsubcom.cpp.
CASE
#define CASE (x) if(!strcasecmp(x,argv[1]))
Definition at line 68 of file unix/rxsubcom.cpp.
CATD_ERR
#define CATD_ERR ((nl_catd)-1) /* Duplicate for AIX */
Definition at line 77 of file unix/rxsubcom.cpp.
REXXMESSAGEFILE
#define REXXMESSAGEFILE "rexx.cat"
Definition at line 64 of file unix/rxsubcom.cpp.
SECOND_PARAMETER
#define SECOND_PARAMETER 0 /* 0 for no NL_CAT_LOCALE */
Definition at line 73 of file unix/rxsubcom.cpp.
Function Documentation
main()
int main (int argc, char * argv[], char * envp[])
Definition at line 82 of file unix/rxsubcom.cpp.
References CASE, Error_RXSUBC_drop_msg, Error_RXSUBC_general_msg, Error_RXSUBC_load_msg, Error_RXSUBC_query_msg, Error_RXSUBC_register_msg, parmerr(), RexxDeregisterSubcom(), RexxLoadSubcom(), RexxQuerySubcom(), RexxRegisterSubcomDll(), and RXSUBCOM_DROPPABLE.
parmerr()
void parmerr (int msgid)
Definition at line 164 of file unix/rxsubcom.cpp.
References BUFFERLEN, CATD_ERR, REXXMESSAGEFILE, and SECOND_PARAMETER.
Referenced by main().