executor.master: RexxCompiler.cpp File Reference
windows/RexxCompiler.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "windows.h"
#include "rexx.h"
#include "PlatformDefinitions.h"
#include "RexxErrorCodes.h"
#include "RexxInternalApis.h"
Macros
#define DLLNAME "rexx.dll"
#define BUFFERLEN 256 /* Length of message bufs used */
Functions
void DisplayError (HINSTANCE hDll, int err_no)
int SysCall main (int argc, char **argv)
Macro Definition Documentation
BUFFERLEN
#define BUFFERLEN 256 /* Length of message bufs used */
Definition at line 55 of file windows/RexxCompiler.cpp.
DLLNAME
#define DLLNAME "rexx.dll"
Definition at line 53 of file windows/RexxCompiler.cpp.
Function Documentation
DisplayError()
void DisplayError (HINSTANCE hDll, int err_no)
Definition at line 59 of file windows/RexxCompiler.cpp.
References BUFFERLEN.
Referenced by main().
main()
int SysCall main (int argc, char ** argv)
Definition at line 69 of file windows/RexxCompiler.cpp.
References BUFFERLEN, DisplayError(), DLLNAME, Error_REXXC_cmd_parm_incorrect, Error_REXXC_outDifferent, Error_REXXC_SynCheckInfo, Error_REXXC_wrongNrArg, RexxFreeMemory(), RexxGetVersionInformation(), RexxTranslateProgram(), and strupr().