executor.master: rexx.cpp File Reference
windows/rexx.cpp File Reference
#include <windows.h>
#include <oorexxapi.h>
#include <malloc.h>
#include <stdio.h>
#include <string.h>
#include "ArgumentParser.h"
Functions
int __cdecl main (int argc, char *argv[])
LONG REXXENTRY MY_IOEXIT (LONG ExitNumber, LONG Subfunction, PEXIT ParmBlock)
Function Documentation
main()
int __cdecl main (int argc, char * argv[])
Definition at line 68 of file windows/rexx.cpp.
References freeArguments(), getArguments(), RexxCreateInterpreter(), RexxFreeMemory(), RexxGetVersionInformation(), REXXSTART, RXCOMMAND, _RXSTRING::strlength, _RXSTRING::strptr, and _CONSTRXSTRING::strptr.
MY_IOEXIT()
LONG REXXENTRY MY_IOEXIT (LONG ExitNumber, LONG Subfunction, PEXIT ParmBlock)