ooRexx: BufferClass.hpp File Reference
BufferClass.hpp File Reference
#include <string.h>
Classes
class BufferClassBase
class BufferClass
Functions
BufferClass * new_buffer (size_t s)
BufferClass * new_buffer (CONSTRXSTRING &r)
BufferClass * new_buffer (RXSTRING &r)
BufferClass * new_buffer (const char *data, size_t length)
Function Documentation
new_buffer() [1/4]
BufferClass* new_buffer (const char * data, size_t length) inline
Definition at line 139 of file BufferClass.hpp.
References BufferClassBase::copyData(), and new_buffer().
new_buffer() [2/4]
BufferClass* new_buffer (CONSTRXSTRING & r) inline
Definition at line 125 of file BufferClass.hpp.
References BufferClassBase::copyData(), new_buffer(), and _CONSTRXSTRING::strlength.
new_buffer() [3/4]
BufferClass* new_buffer (RXSTRING & r) inline
Definition at line 132 of file BufferClass.hpp.
References BufferClassBase::copyData(), new_buffer(), and _RXSTRING::strlength.
new_buffer() [4/4]
BufferClass* new_buffer (size_t s) inline
Definition at line 124 of file BufferClass.hpp.
Referenced by NumberString::addSub(), RexxObject::allocateObjectMemory(), SystemInterpreter::buildEnvlist(), NativeActivation::callRegisteredRoutine(), MutableBuffer::copy(), LanguageParser::createMethod(), LanguageParser::createProgram(), LanguageParser::createRoutine(), NumberString::d2xD2c(), NumberString::dividePower(), NumberString::Division(), BufferClass::expand(), CompoundVariableTail::expandCapacity(), PackageManager::loadRequires(), NumberString::Multiply(), MutableBuffer::MutableBuffer(), new_buffer(), NewBuffer(), NewMethod(), NewRoutine(), NumberString::power(), LanguageParser::processInstore(), FileProgramSource::readProgram(), RoutineClass::restore(), MutableBuffer::setBufferSize(), SmartBuffer::SmartBuffer(), and RexxString::x2dC2d().