ooRexx: CallContextStubs.cpp File Reference
CallContextStubs.cpp File Reference
#include "RexxCore.h"
#include "ContextApi.hpp"
#include "NativeActivation.hpp"
#include "SupplierClass.hpp"
#include "Interpreter.hpp"
#include "MethodClass.hpp"
#include "PackageClass.hpp"
#include "DirectoryClass.hpp"
#include "ActivityManager.hpp"
#include "CommandIOContext.hpp"
Functions
RexxArrayObject RexxEntry GetCallArguments (RexxCallContext *c)
RexxObjectPtr RexxEntry GetCallArgument (RexxCallContext *c, stringsize_t i)
CSTRING RexxEntry GetRoutineName (RexxCallContext *c)
RexxRoutineObject RexxEntry GetCurrentRoutine (RexxCallContext *c)
void RexxEntry SetContextVariable (RexxCallContext *c, CSTRING n, RexxObjectPtr v)
RexxObjectPtr RexxEntry GetContextVariable (RexxCallContext *c, CSTRING n)
void RexxEntry DropContextVariable (RexxCallContext *c, CSTRING n)
RexxVariableReferenceObject RexxEntry GetContextVariableReference (RexxCallContext *c, CSTRING n)
RexxDirectoryObject RexxEntry GetAllContextVariables (RexxCallContext *c)
RexxStemObject RexxEntry ResolveStemVariable (RexxCallContext *c, RexxObjectPtr s)
void RexxEntry InvalidRoutine (RexxCallContext *c)
void RexxEntry CallThrowException0 (RexxCallContext *c, size_t n)
void RexxEntry CallThrowException1 (RexxCallContext *c, size_t n, RexxObjectPtr o1)
void RexxEntry CallThrowException2 (RexxCallContext *c, size_t n, RexxObjectPtr o1, RexxObjectPtr o2)
void RexxEntry CallThrowException (RexxCallContext *c, size_t n, RexxArrayObject a)
void RexxEntry CallThrowCondition (RexxCallContext *c, CSTRING n, RexxStringObject desc, RexxObjectPtr add, RexxObjectPtr result)
void RexxEntry SetExitContextVariable (RexxExitContext *c, CSTRING n, RexxObjectPtr v)
RexxObjectPtr RexxEntry GetExitContextVariable (RexxExitContext *c, CSTRING n)
void RexxEntry DropExitContextVariable (RexxExitContext *c, CSTRING n)
RexxVariableReferenceObject RexxEntry GetExitContextVariableReference (RexxExitContext *c, CSTRING n)
RexxDirectoryObject RexxEntry GetAllExitContextVariables (RexxExitContext *c)
RexxObjectPtr RexxEntry GetExitCallerContext (RexxExitContext *c)
void RexxEntry ExitThrowException0 (RexxExitContext *c, size_t n)
void RexxEntry ExitThrowException1 (RexxExitContext *c, size_t n, RexxObjectPtr o1)
void RexxEntry ExitThrowException2 (RexxExitContext *c, size_t n, RexxObjectPtr o1, RexxObjectPtr o2)
void RexxEntry ExitThrowException (RexxExitContext *c, size_t n, RexxArrayObject a)
void RexxEntry ExitThrowCondition (RexxExitContext *c, CSTRING n, RexxStringObject desc, RexxObjectPtr add, RexxObjectPtr result)
stringsize_t RexxEntry GetContextDigits (RexxCallContext *c)
stringsize_t RexxEntry GetContextFuzz (RexxCallContext *c)
logical_t RexxEntry GetContextForm (RexxCallContext *c)
RexxObjectPtr RexxEntry GetCallerContext (RexxCallContext *c)
RexxClassObject RexxEntry FindCallContextClass (RexxCallContext *c, CSTRING n)
void RexxEntry ReadInput (RexxIORedirectorContext *c, CSTRING *data, size_t *length)
void RexxEntry ReadInputBuffer (RexxIORedirectorContext *c, CSTRING *data, size_t *length)
void RexxEntry WriteOutput (RexxIORedirectorContext *c, const char *data, size_t length)
void RexxEntry WriteError (RexxIORedirectorContext *c, const char *data, size_t length)
void RexxEntry WriteOutputBuffer (RexxIORedirectorContext *c, const char *data, size_t length)
void RexxEntry WriteErrorBuffer (RexxIORedirectorContext *c, const char *data, size_t length)
logical_t RexxEntry IsInputRedirected (RexxIORedirectorContext *c)
logical_t RexxEntry IsOutputRedirected (RexxIORedirectorContext *c)
logical_t RexxEntry IsErrorRedirected (RexxIORedirectorContext *c)
logical_t RexxEntry AreOutputAndErrorSameTarget (RexxIORedirectorContext *c)
logical_t RexxEntry IsRedirectionRequested (RexxIORedirectorContext *c)
Function Documentation
AreOutputAndErrorSameTarget()
logical_t RexxEntry AreOutputAndErrorSameTarget (RexxIORedirectorContext * c)
Definition at line 643 of file CallContextStubs.cpp.
References CommandIOContext::areOutputAndErrorSameTarget(), and OREF_NULL.
CallThrowCondition()
void RexxEntry CallThrowCondition (RexxCallContext * c, CSTRING n, RexxStringObject desc, RexxObjectPtr add, RexxObjectPtr result)
Definition at line 234 of file CallContextStubs.cpp.
References ApiContext::activity, ApiContext::context, NativeActivation::enableConditionTrap(), new_upper_string(), OREF_NULL, and Activity::raiseCondition().
CallThrowException()
void RexxEntry CallThrowException (RexxCallContext * c, size_t n, RexxArrayObject a)
Definition at line 228 of file CallContextStubs.cpp.
References reportException().
CallThrowException0()
void RexxEntry CallThrowException0 (RexxCallContext * c, size_t n)
Definition at line 210 of file CallContextStubs.cpp.
References reportException().
CallThrowException1()
void RexxEntry CallThrowException1 (RexxCallContext * c, size_t n, RexxObjectPtr o1)
Definition at line 216 of file CallContextStubs.cpp.
References reportException().
CallThrowException2()
void RexxEntry CallThrowException2 (RexxCallContext * c, size_t n, RexxObjectPtr o1, RexxObjectPtr o2)
Definition at line 222 of file CallContextStubs.cpp.
References reportException().
DropContextVariable()
void RexxEntry DropContextVariable (RexxCallContext * c, CSTRING n)
Definition at line 137 of file CallContextStubs.cpp.
References ApiContext::context, and NativeActivation::dropContextVariable().
DropExitContextVariable()
void RexxEntry DropExitContextVariable (RexxExitContext * c, CSTRING n)
Definition at line 267 of file CallContextStubs.cpp.
References ApiContext::context, and NativeActivation::dropContextVariable().
ExitThrowCondition()
void RexxEntry ExitThrowCondition (RexxExitContext * c, CSTRING n, RexxStringObject desc, RexxObjectPtr add, RexxObjectPtr result)
Definition at line 349 of file CallContextStubs.cpp.
References ApiContext::activity, ApiContext::context, NativeActivation::enableConditionTrap(), new_upper_string(), OREF_NULL, and Activity::raiseCondition().
ExitThrowException()
void RexxEntry ExitThrowException (RexxExitContext * c, size_t n, RexxArrayObject a)
Definition at line 343 of file CallContextStubs.cpp.
References reportException().
ExitThrowException0()
void RexxEntry ExitThrowException0 (RexxExitContext * c, size_t n)
Definition at line 325 of file CallContextStubs.cpp.
References reportException().
ExitThrowException1()
void RexxEntry ExitThrowException1 (RexxExitContext * c, size_t n, RexxObjectPtr o1)
Definition at line 331 of file CallContextStubs.cpp.
References reportException().
ExitThrowException2()
void RexxEntry ExitThrowException2 (RexxExitContext * c, size_t n, RexxObjectPtr o1, RexxObjectPtr o2)
Definition at line 337 of file CallContextStubs.cpp.
References reportException().
FindCallContextClass()
RexxClassObject RexxEntry FindCallContextClass (RexxCallContext * c, CSTRING n)
Definition at line 412 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::findCallerClass(), new_upper_string(), NULLOBJECT, and ApiContext::ret().
GetAllContextVariables()
RexxDirectoryObject RexxEntry GetAllContextVariables (RexxCallContext * c)
Definition at line 164 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getAllContextVariables(), NULLOBJECT, and ApiContext::ret().
GetAllExitContextVariables()
RexxDirectoryObject RexxEntry GetAllExitContextVariables (RexxExitContext * c)
Definition at line 294 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getAllContextVariables(), NULLOBJECT, and ApiContext::ret().
GetCallArgument()
RexxObjectPtr RexxEntry GetCallArgument (RexxCallContext * c, stringsize_t i)
Definition at line 71 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getArgument(), and NULLOBJECT.
GetCallArguments()
RexxArrayObject RexxEntry GetCallArguments (RexxCallContext * c)
Definition at line 58 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getArguments(), and NULLOBJECT.
GetCallerContext()
RexxObjectPtr RexxEntry GetCallerContext (RexxCallContext * c)
Definition at line 397 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getRexxContextObject(), NULLOBJECT, and ApiContext::ret().
GetContextDigits()
stringsize_t RexxEntry GetContextDigits (RexxCallContext * c)
Definition at line 357 of file CallContextStubs.cpp.
References ApiContext::context, and NativeActivation::digits().
GetContextForm()
logical_t RexxEntry GetContextForm (RexxCallContext * c)
Definition at line 384 of file CallContextStubs.cpp.
References ApiContext::context, and NativeActivation::form().
GetContextFuzz()
stringsize_t RexxEntry GetContextFuzz (RexxCallContext * c)
Definition at line 370 of file CallContextStubs.cpp.
References ApiContext::context, and NativeActivation::fuzz().
GetContextVariable()
RexxObjectPtr RexxEntry GetContextVariable (RexxCallContext * c, CSTRING n)
Definition at line 124 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getContextVariable(), and NULLOBJECT.
GetContextVariableReference()
RexxVariableReferenceObject RexxEntry GetContextVariableReference (RexxCallContext * c, CSTRING n)
Definition at line 150 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getContextVariableReference(), and NULLOBJECT.
GetCurrentRoutine()
RexxRoutineObject RexxEntry GetCurrentRoutine (RexxCallContext * c)
Definition at line 99 of file CallContextStubs.cpp.
References ApiContext::context, and ActivationBase::getExecutable().
GetExitCallerContext()
RexxObjectPtr RexxEntry GetExitCallerContext (RexxExitContext * c)
Definition at line 308 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getRexxContextObject(), NULLOBJECT, and ApiContext::ret().
GetExitContextVariable()
RexxObjectPtr RexxEntry GetExitContextVariable (RexxExitContext * c, CSTRING n)
Definition at line 254 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getContextVariable(), and NULLOBJECT.
GetExitContextVariableReference()
RexxVariableReferenceObject RexxEntry GetExitContextVariableReference (RexxExitContext * c, CSTRING n)
Definition at line 279 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getContextVariableReference(), and NULLOBJECT.
GetRoutineName()
CSTRING RexxEntry GetRoutineName (RexxCallContext * c)
Definition at line 86 of file CallContextStubs.cpp.
References ApiContext::context, NativeActivation::getMessageName(), and RexxString::getStringData().
InvalidRoutine()
void RexxEntry InvalidRoutine (RexxCallContext * c)
Definition at line 193 of file CallContextStubs.cpp.
References ApiContext::context, Error_Incorrect_call_external, NativeActivation::getMessageName(), and reportException().
IsErrorRedirected()
logical_t RexxEntry IsErrorRedirected (RexxIORedirectorContext * c)
Definition at line 621 of file CallContextStubs.cpp.
References CommandIOContext::isErrorRedirected(), and OREF_NULL.
IsInputRedirected()
logical_t RexxEntry IsInputRedirected (RexxIORedirectorContext * c)
Definition at line 577 of file CallContextStubs.cpp.
References CommandIOContext::isInputRedirected(), and OREF_NULL.
IsOutputRedirected()
logical_t RexxEntry IsOutputRedirected (RexxIORedirectorContext * c)
Definition at line 599 of file CallContextStubs.cpp.
References CommandIOContext::isOutputRedirected(), and OREF_NULL.
IsRedirectionRequested()
logical_t RexxEntry IsRedirectionRequested (RexxIORedirectorContext * c)
Definition at line 665 of file CallContextStubs.cpp.
References OREF_NULL.
ReadInput()
void RexxEntry ReadInput (RexxIORedirectorContext * c, CSTRING * data, size_t * length)
Definition at line 428 of file CallContextStubs.cpp.
References ApiContext::context, RexxString::getLength(), RexxString::getStringData(), OREF_NULL, and CommandIOContext::readInput().
ReadInputBuffer()
void RexxEntry ReadInputBuffer (RexxIORedirectorContext * c, CSTRING * data, size_t * length)
Definition at line 463 of file CallContextStubs.cpp.
References ApiContext::context, OREF_NULL, and CommandIOContext::readInputBuffered().
ResolveStemVariable()
RexxStemObject RexxEntry ResolveStemVariable (RexxCallContext * c, RexxObjectPtr s)
Definition at line 177 of file CallContextStubs.cpp.
References NativeActivation::clearException(), ApiContext::context, NULLOBJECT, and NativeActivation::resolveStemVariable().
SetContextVariable()
void RexxEntry SetContextVariable (RexxCallContext * c, CSTRING n, RexxObjectPtr v)
Definition at line 112 of file CallContextStubs.cpp.
References ApiContext::context, and NativeActivation::setContextVariable().
SetExitContextVariable()
void RexxEntry SetExitContextVariable (RexxExitContext * c, CSTRING n, RexxObjectPtr v)
Definition at line 242 of file CallContextStubs.cpp.
References ApiContext::context, and NativeActivation::setContextVariable().
WriteError()
void RexxEntry WriteError (RexxIORedirectorContext * c, const char * data, size_t length)
Definition at line 512 of file CallContextStubs.cpp.
References ApiContext::context, new_string(), OREF_NULL, and CommandIOContext::writeError().
WriteErrorBuffer()
void RexxEntry WriteErrorBuffer (RexxIORedirectorContext * c, const char * data, size_t length)
Definition at line 555 of file CallContextStubs.cpp.
References ApiContext::context, new_string(), OREF_NULL, and CommandIOContext::writeErrorBuffer().
WriteOutput()
void RexxEntry WriteOutput (RexxIORedirectorContext * c, const char * data, size_t length)
Definition at line 491 of file CallContextStubs.cpp.
References ApiContext::context, OREF_NULL, and CommandIOContext::writeOutput().
WriteOutputBuffer()
void RexxEntry WriteOutputBuffer (RexxIORedirectorContext * c, const char * data, size_t length)
Definition at line 534 of file CallContextStubs.cpp.
References ApiContext::context, OREF_NULL, and CommandIOContext::writeOutputBuffer().