ooRexx: FileNative.cpp File Reference
FileNative.cpp File Reference
#include "oorexxapi.h"
#include <fcntl.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>
#include "SysFileSystem.hpp"
#include "ExternalFileBuffer.hpp"
Functions
RexxMethod0 (CSTRING, file_separator)
RexxMethod0 (CSTRING, file_path_separator)
RexxMethod0 (logical_t, file_case_sensitive)
RexxMethod1 (logical_t, this_file_case_sensitive, CSTRING, fileName)
RexxMethod1 (logical_t, file_can_read, CSTRING, name)
RexxMethod1 (logical_t, file_can_write, CSTRING, name)
RexxMethod0 (RexxArrayObject, file_list_roots)
RexxMethod1 (RexxStringObject, file_qualify, CSTRING, name)
RexxMethod1 (logical_t, file_exists, CSTRING, name)
RexxMethod1 (logical_t, file_delete_file, CSTRING, name)
RexxMethod1 (logical_t, file_delete_directory, CSTRING, name)
RexxMethod1 (logical_t, file_isDirectory, CSTRING, name)
RexxMethod1 (logical_t, file_isFile, CSTRING, name)
RexxMethod1 (logical_t, file_isHidden, CSTRING, name)
RexxMethod1 (int64_t, file_get_last_modified, CSTRING, name)
RexxMethod2 (logical_t, file_set_last_modified, CSTRING, name, int64_t, time)
RexxMethod1 (int64_t, file_get_last_accessed, CSTRING, name)
RexxMethod2 (logical_t, file_set_last_accessed, CSTRING, name, int64_t, time)
RexxMethod1 (logical_t, file_set_read_only, CSTRING, name)
RexxMethod1 (logical_t, file_set_writable, CSTRING, name)
RexxMethod1 (uint64_t, file_length, CSTRING, name)
RexxMethod1 (RexxObjectPtr, file_list, CSTRING, name)
RexxMethod1 (logical_t, file_make_dir, CSTRING, name)
RexxMethod2 (logical_t, file_rename, CSTRING, fromName, CSTRING, toName)
RexxMethod0 (RexxStringObject, file_temporary_path)
RexxMethod2 (RexxObjectPtr, file_search_path_impl, CSTRING, file, CSTRING, path)
Function Documentation
RexxMethod0() [1/5]
RexxMethod0 (CSTRING , file_path_separator)
Return the separator used for file search paths
Definition at line 64 of file FileNative.cpp.
References SysFileSystem::getPathSeparator().
RexxMethod0() [2/5]
RexxMethod0 (CSTRING , file_separator)
Return the file name separator used by the file system.
Definition at line 56 of file FileNative.cpp.
References SysFileSystem::getSeparator().
RexxMethod0() [3/5]
RexxMethod0 (logical_t , file_case_sensitive)
Return the file system case sensitivity
Definition at line 73 of file FileNative.cpp.
References SysFileSystem::isCaseSensitive().
RexxMethod0() [4/5]
RexxMethod0 (RexxArrayObject , file_list_roots)
Return the list of file system root elements.
Definition at line 110 of file FileNative.cpp.
References SysFileSystem::getRoots().
RexxMethod0() [5/5]
RexxMethod0 (RexxStringObject , file_temporary_path)
Return the temporary directory.
Definition at line 312 of file FileNative.cpp.
References SysFileSystem::getTemporaryPath().
RexxMethod1() [1/17]
RexxMethod1 (int64_t , file_get_last_accessed , CSTRING , name)
Return the last access date as a Ticks time value.
Definition at line 215 of file FileNative.cpp.
References SysFileSystem::getLastAccessDate().
RexxMethod1() [2/17]
RexxMethod1 (int64_t , file_get_last_modified , CSTRING , name)
Return the last modified date as a Ticks time value.
Definition at line 197 of file FileNative.cpp.
References SysFileSystem::getLastModifiedDate().
RexxMethod1() [3/17]
RexxMethod1 (logical_t , file_can_read , CSTRING , name)
Return whether file can be opened for reading
Definition at line 92 of file FileNative.cpp.
References SysFileSystem::canRead(), and SysFileSystem::exists().
RexxMethod1() [4/17]
RexxMethod1 (logical_t , file_can_write , CSTRING , name)
Return whether file can be opened for writing
Definition at line 101 of file FileNative.cpp.
References SysFileSystem::canWrite(), and SysFileSystem::exists().
RexxMethod1() [5/17]
RexxMethod1 (logical_t , file_delete_directory , CSTRING , name)
Delete a directory
Definition at line 161 of file FileNative.cpp.
References SysFileSystem::deleteDirectory().
RexxMethod1() [6/17]
RexxMethod1 (logical_t , file_delete_file , CSTRING , name)
Delete a file
Definition at line 152 of file FileNative.cpp.
References SysFileSystem::deleteFile().
RexxMethod1() [7/17]
RexxMethod1 (logical_t , file_exists , CSTRING , name)
Test if the file exists
Definition at line 143 of file FileNative.cpp.
References SysFileSystem::exists().
RexxMethod1() [8/17]
RexxMethod1 (logical_t , file_isDirectory , CSTRING , name)
Tests if the file is a directory
Definition at line 170 of file FileNative.cpp.
References SysFileSystem::isDirectory().
RexxMethod1() [9/17]
RexxMethod1 (logical_t , file_isFile , CSTRING , name)
Tests if the file is a file
Definition at line 179 of file FileNative.cpp.
References SysFileSystem::isFile().
RexxMethod1() [10/17]
RexxMethod1 (logical_t , file_isHidden , CSTRING , name)
Tests if the file hidden
Definition at line 188 of file FileNative.cpp.
References SysFileSystem::isHidden().
RexxMethod1() [11/17]
RexxMethod1 (logical_t , file_make_dir , CSTRING , name)
Make a directory instance
Definition at line 294 of file FileNative.cpp.
References SysFileSystem::makeDirectory().
RexxMethod1() [12/17]
RexxMethod1 (logical_t , file_set_read_only , CSTRING , name)
Set the read-only flag for the target file
Definition at line 233 of file FileNative.cpp.
References SysFileSystem::setFileReadOnly().
RexxMethod1() [13/17]
RexxMethod1 (logical_t , file_set_writable , CSTRING , name)
Set the read-only flag for the target file
Definition at line 242 of file FileNative.cpp.
References SysFileSystem::setFileWritable().
RexxMethod1() [14/17]
RexxMethod1 (logical_t , this_file_case_sensitive , CSTRING , fileName)
Return the case sensitivity of a file
Definition at line 82 of file FileNative.cpp.
References SysFileSystem::isCaseSensitive().
RexxMethod1() [15/17]
RexxMethod1 (RexxObjectPtr , file_list , CSTRING , name)
Get a list of the file children for a directory.
Definition at line 261 of file FileNative.cpp.
References SysFileIterator::hasNext(), SysFileSystem::isDirectory(), FileNameBuffer::length(), and SysFileIterator::next().
RexxMethod1() [16/17]
RexxMethod1 (RexxStringObject , file_qualify , CSTRING , name)
Create a fully-qualified path name for a file.
Definition at line 132 of file FileNative.cpp.
RexxMethod1() [17/17]
RexxMethod1 (uint64_t , file_length , CSTRING , name)
Return the last modified date as a Ticks time value.
Definition at line 252 of file FileNative.cpp.
References SysFileSystem::getFileLength().
RexxMethod2() [1/4]
RexxMethod2 (logical_t , file_rename , CSTRING , fromName , CSTRING , toName)
Rename a file.
Definition at line 303 of file FileNative.cpp.
References SysFileSystem::moveFile().
RexxMethod2() [2/4]
RexxMethod2 (logical_t , file_set_last_accessed , CSTRING , name , int64_t , time)
Return the last modified date as a Ticks time value.
Definition at line 224 of file FileNative.cpp.
References SysFileSystem::setLastAccessDate().
RexxMethod2() [3/4]
RexxMethod2 (logical_t , file_set_last_modified , CSTRING , name , int64_t , time)
Return the last modified date as a Ticks time value.
Definition at line 206 of file FileNative.cpp.
References SysFileSystem::setLastModifiedDate().
RexxMethod2() [4/4]
RexxMethod2 (RexxObjectPtr , file_search_path_impl , CSTRING , file , CSTRING , path)
Return the file system case sensitivity section
Definition at line 324 of file FileNative.cpp.
References SysFileSystem::searchPath().