ooRexx: InterpreterAPI.cpp File Reference
InterpreterAPI.cpp File Reference
#include "RexxCore.h"
#include "RexxMemory.hpp"
#include "StringClass.hpp"
#include "DirectoryClass.hpp"
#include "Activity.hpp"
#include "ActivityManager.hpp"
#include "MethodClass.hpp"
#include "Interpreter.hpp"
#include "TranslateDispatcher.hpp"
#include "RexxStartDispatcher.hpp"
#include "InterpreterInstance.hpp"
#include "NativeActivation.hpp"
#include "RexxInternalApis.h"
#include "SystemInterpreter.hpp"
#include <stdio.h>
Functions
int REXXENTRY RexxTerminate ()
int REXXENTRY RexxInitialize ()
void REXXENTRY RexxCreateInterpreterImage (const char *target)
int REXXENTRY RexxStart (size_t argcount, PCONSTRXSTRING arglist, const char *programname, PRXSTRING instore, const char *envname, int calltype, PRXSYSEXIT exits, short *retcode, PRXSTRING result)
RexxReturnCode REXXENTRY RexxCompileProgram (const char *inFile, const char *outFile, PRXSYSEXIT exits, bool encode)
RexxReturnCode REXXENTRY RexxTranslateProgram (const char *inFile, const char *outFile, PRXSYSEXIT exits)
RexxReturnCode REXXENTRY RexxTranslateInstoreProgram (const char *inFile, CONSTRXSTRING *source, RXSTRING *image)
char *REXXENTRY RexxGetVersionInformation ()
RexxReturnCode REXXENTRY RexxHaltThread (thread_id_t threadid)
RexxReturnCode REXXENTRY RexxSetHalt (process_id_t procid, thread_id_t threadid)
RexxReturnCode REXXENTRY RexxSetThreadTrace (thread_id_t threadid)
RexxReturnCode REXXENTRY RexxResetThreadTrace (thread_id_t threadid)
RexxReturnCode REXXENTRY RexxSetTrace (process_id_t procid, thread_id_t threadid)
RexxReturnCode REXXENTRY RexxResetTrace (process_id_t procid, thread_id_t threadid)
RexxReturnCode RexxEntry RexxCreateInterpreter (RexxInstance **instance, RexxThreadContext **context, RexxOption *options)
RexxReturnCode RexxEntry RexxVariablePool (PSHVBLOCK pshvblock)
RexxReturnCode RexxEntry RexxStemSort (RexxStemObject stem, const char *tailExtension, int order, int type, wholenumber_t start, wholenumber_t end, wholenumber_t firstcol, wholenumber_t lastcol)
void RexxEntry RexxWaitForTermination ()
RexxReturnCode RexxEntry RexxDidRexxTerminate ()
Function Documentation
RexxCompileProgram()
RexxReturnCode REXXENTRY RexxCompileProgram (const char * inFile, const char * outFile, PRXSYSEXIT exits, bool encode)
Translate a program and store the translated results in an external file.
Parameters
inFile The input source file.
outFile The output source.
exits The exits to use during the translation process.
Returns
The error return code (if any).
Definition at line 185 of file InterpreterAPI.cpp.
References TranslateDispatcher::encode, TranslateDispatcher::instore, ActivityDispatcher::invoke(), TranslateDispatcher::outputName, TranslateDispatcher::programName, ActivityDispatcher::rc, and Interpreter::terminateInterpreter().
Referenced by main(), and RexxTranslateProgram().
RexxCreateInterpreter()
RexxReturnCode RexxEntry RexxCreateInterpreter (RexxInstance ** instance, RexxThreadContext ** context, RexxOption * options)
Create an interpreter instance at the API level.
Parameters
instance The returned instance pointer.
context The initial thread context for this instance.
options An array of interpreter instance options.
Returns
1 if the instance was created, 0 for any creation errors.
Definition at line 396 of file InterpreterAPI.cpp.
References Interpreter::createInstance().
Referenced by createInstance(), main(), and WinMain().
RexxCreateInterpreterImage()
void REXXENTRY RexxCreateInterpreterImage (const char * target)
Create the Rexx saved image during build processing.
Returns
Nothing
Definition at line 90 of file InterpreterAPI.cpp.
References Interpreter::SAVE_IMAGE_MODE, and Interpreter::startInterpreter().
Referenced by main().
RexxDidRexxTerminate()
RexxReturnCode RexxEntry RexxDidRexxTerminate (void)
Test if the interpreter environment has terminated. This is a nop in 4.0 since the APIs do the proper thing with respect to threading termination. This is maintained solely for binary compatibility.
Returns
always returns true
Definition at line 457 of file InterpreterAPI.cpp.
RexxGetVersionInformation()
char* REXXENTRY RexxGetVersionInformation (void)
Retrieve the interpreter version information.
Returns
Definition at line 250 of file InterpreterAPI.cpp.
References SystemInterpreter::allocateResultMemory().
Referenced by main().
RexxHaltThread()
RexxReturnCode REXXENTRY RexxHaltThread (thread_id_t threadid)
Raise a halt condition for a target thread.
Parameters
threadid The target threadid.
Returns
RXARI_OK if this worked, RXARI_NOT_FOUND if the thread isn't active.
Definition at line 289 of file InterpreterAPI.cpp.
References ActivityManager::haltActivity(), Interpreter::isActive(), OREF_NULL, RXARI_NOT_FOUND, and RXARI_OK.
Referenced by RexxSetHalt().
RexxInitialize()
int REXXENTRY RexxInitialize ()
Definition at line 73 of file InterpreterAPI.cpp.
References Interpreter::RUN_MODE, and Interpreter::startInterpreter().
RexxResetThreadTrace()
RexxReturnCode REXXENTRY RexxResetThreadTrace (thread_id_t threadid)
Reset the external trace for a target thread.
Parameters
threadid The target thread id.
Returns
The success/failure indicator.
Definition at line 345 of file InterpreterAPI.cpp.
References Interpreter::isActive(), RXARI_NOT_FOUND, RXARI_OK, and ActivityManager::setActivityTrace().
Referenced by RexxResetTrace().
RexxResetTrace()
RexxReturnCode REXXENTRY RexxResetTrace (process_id_t procid, thread_id_t threadid)
The compatibility stub for the reset trace API.
Parameters
procid The target process id (ignored).
threadid The thread id of the target thread.
Returns
The success/failure indicator.
Definition at line 381 of file InterpreterAPI.cpp.
References RexxResetThreadTrace().
Referenced by GrxHost().
RexxSetHalt()
RexxReturnCode REXXENTRY RexxSetHalt (process_id_t procid, thread_id_t threadid)
Compatibility function for doing a RexxHaltThread().
Parameters
procid The process id (ignored).
threadid The target threadid
Returns
the success/failure return code.
Definition at line 311 of file InterpreterAPI.cpp.
References RexxHaltThread().
Referenced by GrxHost().
RexxSetThreadTrace()
RexxReturnCode REXXENTRY RexxSetThreadTrace (thread_id_t threadid)
Turn on tracing for a given interpreter thread.
Parameters
threadid The target thread identifier.
Returns
the success/failure return code.
Definition at line 324 of file InterpreterAPI.cpp.
References Interpreter::isActive(), RXARI_NOT_FOUND, RXARI_OK, and ActivityManager::setActivityTrace().
Referenced by RexxSetTrace().
RexxSetTrace()
RexxReturnCode REXXENTRY RexxSetTrace (process_id_t procid, thread_id_t threadid)
Compatibility stub for the old signature of RexxSetTrace.
Parameters
procid The process id (ignored).
threadid The target thread identifier.
Returns
the success/failure return code.
Definition at line 367 of file InterpreterAPI.cpp.
References RexxSetThreadTrace().
Referenced by GrxHost().
RexxStart()
int REXXENTRY RexxStart (size_t argcount, PCONSTRXSTRING arglist, const char * programname, PRXSTRING instore, const char * envname, int calltype, PRXSYSEXIT exits, short * retcode, PRXSTRING result)
Definition at line 116 of file InterpreterAPI.cpp.
References RexxStartDispatcher::argcount, RexxStartDispatcher::arglist, RexxStartDispatcher::calltype, StringUtil::caselessCompare(), TranslateDispatcher::encode, RexxStartDispatcher::instore, TranslateDispatcher::instore, ActivityDispatcher::invoke(), TranslateDispatcher::outputName, RexxStartDispatcher::programName, TranslateDispatcher::programName, ActivityDispatcher::rc, RexxStartDispatcher::result, RexxStartDispatcher::retcode, RXCOMMAND, and Interpreter::terminateInterpreter().
Referenced by ApiRexxStart(), CallRexx(), invokeRexxStart(), and main().
RexxStemSort()
RexxReturnCode RexxEntry RexxStemSort (RexxStemObject stem, const char * tailExtension, int order, int type, wholenumber_t start, wholenumber_t end, wholenumber_t firstcol, wholenumber_t lastcol)
Process a stemsort call for the rexxutil SysStemSort function.
Parameters
stemname The name of the stem.
order The sort order.
type The type of sort (case sensitivity).
start The starting element number.
end The end element number.
firstcol The first sort column.
lastcol The last sort column.
Returns
The sort return code result.
Definition at line 428 of file InterpreterAPI.cpp.
References NativeContextBlock::self, NativeActivation::stemSort(), and type.
Referenced by RexxRoutine7().
RexxTerminate()
int REXXENTRY RexxTerminate ()
Definition at line 62 of file InterpreterAPI.cpp.
References Interpreter::terminateInterpreter().
RexxTranslateInstoreProgram()
RexxReturnCode REXXENTRY RexxTranslateInstoreProgram (const char * inFile, CONSTRXSTRING * source, RXSTRING * image)
Translate a program and store the translated results in an external file.
Parameters
inFile The input name.
source The source RXSTRING
image The returned image RXSTRING
Returns
The error return code (if any).
Definition at line 232 of file InterpreterAPI.cpp.
References TranslateInstoreDispatcher::image, ActivityDispatcher::invoke(), TranslateInstoreDispatcher::programName, ActivityDispatcher::rc, and TranslateInstoreDispatcher::source.
RexxTranslateProgram()
RexxReturnCode REXXENTRY RexxTranslateProgram (const char * inFile, const char * outFile, PRXSYSEXIT exits)
Translate a program and store the translated results in an external file.
Parameters
inFile The input source file.
outFile The output source.
exits The exits to use during the translation process.
Returns
The error return code (if any).
Definition at line 216 of file InterpreterAPI.cpp.
References RexxCompileProgram().
RexxVariablePool()
RexxReturnCode RexxEntry RexxVariablePool (PSHVBLOCK pshvblock)
Main entry point for processing variable pool requests
Parameters
pshvblock The shaved variable block chain for the request.
Returns
The composite request return code.
Definition at line 408 of file InterpreterAPI.cpp.
References NativeContextBlock::self, and NativeActivation::variablePoolInterface().
Referenced by Api_Fill_REXX_Variable_Pool(), Api_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP(), Api_Read_All_Variables_From_REXX_VP(), dropContextVariable(), FetchRexxVar(), getContextVariable(), RexxMethod0(), RexxRoutine1(), setContextVariable(), SetRexxVar(), and WSRegistryValue().
RexxWaitForTermination()
void RexxEntry RexxWaitForTermination (void)
Wait for Rexx termination. This is a nop in 4.0 since the APIs do the proper thing with respect to threading termination. This is maintained solely for binary compatibility.
Returns
Definition at line 444 of file InterpreterAPI.cpp.