ooRexx: InternalPackage.cpp File Reference
InternalPackage.cpp File Reference
#include "RexxCore.h"
#include "PackageManager.hpp"
#include "SysFileSystem.hpp"
#include "ExternalFileBuffer.hpp"
#include "SysProcess.hpp"
#include <ctype.h>
#include "NativeMethods.h"
#include "SysNativeMethods.h"
#include "NativeFunctions.h"
#include "SysNativeFunctions.h"
Macros
#define FILESPEC_PATH 'P'
#define FILESPEC_NAME 'N'
#define FILESPEC_LOCATION 'L'
#define FILESPEC_EXTENSION 'E'
#define FILESPEC_DRIVE 'D'
#define MAX_FREQUENCY 32767
#define MIN_FREQUENCY 37
#define MAX_DURATION 60000
#define MIN_DURATION 0
#define INTERNAL_METHOD(name) REXX_METHOD_PROTOTYPE(name)
#define INTERNAL_METHOD(name) REXX_METHOD(name, name),
#define INTERNAL_ROUTINE(name, entry) REXX_TYPED_ROUTINE_PROTOTYPE(entry)
#define INTERNAL_ROUTINE(name, entry) REXX_TYPED_ROUTINE(name, entry),
Functions
RexxRoutine1 (RexxStringObject, sysDirectory, OPTIONAL_CSTRING, dir)
RexxRoutine2 (RexxStringObject, sysFilespec, CSTRING, option, CSTRING, name)
RexxRoutine2 (CSTRING, sysBeep, wholenumber_t, Frequency, wholenumber_t, Duration)
Variables
RexxMethodEntry rexx_methods []
RexxRoutineEntry rexx_routines []
RexxPackageEntry rexx_package_entry
Macro Definition Documentation
FILESPEC_DRIVE
#define FILESPEC_DRIVE 'D'
Definition at line 58 of file InternalPackage.cpp.
FILESPEC_EXTENSION
#define FILESPEC_EXTENSION 'E'
Definition at line 57 of file InternalPackage.cpp.
FILESPEC_LOCATION
#define FILESPEC_LOCATION 'L'
Definition at line 56 of file InternalPackage.cpp.
FILESPEC_NAME
#define FILESPEC_NAME 'N'
Definition at line 55 of file InternalPackage.cpp.
FILESPEC_PATH
#define FILESPEC_PATH 'P'
Definition at line 54 of file InternalPackage.cpp.
INTERNAL_METHOD [1/2]
#define INTERNAL_METHOD (name) REXX_METHOD_PROTOTYPE(name)
Definition at line 210 of file InternalPackage.cpp.
INTERNAL_METHOD [2/2]
#define INTERNAL_METHOD (name) REXX_METHOD(name, name),
Definition at line 210 of file InternalPackage.cpp.
INTERNAL_ROUTINE [1/2]
#define INTERNAL_ROUTINE (name, entry) REXX_TYPED_ROUTINE_PROTOTYPE(entry)
Definition at line 227 of file InternalPackage.cpp.
INTERNAL_ROUTINE [2/2]
#define INTERNAL_ROUTINE (name, entry) REXX_TYPED_ROUTINE(name, entry),
Definition at line 227 of file InternalPackage.cpp.
MAX_DURATION
#define MAX_DURATION 60000
Definition at line 162 of file InternalPackage.cpp.
MAX_FREQUENCY
#define MAX_FREQUENCY 32767
Definition at line 160 of file InternalPackage.cpp.
MIN_DURATION
#define MIN_DURATION 0
Definition at line 163 of file InternalPackage.cpp.
MIN_FREQUENCY
#define MIN_FREQUENCY 37
Definition at line 161 of file InternalPackage.cpp.
Function Documentation
RexxRoutine1()
RexxRoutine1 (RexxStringObject , sysDirectory , OPTIONAL_CSTRING , dir)
Definition at line 64 of file InternalPackage.cpp.
References SysFileSystem::getCurrentDirectory(), NO_CSTRING, and SysFileSystem::setCurrentDirectory().
RexxRoutine2() [1/2]
RexxRoutine2 (CSTRING , sysBeep , wholenumber_t , Frequency , wholenumber_t , Duration)
Definition at line 174 of file InternalPackage.cpp.
References SysProcess::beep(), MAX_DURATION, MAX_FREQUENCY, MIN_DURATION, MIN_FREQUENCY, and Rexx_Error_Invalid_argument_range.
RexxRoutine2() [2/2]
RexxRoutine2 (RexxStringObject , sysFilespec , CSTRING , option , CSTRING , name)
Definition at line 89 of file InternalPackage.cpp.
References FILESPEC_DRIVE, FILESPEC_EXTENSION, FILESPEC_LOCATION, FILESPEC_NAME, FILESPEC_PATH, SysFileSystem::getPathEnd(), SysFileSystem::getPathStart(), NULLOBJECT, Rexx_Error_Incorrect_call_list, and Utilities::toUpper().
Variable Documentation
rexx_methods
RexxMethodEntry rexx_methods[]
Initial value:
=
{
}
Definition at line 213 of file InternalPackage.cpp.
rexx_package_entry
RexxPackageEntry rexx_package_entry
Initial value:
=
{
    STANDARD_PACKAGE_HEADER
    REXX_CURRENT_INTERPRETER_VERSION,
    "REXX",
    "4.0",
    NULL,
    NULL,
    rexx_routines,
    rexx_methods
}
Definition at line 237 of file InternalPackage.cpp.
rexx_routines
RexxRoutineEntry rexx_routines[]
Initial value:
=
{
}
Definition at line 230 of file InternalPackage.cpp.