ooRexx: IntegerClass.hpp File Reference
IntegerClass.hpp File Reference
#include "ClassClass.hpp"
Classes
class RexxInteger
class RexxIntegerClass
Macros
#define RexxIntegerMaxBase 999
#define RexxIntegerMaxPower 18
Functions
void integer_create ()
RexxInteger * new_integer (wholenumber_t v)
RexxInteger * new_integer (bool sign, const char *digits, wholenumber_t intDigits, wholenumber_t pad=0)
wholenumber_t length_in_bits (wholenumber_t v)
Macro Definition Documentation
RexxIntegerMaxBase
#define RexxIntegerMaxBase 999
Definition at line 253 of file IntegerClass.hpp.
RexxIntegerMaxPower
#define RexxIntegerMaxPower 18
Definition at line 255 of file IntegerClass.hpp.
Function Documentation
integer_create()
void integer_create ()
length_in_bits()
wholenumber_t length_in_bits (wholenumber_t v) inline
Definition at line 229 of file IntegerClass.hpp.
Referenced by RexxInteger::d2c(), RexxInteger::d2x(), RexxInteger::multiply(), and RexxInteger::power().
new_integer() [1/2]
RexxInteger* new_integer (bool sign, const char * digits, wholenumber_t intDigits, wholenumber_t pad = 0) inline
Definition at line 211 of file IntegerClass.hpp.
References TheIntegerClass.
new_integer() [2/2]
RexxInteger* new_integer (wholenumber_t v) inline
Definition at line 210 of file IntegerClass.hpp.
References TheIntegerClass.
Referenced by RexxInteger::abs(), ListContents::allIndexes(), ArrayClass::allocateArrayOfClass(), ArrayClass::appendRexx(), ListClass::appendRexx(), BUILTIN(), Activity::callQueueSizeExit(), RexxString::caselessCompare(), RexxString::caselessCompareToRexx(), RexxString::caselessCountStrRexx(), MutableBuffer::caselessCountStrRexx(), MutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), MutableBuffer::caselessPos(), RexxString::caselessPosRexx(), MutableBuffer::caselessWordPos(), RexxString::caselessWordPos(), checkPadArgument(), RexxActivation::command(), RexxString::compare(), RexxString::compareToRexx(), CommandHandlerDispatcher::complete(), ArrayClass::convertIndex(), RexxString::countStrRexx(), MutableBuffer::countStrRexx(), Activity::createExceptionObject(), MemoryObject::createImage(), RexxActivation::createTraceObject(), PackageClass::digitsRexx(), ArrayClass::dimensionRexx(), RexxInteger::divide(), NumberString::Division(), LanguageParser::errorLine(), LanguageParser::errorPosition(), RexxInstructionRaise::execute(), PackageClass::fuzzRexx(), RexxInfo::getArchitecture(), MutableBuffer::getBufferSize(), RexxActivation::getContextLine(), RexxActivation::getContextReturnStatus(), RexxContext::getDigits(), RexxInfo::getDigits(), ArrayClass::getDimensionsRexx(), RexxContext::getFuzz(), RexxInfo::getFuzz(), RexxInfo::getInternalDigits(), RexxInfo::getInternalMaxNumber(), RexxInfo::getInternalMinNumber(), RexxContext::getInterpreter(), RexxContext::getInvocation(), StackFrameClass::getInvocation(), StackFrameClass::getLine(), RexxInfo::getMajorVersion(), RexxInfo::getMaxArraySize(), RexxInfo::getMaxExponent(), RexxInfo::getMaxPathLength(), RexxInfo::getMinExponent(), RexxInfo::getModification(), RexxInfo::getRelease(), RexxInfo::getRevision(), PackageClass::getSourceSizeRexx(), RexxContext::getThread(), RexxObject::identityHashRexx(), SupplierClass::index(), ListClass::indexObject(), ArrayClass::indexToArray(), ArrayClass::insertRexx(), ListClass::insertRexx(), Numerics::int64ToObject(), NativeActivation::int64Value(), RexxInteger::integerDivide(), NumberString::integerValue(), RexxActivation::internalCall(), RexxActivation::internalCallTrap(), Numerics::intptrToObject(), ArrayClass::itemsRexx(), ListClass::itemsRexx(), StemClass::itemsRexx(), HashCollection::itemsRexx(), RelationClass::itemsRexx(), StringUtil::lastPosRexx(), MutableBuffer::lengthRexx(), RexxString::lengthRexx(), RexxInstructionSelect::matchEnd(), RexxBaseBlockInstruction::matchLabel(), RexxInteger::minus(), RexxInteger::modulo(), RexxInteger::multiply(), ExpressionStack::optionalIntegerArg(), LanguageParser::packBinaryLiteral(), LanguageParser::packHexLiteral(), RexxInteger::plus(), StringUtil::posRexx(), RexxInteger::power(), RexxActivation::random(), RexxInteger::remainder(), Activity::reportAnException(), ExpressionStack::requiredIntegerArg(), Activity::reraiseException(), MemoryObject::restore(), RexxActivation::rexxVariable(), LanguageParser::scanComment(), Activity::setCallerStackFrameAsStringTable(), NumberString::Sign(), RexxActivation::signalTo(), NativeActivation::signedIntegerValue(), ArrayClass::sizeRexx(), Numerics::stringsizeToObject(), NumberArray::toArray(), NumberString::truncInternal(), Numerics::uint64ToObject(), Numerics::uintptrToObject(), NativeActivation::unsignedInt64Value(), NativeActivation::unsignedIntegerValue(), NativeActivation::variablePoolFetchPrivate(), StringUtil::verify(), Numerics::wholenumberToObject(), StringUtil::wordIndex(), StringUtil::wordLength(), MutableBuffer::wordPos(), RexxString::wordPos(), MutableBuffer::words(), RexxString::words(), StemOutputTarget::writeLine(), and RexxString::x2dC2d().