ooRexx: InterpreterInstanceStubs.cpp File Reference
InterpreterInstanceStubs.cpp File Reference
#include "RexxCore.h"
#include "ContextApi.hpp"
#include "InterpreterInstance.hpp"
#include "Interpreter.hpp"
Functions
void RexxEntry Terminate (RexxInstance *c)
logical_t RexxEntry AttachThread (RexxInstance *c, RexxThreadContext **tc)
void RexxEntry Halt (RexxInstance *c)
void RexxEntry SetTrace (RexxInstance *c, logical_t setting)
size_t RexxEntry InterpreterVersion (RexxInstance *)
size_t RexxEntry LanguageLevel (RexxInstance *)
void RexxEntry AddCommandEnvironment (RexxInstance *c, const char *name, REXXPFN handler, int type)
Function Documentation
AddCommandEnvironment()
void RexxEntry AddCommandEnvironment (RexxInstance * c, const char * name, REXXPFN handler, int type)
Definition at line 89 of file InterpreterInstanceStubs.cpp.
References InterpreterInstance::addCommandHandler(), HandlerType::DIRECT, DIRECT_COMMAND_ENVIRONMENT, InstanceApiContext::instance, HandlerType::REDIRECTING, REDIRECTING_COMMAND_ENVIRONMENT, and type.
AttachThread()
logical_t RexxEntry AttachThread (RexxInstance * c, RexxThreadContext ** tc)
Definition at line 61 of file InterpreterInstanceStubs.cpp.
References InterpreterInstance::attachThread(), and InstanceApiContext::instance.
Halt()
void RexxEntry Halt (RexxInstance * c)
Definition at line 67 of file InterpreterInstanceStubs.cpp.
References InterpreterInstance::haltAllActivities(), InstanceApiContext::instance, and OREF_NULL.
InterpreterVersion()
size_t RexxEntry InterpreterVersion (RexxInstance *)
Definition at line 79 of file InterpreterInstanceStubs.cpp.
References Interpreter::getInterpreterVersion().
LanguageLevel()
size_t RexxEntry LanguageLevel (RexxInstance *)
Definition at line 84 of file InterpreterInstanceStubs.cpp.
References Interpreter::getLanguageLevel().
SetTrace()
void RexxEntry SetTrace (RexxInstance * c, logical_t setting)
Definition at line 73 of file InterpreterInstanceStubs.cpp.
References InstanceApiContext::instance, and InterpreterInstance::traceAllActivities().
Terminate()
void RexxEntry Terminate (RexxInstance * c)
Definition at line 52 of file InterpreterInstanceStubs.cpp.
References InstanceApiContext::instance, InterpreterInstance::terminate(), and Interpreter::terminateInterpreter().