ooRexx: Interpreter.cpp File Reference
Interpreter.cpp File Reference
#include "Interpreter.hpp"
#include "ActivityManager.hpp"
#include "QueueClass.hpp"
#include "SystemInterpreter.hpp"
#include "InterpreterInstance.hpp"
#include "DirectoryClass.hpp"
#include "ProtectedObject.hpp"
#include "RexxInternalApis.h"
#include "PackageManager.hpp"
#include "PackageClass.hpp"
#include <stdio.h>
#include "RexxErrorMessages.h"
#include "RexxMessageNumbers.h"
#include "RexxMessageTable.h"
Classes
struct msgEntry
struct msgMap
Macros
#define ERROR_TABLE
#define MESSAGE(code, message) {code, message},
#define MAJOR(code) {code, code##_msg},
#define MINOR(code) {code, code##_msg},
Typedefs
typedef struct msgEntry ERROR_MESSAGE
typedef struct msgMap ERROR_MAP
Functions
const char *REXXENTRY RexxGetErrorMessage (int code)
const char *REXXENTRY RexxGetErrorMessageByNumber (int msgid)
Variables
const int RC_OK = 0
const int RC_LOGIC_ERROR = 2
Macro Definition Documentation
ERROR_TABLE
#define ERROR_TABLE
Definition at line 689 of file Interpreter.cpp.
MAJOR
#define MAJOR (code) {code, code##_msg},
Definition at line 704 of file Interpreter.cpp.
MESSAGE
#define MESSAGE (code, message) {code, message},
Definition at line 692 of file Interpreter.cpp.
MINOR
#define MINOR (code) {code, code##_msg},
Definition at line 705 of file Interpreter.cpp.
Typedef Documentation
ERROR_MAP
typedef struct msgMap ERROR_MAP
ERROR_MESSAGE
typedef struct msgEntry ERROR_MESSAGE
Function Documentation
RexxGetErrorMessage()
const char* REXXENTRY RexxGetErrorMessage (int code)
Retrieve an error message by symbolic error number mapping.
Parameters
code The fully qualified message code.
Returns
The character string message or NULL if not found.
Definition at line 725 of file Interpreter.cpp.
References msgEntry::code.
Referenced by displayError(), Interpreter::getMessageText(), options_error(), parmerr(), and RexxGetErrorMessageByNumber().
RexxGetErrorMessageByNumber()
const char* REXXENTRY RexxGetErrorMessageByNumber (int msgid)
Retrieve an error message by assigned external message number. This is mapped to the appropriate Rexx error code.
Parameters
msgid The message number
Returns
The character string message or NULL if the message is not found.
Definition at line 750 of file Interpreter.cpp.
References msgMap::msgid, and RexxGetErrorMessage().
Referenced by getErrorMessage().
Variable Documentation
RC_LOGIC_ERROR
const int RC_LOGIC_ERROR = 2
Definition at line 77 of file Interpreter.cpp.
Referenced by Interpreter::logicError().
RC_OK
const int RC_OK = 0
Definition at line 76 of file Interpreter.cpp.