ooRexx: MethodContextStubs.cpp File Reference
MethodContextStubs.cpp File Reference
#include "RexxCore.h"
#include "ContextApi.hpp"
#include "NativeActivation.hpp"
#include "ProtectedObject.hpp"
#include "MethodClass.hpp"
#include "ActivityManager.hpp"
Functions
RexxArrayObject RexxEntry GetMethodArguments (RexxMethodContext *c)
RexxObjectPtr RexxEntry GetMethodArgument (RexxMethodContext *c, stringsize_t i)
RexxMethodObject RexxEntry GetCurrentMethod (RexxMethodContext *c)
CSTRING RexxEntry GetMessageName (RexxMethodContext *c)
RexxObjectPtr RexxEntry GetSelf (RexxMethodContext *c)
POINTER RexxEntry GetCSelf (RexxMethodContext *c)
RexxClassObject RexxEntry GetSuper (RexxMethodContext *c)
RexxObjectPtr RexxEntry GetScope (RexxMethodContext *c)
void RexxEntry SetObjectVariable (RexxMethodContext *c, CSTRING n, RexxObjectPtr v)
RexxObjectPtr RexxEntry GetObjectVariable (RexxMethodContext *c, CSTRING n)
RexxVariableReferenceObject RexxEntry GetObjectVariableReference (RexxMethodContext *c, CSTRING n)
void RexxEntry DropObjectVariable (RexxMethodContext *c, CSTRING n)
RexxObjectPtr RexxEntry ForwardMessage (RexxMethodContext *c, RexxObjectPtr o, CSTRING n, RexxClassObject clazz, RexxArrayObject a)
void RexxEntry SetGuardOn (RexxMethodContext *c)
void RexxEntry SetGuardOff (RexxMethodContext *c)
RexxClassObject RexxEntry FindContextClass (RexxMethodContext *c, CSTRING n)
POINTER RexxEntry AllocateObjectMemory (RexxMethodContext *c, size_t l)
POINTER RexxEntry ReallocateObjectMemory (RexxMethodContext *c, POINTER p, size_t l)
void RexxEntry FreeObjectMemory (RexxMethodContext *c, POINTER p)
RexxObjectPtr RexxEntry SetGuardOnWhenUpdated (RexxMethodContext *c, CSTRING n)
RexxObjectPtr RexxEntry SetGuardOffWhenUpdated (RexxMethodContext *c, CSTRING n)
void RexxEntry ThrowException0 (RexxMethodContext *c, size_t n)
void RexxEntry ThrowException1 (RexxMethodContext *c, size_t n, RexxObjectPtr o1)
void RexxEntry ThrowException2 (RexxMethodContext *c, size_t n, RexxObjectPtr o1, RexxObjectPtr o2)
void RexxEntry ThrowException (RexxMethodContext *c, size_t n, RexxArrayObject a)
void RexxEntry ThrowCondition (RexxMethodContext *c, CSTRING n, RexxStringObject desc, RexxObjectPtr add, RexxObjectPtr result)
Function Documentation
AllocateObjectMemory()
POINTER RexxEntry AllocateObjectMemory (RexxMethodContext * c, size_t l)
Definition at line 266 of file MethodContextStubs.cpp.
References NativeActivation::allocateObjectMemory(), and ApiContext::context.
DropObjectVariable()
void RexxEntry DropObjectVariable (RexxMethodContext * c, CSTRING n)
Definition at line 198 of file MethodContextStubs.cpp.
References ApiContext::context, and NativeActivation::dropObjectVariable().
FindContextClass()
RexxClassObject RexxEntry FindContextClass (RexxMethodContext * c, CSTRING n)
Definition at line 250 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::findClass(), new_upper_string(), NULLOBJECT, and ApiContext::ret().
ForwardMessage()
RexxObjectPtr RexxEntry ForwardMessage (RexxMethodContext * c, RexxObjectPtr o, CSTRING n, RexxClassObject clazz, RexxArrayObject a)
Definition at line 210 of file MethodContextStubs.cpp.
References ApiContext::activity, ApiContext::context, NativeActivation::forwardMessage(), new_upper_string(), NULLOBJECT, OREF_NULL, and ApiContext::ret().
FreeObjectMemory()
void RexxEntry FreeObjectMemory (RexxMethodContext * c, POINTER p)
Definition at line 294 of file MethodContextStubs.cpp.
References ApiContext::context, and NativeActivation::freeObjectMemory().
GetCSelf()
POINTER RexxEntry GetCSelf (RexxMethodContext * c)
Definition at line 120 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::cself(), and NULLOBJECT.
GetCurrentMethod()
RexxMethodObject RexxEntry GetCurrentMethod (RexxMethodContext * c)
Definition at line 81 of file MethodContextStubs.cpp.
References ApiContext::context, and ActivationBase::getExecutable().
GetMessageName()
CSTRING RexxEntry GetMessageName (RexxMethodContext * c)
Definition at line 94 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::getMessageName(), and RexxString::getStringData().
GetMethodArgument()
RexxObjectPtr RexxEntry GetMethodArgument (RexxMethodContext * c, stringsize_t i)
Definition at line 66 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::getArgument(), and NULLOBJECT.
GetMethodArguments()
RexxArrayObject RexxEntry GetMethodArguments (RexxMethodContext * c)
Definition at line 53 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::getArguments(), and NULLOBJECT.
GetObjectVariable()
RexxObjectPtr RexxEntry GetObjectVariable (RexxMethodContext * c, CSTRING n)
Definition at line 172 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::getObjectVariable(), and NULLOBJECT.
GetObjectVariableReference()
RexxVariableReferenceObject RexxEntry GetObjectVariableReference (RexxMethodContext * c, CSTRING n)
Definition at line 185 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::getObjectVariableReference(), and NULLOBJECT.
GetScope()
RexxObjectPtr RexxEntry GetScope (RexxMethodContext * c)
Definition at line 147 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::getScope(), and NULLOBJECT.
GetSelf()
RexxObjectPtr RexxEntry GetSelf (RexxMethodContext * c)
Definition at line 107 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::getSelf(), and NULLOBJECT.
GetSuper()
RexxClassObject RexxEntry GetSuper (RexxMethodContext * c)
Definition at line 134 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::getSuper(), and NULLOBJECT.
ReallocateObjectMemory()
POINTER RexxEntry ReallocateObjectMemory (RexxMethodContext * c, POINTER p, size_t l)
Definition at line 280 of file MethodContextStubs.cpp.
References ApiContext::context, and NativeActivation::reallocateObjectMemory().
SetGuardOff()
void RexxEntry SetGuardOff (RexxMethodContext * c)
Definition at line 238 of file MethodContextStubs.cpp.
References ApiContext::context, and NativeActivation::guardOff().
SetGuardOffWhenUpdated()
RexxObjectPtr RexxEntry SetGuardOffWhenUpdated (RexxMethodContext * c, CSTRING n)
Definition at line 321 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::guardOffWhenUpdated(), OREF_NULL, and ApiContext::ret().
SetGuardOn()
void RexxEntry SetGuardOn (RexxMethodContext * c)
Definition at line 226 of file MethodContextStubs.cpp.
References ApiContext::context, and NativeActivation::guardOn().
SetGuardOnWhenUpdated()
RexxObjectPtr RexxEntry SetGuardOnWhenUpdated (RexxMethodContext * c, CSTRING n)
Definition at line 307 of file MethodContextStubs.cpp.
References ApiContext::context, NativeActivation::guardOnWhenUpdated(), OREF_NULL, and ApiContext::ret().
SetObjectVariable()
void RexxEntry SetObjectVariable (RexxMethodContext * c, CSTRING n, RexxObjectPtr v)
Definition at line 160 of file MethodContextStubs.cpp.
References ApiContext::context, and NativeActivation::setObjectVariable().
ThrowCondition()
void RexxEntry ThrowCondition (RexxMethodContext * c, CSTRING n, RexxStringObject desc, RexxObjectPtr add, RexxObjectPtr result)
Definition at line 362 of file MethodContextStubs.cpp.
References ApiContext::activity, ApiContext::context, NativeActivation::enableConditionTrap(), new_upper_string(), OREF_NULL, and Activity::raiseCondition().
ThrowException()
void RexxEntry ThrowException (RexxMethodContext * c, size_t n, RexxArrayObject a)
Definition at line 356 of file MethodContextStubs.cpp.
References reportException().
ThrowException0()
void RexxEntry ThrowException0 (RexxMethodContext * c, size_t n)
Definition at line 338 of file MethodContextStubs.cpp.
References reportException().
ThrowException1()
void RexxEntry ThrowException1 (RexxMethodContext * c, size_t n, RexxObjectPtr o1)
Definition at line 344 of file MethodContextStubs.cpp.
References reportException().
ThrowException2()
void RexxEntry ThrowException2 (RexxMethodContext * c, size_t n, RexxObjectPtr o1, RexxObjectPtr o2)
Definition at line 350 of file MethodContextStubs.cpp.
References reportException().