ooRexx: MethodArguments.hpp File Reference
MethodArguments.hpp File Reference
#include "ActivityManager.hpp"
Functions
void missingArgument (size_t argumentPosition)
void missingArgument (const char *argumentPosition)
RexxObject * requiredArgument (RexxObject *object, size_t position)
RexxObject * requiredArgument (RexxObject *object, const char *position)
RexxString * stringArgument (RexxObject *object, size_t position)
RexxString * stringArgument (RexxObject *object, const char *name)
RexxString * optionalStringArgument (RexxObject *o, RexxString *d, size_t p)
RexxString * optionalStringArgument (RexxObject *o, RexxString *d, const char *p)
wholenumber_t numberArgument (RexxObject *argument, size_t position)
wholenumber_t numberArgument (RexxObject *argument, const char *position)
wholenumber_t optionalNumberArgument (RexxObject *o, wholenumber_t d, size_t p)
wholenumber_t optionalNumberArgument (RexxObject *o, wholenumber_t d, const char *p)
size_t lengthArgument (RexxObject *o, size_t p)
size_t lengthArgument (RexxObject *o, const char *p)
size_t nonNegativeArgument (RexxObject *o, size_t p)
size_t nonNegativeArgument (RexxObject *o, const char *p)
size_t optionalLengthArgument (RexxObject *o, size_t d, size_t p)
size_t optionalLengthArgument (RexxObject *o, size_t d, const char *p)
size_t positionArgument (RexxObject *o, size_t p)
size_t positionArgument (RexxObject *o, const char *p)
size_t optionalPositionArgument (RexxObject *o, size_t d, size_t p)
size_t optionalPositionArgument (RexxObject *o, size_t d, const char *p)
char padArgument (RexxObject *o, size_t p)
char padArgument (RexxObject *o, const char *p)
char optionalPadArgument (RexxObject *o, char d, size_t p)
char optionalPadArgument (RexxObject *o, char d, const char *p)
char optionArgument (RexxObject *o, size_t p)
char optionArgument (RexxObject *o, const char *p)
char optionArgument (RexxObject *o, const char *validOptions, size_t p)
char optionArgument (RexxObject *o, const char *validOptions, const char *p)
void stringArrayArgument (ArrayClass *argArray, const char *position)
char optionalOptionArgument (RexxObject *o, char d, size_t p)
char optionalOptionArgument (RexxObject *o, char d, const char *p)
char optionalOptionArgument (RexxObject *o, const char *v, char d, size_t p)
char optionalOptionArgument (RexxObject *o, const char *v, char d, const char *p)
size_t optionalNonNegative (RexxObject *o, size_t d, size_t p)
size_t optionalNonNegative (RexxObject *o, size_t d, const char *p)
size_t optionalPositive (RexxObject *o, size_t d, size_t p)
size_t optionalPositive (RexxObject *o, size_t d, const char *p)
double floatingPointArgument (RexxObject *argument, const char *name)
ArrayClass * arrayArgument (RexxObject *object, size_t position)
ArrayClass * arrayArgument (RexxObject *object, const char *name)
void classArgument (RexxObject *object, RexxClass *clazz, const char *name)
RexxObject * resultOrNil (RexxInternalObject *o)
RexxObject * booleanObject (bool v)
Variables
const int ARG_ONE = 1
const int ARG_TWO = 2
const int ARG_THREE = 3
const int ARG_FOUR = 4
const int ARG_FIVE = 5
const int ARG_SIX = 6
const int ARG_SEVEN = 7
const int ARG_EIGHT = 8
const int ARG_NINE = 9
const int ARG_TEN = 10
Function Documentation
arrayArgument() [1/2]
ArrayClass* arrayArgument (RexxObject * object, const char * name) inline
REQUEST an ARRAY needed as a method argument. This raises an error if the object cannot be converted to a single dimensional array item.
Parameters
object The argument object.
position The argument name (used for error reporting.)
Returns
A converted single-dimension array.
Definition at line 703 of file MethodArguments.hpp.
References Error_Invalid_argument_noarg, Error_Invalid_argument_noarray, ArrayClass::isMultiDimensional(), OREF_NULL, reportException(), RexxInternalObject::requestArray(), and TheNilObject.
arrayArgument() [2/2]
ArrayClass* arrayArgument (RexxObject * object, size_t position) inline
REQUEST an ARRAY needed as a method argument. This raises an error if the object cannot be converted to a single dimensional array item.
Parameters
object The argument object.
position The argument position (used for error reporting.)
Returns
A converted single-dimension array.
Definition at line 675 of file MethodArguments.hpp.
References Error_Execution_noarray, ArrayClass::isMultiDimensional(), missingArgument(), OREF_NULL, reportException(), RexxInternalObject::requestArray(), and TheNilObject.
Referenced by RoutineClass::callWithRexx(), SupplierClass::initRexx(), PackageClass::loadPackageRexx(), MessageClass::newRexx(), NativeActivation::objectToValue(), NativeActivation::processArguments(), MessageClass::replyWithRexx(), RexxObject::run(), RexxObject::sendWith(), MessageClass::sendWithRexx(), RexxObject::startWith(), MessageClass::startWithRexx(), StemClass::unknownRexx(), StringHashCollection::unknownRexx(), and VariableReference::unknownRexx().
booleanObject()
RexxObject* booleanObject (bool v) inline
Handy method for transforming a boolean value into Rexx method boolean return values (i.e., .true or .false).
Parameters
v The boolean value.
Returns
Either TheTrueObject or TheFalseObject, depending on the argument value.
Definition at line 761 of file MethodArguments.hpp.
References TheFalseObject, and TheTrueObject.
Referenced by RexxString::abbrev(), PackageManager::addRegisteredRoutine(), RexxInteger::andOp(), RexxString::andOp(), SupplierClass::available(), BUILTIN(), RexxString::caselessAbbrev(), RexxString::caselessContains(), MutableBuffer::caselessContains(), MutableBuffer::caselessContainsWord(), RexxString::caselessContainsWord(), MutableBuffer::caselessEndsWithRexx(), RexxString::caselessEndsWithRexx(), RexxString::caselessEquals(), MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessStartsWithRexx(), RexxString::caselessStartsWithRexx(), MessageClass::completed(), StringUtil::containsRexx(), MutableBuffer::containsWord(), RexxString::containsWord(), StringUtil::dataType(), PackageManager::dropRegisteredRoutine(), MutableBuffer::endsWithRexx(), RexxString::endsWithRexx(), RexxClass::equal(), RexxInteger::equal(), NumberString::equal(), RexxObject::equal(), PointerClass::equal(), RexxString::equals(), RexxInfo::getCaseSensitiveFiles(), MessageClass::halt(), StringHashCollection::hasEntryRexx(), MessageClass::hasError(), StemClass::hasIndex(), HashCollection::hasIndexRexx(), ArrayClass::hasIndexRexx(), ListClass::hasIndexRexx(), StemClass::hasItem(), ArrayClass::hasItemRexx(), HashCollection::hasItemRexx(), ListClass::hasItemRexx(), BagClass::hasItemRexx(), RelationClass::hasItemRexx(), RexxObject::hasMethodRexx(), MessageClass::hasResult(), RexxClass::isAbstractRexx(), MethodClass::isAbstractRexx(), MethodClass::isAttributeRexx(), MethodClass::isConstantRexx(), ArrayClass::isEmptyRexx(), ListClass::isEmptyRexx(), StemClass::isEmptyRexx(), HashCollection::isEmptyRexx(), RexxInteger::isGreaterOrEqual(), RexxInteger::isGreaterThan(), MethodClass::isGuardedRexx(), RexxObject::isInstanceOfRexx(), RexxInteger::isLessOrEqual(), RexxInteger::isLessThan(), RexxClass::isMetaClassRexx(), RexxObject::isNilRexx(), PointerClass::isNull(), MethodClass::isPackageRexx(), MethodClass::isPrivateRexx(), MethodClass::isProtectedRexx(), RexxClass::isSubclassOf(), PackageClass::loadLibraryRexx(), LogicalToObject(), MutableBuffer::match(), RexxString::match(), RexxClass::notEqual(), RexxInteger::notEqual(), NumberString::notEqual(), RexxString::notEqual(), RexxObject::notEqual(), PointerClass::notEqual(), RexxInteger::notOp(), RexxString::notOp(), RexxInteger::operatorNot(), RexxString::operatorNot(), RexxInteger::orOp(), RexxString::orOp(), EventSemaphoreClass::posted(), RexxClass::queryMixinClass(), PackageManager::queryRegisteredRoutine(), MutexSemaphoreClass::release(), MutexSemaphoreClass::request(), MutableBuffer::startsWithRexx(), RexxString::startsWithRexx(), RexxInteger::strictEqual(), NumberString::strictEqual(), RexxObject::strictEqual(), RexxString::strictEqual(), RexxInteger::strictGreaterOrEqual(), RexxInteger::strictGreaterThan(), RexxInteger::strictLessOrEqual(), RexxInteger::strictLessThan(), RexxInteger::strictNotEqual(), NumberString::strictNotEqual(), RexxString::strictNotEqual(), RexxObject::strictNotEqual(), NativeActivation::valueToObject(), EventSemaphoreClass::wait(), RexxInteger::xorOp(), and RexxString::xorOp().
classArgument()
void classArgument (RexxObject * object, RexxClass * clazz, const char * name) inline
Validate that an argument is an instance of a specific class.
Parameters
object The argument to test.
clazz The class type to check it against.
name The argument name for error reporting.
Definition at line 727 of file MethodArguments.hpp.
References Error_Invalid_argument_noarg, Error_Invalid_argument_noclass, RexxClass::getId(), RexxObject::isInstanceOf(), OREF_NULL, and reportException().
Referenced by PackageClass::addClassRexx(), PackageClass::addPackageRexx(), PackageClass::addPublicClassRexx(), PackageClass::addPublicRoutineRexx(), PackageClass::addRoutineRexx(), RexxObject::decodeMessageName(), RexxObject::isInstanceOfRexx(), RexxClass::isSubclassOf(), and MessageClass::notify().
floatingPointArgument()
double floatingPointArgument (RexxObject * argument, const char * name)
Take in an argument passed to a method, convert it to a floating point number. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The name of the argument (used for error reporting.)
Returns
The argument converted to a double floating point value.
Definition at line 395 of file StringClassUtil.cpp.
References RexxInternalObject::doubleValue(), Error_Invalid_argument_number, missingArgument(), OREF_NULL, and reportException().
Referenced by MutexSemaphoreClass::request(), and EventSemaphoreClass::wait().
lengthArgument() [1/2]
size_t lengthArgument (RexxObject * argument, const char * position)
Parse a length method argument. this must be a non-negative whole number. Raises a number if the argument was omitted or is not a length numeric value.
Parameters
o The object to check.
p The argument position.
Returns
The converted numeric value of the object.
Take in an argument passed to a method, convert it to a length object, verifying that the number is a non-negative value. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to a non-negative integer value.
Definition at line 87 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Invalid_argument_length, missingArgument(), OREF_NULL, reportException(), and RexxInternalObject::unsignedNumberValue().
lengthArgument() [2/2]
size_t lengthArgument (RexxObject * argument, size_t position)
Parse a length method argument. this must be a non-negative whole number. Raises a number if the argument was omitted or is not a length numeric value.
Parameters
o The object to check.
p The argument position.
Returns
The converted numeric value of the object.
Take in an argument passed to a method, convert it to a length object, verifying that the number is a non-negative value. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to a non-negative integer value.
Definition at line 61 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_method_length, missingArgument(), OREF_NULL, reportException(), and RexxInternalObject::unsignedNumberValue().
Referenced by RexxString::center(), RexxString::left(), optionalLengthArgument(), RexxString::right(), and MutableBuffer::setBufferSize().
missingArgument() [1/2]
void missingArgument (const char * argumentPosition) inline
Report an error with a missing argument.
Parameters
argumentPosition The argument position.
Definition at line 86 of file MethodArguments.hpp.
References Error_Invalid_argument_noarg, and reportException().
missingArgument() [2/2]
void missingArgument (size_t argumentPosition) inline
Report an error with a missing argument.
Parameters
argumentPosition The argument position.
Definition at line 74 of file MethodArguments.hpp.
References Error_Incorrect_method_noarg, and reportException().
Referenced by arrayArgument(), floatingPointArgument(), lengthArgument(), nonNegativeArgument(), numberArgument(), positionArgument(), requiredArgument(), AttributeSetterCode::run(), RexxObject::run(), RexxObject::send(), RexxObject::start(), and stringArgument().
nonNegativeArgument() [1/2]
size_t nonNegativeArgument (RexxObject * argument, const char * position)
Parse a non-negative method argument. this must be a non-negative whole number. Raises a number if the argument was omitted or is not a length numeric value.
Parameters
o The object to check.
p The argument position.
Returns
The converted numeric value of the object.
Take in an argument passed to a method, convert it to a length object, verifying that the number is a non-negative value. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to a non-negative integer value.
Definition at line 188 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, missingArgument(), OREF_NULL, and RexxInternalObject::requiredNonNegative().
nonNegativeArgument() [2/2]
size_t nonNegativeArgument (RexxObject * argument, size_t position)
Parse a non-negative method argument. this must be a non-negative whole number. Raises a number if the argument was omitted or is not a length numeric value.
Parameters
o The object to check.
p The argument position.
Returns
The converted numeric value of the object.
Take in an argument passed to a method, convert it to a length object, verifying that the number is a non-negative value. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to a non-negative integer value.
Definition at line 167 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, missingArgument(), OREF_NULL, and RexxInternalObject::requiredNonNegative().
Referenced by RexxString::copies(), ArrayClass::createMultidimensional(), optionalNonNegative(), and ArrayClass::validateSize().
numberArgument() [1/2]
wholenumber_t numberArgument (RexxObject * argument, const char * position)
Take in an argument passed to a method, convert it to a numeric object. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to an integer value.
Definition at line 140 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Invalid_argument_whole, missingArgument(), RexxInternalObject::numberValue(), OREF_NULL, and reportException().
numberArgument() [2/2]
wholenumber_t numberArgument (RexxObject * argument, size_t position)
Take in an argument passed to a method, convert it to a numeric object. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to an integer value.
Definition at line 113 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_method_whole, missingArgument(), RexxInternalObject::numberValue(), OREF_NULL, and reportException().
Referenced by optionalNumberArgument().
optionalLengthArgument() [1/2]
size_t optionalLengthArgument (RexxObject * o, size_t d, const char * p) inline
Parse an optional length method argument. this must be a non-negative whole number. Raises a number if the argument not a length numeric value.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position.
Returns
The converted numeric value of the object.
Definition at line 344 of file MethodArguments.hpp.
References lengthArgument(), and OREF_NULL.
optionalLengthArgument() [2/2]
size_t optionalLengthArgument (RexxObject * o, size_t d, size_t p) inline
Parse an optional length method argument. this must be a non-negative whole number. Raises a number if the argument not a length numeric value.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position.
Returns
The converted numeric value of the object.
Definition at line 327 of file MethodArguments.hpp.
References lengthArgument(), and OREF_NULL.
Referenced by RexxString::abbrev(), RexxString::caselessAbbrev(), RexxString::caselessCompareToRexx(), RexxString::caselessContains(), MutableBuffer::caselessContains(), MutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessPos(), RexxString::caselessPosRexx(), RexxString::compareToRexx(), StringUtil::containsRexx(), NumberString::d2xD2c(), RexxString::delstr(), RexxString::delWord(), MutableBuffer::delWord(), HashCollection::initRexx(), ListClass::initRexx(), QueueClass::initRexx(), MutableBuffer::insert(), RexxString::insert(), StringUtil::lastPosRexx(), MutableBuffer::lower(), RexxString::lowerRexx(), MutableBuffer::match(), RexxString::match(), MutableBuffer::mydelete(), MutableBuffer::newRexx(), MutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), MutableBuffer::replaceAt(), RexxString::replaceAt(), ArrayClass::sectionRexx(), ListClass::sectionRexx(), RexxString::space(), MutableBuffer::space(), StringUtil::substr(), StringUtil::subWord(), StringUtil::subWords(), RexxString::translate(), MutableBuffer::translate(), MutableBuffer::upper(), RexxString::upperRexx(), StringUtil::verify(), and RexxString::x2dC2d().
optionalNonNegative() [1/2]
size_t optionalNonNegative (RexxObject * o, size_t d, const char * p) inline
Handle an optional non-negative numeric option.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position used for error reporting.
Returns
The converted numeric value.
Definition at line 616 of file MethodArguments.hpp.
References nonNegativeArgument(), and OREF_NULL.
optionalNonNegative() [2/2]
size_t optionalNonNegative (RexxObject * o, size_t d, size_t p) inline
Handle an optional non-negative numeric option.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position used for error reporting.
Returns
The converted numeric value.
Definition at line 601 of file MethodArguments.hpp.
References nonNegativeArgument(), and OREF_NULL.
Referenced by RexxString::caselessChangeStr(), MutableBuffer::caselessChangeStr(), RexxString::changeStr(), MutableBuffer::changeStr(), NumberString::formatRexx(), MutableBuffer::insert(), and NumberString::trunc().
optionalNumberArgument() [1/2]
wholenumber_t optionalNumberArgument (RexxObject * o, wholenumber_t d, const char * p) inline
Parse an optional whole number method argument. this must be a whole number. Raises a number if the argument not a numeric value.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position.
Returns
The converted numeric value of the object.
Definition at line 258 of file MethodArguments.hpp.
References numberArgument(), and OREF_NULL.
optionalNumberArgument() [2/2]
wholenumber_t optionalNumberArgument (RexxObject * o, wholenumber_t d, size_t p) inline
Parse an optional whole number method argument. this must be a whole number. Raises a number if the argument not a numeric value.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position.
Returns
The converted numeric value of the object.
Definition at line 241 of file MethodArguments.hpp.
References numberArgument(), and OREF_NULL.
optionalOptionArgument() [1/4]
char optionalOptionArgument (RexxObject * o, char d, const char * p) inline
Parse an optional option argument. This must be a non-zero length string.
Parameters
o The object to check.
d The default option if this was an omitted argument.
p The argument position for error messages.
Returns
The first character of the option string.
Definition at line 552 of file MethodArguments.hpp.
References optionArgument(), and OREF_NULL.
optionalOptionArgument() [2/4]
char optionalOptionArgument (RexxObject * o, char d, size_t p) inline
Parse an optional option argument. This must be a non-zero length string.
Parameters
o The object to check.
d The default option if this was an omitted argument.
p The argument position for error messages.
Returns
The first character of the option string.
Definition at line 536 of file MethodArguments.hpp.
References optionArgument(), and OREF_NULL.
Referenced by RexxString::dataType(), RexxString::strip(), ArrayClass::toString(), and StringUtil::verify().
optionalOptionArgument() [3/4]
char optionalOptionArgument (RexxObject * o, const char * v, char d, const char * p) inline
Parse an optional option argument. This must be a non-zero length string.
Parameters
o The object to check.
v The list of valid option characters.
d The default option if this was an omitted argument.
p The argument position for error messages.
Returns
The first character of the option string.
Definition at line 586 of file MethodArguments.hpp.
References optionArgument(), and OREF_NULL.
optionalOptionArgument() [4/4]
char optionalOptionArgument (RexxObject * o, const char * v, char d, size_t p) inline
Parse an optional option argument. This must be a non-zero length string.
Parameters
o The object to check.
v The list of valid option characters.
d The default option if this was an omitted argument.
p The argument position for error messages.
Returns
The first character of the option string.
Definition at line 569 of file MethodArguments.hpp.
References optionArgument(), and OREF_NULL.
optionalPadArgument() [1/2]
char optionalPadArgument (RexxObject * o, char d, const char * p) inline
Parse an optional pad argument. This must a string object and only a single character long.
Parameters
o The object argument to check.
d The default pad character if the argument was omitted.
p The argument position, for error reporting.
Returns
The pad character from the argument string.
Definition at line 462 of file MethodArguments.hpp.
References OREF_NULL, and padArgument().
optionalPadArgument() [2/2]
char optionalPadArgument (RexxObject * o, char d, size_t p) inline
Parse an optional pad argument. This must a string object and only a single character long.
Parameters
o The object argument to check.
d The default pad character if the argument was omitted.
p The argument position, for error reporting.
Returns
The pad character from the argument string.
Definition at line 446 of file MethodArguments.hpp.
References OREF_NULL, and padArgument().
Referenced by RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), RexxString::caselessCompare(), RexxString::center(), RexxString::compare(), MutableBuffer::insert(), RexxString::insert(), RexxString::left(), MutableBuffer::overlay(), RexxString::overlay(), MutableBuffer::replaceAt(), RexxString::replaceAt(), RexxString::right(), RexxString::space(), MutableBuffer::space(), StringUtil::substr(), RexxString::translate(), and MutableBuffer::translate().
optionalPositionArgument() [1/2]
size_t optionalPositionArgument (RexxObject * o, size_t d, const char * p) inline
Parse an optional position method argument. this must be a positive whole number. Raises a number if the argument not a length numeric value.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position.
Returns
The converted numeric value of the object.
Definition at line 404 of file MethodArguments.hpp.
References OREF_NULL, and positionArgument().
optionalPositionArgument() [2/2]
size_t optionalPositionArgument (RexxObject * o, size_t d, size_t p) inline
Parse an optional position method argument. this must be a positive whole number. Raises a number if the argument not a length numeric value.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position.
Returns
The converted numeric value of the object.
Definition at line 387 of file MethodArguments.hpp.
References OREF_NULL, and positionArgument().
Referenced by RexxString::caselessCompareToRexx(), RexxString::caselessContains(), MutableBuffer::caselessContains(), MutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessPos(), RexxString::caselessPosRexx(), StringUtil::caselessWordPos(), RexxString::compareToRexx(), StringUtil::containsRexx(), RexxString::delstr(), StringUtil::lastPosRexx(), MutableBuffer::lower(), RexxString::lowerRexx(), MutableBuffer::match(), RexxString::match(), MutableBuffer::mydelete(), MutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), StringUtil::subWords(), RexxString::translate(), MutableBuffer::translate(), MutableBuffer::upper(), RexxString::upperRexx(), StringUtil::verify(), and StringUtil::wordPos().
optionalPositive() [1/2]
size_t optionalPositive (RexxObject * o, size_t d, const char * p) inline
Handle an optional positive numeric option.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position used for error reporting.
Returns
The converted numeric value.
Definition at line 646 of file MethodArguments.hpp.
References OREF_NULL, and RexxInternalObject::requiredPositive().
optionalPositive() [2/2]
size_t optionalPositive (RexxObject * o, size_t d, size_t p) inline
Handle an optional positive numeric option.
Parameters
o The object to check.
d The default value to return if the argument was omitted.
p The argument position used for error reporting.
Returns
The converted numeric value.
Definition at line 631 of file MethodArguments.hpp.
References OREF_NULL, and RexxInternalObject::requiredPositive().
optionalStringArgument() [1/2]
RexxString* optionalStringArgument (RexxObject * o, RexxString * d, const char * p) inline
handle an optional string argument where a default argument value is provided.
Parameters
o The argument object to test.
d The default argument value (can be null)
p The argument position.
Returns
The argument value, in string form.
Definition at line 198 of file MethodArguments.hpp.
References OREF_NULL, and stringArgument().
optionalStringArgument() [2/2]
RexxString* optionalStringArgument (RexxObject * o, RexxString * d, size_t p) inline
handle an optional string argument where a default argument value is provided.
Parameters
o The argument object to test.
d The default argument value (can be null)
p The argument position.
Returns
The argument value, in string form.
Definition at line 181 of file MethodArguments.hpp.
References OREF_NULL, and stringArgument().
Referenced by PackageClass::addPackageRexx(), RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), MessageClass::halt(), StemClass::StemClass(), RexxString::strip(), RexxString::translate(), and MutableBuffer::translate().
optionArgument() [1/4]
char optionArgument (RexxObject * argument, const char * position)
Parse an option argument. This must be a non-zero length string.
Parameters
o The object to check.
p The argument position for error messages.
Returns
The first character of the option string.
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF.
Parameters
argument The argument to test.
position The position of the argument
Returns
The first character of the option string.
Definition at line 323 of file StringClassUtil.cpp.
References RexxString::getChar(), stringArgument(), and Utilities::toUpper().
optionArgument() [2/4]
char optionArgument (RexxObject * argument, const char * validOptions, const char * position)
Parse an option argument. This must be a non-zero length string.
Parameters
o The object to check.
validOptions The list of valid option characters as an ASCII-Z string.
p The argument position for error messages.
Returns
The first character of the option string.
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF. Also validate against the set of allowed characters.
Parameters
argument The argument to test.
position The position of the argument
Returns
The first character of the option string.
Definition at line 369 of file StringClassUtil.cpp.
References Error_Incorrect_method_option, RexxString::getChar(), RexxString::isNullString(), reportException(), stringArgument(), and Utilities::toUpper().
optionArgument() [3/4]
char optionArgument (RexxObject * argument, const char * validOptions, size_t position)
Parse an option argument. This must be a non-zero length string.
Parameters
o The object to check.
validOptions The list of valid option characters as an ASCII-Z string.
p The argument position for error messages.
Returns
The first character of the option string.
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF. Also validate against the set of allowed characters.
Parameters
argument The argument to test.
position The position of the argument
Returns
The first character of the option string.
Definition at line 342 of file StringClassUtil.cpp.
References Error_Incorrect_method_option, RexxString::getChar(), RexxString::isNullString(), reportException(), stringArgument(), and Utilities::toUpper().
optionArgument() [4/4]
char optionArgument (RexxObject * argument, size_t position)
Parse an option argument. This must be a non-zero length string.
Parameters
o The object to check.
p The argument position for error messages.
Returns
The first character of the option string.
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF.
Parameters
argument The argument to test.
position The position of the argument
Returns
The first character of the option string.
Definition at line 305 of file StringClassUtil.cpp.
References RexxString::getChar(), stringArgument(), and Utilities::toUpper().
Referenced by MessageClass::newRexx(), optionalOptionArgument(), and RexxObject::run().
padArgument() [1/2]
char padArgument (RexxObject * argument, const char * position)
Parse a pad argument. This must a string object and only a single character long.
Parameters
o The object argument to check. Raises an error if this was omitted.
p The argument position, for error reporting.
Returns
The pad character from the argument string.
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF.
Parameters
argument The argument to test.
position The argument position in the argument list.
Returns
The first character of the option.
Definition at line 283 of file StringClassUtil.cpp.
References Error_Invalid_argument_pad, RexxString::getChar(), RexxString::getLength(), new_string(), reportException(), and stringArgument().
padArgument() [2/2]
char padArgument (RexxObject * argument, size_t position)
Parse a pad argument. This must a string object and only a single character long.
Parameters
o The object argument to check. Raises an error if this was omitted.
p The argument position, for error reporting.
Returns
The pad character from the argument string.
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF.
Parameters
argument The argument to test.
position The argument position in the argument list.
Returns
The first character of the option.
Definition at line 261 of file StringClassUtil.cpp.
References Error_Incorrect_method_pad, RexxString::getChar(), RexxString::getLength(), reportException(), and stringArgument().
Referenced by optionalPadArgument().
positionArgument() [1/2]
size_t positionArgument (RexxObject * argument, const char * position)
Parse a position method argument. this must be a positive whole number. Raises a number if the argument was omitted or is not a length numeric value.
Parameters
o The object to check.
p The argument position.
Returns
The converted numeric value of the object.
Take in an argument passed to a method, convert it to a position value, verifying that the number is a positive value. If the argument is omitted, an error is raised.
Parameters
argument The argument to test.
position The argument list position of the argument.
Returns
The converted numeric value.
Definition at line 235 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Invalid_argument_position, missingArgument(), OREF_NULL, reportException(), and RexxInternalObject::unsignedNumberValue().
positionArgument() [2/2]
size_t positionArgument (RexxObject * argument, size_t position)
Parse a position method argument. this must be a positive whole number. Raises a number if the argument was omitted or is not a length numeric value.
Parameters
o The object to check.
p The argument position.
Returns
The converted numeric value of the object.
Take in an argument passed to a method, convert it to a position value, verifying that the number is a positive value. If the argument is omitted, an error is raised.
Parameters
argument The argument to test.
position The argument list position of the argument.
Returns
The converted numeric value.
Definition at line 209 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_method_position, missingArgument(), OREF_NULL, reportException(), and RexxInternalObject::unsignedNumberValue().
Referenced by MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), RexxString::delWord(), MutableBuffer::delWord(), ArrayClass::extendMulti(), PackageClass::getSourceLineRexx(), MutableBuffer::match(), RexxString::match(), MutableBuffer::matchChar(), RexxString::matchChar(), optionalPositionArgument(), MutableBuffer::replaceAt(), RexxString::replaceAt(), StringUtil::subchar(), StringUtil::substr(), StringUtil::subWord(), ArrayClass::validateMultiDimensionIndex(), StringUtil::word(), StringUtil::wordIndex(), and StringUtil::wordLength().
requiredArgument() [1/2]
RexxObject* requiredArgument (RexxObject * object, const char * position) inline
Check for required arguments and raise a missing argument error for the given position.
Parameters
object The reference to check.
position the position of the argument for the error message.
Definition at line 116 of file MethodArguments.hpp.
References missingArgument(), and OREF_NULL.
requiredArgument() [2/2]
RexxObject* requiredArgument (RexxObject * object, size_t position) inline
Check for required arguments and raise a missing argument error for the given position.
Parameters
object The reference to check.
position the position of the argument for the error message.
Definition at line 99 of file MethodArguments.hpp.
References missingArgument(), and OREF_NULL.
Referenced by RelationClass::allAt(), RelationClass::allIndexRexx(), RexxInteger::andOp(), RexxString::andOp(), ArrayClass::appendRexx(), ListClass::appendRexx(), StemClass::bracketEqual(), RexxInteger::choiceRexx(), RexxString::choiceRexx(), RexxString::comp(), NumberString::comp(), RexxInteger::comp(), RexxString::concatBlank(), RexxString::concatRexx(), RexxObject::decodeMessageName(), RexxClass::defineClassMethod(), RexxClass::defineMethodsRexx(), ArrayClass::deleteRexx(), QueueClass::deleteRexx(), RexxClass::enhanced(), RexxClass::equal(), RexxObject::equal(), PointerClass::equal(), ArrayClass::fillRexx(), ArrayClass::hasItemRexx(), HashCollection::hasItemRexx(), ListClass::hasItemRexx(), BagClass::hasItemRexx(), RelationClass::hasItemRexx(), ArrayClass::indexRexx(), ListClass::indexRexx(), HashCollection::indexRexx(), RexxClass::inherit(), RexxInteger::Max(), RexxInteger::Min(), NumberString::modulo(), MessageClass::newRexx(), WeakReference::newRexx(), RexxClass::notEqual(), RexxObject::notEqual(), PointerClass::notEqual(), NumberString::operatorArgument(), RexxInteger::orOp(), RexxString::orOp(), NumberString::power(), RexxString::primitiveCaselessIsEqual(), RexxString::primitiveIsEqual(), BaseExecutable::processNewExecutableArgs(), QueueClass::pushRexx(), ArrayClass::putRexx(), QueueClass::putRexx(), QueueClass::queueRexx(), RelationClass::removeAll(), StemClass::removeItemRexx(), ArrayClass::removeItemRexx(), ListClass::removeItemRexx(), HashCollection::removeItemRexx(), BagClass::removeItemRexx(), RelationClass::removeItemRexx(), RexxObject::run(), ArrayClass::sectionRexx(), VariableReference::setValueRexx(), ArrayClass::stableSortWithRexx(), RexxObject::start(), RexxObject::startWith(), RexxInteger::strictComp(), RexxObject::strictEqual(), RexxInteger::strictEquality(), RexxObject::strictNotEqual(), RexxClass::uninherit(), HashCollection::validateIndex(), ListClass::validateIndex(), HashCollection::validateValueIndex(), IndexOnlyHashCollection::validateValueIndex(), RexxInteger::xorOp(), and RexxString::xorOp().
resultOrNil()
RexxObject* resultOrNil (RexxInternalObject * o) inline
Handy function for situations where a NULL results needs translation into .nil.
Parameters
o The result value.
Returns
Either the result object, or TheNilObject.
Definition at line 749 of file MethodArguments.hpp.
References OREF_NULL, and TheNilObject.
Referenced by ArrayClass::deleteRexx(), QueueClass::deleteRexx(), StringHashCollection::entryRexx(), MessageClass::errorCondition(), PackageClass::findClassRexx(), PackageClass::findNamespaceRexx(), PackageClass::findPublicClassRexx(), PackageClass::findPublicRoutineRexx(), PackageClass::findRoutineRexx(), ListClass::firstItemRexx(), RexxClass::getAnnotationRexx(), PackageClass::getAnnotationRexx(), BaseExecutable::getAnnotationRexx(), StackFrameClass::getContext(), StackFrameClass::getExecutable(), PackageClass::getMainRexx(), RexxContext::getName(), RexxClass::getPackage(), BaseExecutable::getPackage(), PackageClass::getResourceRexx(), HashCollection::getRexx(), ArrayClass::getRexx(), ListClass::getRexx(), MethodClass::getScopeRexx(), StackFrameClass::getTarget(), SupplierClass::index(), HashCollection::indexRexx(), RexxObject::instanceMethod(), SupplierClass::item(), ListClass::lastItemRexx(), RoutineClass::loadExternalRoutine(), RexxInternalObject::makeArray(), RexxInternalObject::makeString(), HashContents::nextItem(), RexxActivation::novalueHandler(), QueueClass::pullRexx(), StringHashCollection::removeEntryRexx(), ListClass::removeItemRexx(), HashCollection::removeItemRexx(), BagClass::removeItemRexx(), RelationClass::removeItemRexx(), HashCollection::removeRexx(), ArrayClass::removeRexx(), ListClass::removeRexx(), RexxInternalObject::requestArray(), RexxObject::requestRexx(), RexxInternalObject::requiredString(), MessageClass::result(), StringHashCollection::unknown(), and WeakReference::value().
stringArgument() [1/2]
RexxString* stringArgument (RexxObject * object, const char * name) inline
REQUEST a STRING needed as a method argument. This raises an error if the object cannot be converted to a string value.
Parameters
object The object to check.
name The parameter name of the argument (used for error reporting.)
Returns
The string value of the object if it truely has a string value.
Definition at line 161 of file MethodArguments.hpp.
References Error_Invalid_argument_noarg, OREF_NULL, and reportException().
stringArgument() [2/2]
RexxString* stringArgument (RexxObject * object, size_t position) inline
REQUEST a STRING needed as a method argument. This raises an error if the object cannot be converted to a string value.
Parameters
object The object argument to check.
position The argument position, used for any error messages.
Returns
The String value of the object, if it really has a string value.
Definition at line 136 of file MethodArguments.hpp.
References missingArgument(), and OREF_NULL.
Referenced by RexxString::abbrev(), PackageClass::addClassRexx(), PackageClass::addPublicClassRexx(), PackageClass::addPublicRoutineRexx(), PackageClass::addRoutineRexx(), MutableBuffer::appendRexx(), BUILTIN(), NativeActivation::callRegisteredRoutine(), RexxString::caselessAbbrev(), RexxString::caselessChangeStr(), MutableBuffer::caselessChangeStr(), RexxString::caselessCompare(), RexxString::caselessCompareToRexx(), RexxString::caselessContains(), MutableBuffer::caselessContains(), RexxString::caselessCountStrRexx(), MutableBuffer::caselessCountStrRexx(), MutableBuffer::caselessEndsWithRexx(), RexxString::caselessEndsWithRexx(), MutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), MutableBuffer::caselessPos(), RexxString::caselessPosRexx(), MutableBuffer::caselessStartsWithRexx(), RexxString::caselessStartsWithRexx(), StringUtil::caselessWordPos(), RexxString::changeStr(), MutableBuffer::changeStr(), RexxString::compare(), RexxString::compareTo(), RexxString::compareToRexx(), StringUtil::containsRexx(), RexxString::countStrRexx(), MutableBuffer::countStrRexx(), NativeActivation::cstring(), RexxObject::decodeMessageName(), RexxClass::defineClassMethod(), RexxClass::defineMethod(), RexxClass::deleteMethod(), MutableBuffer::endsWithRexx(), RexxString::endsWithRexx(), PackageClass::findClassRexx(), PackageClass::findNamespaceRexx(), PackageClass::findProgramRexx(), PackageClass::findPublicClassRexx(), PackageClass::findPublicRoutineRexx(), PackageClass::findRoutineRexx(), RexxClass::getAnnotationRexx(), PackageClass::getAnnotationRexx(), BaseExecutable::getAnnotationRexx(), RexxBehaviour::getMethodObject(), PackageClass::getResourceRexx(), RexxObject::hasMethodRexx(), MutableBuffer::insert(), RexxString::insert(), RexxObject::instanceMethod(), StringUtil::lastPosRexx(), MethodClass::loadExternalMethod(), RoutineClass::loadExternalRoutine(), PackageClass::loadLibraryRexx(), PackageClass::loadPackageRexx(), StringUtil::makearray(), MutableBuffer::match(), RexxString::match(), MutableBuffer::matchChar(), RexxString::matchChar(), RexxClass::method(), MutableBuffer::newRexx(), RexxString::newRexx(), RexxClass::newRexx(), PackageClass::newRexx(), RexxObject::objectNameEquals(), NativeActivation::objectToValue(), optionalStringArgument(), optionArgument(), MutableBuffer::overlay(), RexxString::overlay(), padArgument(), StringUtil::posRexx(), NativeActivation::processArguments(), BaseExecutable::processNewExecutableArgs(), BaseExecutable::processNewFileExecutableArgs(), MutableBuffer::replaceAt(), RexxString::replaceAt(), StemClass::request(), RexxObject::requestRexx(), NativeActivation::resolveStemVariable(), RexxObject::setMethod(), DirectoryClass::setMethodRexx(), MutableBuffer::setTextRexx(), MutableBuffer::startsWithRexx(), RexxString::startsWithRexx(), RexxString::strictComp(), ArrayClass::toString(), StemClass::unknownRexx(), StringHashCollection::unknownRexx(), VariableReference::unknownRexx(), RexxObject::unsetMethod(), DirectoryClass::unsetMethodRexx(), StringHashCollection::validateIndex(), StringUtil::verify(), and StringUtil::wordPos().
stringArrayArgument()
void stringArrayArgument (ArrayClass * argArray, const char * position)
Validate that an array is non-space up to the last item and contains nothing but string values.
Parameters
argArray The argument array.
position The argument name for error reporting.
Definition at line 417 of file StringClassUtil.cpp.
References counter(), Error_Incorrect_method_nostring_inarray, ArrayClass::get(), ArrayClass::lastIndex(), RexxString::makeString(), OREF_NULL, ArrayClass::put(), reportException(), and TheNilObject.
Referenced by BaseExecutable::processExecutableSource().
Variable Documentation
ARG_EIGHT
const int ARG_EIGHT = 8
Definition at line 63 of file MethodArguments.hpp.
ARG_FIVE
const int ARG_FIVE = 5
Definition at line 60 of file MethodArguments.hpp.
Referenced by RexxString::translate().
ARG_FOUR
const int ARG_FOUR = 4
Definition at line 59 of file MethodArguments.hpp.
Referenced by MutableBuffer::caselessMatch(), RexxString::caselessMatch(), NumberString::formatRexx(), MutableBuffer::insert(), RexxString::insert(), MutableBuffer::match(), RexxString::match(), MutableBuffer::overlay(), RexxString::overlay(), RexxString::replaceAt(), RexxString::translate(), MutableBuffer::translate(), and StringUtil::verify().
ARG_NINE
const int ARG_NINE = 9
Definition at line 64 of file MethodArguments.hpp.
ARG_ONE
const int ARG_ONE = 1
Definition at line 56 of file MethodArguments.hpp.
Referenced by RexxString::abbrev(), RelationClass::allAt(), RelationClass::allIndexRexx(), RexxInteger::andOp(), RexxString::andOp(), ArrayClass::appendRexx(), MutableBuffer::appendRexx(), ListClass::appendRexx(), RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), StemClass::bracketEqual(), RoutineClass::callWithRexx(), RexxString::caselessAbbrev(), RexxString::caselessChangeStr(), MutableBuffer::caselessChangeStr(), RexxString::caselessCompare(), RexxString::caselessCompareToRexx(), RexxString::caselessContains(), MutableBuffer::caselessContains(), RexxString::caselessCountStrRexx(), MutableBuffer::caselessCountStrRexx(), MutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), MutableBuffer::caselessPos(), RexxString::caselessPosRexx(), StringUtil::caselessWordPos(), RexxString::center(), RexxString::changeStr(), MutableBuffer::changeStr(), RexxString::comp(), NumberString::comp(), RexxInteger::comp(), RexxString::compare(), RexxString::compareTo(), RexxString::compareToRexx(), RexxString::concatBlank(), RexxString::concatRexx(), StringUtil::containsRexx(), RexxString::copies(), RexxString::countStrRexx(), MutableBuffer::countStrRexx(), NumberString::d2xD2c(), RexxString::dataType(), RexxObject::decodeMessageName(), RexxClass::defineClassMethod(), ArrayClass::deleteRexx(), QueueClass::deleteRexx(), RexxString::delstr(), RexxString::delWord(), MutableBuffer::delWord(), ArrayClass::dimensionRexx(), RexxClass::equal(), RexxObject::equal(), PointerClass::equal(), ArrayClass::fillRexx(), NumberString::formatRexx(), RexxBehaviour::getMethodObject(), ArrayClass::getRexx(), PackageClass::getSourceLineRexx(), ArrayClass::hasIndexRexx(), ListClass::hasIndexRexx(), ArrayClass::hasItemRexx(), HashCollection::hasItemRexx(), ListClass::hasItemRexx(), BagClass::hasItemRexx(), RelationClass::hasItemRexx(), RexxObject::hasMethodRexx(), ArrayClass::indexRexx(), ListClass::indexRexx(), HashCollection::indexRexx(), SupplierClass::initRexx(), HashCollection::initRexx(), ListClass::initRexx(), QueueClass::initRexx(), MutableBuffer::insert(), RexxString::insert(), RexxObject::instanceMethod(), StringUtil::lastPosRexx(), RexxString::left(), MutableBuffer::lower(), RexxString::lowerRexx(), StringUtil::makearray(), MutableBuffer::match(), RexxString::match(), MutableBuffer::matchChar(), RexxString::matchChar(), NumberString::modulo(), MutableBuffer::mydelete(), ArrayClass::newRexx(), MutableBuffer::newRexx(), RexxString::newRexx(), WeakReference::newRexx(), ArrayClass::nextRexx(), ListClass::nextRexx(), RexxClass::notEqual(), RexxObject::notEqual(), PointerClass::notEqual(), RexxObject::objectNameEquals(), NumberString::operatorArgument(), RexxInteger::orOp(), RexxString::orOp(), MutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), NumberString::power(), ArrayClass::previousRexx(), ListClass::previousRexx(), RexxString::primitiveCaselessIsEqual(), RexxString::primitiveIsEqual(), QueueClass::pushRexx(), ArrayClass::putRexx(), QueueClass::putRexx(), QueueClass::queueRexx(), RelationClass::removeAll(), StemClass::removeItemRexx(), ArrayClass::removeItemRexx(), ListClass::removeItemRexx(), HashCollection::removeItemRexx(), BagClass::removeItemRexx(), RelationClass::removeItemRexx(), ArrayClass::removeRexx(), ListClass::removeRexx(), RexxString::replaceAt(), StemClass::request(), RexxObject::requestRexx(), RexxString::right(), AttributeSetterCode::run(), ArrayClass::sectionRexx(), ListClass::sectionRexx(), MutableBuffer::setBufferSize(), MutableBuffer::setTextRexx(), RexxString::space(), MutableBuffer::space(), ArrayClass::stableSortWithRexx(), StemClass::StemClass(), RexxInteger::strictComp(), RexxString::strictComp(), RexxObject::strictEqual(), RexxInteger::strictEquality(), RexxObject::strictNotEqual(), RexxString::strip(), StringUtil::subchar(), StringUtil::substr(), StringUtil::subWord(), StringUtil::subWords(), ArrayClass::toString(), RexxString::translate(), MutableBuffer::translate(), NumberString::trunc(), StemClass::unknownRexx(), StringHashCollection::unknownRexx(), VariableReference::unknownRexx(), MutableBuffer::upper(), RexxString::upperRexx(), StringUtil::verify(), StringUtil::word(), StringUtil::wordIndex(), StringUtil::wordLength(), StringUtil::wordPos(), RexxString::x2dC2d(), RexxInteger::xorOp(), and RexxString::xorOp().
ARG_SEVEN
const int ARG_SEVEN = 7
Definition at line 62 of file MethodArguments.hpp.
ARG_SIX
const int ARG_SIX = 6
Definition at line 61 of file MethodArguments.hpp.
ARG_TEN
const int ARG_TEN = 10
Definition at line 65 of file MethodArguments.hpp.
ARG_THREE
const int ARG_THREE = 3
Definition at line 58 of file MethodArguments.hpp.
Referenced by RexxString::caselessChangeStr(), MutableBuffer::caselessChangeStr(), RexxString::caselessCompareToRexx(), RexxString::caselessContains(), MutableBuffer::caselessContains(), MutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessPos(), RexxString::caselessPosRexx(), RexxString::changeStr(), MutableBuffer::changeStr(), RexxString::compareToRexx(), StringUtil::containsRexx(), NumberString::formatRexx(), MutableBuffer::insert(), RexxString::insert(), StringUtil::lastPosRexx(), MutableBuffer::match(), RexxString::match(), MutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), RexxString::replaceAt(), StringUtil::substr(), RexxString::translate(), MutableBuffer::translate(), and StringUtil::verify().
ARG_TWO
const int ARG_TWO = 2
Definition at line 57 of file MethodArguments.hpp.
Referenced by RexxString::abbrev(), RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), BUILTIN(), RexxString::caselessAbbrev(), RexxString::caselessChangeStr(), MutableBuffer::caselessChangeStr(), RexxString::caselessCompare(), RexxString::caselessCompareToRexx(), RexxString::caselessContains(), MutableBuffer::caselessContains(), MutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), MutableBuffer::caselessPos(), RexxString::caselessPosRexx(), StringUtil::caselessWordPos(), RexxString::center(), RexxString::changeStr(), MutableBuffer::changeStr(), RexxString::compare(), RexxString::compareToRexx(), StringUtil::containsRexx(), RexxClass::defineClassMethod(), RexxString::delstr(), RexxString::delWord(), MutableBuffer::delWord(), NumberString::formatRexx(), ListClass::getRexx(), SupplierClass::initRexx(), MutableBuffer::insert(), RexxString::insert(), ArrayClass::insertRexx(), ListClass::insertRexx(), StringUtil::lastPosRexx(), RexxString::left(), MutableBuffer::lower(), RexxString::lowerRexx(), MutableBuffer::match(), RexxString::match(), MutableBuffer::matchChar(), RexxString::matchChar(), MutableBuffer::mydelete(), MutableBuffer::newRexx(), MutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), ArrayClass::putRexx(), ListClass::putRexx(), QueueClass::putRexx(), RexxString::replaceAt(), RexxString::right(), ArrayClass::sectionRexx(), ListClass::sectionRexx(), RexxString::space(), MutableBuffer::space(), RexxObject::startWith(), RexxString::strip(), StringUtil::substr(), StringUtil::subWord(), StringUtil::subWords(), ArrayClass::toString(), RexxString::translate(), MutableBuffer::translate(), StemClass::unknownRexx(), StringHashCollection::unknownRexx(), VariableReference::unknownRexx(), MutableBuffer::upper(), RexxString::upperRexx(), StringUtil::verify(), and StringUtil::wordPos().