ooRexx: Numerics.hpp File Reference
Numerics.hpp File Reference
#include <algorithm>
#include "RexxCore.h"
Classes
class NumericSettings
class Numerics
Functions
wholenumber_t number_digits ()
wholenumber_t number_fuzz ()
bool number_form ()
wholenumber_t number_fuzzydigits ()
Function Documentation
number_digits()
wholenumber_t number_digits () inline
Definition at line 202 of file Numerics.hpp.
References Numerics::digits().
Referenced by RexxInteger::abs(), RexxInteger::ceiling(), NumberString::ceiling(), NumberString::comp(), RexxInteger::comp(), NumberString::copyForCurrentSettings(), NumberString::copyIfNecessary(), RexxInteger::d2c(), RexxInteger::d2x(), NumberString::d2xD2c(), RexxInteger::divide(), NumberString::Division(), RexxInstructionNumeric::execute(), RexxInstructionTrace::execute(), RexxInteger::floor(), NumberString::floor(), NumberString::formatRexx(), RexxInteger::integerDivide(), ParseTrigger::integerTrigger(), RexxInteger::Max(), NumberString::maxMin(), RexxInteger::Min(), RexxInteger::minus(), NumberString::minus(), RexxInteger::modulo(), NumberString::Multiply(), RexxInteger::multiply(), NumberString::newInstanceFromDouble(), NumberString::newInstanceFromFloat(), number_fuzzydigits(), NumberString::NumberString(), RexxInteger::plus(), NumberString::plus(), RexxInteger::power(), NumberString::power(), RexxInteger::remainder(), RexxInteger::round(), NumberString::round(), ControlledLoop::setup(), ForLoop::setup(), NumberString::setupNumber(), LanguageParser::traceNew(), RexxInteger::trunc(), NumberString::trunc(), and RexxString::x2dC2d().
number_form()
bool number_form () inline
Definition at line 204 of file Numerics.hpp.
References Numerics::form().
Referenced by NumberString::adjustPrecision(), NumberString::copyForCurrentSettings(), NumberString::copyIfNecessary(), NumberString::formatRexx(), NumberString::NumberString(), NumberString::plus(), NumberString::prepareNumber(), NumberString::prepareOperatorNumber(), and NumberString::setupNumber().
number_fuzz()
wholenumber_t number_fuzz () inline
Definition at line 203 of file Numerics.hpp.
References Numerics::fuzz().
Referenced by RexxString::comp(), RexxInteger::comp(), NumberString::equal(), NumberString::isGreaterOrEqual(), NumberString::isGreaterThan(), NumberString::isLessOrEqual(), NumberString::isLessThan(), NumberString::maxMin(), NumberString::notEqual(), and number_fuzzydigits().
number_fuzzydigits()
wholenumber_t number_fuzzydigits () inline
Definition at line 205 of file Numerics.hpp.
References number_digits(), and number_fuzz().