ooRexx: QueuesAPI.cpp File Reference
QueuesAPI.cpp File Reference
#include "rexx.h"
#include "LocalAPIManager.hpp"
#include "LocalQueueManager.hpp"
#include "LocalAPIContext.hpp"
#include "RexxAPI.h"
#include "RexxInternalApis.h"
Macros
#define INTERNALNAME_MINIMUM ((sizeof(void *) * 4) + 3)
Functions
RexxReturnCode RexxEntry RexxCreateQueue (char *name, size_t size, const char *userRequested, size_t *pdup)
RexxReturnCode RexxEntry RexxOpenQueue (const char *name, size_t *pdup)
RexxReturnCode RexxEntry RexxQueueExists (const char *name)
RexxReturnCode RexxEntry RexxDeleteQueue (const char *name)
RexxReturnCode RexxEntry RexxClearQueue (const char *name)
RexxReturnCode RexxEntry RexxQueryQueue (const char *name, size_t *count)
RexxReturnCode RexxEntry RexxAddQueue (const char *name, PCONSTRXSTRING data, size_t flag)
RexxReturnCode RexxEntry RexxPullFromQueue (const char *name, RXSTRING *data_buf, RexxQueueTime *time, size_t waitflag)
RexxReturnCode RexxEntry RexxDeleteSessionQueue ()
RexxReturnCode RexxEntry RexxCreateSessionQueue ()
Macro Definition Documentation
INTERNALNAME_MINIMUM
#define INTERNALNAME_MINIMUM ((sizeof(void *) * 4) + 3)
Definition at line 47 of file QueuesAPI.cpp.
Function Documentation
RexxAddQueue()
RexxReturnCode RexxEntry RexxAddQueue (const char * name, PCONSTRXSTRING data, size_t flag)
Definition at line 269 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, QueueManager, RXQUEUE_FIFO, RXQUEUE_LIFO, and RXQUEUE_PRIORITY.
RexxClearQueue()
RexxReturnCode RexxEntry RexxClearQueue (const char * name)
Definition at line 200 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, and QueueManager.
RexxCreateQueue()
RexxReturnCode RexxEntry RexxCreateQueue (char * name, size_t size, const char * userRequested, size_t * pdup)
Definition at line 98 of file QueuesAPI.cpp.
References BAD_STORAGE, ENTER_REXX_API, EXIT_REXX_API, and QueueManager.
RexxCreateSessionQueue()
RexxReturnCode RexxEntry RexxCreateSessionQueue ()
Initialize the API subsystem at process startup.
Returns
Always returns 0;
Definition at line 366 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, and QueueManager.
Referenced by Interpreter::startInterpreter().
RexxDeleteQueue()
RexxReturnCode RexxEntry RexxDeleteQueue (const char * name)
Definition at line 176 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, and QueueManager.
RexxDeleteSessionQueue()
RexxReturnCode RexxEntry RexxDeleteSessionQueue ()
Definition at line 353 of file QueuesAPI.cpp.
References RXQUEUE_OK, and LocalAPIManager::shutdownInstance().
Referenced by Interpreter::terminateInterpreter().
RexxOpenQueue()
RexxReturnCode RexxEntry RexxOpenQueue (const char * name, size_t * pdup)
Get access to a named queue, creating it if necessary.
Parameters
name The name of the desired queue.
pdup A flag indicating whether the queue already existed.
Returns
0 if the queue was accessed ok, otherwise the error code for any errors.
Definition at line 131 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, and QueueManager.
RexxPullFromQueue()
RexxReturnCode RexxEntry RexxPullFromQueue (const char * name, RXSTRING * data_buf, RexxQueueTime * time, size_t waitflag)
Definition at line 322 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, QueueManager, RXQUEUE_BADWAITFLAG, RXQUEUE_NOWAIT, and RXQUEUE_WAIT.
RexxQueryQueue()
RexxReturnCode RexxEntry RexxQueryQueue (const char * name, size_t * count)
Definition at line 232 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, and QueueManager.
RexxQueueExists()
RexxReturnCode RexxEntry RexxQueueExists (const char * name)
Check to see if a given named queue exists
Parameters
name The name of the desired queue.
Returns
0 if the queue was accessed ok, otherwise the error code for any errors.
Definition at line 149 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, and QueueManager.