ooRexx: RexxQueueMethods.cpp File Reference
RexxQueueMethods.cpp File Reference
#include "RexxCore.h"
#include "StringClass.hpp"
Functions
bool getQueueName (RexxMethodContext *context, CSTRING &name)
RexxMethod0 (size_t, rexx_query_queue)
RexxMethod0 (RexxObjectPtr, rexx_pull_queue)
RexxMethod0 (RexxObjectPtr, rexx_linein_queue)
wholenumber_t rexx_add_queue (RexxMethodContext *context, RexxStringObject queue_line, int order)
RexxMethod1 (wholenumber_t, rexx_push_queue, OPTIONAL_RexxStringObject, queue_line)
RexxMethod1 (wholenumber_t, rexx_queue_queue, OPTIONAL_RexxStringObject, queue_line)
RexxMethod1 (RexxStringObject, rexx_create_queue, OPTIONAL_CSTRING, queue_name)
RexxMethod1 (wholenumber_t, rexx_open_queue, CSTRING, queue_name)
RexxMethod1 (logical_t, rexx_queue_exists, CSTRING, queue_name)
RexxMethod1 (wholenumber_t, rexx_delete_queue, CSTRING, queue_name)
RexxMethod0 (wholenumber_t, rexx_clear_queue)
Function Documentation
getQueueName()
bool getQueueName (RexxMethodContext * context, CSTRING & name)
Retrieve the name of the queue. Raises an exception if the variable is not set.
Parameters
context The current message context.
Returns
a success indicator and the CSTRING version of the queue name.
Definition at line 54 of file RexxQueueMethods.cpp.
References Rexx_Error_Execution_noinit.
Referenced by rexx_add_queue(), and RexxMethod0().
rexx_add_queue()
wholenumber_t rexx_add_queue (RexxMethodContext * context, RexxStringObject queue_line, int order)
Definition at line 164 of file RexxQueueMethods.cpp.
References getQueueName(), MAKERXSTRING, NULLOBJECT, Rexx_Error_System_service_service, RexxAddQueue(), RXAPI_MEMFAIL, RXAPI_NORXAPI, RXQUEUE_ACCESS, RXQUEUE_BADQNAME, RXQUEUE_BADWAITFLAG, RXQUEUE_EMPTY, RXQUEUE_NOTREG, and RXQUEUE_PRIORITY.
Referenced by RexxMethod1().
RexxMethod0() [1/4]
RexxMethod0 (RexxObjectPtr , rexx_linein_queue)
Definition at line 128 of file RexxQueueMethods.cpp.
References getQueueName(), OREF_NULL, RexxFreeMemory(), RexxPullFromQueue(), RXQUEUE_WAIT, _RXSTRING::strlength, and _RXSTRING::strptr.
RexxMethod0() [2/4]
RexxMethod0 (RexxObjectPtr , rexx_pull_queue)
Definition at line 95 of file RexxQueueMethods.cpp.
References getQueueName(), OREF_NULL, RexxFreeMemory(), RexxPullFromQueue(), RXQUEUE_NOWAIT, _RXSTRING::strlength, and _RXSTRING::strptr.
RexxMethod0() [3/4]
RexxMethod0 (size_t , rexx_query_queue)
Definition at line 75 of file RexxQueueMethods.cpp.
References getQueueName(), and RexxQueryQueue().
RexxMethod0() [4/4]
RexxMethod0 (wholenumber_t , rexx_clear_queue)
Definition at line 291 of file RexxQueueMethods.cpp.
References RexxClearQueue().
RexxMethod1() [1/6]
RexxMethod1 (logical_t , rexx_queue_exists , CSTRING , queue_name)
Definition at line 272 of file RexxQueueMethods.cpp.
References RexxQueueExists().
RexxMethod1() [2/6]
RexxMethod1 (RexxStringObject , rexx_create_queue , OPTIONAL_CSTRING , queue_name)
Definition at line 242 of file RexxQueueMethods.cpp.
References MAX_QUEUE_NAME_LENGTH, and RexxCreateQueue().
RexxMethod1() [3/6]
RexxMethod1 (wholenumber_t , rexx_delete_queue , CSTRING , queue_name)
Definition at line 281 of file RexxQueueMethods.cpp.
References RexxDeleteQueue().
RexxMethod1() [4/6]
RexxMethod1 (wholenumber_t , rexx_open_queue , CSTRING , queue_name)
Definition at line 262 of file RexxQueueMethods.cpp.
References RexxOpenQueue().
RexxMethod1() [5/6]
RexxMethod1 (wholenumber_t , rexx_push_queue , OPTIONAL_RexxStringObject , queue_line)
Definition at line 222 of file RexxQueueMethods.cpp.
References rexx_add_queue(), and RXQUEUE_LIFO.
RexxMethod1() [6/6]
RexxMethod1 (wholenumber_t , rexx_queue_queue , OPTIONAL_RexxStringObject , queue_line)
Definition at line 232 of file RexxQueueMethods.cpp.
References rexx_add_queue(), and RXQUEUE_FIFO.