ooRexx: RexxBehaviour.hpp File Reference
RexxBehaviour.hpp File Reference
#include "FlagSet.hpp"
#include "PrimitiveBehaviourNames.h"
Classes
class RexxBehaviour
Macros
#define isOfClass(t, r) (r)->isObjectType(The##t##Behaviour)
#define isOfClassType(t, r) (r)->isObjectType(T_##t)
Functions
bool isString (RexxInternalObject *o)
bool isInteger (RexxInternalObject *o)
bool isNumberString (RexxInternalObject *o)
bool isArray (RexxInternalObject *o)
bool isStem (RexxInternalObject *o)
bool isMethod (RexxInternalObject *o)
bool isVariableReference (RexxInternalObject *o)
Macro Definition Documentation
isOfClass
#define isOfClass (t, r) (r)->isObjectType(The##t##Behaviour)
Definition at line 186 of file RexxBehaviour.hpp.
isOfClassType
#define isOfClassType (t, r) (r)->isObjectType(T_##t)
Definition at line 187 of file RexxBehaviour.hpp.
Function Documentation
isArray()
bool isArray (RexxInternalObject * o) inline
Definition at line 192 of file RexxBehaviour.hpp.
References isOfClass.
Referenced by ArrayClass::allocateArrayOfClass(), CommandIOConfiguration::createInputSource(), IsArray(), ArrayClass::newRexx(), RexxInternalObject::requestArray(), OverLoop::setup(), and ArrayClass::validateIndex().
isInteger()
bool isInteger (RexxInternalObject * o) inline
Definition at line 190 of file RexxBehaviour.hpp.
References isOfClass.
Referenced by CompoundVariableTail::buildTail(), BUILTIN(), RexxInteger::comp(), RexxInteger::d2c(), RexxInteger::d2x(), RexxInteger::divide(), Numerics::int64Object(), RexxInteger::integerDivide(), RexxInteger::isEqual(), RexxInteger::Max(), RexxInteger::Min(), RexxInteger::minus(), RexxInteger::modulo(), RexxInteger::multiply(), Numerics::objectToInt64(), Numerics::objectToSignedInteger(), Numerics::objectToStringSize(), Numerics::objectToUnsignedInt64(), Numerics::objectToUnsignedInteger(), Numerics::objectToWholeNumber(), ExpressionStack::optionalIntegerArg(), RexxInteger::plus(), RexxInteger::power(), RexxInteger::remainder(), ExpressionStack::requiredIntegerArg(), ForLoop::setup(), RexxInteger::strictEquality(), and RexxInteger::trunc().
isMethod()
bool isMethod (RexxInternalObject * o) inline
Definition at line 194 of file RexxBehaviour.hpp.
References isOfClass.
Referenced by MethodDictionary::addMethods(), MethodDictionary::getMethods(), MethodClass::newMethodObject(), and MethodDictionary::replaceMethods().
isNumberString()
bool isNumberString (RexxInternalObject * o) inline
Definition at line 191 of file RexxBehaviour.hpp.
References isOfClass.
Referenced by BUILTIN().
isStem()
bool isStem (RexxInternalObject * o) inline
Definition at line 193 of file RexxBehaviour.hpp.
References isOfClass.
Referenced by StemClass::bracketEqual(), CommandIOConfiguration::createInputSource(), CommandIOConfiguration::createOutputTarget(), IsStem(), NativeActivation::objectToValue(), NativeActivation::processArguments(), StemClass::request(), and NativeActivation::resolveStemVariable().
isString()
bool isString (RexxInternalObject * o) inline
Definition at line 189 of file RexxBehaviour.hpp.
References isOfClass.
Referenced by CompoundVariableTail::buildTail(), BUILTIN(), CommandIOConfiguration::createInputSource(), RexxObject::decodeMessageName(), NativeActivation::dropContextVariable(), NativeActivation::getContextVariable(), ArrayProgramSource::getLine(), NativeActivation::getObjectVariableRetriever(), IsString(), ExpressionStack::optionalStringArg(), BaseExecutable::processExecutableSource(), ExpressionStack::requiredStringArg(), NativeActivation::setContextVariable(), and NativeActivation::variablePoolGetVariable().
isVariableReference()
bool isVariableReference (RexxInternalObject * o) inline
Definition at line 195 of file RexxBehaviour.hpp.
References isOfClass.
Referenced by UseVariable::handleReferenceArgument().