ooRexx: RexxUtilCommon.cpp File Reference
RexxUtilCommon.cpp File Reference
#include <time.h>
#include <algorithm>
#include <math.h>
#include <ctype.h>
#include <cmath>
#include <cfloat>
#include "oorexxapi.h"
#include "PackageManager.hpp"
#include "RexxUtilCommon.hpp"
#include "RexxInternalApis.h"
#include "ExternalFileBuffer.hpp"
#include "SysFile.hpp"
#include "SysFileSystem.hpp"
#include "SystemInterpreter.hpp"
#include "Utilities.hpp"
#include "Numerics.hpp"
#include "SysRexxUtilFunctions.h"
Classes
class LineReader
Macros
#define INTERNAL_ROUTINE(name, entry) REXX_TYPED_ROUTINE_PROTOTYPE(entry)
#define INTERNAL_ROUTINE(name, entry) REXX_TYPED_ROUTINE(name, entry),
Functions
void getUniqueFileName (const char *fileTemplate, char filler, FileNameBuffer &file)
RexxRoutine5 (uint32_t, SysFileTree, CSTRING, fileSpec, RexxObjectPtr, files, OPTIONAL_CSTRING, opts, OPTIONAL_CSTRING, targetAttr, OPTIONAL_CSTRING, newAttr)
const char * mystrstr (const char *haystack, const char *needle, size_t hlen, size_t nlen, bool sensitive)
RexxRoutine0 (int, SysDropFuncs)
RexxRoutine0 (int, SysLoadFuncs)
RexxRoutine3 (int, SysAddRexxMacro, CSTRING, name, CSTRING, file, OPTIONAL_CSTRING, option)
RexxRoutine2 (int, SysReorderRexxMacro, CSTRING, name, CSTRING, option)
RexxRoutine1 (int, SysDropRexxMacro, CSTRING, name)
RexxRoutine1 (CSTRING, SysQueryRexxMacro, CSTRING, name)
RexxRoutine0 (int, SysClearRexxMacroSpace)
RexxRoutine1 (int, SysSaveRexxMacroSpace, CSTRING, file)
RexxRoutine1 (int, SysLoadRexxMacroSpace, CSTRING, file)
RexxRoutine7 (int, SysStemSort, RexxObjectPtr, stemArgument, OPTIONAL_CSTRING, order, OPTIONAL_CSTRING, type, OPTIONAL_positive_wholenumber_t, first, OPTIONAL_positive_wholenumber_t, last, OPTIONAL_positive_wholenumber_t, firstCol, OPTIONAL_positive_wholenumber_t, lastCol)
RexxRoutine3 (int, SysStemDelete, RexxStemObject, toStem, positive_wholenumber_t, start, OPTIONAL_positive_wholenumber_t, count)
RexxRoutine3 (int, SysStemInsert, RexxStemObject, toStem, positive_wholenumber_t, position, RexxObjectPtr, newValue)
RexxRoutine6 (int, SysStemCopy, RexxStemObject, fromStem, RexxStemObject, toStem, OPTIONAL_positive_wholenumber_t, from, OPTIONAL_positive_wholenumber_t, to, OPTIONAL_nonnegative_wholenumber_t, count, OPTIONAL_CSTRING, option)
RexxRoutine0 (RexxStringObject, SysUtilVersion)
void writeVariable (SysFile &file, RexxCallContext *context, const char *name, RexxObjectPtr value)
void writeVariable (SysFile &file, RexxCallContext *context, const char *stem, RexxStringObject tail, RexxObjectPtr value)
RexxRoutine1 (int, SysDumpVariables, OPTIONAL_CSTRING, fileName)
RexxRoutine1 (logical_t, SysFileExists, CSTRING, name)
RexxRoutine1 (logical_t, SysIsFileLink, CSTRING, file)
RexxRoutine1 (logical_t, SysIsFile, CSTRING, file)
RexxRoutine1 (logical_t, SysIsFileDirectory, CSTRING, file)
RexxRoutine1 (int, SysRmDir, CSTRING, path)
RexxRoutine1 (int, SysFileDelete, CSTRING, path)
RexxRoutine4 (CSTRING, SysFileSearch, RexxStringObject, needle, CSTRING, file, RexxObjectPtr, stem, OPTIONAL_CSTRING, opts)
RexxRoutine3 (RexxStringObject, SysSearchPath, CSTRING, path, CSTRING, file, OPTIONAL_CSTRING, options)
RexxRoutine1 (int, SysSleep, RexxStringObject, delay)
RexxRoutine2 (int, SysFileCopy, CSTRING, from, CSTRING, to)
RexxRoutine2 (int, SysFileMove, CSTRING, from, CSTRING, to)
RexxRoutine2 (RexxStringObject, SysTempFileName, CSTRING, fileTemplate, OPTIONAL_CSTRING, fillerOpt)
RexxStringObject formatMessage (RexxCallContext *context, const char *message, RexxArrayObject args, size_t firstSubstitution)
RexxRoutine2 (RexxStringObject, SysFormatMessage, CSTRING, message, RexxArrayObject, substitutions)
Variables
const int INVALID_FILE_NAME = 123
RexxRoutineEntry rexxutil_routines []
RexxPackageEntry rexxutil_package_entry
Macro Definition Documentation
INTERNAL_ROUTINE [1/2]
#define INTERNAL_ROUTINE (name, entry) REXX_TYPED_ROUTINE_PROTOTYPE(entry)
Definition at line 2154 of file RexxUtilCommon.cpp.
INTERNAL_ROUTINE [2/2]
#define INTERNAL_ROUTINE (name, entry) REXX_TYPED_ROUTINE(name, entry),
Definition at line 2154 of file RexxUtilCommon.cpp.
Function Documentation
formatMessage()
RexxStringObject formatMessage (RexxCallContext * context, const char * message, RexxArrayObject args, size_t firstSubstitution)
Format a message using passed in arguments.
Parameters
context The call context.
message The message test
args The array of arguments to the function.
firstSubstitution The first substitution argument in the array.
Returns
The formated test as a Rexx String object.
Definition at line 2014 of file RexxUtilCommon.cpp.
References NULLOBJECT, and Rexx_Error_Incorrect_call_external.
Referenced by RexxRoutine2(), RexxRoutine3(), and RexxRoutine4().
getUniqueFileName()
void getUniqueFileName (const char * fileTemplate, char filler, FileNameBuffer & file)
Generate a unique file name based off of a template.
Definition at line 167 of file RexxUtilCommon.cpp.
References SysFileSystem::exists(), SysFileSystem::qualifyStreamName(), and FileNameBuffer::truncate().
Referenced by RexxRoutine2().
mystrstr()
const char* mystrstr (const char * haystack, const char * needle, size_t hlen, size_t nlen, bool sensitive)
Determines if the string 'needle' is in the string 'haystack' by returning it's position or a NULL if not found. The length of haystack and needle are given by 'hlen' and 'nlen' respectively.
If 'sensitive' is true, then the search is case sensitive, else it is case insensitive.
Parameters
haystack The haystack to search in.
needle The needle to search for
hlen the length of the haystack string
nlen The lenght of the needle string
sensitive if true, a case sensitive search is performed. if false, the search is case insensitive.
Returns
A pointer to the first match position or NULL if the string is not found.
Definition at line 767 of file RexxUtilCommon.cpp.
References Utilities::memicmp(), and Utilities::toUpper().
Referenced by mystrstr(), and RexxRoutine4().
RexxRoutine0() [1/4]
RexxRoutine0 (int , SysClearRexxMacroSpace)
Definition at line 983 of file RexxUtilCommon.cpp.
References RexxClearMacroSpace().
RexxRoutine0() [2/4]
RexxRoutine0 (int , SysDropFuncs)
Definition at line 831 of file RexxUtilCommon.cpp.
RexxRoutine0() [3/4]
RexxRoutine0 (int , SysLoadFuncs)
Definition at line 847 of file RexxUtilCommon.cpp.
RexxRoutine0() [4/4]
RexxRoutine0 (RexxStringObject , SysUtilVersion)
Definition at line 1426 of file RexxUtilCommon.cpp.
RexxRoutine1() [1/12]
RexxRoutine1 (CSTRING , SysQueryRexxMacro , CSTRING , name)
Definition at line 954 of file RexxUtilCommon.cpp.
References RexxQueryMacro(), and RXMACRO_SEARCH_BEFORE.
RexxRoutine1() [2/12]
RexxRoutine1 (int , SysDropRexxMacro , CSTRING , name)
Definition at line 939 of file RexxUtilCommon.cpp.
References RexxDropMacro().
RexxRoutine1() [3/12]
RexxRoutine1 (int , SysDumpVariables , OPTIONAL_CSTRING , fileName)
Definition at line 1516 of file RexxUtilCommon.cpp.
References SysFile::close(), SysFile::open(), RX_O_APPEND, RX_O_CREAT, RX_O_WRONLY, RX_S_IREAD, RX_S_IWRITE, RX_SH_DENYRW, SysFile::setStdOut(), and writeVariable().
RexxRoutine1() [4/12]
RexxRoutine1 (int , SysFileDelete , CSTRING , path)
Definition at line 1689 of file RexxUtilCommon.cpp.
References SysFileSystem::deleteFile().
RexxRoutine1() [5/12]
RexxRoutine1 (int , SysLoadRexxMacroSpace , CSTRING , file)
Definition at line 1013 of file RexxUtilCommon.cpp.
References RexxLoadMacroSpace().
RexxRoutine1() [6/12]
RexxRoutine1 (int , SysRmDir , CSTRING , path)
Definition at line 1672 of file RexxUtilCommon.cpp.
References SysFileSystem::deleteDirectory().
RexxRoutine1() [7/12]
RexxRoutine1 (int , SysSaveRexxMacroSpace , CSTRING , file)
Definition at line 998 of file RexxUtilCommon.cpp.
References RexxSaveMacroSpace().
RexxRoutine1() [8/12]
RexxRoutine1 (int , SysSleep , RexxStringObject , delay)
Definition at line 1891 of file RexxUtilCommon.cpp.
References SysThread::longSleep(), Rexx_Error_Invalid_argument_number, and Rexx_Error_Invalid_argument_range.
RexxRoutine1() [9/12]
RexxRoutine1 (logical_t , SysFileExists , CSTRING , name)
Test if the file exists
Definition at line 1602 of file RexxUtilCommon.cpp.
References SysFileSystem::exists().
RexxRoutine1() [10/12]
RexxRoutine1 (logical_t , SysIsFile , CSTRING , file)
Definition at line 1637 of file RexxUtilCommon.cpp.
References SysFileSystem::isFile().
RexxRoutine1() [11/12]
RexxRoutine1 (logical_t , SysIsFileDirectory , CSTRING , file)
Definition at line 1654 of file RexxUtilCommon.cpp.
References SysFileSystem::isDirectory().
RexxRoutine1() [12/12]
RexxRoutine1 (logical_t , SysIsFileLink , CSTRING , file)
Definition at line 1620 of file RexxUtilCommon.cpp.
References SysFileSystem::isLink().
RexxRoutine2() [1/5]
RexxRoutine2 (int , SysFileCopy , CSTRING , from , CSTRING , to)
Definition at line 1935 of file RexxUtilCommon.cpp.
References SysFileSystem::copyFile().
RexxRoutine2() [2/5]
RexxRoutine2 (int , SysFileMove , CSTRING , from , CSTRING , to)
Definition at line 1954 of file RexxUtilCommon.cpp.
References SysFileSystem::moveFile().
RexxRoutine2() [3/5]
RexxRoutine2 (int , SysReorderRexxMacro , CSTRING , name , CSTRING , option)
Definition at line 906 of file RexxUtilCommon.cpp.
References invalidOptionException(), RexxReorderMacro(), RXMACRO_SEARCH_AFTER, and RXMACRO_SEARCH_BEFORE.
RexxRoutine2() [4/5]
RexxRoutine2 (RexxStringObject , SysFormatMessage , CSTRING , message , RexxArrayObject , substitutions)
Definition at line 2142 of file RexxUtilCommon.cpp.
References formatMessage().
RexxRoutine2() [5/5]
RexxRoutine2 (RexxStringObject , SysTempFileName , CSTRING , fileTemplate , OPTIONAL_CSTRING , fillerOpt)
Definition at line 1978 of file RexxUtilCommon.cpp.
References getUniqueFileName(), and Rexx_Error_Incorrect_call_pad.
RexxRoutine3() [1/4]
RexxRoutine3 (int , SysAddRexxMacro , CSTRING , name , CSTRING , file , OPTIONAL_CSTRING , option)
Definition at line 866 of file RexxUtilCommon.cpp.
References invalidOptionException(), RexxAddMacro(), RXMACRO_SEARCH_AFTER, and RXMACRO_SEARCH_BEFORE.
RexxRoutine3() [2/4]
RexxRoutine3 (int , SysStemDelete , RexxStemObject , toStem , positive_wholenumber_t , start , OPTIONAL_positive_wholenumber_t , count)
Definition at line 1193 of file RexxUtilCommon.cpp.
References argumentOmitted, NULLOBJECT, Rexx_Error_Incorrect_call_stem_range, Rexx_Error_Incorrect_call_stem_sparse_array, and unsetStemException().
RexxRoutine3() [3/4]
RexxRoutine3 (int , SysStemInsert , RexxStemObject , toStem , positive_wholenumber_t , position , RexxObjectPtr , newValue)
Definition at line 1252 of file RexxUtilCommon.cpp.
References NULLOBJECT, Rexx_Error_Incorrect_call_stem_range, Rexx_Error_Incorrect_call_stem_sparse_array, and unsetStemException().
RexxRoutine3() [4/4]
RexxRoutine3 (RexxStringObject , SysSearchPath , CSTRING , path , CSTRING , file , OPTIONAL_CSTRING , options)
Definition at line 1833 of file RexxUtilCommon.cpp.
References SysFileSystem::getCurrentDirectory(), SystemInterpreter::getEnvironmentVariable(), SysFileSystem::getPathSeparator(), invalidOptionException(), FileNameBuffer::length(), SysFileSystem::searchPath(), and Utilities::toUpper().
RexxRoutine4()
RexxRoutine4 (CSTRING , SysFileSearch , RexxStringObject , needle , CSTRING , file , RexxObjectPtr , stem , OPTIONAL_CSTRING , opts)
SysFileSearch searches a file for lines containing needle.
Parameters
needle The string to search for.
file The name of the file to search.
stem The name of the stem variable that will receive each file line containing needle.
opts A string of options. A combination of the following chars: 'C' - Case-sensitive search (non-default) 'I' - Case-insensitive search (default) 'N' - Precede each found string in result stem with its line number in file (non-default)
Returns
0 on success, non-zero on error. ERROR_FILEOPEN if file cannot be opened. ERROR_NOMEM if not enough memory.
Definition at line 1714 of file RexxUtilCommon.cpp.
References StemHandler::addValue(), LineReader::close(), ERROR_FILEOPEN, ERROR_NOMEM, LineReader::getLine(), line, mystrstr(), LineReader::open(), Rexx_Error_Incorrect_call_user_defined, and Utilities::toUpper().
RexxRoutine5()
RexxRoutine5 (uint32_t , SysFileTree , CSTRING , fileSpec , RexxObjectPtr , files , OPTIONAL_CSTRING , opts , OPTIONAL_CSTRING , targetAttr , OPTIONAL_CSTRING , newAttr)
SysFileTree() implementation. Searches for files in a directory tree matching the specified search pattern.
Parameters
fSpec [required] The search pattern, may contain glob characters and full or partial path informattion. E.g., *.bat, or ../../abc*.txt, or C:\temp. May not contain illegal file name characters which are: ", <, >, |, and : The semicolon is only legal if it is exactly the second character. Do not use a double quote in fSpec, it is not needed and is taken as a character in a file name, which is an illegal character.
files [required] A stem to contain the returned results. On return, files.0 contains the count N of found files and files.1 through files.N will contain the found files.
opts [optional] Any combination of the following letters that specify how the search takes place, or how the returned found file line is formatted. Case is not significant:
'B' - Search for files and directories. 'D' - Search for directories only. 'F' - Search for files only. 'O' - Only output file names. 'S' - Recursively scan subdirectories. 'T' - Combine time & date fields into one. 'L' - Long time format 'H' - Large file size format 'I' - Case Insensitive search.
The default is 'B' using normal time (neither 'T' nor 'L'.) The 'I'option is meaningless on Windows.
Parameters
targetAttr [optional] Target attribute mask. Only files with these attributes will be searched for. The default is to ignore the attributes of the files found, so all files found are returned.
newAttr [optional] New attribute mask. Each found file will have its attributes set (changed) to match this mask. The default is to not change any attributes.
Returns
0 on success, non-zero on error. For all errors, a condition is raised.
Definition at line 287 of file RexxUtilCommon.cpp.
References TreeFinder::findFiles(), INVALID_FILE_NAME, and TreeFinder::InvalidFileName.
RexxRoutine6()
RexxRoutine6 (int , SysStemCopy , RexxStemObject , fromStem , RexxStemObject , toStem , OPTIONAL_positive_wholenumber_t , from , OPTIONAL_positive_wholenumber_t , to , OPTIONAL_nonnegative_wholenumber_t , count , OPTIONAL_CSTRING , option)
Definition at line 1303 of file RexxUtilCommon.cpp.
References argumentExists, argumentOmitted, invalidOptionException(), NULLOBJECT, Rexx_Error_Incorrect_call_stem_range, Rexx_Error_Incorrect_call_stem_sparse_array, and unsetStemException().
RexxRoutine7()
RexxRoutine7 (int , SysStemSort , RexxObjectPtr , stemArgument , OPTIONAL_CSTRING , order , OPTIONAL_CSTRING , type , OPTIONAL_positive_wholenumber_t , first , OPTIONAL_positive_wholenumber_t , last , OPTIONAL_positive_wholenumber_t , firstCol , OPTIONAL_positive_wholenumber_t , lastCol)
Definition at line 1037 of file RexxUtilCommon.cpp.
References argumentOmitted, invalidOptionException(), Numerics::MAX_WHOLENUMBER, NULLOBJECT, relativeOptionException(), Rexx_Error_Incorrect_call_nostem, RexxStemSort(), SORT_ASCENDING, SORT_CASEIGNORE, SORT_CASESENSITIVE, SORT_DECENDING, and type.
writeVariable() [1/2]
void writeVariable (SysFile & file, RexxCallContext * context, const char * name, RexxObjectPtr value)
Write out the name/value pair for an individual variable to the output stream.
Parameters
file The output target
context The call context
name The name of the variable
value The object value
Returns
an error code if there is a failure.
Definition at line 1445 of file RexxUtilCommon.cpp.
References SysFile::write().
Referenced by RexxRoutine1().
writeVariable() [2/2]
void writeVariable (SysFile & file, RexxCallContext * context, const char * stem, RexxStringObject tail, RexxObjectPtr value)
Write out the compound name/value pair for an individual compound variable to the output stream.
Parameters
file The output target
name The name of the variable
value The object value
Returns
an error code if there is a failure.
Definition at line 1479 of file RexxUtilCommon.cpp.
References SysFile::write().
Variable Documentation
INVALID_FILE_NAME
const int INVALID_FILE_NAME = 123
Definition at line 62 of file RexxUtilCommon.cpp.
Referenced by RexxRoutine5().
rexxutil_package_entry
RexxPackageEntry rexxutil_package_entry
Initial value:
=
{
    STANDARD_PACKAGE_HEADER
    REXX_INTERPRETER_4_0_0,
    "REXXUTIL",
    "5.0.0",
    NULL,
    NULL,
    rexxutil_routines,
    NULL
}
Definition at line 2194 of file RexxUtilCommon.cpp.
rexxutil_routines
RexxRoutineEntry rexxutil_routines[]
Definition at line 2158 of file RexxUtilCommon.cpp.