ooRexx: RexxUtilCommon.hpp File Reference
RexxUtilCommon.hpp File Reference
#include "SysFileSystem.hpp"
#include "ExternalFileBuffer.hpp"
#include "FlagSet.hpp"
Classes
class StemHandler
class TreeFinder
class TreeFinder::AttributeMask
Macros
#define ERROR_NOMEM "2"
#define ERROR_FILEOPEN "3"
#define ERROR_RETSTR "ERROR:"
Functions
const char * mystrstr (const char *haystack, const char *needle, size_t hlen, size_t nlen, bool sensitive)
const char * mystrstr (const char *haystack, const char *needle, bool sensitive=true)
void outOfMemoryException (RexxCallContext *c)
RexxStringObject formatMessage (RexxCallContext *context, const char *message, RexxArrayObject args, size_t firstSubstitution)
void nullStringException (RexxCallContext *c, const char *fName, size_t pos)
void invalidOptionException (RexxCallContext *c, const char *fName, const char *aName, const char *options, const char *actual)
void maxArgException (RexxCallContext *c, const char *fname, size_t max)
void relativeOptionException (RexxCallContext *c, const char *arg1, size_t value1, const char *arg2, size_t value2)
void unsetStemException (RexxCallContext *c)
Macro Definition Documentation
ERROR_FILEOPEN
#define ERROR_FILEOPEN "3"
Definition at line 51 of file RexxUtilCommon.hpp.
ERROR_NOMEM
#define ERROR_NOMEM "2"
Definition at line 50 of file RexxUtilCommon.hpp.
ERROR_RETSTR
#define ERROR_RETSTR "ERROR:"
Definition at line 58 of file RexxUtilCommon.hpp.
Function Documentation
formatMessage()
RexxStringObject formatMessage (RexxCallContext * context, const char * message, RexxArrayObject args, size_t firstSubstitution)
Format a message using passed in arguments.
Parameters
context The call context.
message The message test
args The array of arguments to the function.
firstSubstitution The first substitution argument in the array.
Returns
The formated test as a Rexx String object.
Definition at line 2014 of file RexxUtilCommon.cpp.
References NULLOBJECT, and Rexx_Error_Incorrect_call_external.
Referenced by RexxRoutine2(), RexxRoutine3(), and RexxRoutine4().
invalidOptionException()
void invalidOptionException (RexxCallContext * c, const char * fName, const char * aName, const char * options, const char * actual) inline
Raise an error for an invalid option.
Parameters
c The call context
fName The function name
aName The argument name
options The allowed options
actual The actual invalid option.
Definition at line 104 of file RexxUtilCommon.hpp.
References Rexx_Error_Incorrect_call_bad_option.
Referenced by evaluateCodePage(), RexxRoutine1(), RexxRoutine2(), RexxRoutine3(), RexxRoutine4(), RexxRoutine5(), RexxRoutine6(), and RexxRoutine7().
maxArgException()
void maxArgException (RexxCallContext * c, const char * fname, size_t max) inline
Raise an error for too many arguments
Parameters
c The call context
fname The name of the function.
max The maximum number of arguments
Definition at line 123 of file RexxUtilCommon.hpp.
References Rexx_Error_Incorrect_call_maxarg.
Referenced by RexxRoutine4().
mystrstr() [1/2]
const char* mystrstr (const char * haystack, const char * needle, bool sensitive = true) inline
Definition at line 68 of file RexxUtilCommon.hpp.
References mystrstr().
mystrstr() [2/2]
const char* mystrstr (const char * haystack, const char * needle, size_t hlen, size_t nlen, bool sensitive)
Determines if the string 'needle' is in the string 'haystack' by returning it's position or a NULL if not found. The length of haystack and needle are given by 'hlen' and 'nlen' respectively.
If 'sensitive' is true, then the search is case sensitive, else it is case insensitive.
Parameters
haystack The haystack to search in.
needle The needle to search for
hlen the length of the haystack string
nlen The lenght of the needle string
sensitive if true, a case sensitive search is performed. if false, the search is case insensitive.
Returns
A pointer to the first match position or NULL if the string is not found.
Definition at line 767 of file RexxUtilCommon.cpp.
References Utilities::memicmp(), and Utilities::toUpper().
Referenced by mystrstr(), and RexxRoutine4().
nullStringException()
void nullStringException (RexxCallContext * c, const char * fName, size_t pos) inline
<routineName> argument <argPos> must not be a null string
SysFileTree argument 2 must not be a null string
Parameters
c Threade context we are operating in.
fName Routine name.
pos Argument position.
Definition at line 89 of file RexxUtilCommon.hpp.
References Rexx_Error_Incorrect_call_null.
Referenced by TreeFinder::getOptions(), and TreeFinder::validateFileSpec().
outOfMemoryException()
void outOfMemoryException (RexxCallContext * c) inline
Definition at line 73 of file RexxUtilCommon.hpp.
References Rexx_Error_System_service_user_defined.
Referenced by RexxRoutine1(), RexxRoutine3(), RexxRoutine4(), and RexxRoutine5().
relativeOptionException()
void relativeOptionException (RexxCallContext * c, const char * arg1, size_t value1, const char * arg2, size_t value2) inline
Raise an error for an error in relative values of two arguments.
Parameters
c The call context
arg1 The name of the first argument
value1 The value of the first argument
arg2 The name of the second argument
value2 The value of the second argument
Definition at line 139 of file RexxUtilCommon.hpp.
References Rexx_Error_Incorrect_call_relative.
Referenced by RexxRoutine7().
unsetStemException()
void unsetStemException (RexxCallContext * c) inline
Raise an error for an error in relative values of two arguments.
Parameters
c The call context
Definition at line 156 of file RexxUtilCommon.hpp.
References Rexx_Error_Incorrect_call_stem_size.
Referenced by RexxRoutine3(), and RexxRoutine6().