ooRexx: RexxInternalApis.h File Reference
RexxInternalApis.h File Reference
Macros
#define SORT_CASESENSITIVE 0
#define SORT_CASEIGNORE 1
#define SORT_ASCENDING 0
#define SORT_DECENDING 1
Functions
int REXXENTRY RexxResolveExit (const char *, REXXPFN *)
int REXXENTRY RexxResolveRoutine (const char *, REXXPFN *)
RexxReturnCode REXXENTRY RexxResolveMacroFunction (const char *, PRXSTRING)
void REXXENTRY RexxCreateInterpreterImage (const char *t)
RexxReturnCode REXXENTRY RexxLoadSubcom (const char *, const char *)
RexxReturnCode REXXENTRY RexxResolveSubcom (const char *name, REXXPFN *)
RexxReturnCode RexxEntry RexxCreateSessionQueue ()
RexxReturnCode RexxEntry RexxDeleteSessionQueue ()
RexxReturnCode REXXENTRY RexxStemSort (RexxStemObject stem, const char *tailExtension, int order, int type, wholenumber_t start, wholenumber_t end, wholenumber_t firstcol, wholenumber_t lastcol)
const char *REXXENTRY RexxGetErrorMessage (int number)
const char *REXXENTRY RexxGetErrorMessageByNumber (int number)
RexxReturnCode REXXENTRY RexxCompileProgram (const char *input, const char *output, PRXSYSEXIT, bool encode)
Macro Definition Documentation
SORT_ASCENDING
#define SORT_ASCENDING 0
Definition at line 50 of file RexxInternalApis.h.
SORT_CASEIGNORE
#define SORT_CASEIGNORE 1
Definition at line 48 of file RexxInternalApis.h.
SORT_CASESENSITIVE
#define SORT_CASESENSITIVE 0
Definition at line 47 of file RexxInternalApis.h.
SORT_DECENDING
#define SORT_DECENDING 1
Definition at line 51 of file RexxInternalApis.h.
Function Documentation
RexxCompileProgram()
RexxReturnCode REXXENTRY RexxCompileProgram (const char * inFile, const char * outFile, PRXSYSEXIT exits, bool encode)
Translate a program and store the translated results in an external file.
Parameters
inFile The input source file.
outFile The output source.
exits The exits to use during the translation process.
Returns
The error return code (if any).
Definition at line 185 of file InterpreterAPI.cpp.
References TranslateDispatcher::encode, TranslateDispatcher::instore, ActivityDispatcher::invoke(), TranslateDispatcher::outputName, TranslateDispatcher::programName, ActivityDispatcher::rc, and Interpreter::terminateInterpreter().
Referenced by main(), and RexxTranslateProgram().
RexxCreateInterpreterImage()
void REXXENTRY RexxCreateInterpreterImage (const char * target)
Create the Rexx saved image during build processing.
Returns
Nothing
Definition at line 90 of file InterpreterAPI.cpp.
References Interpreter::SAVE_IMAGE_MODE, and Interpreter::startInterpreter().
Referenced by main().
RexxCreateSessionQueue()
RexxReturnCode RexxEntry RexxCreateSessionQueue ()
Initialize the API subsystem at process startup.
Returns
Always returns 0;
Definition at line 366 of file QueuesAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, and QueueManager.
Referenced by Interpreter::startInterpreter().
RexxDeleteSessionQueue()
RexxReturnCode RexxEntry RexxDeleteSessionQueue ()
Definition at line 353 of file QueuesAPI.cpp.
References RXQUEUE_OK, and LocalAPIManager::shutdownInstance().
Referenced by Interpreter::terminateInterpreter().
RexxGetErrorMessage()
const char* REXXENTRY RexxGetErrorMessage (int code)
Retrieve an error message by symbolic error number mapping.
Parameters
code The fully qualified message code.
Returns
The character string message or NULL if not found.
Definition at line 725 of file Interpreter.cpp.
References msgEntry::code.
Referenced by displayError(), Interpreter::getMessageText(), options_error(), parmerr(), and RexxGetErrorMessageByNumber().
RexxGetErrorMessageByNumber()
const char* REXXENTRY RexxGetErrorMessageByNumber (int msgid)
Retrieve an error message by assigned external message number. This is mapped to the appropriate Rexx error code.
Parameters
msgid The message number
Returns
The character string message or NULL if the message is not found.
Definition at line 750 of file Interpreter.cpp.
References msgMap::msgid, and RexxGetErrorMessage().
Referenced by getErrorMessage().
RexxLoadSubcom()
RexxReturnCode REXXENTRY RexxLoadSubcom (const char * name, const char * lib)
Definition at line 244 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, RegistrationManager, and SubcomAPI.
Referenced by main().
RexxResolveExit()
int REXXENTRY RexxResolveExit (const char * name, REXXPFN * entryPoint)
Definition at line 405 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, ExitAPI, and RegistrationManager.
Referenced by ExitHandler::resolve().
RexxResolveMacroFunction()
RexxReturnCode REXXENTRY RexxResolveMacroFunction (const char * , PRXSTRING)
Referenced by RexxActivation::getMacroCode(), and LanguageParser::restoreFromMacroSpace().
RexxResolveRoutine()
int REXXENTRY RexxResolveRoutine (const char * name, REXXPFN * entryPoint)
Definition at line 526 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, FunctionAPI, and RegistrationManager.
Referenced by PackageManager::createRegisteredRoutine(), and PackageManager::resolveRegisteredRoutineEntry().
RexxResolveSubcom()
RexxReturnCode REXXENTRY RexxResolveSubcom (const char * name, REXXPFN * entryPoint)
Definition at line 215 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, RegistrationManager, and SubcomAPI.
Referenced by CommandHandler::resolve().
RexxStemSort()
RexxReturnCode REXXENTRY RexxStemSort (RexxStemObject stem, const char * tailExtension, int order, int type, wholenumber_t start, wholenumber_t end, wholenumber_t firstcol, wholenumber_t lastcol)
Process a stemsort call for the rexxutil SysStemSort function.
Parameters
stemname The name of the stem.
order The sort order.
type The type of sort (case sensitivity).
start The starting element number.
end The end element number.
firstcol The first sort column.
lastcol The last sort column.
Returns
The sort return code result.
Definition at line 428 of file InterpreterAPI.cpp.
References NativeContextBlock::self, NativeActivation::stemSort(), and type.
Referenced by RexxRoutine7().