ooRexx: StringClassUtil.cpp File Reference
StringClassUtil.cpp File Reference
#include "RexxCore.h"
#include "StringClass.hpp"
#include "ActivityManager.hpp"
#include "MethodArguments.hpp"
#include <ctype.h>
Functions
size_t lengthArgument (RexxObject *argument, size_t position)
size_t lengthArgument (RexxObject *argument, const char *position)
wholenumber_t numberArgument (RexxObject *argument, size_t position)
wholenumber_t numberArgument (RexxObject *argument, const char *position)
size_t nonNegativeArgument (RexxObject *argument, size_t position)
size_t nonNegativeArgument (RexxObject *argument, const char *position)
size_t positionArgument (RexxObject *argument, size_t position)
size_t positionArgument (RexxObject *argument, const char *position)
char padArgument (RexxObject *argument, size_t position)
char padArgument (RexxObject *argument, const char *position)
char optionArgument (RexxObject *argument, size_t position)
char optionArgument (RexxObject *argument, const char *position)
char optionArgument (RexxObject *argument, const char *validOptions, size_t position)
char optionArgument (RexxObject *argument, const char *validOptions, const char *position)
double floatingPointArgument (RexxObject *argument, const char *name)
void stringArrayArgument (ArrayClass *argArray, const char *position)
Function Documentation
floatingPointArgument()
double floatingPointArgument (RexxObject * argument, const char * name)
Take in an argument passed to a method, convert it to a floating point number. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The name of the argument (used for error reporting.)
Returns
The argument converted to a double floating point value.
Definition at line 395 of file StringClassUtil.cpp.
References RexxInternalObject::doubleValue(), Error_Invalid_argument_number, missingArgument(), OREF_NULL, and reportException().
Referenced by MutexSemaphoreClass::request(), and EventSemaphoreClass::wait().
lengthArgument() [1/2]
size_t lengthArgument (RexxObject * argument, const char * position)
Take in an argument passed to a method, convert it to a length object, verifying that the number is a non-negative value. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to a non-negative integer value.
Definition at line 87 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Invalid_argument_length, missingArgument(), OREF_NULL, reportException(), and RexxInternalObject::unsignedNumberValue().
lengthArgument() [2/2]
size_t lengthArgument (RexxObject * argument, size_t position)
Take in an argument passed to a method, convert it to a length object, verifying that the number is a non-negative value. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to a non-negative integer value.
Definition at line 61 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_method_length, missingArgument(), OREF_NULL, reportException(), and RexxInternalObject::unsignedNumberValue().
Referenced by RexxString::center(), RexxString::left(), optionalLengthArgument(), RexxString::right(), and MutableBuffer::setBufferSize().
nonNegativeArgument() [1/2]
size_t nonNegativeArgument (RexxObject * argument, const char * position)
Take in an argument passed to a method, convert it to a length object, verifying that the number is a non-negative value. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to a non-negative integer value.
Definition at line 188 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, missingArgument(), OREF_NULL, and RexxInternalObject::requiredNonNegative().
nonNegativeArgument() [2/2]
size_t nonNegativeArgument (RexxObject * argument, size_t position)
Take in an argument passed to a method, convert it to a length object, verifying that the number is a non-negative value. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to a non-negative integer value.
Definition at line 167 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, missingArgument(), OREF_NULL, and RexxInternalObject::requiredNonNegative().
Referenced by RexxString::copies(), ArrayClass::createMultidimensional(), optionalNonNegative(), and ArrayClass::validateSize().
numberArgument() [1/2]
wholenumber_t numberArgument (RexxObject * argument, const char * position)
Take in an argument passed to a method, convert it to a numeric object. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to an integer value.
Definition at line 140 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Invalid_argument_whole, missingArgument(), RexxInternalObject::numberValue(), OREF_NULL, and reportException().
numberArgument() [2/2]
wholenumber_t numberArgument (RexxObject * argument, size_t position)
Take in an argument passed to a method, convert it to a numeric object. If the argument is omitted, an error is raised.
Parameters
argument The argument reference to test.
position The position of the argument (used for error reporting.)
Returns
The argument converted to an integer value.
Definition at line 113 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_method_whole, missingArgument(), RexxInternalObject::numberValue(), OREF_NULL, and reportException().
Referenced by optionalNumberArgument().
optionArgument() [1/4]
char optionArgument (RexxObject * argument, const char * position)
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF.
Parameters
argument The argument to test.
position The position of the argument
Returns
The first character of the option string.
Definition at line 323 of file StringClassUtil.cpp.
References RexxString::getChar(), stringArgument(), and Utilities::toUpper().
optionArgument() [2/4]
char optionArgument (RexxObject * argument, const char * validOptions, const char * position)
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF. Also validate against the set of allowed characters.
Parameters
argument The argument to test.
position The position of the argument
Returns
The first character of the option string.
Definition at line 369 of file StringClassUtil.cpp.
References Error_Incorrect_method_option, RexxString::getChar(), RexxString::isNullString(), reportException(), stringArgument(), and Utilities::toUpper().
optionArgument() [3/4]
char optionArgument (RexxObject * argument, const char * validOptions, size_t position)
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF. Also validate against the set of allowed characters.
Parameters
argument The argument to test.
position The position of the argument
Returns
The first character of the option string.
Definition at line 342 of file StringClassUtil.cpp.
References Error_Incorrect_method_option, RexxString::getChar(), RexxString::isNullString(), reportException(), stringArgument(), and Utilities::toUpper().
optionArgument() [4/4]
char optionArgument (RexxObject * argument, size_t position)
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF.
Parameters
argument The argument to test.
position The position of the argument
Returns
The first character of the option string.
Definition at line 305 of file StringClassUtil.cpp.
References RexxString::getChar(), stringArgument(), and Utilities::toUpper().
Referenced by MessageClass::newRexx(), optionalOptionArgument(), and RexxObject::run().
padArgument() [1/2]
char padArgument (RexxObject * argument, const char * position)
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF.
Parameters
argument The argument to test.
position The argument position in the argument list.
Returns
The first character of the option.
Definition at line 283 of file StringClassUtil.cpp.
References Error_Invalid_argument_pad, RexxString::getChar(), RexxString::getLength(), new_string(), reportException(), and stringArgument().
padArgument() [2/2]
char padArgument (RexxObject * argument, size_t position)
Take in an argument passed to the BIF, convert it to a character, if it exists otherwise return the default character as defined (passed in) by the BIF.
Parameters
argument The argument to test.
position The argument position in the argument list.
Returns
The first character of the option.
Definition at line 261 of file StringClassUtil.cpp.
References Error_Incorrect_method_pad, RexxString::getChar(), RexxString::getLength(), reportException(), and stringArgument().
Referenced by optionalPadArgument().
positionArgument() [1/2]
size_t positionArgument (RexxObject * argument, const char * position)
Take in an argument passed to a method, convert it to a position value, verifying that the number is a positive value. If the argument is omitted, an error is raised.
Parameters
argument The argument to test.
position The argument list position of the argument.
Returns
The converted numeric value.
Definition at line 235 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Invalid_argument_position, missingArgument(), OREF_NULL, reportException(), and RexxInternalObject::unsignedNumberValue().
positionArgument() [2/2]
size_t positionArgument (RexxObject * argument, size_t position)
Take in an argument passed to a method, convert it to a position value, verifying that the number is a positive value. If the argument is omitted, an error is raised.
Parameters
argument The argument to test.
position The argument list position of the argument.
Returns
The converted numeric value.
Definition at line 209 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_method_position, missingArgument(), OREF_NULL, reportException(), and RexxInternalObject::unsignedNumberValue().
Referenced by MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), RexxString::delWord(), MutableBuffer::delWord(), ArrayClass::extendMulti(), PackageClass::getSourceLineRexx(), MutableBuffer::match(), RexxString::match(), MutableBuffer::matchChar(), RexxString::matchChar(), optionalPositionArgument(), MutableBuffer::replaceAt(), RexxString::replaceAt(), StringUtil::subchar(), StringUtil::substr(), StringUtil::subWord(), ArrayClass::validateMultiDimensionIndex(), StringUtil::word(), StringUtil::wordIndex(), and StringUtil::wordLength().
stringArrayArgument()
void stringArrayArgument (ArrayClass * argArray, const char * position)
Validate that an array is non-space up to the last item and contains nothing but string values.
Parameters
argArray The argument array.
position The argument name for error reporting.
Definition at line 417 of file StringClassUtil.cpp.
References counter(), Error_Incorrect_method_nostring_inarray, ArrayClass::get(), ArrayClass::lastIndex(), RexxString::makeString(), OREF_NULL, ArrayClass::put(), reportException(), and TheNilObject.
Referenced by BaseExecutable::processExecutableSource().