ooRexx: ThreadContextStubs.cpp File Reference
ThreadContextStubs.cpp File Reference
#include "RexxCore.h"
#include "ContextApi.hpp"
#include "Activity.hpp"
#include "StringClass.hpp"
#include "IntegerClass.hpp"
#include "BufferClass.hpp"
#include "SupplierClass.hpp"
#include "ArrayClass.hpp"
#include "DirectoryClass.hpp"
#include "MethodClass.hpp"
#include "RoutineClass.hpp"
#include "PackageClass.hpp"
#include "Interpreter.hpp"
#include "InterpreterInstance.hpp"
#include "SystemInterpreter.hpp"
#include "PointerClass.hpp"
#include "ActivityManager.hpp"
#include "RexxStartDispatcher.hpp"
#include "PackageManager.hpp"
#include "MutableBufferClass.hpp"
#include "MethodArguments.hpp"
#include "LanguageParser.hpp"
#include "StemClass.hpp"
#include "NumberStringClass.hpp"
#include "VariableReference.hpp"
#include "StringTableClass.hpp"
Functions
void RexxEntry DetachThread (RexxThreadContext *c)
void RexxEntry HaltThread (RexxThreadContext *c)
void RexxEntry SetThreadTrace (RexxThreadContext *c, logical_t setting)
RexxObjectPtr RexxEntry RequestGlobalReference (RexxThreadContext *c, RexxObjectPtr o)
void RexxEntry ReleaseGlobalReference (RexxThreadContext *c, RexxObjectPtr o)
void RexxEntry ReleaseLocalReference (RexxThreadContext *c, RexxObjectPtr o)
RexxObjectPtr RexxEntry SendMessageArray (RexxThreadContext *c, RexxObjectPtr o, CSTRING m, RexxArrayObject a)
RexxObjectPtr RexxEntry SendMessageScoped (RexxThreadContext *c, RexxObjectPtr o, CSTRING m, RexxClassObject s, RexxArrayObject a)
RexxObjectPtr RexxEntry SendMessage0 (RexxThreadContext *c, RexxObjectPtr o, CSTRING m)
RexxObjectPtr RexxEntry SendMessage1 (RexxThreadContext *c, RexxObjectPtr o, CSTRING m, RexxObjectPtr a1)
RexxObjectPtr RexxEntry SendMessage2 (RexxThreadContext *c, RexxObjectPtr o, CSTRING m, RexxObjectPtr a1, RexxObjectPtr a2)
RexxDirectoryObject RexxEntry GetLocalEnvironment (RexxThreadContext *c)
RexxDirectoryObject RexxEntry GetGlobalEnvironment (RexxThreadContext *c)
logical_t RexxEntry IsInstanceOf (RexxThreadContext *c, RexxObjectPtr o, RexxClassObject cl)
logical_t RexxEntry IsOfType (RexxThreadContext *c, RexxObjectPtr o, CSTRING cn)
logical_t RexxEntry HasMethod (RexxThreadContext *c, RexxObjectPtr o, CSTRING n)
RexxPackageObject RexxEntry LoadPackage (RexxThreadContext *c, CSTRING n)
RexxPackageObject RexxEntry LoadPackageFromData (RexxThreadContext *c, CSTRING n, CSTRING d, size_t l)
logical_t RexxEntry LoadLibraryPackage (RexxThreadContext *c, CSTRING n)
logical_t RexxEntry RegisterLibrary (RexxThreadContext *c, CSTRING n, RexxPackageEntry *e)
RexxClassObject RexxEntry FindClass (RexxThreadContext *c, CSTRING n)
RexxClassObject RexxEntry FindClassFromPackage (RexxThreadContext *c, RexxPackageObject m, CSTRING n)
RexxDirectoryObject RexxEntry GetPackageRoutines (RexxThreadContext *c, RexxPackageObject m)
RexxDirectoryObject RexxEntry GetPackagePublicRoutines (RexxThreadContext *c, RexxPackageObject m)
RexxDirectoryObject RexxEntry GetPackageClasses (RexxThreadContext *c, RexxPackageObject m)
RexxDirectoryObject RexxEntry GetPackagePublicClasses (RexxThreadContext *c, RexxPackageObject m)
RexxDirectoryObject RexxEntry GetPackageMethods (RexxThreadContext *c, RexxPackageObject m)
RexxObjectPtr RexxEntry CallRoutine (RexxThreadContext *c, RexxRoutineObject r, RexxArrayObject a)
RexxObjectPtr RexxEntry CallProgram (RexxThreadContext *c, const char *p, RexxArrayObject a)
RexxMethodObject RexxEntry NewMethod (RexxThreadContext *c, CSTRING n, CSTRING s, stringsize_t l)
RexxRoutineObject RexxEntry NewRoutine (RexxThreadContext *c, CSTRING n, CSTRING s, stringsize_t l)
logical_t RexxEntry IsRoutine (RexxThreadContext *c, RexxObjectPtr o)
logical_t RexxEntry IsMethod (RexxThreadContext *c, RexxObjectPtr o)
RexxPackageObject RexxEntry GetRoutinePackage (RexxThreadContext *c, RexxRoutineObject o)
RexxPackageObject RexxEntry GetMethodPackage (RexxThreadContext *c, RexxMethodObject o)
POINTER RexxEntry ObjectToCSelf (RexxThreadContext *c, RexxObjectPtr o)
POINTER RexxEntry ObjectToCSelfScoped (RexxThreadContext *c, RexxObjectPtr o, RexxObjectPtr s)
RexxObjectPtr RexxEntry WholeNumberToObject (RexxThreadContext *c, wholenumber_t n)
RexxObjectPtr RexxEntry UintptrToObject (RexxThreadContext *c, uintptr_t n)
RexxObjectPtr RexxEntry IntptrToObject (RexxThreadContext *c, intptr_t n)
RexxObjectPtr RexxEntry ValueToObject (RexxThreadContext *c, ValueDescriptor *d)
RexxArrayObject RexxEntry ValuesToObject (RexxThreadContext *c, ValueDescriptor *d, size_t count)
logical_t RexxEntry ObjectToValue (RexxThreadContext *c, RexxObjectPtr o, ValueDescriptor *d)
RexxObjectPtr RexxEntry StringSizeToObject (RexxThreadContext *c, stringsize_t n)
logical_t RexxEntry ObjectToWholeNumber (RexxThreadContext *c, RexxObjectPtr o, wholenumber_t *n)
RexxObjectPtr RexxEntry Int32ToObject (RexxThreadContext *c, int32_t n)
RexxObjectPtr RexxEntry UnsignedInt32ToObject (RexxThreadContext *c, uint32_t n)
logical_t RexxEntry ObjectToStringSize (RexxThreadContext *c, RexxObjectPtr o, stringsize_t *n)
logical_t RexxEntry ObjectToInt32 (RexxThreadContext *c, RexxObjectPtr o, int32_t *n)
logical_t RexxEntry ObjectToUnsignedInt32 (RexxThreadContext *c, RexxObjectPtr o, uint32_t *n)
RexxObjectPtr RexxEntry Int64ToObject (RexxThreadContext *c, int64_t n)
RexxObjectPtr RexxEntry UnsignedInt64ToObject (RexxThreadContext *c, uint64_t n)
logical_t RexxEntry ObjectToInt64 (RexxThreadContext *c, RexxObjectPtr o, int64_t *n)
logical_t RexxEntry ObjectToUnsignedInt64 (RexxThreadContext *c, RexxObjectPtr o, uint64_t *n)
logical_t RexxEntry ObjectToUintptr (RexxThreadContext *c, RexxObjectPtr o, uintptr_t *n)
logical_t RexxEntry ObjectToIntptr (RexxThreadContext *c, RexxObjectPtr o, intptr_t *n)
logical_t RexxEntry ObjectToLogical (RexxThreadContext *c, RexxObjectPtr o, logical_t *n)
RexxObjectPtr RexxEntry LogicalToObject (RexxThreadContext *c, logical_t n)
RexxObjectPtr RexxEntry DoubleToObject (RexxThreadContext *c, double n)
RexxObjectPtr RexxEntry DoubleToObjectWithPrecision (RexxThreadContext *c, double n, size_t precision)
logical_t RexxEntry ObjectToDouble (RexxThreadContext *c, RexxObjectPtr o, double *n)
RexxStringObject RexxEntry ObjectToString (RexxThreadContext *c, RexxObjectPtr o)
CSTRING RexxEntry ObjectToStringValue (RexxThreadContext *c, RexxObjectPtr o)
size_t RexxEntry StringGet (RexxThreadContext *c, RexxStringObject s, size_t o, POINTER r, size_t l)
size_t RexxEntry StringLength (RexxThreadContext *c, RexxStringObject s)
CSTRING RexxEntry StringData (RexxThreadContext *c, RexxStringObject s)
RexxStringObject RexxEntry NewString (RexxThreadContext *c, CSTRING s, size_t l)
RexxStringObject RexxEntry NewStringFromAsciiz (RexxThreadContext *c, CSTRING s)
RexxStringObject RexxEntry StringUpper (RexxThreadContext *c, RexxStringObject s)
RexxStringObject RexxEntry StringLower (RexxThreadContext *c, RexxStringObject s)
logical_t RexxEntry IsString (RexxThreadContext *c, RexxObjectPtr o)
RexxBufferStringObject RexxEntry NewBufferString (RexxThreadContext *c, size_t l)
size_t RexxEntry BufferStringLength (RexxThreadContext *c, RexxBufferStringObject s)
POINTER RexxEntry BufferStringData (RexxThreadContext *c, RexxBufferStringObject s)
RexxStringObject RexxEntry FinishBufferString (RexxThreadContext *c, RexxBufferStringObject s, size_t l)
void RexxEntry DirectoryPut (RexxThreadContext *c, RexxDirectoryObject t, RexxObjectPtr o, CSTRING i)
RexxObjectPtr RexxEntry DirectoryAt (RexxThreadContext *c, RexxDirectoryObject t, CSTRING i)
RexxObjectPtr RexxEntry DirectoryRemove (RexxThreadContext *c, RexxDirectoryObject t, CSTRING i)
RexxDirectoryObject RexxEntry NewDirectory (RexxThreadContext *c)
logical_t RexxEntry IsDirectory (RexxThreadContext *c, RexxObjectPtr o)
void RexxEntry StringTablePut (RexxThreadContext *c, RexxStringTableObject t, RexxObjectPtr o, CSTRING i)
RexxObjectPtr RexxEntry StringTableAt (RexxThreadContext *c, RexxStringTableObject t, CSTRING i)
RexxObjectPtr RexxEntry StringTableRemove (RexxThreadContext *c, RexxStringTableObject t, CSTRING i)
RexxStringTableObject RexxEntry NewStringTable (RexxThreadContext *c)
logical_t RexxEntry IsStringTable (RexxThreadContext *c, RexxObjectPtr o)
RexxObjectPtr RexxEntry ArrayAt (RexxThreadContext *c, RexxArrayObject a, size_t i)
void RexxEntry ArrayPut (RexxThreadContext *c, RexxArrayObject a, RexxObjectPtr o, size_t i)
size_t RexxEntry ArrayAppend (RexxThreadContext *c, RexxArrayObject a, RexxObjectPtr o)
size_t RexxEntry ArrayAppendString (RexxThreadContext *c, RexxArrayObject a, CSTRING s, size_t l)
size_t RexxEntry ArraySize (RexxThreadContext *c, RexxArrayObject a)
size_t RexxEntry ArrayItems (RexxThreadContext *c, RexxArrayObject a)
size_t RexxEntry ArrayDimension (RexxThreadContext *c, RexxArrayObject a)
RexxArrayObject RexxEntry NewArray (RexxThreadContext *c, size_t s)
RexxArrayObject RexxEntry ArrayOfOne (RexxThreadContext *c, RexxObjectPtr o)
RexxArrayObject RexxEntry ArrayOfTwo (RexxThreadContext *c, RexxObjectPtr o1, RexxObjectPtr o2)
RexxArrayObject RexxEntry ArrayOfThree (RexxThreadContext *c, RexxObjectPtr o1, RexxObjectPtr o2, RexxObjectPtr o3)
RexxArrayObject RexxEntry ArrayOfFour (RexxThreadContext *c, RexxObjectPtr o1, RexxObjectPtr o2, RexxObjectPtr o3, RexxObjectPtr o4)
logical_t RexxEntry IsArray (RexxThreadContext *c, RexxObjectPtr o)
POINTER RexxEntry BufferData (RexxThreadContext *c, RexxBufferObject b)
size_t RexxEntry BufferLength (RexxThreadContext *c, RexxBufferObject b)
RexxBufferObject RexxEntry NewBuffer (RexxThreadContext *c, size_t l)
logical_t RexxEntry IsBuffer (RexxThreadContext *c, RexxObjectPtr o)
POINTER RexxEntry PointerValue (RexxThreadContext *c, RexxPointerObject o)
RexxPointerObject RexxEntry NewPointer (RexxThreadContext *c, POINTER p)
logical_t RexxEntry IsPointer (RexxThreadContext *c, RexxObjectPtr o)
logical_t RexxEntry IsVariableReference (RexxThreadContext *c, RexxObjectPtr o)
RexxStringObject RexxEntry VariableReferenceName (RexxThreadContext *c, RexxVariableReferenceObject o)
RexxObjectPtr RexxEntry VariableReferenceValue (RexxThreadContext *c, RexxVariableReferenceObject o)
void RexxEntry SetVariableReferenceValue (RexxThreadContext *c, RexxVariableReferenceObject o, RexxObjectPtr v)
RexxObjectPtr RexxEntry SupplierItem (RexxThreadContext *c, RexxSupplierObject o)
RexxObjectPtr RexxEntry SupplierIndex (RexxThreadContext *c, RexxSupplierObject o)
logical_t RexxEntry SupplierAvailable (RexxThreadContext *c, RexxSupplierObject o)
void RexxEntry SupplierNext (RexxThreadContext *c, RexxSupplierObject o)
RexxSupplierObject RexxEntry NewSupplier (RexxThreadContext *c, RexxArrayObject values, RexxArrayObject names)
RexxStemObject RexxEntry NewStem (RexxThreadContext *c, CSTRING n)
void RexxEntry SetStemElement (RexxThreadContext *c, RexxStemObject s, CSTRING n, RexxObjectPtr v)
RexxObjectPtr RexxEntry GetStemElement (RexxThreadContext *c, RexxStemObject s, CSTRING n)
void RexxEntry DropStemElement (RexxThreadContext *c, RexxStemObject s, CSTRING n)
void RexxEntry SetStemArrayElement (RexxThreadContext *c, RexxStemObject s, size_t i, RexxObjectPtr v)
RexxObjectPtr RexxEntry GetStemArrayElement (RexxThreadContext *c, RexxStemObject s, size_t i)
void RexxEntry DropStemArrayElement (RexxThreadContext *c, RexxStemObject s, size_t i)
RexxDirectoryObject RexxEntry GetAllStemElements (RexxThreadContext *c, RexxStemObject s)
RexxObjectPtr RexxEntry GetStemValue (RexxThreadContext *c, RexxStemObject s)
logical_t RexxEntry IsStem (RexxThreadContext *c, RexxObjectPtr o)
void RexxEntry RaiseException0 (RexxThreadContext *c, size_t n)
void RexxEntry RaiseException1 (RexxThreadContext *c, size_t n, RexxObjectPtr o1)
void RexxEntry RaiseException2 (RexxThreadContext *c, size_t n, RexxObjectPtr o1, RexxObjectPtr o2)
void RexxEntry APIRaiseException (RexxThreadContext *c, size_t n, RexxArrayObject a)
void RexxEntry RaiseCondition (RexxThreadContext *c, CSTRING n, RexxStringObject desc, RexxObjectPtr add, RexxObjectPtr result)
logical_t RexxEntry CheckCondition (RexxThreadContext *c)
wholenumber_t RexxEntry DisplayCondition (RexxThreadContext *c)
RexxDirectoryObject RexxEntry GetConditionInfo (RexxThreadContext *c)
void RexxEntry DecodeConditionInfo (RexxThreadContext *c, RexxDirectoryObject d, RexxCondition *cd)
void RexxEntry ClearCondition (RexxThreadContext *c)
POINTER RexxEntry MutableBufferData (RexxThreadContext *c, RexxMutableBufferObject b)
size_t RexxEntry MutableBufferLength (RexxThreadContext *c, RexxMutableBufferObject b)
size_t RexxEntry SetMutableBufferLength (RexxThreadContext *c, RexxMutableBufferObject b, size_t length)
size_t RexxEntry MutableBufferCapacity (RexxThreadContext *c, RexxMutableBufferObject b)
POINTER RexxEntry SetMutableBufferCapacity (RexxThreadContext *c, RexxMutableBufferObject b, size_t length)
RexxMutableBufferObject RexxEntry NewMutableBuffer (RexxThreadContext *c, size_t l)
logical_t RexxEntry IsMutableBuffer (RexxThreadContext *c, RexxObjectPtr o)
RexxInstance *RexxEntry GetInterpreterInstance (RexxThreadContext *c)
Function Documentation
APIRaiseException()
void RexxEntry APIRaiseException (RexxThreadContext * c, size_t n, RexxArrayObject a)
Definition at line 1899 of file ThreadContextStubs.cpp.
References reportException().
ArrayAppend()
size_t RexxEntry ArrayAppend (RexxThreadContext * c, RexxArrayObject a, RexxObjectPtr o)
Definition at line 1374 of file ThreadContextStubs.cpp.
ArrayAppendString()
size_t RexxEntry ArrayAppendString (RexxThreadContext * c, RexxArrayObject a, CSTRING s, size_t l)
Definition at line 1388 of file ThreadContextStubs.cpp.
References new_string().
ArrayAt()
RexxObjectPtr RexxEntry ArrayAt (RexxThreadContext * c, RexxArrayObject a, size_t i)
Definition at line 1339 of file ThreadContextStubs.cpp.
References Error_Incorrect_method_positive, OREF_NULL, reportException(), and ApiContext::ret().
ArrayDimension()
size_t RexxEntry ArrayDimension (RexxThreadContext * c, RexxArrayObject a)
Definition at line 1430 of file ThreadContextStubs.cpp.
ArrayItems()
size_t RexxEntry ArrayItems (RexxThreadContext * c, RexxArrayObject a)
Definition at line 1417 of file ThreadContextStubs.cpp.
ArrayOfFour()
RexxArrayObject RexxEntry ArrayOfFour (RexxThreadContext * c, RexxObjectPtr o1, RexxObjectPtr o2, RexxObjectPtr o3, RexxObjectPtr o4)
Definition at line 1495 of file ThreadContextStubs.cpp.
References new_array(), NULLOBJECT, and ApiContext::ret().
ArrayOfOne()
RexxArrayObject RexxEntry ArrayOfOne (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1456 of file ThreadContextStubs.cpp.
References new_array(), NULLOBJECT, and ApiContext::ret().
ArrayOfThree()
RexxArrayObject RexxEntry ArrayOfThree (RexxThreadContext * c, RexxObjectPtr o1, RexxObjectPtr o2, RexxObjectPtr o3)
Definition at line 1482 of file ThreadContextStubs.cpp.
References new_array(), NULLOBJECT, and ApiContext::ret().
ArrayOfTwo()
RexxArrayObject RexxEntry ArrayOfTwo (RexxThreadContext * c, RexxObjectPtr o1, RexxObjectPtr o2)
Definition at line 1469 of file ThreadContextStubs.cpp.
References new_array(), NULLOBJECT, and ApiContext::ret().
ArrayPut()
void RexxEntry ArrayPut (RexxThreadContext * c, RexxArrayObject a, RexxObjectPtr o, size_t i)
Definition at line 1357 of file ThreadContextStubs.cpp.
References Error_Incorrect_method_positive, and reportException().
ArraySize()
size_t RexxEntry ArraySize (RexxThreadContext * c, RexxArrayObject a)
Definition at line 1403 of file ThreadContextStubs.cpp.
BufferData()
POINTER RexxEntry BufferData (RexxThreadContext * c, RexxBufferObject b)
Definition at line 1522 of file ThreadContextStubs.cpp.
BufferLength()
size_t RexxEntry BufferLength (RexxThreadContext * c, RexxBufferObject b)
Definition at line 1535 of file ThreadContextStubs.cpp.
BufferStringData()
POINTER RexxEntry BufferStringData (RexxThreadContext * c, RexxBufferStringObject s)
Definition at line 1176 of file ThreadContextStubs.cpp.
References RexxString::getWritableData().
BufferStringLength()
size_t RexxEntry BufferStringLength (RexxThreadContext * c, RexxBufferStringObject s)
Definition at line 1162 of file ThreadContextStubs.cpp.
References RexxString::getLength().
CallProgram()
RexxObjectPtr RexxEntry CallProgram (RexxThreadContext * c, const char * p, RexxArrayObject a)
Definition at line 505 of file ThreadContextStubs.cpp.
References ApiContext::activity, NULLOBJECT, CallProgramDispatcher::result, ApiContext::ret(), and Activity::run().
CallRoutine()
RexxObjectPtr RexxEntry CallRoutine (RexxThreadContext * c, RexxRoutineObject r, RexxArrayObject a)
Definition at line 489 of file ThreadContextStubs.cpp.
References ApiContext::activity, NULLOBJECT, CallRoutineDispatcher::result, ApiContext::ret(), and Activity::run().
CheckCondition()
logical_t RexxEntry CheckCondition (RexxThreadContext * c)
Definition at line 1925 of file ThreadContextStubs.cpp.
References ApiContext::context, NativeActivation::getConditionInfo(), and OREF_NULL.
ClearCondition()
void RexxEntry ClearCondition (RexxThreadContext * c)
Definition at line 1977 of file ThreadContextStubs.cpp.
References NativeActivation::clearException(), and ApiContext::context.
DecodeConditionInfo()
void RexxEntry DecodeConditionInfo (RexxThreadContext * c, RexxDirectoryObject d, RexxCondition * cd)
Definition at line 1965 of file ThreadContextStubs.cpp.
References Interpreter::decodeConditionData().
DetachThread()
void RexxEntry DetachThread (RexxThreadContext * c)
Definition at line 74 of file ThreadContextStubs.cpp.
References ApiContext::activity, and Activity::detachThread().
DirectoryAt()
RexxObjectPtr RexxEntry DirectoryAt (RexxThreadContext * c, RexxDirectoryObject t, CSTRING i)
Definition at line 1218 of file ThreadContextStubs.cpp.
References new_string(), OREF_NULL, and ApiContext::ret().
DirectoryPut()
void RexxEntry DirectoryPut (RexxThreadContext * c, RexxDirectoryObject t, RexxObjectPtr o, CSTRING i)
Definition at line 1205 of file ThreadContextStubs.cpp.
References new_string().
DirectoryRemove()
RexxObjectPtr RexxEntry DirectoryRemove (RexxThreadContext * c, RexxDirectoryObject t, CSTRING i)
Definition at line 1232 of file ThreadContextStubs.cpp.
References new_string(), OREF_NULL, and ApiContext::ret().
DisplayCondition()
wholenumber_t RexxEntry DisplayCondition (RexxThreadContext * c)
Definition at line 1938 of file ThreadContextStubs.cpp.
References ApiContext::activity, ApiContext::context, Activity::displayCondition(), Error_Interpretation, and NativeActivation::getConditionInfo().
DoubleToObject()
RexxObjectPtr RexxEntry DoubleToObject (RexxThreadContext * c, double n)
Definition at line 973 of file ThreadContextStubs.cpp.
References new_numberstringFromDouble(), NULLOBJECT, and ApiContext::ret().
DoubleToObjectWithPrecision()
RexxObjectPtr RexxEntry DoubleToObjectWithPrecision (RexxThreadContext * c, double n, size_t precision)
Definition at line 986 of file ThreadContextStubs.cpp.
References new_numberstringFromDouble(), NULLOBJECT, and ApiContext::ret().
DropStemArrayElement()
void RexxEntry DropStemArrayElement (RexxThreadContext * c, RexxStemObject s, size_t i)
Definition at line 1812 of file ThreadContextStubs.cpp.
DropStemElement()
void RexxEntry DropStemElement (RexxThreadContext * c, RexxStemObject s, CSTRING n)
Definition at line 1775 of file ThreadContextStubs.cpp.
FindClass()
RexxClassObject RexxEntry FindClass (RexxThreadContext * c, CSTRING n)
Definition at line 387 of file ThreadContextStubs.cpp.
References ApiContext::context, NativeActivation::findClass(), new_upper_string(), NULLOBJECT, and ApiContext::ret().
FindClassFromPackage()
RexxClassObject RexxEntry FindClassFromPackage (RexxThreadContext * c, RexxPackageObject m, CSTRING n)
Definition at line 405 of file ThreadContextStubs.cpp.
References new_upper_string(), NULLOBJECT, and ApiContext::ret().
FinishBufferString()
RexxStringObject RexxEntry FinishBufferString (RexxThreadContext * c, RexxBufferStringObject s, size_t l)
Definition at line 1190 of file ThreadContextStubs.cpp.
References RexxString::finish().
GetAllStemElements()
RexxDirectoryObject RexxEntry GetAllStemElements (RexxThreadContext * c, RexxStemObject s)
Definition at line 1824 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
GetConditionInfo()
RexxDirectoryObject RexxEntry GetConditionInfo (RexxThreadContext * c)
Definition at line 1951 of file ThreadContextStubs.cpp.
References ApiContext::context, NativeActivation::getConditionInfo(), OREF_NULL, and ApiContext::ret().
GetGlobalEnvironment()
RexxDirectoryObject RexxEntry GetGlobalEnvironment (RexxThreadContext * c)
Definition at line 252 of file ThreadContextStubs.cpp.
References NULLOBJECT, and TheEnvironment.
GetInterpreterInstance()
RexxInstance* RexxEntry GetInterpreterInstance (RexxThreadContext * c)
Definition at line 2081 of file ThreadContextStubs.cpp.
References ApiContext::context, NativeActivation::getActivity(), Activity::getInstance(), and InterpreterInstance::getInstanceContext().
GetLocalEnvironment()
RexxDirectoryObject RexxEntry GetLocalEnvironment (RexxThreadContext * c)
Definition at line 239 of file ThreadContextStubs.cpp.
References ApiContext::activity, Activity::getLocal(), and NULLOBJECT.
GetMethodPackage()
RexxPackageObject RexxEntry GetMethodPackage (RexxThreadContext * c, RexxMethodObject o)
Definition at line 601 of file ThreadContextStubs.cpp.
References ApiContext::ret().
GetPackageClasses()
RexxDirectoryObject RexxEntry GetPackageClasses (RexxThreadContext * c, RexxPackageObject m)
Definition at line 449 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
GetPackageMethods()
RexxDirectoryObject RexxEntry GetPackageMethods (RexxThreadContext * c, RexxPackageObject m)
Definition at line 475 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
GetPackagePublicClasses()
RexxDirectoryObject RexxEntry GetPackagePublicClasses (RexxThreadContext * c, RexxPackageObject m)
Definition at line 462 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
GetPackagePublicRoutines()
RexxDirectoryObject RexxEntry GetPackagePublicRoutines (RexxThreadContext * c, RexxPackageObject m)
Definition at line 436 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
GetPackageRoutines()
RexxDirectoryObject RexxEntry GetPackageRoutines (RexxThreadContext * c, RexxPackageObject m)
Definition at line 422 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
GetRoutinePackage()
RexxPackageObject RexxEntry GetRoutinePackage (RexxThreadContext * c, RexxRoutineObject o)
Definition at line 586 of file ThreadContextStubs.cpp.
References ApiContext::ret().
GetStemArrayElement()
RexxObjectPtr RexxEntry GetStemArrayElement (RexxThreadContext * c, RexxStemObject s, size_t i)
Definition at line 1799 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
GetStemElement()
RexxObjectPtr RexxEntry GetStemElement (RexxThreadContext * c, RexxStemObject s, CSTRING n)
Definition at line 1762 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
GetStemValue()
RexxObjectPtr RexxEntry GetStemValue (RexxThreadContext * c, RexxStemObject s)
Definition at line 1837 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
HaltThread()
void RexxEntry HaltThread (RexxThreadContext * c)
API stub for raising a halt condition on a thread.
Definition at line 91 of file ThreadContextStubs.cpp.
References ApiContext::activity, Activity::halt(), and OREF_NULL.
HasMethod()
logical_t RexxEntry HasMethod (RexxThreadContext * c, RexxObjectPtr o, CSTRING n)
Definition at line 303 of file ThreadContextStubs.cpp.
References new_upper_string().
Int32ToObject()
RexxObjectPtr RexxEntry Int32ToObject (RexxThreadContext * c, int32_t n)
Definition at line 771 of file ThreadContextStubs.cpp.
References NULLOBJECT, ApiContext::ret(), and Numerics::wholenumberToObject().
Int64ToObject()
RexxObjectPtr RexxEntry Int64ToObject (RexxThreadContext * c, int64_t n)
Definition at line 864 of file ThreadContextStubs.cpp.
References Numerics::int64ToObject(), NULLOBJECT, and ApiContext::ret().
IntptrToObject()
RexxObjectPtr RexxEntry IntptrToObject (RexxThreadContext * c, intptr_t n)
Definition at line 672 of file ThreadContextStubs.cpp.
References Numerics::intptrToObject(), NULLOBJECT, and ApiContext::ret().
IsArray()
logical_t RexxEntry IsArray (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1509 of file ThreadContextStubs.cpp.
References isArray().
IsBuffer()
logical_t RexxEntry IsBuffer (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1561 of file ThreadContextStubs.cpp.
References isOfClass.
IsDirectory()
logical_t RexxEntry IsDirectory (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1259 of file ThreadContextStubs.cpp.
References isOfClass.
IsInstanceOf()
logical_t RexxEntry IsInstanceOf (RexxThreadContext * c, RexxObjectPtr o, RexxClassObject cl)
Definition at line 266 of file ThreadContextStubs.cpp.
IsMethod()
logical_t RexxEntry IsMethod (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 571 of file ThreadContextStubs.cpp.
References TheMethodClass.
IsMutableBuffer()
logical_t RexxEntry IsMutableBuffer (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 2067 of file ThreadContextStubs.cpp.
References isOfClass.
IsOfType()
logical_t RexxEntry IsOfType (RexxThreadContext * c, RexxObjectPtr o, CSTRING cn)
Definition at line 279 of file ThreadContextStubs.cpp.
References ApiContext::context, NativeActivation::findClass(), RexxObject::isInstanceOf(), new_upper_string(), and OREF_NULL.
IsPointer()
logical_t RexxEntry IsPointer (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1600 of file ThreadContextStubs.cpp.
References isOfClass.
IsRoutine()
logical_t RexxEntry IsRoutine (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 556 of file ThreadContextStubs.cpp.
References TheRoutineClass.
IsStem()
logical_t RexxEntry IsStem (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1850 of file ThreadContextStubs.cpp.
References isStem().
IsString()
logical_t RexxEntry IsString (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1136 of file ThreadContextStubs.cpp.
References isString().
IsStringTable()
logical_t RexxEntry IsStringTable (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1326 of file ThreadContextStubs.cpp.
References isOfClass.
IsVariableReference()
logical_t RexxEntry IsVariableReference (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1613 of file ThreadContextStubs.cpp.
References isOfClass.
LoadLibraryPackage()
logical_t RexxEntry LoadLibraryPackage (RexxThreadContext * c, CSTRING n)
Definition at line 353 of file ThreadContextStubs.cpp.
References PackageManager::loadLibrary(), new_string(), and OREF_NULL.
LoadPackage()
RexxPackageObject RexxEntry LoadPackage (RexxThreadContext * c, CSTRING n)
Definition at line 320 of file ThreadContextStubs.cpp.
References ApiContext::activity, Activity::getInstance(), InterpreterInstance::loadRequires(), new_string(), NULLOBJECT, OREF_NULL, RESOLVE_DEFAULT, Activity::resolveProgramName(), and ApiContext::ret().
LoadPackageFromData()
RexxPackageObject RexxEntry LoadPackageFromData (RexxThreadContext * c, CSTRING n, CSTRING d, size_t l)
Definition at line 338 of file ThreadContextStubs.cpp.
References ApiContext::activity, Activity::getInstance(), InterpreterInstance::loadRequires(), new_string(), NULLOBJECT, and ApiContext::ret().
LogicalToObject()
RexxObjectPtr RexxEntry LogicalToObject (RexxThreadContext * c, logical_t n)
Definition at line 960 of file ThreadContextStubs.cpp.
References booleanObject(), and NULLOBJECT.
MutableBufferCapacity()
size_t RexxEntry MutableBufferCapacity (RexxThreadContext * c, RexxMutableBufferObject b)
Definition at line 2028 of file ThreadContextStubs.cpp.
MutableBufferData()
POINTER RexxEntry MutableBufferData (RexxThreadContext * c, RexxMutableBufferObject b)
Definition at line 1989 of file ThreadContextStubs.cpp.
MutableBufferLength()
size_t RexxEntry MutableBufferLength (RexxThreadContext * c, RexxMutableBufferObject b)
Definition at line 2002 of file ThreadContextStubs.cpp.
NewArray()
RexxArrayObject RexxEntry NewArray (RexxThreadContext * c, size_t s)
Definition at line 1443 of file ThreadContextStubs.cpp.
References new_array(), NULLOBJECT, and ApiContext::ret().
NewBuffer()
RexxBufferObject RexxEntry NewBuffer (RexxThreadContext * c, size_t l)
Definition at line 1548 of file ThreadContextStubs.cpp.
References new_buffer(), NULLOBJECT, and ApiContext::ret().
NewBufferString()
RexxBufferStringObject RexxEntry NewBufferString (RexxThreadContext * c, size_t l)
Definition at line 1149 of file ThreadContextStubs.cpp.
References NULLOBJECT, raw_string(), and ApiContext::ret().
NewDirectory()
RexxDirectoryObject RexxEntry NewDirectory (RexxThreadContext * c)
Definition at line 1246 of file ThreadContextStubs.cpp.
References new_directory(), OREF_NULL, and ApiContext::ret().
NewMethod()
RexxMethodObject RexxEntry NewMethod (RexxThreadContext * c, CSTRING n, CSTRING s, stringsize_t l)
Definition at line 521 of file ThreadContextStubs.cpp.
References LanguageParser::createMethod(), new_buffer(), new_string(), NULLOBJECT, and ApiContext::ret().
NewMutableBuffer()
RexxMutableBufferObject RexxEntry NewMutableBuffer (RexxThreadContext * c, size_t l)
Definition at line 2054 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
NewPointer()
RexxPointerObject RexxEntry NewPointer (RexxThreadContext * c, POINTER p)
Definition at line 1587 of file ThreadContextStubs.cpp.
References new_pointer(), NULLOBJECT, and ApiContext::ret().
NewRoutine()
RexxRoutineObject RexxEntry NewRoutine (RexxThreadContext * c, CSTRING n, CSTRING s, stringsize_t l)
Definition at line 538 of file ThreadContextStubs.cpp.
References LanguageParser::createRoutine(), new_buffer(), new_string(), NULLOBJECT, OREF_NULL, and ApiContext::ret().
NewStem()
RexxStemObject RexxEntry NewStem (RexxThreadContext * c, CSTRING n)
Definition at line 1728 of file ThreadContextStubs.cpp.
References new_string(), NULLOBJECT, OREF_NULL, and ApiContext::ret().
NewString()
RexxStringObject RexxEntry NewString (RexxThreadContext * c, CSTRING s, size_t l)
Definition at line 1082 of file ThreadContextStubs.cpp.
References new_string(), NULLOBJECT, and ApiContext::ret().
NewStringFromAsciiz()
RexxStringObject RexxEntry NewStringFromAsciiz (RexxThreadContext * c, CSTRING s)
Definition at line 1095 of file ThreadContextStubs.cpp.
References new_string(), NULLOBJECT, and ApiContext::ret().
NewStringTable()
RexxStringTableObject RexxEntry NewStringTable (RexxThreadContext * c)
Definition at line 1313 of file ThreadContextStubs.cpp.
References new_string_table(), OREF_NULL, and ApiContext::ret().
NewSupplier()
RexxSupplierObject RexxEntry NewSupplier (RexxThreadContext * c, RexxArrayObject values, RexxArrayObject names)
Definition at line 1715 of file ThreadContextStubs.cpp.
References new_supplier(), NULLOBJECT, and ApiContext::ret().
ObjectToCSelf()
POINTER RexxEntry ObjectToCSelf (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 616 of file ThreadContextStubs.cpp.
ObjectToCSelfScoped()
POINTER RexxEntry ObjectToCSelfScoped (RexxThreadContext * c, RexxObjectPtr o, RexxObjectPtr s)
Definition at line 631 of file ThreadContextStubs.cpp.
ObjectToDouble()
logical_t RexxEntry ObjectToDouble (RexxThreadContext * c, RexxObjectPtr o, double * n)
Definition at line 999 of file ThreadContextStubs.cpp.
ObjectToInt32()
logical_t RexxEntry ObjectToInt32 (RexxThreadContext * c, RexxObjectPtr o, int32_t * n)
Definition at line 820 of file ThreadContextStubs.cpp.
References INT32_MAX, INT32_MIN, and Numerics::objectToSignedInteger().
ObjectToInt64()
logical_t RexxEntry ObjectToInt64 (RexxThreadContext * c, RexxObjectPtr o, int64_t * n)
Definition at line 890 of file ThreadContextStubs.cpp.
References Numerics::objectToInt64().
ObjectToIntptr()
logical_t RexxEntry ObjectToIntptr (RexxThreadContext * c, RexxObjectPtr o, intptr_t * n)
Definition at line 932 of file ThreadContextStubs.cpp.
References Numerics::objectToIntptr().
ObjectToLogical()
logical_t RexxEntry ObjectToLogical (RexxThreadContext * c, RexxObjectPtr o, logical_t * n)
Definition at line 946 of file ThreadContextStubs.cpp.
ObjectToString()
RexxStringObject RexxEntry ObjectToString (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1012 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
ObjectToStringSize()
logical_t RexxEntry ObjectToStringSize (RexxThreadContext * c, RexxObjectPtr o, stringsize_t * n)
Definition at line 799 of file ThreadContextStubs.cpp.
References Numerics::MAX_WHOLENUMBER, and Numerics::objectToStringSize().
ObjectToStringValue()
CSTRING RexxEntry ObjectToStringValue (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 1025 of file ThreadContextStubs.cpp.
References RexxString::getStringData(), RexxInternalObject::requestString(), and ApiContext::ret().
ObjectToUintptr()
logical_t RexxEntry ObjectToUintptr (RexxThreadContext * c, RexxObjectPtr o, uintptr_t * n)
Definition at line 918 of file ThreadContextStubs.cpp.
References Numerics::objectToUintptr().
ObjectToUnsignedInt32()
logical_t RexxEntry ObjectToUnsignedInt32 (RexxThreadContext * c, RexxObjectPtr o, uint32_t * n)
Definition at line 843 of file ThreadContextStubs.cpp.
References Numerics::objectToUnsignedInteger(), and UINT32_MAX.
ObjectToUnsignedInt64()
logical_t RexxEntry ObjectToUnsignedInt64 (RexxThreadContext * c, RexxObjectPtr o, uint64_t * n)
Definition at line 904 of file ThreadContextStubs.cpp.
References Numerics::objectToUnsignedInt64().
ObjectToValue()
logical_t RexxEntry ObjectToValue (RexxThreadContext * c, RexxObjectPtr o, ValueDescriptor * d)
Definition at line 718 of file ThreadContextStubs.cpp.
References NativeActivation::clearException(), ApiContext::context, and NativeActivation::objectToValue().
ObjectToWholeNumber()
logical_t RexxEntry ObjectToWholeNumber (RexxThreadContext * c, RexxObjectPtr o, wholenumber_t * n)
Definition at line 748 of file ThreadContextStubs.cpp.
References Numerics::MAX_WHOLENUMBER, Numerics::MIN_WHOLENUMBER, and Numerics::objectToWholeNumber().
PointerValue()
POINTER RexxEntry PointerValue (RexxThreadContext * c, RexxPointerObject o)
Definition at line 1574 of file ThreadContextStubs.cpp.
RaiseCondition()
void RexxEntry RaiseCondition (RexxThreadContext * c, CSTRING n, RexxStringObject desc, RexxObjectPtr add, RexxObjectPtr result)
Definition at line 1911 of file ThreadContextStubs.cpp.
References ApiContext::activity, ApiContext::context, NativeActivation::enableConditionTrap(), new_upper_string(), OREF_NULL, and Activity::raiseCondition().
RaiseException0()
void RexxEntry RaiseException0 (RexxThreadContext * c, size_t n)
Definition at line 1863 of file ThreadContextStubs.cpp.
References reportException().
RaiseException1()
void RexxEntry RaiseException1 (RexxThreadContext * c, size_t n, RexxObjectPtr o1)
Definition at line 1875 of file ThreadContextStubs.cpp.
References reportException().
RaiseException2()
void RexxEntry RaiseException2 (RexxThreadContext * c, size_t n, RexxObjectPtr o1, RexxObjectPtr o2)
Definition at line 1887 of file ThreadContextStubs.cpp.
References reportException().
RegisterLibrary()
logical_t RexxEntry RegisterLibrary (RexxThreadContext * c, CSTRING n, RexxPackageEntry * e)
Definition at line 370 of file ThreadContextStubs.cpp.
References new_string(), and PackageManager::registerPackage().
ReleaseGlobalReference()
void RexxEntry ReleaseGlobalReference (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 132 of file ThreadContextStubs.cpp.
References ApiContext::activity, Activity::getInstance(), and InterpreterInstance::removeGlobalReference().
ReleaseLocalReference()
void RexxEntry ReleaseLocalReference (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 145 of file ThreadContextStubs.cpp.
References ApiContext::context, and NativeActivation::removeLocalReference().
RequestGlobalReference()
RexxObjectPtr RexxEntry RequestGlobalReference (RexxThreadContext * c, RexxObjectPtr o)
Definition at line 117 of file ThreadContextStubs.cpp.
References ApiContext::activity, InterpreterInstance::addGlobalReference(), Activity::getInstance(), and NULLOBJECT.
SendMessage0()
RexxObjectPtr RexxEntry SendMessage0 (RexxThreadContext * c, RexxObjectPtr o, CSTRING m)
Definition at line 193 of file ThreadContextStubs.cpp.
References new_upper_string(), NULLOBJECT, and ApiContext::ret().
SendMessage1()
RexxObjectPtr RexxEntry SendMessage1 (RexxThreadContext * c, RexxObjectPtr o, CSTRING m, RexxObjectPtr a1)
Definition at line 209 of file ThreadContextStubs.cpp.
References new_upper_string(), NULLOBJECT, and ApiContext::ret().
SendMessage2()
RexxObjectPtr RexxEntry SendMessage2 (RexxThreadContext * c, RexxObjectPtr o, CSTRING m, RexxObjectPtr a1, RexxObjectPtr a2)
Definition at line 224 of file ThreadContextStubs.cpp.
References new_upper_string(), NULLOBJECT, and ApiContext::ret().
SendMessageArray()
RexxObjectPtr RexxEntry SendMessageArray (RexxThreadContext * c, RexxObjectPtr o, CSTRING m, RexxArrayObject a)
Definition at line 160 of file ThreadContextStubs.cpp.
References new_upper_string(), NULLOBJECT, and ApiContext::ret().
SendMessageScoped()
RexxObjectPtr RexxEntry SendMessageScoped (RexxThreadContext * c, RexxObjectPtr o, CSTRING m, RexxClassObject s, RexxArrayObject a)
Definition at line 176 of file ThreadContextStubs.cpp.
References new_upper_string(), NULLOBJECT, and ApiContext::ret().
SetMutableBufferCapacity()
POINTER RexxEntry SetMutableBufferCapacity (RexxThreadContext * c, RexxMutableBufferObject b, size_t length)
Definition at line 2041 of file ThreadContextStubs.cpp.
SetMutableBufferLength()
size_t RexxEntry SetMutableBufferLength (RexxThreadContext * c, RexxMutableBufferObject b, size_t length)
Definition at line 2015 of file ThreadContextStubs.cpp.
SetStemArrayElement()
void RexxEntry SetStemArrayElement (RexxThreadContext * c, RexxStemObject s, size_t i, RexxObjectPtr v)
Definition at line 1787 of file ThreadContextStubs.cpp.
SetStemElement()
void RexxEntry SetStemElement (RexxThreadContext * c, RexxStemObject s, CSTRING n, RexxObjectPtr v)
Definition at line 1750 of file ThreadContextStubs.cpp.
SetThreadTrace()
void RexxEntry SetThreadTrace (RexxThreadContext * c, logical_t setting)
Definition at line 104 of file ThreadContextStubs.cpp.
References ApiContext::activity, and Activity::setTrace().
SetVariableReferenceValue()
void RexxEntry SetVariableReferenceValue (RexxThreadContext * c, RexxVariableReferenceObject o, RexxObjectPtr v)
Definition at line 1652 of file ThreadContextStubs.cpp.
StringData()
CSTRING RexxEntry StringData (RexxThreadContext * c, RexxStringObject s)
Definition at line 1068 of file ThreadContextStubs.cpp.
References RexxString::getStringData().
StringGet()
size_t RexxEntry StringGet (RexxThreadContext * c, RexxStringObject s, size_t o, POINTER r, size_t l)
Definition at line 1040 of file ThreadContextStubs.cpp.
References RexxString::copyData().
StringLength()
size_t RexxEntry StringLength (RexxThreadContext * c, RexxStringObject s)
Definition at line 1054 of file ThreadContextStubs.cpp.
References RexxString::getLength().
StringLower()
RexxStringObject RexxEntry StringLower (RexxThreadContext * c, RexxStringObject s)
Definition at line 1122 of file ThreadContextStubs.cpp.
References RexxString::lower(), NULLOBJECT, and ApiContext::ret().
StringSizeToObject()
RexxObjectPtr RexxEntry StringSizeToObject (RexxThreadContext * c, stringsize_t n)
Definition at line 734 of file ThreadContextStubs.cpp.
References NULLOBJECT, ApiContext::ret(), and Numerics::stringsizeToObject().
StringTableAt()
RexxObjectPtr RexxEntry StringTableAt (RexxThreadContext * c, RexxStringTableObject t, CSTRING i)
Definition at line 1285 of file ThreadContextStubs.cpp.
References new_string(), OREF_NULL, and ApiContext::ret().
StringTablePut()
void RexxEntry StringTablePut (RexxThreadContext * c, RexxStringTableObject t, RexxObjectPtr o, CSTRING i)
Definition at line 1272 of file ThreadContextStubs.cpp.
References new_string().
StringTableRemove()
RexxObjectPtr RexxEntry StringTableRemove (RexxThreadContext * c, RexxStringTableObject t, CSTRING i)
Definition at line 1299 of file ThreadContextStubs.cpp.
References new_string(), OREF_NULL, and ApiContext::ret().
StringUpper()
RexxStringObject RexxEntry StringUpper (RexxThreadContext * c, RexxStringObject s)
Definition at line 1108 of file ThreadContextStubs.cpp.
References NULLOBJECT, ApiContext::ret(), and RexxString::upper().
SupplierAvailable()
logical_t RexxEntry SupplierAvailable (RexxThreadContext * c, RexxSupplierObject o)
Definition at line 1690 of file ThreadContextStubs.cpp.
SupplierIndex()
RexxObjectPtr RexxEntry SupplierIndex (RexxThreadContext * c, RexxSupplierObject o)
Definition at line 1677 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
SupplierItem()
RexxObjectPtr RexxEntry SupplierItem (RexxThreadContext * c, RexxSupplierObject o)
Definition at line 1664 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
SupplierNext()
void RexxEntry SupplierNext (RexxThreadContext * c, RexxSupplierObject o)
Definition at line 1703 of file ThreadContextStubs.cpp.
UintptrToObject()
RexxObjectPtr RexxEntry UintptrToObject (RexxThreadContext * c, uintptr_t n)
Definition at line 659 of file ThreadContextStubs.cpp.
References NULLOBJECT, ApiContext::ret(), and Numerics::uintptrToObject().
UnsignedInt32ToObject()
RexxObjectPtr RexxEntry UnsignedInt32ToObject (RexxThreadContext * c, uint32_t n)
Definition at line 785 of file ThreadContextStubs.cpp.
References NULLOBJECT, ApiContext::ret(), and Numerics::stringsizeToObject().
UnsignedInt64ToObject()
RexxObjectPtr RexxEntry UnsignedInt64ToObject (RexxThreadContext * c, uint64_t n)
Definition at line 877 of file ThreadContextStubs.cpp.
References NULLOBJECT, ApiContext::ret(), and Numerics::uint64ToObject().
ValuesToObject()
RexxArrayObject RexxEntry ValuesToObject (RexxThreadContext * c, ValueDescriptor * d, size_t count)
Definition at line 702 of file ThreadContextStubs.cpp.
References NativeActivation::clearException(), ApiContext::context, NULLOBJECT, ApiContext::ret(), and NativeActivation::valuesToObject().
ValueToObject()
RexxObjectPtr RexxEntry ValueToObject (RexxThreadContext * c, ValueDescriptor * d)
Definition at line 686 of file ThreadContextStubs.cpp.
References NativeActivation::clearException(), ApiContext::context, NULLOBJECT, ApiContext::ret(), and NativeActivation::valueToObject().
VariableReferenceName()
RexxStringObject RexxEntry VariableReferenceName (RexxThreadContext * c, RexxVariableReferenceObject o)
Definition at line 1626 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
VariableReferenceValue()
RexxObjectPtr RexxEntry VariableReferenceValue (RexxThreadContext * c, RexxVariableReferenceObject o)
Definition at line 1639 of file ThreadContextStubs.cpp.
References NULLOBJECT, and ApiContext::ret().
WholeNumberToObject()
RexxObjectPtr RexxEntry WholeNumberToObject (RexxThreadContext * c, wholenumber_t n)
Definition at line 646 of file ThreadContextStubs.cpp.
References NULLOBJECT, ApiContext::ret(), and Numerics::wholenumberToObject().