ooRexx: VariableDictionary.hpp File Reference
VariableDictionary.hpp File Reference
#include "CompoundVariableTable.hpp"
#include "RexxVariable.hpp"
#include "HashContents.hpp"
Classes
class VariableDictionary
class VariableDictionary::VariableIterator
Functions
VariableDictionary * new_variableDictionary (size_t s)
VariableDictionary * new_objectVariableDictionary (RexxClass *s)
Function Documentation
new_objectVariableDictionary()
VariableDictionary* new_objectVariableDictionary (RexxClass * s) inline
Definition at line 236 of file VariableDictionary.hpp.
References VariableDictionary::VariableDictionary().
Referenced by RexxObject::getObjectVariables().
new_variableDictionary()
VariableDictionary* new_variableDictionary (size_t s) inline
Definition at line 235 of file VariableDictionary.hpp.
References VariableDictionary::VariableDictionary().
Referenced by RexxLocalVariables::createDictionary().