ooRexx: ListContents Class Reference
ListContents Class Reference
#include <ListContents.hpp>
Classes
class ListEntry
Public Types
typedef size_t ItemLink
Public Member Functions
void * operator new (size_t, size_t)
void operator delete (void *)
ListContents (RESTORETYPE restoreType)
ListContents ()
ListContents (size_t size)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
void initializeFreeChain ()
void prepareForMerge ()
void completeMerge ()
void mergeInto (ListContents *target)
ItemLink allocateSlot (RexxInternalObject *value)
void insertAtEnd (ItemLink newItem)
void insertAtFront (ItemLink newItem)
void insertAfter (ItemLink newItem, ItemLink insertItem)
void insertBefore (ItemLink newItem, ItemLink insertItem)
ItemLink insert (RexxInternalObject *value, ItemLink index)
ItemLink insertAtBeginning (RexxInternalObject *value)
ItemLink insertAtEnd (RexxInternalObject *value)
void removeItem (ItemLink item)
ItemLink append (RexxInternalObject *value)
void append (ItemLink index, RexxInternalObject *value)
RexxInternalObject * get (ItemLink index)
RexxInternalObject * put (RexxInternalObject *value, ItemLink index)
RexxInternalObject * remove (ItemLink index)
RexxInternalObject * getFirstItem ()
RexxInternalObject * getLastItem ()
ItemLink firstIndex ()
ItemLink lastIndex ()
ItemLink nextIndex (ItemLink item)
ItemLink previousIndex (ItemLink item)
ArrayClass * allItems ()
ArrayClass * allIndexes ()
void empty ()
ItemLink getIndex (RexxInternalObject *target)
bool hasItem (RexxInternalObject *target)
RexxInternalObject * removeItem (RexxInternalObject *target)
SupplierClass * supplier ()
ArrayClass * weakReferenceArray ()
void clearEntry (ItemLink position)
void setNext (ItemLink position, ItemLink next)
void setPrevious (ItemLink position, ItemLink previous)
void clearLinks (ItemLink position)
void copyEntry (ItemLink target, ItemLink source)
void closeChain (ItemLink position, ItemLink previous)
void returnToFreeChain (ItemLink position)
void setValue (ItemLink position, RexxInternalObject *value)
bool isItem (ItemLink position, RexxInternalObject *item)
bool isAvailable (ItemLink postion)
bool isInUse (ItemLink postion)
ItemLink nextEntry (ItemLink position)
ItemLink previousEntry (ItemLink position)
RexxInternalObject * entryValue (ItemLink position)
bool isFull ()
bool hasCapacity (size_t count)
size_t capacity ()
bool isIndexValid (ItemLink i)
size_t items ()
bool isEmpty ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Attributes
static const ItemLink NoMore = SIZE_MAX
static const ItemLink NoLink = SIZE_MAX
static const ItemLink AtEnd = SIZE_MAX
static const ItemLink AtBeginning = SIZE_MAX - 1
Protected Attributes
size_t totalSize
size_t itemCount
ItemLink firstItem
ItemLink lastItem
ItemLink freeChain
ListEntry entries [1]
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 49 of file ListContents.hpp.
Member Typedef Documentation
ItemLink
typedef size_t ListContents::ItemLink
Definition at line 53 of file ListContents.hpp.
Constructor & Destructor Documentation
ListContents() [1/3]
ListContents::ListContents (RESTORETYPE restoreType) inline
Definition at line 77 of file ListContents.hpp.
ListContents() [2/3]
ListContents::ListContents () inline
Definition at line 78 of file ListContents.hpp.
ListContents() [3/3]
ListContents::ListContents (size_t size)
Construct a ListContent item of the given size.
Parameters
size The total number of entries in the object.
Definition at line 72 of file ListContents.cpp.
References RexxInternalObject::clearObject(), firstItem, initializeFreeChain(), lastItem, NoMore, and totalSize.
Member Function Documentation
allIndexes()
ArrayClass * ListContents::allIndexes ()
Get all of the indexes in the list as an array item.
Returns
An array containing all of the indexes.
Definition at line 690 of file ListContents.cpp.
References ArrayClass::append(), firstItem, itemCount, new_array(), new_integer(), nextEntry(), and NoMore.
Referenced by ListClass::allIndexes(), and supplier().
allItems()
ArrayClass * ListContents::allItems ()
Get all of the items in the list as an array item.
Returns
An array containing all of the items.
Definition at line 672 of file ListContents.cpp.
References ArrayClass::append(), entryValue(), firstItem, itemCount, new_array(), nextEntry(), and NoMore.
Referenced by ListClass::allItems(), and supplier().
allocateSlot()
ListContents::ItemLink ListContents::allocateSlot (RexxInternalObject * value)
Allocate a slot for a new value and fill it in.
Parameters
value The value we're inserting.
Returns
The index position for the inserted item.
Definition at line 254 of file ListContents.cpp.
References clearLinks(), freeChain, itemCount, Interpreter::logicError(), nextEntry(), NoMore, and setValue().
Referenced by append(), insert(), insertAtBeginning(), and insertAtEnd().
append() [1/2]
void ListContents::append (ItemLink newItem, RexxInternalObject * value)
Append an item to the list, using a provided index. This is only used during a merge operation.
Parameters
value The value to add.
Returns
The index position of the new item.
Definition at line 433 of file ListContents.cpp.
References insertAtEnd(), itemCount, and setValue().
append() [2/2]
ListContents::ItemLink ListContents::append (RexxInternalObject * value)
Append an item to the list
Parameters
value The value to add.
Returns
The index position of the new item.
Definition at line 416 of file ListContents.cpp.
References allocateSlot(), and insertAtEnd().
Referenced by mergeInto().
capacity()
size_t ListContents::capacity () inline
Return the total current capacity.
Returns
The total number of items this table can hold.
Definition at line 229 of file ListContents.hpp.
References totalSize.
Referenced by ListClass::ensureCapacity(), and ListClass::expandContents().
clearEntry()
void ListContents::clearEntry (ListContents::ItemLink position)
Clear the value from a given entry.
Parameters
position The table position to clear.
Definition at line 731 of file ListContents.cpp.
References clearField, entries, ListContents::ListEntry::next, NoMore, and ListContents::ListEntry::previous.
Referenced by empty(), prepareForMerge(), and returnToFreeChain().
clearLinks()
void ListContents::clearLinks (ItemLink position) inline
Definition at line 126 of file ListContents.hpp.
References NoMore, setNext(), and setPrevious().
Referenced by allocateSlot().
closeChain()
void ListContents::closeChain (ItemLink position, ItemLink previous) inline
Definition at line 143 of file ListContents.hpp.
References entries, ListContents::ListEntry::next, NoMore, ListContents::ListEntry::previous, and returnToFreeChain().
completeMerge()
void ListContents::completeMerge ()
We've completed the merge operation. Now we need to up the unused slots and build a free chain.
Definition at line 147 of file ListContents.cpp.
References freeChain, isAvailable(), NoMore, returnToFreeChain(), and totalSize.
Referenced by mergeInto().
copyEntry()
void ListContents::copyEntry (ItemLink target, ItemLink source) inline
Definition at line 133 of file ListContents.hpp.
References entries, entryValue(), ListContents::ListEntry::next, ListContents::ListEntry::previous, and setValue().
empty()
void ListContents::empty ()
Empty the list of all contents.
Definition at line 706 of file ListContents.cpp.
References clearEntry(), firstItem, initializeFreeChain(), itemCount, lastItem, nextEntry(), and NoMore.
Referenced by ListClass::empty().
entryValue()
RexxInternalObject* ListContents::entryValue (ItemLink position) inline
Definition at line 205 of file ListContents.hpp.
References entries, and ListContents::ListEntry::value.
Referenced by allItems(), copyEntry(), get(), getFirstItem(), getIndex(), getLastItem(), isItem(), mergeInto(), put(), remove(), removeItem(), and weakReferenceArray().
firstIndex()
ListContents::ItemLink ListContents::firstIndex ()
Return the index of the first item in the list.
Returns
The first item index, or NoMore
Definition at line 624 of file ListContents.cpp.
References firstItem.
Referenced by ListClass::firstIndex().
flatten()
void ListContents::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxVirtualBase.
Definition at line 204 of file ListContents.cpp.
References cleanUpFlatten, entries, firstItem, flattenRef, nextEntry(), NoMore, and setUpFlatten.
get()
RexxInternalObject * ListContents::get (ListContents::ItemLink index)
Retrieve an index from the contents.
Parameters
index The index position.
Returns
The associated value.
Definition at line 535 of file ListContents.cpp.
References entryValue(), isIndexValid(), and OREF_NULL.
Referenced by ListClass::get(), and ListClass::section().
getFirstItem()
RexxInternalObject * ListContents::getFirstItem ()
Return the first item in the list.
Returns
The first item, or OREF_NULL if the list is empty.
Definition at line 592 of file ListContents.cpp.
References entryValue(), firstItem, NoMore, and OREF_NULL.
Referenced by ListClass::firstItem().
getIndex()
ListContents::ItemLink ListContents::getIndex (RexxInternalObject * target)
Find the index for a target item.
Parameters
target The target item.
Returns
The index of the located item or NoMore if this cannot be found.
Definition at line 753 of file ListContents.cpp.
References entryValue(), RexxInternalObject::equalValue(), firstItem, nextEntry(), and NoMore.
Referenced by ListClass::getIndex(), and hasItem().
getLastItem()
RexxInternalObject * ListContents::getLastItem ()
Return the last item in the list.
Returns
The last item, or OREF_NULL if the list is empty.
Definition at line 608 of file ListContents.cpp.
References entryValue(), lastItem, NoMore, and OREF_NULL.
Referenced by ListClass::lastItem().
hasCapacity()
bool ListContents::hasCapacity (size_t count) inline
Definition at line 218 of file ListContents.hpp.
References itemCount, and totalSize.
Referenced by ListClass::ensureCapacity().
hasItem()
bool ListContents::hasItem (RexxInternalObject * target)
Test if the collection contains an instance of the given item.
Parameters
target The target item.
Returns
The index of the located item or NoMore if this cannot be found.
Definition at line 775 of file ListContents.cpp.
References getIndex(), and NoMore.
Referenced by ListClass::hasItem(), and ListClass::hasItemRexx().
initializeFreeChain()
void ListContents::initializeFreeChain ()
Initialize the free chains, either at construction time or after an empty() operation.
Definition at line 93 of file ListContents.cpp.
References entries, freeChain, itemCount, ListContents::ListEntry::next, NoMore, and totalSize.
Referenced by empty(), and ListContents().
insert()
ListContents::ItemLink ListContents::insert (RexxInternalObject * value, ListContents::ItemLink index)
Add a value to the list at a given index position.
Parameters
value The value to add.
index The target index postion. NoMore indicates add to the end.
Returns
The index position of the new item.
Definition at line 386 of file ListContents.cpp.
References allocateSlot(), AtBeginning, AtEnd, insertAfter(), insertAtEnd(), and insertAtFront().
Referenced by ListClass::addFirst(), ListClass::addLast(), and ListClass::insert().
insertAfter()
void ListContents::insertAfter (ListContents::ItemLink newItem, ListContents::ItemLink insertItem)
Insert an item after a given list item.
Parameters
newItem The new item we're inserting.
insertItem The item this is inserted after.
Definition at line 330 of file ListContents.cpp.
References lastItem, nextEntry(), NoMore, setNext(), and setPrevious().
Referenced by insert(), and insertAtEnd().
insertAtBeginning()
ListContents::ItemLink ListContents::insertAtBeginning (RexxInternalObject * value)
Add a value to the beginning of the list
Parameters
value The value to add.
Returns
The index position of the new item.
Definition at line 453 of file ListContents.cpp.
References allocateSlot(), and insertAtFront().
insertAtEnd() [1/2]
void ListContents::insertAtEnd (ListContents::ItemLink newItem)
Insert an item at the end of the existing list.
Parameters
newItem The new item we're inserting.
Definition at line 283 of file ListContents.cpp.
References firstItem, insertAfter(), lastItem, and NoMore.
Referenced by ListClass::append(), append(), insert(), and insertAtEnd().
insertAtEnd() [2/2]
ListContents::ItemLink ListContents::insertAtEnd (RexxInternalObject * value)
Add a value to the beginning of the list
Parameters
value The value to add.
Returns
The index position of the new item.
Definition at line 469 of file ListContents.cpp.
References allocateSlot(), and insertAtEnd().
insertAtFront()
void ListContents::insertAtFront (ListContents::ItemLink newItem)
Insert an item at the front of the existing list.
Parameters
newItem The new item we're inserting.
Definition at line 306 of file ListContents.cpp.
References firstItem, insertBefore(), lastItem, and NoMore.
Referenced by insert(), and insertAtBeginning().
insertBefore()
void ListContents::insertBefore (ListContents::ItemLink newItem, ListContents::ItemLink insertItem)
Insert an item before a given list item.
Parameters
newItem The new item we're inserting.
insertItem The item this is inserted before.
Definition at line 357 of file ListContents.cpp.
References firstItem, NoMore, previousEntry(), setNext(), and setPrevious().
Referenced by insertAtFront().
isAvailable()
bool ListContents::isAvailable (ItemLink postion) inline
Definition at line 181 of file ListContents.hpp.
References entries, and ListContents::ListEntry::isAvailable().
Referenced by completeMerge().
isEmpty()
bool ListContents::isEmpty () inline
Definition at line 241 of file ListContents.hpp.
References itemCount.
Referenced by ListClass::isEmpty().
isFull()
bool ListContents::isFull () inline
Definition at line 211 of file ListContents.hpp.
References freeChain, and NoMore.
Referenced by ListClass::checkFull().
isIndexValid()
bool ListContents::isIndexValid (ItemLink i) inline
Definition at line 235 of file ListContents.hpp.
References isInUse(), and totalSize.
Referenced by get(), ListClass::hasIndex(), put(), and ListClass::validateIndex().
isInUse()
bool ListContents::isInUse (ItemLink postion) inline
Definition at line 187 of file ListContents.hpp.
References entries, and ListContents::ListEntry::isInUse().
Referenced by isIndexValid().
isItem()
bool ListContents::isItem (ItemLink position, RexxInternalObject * item) inline
Definition at line 174 of file ListContents.hpp.
References entryValue(), and RexxInternalObject::isEqual().
items()
size_t ListContents::items () inline
Definition at line 240 of file ListContents.hpp.
References itemCount.
Referenced by ListClass::items(), and weakReferenceArray().
lastIndex()
ListContents::ItemLink ListContents::lastIndex ()
Return the index of the last item in the list.
Returns
The last item index, or NoMore if the list is empty
Definition at line 635 of file ListContents.cpp.
References lastItem.
Referenced by ListClass::lastIndex().
live()
void ListContents::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 174 of file ListContents.cpp.
References entries, firstItem, memory_mark, nextEntry(), and NoMore.
liveGeneral()
void ListContents::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 189 of file ListContents.cpp.
References entries, firstItem, memory_mark_general, nextEntry(), and NoMore.
mergeInto()
void ListContents::mergeInto (ListContents * target)
Merge the list maintained in this contents object into a target one after an expansion has occurred. Note that this is a little complicated, because we need to maintain the relationship between items are their current indexes.
Parameters
target The target contents.
Definition at line 226 of file ListContents.cpp.
References append(), completeMerge(), entryValue(), firstItem, nextEntry(), NoMore, and prepareForMerge().
Referenced by ListClass::expandContents().
nextEntry()
ItemLink ListContents::nextEntry (ItemLink position) inline
Definition at line 193 of file ListContents.hpp.
References entries, and ListContents::ListEntry::next.
Referenced by allIndexes(), allItems(), allocateSlot(), empty(), flatten(), getIndex(), insertAfter(), live(), liveGeneral(), mergeInto(), nextIndex(), removeItem(), and weakReferenceArray().
nextIndex()
ListContents::ItemLink ListContents::nextIndex (ListContents::ItemLink item)
Get the index of the next item after a target item.
Parameters
item The item index.
Returns
The next item. NoMore indicates there is no next item.
Definition at line 648 of file ListContents.cpp.
References nextEntry(), and NoMore.
Referenced by ListClass::nextIndex(), and ListClass::section().
operator delete()
void ListContents::operator delete (void *) inline
Definition at line 75 of file ListContents.hpp.
operator new()
void * ListContents::operator new (size_t size, size_t initialSize)
Allocate memory for a new ListContents entry.
Parameters
size The base object size.
initialSize The initial number of entries
Returns
The storage for a new table object.
Definition at line 61 of file ListContents.cpp.
References new_object(), and T_ListContents.
prepareForMerge()
void ListContents::prepareForMerge ()
We're merging a list contents into this collection after an expansion. We need to take care to keep the same index values for each of the inserted items. We cleare out all slot positions, then rebuild the chains using the same positions as the original. Once the merge is complete, then we rescan the table for free entries and rebuild the table.
Definition at line 122 of file ListContents.cpp.
References clearEntry(), firstItem, freeChain, itemCount, lastItem, NoMore, and totalSize.
Referenced by mergeInto().
previousEntry()
ItemLink ListContents::previousEntry (ItemLink position) inline
Definition at line 199 of file ListContents.hpp.
References entries, and ListContents::ListEntry::previous.
Referenced by insertBefore(), previousIndex(), and removeItem().
previousIndex()
ListContents::ItemLink ListContents::previousIndex (ListContents::ItemLink item)
Get the index of the item before a given index.
Parameters
item The target item.
Returns
The item index, or NoMore if there is not valid previous item.
Definition at line 661 of file ListContents.cpp.
References NoMore, and previousEntry().
Referenced by ListClass::previousIndex().
put()
RexxInternalObject * ListContents::put (RexxInternalObject * value, ListContents::ItemLink index)
Perform a PUT() operation on an existing index, replacing the existing value.
Parameters
value The new value
index The index position.
Returns
The old value or OREF_NULL if this is not a valid index.
Definition at line 550 of file ListContents.cpp.
References entryValue(), isIndexValid(), OREF_NULL, and setValue().
Referenced by ListClass::put().
remove()
RexxInternalObject * ListContents::remove (ItemLink index)
Remove an item from the list at a given index.
Parameters
index The target index.
Returns
The removed item, if any.
Definition at line 570 of file ListContents.cpp.
References entryValue(), NoLink, OREF_NULL, and removeItem().
Referenced by ListClass::remove().
removeItem() [1/2]
void ListContents::removeItem (ListContents::ItemLink item)
Remove an item postion from the chain and return the location to the free chain.
Parameters
item The item position to remove.
Definition at line 484 of file ListContents.cpp.
References firstItem, itemCount, lastItem, nextEntry(), NoMore, previousEntry(), returnToFreeChain(), setNext(), and setPrevious().
Referenced by remove(), ListClass::removeItem(), removeItem(), and weakReferenceArray().
removeItem() [2/2]
RexxInternalObject * ListContents::removeItem (RexxInternalObject * target)
Remove an item from the collection.
Parameters
target The target item.
Returns
The actual stored object value.
Definition at line 788 of file ListContents.cpp.
References entryValue(), RexxInternalObject::equalValue(), firstItem, nextEntry(), NoMore, OREF_NULL, and removeItem().
returnToFreeChain()
void ListContents::returnToFreeChain (ItemLink position) inline
Definition at line 160 of file ListContents.hpp.
References clearEntry(), entries, freeChain, and ListContents::ListEntry::next.
Referenced by closeChain(), completeMerge(), and removeItem().
setNext()
void ListContents::setNext (ItemLink position, ItemLink next) inline
Definition at line 124 of file ListContents.hpp.
References entries, and ListContents::ListEntry::next.
Referenced by clearLinks(), insertAfter(), insertBefore(), and removeItem().
setPrevious()
void ListContents::setPrevious (ItemLink position, ItemLink previous) inline
Definition at line 125 of file ListContents.hpp.
References entries, and ListContents::ListEntry::previous.
Referenced by clearLinks(), insertAfter(), insertBefore(), and removeItem().
setValue()
void ListContents::setValue (ListContents::ItemLink position, RexxInternalObject * value)
Definition at line 740 of file ListContents.cpp.
References entries, and setField.
Referenced by allocateSlot(), append(), copyEntry(), and put().
supplier()
SupplierClass * ListContents::supplier ()
Create a supplier for the collection.
Returns
A supplier for iterating over the collection.
Definition at line 809 of file ListContents.cpp.
References allIndexes(), allItems(), and new_supplier().
Referenced by ListClass::supplier().
weakReferenceArray()
ArrayClass * ListContents::weakReferenceArray ()
Not really part of normal list operation, but classes maintain their subclasses as a list of weak references so that subclasses can get garbage collected when no longer needed. When the class needs to iterate over the subclasses, it needs to resolve which weak references are still valid. This method will check the weak references and remove any stale entries. Then it will return an array of the dereferenced objects.
Returns
An array of the dereferenced objects.
Definition at line 829 of file ListContents.cpp.
References entryValue(), firstItem, WeakReference::get(), WeakReference::hasReferent(), items(), nextEntry(), NoMore, and removeItem().
Referenced by ListClass::weakReferenceArray().
Member Data Documentation
AtBeginning
const ItemLink ListContents::AtBeginning = SIZE_MAX - 1 static
Definition at line 62 of file ListContents.hpp.
Referenced by ListClass::addFirst(), insert(), and ListClass::validateInsertionIndex().
AtEnd
const ItemLink ListContents::AtEnd = SIZE_MAX static
Definition at line 60 of file ListContents.hpp.
Referenced by ListClass::addLast(), insert(), and ListClass::validateInsertionIndex().
entries
ListEntry ListContents::entries[1] protected
Definition at line 250 of file ListContents.hpp.
Referenced by clearEntry(), closeChain(), copyEntry(), entryValue(), flatten(), initializeFreeChain(), isAvailable(), isInUse(), live(), liveGeneral(), nextEntry(), previousEntry(), returnToFreeChain(), setNext(), setPrevious(), and setValue().
firstItem
ItemLink ListContents::firstItem protected
Definition at line 247 of file ListContents.hpp.
Referenced by allIndexes(), allItems(), empty(), firstIndex(), flatten(), getFirstItem(), getIndex(), insertAtEnd(), insertAtFront(), insertBefore(), ListContents(), live(), liveGeneral(), mergeInto(), prepareForMerge(), removeItem(), and weakReferenceArray().
freeChain
ItemLink ListContents::freeChain protected
Definition at line 249 of file ListContents.hpp.
Referenced by allocateSlot(), completeMerge(), initializeFreeChain(), isFull(), prepareForMerge(), and returnToFreeChain().
itemCount
size_t ListContents::itemCount protected
Definition at line 246 of file ListContents.hpp.
Referenced by allIndexes(), allItems(), allocateSlot(), append(), empty(), hasCapacity(), initializeFreeChain(), isEmpty(), items(), prepareForMerge(), and removeItem().
lastItem
ItemLink ListContents::lastItem protected
Definition at line 248 of file ListContents.hpp.
Referenced by empty(), getLastItem(), insertAfter(), insertAtEnd(), insertAtFront(), lastIndex(), ListContents(), prepareForMerge(), and removeItem().
NoLink
const ItemLink ListContents::NoLink = SIZE_MAX static
Definition at line 58 of file ListContents.hpp.
Referenced by remove(), ListClass::requiredIndex(), and ListClass::validateIndex().
NoMore
const ItemLink ListContents::NoMore = SIZE_MAX static
Definition at line 56 of file ListContents.hpp.
Referenced by allIndexes(), allItems(), allocateSlot(), clearEntry(), clearLinks(), closeChain(), completeMerge(), empty(), flatten(), getFirstItem(), getIndex(), getLastItem(), hasItem(), ListClass::indexObject(), initializeFreeChain(), insertAfter(), insertAtEnd(), insertAtFront(), insertBefore(), isFull(), ListContents(), live(), liveGeneral(), mergeInto(), nextIndex(), prepareForMerge(), previousIndex(), removeItem(), ListClass::section(), and weakReferenceArray().
totalSize
size_t ListContents::totalSize protected
Definition at line 245 of file ListContents.hpp.
Referenced by capacity(), completeMerge(), hasCapacity(), initializeFreeChain(), isIndexValid(), ListContents(), and prepareForMerge().
The documentation for this class was generated from the following files:
ListContents.hpp
ListContents.cpp