ooRexx: RegisteredRoutine Class Reference
RegisteredRoutine Class Reference
#include <NativeCode.hpp>
Public Member Functions
void * operator new (size_t size)
void operator delete (void *)
RegisteredRoutine (RESTORETYPE restoreType)
RegisteredRoutine (RexxString *n, RexxRoutineHandler *e)
RegisteredRoutine (RexxString *p, RexxString *n, RexxRoutineHandler *e)
void liveGeneral (MarkReason reason) override
void flatten (Envelope *envelope) override
void call (Activity *, RoutineClass *, RexxString *, RexxObject **, size_t, ProtectedObject &) override
RexxRoutineHandler * getEntry ()
Public Member Functions inherited from BaseNativeRoutine
BaseNativeRoutine ()
BaseNativeRoutine (RexxString *p, RexxString *n)
Public Member Functions inherited from NativeCode
NativeCode ()
NativeCode (RexxString *p, RexxString *n)
void live (size_t) override
BaseCode * setPackageObject (PackageClass *s) override
SecurityManager * getSecurityManager ()
Public Member Functions inherited from BaseCode
virtual void run (Activity *, MethodClass *, RexxObject *, RexxString *, RexxObject **, size_t, ProtectedObject &)
virtual void call (Activity *, RoutineClass *, RexxString *, RexxObject **, size_t, RexxString *, RexxString *, ActivationContext, ProtectedObject &)
virtual ArrayClass * getSource ()
virtual RexxObject * setSecurityManager (RexxObject *manager)
virtual PackageClass * getPackageObject ()
virtual RexxClass * findClass (RexxString *className)
virtual PackageClass * getPackage ()
bool isSamePackage (PackageClass *p)
ProgramSource * detachSource ()
void attachSource (ProgramSource *)
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Protected Attributes
RexxRoutineHandler * entry
Protected Attributes inherited from NativeCode
RexxString * packageName
RexxString * name
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from BaseCode
PackageClass * package
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
A legacy-style external routine.
Definition at line 142 of file NativeCode.hpp.
Constructor & Destructor Documentation
RegisteredRoutine() [1/3]
RegisteredRoutine::RegisteredRoutine (RESTORETYPE restoreType) inline
Definition at line 148 of file NativeCode.hpp.
RegisteredRoutine() [2/3]
RegisteredRoutine::RegisteredRoutine (RexxString * n, RexxRoutineHandler * e) inline
Definition at line 149 of file NativeCode.hpp.
RegisteredRoutine() [3/3]
RegisteredRoutine::RegisteredRoutine (RexxString * p, RexxString * n, RexxRoutineHandler * e) inline
Definition at line 150 of file NativeCode.hpp.
Member Function Documentation
call()
void RegisteredRoutine::call (Activity * activity, RoutineClass * routine, RexxString * functionName, RexxObject ** argPtr, size_t count, ProtectedObject & result) override virtual
Run a method call (vs a straight program call).
Parameters
activity The current activity.
functionName The name of the message used to invoke the method.
count The count of arguments.
argPtr The pointer to the arguments.
result The protected object used to return the result.
Reimplemented from BaseCode.
Definition at line 369 of file NativeCode.cpp.
References NativeActivation::callRegisteredRoutine(), NativeCode::name, ActivityManager::newNativeActivation(), NativeCode::packageName, Activity::pushStackFrame(), and PackageManager::resolveRegisteredRoutineEntry().
flatten()
void RegisteredRoutine::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from NativeCode.
Definition at line 291 of file NativeCode.cpp.
References cleanUpFlatten, NativeCode::flatten(), and setUpFlatten.
getEntry()
RexxRoutineHandler* RegisteredRoutine::getEntry () inline
Definition at line 157 of file NativeCode.hpp.
References entry.
Referenced by NativeActivation::callRegisteredRoutine().
liveGeneral()
void RegisteredRoutine::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from NativeCode.
Definition at line 275 of file NativeCode.cpp.
References NativeCode::liveGeneral(), and SAVINGIMAGE.
operator delete()
void RegisteredRoutine::operator delete (void *) inline
Definition at line 146 of file NativeCode.hpp.
operator new()
void * RegisteredRoutine::operator new (size_t size)
Allocate memory for a new native routine.
Parameters
size The size of the object.
Returns
Storage for the new object.
Definition at line 264 of file NativeCode.cpp.
References new_object(), and T_RegisteredRoutine.
Member Data Documentation
entry
RexxRoutineHandler* RegisteredRoutine::entry protected
Definition at line 161 of file NativeCode.hpp.
Referenced by getEntry().
The documentation for this class was generated from the following files:
NativeCode.hpp
NativeCode.cpp