ooRexx: SysFileIterator Class Reference
SysFileIterator Class Reference
#include <SysFileSystem.hpp>
Classes
class FileAttributes
Public Member Functions
SysFileIterator (const char *path, const char *pattern, FileNameBuffer &buffer, bool c=false)
~SysFileIterator ()
void close ()
bool hasNext ()
void next (FileNameBuffer &buffer, FileAttributes &attributes)
SysFileIterator (const char *path, const char *pattern, FileNameBuffer &buffer, bool c=false)
~SysFileIterator ()
void close ()
bool hasNext ()
void next (FileNameBuffer &buffer, FileAttributes &attributes)
Protected Member Functions
void findNextEntry ()
void findNextEntry ()
void filterShortNames ()
Protected Attributes
bool completed
const char * directory
struct dirent * entry
struct stat64 findFileData
DIR * handle
bool caseLess
const char * patternSpec
const char * fileSpec
HANDLE handle
WIN32_FIND_DATA findFileData
Detailed Description
Definition at line 156 of file unix/SysFileSystem.hpp.
Constructor & Destructor Documentation
SysFileIterator() [1/2]
SysFileIterator::SysFileIterator (const char * path, const char * pattern, FileNameBuffer & buffer, bool c = false)
Create a new SysFileIterator instance.
Parameters
path The path we're going to be searching in
pattern The pattern to use. If NULL, then everything in the path will be returned.
buffer A FileNameBuffer object used to construct the path name.
Create a new SysFileIterator instance.
Parameters
path The path we're going to be searching in
pattern The pattern to use. If NULL, then everything in the path will be returned.
buffer A FileNameBuffer object used to construct the path name.
c the caseless flag (ignored for Windows)
Definition at line 1855 of file unix/SysFileSystem.cpp.
References caseLess, completed, directory, findNextEntry(), handle, SysFileSystem::isCaseSensitive(), patternSpec, and Utilities::strupper().
~SysFileIterator() [1/2]
SysFileIterator::~SysFileIterator ()
Destructor for the iteration operation.
Definition at line 1899 of file unix/SysFileSystem.cpp.
References close().
SysFileIterator() [2/2]
SysFileIterator::SysFileIterator (const char * path, const char * pattern, FileNameBuffer & buffer, bool c = false)
~SysFileIterator() [2/2]
SysFileIterator::~SysFileIterator ()
Member Function Documentation
close() [1/2]
void SysFileIterator::close ()
close the iterator.
Definition at line 1908 of file unix/SysFileSystem.cpp.
References caseLess, handle, and patternSpec.
Referenced by filterShortNames(), findNextEntry(), TreeFinder::recursiveFindFile(), and ~SysFileIterator().
close() [2/2]
void SysFileIterator::close ()
filterShortNames()
void SysFileIterator::filterShortNames () protected
Perform filtering on false hits due to short file name matching problems.
Definition at line 1573 of file windows/SysFileSystem.cpp.
References close(), completed, fileSpec, findFileData, and handle.
findNextEntry() [1/2]
void SysFileIterator::findNextEntry () protected
Scan forward through the directory to find the next matching entry.
Returns
true if a matching entry was found, false for any error or nothign found.
Definition at line 1965 of file unix/SysFileSystem.cpp.
References caseLess, close(), completed, directory, entry, findFileData, handle, patternSpec, and Utilities::strupper().
Referenced by next(), and SysFileIterator().
findNextEntry() [2/2]
void SysFileIterator::findNextEntry () protected
hasNext() [1/2]
bool SysFileIterator::hasNext ()
Check if the iterator has new results it can return.
Returns
true if the iterator has another value to return, false if the iteration is complete.
Definition at line 1932 of file unix/SysFileSystem.cpp.
References completed.
Referenced by TreeFinder::recursiveFindFile(), and RexxMethod1().
hasNext() [2/2]
bool SysFileIterator::hasNext ()
next() [1/2]
void SysFileIterator::next (FileNameBuffer & buffer, SysFileIterator::FileAttributes & attributes)
Retrieve the next iteration value.
Parameters
buffer The buffer used to return the value.
attributes The returned system-dependent attributes of the next file.
Definition at line 1944 of file unix/SysFileSystem.cpp.
References completed, entry, SysFileIterator::FileAttributes::findFileData, findFileData, and findNextEntry().
Referenced by TreeFinder::recursiveFindFile(), and RexxMethod1().
next() [2/2]
void SysFileIterator::next (FileNameBuffer & buffer, FileAttributes & attributes)
Member Data Documentation
caseLess
bool SysFileIterator::caseLess protected
Definition at line 191 of file unix/SysFileSystem.hpp.
Referenced by close(), findNextEntry(), and SysFileIterator().
completed
bool SysFileIterator::completed protected
Definition at line 186 of file unix/SysFileSystem.hpp.
Referenced by filterShortNames(), findNextEntry(), hasNext(), next(), and SysFileIterator().
directory
const char* SysFileIterator::directory protected
Definition at line 187 of file unix/SysFileSystem.hpp.
Referenced by findNextEntry(), and SysFileIterator().
entry
struct dirent* SysFileIterator::entry protected
Definition at line 188 of file unix/SysFileSystem.hpp.
Referenced by findNextEntry(), and next().
fileSpec
const char* SysFileIterator::fileSpec protected
Definition at line 167 of file windows/SysFileSystem.hpp.
Referenced by filterShortNames().
findFileData [1/2]
struct stat64 SysFileIterator::findFileData protected
Definition at line 188 of file unix/SysFileSystem.hpp.
Referenced by filterShortNames(), findNextEntry(), and next().
findFileData [2/2]
WIN32_FIND_DATA SysFileIterator::findFileData protected
Definition at line 171 of file windows/SysFileSystem.hpp.
handle [1/2]
DIR* SysFileIterator::handle protected
Definition at line 190 of file unix/SysFileSystem.hpp.
Referenced by close(), filterShortNames(), findNextEntry(), and SysFileIterator().
handle [2/2]
HANDLE SysFileIterator::handle protected
Definition at line 169 of file windows/SysFileSystem.hpp.
patternSpec
const char* SysFileIterator::patternSpec protected
Definition at line 192 of file unix/SysFileSystem.hpp.
Referenced by close(), findNextEntry(), and SysFileIterator().
The documentation for this class was generated from the following files:
unix/SysFileSystem.hpp
windows/SysFileSystem.hpp
unix/SysFileSystem.cpp
windows/SysFileSystem.cpp