ooRexx: MemorySegmentSet Class Reference
MemorySegmentSet Class Reference
#include <MemorySegment.hpp>
Public Types
enum SegmentSetID {
SET_UNINITIALIZED , SET_NORMAL , SET_LARGEBLOCK , SET_OLDSPACE ,
SET_SINGLEOBJECT
}
Public Member Functions
MemorySegmentSet (MemoryObject *memObject, SegmentSetID id, const char *setName)
MemorySegmentSet ()
virtual ~MemorySegmentSet ()
void removeSegment (MemorySegment *segment)
void removeSegmentAndStorage (MemorySegment *segment)
void add (MemorySegment *segment)
MemorySegment * first ()
MemorySegment * next (MemorySegment *segment)
void transferSegment (MemorySegment *segment)
void dumpSegments (FILE *keyfile, FILE *dumpfile)
void addSegment (MemorySegment *segment)
void sweep ()
void sweepSingleSegment (MemorySegment *sweepSegment)
bool is (SegmentSetID id)
void gatherStats (MemoryStats *memStats, SegmentStats *stats)
MemorySegment * largestActiveSegment ()
virtual void dumpMemoryProfile (FILE *outfile)
virtual DeadObject * donateObject (size_t allocationLength)
Static Public Attributes
static const size_t MinimumSegmentSize = (MemorySegment::SegmentSize/2)
static const size_t MinimumSegmentDeadSpace = (MinimumSegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentSize = (MemorySegment::SegmentSize * 4)
static const size_t SegmentDeadSpace = (MemorySegment::SegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentDeadSpace = (LargeSegmentSize - MemorySegment::MemorySegmentOverhead)
Protected Member Functions
virtual void addDeadObject (DeadObject *object)
virtual void addDeadObject (char *object, size_t length)
RexxInternalObject * splitDeadObject (DeadObject *object, size_t allocationLength, size_t splitMinimum)
void insertSegment (MemorySegment *segment)
virtual size_t suggestMemoryExpansion ()
virtual void prepareForSweep ()
virtual void completeSweepOperation ()
void adjustMemorySize ()
bool newSegment (size_t requestLength, size_t minimumLength)
virtual MemorySegment * allocateSegment (size_t requestLength, size_t minimumLength)
float freeMemoryPercentage ()
size_t totalFreeMemory ()
size_t calculateSegmentAllocation (size_t n)
void addSegments (size_t requiredSpace)
void validateObject (RexxInternalObject *o)
Protected Attributes
MemorySegment anchor
size_t count
size_t liveObjectBytes
size_t deadObjectBytes
SegmentSetID owner
const char * name
MemoryObject * memory
Friends
class MemoryObject
Detailed Description
Definition at line 173 of file MemorySegment.hpp.
Member Enumeration Documentation
SegmentSetID
enum MemorySegmentSet::SegmentSetID
Enumerator
SET_UNINITIALIZED
SET_NORMAL
SET_LARGEBLOCK
SET_OLDSPACE
SET_SINGLEOBJECT
Definition at line 178 of file MemorySegment.hpp.
Constructor & Destructor Documentation
MemorySegmentSet() [1/2]
MemorySegmentSet::MemorySegmentSet (MemoryObject * memObject, SegmentSetID id, const char * setName) inline
Definition at line 180 of file MemorySegment.hpp.
References count, memory, name, and owner.
MemorySegmentSet() [2/2]
MemorySegmentSet::MemorySegmentSet () inline
Definition at line 191 of file MemorySegment.hpp.
References count, memory, owner, and SET_UNINITIALIZED.
~MemorySegmentSet()
virtual MemorySegmentSet::~MemorySegmentSet () inline virtual
Definition at line 200 of file MemorySegment.hpp.
Member Function Documentation
add()
void MemorySegmentSet::add (MemorySegment * segment) inline
Definition at line 221 of file MemorySegment.hpp.
References anchor, count, and MemorySegment::insertBefore().
addDeadObject() [1/2]
void MemorySegmentSet::addDeadObject (char * object, size_t length) protected virtual
Add a block of storage to the dead object chains
Parameters
object The pointer to the start of the object.
length The length of the object.
Reimplemented in NormalSegmentSet, LargeSegmentSet, SingleObjectSegmentSet, and OldSpaceSegmentSet.
Definition at line 459 of file MemorySegment.cpp.
addDeadObject() [2/2]
void MemorySegmentSet::addDeadObject (DeadObject * object) protected virtual
Add a dead object to the segment set.
Parameters
object The newly swept up dead object.
Reimplemented in NormalSegmentSet, LargeSegmentSet, SingleObjectSegmentSet, and OldSpaceSegmentSet.
Definition at line 372 of file MemorySegment.cpp.
Referenced by addSegment(), MemoryObject::scavengeSegmentSets(), splitDeadObject(), and sweepSingleSegment().
addSegment()
void MemorySegmentSet::addSegment (MemorySegment * segment)
Add a segment to the segment pool.
Parameters
segment The new segment to insert
Definition at line 549 of file MemorySegment.cpp.
References addDeadObject(), anchor, MemorySegment::createDeadObject(), MemorySegment::insertBefore(), line_end, memory, name, MemorySegmentHeader::next, MemorySegment::size(), and MemoryObject::verboseMessage().
Referenced by addSegments(), NormalSegmentSet::handleAllocationFailure(), and newSegment().
addSegments()
void MemorySegmentSet::addSegments (size_t requiredSpace) protected
Add segments to the segment set until the required space is achieved or we've had a real memory failure. Our preference is to add this in one chunk, but we'll subdivide down to smaller units as long as we're still getting the segments we require.
Parameters
requiredSpace The required total memory we need.
Definition at line 761 of file MemorySegment.cpp.
References addSegment(), allocateSegment(), calculateSegmentAllocation(), LargeSegmentDeadSpace, SegmentDeadSpace, and MemorySegment::size().
Referenced by adjustMemorySize(), and NormalSegmentSet::handleAllocationFailure().
adjustMemorySize()
void MemorySegmentSet::adjustMemorySize () protected
Decide if we should add segments from the segment set based on the current state of the heap immediately following a sweep. We want to avoid thrashing the garbage collector because of chronic low memory conditions. If we wait until we get an actual allocation failure, we will end up in a state where we're constantly running a mark-and-sweep to reclaim just a tiny amount of storage, and then repeat. We will try to keep the heap with appropriate free space limits.
Definition at line 736 of file MemorySegment.cpp.
References addSegments(), line_end, memory, name, suggestMemoryExpansion(), and MemoryObject::verboseMessage().
Referenced by NormalSegmentSet::handleAllocationFailure(), and LargeSegmentSet::handleAllocationFailure().
allocateSegment()
MemorySegment * MemorySegmentSet::allocateSegment (size_t requestLength, size_t minimumLength) protected virtual
Allocate a segment...designed for subclass overrides to provide specialized handling.
Parameters
requestLength The requested segment size.
minimumLength The minimum segment size we can take as a fall back
Returns
A newly allocated memory segment or NULL if there is an allocation failure.
Reimplemented in LargeSegmentSet, and SingleObjectSegmentSet.
Definition at line 302 of file MemorySegment.cpp.
References memory, and MemoryObject::newSegment().
Referenced by addSegments(), and newSegment().
calculateSegmentAllocation()
size_t MemorySegmentSet::calculateSegmentAllocation (size_t n) inline protected
Definition at line 291 of file MemorySegment.hpp.
References MemorySegment::MemorySegmentOverhead, MemorySegment::roundSegmentBoundary(), and MemorySegment::SegmentSize.
Referenced by addSegments().
completeSweepOperation()
void MemorySegmentSet::completeSweepOperation () protected virtual
Handle all segment set post sweep activities.
Reimplemented in NormalSegmentSet, LargeSegmentSet, and SingleObjectSegmentSet.
Definition at line 847 of file MemorySegment.cpp.
Referenced by sweep().
donateObject()
DeadObject * MemorySegmentSet::donateObject (size_t allocationLength) virtual
Search the cache of dead objects for an object of sufficient size to fulfill this request. For the default implementation, we always return NULL. Different segment sets may have different strategies for determining which block is most suitable for donation.
Parameters
allocationLength The size of the object needed.
Returns
Either a pointer to a dead object or NULL if none are available in the size required.
Reimplemented in NormalSegmentSet, and LargeSegmentSet.
Definition at line 595 of file MemorySegment.cpp.
Referenced by MemoryObject::scavengeSegmentSets().
dumpMemoryProfile()
void MemorySegmentSet::dumpMemoryProfile (FILE * outfile) virtual
Dump profile informaton about a segment set (empty for base class)
Parameters
outfile The profile output file.
Reimplemented in NormalSegmentSet, LargeSegmentSet, and SingleObjectSegmentSet.
Definition at line 130 of file MemorySegment.cpp.
dumpSegments()
void MemorySegmentSet::dumpSegments (FILE * keyfile, FILE * dumpfile)
Dump information about the each of the segments
Parameters
keyfile The keyfile for the output
dumpfile The dumpfile for dump information.
Definition at line 113 of file MemorySegment.cpp.
References counter(), first(), name, and next().
first()
MemorySegment* MemorySegmentSet::first () inline
Definition at line 227 of file MemorySegment.hpp.
References anchor, MemorySegment::isReal(), and MemorySegmentHeader::next.
Referenced by SingleObjectSegmentSet::completeSweepOperation(), dumpSegments(), gatherStats(), OldSpaceSegmentSet::markOldSpaceObjects(), and sweep().
freeMemoryPercentage()
float MemorySegmentSet::freeMemoryPercentage () inline protected
Definition at line 287 of file MemorySegment.hpp.
References deadObjectBytes, and liveObjectBytes.
Referenced by NormalSegmentSet::suggestMemoryExpansion(), and LargeSegmentSet::suggestMemoryExpansion().
gatherStats()
void MemorySegmentSet::gatherStats (MemoryStats * memStats, SegmentStats * stats)
Accumulate memory statistics for a segment
Parameters
memStats Gather current statistics from each memory segment.
stats
Definition at line 1450 of file MemorySegment.cpp.
References count, SegmentStats::count, first(), MemorySegment::gatherObjectStats(), SegmentStats::largestSegment, next(), MemorySegment::size(), and SegmentStats::smallestSegment.
Referenced by MemoryObject::dumpImageStats().
insertSegment()
void MemorySegmentSet::insertSegment (MemorySegment * segment) protected
is()
bool MemorySegmentSet::is (SegmentSetID id) inline
Definition at line 257 of file MemorySegment.hpp.
References owner.
Referenced by MemoryObject::scavengeSegmentSets().
largestActiveSegment()
MemorySegment * MemorySegmentSet::largestActiveSegment ()
Find the largest segment in the segment set.
Returns
The largest segment in the set (this assumes the segment set has at least one allocated segment).
Definition at line 1404 of file MemorySegment.cpp.
References anchor, MemorySegment::isReal(), MemorySegmentHeader::next, and MemorySegment::size().
newSegment()
bool MemorySegmentSet::newSegment (size_t requestLength, size_t minimumLength) protected
Allocate a segment and add it to the segment pool
Parameters
requestLength The length requested.
minimumLength A minimum acceptable length
Returns
true if the allocation succeeded, false otherwise. If allocated, this is also added to the segment set memory pool.
Definition at line 353 of file MemorySegment.cpp.
References addSegment(), and allocateSegment().
Referenced by OldSpaceSegmentSet::allocateObject(), LargeSegmentSet::expandSegmentSet(), NormalSegmentSet::getInitialSet(), and LargeSegmentSet::getInitialSet().
next()
MemorySegment* MemorySegmentSet::next (MemorySegment * segment) inline
Definition at line 239 of file MemorySegment.hpp.
References MemorySegment::isReal(), and MemorySegmentHeader::next.
Referenced by SingleObjectSegmentSet::completeSweepOperation(), dumpSegments(), gatherStats(), OldSpaceSegmentSet::markOldSpaceObjects(), and sweep().
prepareForSweep()
void MemorySegmentSet::prepareForSweep () protected virtual
Reimplemented in NormalSegmentSet, and LargeSegmentSet.
Definition at line 803 of file MemorySegment.cpp.
References deadObjectBytes, and liveObjectBytes.
Referenced by NormalSegmentSet::prepareForSweep(), LargeSegmentSet::prepareForSweep(), and sweep().
removeSegment()
void MemorySegmentSet::removeSegment (MemorySegment * segment) inline
Definition at line 205 of file MemorySegment.hpp.
References count, and MemorySegment::remove().
removeSegmentAndStorage()
void MemorySegmentSet::removeSegmentAndStorage (MemorySegment * segment) inline
Definition at line 213 of file MemorySegment.hpp.
References count, and MemorySegment::removeAll().
splitDeadObject()
RexxInternalObject * MemorySegmentSet::splitDeadObject (DeadObject * object, size_t allocationLength, size_t splitMinimum) protected
Process a dead object and potentially split the object into an allocated object and a second dead object that will be added back into the appropriate pool of dead objects.
Parameters
object The object to split.
allocationLength The front length we require, already rounded to the appropriate grain size.
splitMinimum The minimum required length for the back object. If the trailing portion is short than this, then the original dead object is left the same size.
Returns
The split off real object.
Definition at line 1056 of file MemorySegment.cpp.
References addDeadObject(), and RexxInternalObject::getObjectSize().
Referenced by LargeSegmentSet::allocateObject(), NormalSegmentSet::findLargeDeadObject(), and OldSpaceSegmentSet::findObject().
suggestMemoryExpansion()
size_t MemorySegmentSet::suggestMemoryExpansion () protected virtual
Decide if we should add additional segments to the normal heap based on the amount of free space we have after a garbage collection. If we're starting to run full, then we should expand the heap to prevent recycling the garbage collector to reclaim minimal amounts of storage that is immediately reused, causing another GC cycle.
Returns
A recommended expansion size.
Reimplemented in NormalSegmentSet, and LargeSegmentSet.
Definition at line 650 of file MemorySegment.cpp.
Referenced by adjustMemorySize().
sweep()
void MemorySegmentSet::sweep ()
Perform a sweep of all segments controlled by this segment set.
Definition at line 951 of file MemorySegment.cpp.
References completeSweepOperation(), first(), MemoryObject::markWord, memoryObject, next(), prepareForSweep(), and sweepSingleSegment().
Referenced by MemoryObject::collect().
sweepSingleSegment()
void MemorySegmentSet::sweepSingleSegment (MemorySegment * sweepSegment)
Sweep a single memory segment and return the dead objects to the segment set dead object cache for reuse.
Parameters
sweepSegment The segment to sweep.
Definition at line 980 of file MemorySegment.cpp.
References addDeadObject(), deadObjectBytes, MemorySegment::endObject(), RexxInternalObject::getObjectSize(), RexxInternalObject::isObjectDead(), RexxInternalObject::isObjectLive(), liveObjectBytes, MemorySegmentHeader::liveObjects, MemoryObject::markWord, memoryObject, RexxInternalObject::nextObject(), MemorySegment::startObject(), and validateObject().
Referenced by sweep(), and transferSegment().
totalFreeMemory()
size_t MemorySegmentSet::totalFreeMemory () inline protected
Definition at line 288 of file MemorySegment.hpp.
References deadObjectBytes, and liveObjectBytes.
transferSegment()
void MemorySegmentSet::transferSegment (MemorySegment * segment)
Accept transfer of a memory segment from another segment set. This occurs at the end of the sweep phase, so we will add the segment to our list and then perform a sweep on it to add the dead storage to our chains. Normally this segment will have just one live object and one large dead object.
Parameters
segment The segment to transfer.
Definition at line 572 of file MemorySegment.cpp.
References anchor, MemorySegment::insertBefore(), line_end, memory, name, MemorySegmentHeader::next, MemorySegment::size(), sweepSingleSegment(), and MemoryObject::verboseMessage().
Referenced by MemoryObject::transferSegmentToNormalSet().
validateObject()
void MemorySegmentSet::validateObject (RexxInternalObject * o) inline protected
Definition at line 304 of file MemorySegment.hpp.
References RexxInternalObject::dumpObject(), and RexxInternalObject::isValid().
Referenced by sweepSingleSegment().
Friends And Related Function Documentation
MemoryObject
friend class MemoryObject friend
Definition at line 175 of file MemorySegment.hpp.
Member Data Documentation
anchor
MemorySegment MemorySegmentSet::anchor protected
Definition at line 318 of file MemorySegment.hpp.
Referenced by add(), addSegment(), SingleObjectSegmentSet::allocateObject(), first(), largestActiveSegment(), and transferSegment().
count
size_t MemorySegmentSet::count protected
Definition at line 319 of file MemorySegment.hpp.
Referenced by add(), gatherStats(), MemorySegmentSet(), removeSegment(), and removeSegmentAndStorage().
deadObjectBytes
size_t MemorySegmentSet::deadObjectBytes protected
Definition at line 321 of file MemorySegment.hpp.
Referenced by freeMemoryPercentage(), prepareForSweep(), NormalSegmentSet::suggestMemoryExpansion(), LargeSegmentSet::suggestMemoryExpansion(), sweepSingleSegment(), and totalFreeMemory().
LargeSegmentDeadSpace
const size_t MemorySegmentSet::LargeSegmentDeadSpace = (LargeSegmentSize - MemorySegment::MemorySegmentOverhead) static
Definition at line 272 of file MemorySegment.hpp.
Referenced by addSegments(), and LargeSegmentSet::expandSegmentSet().
LargeSegmentSize
const size_t MemorySegmentSet::LargeSegmentSize = (MemorySegment::SegmentSize * 4) static
Definition at line 268 of file MemorySegment.hpp.
liveObjectBytes
size_t MemorySegmentSet::liveObjectBytes protected
Definition at line 320 of file MemorySegment.hpp.
Referenced by freeMemoryPercentage(), prepareForSweep(), NormalSegmentSet::recommendedMemorySize(), LargeSegmentSet::recommendedMemorySize(), NormalSegmentSet::suggestMemoryExpansion(), LargeSegmentSet::suggestMemoryExpansion(), sweepSingleSegment(), and totalFreeMemory().
memory
MemoryObject* MemorySegmentSet::memory protected
Definition at line 324 of file MemorySegment.hpp.
Referenced by addSegment(), adjustMemorySize(), SingleObjectSegmentSet::allocateObject(), allocateSegment(), LargeSegmentSet::allocateSegment(), SingleObjectSegmentSet::allocateSegment(), LargeSegmentSet::completeSweepOperation(), SingleObjectSegmentSet::completeSweepOperation(), LargeSegmentSet::expandSegmentSet(), NormalSegmentSet::handleAllocationFailure(), LargeSegmentSet::handleAllocationFailure(), SingleObjectSegmentSet::handleAllocationFailure(), MemorySegmentSet(), NormalSegmentSet::NormalSegmentSet(), NormalSegmentSet::suggestMemoryExpansion(), LargeSegmentSet::suggestMemoryExpansion(), and transferSegment().
MinimumSegmentDeadSpace
const size_t MemorySegmentSet::MinimumSegmentDeadSpace = (MinimumSegmentSize - MemorySegment::MemorySegmentOverhead) static
Definition at line 266 of file MemorySegment.hpp.
MinimumSegmentSize
const size_t MemorySegmentSet::MinimumSegmentSize = (MemorySegment::SegmentSize/2) static
Definition at line 264 of file MemorySegment.hpp.
name
const char* MemorySegmentSet::name protected
Definition at line 323 of file MemorySegment.hpp.
Referenced by addSegment(), adjustMemorySize(), SingleObjectSegmentSet::allocateObject(), dumpSegments(), MemorySegmentSet(), MemoryObject::scavengeSegmentSets(), and transferSegment().
owner
SegmentSetID MemorySegmentSet::owner protected
Definition at line 322 of file MemorySegment.hpp.
Referenced by is(), and MemorySegmentSet().
SegmentDeadSpace
const size_t MemorySegmentSet::SegmentDeadSpace = (MemorySegment::SegmentSize - MemorySegment::MemorySegmentOverhead) static
Definition at line 270 of file MemorySegment.hpp.
Referenced by addSegments().
The documentation for this class was generated from the following files:
MemorySegment.hpp
MemorySegment.cpp