ooRexx: APIServerThread Class Reference
APIServerThread Class Reference
#include <APIServerThread.hpp>
Public Member Functions
APIServerThread (APIServer *s, ApiConnection *c)
~APIServerThread ()
void start ()
void dispatch () override
Public Member Functions inherited from SysThread
SysThread ()
virtual ~SysThread ()
virtual void attachThread ()
void terminate ()
void startup ()
void shutdown ()
void yield ()
bool equals (SysThread &other)
void waitForTermination ()
SysThread ()
virtual ~SysThread ()
SysThread (thread_id_t threadID)
virtual void attachThread ()
void terminate ()
void startup ()
void shutdown ()
void yield ()
uintptr_t threadID ()
bool equals (SysThread &other)
size_t hash ()
void waitForTermination ()
Protected Attributes
APIServer * server
ApiConnection * connection
Protected Attributes inherited from SysThread
bool valid
bool attached
pthread_t _threadID
HANDLE _threadHandle
DWORD _threadID
Additional Inherited Members
Public Types inherited from SysThread
enum { THREAD_STACK_SIZE = 1024*512 }
enum { THREAD_STACK_SIZE = 1024*512 }
Static Public Member Functions inherited from SysThread
static void sleep (int msecs)
static int longSleep (uint64_t microseconds)
static uint64_t getMillisecondTicks ()
static int createThread (pthread_t &id, bool &idValid, size_t stackSize, void *(*startRoutine)(void *), void *startArgument)
static void sleep (int msecs)
static int longSleep (uint64_t microseconds)
static uint64_t getMillisecondTicks ()
static int createThread (HANDLE &threadHandle, DWORD &threadId, size_t stackSize, LPTHREAD_START_ROUTINE, void *startArgument)
Protected Member Functions inherited from SysThread
void createThread ()
void createThread ()
Detailed Description
Definition at line 46 of file APIServerThread.hpp.
Constructor & Destructor Documentation
APIServerThread()
APIServerThread::APIServerThread (APIServer * s, ApiConnection * c) inline
Definition at line 50 of file APIServerThread.hpp.
~APIServerThread()
APIServerThread::~APIServerThread () inline
Definition at line 51 of file APIServerThread.hpp.
References SysThread::terminate().
Member Function Documentation
dispatch()
void APIServerThread::dispatch () override virtual
Dispatch the newly created reader thread to do it's work.
Reimplemented from SysThread.
Definition at line 53 of file APIServerThread.cpp.
References connection, APIServer::processMessages(), server, and APIServer::sessionTerminated().
start()
void APIServerThread::start ()
Definition at line 45 of file APIServerThread.cpp.
References SysThread::createThread().
Referenced by APIServer::listenForConnections().
Member Data Documentation
connection
ApiConnection* APIServerThread::connection protected
Definition at line 58 of file APIServerThread.hpp.
Referenced by dispatch().
server
APIServer* APIServerThread::server protected
Definition at line 57 of file APIServerThread.hpp.
Referenced by dispatch().
The documentation for this class was generated from the following files:
APIServerThread.hpp
APIServerThread.cpp