ooRexx: RexxStartDispatcher Class Reference
RexxStartDispatcher Class Reference
#include <RexxStartDispatcher.hpp>
Public Member Functions
RexxStartDispatcher ()
virtual ~RexxStartDispatcher ()
void run () override
void handleError (wholenumber_t, DirectoryClass *) override
Public Member Functions inherited from ActivityDispatcher
ActivityDispatcher ()
virtual ~ActivityDispatcher ()
virtual void handleError (DirectoryClass *)
virtual void invoke ()
virtual void invoke (RexxOption *)
virtual void invoke (PRXSYSEXIT exits, const char *env)
void setContext (Activity *act, NativeActivation *a)
Public Attributes
size_t argcount
PCONSTRXSTRING arglist
const char * programName
PRXSTRING instore
const char * envname
int calltype
short retcode
PRXSTRING result
Public Attributes inherited from ActivityDispatcher
wholenumber_t rc
DirectoryClass * conditionData
Additional Inherited Members
Protected Attributes inherited from ActivityDispatcher
Activity * activity
NativeActivation * activation
Detailed Description
A dispatcher for processing a RexxStart call.
Definition at line 51 of file RexxStartDispatcher.hpp.
Constructor & Destructor Documentation
RexxStartDispatcher()
RexxStartDispatcher::RexxStartDispatcher () inline
Definition at line 54 of file RexxStartDispatcher.hpp.
~RexxStartDispatcher()
virtual RexxStartDispatcher::~RexxStartDispatcher () inline virtual
Definition at line 55 of file RexxStartDispatcher.hpp.
Member Function Documentation
handleError()
void RexxStartDispatcher::handleError (wholenumber_t r, DirectoryClass * c) override virtual
Default handler for any error conditions. This just sets the condition information in the dispatch unit.
Parameters
c The condition information for the error.
Reimplemented from ActivityDispatcher.
Definition at line 191 of file RexxStartDispatcher.cpp.
References ActivityDispatcher::activation, ActivityDispatcher::activity, ActivityDispatcher::conditionData, NativeActivation::enableConditionTraps(), Activity::error(), ActivityDispatcher::handleError(), ActivityDispatcher::rc, and retcode.
run()
void RexxStartDispatcher::run () override virtual
Default virtual method for handling a run() methods on an activity dispatcher.
Reimplemented from ActivityDispatcher.
Definition at line 56 of file RexxStartDispatcher.cpp.
References ActivityDispatcher::activity, ProtectedSet::add(), argcount, arglist, calltype, RexxString::copyToRxstring(), LanguageParser::createProgramFromFile(), Error_Program_unreadable_name, Error_Program_unreadable_notfound, InterpreterInstance::getDefaultEnvironment(), Activity::getInstance(), instore, ProtectedObject::isNull(), Protected< objType >::isNull(), MAKERXSTRING, ArrayClass::messageArgs(), new_array(), new_string(), RexxInternalObject::numberValue(), OREF_NULL, LanguageParser::processInstore(), programName, ArrayClass::put(), ActivityDispatcher::rc, reportException(), RESOLVE_DEFAULT, Activity::resolveProgramName(), result, retcode, RXCOMMAND, RXFUNCTION, RXSUBROUTINE, and RexxObject::stringValue().
Member Data Documentation
argcount
size_t RexxStartDispatcher::argcount
Definition at line 60 of file RexxStartDispatcher.hpp.
Referenced by RexxStart(), and run().
arglist
PCONSTRXSTRING RexxStartDispatcher::arglist
Definition at line 61 of file RexxStartDispatcher.hpp.
Referenced by RexxStart(), and run().
calltype
int RexxStartDispatcher::calltype
Definition at line 65 of file RexxStartDispatcher.hpp.
Referenced by RexxStart(), and run().
envname
const char* RexxStartDispatcher::envname
Definition at line 64 of file RexxStartDispatcher.hpp.
instore
PRXSTRING RexxStartDispatcher::instore
Definition at line 63 of file RexxStartDispatcher.hpp.
Referenced by RexxStart(), and run().
programName
const char* RexxStartDispatcher::programName
Definition at line 62 of file RexxStartDispatcher.hpp.
Referenced by RexxStart(), and run().
result
PRXSTRING RexxStartDispatcher::result
Definition at line 67 of file RexxStartDispatcher.hpp.
Referenced by RexxStart(), and run().
retcode
short RexxStartDispatcher::retcode
Definition at line 66 of file RexxStartDispatcher.hpp.
Referenced by handleError(), RexxStart(), and run().
The documentation for this class was generated from the following files:
RexxStartDispatcher.hpp
RexxStartDispatcher.cpp