ooRexx: InterpreterInstance Class Reference
InterpreterInstance Class Reference
#include <InterpreterInstance.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
InterpreterInstance (RESTORETYPE restoreType)
InterpreterInstance ()
void live (size_t) override
void liveGeneral (MarkReason) override
RexxString * getDefaultEnvironment ()
Activity * getRootActivity ()
uint32_t getIdntfr ()
InterpreterInstance (ExitHandler *handlers)
void addActivity (Activity *)
void removeActivity (Activity *)
void initialize (Activity *activity, RexxOption *options)
bool terminate ()
void waitForCompletion ()
void attachToProcess ()
Activity * enterOnCurrentThread ()
Activity * attachThread ()
int attachThread (RexxThreadContext *&attachedContext)
bool detachThread ()
bool detachThread (Activity *activity)
Activity * spawnActivity (Activity *parent)
Activity * findActivity (thread_id_t threadId)
Activity * findActivity ()
DirectoryClass * getLocalEnvironment ()
void copyExits (ExitHandler *target)
void activityDeactivated (Activity *activity)
void addGlobalReference (RexxObject *o)
void removeGlobalReference (RexxObject *o)
bool poolActivity (Activity *activity)
ExitHandler & getExitHandler (int exitNum)
void setExitHandler (int exitNum, REXXPFN e)
void setExitHandler (int exitNum, const char *e)
void setExitHandler (RXSYSEXIT &e)
void setExitHandler (RexxContextExit &e)
void removeInactiveActivities ()
bool haltAllActivities (RexxString *)
void traceAllActivities (bool on)
RexxString * resolveProgramName (RexxString *name, RexxString *dir, RexxString *ext, ResolveType type)
SecurityManager * getSecurityManager ()
void setSecurityManager (RexxObject *m)
RexxInstance * getInstanceContext ()
RexxThreadContext * getRootThreadContext ()
RexxObject * getLocalEnvironment (RexxString *)
DirectoryClass * getLocal ()
void addCommandHandler (const char *name, const char *registeredName)
void addCommandHandler (const char *name, REXXPFN entryPoint, HandlerType::Enum type)
CommandHandler * resolveCommandHandler (RexxString *name)
PackageClass * getRequiresFile (Activity *activity, RexxString *name)
PackageClass * loadRequires (Activity *activity, RexxString *shortName, ArrayClass *source)
PackageClass * loadRequires (Activity *activity, RexxString *shortName, RexxString *fullName)
PackageClass * loadRequires (Activity *activity, RexxString *shortName, const char *data, size_t length)
void addRequiresFile (RexxString *shortName, RexxString *fullName, PackageClass *package)
void setupProgram (RexxActivation *activation)
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Protected Member Functions
bool processOptions (RexxOption *options)
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Protected Attributes
InstanceContext context
SysInterpreterInstance sysInstance
Activity * rootActivity
SecurityManager * securityManager
QueueClass * allActivities
RexxString * defaultEnvironment
RexxString * searchPath
ArrayClass * searchExtensions
void * applicationData
uint32_t idntfr
DirectoryClass * localEnvironment
StringTable * commandHandlers
StringTable * requiresFiles
bool terminating
bool terminated
SysSemaphore terminationSem
ExitHandler exits [RXNOOFEXITS+1]
Static Protected Attributes
static RexxInstanceInterface interfaceVector
Friends
class SysInterpreterInstance
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Detailed Description
Definition at line 63 of file InterpreterInstance.hpp.
Constructor & Destructor Documentation
InterpreterInstance() [1/3]
InterpreterInstance::InterpreterInstance (RESTORETYPE restoreType) inline
Definition at line 74 of file InterpreterInstance.hpp.
InterpreterInstance() [2/3]
InterpreterInstance::InterpreterInstance ()
Constructor for an interpreter instance.
Definition at line 83 of file InterpreterInstance.cpp.
References context, SysSemaphore::create(), RexxInstance_::functions, InstanceContext::instance, InstanceContext::instanceContext, interfaceVector, SysSemaphore::reset(), and terminationSem.
InterpreterInstance() [3/3]
InterpreterInstance::InterpreterInstance (ExitHandler * handlers)
Member Function Documentation
activityDeactivated()
void InterpreterInstance::activityDeactivated (Activity * activity)
addActivity()
void InterpreterInstance::addActivity (Activity *)
addCommandHandler() [1/2]
void InterpreterInstance::addCommandHandler (const char * name, const char * registeredName)
Add a handler for a registered subcom handler to the address handler list.
Parameters
name The environment name of the handler.
registeredName The name of the registered subcom handler.
Definition at line 840 of file InterpreterInstance.cpp.
References commandHandlers, CommandHandler::isResolved(), new_upper_string(), and HashCollection::put().
Referenced by AddCommandEnvironment(), processOptions(), and SysInterpreterInstance::registerCommandHandlers().
addCommandHandler() [2/2]
void InterpreterInstance::addCommandHandler (const char * name, REXXPFN entryPoint, HandlerType::Enum type)
Add a handler to the environment list.
Parameters
name The name of the address environment this services.
entryPoint The entry point address of the handler.
type The category of handler to add.
Definition at line 826 of file InterpreterInstance.cpp.
References commandHandlers, new_upper_string(), HashCollection::put(), and type.
addGlobalReference()
void InterpreterInstance::addGlobalReference (RexxObject * o)
Add an object to the global references table.
Parameters
o The added object.
Definition at line 574 of file InterpreterInstance.cpp.
References MemoryObject::addGlobalReference(), memoryObject, and OREF_NULL.
Referenced by RequestGlobalReference().
addRequiresFile()
void InterpreterInstance::addRequiresFile (RexxString * shortName, RexxString * fullName, PackageClass * package)
Add a package to our cache, using weak references.
Parameters
shortName The shortName (always provided).
fullName A second, fully resolved alias name.
package The package to add
Definition at line 913 of file InterpreterInstance.cpp.
References OREF_NULL, HashCollection::put(), and requiresFiles.
Referenced by loadRequires().
attachThread() [1/2]
Activity * InterpreterInstance::attachThread ()
Attach a thread to an interpreter instance.
Returns
The attached activity.
Definition at line 214 of file InterpreterInstance.cpp.
References allActivities, ArrayClass::append(), ActivityManager::attachThread(), findActivity(), Activity::isNestable(), Activity::nestAttach(), OREF_NULL, and Activity::setupAttachedActivity().
Referenced by AttachThread(), attachThread(), and enterOnCurrentThread().
attachThread() [2/2]
int InterpreterInstance::attachThread (RexxThreadContext *& attachedContext)
Attach a thread to an interpreter instance, returning the activity thread context.
Parameters
attachedContext The pointer for returning the thread context.
Returns
0 indicates success.
Definition at line 198 of file InterpreterInstance.cpp.
References attachThread(), Activity::getThreadContext(), and Activity::releaseAccess().
attachToProcess()
void InterpreterInstance::attachToProcess ()
copyExits()
void InterpreterInstance::copyExits (ExitHandler * target)
detachThread() [1/2]
bool InterpreterInstance::detachThread ()
Detach a thread from this interpreter instance.
Returns
true if this worked ok.
Definition at line 311 of file InterpreterInstance.cpp.
References findActivity().
Referenced by Activity::detachThread().
detachThread() [2/2]
bool InterpreterInstance::detachThread (Activity * activity)
Detach a thread from this interpreter instance.
Parameters
activity The activity to detach
Returns
true if this worked ok.
Definition at line 268 of file InterpreterInstance.cpp.
References allActivities, Activity::isAttached(), Activity::isNestedAttach(), ArrayClass::items(), OREF_NULL, SysSemaphore::post(), Activity::releaseAccess(), ArrayClass::removeItem(), ActivityManager::returnActivity(), Activity::returnAttach(), terminating, and terminationSem.
enterOnCurrentThread()
Activity * InterpreterInstance::enterOnCurrentThread ()
Enter on the current thread context, making sure the interpreter lock is obtained.
Returns
The activity object associated with this thread/instance combination.
Definition at line 422 of file InterpreterInstance.cpp.
References Activity::activate(), attachThread(), and Activity::requestApiAccess().
Referenced by terminate().
findActivity() [1/2]
Activity * InterpreterInstance::findActivity ()
Find an activity for the current thread that's associated with this activity.
Returns
The target activity.
Definition at line 409 of file InterpreterInstance.cpp.
References SysActivity::queryThreadID().
Referenced by attachThread(), and detachThread().
findActivity() [2/2]
Activity * InterpreterInstance::findActivity (thread_id_t threadId)
Locate an activity for a specific thread ID that's attached to this instance.
Parameters
threadId The target thread id.
Returns
The associated activity, or OREF_NULL if the current thread is not attached.
Definition at line 383 of file InterpreterInstance.cpp.
References allActivities, ArrayClass::get(), Activity::isSuspended(), Activity::isThread(), ArrayClass::items(), and OREF_NULL.
getDefaultEnvironment()
RexxString* InterpreterInstance::getDefaultEnvironment () inline
Definition at line 80 of file InterpreterInstance.hpp.
References defaultEnvironment.
Referenced by RexxActivation::RexxActivation(), RexxStartDispatcher::run(), and RoutineClass::runProgram().
getExitHandler()
ExitHandler& InterpreterInstance::getExitHandler (int exitNum) inline
Definition at line 105 of file InterpreterInstance.hpp.
References exits.
Referenced by Activity::getExitHandler(), and setExitHandler().
getIdntfr()
uint32_t InterpreterInstance::getIdntfr ()
Definition at line 60 of file InterpreterInstance.cpp.
References counter(), and idntfr.
Referenced by RexxActivation::createTraceObject().
getInstanceContext()
RexxInstance* InterpreterInstance::getInstanceContext () inline
Definition at line 116 of file InterpreterInstance.hpp.
References context, and InstanceContext::instanceContext.
Referenced by Activity::addToInstance(), Interpreter::createInstance(), and GetInterpreterInstance().
getLocal()
DirectoryClass* InterpreterInstance::getLocal () inline
Definition at line 119 of file InterpreterInstance.hpp.
References localEnvironment.
Referenced by Activity::getLocal().
getLocalEnvironment() [1/2]
DirectoryClass* InterpreterInstance::getLocalEnvironment ()
Referenced by Activity::getLocalEnvironment().
getLocalEnvironment() [2/2]
RexxObject * InterpreterInstance::getLocalEnvironment (RexxString * name)
Retrieve a value from the instance local environment.
Parameters
name The name of the .local object.
Returns
The object stored at the given name.
Definition at line 810 of file InterpreterInstance.cpp.
References DirectoryClass::get(), localEnvironment, OREF_NULL, and TheNilObject.
getRequiresFile()
PackageClass * InterpreterInstance::getRequiresFile (Activity * activity, RexxString * name)
Retrieve a requires file that might be loaded for this instance.
Parameters
name The name used for the requires file.
Returns
The loaded requires file, or OREF_NULL if this instance has not used the file yet.
Definition at line 886 of file InterpreterInstance.cpp.
References WeakReference::get(), HashCollection::get(), OREF_NULL, HashCollection::remove(), requiresFiles, and ThePackageClass.
getRootActivity()
Activity* InterpreterInstance::getRootActivity () inline
Definition at line 81 of file InterpreterInstance.hpp.
References rootActivity.
Referenced by Interpreter::createInstance(), InstanceBlock::InstanceBlock(), and NativeContextBlock::NativeContextBlock().
getRootThreadContext()
RexxThreadContext * InterpreterInstance::getRootThreadContext ()
Get the thread context vector for the root activity of the instance.
Returns
The root RexxThreadContext environment;
Definition at line 797 of file InterpreterInstance.cpp.
References Activity::getThreadContext(), and rootActivity.
Referenced by Interpreter::createInstance().
getSecurityManager()
SecurityManager* InterpreterInstance::getSecurityManager () inline
Definition at line 114 of file InterpreterInstance.hpp.
References securityManager.
Referenced by Activity::getEffectiveSecurityManager(), and Activity::getInstanceSecurityManager().
haltAllActivities()
bool InterpreterInstance::haltAllActivities (RexxString * name)
Raise a halt condition on all running activities.
Definition at line 599 of file InterpreterInstance.cpp.
References allActivities, ArrayClass::get(), Activity::halt(), Activity::isActive(), ArrayClass::items(), and OREF_NULL.
Referenced by Halt(), and Interpreter::haltAllActivities().
initialize()
void InterpreterInstance::initialize (Activity * activity, RexxOption * options)
Initialize an interpreter instance.
Parameters
activity The root activity for the interpreter instance.
handlers The exit handlers used by all threads running under this instance.
defaultEnvironment The default address environment for this interpreter instance. Each active interpreter instance can define its own default environment.
Definition at line 146 of file InterpreterInstance.cpp.
References allActivities, ArrayClass::append(), commandHandlers, defaultEnvironment, SystemInterpreter::getDefaultAddressName(), SysInterpreterInstance::initialize(), Interpreter::initLocal(), localEnvironment, new_array(), new_directory(), new_queue(), new_string_table(), OREF_NULL, processOptions(), SysInterpreterInstance::registerCommandHandlers(), requiresFiles, rootActivity, searchExtensions, securityManager, Activity::setupAttachedActivity(), Activity::setupExits(), and sysInstance.
live()
void InterpreterInstance::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 102 of file InterpreterInstance.cpp.
References allActivities, commandHandlers, defaultEnvironment, localEnvironment, memory_mark, requiresFiles, rootActivity, searchExtensions, searchPath, and securityManager.
liveGeneral()
void InterpreterInstance::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 123 of file InterpreterInstance.cpp.
References allActivities, commandHandlers, defaultEnvironment, localEnvironment, memory_mark_general, requiresFiles, rootActivity, searchExtensions, searchPath, and securityManager.
loadRequires() [1/3]
PackageClass * InterpreterInstance::loadRequires (Activity * activity, RexxString * shortName, ArrayClass * source)
Load a ::requires file into this interpreter instance.
Parameters
activity The current activity we're loading on.,
shortName The original short name of this package.
fullName An expanded fully resolved file name.
Returns
The loaded package class, if located.
Definition at line 989 of file InterpreterInstance.cpp.
References addRequiresFile(), Error_Routine_not_found_requires, OREF_NULL, reportException(), and ThePackageClass.
Referenced by LoadPackage(), LoadPackageFromData(), and PackageClass::loadRequires().
loadRequires() [2/3]
PackageClass * InterpreterInstance::loadRequires (Activity * activity, RexxString * shortName, const char * data, size_t length)
Load a ::requires file into this interpreter instance.
Parameters
activity The current activity we're loading on.,
shortName The original short name of this package.
data The source file data.
length The length of the source data.
Returns
The loaded package class, if located.
Definition at line 1030 of file InterpreterInstance.cpp.
References addRequiresFile(), Error_Routine_not_found_requires, OREF_NULL, reportException(), and ThePackageClass.
loadRequires() [3/3]
PackageClass * InterpreterInstance::loadRequires (Activity * activity, RexxString * shortName, RexxString * fullName)
Load a ::requires file into this interpreter instance.
Parameters
activity The current activity we're loading on.,
shortName The original short name of this package.
fullName An expanded fully resolved file name.
Returns
The loaded package class, if located.
Definition at line 934 of file InterpreterInstance.cpp.
References addRequiresFile(), Activity::checkRequires(), Error_Routine_not_found_requires, OREF_NULL, reportException(), and ThePackageClass.
operator delete()
void InterpreterInstance::operator delete (void *) inline
Definition at line 71 of file InterpreterInstance.hpp.
operator new()
void * InterpreterInstance::operator new (size_t size)
Create a new Package object instance.
Parameters
size Size of the object.
Returns
Pointer to new object storage.
Definition at line 74 of file InterpreterInstance.cpp.
References new_object(), and T_InterpreterInstance.
poolActivity()
bool InterpreterInstance::poolActivity (Activity * activity)
Return a spawned activity back to the activity pool. This will disassociate the activity from the interpreter instance and place the thread back into the global thread pool.
Parameters
activity The activity to return.
Returns
true if the activity was added to the pool, false if the activity should continue with termination.
Definition at line 350 of file InterpreterInstance.cpp.
References allActivities, Activity::detachInstance(), ArrayClass::items(), ActivityManager::poolActivity(), SysSemaphore::post(), ArrayClass::removeItem(), terminating, and terminationSem.
Referenced by Activity::runThread().
processOptions()
bool InterpreterInstance::processOptions (RexxOption * options) protected
Process interpreter instance options.
Parameters
options The list of defined options.
Returns
True if the options were processed correctly, false otherwise.
Definition at line 646 of file InterpreterInstance.cpp.
References addCommandHandler(), ArrayClass::append(), APPLICATION_DATA, RexxInstance_::applicationData, context, defaultEnvironment, HandlerType::DIRECT, DIRECT_ENVIRONMENTS, DIRECT_EXITS, EXTERNAL_CALL_EXTENSIONS, EXTERNAL_CALL_PATH, PackageManager::getLibrary(), RexxContextEnvironment::handler, RexxRedirectingEnvironment::handler, if(), INITIAL_ADDRESS_ENVIRONMENT, InstanceContext::instanceContext, LOAD_REQUIRED_LIBRARY, RexxContextEnvironment::name, RexxRedirectingEnvironment::name, new_string(), RexxOption::option, RexxOption::optionName, HandlerType::REDIRECTING, REDIRECTING_ENVIRONMENTS, REGISTER_LIBRARY, REGISTERED_ENVIRONMENTS, REGISTERED_EXITS, RexxRegisteredEnvironment::registeredName, PackageManager::registerPackage(), RXENDLST, searchExtensions, searchPath, setExitHandler(), _RexxContextExit::sysexit_code, _RXSYSEXIT::sysexit_code, _ValueDescriptor::value, _ValueDescriptor::value_CSTRING, and _ValueDescriptor::value_POINTER.
Referenced by initialize().
removeActivity()
void InterpreterInstance::removeActivity (Activity *)
removeGlobalReference()
void InterpreterInstance::removeGlobalReference (RexxObject * o)
Remove the global reference protection from an object.
Parameters
o The protected object.
Definition at line 587 of file InterpreterInstance.cpp.
References MemoryObject::addGlobalReference(), memoryObject, and OREF_NULL.
Referenced by ReleaseGlobalReference().
removeInactiveActivities()
void InterpreterInstance::removeInactiveActivities ()
Definition at line 436 of file InterpreterInstance.cpp.
References allActivities, ArrayClass::append(), Activity::isActive(), ArrayClass::items(), QueueClass::pull(), rootActivity, and Activity::terminatePoolActivity().
Referenced by terminate().
resolveCommandHandler()
CommandHandler * InterpreterInstance::resolveCommandHandler (RexxString * name)
Resolve a command handler for invoking a command.
Parameters
name The name of the target address environment.
Returns
The resolved handler, or OREF_NULL if this is not known.
Definition at line 859 of file InterpreterInstance.cpp.
References commandHandlers, HashCollection::get(), RexxString::getStringData(), CommandHandler::isResolved(), OREF_NULL, HashCollection::put(), and RexxString::upper().
Referenced by Activity::resolveCommandHandler().
resolveProgramName()
RexxString * InterpreterInstance::resolveProgramName (RexxString * _name, RexxString * _parentDir, RexxString * _parentExtension, ResolveType type)
Resolve a program for intial loading or a subroutine call.
Parameters
_name The target name. This can be fully qualified, or a simple name without an extension.
_parentDir The directory of the file of our calling program. The first place we'll look is in the same directory as the program.
_parentExtension The extension our calling program has. If there is an extension, we'll use that version first before trying any of the default extensions.
type Either RESOLVE_REQUIRES, which requests an additional extension to be tried before the standard search order, or RESOLVE_DEFAULT.
Returns
A string version of the file name, if found. Returns OREF_NULL if the program cannot be found.
Definition at line 1080 of file InterpreterInstance.cpp.
References ArrayClass::get(), RexxString::getStringData(), SysFileSystem::hasExtension(), ArrayClass::items(), new_string(), OREF_NULL, RESOLVE_REQUIRES, searchExtensions, SysFileSystem::searchName(), searchPath, and type.
Referenced by PackageClass::findProgramRexx(), PackageClass::newRexx(), and Activity::resolveProgramName().
setExitHandler() [1/4]
void InterpreterInstance::setExitHandler (int exitNum, const char * e) inline
Definition at line 107 of file InterpreterInstance.hpp.
References getExitHandler(), and ExitHandler::resolve().
setExitHandler() [2/4]
void InterpreterInstance::setExitHandler (int exitNum, REXXPFN e) inline
Definition at line 106 of file InterpreterInstance.hpp.
References getExitHandler(), and ExitHandler::setEntryPoint().
Referenced by processOptions().
setExitHandler() [3/4]
void InterpreterInstance::setExitHandler (RexxContextExit & e) inline
Definition at line 109 of file InterpreterInstance.hpp.
References getExitHandler(), _RexxContextExit::handler, ExitHandler::resolve(), and _RexxContextExit::sysexit_code.
setExitHandler() [4/4]
void InterpreterInstance::setExitHandler (RXSYSEXIT & e) inline
Definition at line 108 of file InterpreterInstance.hpp.
References getExitHandler(), ExitHandler::resolve(), _RXSYSEXIT::sysexit_code, and _RXSYSEXIT::sysexit_name.
setSecurityManager()
void InterpreterInstance::setSecurityManager (RexxObject * m)
Set a new security manager object for this instance.
Parameters
m The security manager to set.
Definition at line 183 of file InterpreterInstance.cpp.
References securityManager.
setupProgram()
void InterpreterInstance::setupProgram (RexxActivation * activation) inline
Definition at line 128 of file InterpreterInstance.hpp.
References SysInterpreterInstance::setupProgram(), and sysInstance.
Referenced by RexxActivation::run().
spawnActivity()
Activity * InterpreterInstance::spawnActivity (Activity * parent)
Spawn off a new thread from an existing thread.
Parameters
parent The parent thread.
Returns
The attached activity.
Definition at line 326 of file InterpreterInstance.cpp.
References Activity::addToInstance(), allActivities, ArrayClass::append(), and ActivityManager::createNewActivity().
Referenced by Activity::spawnReply().
terminate()
bool InterpreterInstance::terminate ()
Attempt to shutdown the interpreter instance. This can only be done from the root activity.
Returns
true if shutdown has been initiated, false otherwise.
Definition at line 468 of file InterpreterInstance.cpp.
References allActivities, Activity::clearLocalReferences(), SysSemaphore::close(), MemoryObject::collectAndUninit(), commandHandlers, defaultEnvironment, enterOnCurrentThread(), Activity::exitCurrentThread(), Activity::isActive(), Interpreter::isInstanceActive(), ArrayClass::items(), Interpreter::lastInstance(), localEnvironment, memoryObject, OREF_NULL, removeInactiveActivities(), requiresFiles, ActivityManager::returnRootActivity(), rootActivity, searchExtensions, searchPath, securityManager, sysInstance, SysInterpreterInstance::terminate(), terminated, Interpreter::terminateInterpreterInstance(), terminating, terminationSem, and SysSemaphore::wait().
Referenced by Terminate(), InstanceBlock::~InstanceBlock(), and NativeContextBlock::~NativeContextBlock().
traceAllActivities()
void InterpreterInstance::traceAllActivities (bool on)
Raise a trace condition on all running activities.
Definition at line 622 of file InterpreterInstance.cpp.
References allActivities, ArrayClass::get(), Activity::isActive(), ArrayClass::items(), and Activity::setTrace().
Referenced by SetTrace().
waitForCompletion()
void InterpreterInstance::waitForCompletion ()
Friends And Related Function Documentation
SysInterpreterInstance
friend class SysInterpreterInstance friend
Definition at line 67 of file InterpreterInstance.hpp.
Member Data Documentation
allActivities
QueueClass* InterpreterInstance::allActivities protected
Definition at line 143 of file InterpreterInstance.hpp.
Referenced by attachThread(), detachThread(), findActivity(), haltAllActivities(), initialize(), live(), liveGeneral(), poolActivity(), removeInactiveActivities(), spawnActivity(), terminate(), and traceAllActivities().
applicationData
void* InterpreterInstance::applicationData protected
Definition at line 147 of file InterpreterInstance.hpp.
commandHandlers
StringTable* InterpreterInstance::commandHandlers protected
Definition at line 150 of file InterpreterInstance.hpp.
Referenced by addCommandHandler(), initialize(), live(), liveGeneral(), resolveCommandHandler(), and terminate().
context
InstanceContext InterpreterInstance::context protected
Definition at line 138 of file InterpreterInstance.hpp.
Referenced by getInstanceContext(), InterpreterInstance(), and processOptions().
defaultEnvironment
RexxString* InterpreterInstance::defaultEnvironment protected
Definition at line 144 of file InterpreterInstance.hpp.
Referenced by getDefaultEnvironment(), initialize(), live(), liveGeneral(), processOptions(), and terminate().
exits
ExitHandler InterpreterInstance::exits[RXNOOFEXITS+1] protected
Definition at line 158 of file InterpreterInstance.hpp.
Referenced by getExitHandler().
idntfr
uint32_t InterpreterInstance::idntfr protected
Definition at line 148 of file InterpreterInstance.hpp.
Referenced by getIdntfr().
interfaceVector
RexxInstanceInterface InterpreterInstance::interfaceVector static protected
Initial value:
=
{
    INSTANCE_INTERFACE_VERSION,
    Terminate,
    AttachThread,
    InterpreterVersion,
    LanguageLevel,
    Halt,
    SetTrace,
    AddCommandEnvironment,
}
Definition at line 160 of file InterpreterInstance.hpp.
Referenced by InterpreterInstance().
localEnvironment
DirectoryClass* InterpreterInstance::localEnvironment protected
Definition at line 149 of file InterpreterInstance.hpp.
Referenced by getLocal(), getLocalEnvironment(), initialize(), live(), liveGeneral(), and terminate().
requiresFiles
StringTable* InterpreterInstance::requiresFiles protected
Definition at line 151 of file InterpreterInstance.hpp.
Referenced by addRequiresFile(), getRequiresFile(), initialize(), live(), liveGeneral(), and terminate().
rootActivity
Activity* InterpreterInstance::rootActivity protected
Definition at line 141 of file InterpreterInstance.hpp.
Referenced by getRootActivity(), getRootThreadContext(), initialize(), live(), liveGeneral(), removeInactiveActivities(), and terminate().
searchExtensions
ArrayClass* InterpreterInstance::searchExtensions protected
Definition at line 146 of file InterpreterInstance.hpp.
Referenced by SysInterpreterInstance::addSearchExtension(), initialize(), live(), liveGeneral(), processOptions(), resolveProgramName(), and terminate().
searchPath
RexxString* InterpreterInstance::searchPath protected
Definition at line 145 of file InterpreterInstance.hpp.
Referenced by live(), liveGeneral(), processOptions(), resolveProgramName(), and terminate().
securityManager
SecurityManager* InterpreterInstance::securityManager protected
Definition at line 142 of file InterpreterInstance.hpp.
Referenced by getSecurityManager(), initialize(), live(), liveGeneral(), setSecurityManager(), and terminate().
sysInstance
SysInterpreterInstance InterpreterInstance::sysInstance protected
Definition at line 139 of file InterpreterInstance.hpp.
Referenced by initialize(), setupProgram(), and terminate().
terminated
bool InterpreterInstance::terminated protected
Definition at line 154 of file InterpreterInstance.hpp.
Referenced by terminate().
terminating
bool InterpreterInstance::terminating protected
Definition at line 153 of file InterpreterInstance.hpp.
Referenced by detachThread(), poolActivity(), and terminate().
terminationSem
SysSemaphore InterpreterInstance::terminationSem protected
Definition at line 155 of file InterpreterInstance.hpp.
Referenced by detachThread(), InterpreterInstance(), poolActivity(), and terminate().
The documentation for this class was generated from the following files:
InterpreterInstance.hpp
InterpreterInstance.cpp
InterpreterInstanceStubs.cpp