ooRexx: RexxInternalObject Class Reference
RexxInternalObject Class Reference
#include <ObjectClass.hpp>
Public Member Functions
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void live (size_t)
virtual void liveGeneral (MarkReason reason)
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static size_t getObjectHeaderSize ()
Public Attributes
ObjectHeader header
RexxBehaviour * behaviour
Additional Inherited Members
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Base class for an object Rexx object. This class is used for internal objects only. An internal object is one that is not exposed to the Rexx programmer and are only used internal to the interpreter. Objects of this type are allocated from the ooRexx object heap and participate in garbage collection.
Definition at line 238 of file ObjectClass.hpp.
Constructor & Destructor Documentation
RexxInternalObject() [1/2]
RexxInternalObject::RexxInternalObject () inline
Definition at line 241 of file ObjectClass.hpp.
Referenced by getObjectHeaderSize().
RexxInternalObject() [2/2]
RexxInternalObject::RexxInternalObject (RESTORETYPE restoreType) inline
Following constructor used to reconstruct the Virtual Functions table, o it doesn't need to do anything. Every class defined in PrimitiveClasses.xml will need to provide one of these.
Parameters
restoreType Dummy argument used for contstructor signature matches.
Definition at line 251 of file ObjectClass.hpp.
~RexxInternalObject()
virtual RexxInternalObject::~RexxInternalObject () inline virtual
Definition at line 252 of file ObjectClass.hpp.
Member Function Documentation
checkVirtualFunctions() [1/2]
bool RexxInternalObject::checkVirtualFunctions () inline
Definition at line 280 of file ObjectClass.hpp.
Referenced by isValid(), and MemoryObject::mark().
checkVirtualFunctions() [2/2]
bool RexxInternalObject::checkVirtualFunctions (void * c) inline
Definition at line 281 of file ObjectClass.hpp.
clearHasUninit()
void RexxInternalObject::clearHasUninit () inline
Definition at line 295 of file ObjectClass.hpp.
References ObjectHeader::clearHasUninit(), and header.
Referenced by removedUninit().
clearObject() [1/2]
void RexxInternalObject::clearObject () inline
Definition at line 277 of file ObjectClass.hpp.
References getObjectDataSize(), and getObjectDataSpace().
Referenced by Activity::Activity(), HashContents::HashContents(), RexxObject::initializeNewObject(), ListContents::ListContents(), NativeActivation::NativeActivation(), PushThroughStack::PushThroughStack(), and RexxActivation::RexxActivation().
clearObject() [2/2]
void RexxInternalObject::clearObject (size_t l) inline
Definition at line 278 of file ObjectClass.hpp.
References getObjectDataSpace(), and getObjectHeaderSize().
clearObjectMark()
void RexxInternalObject::clearObjectMark () inline
Definition at line 304 of file ObjectClass.hpp.
References ObjectHeader::clearObjectMark(), and header.
Referenced by ImageSaveMarkHandler::mark().
clone()
RexxInternalObject * RexxInternalObject::clone ()
Copy the storage of an object and set up its header. This method should be called by other copy() methods instead ov using new_object and memcpy so that the memory can properly initialize the new object's header will be garbage collected properly.
Returns
A new object copied for the source object.
Definition at line 2657 of file ObjectClass.cpp.
References getObjectSize(), header, new_object(), and setNewSpace().
Referenced by NumberString::clone(), copy(), RexxBehaviour::copy(), RexxObject::copy(), VariableDictionary::copy(), and RexxClass::newRexx().
compareTo()
wholenumber_t RexxInternalObject::compareTo (RexxInternalObject * other) virtual
Wrapper around the compareTo() method that validates and extracts integer value.
Parameters
other The other comparison object
Returns
-1, 0, 1 depending on the comparison result.
Reimplemented in RexxInteger, NumberString, and RexxString.
Definition at line 230 of file ObjectClass.cpp.
References Error_Invalid_whole_number_compareto, Error_No_result_object_message, ProtectedObject::isNull(), numberValue(), reportException(), and RexxObject::sendMessage().
Referenced by ArrayClass::BaseSortComparator::compare(), and RexxString::compareTo().
copy()
RexxInternalObject * RexxInternalObject::copy () virtual
First level primitive copy of an object. This just copies the object storage, and nothing else.
Returns
A copy of the target internal object.
Reimplemented in MethodDictionary, RexxBehaviour, ArrayClass, DirectoryClass, ListClass, MessageClass, MutableBuffer, RexxObject, PackageClass, StemClass, HashCollection, WeakReference, BaseExecutable, VariableDictionary, MapTable, and PointerTable.
Definition at line 537 of file ObjectClass.cpp.
References clone().
Referenced by MethodDictionary::copy(), ListClass::copy(), HashCollection::copy(), VariableDictionary::copy(), MapTable::copy(), PointerTable::copy(), HashContents::copyValues(), LanguageParser::messageAssignmentOpNew(), HashCollection::reHash(), and NativeCode::setPackageObject().
copyIntoTail()
void RexxInternalObject::copyIntoTail (CompoundVariableTail * tail) virtual
Copy an object value into a compound variable tail under construction.
Parameters
tail The target tail.
Reimplemented in RexxInteger, and RexxString.
Definition at line 1201 of file ObjectClass.cpp.
References RexxString::copyIntoTail(), and requestString().
Referenced by CompoundVariableTail::buildTail(), and CompoundVariableTail::buildUnresolvedTail().
defaultName()
RexxString * RexxInternalObject::defaultName () virtual
Handle "final" string coercion level
Returns
The default string value for an object...generally just constructed from the class id.
Reimplemented in RexxClass, and RexxObject.
Definition at line 1748 of file ObjectClass.cpp.
References new_string().
Referenced by Activity::messageSubstitution().
doubleValue()
bool RexxInternalObject::doubleValue (double & result) virtual
Convert a REXX object to a double value.
Parameters
result the returned converted number.
Returns
true if the number converted, false otherwise.
Reimplemented in RexxInteger, NumberString, StemClass, RexxString, and VariableReference.
Definition at line 1101 of file ObjectClass.cpp.
References RexxString::doubleValue(), and requestString().
Referenced by StemClass::doubleValue(), VariableReference::doubleValue(), floatingPointArgument(), NativeActivation::getDoubleValue(), NativeActivation::objectToValue(), and requiredFloat().
dumpObject()
void RexxInternalObject::dumpObject ()
Provide a dump of the header part of an object. This is generally used when an invalid heap object is detected during garbage collection.
Definition at line 2680 of file ObjectClass.cpp.
References getObjectSize(), getObjectTypeNumber(), line_end, Memory::MinimumObjectSize, and Memory::ObjectGrain.
Referenced by setObjectSize(), and MemorySegmentSet::validateObject().
equalValue()
bool RexxInternalObject::equalValue (RexxInternalObject * other) inline
Definition at line 366 of file ObjectClass.hpp.
References isEqual().
Referenced by StemClass::findByValue(), ArrayClass::findSingleIndexItem(), ListContents::getIndex(), DirectoryClass::getIndex(), EqualityHashContents::isIndexEqual(), EqualityHashContents::isItemEqual(), and ListContents::removeItem().
evaluate()
virtual RexxObject* RexxInternalObject::evaluate (RexxActivation * , ExpressionStack *) inline virtual
Reimplemented in RexxInteger, NumberString, RexxString, ClassResolver, RexxCompoundVariable, RexxDotVariable, RexxExpressionFunction, RexxExpressionList, RexxExpressionLogical, RexxExpressionMessage, RexxBinaryOperator, RexxUnaryOperator, QualifiedFunction, RexxStemVariable, RexxSimpleVariable, SpecialDotVariable, and VariableReferenceOp.
Definition at line 328 of file ObjectClass.hpp.
References OREF_NULL.
Referenced by RexxExpressionMessage::assign(), DoBlock::checkControl(), WhileUntilLoop::checkUntil(), WhileUntilLoop::checkWhile(), CommandIOConfiguration::createInputSource(), CommandIOConfiguration::createOutputTarget(), RexxExpressionList::evaluate(), RexxExpressionLogical::evaluate(), RexxExpressionMessage::evaluate(), RexxBinaryOperator::evaluate(), RexxUnaryOperator::evaluate(), RexxInstruction::evaluateArguments(), RexxInstructionExpression::evaluateExpression(), RexxInstructionExpression::evaluateStringExpression(), ConstantDirective::execute(), RexxInstructionAddress::execute(), RexxInstructionAssignment::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionCommand::execute(), RexxInstructionForward::execute(), RexxInstructionGuard::execute(), RexxInstructionIf::execute(), RexxInstructionMessage::execute(), RexxInstructionNumeric::execute(), RexxInstructionParse::execute(), RexxInstructionRaise::execute(), RexxInstructionSelectCase::execute(), RexxInstructionDynamicSignal::execute(), RexxInstructionTrace::execute(), RexxInstructionCaseWhen::execute(), UseVariable::handleArgument(), ParseTrigger::integerTrigger(), RexxVariableReference::list(), ControlledLoop::setup(), OverLoop::setup(), WithLoop::setup(), ForLoop::setup(), and ParseTrigger::stringTrigger().
getHashValue()
virtual HashCode RexxInternalObject::getHashValue () inline virtual
Reimplemented in RexxClass, RexxInteger, NumberString, RexxNilObject, PointerClass, and RexxString.
Definition at line 335 of file ObjectClass.hpp.
References identityHash().
Referenced by hash(), RexxObject::hash(), RexxObject::hashCode(), and HashContents::hashIndex().
getObjectDataSize()
size_t RexxInternalObject::getObjectDataSize () inline
Definition at line 271 of file ObjectClass.hpp.
References getObjectHeaderSize(), and getObjectSize().
Referenced by clearObject().
getObjectDataSpace()
void* RexxInternalObject::getObjectDataSpace () inline
Definition at line 272 of file ObjectClass.hpp.
References getObjectHeaderSize().
Referenced by clearObject().
getObjectHeaderSize()
static size_t RexxInternalObject::getObjectHeaderSize () inline static
Definition at line 270 of file ObjectClass.hpp.
References RexxInternalObject().
Referenced by clearObject(), getObjectDataSize(), and getObjectDataSpace().
getObjectSize()
size_t RexxInternalObject::getObjectSize () inline
Definition at line 256 of file ObjectClass.hpp.
References ObjectHeader::getObjectSize(), and header.
Referenced by clone(), SingleObjectSegmentSet::completeSweepOperation(), Envelope::copyBuffer(), dumpObject(), getObjectDataSize(), isValid(), ObjectStats::logObject(), ImageSaveMarkHandler::mark(), nextObject(), SegmentStats::recordObject(), MemoryObject::reSize(), MemorySegmentSet::splitDeadObject(), MemorySegmentSet::sweepSingleSegment(), and MemoryObject::unflattenObjectBuffer().
getObjectType()
RexxBehaviour* RexxInternalObject::getObjectType () inline
Definition at line 318 of file ObjectClass.hpp.
References behaviour.
Referenced by isSameType().
getObjectTypeNumber()
size_t RexxInternalObject::getObjectTypeNumber ()
Return the object's primitive type number
Returns
The object type number.
Definition at line 2347 of file ObjectClass.cpp.
References behaviour, and RexxBehaviour::getClassType().
Referenced by dumpObject(), isObjectType(), isValid(), and MemoryStats::logObject().
getRealValue() [1/2]
virtual RexxObject* RexxInternalObject::getRealValue (RexxActivation *) inline virtual
Reimplemented in RexxInteger, NumberString, RexxString, RexxCompoundVariable, RexxStemVariable, and RexxSimpleVariable.
Definition at line 331 of file ObjectClass.hpp.
References OREF_NULL.
Referenced by RexxActivation::autoExpose(), and NativeActivation::getContextVariable().
getRealValue() [2/2]
virtual RexxObject* RexxInternalObject::getRealValue (VariableDictionary *) inline virtual
Reimplemented in RexxInteger, NumberString, RexxString, RexxCompoundVariable, RexxStemVariable, and RexxSimpleVariable.
Definition at line 332 of file ObjectClass.hpp.
References OREF_NULL.
getValue() [1/2]
virtual RexxObject* RexxInternalObject::getValue (RexxActivation *) inline virtual
Reimplemented in RexxInteger, RexxString, RexxDotVariable, RexxStemVariable, RexxSimpleVariable, SpecialDotVariable, NumberString, and RexxCompoundVariable.
Definition at line 329 of file ObjectClass.hpp.
References OREF_NULL.
Referenced by CompoundVariableTail::buildTail(), DoBlock::checkControl(), NativeActivation::getContextStem(), RexxInteger::power(), RexxActivation::raise(), AttributeGetterCode::run(), DelegateCode::run(), VariableDictionary::VariableIterator::value(), and NativeActivation::variablePoolFetchVariable().
getValue() [2/2]
virtual RexxObject* RexxInternalObject::getValue (VariableDictionary *) inline virtual
Reimplemented in RexxInteger, RexxString, RexxStemVariable, RexxSimpleVariable, RexxCompoundVariable, and NumberString.
Definition at line 330 of file ObjectClass.hpp.
References OREF_NULL.
hash()
virtual HashCode RexxInternalObject::hash () inline virtual
Reimplemented in RexxClass, and RexxObject.
Definition at line 334 of file ObjectClass.hpp.
References getHashValue().
Referenced by EqualityHashContents::hashIndex().
hasNoReferences()
bool RexxInternalObject::hasNoReferences () inline
Definition at line 297 of file ObjectClass.hpp.
References ObjectHeader::hasNoReferences(), and header.
Referenced by MemoryObject::mark().
hasReferences()
bool RexxInternalObject::hasReferences () inline
Definition at line 296 of file ObjectClass.hpp.
References ObjectHeader::hasReferences(), and header.
Referenced by MemorySegment::markAllObjects(), and MemoryObject::restoreImage().
hasUninit()
bool RexxInternalObject::hasUninit () inline
Definition at line 293 of file ObjectClass.hpp.
References ObjectHeader::hasUninit(), and header.
Referenced by RexxObject::copy().
identityHash()
HashCode RexxInternalObject::identityHash () inline
Definition at line 340 of file ObjectClass.hpp.
References UINTPTR_MAX.
Referenced by getHashValue(), MapBucket::hashIndex(), and RexxObject::identityHashRexx().
instanceMethod()
MethodClass * RexxInternalObject::instanceMethod (RexxString * method_name) virtual
Retrieve the method instance for an object's defined method.
Parameters
method_name The method name.
Returns
The method object that implements the object method.
Reimplemented in RexxInteger, NumberString, and RexxObject.
Definition at line 302 of file ObjectClass.cpp.
References TheNilObject.
instanceMethods()
SupplierClass * RexxInternalObject::instanceMethods (RexxClass * class_object) virtual
Return a supplier containing the methods implemented by an object. Depending on the argument, this is either A) all of the methods, B) just the explicitly set instance methods, or C) the methods provided by a given class.
Parameters
class_object The target class object (optional).
Returns
A supplier with the appropriate method set.
Reimplemented in RexxInteger, NumberString, and RexxObject.
Definition at line 337 of file ObjectClass.cpp.
References OREF_NULL.
integerValue()
RexxInteger * RexxInternalObject::integerValue (wholenumber_t precision) virtual
Convert a primitive internal object to an integer value
Parameters
precision The precision used on the conversion.
Returns
An integer object representation for the object or .nil
Reimplemented in RexxInteger, NumberString, StemClass, RexxString, and VariableReference.
Definition at line 1116 of file ObjectClass.cpp.
References RexxString::integerValue(), and requestString().
Referenced by StemClass::integerValue(), VariableReference::integerValue(), requestInteger(), and requiredInteger().
isBaseClass()
bool RexxInternalObject::isBaseClass ()
Test if an object instance is a true instance of a primitive class.
Returns
true if the object is not a subclass instance or an enhanced one-off.
Definition at line 216 of file ObjectClass.cpp.
References behaviour, and RexxBehaviour::isPrimitive().
Referenced by RexxString::baseString(), RexxString::compareTo(), RexxObject::hash(), isEqual(), RexxString::isEqual(), SupplierClass::loopAvailable(), SupplierClass::loopIndex(), SupplierClass::loopItem(), SupplierClass::loopNext(), makeArray(), makeString(), RexxString::makeString(), RexxString::numberString(), RexxString::numberValue(), RexxObject::objectName(), StringHashCollection::processUnknown(), requestArray(), requestInteger(), requestString(), requestStringNoNOSTRING(), requiredString(), RexxString::stringValue(), and RexxString::unsignedNumberValue().
isEqual()
bool RexxInternalObject::isEqual (RexxInternalObject * other) virtual
The rexx object override for the isequal method. This will either compare using the pointers or for non-primitive objects, will call the == method to compare.
Parameters
other The object to compare against.
Returns
true if the objects compare equal, false otherwise.
Reimplemented in RexxInteger, NumberString, and RexxString.
Definition at line 180 of file ObjectClass.cpp.
References Error_Logical_value_method, isBaseClass(), RexxObject::sendMessage(), and truthValue().
Referenced by equalValue(), and ListContents::isItem().
isInstanceOf()
bool RexxInternalObject::isInstanceOf (RexxClass * other) virtual
Test if an internal object is an instance of another class.
Parameters
other The test class.
Returns
Always returns false.
Reimplemented in RexxInteger, NumberString, and RexxObject.
Definition at line 258 of file ObjectClass.cpp.
isNewSpace()
bool RexxInternalObject::isNewSpace () inline
Definition at line 308 of file ObjectClass.hpp.
References header, and ObjectHeader::isNewSpace().
Referenced by ArrayClass::empty(), and MemoryObject::setOref().
isNonPrimitive()
bool RexxInternalObject::isNonPrimitive () inline
Definition at line 301 of file ObjectClass.hpp.
References header, and ObjectHeader::isNonPrimitive().
Referenced by MemoryObject::restoreImage(), MemoryObject::saveImage(), and MemoryObject::unflattenObjectBuffer().
isObjectDead()
bool RexxInternalObject::isObjectDead (size_t mark) inline
Definition at line 306 of file ObjectClass.hpp.
References header, and ObjectHeader::isObjectDead().
Referenced by MemoryObject::checkUninit(), and MemorySegmentSet::sweepSingleSegment().
isObjectLive()
bool RexxInternalObject::isObjectLive (size_t mark) inline
Definition at line 305 of file ObjectClass.hpp.
References header, and ObjectHeader::isObjectLive().
Referenced by MemoryObject::checkWeakReferences(), ImageSaveMarkHandler::mark(), TracingMarkHandler::mark(), SegmentStats::recordObject(), MemorySegmentSet::sweepSingleSegment(), and MemoryObject::unflattenProxyObjects().
isObjectMarked()
bool RexxInternalObject::isObjectMarked (size_t markword) inline
Definition at line 302 of file ObjectClass.hpp.
References header, and ObjectHeader::isObjectMarked().
isObjectType() [1/2]
bool RexxInternalObject::isObjectType (RexxBehaviour * b) inline
Definition at line 319 of file ObjectClass.hpp.
References behaviour.
isObjectType() [2/2]
bool RexxInternalObject::isObjectType (size_t t) inline
Definition at line 320 of file ObjectClass.hpp.
References getObjectTypeNumber().
isOldSpace()
bool RexxInternalObject::isOldSpace () inline
Definition at line 307 of file ObjectClass.hpp.
References header, and ObjectHeader::isOldSpace().
Referenced by HashCollection::expandContents(), VariableDictionary::expandContents(), PackageClass::isInternalCode(), OrefSet(), ArrayClass::resize(), and RexxActivation::run().
isPrimitive()
bool RexxInternalObject::isPrimitive () inline
Definition at line 300 of file ObjectClass.hpp.
References header, and ObjectHeader::isPrimitive().
isProxyObject()
bool RexxInternalObject::isProxyObject () inline
Definition at line 314 of file ObjectClass.hpp.
References header, and ObjectHeader::isProxyObject().
Referenced by RexxString::unflatten().
isReadyForUninit()
bool RexxInternalObject::isReadyForUninit () inline
Definition at line 292 of file ObjectClass.hpp.
References header, and ObjectHeader::isReadyForUninit().
Referenced by MemoryObject::runUninits().
isSameType()
bool RexxInternalObject::isSameType (RexxInternalObject * o) inline
Definition at line 321 of file ObjectClass.hpp.
References behaviour, and getObjectType().
isSubClassOrEnhanced()
bool RexxInternalObject::isSubClassOrEnhanced ()
Test if an object instance is an enhanced version of a primitive class or a subclass of the primitive class.
Returns
true if the object is a subclass instance or an enhanced one-off.
Definition at line 204 of file ObjectClass.cpp.
References behaviour, and RexxBehaviour::isNonPrimitive().
isValid()
bool RexxInternalObject::isValid ()
Perform a simple validation on an object so we can detect corrupted objects during garbage collection
Returns
True if the object is value, false if it fails any of the validity tests.
Definition at line 2703 of file ObjectClass.cpp.
References checkVirtualFunctions(), getObjectSize(), getObjectTypeNumber(), Memory::isValidSize(), memoryObject, T_Last_Class_Type, and MemoryObject::virtualFunctionTable.
Referenced by setObjectSize(), and MemorySegmentSet::validateObject().
logicalValue()
bool RexxInternalObject::logicalValue (logical_t & result) virtual
Convert an object to a logical value without raising an error.
Parameters
result The converted value.
Returns
true if this converted ok, false for an invalid logical.
Reimplemented in RexxInteger, NumberString, and RexxString.
Definition at line 507 of file ObjectClass.cpp.
References RexxString::logicalValue(), and requestString().
Referenced by NativeActivation::objectToValue().
makeArray()
ArrayClass * RexxInternalObject::makeArray () virtual
Handle an array conversion for a REXX object.
Returns
The converted array, or TheNilObject for no result returned.
Reimplemented in ArrayClass, RexxInteger, ListClass, MutableBuffer, NumberString, StemClass, RexxString, and HashCollection.
Definition at line 1214 of file ObjectClass.cpp.
References isBaseClass(), resultOrNil(), and TheNilObject.
Referenced by RexxObject::makeArrayRexx(), and requestArray().
makeProxiedObject()
void RexxInternalObject::makeProxiedObject () inline
Definition at line 311 of file ObjectClass.hpp.
References header, and ObjectHeader::makeProxiedObject().
Referenced by RexxClass::RexxClass(), and RexxNilObject::RexxNilObject().
makeProxy()
RexxObject * RexxInternalObject::makeProxy (Envelope * envelope) virtual
Create a proxy object for a "special" REXX object.
Parameters
envelope The target envelope.
Returns
The proxy object, which is usually a name.
Reimplemented in RexxClass, and DirectoryClass.
Definition at line 143 of file ObjectClass.cpp.
References new_proxy(), and TheNilObject.
Referenced by Envelope::flattenReference().
makeProxyObject()
void RexxInternalObject::makeProxyObject () inline
Definition at line 313 of file ObjectClass.hpp.
References header, and ObjectHeader::makeProxyObject().
Referenced by RexxString::newProxy().
makeString()
RexxString * RexxInternalObject::makeString () virtual
Handle a request to convert this object to a string value.
Returns
Either a string value or .nil.
Reimplemented in ArrayClass, RexxInteger, MutableBuffer, NumberString, QueueClass, StackFrameClass, StemClass, and RexxString.
Definition at line 1180 of file ObjectClass.cpp.
References isBaseClass(), resultOrNil(), and TheNilObject.
Referenced by StemClass::makeString(), RexxObject::makeStringRexx(), and requiredString().
nextObject() [1/2]
RexxInternalObject* RexxInternalObject::nextObject () inline
Definition at line 274 of file ObjectClass.hpp.
References getObjectSize().
Referenced by MemorySegment::gatherObjectStats(), MemorySegment::markAllObjects(), NumberString::maxMin(), MemoryObject::restoreImage(), MemorySegmentSet::sweepSingleSegment(), MemoryObject::unflattenObjectBuffer(), and MemoryObject::unflattenProxyObjects().
nextObject() [2/2]
RexxInternalObject* RexxInternalObject::nextObject (size_t l) inline
Definition at line 275 of file ObjectClass.hpp.
numberString()
NumberString * RexxInternalObject::numberString () virtual
Convert a primitive internal object to a number string equivalent.
Returns
A number string object representation for the object or .nil
Reimplemented in RexxInteger, NumberString, StemClass, RexxString, and VariableReference.
Definition at line 1129 of file ObjectClass.cpp.
References RexxString::numberString(), and requestString().
Referenced by LanguageParser::addText(), RexxString::comp(), NumberString::comp(), LanguageParser::constantDirective(), Numerics::int64Object(), NumberString::maxMin(), NumberString::modulo(), StemClass::numberString(), VariableReference::numberString(), Numerics::objectToInt64(), Numerics::objectToSignedInteger(), Numerics::objectToStringSize(), Numerics::objectToUnsignedInt64(), Numerics::objectToUnsignedInteger(), Numerics::objectToWholeNumber(), and NumberString::operatorArgument().
numberValue() [1/2]
bool RexxInternalObject::numberValue (wholenumber_t & result) virtual
Convert a REXX object to a whole number value
Parameters
result the returned converted number.
Returns
true if the number converted, false otherwise.
Reimplemented in RexxInteger, NumberString, StemClass, RexxString, and VariableReference.
Definition at line 1060 of file ObjectClass.cpp.
References RexxString::numberValue(), and requestString().
numberValue() [2/2]
bool RexxInternalObject::numberValue (wholenumber_t & result, wholenumber_t digits) virtual
Convert a REXX object to a whole number value
Parameters
result the returned converted number.
digits The digits under which the conversion needs to be performed.
Returns
true if the number converted, false otherwise.
Reimplemented in RexxInteger, NumberString, StemClass, RexxString, and VariableReference.
Definition at line 1047 of file ObjectClass.cpp.
References RexxString::numberValue(), and requestString().
Referenced by BUILTIN(), RexxActivation::command(), ArrayClass::WithSortComparator::compare(), compareTo(), CommandHandlerDispatcher::complete(), Activity::displayCondition(), Activity::errorNumber(), numberArgument(), StemClass::numberValue(), VariableReference::numberValue(), NumberString::power(), requestNumber(), requiredNumber(), and RexxStartDispatcher::run().
operator RexxObject *()
RexxInternalObject::operator RexxObject * () inline
Definition at line 254 of file ObjectClass.hpp.
primitiveMakeString()
RexxString * RexxInternalObject::primitiveMakeString () virtual
Handle a string conversion REQUEST for an internal object
Returns
Always return .nil because default behaviour is to not return anything here.
Reimplemented in ArrayClass, RexxInteger, MutableBuffer, NumberString, QueueClass, and RexxString.
Definition at line 1169 of file ObjectClass.cpp.
References TheNilObject.
Referenced by requestString(), requestStringNoNOSTRING(), and requiredString().
removedUninit()
void RexxInternalObject::removedUninit ()
Remove an UNINIT method from an object
Definition at line 2356 of file ObjectClass.cpp.
References clearHasUninit(), memoryObject, and MemoryObject::removeUninitObject().
Referenced by RexxObject::checkUninit().
requestArray()
ArrayClass * RexxInternalObject::requestArray () virtual
Request an array value from an object.
Returns
The converted array value, or .nil if it did not convert.
Reimplemented in ListClass.
Definition at line 1646 of file ObjectClass.cpp.
References isArray(), isBaseClass(), makeArray(), and resultOrNil().
Referenced by arrayArgument(), CommandIOConfiguration::createInputSource(), RexxObject::decodeMessageName(), RexxInstructionForward::execute(), RexxInstructionRaise::execute(), BaseExecutable::processExecutableSource(), and OverLoop::setup().
requestInteger()
RexxInteger * RexxInternalObject::requestInteger (wholenumber_t precision = Numerics::ARGUMENT_DIGITS)
Request an integer value from an object. If this is not a primitive object, the object will be converted to a string, and then the string integer value will be returned.
Parameters
precision The required precision for the conversion.
Returns
An integer object version of this object, if possible.
Definition at line 1422 of file ObjectClass.cpp.
References integerValue(), RexxString::integerValue(), isBaseClass(), and requestString().
Referenced by LanguageParser::addText().
requestNumber()
bool RexxInternalObject::requestNumber (wholenumber_t & result, wholenumber_t precision)
Request an object to convert itself into a number value.
Parameters
result The numeric result value.
precision The precision used for the conversion.
Returns
true if the object converted ok, false for a conversion failure.
Definition at line 1489 of file ObjectClass.cpp.
References numberValue().
Referenced by ExpressionStack::optionalIntegerArg(), ExpressionStack::requiredIntegerArg(), and LanguageParser::traceNew().
requestString()
RexxString * RexxInternalObject::requestString ()
Handle a string request for a REXX object. This will go through the whole search order to do the conversion.
Returns
The converted string value or TheNilObject.
Definition at line 1235 of file ObjectClass.cpp.
References ActivityManager::currentActivity, Error_No_result_object_message, isBaseClass(), OREF_NULL, primitiveMakeString(), Activity::raiseCondition(), reportException(), RexxObject::sendMessage(), stringValue(), and TheNilObject.
Referenced by RexxString::baseString(), Activity::callFunctionExit(), RexxString::comp(), NumberString::comp(), RexxObject::concatBlank(), RexxString::concatBlank(), RexxString::concatRexx(), copyIntoTail(), CommandIOConfiguration::createInputSource(), RexxClass::createMethodDictionary(), CommandIOConfiguration::createOutputTarget(), RexxActivation::createTraceObject(), Activity::display(), doubleValue(), RexxInstructionExpression::evaluateStringExpression(), RexxInstructionAddress::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionCommand::execute(), RexxInstructionForward::execute(), RexxInstructionNumeric::execute(), RexxInstructionRaise::execute(), RexxInstructionDynamicSignal::execute(), RexxInstructionTrace::execute(), integerValue(), RexxString::isEqual(), RexxVariableReference::list(), logicalValue(), numberString(), RexxString::numberString(), numberValue(), RexxString::numberValue(), ObjectToStringValue(), ExpressionStack::optionalStringArg(), RexxString::primitiveCaselessIsEqual(), RexxString::primitiveIsEqual(), RexxString::primitiveStrictComp(), NativeActivation::processArguments(), BaseExecutable::processNewExecutableArgs(), BaseExecutable::processNewFileExecutableArgs(), StemInputSource::read(), ArrayInputSource::read(), requestInteger(), ExpressionStack::requiredStringArg(), ForLoop::setup(), StemClass::sort(), ParseTrigger::stringTrigger(), Activity::traceOutput(), truthValue(), unsignedNumberValue(), and RexxString::unsignedNumberValue().
requestStringNoNOSTRING()
RexxString * RexxInternalObject::requestStringNoNOSTRING ()
Handle a string request for a REXX object. This will go through the whole search order to do the conversion, but will not raise a NOSTRING condition.
Returns
The converted string object.
Definition at line 1302 of file ObjectClass.cpp.
References isBaseClass(), primitiveMakeString(), RexxObject::sendMessage(), stringValue(), and TheNilObject.
requestUnsignedNumber()
bool RexxInternalObject::requestUnsignedNumber (size_t & result, wholenumber_t precision)
Request an object to convert itself into a number value.
Parameters
result The numeric result value.
precision The precision used for the conversion.
Returns
true if the object converted ok, false for a conversion failure.
Definition at line 1504 of file ObjectClass.cpp.
References unsignedNumberValue().
Referenced by RexxInstructionNumeric::execute(), ParseTrigger::integerTrigger(), and LanguageParser::optionsDirective().
requiredFloat()
double RexxInternalObject::requiredFloat (const char * position)
Request a double floating point number value from an object in a situation where a value is required.
Parameters
position The position of the argument used for error reporting.
precision The conversion precision.
Returns
The double floating point number.
Definition at line 1679 of file ObjectClass.cpp.
References doubleValue(), Error_Invalid_argument_number, and reportException().
requiredInteger() [1/2]
RexxInteger * RexxInternalObject::requiredInteger (const char * position, wholenumber_t precision)
Get an integer value in a situation where a value is requied.
Parameters
position The argument name for error messages.
precision The precision for the conversion.
Returns
The converted object value.
Definition at line 1467 of file ObjectClass.cpp.
References Error_Invalid_argument_whole, integerValue(), reportException(), and TheNilObject.
requiredInteger() [2/2]
RexxInteger * RexxInternalObject::requiredInteger (size_t position, wholenumber_t precision)
Get an integer value in a situation where a value is requied.
Parameters
position The argument position for error messages.
precision The precision for the conversion.
Returns
The converted object value.
Definition at line 1445 of file ObjectClass.cpp.
References Error_Incorrect_method_whole, integerValue(), reportException(), and TheNilObject.
requiredNonNegative() [1/2]
size_t RexxInternalObject::requiredNonNegative (const char * position, wholenumber_t precision = Numerics::ARGUMENT_DIGITS)
Request a non-negative whole number value from an object in a situation where a value is required.
Parameters
position The position of the argument used for error reporting.
precision The conversion precision.
Returns
The converted whole number.
Definition at line 1629 of file ObjectClass.cpp.
References Error_Invalid_argument_nonnegative, reportException(), and unsignedNumberValue().
requiredNonNegative() [2/2]
size_t RexxInternalObject::requiredNonNegative (size_t position, wholenumber_t precision = Numerics::ARGUMENT_DIGITS)
Request a non-negative whole number value from an object in a situation where a value is required.
Parameters
position The position of the argument used for error reporting.
precision The conversion precision.
Returns
The converted whole number.
Definition at line 1608 of file ObjectClass.cpp.
References Error_Incorrect_method_nonnegative, reportException(), and unsignedNumberValue().
Referenced by nonNegativeArgument().
requiredNumber() [1/2]
wholenumber_t RexxInternalObject::requiredNumber (const char * position, wholenumber_t precision = Numerics::ARGUMENT_DIGITS)
Request a whole number value from an object in a situation where a value is required.
Parameters
position The position of the argument used for error reporting.
precision The conversion precision.
Returns
The converted whole number.
Definition at line 1542 of file ObjectClass.cpp.
References Error_Invalid_argument_whole, numberValue(), and reportException().
requiredNumber() [2/2]
wholenumber_t RexxInternalObject::requiredNumber (size_t position, wholenumber_t precision = Numerics::ARGUMENT_DIGITS)
Request a whole number value from an object in a situation where a value is required.
Parameters
position The position of the argument used for error reporting.
precision The conversion precision.
Returns
The converted whole number.
Definition at line 1520 of file ObjectClass.cpp.
References Error_Incorrect_method_whole, numberValue(), and reportException().
requiredPositive() [1/2]
size_t RexxInternalObject::requiredPositive (const char * position, wholenumber_t precision = Numerics::ARGUMENT_DIGITS)
Request a positive whole number value from an object in a situation where a value is required.
Parameters
position The position of the argument used for error reporting.
precision The conversion precision.
Returns
The converted whole number.
Definition at line 1586 of file ObjectClass.cpp.
References Error_Invalid_argument_positive, reportException(), and unsignedNumberValue().
requiredPositive() [2/2]
size_t RexxInternalObject::requiredPositive (size_t position, wholenumber_t precision = Numerics::ARGUMENT_DIGITS)
Request a positive whole number value from an object in a situation where a value is required.
Parameters
position The position of the argument used for error reporting.
precision The conversion precision.
Returns
The converted whole number.
Definition at line 1564 of file ObjectClass.cpp.
References Error_Incorrect_method_positive, reportException(), and unsignedNumberValue().
Referenced by ArrayClass::dimensionRexx(), optionalPositive(), and ArrayClass::validateSingleDimensionIndex().
requiredString() [1/3]
RexxString * RexxInternalObject::requiredString ()
Base method for converting a Rexx object into a required string value. This takes the conversion as far as it can without reporting an error.
Returns
The converted string value or the .nil if this did not convert.
Definition at line 1341 of file ObjectClass.cpp.
References isBaseClass(), makeString(), primitiveMakeString(), resultOrNil(), and TheNilObject.
Referenced by requiredString().
requiredString() [2/3]
RexxString * RexxInternalObject::requiredString (const char * name)
Handle a string request for a REXX object in a context where the object MUST have a string value.
Parameters
name The name of the argument.
Returns
The converted string value.
Definition at line 1397 of file ObjectClass.cpp.
References Error_Invalid_argument_string, reportException(), requiredString(), and TheNilObject.
requiredString() [3/3]
RexxString * RexxInternalObject::requiredString (size_t position)
Handle a string request for a REXX object in a context where the object MUST have a string value.
Parameters
position The argument position for error reporting.
Returns
The converted string value.
Definition at line 1373 of file ObjectClass.cpp.
References Error_Invalid_argument_string, reportException(), requiredString(), and TheNilObject.
requiresProxyObject()
bool RexxInternalObject::requiresProxyObject () inline
Definition at line 312 of file ObjectClass.hpp.
References header, and ObjectHeader::requiresProxyObject().
Referenced by Envelope::flattenReference().
requiresUninit()
void RexxInternalObject::requiresUninit ()
Tag an object as having an UNINIT method
Definition at line 2167 of file ObjectClass.cpp.
References MemoryObject::addUninitObject(), memoryObject, and setHasUninit().
Referenced by RexxClass::checkUninit(), RexxObject::checkUninit(), RexxClass::completeNewObject(), and RexxObject::copy().
setBehaviour()
void RexxInternalObject::setBehaviour (RexxBehaviour * b) inline
Definition at line 322 of file ObjectClass.hpp.
References behaviour.
Referenced by RexxClass::completeNewObject(), RexxObject::copy(), MemoryObject::initialize(), RexxObject::initializeNewObject(), RexxBehaviour::restore(), RexxClass::RexxClass(), setObjectType(), and LanguageParser::sourceNewObject().
setHasNoReferences()
void RexxInternalObject::setHasNoReferences () inline
Definition at line 290 of file ObjectClass.hpp.
References header, and ObjectHeader::setHasNoReferences().
Referenced by RexxActivation::allocateStackFrame(), BufferClass::BufferClass(), NativeActivation::callNativeRoutine(), NativeActivation::callRegisteredRoutine(), Activity::cleanupStackFrame(), NativeActivation::NativeActivation(), RexxString::newString(), RexxString::newUpperString(), NumberArray::NumberArray(), RexxInteger::operator new(), PointerClass::operator new(), NumberString::operator new(), RexxActivation::popBlockInstruction(), Activity::popStackFrame(), RexxString::rawString(), Activity::returnAttach(), RexxActivation::RexxActivation(), NativeActivation::run(), and RexxString::setNumberString().
setHasReferences()
void RexxInternalObject::setHasReferences () inline
Definition at line 289 of file ObjectClass.hpp.
References header, and ObjectHeader::setHasReferences().
Referenced by RexxActivation::allocateStackFrame(), RexxObject::getObjectVariables(), RexxString::numberString(), RexxInteger::primitiveMakeString(), RexxString::setNumberString(), NumberString::setString(), and RexxInteger::setString().
setHasUninit()
void RexxInternalObject::setHasUninit () inline
Definition at line 294 of file ObjectClass.hpp.
References header, and ObjectHeader::setHasUninit().
Referenced by requiresUninit().
setInitHeader() [1/2]
void RexxInternalObject::setInitHeader (size_t markword) inline
Definition at line 284 of file ObjectClass.hpp.
References header, and ObjectHeader::initHeader().
setInitHeader() [2/2]
void RexxInternalObject::setInitHeader (size_t s, size_t markword) inline
Definition at line 283 of file ObjectClass.hpp.
References header, and ObjectHeader::initHeader().
setNewSpace()
void RexxInternalObject::setNewSpace () inline
Definition at line 309 of file ObjectClass.hpp.
References header, and ObjectHeader::setNewSpace().
Referenced by clone(), and Envelope::copyBuffer().
setNonPrimitive()
void RexxInternalObject::setNonPrimitive () inline
Definition at line 299 of file ObjectClass.hpp.
References header, and ObjectHeader::setNonPrimitive().
Referenced by ImageSaveMarkHandler::mark().
setObjectLive()
void RexxInternalObject::setObjectLive (size_t markword) inline
Definition at line 288 of file ObjectClass.hpp.
References header, and ObjectHeader::setObjectMark().
Referenced by MemoryObject::mark(), UnflatteningMarkHandler::mark(), ImageSaveMarkHandler::mark(), TracingMarkHandler::mark(), and MemoryObject::unflattenObjectBuffer().
setObjectMark()
void RexxInternalObject::setObjectMark (size_t markword) inline
Definition at line 303 of file ObjectClass.hpp.
References header, and ObjectHeader::setObjectMark().
setObjectSize()
void RexxInternalObject::setObjectSize (size_t s) inline
Definition at line 257 of file ObjectClass.hpp.
References dumpObject(), header, isValid(), and ObjectHeader::setObjectSize().
Referenced by MemoryObject::MemoryObject(), MemoryObject::reSize(), RexxBehaviour::restore(), and MemoryObject::unflattenObjectBuffer().
setObjectType()
void RexxInternalObject::setObjectType (size_t type)
Set the object virtual function table and behaviour to a particular type designation.
Parameters
type The internal type number.
Definition at line 164 of file ObjectClass.cpp.
References RexxBehaviour::getPrimitiveBehaviour(), memoryObject, setBehaviour(), setVirtualFunctions(), type, and MemoryObject::virtualFunctionTable.
setOldSpace()
void RexxInternalObject::setOldSpace () inline
Definition at line 310 of file ObjectClass.hpp.
References header, and ObjectHeader::setOldSpace().
Referenced by MemoryObject::restore(), RexxBehaviour::restore(), and MemoryObject::restoreImage().
setPrimitive()
void RexxInternalObject::setPrimitive () inline
Definition at line 298 of file ObjectClass.hpp.
References header, and ObjectHeader::setPrimitive().
Referenced by RexxClass::buildFinalClassBehaviour(), and ImageSaveMarkHandler::mark().
setReadyForUninit()
void RexxInternalObject::setReadyForUninit () inline
Definition at line 291 of file ObjectClass.hpp.
References header, and ObjectHeader::setReadyForUninit().
Referenced by MemoryObject::checkUninit().
setVirtualFunctions()
void RexxInternalObject::setVirtualFunctions (void * t) inline
Definition at line 279 of file ObjectClass.hpp.
Referenced by RexxObject::initializeNewObject(), MemoryObject::restoreImage(), MemoryObject::saveImage(), setObjectType(), and MemoryObject::unflattenObjectBuffer().
stringValue()
RexxString * RexxInternalObject::stringValue () virtual
Convert a primitive internal object to a string value
Returns
The string value of the internal object, which is always "".
Reimplemented in RexxInteger, MutableBuffer, NumberString, RexxObject, PointerClass, StackFrameClass, StemClass, RexxString, and VariableReference.
Definition at line 1141 of file ObjectClass.cpp.
Referenced by CompoundVariableTail::buildUnresolvedTail(), LanguageParser::createMethod(), LanguageParser::createProgram(), LanguageParser::createRoutine(), RexxInstructionOptions::execute(), MemoryObject::getGlobalName(), MemoryObject::getUpperGlobalName(), Activity::messageSubstitution(), requestString(), requestStringNoNOSTRING(), and ArrayClass::toString().
truthValue()
bool RexxInternalObject::truthValue (RexxErrorCodes errorCode) virtual
test the truth value of a primitive object. Raises an error if this does not have a valid truth value.
Parameters
errorCode The error code to issue.
Returns
The logical value of the object.
Reimplemented in RexxInteger, NumberString, and RexxString.
Definition at line 523 of file ObjectClass.cpp.
References requestString(), and RexxString::truthValue().
Referenced by RexxInteger::andOp(), RexxString::andOp(), SecurityManager::callSecurityManager(), WhileUntilLoop::checkUntil(), WhileUntilLoop::checkWhile(), RexxExpressionLogical::evaluate(), RexxInstructionGuard::execute(), RexxInstructionIf::execute(), RexxInstructionCaseWhen::execute(), isEqual(), RexxString::isEqual(), SupplierClass::loopAvailable(), RexxInteger::orOp(), RexxString::orOp(), NativeActivation::processArguments(), RexxInteger::xorOp(), and RexxString::xorOp().
uninit()
virtual void RexxInternalObject::uninit () inline virtual
Reimplemented in RexxObject.
Definition at line 333 of file ObjectClass.hpp.
Referenced by UninitDispatcher::run().
unsignedNumberValue() [1/2]
bool RexxInternalObject::unsignedNumberValue (size_t & result) virtual
Convert a REXX object to an unsigned number
Parameters
result the returned converted number.
Returns
true if the number converted, false otherwise.
Reimplemented in RexxInteger, NumberString, StemClass, RexxString, and VariableReference.
Definition at line 1088 of file ObjectClass.cpp.
References requestString(), and RexxString::unsignedNumberValue().
unsignedNumberValue() [2/2]
bool RexxInternalObject::unsignedNumberValue (size_t & result, wholenumber_t digits) virtual
Convert a REXX object to an unsigned number
Parameters
result the returned converted number.
digits The digits under which the conversion needs to be performed.
Returns
true if the number converted, false otherwise.
Reimplemented in RexxInteger, NumberString, StemClass, RexxString, and VariableReference.
Definition at line 1074 of file ObjectClass.cpp.
References requestString(), and RexxString::unsignedNumberValue().
Referenced by StemInputSource::init(), StemOutputTarget::init(), lengthArgument(), positionArgument(), requestUnsignedNumber(), requiredNonNegative(), requiredPositive(), StemClass::sort(), StemClass::unsignedNumberValue(), VariableReference::unsignedNumberValue(), and ListClass::validateIndex().
Member Data Documentation
behaviour
RexxBehaviour* RexxInternalObject::behaviour
Definition at line 397 of file ObjectClass.hpp.
Referenced by RexxObject::behaviourObject(), RexxClass::buildFinalClassBehaviour(), RexxObject::callOperatorMethod(), RexxObject::classObject(), RexxObject::copy(), Envelope::copyBuffer(), RexxObject::defaultName(), RexxClass::defineClassMethod(), RexxObject::defineInstanceMethod(), RexxObject::defineInstanceMethods(), MemoryObject::defineMethod(), MemoryObject::definePrivateMethod(), MemoryObject::defineProtectedMethod(), MemoryObject::defineUnguardedMethod(), RexxObject::deleteInstanceMethod(), RexxClass::enhanced(), RexxClass::getBehaviourDictionary(), getObjectType(), getObjectTypeNumber(), RexxObject::hasMethod(), RexxClass::inherit(), RexxObject::instanceMethod(), RexxObject::instanceMethods(), isBaseClass(), isObjectType(), isSameType(), isSubClassOrEnhanced(), MemoryObject::mark(), ImageSaveMarkHandler::mark(), MemorySegment::markAllObjects(), RexxObject::messageSend(), RexxObject::methodLookup(), RexxObject::processUnknown(), RexxClass::removeClassMethod(), RexxClass::removeSetupMethods(), RexxObject::requestRexx(), MemoryObject::restoreImage(), RexxBehaviour::RexxBehaviour(), RexxClass::RexxClass(), MemoryObject::saveImage(), setBehaviour(), RexxClass::subclass(), RexxObject::superMethod(), RexxObject::superScope(), MemoryObject::unflattenObjectBuffer(), RexxClass::updateSubClasses(), and RexxObject::validateScopeOverride().
header
ObjectHeader RexxInternalObject::header
Definition at line 396 of file ObjectClass.hpp.
Referenced by clearHasUninit(), clearObjectMark(), clone(), getObjectSize(), hasNoReferences(), hasReferences(), hasUninit(), RexxObject::initializeNewObject(), isNewSpace(), isNonPrimitive(), isObjectDead(), isObjectLive(), isObjectMarked(), isOldSpace(), isPrimitive(), isProxyObject(), isReadyForUninit(), makeProxiedObject(), makeProxyObject(), requiresProxyObject(), RexxBehaviour::RexxBehaviour(), setHasNoReferences(), setHasReferences(), setHasUninit(), setInitHeader(), setNewSpace(), setNonPrimitive(), setObjectLive(), setObjectMark(), setObjectSize(), setOldSpace(), setPrimitive(), and setReadyForUninit().
The documentation for this class was generated from the following files:
ObjectClass.hpp
ObjectClass.cpp