ooRexx: ArrayClass::BaseSortComparator Class Reference
ArrayClass::BaseSortComparator Class Reference
#include <ArrayClass.hpp>
Public Member Functions
BaseSortComparator ()
virtual wholenumber_t compare (RexxInternalObject *first, RexxInternalObject *second)
Detailed Description
Our base sort comparator, which just uses a compareTo method.
Definition at line 112 of file ArrayClass.hpp.
Constructor & Destructor Documentation
BaseSortComparator()
ArrayClass::BaseSortComparator::BaseSortComparator () inline
Definition at line 115 of file ArrayClass.hpp.
Member Function Documentation
compare()
wholenumber_t ArrayClass::BaseSortComparator::compare (RexxInternalObject * first, RexxInternalObject * second) virtual
Reimplemented in ArrayClass::WithSortComparator.
Definition at line 2891 of file ArrayClass.cpp.
References RexxInternalObject::compareTo().
Referenced by ArrayClass::find(), ArrayClass::merge(), and ArrayClass::mergeSort().
The documentation for this class was generated from the following files:
ArrayClass.hpp
ArrayClass.cpp