ooRexx: SysNamedPipeConnection Class Reference
SysNamedPipeConnection Class Reference
#include <SysCSNamedPipeStream.hpp>
Public Member Functions
SysNamedPipeConnection ()
SysNamedPipeConnection (HANDLE h)
SysNamedPipeConnection (const char *pipe)
~SysNamedPipeConnection ()
bool read (void *buf, size_t bufsize, size_t *bytesread) override
bool write (void *buf, size_t bufsize, size_t *byteswritten) override
bool write (void *buf, size_t bufsize, void *buf2, size_t buf2size, size_t *byteswritten) override
bool disconnect () override
bool connect (const char *pipeName)
Public Member Functions inherited from ApiConnection
ApiConnection ()
virtual ~ApiConnection ()
CSErrorCodeT getError ()
bool isClean ()
char * getMessageBuffer (size_t size)
void returnMessageBuffer (void *)
Protected Attributes
HANDLE pipeHandle
Protected Attributes inherited from ApiConnection
CSErrorCodeT errcode
char * messageBuffer
Additional Inherited Members
Protected Types inherited from ApiConnection
enum { MAX_CACHED_BUFFER = 4096 }
Detailed Description
Definition at line 44 of file SysCSNamedPipeStream.hpp.
Constructor & Destructor Documentation
SysNamedPipeConnection() [1/3]
SysNamedPipeConnection::SysNamedPipeConnection () inline
Definition at line 47 of file SysCSNamedPipeStream.hpp.
SysNamedPipeConnection() [2/3]
SysNamedPipeConnection::SysNamedPipeConnection (HANDLE h) inline
Definition at line 48 of file SysCSNamedPipeStream.hpp.
SysNamedPipeConnection() [3/3]
SysNamedPipeConnection::SysNamedPipeConnection (const char * pipe) inline
Definition at line 49 of file SysCSNamedPipeStream.hpp.
References connect().
~SysNamedPipeConnection()
SysNamedPipeConnection::~SysNamedPipeConnection () inline
Definition at line 50 of file SysCSNamedPipeStream.hpp.
Member Function Documentation
connect()
bool SysNamedPipeConnection::connect (const char * pipeName)
Open a connection to a named pipe.
Parameters
pipeName The name of the target pipe
Returns
True on success, otherwise false.
Definition at line 209 of file SysCSNamedPipeStream.cpp.
References CSERROR_CONNX_FAILED, CSERROR_OK, ApiConnection::errcode, and pipeHandle.
Referenced by SysNamedPipeConnection().
disconnect()
bool SysNamedPipeConnection::disconnect () override virtual
Close the server connection.
Returns
True on an error, otherwise false
Reimplemented from ApiConnection.
Definition at line 182 of file SysCSNamedPipeStream.cpp.
References CSERROR_INTERNAL, CSERROR_OK, ApiConnection::errcode, and pipeHandle.
read()
bool SysNamedPipeConnection::read (void * buf, size_t bufsize, size_t * bytesread) override virtual
Read from the connection.
Parameters
buf Target buffer for the read operation.
bufsize Size of the target buffer.
bytesread Number of bytes actually read.
Returns
True on an error, otherwise false
Implements ApiConnection.
Definition at line 66 of file SysCSNamedPipeStream.cpp.
References CSERROR_IO_FAILED, CSERROR_OK, ApiConnection::errcode, and pipeHandle.
write() [1/2]
bool SysNamedPipeConnection::write (void * buf, size_t bufsize, size_t * byteswritten) override virtual
Write a buffer to the connection.
Parameters
buf Source buffer for the write operation.
bufsize Size of the source buffer.
byteswritten Number of bytes actually written to the connection.
Returns
True on an error, otherwise false
Implements ApiConnection.
Definition at line 100 of file SysCSNamedPipeStream.cpp.
References CSERROR_IO_FAILED, CSERROR_OK, ApiConnection::errcode, and pipeHandle.
Referenced by write().
write() [2/2]
bool SysNamedPipeConnection::write (void * buf, size_t bufsize, void * buf2, size_t buf2size, size_t * byteswritten) override virtual
Write a multi-buffer message to the connection.
Parameters
buf Source buffer for the write operation.
bufsize Size of the source buffer.
byteswritten Number of bytes actually written to the connection.
Returns
True on an error, otherwise false
Implements ApiConnection.
Definition at line 134 of file SysCSNamedPipeStream.cpp.
References ApiConnection::getMessageBuffer(), ApiConnection::returnMessageBuffer(), and write().
Member Data Documentation
pipeHandle
HANDLE SysNamedPipeConnection::pipeHandle protected
Definition at line 62 of file SysCSNamedPipeStream.hpp.
Referenced by connect(), disconnect(), read(), and write().
The documentation for this class was generated from the following files:
SysCSNamedPipeStream.hpp
SysCSNamedPipeStream.cpp