ooRexx: HashContents Class Reference
HashContents Class Reference
#include <HashContents.hpp>
Classes
class ContentEntry
class IndexIterator
class ReverseTableIterator
class TableIterator
Public Types
typedef size_t ItemLink
Public Member Functions
HashContents ()
HashContents (size_t entries, size_t total)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
virtual bool isIndexEqual (RexxInternalObject *target, RexxInternalObject *entryIndex)
virtual bool isItemEqual (RexxInternalObject *target, RexxInternalObject *entryItem)
virtual ItemLink hashIndex (RexxInternalObject *index)
void initializeFreeChain ()
void setEntry (ItemLink position, RexxInternalObject *value, RexxInternalObject *index)
void clearEntry (ItemLink position)
void setNext (ItemLink position, ItemLink next)
void copyEntry (ItemLink target, ItemLink source)
void closeChain (ItemLink position, ItemLink previous)
void returnToFreeChain (ItemLink position)
void setValue (ItemLink position, RexxInternalObject *value)
bool isIndex (ItemLink position, RexxInternalObject *index)
bool isItem (ItemLink position, RexxInternalObject *item)
bool isItem (ItemLink position, RexxInternalObject *index, RexxInternalObject *item)
bool isAvailable (ItemLink postion)
bool isInUse (ItemLink postion)
ItemLink nextEntry (ItemLink position)
RexxInternalObject * entryValue (ItemLink position)
RexxInternalObject * entryIndex (ItemLink position)
bool isFull ()
bool hasCapacity (size_t count)
bool isBucketPosition (ItemLink position)
size_t capacity ()
size_t hashBucket ()
virtual void put (RexxInternalObject *value, RexxInternalObject *index)
size_t items ()
bool isEmpty ()
void append (RexxInternalObject *value, RexxInternalObject *index, ItemLink position)
void insert (RexxInternalObject *value, RexxInternalObject *index, ItemLink position)
RexxInternalObject * remove (RexxInternalObject *index)
void removeChainLink (ItemLink &position, ItemLink previous)
bool locateEntry (RexxInternalObject *index, ItemLink &position, ItemLink &previous)
bool locateEntry (RexxInternalObject *index, RexxInternalObject *item, ItemLink &position, ItemLink &previous)
bool locateItem (RexxInternalObject *item, ItemLink &position, ItemLink &previous)
void nextMatch (RexxInternalObject *index, ItemLink &position)
void iterateNext (ItemLink &position, ItemLink &nextBucket)
void iterateNextAndRemove (ItemLink &position, ItemLink &nextBucket)
void iterateNextReverse (ItemLink &position, ItemLink &nextBucket)
void locateNextBucketEnd (ItemLink &position, ItemLink &currentBucket)
void locatePreviousEntry (ItemLink &position, ItemLink currentBucket)
ArrayClass * removeAll (RexxInternalObject *index)
RexxInternalObject * removeItem (RexxInternalObject *value, RexxInternalObject *index)
bool hasItem (RexxInternalObject *value, RexxInternalObject *index)
bool hasItem (RexxInternalObject *item)
bool hasIndex (RexxInternalObject *index)
RexxInternalObject * removeItem (RexxInternalObject *item)
RexxInternalObject * nextItem (RexxInternalObject *value, RexxInternalObject *index)
RexxInternalObject * get (RexxInternalObject *index)
ArrayClass * getAll (RexxInternalObject *index)
size_t countAllIndex (RexxInternalObject *index, ItemLink &anchorPosition)
size_t countAllItem (RexxInternalObject *item)
ArrayClass * allIndex (RexxInternalObject *item)
RexxInternalObject * getIndex (RexxInternalObject *item)
void merge (HashCollection *target)
void putAll (HashCollection *target)
void reMerge (HashContents *newHash)
void mergeItem (RexxInternalObject *, RexxInternalObject *index)
void mergePut (RexxInternalObject *item, RexxInternalObject *index)
ArrayClass * allItems ()
void empty ()
ArrayClass * allIndexes ()
ArrayClass * uniqueIndexes ()
SupplierClass * supplier ()
SupplierClass * supplier (RexxInternalObject *index)
void reHash (HashContents *newHash)
void add (RexxInternalObject *item, RexxInternalObject *index)
void addFront (RexxInternalObject *item, RexxInternalObject *index)
void copyValues ()
size_t items (RexxInternalObject *item)
IndexIterator iterator (RexxInternalObject *index)
TableIterator iterator ()
ReverseTableIterator reverseIterator ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Attributes
static const ItemLink NoMore = SIZE_MAX
static const ItemLink NoLink = SIZE_MAX
Protected Attributes
size_t bucketSize
size_t totalSize
size_t itemCount
ItemLink freeChain
ContentEntry entries [1]
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Base class for storing the contents of a hash-based collection. This version bases all index and item searches on object equality. Subclasses can override these default rules. This is the backing contents only, there is a separate collection class that implements the collection interface and allocates a backing context.
Definition at line 60 of file HashContents.hpp.
Member Typedef Documentation
ItemLink
typedef size_t HashContents::ItemLink
Definition at line 64 of file HashContents.hpp.
Constructor & Destructor Documentation
HashContents() [1/2]
HashContents::HashContents () inline
Definition at line 174 of file HashContents.hpp.
HashContents() [2/2]
HashContents::HashContents (size_t entries, size_t total)
Construct a HashContent item of the given size.
Parameters
entries The total number of entries in the object.
Definition at line 125 of file HashContents.cpp.
References bucketSize, RexxInternalObject::clearObject(), entries, initializeFreeChain(), and totalSize.
Member Function Documentation
add()
void HashContents::add (RexxInternalObject * item, RexxInternalObject * index)
Add an element to a hash table without accounting for duplicates. This is not to be used directly, but collections that allow multiple occurences of an index (e.g relation and bag) should override the put() virtual method and redirect it to this method.
Parameters
item The value to add.
index The index this will be added under.
Returns
True if this was successfully added, false if the table is full.
Definition at line 1606 of file HashContents.cpp.
References append(), entries, hashIndex(), isAvailable(), itemCount, HashContents::ContentEntry::next, NoLink, NoMore, and setEntry().
Referenced by HashCollection::add(), and reMerge().
addFront()
void HashContents::addFront (RexxInternalObject * item, RexxInternalObject * index)
Add an element to a hash table without accounting for duplicates. This operation adds the item to the front of the bucket chain so that a search on this index will return this item, essentially overriding any other item already in the collection.
Parameters
item The value to add.
index The index this will be added under.
Returns
True if this was successfully added, false if the table is full.
Definition at line 1650 of file HashContents.cpp.
References hashIndex(), insert(), isAvailable(), itemCount, and setEntry().
Referenced by HashCollection::addFront(), and MultiValueContents::put().
allIndex()
ArrayClass * HashContents::allIndex (RexxInternalObject * item)
Return an array of all index values that match a given item value.
Parameters
item The target item.
Returns
An array of all matching indexes.
Definition at line 1097 of file HashContents.cpp.
References bucketSize, countAllItem(), entryIndex(), isInUse(), isItem(), new_array(), nextEntry(), NoMore, and ArrayClass::put().
Referenced by RelationClass::allIndexRexx().
allIndexes()
ArrayClass * HashContents::allIndexes ()
Create an array of all index items.
Returns
An array of all indexes.
Definition at line 1417 of file HashContents.cpp.
References bucketSize, entryIndex(), isInUse(), itemCount, new_array(), nextEntry(), NoMore, and ArrayClass::put().
Referenced by HashCollection::allIndexes(), and DirectoryClass::allIndexes().
allItems()
ArrayClass * HashContents::allItems ()
Return an array containing all of the table item objects.
Returns
An array containing all of the items.
Definition at line 1347 of file HashContents.cpp.
References bucketSize, entryValue(), isInUse(), itemCount, new_array(), nextEntry(), NoMore, and ArrayClass::put().
Referenced by HashCollection::allItems(), and DirectoryClass::allItems().
append()
void HashContents::append (RexxInternalObject * value, RexxInternalObject * index, ItemLink position)
Add a link to a slot position chain.
Parameters
value The value to add.
index The index value.
position The position of the last link in the chain.
Definition at line 275 of file HashContents.cpp.
References entries, freeChain, itemCount, Interpreter::logicError(), HashContents::ContentEntry::next, NoMore, setEntry(), and setNext().
Referenced by add(), mergePut(), and put().
capacity()
size_t HashContents::capacity () inline
Return the total current capacity.
Returns
The total number of items this table can hold.
Definition at line 316 of file HashContents.hpp.
References totalSize.
Referenced by HashCollection::ensureCapacity(), VariableDictionary::ensureCapacity(), HashCollection::expandContents(), and VariableDictionary::expandContents().
clearEntry()
void HashContents::clearEntry (ItemLink position)
clear an entry in the chain
Parameters
position The entry position.
Definition at line 1712 of file HashContents.cpp.
References entries, HashContents::ContentEntry::next, NoMore, OREF_NULL, and setField.
Referenced by empty(), removeChainLink(), and returnToFreeChain().
closeChain()
void HashContents::closeChain (ItemLink position, ItemLink previous) inline
Definition at line 227 of file HashContents.hpp.
References entries, HashContents::ContentEntry::next, and returnToFreeChain().
Referenced by removeChainLink().
copyEntry()
void HashContents::copyEntry (ItemLink target, ItemLink source) inline
Definition at line 219 of file HashContents.hpp.
References entries, entryIndex(), entryValue(), HashContents::ContentEntry::next, and setEntry().
Referenced by insert(), and removeChainLink().
copyValues()
void HashContents::copyValues ()
copy all of the values contained in this table.
Definition at line 1674 of file HashContents.cpp.
References bucketSize, RexxInternalObject::copy(), entryValue(), isInUse(), nextEntry(), NoMore, and setValue().
Referenced by HashCollection::copyValues(), and VariableDictionary::copyValues().
countAllIndex()
size_t HashContents::countAllIndex (RexxInternalObject * index, ItemLink & anchorPosition)
Return a count of all entries with a given index.
Parameters
index
anchorPosition The returned hash bucket position for the head of the chain.
Returns
The count of matching items.
Definition at line 1028 of file HashContents.cpp.
References hashIndex(), isIndex(), isInUse(), nextEntry(), and NoMore.
Referenced by getAll(), items(), and removeAll().
countAllItem()
size_t HashContents::countAllItem (RexxInternalObject * item)
Return a count of all entries with a given item.
Parameters
index
Returns
The count of matching items.
Definition at line 1056 of file HashContents.cpp.
References bucketSize, isInUse(), isItem(), nextEntry(), and NoMore.
Referenced by allIndex().
empty()
void HashContents::empty ()
Empty a HashTable.
Definition at line 1388 of file HashContents.cpp.
References bucketSize, clearEntry(), initializeFreeChain(), isInUse(), nextEntry(), and NoMore.
Referenced by HashCollection::empty(), DirectoryClass::empty(), HashCollection::emptyRexx(), HashCollection::expandContents(), and VariableDictionary::expandContents().
entryIndex()
RexxInternalObject* HashContents::entryIndex (ItemLink position) inline
Definition at line 291 of file HashContents.hpp.
References entries, and HashContents::ContentEntry::index.
Referenced by allIndex(), allIndexes(), copyEntry(), getIndex(), HashContents::IndexIterator::index(), HashContents::TableIterator::index(), HashContents::ReverseTableIterator::index(), isIndexEqual(), EqualityHashContents::isIndexEqual(), StringHashContents::isIndexEqual(), merge(), putAll(), reHash(), reMerge(), supplier(), and uniqueIndexes().
entryValue()
RexxInternalObject* HashContents::entryValue (ItemLink position) inline
Definition at line 285 of file HashContents.hpp.
References entries, and HashContents::ContentEntry::value.
Referenced by allItems(), copyEntry(), copyValues(), get(), getAll(), merge(), nextItem(), putAll(), reHash(), reMerge(), remove(), removeAll(), removeItem(), supplier(), HashContents::IndexIterator::value(), HashContents::TableIterator::value(), and HashContents::ReverseTableIterator::value().
flatten()
void HashContents::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxVirtualBase.
Definition at line 204 of file HashContents.cpp.
References cleanUpFlatten, entries, flattenRef, setUpFlatten, and totalSize.
get()
RexxInternalObject * HashContents::get (RexxInternalObject * index)
Get an item from the hash table.
Parameters
index The target index.
Returns
The associated value item, or OREF_NULL if not located.
Definition at line 927 of file HashContents.cpp.
References entryValue(), locateEntry(), and OREF_NULL.
Referenced by DirectoryClass::get(), HashCollection::get(), IndexOnlyHashCollection::getIndex(), nextItem(), and VariableDictionary::resolveVariable().
getAll()
ArrayClass * HashContents::getAll (RexxInternalObject * index)
Get all items with an associated index from the table.
Parameters
index The target index value.
Returns
An array containing all matching entries (zero length if none)
Definition at line 989 of file HashContents.cpp.
References countAllIndex(), entryValue(), isIndex(), new_array(), nextEntry(), NoLink, and ArrayClass::put().
Referenced by RelationClass::allAt(), HashCollection::allAtRexx(), and supplier().
getIndex()
RexxInternalObject * HashContents::getIndex (RexxInternalObject * item)
Return an index associated with the supplied item. The result is undefined for items that are referenced by multiple indices.
Parameters
item The target item.
Returns
The index value, or OREF_NULL if not found.
Definition at line 1150 of file HashContents.cpp.
References entryIndex(), locateItem(), and OREF_NULL.
Referenced by DirectoryClass::getIndex(), and HashCollection::getIndex().
hasCapacity()
bool HashContents::hasCapacity (size_t count) inline
Definition at line 303 of file HashContents.hpp.
References itemCount, and totalSize.
Referenced by HashCollection::ensureCapacity(), and VariableDictionary::ensureCapacity().
hashBucket()
size_t HashContents::hashBucket () inline
Return the bucket size of the contents.
Returns
The hash bucket size
Definition at line 327 of file HashContents.hpp.
References bucketSize.
hashIndex()
virtual ItemLink HashContents::hashIndex (RexxInternalObject * index) inline virtual
Reimplemented in EqualityHashContents, and StringHashContents.
Definition at line 197 of file HashContents.hpp.
References bucketSize, and RexxInternalObject::getHashValue().
Referenced by add(), addFront(), countAllIndex(), locateEntry(), mergePut(), nextItem(), and put().
hasIndex()
bool HashContents::hasIndex (RexxInternalObject * index)
Test if an index exists in the hash collection.
Parameters
index The target index.
Returns
True if we have an item at this index, false otherwise.
Definition at line 949 of file HashContents.cpp.
References locateEntry().
Referenced by HashCollection::hasIndex(), and DirectoryClass::hasIndex().
hasItem() [1/2]
bool HashContents::hasItem (RexxInternalObject * item)
Determine if an item is in the table.
Parameters
index The target item.
Returns
true if the index is in the table, false otherwise.
Definition at line 837 of file HashContents.cpp.
References locateItem().
hasItem() [2/2]
bool HashContents::hasItem (RexxInternalObject * value, RexxInternalObject * index)
Determine if an item is in the table using the value/index pair.
Parameters
value The target value.
index The target index.
Returns
true if the pair is in the table, false otherwise.
Definition at line 814 of file HashContents.cpp.
References locateEntry(), and OREF_NULL.
Referenced by HashCollection::hasItem(), IndexOnlyHashCollection::hasItem(), and RelationClass::hasItemRexx().
initializeFreeChain()
void HashContents::initializeFreeChain ()
Initialize the free chains, either at construction time or after an empty() operation.
Definition at line 145 of file HashContents.cpp.
References bucketSize, entries, freeChain, itemCount, HashContents::ContentEntry::next, NoMore, and totalSize.
Referenced by empty(), and HashContents().
insert()
void HashContents::insert (RexxInternalObject * value, RexxInternalObject * index, ItemLink position)
Add a link to a slot position chain This adds it at the FRONT of the chain.
Parameters
value The value to add.
index The index value.
position The position of the chain anchor.
Definition at line 313 of file HashContents.cpp.
References copyEntry(), entries, freeChain, itemCount, Interpreter::logicError(), HashContents::ContentEntry::next, NoMore, setEntry(), and setNext().
Referenced by addFront().
isAvailable()
bool HashContents::isAvailable (ItemLink postion) inline
Definition at line 267 of file HashContents.hpp.
References entries, and HashContents::ContentEntry::isAvailable().
Referenced by add(), addFront(), mergePut(), and put().
isBucketPosition()
bool HashContents::isBucketPosition (ItemLink position) inline
Definition at line 309 of file HashContents.hpp.
References bucketSize.
Referenced by iterateNextAndRemove().
isEmpty()
bool HashContents::isEmpty () inline
Definition at line 337 of file HashContents.hpp.
References itemCount.
Referenced by HashCollection::isEmptyRexx().
isFull()
bool HashContents::isFull () inline
Definition at line 297 of file HashContents.hpp.
References freeChain, and NoMore.
Referenced by HashCollection::checkFull(), and VariableDictionary::checkFull().
isIndex()
bool HashContents::isIndex (ItemLink position, RexxInternalObject * index) inline
Definition at line 249 of file HashContents.hpp.
References entries, and isIndexEqual().
Referenced by countAllIndex(), getAll(), locateEntry(), mergePut(), nextMatch(), put(), and removeAll().
isIndexEqual()
virtual bool HashContents::isIndexEqual (RexxInternalObject * target, RexxInternalObject * entryIndex) inline virtual
Reimplemented in EqualityHashContents, and StringHashContents.
Definition at line 183 of file HashContents.hpp.
References entryIndex().
Referenced by BagClass::hasItemRexx(), isIndex(), isItem(), BagClass::removeItemRexx(), and IndexOnlyHashCollection::validateValueIndex().
isInUse()
bool HashContents::isInUse (ItemLink postion) inline
Definition at line 273 of file HashContents.hpp.
References entries, and HashContents::ContentEntry::isAvailable().
Referenced by allIndex(), allIndexes(), allItems(), copyValues(), countAllIndex(), countAllItem(), empty(), iterateNext(), locateEntry(), locateItem(), locateNextBucketEnd(), merge(), nextItem(), putAll(), reHash(), reMerge(), supplier(), and uniqueIndexes().
isItem() [1/2]
bool HashContents::isItem (ItemLink position, RexxInternalObject * index, RexxInternalObject * item) inline
Definition at line 261 of file HashContents.hpp.
References entries, isIndexEqual(), and isItemEqual().
isItem() [2/2]
bool HashContents::isItem (ItemLink position, RexxInternalObject * item) inline
Definition at line 255 of file HashContents.hpp.
References entries, and isItemEqual().
Referenced by allIndex(), countAllItem(), locateEntry(), and locateItem().
isItemEqual()
virtual bool HashContents::isItemEqual (RexxInternalObject * target, RexxInternalObject * entryItem) inline virtual
Reimplemented in EqualityHashContents.
Definition at line 190 of file HashContents.hpp.
Referenced by isItem().
items() [1/2]
size_t HashContents::items () inline
Definition at line 336 of file HashContents.hpp.
References itemCount.
Referenced by VariableDictionary::getAllVariables(), VariableDictionary::getVariableDirectory(), HashCollection::items(), DirectoryClass::items(), items(), RelationClass::itemsRexx(), and uniqueIndexes().
items() [2/2]
size_t HashContents::items (RexxInternalObject * index)
Return a count of either all items, or all items with a given index.
Parameters
index The optional index.
Returns
The appropriate count.
Definition at line 967 of file HashContents.cpp.
References countAllIndex(), items(), and OREF_NULL.
iterateNext()
void HashContents::iterateNext (ItemLink & position, ItemLink & nextBucket)
Iterate to the next occupied entry of the list.
Parameters
position The starting position.
nextBucket The next bucket to step to once this chain is used up.
Definition at line 489 of file HashContents.cpp.
References bucketSize, isInUse(), nextEntry(), and NoMore.
Referenced by iterateNextAndRemove(), iterator(), and HashContents::TableIterator::next().
iterateNextAndRemove()
void HashContents::iterateNextAndRemove (ItemLink & position, ItemLink & nextBucket)
Safely remove an item from the table and advance the iterator position to the next location.
Parameters
position The current position.
nextBucket The nextBucket we advance to.
Definition at line 524 of file HashContents.cpp.
References isBucketPosition(), iterateNext(), locatePreviousEntry(), nextEntry(), NoLink, NoMore, and removeChainLink().
Referenced by HashContents::TableIterator::removeAndAdvance().
iterateNextReverse()
void HashContents::iterateNextReverse (ItemLink & position, ItemLink & currentBucket)
Iterate to the next occupied entry of the list in reverse bucket order.
Parameters
position The starting position.
currentBucket The current bucket we're iterating on.
Definition at line 578 of file HashContents.cpp.
References locateNextBucketEnd(), and locatePreviousEntry().
Referenced by HashContents::ReverseTableIterator::next().
iterator() [1/2]
HashContents::TableIterator HashContents::iterator ()
Create an iterator for traversing through all of the entries of the table
Returns
A TableIterator item.
Definition at line 1761 of file HashContents.cpp.
References iterateNext(), and NoMore.
iterator() [2/2]
HashContents::IndexIterator HashContents::iterator (RexxInternalObject * index)
Create an iterator for traversing through all of the entries with a given index.
Parameters
index The target index.
Returns
An IndexIterator item.
Definition at line 1742 of file HashContents.cpp.
References locateEntry().
Referenced by MethodDictionary::addMethod(), MethodDictionary::findSuperMethod(), VariableDictionary::getAllVariables(), MethodDictionary::getMethods(), VariableDictionary::getVariableDirectory(), HashCollection::iterator(), MethodDictionary::setMethodScope(), and VariableDictionary::VariableIterator::VariableIterator().
live()
void HashContents::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 174 of file HashContents.cpp.
References entries, memory_mark, and totalSize.
liveGeneral()
void HashContents::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 189 of file HashContents.cpp.
References entries, memory_mark_general, and totalSize.
locateEntry() [1/2]
bool HashContents::locateEntry (RexxInternalObject * index, ItemLink & position, ItemLink & previous)
Locate an entry in the table.
Parameters
index The target entry index.
position The return position if located.
previous The previous link if located. Has the value NoLink if the located item is the chain anchor.
Returns
true if the item is located, false for a failure
Definition at line 420 of file HashContents.cpp.
References hashIndex(), isIndex(), isInUse(), nextEntry(), NoLink, and NoMore.
Referenced by get(), hasIndex(), hasItem(), iterator(), remove(), and removeItem().
locateEntry() [2/2]
bool HashContents::locateEntry (RexxInternalObject * index, RexxInternalObject * item, ItemLink & position, ItemLink & previous)
Locate an entry in the table by index/item pair
Parameters
index The target entry index.
position The return position if located.
previous The previous link if located. Has the value NoLink if the located item is the chain anchor.
Returns
true if the item is located, false for a failure
Definition at line 664 of file HashContents.cpp.
References hashIndex(), isInUse(), isItem(), nextEntry(), NoLink, and NoMore.
locateItem()
bool HashContents::locateItem (RexxInternalObject * item, ItemLink & position, ItemLink & previous)
Locate an item in the table.
Parameters
item The target item.
position The return position if located.
previous The previous link if located. Has the value NoLink if the located item is the chain anchor.
Returns
true if the item is located, false for a failure
Definition at line 700 of file HashContents.cpp.
References bucketSize, isInUse(), isItem(), nextEntry(), NoLink, and NoMore.
Referenced by getIndex(), hasItem(), and removeItem().
locateNextBucketEnd()
void HashContents::locateNextBucketEnd (ItemLink & position, ItemLink & currentBucket)
Locate the end of the next occupied hash bucket in this collection.
Parameters
position The returned position (NoMore indicates we've hit the end)
currentBucket The starting bucket to search. Updated to the new bucket if something is found.
Definition at line 609 of file HashContents.cpp.
References bucketSize, isInUse(), nextEntry(), and NoMore.
Referenced by iterateNextReverse(), and reverseIterator().
locatePreviousEntry()
void HashContents::locatePreviousEntry (ItemLink & position, ItemLink currentBucket)
Locate the entry that precedes the current bucket item.
Parameters
position The current position in the chain. Note: we've already determined that we are not at the anchor position.
currentBucket The bucket anchor item.
Definition at line 643 of file HashContents.cpp.
References nextEntry().
Referenced by iterateNextAndRemove(), and iterateNextReverse().
merge()
void HashContents::merge (HashCollection * target)
Merge the contents of this collection into another table.
Parameters
target The target collection contents.
Definition at line 1171 of file HashContents.cpp.
References bucketSize, HashCollection::ensureCapacity(), entryIndex(), entryValue(), isInUse(), itemCount, HashCollection::mergeItem(), nextEntry(), and NoMore.
Referenced by HashCollection::merge().
mergeItem()
void HashContents::mergeItem (RexxInternalObject * item, RexxInternalObject * index)
Merge an item into this table without overwriting values that might have the same index. Used for building the method dictionaries.
Parameters
item The item value to merge.
index The associated index value.
Definition at line 1286 of file HashContents.cpp.
References mergePut().
Referenced by HashCollection::mergeItem().
mergePut()
void HashContents::mergePut (RexxInternalObject * item, RexxInternalObject * index)
Add an entry to the hash table, making sure we are not overwriting an existing item. This is used mostly for merging various internal tables.
Parameters
item The item value to add.
index The index to add.
Returns
true if we were able to add this (not full), false otherwise.
Definition at line 1303 of file HashContents.cpp.
References append(), entries, hashIndex(), isAvailable(), isIndex(), itemCount, HashContents::ContentEntry::next, NoLink, NoMore, and setEntry().
Referenced by mergeItem().
nextEntry()
ItemLink HashContents::nextEntry (ItemLink position) inline
Definition at line 279 of file HashContents.hpp.
References entries, and HashContents::ContentEntry::next.
Referenced by allIndex(), allIndexes(), allItems(), copyValues(), countAllIndex(), countAllItem(), empty(), getAll(), iterateNext(), iterateNextAndRemove(), locateEntry(), locateItem(), locateNextBucketEnd(), locatePreviousEntry(), merge(), nextItem(), nextMatch(), putAll(), reHash(), reMerge(), removeAll(), removeChainLink(), supplier(), and uniqueIndexes().
nextItem()
RexxInternalObject * HashContents::nextItem (RexxInternalObject * value, RexxInternalObject * index)
Return the next item with the key index that follows the given (value index) pair. Used only for superscope lookup. Note: This routine does the comparisons in as fast as way as possible, relying solely on object identify for a match. NOTE: this is a somewhat special purpose method used only for internal checks, so a lot of stuff is just done inline rather than in methods because those would be somewhat single purpose.
Parameters
value The target value.
index The target index
Returns
The located next value, or .nil if not found.
Definition at line 888 of file HashContents.cpp.
References entries, entryValue(), get(), hashIndex(), isInUse(), nextEntry(), NoMore, resultOrNil(), and TheNilObject.
nextMatch()
void HashContents::nextMatch (RexxInternalObject * index, ItemLink & position)
Locate the next entry in the table for a given index
Parameters
index The target entry index.
position The starting position for the search (the last match)
Definition at line 454 of file HashContents.cpp.
References isIndex(), nextEntry(), and NoMore.
Referenced by HashContents::IndexIterator::next().
put()
void HashContents::put (RexxInternalObject * value, RexxInternalObject * index) virtual
Put an item into the hashtable. Default behavior is to replace any existing items.
Parameters
value The value to insert.
_index The index to insert under.
Returns
true if was inserted ok, false if we need to expand the table.
Reimplemented in MultiValueContents.
Definition at line 226 of file HashContents.cpp.
References append(), entries, hashIndex(), isAvailable(), isIndex(), itemCount, HashContents::ContentEntry::next, NoLink, NoMore, setEntry(), and setValue().
Referenced by VariableDictionary::addVariable(), HashCollection::put(), and reHash().
putAll()
void HashContents::putAll (HashCollection * target)
Put the contents of this collection into another collection. This is different than merge, which does not replace existing items.
Parameters
target The target collection contents.
Definition at line 1205 of file HashContents.cpp.
References bucketSize, HashCollection::ensureCapacity(), entryIndex(), entryValue(), isInUse(), itemCount, nextEntry(), NoMore, and HashCollection::put().
Referenced by HashCollection::putAll().
reHash()
void HashContents::reHash (HashContents * newHash)
Rehash a hash collection because of a restore. This pushes everything into the new collection object.
Parameters
newHash The target collection object.
Definition at line 1573 of file HashContents.cpp.
References bucketSize, entryIndex(), entryValue(), isInUse(), nextEntry(), NoMore, and put().
Referenced by HashCollection::reHash().
reMerge()
void HashContents::reMerge (HashContents * newHash)
Merge a hash table into another hash table after a table expansion.
Parameters
newHash The target new table.
Definition at line 1238 of file HashContents.cpp.
References add(), bucketSize, entryIndex(), entryValue(), isInUse(), nextEntry(), and NoMore.
Referenced by HashCollection::expandContents(), and VariableDictionary::expandContents().
remove()
RexxInternalObject * HashContents::remove (RexxInternalObject * index)
Remove an item from the collection.
Parameters
index The index value
Returns
The removed object, or OREF_NULL if this was not found.
Definition at line 350 of file HashContents.cpp.
References entryValue(), locateEntry(), OREF_NULL, and removeChainLink().
Referenced by DirectoryClass::remove(), HashCollection::remove(), VariableDictionary::remove(), and DirectoryClass::setMethodRexx().
removeAll()
ArrayClass * HashContents::removeAll (RexxInternalObject * index)
Remove all elements with a given index from a hashtable, returning an array of all items.
Parameters
_index The target index.
Returns
An array of all matching items.
Definition at line 743 of file HashContents.cpp.
References countAllIndex(), entryValue(), isIndex(), new_array(), nextEntry(), NoLink, ArrayClass::put(), and removeChainLink().
Referenced by RelationClass::removeAll().
removeChainLink()
void HashContents::removeChainLink (ItemLink & position, ItemLink previous)
Remove a link from the chain, taking into consideration where the link occurs. This will add a new link to the free chain.
Parameters
position The position we're removing.
previous The previous chain entry (NoLink value if this is the head of the chain).
Definition at line 377 of file HashContents.cpp.
References clearEntry(), closeChain(), copyEntry(), itemCount, nextEntry(), NoLink, NoMore, and returnToFreeChain().
Referenced by iterateNextAndRemove(), remove(), removeAll(), and removeItem().
removeItem() [1/2]
RexxInternalObject * HashContents::removeItem (RexxInternalObject * item)
Removes an item from the hash table.
Parameters
item The target value.
Returns
The removed item or NULL if not located.
Definition at line 854 of file HashContents.cpp.
References entryValue(), locateItem(), OREF_NULL, and removeChainLink().
removeItem() [2/2]
RexxInternalObject * HashContents::removeItem (RexxInternalObject * value, RexxInternalObject * index)
Remove the index/item tuple from the collection.
Parameters
value The value to remove.
index The index to remove.
Returns
The removed value or OREF_NULL if the pair was not located.
Definition at line 781 of file HashContents.cpp.
References entryValue(), locateEntry(), OREF_NULL, and removeChainLink().
Referenced by HashCollection::removeItem(), RelationClass::removeItem(), and RelationClass::removeItemRexx().
returnToFreeChain()
void HashContents::returnToFreeChain (ItemLink position) inline
Definition at line 236 of file HashContents.hpp.
References clearEntry(), entries, freeChain, and HashContents::ContentEntry::next.
Referenced by closeChain(), and removeChainLink().
reverseIterator()
HashContents::ReverseTableIterator HashContents::reverseIterator ()
Create an iterator for traversing through all of the entries of the table in reverse order
Returns
A ReverseTableIterator item.
Definition at line 1780 of file HashContents.cpp.
References locateNextBucketEnd(), and NoMore.
Referenced by HashCollection::reverseIterator().
setEntry()
void HashContents::setEntry (ItemLink position, RexxInternalObject * value, RexxInternalObject * index)
set the entry values for a position
Parameters
position The table position.
value The value to set.
index The index to set.
Definition at line 1700 of file HashContents.cpp.
References entries, and setField.
Referenced by add(), addFront(), append(), copyEntry(), insert(), mergePut(), and put().
setNext()
void HashContents::setNext (ItemLink position, ItemLink next) inline
Definition at line 216 of file HashContents.hpp.
References entries, and HashContents::ContentEntry::next.
Referenced by append(), and insert().
setValue()
void HashContents::setValue (ItemLink position, RexxInternalObject * value)
set the value in an existing entry
Parameters
position The position of the entry.
value The value to set.
Definition at line 1728 of file HashContents.cpp.
References entries, and setField.
Referenced by copyValues(), put(), HashContents::IndexIterator::replace(), HashContents::TableIterator::replace(), and HashContents::ReverseTableIterator::replace().
supplier() [1/2]
SupplierClass * HashContents::supplier ()
Create a supplier from the hash table
Returns
A supplier instance.
Definition at line 1493 of file HashContents.cpp.
References bucketSize, entryIndex(), entryValue(), isInUse(), itemCount, new_array(), new_supplier(), nextEntry(), NoMore, OREF_NULL, and ArrayClass::put().
Referenced by HashCollection::supplier(), DirectoryClass::supplier(), supplier(), and RelationClass::supplierRexx().
supplier() [2/2]
SupplierClass * HashContents::supplier (RexxInternalObject * index)
Create a supplier for the collection. If the index is specified, only the values associated with that index are included.
Parameters
index The optional index value.
Returns
An appropriate supplier object.
Definition at line 1545 of file HashContents.cpp.
References getAll(), new_array(), new_supplier(), OREF_NULL, and supplier().
uniqueIndexes()
ArrayClass * HashContents::uniqueIndexes ()
Return an array containing the unique indexes of a Relation object.
Returns
An array with the set of unique index values
Definition at line 1461 of file HashContents.cpp.
References bucketSize, entryIndex(), isInUse(), items(), new_table(), nextEntry(), NoMore, and TheNilObject.
Referenced by HashCollection::uniqueIndexes().
Member Data Documentation
bucketSize
size_t HashContents::bucketSize protected
Definition at line 387 of file HashContents.hpp.
Referenced by allIndex(), allIndexes(), allItems(), copyValues(), countAllItem(), empty(), hashBucket(), HashContents(), hashIndex(), EqualityHashContents::hashIndex(), StringHashContents::hashIndex(), initializeFreeChain(), isBucketPosition(), iterateNext(), locateItem(), locateNextBucketEnd(), merge(), putAll(), reHash(), reMerge(), supplier(), and uniqueIndexes().
entries
ContentEntry HashContents::entries[1] protected
Definition at line 391 of file HashContents.hpp.
Referenced by add(), append(), clearEntry(), closeChain(), copyEntry(), entryIndex(), entryValue(), flatten(), HashContents(), initializeFreeChain(), insert(), isAvailable(), isIndex(), isInUse(), isItem(), live(), liveGeneral(), mergePut(), nextEntry(), nextItem(), put(), returnToFreeChain(), setEntry(), setNext(), and setValue().
freeChain
ItemLink HashContents::freeChain protected
Definition at line 390 of file HashContents.hpp.
Referenced by append(), initializeFreeChain(), insert(), isFull(), and returnToFreeChain().
itemCount
size_t HashContents::itemCount protected
Definition at line 389 of file HashContents.hpp.
Referenced by add(), addFront(), allIndexes(), allItems(), append(), hasCapacity(), initializeFreeChain(), insert(), isEmpty(), items(), merge(), mergePut(), put(), putAll(), removeChainLink(), and supplier().
NoLink
const ItemLink HashContents::NoLink = SIZE_MAX static
Definition at line 69 of file HashContents.hpp.
Referenced by add(), getAll(), iterateNextAndRemove(), locateEntry(), locateItem(), mergePut(), put(), removeAll(), and removeChainLink().
NoMore
const ItemLink HashContents::NoMore = SIZE_MAX static
Definition at line 67 of file HashContents.hpp.
Referenced by add(), allIndex(), allIndexes(), allItems(), append(), clearEntry(), copyValues(), countAllIndex(), countAllItem(), empty(), initializeFreeChain(), insert(), HashContents::IndexIterator::isAvailable(), HashContents::TableIterator::isAvailable(), HashContents::ReverseTableIterator::isAvailable(), isFull(), iterateNext(), iterateNextAndRemove(), iterator(), locateEntry(), locateItem(), locateNextBucketEnd(), merge(), mergePut(), nextItem(), nextMatch(), put(), putAll(), reHash(), reMerge(), removeChainLink(), reverseIterator(), supplier(), and uniqueIndexes().
totalSize
size_t HashContents::totalSize protected
Definition at line 388 of file HashContents.hpp.
Referenced by capacity(), flatten(), hasCapacity(), HashContents(), initializeFreeChain(), live(), and liveGeneral().
The documentation for this class was generated from the following files:
HashContents.hpp
HashContents.cpp