ooRexx: Protected< objType > Class Template Reference
Protected< objType > Class Template Reference
#include <ProtectedObject.hpp>
Public Member Functions
Protected ()
Protected (Activity *a)
Protected (objType *o)
Protected (objType *o, Activity *a)
~Protected ()
void mark (size_t liveMark) override
void markGeneral (int reason) override
ProtectedBase & operator= (objType *o)
bool operator== (objType *o)
operator RexxObjectPtr ()
operator objType * ()
operator void * ()
bool isNull ()
objType * operator-> ()
Public Member Functions inherited from ProtectedBase
ProtectedBase ()
ProtectedBase (Activity *a)
~ProtectedBase ()
Protected Attributes
objType * protectedObject
Protected Attributes inherited from ProtectedBase
ProtectedBase * next
Activity * activity
Detailed Description
template<class objType>
class Protected< objType >
Typed version of a protected object. Because this uses templates, it is possible to use these like normal pointers to invoke methods. More useful where operations need to be performed on a protected object since it avoids lots of cast operations.
Definition at line 186 of file ProtectedObject.hpp.
Constructor & Destructor Documentation
Protected() [1/4]
template<class objType > Protected< objType >::Protected () inline
Definition at line 189 of file ProtectedObject.hpp.
Protected() [2/4]
template<class objType > Protected< objType >::Protected (Activity * a) inline
Definition at line 190 of file ProtectedObject.hpp.
Protected() [3/4]
template<class objType > Protected< objType >::Protected (objType * o) inline
Definition at line 191 of file ProtectedObject.hpp.
Protected() [4/4]
template<class objType > Protected< objType >::Protected (objType * o, Activity * a) inline
Definition at line 192 of file ProtectedObject.hpp.
~Protected()
template<class objType > Protected< objType >::~Protected () inline
Definition at line 194 of file ProtectedObject.hpp.
Member Function Documentation
isNull()
template<class objType > bool Protected< objType >::isNull () inline
Definition at line 225 of file ProtectedObject.hpp.
References OREF_NULL, and Protected< objType >::protectedObject.
Referenced by RexxActivation::callExternalRexx(), PackageManager::checkRequiresCache(), PackageManager::loadRequires(), RexxObject::objectName(), LanguageParser::processInstore(), and RexxStartDispatcher::run().
mark()
template<class objType > void Protected< objType >::mark (size_t liveMark) inline override virtual
Implements ProtectedBase.
Definition at line 196 of file ProtectedObject.hpp.
References memory_mark, and Protected< objType >::protectedObject.
markGeneral()
template<class objType > void Protected< objType >::markGeneral (int reason) inline override virtual
Implements ProtectedBase.
Definition at line 197 of file ProtectedObject.hpp.
References memory_mark_general, and Protected< objType >::protectedObject.
operator objType *()
template<class objType > Protected< objType >::operator objType * () inline
Definition at line 215 of file ProtectedObject.hpp.
References Protected< objType >::protectedObject.
operator RexxObjectPtr()
template<class objType > Protected< objType >::operator RexxObjectPtr () inline
Definition at line 210 of file ProtectedObject.hpp.
References Protected< objType >::protectedObject.
operator void *()
template<class objType > Protected< objType >::operator void * () inline
Definition at line 220 of file ProtectedObject.hpp.
References Protected< objType >::protectedObject.
operator->()
template<class objType > objType* Protected< objType >::operator-> () inline
Definition at line 231 of file ProtectedObject.hpp.
References Protected< objType >::protectedObject.
operator=()
template<class objType > ProtectedBase& Protected< objType >::operator= (objType * o) inline
Definition at line 199 of file ProtectedObject.hpp.
References Protected< objType >::protectedObject.
operator==()
template<class objType > bool Protected< objType >::operator== (objType * o) inline
Definition at line 205 of file ProtectedObject.hpp.
References Protected< objType >::protectedObject.
Member Data Documentation
protectedObject
template<class objType > objType* Protected< objType >::protectedObject protected
Definition at line 238 of file ProtectedObject.hpp.
Referenced by Protected< objType >::isNull(), Protected< objType >::mark(), Protected< objType >::markGeneral(), Protected< objType >::operator objType *(), Protected< objType >::operator RexxObjectPtr(), Protected< objType >::operator void *(), Protected< objType >::operator->(), Protected< objType >::operator=(), and Protected< objType >::operator==().
The documentation for this class was generated from the following file:
ProtectedObject.hpp