ooRexx: NumberString::NumberBuilder Class Reference
NumberString::NumberBuilder Class Reference
#include <NumberStringClass.hpp>
Public Member Functions
NumberBuilder (RexxString *s)
void addSign (bool isNegative)
void addExponentSign (bool isNegative)
void addDecimal ()
void addExponent (const char *exp)
void append (const char *d, size_t l)
void append (char c)
void addDigits (const char *d, wholenumber_t len)
void addZeroDecimal ()
void addZeros (wholenumber_t count)
void addSpaces (wholenumber_t count)
void addIntegerPart (bool sign, const char *digits, wholenumber_t intDigits, wholenumber_t pad=0)
void addDecimalPart (const char *digits, wholenumber_t decimalDigits, wholenumber_t leadPad=0, wholenumber_t trailingPad=0)
Protected Attributes
char * current
Detailed Description
A class for constructing a number value from a sequence of append steps.
Definition at line 120 of file NumberStringClass.hpp.
Constructor & Destructor Documentation
NumberBuilder()
NumberString::NumberBuilder::NumberBuilder (RexxString * s) inline
Definition at line 123 of file NumberStringClass.hpp.
Member Function Documentation
addDecimal()
void NumberString::NumberBuilder::addDecimal () inline
Definition at line 127 of file NumberStringClass.hpp.
References append(), and RexxString::ch_PERIOD.
Referenced by addDecimalPart().
addDecimalPart()
void NumberString::NumberBuilder::addDecimalPart (const char * digits, wholenumber_t decimalDigits, wholenumber_t leadPad = 0, wholenumber_t trailingPad = 0) inline
Definition at line 175 of file NumberStringClass.hpp.
References addDecimal(), addDigits(), and addZeros().
Referenced by NumberString::formatInternal(), NumberString::stringValue(), and NumberString::truncInternal().
addDigits()
void NumberString::NumberBuilder::addDigits (const char * d, wholenumber_t len) inline
Definition at line 148 of file NumberStringClass.hpp.
References append(), and RexxString::ch_ZERO.
Referenced by addDecimalPart(), and addIntegerPart().
addExponent()
void NumberString::NumberBuilder::addExponent (const char * exp) inline
Definition at line 128 of file NumberStringClass.hpp.
References current.
Referenced by NumberString::stringValue().
addExponentSign()
void NumberString::NumberBuilder::addExponentSign (bool isNegative) inline
Definition at line 126 of file NumberStringClass.hpp.
References RexxString::ch_MINUS, RexxString::ch_PLUS, current, and NumberString::isNegative().
Referenced by NumberString::formatInternal().
addIntegerPart()
void NumberString::NumberBuilder::addIntegerPart (bool sign, const char * digits, wholenumber_t intDigits, wholenumber_t pad = 0) inline
Definition at line 168 of file NumberStringClass.hpp.
References addDigits(), addSign(), and addZeros().
Referenced by NumberString::formatInternal(), NumberString::stringValue(), and NumberString::truncInternal().
addSign()
void NumberString::NumberBuilder::addSign (bool isNegative) inline
Definition at line 125 of file NumberStringClass.hpp.
References RexxString::ch_MINUS, current, and NumberString::isNegative().
Referenced by addIntegerPart().
addSpaces()
void NumberString::NumberBuilder::addSpaces (wholenumber_t count) inline
Definition at line 162 of file NumberStringClass.hpp.
References current.
Referenced by NumberString::formatInternal().
addZeroDecimal()
void NumberString::NumberBuilder::addZeroDecimal () inline
Definition at line 155 of file NumberStringClass.hpp.
References append().
Referenced by NumberString::truncInternal().
addZeros()
void NumberString::NumberBuilder::addZeros (wholenumber_t count) inline
Definition at line 156 of file NumberStringClass.hpp.
References current.
Referenced by addDecimalPart(), addIntegerPart(), NumberString::formatInternal(), and NumberString::truncInternal().
append() [1/2]
void NumberString::NumberBuilder::append (char c) inline
Definition at line 135 of file NumberStringClass.hpp.
References current.
append() [2/2]
void NumberString::NumberBuilder::append (const char * d, size_t l) inline
Definition at line 134 of file NumberStringClass.hpp.
References current.
Referenced by addDecimal(), addDigits(), addZeroDecimal(), and NumberString::formatInternal().
Member Data Documentation
current
char* NumberString::NumberBuilder::current protected
Definition at line 185 of file NumberStringClass.hpp.
Referenced by addExponent(), addExponentSign(), addSign(), addSpaces(), addZeros(), and append().
The documentation for this class was generated from the following file:
NumberStringClass.hpp