ooRexx: RexxContext Class Reference
RexxContext Class Reference
#include <ContextClass.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
RexxContext (RexxActivation *)
RexxContext (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
PackageClass * getPackage ()
RexxObject * getDigits ()
RexxObject * getFuzz ()
RexxObject * getForm ()
RexxObject * getInvocation ()
RexxObject * getInterpreter ()
RexxObject * getThread ()
RexxObject * getVariables ()
RexxObject * getExecutable ()
RexxObject * getArgs ()
RexxObject * getCondition ()
RexxObject * getLine ()
RexxObject * getRS ()
RexxObject * copyRexx ()
RexxObject * getName ()
RexxObject * getStackFrames ()
RexxObject * newRexx (RexxObject **args, size_t argc)
void detach ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
void flatten (Envelope *) override
RexxInternalObject * copy () override
HashCode hash () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Member Functions
void checkValid ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Protected Attributes
RexxActivation * activation
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Detailed Description
A class to provide Rexx program access to an active execution context.
Definition at line 56 of file ContextClass.hpp.
Constructor & Destructor Documentation
RexxContext() [1/2]
RexxContext::RexxContext (RexxActivation * a)
Constructor for a RexxContext object.
Parameters
a The activation we're attached to.
Definition at line 80 of file ContextClass.cpp.
References activation.
RexxContext() [2/2]
RexxContext::RexxContext (RESTORETYPE restoreType) inline
Definition at line 64 of file ContextClass.hpp.
Member Function Documentation
checkValid()
void RexxContext::checkValid () protected
Check that the backing RexxActivation is still available.
Definition at line 145 of file ContextClass.cpp.
References activation, Error_Execution_context_not_active, OREF_NULL, and reportException().
Referenced by getArgs(), getCondition(), getDigits(), getExecutable(), getForm(), getFuzz(), getInterpreter(), getInvocation(), getLine(), getName(), getPackage(), getRS(), getStackFrames(), getThread(), and getVariables().
copyRexx()
RexxObject * RexxContext::copyRexx ()
An override for the copy method to keep RexxContext objects from being copied.
Returns
Never returns.
Definition at line 134 of file ContextClass.cpp.
References Error_Unsupported_copy_method, reportException(), and TheNilObject.
Referenced by MemoryObject::createImage().
createInstance()
void RexxContext::createInstance () static
Create initial bootstrap objects
Definition at line 56 of file ContextClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
detach()
void RexxContext::detach () inline
Definition at line 88 of file ContextClass.hpp.
References activation, and OREF_NULL.
Referenced by RexxActivation::termination().
getArgs()
RexxObject * RexxContext::getArgs ()
Return the executable backing the current context
Returns
The executable object (either a method or routine)
Definition at line 233 of file ContextClass.cpp.
References activation, checkValid(), RexxActivation::getMethodArgumentCount(), RexxActivation::getMethodArgumentList(), and new_array().
Referenced by MemoryObject::createImage().
getCondition()
RexxObject * RexxContext::getCondition ()
Return the current executable condition information
Returns
The condition information
Definition at line 247 of file ContextClass.cpp.
References activation, checkValid(), RexxObject::copy(), RexxActivation::getConditionObj(), OREF_NULL, and TheNilObject.
Referenced by MemoryObject::createImage().
getDigits()
RexxObject * RexxContext::getDigits ()
Return the current digits setting for the running context
Returns
The current digits value
Definition at line 172 of file ContextClass.cpp.
References activation, checkValid(), RexxActivation::digits(), and new_integer().
Referenced by MemoryObject::createImage().
getExecutable()
RexxObject * RexxContext::getExecutable ()
Return the executable backing the current context
Returns
The executable object (either a method or routine)
Definition at line 221 of file ContextClass.cpp.
References activation, checkValid(), and ActivationBase::getExecutable().
Referenced by MemoryObject::createImage().
getForm()
RexxObject * RexxContext::getForm ()
Return the current form setting for the running context
Returns
The current form value
Definition at line 196 of file ContextClass.cpp.
References activation, checkValid(), RexxActivation::form(), and Numerics::FORM_SCIENTIFIC.
Referenced by MemoryObject::createImage().
getFuzz()
RexxObject * RexxContext::getFuzz ()
Return the current fuzz setting for the running context
Returns
The current fuzz value
Definition at line 184 of file ContextClass.cpp.
References activation, checkValid(), RexxActivation::fuzz(), and new_integer().
Referenced by MemoryObject::createImage().
getInterpreter()
RexxObject * RexxContext::getInterpreter ()
Return the context interpreter id.
Returns
The interpreter id of the context.
Definition at line 298 of file ContextClass.cpp.
References activation, checkValid(), and new_integer().
Referenced by MemoryObject::createImage().
getInvocation()
RexxObject * RexxContext::getInvocation ()
Return the context invocation id.
Returns
The invocation id of the context.
Definition at line 273 of file ContextClass.cpp.
References activation, checkValid(), and new_integer().
Referenced by MemoryObject::createImage().
getLine()
RexxObject * RexxContext::getLine ()
Return the execution context current line position.
Returns
The current line number of the context.
Definition at line 261 of file ContextClass.cpp.
References activation, checkValid(), and RexxActivation::getContextLine().
Referenced by MemoryObject::createImage().
getName()
RexxObject * RexxContext::getName ()
Retrieve the name associated with the current context. If this is the top level, then the name of the package is returned. For internal call contexts, the label name is returned, and for routines or methods, the name used to invoke the code is returned.
Returns
The appropriate name for this context.
Definition at line 326 of file ContextClass.cpp.
References activation, checkValid(), RexxActivation::getCallname(), and resultOrNil().
Referenced by MemoryObject::createImage().
getPackage()
PackageClass * RexxContext::getPackage ()
Return the package object for the code that's currently executing.
Returns
The package instance.
Definition at line 160 of file ContextClass.cpp.
References activation, checkValid(), and RexxActivation::getPackage().
Referenced by MemoryObject::createImage().
getRS()
RexxObject * RexxContext::getRS ()
Return the execution context return status
Returns
The .RS value of the context.
Definition at line 310 of file ContextClass.cpp.
References activation, checkValid(), and RexxActivation::getContextReturnStatus().
Referenced by MemoryObject::createImage().
getStackFrames()
RexxObject * RexxContext::getStackFrames ()
Retrieve the stack frames from the current context.
Returns
A list of the current stack frames.
Definition at line 337 of file ContextClass.cpp.
References activation, checkValid(), and RexxActivation::getStackFrames().
Referenced by MemoryObject::createImage().
getThread()
RexxObject * RexxContext::getThread ()
Return the context thread id.
Returns
The thread id of the context.
Definition at line 285 of file ContextClass.cpp.
References activation, checkValid(), and new_integer().
Referenced by MemoryObject::createImage().
getVariables()
RexxObject * RexxContext::getVariables ()
Return a supplier for all of the variables in the current context.
Returns
A supplier object for iterating over the variables
Definition at line 209 of file ContextClass.cpp.
References activation, checkValid(), and RexxActivation::getAllLocalVariables().
Referenced by MemoryObject::createImage().
live()
void RexxContext::live (size_t liveMark) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxObject.
Definition at line 109 of file ContextClass.cpp.
References activation, and memory_mark.
liveGeneral()
void RexxContext::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxObject.
Definition at line 121 of file ContextClass.cpp.
References activation, and memory_mark_general.
newRexx()
RexxObject * RexxContext::newRexx (RexxObject ** args, size_t argc)
The Rexx accessible class NEW method. This raises an error because RexxContext objects can only be created by the internal interpreter.
Parameters
args The NEW args
argc The count of arguments
Returns
Never returns.
Definition at line 96 of file ContextClass.cpp.
References Error_Unsupported_new_method, reportException(), and TheNilObject.
Referenced by MemoryObject::createImage().
operator delete()
void RexxContext::operator delete (void *) inline
Definition at line 60 of file ContextClass.hpp.
operator new()
void * RexxContext::operator new (size_t size)
Allocate a new RexxContext object
Parameters
size The size of the object.
Returns
The newly allocated object.
Definition at line 69 of file ContextClass.cpp.
References new_object(), and T_RexxContext.
Member Data Documentation
activation
RexxActivation* RexxContext::activation protected
Definition at line 97 of file ContextClass.hpp.
Referenced by checkValid(), detach(), getArgs(), getCondition(), getDigits(), getExecutable(), getForm(), getFuzz(), getInterpreter(), getInvocation(), getLine(), getName(), getPackage(), getRS(), getStackFrames(), getThread(), getVariables(), live(), liveGeneral(), and RexxContext().
classInstance
RexxClass * RexxContext::classInstance = OREF_NULL static
Definition at line 91 of file ContextClass.hpp.
The documentation for this class was generated from the following files:
ContextClass.hpp
ContextClass.cpp