ooRexx: ActivationStack Class Reference
ActivationStack Class Reference
#include <ActivationStack.hpp>
Public Types
enum { DefaultFrameBufferSize = 2048 }
Public Member Functions
ActivationStack ()
void live (size_t)
void liveGeneral (MarkReason reason)
void init ()
void expandCapacity (size_t entries)
void ensureCapacity (size_t entries)
RexxInternalObject ** allocateFrame (size_t entries)
void releaseFrame (RexxInternalObject **frame)
Protected Attributes
ActivationFrameBuffer * current
ActivationFrameBuffer * unused
Detailed Description
Special stack for managing the stack frames used by the activations running on an Activity.
Definition at line 107 of file ActivationStack.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DefaultFrameBufferSize
Definition at line 111 of file ActivationStack.hpp.
Constructor & Destructor Documentation
ActivationStack()
ActivationStack::ActivationStack () inline
Definition at line 112 of file ActivationStack.hpp.
Member Function Documentation
allocateFrame()
RexxInternalObject** ActivationStack::allocateFrame (size_t entries) inline
Definition at line 121 of file ActivationStack.hpp.
References ActivationFrameBuffer::allocateFrame(), current, and ensureCapacity().
Referenced by Activity::allocateFrame(), Activity::allocateLocalVariableFrame(), and Activity::allocateStackFrame().
ensureCapacity()
void ActivationStack::ensureCapacity (size_t entries) inline
Definition at line 120 of file ActivationStack.hpp.
References current, expandCapacity(), and ActivationFrameBuffer::hasCapacity().
Referenced by allocateFrame().
expandCapacity()
void ActivationStack::expandCapacity (size_t entries)
Expand the capacity of the stack to add at least entries additional values on the stack.
Parameters
entries
Definition at line 151 of file ActivationStack.cpp.
References current, DefaultFrameBufferSize, ActivationFrameBuffer::hasCapacity(), new_activationFrameBuffer(), OREF_NULL, ActivationFrameBuffer::push(), and unused.
Referenced by ensureCapacity().
init()
void ActivationStack::init ()
Initialize a frame stack for a new activity.
Definition at line 138 of file ActivationStack.cpp.
References current, DefaultFrameBufferSize, new_activationFrameBuffer(), OREF_NULL, and unused.
Referenced by Activity::Activity().
live()
void ActivationStack::live (size_t liveMark)
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Definition at line 114 of file ActivationStack.cpp.
References current, memory_mark, and unused.
Referenced by Activity::live().
liveGeneral()
void ActivationStack::liveGeneral (MarkReason reason)
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Definition at line 128 of file ActivationStack.cpp.
References current, memory_mark_general, and unused.
Referenced by Activity::liveGeneral().
releaseFrame()
void ActivationStack::releaseFrame (RexxInternalObject ** frame) inline
Definition at line 128 of file ActivationStack.hpp.
References ActivationFrameBuffer::contains(), current, ActivationFrameBuffer::getPrevious(), OREF_NULL, ActivationFrameBuffer::releaseFrame(), ActivationFrameBuffer::reset(), and unused.
Referenced by Activity::releaseStackFrame().
Member Data Documentation
current
ActivationFrameBuffer* ActivationStack::current protected
Definition at line 152 of file ActivationStack.hpp.
Referenced by allocateFrame(), ensureCapacity(), expandCapacity(), init(), live(), liveGeneral(), and releaseFrame().
unused
ActivationFrameBuffer* ActivationStack::unused protected
Definition at line 153 of file ActivationStack.hpp.
Referenced by expandCapacity(), init(), live(), liveGeneral(), and releaseFrame().
The documentation for this class was generated from the following files:
ActivationStack.hpp
ActivationStack.cpp