ooRexx: ClassDirective Class Reference
ClassDirective Class Reference
#include <ClassDirective.hpp>
Public Types
enum ClassProperties { PUBLIC , MIXIN , ABSTRACT }
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
ClassDirective (RexxString *, RexxString *, RexxClause *)
ClassDirective (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxString * getName ()
void install (PackageClass *package, RexxActivation *activation)
void resolveConstants (PackageClass *package, Activity *activity)
void activate ()
void addDependencies (StringTable *class_directives)
void checkDependency (ClassResolver *classReference, StringTable *class_directives)
bool dependenciesResolved ()
void removeDependency (RexxString *name)
StringTable * getAnnotations ()
ClassResolver * getMetaClass ()
void setMetaClass (ClassResolver *m)
ClassResolver * getSubClass ()
void setSubClass (ClassResolver *m)
void setMixinClass (ClassResolver *m)
void setPublic ()
void setAbstract ()
bool isPublic ()
bool isMixinClass ()
bool isAbstract ()
void addInherits (ClassResolver *name)
void addMethod (RexxString *name, MethodClass *method, bool classMethod)
void addConstantMethod (RexxString *name, MethodClass *method)
void addConstantMethod (RexxString *name, MethodClass *method, RexxInstruction *directive, size_t maxStack, size_t variableIndex)
bool checkDuplicateMethod (RexxString *name, bool classMethod)
MethodClass * findMethod (RexxString *name)
MethodClass * findClassMethod (RexxString *name)
MethodClass * findInstanceMethod (RexxString *name)
Public Member Functions inherited from RexxDirective
RexxDirective ()
RexxDirective (RexxClause *clause, InstructionKeyword type)
Public Member Functions inherited from RexxInstruction
void * operator new (size_t)
void operator delete (void *)
RexxInstruction (RexxClause *clause, InstructionKeyword type)
RexxInstruction (RESTORETYPE restoreType)
RexxInstruction ()
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
virtual void execute (RexxActivation *, ExpressionStack *)
virtual bool isBlock ()
virtual bool isControl ()
const SourceLocation & getLocation ()
void setLocation (const SourceLocation &l)
void setNext (RexxInstruction *next)
RexxInstruction * next ()
bool isLast ()
void setStart (size_t line, size_t off)
void setEnd (size_t line, size_t off)
void setType (InstructionKeyword type)
InstructionKeyword getType ()
bool isType (InstructionKeyword type)
size_t getLineNumber ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Protected Member Functions
StringTable * getClassMethods ()
StringTable * getInstanceMethods ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Protected Attributes
RexxString * publicName
RexxString * idName
ClassResolver * metaclassName
ClassResolver * subclassName
ArrayClass * inheritsClasses
StringTable * instanceMethods
StringTable * classMethods
StringTable * annotations
StringTable * dependencies
FlagSet< ClassProperties, 32 > classFlags
RexxCode * constantInitializer
RexxClass * classObject
Friends
class PackageClass
Additional Inherited Members
Static Public Member Functions inherited from RexxInstruction
static void evaluateArguments (RexxActivation *context, ExpressionStack *stack, RexxInternalObject **argArray, size_t argCount)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInstruction
InstructionKeyword instructionType
SourceLocation instructionLocation
RexxInstruction * nextInstruction
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Detailed Description
A class representing a directive instruction inside of a package file.
Definition at line 60 of file ClassDirective.hpp.
Member Enumeration Documentation
ClassProperties
enum ClassDirective::ClassProperties
Enumerator
PUBLIC
MIXIN
ABSTRACT
Definition at line 74 of file ClassDirective.hpp.
Constructor & Destructor Documentation
ClassDirective() [1/2]
ClassDirective::ClassDirective (RexxString * n, RexxString * p, RexxClause * clause)
Construct a ClassDirective.
Parameters
n The name of the requires target.
p The public name of the requires target.
clause The source file clause containing the directive.
Definition at line 62 of file ClassDirective.cpp.
References idName, and publicName.
ClassDirective() [2/2]
ClassDirective::ClassDirective (RESTORETYPE restoreType) inline
Definition at line 68 of file ClassDirective.hpp.
Member Function Documentation
activate()
void ClassDirective::activate ()
Perform the last-stage activation for a class object.
Definition at line 284 of file ClassDirective.cpp.
References classObject, and RexxObject::sendMessage().
Referenced by PackageClass::processInstall().
addConstantMethod() [1/2]
void ClassDirective::addConstantMethod (RexxString * name, MethodClass * method)
Add a method to a class definition.
Parameters
name The name to add.
method The method object that maps to this name.
Definition at line 520 of file ClassDirective.cpp.
References addMethod().
Referenced by LanguageParser::createConstantGetterMethod().
addConstantMethod() [2/2]
void ClassDirective::addConstantMethod (RexxString * name, MethodClass * method, RexxInstruction * directive, size_t maxStack, size_t variableIndex)
Add a method to a class definition that is evaluated at install time.
Parameters
name The name to add.
method The method object that maps to this name.
directive The directive instruction that will resolve the constant.
Definition at line 536 of file ClassDirective.cpp.
References RexxCode::addInstruction(), addMethod(), constantInitializer, and OREF_NULL.
addDependencies()
void ClassDirective::addDependencies (StringTable * classDirectives)
Check our class dependencies against the locally defined class list to develop a cross dependency list.
Parameters
classDirectives The global set of defined classes in this package.
Definition at line 327 of file ClassDirective.cpp.
References checkDependency(), ArrayClass::get(), inheritsClasses, ArrayClass::items(), metaclassName, OREF_NULL, and subclassName.
Referenced by LanguageParser::resolveDependencies().
addInherits()
void ClassDirective::addInherits (ClassResolver * name)
Add an inherits class to the class definition.
Parameters
name The name of the inherited class.
Definition at line 385 of file ClassDirective.cpp.
References ArrayClass::append(), inheritsClasses, new_array(), and OREF_NULL.
Referenced by LanguageParser::classDirective().
addMethod()
void ClassDirective::addMethod (RexxString * name, MethodClass * method, bool classMethod)
Add a method to a class definition.
Parameters
name The name to add.
method The method object that maps to this name.
classMethod Indicates whether this is a new class or instance method.
Definition at line 501 of file ClassDirective.cpp.
References getClassMethods(), getInstanceMethods(), and HashCollection::put().
Referenced by addConstantMethod(), and LanguageParser::addMethod().
checkDependency()
void ClassDirective::checkDependency (ClassResolver * classReference, StringTable * classDirectives)
Check if a dependency this class has is based off of a class co-located in the same class package.
Parameters
name The class name.
classDirectives The global local classes list.
Definition at line 300 of file ClassDirective.cpp.
References dependencies, ClassResolver::getName(), HashCollection::hasIndex(), ClassResolver::isQualified(), new_string_table(), OREF_NULL, and StringHashCollection::setEntry().
Referenced by addDependencies().
checkDuplicateMethod()
bool ClassDirective::checkDuplicateMethod (RexxString * name, bool classMethod)
Check for a duplicate method defined on this class.
Parameters
name The method name.
classMethod Indicates whether we are checking for a class or instance method.
Returns
true if this is a duplicate of the method type.
Definition at line 434 of file ClassDirective.cpp.
References getClassMethods(), getInstanceMethods(), and HashCollection::hasIndex().
Referenced by LanguageParser::checkDuplicateMethod().
dependenciesResolved()
bool ClassDirective::dependenciesResolved ()
Check if this class has any additional in-package dependencies.
Returns
true if all in-package dependencies have been resolved already.
Definition at line 353 of file ClassDirective.cpp.
References dependencies, and OREF_NULL.
Referenced by LanguageParser::resolveDependencies().
findClassMethod()
MethodClass * ClassDirective::findClassMethod (RexxString * name)
Locate a class method defined on this class
Parameters
name The method name.
Returns
The located method, or OREF_NULL if not found.
Definition at line 487 of file ClassDirective.cpp.
References StringHashCollection::entry(), and getClassMethods().
Referenced by LanguageParser::findClassMethod().
findInstanceMethod()
MethodClass * ClassDirective::findInstanceMethod (RexxString * name)
Locate an instance method defined on this class.
Parameters
name The method name.
Returns
The located method, or OREF_NULL if not found.
Definition at line 474 of file ClassDirective.cpp.
References StringHashCollection::entry(), and getInstanceMethods().
Referenced by LanguageParser::findInstanceMethod().
findMethod()
MethodClass * ClassDirective::findMethod (RexxString * name)
Locate a method defined on this class, checking first for instance methods, then for class methods.
Parameters
name The method name.
Returns
The located method, or OREF_NULL if not found.
Definition at line 455 of file ClassDirective.cpp.
References StringHashCollection::entry(), getClassMethods(), getInstanceMethods(), and OREF_NULL.
Referenced by LanguageParser::findMethod().
flatten()
void ClassDirective::flatten (Envelope * envelope) override virtual
Flatten the directive instance.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxVirtualBase.
Definition at line 121 of file ClassDirective.cpp.
References annotations, classMethods, cleanUpFlatten, constantInitializer, flattenRef, idName, inheritsClasses, instanceMethods, metaclassName, RexxInstruction::nextInstruction, OREF_NULL, publicName, setUpFlatten, and subclassName.
getAnnotations()
StringTable * ClassDirective::getAnnotations ()
get the annotations from a ClassDirective. Used during the creation phase.
Returns
The annotation StringTable.
Definition at line 565 of file ClassDirective.cpp.
References annotations, new_string_table(), OREF_NULL, and setField.
Referenced by LanguageParser::annotateDirective().
getClassMethods()
StringTable * ClassDirective::getClassMethods () protected
Retrieve the class methods directory for this class.
Returns
The class methods directory.
Definition at line 400 of file ClassDirective.cpp.
References classMethods, new_string_table(), and OREF_NULL.
Referenced by addMethod(), checkDuplicateMethod(), findClassMethod(), and findMethod().
getInstanceMethods()
StringTable * ClassDirective::getInstanceMethods () protected
Retrieve the instance methods directory for this class.
Returns
The instance methods directory.
Definition at line 415 of file ClassDirective.cpp.
References instanceMethods, new_string_table(), and OREF_NULL.
Referenced by addMethod(), checkDuplicateMethod(), findInstanceMethod(), and findMethod().
getMetaClass()
ClassResolver* ClassDirective::getMetaClass () inline
Definition at line 93 of file ClassDirective.hpp.
References metaclassName.
Referenced by LanguageParser::classDirective().
getName()
RexxString* ClassDirective::getName () inline
Definition at line 82 of file ClassDirective.hpp.
References publicName.
Referenced by LanguageParser::resolveDependencies().
getSubClass()
ClassResolver* ClassDirective::getSubClass () inline
Definition at line 95 of file ClassDirective.hpp.
References subclassName.
Referenced by LanguageParser::classDirective().
install()
void ClassDirective::install (PackageClass * package, RexxActivation * activation)
Do install-time processing of the ::requires directive. This will resolve the directive and merge all of the public information from the resolved file into this program context.
Parameters
package The package doing the install (used to resolve class references)
activation The activation we're running under for the install.
Definition at line 165 of file ClassDirective.cpp.
References PackageClass::addInstalledClass(), annotations, classMethods, classObject, RexxClass::defineMethods(), Error_Execution_noclass, Error_Execution_nometaclass, ArrayClass::get(), ClassResolver::getName(), idName, inheritsClasses, instanceMethods, isAbstract(), isMixinClass(), isPublic(), ArrayClass::items(), ClassResolver::lookup(), RexxClass::makeAbstract(), metaclassName, RexxClass::mixinClass(), OREF_NULL, publicName, reportException(), RexxObject::sendMessage(), RexxClass::setAnnotations(), RexxActivation::setCurrent(), RexxClass::subclass(), subclassName, and TheObjectClass.
Referenced by PackageClass::processInstall().
isAbstract()
bool ClassDirective::isAbstract () inline
Definition at line 102 of file ClassDirective.hpp.
References ABSTRACT, and classFlags.
Referenced by LanguageParser::classDirective(), and install().
isMixinClass()
bool ClassDirective::isMixinClass () inline
Definition at line 101 of file ClassDirective.hpp.
References classFlags, and MIXIN.
Referenced by install().
isPublic()
bool ClassDirective::isPublic () inline
Definition at line 100 of file ClassDirective.hpp.
References classFlags, and PUBLIC.
Referenced by install().
live()
void ClassDirective::live (size_t liveMark) override virtual
Normal garbage collecting live mark.
Parameters
liveMark The current live object mark.
Reimplemented from RexxVirtualBase.
Definition at line 73 of file ClassDirective.cpp.
References annotations, classMethods, classObject, constantInitializer, dependencies, idName, inheritsClasses, instanceMethods, memory_mark, metaclassName, RexxInstruction::nextInstruction, publicName, and subclassName.
liveGeneral()
void ClassDirective::liveGeneral (MarkReason reason) override virtual
The generalized object marking routine.
Parameters
reason The processing faze we're running the mark on.
Reimplemented from RexxVirtualBase.
Definition at line 97 of file ClassDirective.cpp.
References annotations, classMethods, classObject, constantInitializer, dependencies, idName, inheritsClasses, instanceMethods, memory_mark_general, metaclassName, RexxInstruction::nextInstruction, publicName, and subclassName.
operator delete()
void ClassDirective::operator delete (void *) inline
Definition at line 65 of file ClassDirective.hpp.
operator new()
void * ClassDirective::operator new (size_t size)
Allocate a new ::CLASS directive.
Parameters
size The size of the object.
Returns
The memory for the new object.
Definition at line 151 of file ClassDirective.cpp.
References new_object(), and T_ClassDirective.
removeDependency()
void ClassDirective::removeDependency (RexxString * name)
Remove a class from the dependency list.
Parameters
name The name of the class that's next in the ordering.
Definition at line 364 of file ClassDirective.cpp.
References dependencies, HashCollection::items(), OREF_NULL, and HashCollection::remove().
Referenced by LanguageParser::resolveDependencies().
resolveConstants()
void ClassDirective::resolveConstants (PackageClass * package, Activity * activity)
Resolve any dynamically generated CONSTANT directives for the class.
Definition at line 257 of file ClassDirective.cpp.
References classObject, constantInitializer, OREF_NULL, and BaseCode::setPackageObject().
Referenced by PackageClass::processInstall().
setAbstract()
void ClassDirective::setAbstract () inline
Definition at line 99 of file ClassDirective.hpp.
References ABSTRACT, and classFlags.
Referenced by LanguageParser::classDirective().
setMetaClass()
void ClassDirective::setMetaClass (ClassResolver * m) inline
Definition at line 94 of file ClassDirective.hpp.
References metaclassName, and setField.
Referenced by LanguageParser::classDirective().
setMixinClass()
void ClassDirective::setMixinClass (ClassResolver * m) inline
Definition at line 97 of file ClassDirective.hpp.
References classFlags, MIXIN, setField, and subclassName.
Referenced by LanguageParser::classDirective().
setPublic()
void ClassDirective::setPublic () inline
Definition at line 98 of file ClassDirective.hpp.
References classFlags, and PUBLIC.
Referenced by LanguageParser::classDirective().
setSubClass()
void ClassDirective::setSubClass (ClassResolver * m) inline
Definition at line 96 of file ClassDirective.hpp.
References setField, and subclassName.
Referenced by LanguageParser::classDirective().
Friends And Related Function Documentation
PackageClass
friend class PackageClass friend
Definition at line 62 of file ClassDirective.hpp.
Member Data Documentation
annotations
StringTable* ClassDirective::annotations protected
Definition at line 125 of file ClassDirective.hpp.
Referenced by flatten(), getAnnotations(), install(), live(), and liveGeneral().
classFlags
FlagSet<ClassProperties, 32> ClassDirective::classFlags protected
Definition at line 127 of file ClassDirective.hpp.
Referenced by isAbstract(), isMixinClass(), isPublic(), setAbstract(), setMixinClass(), and setPublic().
classMethods
StringTable* ClassDirective::classMethods protected
Definition at line 124 of file ClassDirective.hpp.
Referenced by flatten(), getClassMethods(), install(), live(), and liveGeneral().
classObject
RexxClass* ClassDirective::classObject protected
Definition at line 129 of file ClassDirective.hpp.
Referenced by activate(), install(), live(), liveGeneral(), and resolveConstants().
constantInitializer
RexxCode* ClassDirective::constantInitializer protected
Definition at line 128 of file ClassDirective.hpp.
Referenced by addConstantMethod(), flatten(), live(), liveGeneral(), and resolveConstants().
dependencies
StringTable* ClassDirective::dependencies protected
Definition at line 126 of file ClassDirective.hpp.
Referenced by checkDependency(), dependenciesResolved(), live(), liveGeneral(), and removeDependency().
idName
RexxString* ClassDirective::idName protected
Definition at line 119 of file ClassDirective.hpp.
Referenced by ClassDirective(), flatten(), install(), live(), and liveGeneral().
inheritsClasses
ArrayClass* ClassDirective::inheritsClasses protected
Definition at line 122 of file ClassDirective.hpp.
Referenced by addDependencies(), addInherits(), flatten(), install(), live(), and liveGeneral().
instanceMethods
StringTable* ClassDirective::instanceMethods protected
Definition at line 123 of file ClassDirective.hpp.
Referenced by flatten(), getInstanceMethods(), install(), live(), and liveGeneral().
metaclassName
ClassResolver* ClassDirective::metaclassName protected
Definition at line 120 of file ClassDirective.hpp.
Referenced by addDependencies(), flatten(), getMetaClass(), install(), live(), liveGeneral(), and setMetaClass().
publicName
RexxString* ClassDirective::publicName protected
Definition at line 118 of file ClassDirective.hpp.
Referenced by ClassDirective(), flatten(), getName(), install(), live(), and liveGeneral().
subclassName
ClassResolver* ClassDirective::subclassName protected
Definition at line 121 of file ClassDirective.hpp.
Referenced by addDependencies(), flatten(), getSubClass(), install(), live(), liveGeneral(), setMixinClass(), and setSubClass().
The documentation for this class was generated from the following files:
ClassDirective.hpp
ClassDirective.cpp