ooRexx: MemoryObject Class Reference
MemoryObject Class Reference
#include <RexxMemory.hpp>
Public Member Functions
MemoryObject ()
MemoryObject (RESTORETYPE restoreType)
operator RexxObject * ()
RexxObject * operator= (DeadObject *d)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void initialize (bool restoringImage, const char *imageTarget)
MemorySegment * newSegment (size_t requestLength)
MemorySegment * newSegment (size_t requestLength, size_t minLength)
MemorySegment * newLargeSegment (size_t requestLength, size_t minLength)
void freeSegment (MemorySegment *segment)
RexxInternalObject * oldObject (size_t size)
RexxInternalObject * newObject (size_t size)
RexxInternalObject * newObject (size_t size, size_t type)
void * temporaryObject (size_t size)
void deleteTemporaryObject (void *obj)
ArrayClass * newObjects (size_t size, size_t count, size_t objectType)
void reSize (RexxInternalObject *, size_t)
void checkUninit ()
void runUninits ()
void removeUninitObject (RexxInternalObject *obj)
void addUninitObject (RexxInternalObject *obj)
void checkUninitQueue ()
RexxInternalObject * unflattenObjectBuffer (Envelope *envelope, BufferClass *sourceBuffer, char *startPointer, size_t dataLength)
void unflattenProxyObjects (Envelope *envelope, RexxInternalObject *firstObject, RexxInternalObject *endObject)
void markObjects ()
void markObjectsMain (RexxInternalObject *)
void mark (RexxInternalObject *)
void markGeneral (void *)
void tracingMark (RexxInternalObject *root, MarkReason reason)
void collect ()
void removeHold (RexxInternalObject *obj)
RexxInternalObject * holdObject (RexxInternalObject *obj)
void saveImage (const char *imageTarget)
void setOref (RexxInternalObject *variable, RexxInternalObject *value)
void shutdown ()
void liveStackFull ()
void liveStackFull (size_t needed)
char * allocateImageBuffer (size_t size)
void logVerboseOutput (const char *message, void *sub1, void *sub2, void *sub3)
void verboseMessage (const char *message)
void verboseMessage (const char *message, size_t sub1)
void verboseMessage (const char *message, size_t sub1, size_t sub2)
void verboseMessage (const char *message, const char *sub1, size_t sub2)
void verboseMessage (const char *message, size_t sub1, const char *sub2)
void verboseMessage (const char *message, size_t sub1, size_t sub2, size_t sub3)
void verboseMessage (const char *message, size_t sub1, const char *sub2, const char *sub3)
void logObjectStats (RexxInternalObject *obj)
void pushSaveStack (RexxInternalObject *obj)
void removeSavedObject (RexxInternalObject *obj)
void clearSaveStack ()
void checkAllocs ()
void dumpImageStats ()
void scavengeSegmentSets (MemorySegmentSet *requester, size_t allocationLength)
void transferSegmentToNormalSet (MemorySegment *segment)
void setUpMemoryTables (MapTable *old2newTable)
void collectAndUninit (bool clearStack)
void lastChanceUninit ()
StringTable * getGlobalStrings ()
void addWeakReference (WeakReference *ref)
void checkWeakReferences ()
void addGlobalReference (RexxInternalObject *obj)
void removeGlobalReference (RexxInternalObject *obj)
void restore ()
void buildVirtualFunctionTable ()
void create ()
void createImage (const char *imageTarget)
RexxString * getGlobalName (const char *value)
RexxString * getUpperGlobalName (const char *value)
void createStrings ()
ArrayClass * saveStrings ()
void restoreStrings (ArrayClass *stringArray)
void checkLiveStack ()
void checkLiveStack (size_t needed)
void pushLiveStack (RexxInternalObject *obj)
RexxInternalObject * popLiveStack ()
void bumpMarkWord ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void setObjectLive (void *o, size_t mark)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes
size_t markWord
GlobalProtectedObject * protectedObjects
DirectoryClass * environment
StringTable * commonRetrievers
StringTable * system
PackageClass * rexxPackage
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Static Public Attributes
static void * virtualFunctionTable [] = {NULL}
static PCPPM exportedMethods []
Private Types
enum {
saveArray_ENV = 1 , saveArray_SYSTEM , saveArray_NAME_STRINGS , saveArray_TRUE ,
saveArray_FALSE , saveArray_NIL , saveArray_GLOBAL_STRINGS , saveArray_CLASS ,
saveArray_PBEHAV , saveArray_PACKAGES , saveArray_NULLA , saveArray_NULLPOINTER ,
saveArray_REXX_PACKAGE , saveArray_COMMON_RETRIEVERS , saveArray_highest = saveArray_COMMON_RETRIEVERS
}
Private Member Functions
void restoreImage ()
void loadImage (char *&imageBuffer, size_t &imageSize)
bool loadImage (char *&imageBuffer, size_t &imageSize, FileNameBuffer &imageFile)
void setMarkHandler (MarkHandler *h)
void resetMarkHandler ()
void defineMethod (const char *name, RexxBehaviour *behaviour, PCPPM entryPoint, size_t arguments, const char *entryPointName)
void defineProtectedMethod (const char *name, RexxBehaviour *behaviour, PCPPM entryPoint, size_t arguments, const char *entryPointName)
void definePrivateMethod (const char *name, RexxBehaviour *behaviour, PCPPM entryPoint, size_t arguments, const char *entryPointName)
void defineUnguardedMethod (const char *name, RexxBehaviour *behaviour, PCPPM entryPoint, size_t arguments, const char *entryPointName)
void addToEnvironment (const char *name, RexxInternalObject *value)
void addToSystem (const char *name, RexxInternalObject *value)
void completeSystemClass (const char *name, RexxClass *classObj)
void createRexxPackage ()
Private Attributes
LiveStack * liveStack
PushThroughStack * saveStack
bool markingObjects
MapTable * old2new
IdentityTable * uninitTable
size_t pendingUninits
bool processingUninits
WeakReference * weakReferenceList
std::vector< MemorySegment * > segments
OldSpaceSegmentSet oldSpaceSegments
NormalSegmentSet newSpaceNormalSegments
LargeSegmentSet newSpaceLargeSegments
SingleObjectSegmentSet newSpaceSingleSegments
MarkHandler * currentMarkHandler
MarkHandler defaultMarkHandler
MemoryStats * imageStats
size_t allocations
size_t collections
char * restoredImage
StringTable * globalStrings
MapTable * globalReferences
Additional Inherited Members
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 95 of file RexxMemory.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
saveArray_ENV
saveArray_SYSTEM
saveArray_NAME_STRINGS
saveArray_TRUE
saveArray_FALSE
saveArray_NIL
saveArray_GLOBAL_STRINGS
saveArray_CLASS
saveArray_PBEHAV
saveArray_PACKAGES
saveArray_NULLA
saveArray_NULLPOINTER
saveArray_REXX_PACKAGE
saveArray_COMMON_RETRIEVERS
saveArray_highest
Definition at line 246 of file RexxMemory.hpp.
Constructor & Destructor Documentation
MemoryObject() [1/2]
MemoryObject::MemoryObject () inline
Main Constructor for Rexxmemory, called once during main initialization. Will create the initial memory Pool(s), etc.
Definition at line 118 of file RexxMemory.cpp.
References globalReferences, markWord, OREF_NULL, Memory::roundObjectBoundary(), saveStack, RexxInternalObject::setObjectSize(), and weakReferenceList.
MemoryObject() [2/2]
MemoryObject::MemoryObject (RESTORETYPE restoreType) inline
Definition at line 99 of file RexxMemory.hpp.
Member Function Documentation
addGlobalReference()
void MemoryObject::addGlobalReference (RexxInternalObject * obj)
Add a global object reference to an object. The references are counted, so it takes a like number of remove calls to remove the object from the table.
Parameters
obj The object to create a global reference lock on.
Definition at line 1667 of file RexxMemory.cpp.
References globalReferences, and MapTable::increment().
Referenced by InterpreterInstance::addGlobalReference(), and InterpreterInstance::removeGlobalReference().
addToEnvironment()
void MemoryObject::addToEnvironment (const char * name, RexxInternalObject * value) private
Add a object to the environment using the provided name.
Parameters
name The name of the new environment entry.
value The value added.
Definition at line 173 of file Setup.cpp.
References getUpperGlobalName(), and TheEnvironment.
Referenced by createImage().
addToSystem()
void MemoryObject::addToSystem (const char * name, RexxInternalObject * value) private
Add a object to the kernel directory using the provided name.
Parameters
name The name of the new environment entry.
value The value added.
Definition at line 185 of file Setup.cpp.
References getUpperGlobalName(), and TheSystem.
Referenced by createImage().
addUninitObject()
void MemoryObject::addUninitObject (RexxInternalObject * obj)
Add an object with an uninit method to the uninit table
Parameters
obj The object to add.
Definition at line 406 of file RexxMemory.cpp.
References HashCollection::put(), and uninitTable.
Referenced by RexxInternalObject::requiresUninit().
addWeakReference()
void MemoryObject::addWeakReference (WeakReference * ref)
Add a new weak reference to the tracking table
Parameters
ref The weak reference item to add.
Definition at line 489 of file RexxMemory.cpp.
References WeakReference::nextReferenceList, and weakReferenceList.
Referenced by WeakReference::copy(), WeakReference::unflatten(), and WeakReference::WeakReference().
allocateImageBuffer()
char * MemoryObject::allocateImageBuffer (size_t imageSize)
Allocate an image buffer for the system code. The image buffer is allocated in the oldspace segment set. We create an object from that space, then return this object as a character pointer. We eventually will get that pointer passed back to us as the image address.
Parameters
imageSize The size required for the image buffer.
Returns
The storage for the image.
Definition at line 966 of file RexxMemory.cpp.
References oldObject().
Referenced by loadImage().
buildVirtualFunctionTable()
void MemoryObject::buildVirtualFunctionTable ()
Definition at line 199 of file VirtualFunctionTable.cpp.
References getVftPointer(), RESTOREIMAGE, T_AbstractCode, T_Activation, T_ActivationFrameBuffer, T_Activity, T_AddressInstruction, T_AddressWithInstruction, T_Array, T_ArrayClass, T_ArrayInputSource, T_ArrayProgramSource, T_AssignmentInstruction, T_AttributeGetterCode, T_AttributeSetterCode, T_Bag, T_BagClass, T_Behaviour, T_BinaryOperatorTerm, T_Buffer, T_BufferClass, T_BufferingOutputTarget, T_BufferProgramSource, T_CallInstruction, T_CallOnInstruction, T_CaseWhenInstruction, T_Class, T_ClassClass, T_ClassDirective, T_ClassResolver, T_Clause, T_CollectionOutputTarget, T_CommandHandler, T_CommandInstruction, T_CommandIOConfiguration, T_CommandIOContext, T_CompoundElement, T_CompoundVariableTerm, T_ConstantDirective, T_ConstantGetterCode, T_ControlledDoInstruction, T_ControlledDoUntilInstruction, T_ControlledDoWhileInstruction, T_CPPCode, T_DelegateCode, T_Directory, T_DirectoryClass, T_DoBlock, T_DoCountInstruction, T_DoCountUntilInstruction, T_DoCountWhileInstruction, T_DoForeverInstruction, T_DoOverForInstruction, T_DoOverForUntilInstruction, T_DoOverForWhileInstruction, T_DoOverInstruction, T_DoOverUntilInstruction, T_DoOverWhileInstruction, T_DotVariableTerm, T_DoUntilInstruction, T_DoWhileInstruction, T_DoWithForInstruction, T_DoWithForUntilInstruction, T_DoWithForWhileInstruction, T_DoWithInstruction, T_DoWithUntilInstruction, T_DoWithWhileInstruction, T_DropInstruction, T_DynamicCallInstruction, T_DynamicSignalInstruction, T_ElseInstruction, T_EndIfInstruction, T_EndInstruction, T_Envelope, T_EqualityHashContents, T_EventSemaphore, T_EventSemaphoreClass, T_ExitInstruction, T_ExposeInstruction, T_FileProgramSource, T_ForwardInstruction, T_FunctionCallTerm, T_GuardInstruction, T_IdentityHashContents, T_IdentityTable, T_IdentityTableClass, T_IfInstruction, T_IndirectVariableTerm, T_Instruction, T_Integer, T_IntegerClass, T_InternalStack, T_InterpreterInstance, T_InterpretInstruction, T_LabelInstruction, T_LanguageParser, T_LeaveInstruction, T_LibraryDirective, T_LibraryPackage, T_List, T_ListClass, T_ListContents, T_ListTerm, T_LogicalTerm, T_MapBucket, T_MapTable, T_Memory, T_Message, T_MessageClass, T_MessageInstruction, T_MessageSendTerm, T_Method, T_MethodClass, T_MethodDictionary, T_MultiValueContents, T_MutableBuffer, T_MutableBufferClass, T_MutexSemaphore, T_MutexSemaphoreClass, T_NativeActivation, T_NativeMethod, T_NativeRoutine, T_NilObject, T_NopInstruction, T_NumberArray, T_NumberString, T_NumberStringClass, T_NumericInstruction, T_Object, T_ObjectClass, T_OptionsInstruction, T_OtherwiseInstruction, T_Package, T_PackageClass, T_ParseInstruction, T_ParseTrigger, T_Pointer, T_PointerBucket, T_PointerClass, T_PointerTable, T_ProcedureInstruction, T_ProgramSource, T_PushThroughStack, T_QualifiedCallInstruction, T_QualifiedFunction, T_Queue, T_QueueClass, T_QueueInstruction, T_RaiseInstruction, T_RegisteredRoutine, T_Relation, T_RelationClass, T_ReplyInstruction, T_RequiresDirective, T_ReturnInstruction, T_RexxCode, T_RexxContext, T_RexxContextClass, T_RexxInfo, T_RexxInfoClass, T_RexxQueueOutputTarget, T_Routine, T_RoutineClass, T_SayInstruction, T_SecurityManager, T_SelectCaseInstruction, T_SelectInstruction, T_Set, T_SetClass, T_SignalInstruction, T_SignalOnInstruction, T_SimpleDoInstruction, T_SmartBuffer, T_SpecialDotVariableTerm, T_StackFrame, T_StackFrameClass, T_Stem, T_StemClass, T_StemInputSource, T_StemOutputTarget, T_StemVariableTerm, T_StreamInputSource, T_StreamObjectInputSource, T_StreamObjectOutputTarget, T_StreamOutputTarget, T_String, T_StringClass, T_StringHashContents, T_StringTable, T_StringTableClass, T_Supplier, T_SupplierClass, T_Table, T_TableClass, T_ThenInstruction, T_Token, T_TraceInstruction, T_TrapHandler, T_UnaryOperatorTerm, T_UseArgVariableRef, T_UseInstruction, T_UseLocalInstruction, T_Variable, T_VariableDictionary, T_VariableReference, T_VariableReferenceClass, T_VariableReferenceOp, T_VariableTerm, T_WeakReference, T_WeakReferenceClass, and virtualFunctionTable.
Referenced by initialize().
bumpMarkWord()
void MemoryObject::bumpMarkWord () inline
Definition at line 218 of file RexxMemory.hpp.
References ObjectHeader::MarkMask, and markWord.
Referenced by collect(), and saveImage().
checkAllocs()
void MemoryObject::checkAllocs ()
checkLiveStack() [1/2]
void MemoryObject::checkLiveStack () inline
Definition at line 214 of file RexxMemory.hpp.
References LiveStack::checkRoom(), liveStack, and liveStackFull().
Referenced by new_object(), and pushLiveStack().
checkLiveStack() [2/2]
void MemoryObject::checkLiveStack (size_t needed) inline
Definition at line 215 of file RexxMemory.hpp.
References LiveStack::checkRoom(), liveStack, and liveStackFull().
checkUninit()
void MemoryObject::checkUninit ()
Check for objects that require an uninit method run.
Definition at line 274 of file RexxMemory.cpp.
References HashContents::TableIterator::isAvailable(), RexxInternalObject::isObjectDead(), HashCollection::iterator(), markWord, OREF_NULL, pendingUninits, RexxInternalObject::setReadyForUninit(), and uninitTable.
Referenced by markObjects().
checkUninitQueue()
void MemoryObject::checkUninitQueue () inline
Definition at line 123 of file RexxMemory.hpp.
References pendingUninits, and runUninits().
Referenced by Activity::exitCurrentThread(), Activity::run(), NativeActivation::run(), RexxActivation::run(), and Activity::runThread().
checkWeakReferences()
void MemoryObject::checkWeakReferences ()
Scan the weak reference queue looking for either dead weak objects or weak references that refer to objects that have gone out of scope.
Definition at line 448 of file RexxMemory.cpp.
References RexxInternalObject::isObjectLive(), markWord, WeakReference::nextReferenceList, OREF_NULL, WeakReference::referentObject, and weakReferenceList.
Referenced by markObjects().
clearSaveStack()
void MemoryObject::clearSaveStack () inline
Definition at line 189 of file RexxMemory.hpp.
References PushThroughStack::clear(), and saveStack.
Referenced by collectAndUninit().
collect()
void MemoryObject::collect ()
Collect all dead memory in the Rexx object space. The collection process performs a mark operation to mark all of the live objects, followed by sweep of each of the segment sets.
Definition at line 894 of file RexxMemory.cpp.
References allocations, bumpMarkWord(), collections, markObjects(), newSpaceLargeSegments, newSpaceNormalSegments, newSpaceSingleSegments, MemorySegmentSet::sweep(), and verboseMessage().
Referenced by collectAndUninit(), NormalSegmentSet::handleAllocationFailure(), LargeSegmentSet::handleAllocationFailure(), and SingleObjectSegmentSet::handleAllocationFailure().
collectAndUninit()
void MemoryObject::collectAndUninit (bool clearStack)
Force a last-gasp garbage collection and running of the uninits during interpreter instance shutdown. This is an attempt to ensure that all objects with uninit methods get a chance to clean up prior to termination.
Definition at line 306 of file RexxMemory.cpp.
References clearSaveStack(), collect(), and runUninits().
Referenced by lastChanceUninit(), and InterpreterInstance::terminate().
completeSystemClass()
void MemoryObject::completeSystemClass (const char * name, RexxClass * classObj) private
Finalize a system class during image construction. This places the class in the Environment and also adds it to the Rexx package.
Parameters
name The class name.
classObj The class object.
Definition at line 199 of file Setup.cpp.
References getUpperGlobalName(), TheEnvironment, and TheRexxPackage.
create()
void MemoryObject::create ()
Initial memory setup during image build
Definition at line 1802 of file RexxMemory.cpp.
References memoryObject, OREF_NULL, and setUpMemoryTables().
Referenced by createImage().
createImage()
void MemoryObject::createImage (const char * imageTarget)
Initialize the Rexx memory environment during an image built.
Parameters
imageTarget The location to save the created image file.
Definition at line 227 of file Setup.cpp.
References A_COUNT, RexxString::abbrev(), RexxInteger::abs(), NumberString::abs(), RexxString::abs(), AddClassMethod, PackageClass::addClassRexx(), AddMethod, PackageClass::addPackageRexx(), AddPrivateMethod, AddProtectedMethod, PackageClass::addPublicClassRexx(), PackageClass::addPublicRoutineRexx(), PackageClass::addRoutineRexx(), addToEnvironment(), addToSystem(), AddUnguardedMethod, RelationClass::allAt(), ArrayClass::allIndexes(), ListClass::allIndexes(), StemClass::allIndexes(), HashCollection::allIndexes(), RelationClass::allIndexRexx(), ArrayClass::allItems(), ListClass::allItems(), StemClass::allItems(), HashCollection::allItems(), RexxInteger::andOp(), NumberString::andOp(), RexxString::andOp(), ArrayClass::appendRexx(), MutableBuffer::appendRexx(), ListClass::appendRexx(), MessageClass::arguments(), SupplierClass::available(), RexxString::b2x(), BASEIMAGELOAD, RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), StemClass::bracket(), StemClass::bracketEqual(), RexxString::brackets(), MutableBuffer::brackets(), MutableBuffer::bracketsEqual(), RexxString::c2d(), RexxString::c2x(), RoutineClass::callRexx(), RoutineClass::callWithRexx(), RexxString::caselessAbbrev(), RexxString::caselessChangeStr(), MutableBuffer::caselessChangeStr(), RexxString::caselessCompare(), RexxString::caselessCompareToRexx(), RexxString::caselessContains(), MutableBuffer::caselessContains(), MutableBuffer::caselessContainsWord(), RexxString::caselessContainsWord(), RexxString::caselessCountStrRexx(), MutableBuffer::caselessCountStrRexx(), MutableBuffer::caselessEndsWithRexx(), RexxString::caselessEndsWithRexx(), RexxString::caselessEquals(), MutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), MutableBuffer::caselessMatch(), RexxString::caselessMatch(), MutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), MutableBuffer::caselessPos(), RexxString::caselessPosRexx(), MutableBuffer::caselessStartsWithRexx(), RexxString::caselessStartsWithRexx(), MutableBuffer::caselessWordPos(), RexxString::caselessWordPos(), RexxInteger::ceiling(), NumberString::ceiling(), RexxString::ceiling(), RexxString::center(), RexxString::changeStr(), MutableBuffer::changeStr(), RexxInteger::choiceRexx(), RexxString::choiceRexx(), RexxInteger::classObject(), NumberString::classObject(), RexxObject::classObject(), EventSemaphoreClass::close(), MutexSemaphoreClass::close(), RexxString::compare(), RexxString::compareToRexx(), CompleteClassDefinition, CompleteClassMethodDefinitions, MessageClass::completed(), CompleteMethodDefinitions, RexxObject::concatBlank(), RexxString::concatBlank(), RexxObject::concatRexx(), RexxString::concatRexx(), RexxString::containsRexx(), MutableBuffer::containsRexx(), MutableBuffer::containsWord(), RexxString::containsWord(), RexxString::copies(), RexxClass::copyRexx(), RexxContext::copyRexx(), RexxObject::copyRexx(), RexxInfo::copyRexx(), RexxString::countStrRexx(), MutableBuffer::countStrRexx(), CPPM, create(), ArrayClass::createInstance(), BagClass::createInstance(), BufferClass::createInstance(), RexxClass::createInstance(), RexxContext::createInstance(), DirectoryClass::createInstance(), EventSemaphoreClass::createInstance(), IdentityTable::createInstance(), RexxInteger::createInstance(), ListClass::createInstance(), MessageClass::createInstance(), MethodClass::createInstance(), MutableBuffer::createInstance(), MutexSemaphoreClass::createInstance(), NumberString::createInstance(), RexxObject::createInstance(), PackageClass::createInstance(), PointerClass::createInstance(), QueueClass::createInstance(), RelationClass::createInstance(), RexxInfo::createInstance(), RoutineClass::createInstance(), SetClass::createInstance(), StackFrameClass::createInstance(), StemClass::createInstance(), RexxString::createInstance(), StringTable::createInstance(), SupplierClass::createInstance(), TableClass::createInstance(), VariableReference::createInstance(), WeakReference::createInstance(), Interpreter::createInterpreterInstance(), Activity::createNewActivationStack(), LanguageParser::createProgram(), createRexxPackage(), createStrings(), ActivityManager::currentActivity, RexxInteger::d2c(), RexxString::d2c(), NumberString::d2c(), RexxInteger::d2x(), RexxString::d2x(), NumberString::d2x(), RexxString::dataType(), RexxString::decodeBase64(), RexxClass::defaultNameRexx(), RexxObject::defaultNameRexx(), RexxClass::defineClassMethod(), RexxClass::defineMethod(), RexxClass::defineMethodsRexx(), RexxClass::deleteMethod(), ArrayClass::deleteRexx(), QueueClass::deleteRexx(), RexxString::delstr(), RexxString::delWord(), MutableBuffer::delWord(), PackageClass::digitsRexx(), ArrayClass::dimensionRexx(), RexxInteger::divide(), NumberString::divide(), RexxString::divide(), ArrayClass::empty(), StemClass::empty(), ListClass::emptyRexx(), HashCollection::emptyRexx(), RexxString::encodeBase64(), EndClassDefinition, EndSpecialClassDefinition, MutableBuffer::endsWithRexx(), RexxString::endsWithRexx(), RexxClass::enhanced(), StringHashCollection::entryRexx(), RexxClass::equal(), RexxInteger::equal(), NumberString::equal(), RexxObject::equal(), PointerClass::equal(), RexxString::equal(), RexxString::equals(), Activity::error(), MessageClass::errorCondition(), ArrayClass::fillRexx(), PackageClass::findClassRexx(), PackageClass::findNamespaceRexx(), PackageClass::findProgramRexx(), PackageClass::findPublicClassRexx(), PackageClass::findPublicRoutineRexx(), PackageClass::findRoutineRexx(), ListClass::firstItemRexx(), ArrayClass::firstRexx(), ListClass::firstRexx(), RexxInteger::floor(), NumberString::floor(), RexxString::floor(), RexxInteger::format(), RexxString::format(), NumberString::formatRexx(), PackageClass::formRexx(), PackageClass::fuzzRexx(), RexxClass::getAnnotationRexx(), PackageClass::getAnnotationRexx(), BaseExecutable::getAnnotationRexx(), RexxClass::getAnnotations(), PackageClass::getAnnotations(), BaseExecutable::getAnnotations(), RexxInfo::getArchitecture(), RexxContext::getArgs(), StackFrameClass::getArguments(), RexxClass::getBaseClass(), MutableBuffer::getBufferSize(), RexxInfo::getCaseSensitiveFiles(), PackageClass::getClassesRexx(), RexxContext::getCondition(), StackFrameClass::getContext(), RexxInfo::getDebug(), RexxContext::getDigits(), RexxInfo::getDigits(), ArrayClass::getDimensionsRexx(), RexxInfo::getDirectorySeparator(), RexxContext::getExecutable(), StackFrameClass::getExecutable(), RexxInfo::getFileEndOfLine(), ArrayClass::getFirstItem(), RexxContext::getForm(), RexxInfo::getForm(), RexxContext::getFuzz(), RexxInfo::getFuzz(), getGlobalName(), RexxClass::getId(), PackageClass::getImportedClassesRexx(), PackageClass::getImportedPackagesRexx(), PackageClass::getImportedRoutinesRexx(), RexxInfo::getInternalDigits(), RexxInfo::getInternalMaxNumber(), RexxInfo::getInternalMinNumber(), RexxContext::getInterpreter(), RexxInfo::getInterpreterDate(), RexxInfo::getInterpreterName(), RexxInfo::getInterpreterVersion(), RexxContext::getInvocation(), StackFrameClass::getInvocation(), RexxInfo::getLanguageLevel(), ArrayClass::getLastItem(), RexxContext::getLine(), StackFrameClass::getLine(), ActivityManager::getLocalRexx(), PackageClass::getMainRexx(), RexxInfo::getMajorVersion(), RexxInfo::getMaxArraySize(), RexxInfo::getMaxExponent(), RexxInfo::getMaxPathLength(), RexxClass::getMetaClass(), PackageClass::getMethodsRexx(), RexxInfo::getMinExponent(), RexxInfo::getModification(), RexxContext::getName(), StackFrameClass::getName(), VariableReference::getName(), PackageClass::getNamespacesRexx(), RexxClass::getPackage(), RexxContext::getPackage(), RexxInfo::getPackage(), BaseExecutable::getPackage(), PackageClass::getPackageLocal(), RexxInfo::getPathSeparator(), RexxInfo::getPlatform(), PackageClass::getProgramName(), PackageClass::getPublicClassesRexx(), PackageClass::getPublicRoutinesRexx(), RexxInfo::getRelease(), PackageClass::getResourceRexx(), PackageClass::getResourcesRexx(), RexxInfo::getRevision(), HashCollection::getRexx(), ArrayClass::getRexx(), ListClass::getRexx(), RexxInfo::getRexxExecutable(), RexxInfo::getRexxLibrary(), PackageClass::getRoutinesRexx(), RexxContext::getRS(), MethodClass::getScopeRexx(), PackageClass::getSourceLineRexx(), PackageClass::getSourceRexx(), PackageClass::getSourceSizeRexx(), RexxContext::getStackFrames(), RexxClass::getSubClasses(), RexxClass::getSuperClass(), RexxClass::getSuperClasses(), StackFrameClass::getTarget(), RexxContext::getThread(), StackFrameClass::getTraceLine(), StackFrameClass::getType(), VariableReference::getValue(), RexxContext::getVariables(), Interpreter::getVersionString(), MessageClass::halt(), StringHashCollection::hasEntryRexx(), MessageClass::hasError(), RexxInteger::hashCode(), NumberString::hashCode(), RexxObject::hashCode(), StemClass::hasIndex(), HashCollection::hasIndexRexx(), ArrayClass::hasIndexRexx(), ListClass::hasIndexRexx(), StemClass::hasItem(), ArrayClass::hasItemRexx(), HashCollection::hasItemRexx(), ListClass::hasItemRexx(), BagClass::hasItemRexx(), RelationClass::hasItemRexx(), RexxObject::hasMethodRexx(), MessageClass::hasResult(), HideMethod, RexxObject::identityHashRexx(), SupplierClass::index(), StemClass::index(), ArrayClass::indexRexx(), ListClass::indexRexx(), HashCollection::indexRexx(), RexxClass::inherit(), InheritInstanceMethods, RexxClass::inheritInstanceMethodsRexx(), ActivityManager::init(), Interpreter::init(), RexxInfo::initialize(), PackageManager::initialize(), Activity::initializeThreadContext(), RexxObject::initRexx(), MutableBuffer::insert(), RexxString::insert(), ArrayClass::insertRexx(), ListClass::insertRexx(), RexxObject::instanceMethodRexx(), RexxObject::instanceMethodsRexx(), RexxInteger::integerDivide(), NumberString::integerDivide(), RexxString::integerDivide(), IntegerEight, IntegerFive, IntegerFour, IntegerMinusOne, IntegerNine, IntegerOne, IntegerSeven, IntegerSix, IntegerThree, IntegerTwo, IntegerZero, RexxClass::isAbstractRexx(), MethodClass::isAbstractRexx(), MethodClass::isAttributeRexx(), MethodClass::isConstantRexx(), ArrayClass::isEmptyRexx(), ListClass::isEmptyRexx(), StemClass::isEmptyRexx(), HashCollection::isEmptyRexx(), RexxInteger::isGreaterOrEqual(), NumberString::isGreaterOrEqual(), RexxString::isGreaterOrEqual(), RexxInteger::isGreaterThan(), NumberString::isGreaterThan(), RexxString::isGreaterThan(), MethodClass::isGuardedRexx(), RexxObject::isInstanceOfRexx(), RexxInteger::isLessOrEqual(), NumberString::isLessOrEqual(), RexxString::isLessOrEqual(), RexxInteger::isLessThan(), NumberString::isLessThan(), RexxString::isLessThan(), RexxClass::isMetaClassRexx(), RexxObject::isNilRexx(), PointerClass::isNull(), MethodClass::isPackageRexx(), MethodClass::isPrivateRexx(), MethodClass::isProtectedRexx(), RexxClass::isSubclassOf(), SupplierClass::item(), ArrayClass::itemsRexx(), ListClass::itemsRexx(), StemClass::itemsRexx(), HashCollection::itemsRexx(), ListClass::lastItemRexx(), MutableBuffer::lastPos(), RexxString::lastPosRexx(), ArrayClass::lastRexx(), ListClass::lastRexx(), RexxString::left(), MutableBuffer::lengthRexx(), RexxString::lengthRexx(), loader(), MethodClass::loadExternalMethod(), RoutineClass::loadExternalRoutine(), PackageClass::loadLibraryRexx(), PackageClass::loadPackageRexx(), Interpreter::logicError(), MutableBuffer::lower(), RexxString::lowerRexx(), RexxObject::makeArrayRexx(), RexxObject::makeStringRexx(), MutableBuffer::match(), RexxString::match(), MutableBuffer::matchChar(), RexxString::matchChar(), RexxInteger::Max(), NumberString::Max(), RexxString::Max(), memoryObject, MessageClass::messageCompleted(), MessageClass::messageName(), MessageClass::messageTarget(), RexxClass::method(), RexxClass::methods(), RexxInteger::Min(), NumberString::Min(), RexxString::Min(), RexxInteger::minus(), NumberString::minus(), RexxString::minus(), RexxClass::mixinClassRexx(), RexxInteger::modulo(), NumberString::modulo(), RexxString::modulo(), RexxInteger::multiply(), NumberString::multiply(), RexxString::multiply(), MutableBuffer::mydelete(), new_directory(), new_integer(), new_string(), new_string_table(), MethodClass::newFileRexx(), RoutineClass::newFileRexx(), ArrayClass::newRexx(), BagClass::newRexx(), DirectoryClass::newRexx(), IdentityTable::newRexx(), ListClass::newRexx(), MessageClass::newRexx(), MethodClass::newRexx(), MutableBuffer::newRexx(), RelationClass::newRexx(), RoutineClass::newRexx(), SetClass::newRexx(), StemClass::newRexx(), RexxString::newRexx(), StringTable::newRexx(), SupplierClass::newRexx(), TableClass::newRexx(), BufferClass::newRexx(), RexxContext::newRexx(), EventSemaphoreClass::newRexx(), MutexSemaphoreClass::newRexx(), PointerClass::newRexx(), RexxInfo::newRexx(), StackFrameClass::newRexx(), VariableReference::newRexx(), WeakReference::newRexx(), RexxClass::newRexx(), RexxObject::newRexx(), PackageClass::newRexx(), QueueClass::newRexx(), SupplierClass::next(), ArrayClass::nextRexx(), ListClass::nextRexx(), RexxClass::notEqual(), RexxInteger::notEqual(), NumberString::notEqual(), RexxString::notEqual(), RexxObject::notEqual(), PointerClass::notEqual(), MessageClass::notify(), RexxInteger::notOp(), NumberString::notOp(), RexxString::notOp(), RexxObject::objectName(), RexxObject::objectNameEquals(), ArrayClass::ofRexx(), BagClass::ofRexx(), ListClass::ofRexx(), SetClass::ofRexx(), QueueClass::ofRexx(), OREF_NULL, RexxInteger::orOp(), NumberString::orOp(), RexxString::orOp(), MutableBuffer::overlay(), RexxString::overlay(), QueueClass::peek(), RexxInteger::plus(), NumberString::plus(), RexxString::plus(), RexxString::posRexx(), MutableBuffer::posRexx(), EventSemaphoreClass::post(), EventSemaphoreClass::posted(), RexxInteger::power(), NumberString::power(), RexxString::power(), ArrayClass::previousRexx(), ListClass::previousRexx(), QueueClass::pullRexx(), QueueClass::pushRexx(), ArrayClass::putRexx(), HashCollection::putRexx(), ListClass::putRexx(), QueueClass::putRexx(), RexxClass::queryMixinClass(), QueueClass::queueRexx(), MutexSemaphoreClass::release(), RexxInteger::remainder(), NumberString::remainder(), RexxString::remainder(), StemClass::remove(), RelationClass::removeAll(), StringHashCollection::removeEntryRexx(), StemClass::removeItemRexx(), ArrayClass::removeItemRexx(), ListClass::removeItemRexx(), HashCollection::removeItemRexx(), BagClass::removeItemRexx(), RelationClass::removeItemRexx(), RemoveMethod, HashCollection::removeRexx(), ArrayClass::removeRexx(), ListClass::removeRexx(), MutableBuffer::replaceAt(), RexxString::replaceAt(), MessageClass::replyRexx(), MessageClass::replyWithRexx(), MutexSemaphoreClass::request(), StemClass::request(), VariableReference::request(), RexxObject::requestRexx(), EventSemaphoreClass::reset(), RESOLVE_DEFAULT, CPPCode::resolveExportedMethod(), Activity::resolveProgramName(), MessageClass::result(), ActivityManager::returnActivity(), RexxString::reverse(), RexxString::right(), RexxInteger::round(), NumberString::round(), RexxString::round(), RexxObject::run(), saveImage(), ArrayClass::sectionRexx(), ListClass::sectionRexx(), RexxObject::send(), MessageClass::sendRexx(), RexxObject::sendWith(), MessageClass::sendWithRexx(), MutableBuffer::setBufferSize(), StringHashCollection::setEntryRexx(), MethodClass::setGuardedRexx(), RexxObject::setMethod(), DirectoryClass::setMethodRexx(), MethodClass::setPrivateRexx(), MethodClass::setProtectedRexx(), MethodClass::setSecurityManager(), RoutineClass::setSecurityManager(), PackageClass::setSecurityManagerRexx(), MutableBuffer::setTextRexx(), MethodClass::setUnguardedRexx(), VariableReference::setValueRexx(), RexxInteger::sign(), NumberString::Sign(), RexxString::sign(), ArrayClass::sizeRexx(), BaseExecutable::source(), RexxString::space(), MutableBuffer::space(), ArrayClass::stableSortRexx(), ArrayClass::stableSortWithRexx(), RexxObject::start(), StartClassDefinition, MessageClass::startRexx(), MutableBuffer::startsWithRexx(), RexxString::startsWithRexx(), RexxObject::startWith(), MessageClass::startWithRexx(), RexxClass::strictEqual(), RexxInteger::strictEqual(), NumberString::strictEqual(), RexxObject::strictEqual(), RexxString::strictEqual(), RexxInteger::strictGreaterOrEqual(), NumberString::strictGreaterOrEqual(), RexxString::strictGreaterOrEqual(), RexxInteger::strictGreaterThan(), NumberString::strictGreaterThan(), RexxString::strictGreaterThan(), RexxInteger::strictLessOrEqual(), NumberString::strictLessOrEqual(), RexxString::strictLessOrEqual(), RexxInteger::strictLessThan(), NumberString::strictLessThan(), RexxString::strictLessThan(), RexxInteger::strictNotEqual(), NumberString::strictNotEqual(), RexxString::strictNotEqual(), RexxObject::strictNotEqual(), RexxObject::stringRexx(), RexxString::strip(), RexxString::subchar(), MutableBuffer::subchar(), RexxClass::subclassRexx(), RexxString::substr(), MutableBuffer::substr(), MutableBuffer::subWord(), RexxString::subWord(), MutableBuffer::subWords(), RexxString::subWords(), ArrayClass::supplier(), ListClass::supplier(), StemClass::supplier(), HashCollection::supplier(), HashCollection::supplierRexx(), T_NilObject, TheClassClass, TheCommonRetrievers, TheEnvironment, TheFalseObject, TheIntegerClass, TheNilObject, TheNullArray, TheNullPointer, TheNumberStringClass, TheRexxPackage, TheSystem, TheTrueObject, StemClass::toDirectory(), ArrayClass::toString(), PackageClass::traceRexx(), RexxString::translate(), MutableBuffer::translate(), RexxString::trunc(), RexxInteger::trunc(), NumberString::trunc(), RexxClass::uninherit(), HashCollection::uniqueIndexes(), StemClass::unknownRexx(), StringHashCollection::unknownRexx(), VariableReference::unknownRexx(), RexxObject::unsetMethod(), DirectoryClass::unsetMethodRexx(), MutableBuffer::upper(), RexxString::upperRexx(), WeakReference::value(), VARIABLE_RC, VARIABLE_RESULT, VARIABLE_SELF, VARIABLE_SIGL, VARIABLE_SUPER, MutableBuffer::verify(), RexxString::verify(), MessageClass::wait(), EventSemaphoreClass::wait(), MutableBuffer::word(), RexxString::word(), MutableBuffer::wordIndex(), RexxString::wordIndex(), MutableBuffer::wordLength(), RexxString::wordLength(), MutableBuffer::wordPos(), RexxString::wordPos(), MutableBuffer::words(), RexxString::words(), RexxString::x2b(), RexxString::x2c(), RexxString::x2d(), RexxInteger::xorOp(), NumberString::xorOp(), and RexxString::xorOp().
Referenced by initialize().
createRexxPackage()
void MemoryObject::createRexxPackage () private
Create the base Rexx package object. All Rexx-defined classes in the image will be added to this package.
Definition at line 213 of file Setup.cpp.
References rexxPackage.
Referenced by createImage().
createStrings()
void MemoryObject::createStrings ()
Definition at line 52 of file GlobalNames.cpp.
References globalStrings, and new_string_table().
Referenced by createImage().
defineMethod()
void MemoryObject::defineMethod (const char * name, RexxBehaviour * behaviour, PCPPM entryPoint, size_t arguments, const char * entryPointName) private
Add a C++ method to an object's behaviour.
Parameters
name The name of the method.
behaviour The target behaviour.
entryPoint The entry point of the C++ method that implements the method.
arguments The method argument style (argument count or array indicator).
Definition at line 106 of file Setup.cpp.
References RexxInternalObject::behaviour, and RexxBehaviour::defineMethod().
definePrivateMethod()
void MemoryObject::definePrivateMethod (const char * name, RexxBehaviour * behaviour, PCPPM entryPoint, size_t arguments, const char * entryPointName) private
Add a C++ method to an object's behaviour. This method is marked as private.
Parameters
name The name of the method.
behaviour The target behaviour.
entryPoint The entry point of the C++ method that implements the method.
arguments The method argument style (argument count or array indicator).
Definition at line 159 of file Setup.cpp.
References RexxInternalObject::behaviour, RexxBehaviour::defineMethod(), and MethodClass::setPrivate().
defineProtectedMethod()
void MemoryObject::defineProtectedMethod (const char * name, RexxBehaviour * behaviour, PCPPM entryPoint, size_t arguments, const char * entryPointName) private
Add a C++ method to an object's behaviour. This method is marked as protected.
Parameters
name The name of the method.
behaviour The target behaviour.
entryPoint The entry point of the C++ method that implements the method.
arguments The method argument style (argument count or array indicator).
Definition at line 122 of file Setup.cpp.
References RexxInternalObject::behaviour, RexxBehaviour::defineMethod(), and MethodClass::setProtected().
defineUnguardedMethod()
void MemoryObject::defineUnguardedMethod (const char * name, RexxBehaviour * behaviour, PCPPM entryPoint, size_t arguments, const char * entryPointName) private
Add a C++ method to an object's behaviour. This method is marked as unguarded.
Parameters
name The name of the method.
behaviour The target behaviour.
entryPoint The entry point of the C++ method that implements the method.
arguments The method argument style (argument count or array indicator).
Definition at line 140 of file Setup.cpp.
References RexxInternalObject::behaviour, RexxBehaviour::defineMethod(), and MethodClass::setUnguarded().
deleteTemporaryObject()
void MemoryObject::deleteTemporaryObject (void * storage)
Delete a temporary object.
Parameters
storage The storage pointer to release,
Definition at line 1278 of file RexxMemory.cpp.
Referenced by LiveStack::operator delete().
dumpImageStats()
void MemoryObject::dumpImageStats ()
Dump the image statistics
Definition at line 1693 of file RexxMemory.cpp.
References MemoryStats::clear(), MemorySegmentSet::gatherStats(), MemoryStats::largeStats, newSpaceLargeSegments, newSpaceNormalSegments, MemoryStats::normalStats, and MemoryStats::printMemoryStats().
Referenced by RexxInstructionOptions::execute().
freeSegment()
void MemoryObject::freeSegment (MemorySegment * segment)
Return a memory segment to the system.
Parameters
segment The segment to release.
Definition at line 528 of file RexxMemory.cpp.
References SystemInterpreter::releaseSegmentMemory(), and segments.
Referenced by SingleObjectSegmentSet::completeSweepOperation().
getGlobalName()
RexxString * MemoryObject::getGlobalName (const char * value)
Add a string to the global name table.
Parameters
value The new value to add.
Returns
The single instance of this string.
Definition at line 1746 of file RexxMemory.cpp.
References HashCollection::get(), globalStrings, new_string(), OREF_NULL, HashCollection::put(), and RexxInternalObject::stringValue().
Referenced by createImage().
getGlobalStrings()
StringTable* MemoryObject::getGlobalStrings () inline
Definition at line 198 of file RexxMemory.hpp.
References globalStrings.
Referenced by LanguageParser::initializeForParsing().
getUpperGlobalName()
RexxString * MemoryObject::getUpperGlobalName (const char * value)
Add a string to the global name table, in uppercase
Parameters
value The new value to add.
Returns
The single instance of this string.
Definition at line 1776 of file RexxMemory.cpp.
References HashCollection::get(), globalStrings, new_upper_string(), OREF_NULL, HashCollection::put(), and RexxInternalObject::stringValue().
Referenced by addToEnvironment(), addToSystem(), completeSystemClass(), RexxBehaviour::defineMethod(), RexxBehaviour::hideMethod(), and RexxBehaviour::removeMethod().
holdObject()
RexxInternalObject * MemoryObject::holdObject (RexxInternalObject * obj)
Place an object on the hold stack to provide some temporary GC protection.
Parameters
obj The object to hold.
Returns
The same object.
Definition at line 1323 of file RexxMemory.cpp.
References PushThroughStack::push(), and saveStack.
Referenced by holdObject(), and GlobalProtectedObject::~GlobalProtectedObject().
initialize()
void MemoryObject::initialize (bool restoringImage, const char * imageTarget)
Initialize the memory object, including getting the initial memory pool allocations.
Parameters
restoringImage True if we are initializing during an image restore, false if we need to build the initial image environemnt (i.e., called via rexximage during a build).
imageTarget The location to store the image if this is a save operation.
Definition at line 149 of file RexxMemory.cpp.
References allocations, buildVirtualFunctionTable(), collections, createImage(), Memory::DefaultGlobalReferenceSize, NormalSegmentSet::getInitialSet(), LargeSegmentSet::getInitialSet(), globalReferences, globalStrings, liveStack, Memory::LiveStackSize, memoryObject, new_identity_table(), newSpaceLargeSegments, newSpaceNormalSegments, newSpaceSingleSegments, oldSpaceSegments, OREF_NULL, pendingUninits, restore(), restoreImage(), RexxInternalObject::setBehaviour(), TheMemoryBehaviour, and uninitTable.
Referenced by Interpreter::startInterpreter().
lastChanceUninit()
void MemoryObject::lastChanceUninit ()
Force a last-gasp garbage collection and running of the uninits during interpreter instance shutdown. This is an attempt to ensure that all objects with uninit methods get a chance to clean up prior to termination.
Definition at line 324 of file RexxMemory.cpp.
References collectAndUninit(), HashCollection::empty(), and uninitTable.
Referenced by Interpreter::terminateInterpreter().
live()
void MemoryObject::live (size_t liveMark) override virtual
Main live marking routine for normal garbage collection. This starts the process by marking the key root objects.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 823 of file RexxMemory.cpp.
References commonRetrievers, environment, globalReferences, globalStrings, PackageManager::live(), ActivityManager::live(), SystemInterpreter::live(), Interpreter::live(), memory_mark, GlobalProtectedObject::next, old2new, OREF_NULL, GlobalProtectedObject::protectedObject, protectedObjects, rexxPackage, saveStack, and system.
liveGeneral()
void MemoryObject::liveGeneral (MarkReason reason) override virtual
General live marking routine for the memory object.
Parameters
reason The marking reason.
Reimplemented from RexxVirtualBase.
Definition at line 862 of file RexxMemory.cpp.
References commonRetrievers, environment, globalReferences, globalStrings, ActivityManager::liveGeneral(), PackageManager::liveGeneral(), SystemInterpreter::liveGeneral(), Interpreter::liveGeneral(), memory_mark_general, GlobalProtectedObject::next, old2new, GlobalProtectedObject::protectedObject, protectedObjects, rexxPackage, saveStack, and system.
liveStackFull() [1/2]
void MemoryObject::liveStackFull ()
Process a live-stack overflow situation
Definition at line 1160 of file RexxMemory.cpp.
References liveStack, Memory::LiveStackSize, and LiveStack::reallocate().
Referenced by checkLiveStack().
liveStackFull() [2/2]
void MemoryObject::liveStackFull (size_t needed)
Process a predictive live-stack overflow situation
Definition at line 1175 of file RexxMemory.cpp.
References LiveStack::ensureSpace(), and liveStack.
loadImage() [1/2]
void MemoryObject::loadImage (char *& imageBuffer, size_t & imageSize) private
Load the image file into storage
Parameters
imageBuffer The returned image buffer
imageSize The returned image size.
Definition at line 739 of file RexxMemory.cpp.
References BASEIMAGE, SystemInterpreter::getEnvironmentVariable(), SysProcess::getLibraryLocation(), Interpreter::logicError(), and SysFileSystem::primitiveSearchName().
Referenced by restoreImage().
loadImage() [2/2]
bool MemoryObject::loadImage (char *& imageBuffer, size_t & imageSize, FileNameBuffer & imageFile) private
Load the image file into storage
Parameters
imageBuffer The returned image buffer
imageSize The returned image size.
Definition at line 786 of file RexxMemory.cpp.
References allocateImageBuffer(), Interpreter::logicError(), memoryObject, SysFile::open(), SysFile::read(), RX_O_RDONLY, RX_S_IREAD, and RX_SH_DENYWR.
logObjectStats()
void MemoryObject::logObjectStats (RexxInternalObject * obj) inline
Definition at line 186 of file RexxMemory.hpp.
References imageStats, and MemoryStats::logObject().
Referenced by ImageSaveMarkHandler::mark().
logVerboseOutput()
void MemoryObject::logVerboseOutput (const char * message, void * sub1, void * sub2, void * sub3)
Log verbose output events
Parameters
message The main message text.
sub1 The first substitution value.
sub2 The second substitution value.
sub3 third substitution value
Definition at line 220 of file RexxMemory.cpp.
References logMemoryCheck().
Referenced by verboseMessage().
mark()
void MemoryObject::mark (RexxInternalObject * markObject)
Perform a memory management mark operation. This is only used during a real garbage collection.
Parameters
markObject The object being marked.
Definition at line 1193 of file RexxMemory.cpp.
References RexxInternalObject::behaviour, RexxInternalObject::checkVirtualFunctions(), RexxInternalObject::hasNoReferences(), Interpreter::logicError(), markWord, ObjectNeedsMarking, ObjectHeader::OldSpaceBit, pushLiveStack(), and RexxInternalObject::setObjectLive().
Referenced by ObjectHeader::initHeader(), ObjectHeader::isObjectDead(), ObjectHeader::isObjectLive(), ObjectHeader::isObjectMarked(), markObjectsMain(), setObjectLive(), and ObjectHeader::setObjectMark().
markGeneral()
void MemoryObject::markGeneral (void * obj)
When we are doing a general marking operation, all objects call markGeneral for all of its object references. We perform different functions based on what the current marking reason is.
Parameters
obj A pointer to the field being marked. This is passed as a void * because there are lots of issues with passing this as a object type. We just fake things out and avoid the compile problems this way.
Definition at line 1297 of file RexxMemory.cpp.
References currentMarkHandler, MarkHandler::mark(), and OREF_NULL.
markObjects()
void MemoryObject::markObjects ()
Main mark routine for garbage collection.
Definition at line 416 of file RexxMemory.cpp.
References checkUninit(), checkWeakReferences(), markObjectsMain(), uninitTable, and verboseMessage().
Referenced by collect().
markObjectsMain()
void MemoryObject::markObjectsMain (RexxInternalObject * rootObject)
Main memory_mark driving loop
Parameters
rootObject The root object used for the marking (usually the MemoryObject).
Definition at line 232 of file RexxMemory.cpp.
References allocations, mark(), markingObjects, markWord, memory_mark, ObjectHeader::OldSpaceBit, OREF_NULL, popLiveStack(), and pushLiveStack().
Referenced by markObjects().
newLargeSegment()
MemorySegment * MemoryObject::newLargeSegment (size_t requestedBytes, size_t minBytes)
Allocate a segment of the requested size. The requested size is the desired size, while the minimum is the absolute minimum we can handle.
Parameters
requestedBytes The requested bytes for the allocation.
minBytes The minimum acceptable allocation size.
Returns
A new segment.
Definition at line 601 of file RexxMemory.cpp.
References MemorySegment::MemorySegmentOverhead, newSegment(), and MemorySegment::roundSegmentBoundary().
Referenced by LargeSegmentSet::allocateSegment(), and SingleObjectSegmentSet::allocateSegment().
newObject() [1/2]
RexxInternalObject* MemoryObject::newObject (size_t size) inline
Definition at line 113 of file RexxMemory.hpp.
References newObject(), and T_Object.
Referenced by new_object(), and newObject().
newObject() [2/2]
RexxInternalObject * MemoryObject::newObject (size_t requestLength, size_t type)
allocate a new object of the requested size.
Parameters
requestLength The required object length.
type The object type this should be initialized to.
Returns
The storage for creating a new object.
Definition at line 981 of file RexxMemory.cpp.
References NormalSegmentSet::allocateObject(), LargeSegmentSet::allocateObject(), SingleObjectSegmentSet::allocateObject(), allocations, RexxBehaviour::getPrimitiveBehaviour(), NormalSegmentSet::handleAllocationFailure(), LargeSegmentSet::handleAllocationFailure(), SingleObjectSegmentSet::handleAllocationFailure(), MemorySegment::LargeBlockThreshold, markWord, Memory::MinimumObjectSize, newSpaceLargeSegments, newSpaceNormalSegments, newSpaceSingleSegments, OREF_NULL, pushSaveStack(), Memory::roundObjectBoundary(), saveStack, MemorySegment::SingleBlockThreshold, type, and virtualFunctionTable.
newObjects()
ArrayClass* MemoryObject::newObjects (size_t size, size_t count, size_t objectType)
Referenced by new_arrayOfObject().
newSegment() [1/2]
MemorySegment * MemoryObject::newSegment (size_t requestedBytes)
Allocate the memory for a managed heap segment.
Parameters
requestedBytes The size required for the segment
Returns
A new segment or NULL in the case of an allocation failure.
Definition at line 505 of file RexxMemory.cpp.
References SystemInterpreter::allocateSegmentMemory(), and segments.
Referenced by MemorySegmentSet::allocateSegment(), MemorySegment::insertAfter(), MemorySegment::insertBefore(), newLargeSegment(), newSegment(), and NormalSegmentSet::NormalSegmentSet().
newSegment() [2/2]
MemorySegment * MemoryObject::newSegment (size_t requestedBytes, size_t minBytes)
Allocate a segment of the requested size. The requested size is the desired size, while the minimum is the absolute minimum we can handle. This takes care of the overhead accounting and additional rounding. The requested size is assumed to have been rounded up to the next "appropriate" boundary already, and the segment overhead will be allocated from that part, if possible. Otherwise, an additional page is added.
Parameters
requestedBytes The suggested number of bytes to allocate.
minBytes The minimum number of bytes we can accept. Failure to allocate the minimum is an out-of-memory situation.
Returns
The new memory segment.
Definition at line 563 of file RexxMemory.cpp.
References MemorySegment::MemorySegmentOverhead, newSegment(), and verboseMessage().
oldObject()
RexxInternalObject * MemoryObject::oldObject (size_t requestLength)
Allocate an object in "old space". This is generally used just for special memory objects or for allocating the space for the restored image.
Parameters
requestLength The size of the object.
Returns
Storage for a new object.
Definition at line 936 of file RexxMemory.cpp.
References OldSpaceSegmentSet::allocateObject(), markWord, oldSpaceSegments, OREF_NULL, Memory::roundObjectBoundary(), T_Object, TheObjectBehaviour, and virtualFunctionTable.
Referenced by allocateImageBuffer().
operator RexxObject *()
MemoryObject::operator RexxObject * () inline
Definition at line 101 of file RexxMemory.hpp.
operator=()
RexxObject* MemoryObject::operator= (DeadObject * d) inline
Definition at line 102 of file RexxMemory.hpp.
popLiveStack()
RexxInternalObject* MemoryObject::popLiveStack () inline
Definition at line 217 of file RexxMemory.hpp.
References liveStack, and LiveStack::pop().
Referenced by markObjectsMain(), saveImage(), and tracingMark().
pushLiveStack()
void MemoryObject::pushLiveStack (RexxInternalObject * obj) inline
Definition at line 216 of file RexxMemory.hpp.
References checkLiveStack(), liveStack, and LiveStack::push().
Referenced by mark(), ImageSaveMarkHandler::mark(), TracingMarkHandler::mark(), markObjectsMain(), saveImage(), and tracingMark().
pushSaveStack()
void MemoryObject::pushSaveStack (RexxInternalObject * obj) inline
Definition at line 187 of file RexxMemory.hpp.
References PushThroughStack::push(), and saveStack.
Referenced by newObject().
removeGlobalReference()
void MemoryObject::removeGlobalReference (RexxInternalObject * obj)
Remove a global object reference to an object. The references are counted, so it takes a like number of remove calls to remove the object from the table.
Parameters
obj The object to remove global reference lock.
Definition at line 1682 of file RexxMemory.cpp.
References MapTable::decrement(), and globalReferences.
removeHold()
void MemoryObject::removeHold (RexxInternalObject * obj) inline
Definition at line 133 of file RexxMemory.hpp.
References PushThroughStack::remove(), and saveStack.
removeSavedObject()
void MemoryObject::removeSavedObject (RexxInternalObject * obj) inline
Definition at line 188 of file RexxMemory.hpp.
References PushThroughStack::remove(), and saveStack.
removeUninitObject()
void MemoryObject::removeUninitObject (RexxInternalObject * obj)
Remove an object from the uninit tables. This can happen if a setMethod() on an object removes the uninit method.
Parameters
obj The object to remove.
Definition at line 394 of file RexxMemory.cpp.
References HashCollection::remove(), and uninitTable.
Referenced by RexxInternalObject::removedUninit().
resetMarkHandler()
void MemoryObject::resetMarkHandler () inline private
Definition at line 272 of file RexxMemory.hpp.
References currentMarkHandler, and defaultMarkHandler.
Referenced by saveImage(), unflattenObjectBuffer(), and unflattenProxyObjects().
reSize()
void MemoryObject::reSize (RexxInternalObject * shrinkObj, size_t requestSize)
Resize an object to a smaller size. Usually used for array objects after a reallocation.
The object shrinkObj only needs to be the size of newSize If the left over space is big enough to become a dead object we will shrink the object to the specified size.
NOTE: Since memory knows nothing about any objects that are in the extra space, it cannot do anything about them if this is an OldSpace objetc, therefore the caller must have already take care of this.
Parameters
shrinkObj The object to resize.
requestSize The new object size.
Definition at line 1077 of file RexxMemory.cpp.
References RexxInternalObject::getObjectSize(), Memory::MinimumObjectSize, Memory::roundObjectResize(), and RexxInternalObject::setObjectSize().
Referenced by ArrayClass::resize().
restore()
void MemoryObject::restore ()
Memory management image restore functions
Definition at line 1812 of file RexxMemory.cpp.
References Memory::DefaultOld2NewSize, ActivityManager::init(), Interpreter::init(), IntegerEight, IntegerFive, IntegerFour, IntegerMinusOne, IntegerNine, IntegerOne, IntegerSeven, IntegerSix, IntegerThree, IntegerTwo, IntegerZero, memoryObject, new_integer(), PackageManager::restore(), RESTORE_CLASS, RexxInternalObject::setOldSpace(), and setUpMemoryTables().
Referenced by initialize().
restoreImage()
void MemoryObject::restoreImage () private
Restore a saved image to usefulness.
Definition at line 627 of file RexxMemory.cpp.
References RexxInternalObject::behaviour, ArrayClass::get(), RexxBehaviour::getClassType(), RexxInternalObject::hasReferences(), Activity::initializeThreadContext(), RexxInternalObject::isNonPrimitive(), RexxVirtualBase::liveGeneral(), loadImage(), memoryObject, RexxInternalObject::nextObject(), RexxBehaviour::primitiveBehaviours, PackageManager::restore(), RexxBehaviour::restore(), restoredImage, RexxBehaviour::restoreSavedPrimitiveBehaviour(), restoreStrings(), RESTORINGIMAGE, saveArray_CLASS, saveArray_COMMON_RETRIEVERS, saveArray_ENV, saveArray_FALSE, saveArray_NAME_STRINGS, saveArray_NIL, saveArray_NULLA, saveArray_NULLPOINTER, saveArray_PACKAGES, saveArray_PBEHAV, saveArray_REXX_PACKAGE, saveArray_SYSTEM, saveArray_TRUE, setMarkHandler(), RexxInternalObject::setOldSpace(), RexxInternalObject::setVirtualFunctions(), T_Last_Exported_Class, TheClassClass, TheCommonRetrievers, TheEnvironment, TheFalseObject, TheNilObject, TheNullArray, TheNullPointer, TheRexxPackage, TheSystem, TheTrueObject, and virtualFunctionTable.
Referenced by initialize().
restoreStrings()
void MemoryObject::restoreStrings (ArrayClass * stringArray)
Restore all globally available string objects during an image restore.
Parameters
stringArray The string array from the image.
Definition at line 101 of file GlobalNames.cpp.
References ArrayClass::data().
Referenced by restoreImage().
runUninits()
void MemoryObject::runUninits ()
Run any pending uninit methods for this activity.
Definition at line 337 of file RexxMemory.cpp.
References ActivityManager::currentActivity, HashContents::TableIterator::isAvailable(), RexxInternalObject::isReadyForUninit(), HashCollection::iterator(), OREF_NULL, pendingUninits, processingUninits, Activity::run(), uninitTable, and verboseMessage().
Referenced by checkUninitQueue(), and collectAndUninit().
saveImage()
void MemoryObject::saveImage (const char * imageTarget)
Save the memory image as part of the interpreter build.
Definition at line 1334 of file RexxMemory.cpp.
References BASEIMAGE, RexxInternalObject::behaviour, bumpMarkWord(), MemoryStats::clear(), SysFile::close(), PackageManager::getImageData(), RexxBehaviour::getPrimitiveBehaviour(), ImageSaveMarkHandler::imageOffset, imageStats, RexxInternalObject::isNonPrimitive(), RexxVirtualBase::liveGeneral(), markWord, Memory::MaxImageSize, memory_mark_general, new_array(), SysFile::open(), OREF_NULL, popLiveStack(), PREPARINGIMAGE, MemoryStats::printSavedImageStats(), pushLiveStack(), ArrayClass::put(), resetMarkHandler(), RX_O_CREAT, RX_O_TRUNC, RX_O_WRONLY, RX_S_IREAD, RX_S_IWRITE, RX_SH_DENYRW, saveArray_CLASS, saveArray_COMMON_RETRIEVERS, saveArray_ENV, saveArray_FALSE, saveArray_highest, saveArray_NAME_STRINGS, saveArray_NIL, saveArray_NULLA, saveArray_NULLPOINTER, saveArray_PACKAGES, saveArray_PBEHAV, saveArray_REXX_PACKAGE, saveArray_SYSTEM, saveArray_TRUE, saveStrings(), SAVINGIMAGE, setMarkHandler(), RexxInternalObject::setVirtualFunctions(), T_Last_Exported_Class, TheClassClass, TheCommonRetrievers, TheEnvironment, TheFalseObject, TheNilObject, TheNullArray, TheNullPointer, TheRexxPackage, TheSystem, TheTrueObject, tracingMark(), and SysFile::write().
Referenced by createImage().
saveStrings()
ArrayClass * MemoryObject::saveStrings ()
Save all globally available string objects in the image.
Returns
An array of all global string objects.
Definition at line 71 of file GlobalNames.cpp.
References new_array().
Referenced by saveImage().
scavengeSegmentSets()
void MemoryObject::scavengeSegmentSets (MemorySegmentSet * requestor, size_t allocationLength)
Orchestrate sharing of sharing of storage between the segment sets in low storage conditions. We do this only as a last ditch, as we'll end up fragmenting the large heap with small blocks, messing up the benefits of keeping the heaps separate. We first look a set to donate a segment to the requesting set. We try to find a block of storage large enough for the request than we can add to our dead cache until the next GC cycle.
Parameters
requestor The segment set needing to steal storage.
allocationLength The allocation length needed.
Definition at line 1112 of file RexxMemory.cpp.
References MemorySegmentSet::addDeadObject(), MemorySegmentSet::donateObject(), DeadObject::getObjectSize(), MemorySegmentSet::is(), MemorySegmentSet::name, newSpaceLargeSegments, newSpaceNormalSegments, MemorySegmentSet::SET_NORMAL, and verboseMessage().
Referenced by NormalSegmentSet::handleAllocationFailure(), and LargeSegmentSet::handleAllocationFailure().
setMarkHandler()
void MemoryObject::setMarkHandler (MarkHandler * h) inline private
Definition at line 271 of file RexxMemory.hpp.
References currentMarkHandler.
Referenced by restoreImage(), saveImage(), unflattenObjectBuffer(), and unflattenProxyObjects().
setObjectLive()
static void MemoryObject::setObjectLive (void * o, size_t mark) inline static
Definition at line 221 of file RexxMemory.hpp.
References mark().
setOref()
void MemoryObject::setOref (RexxInternalObject * oldValue, RexxInternalObject * value)
Update a reference to an object when the target object is a member of the OldSpace.
Parameters
oldValue The old field needing updating.
value The new value being assigned.
Returns
The assigned object value.
Definition at line 1635 of file RexxMemory.cpp.
References MapTable::decrement(), MapTable::increment(), RexxInternalObject::isNewSpace(), old2new, and OREF_NULL.
Referenced by OrefSet().
setUpMemoryTables()
void MemoryObject::setUpMemoryTables (MapTable * old2newTable)
Set up the initial memory table.
Parameters
old2newTable The old-to-new tracking table.
Definition at line 1730 of file RexxMemory.cpp.
References old2new, saveStack, and Memory::SaveStackSize.
Referenced by create(), and restore().
shutdown()
void MemoryObject::shutdown ()
Free all the memory pools currently accessed by this process If not already released. Then set process Pool to NULL, indicate pools have been released.
Definition at line 1711 of file RexxMemory.cpp.
References liveStack, SystemInterpreter::releaseSegmentMemory(), and segments.
temporaryObject()
void * MemoryObject::temporaryObject (size_t requestLength)
Allocate and setup a temporary object obtained via malloc storage. This is used currently only by the mark routine to expand the size of the live stack during a garbage collection.
Parameters
requestLength The size of the object.
Returns
Storage for creating a new object.
Definition at line 1243 of file RexxMemory.cpp.
References Error_System_resources, Interpreter::logicError(), markingObjects, OREF_NULL, reportException(), and Memory::roundObjectBoundary().
Referenced by LiveStack::operator new().
tracingMark()
void MemoryObject::tracingMark (RexxInternalObject * root, MarkReason reason)
Perform a general marking operation with a specified reason. This performs no real operation, but touches all of the objects and traverses the live object tree. Usually used during image save preparation.
Parameters
root The root object to mark from.
reason The marking reason.
Definition at line 1464 of file RexxMemory.cpp.
References memory_mark_general, OREF_NULL, popLiveStack(), and pushLiveStack().
Referenced by saveImage().
transferSegmentToNormalSet()
void MemoryObject::transferSegmentToNormalSet (MemorySegment * segment)
Transfer a memory segment from the single object pool into the normal segment space because of array object expansion.
Parameters
segment The segment to transfer.
Definition at line 1151 of file RexxMemory.cpp.
References newSpaceNormalSegments, and MemorySegmentSet::transferSegment().
Referenced by SingleObjectSegmentSet::completeSweepOperation().
unflattenObjectBuffer()
RexxInternalObject * MemoryObject::unflattenObjectBuffer (Envelope * envelope, BufferClass * sourceBuffer, char * startPointer, size_t dataLength)
Perform an in-place unflatten operation on an object in a buffer.
Parameters
envelope The envelope for the unflatten operation.
sourceBuffer The source buffer that contains this data (will need fixups at the end)
startPointer The starting data location in the buffer.
dataLength The length of the data to unflatten
Returns
The first "real" object in the buffer.
Definition at line 1496 of file RexxMemory.cpp.
References RexxInternalObject::behaviour, RexxBehaviour::getClassType(), RexxInternalObject::getObjectSize(), RexxInternalObject::isNonPrimitive(), RexxVirtualBase::liveGeneral(), markWord, memoryObject, RexxInternalObject::nextObject(), OREF_NULL, resetMarkHandler(), RexxBehaviour::resolveNonPrimitiveBehaviour(), RexxBehaviour::restoreSavedPrimitiveBehaviour(), setMarkHandler(), RexxInternalObject::setObjectLive(), RexxInternalObject::setObjectSize(), RexxInternalObject::setVirtualFunctions(), UNFLATTENINGOBJECT, unflattenProxyObjects(), and virtualFunctionTable.
Referenced by Envelope::puff().
unflattenProxyObjects()
void MemoryObject::unflattenProxyObjects (Envelope * envelope, RexxInternalObject * firstObject, RexxInternalObject * endObject)
Run the list of objects in an unflattened buffer calling the unflatten() method to perform any proxy/collection table processing.
Parameters
envelope The envelope for the unflatten operation.
firstObject The first object of the buffer.
endObject The end location for the buffer (actually the first object past the end of the buffer).
Definition at line 1595 of file RexxMemory.cpp.
References RexxInternalObject::isObjectLive(), RexxVirtualBase::liveGeneral(), markWord, memoryObject, RexxInternalObject::nextObject(), resetMarkHandler(), setMarkHandler(), and UNFLATTENINGOBJECT.
Referenced by unflattenObjectBuffer().
verboseMessage() [1/7]
void MemoryObject::verboseMessage (const char * message) inline
Definition at line 143 of file RexxMemory.hpp.
References logVerboseOutput().
Referenced by MemorySegmentSet::addSegment(), MemorySegmentSet::adjustMemorySize(), SingleObjectSegmentSet::allocateObject(), collect(), LargeSegmentSet::completeSweepOperation(), SingleObjectSegmentSet::completeSweepOperation(), LargeSegmentSet::expandSegmentSet(), NormalSegmentSet::handleAllocationFailure(), LargeSegmentSet::handleAllocationFailure(), SingleObjectSegmentSet::handleAllocationFailure(), markObjects(), newSegment(), runUninits(), scavengeSegmentSets(), NormalSegmentSet::suggestMemoryExpansion(), LargeSegmentSet::suggestMemoryExpansion(), and MemorySegmentSet::transferSegment().
verboseMessage() [2/7]
void MemoryObject::verboseMessage (const char * message, const char * sub1, size_t sub2) inline
Definition at line 162 of file RexxMemory.hpp.
References logVerboseOutput().
verboseMessage() [3/7]
void MemoryObject::verboseMessage (const char * message, size_t sub1) inline
Definition at line 150 of file RexxMemory.hpp.
References logVerboseOutput().
verboseMessage() [4/7]
void MemoryObject::verboseMessage (const char * message, size_t sub1, const char * sub2) inline
Definition at line 168 of file RexxMemory.hpp.
References logVerboseOutput().
verboseMessage() [5/7]
void MemoryObject::verboseMessage (const char * message, size_t sub1, const char * sub2, const char * sub3) inline
Definition at line 180 of file RexxMemory.hpp.
References logVerboseOutput().
verboseMessage() [6/7]
void MemoryObject::verboseMessage (const char * message, size_t sub1, size_t sub2) inline
Definition at line 156 of file RexxMemory.hpp.
References logVerboseOutput().
verboseMessage() [7/7]
void MemoryObject::verboseMessage (const char * message, size_t sub1, size_t sub2, size_t sub3) inline
Definition at line 174 of file RexxMemory.hpp.
References logVerboseOutput().
Member Data Documentation
allocations
size_t MemoryObject::allocations private
Definition at line 304 of file RexxMemory.hpp.
Referenced by collect(), initialize(), markObjectsMain(), and newObject().
collections
size_t MemoryObject::collections private
Definition at line 305 of file RexxMemory.hpp.
Referenced by collect(), and initialize().
commonRetrievers
StringTable* MemoryObject::commonRetrievers
Definition at line 233 of file RexxMemory.hpp.
Referenced by live(), and liveGeneral().
currentMarkHandler
MarkHandler* MemoryObject::currentMarkHandler private
Definition at line 299 of file RexxMemory.hpp.
Referenced by markGeneral(), resetMarkHandler(), and setMarkHandler().
defaultMarkHandler
MarkHandler MemoryObject::defaultMarkHandler private
Definition at line 300 of file RexxMemory.hpp.
Referenced by resetMarkHandler().
environment
DirectoryClass* MemoryObject::environment
Definition at line 232 of file RexxMemory.hpp.
Referenced by live(), and liveGeneral().
exportedMethods
PCPPM MemoryObject::exportedMethods[] static
Definition at line 227 of file RexxMemory.hpp.
globalReferences
MapTable* MemoryObject::globalReferences private
Definition at line 309 of file RexxMemory.hpp.
Referenced by addGlobalReference(), initialize(), live(), liveGeneral(), MemoryObject(), and removeGlobalReference().
globalStrings
StringTable* MemoryObject::globalStrings private
Definition at line 308 of file RexxMemory.hpp.
Referenced by createStrings(), getGlobalName(), getGlobalStrings(), getUpperGlobalName(), initialize(), live(), and liveGeneral().
imageStats
MemoryStats* MemoryObject::imageStats private
Definition at line 302 of file RexxMemory.hpp.
Referenced by logObjectStats(), and saveImage().
liveStack
LiveStack* MemoryObject::liveStack private
Definition at line 283 of file RexxMemory.hpp.
Referenced by checkLiveStack(), initialize(), liveStackFull(), popLiveStack(), pushLiveStack(), and shutdown().
markingObjects
bool MemoryObject::markingObjects private
Definition at line 285 of file RexxMemory.hpp.
Referenced by markObjectsMain(), and temporaryObject().
markWord
size_t MemoryObject::markWord
Definition at line 229 of file RexxMemory.hpp.
Referenced by bumpMarkWord(), checkUninit(), checkWeakReferences(), mark(), markObjectsMain(), MemoryObject(), newObject(), oldObject(), SegmentStats::recordObject(), saveImage(), MemorySegmentSet::sweep(), MemorySegmentSet::sweepSingleSegment(), unflattenObjectBuffer(), and unflattenProxyObjects().
newSpaceLargeSegments
LargeSegmentSet MemoryObject::newSpaceLargeSegments private
Definition at line 296 of file RexxMemory.hpp.
Referenced by collect(), dumpImageStats(), initialize(), newObject(), and scavengeSegmentSets().
newSpaceNormalSegments
NormalSegmentSet MemoryObject::newSpaceNormalSegments private
Definition at line 295 of file RexxMemory.hpp.
Referenced by collect(), dumpImageStats(), initialize(), newObject(), scavengeSegmentSets(), and transferSegmentToNormalSet().
newSpaceSingleSegments
SingleObjectSegmentSet MemoryObject::newSpaceSingleSegments private
Definition at line 297 of file RexxMemory.hpp.
Referenced by collect(), initialize(), and newObject().
old2new
MapTable* MemoryObject::old2new private
Definition at line 287 of file RexxMemory.hpp.
Referenced by live(), liveGeneral(), setOref(), and setUpMemoryTables().
oldSpaceSegments
OldSpaceSegmentSet MemoryObject::oldSpaceSegments private
Definition at line 294 of file RexxMemory.hpp.
Referenced by initialize(), and oldObject().
pendingUninits
size_t MemoryObject::pendingUninits private
Definition at line 289 of file RexxMemory.hpp.
Referenced by checkUninit(), checkUninitQueue(), initialize(), and runUninits().
processingUninits
bool MemoryObject::processingUninits private
Definition at line 290 of file RexxMemory.hpp.
Referenced by runUninits().
protectedObjects
GlobalProtectedObject* MemoryObject::protectedObjects
Definition at line 230 of file RexxMemory.hpp.
Referenced by GlobalProtectedObject::GlobalProtectedObject(), live(), liveGeneral(), and GlobalProtectedObject::~GlobalProtectedObject().
restoredImage
char* MemoryObject::restoredImage private
Definition at line 307 of file RexxMemory.hpp.
Referenced by restoreImage().
rexxPackage
PackageClass* MemoryObject::rexxPackage
Definition at line 236 of file RexxMemory.hpp.
Referenced by createRexxPackage(), live(), and liveGeneral().
saveStack
PushThroughStack* MemoryObject::saveStack private
Definition at line 284 of file RexxMemory.hpp.
Referenced by clearSaveStack(), holdObject(), live(), liveGeneral(), MemoryObject(), newObject(), pushSaveStack(), removeHold(), removeSavedObject(), and setUpMemoryTables().
segments
std::vector<MemorySegment *> MemoryObject::segments private
Definition at line 292 of file RexxMemory.hpp.
Referenced by freeSegment(), newSegment(), and shutdown().
system
StringTable* MemoryObject::system
Definition at line 235 of file RexxMemory.hpp.
Referenced by live(), and liveGeneral().
uninitTable
IdentityTable* MemoryObject::uninitTable private
Definition at line 288 of file RexxMemory.hpp.
Referenced by addUninitObject(), checkUninit(), initialize(), lastChanceUninit(), markObjects(), removeUninitObject(), and runUninits().
virtualFunctionTable
void * MemoryObject::virtualFunctionTable = {NULL} static
Definition at line 226 of file RexxMemory.hpp.
Referenced by buildVirtualFunctionTable(), RexxInternalObject::isValid(), newObject(), oldObject(), restoreImage(), RexxInternalObject::setObjectType(), and unflattenObjectBuffer().
weakReferenceList
WeakReference* MemoryObject::weakReferenceList private
Definition at line 291 of file RexxMemory.hpp.
Referenced by addWeakReference(), checkWeakReferences(), and MemoryObject().
The documentation for this class was generated from the following files:
RexxMemory.hpp
Setup.cpp
GlobalNames.cpp
RexxMemory.cpp
VirtualFunctionTable.cpp