ooRexx: RexxLocalVariables Class Reference
RexxLocalVariables Class Reference
#include <RexxLocalVariables.hpp>
Public Types
enum VDictFlag { VDICT_NOVALUE , NESTED_INTERNAL , METHOD_CONTEXT }
Public Member Functions
RexxLocalVariables (RexxObject **frames, size_t items)
RexxLocalVariables ()
void live (size_t)
void liveGeneral (MarkReason reason)
void migrate (Activity *)
void init (RexxActivation *creator, size_t poolSize)
void setFrame (RexxInternalObject **frame)
RexxVariable * lookupVariable (RexxString *name, size_t index)
RexxVariable * findVariable (RexxString *name, size_t index)
RexxVariable * lookupStemVariable (RexxString *name, size_t index)
void createDictionary ()
VariableDictionary * getDictionary ()
void putVariable (RexxVariable *variable, size_t index)
void updateVariable (RexxVariable *)
void setAutoExpose (VariableDictionary *ov)
void aliasVariable (RexxString *n, size_t index, RexxVariable *var)
RexxVariable * get (size_t index)
RexxVariable * find (RexxString *name, size_t index)
size_t getSize ()
void setNovalueOn ()
void setNovalueOff ()
bool getNovalue ()
void setNested ()
void clearNested ()
bool isNested ()
bool autoExpose ()
void procedure (RexxActivation *activation)
void setDictionary (VariableDictionary *dict)
VariableDictionary * getNestedDictionary ()
Static Public Attributes
static const size_t FIRST_VARIABLE_INDEX = VARIABLE_SIGL
Protected Attributes
FlagSet< VDictFlag, 32 > flags
size_t size
RexxActivation * owner
RexxVariable ** locals
VariableDictionary * dictionary
VariableDictionary * objectVariables
Friends
class RexxActivation
Detailed Description
Local variable frame managed by an activation.
Definition at line 67 of file RexxLocalVariables.hpp.
Member Enumeration Documentation
VDictFlag
enum RexxLocalVariables::VDictFlag
Enumerator
VDICT_NOVALUE
NESTED_INTERNAL
METHOD_CONTEXT
Definition at line 72 of file RexxLocalVariables.hpp.
Constructor & Destructor Documentation
RexxLocalVariables() [1/2]
RexxLocalVariables::RexxLocalVariables (RexxObject ** frames, size_t items) inline
Definition at line 79 of file RexxLocalVariables.hpp.
References locals, and size.
RexxLocalVariables() [2/2]
RexxLocalVariables::RexxLocalVariables () inline
Definition at line 80 of file RexxLocalVariables.hpp.
References locals, OREF_NULL, and size.
Member Function Documentation
aliasVariable()
void RexxLocalVariables::aliasVariable (RexxString * name, size_t index, RexxVariable * variable)
Create a local variable object of the given name and store it at the given location.
Parameters
name The variable name.
index The target index position.
Returns
The created or resolved variable object.
Definition at line 544 of file RexxLocalVariables.cpp.
References VariableDictionary::addVariable(), dictionary, Error_Execution_reference_variable_in_use, findVariable(), getDictionary(), RexxVariable::isAliasable(), locals, OREF_NULL, and reportException().
Referenced by RexxActivation::aliasLocalVariable().
autoExpose()
bool RexxLocalVariables::autoExpose () inline
Definition at line 160 of file RexxLocalVariables.hpp.
References objectVariables, and OREF_NULL.
Referenced by findVariable(), lookupStemVariable(), and lookupVariable().
clearNested()
void RexxLocalVariables::clearNested () inline
Definition at line 158 of file RexxLocalVariables.hpp.
References flags, and NESTED_INTERNAL.
Referenced by procedure(), and RexxActivation::run().
createDictionary()
void RexxLocalVariables::createDictionary ()
Create a variable dictionary for this activation to support dynamic access to variables. This is created only when dynamic lookup cannot be avoided.
Definition at line 589 of file RexxLocalVariables.cpp.
References VariableDictionary::addVariable(), dictionary, RexxVariable::getName(), locals, new_variableDictionary(), OREF_NULL, and size.
Referenced by findVariable(), getDictionary(), lookupStemVariable(), lookupVariable(), putVariable(), and updateVariable().
find()
RexxVariable* RexxLocalVariables::find (RexxString * name, size_t index) inline
Definition at line 143 of file RexxLocalVariables.hpp.
References findVariable(), get(), and OREF_NULL.
Referenced by RexxActivation::localStemVariableExists(), and RexxActivation::localVariableExists().
findVariable()
RexxVariable * RexxLocalVariables::findVariable (RexxString * name, size_t index)
Do a more extensive search for a variable, without creating one if it doesn't exist. This is only called after we've had a miss on the variable table.
Parameters
name The target name.
index The target index (can be 0, which requires a search).
Returns
The variable object corresponding to the name, or NULL if not found.
Definition at line 127 of file RexxLocalVariables.cpp.
References VariableDictionary::addVariable(), autoExpose(), createDictionary(), dictionary, RexxVariable::getName(), VariableDictionary::getVariable(), locals, objectVariables, OREF_NULL, VariableDictionary::resolveVariable(), size, and RexxString::strCompare().
Referenced by aliasVariable(), and find().
get()
RexxVariable* RexxLocalVariables::get (size_t index) inline
Definition at line 142 of file RexxLocalVariables.hpp.
References locals.
Referenced by find(), RexxActivation::getLocalStemVariable(), and RexxActivation::getLocalVariable().
getDictionary()
VariableDictionary* RexxLocalVariables::getDictionary () inline
Definition at line 108 of file RexxLocalVariables.hpp.
References createDictionary(), dictionary, and OREF_NULL.
Referenced by aliasVariable(), and RexxActivation::getLocalVariables().
getNestedDictionary()
VariableDictionary* RexxLocalVariables::getNestedDictionary () inline
Definition at line 164 of file RexxLocalVariables.hpp.
References dictionary.
Referenced by RexxActivation::cleanupLocalVariables().
getNovalue()
bool RexxLocalVariables::getNovalue () inline
Definition at line 156 of file RexxLocalVariables.hpp.
References flags, and VDICT_NOVALUE.
Referenced by RexxActivation::novalueEnabled().
getSize()
size_t RexxLocalVariables::getSize () inline
Definition at line 153 of file RexxLocalVariables.hpp.
References size.
Referenced by Activity::allocateLocalVariableFrame().
init()
void RexxLocalVariables::init (RexxActivation * creator, size_t poolSize) inline
Definition at line 91 of file RexxLocalVariables.hpp.
References dictionary, flags, objectVariables, OREF_NULL, owner, and size.
Referenced by RexxActivation::allocateLocalVariables().
isNested()
bool RexxLocalVariables::isNested () inline
Definition at line 159 of file RexxLocalVariables.hpp.
References flags, and NESTED_INTERNAL.
Referenced by RexxActivation::cleanupLocalVariables(), and RexxActivation::run().
live()
void RexxLocalVariables::live (size_t liveMark)
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Definition at line 55 of file RexxLocalVariables.cpp.
References dictionary, locals, memory_mark, objectVariables, owner, and size.
Referenced by ActivationSettings::live().
liveGeneral()
void RexxLocalVariables::liveGeneral (MarkReason reason)
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Definition at line 81 of file RexxLocalVariables.cpp.
References dictionary, locals, memory_mark_general, objectVariables, owner, and size.
Referenced by ActivationSettings::liveGeneral().
lookupStemVariable()
RexxVariable * RexxLocalVariables::lookupStemVariable (RexxString * name, size_t index)
Create a local stem variable variable object of the given name and store it at the given location.
Parameters
name The variable name.
index The variable cache slot (can be zero)
Returns
The located or created variable object.
Definition at line 370 of file RexxLocalVariables.cpp.
References VariableDictionary::addVariable(), autoExpose(), createDictionary(), dictionary, RexxVariable::getName(), VariableDictionary::getStemVariable(), locals, RexxActivation::newLocalVariable(), objectVariables, OREF_NULL, owner, VariableDictionary::resolveVariable(), RexxVariable::set(), size, and RexxString::strCompare().
Referenced by RexxActivation::getLocalStemVariable().
lookupVariable()
RexxVariable * RexxLocalVariables::lookupVariable (RexxString * name, size_t index)
Create a local variable object of the given name and store it at the given location.
Parameters
name The variable name.
index The target index position.
Returns
The created or resolved variable object.
Definition at line 249 of file RexxLocalVariables.cpp.
References VariableDictionary::addVariable(), autoExpose(), createDictionary(), dictionary, RexxVariable::getName(), VariableDictionary::getVariable(), locals, RexxActivation::newLocalVariable(), objectVariables, OREF_NULL, owner, VariableDictionary::resolveVariable(), size, and RexxString::strCompare().
Referenced by RexxActivation::getLocalVariable().
migrate()
void RexxLocalVariables::migrate (Activity * activity)
Migrate the local variable cache to a new activity.
Parameters
activity The new target activity.
Definition at line 105 of file RexxLocalVariables.cpp.
References Activity::allocateLocalVariableFrame(), locals, and size.
Referenced by RexxActivation::run().
procedure()
void RexxLocalVariables::procedure (RexxActivation * activation) inline
Definition at line 162 of file RexxLocalVariables.hpp.
References clearNested(), dictionary, objectVariables, OREF_NULL, and owner.
Referenced by RexxActivation::procedureExpose().
putVariable()
void RexxLocalVariables::putVariable (RexxVariable * variable, size_t index) inline
Definition at line 117 of file RexxLocalVariables.hpp.
References VariableDictionary::addVariable(), createDictionary(), dictionary, RexxVariable::getName(), locals, and OREF_NULL.
Referenced by RexxActivation::putLocalVariable().
setAutoExpose()
void RexxLocalVariables::setAutoExpose (VariableDictionary * ov)
Enable auto exposing of variables. This will switch lookup of variables on the first reference to perform an implicit expose operation.
Parameters
ov The object variables from the current scope used for the expose operation.
Definition at line 234 of file RexxLocalVariables.cpp.
References objectVariables.
Referenced by RexxActivation::autoExpose().
setDictionary()
void RexxLocalVariables::setDictionary (VariableDictionary * dict) inline
Definition at line 163 of file RexxLocalVariables.hpp.
References dictionary.
Referenced by RexxActivation::setLocalVariableDictionary().
setFrame()
void RexxLocalVariables::setFrame (RexxInternalObject ** frame) inline
Definition at line 92 of file RexxLocalVariables.hpp.
References locals, and size.
Referenced by Activity::allocateLocalVariableFrame().
setNested()
void RexxLocalVariables::setNested () inline
Definition at line 157 of file RexxLocalVariables.hpp.
References flags, and NESTED_INTERNAL.
Referenced by RexxActivation::RexxActivation().
setNovalueOff()
void RexxLocalVariables::setNovalueOff () inline
Definition at line 155 of file RexxLocalVariables.hpp.
References flags, and VDICT_NOVALUE.
Referenced by RexxActivation::trapOff().
setNovalueOn()
void RexxLocalVariables::setNovalueOn () inline
Definition at line 154 of file RexxLocalVariables.hpp.
References flags, and VDICT_NOVALUE.
Referenced by RexxActivation::trapOn().
updateVariable()
void RexxLocalVariables::updateVariable (RexxVariable * variable)
Update a local variable context with a provided variable object.
Parameters
variable The variable used for the replacement.
Definition at line 493 of file RexxLocalVariables.cpp.
References VariableDictionary::addVariable(), createDictionary(), dictionary, RexxVariable::getName(), locals, OREF_NULL, size, and RexxString::strCompare().
Referenced by RexxActivation::updateLocalVariable().
Friends And Related Function Documentation
RexxActivation
friend class RexxActivation friend
Definition at line 69 of file RexxLocalVariables.hpp.
Member Data Documentation
dictionary
VariableDictionary* RexxLocalVariables::dictionary protected
Definition at line 174 of file RexxLocalVariables.hpp.
Referenced by aliasVariable(), createDictionary(), findVariable(), getDictionary(), getNestedDictionary(), init(), live(), liveGeneral(), lookupStemVariable(), lookupVariable(), procedure(), putVariable(), setDictionary(), and updateVariable().
FIRST_VARIABLE_INDEX
const size_t RexxLocalVariables::FIRST_VARIABLE_INDEX = VARIABLE_SIGL static
Definition at line 166 of file RexxLocalVariables.hpp.
Referenced by LanguageParser::classDirective(), and LanguageParser::initializeForTranslation().
flags
FlagSet<VDictFlag, 32> RexxLocalVariables::flags protected
Definition at line 170 of file RexxLocalVariables.hpp.
Referenced by clearNested(), getNovalue(), init(), isNested(), setNested(), setNovalueOff(), and setNovalueOn().
locals
RexxVariable** RexxLocalVariables::locals protected
Definition at line 173 of file RexxLocalVariables.hpp.
Referenced by aliasVariable(), createDictionary(), findVariable(), get(), live(), liveGeneral(), lookupStemVariable(), lookupVariable(), migrate(), putVariable(), RexxLocalVariables(), setFrame(), and updateVariable().
objectVariables
VariableDictionary* RexxLocalVariables::objectVariables protected
Definition at line 175 of file RexxLocalVariables.hpp.
Referenced by autoExpose(), findVariable(), init(), live(), liveGeneral(), lookupStemVariable(), lookupVariable(), procedure(), and setAutoExpose().
owner
RexxActivation* RexxLocalVariables::owner protected
Definition at line 172 of file RexxLocalVariables.hpp.
Referenced by init(), live(), liveGeneral(), lookupStemVariable(), lookupVariable(), and procedure().
size
size_t RexxLocalVariables::size protected
Definition at line 171 of file RexxLocalVariables.hpp.
Referenced by createDictionary(), findVariable(), getSize(), init(), live(), liveGeneral(), lookupStemVariable(), lookupVariable(), migrate(), RexxLocalVariables(), setFrame(), and updateVariable().
The documentation for this class was generated from the following files:
RexxLocalVariables.hpp
RexxLocalVariables.cpp