ooRexx: RexxVirtualBase Class Reference
RexxVirtualBase Class Reference
#include <ObjectClass.hpp>
Public Member Functions
virtual void live (size_t)
virtual void liveGeneral (MarkReason reason)
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Protected Member Functions
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
create first base level class dummy virtual function to force the virtual function table to a specific location. Different compilers place the virtual function table pointer at different locations. By having virtual methods defined on the very first class level, we can get things where we expect to find it.
Definition at line 191 of file ObjectClass.hpp.
Constructor & Destructor Documentation
~RexxVirtualBase()
virtual RexxVirtualBase::~RexxVirtualBase () inline protected virtual
Definition at line 194 of file ObjectClass.hpp.
Member Function Documentation
baseVirtual()
virtual void RexxVirtualBase::baseVirtual () inline protected virtual
Definition at line 195 of file ObjectClass.hpp.
flatten()
virtual void RexxVirtualBase::flatten (Envelope *) inline virtual
Reimplemented in ConstantDirective, MethodDictionary, RexxBehaviour, ArrayClass, DirectoryClass, RexxInteger, ListClass, MessageClass, MethodClass, NumberString, RexxObject, PackageClass, RexxInfo, RoutineClass, StackFrameClass, StemClass, SupplierClass, CompoundTableElement, HashCollection, HashContents, ListContents, VariableReference, WeakReference, AttributeGetterCode, ConstantGetterCode, AbstractCode, DelegateCode, RexxCode, RexxVariable, ClassResolver, RexxCompoundVariable, RexxDotVariable, RexxExpressionFunction, RexxExpressionList, RexxExpressionLogical, RexxExpressionMessage, RexxExpressionOperator, QualifiedFunction, RexxStemVariable, RexxSimpleVariable, RexxVariableReference, SpecialDotVariable, VariableReferenceOp, RexxInstructionAddress, RexxInstructionAddressWith, RexxInstructionAssignment, RexxInstructionCall, RexxInstructionDynamicCall, RexxInstructionQualifiedCall, RexxInstructionCallOn, ClassDirective, CommandIOConfiguration, RexxInstructionBaseLoop, RexxInstructionDoOver, RexxInstructionDoOverFor, RexxInstructionDoOverUntil, RexxInstructionDoOverForUntil, RexxInstructionControlledDo, RexxInstructionControlledDoUntil, RexxInstructionDoWhile, RexxInstructionDoCount, RexxInstructionDoCountUntil, RexxInstructionDoWith, RexxInstructionDoWithFor, RexxInstructionDoWithUntil, RexxInstructionDoWithForUntil, RexxInstructionDrop, RexxInstructionElse, RexxInstructionEndIf, RexxInstructionEnd, RexxInstructionExpose, RexxInstructionForward, RexxInstructionGuard, RexxInstructionIf, RexxInstructionLeave, LibraryDirective, RexxInstructionMessage, RexxInstructionParse, ParseTrigger, RexxInstructionProcedure, RexxInstructionRaise, RequiresDirective, RexxInstruction, RexxBlockInstruction, RexxInstructionExpression, RexxInstructionSelect, RexxInstructionSelectCase, RexxInstructionSignal, RexxInstructionDynamicSignal, RexxInstructionSignalOn, RexxInstructionThen, RexxInstructionTrace, UseArgVariableRef, RexxInstructionUse, RexxInstructionUseLocal, RexxInstructionCaseWhen, SmartBuffer, BufferProgramSource, FileProgramSource, ArrayProgramSource, MutableBuffer, RexxString, NativeCode, NativeMethod, NativeRoutine, RegisteredRoutine, and VariableDictionary.
Definition at line 205 of file ObjectClass.hpp.
Referenced by Envelope::pack().
live()
virtual void RexxVirtualBase::live (size_t) inline virtual
Reimplemented in LibraryPackage, CPPCode, ConstantDirective, MethodDictionary, RexxBehaviour, ArrayClass, RexxClass, RexxContext, DirectoryClass, RexxInteger, RexxIntegerClass, ListClass, MessageClass, MethodClass, MutableBuffer, NumberString, RexxObject, PackageClass, RexxInfo, RoutineClass, StackFrameClass, StemClass, RexxString, SupplierClass, CompoundTableElement, HashCollection, HashContents, ListContents, VariableReference, WeakReference, Activity, ActivationFrameBuffer, AttributeGetterCode, ConstantGetterCode, AbstractCode, DelegateCode, NativeActivation, NativeCode, RexxActivation, RexxCode, RexxVariable, SecurityManager, TrapHandler, VariableDictionary, ClassResolver, RexxCompoundVariable, RexxDotVariable, RexxExpressionFunction, RexxExpressionList, RexxExpressionLogical, RexxExpressionMessage, RexxExpressionOperator, QualifiedFunction, RexxStemVariable, RexxSimpleVariable, RexxVariableReference, SpecialDotVariable, VariableReferenceOp, RexxInstructionAddress, RexxInstructionAddressWith, RexxInstructionAssignment, RexxInstructionCall, RexxInstructionDynamicCall, RexxInstructionQualifiedCall, RexxInstructionCallOn, ClassDirective, CommandIOConfiguration, CommandIOContext, DoBlock, RexxInstructionBaseLoop, RexxInstructionDoOver, RexxInstructionDoOverFor, RexxInstructionDoOverUntil, RexxInstructionDoOverForUntil, RexxInstructionControlledDo, RexxInstructionControlledDoUntil, RexxInstructionDoWhile, RexxInstructionDoCount, RexxInstructionDoCountUntil, RexxInstructionDoWith, RexxInstructionDoWithFor, RexxInstructionDoWithUntil, RexxInstructionDoWithForUntil, RexxInstructionDrop, RexxInstructionElse, RexxInstructionEndIf, RexxInstructionEnd, RexxInstructionExpose, RexxInstructionForward, RexxInstructionGuard, RexxInstructionIf, StemInputSource, StreamObjectInputSource, StreamInputSource, ArrayInputSource, RexxInstructionLeave, LibraryDirective, RexxInstructionMessage, StemOutputTarget, StreamObjectOutputTarget, RexxQueueOutputTarget, StreamOutputTarget, CollectionOutputTarget, BufferingOutputTarget, RexxInstructionParse, ParseTrigger, RexxInstructionProcedure, RexxInstructionRaise, RequiresDirective, RexxInstruction, RexxBlockInstruction, RexxInstructionExpression, RexxInstructionSelect, RexxInstructionSelectCase, RexxInstructionSignal, RexxInstructionDynamicSignal, RexxInstructionSignalOn, RexxInstructionThen, RexxInstructionTrace, UseArgVariableRef, RexxInstructionUse, RexxInstructionUseLocal, RexxInstructionCaseWhen, Envelope, InternalStack, MapBucket, MapTable, PushThroughStack, PointerBucket, PointerTable, MemoryObject, SmartBuffer, RexxClause, LanguageParser, BufferProgramSource, FileProgramSource, ArrayProgramSource, RexxToken, and InterpreterInstance.
Definition at line 203 of file ObjectClass.hpp.
liveGeneral()
virtual void RexxVirtualBase::liveGeneral (MarkReason reason) inline virtual
Reimplemented in ConstantDirective, MethodDictionary, RexxBehaviour, ArrayClass, RexxClass, RexxContext, DirectoryClass, RexxInteger, RexxIntegerClass, ListClass, MessageClass, MethodClass, MutableBuffer, NumberString, RexxObject, PackageClass, RexxInfo, RoutineClass, StackFrameClass, StemClass, RexxString, SupplierClass, CompoundTableElement, HashCollection, HashContents, ListContents, VariableReference, Activity, ActivationFrameBuffer, CPPCode, AttributeGetterCode, ConstantGetterCode, DelegateCode, NativeActivation, NativeCode, NativeMethod, NativeRoutine, RegisteredRoutine, RexxActivation, RexxCode, RexxVariable, SecurityManager, TrapHandler, VariableDictionary, ClassResolver, RexxCompoundVariable, RexxDotVariable, RexxExpressionFunction, RexxExpressionList, RexxExpressionLogical, RexxExpressionMessage, RexxExpressionOperator, QualifiedFunction, RexxStemVariable, RexxSimpleVariable, RexxVariableReference, SpecialDotVariable, VariableReferenceOp, RexxInstructionAddress, RexxInstructionAddressWith, RexxInstructionAssignment, RexxInstructionCall, RexxInstructionDynamicCall, RexxInstructionQualifiedCall, RexxInstructionCallOn, ClassDirective, CommandIOConfiguration, CommandIOContext, DoBlock, RexxInstructionBaseLoop, RexxInstructionDoOver, RexxInstructionDoOverFor, RexxInstructionDoOverUntil, RexxInstructionDoOverForUntil, RexxInstructionControlledDo, RexxInstructionControlledDoUntil, RexxInstructionDoWhile, RexxInstructionDoCount, RexxInstructionDoCountUntil, RexxInstructionDoWith, RexxInstructionDoWithFor, RexxInstructionDoWithUntil, RexxInstructionDoWithForUntil, RexxInstructionDrop, RexxInstructionElse, RexxInstructionEndIf, RexxInstructionEnd, RexxInstructionExpose, RexxInstructionForward, RexxInstructionGuard, RexxInstructionIf, StemInputSource, StreamObjectInputSource, StreamInputSource, ArrayInputSource, RexxInstructionLeave, LibraryDirective, RexxInstructionMessage, StemOutputTarget, StreamObjectOutputTarget, RexxQueueOutputTarget, StreamOutputTarget, CollectionOutputTarget, BufferingOutputTarget, RexxInstructionParse, ParseTrigger, RexxInstructionProcedure, RexxInstructionRaise, RequiresDirective, RexxInstruction, RexxBlockInstruction, RexxInstructionExpression, RexxInstructionSelect, RexxInstructionSelectCase, RexxInstructionSignal, RexxInstructionDynamicSignal, RexxInstructionSignalOn, RexxInstructionThen, RexxInstructionTrace, UseArgVariableRef, RexxInstructionUse, RexxInstructionUseLocal, RexxInstructionCaseWhen, Envelope, InternalStack, MapBucket, MapTable, PushThroughStack, PointerBucket, PointerTable, MemoryObject, SmartBuffer, LibraryPackage, RexxClause, LanguageParser, BufferProgramSource, FileProgramSource, ArrayProgramSource, RexxToken, WeakReference, AbstractCode, and InterpreterInstance.
Definition at line 204 of file ObjectClass.hpp.
Referenced by MemorySegment::markAllObjects(), MemoryObject::restoreImage(), MemoryObject::saveImage(), MemoryObject::unflattenObjectBuffer(), and MemoryObject::unflattenProxyObjects().
unflatten()
virtual RexxInternalObject* RexxVirtualBase::unflatten (Envelope *) inline virtual
Reimplemented in RexxString, HashCollection, and WeakReference.
Definition at line 206 of file ObjectClass.hpp.
Referenced by EnvelopeMarkHandler::mark(), and RexxString::unflatten().
The documentation for this class was generated from the following file:
ObjectClass.hpp