ooRexx: RexxClass Class Reference
RexxClass Class Reference
#include <ClassClass.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
RexxClass ()
RexxClass (RESTORETYPE restoreType)
RexxClass (const char *id, RexxBehaviour *classBehaviour, RexxBehaviour *instanceBehaviour)
void live (size_t) override
void liveGeneral (MarkReason reason) override
RexxObject * makeProxy (Envelope *) override
HashCode hash () override
HashCode getHashValue () override
RexxObject * equal (RexxObject *)
RexxObject * strictEqual (RexxObject *)
RexxObject * notEqual (RexxObject *)
RexxObject * setRexxDefined ()
void buildFinalClassBehaviour ()
void buildFinalClassBehaviour (RexxClass *superClass)
void mergeSuperClassScopes (RexxBehaviour *target_instance_behaviour)
RexxObject * defineMethod (RexxString *, RexxObject *)
RexxObject * defineMethodsRexx (RexxObject *methods)
RexxObject * deleteMethod (RexxString *)
RexxObject * defineClassMethod (RexxString *method_name, MethodClass *newMethod)
void removeClassMethod (RexxString *method_name)
void removeSetupMethods ()
RexxObject * defineMethods (StringTable *)
void inheritInstanceMethods (RexxClass *)
RexxObject * inheritInstanceMethodsRexx (RexxClass *)
MethodDictionary * getInstanceBehaviourDictionary ()
MethodDictionary * getBehaviourDictionary ()
void updateSubClasses ()
void updateInstanceSubClasses ()
void createClassBehaviour (RexxBehaviour *)
void createInstanceBehaviour (RexxBehaviour *)
void mergeBehaviour (RexxBehaviour *target_instance_behaviour)
MethodDictionary * createMethodDictionary (RexxObject *sourceCollection, RexxClass *scope)
MethodDictionary * copyInstanceMethods ()
void mergeInstanceBehaviour (RexxBehaviour *targetBehaviour)
void mergeClassMethodDictionary (RexxBehaviour *targetBehaviour)
RexxObject * queryMixinClass ()
RexxObject * isMetaClassRexx ()
RexxObject * isAbstractRexx ()
RexxString * getId ()
RexxClass * getBaseClass ()
RexxClass * getMetaClass ()
RexxClass * getSuperClass ()
ArrayClass * getSuperClasses ()
ArrayClass * getSubClasses ()
RexxObject * copyRexx ()
void setInstanceBehaviour (RexxBehaviour *)
RexxString * defaultName () override
MethodClass * method (RexxString *)
SupplierClass * methods (RexxClass *)
RexxObject * inherit (RexxClass *, RexxClass *)
RexxObject * uninherit (RexxClass *)
RexxObject * enhanced (RexxObject **, size_t)
RexxClass * mixinClass (PackageClass *, RexxString *, RexxClass *, RexxObject *)
RexxClass * subclass (PackageClass *, RexxString *, RexxClass *, RexxObject *)
RexxClass * mixinClassRexx (RexxString *, RexxClass *, RexxObject *)
RexxClass * subclassRexx (RexxString *, RexxClass *, RexxObject *)
RexxClass * newRexx (RexxObject **args, size_t argCount)
void setMetaClass (RexxClass *)
bool isCompatibleWith (RexxClass *other)
RexxObject * isSubclassOf (RexxClass *other)
RexxString * defaultNameRexx ()
RexxObject * getAnnotationRexx (RexxObject *name)
void setPackage (PackageClass *s)
PackageClass * getPackage ()
void completeNewObject (RexxObject *obj, RexxObject **initArgs=OREF_NULL, size_t argCount=0)
StringTable * getAnnotations ()
RexxString * getAnnotation (RexxString *name)
void setAnnotations (StringTable *annotations)
bool isRexxDefined ()
bool isMixinClass ()
bool isMetaClass ()
bool isAbstract ()
bool hasUninitDefined ()
void setHasUninitDefined ()
void clearHasUninitDefined ()
void setInitialFlagState ()
bool parentHasUninitDefined ()
void setParentHasUninitDefined ()
bool isPrimitiveClass ()
void setMixinClass ()
void setNonPrimitive ()
RexxBehaviour * getInstanceBehaviour ()
void setMetaClass ()
void setAbstract ()
void clearAbstract ()
void addSubClass (RexxClass *)
void removeSubclass (RexxClass *c)
void checkUninit ()
void checkAbstract ()
void makeAbstract ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
void flatten (Envelope *) override
RexxInternalObject * copy () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void processNewArgs (RexxObject **, size_t, RexxObject **&, size_t &, size_t, RexxObject *&, RexxObject **)
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Types
enum ClassFlag {
REXX_DEFINED , MIXIN , HAS_UNINIT , META_CLASS ,
PRIMITIVE_CLASS , PARENT_HAS_UNINIT , ABSTRACT
}
Protected Attributes
RexxString * id
MethodDictionary * classMethodDictionary
MethodDictionary * instanceMethodDictionary
RexxBehaviour * instanceBehaviour
RexxClass * baseClass
RexxClass * metaClass
RexxClass * superClass
ArrayClass * superClasses
FlagSet< ClassFlag, 32 > classFlags
ListClass * subClasses
PackageClass * package
StringTable * annotations
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 60 of file ClassClass.hpp.
Member Enumeration Documentation
ClassFlag
enum RexxClass::ClassFlag protected
Enumerator
REXX_DEFINED
MIXIN
HAS_UNINIT
META_CLASS
PRIMITIVE_CLASS
PARENT_HAS_UNINIT
ABSTRACT
Definition at line 180 of file ClassClass.hpp.
Constructor & Destructor Documentation
RexxClass() [1/3]
RexxClass::RexxClass () inline
Definition at line 66 of file ClassClass.hpp.
Referenced by createInstance().
RexxClass() [2/3]
RexxClass::RexxClass (RESTORETYPE restoreType) inline
Definition at line 67 of file ClassClass.hpp.
RexxClass() [3/3]
RexxClass::RexxClass (const char * className, RexxBehaviour * classBehaviour, RexxBehaviour * _instanceBehaviour)
Initialize a new class instance.
Parameters
className The id of class
classBehaviour The class behaviour pointer.
instanceBehaviour The class instance behaviour pointer.
Definition at line 92 of file ClassClass.cpp.
References RexxInternalObject::behaviour, instanceBehaviour, RexxInternalObject::makeProxiedObject(), new_string(), RexxInternalObject::setBehaviour(), and RexxBehaviour::setOwningClass().
Member Function Documentation
addSubClass()
void RexxClass::addSubClass (RexxClass * subClass)
Add a subclass to the list of subclasses.
Parameters
subClass The new subclass.
Definition at line 482 of file ClassClass.cpp.
References ListClass::addFirst(), and subClasses.
Referenced by buildFinalClassBehaviour(), inherit(), and subclass().
buildFinalClassBehaviour() [1/2]
void RexxClass::buildFinalClassBehaviour ()
Initialize a base Rexx class.
Definition at line 654 of file ClassClass.cpp.
References ArrayClass::addLast(), RexxBehaviour::addScope(), baseClass, RexxInternalObject::behaviour, checkUninit(), classMethodDictionary, RexxBehaviour::clearMethodDictionary(), getBehaviourDictionary(), getInstanceBehaviourDictionary(), instanceBehaviour, instanceMethodDictionary, RexxBehaviour::merge(), RexxBehaviour::mergeMethodDictionary(), metaClass, new_array(), new_list(), setMetaClass(), RexxBehaviour::setOwningClass(), RexxInternalObject::setPrimitive(), subClasses, superClasses, TheClassBehaviour, TheClassClass, TheIntegerClass, TheNumberStringClass, TheObjectBehaviour, and TheObjectClass.
buildFinalClassBehaviour() [2/2]
void RexxClass::buildFinalClassBehaviour (RexxClass * superClass)
Initialize a base Rexx class that inherits from a primitive class other than Object.
Parameters
superClass The immediate superclass of the created class.
Definition at line 758 of file ClassClass.cpp.
References RexxBehaviour::addScope(), addSubClass(), baseClass, RexxInternalObject::behaviour, classFlags, classMethodDictionary, getBehaviourDictionary(), getInstanceBehaviourDictionary(), instanceBehaviour, instanceMethodDictionary, RexxBehaviour::merge(), mergeBehaviour(), metaClass, new_array(), new_list(), PRIMITIVE_CLASS, setField, RexxBehaviour::setOwningClass(), subClasses, superClass, superClasses, TheClassBehaviour, TheClassClass, and TheObjectClass.
checkAbstract()
void RexxClass::checkAbstract ()
Definition at line 1741 of file ClassClass.cpp.
References Error_Execution_abstract_class, isAbstract(), and reportException().
Referenced by completeNewObject().
checkUninit()
void RexxClass::checkUninit ()
Check if a class definition has an UNINIT method defined.
Definition at line 1210 of file ClassClass.cpp.
References RexxObject::hasUninitMethod(), instanceBehaviour, RexxBehaviour::methodLookup(), OREF_NULL, RexxInternalObject::requiresUninit(), and setHasUninitDefined().
Referenced by buildFinalClassBehaviour(), defineMethods(), defineMethodsRexx(), inheritInstanceMethods(), subclass(), updateInstanceSubClasses(), and updateSubClasses().
clearAbstract()
void RexxClass::clearAbstract () inline
Definition at line 165 of file ClassClass.hpp.
References ABSTRACT, and classFlags.
clearHasUninitDefined()
void RexxClass::clearHasUninitDefined () inline
Definition at line 154 of file ClassClass.hpp.
References classFlags, and HAS_UNINIT.
completeNewObject()
void RexxClass::completeNewObject (RexxObject * obj, RexxObject ** initArgs = OREF_NULL, size_t argCount = 0)
Perform common initialization steps on an object created by a new method from Rexx. This handles subclass behaviour issues, uninit processing, etc.
Parameters
obj The newly created object. NOTE: this assumes the caller has protected this object from garbage collection.
initArgs A pointer to arguments intended for the INIT method.
argCount The count of arguments.
Definition at line 1882 of file ClassClass.cpp.
References checkAbstract(), getInstanceBehaviour(), hasUninitDefined(), RexxInternalObject::requiresUninit(), RexxObject::sendMessage(), and RexxInternalObject::setBehaviour().
Referenced by ArrayClass::createMultidimensional(), MethodClass::newFileRexx(), RoutineClass::newFileRexx(), ArrayClass::newRexx(), BagClass::newRexx(), DirectoryClass::newRexx(), IdentityTable::newRexx(), ListClass::newRexx(), MessageClass::newRexx(), MethodClass::newRexx(), MutableBuffer::newRexx(), RelationClass::newRexx(), RoutineClass::newRexx(), SetClass::newRexx(), StemClass::newRexx(), RexxString::newRexx(), StringTable::newRexx(), SupplierClass::newRexx(), TableClass::newRexx(), EventSemaphoreClass::newRexx(), MutexSemaphoreClass::newRexx(), WeakReference::newRexx(), RexxObject::newRexx(), PackageClass::newRexx(), QueueClass::newRexx(), and ArrayClass::ofRexx().
copyInstanceMethods()
MethodDictionary * RexxClass::copyInstanceMethods ()
Copy the instance method dictionary for a class
Returns
The array of all scopes
Definition at line 1956 of file ClassClass.cpp.
References MethodDictionary::copy(), and instanceMethodDictionary.
copyRexx()
RexxObject * RexxClass::copyRexx ()
An override for the copy method to keep Class objects from being copied.
Returns
Never returns.
Definition at line 166 of file ClassClass.cpp.
References Error_Unsupported_copy_method, reportException(), and TheNilObject.
Referenced by MemoryObject::createImage().
createClassBehaviour()
void RexxClass::createClassBehaviour (RexxBehaviour * target_class_behaviour)
Create the class behaviour (the behavior for the class object itself). This merges all of the information from our superclasses with the information defined at this class scope.
Parameters
target_class_behaviour The behaviour object we're going to build into.
Definition at line 1098 of file ClassClass.cpp.
References RexxBehaviour::addScope(), classMethodDictionary, createClassBehaviour(), ArrayClass::get(), RexxBehaviour::hasScope(), ArrayClass::items(), mergeInstanceBehaviour(), RexxBehaviour::mergeMethodDictionary(), metaClass, superClasses, and TheObjectClass.
Referenced by createClassBehaviour(), subclass(), and updateSubClasses().
createInstance()
void RexxClass::createInstance () static
Create the initial class object
Definition at line 1854 of file ClassClass.cpp.
References new_object(), new_string(), RexxClass(), TheClassBehaviour, TheClassClass, and TheClassClassBehaviour.
Referenced by MemoryObject::createImage().
createInstanceBehaviour()
void RexxClass::createInstanceBehaviour (RexxBehaviour * target_instance_behaviour)
Create the instance behaviour for a class. The instance behaviour in this context is the behaviour that the class bestows upon its instances when instantiated.
Parameters
target_instance_behaviour The behaviour we are merging information into.
Definition at line 1148 of file ClassClass.cpp.
References RexxBehaviour::addScope(), createInstanceBehaviour(), ArrayClass::get(), RexxBehaviour::hasScope(), instanceMethodDictionary, RexxBehaviour::mergeMethodDictionary(), ArrayClass::size(), and superClasses.
Referenced by createInstanceBehaviour(), defineMethods(), inheritInstanceMethods(), subclass(), updateInstanceSubClasses(), and updateSubClasses().
createMethodDictionary()
MethodDictionary * RexxClass::createMethodDictionary (RexxObject * sourceCollection, RexxClass * scope)
Process a collection of methods that will be added to a class as class methods, or will be added to an enhanced object. In either case, this is an arbitrary collection of objects that may need conversion into method objects and given a scope.
Parameters
sourceCollection the table containing the defined method objects. This can be any object that supports a Supplier method.
scope The scope these method objects belong to.
Returns
A method dictionary built from this collection of methods.
Definition at line 1242 of file ClassClass.cpp.
References SupplierClass::available(), SupplierClass::index(), SupplierClass::item(), MethodClass::newMethodObject(), SupplierClass::next(), RexxInternalObject::requestString(), RexxObject::sendMessage(), MethodClass::setScope(), TheNilObject, and TheTrueObject.
Referenced by defineMethodsRexx(), and subclass().
defaultName()
RexxString * RexxClass::defaultName () override virtual
Retrieve a class default name value...this is composed from the class id value.
Returns
The default object name.
Reimplemented from RexxObject.
Definition at line 614 of file ClassClass.cpp.
References RexxString::concatToCstring(), RexxString::concatWithCstring(), and id.
Referenced by defaultNameRexx().
defaultNameRexx()
RexxString * RexxClass::defaultNameRexx ()
Exported access to an object virtual function
Returns
The default name of the class object.
Definition at line 1705 of file ClassClass.cpp.
References defaultName().
Referenced by MemoryObject::createImage().
defineClassMethod()
RexxObject * RexxClass::defineClassMethod (RexxString * method_name, MethodClass * newMethod)
special method to allow a class method to be added to a primitive class during image build.
Parameters
method_name The name of the new method.
newMethod The method object to add
Returns
always returns OREF_NULL
Definition at line 883 of file ClassClass.cpp.
References MethodDictionary::addMethod(), ARG_ONE, ARG_TWO, RexxInternalObject::behaviour, classMethodDictionary, RexxBehaviour::defineMethod(), MethodClass::newScope(), OREF_NULL, requiredArgument(), stringArgument(), and RexxString::upper().
Referenced by MemoryObject::createImage().
defineMethod()
RexxObject * RexxClass::defineMethod (RexxString * method_name, RexxObject * methodSource)
Add a new instance method to this class object.
Parameters
method_name The name the method will be added under.
method_object The associated method object.
Returns
Always returns nothing.
Definition at line 819 of file ClassClass.cpp.
References RexxBehaviour::copy(), Error_Execution_rexx_defined_class, instanceBehaviour, instanceMethodDictionary, isRexxDefined(), MethodClass::newMethodObject(), OREF_NULL, MethodDictionary::replaceMethod(), reportException(), setField, setHasUninitDefined(), RexxString::strCompare(), stringArgument(), TheNilObject, updateInstanceSubClasses(), and RexxString::upper().
Referenced by MemoryObject::createImage().
defineMethods()
RexxObject * RexxClass::defineMethods (StringTable * newMethods)
Add a full table of methods to a class definition. This is only used during the initial image build.
Parameters
newMethods The new methods to add.
Definition at line 497 of file ClassClass.cpp.
References MethodDictionary::addMethods(), checkUninit(), createInstanceBehaviour(), instanceBehaviour, instanceMethodDictionary, OREF_NULL, and RexxBehaviour::setMethodDictionary().
Referenced by ClassDirective::install().
defineMethodsRexx()
RexxObject * RexxClass::defineMethodsRexx (RexxObject * newMethods)
Add a full table of methods to a class definition.
Parameters
newMethods The new methods to add.
Definition at line 518 of file ClassClass.cpp.
References checkUninit(), RexxBehaviour::copy(), createMethodDictionary(), Error_Execution_rexx_defined_class, instanceBehaviour, instanceMethodDictionary, isRexxDefined(), OREF_NULL, MethodDictionary::replaceMethods(), reportException(), requiredArgument(), setField, and updateInstanceSubClasses().
Referenced by MemoryObject::createImage().
deleteMethod()
RexxObject * RexxClass::deleteMethod (RexxString * method_name)
Delete an instance method from this class definition.
Parameters
method_name The target method name.
Returns
Returns nothing.
Definition at line 952 of file ClassClass.cpp.
References RexxBehaviour::copy(), Error_Execution_rexx_defined_class, instanceBehaviour, instanceMethodDictionary, isRexxDefined(), OREF_NULL, MethodDictionary::removeMethod(), reportException(), setField, stringArgument(), updateInstanceSubClasses(), and RexxString::upper().
Referenced by MemoryObject::createImage().
enhanced()
RexxObject * RexxClass::enhanced (RexxObject ** args, size_t argCount)
Create a new object of the receive class that has had additional instance methods added to the created instance. This creates a one-off object instance.
Parameters
args The array of arguments to the method.
argCount The count of method arguments.
Returns
The enhanced object instance.
Definition at line 1440 of file ClassClass.cpp.
References RexxInternalObject::behaviour, Error_Incorrect_method_minarg, IntegerOne, new_string(), OREF_NULL, reportException(), requiredArgument(), RexxBehaviour::setEnhanced(), RexxBehaviour::setOwningClass(), subclass(), and TheNilObject.
Referenced by MemoryObject::createImage().
equal()
RexxObject * RexxClass::equal (RexxObject * other)
Compare two classes
Parameters
other The other class to compare.
Returns
The True object if they are equal, the False object if not.
Definition at line 240 of file ClassClass.cpp.
References ARG_ONE, booleanObject(), requiredArgument(), TheIntegerClass, TheNumberStringClass, TheStringClass, and TheTrueObject.
Referenced by MemoryObject::createImage(), and strictEqual().
getAnnotation()
RexxString * RexxClass::getAnnotation (RexxString * name)
Get a specific named annotation.
Parameters
name The annotation name
Returns
The annotation value, or OREF_NULL if it doesn't exist.
Definition at line 357 of file ClassClass.cpp.
References annotations, StringHashCollection::entry(), and OREF_NULL.
Referenced by getAnnotationRexx().
getAnnotationRexx()
RexxObject * RexxClass::getAnnotationRexx (RexxObject * name)
The Rexx stub for the get annotation method
Parameters
name The name of the target annotation.
Returns
The annotation value, or .nil if it does not exist.
Definition at line 374 of file ClassClass.cpp.
References getAnnotation(), resultOrNil(), and stringArgument().
Referenced by MemoryObject::createImage().
getAnnotations()
StringTable * RexxClass::getAnnotations ()
Retrieve the read/write annotation table for a class object.
Returns
The class annotations. This might be an empty string table.
Definition at line 325 of file ClassClass.cpp.
References annotations, new_string_table(), OREF_NULL, and setField.
Referenced by MemoryObject::createImage().
getBaseClass()
RexxClass * RexxClass::getBaseClass ()
Return the base class for this class.
Returns
The baseclass (the lowest non-mixin class).
Definition at line 408 of file ClassClass.cpp.
References baseClass.
Referenced by MemoryObject::createImage(), and inherit().
getBehaviourDictionary()
MethodDictionary * RexxClass::getBehaviourDictionary ()
Get a copy of the method dictionary from the class behaviour.
Returns
A copy of the behaviour method dictionary.
Definition at line 645 of file ClassClass.cpp.
References RexxInternalObject::behaviour, and RexxBehaviour::copyMethodDictionary().
Referenced by buildFinalClassBehaviour().
getHashValue()
HashCode RexxClass::getHashValue () override virtual
Get the primitive hash value of this String object.
Returns
The calculated string hash for the string.
Reimplemented from RexxInternalObject.
Definition at line 209 of file ClassClass.cpp.
Referenced by hash().
getId()
RexxString * RexxClass::getId ()
Retrieve the String ID for a class object.
Returns
The string ID.
Definition at line 385 of file ClassClass.cpp.
References id.
Referenced by classArgument(), MemoryObject::createImage(), RexxObject::defaultName(), MethodClass::getScopeName(), and RexxObject::requestRexx().
getInstanceBehaviour()
RexxBehaviour* RexxClass::getInstanceBehaviour () inline
Definition at line 162 of file ClassClass.hpp.
References instanceBehaviour.
Referenced by completeNewObject().
getInstanceBehaviourDictionary()
MethodDictionary * RexxClass::getInstanceBehaviourDictionary ()
Get the method dictionary for the instance behaviour.
Returns
The instance behaviour dictionary for the class.
Definition at line 632 of file ClassClass.cpp.
References RexxBehaviour::copyMethodDictionary(), and instanceBehaviour.
Referenced by buildFinalClassBehaviour().
getMetaClass()
RexxClass * RexxClass::getMetaClass ()
Get the MetaClass for the class object.
Returns
The class metaclass.
Definition at line 419 of file ClassClass.cpp.
References metaClass.
Referenced by MemoryObject::createImage(), and subclass().
getPackage()
PackageClass * RexxClass::getPackage ()
Return the package containing the directive that defined a class.
Returns
The package containing the directive that defined this class, or .nil if this class was not created from a directive.
Definition at line 1732 of file ClassClass.cpp.
References package, and resultOrNil().
Referenced by MemoryObject::createImage().
getSubClasses()
ArrayClass * RexxClass::getSubClasses ()
Get a list of all current subclasses of this class.
Returns
An array of the subclasses.
Definition at line 470 of file ClassClass.cpp.
References subClasses, and ListClass::weakReferenceArray().
Referenced by MemoryObject::createImage(), removeClassMethod(), updateInstanceSubClasses(), and updateSubClasses().
getSuperClass()
RexxClass * RexxClass::getSuperClass ()
Return the immediate superclass of this class.
Returns
The first superclass of the class.
Definition at line 441 of file ClassClass.cpp.
References ArrayClass::getFirstItem(), superClasses, TheNilObject, and TheObjectClass.
Referenced by MemoryObject::createImage().
getSuperClasses()
ArrayClass * RexxClass::getSuperClasses ()
return an array of the class superclasses.
Returns
An array containing all of the superclasses.
Definition at line 458 of file ClassClass.cpp.
References ArrayClass::copy(), and superClasses.
Referenced by MemoryObject::createImage().
hash()
HashCode RexxClass::hash () override virtual
Hash a class object. Because behaviors don't always get set up properly with this, we'll always use the primitive one for class objects. We want to ensure that this is not overridden on us.
Returns
A "hashed hash" that can be used by the map collections.
Reimplemented from RexxObject.
Definition at line 195 of file ClassClass.cpp.
References getHashValue().
hasUninitDefined()
bool RexxClass::hasUninitDefined () inline
Definition at line 152 of file ClassClass.hpp.
References classFlags, and HAS_UNINIT.
Referenced by completeNewObject(), inherit(), mixinClass(), and subclass().
inherit()
RexxObject * RexxClass::inherit (RexxClass * mixin_class, RexxClass * position)
To add the mixin class (parameter one) to the superclass hierarchy of the receiver class (this), at the last position or the specified position (parameter two).
Parameters
mixin_class The class to inherit from.
position The position to insert the class into the hierarchy (optional)
Returns
returns nothing.
Definition at line 1287 of file ClassClass.cpp.
References ArrayClass::addLast(), addSubClass(), RexxInternalObject::behaviour, Error_Execution_baseclass, Error_Execution_mixinclass, Error_Execution_recursive_inherit, Error_Execution_rexx_defined_class, Error_Execution_uninherit, getBaseClass(), RexxBehaviour::hasScope(), hasUninitDefined(), ArrayClass::indexOf(), ArrayClass::insertAfter(), instanceBehaviour, RexxObject::isInstanceOf(), isMixinClass(), isRexxDefined(), OREF_NULL, parentHasUninitDefined(), reportException(), requiredArgument(), setParentHasUninitDefined(), superClasses, TheClassClass, and updateSubClasses().
Referenced by MemoryObject::createImage().
inheritInstanceMethods()
void RexxClass::inheritInstanceMethods (RexxClass * source)
Inherit the instance methods from another class definition. This is not a true inherit operation where the class is part of the hierarchy. This directly grabs the instance methods defined directly by the other class and merges them into the class method dictionary. This is a special method that is only done during the initial image build.
Parameters
newMethods The new methods to add.
Definition at line 558 of file ClassClass.cpp.
References MethodDictionary::addMethod(), checkUninit(), createInstanceBehaviour(), HashContents::TableIterator::index(), instanceBehaviour, instanceMethodDictionary, HashContents::TableIterator::isAvailable(), HashCollection::iterator(), method(), HashContents::TableIterator::next(), OREF_NULL, RexxBehaviour::setMethodDictionary(), MethodDictionary::setMethodScope(), and HashContents::TableIterator::value().
Referenced by inheritInstanceMethodsRexx().
inheritInstanceMethodsRexx()
RexxObject * RexxClass::inheritInstanceMethodsRexx (RexxClass * source)
Inherit the instance methods from another class definition. This is not a true inherit operation where the class is part of the hierarchy. This directly grabs the instance methods defined directly by the other class and merges them into the class method dictionary. This is a special method that is only done during the initial image build.
Parameters
newMethods The new methods to add.
Definition at line 599 of file ClassClass.cpp.
References inheritInstanceMethods(), and OREF_NULL.
Referenced by MemoryObject::createImage().
isAbstract()
bool RexxClass::isAbstract () inline
Definition at line 151 of file ClassClass.hpp.
References ABSTRACT, and classFlags.
Referenced by checkAbstract(), and isAbstractRexx().
isAbstractRexx()
RexxObject * RexxClass::isAbstractRexx ()
Test if this class is marked as abstract
Returns
True if this is abstract, false if not
Definition at line 314 of file ClassClass.cpp.
References booleanObject(), and isAbstract().
Referenced by MemoryObject::createImage().
isCompatibleWith()
bool RexxClass::isCompatibleWith (RexxClass * other)
Test if the target class is a "compatible" with the argument class. To be compatible, the target class must either A) be the same class, B) be a direct subclass of the argument class, or C) inherit the argument class as a mixin. This rule gets applied recursively down the hierarchy.
Parameters
other The comparison class.
Returns
True if the two classes are compatible, false otherwise.
Definition at line 1660 of file ClassClass.cpp.
References ArrayClass::get(), OREF_NULL, ArrayClass::size(), and superClasses.
Referenced by RexxObject::isInstanceOf(), and isSubclassOf().
isMetaClass()
bool RexxClass::isMetaClass () inline
Definition at line 150 of file ClassClass.hpp.
References classFlags, and META_CLASS.
Referenced by isMetaClassRexx(), makeAbstract(), and subclass().
isMetaClassRexx()
RexxObject * RexxClass::isMetaClassRexx ()
Test if a class can be used as a metaclass
Returns
True if this is a metaclass, False if not.
Definition at line 303 of file ClassClass.cpp.
References booleanObject(), and isMetaClass().
Referenced by MemoryObject::createImage().
isMixinClass()
bool RexxClass::isMixinClass () inline
Definition at line 149 of file ClassClass.hpp.
References classFlags, and MIXIN.
Referenced by inherit(), queryMixinClass(), and uninherit().
isPrimitiveClass()
bool RexxClass::isPrimitiveClass () inline
Definition at line 159 of file ClassClass.hpp.
References classFlags, and PRIMITIVE_CLASS.
Referenced by newRexx().
isRexxDefined()
bool RexxClass::isRexxDefined () inline
Definition at line 148 of file ClassClass.hpp.
References classFlags, and REXX_DEFINED.
Referenced by defineMethod(), defineMethodsRexx(), deleteMethod(), inherit(), and uninherit().
isSubclassOf()
RexxObject * RexxClass::isSubclassOf (RexxClass * other)
A stub to test compatibility of two classes.
Parameters
other The class for the superclass test.
Returns
True if the class is a subclass of the argument class (or IS the argument class).
Definition at line 1692 of file ClassClass.cpp.
References booleanObject(), classArgument(), isCompatibleWith(), and TheClassClass.
Referenced by MemoryObject::createImage().
live()
void RexxClass::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxObject.
Definition at line 110 of file ClassClass.cpp.
References annotations, baseClass, classMethodDictionary, instanceBehaviour, instanceMethodDictionary, memory_mark, metaClass, package, subClasses, superClass, and superClasses.
Referenced by RexxIntegerClass::live().
liveGeneral()
void RexxClass::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxObject.
Definition at line 134 of file ClassClass.cpp.
References annotations, baseClass, classMethodDictionary, instanceBehaviour, instanceMethodDictionary, memory_mark_general, metaClass, package, PREPARINGIMAGE, setRexxDefined(), subClasses, superClass, and superClasses.
Referenced by RexxIntegerClass::liveGeneral().
makeAbstract()
void RexxClass::makeAbstract ()
Mark a class as abstract, if this is allowed for this type of class.
Definition at line 1754 of file ClassClass.cpp.
References Error_Execution_abstract_metaclass, isMetaClass(), reportException(), and setAbstract().
Referenced by ClassDirective::install().
makeProxy()
RexxObject * RexxClass::makeProxy (Envelope * envelope) override virtual
Make a proxy object from a class.
Parameters
envelope The envelope we're flattening into.
Returns
A string proxy name for this object.
Reimplemented from RexxInternalObject.
Definition at line 181 of file ClassClass.cpp.
References RexxString::getStringData(), id, and new_proxy().
mergeBehaviour()
void RexxClass::mergeBehaviour (RexxBehaviour * target_instance_behaviour)
Merge the behaviours from the superclasses into a target primitive class.
Parameters
target_instance_behaviour The target behavior to update.
Definition at line 1182 of file ClassClass.cpp.
References RexxBehaviour::addScope(), ArrayClass::get(), RexxBehaviour::hasScope(), instanceBehaviour, RexxBehaviour::merge(), mergeBehaviour(), ArrayClass::size(), and superClasses.
Referenced by buildFinalClassBehaviour(), and mergeBehaviour().
mergeClassMethodDictionary()
void RexxClass::mergeClassMethodDictionary (RexxBehaviour * targetBehaviour)
Merge this classes method dictionary into a behaviour.
Parameters
targetBehaviour The target behaviour.
Definition at line 1981 of file ClassClass.cpp.
References classMethodDictionary, and RexxBehaviour::mergeMethodDictionary().
mergeInstanceBehaviour()
void RexxClass::mergeInstanceBehaviour (RexxBehaviour * targetBehaviour)
Merge the instance behaviour for this class into another behaviour.
Parameters
targetBehaviour The target behaviour.
Definition at line 1969 of file ClassClass.cpp.
References instanceBehaviour, and RexxBehaviour::merge().
Referenced by createClassBehaviour().
mergeSuperClassScopes()
void RexxClass::mergeSuperClassScopes (RexxBehaviour * target_instance_behaviour)
method()
MethodClass * RexxClass::method (RexxString * method_name)
Returns the method object associated with a given name.
Parameters
method_name The target method name.
Returns
The method object, or .nil if the method does not exist.
Definition at line 984 of file ClassClass.cpp.
References Error_No_method_name, MethodDictionary::getMethod(), instanceMethodDictionary, OREF_NULL, reportException(), stringArgument(), and RexxString::upper().
Referenced by MemoryObject::createImage(), and inheritInstanceMethods().
methods()
SupplierClass * RexxClass::methods (RexxClass * class_object)
If no qualification parameter entered return all the methods that an instance of this class will inherit.
If TheNilObject is the qualification parameter return just the methods introduced at this class scope
For any other qualification parameter return just the methods introduced at that class scope
Parameters
class_object The class object qualifier.
Returns
A supplier for iterating the requested methods.
Definition at line 1018 of file ClassClass.cpp.
References RexxBehaviour::getMethods(), instanceBehaviour, and TheNilObject.
Referenced by MemoryObject::createImage().
mixinClass()
RexxClass * RexxClass::mixinClass (PackageClass * package, RexxString * mixin_id, RexxClass * meta_class, RexxObject * enhancing_class_methods)
Create a mixin class that can be used for INHERIT.
Parameters
package The source this is created from (can be null if created using methods.
mixin_id The id of the class object.
meta_class The metaclass this is created from
enhancing_class_methods Additional class methods to be added to this class. This can be any collection supports a supplier method.
Returns
A created class object.
Definition at line 1514 of file ClassClass.cpp.
References baseClass, hasUninitDefined(), package, parentHasUninitDefined(), setMixinClass(), setParentHasUninitDefined(), and subclass().
Referenced by ClassDirective::install(), and mixinClassRexx().
mixinClassRexx()
RexxClass * RexxClass::mixinClassRexx (RexxString * class_id, RexxClass * meta_class, RexxObject * enhancing_class_methods)
Create a mixinclass of a class directly from Rexx code.
Parameters
class_id The id of the created class.
meta_class The meta class to create this from.
enhancing_class_methods Additional class methods.
Returns
A created class object.
Definition at line 1493 of file ClassClass.cpp.
References mixinClass(), and OREF_NULL.
Referenced by MemoryObject::createImage().
newRexx()
RexxClass * RexxClass::newRexx (RexxObject ** args, size_t argCount)
Create a new class for a rexx class A copy of this class object is made This class' behaviour, class_mdict, metaclass, and class_info are used in the new class. All the rest of the object state data is updated to reflect a new class object
Parameters
args The args to the new method.
argCount The argument count.
Returns
A new class object.
Definition at line 1776 of file ClassClass.cpp.
References RexxInternalObject::clone(), Error_Incorrect_method_minarg, IntegerOne, isPrimitiveClass(), new_array(), new_list(), OREF_NULL, reportException(), stringArgument(), TheClassClass, and TheObjectClass.
Referenced by MemoryObject::createImage().
notEqual()
RexxObject * RexxClass::notEqual (RexxObject * other)
Inequality comparison between two class objects.
Parameters
other The other class for the comparison.
Returns
The True object if they are not equal, the False object otherwise.
Definition at line 268 of file ClassClass.cpp.
References ARG_ONE, booleanObject(), requiredArgument(), TheFalseObject, TheIntegerClass, TheNumberStringClass, and TheStringClass.
Referenced by MemoryObject::createImage().
operator delete()
void RexxClass::operator delete (void *) inline
Definition at line 64 of file ClassClass.hpp.
operator new()
void * RexxClass::operator new (size_t size)
Allocate new memory for a class object.
Parameters
size the size of the class object.
Returns
Storage for creating a new class object.
Definition at line 77 of file ClassClass.cpp.
References new_object(), and T_Class.
parentHasUninitDefined()
bool RexxClass::parentHasUninitDefined () inline
Definition at line 157 of file ClassClass.hpp.
References classFlags, and PARENT_HAS_UNINIT.
Referenced by inherit(), mixinClass(), and subclass().
processNewArgs()
void RexxClass::processNewArgs (RexxObject ** arg_array, size_t argCount, RexxObject **& init_args, size_t & remainderSize, size_t required, RexxObject *& argument1, RexxObject ** argument2) static
Common routine for processing class new method arguments.
Parameters
arg_array The original array of arguments.
argCount The count of arguments passed to the new method.
init_args The arguments left for an INIT method after processing the new argument.
remainderSize The count of arguments remaining after stripping off the new arguments.
required The count of required arguments.
argument1 Pointer to the first argument.
argument2 Pointer to the second argument.
Definition at line 1916 of file ClassClass.cpp.
References OREF_NULL.
Referenced by StemClass::newRexx(), RexxString::newRexx(), WeakReference::newRexx(), PackageClass::newRexx(), and BaseExecutable::processNewExecutableArgs().
queryMixinClass()
RexxObject * RexxClass::queryMixinClass ()
Test if a class is defined as a MIXIN class.
Returns
True if this is a mixin, False if not.
Definition at line 292 of file ClassClass.cpp.
References booleanObject(), and isMixinClass().
Referenced by MemoryObject::createImage().
removeClassMethod()
void RexxClass::removeClassMethod (RexxString * method_name)
Remove a class method from a class and all of its class methods.
Parameters
method_name The target method name.
Definition at line 904 of file ClassClass.cpp.
References RexxInternalObject::behaviour, RexxBehaviour::deleteMethod(), ArrayClass::get(), getSubClasses(), instanceBehaviour, and ArrayClass::items().
removeSetupMethods()
void RexxClass::removeSetupMethods ()
Remove the special class methods that are defined just for image building.
Definition at line 923 of file ClassClass.cpp.
References RexxInternalObject::behaviour, RexxBehaviour::deleteMethod(), instanceBehaviour, instanceMethodDictionary, new_string(), MethodDictionary::removeMethod(), and TheObjectClass.
removeSubclass()
void RexxClass::removeSubclass (RexxClass * c)
Remove a subclass from the uninherit list after an uninherit operation.
Parameters
c The class to remove.
Definition at line 1424 of file ClassClass.cpp.
References ListClass::removeItem(), and subClasses.
Referenced by uninherit().
setAbstract()
void RexxClass::setAbstract () inline
Definition at line 164 of file ClassClass.hpp.
References ABSTRACT, and classFlags.
Referenced by makeAbstract().
setAnnotations()
void RexxClass::setAnnotations (StringTable * a)
Set the annotations on an installed class object.
Parameters
a The annotations table (used by the ClassDirective object)
Definition at line 343 of file ClassClass.cpp.
References annotations, and setField.
Referenced by ClassDirective::install().
setHasUninitDefined()
void RexxClass::setHasUninitDefined () inline
Definition at line 153 of file ClassClass.hpp.
References classFlags, and HAS_UNINIT.
Referenced by checkUninit(), defineMethod(), and subclass().
setInitialFlagState()
void RexxClass::setInitialFlagState () inline
Definition at line 156 of file ClassClass.hpp.
References classFlags, HAS_UNINIT, and RexxObject::uninit().
setInstanceBehaviour()
void RexxClass::setInstanceBehaviour (RexxBehaviour * b)
Set the instance behaviour of this class object.
Parameters
b the new instance behaviour.
Definition at line 430 of file ClassClass.cpp.
References instanceBehaviour, and setField.
Referenced by RexxBehaviour::restoreClass().
setMetaClass() [1/2]
void RexxClass::setMetaClass () inline
Definition at line 163 of file ClassClass.hpp.
References classFlags, and META_CLASS.
Referenced by buildFinalClassBehaviour().
setMetaClass() [2/2]
void RexxClass::setMetaClass (RexxClass *)
Referenced by subclass().
setMixinClass()
void RexxClass::setMixinClass () inline
Definition at line 160 of file ClassClass.hpp.
References classFlags, and MIXIN.
Referenced by mixinClass().
setNonPrimitive()
void RexxClass::setNonPrimitive () inline
Definition at line 161 of file ClassClass.hpp.
References classFlags, and PRIMITIVE_CLASS.
setPackage()
void RexxClass::setPackage (PackageClass * s)
Set the source object what a class was created in. This will be the source that contains the ::class directive that defined the class.
Parameters
s The package file containing the ::class directive that created this class.
Definition at line 1719 of file ClassClass.cpp.
References package, and setField.
Referenced by subclass().
setParentHasUninitDefined()
void RexxClass::setParentHasUninitDefined () inline
Definition at line 158 of file ClassClass.hpp.
References classFlags, and PARENT_HAS_UNINIT.
Referenced by inherit(), mixinClass(), and subclass().
setRexxDefined()
RexxObject * RexxClass::setRexxDefined ()
Set a class as a Rexx defined, non-alterable class.
Returns
Dummy OREF_NULL.
Definition at line 396 of file ClassClass.cpp.
References classFlags, OREF_NULL, and REXX_DEFINED.
Referenced by liveGeneral().
strictEqual()
RexxObject * RexxClass::strictEqual (RexxObject * other)
Compare two classes for equality.
Parameters
other The other class to compare.
Returns
The True object if they are equal, the False object otherwise.
Definition at line 226 of file ClassClass.cpp.
References equal().
Referenced by MemoryObject::createImage().
subclass()
RexxClass * RexxClass::subclass (PackageClass * package, RexxString * class_id, RexxClass * meta_class, RexxObject * enhancing_methods)
Create a subclass of a class.
Parameters
source The source containing the directive this is created from. If created dynamically from a method, this will be null.
class_id The id of the created class.
meta_class The meta class to create this from.
enhancing_class_methods Additional class methods.
Returns
A created class object.
Definition at line 1562 of file ClassClass.cpp.
References addSubClass(), RexxInternalObject::behaviour, checkUninit(), classMethodDictionary, RexxBehaviour::clearMethodDictionary(), createClassBehaviour(), createInstanceBehaviour(), createMethodDictionary(), Error_Translation_bad_metaclass, getMetaClass(), hasUninitDefined(), instanceBehaviour, RexxObject::isInstanceOf(), isMetaClass(), MethodDictionary::merge(), metaClass, new_array(), OREF_NULL, package, parentHasUninitDefined(), reportException(), RexxObject::sendMessage(), setHasUninitDefined(), setMetaClass(), RexxBehaviour::setOwningClass(), setPackage(), setParentHasUninitDefined(), RexxBehaviour::subclass(), superClass, superClasses, and TheClassClass.
Referenced by enhanced(), ClassDirective::install(), mixinClass(), and subclassRexx().
subclassRexx()
RexxClass * RexxClass::subclassRexx (RexxString * class_id, RexxClass * meta_class, RexxObject * enhancing_class_methods)
Create a subclass of a class directly from Rexx code.
Parameters
class_id The id of the created class.
meta_class The meta class to create this from.
enhancing_class_methods Additional class methods.
Returns
A created class object.
Definition at line 1543 of file ClassClass.cpp.
References OREF_NULL, and subclass().
Referenced by MemoryObject::createImage().
uninherit()
RexxObject * RexxClass::uninherit (RexxClass * mixin_class)
Remove a mixin class from the class hierarchy.
Parameters
mixin_class The target mixin
Returns
Returns nothing.
Definition at line 1379 of file ClassClass.cpp.
References ArrayClass::deleteItem(), Error_Execution_mixinclass, Error_Execution_rexx_defined_class, Error_Execution_uninherit, ArrayClass::indexOf(), RexxObject::isInstanceOf(), isMixinClass(), isRexxDefined(), OREF_NULL, removeSubclass(), reportException(), requiredArgument(), superClasses, TheClassClass, and updateSubClasses().
Referenced by MemoryObject::createImage().
updateInstanceSubClasses()
void RexxClass::updateInstanceSubClasses ()
Update my instance behaviour and have my subclasses do the same.
Definition at line 1071 of file ClassClass.cpp.
References checkUninit(), RexxBehaviour::clearMethodDictionary(), createInstanceBehaviour(), getSubClasses(), and instanceBehaviour.
Referenced by defineMethod(), defineMethodsRexx(), and deleteMethod().
updateSubClasses()
void RexxClass::updateSubClasses ()
A change to this class' definitions has occurred. We need to update the behaviour, and propagate this change to all of our subclasses as well.
Definition at line 1036 of file ClassClass.cpp.
References RexxInternalObject::behaviour, checkUninit(), RexxBehaviour::clearMethodDictionary(), createClassBehaviour(), createInstanceBehaviour(), getSubClasses(), and instanceBehaviour.
Referenced by inherit(), and uninherit().
Member Data Documentation
annotations
StringTable* RexxClass::annotations protected
Definition at line 210 of file ClassClass.hpp.
Referenced by getAnnotation(), getAnnotations(), live(), liveGeneral(), and setAnnotations().
baseClass
RexxClass* RexxClass::baseClass protected
Definition at line 201 of file ClassClass.hpp.
Referenced by buildFinalClassBehaviour(), getBaseClass(), live(), liveGeneral(), and mixinClass().
classFlags
FlagSet<ClassFlag, 32> RexxClass::classFlags protected
Definition at line 206 of file ClassClass.hpp.
Referenced by buildFinalClassBehaviour(), clearAbstract(), clearHasUninitDefined(), hasUninitDefined(), isAbstract(), isMetaClass(), isMixinClass(), isPrimitiveClass(), isRexxDefined(), parentHasUninitDefined(), setAbstract(), setHasUninitDefined(), setInitialFlagState(), setMetaClass(), setMixinClass(), setNonPrimitive(), setParentHasUninitDefined(), and setRexxDefined().
classInstance
RexxClass * RexxClass::classInstance = OREF_NULL static
Definition at line 176 of file ClassClass.hpp.
classMethodDictionary
MethodDictionary* RexxClass::classMethodDictionary protected
Definition at line 194 of file ClassClass.hpp.
Referenced by buildFinalClassBehaviour(), createClassBehaviour(), defineClassMethod(), live(), liveGeneral(), mergeClassMethodDictionary(), and subclass().
id
RexxString* RexxClass::id protected
Definition at line 192 of file ClassClass.hpp.
Referenced by defaultName(), getId(), and makeProxy().
instanceBehaviour
RexxBehaviour* RexxClass::instanceBehaviour protected
Definition at line 199 of file ClassClass.hpp.
Referenced by buildFinalClassBehaviour(), checkUninit(), defineMethod(), defineMethods(), defineMethodsRexx(), deleteMethod(), getInstanceBehaviour(), getInstanceBehaviourDictionary(), inherit(), inheritInstanceMethods(), live(), liveGeneral(), mergeBehaviour(), mergeInstanceBehaviour(), methods(), removeClassMethod(), removeSetupMethods(), RexxClass(), setInstanceBehaviour(), subclass(), updateInstanceSubClasses(), and updateSubClasses().
instanceMethodDictionary
MethodDictionary* RexxClass::instanceMethodDictionary protected
Definition at line 196 of file ClassClass.hpp.
Referenced by buildFinalClassBehaviour(), copyInstanceMethods(), createInstanceBehaviour(), defineMethod(), defineMethods(), defineMethodsRexx(), deleteMethod(), inheritInstanceMethods(), live(), liveGeneral(), method(), and removeSetupMethods().
metaClass
RexxClass* RexxClass::metaClass protected
Definition at line 202 of file ClassClass.hpp.
Referenced by buildFinalClassBehaviour(), createClassBehaviour(), getMetaClass(), live(), liveGeneral(), and subclass().
package
PackageClass* RexxClass::package protected
Definition at line 209 of file ClassClass.hpp.
Referenced by getPackage(), live(), liveGeneral(), mixinClass(), setPackage(), and subclass().
subClasses
ListClass* RexxClass::subClasses protected
Definition at line 208 of file ClassClass.hpp.
Referenced by addSubClass(), buildFinalClassBehaviour(), getSubClasses(), live(), liveGeneral(), and removeSubclass().
superClass
RexxClass* RexxClass::superClass protected
Definition at line 203 of file ClassClass.hpp.
Referenced by buildFinalClassBehaviour(), live(), liveGeneral(), and subclass().
superClasses
ArrayClass* RexxClass::superClasses protected
Definition at line 205 of file ClassClass.hpp.
Referenced by buildFinalClassBehaviour(), createClassBehaviour(), createInstanceBehaviour(), getSuperClass(), getSuperClasses(), inherit(), isCompatibleWith(), live(), liveGeneral(), mergeBehaviour(), subclass(), and uninherit().
The documentation for this class was generated from the following files:
ClassClass.hpp
ClassClass.cpp