ooRexx: PackageSetting Class Reference
PackageSetting Class Reference
#include <PackageSetting.hpp>
Public Member Functions
PackageSetting ()
void setDefault ()
void setDigits (size_t d)
size_t getDigits () const
void setForm (bool f)
bool getForm () const
void setFuzz (size_t f)
size_t getFuzz () const
void setTraceSetting (const TraceSetting &s)
bool isDebug ()
const TraceSetting & getTraceSetting () const
RexxString * getTrace ()
bool isErrorSyntaxEnabled ()
void enableErrorSyntax ()
void disableErrorSyntax ()
bool isFailureSyntaxEnabled ()
void enableFailureSyntax ()
void disableFailureSyntax ()
bool isLostdigitsSyntaxEnabled ()
void enableLostdigitsSyntax ()
void disableLostdigitsSyntax ()
bool isNostringSyntaxEnabled ()
void enableNostringSyntax ()
void disableNostringSyntax ()
bool isNotreadySyntaxEnabled ()
void enableNotreadySyntax ()
void disableNotreadySyntax ()
bool isNovalueSyntaxEnabled ()
void enableNovalueSyntax ()
void disableNovalueSyntax ()
void enableProlog ()
void disableProlog ()
bool isPrologEnabled ()
Public Attributes
NumericSettings numericSettings
TraceSetting traceSettings
FlagSet< PackageFlags > packageOptions
Detailed Description
A class for processing different numeric settings
Definition at line 73 of file PackageSetting.hpp.
Constructor & Destructor Documentation
PackageSetting()
PackageSetting::PackageSetting () inline
Definition at line 77 of file PackageSetting.hpp.
Member Function Documentation
disableErrorSyntax()
void PackageSetting::disableErrorSyntax () inline
Definition at line 98 of file PackageSetting.hpp.
References ErrorSyntax, and packageOptions.
Referenced by PackageClass::disableErrorSyntax(), and RexxActivation::disableErrorSyntax().
disableFailureSyntax()
void PackageSetting::disableFailureSyntax () inline
Definition at line 101 of file PackageSetting.hpp.
References FailureSyntax, and packageOptions.
Referenced by PackageClass::disableFailureSyntax(), and RexxActivation::disableFailureSyntax().
disableLostdigitsSyntax()
void PackageSetting::disableLostdigitsSyntax () inline
Definition at line 104 of file PackageSetting.hpp.
References LostdigitsSyntax, and packageOptions.
Referenced by PackageClass::disableLostdigitsSyntax(), and RexxActivation::disableLostdigitsSyntax().
disableNostringSyntax()
void PackageSetting::disableNostringSyntax () inline
Definition at line 107 of file PackageSetting.hpp.
References NostringSyntax, and packageOptions.
Referenced by PackageClass::disableNostringSyntax(), and RexxActivation::disableNostringSyntax().
disableNotreadySyntax()
void PackageSetting::disableNotreadySyntax () inline
Definition at line 110 of file PackageSetting.hpp.
References NotreadySyntax, and packageOptions.
Referenced by PackageClass::disableNotreadySyntax(), and RexxActivation::disableNotreadySyntax().
disableNovalueSyntax()
void PackageSetting::disableNovalueSyntax () inline
Definition at line 113 of file PackageSetting.hpp.
References NovalueSyntax, and packageOptions.
Referenced by PackageClass::disableNovalueSyntax(), and RexxActivation::disableNovalueSyntax().
disableProlog()
void PackageSetting::disableProlog () inline
Definition at line 115 of file PackageSetting.hpp.
References NoProlog, and packageOptions.
Referenced by PackageClass::disableProlog().
enableErrorSyntax()
void PackageSetting::enableErrorSyntax () inline
Definition at line 97 of file PackageSetting.hpp.
References ErrorSyntax, and packageOptions.
Referenced by PackageClass::enableErrorSyntax().
enableFailureSyntax()
void PackageSetting::enableFailureSyntax () inline
Definition at line 100 of file PackageSetting.hpp.
References FailureSyntax, and packageOptions.
Referenced by PackageClass::enableFailureSyntax().
enableLostdigitsSyntax()
void PackageSetting::enableLostdigitsSyntax () inline
Definition at line 103 of file PackageSetting.hpp.
References LostdigitsSyntax, and packageOptions.
Referenced by PackageClass::enableLostdigitsSyntax().
enableNostringSyntax()
void PackageSetting::enableNostringSyntax () inline
Definition at line 106 of file PackageSetting.hpp.
References NostringSyntax, and packageOptions.
Referenced by PackageClass::enableNostringSyntax().
enableNotreadySyntax()
void PackageSetting::enableNotreadySyntax () inline
Definition at line 109 of file PackageSetting.hpp.
References NotreadySyntax, and packageOptions.
Referenced by PackageClass::enableNotreadySyntax().
enableNovalueSyntax()
void PackageSetting::enableNovalueSyntax () inline
Definition at line 112 of file PackageSetting.hpp.
References NovalueSyntax, and packageOptions.
Referenced by PackageClass::enableNovalueSyntax().
enableProlog()
void PackageSetting::enableProlog () inline
Definition at line 114 of file PackageSetting.hpp.
References NoProlog, and packageOptions.
Referenced by PackageClass::enableProlog().
getDigits()
size_t PackageSetting::getDigits () const inline
Definition at line 87 of file PackageSetting.hpp.
References NumericSettings::getDigits(), and numericSettings.
Referenced by RexxActivation::digits(), and PackageClass::getDigits().
getForm()
bool PackageSetting::getForm () const inline
Definition at line 89 of file PackageSetting.hpp.
References NumericSettings::getForm(), and numericSettings.
Referenced by RexxActivation::form(), and PackageClass::getForm().
getFuzz()
size_t PackageSetting::getFuzz () const inline
Definition at line 91 of file PackageSetting.hpp.
References NumericSettings::getFuzz(), and numericSettings.
Referenced by RexxActivation::fuzz(), and PackageClass::getFuzz().
getTrace()
RexxString* PackageSetting::getTrace () inline
Definition at line 95 of file PackageSetting.hpp.
References TraceSetting::toString(), and traceSettings.
Referenced by RexxActivation::traceSetting().
getTraceSetting()
const TraceSetting& PackageSetting::getTraceSetting () const inline
Definition at line 94 of file PackageSetting.hpp.
References traceSettings.
Referenced by PackageClass::getTraceSetting().
isDebug()
bool PackageSetting::isDebug () inline
Definition at line 93 of file PackageSetting.hpp.
References TraceSetting::isDebug(), and traceSettings.
isErrorSyntaxEnabled()
bool PackageSetting::isErrorSyntaxEnabled () inline
Definition at line 96 of file PackageSetting.hpp.
References ErrorSyntax, and packageOptions.
Referenced by RexxActivation::isErrorSyntaxEnabled().
isFailureSyntaxEnabled()
bool PackageSetting::isFailureSyntaxEnabled () inline
Definition at line 99 of file PackageSetting.hpp.
References FailureSyntax, and packageOptions.
Referenced by RexxActivation::isFailureSyntaxEnabled().
isLostdigitsSyntaxEnabled()
bool PackageSetting::isLostdigitsSyntaxEnabled () inline
Definition at line 102 of file PackageSetting.hpp.
References LostdigitsSyntax, and packageOptions.
Referenced by RexxActivation::isLostdigitsSyntaxEnabled().
isNostringSyntaxEnabled()
bool PackageSetting::isNostringSyntaxEnabled () inline
Definition at line 105 of file PackageSetting.hpp.
References NostringSyntax, and packageOptions.
Referenced by RexxActivation::isNostringSyntaxEnabled().
isNotreadySyntaxEnabled()
bool PackageSetting::isNotreadySyntaxEnabled () inline
Definition at line 108 of file PackageSetting.hpp.
References NotreadySyntax, and packageOptions.
Referenced by RexxActivation::isNotreadySyntaxEnabled().
isNovalueSyntaxEnabled()
bool PackageSetting::isNovalueSyntaxEnabled () inline
Definition at line 111 of file PackageSetting.hpp.
References NovalueSyntax, and packageOptions.
Referenced by RexxActivation::isNovalueSyntaxEnabled().
isPrologEnabled()
bool PackageSetting::isPrologEnabled () inline
Definition at line 116 of file PackageSetting.hpp.
References NoProlog, and packageOptions.
Referenced by PackageClass::isPrologEnabled().
setDefault()
void PackageSetting::setDefault () inline
Definition at line 80 of file PackageSetting.hpp.
References numericSettings, TraceSetting::setDefault(), NumericSettings::setDefault(), and traceSettings.
Referenced by LanguageParser::translate().
setDigits()
void PackageSetting::setDigits (size_t d) inline
Definition at line 86 of file PackageSetting.hpp.
References numericSettings, and NumericSettings::setDigits().
Referenced by PackageClass::setDigits(), and RexxActivation::setDigits().
setForm()
void PackageSetting::setForm (bool f) inline
Definition at line 88 of file PackageSetting.hpp.
References numericSettings, and NumericSettings::setForm().
Referenced by PackageClass::setForm(), and RexxActivation::setForm().
setFuzz()
void PackageSetting::setFuzz (size_t f) inline
Definition at line 90 of file PackageSetting.hpp.
References numericSettings, and NumericSettings::setFuzz().
Referenced by PackageClass::setFuzz(), and RexxActivation::setFuzz().
setTraceSetting()
void PackageSetting::setTraceSetting (const TraceSetting & s) inline
Definition at line 92 of file PackageSetting.hpp.
References traceSettings.
Referenced by PackageClass::setTraceSetting().
Member Data Documentation
numericSettings
NumericSettings PackageSetting::numericSettings
Definition at line 118 of file PackageSetting.hpp.
Referenced by getDigits(), getForm(), getFuzz(), RexxActivation::getNumericSettings(), setDefault(), setDigits(), setForm(), and setFuzz().
packageOptions
FlagSet<PackageFlags> PackageSetting::packageOptions
Definition at line 120 of file PackageSetting.hpp.
Referenced by disableErrorSyntax(), disableFailureSyntax(), disableLostdigitsSyntax(), disableNostringSyntax(), disableNotreadySyntax(), disableNovalueSyntax(), disableProlog(), enableErrorSyntax(), enableFailureSyntax(), enableLostdigitsSyntax(), enableNostringSyntax(), enableNotreadySyntax(), enableNovalueSyntax(), enableProlog(), isErrorSyntaxEnabled(), isFailureSyntaxEnabled(), isLostdigitsSyntaxEnabled(), isNostringSyntaxEnabled(), isNotreadySyntaxEnabled(), isNovalueSyntaxEnabled(), and isPrologEnabled().
traceSettings
TraceSetting PackageSetting::traceSettings
Definition at line 119 of file PackageSetting.hpp.
Referenced by RexxActivation::clearTraceSettings(), getTrace(), getTraceSetting(), RexxActivation::inDebug(), RexxActivation::inheritPackageSettings(), isDebug(), RexxActivation::pauseCommand(), RexxActivation::pauseLabel(), RexxActivation::pausingInstructions(), RexxActivation::resetDebug(), setDefault(), RexxActivation::setTrace(), setTraceSetting(), RexxActivation::traceLabel(), RexxActivation::tracingAll(), RexxActivation::tracingCommands(), RexxActivation::tracingErrors(), RexxActivation::tracingFailures(), RexxActivation::tracingLabels(), and RexxActivation::tracingResults().
The documentation for this class was generated from the following file:
PackageSetting.hpp