ooRexx: RexxBehaviour Class Reference
RexxBehaviour Class Reference
#include <RexxBehaviour.hpp>
Public Member Functions
RexxBehaviour (ClassTypeCode, PCPPM *)
RexxBehaviour ()
RexxBehaviour (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
void copyBehaviour ()
void copyBehaviour (RexxBehaviour *source)
void defineMethod (RexxString *, MethodClass *)
RexxObject * defineMethods (StringTable *)
MethodClass * defineMethod (const char *, PCPPM, size_t, const char *)
void addInstanceMethod (RexxString *, MethodClass *)
void removeInstanceMethod (RexxString *)
void hideMethod (const char *name)
void removeMethod (const char *name)
void replaceMethod (RexxString *methodName, MethodClass *method)
void inheritInstanceMethods (RexxBehaviour *source)
void setMethodDictionaryScope (RexxClass *scope)
MethodClass * getMethodObject (RexxString *messageName)
MethodClass * methodObject (RexxString *)
MethodClass * methodLookup (RexxString *)
bool hasMethod (RexxString *name)
MethodClass * getMethod (RexxString *)
void deleteMethod (RexxString *)
void restore (RexxBehaviour *)
RexxClass * restoreClass ()
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
void subclass (RexxBehaviour *)
SupplierClass * getMethods (RexxClass *scope)
void resolveNonPrimitiveBehaviour ()
void merge (RexxBehaviour *)
void mergeMethodDictionary (MethodDictionary *)
MethodDictionary * copyMethodDictionary ()
MethodDictionary * getMethodDictionary ()
bool hasInstanceMethods ()
void setMethodDictionary (MethodDictionary *m)
void clearMethodDictionary ()
RexxClass * getOwningClass ()
void setOwningClass (RexxClass *c)
ArrayClass * allScopes ()
void addScope (RexxClass *scope)
RexxClass * immediateSuperScope ()
bool hasScope (RexxClass *scope)
void addInstanceMethods (MethodDictionary *source)
void setClassType (ClassTypeCode n)
ClassTypeCode getClassType ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isNotResolved ()
bool isResolved ()
bool isEnhanced ()
bool isInternalClass ()
bool isTransientClass ()
void setResolved ()
void setNotResolved ()
void setEnhanced ()
void setNonPrimitive ()
void setInternalClass ()
void setTransientClass ()
RexxBehaviour * getSavedPrimitiveBehaviour ()
PCPPM getOperatorMethod (size_t index)
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static RexxBehaviour * restoreSavedPrimitiveBehaviour (RexxBehaviour *b)
static RexxBehaviour * getPrimitiveBehaviour (size_t index)
static PCPPM * getOperatorMethods (size_t index)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static const uintptr_t INTERNALCLASS = (((uintptr_t)1) << ((sizeof(uintptr_t) * 8) - 1))
static RexxBehaviour primitiveBehaviours []
Protected Types
enum BehaviourFlag {
NON_PRIMITIVE_BEHAVIOUR , ENHANCED_OBJECT , INTERNAL_CLASS , TRANSIENT_CLASS ,
BEHAVIOUR_NOT_RESOLVED
}
Protected Attributes
ClassTypeCode classType
FlagSet< BehaviourFlag, 32 > behaviourFlags
MethodDictionary * methodDictionary
PCPPM * operatorMethods
RexxClass * owningClass
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
The class that defines base object behaviour (i.e., what methods can be invoked)
Definition at line 53 of file RexxBehaviour.hpp.
Member Enumeration Documentation
BehaviourFlag
enum RexxBehaviour::BehaviourFlag protected
Enumerator
NON_PRIMITIVE_BEHAVIOUR
ENHANCED_OBJECT
INTERNAL_CLASS
TRANSIENT_CLASS
BEHAVIOUR_NOT_RESOLVED
Definition at line 160 of file RexxBehaviour.hpp.
Constructor & Destructor Documentation
RexxBehaviour() [1/3]
RexxBehaviour::RexxBehaviour (ClassTypeCode newTypenum, PCPPM * operator_methods)
Construct a statically defined primitive behaviour. Behaviours are created originally in a table of objects that are not allocated from object heap memory. There is one primitive behaviour for every class defined in PrimitiveClasses.xml. After that, all additional behaviours are created using copies of one of the primitive behaviours.
Parameters
newTypenum The primitive type number.
operator_methods The associated operator methods.
Definition at line 69 of file RexxBehaviour.cpp.
References RexxInternalObject::behaviour, behaviourFlags, getPrimitiveBehaviour(), RexxInternalObject::header, INTERNAL_CLASS, methodDictionary, operatorMethods, OREF_NULL, owningClass, setClassType(), ObjectHeader::setObjectSize(), T_Behaviour, T_First_Transient_Class, T_Last_Exported_Class, and TRANSIENT_CLASS.
RexxBehaviour() [2/3]
RexxBehaviour::RexxBehaviour () inline
Definition at line 59 of file RexxBehaviour.hpp.
RexxBehaviour() [3/3]
RexxBehaviour::RexxBehaviour (RESTORETYPE restoreType) inline
Definition at line 60 of file RexxBehaviour.hpp.
Member Function Documentation
addInstanceMethod()
void RexxBehaviour::addInstanceMethod (RexxString * methodName, MethodClass * method)
Add an instance method to an object's behaviour.
Parameters
methodName The name of the method to add.
method
Definition at line 400 of file RexxBehaviour.cpp.
References MethodDictionary::addInstanceMethod(), methodDictionary, OREF_NULL, and setField.
Referenced by RexxObject::defineInstanceMethod().
addInstanceMethods()
void RexxBehaviour::addInstanceMethods (MethodDictionary * source)
Add a collection of object-scope instance methods to a behaviour.
Parameters
source The source collection of instance methods.
Definition at line 749 of file RexxBehaviour.cpp.
References MethodDictionary::addInstanceMethods(), and methodDictionary.
addScope()
void RexxBehaviour::addScope (RexxClass * scope)
Add a new scope to the set used by the behaviour.
Parameters
scope The new scope class
Definition at line 629 of file RexxBehaviour.cpp.
References MethodDictionary::addScope(), methodDictionary, OREF_NULL, and setField.
Referenced by RexxClass::buildFinalClassBehaviour(), RexxClass::createClassBehaviour(), RexxClass::createInstanceBehaviour(), and RexxClass::mergeBehaviour().
allScopes()
ArrayClass * RexxBehaviour::allScopes ()
Get an array of all scopes defined in a behaviour.
Returns
An array of the behaviour scopes.
Definition at line 691 of file RexxBehaviour.cpp.
References MethodDictionary::allScopes(), and methodDictionary.
clearMethodDictionary()
void RexxBehaviour::clearMethodDictionary () inline
Definition at line 101 of file RexxBehaviour.hpp.
References OREF_NULL, and setMethodDictionary().
Referenced by RexxClass::buildFinalClassBehaviour(), RexxClass::subclass(), RexxClass::updateInstanceSubClasses(), and RexxClass::updateSubClasses().
copy()
RexxInternalObject * RexxBehaviour::copy () override virtual
Copy a behaviour object. This will make copies of all of the contained tables so that the relevant information can be changed independently of the original behaviour.
Returns
The new behaviour object.
Reimplemented from RexxInternalObject.
Definition at line 214 of file RexxBehaviour.cpp.
References RexxInternalObject::clone(), and RexxObject::operatorMethods.
Referenced by RexxObject::copy(), RexxObject::defineInstanceMethod(), RexxObject::defineInstanceMethods(), RexxClass::defineMethod(), RexxClass::defineMethodsRexx(), RexxObject::deleteInstanceMethod(), and RexxClass::deleteMethod().
copyBehaviour() [1/2]
void RexxBehaviour::copyBehaviour ()
Copy the internal tables of a behaviour object...used to finish up the copy() operation.
Definition at line 233 of file RexxBehaviour.cpp.
copyBehaviour() [2/2]
void RexxBehaviour::copyBehaviour (RexxBehaviour * source)
Copy the source behaviour object into this, inheriting all of the method dictionaries. Generally done during an image restore to restore the behaviours from the image.
Parameters
source The source behaviour.
Definition at line 248 of file RexxBehaviour.cpp.
References copyMethodDictionary(), methodDictionary, operatorMethods, owningClass, and setField.
copyMethodDictionary()
MethodDictionary * RexxBehaviour::copyMethodDictionary ()
Make a copy of the current method dictionary.
Returns
The copy of the method dictionary, or OREF_NULL if this behaviour does not have one.
Definition at line 721 of file RexxBehaviour.cpp.
References MethodDictionary::copy(), methodDictionary, and OREF_NULL.
Referenced by copyBehaviour(), RexxClass::getBehaviourDictionary(), and RexxClass::getInstanceBehaviourDictionary().
defineMethod() [1/2]
MethodClass * RexxBehaviour::defineMethod (const char * name, PCPPM entryPoint, size_t arguments, const char * entryPointName)
Define a native kernel method on this behaviour.
Parameters
name The method name.
entryPoint The method entry point
arguments The argument definition.
Returns
The created method object.
Definition at line 267 of file RexxBehaviour.cpp.
References MemoryObject::getUpperGlobalName(), memoryObject, replaceMethod(), and CPPCode::resolveExportedMethod().
defineMethod() [2/2]
void RexxBehaviour::defineMethod (RexxString * methodName, MethodClass * method)
Add a method to the method dictionary.l
Parameters
methodName The method name.
method The target method object.
Definition at line 370 of file RexxBehaviour.cpp.
References MethodDictionary::addMethod(), methodDictionary, OREF_NULL, and setField.
Referenced by RexxClass::defineClassMethod(), RexxObject::defineInstanceMethods(), MemoryObject::defineMethod(), defineMethods(), MemoryObject::definePrivateMethod(), MemoryObject::defineProtectedMethod(), and MemoryObject::defineUnguardedMethod().
defineMethods()
RexxObject * RexxBehaviour::defineMethods (StringTable * newMethods)
Add a full table of methods to a class definition. This is only used during the initial image build.
Parameters
newMethods The new methods to add.
Definition at line 761 of file RexxBehaviour.cpp.
References defineMethod(), HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), HashCollection::iterator(), HashContents::TableIterator::next(), OREF_NULL, TheNilObject, and HashContents::TableIterator::value().
deleteMethod()
void RexxBehaviour::deleteMethod (RexxString * messageName)
Delete a method from an object's behaviour.
Parameters
messageName The name of the method.
Returns
The deleted method, if any.
Definition at line 476 of file RexxBehaviour.cpp.
References methodDictionary, and HashCollection::remove().
Referenced by RexxClass::removeClassMethod(), and RexxClass::removeSetupMethods().
flatten()
void RexxBehaviour::flatten (Envelope * envelope) override virtual
Flatten the behaviour contents
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxVirtualBase.
Definition at line 153 of file RexxBehaviour.cpp.
References cleanUpFlatten, flattenRef, isNonPrimitive(), methodDictionary, owningClass, and setUpFlatten.
getClassType()
ClassTypeCode RexxBehaviour::getClassType () inline
Definition at line 111 of file RexxBehaviour.hpp.
References classType.
Referenced by RexxInternalObject::getObjectTypeNumber(), getSavedPrimitiveBehaviour(), resolveNonPrimitiveBehaviour(), MemoryObject::restoreImage(), subclass(), and MemoryObject::unflattenObjectBuffer().
getMethod()
MethodClass * RexxBehaviour::getMethod (RexxString * messageName)
Get a method object from the method dictionary. If the object is suppressed by putting .nil into the table, this is still returned.
Parameters
messageName The target message name.
Returns
Any value from the method dictionary.
Definition at line 462 of file RexxBehaviour.cpp.
References MethodDictionary::getMethod(), and methodDictionary.
getMethodDictionary()
MethodDictionary* RexxBehaviour::getMethodDictionary () inline
Definition at line 98 of file RexxBehaviour.hpp.
References methodDictionary.
Referenced by inheritInstanceMethods(), and restore().
getMethodObject()
MethodClass * RexxBehaviour::getMethodObject (RexxString * messageName)
Retrieve a method object associated with a given name.
Parameters
messageName The name of the desired method.
Returns
Any associated method object.
Definition at line 421 of file RexxBehaviour.cpp.
References ARG_ONE, methodLookup(), stringArgument(), and RexxString::upper().
getMethods()
SupplierClass * RexxBehaviour::getMethods (RexxClass * scope)
Extract from the method dictionary all methods defined with a given scope.
Parameters
scope The target scope. If null, then all methods are returned.
Returns
A supplier holding the names and methods with the target scope. This supplier can be empty.
Definition at line 617 of file RexxBehaviour.cpp.
References MethodDictionary::getMethods(), and methodDictionary.
Referenced by RexxObject::instanceMethods(), and RexxClass::methods().
getOperatorMethod()
PCPPM RexxBehaviour::getOperatorMethod (size_t index) inline
Definition at line 152 of file RexxBehaviour.hpp.
References operatorMethods.
Referenced by RexxObject::callOperatorMethod().
getOperatorMethods()
static PCPPM* RexxBehaviour::getOperatorMethods (size_t index) inline static
Definition at line 154 of file RexxBehaviour.hpp.
References getPrimitiveBehaviour(), and operatorMethods.
Referenced by resolveNonPrimitiveBehaviour().
getOwningClass()
RexxClass* RexxBehaviour::getOwningClass () inline
Definition at line 102 of file RexxBehaviour.hpp.
References owningClass.
Referenced by RexxObject::classObject(), RexxObject::defaultName(), inheritInstanceMethods(), RexxObject::requestRexx(), and restore().
getPrimitiveBehaviour()
static RexxBehaviour* RexxBehaviour::getPrimitiveBehaviour (size_t index) inline static
Definition at line 153 of file RexxBehaviour.hpp.
References primitiveBehaviours.
Referenced by getOperatorMethods(), MemoryObject::newObject(), restore(), RexxBehaviour(), MemoryObject::saveImage(), and RexxInternalObject::setObjectType().
getSavedPrimitiveBehaviour()
RexxBehaviour* RexxBehaviour::getSavedPrimitiveBehaviour () inline
Definition at line 126 of file RexxBehaviour.hpp.
References getClassType(), INTERNALCLASS, isInternalClass(), and T_Last_Exported_Class.
Referenced by Envelope::copyBuffer(), and ImageSaveMarkHandler::mark().
hasInstanceMethods()
bool RexxBehaviour::hasInstanceMethods ()
Test if the behaviour has additional instance methods defined.
Returns
true if the object has specific instance methods, defined, false otherwise.
Definition at line 737 of file RexxBehaviour.cpp.
References MethodDictionary::hasInstanceMethods(), methodDictionary, and OREF_NULL.
Referenced by RexxObject::copy().
hasMethod()
bool RexxBehaviour::hasMethod (RexxString * name) inline
Definition at line 82 of file RexxBehaviour.hpp.
References methodLookup(), and OREF_NULL.
Referenced by RexxObject::hasMethod().
hasScope()
bool RexxBehaviour::hasScope (RexxClass * scope)
Test if a scope is defined in a behaviour.
Parameters
scope The target scope.
Returns
True if this scope has already been added, false otherwise.
Definition at line 704 of file RexxBehaviour.cpp.
References MethodDictionary::hasScope(), methodDictionary, and OREF_NULL.
Referenced by RexxClass::createClassBehaviour(), RexxClass::createInstanceBehaviour(), RexxClass::inherit(), RexxClass::mergeBehaviour(), and RexxObject::validateScopeOverride().
hideMethod()
void RexxBehaviour::hideMethod (const char * name)
Block use of an inherited method by adding TheNilObject as an entry in the table.
Parameters
name The target name.
Definition at line 286 of file RexxBehaviour.cpp.
References MemoryObject::getUpperGlobalName(), MethodDictionary::hideMethod(), memoryObject, methodDictionary, OREF_NULL, and setField.
immediateSuperScope()
RexxClass * RexxBehaviour::immediateSuperScope ()
Get the immediate superscope defined for this behaviour.
Returns
The superscope that a method defined by this class would use to set the SUPER variable for lookups.
Definition at line 568 of file RexxBehaviour.cpp.
References methodDictionary, owningClass, and MethodDictionary::resolveSuperScope().
inheritInstanceMethods()
void RexxBehaviour::inheritInstanceMethods (RexxBehaviour * source)
Inherit a set of instance methods from another behaviour. This occurs early in building up the primitive classes, so we just update the defintions at this point. Completion of the processing will get methods of the correct scope created.
Parameters
source The source behaviour we're inheriting from.
Definition at line 350 of file RexxBehaviour.cpp.
References getMethodDictionary(), getOwningClass(), methodDictionary, OREF_NULL, MethodDictionary::replaceMethods(), and setField.
isEnhanced()
bool RexxBehaviour::isEnhanced () inline
Definition at line 116 of file RexxBehaviour.hpp.
References behaviourFlags, and ENHANCED_OBJECT.
Referenced by RexxObject::defaultName().
isInternalClass()
bool RexxBehaviour::isInternalClass () inline
Definition at line 117 of file RexxBehaviour.hpp.
References behaviourFlags, and INTERNAL_CLASS.
Referenced by getSavedPrimitiveBehaviour().
isNonPrimitive()
bool RexxBehaviour::isNonPrimitive () inline
Definition at line 113 of file RexxBehaviour.hpp.
References behaviourFlags, and NON_PRIMITIVE_BEHAVIOUR.
Referenced by Envelope::copyBuffer(), flatten(), RexxInternalObject::isSubClassOrEnhanced(), liveGeneral(), and ImageSaveMarkHandler::mark().
isNotResolved()
bool RexxBehaviour::isNotResolved () inline
Definition at line 114 of file RexxBehaviour.hpp.
References BEHAVIOUR_NOT_RESOLVED, and behaviourFlags.
Referenced by resolveNonPrimitiveBehaviour().
isPrimitive()
bool RexxBehaviour::isPrimitive () inline
Definition at line 112 of file RexxBehaviour.hpp.
References behaviourFlags, and NON_PRIMITIVE_BEHAVIOUR.
Referenced by RexxInternalObject::isBaseClass().
isResolved()
bool RexxBehaviour::isResolved () inline
Definition at line 115 of file RexxBehaviour.hpp.
References BEHAVIOUR_NOT_RESOLVED, and behaviourFlags.
isTransientClass()
bool RexxBehaviour::isTransientClass () inline
Definition at line 118 of file RexxBehaviour.hpp.
References behaviourFlags, and TRANSIENT_CLASS.
Referenced by Envelope::copyBuffer(), and ImageSaveMarkHandler::mark().
live()
void RexxBehaviour::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 102 of file RexxBehaviour.cpp.
References memory_mark, methodDictionary, and owningClass.
liveGeneral()
void RexxBehaviour::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 118 of file RexxBehaviour.cpp.
References isNonPrimitive(), memory_mark_general, methodDictionary, operatorMethods, owningClass, resolveNonPrimitiveBehaviour(), RESTORINGIMAGE, SAVINGIMAGE, and setNotResolved().
merge()
void RexxBehaviour::merge (RexxBehaviour * source_behav)
Merge another behaviour's method dictionary into this one. Our information will take precedence over the source behaviour.
Parameters
source_behav The source behaviour to merge in.
Definition at line 649 of file RexxBehaviour.cpp.
References mergeMethodDictionary(), and methodDictionary.
Referenced by RexxClass::buildFinalClassBehaviour(), RexxClass::mergeBehaviour(), and RexxClass::mergeInstanceBehaviour().
mergeMethodDictionary()
void RexxBehaviour::mergeMethodDictionary (MethodDictionary * sourceDictionary)
Merge a method dictionary without method dictionary. The target dictionary methods will take lookup priority over the source dictionary methods.
Parameters
sourceDictionary The source for the merge.
Definition at line 664 of file RexxBehaviour.cpp.
References MethodDictionary::copy(), MethodDictionary::merge(), methodDictionary, OREF_NULL, and setField.
Referenced by RexxClass::buildFinalClassBehaviour(), RexxClass::createClassBehaviour(), RexxClass::createInstanceBehaviour(), merge(), and RexxClass::mergeClassMethodDictionary().
methodLookup()
MethodClass * RexxBehaviour::methodLookup (RexxString * messageName)
Perform method lookup on a object. This version filters out suppressed methods.
Parameters
messageName The target message name.
Returns
The associated method object (if any)
Definition at line 438 of file RexxBehaviour.cpp.
References MethodDictionary::getMethod(), methodDictionary, OREF_NULL, and TheNilObject.
Referenced by RexxClass::checkUninit(), getMethodObject(), hasMethod(), RexxObject::instanceMethod(), RexxObject::messageSend(), RexxObject::methodLookup(), RexxObject::processUnknown(), and RexxObject::requestRexx().
methodObject()
MethodClass* RexxBehaviour::methodObject (RexxString *)
removeInstanceMethod()
void RexxBehaviour::removeInstanceMethod (RexxString * methodName)
Remove a method from the behaviour. this must be an instance method defined via SETMETHOD
Parameters
methodName The name of the method to remove.
Definition at line 388 of file RexxBehaviour.cpp.
References methodDictionary, and MethodDictionary::removeInstanceMethod().
Referenced by RexxObject::deleteInstanceMethod().
removeMethod()
void RexxBehaviour::removeMethod (const char * name)
Remove an object entirely from a method dictionary.
Parameters
name The target name.
Definition at line 305 of file RexxBehaviour.cpp.
References MemoryObject::getUpperGlobalName(), memoryObject, methodDictionary, OREF_NULL, and MethodDictionary::removeMethod().
replaceMethod()
void RexxBehaviour::replaceMethod (RexxString * methodName, MethodClass * method)
Add a method to the method dictionary during image setup. This occurs while we are constructing the instance behaviours of the different classes. If we've inherited a set of methods from another class and then define a replacement method, we want to completely replace the inherited method rather than leave it in the method dictionary.
Parameters
methodName The method name.
method The target method object.
Definition at line 329 of file RexxBehaviour.cpp.
References methodDictionary, OREF_NULL, MethodDictionary::replaceMethod(), and setField.
Referenced by defineMethod().
resolveNonPrimitiveBehaviour()
void RexxBehaviour::resolveNonPrimitiveBehaviour ()
Do fix ups for non-primitive behaviours, ensuring they get all of the appropriate information from their parent primitive behaviour types.
Definition at line 197 of file RexxBehaviour.cpp.
References getClassType(), getOperatorMethods(), isNotResolved(), operatorMethods, and setResolved().
Referenced by liveGeneral(), and MemoryObject::unflattenObjectBuffer().
restore()
void RexxBehaviour::restore (RexxBehaviour * saved)
Restore a primitive behaviour after an image restore.
Parameters
saved The behaviour that was stored in the saved image.
Definition at line 502 of file RexxBehaviour.cpp.
References getMethodDictionary(), getOwningClass(), getPrimitiveBehaviour(), methodDictionary, owningClass, Memory::roundObjectBoundary(), RexxInternalObject::setBehaviour(), RexxInternalObject::setObjectSize(), RexxInternalObject::setOldSpace(), and T_Behaviour.
Referenced by MemoryObject::restoreImage().
restoreClass()
RexxClass * RexxBehaviour::restoreClass ()
Update a behaviour in a class objects behaviour during image restore.
Returns
Owning class.
Definition at line 528 of file RexxBehaviour.cpp.
References owningClass, and RexxClass::setInstanceBehaviour().
restoreSavedPrimitiveBehaviour()
static RexxBehaviour* RexxBehaviour::restoreSavedPrimitiveBehaviour (RexxBehaviour * b) inline static
Definition at line 139 of file RexxBehaviour.hpp.
References INTERNALCLASS, primitiveBehaviours, and T_Last_Exported_Class.
Referenced by MemoryObject::restoreImage(), and MemoryObject::unflattenObjectBuffer().
setClassType()
void RexxBehaviour::setClassType (ClassTypeCode n) inline
Definition at line 110 of file RexxBehaviour.hpp.
References classType.
Referenced by RexxBehaviour(), and subclass().
setEnhanced()
void RexxBehaviour::setEnhanced () inline
Definition at line 121 of file RexxBehaviour.hpp.
References behaviourFlags, and ENHANCED_OBJECT.
Referenced by RexxClass::enhanced().
setInternalClass()
void RexxBehaviour::setInternalClass () inline
Definition at line 123 of file RexxBehaviour.hpp.
References behaviourFlags, and INTERNAL_CLASS.
setMethodDictionary()
void RexxBehaviour::setMethodDictionary (MethodDictionary * m)
Set a new method dictionary in the behaviour.
Parameters
m The new dictionary.
Definition at line 175 of file RexxBehaviour.cpp.
References methodDictionary, and setField.
Referenced by clearMethodDictionary(), RexxClass::defineMethods(), and RexxClass::inheritInstanceMethods().
setMethodDictionaryScope()
void RexxBehaviour::setMethodDictionaryScope (RexxClass * scope)
Set a new set of scoping information for all methods in a method dictionary. Used during image setup processing.
Parameters
scope The scope to set.
Definition at line 597 of file RexxBehaviour.cpp.
References methodDictionary, OREF_NULL, and MethodDictionary::setMethodScope().
setNonPrimitive()
void RexxBehaviour::setNonPrimitive () inline
Definition at line 122 of file RexxBehaviour.hpp.
References behaviourFlags, and NON_PRIMITIVE_BEHAVIOUR.
setNotResolved()
void RexxBehaviour::setNotResolved () inline
Definition at line 120 of file RexxBehaviour.hpp.
References BEHAVIOUR_NOT_RESOLVED, and behaviourFlags.
Referenced by liveGeneral().
setOwningClass()
void RexxBehaviour::setOwningClass (RexxClass * c)
Set a new owning class for this behaviour.
Parameters
c The new class.
Definition at line 186 of file RexxBehaviour.cpp.
References owningClass, and setField.
Referenced by RexxClass::buildFinalClassBehaviour(), RexxClass::enhanced(), RexxClass::RexxClass(), and RexxClass::subclass().
setResolved()
void RexxBehaviour::setResolved () inline
Definition at line 119 of file RexxBehaviour.hpp.
References BEHAVIOUR_NOT_RESOLVED, and behaviourFlags.
Referenced by resolveNonPrimitiveBehaviour().
setTransientClass()
void RexxBehaviour::setTransientClass () inline
Definition at line 124 of file RexxBehaviour.hpp.
References behaviourFlags, and TRANSIENT_CLASS.
subclass()
void RexxBehaviour::subclass (RexxBehaviour * subclass_behaviour)
Subclass a behaviour from another classes base type. Used to subclass the primitive classes.
Parameters
subclass_behaviour The source behaviour for the subclass.
Definition at line 491 of file RexxBehaviour.cpp.
References getClassType(), and setClassType().
Referenced by RexxClass::subclass().
superMethod()
MethodClass * RexxBehaviour::superMethod (RexxString * messageName, RexxClass * startScope)
Locate a super class method given the starting lookup information.
Parameters
messageName The target message name.
startScope The starting lookup scope.
Returns
The matching method (if any)
Definition at line 584 of file RexxBehaviour.cpp.
References MethodDictionary::findSuperMethod(), and methodDictionary.
Referenced by RexxObject::superMethod().
superScope()
RexxClass * RexxBehaviour::superScope (RexxClass * start_scope)
Locate the scope following a given scope.
Parameters
start_scope The starting scope.
Returns
The following scope, or .nil if not found.
Definition at line 549 of file RexxBehaviour.cpp.
References methodDictionary, owningClass, MethodDictionary::resolveSuperScope(), and TheNilObject.
Referenced by RexxObject::superScope().
Member Data Documentation
behaviourFlags
FlagSet<BehaviourFlag, 32> RexxBehaviour::behaviourFlags protected
Definition at line 171 of file RexxBehaviour.hpp.
Referenced by isEnhanced(), isInternalClass(), isNonPrimitive(), isNotResolved(), isPrimitive(), isResolved(), isTransientClass(), RexxBehaviour(), setEnhanced(), setInternalClass(), setNonPrimitive(), setNotResolved(), setResolved(), and setTransientClass().
classType
ClassTypeCode RexxBehaviour::classType protected
Definition at line 170 of file RexxBehaviour.hpp.
Referenced by getClassType(), and setClassType().
INTERNALCLASS
const uintptr_t RexxBehaviour::INTERNALCLASS = (((uintptr_t)1) << ((sizeof(uintptr_t) * 8) - 1)) static
Definition at line 56 of file RexxBehaviour.hpp.
Referenced by getSavedPrimitiveBehaviour(), and restoreSavedPrimitiveBehaviour().
methodDictionary
MethodDictionary* RexxBehaviour::methodDictionary protected
Definition at line 172 of file RexxBehaviour.hpp.
Referenced by addInstanceMethod(), addInstanceMethods(), addScope(), allScopes(), copyBehaviour(), copyMethodDictionary(), defineMethod(), deleteMethod(), flatten(), getMethod(), getMethodDictionary(), getMethods(), hasInstanceMethods(), hasScope(), hideMethod(), immediateSuperScope(), inheritInstanceMethods(), live(), liveGeneral(), merge(), mergeMethodDictionary(), methodLookup(), removeInstanceMethod(), removeMethod(), replaceMethod(), restore(), RexxBehaviour(), setMethodDictionary(), setMethodDictionaryScope(), superMethod(), and superScope().
operatorMethods
PCPPM* RexxBehaviour::operatorMethods protected
Definition at line 173 of file RexxBehaviour.hpp.
Referenced by copyBehaviour(), getOperatorMethod(), getOperatorMethods(), liveGeneral(), resolveNonPrimitiveBehaviour(), and RexxBehaviour().
owningClass
RexxClass* RexxBehaviour::owningClass protected
Definition at line 174 of file RexxBehaviour.hpp.
Referenced by copyBehaviour(), flatten(), getOwningClass(), immediateSuperScope(), live(), liveGeneral(), restore(), restoreClass(), RexxBehaviour(), setOwningClass(), and superScope().
primitiveBehaviours
RexxBehaviour RexxBehaviour::primitiveBehaviours static
Definition at line 156 of file RexxBehaviour.hpp.
Referenced by getPrimitiveBehaviour(), MemoryObject::restoreImage(), and restoreSavedPrimitiveBehaviour().
The documentation for this class was generated from the following files:
RexxBehaviour.hpp
PrimitiveBehaviours.cpp
RexxBehaviour.cpp