ooRexx: ActivityManager Class Reference
ActivityManager Class Reference
#include <ActivityManager.hpp>
Public Member Functions
DirectoryClass * getLocalRexx ()
Static Public Member Functions
static void live (size_t)
static void liveGeneral (MarkReason reason)
static void addWaitingActivity (Activity *a, bool release)
static void addWaitingApiActivity (Activity *a)
static bool dispatchNext ()
static bool hasWaiters ()
static bool hasApiWaiters ()
static Activity * findActivity ()
static Activity * findActivity (thread_id_t)
static Activity * getActivity ()
static void returnActivity (Activity *)
static void activityEnded (Activity *)
static void shutdown ()
static void checkShutdown ()
static void createInterpreter ()
static void terminateInterpreter ()
static void lockKernel ()
static void unlockKernel ()
static void releaseAccess ()
static bool lockKernelImmediate ()
static void createLocks ()
static void closeLocks ()
static void init ()
static RexxActivation * newActivation (Activity *activity, RoutineClass *routine, RexxCode *code, RexxString *calltype, RexxString *environment, ActivationContext context)
static RexxActivation * newActivation (Activity *activity, RexxActivation *parent, RexxCode *code, ActivationContext context)
static RexxActivation * newActivation (Activity *activity, MethodClass *method, RexxCode *code)
static NativeActivation * newNativeActivation (Activity *activity, RexxActivation *parent)
static NativeActivation * newNativeActivation (Activity *activity)
static Activity * createNewActivity ()
static Activity * createCurrentActivity ()
static Activity * createNewActivity (Activity *)
static void haltAllActivities (RexxString *)
static void traceAllActivities (bool on)
static bool setActivityTrace (thread_id_t thread_id, bool on_or_off)
static void clearActivityPool ()
static bool poolActivity (Activity *activity)
static bool haltActivity (thread_id_t thread_id, RexxString *description)
static void yieldCurrentActivity ()
static void exit (int retcode)
static void relinquish (Activity *activity)
static void relinquishIfNeeded (Activity *activity)
static Activity * getRootActivity ()
static void returnRootActivity (Activity *activity)
static Activity * attachThread ()
static RexxObject * getLocalEnvironment (RexxString *name)
static DirectoryClass * getLocal ()
static void suspendDispatch (Activity *activity)
static void removeWaitingActivity (Activity *waitingAct)
static void returnWaitingActivity (Activity *waitingAct)
static void handleNestedActivity (Activity *newActivity, Activity *oldActivity)
static void postTermination ()
static void waitForTermination ()
Static Public Attributes
static Activity *volatile currentActivity = OREF_NULL
Static Protected Attributes
static const size_t MAX_THREAD_POOL_SIZE = 5
static const uint64_t timeSliceLength = 24
static QueueClass * availableActivities = OREF_NULL
static QueueClass * allActivities = OREF_NULL
static bool processTerminating = false
static size_t interpreterInstances = 0
static SysMutex kernelSemaphore
static SysSemaphore terminationSem
static volatile bool sentinel = false
static std::deque< Activity * > waitingActivities
static size_t waitingAttaches = 0
static size_t waitingAccess = 0
static size_t waitingApiAccess = 0
static uint64_t lastLockTime = 0
Detailed Description
Definition at line 58 of file ActivityManager.hpp.
Member Function Documentation
activityEnded()
void ActivityManager::activityEnded (Activity * activityObject) static
Return an activity to the activity pool.
Parameters
activityObject The released activity.
Definition at line 833 of file ActivityManager.cpp.
References allActivities, Activity::cleanupActivityResources(), ArrayClass::isEmpty(), postTermination(), processTerminating, and ArrayClass::removeItem().
Referenced by Activity::runThread().
addWaitingActivity()
void ActivityManager::addWaitingActivity (Activity * waitingAct, bool release) static
Add a waiting activity to the waiting queue.
Parameters
waitingAct The activity to queue up.
release If true, the kernel lock should be released on completion.
Definition at line 133 of file ActivityManager.cpp.
References Activity::clearRunWait(), Activity::clearWaitingForDispatch(), currentActivity, hasWaiters(), OREF_NULL, DispatchSection::reacquire(), DispatchSection::release(), releaseAccess(), sentinel, Activity::setupCurrentActivity(), Activity::setWaitingForDispatch(), Activity::waitForDispatch(), Activity::waitForKernel(), waitingAccess, waitingActivities, and Activity::yield().
Referenced by relinquish(), relinquishIfNeeded(), and Activity::requestAccess().
addWaitingApiActivity()
void ActivityManager::addWaitingApiActivity (Activity * waitingAct) static
Add a waiting activity to the waiting queue. This is done with priority access with no dispatch wait so that external callbacks can behave quickly in highly concurrent environments.
Parameters
waitingAct The activity to queue up.
Definition at line 258 of file ActivityManager.cpp.
References Activity::clearWaitingForDispatch(), dispatchNext(), DispatchSection::reacquire(), DispatchSection::release(), sentinel, Activity::setupCurrentActivity(), Activity::setWaitingForDispatch(), Activity::waitForKernel(), waitingAccess, waitingApiAccess, and yieldCurrentActivity().
Referenced by Activity::requestApiAccess().
attachThread()
Activity * ActivityManager::attachThread () static
Attach an activity to an interpreter instance
Parameters
instance The interpreter instance involved.
Returns
A new activity instance created for this thread. This activity will own the kernel lock on return.
Definition at line 952 of file ActivityManager.cpp.
References createCurrentActivity(), findActivity(), handleNestedActivity(), lockKernel(), lockKernelImmediate(), DispatchSection::reacquire(), DispatchSection::release(), sentinel, Activity::setupCurrentActivity(), and waitingAttaches.
Referenced by InterpreterInstance::attachThread().
checkShutdown()
static void ActivityManager::checkShutdown () static
clearActivityPool()
void ActivityManager::clearActivityPool () static
Clear the activty pool of pooled activities.
Definition at line 569 of file ActivityManager.cpp.
References availableActivities, OREF_NULL, QueueClass::pull(), and Activity::terminatePoolActivity().
Referenced by shutdown().
closeLocks()
void ActivityManager::closeLocks () static
Cleanup the global locks for the ActivityManager.
Definition at line 758 of file ActivityManager.cpp.
References SysSemaphore::close(), SysMutex::close(), kernelSemaphore, and terminationSem.
Referenced by Interpreter::processShutdown().
createCurrentActivity()
Activity * ActivityManager::createCurrentActivity () static
Create an activity object for the current thread.
Returns
Definition at line 530 of file ActivityManager.cpp.
References allActivities, and ArrayClass::append().
Referenced by attachThread(), and getRootActivity().
createInterpreter()
void ActivityManager::createInterpreter () static
Terminate an interpreter instance. This starts process shutdown if the last instance goes away.
Definition at line 365 of file ActivityManager.cpp.
References interpreterInstances.
createLocks()
void ActivityManager::createLocks () static
Create the global kernel lock for the ActivityManager.
Definition at line 746 of file ActivityManager.cpp.
References SysSemaphore::create(), SysMutex::create(), kernelSemaphore, SysSemaphore::reset(), and terminationSem.
Referenced by Interpreter::processStartup().
createNewActivity() [1/2]
Activity * ActivityManager::createNewActivity () static
Obtain a new activity for running on a separate thread.
Returns
The created (or pooled) activity object.
Definition at line 496 of file ActivityManager.cpp.
References allActivities, ArrayClass::append(), availableActivities, OREF_NULL, QueueClass::pull(), ResourceSection::reacquire(), ResourceSection::release(), and Activity::reset().
Referenced by createNewActivity(), and InterpreterInstance::spawnActivity().
createNewActivity() [2/2]
Activity * ActivityManager::createNewActivity (Activity * parent) static
Clone off an activity from an existing activity. Used for message start() are early reply operations.
Parameters
parent The currently running activity. The activity-specific settings are inherited from the parent.
Returns
A new activity.
Definition at line 556 of file ActivityManager.cpp.
References createNewActivity(), and Activity::inheritSettings().
dispatchNext()
bool ActivityManager::dispatchNext () static
Find an activity in the queue that is waiting for run permission and free it up for execution. Elements in the waitingActivities queue can be in different places in the dispatch process and we don't want to get things held up because an activity might not be able to obtain the lock immediately.
Returns
true if an item was dispatched, false if nothing was dispatched.
Definition at line 311 of file ActivityManager.cpp.
References Activity::hasRunPermission(), OREF_NULL, Activity::postDispatch(), and waitingActivities.
Referenced by addWaitingApiActivity(), releaseAccess(), and suspendDispatch().
exit()
void ActivityManager::exit (int retcode) static
Really shut down–this exits the process
Parameters
retcode The exit return code.
Definition at line 721 of file ActivityManager.cpp.
findActivity() [1/2]
Activity * ActivityManager::findActivity () static
Locate the activity associated with the current thread
Returns
The Activity for this thread, if it exists.
Definition at line 710 of file ActivityManager.cpp.
References SysActivity::queryThreadID().
Referenced by attachThread(), getActivity(), getRootActivity(), haltActivity(), and setActivityTrace().
findActivity() [2/2]
Activity * ActivityManager::findActivity (thread_id_t threadId) static
Locate the activity associated with a thread
Parameters
threadId The target thread id
Returns
The activity, or OREF_NULL if this is not currently in use.
Definition at line 684 of file ActivityManager.cpp.
References allActivities, ArrayClass::get(), Activity::isSuspended(), Activity::isThread(), ArrayClass::lastIndex(), and OREF_NULL.
getActivity()
Activity * ActivityManager::getActivity () static
Get an already existing activity for the current thread and give it kernel access before returning. This will fail if the thread has not been properly attached.
Returns
The activity for this thread.
Definition at line 1095 of file ActivityManager.cpp.
References Activity::enterCurrentThread(), findActivity(), and OREF_NULL.
Referenced by NativeContextBlock::NativeContextBlock().
getLocal()
DirectoryClass * ActivityManager::getLocal () static
Retrieve the current .local directory instance.
Returns
The .local directory for the current activity.
Definition at line 1135 of file ActivityManager.cpp.
References currentActivity, Activity::getLocal(), and OREF_NULL.
Referenced by getLocalRexx().
getLocalEnvironment()
RexxObject * ActivityManager::getLocalEnvironment (RexxString * name) static
Retrieve a variable from the current local environment object.
Parameters
name The name of the environment variable.
Returns
The object stored in .local at the requested name.
Definition at line 1120 of file ActivityManager.cpp.
References currentActivity, Activity::getLocalEnvironment(), OREF_NULL, and TheNilObject.
Referenced by PackageClass::findClass(), Interpreter::findClass(), and Interpreter::getCurrentQueue().
getLocalRexx()
DirectoryClass* ActivityManager::getLocalRexx () inline
Definition at line 164 of file ActivityManager.hpp.
References getLocal().
Referenced by MemoryObject::createImage().
getRootActivity()
Activity * ActivityManager::getRootActivity () static
Get a root activity for a new interpreter instance.
Returns
The newly created activity.
Definition at line 859 of file ActivityManager.cpp.
References Activity::activate(), createCurrentActivity(), findActivity(), handleNestedActivity(), lockKernel(), sentinel, Activity::setInterpreterRoot(), and Activity::setupCurrentActivity().
Referenced by Interpreter::createInterpreterInstance().
haltActivity()
bool ActivityManager::haltActivity (thread_id_t thread_id, RexxString * description) static
Raise a halt condition on an activity.
Parameters
thread_id The target thread identifier.
description The description of the halt.
Returns
Returns the halt result. Returns false if a halt condition is already pending or the target activity is not found.
Definition at line 628 of file ActivityManager.cpp.
References findActivity(), Activity::halt(), and OREF_NULL.
Referenced by RexxHaltThread().
haltAllActivities()
static void ActivityManager::haltAllActivities (RexxString *) static
handleNestedActivity()
void ActivityManager::handleNestedActivity (Activity * newActivity, Activity * oldActivity) static
Handle nesting of activities caused by recursive reentry into the interpreter with a new attach or instance.
Parameters
newActivity The newly created activity object.
oldActivity The (potential) old activity.
Definition at line 919 of file ActivityManager.cpp.
References Activity::isWaitingForDispatch(), OREF_NULL, Activity::setNestedActivity(), Activity::setSuspended(), and suspendDispatch().
Referenced by attachThread(), and getRootActivity().
hasApiWaiters()
static bool ActivityManager::hasApiWaiters () inline static
Definition at line 68 of file ActivityManager.hpp.
References waitingApiAccess.
Referenced by relinquishIfNeeded().
hasWaiters()
static bool ActivityManager::hasWaiters () inline static
Definition at line 67 of file ActivityManager.hpp.
References waitingAccess, and waitingAttaches.
Referenced by addWaitingActivity(), lockKernelImmediate(), relinquish(), and relinquishIfNeeded().
init()
void ActivityManager::init () static
Initialize the activity manager when the interpreter starts up.
Definition at line 90 of file ActivityManager.cpp.
References allActivities, availableActivities, currentActivity, new_queue(), and OREF_NULL.
Referenced by MemoryObject::createImage(), and MemoryObject::restore().
live()
void ActivityManager::live (size_t liveMark) static
Live marking of the objects owned by the activity manager.
Parameters
liveMark The current live mark value.
Definition at line 103 of file ActivityManager.cpp.
References allActivities, availableActivities, and memory_mark.
Referenced by MemoryObject::live().
liveGeneral()
void ActivityManager::liveGeneral (MarkReason reason) static
Generalized marking of activity manager owned objects.
Parameters
reason The marking reason.
Definition at line 114 of file ActivityManager.cpp.
References allActivities, availableActivities, memory_mark_general, and SAVINGIMAGE.
Referenced by MemoryObject::liveGeneral().
lockKernel()
static void ActivityManager::lockKernel () inline static
Definition at line 80 of file ActivityManager.hpp.
References SysThread::getMillisecondTicks(), kernelSemaphore, lastLockTime, and SysMutex::request().
Referenced by attachThread(), getRootActivity(), and Activity::waitForKernel().
lockKernelImmediate()
bool ActivityManager::lockKernelImmediate () static
Try a fast request for the kernel. This requires A) there be no waiting activities and B) that it be possible to request the semaphore without waiting.
Returns
true if the semaphore was obtained, false if the kernel is not locked by this activity.
Definition at line 773 of file ActivityManager.cpp.
References hasWaiters(), kernelSemaphore, and SysMutex::requestImmediate().
Referenced by attachThread(), Activity::requestAccess(), and Activity::requestApiAccess().
newActivation() [1/3]
RexxActivation * ActivityManager::newActivation (Activity * activity, MethodClass * method, RexxCode * code) static
Create a new activation for a method invocation (vs. a program or routine call)
Parameters
activity The activity we're running on.
method The method object being invoked.
code The code object associated with the method.
Returns
The newly created activation.
Definition at line 452 of file ActivityManager.cpp.
newActivation() [2/3]
RexxActivation * ActivityManager::newActivation (Activity * activity, RexxActivation * parent, RexxCode * code, ActivationContext context) static
Create a new activation for an internal level call (internal call or interpreted execution).
Parameters
activity The activity we're running on.
parent The parent activation. OREF_NULL is used if this is a top-level call.
code The code object associated with the method.
context The context of the invocation.
Returns
The newly created activation.
Definition at line 434 of file ActivityManager.cpp.
newActivation() [3/3]
RexxActivation * ActivityManager::newActivation (Activity * activity, RoutineClass * routine, RexxCode * code, RexxString * calltype, RexxString * environment, ActivationContext context) static
Create a new activation for a toplevel activation using a routine (vs. a method invocation).
Parameters
activity The activity we're running on.
routine The routine object we're calling.
code The code object associated with the method.
calltype The type of call being made.
environment The initial address environment.
context The context of the invocation.
Returns
The newly created activation.
Definition at line 414 of file ActivityManager.cpp.
Referenced by RexxCode::call(), RexxActivation::debugInterpret(), RexxActivation::internalCall(), RexxActivation::internalCallTrap(), RexxActivation::interpret(), and RexxCode::run().
newNativeActivation() [1/2]
NativeActivation * ActivityManager::newNativeActivation (Activity * activity) static
Create a new activation for a a native external call stack
Parameters
activity The activity we're running on.
Returns
The newly created activation.
Definition at line 483 of file ActivityManager.cpp.
newNativeActivation() [2/2]
NativeActivation * ActivityManager::newNativeActivation (Activity * activity, RexxActivation * parent) static
Create a new activation for a a native external call stack
Parameters
activity The activity we're running on.
parent The parent activation.
Returns
The newly created activation.
Definition at line 468 of file ActivityManager.cpp.
Referenced by NativeRoutine::call(), RegisteredRoutine::call(), Activity::createNewActivationStack(), Activity::exitKernel(), NativeMethod::run(), and Activity::run().
poolActivity()
bool ActivityManager::poolActivity (Activity * activity) static
Return an activity to the available pool. If we're in the process of shutting down, or have too many pool activities, we'll return false to tell the activity to completely shut things down.
Parameters
activity The activity we're adding back to the available pool.
Returns
true if this was pooled, false if the thread should not wait for more work.
Definition at line 594 of file ActivityManager.cpp.
References allActivities, ArrayClass::append(), availableActivities, Activity::cleanupActivityResources(), ArrayClass::items(), MAX_THREAD_POOL_SIZE, processTerminating, and ArrayClass::removeItem().
Referenced by InterpreterInstance::poolActivity().
postTermination()
static void ActivityManager::postTermination () inline static
Definition at line 171 of file ActivityManager.hpp.
References SysSemaphore::post(), and terminationSem.
Referenced by activityEnded().
releaseAccess()
void ActivityManager::releaseAccess () static
release the kernel access and make sure waiting activites are woken up.
Definition at line 730 of file ActivityManager.cpp.
References dispatchNext(), and unlockKernel().
Referenced by addWaitingActivity(), and Activity::releaseAccess().
relinquish()
static void ActivityManager::relinquish (Activity * activity) inline static
Definition at line 119 of file ActivityManager.hpp.
References addWaitingActivity(), and hasWaiters().
Referenced by Activity::relinquish().
relinquishIfNeeded()
static void ActivityManager::relinquishIfNeeded (Activity * activity) inline static
Definition at line 129 of file ActivityManager.hpp.
References addWaitingActivity(), SysThread::getMillisecondTicks(), hasApiWaiters(), hasWaiters(), lastLockTime, and timeSliceLength.
Referenced by RexxActivation::run().
removeWaitingActivity()
void ActivityManager::removeWaitingActivity (Activity * waitingAct) static
In certain situations (mostly confined to Windows), we can re-enter the interpreter on a thread that is currently on the dispatch queue. If that activity gets dispatched, then everything blocks because the activity never wakes up until the nested thread returns. In that situation, we need to ensure that the original waiting activity is removed from the dispatch queue until it is the top activity on the stack.
Parameters
waitingAct The activity to remove from the queue.
Definition at line 1063 of file ActivityManager.cpp.
References waitingActivities.
Referenced by suspendDispatch().
returnActivity()
void ActivityManager::returnActivity (Activity * activityObject) static
Return an activity to the activity pool.
Parameters
activityObject The released activity.
Definition at line 791 of file ActivityManager.cpp.
References allActivities, Activity::cleanupActivityResources(), Activity::getNestedActivity(), Activity::isWaitingForDispatch(), OREF_NULL, ArrayClass::removeItem(), returnWaitingActivity(), and Activity::setSuspended().
Referenced by MemoryObject::createImage(), and InterpreterInstance::detachThread().
returnRootActivity()
void ActivityManager::returnRootActivity (Activity * activity) static
return a root activity when an interpreter instance terminates.
Definition at line 895 of file ActivityManager.cpp.
References allActivities, Activity::cleanupActivityResources(), Activity::detachInstance(), and ArrayClass::removeItem().
Referenced by InterpreterInstance::terminate().
returnWaitingActivity()
void ActivityManager::returnWaitingActivity (Activity * waitingAct) static
return a nested waiting activity to the waiting queue.
Parameters
waitingAct The activity to queue up.
Definition at line 342 of file ActivityManager.cpp.
References Activity::isWaitingForApiAccess(), Activity::postDispatch(), waitingAccess, and waitingApiAccess.
Referenced by returnActivity().
setActivityTrace()
bool ActivityManager::setActivityTrace (thread_id_t thread_id, bool on_or_off) static
Flip on external trace for a thread.
Parameters
thread_id The target thread id.
on_or_off The trace setting.
Returns
true if this worked, false otherwise.
Definition at line 650 of file ActivityManager.cpp.
References findActivity(), OREF_NULL, and Activity::setTrace().
Referenced by RexxResetThreadTrace(), and RexxSetThreadTrace().
shutdown()
void ActivityManager::shutdown () static
Shutdown the activity manager and initiate interpreter termination.
Definition at line 391 of file ActivityManager.cpp.
References clearActivityPool(), and processTerminating.
Referenced by terminateInterpreter().
suspendDispatch()
void ActivityManager::suspendDispatch (Activity * activity) static
Remove an activity from the dispatch queue when a an attach is superceding an activity that is in the dispatch queue.
Parameters
activity The activity to suspend.
Definition at line 1012 of file ActivityManager.cpp.
References dispatchNext(), Activity::isWaitingForApiAccess(), removeWaitingActivity(), waitingAccess, waitingActivities, and waitingApiAccess.
Referenced by handleNestedActivity().
terminateInterpreter()
void ActivityManager::terminateInterpreter () static
Terminate an interpreter instance. This starts process shutdown if the last instance goes away.
Definition at line 374 of file ActivityManager.cpp.
References interpreterInstances, and shutdown().
traceAllActivities()
static void ActivityManager::traceAllActivities (bool on) static
unlockKernel()
static void ActivityManager::unlockKernel () inline static
Definition at line 87 of file ActivityManager.hpp.
References currentActivity, kernelSemaphore, OREF_NULL, SysMutex::release(), and sentinel.
Referenced by releaseAccess().
waitForTermination()
static void ActivityManager::waitForTermination () inline static
Definition at line 176 of file ActivityManager.hpp.
References terminationSem, and SysSemaphore::wait().
yieldCurrentActivity()
void ActivityManager::yieldCurrentActivity () static
Signal an activation to yield control
Definition at line 667 of file ActivityManager.cpp.
References currentActivity, OREF_NULL, and Activity::yield().
Referenced by addWaitingApiActivity().
Member Data Documentation
allActivities
QueueClass * ActivityManager::allActivities = OREF_NULL static protected
Definition at line 188 of file ActivityManager.hpp.
Referenced by activityEnded(), createCurrentActivity(), createNewActivity(), findActivity(), init(), live(), liveGeneral(), poolActivity(), returnActivity(), and returnRootActivity().
availableActivities
QueueClass * ActivityManager::availableActivities = OREF_NULL static protected
Definition at line 187 of file ActivityManager.hpp.
Referenced by clearActivityPool(), createNewActivity(), init(), live(), liveGeneral(), and poolActivity().
currentActivity
Activity *volatile ActivityManager::currentActivity = OREF_NULL static
Definition at line 169 of file ActivityManager.hpp.
Referenced by addWaitingActivity(), DirectoryClass::allItems(), NativeActivation::callNativeRoutine(), CalloutBlock::CalloutBlock(), NativeActivation::callRegisteredRoutine(), RoutineClass::callRexx(), RoutineClass::callWithRexx(), RexxObject::checkPackage(), RexxObject::checkPrivate(), RexxObject::checkRestrictedMethod(), MessageClass::checkReuse(), RexxCompoundVariable::clearGuard(), RexxSimpleVariable::clearGuard(), RexxStemVariable::clearGuard(), MutexSemaphoreClass::close(), MemoryObject::createImage(), RexxActivation::debugInterpret(), MessageClass::dispatch(), LanguageParser::error(), LanguageParser::errorLine(), LanguageParser::errorPosition(), LanguageParser::errorToken(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxInstructionGuard::execute(), RexxActivation::exitFrom(), PackageClass::findProgramRexx(), DirectoryClass::getIndex(), getLocal(), getLocalEnvironment(), MutexSemaphoreClass::handleNesting(), init(), PackageClass::install(), RexxActivation::interpret(), lastMessageName(), LibraryPackage::loadPackage(), PackageClass::loadPackageRexx(), RexxObject::messageSend(), DirectoryClass::methodTableValue(), MethodClass::newMethodObject(), PackageClass::newRexx(), RexxVariable::notify(), LanguageParser::parseMessageSubterm(), LanguageParser::parseSubTerm(), BaseExecutable::processNewExecutableArgs(), BaseExecutable::processNewFileExecutableArgs(), RexxObject::processProtectedMethod(), RexxActivation::processTraps(), RexxObject::processUnknown(), ProtectedBase::ProtectedBase(), RexxActivation::raise(), MutexSemaphoreClass::release(), Activity::releaseAccess(), reportCondition(), reportException(), reportNomethod(), RexxInternalObject::requestString(), MessageClass::result(), Activity::run(), NativeActivation::run(), RexxObject::run(), RexxActivation::run(), Activity::runThread(), MemoryObject::runUninits(), MessageClass::sendNotification(), RexxCompoundVariable::setGuard(), RexxSimpleVariable::setGuard(), RexxStemVariable::setGuard(), Activity::setupCurrentActivity(), MessageClass::start(), DirectoryClass::supplier(), PackageClass::traceBack(), LanguageParser::translate(), DirectoryClass::unknownValue(), LibraryPackage::unload(), unlockKernel(), UnsafeBlock::UnsafeBlock(), Activity::updateFrameMarkers(), MessageClass::wait(), and yieldCurrentActivity().
interpreterInstances
size_t ActivityManager::interpreterInstances = 0 static protected
Definition at line 190 of file ActivityManager.hpp.
Referenced by createInterpreter(), and terminateInterpreter().
kernelSemaphore
SysMutex ActivityManager::kernelSemaphore static protected
Definition at line 195 of file ActivityManager.hpp.
Referenced by closeLocks(), createLocks(), lockKernel(), lockKernelImmediate(), and unlockKernel().
lastLockTime
uint64_t ActivityManager::lastLockTime = 0 static protected
Definition at line 202 of file ActivityManager.hpp.
Referenced by lockKernel(), and relinquishIfNeeded().
MAX_THREAD_POOL_SIZE
const size_t ActivityManager::MAX_THREAD_POOL_SIZE = 5 static protected
Definition at line 184 of file ActivityManager.hpp.
Referenced by poolActivity().
processTerminating
bool ActivityManager::processTerminating = false static protected
Definition at line 189 of file ActivityManager.hpp.
Referenced by activityEnded(), poolActivity(), and shutdown().
sentinel
volatile bool ActivityManager::sentinel = false static protected
Definition at line 197 of file ActivityManager.hpp.
Referenced by addWaitingActivity(), addWaitingApiActivity(), attachThread(), getRootActivity(), and unlockKernel().
terminationSem
SysSemaphore ActivityManager::terminationSem static protected
Definition at line 196 of file ActivityManager.hpp.
Referenced by closeLocks(), createLocks(), postTermination(), and waitForTermination().
timeSliceLength
const uint64_t ActivityManager::timeSliceLength = 24 static protected
Definition at line 185 of file ActivityManager.hpp.
Referenced by relinquishIfNeeded().
waitingAccess
size_t ActivityManager::waitingAccess = 0 static protected
Definition at line 200 of file ActivityManager.hpp.
Referenced by addWaitingActivity(), addWaitingApiActivity(), hasWaiters(), returnWaitingActivity(), and suspendDispatch().
waitingActivities
std::deque< Activity * > ActivityManager::waitingActivities static protected
Definition at line 198 of file ActivityManager.hpp.
Referenced by addWaitingActivity(), dispatchNext(), removeWaitingActivity(), and suspendDispatch().
waitingApiAccess
size_t ActivityManager::waitingApiAccess = 0 static protected
Definition at line 201 of file ActivityManager.hpp.
Referenced by addWaitingApiActivity(), hasApiWaiters(), returnWaitingActivity(), and suspendDispatch().
waitingAttaches
size_t ActivityManager::waitingAttaches = 0 static protected
Definition at line 199 of file ActivityManager.hpp.
Referenced by attachThread(), and hasWaiters().
The documentation for this class was generated from the following files:
ActivityManager.hpp
ActivityManager.cpp