ooRexx: ForLoop Class Reference
ForLoop Class Reference
#include <DoBlockComponents.hpp>
Public Member Functions
ForLoop ()
void live (size_t liveMark)
void liveGeneral (MarkReason reason)
void setup (RexxActivation *context, ExpressionStack *stack, DoBlock *doblock, bool forKeyword)
Public Attributes
RexxInternalObject * forCount
Detailed Description
An embedded object that handles the details of a FOR count loop expression.
Definition at line 66 of file DoBlockComponents.hpp.
Constructor & Destructor Documentation
ForLoop()
ForLoop::ForLoop () inline
Definition at line 69 of file DoBlockComponents.hpp.
Member Function Documentation
live()
void ForLoop::live (size_t liveMark) inline
Definition at line 72 of file DoBlockComponents.hpp.
References forCount, and memory_mark.
Referenced by RexxInstructionDoOverFor::live(), RexxInstructionDoOverForUntil::live(), RexxInstructionDoCount::live(), RexxInstructionDoCountUntil::live(), RexxInstructionDoWithFor::live(), and RexxInstructionDoWithForUntil::live().
liveGeneral()
void ForLoop::liveGeneral (MarkReason reason) inline
Definition at line 76 of file DoBlockComponents.hpp.
References forCount, and memory_mark_general.
Referenced by RexxInstructionDoOverFor::liveGeneral(), RexxInstructionDoOverForUntil::liveGeneral(), RexxInstructionDoCount::liveGeneral(), RexxInstructionDoCountUntil::liveGeneral(), RexxInstructionDoWithFor::liveGeneral(), and RexxInstructionDoWithForUntil::liveGeneral().
setup()
void ForLoop::setup (RexxActivation * context, ExpressionStack * stack, DoBlock * doblock, bool forKeyword)
Set up for execution of a FOR loop.
Parameters
context The current execution context.
stack The current evaluation stack.
doblock The context doblock useds to store loop state data.
Definition at line 59 of file DoBlockComponents.cpp.
References Numerics::DEFAULT_DIGITS, RexxActivation::digits(), Error_Invalid_whole_number_for, Error_Invalid_whole_number_repeat, RexxInternalObject::evaluate(), forCount, isInteger(), number_digits(), RexxString::numberString(), OPERATOR_PLUS, OREF_NULL, reportException(), RexxInternalObject::requestString(), DoBlock::setFor(), SIZE_MAX, and RexxActivation::traceKeywordResult().
Referenced by ControlledLoop::setup(), RexxInstructionDoOverFor::setup(), RexxInstructionDoCount::setup(), and RexxInstructionDoWithFor::setup().
Member Data Documentation
forCount
RexxInternalObject* ForLoop::forCount
Definition at line 83 of file DoBlockComponents.hpp.
Referenced by RexxInstructionDoOverFor::flatten(), RexxInstructionDoOverForUntil::flatten(), RexxInstructionControlledDo::flatten(), RexxInstructionControlledDoUntil::flatten(), RexxInstructionDoCount::flatten(), RexxInstructionDoCountUntil::flatten(), RexxInstructionDoWithFor::flatten(), RexxInstructionDoWithForUntil::flatten(), live(), ControlledLoop::live(), liveGeneral(), ControlledLoop::liveGeneral(), LanguageParser::newDoOverLoop(), LanguageParser::newDoWithLoop(), ControlledLoop::operator=(), LanguageParser::parseCountLoop(), ControlledLoop::setup(), and setup().
The documentation for this class was generated from the following files:
DoBlockComponents.hpp
DoBlockComponents.cpp