ooRexx: TreeFinder::AttributeMask Class Reference
TreeFinder::AttributeMask Class Reference
#include <RexxUtilCommon.hpp>
Public Types
enum AttributeType {
Archive , Directory , Hidden , ReadOnly ,
System , Control
}
Public Member Functions
AttributeMask ()
bool parseMask (const char *maskArg)
bool noNewSettings ()
bool isOn (AttributeType maskSetting)
bool isOff (AttributeType maskSetting)
bool isIgnored (AttributeType maskSetting)
void set (AttributeType maskSetting, bool on)
char maskMarker (AttributeType maskSetting)
bool isSelected (AttributeType maskSetting, bool value)
bool acceptAll ()
Protected Attributes
const char AttributeOff = -1
const char AttributeOn = 1
const char AttributeIgnore = 0
const char IgnoreAll = 0
const char HaveMask = 1
int8_t mask [8]
Static Protected Attributes
static const char maskChars [6] = "ADHRS"
Detailed Description
Definition at line 286 of file RexxUtilCommon.hpp.
Member Enumeration Documentation
AttributeType
enum TreeFinder::AttributeMask::AttributeType
Enumerator
Archive
Directory
Hidden
ReadOnly
System
Control
Definition at line 290 of file RexxUtilCommon.hpp.
Constructor & Destructor Documentation
AttributeMask()
TreeFinder::AttributeMask::AttributeMask () inline
Definition at line 300 of file RexxUtilCommon.hpp.
References mask.
Member Function Documentation
acceptAll()
bool TreeFinder::AttributeMask::acceptAll () inline
Definition at line 349 of file RexxUtilCommon.hpp.
References Control, IgnoreAll, and mask.
Referenced by TreeFinder::acceptAll().
isIgnored()
bool TreeFinder::AttributeMask::isIgnored (AttributeType maskSetting) inline
Definition at line 345 of file RexxUtilCommon.hpp.
References AttributeIgnore, and mask.
isOff()
bool TreeFinder::AttributeMask::isOff (AttributeType maskSetting) inline
Definition at line 344 of file RexxUtilCommon.hpp.
References AttributeOff, and mask.
Referenced by isSelected(), and mergeAttrs().
isOn()
bool TreeFinder::AttributeMask::isOn (AttributeType maskSetting) inline
Definition at line 343 of file RexxUtilCommon.hpp.
References AttributeOn, and mask.
Referenced by isSelected(), and mergeAttrs().
isSelected()
bool TreeFinder::AttributeMask::isSelected (AttributeType maskSetting, bool value) inline
Definition at line 348 of file RexxUtilCommon.hpp.
References isOff(), and isOn().
Referenced by TreeFinder::archiveSelected(), TreeFinder::directorySelected(), TreeFinder::hiddenSelected(), TreeFinder::readOnlySelected(), and TreeFinder::systemSelected().
maskMarker()
char TreeFinder::AttributeMask::maskMarker (AttributeType maskSetting) inline
Definition at line 347 of file RexxUtilCommon.hpp.
References AttributeOn, mask, and maskChars.
noNewSettings()
bool TreeFinder::AttributeMask::noNewSettings () inline
Definition at line 342 of file RexxUtilCommon.hpp.
References Control, IgnoreAll, and mask.
Referenced by mergeAttrs().
parseMask()
bool TreeFinder::AttributeMask::parseMask (const char * maskArg) inline
Definition at line 305 of file RexxUtilCommon.hpp.
References AttributeIgnore, AttributeOff, AttributeOn, Control, HaveMask, IgnoreAll, and mask.
Referenced by TreeFinder::parseMask().
set()
void TreeFinder::AttributeMask::set (AttributeType maskSetting, bool on) inline
Definition at line 346 of file RexxUtilCommon.hpp.
References AttributeOff, AttributeOn, and mask.
Member Data Documentation
AttributeIgnore
const char TreeFinder::AttributeMask::AttributeIgnore = 0 protected
Definition at line 355 of file RexxUtilCommon.hpp.
Referenced by isIgnored(), and parseMask().
AttributeOff
const char TreeFinder::AttributeMask::AttributeOff = -1 protected
Definition at line 353 of file RexxUtilCommon.hpp.
Referenced by isOff(), parseMask(), and set().
AttributeOn
const char TreeFinder::AttributeMask::AttributeOn = 1 protected
Definition at line 354 of file RexxUtilCommon.hpp.
Referenced by isOn(), maskMarker(), parseMask(), and set().
HaveMask
const char TreeFinder::AttributeMask::HaveMask = 1 protected
Definition at line 357 of file RexxUtilCommon.hpp.
Referenced by parseMask().
IgnoreAll
const char TreeFinder::AttributeMask::IgnoreAll = 0 protected
Definition at line 356 of file RexxUtilCommon.hpp.
Referenced by acceptAll(), noNewSettings(), and parseMask().
mask
int8_t TreeFinder::AttributeMask::mask[8] protected
Definition at line 360 of file RexxUtilCommon.hpp.
Referenced by acceptAll(), AttributeMask(), isIgnored(), isOff(), isOn(), maskMarker(), noNewSettings(), parseMask(), and set().
maskChars
const char TreeFinder::AttributeMask::maskChars = "ADHRS" static protected
Definition at line 358 of file RexxUtilCommon.hpp.
Referenced by maskMarker().
The documentation for this class was generated from the following files:
RexxUtilCommon.hpp
RexxUtilCommon.cpp