ooRexx: ExpressionStack Class Reference
ExpressionStack Class Reference
#include <ExpressionStack.hpp>
Public Member Functions
ExpressionStack (RexxInternalObject **frames, size_t items)
ExpressionStack ()
void live (size_t)
void liveGeneral (MarkReason reason)
void expandArgs (size_t, size_t, size_t, const char *)
RexxString * requiredStringArg (size_t)
RexxString * optionalStringArg (size_t)
RexxInteger * requiredIntegerArg (size_t, size_t, const char *)
RexxInteger * optionalIntegerArg (size_t, size_t, const char *)
RexxObject * requiredBigIntegerArg (size_t, size_t, const char *)
RexxObject * optionalBigIntegerArg (size_t, size_t, const char *)
void migrate (Activity *)
void setFrame (RexxInternalObject **frames, size_t items)
void send (RexxString *message, RexxClass *scope, size_t count, ProtectedObject &result)
void send (RexxString *message, size_t count, ProtectedObject &result)
void push (RexxInternalObject *value)
RexxInternalObject * pop ()
ArrayClass * argumentArray (size_t count)
RexxObject ** arguments (size_t count)
void replace (size_t offset, RexxObject *value)
size_t getSize ()
RexxInternalObject * getTop ()
void operatorResult (RexxObject *value)
void prefixResult (RexxObject *value)
void popn (size_t c)
void clear ()
RexxInternalObject * peek (size_t v)
RexxInternalObject ** pointer (size_t v)
size_t location ()
void setTop (size_t v)
void toss ()
RexxInternalObject ** getFrame ()
Protected Attributes
size_t size
RexxInternalObject ** top
RexxInternalObject ** stack
Detailed Description
Evaluation stack used for storing expression results during execution.
Definition at line 57 of file ExpressionStack.hpp.
Constructor & Destructor Documentation
ExpressionStack() [1/2]
ExpressionStack::ExpressionStack (RexxInternalObject ** frames, size_t items) inline
Definition at line 60 of file ExpressionStack.hpp.
References size, stack, and top.
ExpressionStack() [2/2]
ExpressionStack::ExpressionStack () inline
Definition at line 61 of file ExpressionStack.hpp.
References OREF_NULL, size, stack, and top.
Member Function Documentation
argumentArray()
ArrayClass* ExpressionStack::argumentArray (size_t count) inline
Definition at line 83 of file ExpressionStack.hpp.
References new_array(), and top.
arguments()
RexxObject** ExpressionStack::arguments (size_t count) inline
Definition at line 84 of file ExpressionStack.hpp.
References top.
Referenced by RexxExpressionFunction::evaluate(), QualifiedFunction::evaluate(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxInstructionForward::execute(), and send().
clear()
void ExpressionStack::clear () inline
Definition at line 91 of file ExpressionStack.hpp.
References stack, and top.
Referenced by RexxInstructionGuard::execute(), and RexxActivation::run().
expandArgs()
void ExpressionStack::expandArgs (size_t argcount, size_t min, size_t max, const char * function)
Verify that a function has received all of its required arguments, and did not receive extras.
Parameters
argcount The argument count.
min The min count for this function.
max The max count for this expression.
function The function name.
Definition at line 106 of file ExpressionStack.cpp.
References Error_Incorrect_call_maxarg, Error_Incorrect_call_minarg, Error_Incorrect_call_noarg, OREF_NULL, pointer(), and reportException().
getFrame()
RexxInternalObject** ExpressionStack::getFrame () inline
Definition at line 97 of file ExpressionStack.hpp.
References stack.
Referenced by RexxActivation::run(), and RexxActivation::termination().
getSize()
size_t ExpressionStack::getSize () inline
Definition at line 86 of file ExpressionStack.hpp.
References size.
getTop()
RexxInternalObject* ExpressionStack::getTop () inline
Definition at line 87 of file ExpressionStack.hpp.
References top.
live()
void ExpressionStack::live (size_t liveMark)
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Definition at line 55 of file ExpressionStack.cpp.
References memory_mark, stack, and top.
Referenced by RexxActivation::live().
liveGeneral()
void ExpressionStack::liveGeneral (MarkReason reason)
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Definition at line 72 of file ExpressionStack.cpp.
References memory_mark_general, stack, and top.
Referenced by RexxActivation::liveGeneral().
location()
size_t ExpressionStack::location () inline
Definition at line 94 of file ExpressionStack.hpp.
References stack, and top.
Referenced by RexxExpressionFunction::evaluate(), RexxExpressionList::evaluate(), QualifiedFunction::evaluate(), and RexxTarget::init().
migrate()
void ExpressionStack::migrate (Activity * activity)
Migrate this expression stack to a new activity.
Parameters
activity The new activity.
Definition at line 87 of file ExpressionStack.cpp.
References Activity::allocateStackFrame(), size, and stack.
Referenced by RexxActivation::run().
operatorResult()
void ExpressionStack::operatorResult (RexxObject * value) inline
Definition at line 88 of file ExpressionStack.hpp.
References top.
Referenced by RexxBinaryOperator::evaluate().
optionalBigIntegerArg()
RexxObject * ExpressionStack::optionalBigIntegerArg (size_t position, size_t argcount, const char * function)
Process an argument and ensure it is a valid integer that can be expressed as a 64-bit value.
Parameters
position The argument position for any error messages.
argcount The number of arguments passed to the function.
function The function name
Returns
An object that can be converted to a 64-bit value for pass-on to a native function.
Definition at line 303 of file ExpressionStack.cpp.
References Error_Incorrect_call_whole, Numerics::int64Object(), OREF_NULL, peek(), replace(), and reportException().
optionalIntegerArg()
RexxInteger * ExpressionStack::optionalIntegerArg (size_t position, size_t argcount, const char * function)
Retrieve an object from the expression stack and potentially convert it into an integer argument.
Parameters
position The argument position.
argcount The argument count (used for error reporting)
function The function name.
Returns
The argument as an integer object.
Definition at line 237 of file ExpressionStack.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_call_whole, isInteger(), new_integer(), OREF_NULL, peek(), replace(), reportException(), and RexxInternalObject::requestNumber().
optionalStringArg()
RexxString * ExpressionStack::optionalStringArg (size_t position)
Retrieve an object from the expression stack and potentially convert it into a string argument.
Parameters
position The argument position.
Returns
The string version of this object.
Definition at line 167 of file ExpressionStack.cpp.
References isString(), OREF_NULL, peek(), replace(), and RexxInternalObject::requestString().
peek()
RexxInternalObject* ExpressionStack::peek (size_t v) inline
Definition at line 92 of file ExpressionStack.hpp.
References top.
Referenced by optionalBigIntegerArg(), optionalIntegerArg(), optionalStringArg(), requiredBigIntegerArg(), requiredIntegerArg(), and requiredStringArg().
pointer()
RexxInternalObject** ExpressionStack::pointer (size_t v) inline
Definition at line 93 of file ExpressionStack.hpp.
References top.
Referenced by expandArgs().
pop()
RexxInternalObject* ExpressionStack::pop () inline
Definition at line 82 of file ExpressionStack.hpp.
References top.
Referenced by UseVariable::handleArgument(), ParseTrigger::integerTrigger(), and ParseTrigger::parse().
popn()
void ExpressionStack::popn (size_t c) inline
Definition at line 90 of file ExpressionStack.hpp.
References top.
Referenced by RexxExpressionMessage::assign(), and RexxExpressionMessage::evaluate().
prefixResult()
void ExpressionStack::prefixResult (RexxObject * value) inline
Definition at line 89 of file ExpressionStack.hpp.
References top.
Referenced by RexxExpressionMessage::evaluate(), and RexxUnaryOperator::evaluate().
push()
void ExpressionStack::push (RexxInternalObject * value) inline
Definition at line 81 of file ExpressionStack.hpp.
References top.
Referenced by RexxExpressionMessage::assign(), RexxInteger::evaluate(), NumberString::evaluate(), RexxString::evaluate(), ClassResolver::evaluate(), RexxCompoundVariable::evaluate(), RexxDotVariable::evaluate(), RexxExpressionFunction::evaluate(), RexxExpressionList::evaluate(), QualifiedFunction::evaluate(), RexxStemVariable::evaluate(), RexxSimpleVariable::evaluate(), SpecialDotVariable::evaluate(), VariableReferenceOp::evaluate(), RexxInstruction::evaluateArguments(), RexxInstructionExpression::evaluateStringExpression(), RexxInstructionAddress::execute(), RexxInstructionCommand::execute(), RexxInstructionForward::execute(), RexxInstructionParse::execute(), RexxInstructionRaise::execute(), RexxInstructionDynamicSignal::execute(), RexxActivation::internalCallTrap(), RexxTarget::next(), and RexxInstructionCallOn::trap().
replace()
void ExpressionStack::replace (size_t offset, RexxObject * value) inline
Definition at line 85 of file ExpressionStack.hpp.
References top.
Referenced by optionalBigIntegerArg(), optionalIntegerArg(), optionalStringArg(), requiredBigIntegerArg(), requiredIntegerArg(), and requiredStringArg().
requiredBigIntegerArg()
RexxObject * ExpressionStack::requiredBigIntegerArg (size_t position, size_t argcount, const char * function)
Process an argument and ensure it is a valid integer that can be expressed as a 64-bit value.
Parameters
position The argument position for any error messages.
argcount The number of arguments passed to the function.
function The function name
Returns
An object that can be converted to a 64-bit value for pass-on to a native function.
Definition at line 275 of file ExpressionStack.cpp.
References Error_Incorrect_call_whole, Numerics::int64Object(), OREF_NULL, peek(), replace(), and reportException().
requiredIntegerArg()
RexxInteger * ExpressionStack::requiredIntegerArg (size_t position, size_t argcount, const char * function)
Retrieve an object from the expression stack and potentially convert it into an integer argument.
Parameters
position The argument position.
argcount The argument count (used for error reporting)
function The function name.
Returns
The argument as an integer object.
Definition at line 201 of file ExpressionStack.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_call_whole, isInteger(), new_integer(), peek(), replace(), reportException(), and RexxInternalObject::requestNumber().
requiredStringArg()
RexxString * ExpressionStack::requiredStringArg (size_t position)
Retrieve an object from the expression stack and potentially convert it into a string argument.
Parameters
position The argument position.
Returns
The argument String value.
Definition at line 142 of file ExpressionStack.cpp.
References isString(), peek(), replace(), and RexxInternalObject::requestString().
send() [1/2]
void ExpressionStack::send (RexxString * message, RexxClass * scope, size_t count, ProtectedObject & result) inline
Definition at line 77 of file ExpressionStack.hpp.
References arguments(), and top.
Referenced by RexxExpressionMessage::assign(), RexxExpressionMessage::evaluate(), and RexxInstructionMessage::execute().
send() [2/2]
void ExpressionStack::send (RexxString * message, size_t count, ProtectedObject & result) inline
Definition at line 79 of file ExpressionStack.hpp.
References arguments(), and top.
setFrame()
void ExpressionStack::setFrame (RexxInternalObject ** frames, size_t items) inline
Definition at line 75 of file ExpressionStack.hpp.
References OREF_NULL, size, stack, and top.
Referenced by Activity::allocateStackFrame().
setTop()
void ExpressionStack::setTop (size_t v) inline
Definition at line 95 of file ExpressionStack.hpp.
References stack, and top.
Referenced by RexxExpressionFunction::evaluate(), RexxExpressionList::evaluate(), QualifiedFunction::evaluate(), and RexxTarget::next().
toss()
void ExpressionStack::toss () inline
Definition at line 96 of file ExpressionStack.hpp.
References top.
Referenced by RexxExpressionMessage::assign(), RexxExpressionMessage::evaluate(), RexxInstructionMessage::execute(), and RexxInstructionCaseWhen::execute().
Member Data Documentation
size
size_t ExpressionStack::size protected
Definition at line 101 of file ExpressionStack.hpp.
Referenced by ExpressionStack(), getSize(), migrate(), and setFrame().
stack
RexxInternalObject** ExpressionStack::stack protected
Definition at line 103 of file ExpressionStack.hpp.
Referenced by clear(), ExpressionStack(), getFrame(), live(), liveGeneral(), location(), migrate(), setFrame(), and setTop().
top
RexxInternalObject** ExpressionStack::top protected
Definition at line 102 of file ExpressionStack.hpp.
Referenced by argumentArray(), arguments(), clear(), ExpressionStack(), getTop(), live(), liveGeneral(), location(), operatorResult(), peek(), pointer(), pop(), popn(), prefixResult(), push(), replace(), send(), setFrame(), setTop(), and toss().
The documentation for this class was generated from the following files:
ExpressionStack.hpp
ExpressionStack.cpp