ooRexx: LibraryPackage Class Reference
LibraryPackage Class Reference
#include <LibraryPackage.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
LibraryPackage (RexxString *n)
LibraryPackage (RexxString *n, RexxPackageEntry *p)
LibraryPackage (RESTORETYPE restoreType)
void live (size_t liveMark) override
void liveGeneral (MarkReason reason) override
bool load ()
void unload ()
RexxPackageEntry * getPackageTable ()
void loadPackage ()
void loadRoutines (RexxRoutineEntry *table)
RexxMethodEntry * locateMethodEntry (RexxString *name)
RexxRoutineEntry * locateRoutineEntry (RexxString *name)
NativeMethod * resolveMethod (RexxString *name)
RoutineClass * resolveRoutine (RexxString *name)
PNATIVEMETHOD resolveMethodEntry (RexxString *name)
PNATIVEROUTINE resolveRoutineEntry (RexxString *name)
PREGISTEREDROUTINE resolveRegisteredRoutineEntry (RexxString *name)
void reload ()
void reload (RexxPackageEntry *pack)
bool isLoaded ()
bool isInternal ()
void makeInternal ()
StringTable * getRoutines ()
bool isPackage (RexxString *n)
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Protected Attributes
RexxPackageEntry * package
RexxString * libraryName
StringTable * routines
StringTable * publicRoutines
StringTable * methods
SysLibrary lib
bool loaded
bool internal
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
An internal descriptor for loaded library collections.
Definition at line 61 of file LibraryPackage.hpp.
Constructor & Destructor Documentation
LibraryPackage() [1/3]
LibraryPackage::LibraryPackage (RexxString * n)
Constructor for a loaded package.
Parameters
n Name of the library associated with this package. This is also the name used to load the library when requested.
Definition at line 74 of file LibraryPackage.cpp.
References libraryName.
LibraryPackage() [2/3]
LibraryPackage::LibraryPackage (RexxString * n, RexxPackageEntry * p)
Constructor for a loaded package.
Parameters
n Name of the library associated with this package. This is also the name used to load the library when requested.
m The package manager that orchestrates the loading operations.
p The packag table attached to this package name.
Definition at line 87 of file LibraryPackage.cpp.
References libraryName.
LibraryPackage() [3/3]
LibraryPackage::LibraryPackage (RESTORETYPE restoreType) inline
Definition at line 69 of file LibraryPackage.hpp.
Member Function Documentation
getPackageTable()
RexxPackageEntry * LibraryPackage::getPackageTable ()
Load a library and see if it is possible to retrieve a package entry from the library.
Returns
A package table entry, if possible. A load failure or no package loading routines returns NULL.
Definition at line 192 of file LibraryPackage.cpp.
References SysLibrary::getProcedure(), RexxString::getStringData(), lib, libraryName, SysLibrary::load(), loaded, loader(), and SysLibrary::reset().
getRoutines()
StringTable* LibraryPackage::getRoutines () inline
Definition at line 91 of file LibraryPackage.hpp.
References publicRoutines.
Referenced by PackageClass::mergeLibrary().
isInternal()
bool LibraryPackage::isInternal () inline
Definition at line 89 of file LibraryPackage.hpp.
isLoaded()
bool LibraryPackage::isLoaded () inline
Definition at line 88 of file LibraryPackage.hpp.
References loaded.
isPackage()
bool LibraryPackage::isPackage (RexxString * n) inline
Definition at line 92 of file LibraryPackage.hpp.
References libraryName, and RexxString::strCaselessCompare().
live()
void LibraryPackage::live (size_t liveMark) override virtual
Normal live marking.
Reimplemented from RexxVirtualBase.
Definition at line 100 of file LibraryPackage.cpp.
References libraryName, memory_mark, methods, publicRoutines, and routines.
liveGeneral()
void LibraryPackage::liveGeneral (MarkReason reason) override virtual
Generalized live marking.
Reimplemented from RexxVirtualBase.
Definition at line 112 of file LibraryPackage.cpp.
References lib, libraryName, memory_mark_general, methods, publicRoutines, SysLibrary::reset(), routines, and SAVINGIMAGE.
load()
bool LibraryPackage::load ()
Perform the initial loading of a package. The loading process involves resolving the external library and attempting to resolve a Rexx package exporter routine in the library. If the library loads, but does not have the package exporter function, this is a classic library.
If we do find a package exporter, then we can load all of the routines immediately. Method loads are deferred until the first request.
Parameters
manager The package manager we're attached to.
Returns
True if we were able to load this as proper ooRexx package file, false if either step failed. We do not throw exceptions here, since these are usually loaded in the context of operations that return an error result instead of an exception.
Definition at line 147 of file LibraryPackage.cpp.
References loadPackage(), and package.
loadPackage()
void LibraryPackage::loadPackage ()
Load a package with a provided package definition.
Parameters
p The package table entry.
Definition at line 229 of file LibraryPackage.cpp.
References ActivityManager::currentActivity, Error_Execution_library_version, libraryName, _RexxPackageEntry::loader, loadRoutines(), package, reportException(), _RexxPackageEntry::requiredVersion, REXX_CURRENT_INTERPRETER_VERSION, _RexxPackageEntry::routines, and Activity::run().
Referenced by load().
loadRoutines()
void LibraryPackage::loadRoutines (RexxRoutineEntry * table)
Load all of the routines in a package, registering them with the package manager.
Parameters
table The package table describing this package.
Definition at line 256 of file LibraryPackage.cpp.
References PackageManager::addPackageRoutine(), _RexxRoutineEntry::entryPoint, libraryName, _RexxRoutineEntry::name, new_string(), new_string_table(), new_upper_string(), publicRoutines, HashCollection::put(), ROUTINE_CLASSIC_STYLE, routines, setField, and _RexxRoutineEntry::style.
Referenced by loadPackage().
locateMethodEntry()
RexxMethodEntry * LibraryPackage::locateMethodEntry (RexxString * name)
Locate a named method entry from the package registration table.
Parameters
name The target name.
Returns
The entry associated with the target entry, if it exists. NULL indicates a not found condition.
Definition at line 313 of file LibraryPackage.cpp.
References _RexxPackageEntry::methods, _RexxMethodEntry::name, package, RexxString::strCaselessCompare(), and _RexxMethodEntry::style.
Referenced by resolveMethod(), and resolveMethodEntry().
locateRoutineEntry()
RexxRoutineEntry * LibraryPackage::locateRoutineEntry (RexxString * name)
Locate a named function entry from the package registration table.
Parameters
name The target name.
Returns
A pointer to the located function structure. Returns NULL if the package doesn't exist.
Definition at line 344 of file LibraryPackage.cpp.
References _RexxRoutineEntry::name, package, _RexxPackageEntry::routines, RexxString::strCaselessCompare(), and _RexxRoutineEntry::style.
Referenced by resolveRegisteredRoutineEntry(), resolveRoutine(), and resolveRoutineEntry().
makeInternal()
void LibraryPackage::makeInternal () inline
Definition at line 90 of file LibraryPackage.hpp.
operator delete()
void LibraryPackage::operator delete (void *) inline
Definition at line 65 of file LibraryPackage.hpp.
operator new()
void * LibraryPackage::operator new (size_t size)
Create a new LibraryPackage object instance.
Parameters
size Size of the object.
Returns
Pointer to new object storage.
Definition at line 62 of file LibraryPackage.cpp.
References new_object(), and T_LibraryPackage.
reload() [1/2]
void LibraryPackage::reload ()
Refresh a non-internal package after an image restore.
Definition at line 516 of file LibraryPackage.cpp.
References Interpreter::logicError(), OREF_NULL, and package.
Referenced by PackageManager::restore().
reload() [2/2]
void LibraryPackage::reload (RexxPackageEntry * pack)
Refresh an internal package after an image restore.
Parameters
pack The internal package entry.
Definition at line 531 of file LibraryPackage.cpp.
resolveMethod()
NativeMethod * LibraryPackage::resolveMethod (RexxString * name)
Get a NativeCode object for a method associated with a package.
Parameters
name Name of the target method.
Returns
A NativeCode object for this method, if located.
Definition at line 374 of file LibraryPackage.cpp.
References _RexxMethodEntry::entryPoint, HashCollection::get(), libraryName, locateMethodEntry(), methods, new_string_table(), OREF_NULL, HashCollection::put(), and setField.
Referenced by PackageManager::resolveMethod().
resolveMethodEntry()
PNATIVEMETHOD LibraryPackage::resolveMethodEntry (RexxString * name)
Resolve an entry point for a package method entry (used on a restore or reflatten);
Parameters
name Name of the target method.
Returns
The target entry point.
Definition at line 446 of file LibraryPackage.cpp.
References _RexxMethodEntry::entryPoint, Error_Execution_library_method, libraryName, locateMethodEntry(), and reportException().
resolveRegisteredRoutineEntry()
PREGISTEREDROUTINE LibraryPackage::resolveRegisteredRoutineEntry (RexxString * name)
Resolve an entry point for a package function entry (used on a restore or reflatten);
Parameters
name Name of the target function.
Returns
The target entry point.
Definition at line 494 of file LibraryPackage.cpp.
References _RexxRoutineEntry::entryPoint, Error_Execution_library_routine, libraryName, locateRoutineEntry(), reportException(), ROUTINE_CLASSIC_STYLE, and _RexxRoutineEntry::style.
resolveRoutine()
RoutineClass * LibraryPackage::resolveRoutine (RexxString * name)
Get a Routine object from a native library package.
Parameters
name Name of the target routine, searching is done caseless.
Returns
A Routine object, if located.
Definition at line 410 of file LibraryPackage.cpp.
References HashCollection::get(), locateRoutineEntry(), _RexxRoutineEntry::name, new_string(), OREF_NULL, and routines.
Referenced by PackageManager::resolveRoutine().
resolveRoutineEntry()
PNATIVEROUTINE LibraryPackage::resolveRoutineEntry (RexxString * name)
Resolve an entry point for a package function entry (used on a restore or reflatten);
Parameters
name Name of the target function.
Returns
The target entry point.
Definition at line 467 of file LibraryPackage.cpp.
References _RexxRoutineEntry::entryPoint, Error_Execution_library_routine, libraryName, locateRoutineEntry(), reportException(), ROUTINE_CLASSIC_STYLE, and _RexxRoutineEntry::style.
unload()
void LibraryPackage::unload ()
Unload a package library.
Definition at line 166 of file LibraryPackage.cpp.
References ActivityManager::currentActivity, lib, loaded, package, Activity::run(), SysLibrary::unload(), and _RexxPackageEntry::unloader.
Referenced by PackageManager::unload().
Member Data Documentation
internal
bool LibraryPackage::internal protected
Definition at line 103 of file LibraryPackage.hpp.
lib
SysLibrary LibraryPackage::lib protected
Definition at line 101 of file LibraryPackage.hpp.
Referenced by getPackageTable(), liveGeneral(), and unload().
libraryName
RexxString* LibraryPackage::libraryName protected
Definition at line 97 of file LibraryPackage.hpp.
Referenced by getPackageTable(), isPackage(), LibraryPackage(), live(), liveGeneral(), loadPackage(), loadRoutines(), resolveMethod(), resolveMethodEntry(), resolveRegisteredRoutineEntry(), and resolveRoutineEntry().
loaded
bool LibraryPackage::loaded protected
Definition at line 102 of file LibraryPackage.hpp.
Referenced by getPackageTable(), isLoaded(), and unload().
methods
StringTable* LibraryPackage::methods protected
Definition at line 100 of file LibraryPackage.hpp.
Referenced by live(), liveGeneral(), and resolveMethod().
package
RexxPackageEntry* LibraryPackage::package protected
Definition at line 96 of file LibraryPackage.hpp.
Referenced by load(), loadPackage(), locateMethodEntry(), locateRoutineEntry(), reload(), and unload().
publicRoutines
StringTable* LibraryPackage::publicRoutines protected
Definition at line 99 of file LibraryPackage.hpp.
Referenced by getRoutines(), live(), liveGeneral(), and loadRoutines().
routines
StringTable* LibraryPackage::routines protected
Definition at line 98 of file LibraryPackage.hpp.
Referenced by live(), liveGeneral(), loadRoutines(), and resolveRoutine().
The documentation for this class was generated from the following files:
LibraryPackage.hpp
LibraryPackage.cpp