ooRexx: CompoundVariableTail Class Reference
CompoundVariableTail Class Reference
#include <CompoundVariableTail.hpp>
Public Member Functions
CompoundVariableTail (VariableDictionary *dictionary, RexxInternalObject **tails, size_t tailCount)
CompoundVariableTail (RexxActivation *context, RexxInternalObject **tails, size_t tailCount)
CompoundVariableTail (RexxInternalObject **tails, size_t count)
CompoundVariableTail (RexxString *tails, size_t count)
CompoundVariableTail (RexxString *tailString)
CompoundVariableTail (const char *tailString)
CompoundVariableTail (size_t index)
CompoundVariableTail (RexxInternalObject **tails, size_t count, bool resolve)
~CompoundVariableTail ()
void ensureCapacity (size_t needed)
void expandCapacity (size_t needed)
void append (const char *newData, size_t stringLen)
void append (char newData)
RexxString * createCompoundName (RexxString *)
RexxString * makeString ()
void init ()
void buildTail (VariableDictionary *dictionary, RexxInternalObject **tails, size_t tailCount)
void buildTail (RexxActivation *context, RexxInternalObject **tails, size_t tailCount)
void buildTail (RexxInternalObject **tails, size_t count)
void buildTail (RexxString *tail)
void buildTail (RexxString *tail, size_t index)
void buildTail (size_t index)
void buildTail (const char *index)
void buildUnresolvedTail (RexxInternalObject **tails, size_t count)
void addDot ()
int compare (RexxString *name)
void useStringValue (RexxString *rep)
size_t getLength ()
const char * getTail ()
Static Public Attributes
static const size_t ALLOCATION_PAD = 100
Protected Attributes
size_t length
size_t remainder
char * tail
char * current
char buffer [LanguageParser::MAX_SYMBOL_LENGTH]
RexxString * value
Protected< BufferClass > temp
Detailed Description
A builder for constructing a tail for a compound variable.
Definition at line 57 of file CompoundVariableTail.hpp.
Constructor & Destructor Documentation
CompoundVariableTail() [1/8]
CompoundVariableTail::CompoundVariableTail (VariableDictionary * dictionary, RexxInternalObject ** tails, size_t tailCount) inline
Definition at line 61 of file CompoundVariableTail.hpp.
References buildTail(), and init().
CompoundVariableTail() [2/8]
CompoundVariableTail::CompoundVariableTail (RexxActivation * context, RexxInternalObject ** tails, size_t tailCount) inline
Definition at line 68 of file CompoundVariableTail.hpp.
References buildTail(), and init().
CompoundVariableTail() [3/8]
CompoundVariableTail::CompoundVariableTail (RexxInternalObject ** tails, size_t count) inline
Definition at line 75 of file CompoundVariableTail.hpp.
References buildTail(), and init().
CompoundVariableTail() [4/8]
CompoundVariableTail::CompoundVariableTail (RexxString * tails, size_t count) inline
Definition at line 82 of file CompoundVariableTail.hpp.
References buildTail(), and init().
CompoundVariableTail() [5/8]
CompoundVariableTail::CompoundVariableTail (RexxString * tailString) inline
Definition at line 89 of file CompoundVariableTail.hpp.
References buildTail(), and init().
CompoundVariableTail() [6/8]
CompoundVariableTail::CompoundVariableTail (const char * tailString) inline
Definition at line 96 of file CompoundVariableTail.hpp.
References buildTail(), and init().
CompoundVariableTail() [7/8]
CompoundVariableTail::CompoundVariableTail (size_t index) inline
Definition at line 103 of file CompoundVariableTail.hpp.
References buildTail(), and init().
CompoundVariableTail() [8/8]
CompoundVariableTail::CompoundVariableTail (RexxInternalObject ** tails, size_t count, bool resolve) inline
Definition at line 111 of file CompoundVariableTail.hpp.
References buildTail(), buildUnresolvedTail(), and init().
~CompoundVariableTail()
CompoundVariableTail::~CompoundVariableTail () inline
Definition at line 124 of file CompoundVariableTail.hpp.
Member Function Documentation
addDot()
void CompoundVariableTail::addDot () inline
Definition at line 169 of file CompoundVariableTail.hpp.
References append().
Referenced by buildTail(), and buildUnresolvedTail().
append() [1/2]
void CompoundVariableTail::append (char newData) inline
Definition at line 139 of file CompoundVariableTail.hpp.
References current, ensureCapacity(), and remainder.
append() [2/2]
void CompoundVariableTail::append (const char * newData, size_t stringLen) inline
Definition at line 130 of file CompoundVariableTail.hpp.
References current, ensureCapacity(), and remainder.
Referenced by addDot(), RexxInteger::copyIntoTail(), and RexxString::copyIntoTail().
buildTail() [1/7]
void CompoundVariableTail::buildTail (const char * t)
Build a tail directly from a single character string value.
Parameters
t The pointer to the tail name (as an asciiz string);
Definition at line 248 of file CompoundVariableTail.cpp.
References length, remainder, and tail.
buildTail() [2/7]
void CompoundVariableTail::buildTail (RexxActivation * context, RexxInternalObject ** tails, size_t tailCount)
Construct a tail piece from its elements, using a Rexx context for resolving variables.
Parameters
context The Rexx variable context
tails
tailCount
Definition at line 153 of file CompoundVariableTail.cpp.
References addDot(), RexxInternalObject::copyIntoTail(), current, RexxInternalObject::getValue(), isInteger(), isString(), length, OREF_NULL, tail, and useStringValue().
buildTail() [3/7]
void CompoundVariableTail::buildTail (RexxInternalObject ** tails, size_t count)
Resolve the "stem.[a,b,c]=" pieces to a fully qualified stem name.
Parameters
tails The array of tails.
count The count of tails.
Definition at line 204 of file CompoundVariableTail.cpp.
References addDot(), RexxInternalObject::copyIntoTail(), current, length, OREF_NULL, and tail.
buildTail() [4/7]
void CompoundVariableTail::buildTail (RexxString * _tail)
Construct a tail from a single string index
Parameters
_tail The single tail value.
Definition at line 234 of file CompoundVariableTail.cpp.
References RexxString::getLength(), RexxString::getWritableData(), length, remainder, tail, and value.
buildTail() [5/7]
void CompoundVariableTail::buildTail (RexxString * _tail, size_t index)
Build a tail from a single string and a number index value. This is used by the stem sort, and the if the tail piece does not end with a dot, one is provided.
Parameters
_tail the tail prefix.
index the index value.
Definition at line 264 of file CompoundVariableTail.cpp.
References addDot(), RexxString::copyIntoTail(), current, RexxString::endsWith(), Numerics::formatWholeNumber(), RexxString::getLength(), length, OREF_NULL, remainder, and tail.
buildTail() [6/7]
void CompoundVariableTail::buildTail (size_t index)
Build a tail from a single numeric value.
Parameters
index The numeric index.
Definition at line 291 of file CompoundVariableTail.cpp.
References current, Numerics::formatWholeNumber(), length, and remainder.
buildTail() [7/7]
void CompoundVariableTail::buildTail (VariableDictionary * dictionary, RexxInternalObject ** tails, size_t tailCount)
Construct a tail piece from its elements, using a variable dictionary as the context for resolving variables.
Parameters
dictionary The source variable dictionary.
tails
tailCount
Definition at line 101 of file CompoundVariableTail.cpp.
References addDot(), RexxInternalObject::copyIntoTail(), current, RexxInternalObject::getValue(), isInteger(), isString(), length, OREF_NULL, tail, and useStringValue().
Referenced by CompoundVariableTail().
buildUnresolvedTail()
void CompoundVariableTail::buildUnresolvedTail (RexxInternalObject ** tails, size_t count)
Build a tail value from a set of tail elements without doing variable resolution.
Parameters
tails An array of tail elements.
count The count of tail elements.
Definition at line 60 of file CompoundVariableTail.cpp.
References addDot(), RexxInternalObject::copyIntoTail(), RexxString::copyIntoTail(), current, isOfClass, length, OREF_NULL, RexxInternalObject::stringValue(), and tail.
Referenced by CompoundVariableTail().
compare()
int CompoundVariableTail::compare (RexxString * name) inline
Definition at line 170 of file CompoundVariableTail.hpp.
References RexxString::getLength(), RexxString::getStringData(), length, and tail.
Referenced by CompoundVariableTable::findEntry().
createCompoundName()
RexxString * CompoundVariableTail::createCompoundName (RexxString * stem)
Create a fully resolved compound name from this tail. This appends the stem name to the constructed tail.
Parameters
stem The stem name.
Returns
The fully resolved compound variable name as a string object.
Definition at line 342 of file CompoundVariableTail.cpp.
References RexxString::getLength(), RexxString::getStringData(), RexxString::getWritableData(), length, raw_string(), and tail.
Referenced by StemClass::createCompoundName(), StemClass::evaluateCompoundVariableValue(), StemClass::getCompoundVariableValue(), RexxActivation::traceCompoundName(), and RexxActivation::traceCompoundValue().
ensureCapacity()
void CompoundVariableTail::ensureCapacity (size_t needed) inline
Definition at line 126 of file CompoundVariableTail.hpp.
References expandCapacity(), and remainder.
Referenced by append().
expandCapacity()
void CompoundVariableTail::expandCapacity (size_t needed)
Ensure we have sufficient space for adding another tail element to our buffer.
Parameters
needed The size of the required element.
Definition at line 306 of file CompoundVariableTail.cpp.
References ALLOCATION_PAD, buffer, current, length, new_buffer(), remainder, tail, and temp.
Referenced by ensureCapacity().
getLength()
size_t CompoundVariableTail::getLength () inline
Definition at line 192 of file CompoundVariableTail.hpp.
References length.
Referenced by RexxActivation::traceCompoundValue().
getTail()
const char* CompoundVariableTail::getTail () inline
Definition at line 193 of file CompoundVariableTail.hpp.
References tail.
Referenced by RexxActivation::traceCompoundValue().
init()
void CompoundVariableTail::init () inline
Definition at line 150 of file CompoundVariableTail.hpp.
References buffer, current, length, LanguageParser::MAX_SYMBOL_LENGTH, OREF_NULL, remainder, tail, temp, and value.
Referenced by CompoundVariableTail().
makeString()
RexxString * CompoundVariableTail::makeString ()
Get the resolved tail value as a string object.
Returns
A string object representation of the tail name.
Definition at line 368 of file CompoundVariableTail.cpp.
References length, new_string(), tail, and value.
Referenced by CompoundVariableTable::findEntry().
useStringValue()
void CompoundVariableTail::useStringValue (RexxString * rep) inline
Definition at line 183 of file CompoundVariableTail.hpp.
References RexxString::getLength(), RexxString::getWritableData(), length, remainder, tail, and value.
Referenced by buildTail().
Member Data Documentation
ALLOCATION_PAD
const size_t CompoundVariableTail::ALLOCATION_PAD = 100 static
Definition at line 195 of file CompoundVariableTail.hpp.
Referenced by expandCapacity().
buffer
char CompoundVariableTail::buffer[LanguageParser::MAX_SYMBOL_LENGTH] protected
Definition at line 203 of file CompoundVariableTail.hpp.
Referenced by expandCapacity(), and init().
current
char* CompoundVariableTail::current protected
Definition at line 202 of file CompoundVariableTail.hpp.
Referenced by append(), buildTail(), buildUnresolvedTail(), expandCapacity(), and init().
length
size_t CompoundVariableTail::length protected
Definition at line 199 of file CompoundVariableTail.hpp.
Referenced by buildTail(), buildUnresolvedTail(), compare(), createCompoundName(), expandCapacity(), getLength(), init(), makeString(), and useStringValue().
remainder
size_t CompoundVariableTail::remainder protected
Definition at line 200 of file CompoundVariableTail.hpp.
Referenced by append(), buildTail(), ensureCapacity(), expandCapacity(), init(), and useStringValue().
tail
char* CompoundVariableTail::tail protected
Definition at line 201 of file CompoundVariableTail.hpp.
Referenced by buildTail(), buildUnresolvedTail(), compare(), createCompoundName(), expandCapacity(), getTail(), init(), makeString(), and useStringValue().
temp
Protected<BufferClass> CompoundVariableTail::temp protected
Definition at line 205 of file CompoundVariableTail.hpp.
Referenced by expandCapacity(), and init().
value
RexxString* CompoundVariableTail::value protected
Definition at line 204 of file CompoundVariableTail.hpp.
Referenced by buildTail(), init(), makeString(), and useStringValue().
The documentation for this class was generated from the following files:
CompoundVariableTail.hpp
CompoundVariableTail.cpp