ooRexx: QueueTable Class Reference
QueueTable Class Reference
#include <QueueManager.hpp>
Public Member Functions
QueueTable ()
DataQueue * locate (const char *name)
DataQueue * synchronizedLocate (ServerQueueManager *manager, const char *name)
DataQueue * locate (SessionID id)
DataQueue * synchronizedLocate (ServerQueueManager *manager, SessionID id)
DataQueue * remove (const char *name)
DataQueue * remove (SessionID id)
void remove (DataQueue *q)
void removeQueue (DataQueue *current, DataQueue *previous)
bool isEmpty ()
void add (DataQueue *queue)
Protected Attributes
DataQueue * queues
Detailed Description
Definition at line 190 of file QueueManager.hpp.
Constructor & Destructor Documentation
QueueTable()
QueueTable::QueueTable () inline
Definition at line 194 of file QueueManager.hpp.
References queues.
Member Function Documentation
add()
void QueueTable::add (DataQueue * queue)
add a named data queue to our list.
Parameters
queue The new queue to add.
Definition at line 450 of file QueueManager.cpp.
References DataQueue::next, and queues.
Referenced by ServerQueueManager::createNamedQueue(), ServerQueueManager::createSessionQueue(), ServerQueueManager::createUniqueQueue(), ServerQueueManager::getSessionQueue(), ServerQueueManager::openNamedQueue(), and remove().
isEmpty()
bool QueueTable::isEmpty () inline
Definition at line 226 of file QueueManager.hpp.
References queues.
Referenced by ServerQueueManager::isStoppable().
locate() [1/2]
DataQueue * QueueTable::locate (const char * name)
locate a named data queue
Parameters
name The target data queue name.
Returns
The DataQueue descriptor, or NULL if it does not exist.
Definition at line 290 of file QueueManager.cpp.
References DataQueue::next, DataQueue::queueName, queues, and Utilities::strCaselessCompare().
Referenced by ServerQueueManager::addToNamedQueue(), ServerQueueManager::cleanupProcessResources(), ServerQueueManager::clearNamedQueue(), ServerQueueManager::createNamedQueue(), ServerQueueManager::createSessionQueue(), ServerQueueManager::createUniqueQueue(), ServerQueueManager::deleteNamedQueue(), ServerQueueManager::getNamedQueueCount(), ServerQueueManager::getSessionQueue(), ServerQueueManager::openNamedQueue(), ServerQueueManager::queryNamedQueue(), and synchronizedLocate().
locate() [2/2]
DataQueue * QueueTable::locate (SessionID id)
locate a session data queue
Parameters
id The session ID of the queue.
Returns
The DataQueue for the session, which will be created if needed.
Definition at line 331 of file QueueManager.cpp.
References DataQueue::next, queues, and DataQueue::session.
remove() [1/3]
DataQueue * QueueTable::remove (const char * name)
locate and remove a named data queue
Parameters
name The queue name.
Returns
The DataQueue matching the name, or NULL if it doesn't exist.
Definition at line 371 of file QueueManager.cpp.
References DataQueue::next, DataQueue::queueName, queues, removeQueue(), and Utilities::strCaselessCompare().
Referenced by ServerQueueManager::deleteNamedQueue(), and ServerQueueManager::deleteSessionQueue().
remove() [2/3]
void QueueTable::remove (DataQueue * q)
locate and remove a specific data queue
Parameters
q The queue to remove.
Definition at line 397 of file QueueManager.cpp.
References DataQueue::next, queues, and removeQueue().
remove() [3/3]
DataQueue * QueueTable::remove (SessionID id)
locate a session data queue
Parameters
id The session identifier of the queue to remove.
Returns
The removed queue.
Definition at line 422 of file QueueManager.cpp.
References add(), DataQueue::next, queues, removeQueue(), and DataQueue::session.
removeQueue()
void QueueTable::removeQueue (DataQueue * current, DataQueue * previous) inline
Definition at line 213 of file QueueManager.hpp.
References DataQueue::next, and queues.
Referenced by remove().
synchronizedLocate() [1/2]
DataQueue * QueueTable::synchronizedLocate (ServerQueueManager * manager, const char * name)
locate a named data queue, with session manager locking
Parameters
name The target data queue name.
Returns
The DataQueue descriptor, or NULL if it does not exist.
Definition at line 317 of file QueueManager.cpp.
References locate(), and ServerQueueManager::lock.
Referenced by ServerQueueManager::pullFromNamedQueue().
synchronizedLocate() [2/2]
DataQueue * QueueTable::synchronizedLocate (ServerQueueManager * manager, SessionID id)
locate a session data queue, with session manager locking
Parameters
id The session ID of the queue.
Returns
The DataQueue for the session, which will be created if needed.
Definition at line 357 of file QueueManager.cpp.
References locate(), and ServerQueueManager::lock.
Member Data Documentation
queues
DataQueue* QueueTable::queues protected
Definition at line 235 of file QueueManager.hpp.
Referenced by add(), isEmpty(), locate(), QueueTable(), remove(), and removeQueue().
The documentation for this class was generated from the following files:
QueueManager.hpp
QueueManager.cpp