ooRexx: OverLoop Class Reference
OverLoop Class Reference
#include <DoBlockComponents.hpp>
Public Member Functions
OverLoop ()
void live (size_t liveMark)
void liveGeneral (MarkReason reason)
void setup (RexxActivation *context, ExpressionStack *stack, DoBlock *doblock)
Public Attributes
RexxVariableBase * control
RexxInternalObject * target
Detailed Description
An embedded object that manages the details of a DO/LOOP OVER type.
Definition at line 155 of file DoBlockComponents.hpp.
Constructor & Destructor Documentation
OverLoop()
OverLoop::OverLoop () inline
Definition at line 158 of file DoBlockComponents.hpp.
Member Function Documentation
live()
void OverLoop::live (size_t liveMark) inline
Definition at line 160 of file DoBlockComponents.hpp.
References control, memory_mark, and target.
Referenced by RexxInstructionDoOver::live(), RexxInstructionDoOverFor::live(), RexxInstructionDoOverUntil::live(), and RexxInstructionDoOverForUntil::live().
liveGeneral()
void OverLoop::liveGeneral (MarkReason reason) inline
Definition at line 165 of file DoBlockComponents.hpp.
References control, memory_mark_general, and target.
Referenced by RexxInstructionDoOver::liveGeneral(), RexxInstructionDoOverFor::liveGeneral(), RexxInstructionDoOverUntil::liveGeneral(), and RexxInstructionDoOverForUntil::liveGeneral().
setup()
void OverLoop::setup (RexxActivation * context, ExpressionStack * stack, DoBlock * doblock)
Set up for execution of a DO OVER loop.
Parameters
context The current execution context.
stack The current evaluation stack.
doblock The context doblock useds to store loop state data.
Definition at line 221 of file DoBlockComponents.cpp.
References control, Error_Execution_noarray, RexxInternalObject::evaluate(), isArray(), ArrayClass::makeArray(), reportException(), RexxInternalObject::requestArray(), DoBlock::setControl(), DoBlock::setOverIndex(), DoBlock::setTo(), target, and RexxActivation::traceKeywordResult().
Referenced by RexxInstructionDoOver::setup(), and RexxInstructionDoOverFor::setup().
Member Data Documentation
control
RexxVariableBase* OverLoop::control
Definition at line 174 of file DoBlockComponents.hpp.
Referenced by RexxInstructionDoOver::flatten(), RexxInstructionDoOverFor::flatten(), RexxInstructionDoOverUntil::flatten(), RexxInstructionDoOverForUntil::flatten(), live(), liveGeneral(), and setup().
target
RexxInternalObject* OverLoop::target
Definition at line 175 of file DoBlockComponents.hpp.
Referenced by RexxInstructionDoOver::flatten(), RexxInstructionDoOverFor::flatten(), RexxInstructionDoOverUntil::flatten(), RexxInstructionDoOverForUntil::flatten(), live(), liveGeneral(), and setup().
The documentation for this class was generated from the following files:
DoBlockComponents.hpp
DoBlockComponents.cpp