ooRexx: PackageClass Class Reference
PackageClass Class Reference
#include <PackageClass.hpp>
Public Member Functions
void * operator new (size_t)
PackageClass (RexxString *p, ProgramSource *s)
PackageClass (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
void deepCopy ()
void setup ()
void extractNameInformation ()
bool reconnect ()
size_t sourceSize ()
RexxString * traceBack (RexxActivation *, SourceLocation &, size_t, bool)
RexxString * extract (SourceLocation &)
ArrayClass * extractSource (SourceLocation &)
ArrayClass * extractSource ()
void mergeRequired (PackageClass *)
void mergeLibrary (LibraryPackage *)
PackageClass * loadRequires (Activity *activity, RexxString *target, ResolveType type)
PackageClass * loadRequires (Activity *activity, RexxString *target, ArrayClass *s)
void addPackage (PackageClass *package)
void inheritPackageContext (PackageClass *parent)
RoutineClass * findRoutine (RexxString *)
RoutineClass * findLocalRoutine (RexxString *)
RoutineClass * findPublicRoutine (RexxString *)
PackageClass * findNamespace (RexxString *)
RexxClass * findClass (RexxString *, RexxObject *&)
RexxClass * findClass (RexxString *n)
RexxClass * findClass (RexxString *, RexxString *)
RexxClass * findInstalledClass (RexxString *name)
RexxClass * findPublicClass (RexxString *name)
RexxString * resolveProgramName (Activity *activity, RexxString *name, ResolveType type)
void processInstall (RexxActivation *)
void install ()
bool isTraceable ()
RexxString * getLine (size_t position)
void attachSource (BufferClass *s)
void checkRexxPackage ()
bool needsInstallation ()
void setNeedsInstallation ()
void install (RexxActivation *activation)
void setProgramName (RexxString *name)
RexxString * getProgramName ()
RexxString * getProgramDirectory ()
RexxString * getProgramExtension ()
RexxString * getProgramFile ()
StringTable * getMethods ()
StringTable * getRoutines ()
bool isInternalCode ()
void setSecurityManager (RexxObject *manager)
SecurityManager * getSecurityManager ()
StringTable * getLocalRoutines ()
StringTable * getPublicRoutines ()
void setLocalRoutines (StringTable *r)
void setPublicRoutines (StringTable *r)
void addInstalledClass (RexxString *name, RexxClass *classObject, bool publicClass)
void addInstalledRoutine (RexxString *name, RoutineClass *routineObject, bool publicRoutine)
StringTable * getInstalledClasses ()
StringTable * getInstalledPublicClasses ()
StringTable * getImportedClasses ()
StringTable * getInstalledRoutines ()
StringTable * getInstalledPublicRoutines ()
StringTable * getImportedRoutines ()
StringTable * getDefinedMethods ()
ArrayClass * getPackages ()
StringTable * getResources ()
StringTable * getNamespaces ()
StringTable * getAnnotations ()
RexxString * getAnnotation (RexxString *name)
ArrayClass * getResource (RexxString *name)
void setDigits (wholenumber_t d)
wholenumber_t getDigits ()
void setForm (bool f)
bool getForm ()
void setFuzz (wholenumber_t f)
wholenumber_t getFuzz ()
void setTraceSetting (const TraceSetting &s)
const TraceSetting & getTraceSetting ()
const PackageSetting & getSettings ()
bool isRexxPackage ()
void setLanguageLevel (LanguageLevel l)
LanguageLevel getLanguageLevel ()
void enableErrorSyntax ()
void disableErrorSyntax ()
void enableFailureSyntax ()
void disableFailureSyntax ()
void enableLostdigitsSyntax ()
void disableLostdigitsSyntax ()
void enableNotreadySyntax ()
void disableNotreadySyntax ()
void enableNostringSyntax ()
void disableNostringSyntax ()
void enableNovalueSyntax ()
void disableNovalueSyntax ()
void enableProlog ()
void disableProlog ()
bool isPrologEnabled ()
RoutineClass * getMain ()
RexxString * getTrace ()
ProgramSource * detachSource ()
void attachSource (ProgramSource *s)
PackageClass * newRexx (RexxObject **init_args, size_t argCount)
RexxString * getSourceLineRexx (RexxObject *position)
RexxInteger * getSourceSizeRexx ()
StringTable * getClassesRexx ()
StringTable * getPublicClassesRexx ()
StringTable * getImportedClassesRexx ()
StringTable * getRoutinesRexx ()
StringTable * getPublicRoutinesRexx ()
StringTable * getImportedRoutinesRexx ()
StringTable * getMethodsRexx ()
StringTable * getResourcesRexx ()
StringTable * getNamespacesRexx ()
PackageClass * getNamespaceRexx ()
ArrayClass * getImportedPackagesRexx ()
RexxObject * getAnnotationRexx (RexxObject *name)
RexxObject * getResourceRexx (RexxObject *name)
PackageClass * loadPackageRexx (RexxString *name, ArrayClass *s)
RexxObject * addPackageRexx (PackageClass *package, RexxString *namespaceName)
RexxObject * addRoutineRexx (RexxString *name, RoutineClass *routine)
RexxObject * addPublicRoutineRexx (RexxString *name, RoutineClass *routine)
RexxObject * addClassRexx (RexxString *name, RexxClass *clazz)
RexxObject * addPublicClassRexx (RexxString *name, RexxClass *clazz)
RexxObject * findClassRexx (RexxString *name)
RexxObject * findRoutineRexx (RexxString *name)
RexxObject * findPublicClassRexx (RexxString *name)
RexxObject * findPublicRoutineRexx (RexxString *name)
RexxObject * findNamespaceRexx (RexxString *name)
RexxObject * setSecurityManagerRexx (RexxObject *manager)
RexxObject * loadLibraryRexx (RexxString *name)
RexxObject * digitsRexx ()
RexxObject * fuzzRexx ()
RexxObject * formRexx ()
RexxObject * traceRexx ()
ArrayClass * getSourceRexx ()
RexxObject * getMainRexx ()
RexxObject * findProgramRexx (RexxObject *name)
void runProlog (Activity *)
void addNamespace (RexxString *name, PackageClass *package)
DirectoryClass * getPackageLocal ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
HashCode hash () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
LanguageLevel requiredLanguageLevel
ProgramSource * source
RexxString * programName
RexxString * programDirectory
RexxString * programFile
RexxString * programExtension
SecurityManager * securityManager
RexxCode * initCode
BaseExecutable * mainExecutable
PackageClass * parentPackage
StringTable * routines
StringTable * publicRoutines
ArrayClass * libraries
ArrayClass * requires
ArrayClass * classes
StringTable * resources
StringTable * unattachedMethods
StringTable * namespaces
ArrayClass * loadedPackages
StringTable * installedPublicClasses
StringTable * installedClasses
StringTable * mergedPublicClasses
StringTable * mergedPublicRoutines
StringTable * annotations
bool installRequired
PackageSetting packageSettings
DirectoryClass * packageLocal
intptr_t reserved [11]
Friends
class LanguageParser
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
An object that represents the source context for a Method or Routine object.
Definition at line 64 of file PackageClass.hpp.
Constructor & Destructor Documentation
PackageClass() [1/2]
PackageClass::PackageClass (RexxString * p, ProgramSource * s)
Initialize a Package instance.
Parameters
p The name of the program we're about to create.
s The appropriate ProgramSource object that represents the program.
Definition at line 128 of file PackageClass.cpp.
References DefaultLanguageLevel.
PackageClass() [2/2]
PackageClass::PackageClass (RESTORETYPE restoreType) inline
Definition at line 71 of file PackageClass.hpp.
Member Function Documentation
addClassRexx()
RexxObject * PackageClass::addClassRexx (RexxString * name, RexxClass * clazz)
Add a class to this package's class list.
Parameters
clazz The class to add.
Returns
The target package object.
Definition at line 1915 of file PackageClass.cpp.
References classArgument(), stringArgument(), and TheClassClass.
Referenced by MemoryObject::createImage().
addInstalledClass()
void PackageClass::addInstalledClass (RexxString * name, RexxClass * classObject, bool publicClass)
Add an installed class to this source package
Parameters
name The class name
classObject The class object
publicClass Indicates whether this needs to be added to the public list as well.
Definition at line 1390 of file PackageClass.cpp.
References new_string_table(), OREF_NULL, and setField.
Referenced by ClassDirective::install().
addInstalledRoutine()
void PackageClass::addInstalledRoutine (RexxString * name, RoutineClass * routineObject, bool publicRoutine)
Add an installed routine to this source package
Parameters
name The routine name
classObject The routine object
publicClass Indicates whether this needs to be added to the public list as well.
Definition at line 1421 of file PackageClass.cpp.
References new_string_table(), OREF_NULL, and setField.
addNamespace()
void PackageClass::addNamespace (RexxString * name, PackageClass * package)
add a namespace to this package.
Parameters
name The name of the namespace.
package The namespace package.
Definition at line 2142 of file PackageClass.cpp.
References new_string_table(), OREF_NULL, InstallingPackage::package, setField, and RexxString::upper().
Referenced by RequiresDirective::install().
addPackage()
void PackageClass::addPackage (PackageClass * p)
Add a package to a source file context. This allows new packages to be imported into a source.
Parameters
p
Definition at line 1356 of file PackageClass.cpp.
References new_array(), and OREF_NULL.
addPackageRexx()
RexxObject * PackageClass::addPackageRexx (PackageClass * package, RexxString * namespaceName)
Load a package in a source context.
Parameters
name The target package name.
Returns
The loaded package object.
Definition at line 1857 of file PackageClass.cpp.
References classArgument(), optionalStringArgument(), OREF_NULL, InstallingPackage::package, and ThePackageClass.
Referenced by MemoryObject::createImage().
addPublicClassRexx()
RexxObject * PackageClass::addPublicClassRexx (RexxString * name, RexxClass * clazz)
Add a class to this package's public class list.
Parameters
clazz The class to add.
Returns
The target package object.
Definition at line 1933 of file PackageClass.cpp.
References classArgument(), stringArgument(), and TheClassClass.
Referenced by MemoryObject::createImage().
addPublicRoutineRexx()
RexxObject * PackageClass::addPublicRoutineRexx (RexxString * name, RoutineClass * routine)
Add a routine to this package's public routine list.
Parameters
routine The routine to add.
Returns
The target package object.
Definition at line 1897 of file PackageClass.cpp.
References classArgument(), stringArgument(), and TheRoutineClass.
Referenced by MemoryObject::createImage().
addRoutineRexx()
RexxObject * PackageClass::addRoutineRexx (RexxString * name, RoutineClass * routine)
Add a routine to this package's private routine list.
Parameters
routine The routine to add.
Returns
The target package object.
Definition at line 1879 of file PackageClass.cpp.
References classArgument(), stringArgument(), and TheRoutineClass.
Referenced by MemoryObject::createImage().
attachSource() [1/2]
void PackageClass::attachSource (BufferClass * s)
Attach a buffered source object to a source that has been saved in sourceless form. Normally used for instore RexxStart calls.
Parameters
s The Buffer with the source code in original form.
Definition at line 1450 of file PackageClass.cpp.
Referenced by BaseCode::attachSource().
attachSource() [2/2]
void PackageClass::attachSource (ProgramSource * s)
Reconnect this package to a source object.
Parameters
s The source object.
Definition at line 1482 of file PackageClass.cpp.
checkRexxPackage()
void PackageClass::checkRexxPackage ()
Check for an invalid attempt to make additions to the REXX package.
Definition at line 459 of file PackageClass.cpp.
References Error_Execution_rexx_package_update, and reportException().
copy()
RexxInternalObject * PackageClass::copy () override virtual
Override for a copy operation on a Package object.
Returns
A new package object.
Reimplemented from RexxInternalObject.
Definition at line 351 of file PackageClass.cpp.
References RexxObject::copy().
createInstance()
void PackageClass::createInstance () static
Create initial class object at bootstrap time.
Definition at line 102 of file PackageClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
deepCopy()
void PackageClass::deepCopy ()
Perform a deep copy on a Package object.
Definition at line 365 of file PackageClass.cpp.
References OREF_NULL.
detachSource()
ProgramSource * PackageClass::detachSource ()
Convert this package to a sourceless form.
Returns
The current source object.
Definition at line 1464 of file PackageClass.cpp.
Referenced by BaseCode::detachSource().
digitsRexx()
RexxObject * PackageClass::digitsRexx ()
Return the package-defined digits setting
Returns
The digits setting defined for this package.
Definition at line 2058 of file PackageClass.cpp.
References new_integer().
Referenced by MemoryObject::createImage().
disableErrorSyntax()
void PackageClass::disableErrorSyntax () inline
Definition at line 170 of file PackageClass.hpp.
References PackageSetting::disableErrorSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
disableFailureSyntax()
void PackageClass::disableFailureSyntax () inline
Definition at line 172 of file PackageClass.hpp.
References PackageSetting::disableFailureSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
disableLostdigitsSyntax()
void PackageClass::disableLostdigitsSyntax () inline
Definition at line 174 of file PackageClass.hpp.
References PackageSetting::disableLostdigitsSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
disableNostringSyntax()
void PackageClass::disableNostringSyntax () inline
Definition at line 178 of file PackageClass.hpp.
References PackageSetting::disableNostringSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
disableNotreadySyntax()
void PackageClass::disableNotreadySyntax () inline
Definition at line 176 of file PackageClass.hpp.
References PackageSetting::disableNotreadySyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
disableNovalueSyntax()
void PackageClass::disableNovalueSyntax () inline
Definition at line 180 of file PackageClass.hpp.
References PackageSetting::disableNovalueSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
disableProlog()
void PackageClass::disableProlog () inline
Definition at line 182 of file PackageClass.hpp.
References PackageSetting::disableProlog(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
enableErrorSyntax()
void PackageClass::enableErrorSyntax () inline
Definition at line 169 of file PackageClass.hpp.
References PackageSetting::enableErrorSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
enableFailureSyntax()
void PackageClass::enableFailureSyntax () inline
Definition at line 171 of file PackageClass.hpp.
References PackageSetting::enableFailureSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
enableLostdigitsSyntax()
void PackageClass::enableLostdigitsSyntax () inline
Definition at line 173 of file PackageClass.hpp.
References PackageSetting::enableLostdigitsSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
enableNostringSyntax()
void PackageClass::enableNostringSyntax () inline
Definition at line 177 of file PackageClass.hpp.
References PackageSetting::enableNostringSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
enableNotreadySyntax()
void PackageClass::enableNotreadySyntax () inline
Definition at line 175 of file PackageClass.hpp.
References PackageSetting::enableNotreadySyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
enableNovalueSyntax()
void PackageClass::enableNovalueSyntax () inline
Definition at line 179 of file PackageClass.hpp.
References PackageSetting::enableNovalueSyntax(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
enableProlog()
void PackageClass::enableProlog () inline
Definition at line 181 of file PackageClass.hpp.
References PackageSetting::enableProlog(), and packageSettings.
Referenced by LanguageParser::optionsDirective().
extract()
RexxString* PackageClass::extract (SourceLocation &)
Referenced by RexxCode::extract().
extractNameInformation()
void PackageClass::extractNameInformation ()
Extract various bits of the source name to give us directory, extension and file portions to be used for searches for additional files.
Definition at line 411 of file PackageClass.cpp.
References SysFileSystem::extractDirectory(), SysFileSystem::extractExtension(), SysFileSystem::extractFile(), OREF_NULL, and setField.
extractSource() [1/2]
ArrayClass * PackageClass::extractSource ()
Extract all of the source from the package.
Returns
An array of the source lines.
Definition at line 632 of file PackageClass.cpp.
References SourceLocation::setEndLine(), SourceLocation::setLineNumber(), and SourceLocation::setOffset().
Referenced by getSourceRexx().
extractSource() [2/2]
ArrayClass * PackageClass::extractSource (SourceLocation & location)
Extract a range of source lines as defined by the location marker.
Parameters
location The location giving the start and end locations to extract.
Returns
An array of all lines (or partial lines), defined by the extract.
Definition at line 655 of file PackageClass.cpp.
Referenced by RexxCode::getSource().
findClass() [1/3]
RexxClass * PackageClass::findClass (RexxString * className, RexxObject *& cachedValue)
Resolve a class from this source file context (including any chained parent contexts).
Parameters
className The target name of the class.
cachedValue If the returned value is resolved from the package context, we also return the value via this argument to indicate that the value can be cached in a dot variable expression object.
Returns
The resolved class object, if any.
Definition at line 1070 of file PackageClass.cpp.
References ActivityManager::getLocalEnvironment(), OREF_NULL, TheEnvironment, TheRexxPackage, and RexxString::upper().
Referenced by BaseCode::findClass(), findClass(), RexxActivation::findClass(), ClassResolver::lookup(), and RexxActivation::resolveDotVariable().
findClass() [2/3]
RexxClass * PackageClass::findClass (RexxString * namespaceName, RexxString * className)
Resolve a class from this source file context, with a potential namespace.
Parameters
namespaceName The potential namespace qualifier.
className The target name of the class.
Returns
The resolved class object.
Definition at line 1165 of file PackageClass.cpp.
References findPublicClass(), OREF_NULL, and RexxString::upper().
findClass() [3/3]
RexxClass* PackageClass::findClass (RexxString * n) inline
Definition at line 103 of file PackageClass.hpp.
References findClass().
findClassRexx()
RexxObject * PackageClass::findClassRexx (RexxString * name)
Resolve a class in the context of a package.
Parameters
name The required class name.
Returns
The resolved class object.
Definition at line 1951 of file PackageClass.cpp.
References OREF_NULL, resultOrNil(), and stringArgument().
Referenced by MemoryObject::createImage().
findInstalledClass()
RexxClass * PackageClass::findInstalledClass (RexxString * name)
Resolve a directly defined class object in this or a parent context.
Parameters
name The name we're searching for (all uppercase).
Returns
A resolved class object, if found.
Definition at line 971 of file PackageClass.cpp.
References OREF_NULL.
findLocalRoutine()
RoutineClass * PackageClass::findLocalRoutine (RexxString * name)
Resolve a directly defined class object in this or a parent context.
Parameters
name The name we're searching for (all uppercase).
Returns
A resolved class object, if found.
Definition at line 811 of file PackageClass.cpp.
References OREF_NULL.
findNamespace()
PackageClass * PackageClass::findNamespace (RexxString * name)
Resolve a directly defined routine object in this or a parent context.
Parameters
name The name we're searching for (all uppercase).
Returns
A resolved routine object, if found.
Definition at line 773 of file PackageClass.cpp.
References findNamespace(), OREF_NULL, RexxString::strCompare(), and TheRexxPackage.
Referenced by QualifiedFunction::evaluate(), RexxInstructionQualifiedCall::execute(), findNamespace(), and ClassResolver::lookup().
findNamespaceRexx()
RexxObject * PackageClass::findNamespaceRexx (RexxString * name)
Resolve a namespace in the context of a package.
Parameters
name The required class name.
Returns
The resolved class object.
Definition at line 1982 of file PackageClass.cpp.
References resultOrNil(), stringArgument(), and RexxString::upper().
Referenced by MemoryObject::createImage().
findProgramRexx()
RexxObject * PackageClass::findProgramRexx (RexxObject * name)
Locate a program using the target package context.
Parameters
name The target name.
Returns
The fully resolved filename, or .nil if no file was found.
Definition at line 935 of file PackageClass.cpp.
References InstallingPackage::activity, ActivityManager::currentActivity, Activity::getInstance(), OREF_NULL, RESOLVE_DEFAULT, InterpreterInstance::resolveProgramName(), stringArgument(), and TheNilObject.
Referenced by MemoryObject::createImage().
findPublicClass()
RexxClass * PackageClass::findPublicClass (RexxString * name)
Find a public class that we might have inherited from our included packages.
Parameters
name The target class name.
Returns
A resolved class object, or OREF_NULL if this cannot be found.
Definition at line 1003 of file PackageClass.cpp.
References OREF_NULL, and TheRexxPackage.
Referenced by findClass(), and ClassResolver::lookup().
findPublicClassRexx()
RexxObject * PackageClass::findPublicClassRexx (RexxString * name)
Resolve a public class in the context of a package.
Parameters
name The required class name.
Returns
The resolved class object.
Definition at line 1968 of file PackageClass.cpp.
References resultOrNil(), stringArgument(), and RexxString::upper().
Referenced by MemoryObject::createImage().
findPublicRoutine()
RoutineClass * PackageClass::findPublicRoutine (RexxString * name)
Resolve a public routine in this source context
Parameters
name The target name.
Returns
A resolved Routine object, if found.
Definition at line 841 of file PackageClass.cpp.
References OREF_NULL.
findPublicRoutineRexx()
RexxObject * PackageClass::findPublicRoutineRexx (RexxString * name)
Resolve a public routine in the context of a package.
Parameters
name The required routine name.
Returns
The resolved routine object.
Definition at line 2010 of file PackageClass.cpp.
References resultOrNil(), and stringArgument().
Referenced by MemoryObject::createImage().
findRoutine()
RoutineClass * PackageClass::findRoutine (RexxString * routineName)
Resolve a routine from this source files base context.
Parameters
routineName The routine name of interest.
Returns
A RoutineClass instance if located. Returns OREF_NULL if this is not known at this level.
Definition at line 886 of file PackageClass.cpp.
References OREF_NULL, and RexxString::upper().
Referenced by RexxCode::findRoutine().
findRoutineRexx()
RexxObject * PackageClass::findRoutineRexx (RexxString * name)
Resolve a routine in the context of a package.
Parameters
name The required routine name.
Returns
The resolved routine object.
Definition at line 1996 of file PackageClass.cpp.
References resultOrNil(), stringArgument(), and RexxString::upper().
Referenced by MemoryObject::createImage().
flatten()
void PackageClass::flatten (Envelope * envelope) override virtual
Flatten a source object.
Parameters
envelope The envelope that will hold the flattened object.
Reimplemented from RexxVirtualBase.
Definition at line 311 of file PackageClass.cpp.
References cleanUpFlatten, flattenRef, OREF_NULL, and setUpFlatten.
formRexx()
RexxObject * PackageClass::formRexx ()
Return the package-defined default form setting.
Returns
The default form setting.
Definition at line 2080 of file PackageClass.cpp.
References Numerics::FORM_SCIENTIFIC.
Referenced by MemoryObject::createImage().
fuzzRexx()
RexxObject * PackageClass::fuzzRexx ()
Return the package-defined default fuzz setting.
Returns
The package defined fuzz setting.
Definition at line 2069 of file PackageClass.cpp.
References new_integer().
Referenced by MemoryObject::createImage().
getAnnotation()
RexxString * PackageClass::getAnnotation (RexxString * name)
Get a specific named annotation.
Parameters
name The annotation name
Returns
The annotation value, or OREF_NULL if it doesn't exist.
Definition at line 1780 of file PackageClass.cpp.
References OREF_NULL.
getAnnotationRexx()
RexxObject * PackageClass::getAnnotationRexx (RexxObject * name)
The Rexx stub for the get annotation method
Parameters
name The name of the target annotation.
Returns
The annotation value, or .nil if it does not exist.
Definition at line 1797 of file PackageClass.cpp.
References resultOrNil(), and stringArgument().
Referenced by MemoryObject::createImage().
getAnnotations()
StringTable * PackageClass::getAnnotations ()
Get all of the information encoded for this package.
Returns
A directory of the defined package annotations
Definition at line 1757 of file PackageClass.cpp.
References new_string_table(), OREF_NULL, and setField.
Referenced by LanguageParser::annotateDirective(), and MemoryObject::createImage().
getClassesRexx()
StringTable * PackageClass::getClassesRexx ()
Retrieve all classes defined by this package.
Returns
A directory of all of the classes defined by this package.
Definition at line 1531 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getDefinedMethods()
StringTable* PackageClass::getDefinedMethods () inline
Definition at line 150 of file PackageClass.hpp.
References install(), and unattachedMethods.
getDigits()
wholenumber_t PackageClass::getDigits () inline
Definition at line 158 of file PackageClass.hpp.
References PackageSetting::getDigits(), and packageSettings.
Referenced by RexxInstructionNumeric::execute(), and LanguageParser::optionsDirective().
getForm()
bool PackageClass::getForm () inline
Definition at line 160 of file PackageClass.hpp.
References PackageSetting::getForm(), and packageSettings.
Referenced by RexxInstructionNumeric::execute().
getFuzz()
wholenumber_t PackageClass::getFuzz () inline
Definition at line 162 of file PackageClass.hpp.
References PackageSetting::getFuzz(), and packageSettings.
Referenced by RexxInstructionNumeric::execute(), and LanguageParser::optionsDirective().
getImportedClasses()
StringTable* PackageClass::getImportedClasses () inline
Definition at line 146 of file PackageClass.hpp.
References install(), and mergedPublicClasses.
getImportedClassesRexx()
StringTable * PackageClass::getImportedClassesRexx ()
Retrieve all of the classes imported into this package from other packages.
Returns
A directory of the imported classes.
Definition at line 1574 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getImportedPackagesRexx()
ArrayClass * PackageClass::getImportedPackagesRexx ()
Get all of the packages that have been added to this package context.
Returns
An array of the added packages.
Definition at line 1809 of file PackageClass.cpp.
References ArrayClass::copy(), new_array(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getImportedRoutines()
StringTable* PackageClass::getImportedRoutines () inline
Definition at line 149 of file PackageClass.hpp.
References install(), and mergedPublicRoutines.
getImportedRoutinesRexx()
StringTable * PackageClass::getImportedRoutinesRexx ()
Get the directory of routines that have been imported into to this package form other packages.
Returns
A directory of the imported routines.
Definition at line 1640 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getInstalledClasses()
StringTable* PackageClass::getInstalledClasses () inline
Definition at line 144 of file PackageClass.hpp.
References install(), and installedClasses.
getInstalledPublicClasses()
StringTable* PackageClass::getInstalledPublicClasses () inline
Definition at line 145 of file PackageClass.hpp.
References install(), and installedPublicClasses.
getInstalledPublicRoutines()
StringTable* PackageClass::getInstalledPublicRoutines () inline
Definition at line 148 of file PackageClass.hpp.
References install(), and publicRoutines.
getInstalledRoutines()
StringTable* PackageClass::getInstalledRoutines () inline
Definition at line 147 of file PackageClass.hpp.
References install(), and routines.
getLanguageLevel()
LanguageLevel PackageClass::getLanguageLevel () inline
Definition at line 168 of file PackageClass.hpp.
References requiredLanguageLevel.
Referenced by RoutineClass::getLanguageLevel(), and LanguageParser::requireLanguageLevel().
getLine()
RexxString * PackageClass::getLine (size_t position)
Get a line from the current source. Returns this as a String object (used for Sourcelines()).
Parameters
_position The target source line.
Returns
The string version of the source line. Returns OREF_NULL if the line is not available.
Definition at line 504 of file PackageClass.cpp.
getLocalRoutines()
StringTable* PackageClass::getLocalRoutines () inline
Definition at line 136 of file PackageClass.hpp.
References routines.
Referenced by RexxCode::getLocalRoutines().
getMain()
RoutineClass* PackageClass::getMain () inline
Definition at line 184 of file PackageClass.hpp.
References mainExecutable.
getMainRexx()
RexxObject * PackageClass::getMainRexx ()
Return the main executable for a package. Returns .nil if the package was created as a new method or a new routine.
Returns
The main section of the package or .nil if there is no main section
Definition at line 2104 of file PackageClass.cpp.
References OREF_NULL, resultOrNil(), and TheNilObject.
Referenced by MemoryObject::createImage().
getMethods()
StringTable* PackageClass::getMethods () inline
Definition at line 128 of file PackageClass.hpp.
References unattachedMethods.
Referenced by RexxCode::getMethods().
getMethodsRexx()
StringTable * PackageClass::getMethodsRexx ()
Get all of the unattached methods defined in this package.
Returns
A directory of the unattached methods.
Definition at line 1661 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getNamespaceRexx()
PackageClass* PackageClass::getNamespaceRexx ()
getNamespaces()
StringTable* PackageClass::getNamespaces () inline
Definition at line 153 of file PackageClass.hpp.
References install(), and namespaces.
getNamespacesRexx()
StringTable * PackageClass::getNamespacesRexx ()
Get all of the namespaces defined in this package.
Returns
A directory of the defined namespaces
Definition at line 1736 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getPackageLocal()
DirectoryClass * PackageClass::getPackageLocal ()
Retrieve the package local directory for this package.
Returns
A mutable directory object associated with this package.
Definition at line 2159 of file PackageClass.cpp.
References new_directory(), OREF_NULL, and setField.
Referenced by MemoryObject::createImage().
getPackages()
ArrayClass* PackageClass::getPackages () inline
Definition at line 151 of file PackageClass.hpp.
References install(), and loadedPackages.
getProgramDirectory()
RexxString* PackageClass::getProgramDirectory () inline
Definition at line 125 of file PackageClass.hpp.
References programDirectory.
getProgramExtension()
RexxString* PackageClass::getProgramExtension () inline
Definition at line 126 of file PackageClass.hpp.
References programExtension.
getProgramFile()
RexxString* PackageClass::getProgramFile () inline
Definition at line 127 of file PackageClass.hpp.
References programFile.
getProgramName()
RexxString* PackageClass::getProgramName () inline
Definition at line 124 of file PackageClass.hpp.
References programName.
Referenced by MemoryObject::createImage(), RexxCode::getProgramName(), ClassResolver::lookup(), RexxActivation::traceEntryOrExit(), and LanguageParser::translateInterpret().
getPublicClassesRexx()
StringTable * PackageClass::getPublicClassesRexx ()
Retrieve all public classes defined by this package.
Returns
A directory of the public classes.
Definition at line 1552 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getPublicRoutines()
StringTable* PackageClass::getPublicRoutines () inline
Definition at line 137 of file PackageClass.hpp.
References publicRoutines.
Referenced by RexxCode::getPublicRoutines().
getPublicRoutinesRexx()
StringTable * PackageClass::getPublicRoutinesRexx ()
Return a directory of the Public routines defined by this package.
Returns
A directory holding the public routines.
Definition at line 1618 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getResource()
ArrayClass * PackageClass::getResource (RexxString * name)
Get a specific named resource
Parameters
name The resource name
Returns
The resource array, or OREF_NULL if it doesn't exist.
Definition at line 1705 of file PackageClass.cpp.
References StringHashCollection::entry(), and OREF_NULL.
getResourceRexx()
RexxObject * PackageClass::getResourceRexx (RexxObject * name)
The Rexx stub for the get resource method
Parameters
name The name of the target resource.
Returns
The resource value, or .nil if it does not exist.
Definition at line 1725 of file PackageClass.cpp.
References resultOrNil(), and stringArgument().
Referenced by MemoryObject::createImage().
getResources()
StringTable* PackageClass::getResources () inline
Definition at line 152 of file PackageClass.hpp.
References install(), and resources.
Referenced by RexxCode::getResources().
getResourcesRexx()
StringTable * PackageClass::getResourcesRexx ()
Get all of the resources defined in this package.
Returns
A directory of the defined resources
Definition at line 1682 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getRoutines()
StringTable* PackageClass::getRoutines () inline
Definition at line 129 of file PackageClass.hpp.
References routines.
Referenced by RexxCode::getRoutines().
getRoutinesRexx()
StringTable * PackageClass::getRoutinesRexx ()
Get a list of all routines defined by this package.
Returns
A directory of the routines.
Definition at line 1595 of file PackageClass.cpp.
References HashCollection::copy(), new_string_table(), and OREF_NULL.
Referenced by MemoryObject::createImage().
getSecurityManager()
SecurityManager* PackageClass::getSecurityManager () inline
Definition at line 134 of file PackageClass.hpp.
References securityManager.
Referenced by NativeCode::getSecurityManager(), RexxCode::getSecurityManager(), and NativeActivation::getSecurityManager().
getSettings()
const PackageSetting& PackageClass::getSettings () inline
Definition at line 165 of file PackageClass.hpp.
References packageSettings.
Referenced by RexxActivation::inheritPackageSettings().
getSourceLineRexx()
RexxString * PackageClass::getSourceLineRexx (RexxObject * position)
Extract a specific line from the program source.
Parameters
n The line position.
Returns
The extracted line.
Definition at line 1507 of file PackageClass.cpp.
References ARG_ONE, and positionArgument().
Referenced by MemoryObject::createImage().
getSourceRexx()
ArrayClass* PackageClass::getSourceRexx () inline
Definition at line 222 of file PackageClass.hpp.
References extractSource().
Referenced by MemoryObject::createImage().
getSourceSizeRexx()
RexxInteger * PackageClass::getSourceSizeRexx ()
Get the number of source lines in the package
Returns
the count of lines
Definition at line 1520 of file PackageClass.cpp.
References new_integer().
Referenced by MemoryObject::createImage().
getTrace()
RexxString * PackageClass::getTrace ()
Return the full default trace setting for this package.
Returns
The current trace setting formatted into readable form.
Definition at line 1493 of file PackageClass.cpp.
getTraceSetting()
const TraceSetting& PackageClass::getTraceSetting () inline
Definition at line 164 of file PackageClass.hpp.
References PackageSetting::getTraceSetting(), and packageSettings.
inheritPackageContext()
void PackageClass::inheritPackageContext (PackageClass * parent)
Merge a parent source context into our context so all of the bits that are visible in the parent are also resolvable in our context. This is mostly used for dynamically created methods.
Parameters
parent The parent source context.
Definition at line 669 of file PackageClass.cpp.
References setField.
Referenced by LanguageParser::generateMethod(), LanguageParser::generatePackage(), LanguageParser::generateProgram(), LanguageParser::generateRoutine(), and LanguageParser::translateInterpret().
install() [1/2]
void PackageClass::install ()
Perform a non-contextual install of a package. This processes the install without calling any leading code section.
Definition at line 1195 of file PackageClass.cpp.
References ActivityManager::currentActivity, and OREF_NULL.
Referenced by getDefinedMethods(), getImportedClasses(), getImportedRoutines(), getInstalledClasses(), getInstalledPublicClasses(), getInstalledPublicRoutines(), getInstalledRoutines(), getNamespaces(), getPackages(), getResources(), RexxCode::install(), and LanguageParser::installPackage().
install() [2/2]
void PackageClass::install (RexxActivation * activation) inline
Definition at line 122 of file PackageClass.hpp.
References needsInstallation(), and processInstall().
isInternalCode()
bool PackageClass::isInternalCode () inline
Definition at line 131 of file PackageClass.hpp.
References RexxInternalObject::isOldSpace().
isPrologEnabled()
bool PackageClass::isPrologEnabled () inline
Definition at line 183 of file PackageClass.hpp.
References initCode, PackageSetting::isPrologEnabled(), OREF_NULL, and packageSettings.
isRexxPackage()
bool PackageClass::isRexxPackage () inline
Definition at line 166 of file PackageClass.hpp.
References TheRexxPackage.
isTraceable()
bool PackageClass::isTraceable ()
Test if the current source context is traceable.
Returns
True if the program has source available, false otherwise.
Definition at line 488 of file PackageClass.cpp.
Referenced by RexxCode::isTraceable().
live()
void PackageClass::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 233 of file PackageClass.cpp.
References memory_mark.
liveGeneral()
void PackageClass::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 270 of file PackageClass.cpp.
References memory_mark_general, and PREPARINGIMAGE.
loadLibraryRexx()
RexxObject * PackageClass::loadLibraryRexx (RexxString * name)
Dynamically load a library package
Parameters
name The required package name.
Returns
True if the package was loaded and resolved, false if the package could not be loaded.
Definition at line 2041 of file PackageClass.cpp.
References booleanObject(), InstallingPackage::package, and stringArgument().
Referenced by MemoryObject::createImage().
loadPackageRexx()
PackageClass * PackageClass::loadPackageRexx (RexxString * name, ArrayClass * s)
Load a package in a source context.
Parameters
name The target package name.
s The optional source lines for the package, as an array.
Returns
The loaded package object.
Definition at line 1831 of file PackageClass.cpp.
References arrayArgument(), ActivityManager::currentActivity, OREF_NULL, RESOLVE_REQUIRES, and stringArgument().
Referenced by MemoryObject::createImage().
loadRequires() [1/2]
PackageClass * PackageClass::loadRequires (Activity * activity, RexxString * target, ArrayClass * s)
Load a ::REQUIRES directive from a provided source target
Parameters
target The name of the ::REQUIRES
s An array of source lines
Definition at line 1331 of file PackageClass.cpp.
References InstallingPackage::activity, Error_Routine_not_found_requires, Activity::getInstance(), InterpreterInstance::loadRequires(), OREF_NULL, and reportException().
loadRequires() [2/2]
PackageClass * PackageClass::loadRequires (Activity * activity, RexxString * target, ResolveType type)
Load a ::REQUIRES directive when the source file is first invoked. This is also called from method loadPackage.
Parameters
target The name of the ::REQUIRES
type The resolve type, RESOLVE_DEFAULT or RESOLVE_REQUIRES
Definition at line 1301 of file PackageClass.cpp.
References InstallingPackage::activity, Error_Routine_not_found_requires, Activity::getInstance(), InterpreterInstance::loadRequires(), OREF_NULL, reportException(), and type.
Referenced by RequiresDirective::install().
mergeLibrary()
void PackageClass::mergeLibrary (LibraryPackage * mergeSource)
Merge the routine information from loaded libraries to our imported routines list
Parameters
source The source object we're merging from.
Definition at line 745 of file PackageClass.cpp.
References LibraryPackage::getRoutines(), HashCollection::merge(), new_string_table(), OREF_NULL, and setField.
Referenced by RexxActivation::loadLibrary().
mergeRequired()
void PackageClass::mergeRequired (PackageClass * mergeSource)
Merge all of the information from inherited packages into this lookup context.
Parameters
source The source object we're merging from.
Definition at line 682 of file PackageClass.cpp.
References installedPublicClasses, HashCollection::merge(), mergedPublicClasses, mergedPublicRoutines, new_string_table(), OREF_NULL, publicRoutines, and setField.
Referenced by RexxActivation::callMacroSpaceFunction(), and RexxCode::mergeRequired().
needsInstallation()
bool PackageClass::needsInstallation () inline
Definition at line 120 of file PackageClass.hpp.
References installRequired.
Referenced by install().
newRexx()
PackageClass * PackageClass::newRexx (RexxObject ** init_args, size_t argCount)
Create a new package from code contained in a file or array.
Parameters
init_args The pointer to the new arguments.
argCount The count of arguments.
Returns
A new package object.
Definition at line 147 of file PackageClass.cpp.
References InstallingPackage::activity, RexxClass::completeNewObject(), ActivityManager::currentActivity, Error_Incorrect_method_argType, Error_Incorrect_method_no_method, Activity::getInstance(), IntegerThree, isOfClass, OREF_NULL, InstallingPackage::package, BaseExecutable::processExecutableSource(), RexxClass::processNewArgs(), reportException(), RESOLVE_REQUIRES, InterpreterInstance::resolveProgramName(), and stringArgument().
Referenced by MemoryObject::createImage().
operator new()
void * PackageClass::operator new (size_t size)
Allocate storage for a PackageClass instance.
Parameters
size The size of the object.
Returns
Object storage for a new instance.
Definition at line 115 of file PackageClass.cpp.
References new_object(), and T_Package.
processInstall()
void PackageClass::processInstall (RexxActivation * activation)
Process directive information contained within a method, calling all ::requires routines, creating all ::class objects, and loading all required libraries.
Parameters
activation
Definition at line 1216 of file PackageClass.cpp.
References ClassDirective::activate(), RexxActivation::getActivity(), ClassDirective::install(), LibraryDirective::install(), RequiresDirective::install(), new_string_table(), OREF_NULL, ClassDirective::resolveConstants(), and setField.
Referenced by install().
reconnect()
bool PackageClass::reconnect ()
resolveProgramName()
RexxString * PackageClass::resolveProgramName (Activity * activity, RexxString * name, ResolveType type)
Resolve an external call in the context of the program making the call. This will use the directory and extension of the context program to modify the search order.
Parameters
activity The current activity
name The target name
type The resolve type, RESOLVE_DEFAULT or RESOLVE_REQUIRES
Returns
The fully resolved string name of the target program, if one is located.
Definition at line 915 of file PackageClass.cpp.
References InstallingPackage::activity, OREF_NULL, Activity::resolveProgramName(), and type.
Referenced by RexxCode::resolveProgramName().
runProlog()
void PackageClass::runProlog (Activity * activity)
Install this package, including running of the prolog portion of the package if required.
Parameters
activity The activity we're running on
Definition at line 2117 of file PackageClass.cpp.
References InstallingPackage::activity, EXTERNALCALL, and OREF_NULL.
setDigits()
void PackageClass::setDigits (wholenumber_t d) inline
Definition at line 157 of file PackageClass.hpp.
References packageSettings, and PackageSetting::setDigits().
Referenced by LanguageParser::optionsDirective().
setForm()
void PackageClass::setForm (bool f) inline
Definition at line 159 of file PackageClass.hpp.
References packageSettings, and PackageSetting::setForm().
Referenced by LanguageParser::optionsDirective().
setFuzz()
void PackageClass::setFuzz (wholenumber_t f) inline
Definition at line 161 of file PackageClass.hpp.
References packageSettings, and PackageSetting::setFuzz().
Referenced by LanguageParser::optionsDirective().
setLanguageLevel()
void PackageClass::setLanguageLevel (LanguageLevel l) inline
Definition at line 167 of file PackageClass.hpp.
References requiredLanguageLevel.
Referenced by LanguageParser::requireLanguageLevel().
setLocalRoutines()
void PackageClass::setLocalRoutines (StringTable * r) inline
Definition at line 138 of file PackageClass.hpp.
References routines.
setNeedsInstallation()
void PackageClass::setNeedsInstallation () inline
Definition at line 121 of file PackageClass.hpp.
References installRequired.
Referenced by LanguageParser::resolveDependencies().
setProgramName()
void PackageClass::setProgramName (RexxString * name)
Set a program name for this source object. Usually used after a program restore to update the restored routine object. This will also update the extension and directory information.
Parameters
name The new program name.
Definition at line 447 of file PackageClass.cpp.
References setField.
setPublicRoutines()
void PackageClass::setPublicRoutines (StringTable * r) inline
Definition at line 139 of file PackageClass.hpp.
References publicRoutines.
setSecurityManager()
void PackageClass::setSecurityManager (RexxObject * manager) inline
Definition at line 133 of file PackageClass.hpp.
References securityManager, and setField.
Referenced by RexxCode::setSecurityManager().
setSecurityManagerRexx()
RexxObject * PackageClass::setSecurityManagerRexx (RexxObject * manager)
Set a security manager on a package.
Parameters
manager The security manager object.
Returns
The security manager object.
Definition at line 2024 of file PackageClass.cpp.
References TheTrueObject.
Referenced by MemoryObject::createImage().
setTraceSetting()
void PackageClass::setTraceSetting (const TraceSetting & s) inline
Definition at line 163 of file PackageClass.hpp.
References packageSettings, and PackageSetting::setTraceSetting().
Referenced by LanguageParser::optionsDirective().
setup()
void PackageClass::setup ()
Perform pre-parsing setup of the source object.
Definition at line 431 of file PackageClass.cpp.
Referenced by LanguageParser::initializeForParsing().
sourceSize()
size_t PackageClass::sourceSize ()
Return count of lines in the source. This could be zero if no source is available for this method.
Returns
The current source line count.
Definition at line 475 of file PackageClass.cpp.
Referenced by BUILTIN().
traceBack()
RexxString * PackageClass::traceBack (RexxActivation * activation, SourceLocation & location, size_t indent, bool trace)
Format a source line for tracing
Parameters
activation The activation of the current running code. This can be null if this is a translation time error.
location The source line location.
indent The indentation amount to apply to the trace line
trace This is a traced line vs. an error line
Returns
A formatted trace line, including headers and indentations.
Definition at line 550 of file PackageClass.cpp.
References Activity::buildMessage(), ActivityManager::currentActivity, RexxActivation::formatSourcelessTraceLine(), SourceLocation::getLineNumber(), INDENT_SPACING, INSTRUCTION_OVERHEAD, line, LINENUMBER, Message_Translations_internal_code, Message_Translations_no_source_available, new_array(), OREF_NULL, PREFIX_LENGTH, PREFIX_OFFSET, RexxString::put(), raw_string(), and RexxString::set().
Referenced by LanguageParser::createStackFrame(), and RexxActivation::formatTrace().
traceRexx()
RexxObject * PackageClass::traceRexx ()
Return the package-defined default trace setting.
Returns
The string-formatted trace setting.
Definition at line 2091 of file PackageClass.cpp.
Referenced by MemoryObject::createImage().
Friends And Related Function Documentation
LanguageParser
friend class LanguageParser friend
Definition at line 66 of file PackageClass.hpp.
Member Data Documentation
annotations
StringTable* PackageClass::annotations protected
Definition at line 263 of file PackageClass.hpp.
classes
ArrayClass* PackageClass::classes protected
Definition at line 249 of file PackageClass.hpp.
Referenced by LanguageParser::resolveDependencies().
classInstance
RexxClass * PackageClass::classInstance = OREF_NULL static
Definition at line 80 of file PackageClass.hpp.
initCode
RexxCode* PackageClass::initCode protected
Definition at line 239 of file PackageClass.hpp.
Referenced by LanguageParser::generateMethod(), LanguageParser::generatePackage(), LanguageParser::generateProgram(), LanguageParser::generateRoutine(), and isPrologEnabled().
installedClasses
StringTable* PackageClass::installedClasses protected
Definition at line 259 of file PackageClass.hpp.
Referenced by getInstalledClasses().
installedPublicClasses
StringTable* PackageClass::installedPublicClasses protected
Definition at line 258 of file PackageClass.hpp.
Referenced by getInstalledPublicClasses(), and mergeRequired().
installRequired
bool PackageClass::installRequired protected
Definition at line 265 of file PackageClass.hpp.
Referenced by needsInstallation(), and setNeedsInstallation().
libraries
ArrayClass* PackageClass::libraries protected
Definition at line 247 of file PackageClass.hpp.
Referenced by LanguageParser::resolveDependencies().
loadedPackages
ArrayClass* PackageClass::loadedPackages protected
Definition at line 256 of file PackageClass.hpp.
Referenced by getPackages().
mainExecutable
BaseExecutable* PackageClass::mainExecutable protected
Definition at line 240 of file PackageClass.hpp.
Referenced by LanguageParser::generateMethod(), LanguageParser::generatePackage(), LanguageParser::generateProgram(), LanguageParser::generateRoutine(), and getMain().
mergedPublicClasses
StringTable* PackageClass::mergedPublicClasses protected
Definition at line 260 of file PackageClass.hpp.
Referenced by getImportedClasses(), and mergeRequired().
mergedPublicRoutines
StringTable* PackageClass::mergedPublicRoutines protected
Definition at line 262 of file PackageClass.hpp.
Referenced by getImportedRoutines(), and mergeRequired().
namespaces
StringTable* PackageClass::namespaces protected
Definition at line 252 of file PackageClass.hpp.
Referenced by getNamespaces().
packageLocal
DirectoryClass* PackageClass::packageLocal protected
Definition at line 268 of file PackageClass.hpp.
packageSettings
PackageSetting PackageClass::packageSettings protected
Definition at line 267 of file PackageClass.hpp.
Referenced by disableErrorSyntax(), disableFailureSyntax(), disableLostdigitsSyntax(), disableNostringSyntax(), disableNotreadySyntax(), disableNovalueSyntax(), disableProlog(), enableErrorSyntax(), enableFailureSyntax(), enableLostdigitsSyntax(), enableNostringSyntax(), enableNotreadySyntax(), enableNovalueSyntax(), enableProlog(), getDigits(), getForm(), getFuzz(), getSettings(), getTraceSetting(), isPrologEnabled(), setDigits(), setForm(), setFuzz(), setTraceSetting(), and LanguageParser::translate().
parentPackage
PackageClass* PackageClass::parentPackage protected
Definition at line 241 of file PackageClass.hpp.
programDirectory
RexxString* PackageClass::programDirectory protected
Definition at line 234 of file PackageClass.hpp.
Referenced by getProgramDirectory().
programExtension
RexxString* PackageClass::programExtension protected
Definition at line 236 of file PackageClass.hpp.
Referenced by getProgramExtension().
programFile
RexxString* PackageClass::programFile protected
Definition at line 235 of file PackageClass.hpp.
Referenced by getProgramFile().
programName
RexxString* PackageClass::programName protected
Definition at line 233 of file PackageClass.hpp.
Referenced by LanguageParser::createStackFrame(), and getProgramName().
publicRoutines
StringTable* PackageClass::publicRoutines protected
Definition at line 246 of file PackageClass.hpp.
Referenced by getInstalledPublicRoutines(), getPublicRoutines(), mergeRequired(), LanguageParser::resolveDependencies(), and setPublicRoutines().
requiredLanguageLevel
LanguageLevel PackageClass::requiredLanguageLevel protected
Definition at line 231 of file PackageClass.hpp.
Referenced by getLanguageLevel(), and setLanguageLevel().
requires
ArrayClass* PackageClass::requires protected
Definition at line 248 of file PackageClass.hpp.
Referenced by LanguageParser::resolveDependencies().
reserved
intptr_t PackageClass::reserved[11] protected
Definition at line 271 of file PackageClass.hpp.
resources
StringTable* PackageClass::resources protected
Definition at line 250 of file PackageClass.hpp.
Referenced by getResources(), and LanguageParser::resolveDependencies().
routines
StringTable* PackageClass::routines protected
Definition at line 245 of file PackageClass.hpp.
Referenced by getInstalledRoutines(), getLocalRoutines(), getRoutines(), LanguageParser::resolveDependencies(), and setLocalRoutines().
securityManager
SecurityManager* PackageClass::securityManager protected
Definition at line 237 of file PackageClass.hpp.
Referenced by getSecurityManager(), and setSecurityManager().
source
ProgramSource* PackageClass::source protected
Definition at line 232 of file PackageClass.hpp.
unattachedMethods
StringTable* PackageClass::unattachedMethods protected
Definition at line 251 of file PackageClass.hpp.
Referenced by getDefinedMethods(), getMethods(), and LanguageParser::resolveDependencies().
The documentation for this class was generated from the following files:
PackageClass.hpp
PackageClass.cpp