ooRexx: RexxVariableReference Class Reference
RexxVariableReference Class Reference
#include <IndirectVariableReference.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
RexxVariableReference (RESTORETYPE restoreType)
RexxVariableReference (RexxVariableBase *)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
void drop (RexxActivation *) override
void expose (RexxActivation *, VariableDictionary *) override
void procedureExpose (RexxActivation *, RexxActivation *) override
ArrayClass * list (RexxActivation *)
Public Member Functions inherited from RexxVariableBase
RexxVariableBase ()
virtual bool exists (RexxActivation *)
virtual void set (RexxActivation *, RexxObject *)
virtual void set (VariableDictionary *, RexxObject *)
virtual void assign (RexxActivation *, RexxObject *)
virtual void drop (VariableDictionary *)
virtual void setGuard (RexxActivation *)
virtual void clearGuard (RexxActivation *)
virtual void setGuard (VariableDictionary *)
virtual void clearGuard (VariableDictionary *)
virtual void alias (RexxActivation *, RexxVariable *)
virtual VariableReference * getVariableReference (RexxActivation *)
virtual VariableReference * getVariableReference (VariableDictionary *)
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Protected Attributes
RexxVariableBase * variableObject
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 51 of file IndirectVariableReference.hpp.
Constructor & Destructor Documentation
RexxVariableReference() [1/2]
RexxVariableReference::RexxVariableReference (RESTORETYPE restoreType) inline
Definition at line 57 of file IndirectVariableReference.hpp.
RexxVariableReference() [2/2]
RexxVariableReference::RexxVariableReference (RexxVariableBase * variable)
Construct an indirect variable reference.
Parameters
variable The variable instance used for retrieval and sub operations.
Definition at line 73 of file IndirectVariableReference.cpp.
References variableObject.
Member Function Documentation
drop()
void RexxVariableReference::drop (RexxActivation * context) override virtual
Perform a drop operation using an indirect name.
Parameters
context The current execution context.
Reimplemented from RexxVariableBase.
Definition at line 177 of file IndirectVariableReference.cpp.
References RexxVariableBase::drop(), ArrayClass::get(), list(), and ArrayClass::size().
expose()
void RexxVariableReference::expose (RexxActivation * context, VariableDictionary * object_dictionary) override virtual
Expose a subsidiary list of variables.
Parameters
context The current execution context.
object_dictionary The source object scope variable dictionary.
Reimplemented from RexxVariableBase.
Definition at line 225 of file IndirectVariableReference.cpp.
References RexxVariableBase::expose(), ArrayClass::get(), list(), ArrayClass::size(), and variableObject.
flatten()
void RexxVariableReference::flatten (Envelope * envelope) override virtual
Flatten a source object.
Parameters
envelope The envelope that will hold the flattened object.
Reimplemented from RexxVirtualBase.
Definition at line 108 of file IndirectVariableReference.cpp.
References cleanUpFlatten, flattenRef, setUpFlatten, and variableObject.
list()
ArrayClass * RexxVariableReference::list (RexxActivation * context)
Parse a variable's string contents into an array of "good" variable retrievers.
Parameters
context The current execution context.
Returns
An array of variable retrievers.
Definition at line 126 of file IndirectVariableReference.cpp.
References Error_Invalid_variable_number, Error_Invalid_variable_period, Error_Symbol_expected_indirect, RexxInternalObject::evaluate(), ArrayClass::get(), RexxString::getChar(), RexxActivation::getStack(), VariableDictionary::getVariableRetriever(), OREF_NULL, ArrayClass::put(), reportException(), RexxInternalObject::requestString(), ArrayClass::size(), and variableObject.
Referenced by drop(), expose(), and procedureExpose().
live()
void RexxVariableReference::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 84 of file IndirectVariableReference.cpp.
References memory_mark, and variableObject.
liveGeneral()
void RexxVariableReference::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 97 of file IndirectVariableReference.cpp.
References memory_mark_general, and variableObject.
operator delete()
void RexxVariableReference::operator delete (void *) inline
Definition at line 55 of file IndirectVariableReference.hpp.
operator new()
void * RexxVariableReference::operator new (size_t size)
Allocate memory for a RexxVariableReference item.
Parameters
size The base object size.
Returns
Storage for creating a new variable instance.
Definition at line 61 of file IndirectVariableReference.cpp.
References new_object(), and T_IndirectVariableTerm.
procedureExpose()
void RexxVariableReference::procedureExpose (RexxActivation * context, RexxActivation * parent) override virtual
Expose a subsidiary list of variables.
Parameters
context The current execution context.
parent The parent execution context.
Reimplemented from RexxVariableBase.
Definition at line 199 of file IndirectVariableReference.cpp.
References ArrayClass::get(), list(), RexxVariableBase::procedureExpose(), ArrayClass::size(), and variableObject.
Member Data Documentation
variableObject
RexxVariableBase* RexxVariableReference::variableObject protected
Definition at line 73 of file IndirectVariableReference.hpp.
Referenced by expose(), flatten(), list(), live(), liveGeneral(), procedureExpose(), and RexxVariableReference().
The documentation for this class was generated from the following files:
IndirectVariableReference.hpp
IndirectVariableReference.cpp