ooRexx: ProtectedSet Class Reference
ProtectedSet Class Reference
#include <ProtectedObject.hpp>
Public Member Functions
ProtectedSet ()
ProtectedSet (Activity *a)
~ProtectedSet ()
void add (RexxInternalObject *)
Public Member Functions inherited from ProtectedObject
ProtectedObject ()
ProtectedObject (Activity *a)
ProtectedObject (RexxInternalObject *o)
ProtectedObject (RexxInternalObject *o, Activity *a)
~ProtectedObject ()
void mark (size_t liveMark) override
void markGeneral (int reason) override
ProtectedBase & operator= (RexxInternalObject *o)
bool operator== (RexxInternalObject *o)
bool operator!= (RexxInternalObject *o)
operator RexxObject * ()
operator RexxInternalObject * ()
operator RexxObjectPtr ()
operator RexxString * ()
operator MethodClass * ()
operator ArrayClass * ()
operator RexxClass * ()
operator RexxInstruction * ()
operator void * ()
bool isNull ()
RexxObject * operator-> ()
Public Member Functions inherited from ProtectedBase
ProtectedBase ()
ProtectedBase (Activity *a)
~ProtectedBase ()
Additional Inherited Members
Protected Attributes inherited from ProtectedObject
RexxInternalObject * protectedObject
Protected Attributes inherited from ProtectedBase
ProtectedBase * next
Activity * activity
Detailed Description
A single proctected object that can protect multiple object instances. Useful for situations where there are a variable number of things that require protecting.
Definition at line 168 of file ProtectedObject.hpp.
Constructor & Destructor Documentation
ProtectedSet() [1/2]
ProtectedSet::ProtectedSet () inline
Definition at line 171 of file ProtectedObject.hpp.
ProtectedSet() [2/2]
ProtectedSet::ProtectedSet (Activity * a) inline
Definition at line 172 of file ProtectedObject.hpp.
~ProtectedSet()
ProtectedSet::~ProtectedSet () inline
Definition at line 173 of file ProtectedObject.hpp.
Member Function Documentation
add()
void ProtectedSet::add (RexxInternalObject * o)
Add an object to a protected set.
Parameters
o The new object.
Definition at line 113 of file ProtectedObject.cpp.
References ArrayClass::append(), new_array(), OREF_NULL, and ProtectedObject::protectedObject.
Referenced by RexxStartDispatcher::run().
The documentation for this class was generated from the following files:
ProtectedObject.hpp
ProtectedObject.cpp