ooRexx: NativeActivation Class Reference
NativeActivation Class Reference
#include <NativeActivation.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
NativeActivation (RESTORETYPE restoreType)
NativeActivation ()
NativeActivation (Activity *_activity, RexxActivation *_activation)
NativeActivation (Activity *_activity)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void run (MethodClass *_method, NativeMethod *_code, RexxObject *_receiver, RexxString *_msgname, RexxObject **_arglist, size_t _argcount, ProtectedObject &resultObj)
RexxObject * dispatch () override
wholenumber_t digits () override
wholenumber_t fuzz () override
bool form () override
void setDigits (wholenumber_t) override
void setFuzz (wholenumber_t) override
void setForm (bool) override
bool trap (RexxString *, DirectoryClass *) override
bool willTrap (RexxString *) override
void termination () override
bool isStackBase () override
RexxActivation * getRexxContext () override
RexxActivation * findRexxContext () override
RexxObject * getReceiver () override
PackageClass * getPackage () override
RexxObject * getContextObject ()
SecurityManager * getSecurityManager () override
const NumericSettings * getNumericSettings () override
MethodClass * getMethod ()
void run (ActivityDispatcher &dispatcher)
void run (CallbackDispatcher &dispatcher)
void run (TrappingDispatcher &dispatcher)
VariableDictionary * methodVariables ()
wholenumber_t signedIntegerValue (RexxObject *o, size_t position, wholenumber_t maxValue, wholenumber_t minValue)
wholenumber_t positiveWholeNumberValue (RexxObject *o, size_t position)
wholenumber_t nonnegativeWholeNumberValue (RexxObject *o, size_t position)
stringsize_t unsignedIntegerValue (RexxObject *o, size_t position, stringsize_t maxValue)
int64_t int64Value (RexxObject *o, size_t position)
uint64_t unsignedInt64Value (RexxObject *o, size_t position)
const char * cstring (RexxObject *, size_t position)
double getDoubleValue (RexxObject *, size_t position)
bool isDouble (RexxObject *)
void * cself ()
void * buffer ()
void * pointer (RexxObject *)
void * pointerString (RexxObject *object, size_t position)
RexxVariableBase * getObjectVariableRetriever (const char *name)
RexxObject * guardOnWhenUpdated (const char *name)
RexxObject * guardOffWhenUpdated (const char *name)
void guardOff ()
void guardOn ()
void guardWait ()
void enableVariablepool ()
void disableVariablepool ()
void resetNext ()
bool fetchNext (RexxString *&name, RexxObject *&value)
void raiseCondition (RexxString *condition, RexxString *description, RexxObject *additional, RexxObject *result)
ArrayClass * getArguments ()
RexxObject * getArgument (size_t index)
RexxClass * getSuper ()
RexxClass * getScope ()
StemClass * resolveStemVariable (RexxObject *s)
RexxClass * findClass (RexxString *className)
RexxClass * findCallerClass (RexxString *className)
void accessCallerContext ()
bool isVariablePoolEnabled ()
RexxString * getMessageName ()
RexxObject * getContextStem (RexxString *name)
RexxObject * getContextVariable (const char *name)
VariableReference * getContextVariableReference (const char *name)
void dropContextVariable (const char *name)
void setContextVariable (const char *name, RexxObject *value)
RexxObject * getObjectVariable (const char *name)
VariableReference * getObjectVariableReference (const char *name)
void setObjectVariable (const char *name, RexxObject *value)
void dropObjectVariable (const char *name)
DirectoryClass * getAllContextVariables ()
void setConditionInfo (RexxString *name, DirectoryClass *info)
void setConditionInfo (DirectoryClass *info)
DirectoryClass * getConditionInfo ()
void clearException ()
void clearCondition ()
void checkConditions ()
bool checkCondition (RexxString *name)
RexxObject * getSelf ()
Activity * getActivity ()
BaseExecutable * getRexxContextExecutable ()
RexxObject * getRexxContextObject ()
PackageClass * getPackageObject ()
void setStackBase ()
void reportSignatureError ()
void reportStemError (size_t position, RexxObject *object)
void processArguments (size_t argcount, RexxObject **arglist, uint16_t *argumentTypes, ValueDescriptor *descriptors, size_t maximumArgumentCount)
RexxObject * valueToObject (ValueDescriptor *value)
ArrayClass * valuesToObject (ValueDescriptor *value, size_t count)
bool objectToValue (RexxObject *o, ValueDescriptor *value)
void createLocalReference (RexxInternalObject *objr)
void removeLocalReference (RexxInternalObject *objr)
void clearLocalReferences ()
void callNativeRoutine (RoutineClass *routine, NativeRoutine *code, RexxString *functionName, RexxObject **list, size_t count, ProtectedObject &result)
void callRegisteredRoutine (RoutineClass *routine, RegisteredRoutine *code, RexxString *functionName, RexxObject **list, size_t count, ProtectedObject &resultObj)
RexxReturnCode variablePoolInterface (PSHVBLOCK requests)
RexxVariableBase * variablePoolGetVariable (PSHVBLOCK pshvblock, bool symbolic)
void variablePoolFetchVariable (PSHVBLOCK pshvblock)
void variablePoolSetVariable (PSHVBLOCK pshvblock)
void variablePoolDropVariable (PSHVBLOCK pshvblock)
void variablePoolNextVariable (PSHVBLOCK pshvblock)
void variablePoolFetchPrivate (PSHVBLOCK pshvblock)
void variablePoolRequest (PSHVBLOCK pshvblock)
RexxReturnCode copyValue (RexxObject *value, RXSTRING *rxstring, size_t *length)
RexxReturnCode copyValue (RexxObject *value, CONSTRXSTRING *rxstring, size_t *length)
int stemSort (StemClass *stem, const char *tailExtension, int order, int type, wholenumber_t start, wholenumber_t end, wholenumber_t firstcol, wholenumber_t lastcol)
void enableConditionTrap ()
void enableConditionCapture ()
void forwardMessage (RexxObject *to, RexxString *msg, RexxClass *super, ArrayClass *args, ProtectedObject &result)
void enableConditionTraps ()
void disableConditionTraps ()
StackFrameClass * createStackFrame ()
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
bool isMethod ()
Public Member Functions inherited from ActivationBase
ActivationBase ()
ActivationBase (RESTORETYPE restoreType)
virtual void setObjNotify (MessageClass *)
virtual bool isForwarded ()
virtual bool isRexxContext ()
void setPreviousStackFrame (ActivationBase *p)
ActivationBase * getPreviousStackFrame ()
BaseExecutable * getExecutable ()
BaseExecutable * getExecutableObject ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Attributes
static const size_t MaxNativeArguments = 16
Protected Types
enum ActivationType {
PROGRAM_ACTIVATION , METHOD_ACTIVATION , FUNCTION_ACTIVATION , DISPATCHER_ACTIVATION ,
CALLBACK_ACTIVATION , TRAPPING_ACTIVATION
}
Protected Attributes
Activity * activity
NativeCode * code
RexxObject * receiver
RexxString * messageName
RexxActivation * activation
size_t argCount
RexxObject ** argList
ArrayClass * argArray
RexxInternalObject * firstSavedObject
IdentityTable * saveList
RexxObject * result
ActivationType activationType
RexxString * conditionName
DirectoryClass * conditionObj
SecurityManager * securityManager
VariableDictionary * objectVariables
bool stackBase
bool trapErrors
bool trapConditions
bool captureConditions
bool variablePoolEnabled
VariableDictionary::VariableIterator iterator
Protected Attributes inherited from ActivationBase
ActivationBase * previous
BaseExecutable * executable
GuardStatus objectScope
Additional Inherited Members
Public Types inherited from ActivationBase
enum GuardStatus { SCOPE_RELEASED = 0 , SCOPE_RESERVED = 1 }
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
An object representing an activation of external native code. Used for handling external methods and routines, as well as other callouts such as exits.
Definition at line 71 of file NativeActivation.hpp.
Member Enumeration Documentation
ActivationType
enum NativeActivation::ActivationType protected
Enumerator
PROGRAM_ACTIVATION
METHOD_ACTIVATION
FUNCTION_ACTIVATION
DISPATCHER_ACTIVATION
CALLBACK_ACTIVATION
TRAPPING_ACTIVATION
Definition at line 213 of file NativeActivation.hpp.
Constructor & Destructor Documentation
NativeActivation() [1/4]
NativeActivation::NativeActivation (RESTORETYPE restoreType) inline
Definition at line 77 of file NativeActivation.hpp.
NativeActivation() [2/4]
NativeActivation::NativeActivation ()
Initialize an activation for direct caching in the activation cache. At this time, this is not an executable activation
Definition at line 92 of file NativeActivation-trace.cpp.
References RexxInternalObject::setHasNoReferences().
NativeActivation() [3/4]
NativeActivation::NativeActivation (Activity * _activity, RexxActivation * _activation)
Constructor for a new native activation used to create a callback context for exit call outs.
Parameters
_activity The activity we're running under.
Definition at line 104 of file NativeActivation-trace.cpp.
References activation, activity, and RexxInternalObject::clearObject().
NativeActivation() [4/4]
NativeActivation::NativeActivation (Activity * _activity)
Constructor for a new native activation used to create a callback context for exit call outs.
Parameters
_activity The activity we're running under.
Definition at line 118 of file NativeActivation-trace.cpp.
References activity, and RexxInternalObject::clearObject().
Member Function Documentation
accessCallerContext()
void NativeActivation::accessCallerContext ()
Establish the caller's context for native activations that require access to the caller's context.
Definition at line 1777 of file NativeActivation-trace.cpp.
References activation, and ActivationBase::getPreviousStackFrame().
Referenced by callNativeRoutine(), and callRegisteredRoutine().
allocateObjectMemory()
void * NativeActivation::allocateObjectMemory (size_t size)
Allocate memory in the current object context.
Parameters
size The requested memory size.
Returns
The newly allocated data buffer.
Definition at line 3658 of file NativeActivation-trace.cpp.
References RexxObject::allocateObjectMemory(), and receiver.
Referenced by AllocateObjectMemory().
buffer()
void* NativeActivation::buffer ()
callNativeRoutine()
void NativeActivation::callNativeRoutine (RoutineClass * _routine, NativeRoutine * _code, RexxString * functionName, RexxObject ** list, size_t count, ProtectedObject & resultObj)
Process a native function call.
Parameters
routine The routine we're executing (used for context resolution).
code The code object.
functionName The name of the function.
list The list of arguments.
count The number of arguments.
resultObj The return value.
Definition at line 1379 of file NativeActivation-trace.cpp.
References accessCallerContext(), activationType, activity, argCount, argList, RexxCallContext_::arguments, checkConditions(), Activity::createCallContext(), ActivityManager::currentActivity, disableVariablepool(), enableVariablepool(), ActivationBase::executable, FUNCTION_ACTIVATION, Activity::getActivationLevel(), NativeRoutine::getEntry(), Activity::getInstanceSecurityManager(), NativeCode::getSecurityManager(), MaxNativeArguments, messageName, OREF_NULL, Activity::popStackFrame(), processArguments(), receiver, Activity::releaseAccess(), Activity::requestAccess(), Activity::restoreActivationLevel(), result, securityManager, RexxInternalObject::setHasNoReferences(), CallContext::threadContext, trapErrors, and valueToObject().
Referenced by NativeRoutine::call().
callRegisteredRoutine()
void NativeActivation::callRegisteredRoutine (RoutineClass * _routine, RegisteredRoutine * _code, RexxString * functionName, RexxObject ** list, size_t count, ProtectedObject & resultObj)
Process a native function call.
Parameters
entryPoint The target function entry point.
list The list of arguments.
count The number of arguments.
result A protected object to receive the function result.
Definition at line 1466 of file NativeActivation-trace.cpp.
References accessCallerContext(), activationType, activity, argCount, argList, createLocalReference(), ActivityManager::currentActivity, DEFRXSTRING, disableVariablepool(), enableVariablepool(), Error_Incorrect_call_external, ActivationBase::executable, FUNCTION_ACTIVATION, Activity::getActivationLevel(), Interpreter::getCurrentQueue(), BufferClass::getData(), RegisteredRoutine::getEntry(), Activity::getInstanceSecurityManager(), RexxString::getStringData(), MAKERXSTRING, MaxNativeArguments, messageName, new_buffer(), new_string(), OREF_NULL, Activity::popStackFrame(), Activity::releaseAccess(), SystemInterpreter::releaseResultMemory(), reportException(), Activity::requestAccess(), Activity::restoreActivationLevel(), result, securityManager, RexxInternalObject::setHasNoReferences(), stringArgument(), RexxObject::stringValue(), _CONSTRXSTRING::strlength, _RXSTRING::strptr, _CONSTRXSTRING::strptr, RexxString::toRxstring(), and trapErrors.
Referenced by RegisteredRoutine::call().
checkCondition()
bool NativeActivation::checkCondition (RexxString * name)
Check if a condition of the given type has been trapped.
Parameters
name The condition name.
Returns
True if this activation has trapped a condition of the indicated type.
Definition at line 1851 of file NativeActivation-trace.cpp.
References conditionName, OREF_NULL, and RexxString::strCompare().
checkConditions()
void NativeActivation::checkConditions ()
Check to see if there are deferred syntax errors that need to be raised on return from a native activation.
Definition at line 1787 of file NativeActivation-trace.cpp.
References activity, conditionName, conditionObj, DirectoryClass::get(), ActivationBase::getPreviousStackFrame(), isStackBase(), OREF_NULL, Activity::reraiseException(), result, RexxString::strCompare(), ActivationBase::trap(), and trapErrors.
Referenced by callNativeRoutine(), CallbackDispatcher::handleError(), TrappingDispatcher::handleError(), ContextCommandHandlerDispatcher::handleError(), and run().
clearCondition()
void NativeActivation::clearCondition ()
Clear any non-syntax conditions that have been trapped so that they are not propagated to a caller.
Definition at line 1828 of file NativeActivation-trace.cpp.
References clearException(), conditionName, conditionObj, OREF_NULL, and RexxString::strCompare().
Referenced by ApiContext::~ApiContext().
clearException()
void NativeActivation::clearException () inline
Definition at line 161 of file NativeActivation.hpp.
References conditionName, conditionObj, and OREF_NULL.
Referenced by clearCondition(), ClearCondition(), ConditionTrappingDispatcher::handleError(), UninitDispatcher::handleError(), ObjectToValue(), ResolveStemVariable(), ValuesToObject(), and ValueToObject().
clearLocalReferences()
void NativeActivation::clearLocalReferences ()
Clear out the local reference table for a NativeActivation
Definition at line 1248 of file NativeActivation-trace.cpp.
References firstSavedObject, OREF_NULL, and saveList.
Referenced by Activity::clearLocalReferences().
copyValue() [1/2]
RexxReturnCode NativeActivation::copyValue (RexxObject * value, CONSTRXSTRING * rxstring, size_t * length)
Copy a value for a variable pool request, with checks for truncation.
Parameters
value The value to copy.
rxstring The target RXSTRING.
length The max length we can copy.
Returns
A return code to be included in the composite return value.
Definition at line 3486 of file NativeActivation-trace.cpp.
References copyValue(), _RXSTRING::strlength, _CONSTRXSTRING::strlength, _RXSTRING::strptr, and _CONSTRXSTRING::strptr.
copyValue() [2/2]
RexxReturnCode NativeActivation::copyValue (RexxObject * value, RXSTRING * rxstring, size_t * length)
Copy a value for a variable pool request, with checks for truncation.
Parameters
value The value to copy.
rxstring The target RXSTRING.
length The max length we can copy.
Returns
A return code to be included in the composite return value.
Definition at line 3511 of file NativeActivation-trace.cpp.
References SystemInterpreter::allocateResultMemory(), RexxString::getLength(), RexxString::getStringData(), RXSHV_MEMFL, RXSHV_TRUNC, RexxObject::stringValue(), _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by copyValue(), variablePoolFetchPrivate(), variablePoolFetchVariable(), and variablePoolNextVariable().
createLocalReference()
void NativeActivation::createLocalReference (RexxInternalObject * objr)
Create a local reference for an object. The protects the object from GC until the environment terminates.
Parameters
objr The object to protect.
Definition at line 1185 of file NativeActivation-trace.cpp.
References firstSavedObject, new_identity_table(), OREF_NULL, HashCollection::put(), and saveList.
Referenced by callRegisteredRoutine(), cstring(), getArguments(), objectToValue(), processArguments(), and ApiContext::ret().
createStackFrame()
StackFrameClass * NativeActivation::createStackFrame ()
Create a stack frame for exception tracebacks.
Returns
A StackFrame instance for this activation.
Definition at line 3628 of file NativeActivation-trace.cpp.
References activity, Activity::buildMessage(), ActivationBase::executable, StackFrameClass::FRAME_METHOD, StackFrameClass::FRAME_ROUTINE, getArguments(), ActivationBase::getExecutableObject(), getMessageName(), Message_Translations_compiled_method_invocation, Message_Translations_compiled_routine_invocation, new_array(), OREF_NULL, receiver, and SIZE_MAX.
Referenced by NativeActivationFrame::createStackFrame().
cself()
void * NativeActivation::cself ()
Returns "unwrapped" C or C++ object associated with this object instance. If the variable CSELF does not exist, then NULL is returned.
Returns
The unwrapped value.
Definition at line 2091 of file NativeActivation-trace.cpp.
References RexxObject::getCSelf(), getScope(), methodVariables(), OREF_NULL, and receiver.
Referenced by GetCSelf(), and processArguments().
cstring()
const char * NativeActivation::cstring (RexxObject * object, size_t position)
Convert an object into a CSTRING pointer.
Parameters
object The source object.
Returns
The CSTRING version of the object.
Definition at line 2028 of file NativeActivation-trace.cpp.
References createLocalReference(), and stringArgument().
Referenced by objectToValue(), and processArguments().
digits()
wholenumber_t NativeActivation::digits () override virtual
Return the current digits setting for the context.
Returns
The digits value
Reimplemented from ActivationBase.
Definition at line 2146 of file NativeActivation-trace.cpp.
References activation, Numerics::DEFAULT_DIGITS, RexxActivation::digits(), and OREF_NULL.
Referenced by GetContextDigits().
disableConditionTraps()
void NativeActivation::disableConditionTraps () inline
Definition at line 201 of file NativeActivation.hpp.
References trapErrors.
Referenced by ApiContext::~ApiContext().
disableVariablepool()
void NativeActivation::disableVariablepool ()
Turn off variable pool access.
Definition at line 2567 of file NativeActivation-trace.cpp.
References resetNext(), and variablePoolEnabled.
Referenced by callNativeRoutine(), and callRegisteredRoutine().
dispatch()
RexxObject * NativeActivation::dispatch () override virtual
Redispatch an activation on a different activity
Returns
The dispatched method result.
Reimplemented from ActivationBase.
Definition at line 2129 of file NativeActivation-trace.cpp.
References argCount, argList, code, ActivationBase::executable, messageName, OREF_NULL, receiver, and run().
dropContextVariable()
void NativeActivation::dropContextVariable (const char * name)
Drop a context variable for an API call.
Parameters
name The target variable name.
Definition at line 2950 of file NativeActivation-trace.cpp.
References activation, RexxVariableBase::drop(), VariableDictionary::getVariableRetriever(), isString(), new_string(), OREF_NULL, and resetNext().
Referenced by DropContextVariable(), and DropExitContextVariable().
dropObjectVariable()
void NativeActivation::dropObjectVariable (const char * name)
Drop an object variable in the current method scope.
Parameters
name The name of the variable.
Definition at line 3079 of file NativeActivation-trace.cpp.
References getObjectVariableRetriever(), methodVariables(), and OREF_NULL.
Referenced by DropObjectVariable().
enableConditionCapture()
void NativeActivation::enableConditionCapture () inline
Definition at line 197 of file NativeActivation.hpp.
References captureConditions, and trapConditions.
enableConditionTrap()
void NativeActivation::enableConditionTrap () inline
Definition at line 196 of file NativeActivation.hpp.
References captureConditions, and trapConditions.
Referenced by CallThrowCondition(), ExitThrowCondition(), RaiseCondition(), and ThrowCondition().
enableConditionTraps()
void NativeActivation::enableConditionTraps () inline
Definition at line 200 of file NativeActivation.hpp.
References trapErrors.
Referenced by ApiContext::ApiContext(), and RexxStartDispatcher::handleError().
enableVariablepool()
void NativeActivation::enableVariablepool ()
Enable the variable pool for access.
Definition at line 2556 of file NativeActivation-trace.cpp.
References resetNext(), and variablePoolEnabled.
Referenced by callNativeRoutine(), callRegisteredRoutine(), Activity::exitKernel(), and Activity::run().
fetchNext()
bool NativeActivation::fetchNext (RexxString *& name, RexxObject *& value)
Fetch the next variable of a variable pool traversal
Parameters
name The returned variable name.
value The returned variable value.
Returns
true if we have a variable, false if we've reached the iteration end.
Definition at line 2593 of file NativeActivation-trace.cpp.
References activation, activity, Activity::getCurrentRexxFrame(), RexxActivation::getLocalVariables(), VariableDictionary::VariableIterator::isActive(), VariableDictionary::VariableIterator::isAvailable(), iterator, VariableDictionary::iterator(), VariableDictionary::VariableIterator::name(), VariableDictionary::VariableIterator::next(), VariableDictionary::VariableIterator::terminate(), and VariableDictionary::VariableIterator::value().
Referenced by variablePoolNextVariable().
findCallerClass()
RexxClass * NativeActivation::findCallerClass (RexxString * className)
Resolve a class in the context of the caller's execution context.
Parameters
className The target class name.
Returns
The resolved class (if any).
Definition at line 3133 of file NativeActivation-trace.cpp.
References activation, Interpreter::findClass(), RexxActivation::findClass(), RexxObject::isInstanceOf(), OREF_NULL, and TheClassClass.
Referenced by FindCallContextClass().
findClass()
RexxClass * NativeActivation::findClass (RexxString * className)
Resolve a class in the context of the current execution context.
Parameters
className The target class name.
Returns
The resolved class (if any).
Definition at line 3102 of file NativeActivation-trace.cpp.
References ActivationBase::executable, BaseExecutable::findClass(), Interpreter::findClass(), RexxObject::isInstanceOf(), OREF_NULL, and TheClassClass.
Referenced by FindClass(), FindContextClass(), and IsOfType().
findRexxContext()
RexxActivation * NativeActivation::findRexxContext () override virtual
Return the Rexx context this operates under. Depending on the context, this could be null.
Returns
The parent Rexx context.
Reimplemented from ActivationBase.
Definition at line 2333 of file NativeActivation-trace.cpp.
References activation, ActivationBase::findRexxContext(), OREF_NULL, and ActivationBase::previous.
Referenced by RexxRoutine7().
form()
bool NativeActivation::form () override virtual
Return the current context form setting.
Returns
The form setting.
Reimplemented from ActivationBase.
Definition at line 2186 of file NativeActivation-trace.cpp.
References activation, Numerics::DEFAULT_FORM, RexxActivation::form(), and OREF_NULL.
Referenced by GetContextForm().
forwardMessage()
void NativeActivation::forwardMessage (RexxObject * to, RexxString * msg, RexxClass * super, ArrayClass * args, ProtectedObject & _result)
Implement the equivalent of a FORWARD CONTINUE instruction as an API call. All null arguments are filled in with the method context args.
Parameters
to The target object. Defaults to SELF
msg The target message name. Defaults to current message.
super Any superclass override. Defaults to none.
args The message arguments. Defaults to current argument set.
Returns
The message send result.
Definition at line 3595 of file NativeActivation-trace.cpp.
References getArguments(), getMessageName(), getSelf(), ArrayClass::messageArgCount(), ArrayClass::messageArgs(), RexxObject::messageSend(), and OREF_NULL.
Referenced by ForwardMessage().
freeObjectMemory()
void NativeActivation::freeObjectMemory (void * pointer)
Free previously allocated object memory.
Parameters
pointer The memory to release.
Definition at line 3683 of file NativeActivation-trace.cpp.
References RexxObject::freeObjectMemory(), pointer(), and receiver.
Referenced by FreeObjectMemory().
fuzz()
wholenumber_t NativeActivation::fuzz () override virtual
Return the context fuzz() setting.
Returns
The current fuzz setting.
Reimplemented from ActivationBase.
Definition at line 2166 of file NativeActivation-trace.cpp.
References activation, Numerics::DEFAULT_FUZZ, RexxActivation::fuzz(), and OREF_NULL.
Referenced by GetContextFuzz().
getActivity()
Activity* NativeActivation::getActivity () inline
Definition at line 166 of file NativeActivation.hpp.
References activity.
Referenced by GetInterpreterInstance(), guardWait(), and StreamObjectInputSource::read().
getAllContextVariables()
DirectoryClass * NativeActivation::getAllContextVariables ()
Retrieve a list of all variables in the current context.
Returns
A directory containing the context variables.
Definition at line 2971 of file NativeActivation-trace.cpp.
References activation, RexxActivation::getAllLocalVariables(), and resetNext().
Referenced by GetAllContextVariables(), and GetAllExitContextVariables().
getArgument()
RexxObject * NativeActivation::getArgument (size_t index)
Retrieve a specific argument from the method invocation context.
Parameters
index The argument of interest.
Returns
The object mapped to that argument. Returns OREF_NULL for omitted arguments.
Definition at line 2775 of file NativeActivation-trace.cpp.
References argCount, argList, and OREF_NULL.
Referenced by GetCallArgument(), and GetMethodArgument().
getArguments()
ArrayClass * NativeActivation::getArguments ()
Return the method context arguments as an array.
Returns
An array containing the method arguments.
Definition at line 2753 of file NativeActivation-trace.cpp.
References argArray, argCount, argList, createLocalReference(), new_array(), and OREF_NULL.
Referenced by createStackFrame(), forwardMessage(), GetCallArguments(), GetMethodArguments(), and processArguments().
getConditionInfo()
DirectoryClass* NativeActivation::getConditionInfo () inline
Definition at line 160 of file NativeActivation.hpp.
References conditionObj.
Referenced by CheckCondition(), DisplayCondition(), and GetConditionInfo().
getContextObject()
RexxObject* NativeActivation::getContextObject () inline
Definition at line 103 of file NativeActivation.hpp.
References getContextObject().
Referenced by getContextObject().
getContextStem()
RexxObject * NativeActivation::getContextStem (RexxString * name)
retrieve a stem variable stem from the current context.
Parameters
name The name, which does not need to end in a period.
Returns
The stem object associated with that name.
Definition at line 2843 of file NativeActivation-trace.cpp.
References activation, RexxString::concatWithCstring(), RexxString::endsWith(), RexxInternalObject::getValue(), VariableDictionary::getVariableRetriever(), isOfClass, and OREF_NULL.
Referenced by objectToValue(), processArguments(), and resolveStemVariable().
getContextVariable()
RexxObject * NativeActivation::getContextVariable (const char * name)
Retrieve the value of a context variable via the API calls. Returns OREF_NULL if the variable does not exist.
Parameters
name The variable name.
Returns
The variable value, if any.
Definition at line 2871 of file NativeActivation-trace.cpp.
References activation, RexxInternalObject::getRealValue(), VariableDictionary::getVariableRetriever(), isString(), new_string(), OREF_NULL, and resetNext().
Referenced by GetContextVariable(), and GetExitContextVariable().
getContextVariableReference()
VariableReference * NativeActivation::getContextVariableReference (const char * name)
Retrieve a context variable as a VariableReference instance via the API calls. This will create the variable if the variable does not exist.
Parameters
name The variable name.
Returns
The variable value, if any.
Definition at line 2905 of file NativeActivation-trace.cpp.
References activation, RexxVariableBase::getVariableReference(), VariableDictionary::getVariableRetriever(), new_string(), OREF_NULL, and resetNext().
Referenced by GetContextVariableReference(), and GetExitContextVariableReference().
getDoubleValue()
double NativeActivation::getDoubleValue (RexxObject * object, size_t position)
Convert an object to a double
Parameters
object The object to convert.
position The argument position for error reporting.
Returns
The converted double value.
Definition at line 2072 of file NativeActivation-trace.cpp.
References RexxInternalObject::doubleValue(), Error_Invalid_argument_double, and reportException().
Referenced by processArguments().
getMessageName()
RexxString* NativeActivation::getMessageName () inline
Definition at line 147 of file NativeActivation.hpp.
References messageName.
Referenced by createStackFrame(), forwardMessage(), GetMessageName(), GetRoutineName(), InvalidRoutine(), and NativeActivationFrame::messageName().
getMethod()
MethodClass * NativeActivation::getMethod ()
Get the active method
Returns
The method object for this frame.. Returns OREF_NULL if this is not a message activation.
Definition at line 2369 of file NativeActivation-trace.cpp.
References ActivationBase::executable, isMethod(), and OREF_NULL.
getNumericSettings()
const NumericSettings * NativeActivation::getNumericSettings () override virtual
Get the numeric settings for this native activation. If we're running in the direct call context from a Rexx activation, then the settings are those inherited from the Rexx context. Otherwise, we just return the default numeric settings.
Returns
The current Numeric settings.
Reimplemented from ActivationBase.
Definition at line 2253 of file NativeActivation-trace.cpp.
References activation, Numerics::getDefaultSettings(), RexxActivation::getNumericSettings(), and OREF_NULL.
getObjectVariable()
RexxObject * NativeActivation::getObjectVariable (const char * name)
Get an object variable in the current method scope. Returns a NULL object reference if the variable does not exist.
Parameters
name The variable name.
Returns
The variable value or OREF_NULL if the variable does not exist.
Definition at line 2987 of file NativeActivation-trace.cpp.
References getObjectVariableRetriever(), methodVariables(), and OREF_NULL.
Referenced by GetObjectVariable().
getObjectVariableReference()
VariableReference * NativeActivation::getObjectVariableReference (const char * name)
Get a reference to an object variable in the current method scope. This will create the object if it does not already exist.
Parameters
name The variable name.
Returns
The variable reference object.
Definition at line 3036 of file NativeActivation-trace.cpp.
References getObjectVariableRetriever(), methodVariables(), and OREF_NULL.
Referenced by GetObjectVariableReference().
getObjectVariableRetriever()
RexxVariableBase * NativeActivation::getObjectVariableRetriever (const char * name)
Validate and retrieve an accessor for an object variable. Note, this only retrieves top-level variables (simple and stem variables).
Parameters
name The name of the required variable.
Returns
The variable retriever or OREF_NULL if this was not a valid variable.
Definition at line 3010 of file NativeActivation-trace.cpp.
References VariableDictionary::getVariableRetriever(), isOfClassType, isString(), new_string(), and OREF_NULL.
Referenced by dropObjectVariable(), getObjectVariable(), getObjectVariableReference(), guardOffWhenUpdated(), guardOnWhenUpdated(), and setObjectVariable().
getPackage()
PackageClass* NativeActivation::getPackage () inline override virtual
Reimplemented from ActivationBase.
Definition at line 102 of file NativeActivation.hpp.
References getPackageObject().
getPackageObject()
PackageClass * NativeActivation::getPackageObject ()
Retrieve the source object for the current context, if there is one.
Returns
The source object associated with any Method or Routine currently being run.
Definition at line 3161 of file NativeActivation-trace.cpp.
References ActivationBase::executable, BaseExecutable::getPackageObject(), and OREF_NULL.
Referenced by NativeActivationFrame::getPackage(), getPackage(), and getSecurityManager().
getReceiver()
RexxObject * NativeActivation::getReceiver () override virtual
Get the message receiver
Returns
The message receiver. Returns OREF_NULL if this is not a message activation.
Reimplemented from ActivationBase.
Definition at line 2357 of file NativeActivation-trace.cpp.
References receiver.
getRexxContext()
RexxActivation * NativeActivation::getRexxContext () override virtual
Return the Rexx context this operates under. Depending on the context, this could be null.
Returns
The parent Rexx context.
Reimplemented from ActivationBase.
Definition at line 2284 of file NativeActivation-trace.cpp.
References activation.
getRexxContextExecutable()
BaseExecutable * NativeActivation::getRexxContextExecutable ()
Return the Rexx executable context that is our immediate caller. Depending on the context, this could be null.
Returns
The parent Rexx context.
Definition at line 2297 of file NativeActivation-trace.cpp.
References activation, ActivationBase::getExecutable(), and OREF_NULL.
getRexxContextObject()
RexxObject * NativeActivation::getRexxContextObject ()
Return the Rexx context object for our immediate caller. Depending on the context, this could be null.
Returns
The parent Rexx context.
Definition at line 2315 of file NativeActivation-trace.cpp.
References activation, RexxActivation::getContextObject(), and OREF_NULL.
Referenced by GetCallerContext(), and GetExitCallerContext().
getScope()
RexxClass * NativeActivation::getScope ()
Return the current method scope.
Returns
The current method scope object.
Definition at line 2799 of file NativeActivation-trace.cpp.
References ActivationBase::executable.
Referenced by cself(), GetScope(), getSuper(), guardOn(), methodVariables(), and processArguments().
getSecurityManager()
SecurityManager * NativeActivation::getSecurityManager () override virtual
Get the security manager context
Returns
The security manager, if there is one.
Implements ActivationBase.
Definition at line 2381 of file NativeActivation-trace.cpp.
References getPackageObject(), PackageClass::getSecurityManager(), and OREF_NULL.
getSelf()
RexxObject* NativeActivation::getSelf () inline
Definition at line 165 of file NativeActivation.hpp.
References receiver.
Referenced by forwardMessage(), and GetSelf().
getSuper()
RexxClass * NativeActivation::getSuper ()
Return the super class scope of the current method context.
Returns
The superclass scope object.
Definition at line 2789 of file NativeActivation-trace.cpp.
References getScope(), receiver, and RexxObject::superScope().
Referenced by GetSuper(), and processArguments().
guardOff()
void NativeActivation::guardOff ()
Release a variable pool guard lock
Definition at line 2395 of file NativeActivation-trace.cpp.
References activity, ActivationBase::objectScope, objectVariables, VariableDictionary::release(), ActivationBase::SCOPE_RELEASED, and ActivationBase::SCOPE_RESERVED.
Referenced by guardOffWhenUpdated(), run(), SetGuardOff(), and termination().
guardOffWhenUpdated()
RexxObject * NativeActivation::guardOffWhenUpdated (const char * name)
Wait for an object variable to be updated and return the new value. The guard state will be OFF on return.
Parameters
name The name of the variable (only simple or stem variables allowed)
Returns
The new value of the variable.
Definition at line 2520 of file NativeActivation-trace.cpp.
References activity, getObjectVariableRetriever(), guardOff(), Activity::guardSet(), guardWait(), isMethod(), methodVariables(), objectVariables, and OREF_NULL.
Referenced by SetGuardOffWhenUpdated().
guardOn()
void NativeActivation::guardOn ()
Acquire a variable pool guard lock
Definition at line 2409 of file NativeActivation-trace.cpp.
References activity, RexxObject::getObjectVariables(), getScope(), isMethod(), ActivationBase::objectScope, objectVariables, OREF_NULL, receiver, VariableDictionary::reserve(), ActivationBase::SCOPE_RELEASED, and ActivationBase::SCOPE_RESERVED.
Referenced by guardOnWhenUpdated(), and SetGuardOn().
guardOnWhenUpdated()
RexxObject * NativeActivation::guardOnWhenUpdated (const char * name)
Wait for an object variable to be updated and return the new value. The guard state will be ON on return.
Parameters
name The name of the variable (only simple or stem variables allowed)
Returns
The new value of the variable.
Definition at line 2478 of file NativeActivation-trace.cpp.
References activity, getObjectVariableRetriever(), guardOn(), Activity::guardSet(), guardWait(), isMethod(), methodVariables(), objectVariables, and OREF_NULL.
Referenced by SetGuardOnWhenUpdated().
guardWait()
void NativeActivation::guardWait ()
Wait for a variable in a guard expression to get updated.
Definition at line 2435 of file NativeActivation-trace.cpp.
References activity, getActivity(), Activity::guardSet(), Activity::guardWait(), ActivationBase::objectScope, objectVariables, VariableDictionary::release(), VariableDictionary::reserve(), ActivationBase::SCOPE_RELEASED, and ActivationBase::SCOPE_RESERVED.
Referenced by guardOffWhenUpdated(), and guardOnWhenUpdated().
int64Value()
int64_t NativeActivation::int64Value (RexxObject * o, size_t position)
Convert a value to an int64_t value
Parameters
o The object to convert.
position The argument position.
Returns
The converted number.
Definition at line 1987 of file NativeActivation-trace.cpp.
References Error_Invalid_argument_range, INT64_MAX, INT64_MIN, Numerics::int64ToObject(), new_array(), new_integer(), Numerics::objectToInt64(), and reportException().
Referenced by processArguments().
isDouble()
bool NativeActivation::isDouble (RexxObject *)
isMethod()
bool NativeActivation::isMethod () inline
Definition at line 207 of file NativeActivation.hpp.
References activationType, and METHOD_ACTIVATION.
Referenced by getMethod(), guardOffWhenUpdated(), guardOn(), guardOnWhenUpdated(), objectToValue(), processArguments(), reportSignatureError(), and reportStemError().
isStackBase()
bool NativeActivation::isStackBase () override virtual
Indicate whether this activation represents the base of the call stack.
Returns
true if this is a base activation.
Reimplemented from ActivationBase.
Definition at line 2272 of file NativeActivation-trace.cpp.
References stackBase.
Referenced by checkConditions().
isVariablePoolEnabled()
bool NativeActivation::isVariablePoolEnabled () inline
Definition at line 146 of file NativeActivation.hpp.
References variablePoolEnabled.
Referenced by variablePoolInterface().
live()
void NativeActivation::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 130 of file NativeActivation-trace.cpp.
References activation, activity, argArray, argCount, argList, code, conditionName, conditionObj, ActivationBase::executable, firstSavedObject, memory_mark, memory_mark_array, messageName, objectVariables, ActivationBase::previous, receiver, result, saveList, and securityManager.
liveGeneral()
void NativeActivation::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 162 of file NativeActivation-trace.cpp.
References activation, activity, argArray, argCount, argList, code, conditionName, conditionObj, ActivationBase::executable, firstSavedObject, memory_mark_general, memory_mark_general_array, messageName, objectVariables, ActivationBase::previous, receiver, result, saveList, and securityManager.
methodVariables()
VariableDictionary * NativeActivation::methodVariables ()
Retrieve the set of object variables for the method scope.
Returns
The associated variable dictionary.
Definition at line 1863 of file NativeActivation-trace.cpp.
References activity, ActivationBase::executable, RexxObject::getObjectVariables(), getScope(), MethodClass::isGuarded(), ActivationBase::objectScope, objectVariables, OREF_NULL, receiver, VariableDictionary::reserve(), ActivationBase::SCOPE_RELEASED, and ActivationBase::SCOPE_RESERVED.
Referenced by cself(), dropObjectVariable(), getObjectVariable(), getObjectVariableReference(), guardOffWhenUpdated(), guardOnWhenUpdated(), and setObjectVariable().
nonnegativeWholeNumberValue()
wholenumber_t NativeActivation::nonnegativeWholeNumberValue (RexxObject * o, size_t position)
Convert a value to a nonnegative wholenumber value.
Parameters
o The object to convert.
position The argument position.
Returns
The converted number.
Definition at line 1943 of file NativeActivation-trace.cpp.
References Error_Invalid_argument_nonnegative, Numerics::MAX_WHOLENUMBER, Numerics::objectToSignedInteger(), and reportException().
Referenced by processArguments().
objectToValue()
bool NativeActivation::objectToValue (RexxObject * o, ValueDescriptor * value)
Convert a Rexx object into the requested value type, if possible.
Parameters
o The source object.
value The receiving value structure, which also defines the type.
Returns
true if the value was convertable, false otherwise.
Definition at line 873 of file NativeActivation-trace.cpp.
References arrayArgument(), createLocalReference(), cstring(), RexxInternalObject::doubleValue(), getContextStem(), RexxString::getStringData(), INT16_MAX, INT16_MIN, INT32_MAX, INT32_MIN, INT8_MAX, INT8_MIN, RexxObject::isInstanceOf(), isMethod(), isStem(), RexxInternalObject::logicalValue(), Numerics::MAX_STRINGSIZE, Numerics::MAX_WHOLENUMBER, Numerics::MIN_WHOLENUMBER, Numerics::objectToInt64(), Numerics::objectToIntptr(), Numerics::objectToSignedInteger(), Numerics::objectToStringSize(), Numerics::objectToUintptr(), Numerics::objectToUnsignedInt64(), Numerics::objectToUnsignedInteger(), Numerics::objectToWholeNumber(), OREF_NULL, pointer(), REXX_VALUE_CSTRING, REXX_VALUE_double, REXX_VALUE_float, REXX_VALUE_int, REXX_VALUE_int16_t, REXX_VALUE_int32_t, REXX_VALUE_int64_t, REXX_VALUE_int8_t, REXX_VALUE_intptr_t, REXX_VALUE_logical_t, REXX_VALUE_nonnegative_wholenumber_t, REXX_VALUE_POINTER, REXX_VALUE_POINTERSTRING, REXX_VALUE_positive_wholenumber_t, REXX_VALUE_RexxArrayObject, REXX_VALUE_RexxClassObject, REXX_VALUE_RexxMutableBufferObject, REXX_VALUE_RexxObjectPtr, REXX_VALUE_RexxStemObject, REXX_VALUE_RexxStringObject, REXX_VALUE_RexxVariableReferenceObject, REXX_VALUE_size_t, REXX_VALUE_ssize_t, REXX_VALUE_stringsize_t, REXX_VALUE_uint16_t, REXX_VALUE_uint32_t, REXX_VALUE_uint64_t, REXX_VALUE_uint8_t, REXX_VALUE_uintptr_t, REXX_VALUE_wholenumber_t, SIZE_MAX, SSIZE_MAX, stringArgument(), RexxObject::stringValue(), TheClassClass, TheMutableBufferClass, TheVariableReferenceClass, _ValueDescriptor::type, UINT16_MAX, UINT32_MAX, UINT8_MAX, _ValueDescriptor::value, _ValueDescriptor::value_CSTRING, _ValueDescriptor::value_double, _ValueDescriptor::value_float, _ValueDescriptor::value_int, _ValueDescriptor::value_int16_t, _ValueDescriptor::value_int32_t, _ValueDescriptor::value_int64_t, _ValueDescriptor::value_int8_t, _ValueDescriptor::value_intptr_t, _ValueDescriptor::value_logical_t, _ValueDescriptor::value_nonnegative_wholenumber_t, _ValueDescriptor::value_POINTER, _ValueDescriptor::value_positive_wholenumber_t, _ValueDescriptor::value_RexxArrayObject, _ValueDescriptor::value_RexxClassObject, _ValueDescriptor::value_RexxMutableBufferObject, _ValueDescriptor::value_RexxObjectPtr, _ValueDescriptor::value_RexxStemObject, _ValueDescriptor::value_RexxStringObject, _ValueDescriptor::value_RexxVariableReferenceObject, _ValueDescriptor::value_size_t, _ValueDescriptor::value_stringsize_t, _ValueDescriptor::value_uint16_t, _ValueDescriptor::value_uint32_t, _ValueDescriptor::value_uint64_t, _ValueDescriptor::value_uint8_t, _ValueDescriptor::value_uintptr_t, and _ValueDescriptor::value_wholenumber_t.
Referenced by ObjectToValue().
operator delete()
void NativeActivation::operator delete (void *) inline
Definition at line 75 of file NativeActivation.hpp.
operator new()
void * NativeActivation::operator new (size_t size)
Allocate a new native Activation.
Parameters
size the allocation size.
Returns
A pointer to the newly allocated object.
Definition at line 82 of file NativeActivation-trace.cpp.
References new_object(), and T_NativeActivation.
pointer()
void * NativeActivation::pointer (RexxObject * object)
Dereference the pointer value inside a pointer object.
Parameters
object The source pointer object.
Returns
The pointer value, or NULL if this is not a pointer object.
Definition at line 2113 of file NativeActivation-trace.cpp.
References RexxObject::isInstanceOf(), and ThePointerClass.
Referenced by freeObjectMemory(), objectToValue(), processArguments(), and reallocateObjectMemory().
pointerString()
void * NativeActivation::pointerString (RexxObject * object, size_t position)
Convert a string in the format 0xnnnnnnnnn into a pointer value.
Parameters
object The object to convert.
Returns
The pointer value.
Definition at line 2049 of file NativeActivation-trace.cpp.
References Error_Invalid_argument_pointer, RexxString::getStringData(), reportException(), and RexxObject::stringValue().
Referenced by processArguments().
positiveWholeNumberValue()
wholenumber_t NativeActivation::positiveWholeNumberValue (RexxObject * o, size_t position)
Convert a value to a positive wholenumber value.
Parameters
o The object to convert.
position The argument position.
Returns
The converted number.
Definition at line 1922 of file NativeActivation-trace.cpp.
References Error_Invalid_argument_positive, Numerics::MAX_WHOLENUMBER, Numerics::objectToSignedInteger(), and reportException().
Referenced by processArguments().
processArguments()
void NativeActivation::processArguments (size_t _argcount, RexxObject ** _arglist, uint16_t * argumentTypes, ValueDescriptor * descriptors, size_t maximumArgumentCount)
Process the arguments for a typed function/method call.
Parameters
argcount The count of arguments.
arglist The original Rexx arguments.
argumentTypes The type descriptor from the target.
descriptors The maximum argument count for the target.
maximumArgumentCount
Definition at line 219 of file NativeActivation-trace.cpp.
References ARGUMENT_EXISTS, ARGUMENT_TYPE, arrayArgument(), createLocalReference(), cself(), cstring(), Error_Invalid_argument_maxarg, Error_Invalid_argument_noarg, Error_Invalid_argument_noclass, Error_Logical_value_method, _ValueDescriptor::flags, getArguments(), getContextStem(), getDoubleValue(), getScope(), RexxString::getStringData(), getSuper(), INT16_MAX, INT16_MIN, INT32_MAX, INT32_MIN, int64Value(), INT8_MAX, INT8_MIN, INTPTR_MAX, INTPTR_MIN, IS_OPTIONAL_ARGUMENT, RexxObject::isInstanceOf(), isMethod(), isStem(), Numerics::MAX_STRINGSIZE, Numerics::MAX_WHOLENUMBER, messageName, Numerics::MIN_WHOLENUMBER, nonnegativeWholeNumberValue(), OREF_NULL, pointer(), pointerString(), positiveWholeNumberValue(), receiver, reportException(), reportSignatureError(), reportStemError(), RexxInternalObject::requestString(), REXX_ARGUMENT_TERMINATOR, REXX_VALUE_ARGLIST, REXX_VALUE_CSELF, REXX_VALUE_CSTRING, REXX_VALUE_double, REXX_VALUE_float, REXX_VALUE_int, REXX_VALUE_int16_t, REXX_VALUE_int32_t, REXX_VALUE_int64_t, REXX_VALUE_int8_t, REXX_VALUE_intptr_t, REXX_VALUE_logical_t, REXX_VALUE_NAME, REXX_VALUE_nonnegative_wholenumber_t, REXX_VALUE_OSELF, REXX_VALUE_POINTER, REXX_VALUE_POINTERSTRING, REXX_VALUE_positive_wholenumber_t, REXX_VALUE_RexxArrayObject, REXX_VALUE_RexxClassObject, REXX_VALUE_RexxMutableBufferObject, REXX_VALUE_RexxObjectPtr, REXX_VALUE_RexxStemObject, REXX_VALUE_RexxStringObject, REXX_VALUE_RexxVariableReferenceObject, REXX_VALUE_SCOPE, REXX_VALUE_size_t, REXX_VALUE_ssize_t, REXX_VALUE_stringsize_t, REXX_VALUE_SUPER, REXX_VALUE_uint16_t, REXX_VALUE_uint32_t, REXX_VALUE_uint64_t, REXX_VALUE_uint8_t, REXX_VALUE_uintptr_t, REXX_VALUE_wholenumber_t, signedIntegerValue(), SIZE_MAX, SPECIAL_ARGUMENT, SSIZE_MAX, stringArgument(), TheClassClass, TheMutableBufferClass, TheNilObject, ThePointerClass, TheVariableReferenceClass, RexxInternalObject::truthValue(), _ValueDescriptor::type, type, UINT16_MAX, UINT32_MAX, UINT8_MAX, UINTPTR_MAX, unsignedInt64Value(), unsignedIntegerValue(), _ValueDescriptor::value, _ValueDescriptor::value_CSTRING, _ValueDescriptor::value_double, _ValueDescriptor::value_float, _ValueDescriptor::value_int, _ValueDescriptor::value_int16_t, _ValueDescriptor::value_int32_t, _ValueDescriptor::value_int64_t, _ValueDescriptor::value_int8_t, _ValueDescriptor::value_intptr_t, _ValueDescriptor::value_logical_t, _ValueDescriptor::value_POINTER, _ValueDescriptor::value_POINTERSTRING, _ValueDescriptor::value_RexxArrayObject, _ValueDescriptor::value_RexxClassObject, _ValueDescriptor::value_RexxMutableBufferObject, _ValueDescriptor::value_RexxObjectPtr, _ValueDescriptor::value_RexxStemObject, _ValueDescriptor::value_RexxStringObject, _ValueDescriptor::value_RexxVariableReferenceObject, _ValueDescriptor::value_size_t, _ValueDescriptor::value_ssize_t, _ValueDescriptor::value_stringsize_t, _ValueDescriptor::value_uint16_t, _ValueDescriptor::value_uint32_t, _ValueDescriptor::value_uint64_t, _ValueDescriptor::value_uint8_t, _ValueDescriptor::value_uintptr_t, and _ValueDescriptor::value_wholenumber_t.
Referenced by callNativeRoutine(), and run().
raiseCondition()
void NativeActivation::raiseCondition (RexxString * condition, RexxString * description, RexxObject * additional, RexxObject * _result)
Raise a condition on behalf of a native method. This method does not return.
Parameters
condition The condition type to raise.
description The condition description string.
additional The additional information associated with this condition.
result The result object.
Definition at line 2737 of file NativeActivation-trace.cpp.
References activity, OREF_NULL, Activity::raiseCondition(), and result.
reallocateObjectMemory()
void * NativeActivation::reallocateObjectMemory (void * pointer, size_t size)
Rellocate memory in the current object context.
Parameters
pointer The data buffer to reallocate
size The requested memory size.
Returns
The new data pointer.
Definition at line 3672 of file NativeActivation-trace.cpp.
References pointer(), RexxObject::reallocateObjectMemory(), and receiver.
Referenced by ReallocateObjectMemory().
removeLocalReference()
void NativeActivation::removeLocalReference (RexxInternalObject * objr)
Remove an object from the local reference table.
Parameters
objr The object to remove.
Definition at line 1219 of file NativeActivation-trace.cpp.
References firstSavedObject, OREF_NULL, HashCollection::remove(), and saveList.
Referenced by ReleaseLocalReference().
reportSignatureError()
void NativeActivation::reportSignatureError ()
Report a method/function signature error
Definition at line 190 of file NativeActivation-trace.cpp.
References Error_Incorrect_call_signature, Error_Incorrect_method_signature, isMethod(), and reportException().
Referenced by processArguments(), and valueToObject().
reportStemError()
void NativeActivation::reportStemError (size_t position, RexxObject * object)
Report a stem argument error.
Parameters
position The argument position
object The object in error.
Definition at line 202 of file NativeActivation-trace.cpp.
References Error_Incorrect_call_nostem, Error_Incorrect_method_nostem, isMethod(), and reportException().
Referenced by processArguments().
resetNext()
void NativeActivation::resetNext ()
Reset the next state of the variable pool.
Definition at line 2577 of file NativeActivation-trace.cpp.
References iterator, and VariableDictionary::VariableIterator::terminate().
Referenced by disableVariablepool(), dropContextVariable(), enableVariablepool(), getAllContextVariables(), getContextVariable(), getContextVariableReference(), setContextVariable(), and variablePoolGetVariable().
resolveStemVariable()
StemClass * NativeActivation::resolveStemVariable (RexxObject * s)
Resolve an argument object into a stem object. The argument object may already be a stem, or may the a variable name used to resolve a stem.
Parameters
s The source object used for the resolution.
Returns
A resolved stem object. Returns a NULLOBJECT if there is a resolution problem.
Definition at line 2814 of file NativeActivation-trace.cpp.
References getContextStem(), isStem(), OREF_NULL, and stringArgument().
Referenced by ResolveStemVariable().
run() [1/4]
void NativeActivation::run (ActivityDispatcher & dispatcher)
Run a task under the scope of a native activation. This is generally a bootstrapping call, such as a top-level program call, method translation, etc.
Parameters
dispatcher The dispatcher instance we're going to run.
Definition at line 1628 of file NativeActivation-trace.cpp.
References activationType, activity, conditionObj, ActivityManager::currentActivity, DISPATCHER_ACTIVATION, Activity::getActivationLevel(), Activity::getInstanceSecurityManager(), ActivityDispatcher::handleError(), OREF_NULL, Activity::popStackFrame(), Activity::requestAccess(), Activity::restoreActivationLevel(), ActivityDispatcher::run(), securityManager, ActivityDispatcher::setContext(), RexxInternalObject::setHasNoReferences(), and trapErrors.
run() [2/4]
void NativeActivation::run (CallbackDispatcher & dispatcher)
Run a callback under the scope of a native actvation. This is generally a call out, such as a system exit, argument callback, etc.
Parameters
dispatcher The dispatcher instance we're going to run.
Definition at line 1680 of file NativeActivation-trace.cpp.
References activationType, activity, CALLBACK_ACTIVATION, conditionObj, ActivityManager::currentActivity, Activity::getActivationLevel(), Activity::getInstanceSecurityManager(), CallbackDispatcher::handleError(), OREF_NULL, Activity::releaseAccess(), Activity::requestAccess(), Activity::restoreActivationLevel(), CallbackDispatcher::run(), securityManager, CallbackDispatcher::setContext(), and trapErrors.
run() [3/4]
void NativeActivation::run (MethodClass * _method, NativeMethod * _code, RexxObject * _receiver, RexxString * _msgname, RexxObject ** _arglist, size_t _argcount, ProtectedObject & resultObj)
Run a native method or function under the context of this activation.
Parameters
_receiver The receiver object (NULL if not a method invocation).
_msgname The message name.
_argcount The argument count
_arglist The list of arguments.
resultObj The returned result object.
Definition at line 1264 of file NativeActivation-trace.cpp.
References activationType, activity, argCount, argList, RexxMethodContext_::arguments, checkConditions(), MemoryObject::checkUninitQueue(), Activity::createMethodContext(), ActivityManager::currentActivity, ActivationFrame::disableFrame(), ActivationBase::executable, Activity::getActivationLevel(), NativeMethod::getEntry(), Activity::getInstanceSecurityManager(), NativeCode::getSecurityManager(), guardOff(), MaxNativeArguments, memoryObject, messageName, METHOD_ACTIVATION, OREF_NULL, Activity::popStackFrame(), processArguments(), receiver, Activity::releaseAccess(), Activity::requestAccess(), Activity::restoreActivationLevel(), result, securityManager, RexxInternalObject::setHasNoReferences(), MethodContext::threadContext, trapErrors, and valueToObject().
Referenced by dispatch(), NativeMethod::run(), and Activity::run().
run() [4/4]
void NativeActivation::run (TrappingDispatcher & dispatcher)
Run a some type of activity using a fresh activation stack. This generally us a method call such as an uninit method where we wish to run the method and ignore errors. This runs without releasing the kernel lock.
Parameters
dispatcher The dispatcher instance we're going to run.
Definition at line 1731 of file NativeActivation-trace.cpp.
References activationType, activity, conditionObj, ActivityManager::currentActivity, Activity::getActivationLevel(), TrappingDispatcher::handleError(), OREF_NULL, Activity::requestAccess(), Activity::restoreActivationLevel(), TrappingDispatcher::run(), TrappingDispatcher::setContext(), TrappingDispatcher::trapConditions(), trapConditions, trapErrors, and TRAPPING_ACTIVATION.
setConditionInfo() [1/2]
void NativeActivation::setConditionInfo (DirectoryClass * c)
Transfer a trapped condition into an activation context.
Parameters
c The condition object.
Definition at line 2686 of file NativeActivation-trace.cpp.
References conditionName, conditionObj, and DirectoryClass::get().
setConditionInfo() [2/2]
void NativeActivation::setConditionInfo (RexxString * name, DirectoryClass * info) inline
Definition at line 158 of file NativeActivation.hpp.
References conditionName, and conditionObj.
Referenced by Activity::run(), and trap().
setContextVariable()
void NativeActivation::setContextVariable (const char * name, RexxObject * value)
Set a context variable on behalf of an API call.
Parameters
name The name of the variable.
value The variable value.
Definition at line 2929 of file NativeActivation-trace.cpp.
References activation, VariableDictionary::getVariableRetriever(), isString(), new_string(), OREF_NULL, resetNext(), and RexxVariableBase::set().
Referenced by SetContextVariable(), and SetExitContextVariable().
setDigits()
void NativeActivation::setDigits (wholenumber_t _digits) override virtual
Set the digits setting in the calling context.
Parameters
_digits The new digits setting.
Reimplemented from ActivationBase.
Definition at line 2206 of file NativeActivation-trace.cpp.
References activation, OREF_NULL, and RexxActivation::setDigits().
setForm()
void NativeActivation::setForm (bool _form) override virtual
update the numeric form setting in the current call context.
Parameters
_form The new form setting.
Reimplemented from ActivationBase.
Definition at line 2235 of file NativeActivation-trace.cpp.
References activation, OREF_NULL, and RexxActivation::setForm().
setFuzz()
void NativeActivation::setFuzz (wholenumber_t _fuzz) override virtual
Set a new fuzz setting in the current context.
Parameters
_fuzz The new fuzz value.
Reimplemented from ActivationBase.
Definition at line 2220 of file NativeActivation-trace.cpp.
References activation, OREF_NULL, and RexxActivation::setFuzz().
setObjectVariable()
void NativeActivation::setObjectVariable (const char * name, RexxObject * value)
Set an object variable to a new value.
Parameters
name The name of the variable.
value The new variable value.
Definition at line 3058 of file NativeActivation-trace.cpp.
References getObjectVariableRetriever(), methodVariables(), and OREF_NULL.
Referenced by SetObjectVariable().
setStackBase()
void NativeActivation::setStackBase () inline
Definition at line 170 of file NativeActivation.hpp.
References stackBase.
Referenced by Activity::createNewActivationStack().
signedIntegerValue()
wholenumber_t NativeActivation::signedIntegerValue (RexxObject * o, size_t position, wholenumber_t maxValue, wholenumber_t minValue)
Convert a value to a wholenumber value.
Parameters
o The object to convert.
position The argument position.
maxValue The maximum value allowed in the range.
minValue The minimum range value.
Returns
The converted number.
Definition at line 1901 of file NativeActivation-trace.cpp.
References Error_Invalid_argument_range, new_array(), new_integer(), Numerics::objectToSignedInteger(), reportException(), and Numerics::wholenumberToObject().
Referenced by processArguments().
stemSort()
int NativeActivation::stemSort (StemClass * stem, const char * tailExtension, int order, int type, wholenumber_t start, wholenumber_t end, wholenumber_t firstcol, wholenumber_t lastcol)
Perform a sort on stem data. If everything works correctly, this returns zero, otherwise an appropriate error value.
Parameters
stemname The name of the stem variable.
order The sort order (ascending or descending).
type The type of sort.
start The starting element.
end The ending element.
firstcol The first comparison column.
lastcol The last comparison column.
Returns
The completion code.
Definition at line 3567 of file NativeActivation-trace.cpp.
References new_upper_string(), StemClass::sort(), and type.
Referenced by RexxStemSort().
termination()
void NativeActivation::termination () inline override virtual
Reimplemented from ActivationBase.
Definition at line 97 of file NativeActivation.hpp.
References guardOff().
trap()
bool NativeActivation::trap (RexxString * condition, DirectoryClass * exception_object) override virtual
Trap a condition at this level of the activation stack.
Parameters
condition The name of the condition.
exception_object The exception object containing the specifics of the condition.
Returns
false if this activation takes a pass on the condition. Does not return at all if the condition is handled.
Reimplemented from ActivationBase.
Definition at line 2633 of file NativeActivation-trace.cpp.
References captureConditions, RexxString::isEqual(), setConditionInfo(), trapConditions, and trapErrors.
unsignedInt64Value()
uint64_t NativeActivation::unsignedInt64Value (RexxObject * o, size_t position)
Convert a value to a uint64_t value
Parameters
o The object to convert.
position The argument position.
Returns
The converted number.
Definition at line 2008 of file NativeActivation-trace.cpp.
References Error_Invalid_argument_range, IntegerZero, new_array(), new_integer(), Numerics::objectToUnsignedInt64(), reportException(), UINT64_MAX, and Numerics::uint64ToObject().
Referenced by processArguments().
unsignedIntegerValue()
size_t NativeActivation::unsignedIntegerValue (RexxObject * o, size_t position, stringsize_t maxValue)
Convert a value to a size_t value.
Parameters
o The object to convert.
position The argument position.
maxValue The maximum value allowed in the range.
Returns
The converted number.
Definition at line 1966 of file NativeActivation-trace.cpp.
References Error_Invalid_argument_range, IntegerZero, new_array(), new_integer(), Numerics::objectToUnsignedInteger(), reportException(), and Numerics::stringsizeToObject().
Referenced by processArguments().
valuesToObject()
ArrayClass * NativeActivation::valuesToObject (ValueDescriptor * value, size_t count)
Convert an collection of value descriptors into a Rexx array object. This is useful for creating arrays of arguments for the various call APIs.
Parameters
value The self-describing value descriptors.
count The number of descriptors in the list.
Returns
The described value converted to an appropriate Rexx object.
Definition at line 697 of file NativeActivation-trace.cpp.
References new_array(), ArrayClass::put(), and valueToObject().
Referenced by ValuesToObject().
valueToObject()
RexxObject * NativeActivation::valueToObject (ValueDescriptor * value)
Convert an API value descriptor into a Rexx object.
Parameters
value The self-describing value descriptor.
Returns
The described value converted to an appropriate Rexx object.
Definition at line 718 of file NativeActivation-trace.cpp.
References booleanObject(), Numerics::int64ToObject(), new_pointer(), new_string(), OREF_NULL, Numerics::pointerToString(), reportSignatureError(), REXX_VALUE_CSTRING, REXX_VALUE_double, REXX_VALUE_float, REXX_VALUE_int, REXX_VALUE_int16_t, REXX_VALUE_int32_t, REXX_VALUE_int64_t, REXX_VALUE_int8_t, REXX_VALUE_intptr_t, REXX_VALUE_logical_t, REXX_VALUE_nonnegative_wholenumber_t, REXX_VALUE_POINTER, REXX_VALUE_POINTERSTRING, REXX_VALUE_positive_wholenumber_t, REXX_VALUE_RexxArrayObject, REXX_VALUE_RexxClassObject, REXX_VALUE_RexxMutableBufferObject, REXX_VALUE_RexxObjectPtr, REXX_VALUE_RexxStemObject, REXX_VALUE_RexxStringObject, REXX_VALUE_RexxVariableReferenceObject, REXX_VALUE_size_t, REXX_VALUE_ssize_t, REXX_VALUE_stringsize_t, REXX_VALUE_uint16_t, REXX_VALUE_uint32_t, REXX_VALUE_uint64_t, REXX_VALUE_uint8_t, REXX_VALUE_uintptr_t, REXX_VALUE_wholenumber_t, Numerics::stringsizeToObject(), _ValueDescriptor::type, Numerics::uint64ToObject(), _ValueDescriptor::value, _ValueDescriptor::value_CSTRING, _ValueDescriptor::value_double, _ValueDescriptor::value_float, _ValueDescriptor::value_int, _ValueDescriptor::value_int16_t, _ValueDescriptor::value_int32_t, _ValueDescriptor::value_int64_t, _ValueDescriptor::value_int8_t, _ValueDescriptor::value_intptr_t, _ValueDescriptor::value_logical_t, _ValueDescriptor::value_POINTER, _ValueDescriptor::value_RexxObjectPtr, _ValueDescriptor::value_size_t, _ValueDescriptor::value_stringsize_t, _ValueDescriptor::value_uint16_t, _ValueDescriptor::value_uint32_t, _ValueDescriptor::value_uint64_t, _ValueDescriptor::value_uint8_t, _ValueDescriptor::value_uintptr_t, _ValueDescriptor::value_wholenumber_t, and Numerics::wholenumberToObject().
Referenced by callNativeRoutine(), run(), valuesToObject(), and ValueToObject().
variablePoolDropVariable()
void NativeActivation::variablePoolDropVariable (PSHVBLOCK pshvblock)
Perform a variable pool drop operation.
Parameters
pshvblock The operation shared variable block.
Definition at line 3315 of file NativeActivation-trace.cpp.
References activation, RexxVariableBase::drop(), RexxVariableBase::exists(), OREF_NULL, RXSHV_NEWV, RXSHV_SYDRO, _SHVBLOCK::shvcode, _SHVBLOCK::shvret, and variablePoolGetVariable().
Referenced by variablePoolRequest().
variablePoolFetchPrivate()
void NativeActivation::variablePoolFetchPrivate (PSHVBLOCK pshvblock)
Perform a variable pool fetch private operation.
Parameters
pshvblock The operation shared variable block.
Definition at line 3360 of file NativeActivation-trace.cpp.
References activation, copyValue(), Interpreter::getCurrentQueue(), RexxActivation::getProgramArgument(), RexxActivation::getProgramArgumentCount(), Interpreter::getVersionString(), new_integer(), new_string(), RexxString::numberValue(), OREF_NULL, RXSHV_BADN, _SHVBLOCK::shvname, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _SHVBLOCK::shvvaluelen, and RexxActivation::sourceString().
Referenced by variablePoolRequest().
variablePoolFetchVariable()
void NativeActivation::variablePoolFetchVariable (PSHVBLOCK pshvblock)
Perform a variable pool fetch operation.
Parameters
pshvblock The operation shared variable block.
Definition at line 3267 of file NativeActivation-trace.cpp.
References activation, copyValue(), RexxVariableBase::exists(), RexxInternalObject::getValue(), OREF_NULL, RXSHV_NEWV, RXSHV_SYFET, _SHVBLOCK::shvcode, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _SHVBLOCK::shvvaluelen, and variablePoolGetVariable().
Referenced by variablePoolRequest().
variablePoolGetVariable()
RexxVariableBase * NativeActivation::variablePoolGetVariable (PSHVBLOCK pshvblock, bool symbolic)
Get a variable retriever for the target variable.
Parameters
pshvblock The variable pool request block.
symbolic The symbolic vs. direct indicator.
Returns
A variable retriever for the variable. Returns OREF_NULL if the variable is not resolvable from the name.
Definition at line 3223 of file NativeActivation-trace.cpp.
References VariableDictionary::getDirectVariableRetriever(), VariableDictionary::getVariableRetriever(), isString(), new_string(), OREF_NULL, resetNext(), RXSHV_BADN, _SHVBLOCK::shvname, and _SHVBLOCK::shvret.
Referenced by variablePoolDropVariable(), variablePoolFetchVariable(), and variablePoolSetVariable().
variablePoolInterface()
RexxReturnCode NativeActivation::variablePoolInterface (PSHVBLOCK pshvblock)
Handle a request chain for the variable pool interface API.
Parameters
pshvblock The shared variable block for the request.
Returns
The composit return code for the chain of requests.
Definition at line 3178 of file NativeActivation-trace.cpp.
References isVariablePoolEnabled(), RXSHV_MEMFL, RXSHV_NOAVL, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, and variablePoolRequest().
Referenced by RexxVariablePool().
variablePoolNextVariable()
void NativeActivation::variablePoolNextVariable (PSHVBLOCK pshvblock)
Perform a variable pool fetch next operation.
Parameters
pshvblock The operation shared variable block.
Definition at line 3335 of file NativeActivation-trace.cpp.
References copyValue(), fetchNext(), RXSHV_LVAR, _SHVBLOCK::shvname, _SHVBLOCK::shvnamelen, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, and _SHVBLOCK::shvvaluelen.
Referenced by variablePoolRequest().
variablePoolRequest()
void NativeActivation::variablePoolRequest (PSHVBLOCK pshvblock)
Process a single variable pool request.
Parameters
pshvblock The request block for this request.
Definition at line 3430 of file NativeActivation-trace.cpp.
References RXSHV_BADF, RXSHV_DROPV, RXSHV_FETCH, RXSHV_NEXTV, RXSHV_PRIV, RXSHV_SET, RXSHV_SYDRO, RXSHV_SYFET, RXSHV_SYSET, _SHVBLOCK::shvcode, _SHVBLOCK::shvret, variablePoolDropVariable(), variablePoolFetchPrivate(), variablePoolFetchVariable(), variablePoolNextVariable(), and variablePoolSetVariable().
Referenced by variablePoolInterface().
variablePoolSetVariable()
void NativeActivation::variablePoolSetVariable (PSHVBLOCK pshvblock)
Perform a variable pool set operation.
Parameters
pshvblock The operation shared variable block.
Definition at line 3293 of file NativeActivation-trace.cpp.
References activation, RexxVariableBase::exists(), new_string(), OREF_NULL, RXSHV_NEWV, RXSHV_SYSET, RexxVariableBase::set(), _SHVBLOCK::shvcode, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, and variablePoolGetVariable().
Referenced by variablePoolRequest().
willTrap()
bool NativeActivation::willTrap (RexxString * condition) override virtual
Test if a condition is trapped at this level of the activation stack.
Parameters
condition The name of the condition.
Returns
false if this activation takes a pass on the condition, true if this activation will handle the condition. handled.
Reimplemented from ActivationBase.
Definition at line 2705 of file NativeActivation-trace.cpp.
References RexxString::isEqual(), trapConditions, and trapErrors.
Member Data Documentation
activation
RexxActivation* NativeActivation::activation protected
Definition at line 227 of file NativeActivation.hpp.
Referenced by accessCallerContext(), digits(), dropContextVariable(), fetchNext(), findCallerClass(), findRexxContext(), form(), fuzz(), getAllContextVariables(), getContextStem(), getContextVariable(), getContextVariableReference(), getNumericSettings(), getRexxContext(), getRexxContextExecutable(), getRexxContextObject(), live(), liveGeneral(), NativeActivation(), setContextVariable(), setDigits(), setForm(), setFuzz(), variablePoolDropVariable(), variablePoolFetchPrivate(), variablePoolFetchVariable(), and variablePoolSetVariable().
activationType
ActivationType NativeActivation::activationType protected
Definition at line 234 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), isMethod(), and run().
activity
Activity* NativeActivation::activity protected
Definition at line 223 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), checkConditions(), createStackFrame(), fetchNext(), getActivity(), guardOff(), guardOffWhenUpdated(), guardOn(), guardOnWhenUpdated(), guardWait(), live(), liveGeneral(), methodVariables(), NativeActivation(), raiseCondition(), and run().
argArray
ArrayClass* NativeActivation::argArray protected
Definition at line 230 of file NativeActivation.hpp.
Referenced by getArguments(), live(), and liveGeneral().
argCount
size_t NativeActivation::argCount protected
Definition at line 228 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), dispatch(), getArgument(), getArguments(), live(), liveGeneral(), and run().
argList
RexxObject** NativeActivation::argList protected
Definition at line 229 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), dispatch(), getArgument(), getArguments(), live(), liveGeneral(), and run().
captureConditions
bool NativeActivation::captureConditions protected
Definition at line 243 of file NativeActivation.hpp.
Referenced by enableConditionCapture(), enableConditionTrap(), and trap().
code
NativeCode* NativeActivation::code protected
Definition at line 224 of file NativeActivation.hpp.
Referenced by dispatch(), live(), and liveGeneral().
conditionName
RexxString* NativeActivation::conditionName protected
Definition at line 235 of file NativeActivation.hpp.
Referenced by checkCondition(), checkConditions(), clearCondition(), clearException(), live(), liveGeneral(), and setConditionInfo().
conditionObj
DirectoryClass* NativeActivation::conditionObj protected
Definition at line 236 of file NativeActivation.hpp.
Referenced by checkConditions(), clearCondition(), clearException(), getConditionInfo(), live(), liveGeneral(), run(), and setConditionInfo().
firstSavedObject
RexxInternalObject* NativeActivation::firstSavedObject protected
Definition at line 231 of file NativeActivation.hpp.
Referenced by clearLocalReferences(), createLocalReference(), live(), liveGeneral(), and removeLocalReference().
iterator
VariableDictionary::VariableIterator NativeActivation::iterator protected
Definition at line 246 of file NativeActivation.hpp.
Referenced by fetchNext(), and resetNext().
MaxNativeArguments
const size_t NativeActivation::MaxNativeArguments = 16 static
Definition at line 209 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), and run().
messageName
RexxString* NativeActivation::messageName protected
Definition at line 226 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), dispatch(), getMessageName(), live(), liveGeneral(), processArguments(), and run().
objectVariables
VariableDictionary* NativeActivation::objectVariables protected
Definition at line 239 of file NativeActivation.hpp.
Referenced by guardOff(), guardOffWhenUpdated(), guardOn(), guardOnWhenUpdated(), guardWait(), live(), liveGeneral(), and methodVariables().
receiver
RexxObject* NativeActivation::receiver protected
Definition at line 225 of file NativeActivation.hpp.
Referenced by allocateObjectMemory(), callNativeRoutine(), createStackFrame(), cself(), dispatch(), freeObjectMemory(), getReceiver(), getSelf(), getSuper(), guardOn(), live(), liveGeneral(), methodVariables(), processArguments(), reallocateObjectMemory(), and run().
result
RexxObject* NativeActivation::result protected
Definition at line 233 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), checkConditions(), live(), liveGeneral(), raiseCondition(), and run().
saveList
IdentityTable* NativeActivation::saveList protected
Definition at line 232 of file NativeActivation.hpp.
Referenced by clearLocalReferences(), createLocalReference(), live(), liveGeneral(), and removeLocalReference().
securityManager
SecurityManager* NativeActivation::securityManager protected
Definition at line 237 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), live(), liveGeneral(), and run().
stackBase
bool NativeActivation::stackBase protected
Definition at line 240 of file NativeActivation.hpp.
Referenced by isStackBase(), and setStackBase().
trapConditions
bool NativeActivation::trapConditions protected
Definition at line 242 of file NativeActivation.hpp.
Referenced by enableConditionCapture(), enableConditionTrap(), run(), trap(), and willTrap().
trapErrors
bool NativeActivation::trapErrors protected
Definition at line 241 of file NativeActivation.hpp.
Referenced by callNativeRoutine(), callRegisteredRoutine(), checkConditions(), disableConditionTraps(), enableConditionTraps(), run(), trap(), and willTrap().
variablePoolEnabled
bool NativeActivation::variablePoolEnabled protected
Definition at line 244 of file NativeActivation.hpp.
Referenced by disableVariablepool(), enableVariablepool(), and isVariablePoolEnabled().
The documentation for this class was generated from the following files:
NativeActivation.hpp
NativeActivation-trace.cpp
NativeActivation.cpp