ooRexx: SysServerNamedPipeConnectionManager Class Reference
SysServerNamedPipeConnectionManager Class Reference
#include <SysCSNamedPipeStream.hpp>
Public Member Functions
SysServerNamedPipeConnectionManager ()
~SysServerNamedPipeConnectionManager ()
bool disconnect () override
ApiConnection * acceptConnection () override
bool bind ()
Public Member Functions inherited from ServerConnectionManager
ServerConnectionManager ()
virtual ~ServerConnectionManager ()
CSErrorCodeT getError ()
bool isClean ()
Static Public Member Functions
static const char * generatePipeName ()
Protected Attributes
HANDLE serverMutexHandle
Protected Attributes inherited from ServerConnectionManager
CSErrorCodeT errcode
Static Protected Attributes
static const char * userPipeName = NULL
static const char * serverMutexName = NULL
Detailed Description
Base class for all socket-based server connections. The subclasses provide all of the setup around the socket.
Definition at line 70 of file SysCSNamedPipeStream.hpp.
Constructor & Destructor Documentation
SysServerNamedPipeConnectionManager()
SysServerNamedPipeConnectionManager::SysServerNamedPipeConnectionManager () inline
Definition at line 73 of file SysCSNamedPipeStream.hpp.
References generatePipeName().
~SysServerNamedPipeConnectionManager()
SysServerNamedPipeConnectionManager::~SysServerNamedPipeConnectionManager () inline
Definition at line 74 of file SysCSNamedPipeStream.hpp.
Member Function Documentation
acceptConnection()
ApiConnection * SysServerNamedPipeConnectionManager::acceptConnection () override virtual
Accept a connection from a client.
Returns
True on an error, otherwise false
Implements ServerConnectionManager.
Definition at line 246 of file SysCSNamedPipeStream.cpp.
References CSERROR_CONNX_FAILED, CSERROR_OK, ServerConnectionManager::errcode, and userPipeName.
bind()
bool SysServerNamedPipeConnectionManager::bind ()
Bind to the named pipe by creating the first instance of the pipe with the given name.
Returns
true if the pipe could be created successfully, false for any creation failures.
Definition at line 303 of file SysCSNamedPipeStream.cpp.
References CSERROR_CONNX_FAILED, ServerConnectionManager::errcode, generatePipeName(), serverMutexHandle, and serverMutexName.
Referenced by WinMain().
disconnect()
bool SysServerNamedPipeConnectionManager::disconnect () override virtual
Close the connection to the host.
Returns
True on an error, otherwise false.
Reimplemented from ServerConnectionManager.
Definition at line 328 of file SysCSNamedPipeStream.cpp.
References CSERROR_OK, ServerConnectionManager::errcode, serverMutexHandle, serverMutexName, and userPipeName.
generatePipeName()
const char * SysServerNamedPipeConnectionManager::generatePipeName () static
Generate a unique string to be used for interprocess communications for this userid. Also generates the unique mutex name used to ensure only one instance exists.
Returns
A unique identifier used to create the named pipes.
Definition at line 359 of file SysCSNamedPipeStream.cpp.
References SysProcess::getUserID(), MAX_USERID_LENGTH, serverMutexName, and userPipeName.
Referenced by bind(), and SysServerNamedPipeConnectionManager().
Member Data Documentation
serverMutexHandle
HANDLE SysServerNamedPipeConnectionManager::serverMutexHandle protected
Definition at line 87 of file SysCSNamedPipeStream.hpp.
Referenced by bind(), and disconnect().
serverMutexName
const char * SysServerNamedPipeConnectionManager::serverMutexName = NULL static protected
Definition at line 85 of file SysCSNamedPipeStream.hpp.
Referenced by bind(), disconnect(), and generatePipeName().
userPipeName
const char * SysServerNamedPipeConnectionManager::userPipeName = NULL static protected
Definition at line 84 of file SysCSNamedPipeStream.hpp.
Referenced by acceptConnection(), disconnect(), and generatePipeName().
The documentation for this class was generated from the following files:
SysCSNamedPipeStream.hpp
SysCSNamedPipeStream.cpp