ooRexx: NumberString Class Reference
NumberString Class Reference
#include <NumberStringClass.hpp>
Classes
class NumberBuilder
Public Types
enum ArithmeticOperator {
OT_PLUS , OT_MINUS , OT_MULTIPLY , OT_DIVIDE ,
OT_INT_DIVIDE , OT_REMAINDER , OT_POWER , OT_MAX ,
OT_MIN
}
Public Types inherited from NumberStringBase
enum NumberFlag { NumberFormScientific , NumberRounded }
Public Member Functions
void * operator new (size_t, size_t)
void operator delete (void *)
NumberString (size_t)
NumberString (size_t, size_t)
NumberString (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
HashCode getHashValue () override
bool numberValue (wholenumber_t &result, wholenumber_t precision) override
bool numberValue (wholenumber_t &result) override
bool unsignedNumberValue (size_t &result, wholenumber_t precision) override
bool unsignedNumberValue (size_t &result) override
bool doubleValue (double &result) override
NumberString * numberString () override
RexxInteger * integerValue (wholenumber_t) override
RexxString * makeString () override
ArrayClass * makeArray () override
bool hasMethod (RexxString *) override
RexxString * primitiveMakeString () override
RexxString * stringValue () override
bool truthValue (RexxErrorCodes) override
bool logicalValue (logical_t &) override
bool isEqual (RexxInternalObject *) override
void processUnknown (RexxErrorCodes error, RexxString *, RexxObject **, size_t, ProtectedObject &) override
wholenumber_t compareTo (RexxInternalObject *) override
wholenumber_t strictComp (RexxObject *)
wholenumber_t comp (RexxObject *, size_t fuzz)
RexxObject * equal (RexxObject *)
RexxObject * strictEqual (RexxObject *)
RexxObject * notEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *)
RexxObject * isGreaterThan (RexxObject *)
RexxObject * isLessThan (RexxObject *)
RexxObject * isGreaterOrEqual (RexxObject *)
RexxObject * isLessOrEqual (RexxObject *)
RexxObject * strictGreaterThan (RexxObject *)
RexxObject * strictLessThan (RexxObject *)
RexxObject * strictGreaterOrEqual (RexxObject *)
RexxObject * strictLessOrEqual (RexxObject *)
RexxObject * hashCode ()
NumberString * clone ()
void setString (RexxString *)
RexxString * formatRexx (RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxString * formatInternal (wholenumber_t, wholenumber_t, wholenumber_t, wholenumber_t, NumberString *, wholenumber_t, bool)
RexxObject * operatorNot (RexxObject *)
RexxObject * evaluate (RexxActivation *, ExpressionStack *) override
RexxObject * getValue (RexxActivation *context) override
RexxObject * getValue (VariableDictionary *dictionary) override
RexxObject * getRealValue (RexxActivation *) override
RexxObject * getRealValue (VariableDictionary *) override
bool isInstanceOf (RexxClass *) override
RexxObject * trunc (RexxObject *)
RexxObject * truncInternal (wholenumber_t)
RexxObject * floor ()
RexxObject * floorInternal ()
RexxObject * ceiling ()
RexxObject * ceilingInternal ()
RexxObject * round ()
RexxObject * roundInternal ()
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxClass * classObject ()
NumberString * checkNumber (wholenumber_t digits)
void checkLostDigits (wholenumber_t digits)
NumberString * operatorArgument (RexxObject *right)
NumberString * prepareNumber (wholenumber_t, bool)
NumberString * prepareOperatorNumber (wholenumber_t, wholenumber_t, bool)
NumberString * copyIfNecessary ()
NumberString * copyForCurrentSettings ()
void adjustPrecision (char *, wholenumber_t)
void adjustPrecision ()
void checkPrecision ()
void setNumericSettings (wholenumber_t digits, bool form)
bool isScientific ()
bool isEngineering ()
void setupNumber ()
void setupNumber (wholenumber_t digits, bool form)
bool createUnsignedValue (const char *thisnum, size_t intlength, int carry, wholenumber_t exponent, size_t maxValue, size_t &result)
bool createUnsignedInt64Value (const char *thisnum, size_t intlength, int carry, wholenumber_t exponent, uint64_t maxValue, uint64_t &result)
bool checkIntegerDigits (wholenumber_t numDigits, wholenumber_t &numberLength, wholenumber_t &numberExponent, bool &carry)
bool int64Value (int64_t *result, wholenumber_t numDigits)
bool unsignedInt64Value (uint64_t *result, wholenumber_t numDigits)
void formatInt64 (int64_t integer)
void formatUnsignedInt64 (uint64_t integer)
NumberString * addSub (NumberString *, ArithmeticOperator, wholenumber_t)
NumberString * plus (RexxObject *)
NumberString * minus (RexxObject *)
NumberString * multiply (RexxObject *)
NumberString * divide (RexxObject *)
NumberString * integerDivide (RexxObject *)
NumberString * remainder (RexxObject *)
NumberString * modulo (RexxObject *)
NumberString * power (RexxObject *)
NumberString * Multiply (NumberString *)
NumberString * Division (NumberString *, ArithmeticOperator)
NumberString * abs ()
RexxInteger * Sign ()
RexxObject * notOp ()
NumberString * Max (RexxObject **, size_t)
NumberString * Min (RexxObject **, size_t)
NumberString * maxMin (RexxObject **, size_t, ArithmeticOperator)
bool isInteger ()
RexxString * d2c (RexxObject *)
RexxString * d2x (RexxObject *)
RexxString * d2xD2c (RexxObject *, bool)
RexxString * concat (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * orOp (RexxObject *)
RexxObject * andOp (RexxObject *)
RexxObject * xorOp (RexxObject *)
bool parseNumber (const char *number, size_t length)
void formatNumber (wholenumber_t integer)
void formatUnsignedNumber (size_t)
void setZero ()
bool isZero ()
bool isOne ()
bool isNegative ()
bool isPositive ()
bool isAllInteger ()
bool hasDecimals ()
bool hasSignificantDecimals (wholenumber_t digits)
void formatExponent (wholenumber_t exponent, char *buffer)
Public Member Functions inherited from NumberStringBase
NumberStringBase ()
NumberStringBase (bool opt)
void mathRound (char *)
char * stripLeadingZeros (char *)
char * adjustNumber (char *, char *, wholenumber_t, wholenumber_t)
void truncateToDigits (wholenumber_t digits, char *digitsPtr, bool round)
void checkOverflow ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
RexxInternalObject * copy () override
HashCode hash () override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
HashCode identityHash ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static NumberString * newInstanceFromDouble (double)
static NumberString * newInstanceFromDouble (double, wholenumber_t)
static NumberString * newInstanceFromFloat (float)
static NumberString * newInstanceFromWholenumber (wholenumber_t)
static NumberString * newInstanceFromInt64 (int64_t)
static NumberString * newInstanceFromUint64 (uint64_t)
static NumberString * newInstanceFromStringsize (size_t)
static NumberString * newInstance (const char *, size_t)
static void createInstance ()
static size_t highBits (size_t)
static void subtractNumbers (NumberString *larger, const char *largerPtr, wholenumber_t aLargerExp, NumberString *smaller, const char *smallerPtr, wholenumber_t aSmallerExp, NumberString *result, char *&resultPtr)
static char * addMultiplier (const char *, wholenumber_t, char *, int)
static char * subtractDivisor (const char *data1, wholenumber_t length1, const char *data2, wholenumber_t length2, char *result, int Mult)
static char * multiplyPower (const char *leftPtr, NumberStringBase *left, const char *rightPtr, NumberStringBase *right, char *OutPtr, wholenumber_t OutLen, wholenumber_t NumberDigits)
static char * dividePower (const char *AccumPtr, NumberStringBase *Accum, char *Output, wholenumber_t NumberDigits)
static char * addToBaseSixteen (int, char *, char *)
static char * addToBaseTen (int, char *, char *)
static char * multiplyBaseSixteen (char *, char *)
static char * multiplyBaseTen (char *, char *)
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes
char numberDigits [4]
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Static Public Attributes
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
static const size_t OVERFLOWSPACE = 2
static const size_t BYTE_SIZE = 8
static const size_t SIZEBITS = (sizeof(size_t) * BYTE_SIZE)
static const bool ROUND = true
static const bool NOROUND = false
static const size_t HIBIT = ~SSIZE_MAX
static const size_t LOWBITS = SSIZE_MAX
static const size_t FAST_BUFFER = 48
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Additional Inherited Members
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Protected Attributes inherited from NumberStringBase
RexxString * stringObject
FlagSet< NumberFlag, 16 > numFlags
short numberSign
wholenumber_t createdDigits
wholenumber_t numberExponent
wholenumber_t digitsCount
Detailed Description
The "Full Monty" NumberString. This implements most of the functions, and directly includes the string data.
Definition at line 96 of file NumberStringClass.hpp.
Member Enumeration Documentation
ArithmeticOperator
enum NumberString::ArithmeticOperator
Identifiers for different arithmetic operators.
Enumerator
OT_PLUS
OT_MINUS
OT_MULTIPLY
OT_DIVIDE
OT_INT_DIVIDE
OT_REMAINDER
OT_POWER
OT_MAX
OT_MIN
Definition at line 102 of file NumberStringClass.hpp.
Constructor & Destructor Documentation
NumberString() [1/3]
NumberString::NumberString (size_t len)
Constructor for a new number string value.
Parameters
len The length we require for the value.
Definition at line 83 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, number_digits(), number_form(), NumberStringBase::numberSign, and setNumericSettings().
NumberString() [2/3]
NumberString::NumberString (size_t len, size_t precision)
Create a number string for a given digits precision
Parameters
len The length of value we need to accomodate
precision The precision to be used for formatting.
Definition at line 97 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, number_form(), NumberStringBase::numberSign, and setNumericSettings().
NumberString() [3/3]
NumberString::NumberString (RESTORETYPE restoreType) inline
Definition at line 193 of file NumberStringClass.hpp.
Member Function Documentation
abs()
NumberString * NumberString::abs ()
Return the absolute value of a number
Returns
The absolute value result.
Definition at line 3700 of file NumberStringClass.cpp.
References copyForCurrentSettings(), copyIfNecessary(), isPositive(), and NumberStringBase::numberSign.
Referenced by RexxInteger::abs(), and MemoryObject::createImage().
addMultiplier()
char * NumberString::addMultiplier (const char * top, wholenumber_t topLen, char * accumPtr, int multChar) static
Multiply current digit through "top" number and add result to the accumulator.
Parameters
top the pointer to the top number first digit
topLen The length of the top number.
accumPtr The pointer to the last digit of the accumulator.
multChar The character to multiply by.
Returns
The new accumulator top bounds.
Definition at line 66 of file NumberStringMath2.cpp.
Referenced by Multiply(), and multiplyPower().
addSub()
NumberString * NumberString::addSub (NumberString * other, ArithmeticOperator operation, wholenumber_t digits)
Add or subtract two normalized numbers
Parameters
other The other number for the operation.
operation The operation identifier (addtion or subtraction)
digits The digits this operation is being performed under.
Returns
The operation result.
Definition at line 574 of file NumberStringMath.cpp.
References adjustPrecision(), clone(), NumberStringBase::digitsCount, FAST_BUFFER, isZero(), new_buffer(), new_numberstring(), numberDigits, NumberStringBase::numberExponent, NumberStringBase::numberSign, OREF_NULL, OT_MINUS, OT_PLUS, reportCondition(), setupNumber(), setZero(), and subtractNumbers().
Referenced by comp(), minus(), and plus().
addToBaseSixteen()
char * NumberString::addToBaseSixteen (int digit, char * value, char * highDigit) static
Adds a base ten digit to string number in base 16 (used by the d2x and d2c functions)
Parameters
digit The digit to add.
value The number we're adding to.
highDigit The highest digit location
Returns
The new highest digit location if this carrys out.
Definition at line 1188 of file NumberStringMath.cpp.
Referenced by d2xD2c().
addToBaseTen()
char * NumberString::addToBaseTen (int digit, char * accum, char * highDigit) static
Adds a base sixteen digit to a string number base 10 (used by the x2d and c2d functions)
Parameters
digit The base-16 digit to add.
accum The accumulator pointer.
highDigit The highest digit of our result so far.
Returns
The new highest digit position.
Definition at line 1274 of file NumberStringMath.cpp.
Referenced by RexxString::x2dC2d().
adjustPrecision() [1/2]
void NumberString::adjustPrecision ()
Adjust the precision of a number to the digits setting it was created under.
Definition at line 365 of file NumberStringMath.cpp.
References NumberStringBase::checkOverflow(), NumberStringBase::createdDigits, NumberStringBase::digitsCount, numberDigits, setZero(), and NumberStringBase::truncateToDigits().
Referenced by checkPrecision().
adjustPrecision() [2/2]
void NumberString::adjustPrecision (char * resultPtr, wholenumber_t digits)
Adjust the precision of a number to the given digits. Also copies the data to the start of the number string buffer after adjustment.
Parameters
resultPtr The start of the digits data to process.
digits The precision for making the adjustment.
Definition at line 448 of file NumberStringMath.cpp.
References NumberStringBase::checkOverflow(), NumberStringBase::digitsCount, NumberStringBase::mathRound(), number_form(), numberDigits, NumberStringBase::numberExponent, setNumericSettings(), setZero(), and NumberStringBase::stripLeadingZeros().
Referenced by addSub(), Division(), and Multiply().
andOp()
RexxObject * NumberString::andOp (RexxObject * operand)
Definition at line 3129 of file NumberStringClass.cpp.
References RexxString::andOp(), and stringValue().
Referenced by MemoryObject::createImage().
ceiling()
RexxObject * NumberString::ceiling ()
Return the ceiling value for a decimal numeric value. The ceiling is the first full number value greater that the current value. If the number has no significant decimal positions, this returns the same value (minus any trailing decimal zeros). NOTE: If the number is negative, the value goes toward the higher number (e.g., the ceiling of -3.5 is -3, not -4).
Returns
The numeric ceiling of this value.
Definition at line 1712 of file NumberStringClass.cpp.
References ceilingInternal(), number_digits(), prepareNumber(), and ROUND.
Referenced by RexxInteger::ceiling(), and MemoryObject::createImage().
ceilingInternal()
RexxObject * NumberString::ceilingInternal ()
Calculate the ceiling value for a number.
Returns
A string value of the ceiling, with appropriate formatting for the function.
Definition at line 1723 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, hasDecimals(), IntegerOne, IntegerZero, isNegative(), isZero(), numberDigits, NumberStringBase::numberExponent, and truncInternal().
Referenced by ceiling().
checkIntegerDigits()
bool NumberString::checkIntegerDigits (wholenumber_t numDigits, wholenumber_t & length, wholenumber_t & exponent, bool & carry)
Check that a numberstring is convertable into an integer value
Parameters
numDigits The digits() setting for the check.
numberLength The length of the value (which can be updated by the check)
numberExponent The exponent value (also updatable)
carry A carry out flag.
Returns
true if this can be converted to an integer, false if it fails.
Definition at line 937 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, numberDigits, and NumberStringBase::numberExponent.
Referenced by int64Value(), numberValue(), unsignedInt64Value(), and unsignedNumberValue().
checkLostDigits()
void NumberString::checkLostDigits (wholenumber_t digits)
Test for whether a LOSTDIGITS condition needs to be raised.
Parameters
digits The digits setting to test.
Definition at line 3174 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, and reportCondition().
Referenced by comp().
checkNumber()
NumberString* NumberString::checkNumber (wholenumber_t digits) inline
Definition at line 262 of file NumberStringClass.hpp.
References NumberStringBase::digitsCount, NOROUND, and prepareOperatorNumber().
Referenced by Division(), and Multiply().
checkPrecision()
void NumberString::checkPrecision () inline
Definition at line 283 of file NumberStringClass.hpp.
References adjustPrecision(), NumberStringBase::createdDigits, and NumberStringBase::digitsCount.
Referenced by setupNumber().
classObject()
RexxClass * NumberString::classObject ()
Return the String class object for numberstring instances
Returns
Always returns the String class.
Definition at line 3971 of file NumberStringClass.cpp.
References TheStringClass.
Referenced by MemoryObject::createImage().
clone()
NumberString * NumberString::clone ()
Special clone code for a number string object.
Returns
A new numberstring with extra fields nulled out.
Definition at line 110 of file NumberStringClass.cpp.
References RexxInternalObject::clone(), OREF_NULL, and NumberStringBase::stringObject.
Referenced by addSub(), copyForCurrentSettings(), copyIfNecessary(), Division(), prepareNumber(), and prepareOperatorNumber().
comp()
wholenumber_t NumberString::comp (RexxObject * right, size_t fuzz)
To a comparison test for two number strings for non-strict comparisons.
Parameters
right The other comparison value.
fuzz The fuzz value for the comparison.
Returns
A value < 0 when this is smaller than the other. A value 0 when this is equal to the other A value > 0 when this is greater than the other.
Definition at line 3194 of file NumberStringClass.cpp.
References addSub(), ARG_ONE, checkLostDigits(), NumberStringBase::digitsCount, isZero(), number_digits(), numberDigits, NumberStringBase::numberExponent, NumberStringBase::numberSign, RexxInternalObject::numberString(), OREF_NULL, OT_MINUS, RexxInternalObject::requestString(), requiredArgument(), RexxString::stringComp(), and stringValue().
Referenced by RexxString::comp(), RexxInteger::comp(), equal(), isGreaterOrEqual(), isGreaterThan(), isLessOrEqual(), isLessThan(), maxMin(), and notEqual().
compareTo()
wholenumber_t NumberString::compareTo (RexxInternalObject * other) override virtual
Wrapper around the compareTo() method that does string sort comparisons.
Parameters
other The other comparison object
Returns
-1, 0, 1 depending on the comparison result.
Reimplemented from RexxInternalObject.
Definition at line 3061 of file NumberStringClass.cpp.
References RexxString::compareTo(), and stringValue().
concat()
RexxString * NumberString::concat (RexxObject * other)
Definition at line 3119 of file NumberStringClass.cpp.
References RexxString::concatRexx(), and stringValue().
concatBlank()
RexxString * NumberString::concatBlank (RexxObject * other)
Definition at line 3114 of file NumberStringClass.cpp.
References RexxString::concatBlank(), and stringValue().
copyForCurrentSettings()
NumberString * NumberString::copyForCurrentSettings ()
Perform conditional rounding of a number value.
Parameters
digits The current digits value.
form The current form.
Returns
Either the same numberstring value or a new one.
Definition at line 3685 of file NumberStringClass.cpp.
References clone(), number_digits(), number_form(), and setupNumber().
Referenced by abs().
copyIfNecessary()
NumberString * NumberString::copyIfNecessary ()
Perform conditional rounding of a number value.
Parameters
digits The current digits value.
form The current form.
Returns
Either the same numberstring value or a new one.
Definition at line 3652 of file NumberStringClass.cpp.
References clone(), NumberStringBase::createdDigits, NumberStringBase::digitsCount, isScientific(), number_digits(), number_form(), and setupNumber().
Referenced by abs(), and Sign().
createInstance()
void NumberString::createInstance () static
Create initial class object at bootstrap time.
Definition at line 72 of file NumberStringClass.cpp.
References CLASS_CREATE_SPECIAL.
Referenced by MemoryObject::createImage().
createUnsignedInt64Value()
bool NumberString::createUnsignedInt64Value (const char * thisnum, size_t intlength, int carry, wholenumber_t exponent, uint64_t maxValue, uint64_t & result)
Convert the numberstring to unsigned INT64 value
Parameters
thisnum The digits for the conversion.
intlength The number of digits to process.
carry A potential carried out digit.
exponent The exponent value for the number.
maxValue The maximum value for the conversion.
result The returned conversion value.
Returns
true if this converted, false otherwise.
Definition at line 863 of file NumberStringClass.cpp.
References Numerics::DIGITS64.
Referenced by int64Value(), and unsignedInt64Value().
createUnsignedValue()
bool NumberString::createUnsignedValue (const char * thisnum, size_t intlength, int carry, wholenumber_t exponent, size_t maxValue, size_t & result)
Convert the numberstring to unsigned value
Parameters
thisnum The number digits.
intlength The length of the digits to process
carry The returned carry flag if this rounds out.
exponent The current exponent.
maxValue The maximum value for this conversion.
result The returned result.
Returns
true if this converted, false for any failures.
Definition at line 788 of file NumberStringClass.cpp.
References Numerics::ARGUMENT_DIGITS.
Referenced by numberValue(), and unsignedNumberValue().
d2c()
RexxString * NumberString::d2c (RexxObject * length)
Convert a valid numberstring to a character string.
Parameters
length The output length (required for negative numbers)
Returns
The converted value.
Definition at line 3886 of file NumberStringClass.cpp.
References d2xD2c().
Referenced by MemoryObject::createImage().
d2x()
RexxString * NumberString::d2x (RexxObject * length)
Convert a valid numberstring to a hex string.
Parameters
length The output length (required if this is a negative number)
Returns
The converted object.
Definition at line 3872 of file NumberStringClass.cpp.
References d2xD2c().
Referenced by MemoryObject::createImage().
d2xD2c()
RexxString * NumberString::d2xD2c (RexxObject * length, bool type)
Convert a valid numberstring to a hex or character string.
Parameters
length The output length (required for negative numbers).
type The type of conversion (hex or character)
Returns
The converted value.
Definition at line 64 of file NumberStringMath.cpp.
References addToBaseSixteen(), ARG_ONE, NumberStringBase::digitsCount, Error_Incorrect_method_d2c, Error_Incorrect_method_d2x, Error_Incorrect_method_d2xd2c, hasDecimals(), hasSignificantDecimals(), RexxString::intToHexDigit(), isNegative(), multiplyBaseSixteen(), new_buffer(), new_string(), number_digits(), numberDigits, NumberStringBase::numberExponent, optionalLengthArgument(), OVERFLOWSPACE, StringUtil::packHex(), reportException(), SIZE_MAX, and type.
Referenced by RexxInteger::d2c(), RexxString::d2c(), d2c(), RexxInteger::d2x(), RexxString::d2x(), and d2x().
divide()
NumberString * NumberString::divide (RexxObject * right)
Divide two numbers
Parameters
right The operator divisor
Returns
The division result.
Definition at line 3571 of file NumberStringClass.cpp.
References Division(), operatorArgument(), and OT_DIVIDE.
Referenced by MemoryObject::createImage().
dividePower()
char * NumberString::dividePower (const char * accumPtr, NumberStringBase * accum, char * output, wholenumber_t digits) static
Invert number from the power operation when a negative power is used.
Parameters
accumPtr The accumulator number.
accum The accumulator number
output The output buffer location.
digits The digits count we're operating under.
Returns
Definition at line 1059 of file NumberStringMath2.cpp.
References NumberStringBase::digitsCount, new_buffer(), NumberStringBase::numberExponent, NumberStringBase::stripLeadingZeros(), and subtractDivisor().
Referenced by power().
Division()
NumberString * NumberString::Division (NumberString * other, ArithmeticOperator divOP)
Divide two numbers
Parameters
other The left-hand-side of the division operation.
DivOP The type of division operation (divide, integer divide, or remainder)
Returns
The division result.
Definition at line 331 of file NumberStringMath2.cpp.
References adjustPrecision(), checkNumber(), clone(), NumberStringBase::digitsCount, Error_Invalid_whole_number_intdiv, Error_Invalid_whole_number_rem, Error_Overflow_zero, FAST_BUFFER, IntegerZero, isZero(), NumberStringBase::mathRound(), new_buffer(), new_integer(), NOROUND, number_digits(), numberDigits, NumberStringBase::numberExponent, NumberStringBase::numberSign, OT_DIVIDE, OT_INT_DIVIDE, OT_REMAINDER, prepareOperatorNumber(), reportException(), Numerics::REXXINTEGER_DIGITS, setupNumber(), NumberStringBase::stripLeadingZeros(), and subtractDivisor().
Referenced by divide(), integerDivide(), modulo(), and remainder().
doubleValue()
bool NumberString::doubleValue (double & result) override virtual
Convert a number string to a double value.
Parameters
result The returned conversion value.
Returns
true if this converted, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 704 of file NumberStringClass.cpp.
References RexxString::getStringData(), and stringValue().
Referenced by RexxString::doubleValue().
equal()
RexxObject * NumberString::equal (RexxObject * other)
non-strict "=" operator
Parameters
other The other object for comparison.
Returns
The comparison result.
Definition at line 3336 of file NumberStringClass.cpp.
References booleanObject(), comp(), number_fuzz(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
evaluate()
RexxObject * NumberString::evaluate (RexxActivation * context, ExpressionStack * stack) override virtual
Polymorphic method that makes numberstring a polymorphic expression term for literals
Parameters
context The current execution context.
stack The current expression stack.
Returns
The evaluated result.
Reimplemented from RexxInternalObject.
Definition at line 3901 of file NumberStringClass.cpp.
References ExpressionStack::push(), RexxActivation::TRACE_PREFIX_LITERAL, and RexxActivation::traceIntermediate().
flatten()
void NumberString::flatten (Envelope * envelope) override virtual
Flatten the object contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxObject.
Definition at line 162 of file NumberStringClass.cpp.
References cleanUpFlatten, flattenRef, setUpFlatten, and NumberStringBase::stringObject.
floor()
RexxObject * NumberString::floor ()
Return the floor value for a decimal numeric value. The floor is the first full number value less that the current value. If the number has no significant decimal positions, this returns the same value (minus any trailing decimal zeros). NOTE: If the number is negative, the value goes toward the lower number (e.g., the floor of -3.5 is -4, not -3).
Returns
The numeric floor of this value.
Definition at line 1578 of file NumberStringClass.cpp.
References floorInternal(), number_digits(), prepareNumber(), and ROUND.
Referenced by MemoryObject::createImage(), and RexxInteger::floor().
floorInternal()
RexxObject * NumberString::floorInternal ()
Calculate the floor value for a number.
Returns
A string value of the floor, with appropriate formatting for the function.
Definition at line 1591 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, IntegerMinusOne, IntegerZero, isPositive(), isZero(), numberDigits, NumberStringBase::numberExponent, and truncInternal().
Referenced by floor().
formatExponent()
void NumberString::formatExponent (wholenumber_t exponent, char * buffer)
Format an exponent value into a buffer, including the "E" marker and the exponent sign.
Parameters
exponent The exponent value.
buffer The buffer for formatting.
Definition at line 290 of file NumberStringClass.cpp.
References Numerics::formatWholeNumber().
Referenced by stringValue().
formatInt64()
void NumberString::formatInt64 (int64_t integer)
Format a 64-bit number into a numberstring.
Parameters
integer The value to format.
Definition at line 2944 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, numberDigits, NumberStringBase::numberSign, and setZero().
Referenced by newInstanceFromInt64().
formatInternal()
RexxString * NumberString::formatInternal (wholenumber_t integers, wholenumber_t decimals, wholenumber_t mathexp, wholenumber_t exptrigger, NumberString * original, wholenumber_t digits, bool form)
Format the numberstring data according to the format function controls.
Parameters
integers The space allocated for the integers.
decimals The space allocated for the decimals.
mathexp The space allocated for the exponent.
exptrigger The exponent trigger value.
original The original numberstring we're formatting from (used for error reporting)
digits The digits value we're formatting to.
form The required ENGINEERING/SCIENTIFIC form.
Returns
The formatted number.
Definition at line 1989 of file NumberStringClass.cpp.
References NumberString::NumberBuilder::addDecimalPart(), NumberString::NumberBuilder::addExponentSign(), NumberString::NumberBuilder::addIntegerPart(), NumberString::NumberBuilder::addSpaces(), NumberString::NumberBuilder::addZeros(), NumberString::NumberBuilder::append(), NumberStringBase::digitsCount, Error_Incorrect_method_before_oversize, Error_Incorrect_method_exponent_oversize, Numerics::FORM_ENGINEERING, Numerics::formatWholeNumber(), isNegative(), NumberStringBase::mathRound(), numberDigits, NumberStringBase::numberExponent, NumberStringBase::numberSign, raw_string(), and reportException().
Referenced by formatRexx().
formatNumber()
void NumberString::formatNumber (wholenumber_t integer)
Create a numberstring object from a whole number value.
Parameters
integer The integer value.
Definition at line 2892 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, Numerics::normalizeWholeNumber(), numberDigits, NumberStringBase::numberSign, and setZero().
Referenced by newInstanceFromWholenumber().
formatRexx()
RexxString * NumberString::formatRexx (RexxObject * Integers, RexxObject * Decimals, RexxObject * MathExp, RexxObject * ExpTrigger)
Format the numberstring data according to the format function controls.
Parameters
Integers The size of the integer section.
Decimals The size of the decimals section.
MathExp The size allocated to the exponent.
ExpTrigger The exponent trigger size.
Returns
the formatted number.
Definition at line 1960 of file NumberStringClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, formatInternal(), number_digits(), number_form(), optionalNonNegative(), prepareNumber(), and ROUND.
Referenced by MemoryObject::createImage(), and RexxInteger::format().
formatUnsignedInt64()
void NumberString::formatUnsignedInt64 (uint64_t integer)
Format an unsigned 64-bit integer num into a numberstring.
Parameters
integer The integer value.
Definition at line 3002 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, numberDigits, and setZero().
Referenced by newInstanceFromUint64().
formatUnsignedNumber()
void NumberString::formatUnsignedNumber (size_t integer)
Format the integer num into a numberstring.
Parameters
integer The unsigned integer value.
Definition at line 2913 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, Numerics::formatStringSize(), numberDigits, NumberStringBase::numberSign, and setZero().
Referenced by newInstanceFromStringsize().
getHashValue()
HashCode NumberString::getHashValue () override virtual
Get the primitive hash value of this String object.
Returns
The calculated string hash for the string.
Reimplemented from RexxInternalObject.
Definition at line 125 of file NumberStringClass.cpp.
References RexxString::getHashValue(), and stringValue().
getRealValue() [1/2]
RexxObject * NumberString::getRealValue (RexxActivation * context) override virtual
Polymorphic get_value function used with expression terms
Parameters
context The evaluation context.
Returns
Just directly returns the number string.
Reimplemented from RexxInternalObject.
Definition at line 3945 of file NumberStringClass.cpp.
getRealValue() [2/2]
RexxObject * NumberString::getRealValue (VariableDictionary * context) override virtual
Polymorphic get_value function used with expression terms
Parameters
context The evaluation context.
Returns
Just directly returns the number string.
Reimplemented from RexxInternalObject.
Definition at line 3959 of file NumberStringClass.cpp.
getValue() [1/2]
RexxObject * NumberString::getValue (RexxActivation * context) override virtual
Polymorphic get_value function used with expression terms
Parameters
context The evaluation context.
Returns
Just directly returns the number string.
Reimplemented from RexxInternalObject.
Definition at line 3917 of file NumberStringClass.cpp.
getValue() [2/2]
RexxObject * NumberString::getValue (VariableDictionary * context) override virtual
Polymorphic get_value function used with expression terms
Parameters
context The evaluation context.
Returns
Just directly returns the number string.
Reimplemented from RexxInternalObject.
Definition at line 3931 of file NumberStringClass.cpp.
hasDecimals()
bool NumberString::hasDecimals () inline
Definition at line 367 of file NumberStringClass.hpp.
References NumberStringBase::numberExponent.
Referenced by ceilingInternal(), d2xD2c(), and hasSignificantDecimals().
hashCode()
RexxObject * NumberString::hashCode ()
Exported version of the HASHCODE method for retrieving the object's hash.
Returns
A string version of the hash (generally holds binary characters).
Definition at line 3399 of file NumberStringClass.cpp.
References RexxObject::hash(), and new_string().
Referenced by MemoryObject::createImage().
hasMethod()
bool NumberString::hasMethod (RexxString * methodName) override virtual
Handle a HASMETHOD request for a numberstring. Since this class is hidden, we get the string value and return its hasmethod result.
Parameters
methodName The target method name.
Returns
The hasmethod result.
Reimplemented from RexxObject.
Definition at line 217 of file NumberStringClass.cpp.
References RexxObject::hasMethod(), and stringValue().
hasSignificantDecimals()
bool NumberString::hasSignificantDecimals (wholenumber_t digits)
Test if a number has any significant (i.e., non-zero) decimal values within a given digits setting.
Parameters
digits The digits setting to test.
Returns
true if this number has significant decimals.
Definition at line 248 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, hasDecimals(), numberDigits, and NumberStringBase::numberExponent.
Referenced by d2xD2c().
highBits()
size_t NumberString::highBits (size_t number) static
Determine high order bit position of an unsigned number setting.
Parameters
number The number we're checking
Returns
The index position of the high bit.
Definition at line 395 of file NumberStringMath.cpp.
References HIBIT, and SIZEBITS.
Referenced by power().
instanceMethod()
MethodClass * NumberString::instanceMethod (RexxString * method_name) override virtual
Retrieve the method instance for an object's defined method.
Parameters
method_name The method name.
Returns
The method object that implements the object method.
Reimplemented from RexxObject.
Definition at line 3090 of file NumberStringClass.cpp.
References RexxObject::instanceMethod(), and stringValue().
instanceMethods()
SupplierClass * NumberString::instanceMethods (RexxClass * class_object) override virtual
Return a supplier containing the methods implemented by an object. Depending on the argument, this is either A) all of the methods, B) just the explicitly set instance methods, or C) the methods provided by a given class.
Parameters
class_object The target class object (optional).
Returns
A supplier with the appropriate method set.
Reimplemented from RexxObject.
Definition at line 3107 of file NumberStringClass.cpp.
References RexxObject::instanceMethods(), and stringValue().
int64Value()
bool NumberString::int64Value (int64_t * result, wholenumber_t numDigits)
Convert a number string to a signed int64 value
Parameters
result The returned result.
numDigits The digits value for the conversion.
Returns
true if this converted ok, false otherwise.
Definition at line 1024 of file NumberStringClass.cpp.
References checkIntegerDigits(), createUnsignedInt64Value(), NumberStringBase::digitsCount, INT64_MAX, INT64_MIN, numberDigits, NumberStringBase::numberExponent, and NumberStringBase::numberSign.
Referenced by Numerics::int64Object(), Numerics::objectToInt64(), Numerics::objectToSignedInteger(), and Numerics::objectToWholeNumber().
integerDivide()
NumberString * NumberString::integerDivide (RexxObject * right)
Integer division between two numbers
Parameters
right The division operand.
Returns
The division result.
Definition at line 3587 of file NumberStringClass.cpp.
References Division(), operatorArgument(), and OT_INT_DIVIDE.
Referenced by MemoryObject::createImage().
integerValue()
RexxInteger * NumberString::integerValue (wholenumber_t digits) override virtual
convert a number string to an integer object
Parameters
digits The digits setting for the conversion.
Returns
The value converted into an Integer object, or .nil if it does not convert.
Reimplemented from RexxInternalObject.
Definition at line 762 of file NumberStringClass.cpp.
References new_integer(), numberValue(), and TheNilObject.
Referenced by RexxString::integerValue().
isAllInteger()
bool NumberString::isAllInteger () inline
Definition at line 366 of file NumberStringClass.hpp.
References NumberStringBase::numberExponent.
Referenced by stringValue().
isEngineering()
bool NumberString::isEngineering () inline
Definition at line 298 of file NumberStringClass.hpp.
References NumberStringBase::NumberFormScientific, and NumberStringBase::numFlags.
Referenced by plus(), and stringValue().
isEqual()
bool NumberString::isEqual (RexxInternalObject * other) override virtual
Primitive strict equal\not equal method. This determines only strict equality, not greater or less than values.
Parameters
other The other object.
Returns
true if they are equal, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 3148 of file NumberStringClass.cpp.
References RexxString::isEqual(), and stringValue().
isGreaterOrEqual()
RexxObject * NumberString::isGreaterOrEqual (RexxObject * other)
Definition at line 3382 of file NumberStringClass.cpp.
References comp(), CompareOperator, and number_fuzz().
Referenced by MemoryObject::createImage().
isGreaterThan()
RexxObject * NumberString::isGreaterThan (RexxObject * other)
Definition at line 3372 of file NumberStringClass.cpp.
References comp(), CompareOperator, and number_fuzz().
Referenced by MemoryObject::createImage().
isInstanceOf()
bool NumberString::isInstanceOf (RexxClass * other) override virtual
Override for the normal isinstanceof method. This version allows the NumberStringClass to "lie" about being a string.
Parameters
other The comparison class
Returns
True if the string value is an instance of the target class.
Reimplemented from RexxObject.
Definition at line 3076 of file NumberStringClass.cpp.
References RexxObject::isInstanceOf(), and stringValue().
isInteger()
bool NumberString::isInteger ()
This method determines if the formatted numberstring is a true integer string. That is, its not of the form 1.00E3 but 1000
Returns
true if this can be represented as a true whole number value, false otherwise.
Definition at line 3821 of file NumberStringClass.cpp.
References NumberStringBase::createdDigits, NumberStringBase::digitsCount, numberDigits, NumberStringBase::numberExponent, and NumberStringBase::numberSign.
Referenced by StringUtil::dataType(), and modulo().
isLessOrEqual()
RexxObject * NumberString::isLessOrEqual (RexxObject * other)
Definition at line 3387 of file NumberStringClass.cpp.
References comp(), CompareOperator, and number_fuzz().
Referenced by MemoryObject::createImage().
isLessThan()
RexxObject * NumberString::isLessThan (RexxObject * other)
Definition at line 3377 of file NumberStringClass.cpp.
References comp(), CompareOperator, and number_fuzz().
Referenced by MemoryObject::createImage().
isNegative()
bool NumberString::isNegative () inline
Definition at line 364 of file NumberStringClass.hpp.
References NumberStringBase::numberSign.
Referenced by NumberString::NumberBuilder::addExponentSign(), NumberString::NumberBuilder::addSign(), ceilingInternal(), d2xD2c(), formatInternal(), roundInternal(), stringValue(), truncInternal(), unsignedInt64Value(), and unsignedNumberValue().
isOne()
bool NumberString::isOne () inline
Definition at line 363 of file NumberStringClass.hpp.
References NumberStringBase::digitsCount, numberDigits, NumberStringBase::numberExponent, and NumberStringBase::numberSign.
Referenced by logicalValue(), notOp(), operatorNot(), and truthValue().
isPositive()
bool NumberString::isPositive () inline
Definition at line 365 of file NumberStringClass.hpp.
References NumberStringBase::numberSign.
Referenced by abs(), and floorInternal().
isScientific()
bool NumberString::isScientific () inline
Definition at line 297 of file NumberStringClass.hpp.
References NumberStringBase::NumberFormScientific, and NumberStringBase::numFlags.
Referenced by copyIfNecessary(), and plus().
isZero()
bool NumberString::isZero () inline
Definition at line 362 of file NumberStringClass.hpp.
References NumberStringBase::numberSign.
Referenced by addSub(), ceilingInternal(), comp(), Division(), floorInternal(), logicalValue(), Multiply(), notOp(), numberValue(), operatorNot(), power(), roundInternal(), stringValue(), truncInternal(), truthValue(), unsignedInt64Value(), and unsignedNumberValue().
live()
void NumberString::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxObject.
Definition at line 138 of file NumberStringClass.cpp.
References memory_mark, and NumberStringBase::stringObject.
liveGeneral()
void NumberString::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxObject.
Definition at line 150 of file NumberStringClass.cpp.
References memory_mark_general, and NumberStringBase::stringObject.
logicalValue()
bool NumberString::logicalValue (logical_t & result) override virtual
Convert an object to a logical value without raising an error.
Parameters
result The converted value.
Returns
true if this converted ok, false for an invalid logical.
Reimplemented from RexxInternalObject.
Definition at line 1234 of file NumberStringClass.cpp.
References isOne(), and isZero().
makeArray()
ArrayClass * NumberString::makeArray () override virtual
Override for the default object makearray method.
Returns
The results of our string representation's makearray.
Reimplemented from RexxInternalObject.
Definition at line 202 of file NumberStringClass.cpp.
References RexxString::makeArray(), and stringValue().
makeString()
RexxString * NumberString::makeString () override virtual
Handle a REQUEST('STRING') request for a REXX numberstring
Returns
Return the backing string value.
Reimplemented from RexxInternalObject.
Definition at line 191 of file NumberStringClass.cpp.
References stringValue().
Max()
NumberString * NumberString::Max (RexxObject ** args, size_t argCount)
Process MAX function
Parameters
args The array of other comparison arguments.
argCount The count of the arguments.
Returns
The largest of the numbers.
Definition at line 3794 of file NumberStringClass.cpp.
References maxMin(), and OT_MAX.
Referenced by MemoryObject::createImage(), and RexxInteger::Max().
maxMin()
NumberString * NumberString::maxMin (RexxObject ** args, size_t argCount, ArithmeticOperator operation)
Process the MAX and MIN builtin functions and methods
Parameters
args The variable length array of arguments.
argCount The count of arguments.
operation Indicates which function we are processing.
Returns
The largest or smallest of the set of numbers.
Definition at line 240 of file NumberStringMath.cpp.
References comp(), Error_Incorrect_call_noarg, Error_Incorrect_method_number, RexxInternalObject::nextObject(), number_digits(), number_fuzz(), RexxInternalObject::numberString(), OREF_NULL, OT_MAX, prepareNumber(), prepareOperatorNumber(), reportException(), and ROUND.
Referenced by Max(), and Min().
Min()
NumberString * NumberString::Min (RexxObject ** args, size_t argCount)
Process Min function
Parameters
args The array of other comparison arguments.
argCount The count of the arguments.
Returns
The smallest of the numbers.
Definition at line 3808 of file NumberStringClass.cpp.
References maxMin(), and OT_MIN.
Referenced by MemoryObject::createImage(), and RexxInteger::Min().
minus()
NumberString * NumberString::minus (RexxObject * right)
Subtraction between two numbers
Parameters
right The subtraction argument.
Returns
The subtraction result.
Definition at line 3528 of file NumberStringClass.cpp.
References addSub(), number_digits(), NumberStringBase::numberSign, operatorArgument(), OREF_NULL, OT_MINUS, prepareOperatorNumber(), and ROUND.
Referenced by MemoryObject::createImage().
modulo()
NumberString * NumberString::modulo (RexxObject * divisorObj)
Perform modulo operation for two numbers. There is no universal agreement how to calculate modulo for floating point arguments or for negative divisors, so we restrict the dividend to a whole number and the divisor to a positive whole number.
Parameters
right The divisor object.
Returns
The module result.
Definition at line 3622 of file NumberStringClass.cpp.
References ARG_ONE, Division(), Error_Incorrect_method_positive, Error_Incorrect_method_string_no_whole_number, isInteger(), NumberStringBase::numberSign, RexxInternalObject::numberString(), OREF_NULL, OT_REMAINDER, plus(), reportException(), and requiredArgument().
Referenced by MemoryObject::createImage().
Multiply()
NumberString * NumberString::Multiply (NumberString * other)
Multiply two NumberString objects
Parameters
other The other object.
Returns
A new numberstring that is the product of the two number strings.
Definition at line 106 of file NumberStringMath2.cpp.
References addMultiplier(), adjustPrecision(), checkNumber(), NumberStringBase::digitsCount, FAST_BUFFER, if(), isZero(), new_buffer(), new_numberstring(), number_digits(), numberDigits, NumberStringBase::numberExponent, and NumberStringBase::numberSign.
Referenced by multiply().
multiply()
NumberString * NumberString::multiply (RexxObject * right)
Multiply operation.
Parameters
right the other operand
Returns
The multiplication result.
Definition at line 3555 of file NumberStringClass.cpp.
References Multiply(), and operatorArgument().
Referenced by MemoryObject::createImage().
multiplyBaseSixteen()
char * NumberString::multiplyBaseSixteen (char * accum, char * highDigit) static
multiplies a base 16 number by decimal 10, placing the result in the same buffer.
Parameters
Accum The current accumulator position.
HighDigit The current high digit location for the number.
Returns
The new high digit location.
Definition at line 1224 of file NumberStringMath.cpp.
Referenced by d2xD2c().
multiplyBaseTen()
char * NumberString::multiplyBaseTen (char * accum, char * highDigit) static
multiplys a base 16 number by 10, placing the number in the same buffer
Parameters
Accum The current accumulator position
HighDigit The high digit of the result.
Returns
The new high digit position.
Definition at line 1308 of file NumberStringMath.cpp.
Referenced by RexxString::x2dC2d().
multiplyPower()
char * NumberString::multiplyPower (const char * leftPtr, NumberStringBase * left, const char * rightPtr, NumberStringBase * right, char * outPtr, wholenumber_t outLen, wholenumber_t digits) static
Multiply numbers for the power operation
Parameters
leftPtr The left number data
left The left number numberstring data
rightPtr The right pointer data
right The right number numberstring info.
outPtr The ouput pointer.
outLen The output buffer length
digits the current digits setting
Returns
The pointer to the new start of the accumulator data.
Definition at line 1005 of file NumberStringMath2.cpp.
References addMultiplier(), NumberStringBase::digitsCount, NumberStringBase::numberExponent, and NumberStringBase::numberSign.
Referenced by power().
newInstance()
NumberString * NumberString::newInstance (const char * number, size_t len) static
Create a new number string object from a character string value.
Parameters
number The number character data.
len The number length.
Returns
A new number string object.
Definition at line 4003 of file NumberStringClass.cpp.
References numberStringScan(), OREF_NULL, parseNumber(), and setZero().
Referenced by new_numberstring().
newInstanceFromDouble() [1/2]
NumberString * NumberString::newInstanceFromDouble (double number) static
Create a NumberString from a double value
Parameters
number The number to convert.
Returns
A numberstring object representing this number.
Definition at line 4058 of file NumberStringClass.cpp.
References number_digits().
Referenced by new_numberstringFromDouble(), and newInstanceFromFloat().
newInstanceFromDouble() [2/2]
NumberString * NumberString::newInstanceFromDouble (double number, wholenumber_t precision) static
Create a numberstring from a double value using a given formatting precision.
Parameters
number The double number to convert
precision The precision to apply to the result.
Returns
The formatted number, as a numberstring value.
Definition at line 4073 of file NumberStringClass.cpp.
References parseNumber(), prepareNumber(), and ROUND.
newInstanceFromFloat()
NumberString * NumberString::newInstanceFromFloat (float num) static
Create a numberstring object from a floating point number
Parameters
num The source number.
Returns
The number string object.
Definition at line 4045 of file NumberStringClass.cpp.
References newInstanceFromDouble(), and number_digits().
Referenced by new_numberstringFromFloat().
newInstanceFromInt64()
NumberString * NumberString::newInstanceFromInt64 (int64_t integer) static
Create a NumberString object from a signed 64 bit number
Parameters
integer The integer value to convert.
Returns
A numberstring value for this.
Definition at line 4168 of file NumberStringClass.cpp.
References Numerics::DIGITS64, and formatInt64().
Referenced by new_numberstringFromInt64().
newInstanceFromStringsize()
NumberString * NumberString::newInstanceFromStringsize (size_t integer) static
Create a NumberString object from a size_t value
Parameters
integer The integer to convert.
Returns
The numberstring value.
Definition at line 4151 of file NumberStringClass.cpp.
References Numerics::ARGUMENT_DIGITS, and formatUnsignedNumber().
Referenced by new_numberstringFromStringsize().
newInstanceFromUint64()
NumberString * NumberString::newInstanceFromUint64 (uint64_t integer) static
Create a NumberString object from an unsigned 64 bit number
Parameters
integer The integer value to convert.
Returns
A new numberstring for the value.
Definition at line 4184 of file NumberStringClass.cpp.
References Numerics::DIGITS64, and formatUnsignedInt64().
Referenced by new_numberstringFromUint64().
newInstanceFromWholenumber()
NumberString * NumberString::newInstanceFromWholenumber (wholenumber_t integer) static
Create a NumberString object from a wholenumber_t value
Parameters
integer The value to convert.
Returns
A NumberString object for this value.
Definition at line 4134 of file NumberStringClass.cpp.
References Numerics::ARGUMENT_DIGITS, and formatNumber().
Referenced by new_numberstringFromWholenumber().
notEqual()
RexxObject * NumberString::notEqual (RexxObject * other)
non-strict "\=" operator
Parameters
other The other comparison value.
Returns
The compare result.
Definition at line 3353 of file NumberStringClass.cpp.
References booleanObject(), comp(), number_fuzz(), TheNilObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
notOp()
RexxObject * NumberString::notOp ()
Logical not of a number string value
Returns
The logical inversion result.
Definition at line 3739 of file NumberStringClass.cpp.
References isOne(), isZero(), RexxString::notOp(), stringValue(), TheFalseObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
numberString()
NumberString* NumberString::numberString () inline override virtual
Convert a primitive internal object to a number string equivalent.
Returns
A number string object representation for the object or .nil
Reimplemented from RexxInternalObject.
Definition at line 206 of file NumberStringClass.hpp.
Referenced by StringUtil::dataType().
numberValue() [1/2]
bool NumberString::numberValue (wholenumber_t & result) override virtual
Convert a number string to a wholenumber value under the default digits.
Parameters
result The returned converted number.
Returns
true if this could be converted, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 517 of file NumberStringClass.cpp.
References Numerics::DEFAULT_DIGITS, and numberValue().
numberValue() [2/2]
bool NumberString::numberValue (wholenumber_t & result, wholenumber_t numDigits) override virtual
Convert a number string to a number value
Parameters
result The returned result.
numDigits The precision used for the conversion.
Returns
The converted value.
Reimplemented from RexxInternalObject.
Definition at line 546 of file NumberStringClass.cpp.
References checkIntegerDigits(), createUnsignedValue(), NumberStringBase::digitsCount, isZero(), Numerics::maxValueForDigits(), numberDigits, NumberStringBase::numberExponent, and NumberStringBase::numberSign.
Referenced by integerValue(), numberValue(), and RexxString::numberValue().
operator delete()
void NumberString::operator delete (void *) inline
Definition at line 189 of file NumberStringClass.hpp.
operator new()
void * NumberString::operator new (size_t size, size_t length)
Allocate memory for a new numberstring object.
Parameters
size The base object size.
length The number of digits to allocate space for.
Returns
Storage for an object.
Definition at line 3986 of file NumberStringClass.cpp.
References new_object(), RexxInternalObject::setHasNoReferences(), and T_NumberString.
operatorArgument()
NumberString * NumberString::operatorArgument (RexxObject * right)
Common method used to process the right-side arguments for arithmetic operators.
Parameters
right The right-hand-side of the operator.
Returns
The converted numberstring value.
Definition at line 3470 of file NumberStringClass.cpp.
References ARG_ONE, Error_Conversion_operator, RexxInternalObject::numberString(), OREF_NULL, reportException(), and requiredArgument().
Referenced by divide(), integerDivide(), minus(), multiply(), plus(), and remainder().
operatorNot()
RexxObject * NumberString::operatorNot (RexxObject * right)
Logical not of a number string value (operator method version)
Parameters
right Dummy unused argument just to have the same signature as other operators.
Returns
The logical inversion result.
Definition at line 3766 of file NumberStringClass.cpp.
References isOne(), isZero(), RexxString::notOp(), stringValue(), TheFalseObject, and TheTrueObject.
orOp()
RexxObject * NumberString::orOp (RexxObject * operand)
Definition at line 3124 of file NumberStringClass.cpp.
References RexxString::orOp(), and stringValue().
Referenced by MemoryObject::createImage().
parseNumber()
bool NumberString::parseNumber (const char * number, size_t length)
Format a string value into a numberString object.
Parameters
number The source character string.
length The length of the character string.
Returns
true if this was a valid number, false for an invalid number.
Definition at line 2586 of file NumberStringClass.cpp.
References NumberStringBuilder::addDecimalDigit(), NumberStringBuilder::addExponentDigit(), NumberStringBuilder::addIntegerDigit(), RexxString::ch_MINUS, RexxString::ch_NINE, RexxString::ch_PERIOD, RexxString::ch_PLUS, RexxString::ch_SPACE, RexxString::ch_TAB, RexxString::ch_ZERO, NumberStringBuilder::finish(), StringScanner::getChar(), StringScanner::moreChars(), NUMBER_DIGIT, NUMBER_E, NUMBER_EDIGIT, NUMBER_ESIGN, NUMBER_POINT, NUMBER_SIGN, NUMBER_SIGN_WHITESPACE, NUMBER_SPOINT, NUMBER_START, NUMBER_TRAILING_WHITESPACE, NumberStringBuilder::setExponentSign(), NumberStringBuilder::setSign(), and StringScanner::stepPosition().
Referenced by newInstance(), and newInstanceFromDouble().
plus()
NumberString * NumberString::plus (RexxObject * right)
Add two number strings
Parameters
right The other string to add.
Returns
The addition result.
Definition at line 3490 of file NumberStringClass.cpp.
References addSub(), NumberStringBase::createdDigits, Numerics::FORM_ENGINEERING, Numerics::FORM_SCIENTIFIC, isEngineering(), isScientific(), number_digits(), number_form(), operatorArgument(), OREF_NULL, OT_PLUS, prepareOperatorNumber(), ROUND, and NumberStringBase::stringObject.
Referenced by MemoryObject::createImage(), StringUtil::dataType(), and modulo().
power()
NumberString * NumberString::power (RexxObject * powerObj)
Perform the Arithmetic power operation
Parameters
PowerObj The power we're raising this number to.
Returns
The power result.
Definition at line 811 of file NumberStringMath2.cpp.
References NumberStringBase::adjustNumber(), ARG_ONE, NumberStringBase::digitsCount, dividePower(), Error_Invalid_whole_number_power, Error_Overflow_overflow, Error_Overflow_power, HIBIT, highBits(), IntegerOne, IntegerZero, isZero(), LOWBITS, NumberStringBase::mathRound(), Numerics::MAX_EXPONENT, multiplyPower(), new_buffer(), NOROUND, number_digits(), numberDigits, NumberStringBase::numberExponent, NumberStringBase::numberSign, RexxInternalObject::numberValue(), prepareOperatorNumber(), reportException(), requiredArgument(), SIZEBITS, and NumberStringBase::stripLeadingZeros().
Referenced by MemoryObject::createImage().
prepareNumber()
NumberString * NumberString::prepareNumber (wholenumber_t digits, bool rounding)
Create new copy of supplied object and make sure the number is computed to correct digits setting
Parameters
NumberDigits The precision we're at.
rounding true if we should round, false if we just truncate.
Returns
The new number that is now safe for modification and also rounded to the current digits setting.
Definition at line 511 of file NumberStringMath.cpp.
References clone(), NumberStringBase::digitsCount, number_form(), numberDigits, setNumericSettings(), and NumberStringBase::truncateToDigits().
Referenced by ceiling(), floor(), formatRexx(), maxMin(), newInstanceFromDouble(), round(), and trunc().
prepareOperatorNumber()
NumberString * NumberString::prepareOperatorNumber (wholenumber_t targetLength, wholenumber_t digits, bool rounding)
Prepare an operator numberstring to a given length, raising a LOSTDIGITS condition if the starting number will cause lost digits
Parameters
targetLength The target preparation length (>= numberDigits)
digits The digits setting used to determine LOSTDIGITS conditions
rounding Inidicates whether rounding is to be performed if the target object is longer than the targetLength
Returns
A new number object no longer than the target length.
Definition at line 544 of file NumberStringMath.cpp.
References clone(), NumberStringBase::digitsCount, number_form(), reportCondition(), and setNumericSettings().
Referenced by checkNumber(), Division(), maxMin(), minus(), plus(), and power().
primitiveMakeString()
RexxString * NumberString::primitiveMakeString () override virtual
primitive level string conversion request.
Returns
The object's string value
Reimplemented from RexxInternalObject.
Definition at line 228 of file NumberStringClass.cpp.
References OREF_NULL, NumberStringBase::stringObject, and stringValue().
processUnknown()
void NumberString::processUnknown (RexxErrorCodes error, RexxString * messageName, RexxObject ** arguments, size_t count, ProtectedObject & result) override virtual
Process an unknown message condition on an object. This is an optimized bypass for the Object default method that can bypass creating an array for the arguments and sending the UNKNOWN message to the object. Since many things funnel through the integer unknown method, this is a big optimization.
Parameters
messageName The target message name.
arguments The message arguments.
count The count of arguments.
result The return result protected object.
Reimplemented from RexxObject.
Definition at line 3046 of file NumberStringClass.cpp.
References RexxObject::messageSend(), and stringValue().
remainder()
NumberString * NumberString::remainder (RexxObject * right)
Remainder division between two numbers
Parameters
right The right side of the operator
Returns
The remainder of the division.
Definition at line 3603 of file NumberStringClass.cpp.
References Division(), operatorArgument(), and OT_REMAINDER.
Referenced by MemoryObject::createImage().
round()
RexxObject * NumberString::round ()
Round the number value depending on the value of the first decimal position using standard rounding rules. NOTE: this uses the same rules for floor and ceiling when determining how things are rounded. This is really defined as floor(number + .5). Thus 3.4 and -3.4 round to 3 and -3, since they end up calculating floor(3.9) and floor(-2.9), repectively.
Returns
The rounded value
Definition at line 1843 of file NumberStringClass.cpp.
References number_digits(), prepareNumber(), ROUND, and roundInternal().
Referenced by MemoryObject::createImage(), and RexxInteger::round().
roundInternal()
RexxObject * NumberString::roundInternal ()
Calculate the rounded number value.
Returns
A string value of the rounded number.
Definition at line 1853 of file NumberStringClass.cpp.
References NumberStringBase::digitsCount, IntegerMinusOne, IntegerOne, IntegerZero, isNegative(), isZero(), numberDigits, NumberStringBase::numberExponent, and truncInternal().
Referenced by round().
setNumericSettings()
void NumberString::setNumericSettings (wholenumber_t digits, bool form) inline
Definition at line 284 of file NumberStringClass.hpp.
References NumberStringBase::createdDigits, Numerics::FORM_SCIENTIFIC, NumberStringBase::NumberFormScientific, and NumberStringBase::numFlags.
Referenced by adjustPrecision(), NumberString(), prepareNumber(), prepareOperatorNumber(), and setupNumber().
setString()
void NumberString::setString (RexxString * stringObj)
Set the number string's string value
Parameters
stringObj The formatted string value.
Definition at line 178 of file NumberStringClass.cpp.
References setField, RexxInternalObject::setHasReferences(), and NumberStringBase::stringObject.
Referenced by RexxString::numberString(), and stringValue().
setupNumber() [1/2]
void NumberString::setupNumber () inline
Definition at line 300 of file NumberStringClass.hpp.
References checkPrecision(), number_digits(), number_form(), and setNumericSettings().
Referenced by addSub(), copyForCurrentSettings(), copyIfNecessary(), and Division().
setupNumber() [2/2]
void NumberString::setupNumber (wholenumber_t digits, bool form) inline
Definition at line 308 of file NumberStringClass.hpp.
References checkPrecision(), and setNumericSettings().
setZero()
void NumberString::setZero () inline
Definition at line 354 of file NumberStringClass.hpp.
References NumberStringBase::digitsCount, numberDigits, NumberStringBase::numberExponent, and NumberStringBase::numberSign.
Referenced by addSub(), adjustPrecision(), NumberStringBuilder::finish(), formatInt64(), formatNumber(), formatUnsignedInt64(), formatUnsignedNumber(), and newInstance().
Sign()
RexxInteger * NumberString::Sign ()
Return the sign of a number
Returns
The sign value, as an integer.
Definition at line 3723 of file NumberStringClass.cpp.
References copyIfNecessary(), new_integer(), and NumberStringBase::numberSign.
Referenced by MemoryObject::createImage().
strictComp()
wholenumber_t NumberString::strictComp (RexxObject * other)
strict comparison of two objects.
Parameters
other The other object.
Returns
The string compare result returned by the string representation.
Definition at line 3162 of file NumberStringClass.cpp.
References RexxString::primitiveStrictComp(), and stringValue().
Referenced by strictEqual(), strictGreaterOrEqual(), strictGreaterThan(), strictLessOrEqual(), strictLessThan(), and strictNotEqual().
strictEqual()
RexxObject * NumberString::strictEqual (RexxObject * other)
Perform the primitive level "==" compare
Parameters
other The other for comparison.
Returns
The compare result.
Definition at line 3414 of file NumberStringClass.cpp.
References booleanObject(), strictComp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
strictGreaterOrEqual()
RexxObject * NumberString::strictGreaterOrEqual (RexxObject * other)
Definition at line 3451 of file NumberStringClass.cpp.
References CompareOperator, and strictComp().
Referenced by MemoryObject::createImage().
strictGreaterThan()
RexxObject * NumberString::strictGreaterThan (RexxObject * other)
Definition at line 3441 of file NumberStringClass.cpp.
References CompareOperator, and strictComp().
Referenced by MemoryObject::createImage().
strictLessOrEqual()
RexxObject * NumberString::strictLessOrEqual (RexxObject * other)
Definition at line 3456 of file NumberStringClass.cpp.
References CompareOperator, and strictComp().
Referenced by MemoryObject::createImage().
strictLessThan()
RexxObject * NumberString::strictLessThan (RexxObject * other)
Definition at line 3446 of file NumberStringClass.cpp.
References CompareOperator, and strictComp().
Referenced by MemoryObject::createImage().
strictNotEqual()
RexxObject * NumberString::strictNotEqual (RexxObject * other)
Strict inequality operation
Parameters
other The other value for comparison.
Returns
The comparison result.
Definition at line 3431 of file NumberStringClass.cpp.
References booleanObject(), strictComp(), TheNilObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
stringValue()
RexxString * NumberString::stringValue () override virtual
Convert a number string to a string object
Returns
The formatted string version of this number string.
Reimplemented from RexxObject.
Definition at line 338 of file NumberStringClass.cpp.
References NumberString::NumberBuilder::addDecimalPart(), NumberString::NumberBuilder::addExponent(), NumberString::NumberBuilder::addIntegerPart(), NumberStringBase::checkOverflow(), NumberStringBase::createdDigits, Numerics::DEFAULT_DIGITS, NumberStringBase::digitsCount, Error_Overflow_expoverflow, Error_Overflow_expunderflow, formatExponent(), isAllInteger(), isEngineering(), isNegative(), isZero(), Numerics::MAX_EXPONENT, numberDigits, NumberStringBase::numberExponent, OREF_NULL, raw_string(), reportException(), RexxString::setNumberString(), setString(), and NumberStringBase::stringObject.
Referenced by andOp(), comp(), compareTo(), concat(), concatBlank(), doubleValue(), getHashValue(), hasMethod(), instanceMethod(), instanceMethods(), isEqual(), isInstanceOf(), makeArray(), makeString(), RexxString::newString(), notOp(), operatorNot(), orOp(), primitiveMakeString(), processUnknown(), strictComp(), and xorOp().
subtractDivisor()
char * NumberString::subtractDivisor (const char * divisor, wholenumber_t divisorLength, const char * dividend, wholenumber_t dividendLength, char * result, int mult) static
Perform a subtraction during division.
Parameters
data1 The data to subtract from.
length1 The length of the string subtract from.
data2 The dividend string.
length2 The length of the dividend.
result The location to place the subtraction result.
mult The multiplier for the subtraction.
Returns
the pointer to the first character of the result.
Definition at line 224 of file NumberStringMath2.cpp.
Referenced by dividePower(), and Division().
subtractNumbers()
void NumberString::subtractNumbers (NumberString * larger, const char * largerPtr, wholenumber_t adjustedLargerExp, NumberString * smaller, const char * smallerPtr, wholenumber_t adjustedSmallerExp, NumberString * result, char *& resultPtr) static
Subtract two numbers. The second number is subtracted from the first. The absolute value of the 1st number must be larger than the absolute value of the second.
Parameters
larger The pointer to the larger number.
largerPtr The larger number digits pointer.
adjustedLargerExp The adjusted exponent for the larger number.
smaller The smaller number value.
smallerPtr The pointer to the digit data for the smaller number.
adjustedSmallerExp The adjusted exponent for the smaller number.
result The result number.
resultPtr The pointer for writing the result data.
Definition at line 1062 of file NumberStringMath.cpp.
References NumberStringBase::digitsCount, and numberDigits.
Referenced by addSub().
trunc()
RexxObject * NumberString::trunc (RexxObject * decimal_digits)
Truncate a number to given decimal digit count
Parameters
decimal_digits The optional count (default is 0 decimals)
Returns
The truncated number.
Definition at line 1395 of file NumberStringClass.cpp.
References ARG_ONE, number_digits(), optionalNonNegative(), prepareNumber(), ROUND, and truncInternal().
Referenced by MemoryObject::createImage(), and RexxInteger::trunc().
truncInternal()
RexxObject * NumberString::truncInternal (wholenumber_t needed_digits)
Truncate a number to given decimal digit count
Parameters
needed_digits The required number of decimals.
Returns
The truncated number.
Definition at line 1413 of file NumberStringClass.cpp.
References NumberString::NumberBuilder::addDecimalPart(), NumberString::NumberBuilder::addIntegerPart(), NumberString::NumberBuilder::addZeroDecimal(), NumberString::NumberBuilder::addZeros(), NumberStringBase::digitsCount, IntegerZero, isNegative(), isZero(), new_integer(), numberDigits, NumberStringBase::numberExponent, raw_string(), and Numerics::REXXINTEGER_DIGITS.
Referenced by ceilingInternal(), floorInternal(), roundInternal(), and trunc().
truthValue()
bool NumberString::truthValue (RexxErrorCodes errorcode) override virtual
Return a truth value boolean for a number string
Parameters
errorcode The error to raise if this is not valid.
Returns
true or false if this is a valid logical.
Reimplemented from RexxInternalObject.
Definition at line 1206 of file NumberStringClass.cpp.
References isOne(), isZero(), and reportException().
unsignedInt64Value()
bool NumberString::unsignedInt64Value (uint64_t * result, wholenumber_t numDigits)
Convert a number string to an unsigned int64 value
Parameters
result The returned result.
numDigits The digis setting for the conversion.
Returns
true if the value converted, false otherwise.
Definition at line 1132 of file NumberStringClass.cpp.
References checkIntegerDigits(), createUnsignedInt64Value(), NumberStringBase::digitsCount, isNegative(), isZero(), numberDigits, NumberStringBase::numberExponent, and UINT64_MAX.
Referenced by Numerics::objectToStringSize(), Numerics::objectToUnsignedInt64(), and Numerics::objectToUnsignedInteger().
unsignedNumberValue() [1/2]
bool NumberString::unsignedNumberValue (size_t & result) override virtual
Convert a number string to an unsigned whole number value
Parameters
result The converted value.
Returns
true if this converted ok, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 531 of file NumberStringClass.cpp.
References Numerics::DEFAULT_DIGITS, and unsignedNumberValue().
unsignedNumberValue() [2/2]
bool NumberString::unsignedNumberValue (size_t & result, wholenumber_t numDigits) override virtual
Convert a number string to an unsigned number value
Parameters
result The returned result.
numDigits The precision for converting this value.
Returns
true if the number could be converted, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 632 of file NumberStringClass.cpp.
References checkIntegerDigits(), createUnsignedValue(), NumberStringBase::digitsCount, isNegative(), isZero(), Numerics::maxValueForDigits(), numberDigits, and NumberStringBase::numberExponent.
Referenced by unsignedNumberValue(), and RexxString::unsignedNumberValue().
xorOp()
RexxObject * NumberString::xorOp (RexxObject * operand)
Definition at line 3134 of file NumberStringClass.cpp.
References stringValue(), and RexxString::xorOp().
Referenced by MemoryObject::createImage().
Member Data Documentation
BYTE_SIZE
const size_t NumberString::BYTE_SIZE = 8 static
Definition at line 401 of file NumberStringClass.hpp.
classInstance
RexxClass * NumberString::classInstance = OREF_NULL static
Definition at line 384 of file NumberStringClass.hpp.
FAST_BUFFER
const size_t NumberString::FAST_BUFFER = 48 static
Definition at line 414 of file NumberStringClass.hpp.
Referenced by addSub(), Division(), and Multiply().
HIBIT
const size_t NumberString::HIBIT = ~SSIZE_MAX static
Definition at line 407 of file NumberStringClass.hpp.
Referenced by highBits(), and power().
LOWBITS
const size_t NumberString::LOWBITS = SSIZE_MAX static
Definition at line 408 of file NumberStringClass.hpp.
Referenced by power().
NOROUND
const bool NumberString::NOROUND = false static
Definition at line 404 of file NumberStringClass.hpp.
Referenced by checkNumber(), Division(), and power().
numberDigits
char NumberString::numberDigits[4]
Definition at line 416 of file NumberStringClass.hpp.
Referenced by addSub(), adjustPrecision(), ceilingInternal(), checkIntegerDigits(), comp(), d2xD2c(), Division(), NumberStringBuilder::finish(), floorInternal(), formatInt64(), formatInternal(), formatNumber(), formatUnsignedInt64(), formatUnsignedNumber(), hasSignificantDecimals(), int64Value(), isInteger(), isOne(), Multiply(), NumberStringBuilder::NumberStringBuilder(), numberValue(), power(), prepareNumber(), roundInternal(), setZero(), stringValue(), subtractNumbers(), truncInternal(), unsignedInt64Value(), and unsignedNumberValue().
operatorMethods
PCPPM NumberString::operatorMethods static
Definition at line 371 of file NumberStringClass.hpp.
OVERFLOWSPACE
const size_t NumberString::OVERFLOWSPACE = 2 static
Definition at line 399 of file NumberStringClass.hpp.
Referenced by d2xD2c(), and RexxString::x2dC2d().
ROUND
const bool NumberString::ROUND = true static
Definition at line 403 of file NumberStringClass.hpp.
Referenced by ceiling(), floor(), formatRexx(), maxMin(), minus(), newInstanceFromDouble(), plus(), round(), and trunc().
SIZEBITS
const size_t NumberString::SIZEBITS = (sizeof(size_t) * BYTE_SIZE) static
Definition at line 402 of file NumberStringClass.hpp.
Referenced by highBits(), and power().
The documentation for this class was generated from the following files:
NumberStringClass.hpp
NumberStringClass.cpp
NumberStringMath.cpp
NumberStringMath2.cpp