ooRexx: Activity Class Reference
Activity Class Reference
#include <Activity.hpp>
Public Types
enum QueueOrder { QUEUE_FIFO , QUEUE_LIFO }
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
Activity (RESTORETYPE restoreType)
Activity (GlobalProtectedObject &, bool)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void reset ()
void runThread ()
wholenumber_t error ()
wholenumber_t error (ActivationBase *, DirectoryClass *errorInfo)
wholenumber_t errorNumber (DirectoryClass *conditionObject)
wholenumber_t displayCondition (DirectoryClass *conditionObject)
bool raiseCondition (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
bool raiseCondition (DirectoryClass *)
bool checkCondition (RexxString *condition)
DirectoryClass * createConditionObject (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
void raiseException (RexxErrorCodes, RexxString *, ArrayClass *, RexxObject *)
DirectoryClass * createExceptionObject (RexxErrorCodes, RexxString *, ArrayClass *, RexxObject *)
void generateProgramInformation (DirectoryClass *exObj)
void reportAnException (RexxErrorCodes, const char *)
void reportAnException (RexxErrorCodes, const char *, const char *)
void reportAnException (RexxErrorCodes, RexxObject *, const char *)
void reportAnException (RexxErrorCodes, RexxObject *, wholenumber_t)
void reportAnException (RexxErrorCodes, const char *, RexxObject *)
void reportAnException (RexxErrorCodes, const char *, wholenumber_t)
void reportAnException (RexxErrorCodes, const char *, wholenumber_t, RexxObject *)
void reportAnException (RexxErrorCodes, const char *, RexxObject *, wholenumber_t)
void reportAnException (RexxErrorCodes, wholenumber_t)
void reportAnException (RexxErrorCodes, wholenumber_t, wholenumber_t)
void reportAnException (RexxErrorCodes, wholenumber_t, RexxObject *)
void reportAnException (RexxErrorCodes)
void reportAnException (RexxErrorCodes, RexxObject *)
void reportAnException (RexxErrorCodes, RexxObject *, RexxObject *)
void reportAnException (RexxErrorCodes, RexxObject *, RexxObject *, RexxObject *)
void reportAnException (RexxErrorCodes, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
void reportAnException (RexxErrorCodes, const char *, RexxObject *, const char *, RexxObject *)
void reraiseException (DirectoryClass *)
void raisePropagate (DirectoryClass *)
void display (DirectoryClass *)
void displayDebug (DirectoryClass *)
RexxString * buildMessage (wholenumber_t, ArrayClass *)
RexxString * messageSubstitution (RexxString *, ArrayClass *)
void run ()
void run (MessageClass *target)
void checkActivationStack ()
void updateFrameMarkers ()
void pushStackFrame (ActivationBase *new_activation)
void createNewActivationStack ()
void popStackFrame (bool reply)
void popStackFrame (ActivationBase *)
void unwindStackFrame ()
void unwindToDepth (size_t depth)
void unwindToFrame (RexxActivation *frame)
void cleanupStackFrame (ActivationBase *poppedStackFrame)
ArrayClass * generateStackFrames (bool skipFirst)
StackFrameClass * generateCallerStackFrame (bool skipFirst)
Activity * spawnReply ()
void exitKernel ()
void enterKernel ()
RexxObject * previous ()
void waitReserve (RexxInternalObject *)
void guardWait ()
void guardPost ()
void guardSet ()
void checkDeadLock (Activity *)
void postDispatch ()
void kill (DirectoryClass *)
void joinKernelQueue ()
void relinquish ()
bool halt (RexxString *)
bool setTrace (bool)
void yieldControl ()
void yield ()
void releaseAccess ()
void requestApiAccess ()
void requestAccess ()
void setupCurrentActivity ()
void checkStackSpace ()
void cleanupActivityResources ()
void terminatePoolActivity ()
thread_id_t threadIdMethod ()
bool isThread (thread_id_t id)
bool isClauseExitUsed ()
void queryTrcHlt ()
bool callExit (RexxActivation *activation, const char *exitName, int function, int subfunction, void *exitbuffer)
void callInitializationExit (RexxActivation *)
void callTerminationExit (RexxActivation *)
bool callSayExit (RexxActivation *, RexxString *)
bool callTraceExit (RexxActivation *, RexxString *)
bool callTerminalInputExit (RexxActivation *, RexxString *&)
bool callDebugInputExit (RexxActivation *, RexxString *&)
bool callObjectFunctionExit (RexxActivation *, RexxString *, bool, ProtectedObject &, RexxObject **, size_t)
bool callFunctionExit (RexxActivation *, RexxString *, bool, ProtectedObject &, RexxObject **, size_t)
bool callScriptingExit (RexxActivation *, RexxString *, bool, ProtectedObject &, RexxObject **, size_t)
bool callCommandExit (RexxActivation *, RexxString *, RexxString *, ProtectedObject &result, ProtectedObject &condition)
bool callPullExit (RexxActivation *, RexxString *&)
bool callPushExit (RexxActivation *, RexxString *, QueueOrder)
bool callQueueSizeExit (RexxActivation *, RexxInteger *&)
bool callQueueNameExit (RexxActivation *, RexxString *&)
bool callHaltTestExit (RexxActivation *)
bool callHaltClearExit (RexxActivation *)
bool callTraceTestExit (RexxActivation *, bool)
bool callNovalueExit (RexxActivation *, RexxString *, RexxObject *&)
bool callValueExit (RexxActivation *, RexxString *, RexxString *, RexxObject *, ProtectedObject &)
void traceOutput (RexxActivation *, RexxString *, StringTable *)
void sayOutput (RexxActivation *, RexxString *)
void queue (RexxActivation *, RexxString *, QueueOrder)
RexxString * traceInput (RexxActivation *)
RexxString * pullInput (RexxActivation *)
RexxObject * lineOut (RexxString *)
RexxString * lineIn (RexxActivation *)
void generateRandomNumberSeed ()
void setupAttachedActivity (InterpreterInstance *interpreter)
void addToInstance (InterpreterInstance *interpreter)
void detachInstance ()
void detachThread ()
InterpreterInstance * getInstance ()
uint32_t getIdntfr ()
void nestAttach ()
void returnAttach ()
bool isNestedAttach ()
void activate ()
void deactivate ()
bool isActive ()
bool isInactive ()
size_t getActivationLevel ()
void restoreActivationLevel (size_t l)
bool isSuspended ()
void clearWaitingForDispatch ()
void setWaitingForDispatch ()
bool isWaitingForDispatch ()
void clearWaitingForApiAccess ()
void setWaitingForApiAccess ()
bool isWaitingForApiAccess ()
bool isNestable ()
bool isWaiting ()
void setSuspended (bool s)
bool isInterpreterRoot ()
void setInterpreterRoot ()
void setNestedActivity (Activity *a)
Activity * getNestedActivity ()
bool isAttached ()
bool isSameActivityStack (Activity *a)
void validateThread ()
SecurityManager * getEffectiveSecurityManager ()
SecurityManager * getInstanceSecurityManager ()
void inheritSettings (Activity *parent)
void setupExits ()
void enterCurrentThread ()
void exitCurrentThread ()
void run (ActivityDispatcher &target)
void run (CallbackDispatcher &target)
void run (TrappingDispatcher &target)
bool waitForDispatch ()
void waitForRunPermission ()
bool hasRunPermission ()
void waitForGuardPermission ()
void waitForKernel ()
RexxActivation * getCurrentRexxFrame ()
ActivationBase * getTopStackFrame ()
size_t getActivationDepth ()
const NumericSettings * getNumericSettings ()
void addRunningRequires (RexxString *program)
void removeRunningRequires (RexxInternalObject *program)
void checkRequires (RexxString *n)
void clearRunWait ()
void clearGuardWait ()
uint64_t getRandomSeed ()
RexxString * getLastMessageName ()
RexxThreadContext * getThreadContext ()
NativeActivation * getApiContext ()
void clearLocalReferences ()
void allocateStackFrame (ExpressionStack *stack, size_t entries)
RexxInternalObject ** allocateFrame (size_t entries)
void releaseStackFrame (RexxInternalObject **frame)
void allocateLocalVariableFrame (RexxLocalVariables *locals)
DirectoryClass * getCurrentCondition ()
void clearCurrentCondition ()
void setExitHandler (int exitNum, REXXPFN e)
void setExitHandler (int exitNum, const char *e)
void setExitHandler (RXSYSEXIT &e)
RexxString * resolveProgramName (RexxString *, RexxString *, RexxString *, ResolveType type)
void createMethodContext (MethodContext &context, NativeActivation *owner)
void createCallContext (CallContext &context, NativeActivation *owner)
void createExitContext (ExitContext &context, NativeActivation *owner)
void createRedirectorContext (RedirectorContext &context, NativeActivation *owner)
RexxObject * getLocalEnvironment (RexxString *name)
DirectoryClass * getLocal ()
CommandHandler * resolveCommandHandler (RexxString *)
void addMutex (MutexSemaphoreClass *m)
void removeMutex (MutexSemaphoreClass *m)
void cleanupMutexes ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void setCallerStackFrameAsStringTable (Activity *oldActivity, Activity *newActivity, bool skipFirst)
static void initializeThreadContext ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes
StringTable * spawnerStackFrameInfo
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions
ExitHandler & getExitHandler (int exitNum)
bool isExitEnabled (int exitNum)
void disableExit (int exitNum)
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Protected Attributes
InterpreterInstance * instance
ActivityContext threadContext
Activity * oldActivity
ActivationStack frameStack
DirectoryClass * conditionobj
StringTable * requiresTable
MessageClass * dispatchMessage
InternalStack * activations
size_t activationStackSize
size_t stackFrameDepth
RexxActivation * currentRexxFrame
ActivationBase * topStackFrame
RexxString * currentExit
RexxInternalObject * waitingObject
SysSemaphore runSem
SysSemaphore guardSem
SysActivity currentThread
const NumericSettings * numericSettings
bool stackcheck
bool exit
bool requestingString
bool suspended
bool interpreterRoot
bool waitingForApiAccess
bool waitingForDispatch
bool waitingOnSemaphore
bool dispatchPosted
size_t nestedCount
size_t attachCount
bool newThreadAttached
char * stackLimit
bool clauseExitUsed
uint64_t randomSeed
ProtectedBase * protectedObjects
ActivationFrame * activationFrames
Activity * nestedActivity
IdentityTable * heldMutexes
Static Protected Attributes
static const uint32_t MaxDispatchWait = 50
static RexxThreadInterface threadContextFunctions
static MethodContextInterface methodContextFunctions
static CallContextInterface callContextFunctions
static ExitContextInterface exitContextFunctions
static IORedirectorInterface ioRedirectorContextFunctions
static const size_t errorRecoveryStack = 1024 * (32 + (4 * sizeof(void *)))
Friends
class ProtectedBase
class ActivationFrame
Detailed Description
Definition at line 90 of file Activity.hpp.
Member Enumeration Documentation
QueueOrder
enum Activity::QueueOrder
Enumerator
QUEUE_FIFO
QUEUE_LIFO
Definition at line 96 of file Activity.hpp.
Constructor & Destructor Documentation
Activity() [1/2]
Activity::Activity (RESTORETYPE restoreType) inline
Definition at line 107 of file Activity.hpp.
Activity() [2/2]
Activity::Activity (GlobalProtectedObject & p, bool createThread)
Initialize an Activity object.
Parameters
createThread Indicates whether we're going to be running on the current thread, or creating a new thread.
Definition at line 346 of file Activity-trace.cpp.
References ACT_STACK_SIZE, activate(), activations, activationStackSize, RexxInternalObject::clearObject(), SysSemaphore::create(), SysActivity::create(), createNewActivationStack(), currentThread, errorRecoveryStack, frameStack, generateRandomNumberSeed(), Numerics::getDefaultSettings(), SysActivity::getStackBase(), SysActivity::getStackSize(), guardSem, ActivationStack::init(), new_internalstack(), new_string_table(), numericSettings, requiresTable, SysSemaphore::reset(), runSem, stackcheck, stackLimit, and SysActivity::useCurrentThread().
Member Function Documentation
activate()
void Activity::activate () inline
Definition at line 235 of file Activity.hpp.
References nestedCount.
Referenced by Activity(), enterCurrentThread(), InterpreterInstance::enterOnCurrentThread(), ActivityManager::getRootActivity(), and reset().
addMutex()
void Activity::addMutex (MutexSemaphoreClass * sem)
Register this mutex with the activity as being held.
Parameters
sem the semaphore to add
Definition at line 3603 of file Activity-trace.cpp.
References heldMutexes, new_identity_table(), OREF_NULL, and HashCollection::put().
Referenced by MutexSemaphoreClass::handleNesting().
addRunningRequires()
void Activity::addRunningRequires (RexxString * program) inline
Definition at line 295 of file Activity.hpp.
References HashCollection::put(), and requiresTable.
Referenced by InstallingPackage::InstallingPackage().
addToInstance()
void Activity::addToInstance (InterpreterInstance * interpreter)
Set up an activity as a root activity used either for a main interpreter thread or an attached thread.
Parameters
interpreter The interpreter instance this thread belongs to.
Definition at line 1808 of file Activity-trace.cpp.
References RexxThreadContext_::functions, InterpreterInstance::getInstanceContext(), RexxThreadContext_::instance, instance, ActivityContext::owningActivity, setupExits(), ActivityContext::threadContext, threadContext, and threadContextFunctions.
Referenced by setupAttachedActivity(), and InterpreterInstance::spawnActivity().
allocateFrame()
RexxInternalObject** Activity::allocateFrame (size_t entries) inline
Definition at line 312 of file Activity.hpp.
References ActivationStack::allocateFrame(), and frameStack.
Referenced by RexxActivation::run().
allocateLocalVariableFrame()
void Activity::allocateLocalVariableFrame (RexxLocalVariables * locals) inline
Definition at line 322 of file Activity.hpp.
References ActivationStack::allocateFrame(), frameStack, RexxLocalVariables::getSize(), and RexxLocalVariables::setFrame().
Referenced by RexxActivation::allocateLocalVariables(), RexxLocalVariables::migrate(), and RexxActivation::procedureExpose().
allocateStackFrame()
void Activity::allocateStackFrame (ExpressionStack * stack, size_t entries) inline
Definition at line 307 of file Activity.hpp.
References ActivationStack::allocateFrame(), frameStack, and ExpressionStack::setFrame().
Referenced by RexxActivation::allocateStackFrame(), and ExpressionStack::migrate().
buildMessage()
RexxString * Activity::buildMessage (wholenumber_t messageCode, ArrayClass * substitutions)
Build a message and perform the indicated substitutions.
Parameters
messageCode The target message code
substitutions An array of substitution values
Returns
The message with the substitution values inserted.
Definition at line 1216 of file Activity-trace.cpp.
References Error_Execution_error_condition, Interpreter::getMessageText(), messageSubstitution(), OREF_NULL, and reportException().
Referenced by createExceptionObject(), NativeActivation::createStackFrame(), InternalActivationFrame::createStackFrame(), RexxActivation::formatSourcelessTraceLine(), PackageClass::traceBack(), and RexxActivation::traceEntryOrExit().
callCommandExit()
bool Activity::callCommandExit (RexxActivation * activation, RexxString * address, RexxString * command, ProtectedObject & result, ProtectedObject & condition)
Call the command exit.
Parameters
activation The activaton context.
address The current address environment
command The string command.
result The command result.
condition any raised condition.
Returns
The handled flag.
Definition at line 2743 of file Activity-trace.cpp.
References callExit(), SecurityManager::checkCommand(), createConditionObject(), DEFRXSTRING, RexxActivation::getEffectiveSecurityManager(), RexxString::getLength(), RexxString::getStringData(), isExitEnabled(), MAKERXSTRING, new_string(), OREF_NULL, SystemInterpreter::releaseResultMemory(), RXCMD, _RXCMDHST_PARM::rxcmd_address, _RXCMDHST_PARM::rxcmd_addressl, _RXCMDHST_PARM::rxcmd_command, _RXCMDHST_PARM::rxcmd_dll, _RXCMDHST_PARM::rxcmd_dll_len, _RXCMDHST_PARM::rxcmd_flags, _RXCMDHST_PARM::rxcmd_retc, RXCMDHST, _RXCMD_FLAGS::rxfcerr, _RXCMD_FLAGS::rxfcfail, _RXSTRING::strptr, and RexxString::toRxstring().
Referenced by RexxActivation::command().
callDebugInputExit()
bool Activity::callDebugInputExit (RexxActivation * activation, RexxString *& inputstring)
Retrieve an input string from the debug input exit.
Parameters
activation The activation context.
inputstring The retrieved inputstring.
Returns
The handled flag.
Definition at line 2466 of file Activity-trace.cpp.
References callExit(), DEFRXSTRING, isExitEnabled(), MAKERXSTRING, new_string(), SystemInterpreter::releaseResultMemory(), RXSIO, RXSIODTR, _RXSIOTRD_PARM::rxsiotrd_retc, and _RXSTRING::strptr.
Referenced by traceInput().
callExit()
bool Activity::callExit (RexxActivation * activation, const char * exitName, int function, int subfunction, void * exitbuffer)
Call an individual exit handler.
Parameters
activation The activation this is in the context of.
exitName The logical name of the handler.
function The exit function.
subfunction The exit subfunction.
exitbuffer The parameter structure for the exit in question.
Returns
The exit handling state.
Definition at line 2327 of file Activity-trace.cpp.
References ExitHandler::call(), disableExit(), Error_System_service_service, getExitHandler(), reportException(), RXEXIT_HANDLED, RXEXIT_RAISE_ERROR, and RXSIO.
Referenced by callCommandExit(), callDebugInputExit(), callFunctionExit(), callHaltClearExit(), callHaltTestExit(), callInitializationExit(), callNovalueExit(), callObjectFunctionExit(), callPullExit(), callPushExit(), callQueueNameExit(), callQueueSizeExit(), callSayExit(), callScriptingExit(), callTerminalInputExit(), callTerminationExit(), callTraceExit(), callTraceTestExit(), and callValueExit().
callFunctionExit()
bool Activity::callFunctionExit (RexxActivation * activation, RexxString * rname, bool isFunction, ProtectedObject & funcresult, RexxObject ** arguments, size_t argcount)
Call the function exit to handle a function call.
Parameters
activation The activation context.
rname The call target name.
isFunction true if this is a function call.
funcresult The returned function result.
arguments The array of function arguments.
argcount The count of arguments.
Returns
The handled flag.
Definition at line 2503 of file Activity-trace.cpp.
References SystemInterpreter::allocateResultMemory(), callExit(), DEFRXSTRING, Error_Function_no_data_function, Error_Incorrect_call_external, Error_Routine_not_found_name, Error_System_resources, Interpreter::getCurrentQueue(), RexxString::getLength(), RexxString::getStringData(), isExitEnabled(), MAKERXSTRING, new_string(), OREF_NULL, SystemInterpreter::releaseResultMemory(), reportException(), RexxInternalObject::requestString(), _RXFNC_FLAGS::rxfferr, _RXFNC_FLAGS::rxffnfnd, _RXFNC_FLAGS::rxffsub, RXFNC, _RXFNCCAL_PARM::rxfnc_argc, _RXFNCCAL_PARM::rxfnc_argv, _RXFNCCAL_PARM::rxfnc_flags, _RXFNCCAL_PARM::rxfnc_name, _RXFNCCAL_PARM::rxfnc_namel, _RXFNCCAL_PARM::rxfnc_que, _RXFNCCAL_PARM::rxfnc_quel, _RXFNCCAL_PARM::rxfnc_retc, RXFNCCAL, _RXSTRING::strptr, and RexxString::toRxstring().
Referenced by RexxActivation::externalCall().
callHaltClearExit()
bool Activity::callHaltClearExit (RexxActivation * activation)
Call the halt exit to clear the halt condition after it has been acknowledged.
Parameters
activation The activation context.
Returns
The handled flag.
Definition at line 2971 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), RXHLT, and RXHLTCLR.
Referenced by RexxActivation::trap().
callHaltTestExit()
bool Activity::callHaltTestExit (RexxActivation * activation)
Call the external handler to test for a halt condition.
Parameters
activation The activation context.
Returns
The handled flag.
Definition at line 2939 of file Activity-trace.cpp.
References callExit(), RexxActivation::halt(), isExitEnabled(), OREF_NULL, _RXHLT_FLAGS::rxfhhalt, RXHLT, _RXHLTTST_PARM::rxhlt_flags, and RXHLTTST.
Referenced by RexxActivation::processClauseBoundary().
callInitializationExit()
void Activity::callInitializationExit (RexxActivation * activation)
Call the initialization exit
Parameters
activation The activation context for the top level.
Definition at line 2356 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), RXINI, and RXINIEXT.
Referenced by RexxActivation::run().
callNovalueExit()
bool Activity::callNovalueExit (RexxActivation * activation, RexxString * variableName, RexxObject *& value)
Call the NOVALUE exit to see if the exit handler can provide a new value.
Parameters
activation The activation context.
variableName The name of the variable.
value The returned value if handled.
Returns
The handled flag.
Definition at line 3034 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), NULLOBJECT, RXNOVAL, RXNOVALCALL, _RXVARNOVALUE_PARM::value, and _RXVARNOVALUE_PARM::variable_name.
Referenced by RexxActivation::handleNovalueEvent().
callObjectFunctionExit()
bool Activity::callObjectFunctionExit (RexxActivation * activation, RexxString * rname, bool isFunction, ProtectedObject & funcresult, RexxObject ** arguments, size_t argcount)
Invoke the object-oriented function exit.
Parameters
activation The activation context.
rname The function name.
isFunction true if this is a function call.
funcresult The returned result.
arguments The array of arguments.
argcount The count of arguments.
Returns
The handled flag.
Definition at line 2616 of file Activity-trace.cpp.
References callExit(), SecurityManager::checkFunctionCall(), Error_Function_no_data_function, Error_Incorrect_call_external, Error_Routine_not_found_name, RexxActivation::getEffectiveSecurityManager(), isExitEnabled(), NULLOBJECT, OREF_NULL, reportException(), _RXOFNC_FLAGS::rxfferr, _RXOFNC_FLAGS::rxffnfnd, _RXOFNC_FLAGS::rxffsub, _RXOFNCCAL_PARM::rxfnc_argc, _RXOFNCCAL_PARM::rxfnc_argv, _RXOFNCCAL_PARM::rxfnc_flags, _RXOFNCCAL_PARM::rxfnc_name, _RXOFNCCAL_PARM::rxfnc_retc, RXOFNC, RXOFNCCAL, and RexxString::toRxstring().
Referenced by RexxActivation::externalCall().
callPullExit()
bool Activity::callPullExit (RexxActivation * activation, RexxString *& inputstring)
Pull a string from the queue input exit.
Parameters
activation The activation context.
inputstring The returned input string.
Returns
The handled flag.
Definition at line 2813 of file Activity-trace.cpp.
References callExit(), DEFRXSTRING, isExitEnabled(), MAKERXSTRING, new_string(), SystemInterpreter::releaseResultMemory(), RXMSQ, _RXMSQPLL_PARM::rxmsq_retc, RXMSQPLL, _RXSTRING::strptr, and TheNilObject.
Referenced by pullInput().
callPushExit()
bool Activity::callPushExit (RexxActivation * activation, RexxString * outputString, QueueOrder lifo_flag)
Handle a push or queue operation via a system exit.
Parameters
activation The activation context.
outputString The string to push
lifo_flag The queuing order flag.
Returns
The handled flag.
Definition at line 2854 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), QUEUE_LIFO, _RXMSQ_FLAGS::rxfmlifo, RXMSQ, _RXMSQPSH_PARM::rxmsq_flags, _RXMSQPSH_PARM::rxmsq_value, RXMSQPSH, and RexxString::toRxstring().
Referenced by queue().
callQueueNameExit()
bool Activity::callQueueNameExit (RexxActivation * activation, RexxString *& inputstring)
Call the system exit indicating a queue name change.
Parameters
activation The activation context.
inputstring The new queue name (can also be a return value).
Returns
The handled flag.
Definition at line 2905 of file Activity-trace.cpp.
References callExit(), DEFRXSTRING, RexxString::getLength(), RexxString::getStringData(), isExitEnabled(), MAKERXSTRING, new_string(), SystemInterpreter::releaseResultMemory(), RXMSQ, _RXMSQNAM_PARM::rxmsq_name, RXMSQNAM, and _RXSTRING::strptr.
callQueueSizeExit()
bool Activity::callQueueSizeExit (RexxActivation * activation, RexxInteger *& returnsize)
Retrieve the queue size via an exit.
Parameters
activation The activation context
returnsize The returned size.
Returns
The handled flag.
Definition at line 2878 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), new_integer(), RXMSQ, _RXMSQSIZ_PARM::rxmsq_size, and RXMSQSIZ.
callSayExit()
bool Activity::callSayExit (RexxActivation * activation, RexxString * sayoutput)
Call the sytem I/O exit for say output.
Parameters
activation The source activation context.
sayoutput The output string.
Returns
The handled/not handled flag.
Definition at line 2387 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), RXSIO, _RXSIOSAY_PARM::rxsio_string, RXSIOSAY, and RexxString::toRxstring().
Referenced by sayOutput().
callScriptingExit()
bool Activity::callScriptingExit (RexxActivation * activation, RexxString * rname, bool isFunction, ProtectedObject & funcresult, RexxObject ** arguments, size_t argcount)
Call the scripting function exit. this is the very last step in external call lookups.
Parameters
activation The activation context.
rname The call name.
isFunction true if this is a function call, false for a routine.
funcresult The returned result.
arguments The function arguments.
argcount The argument count.
Returns
The handled flag.
Definition at line 2687 of file Activity-trace.cpp.
References callExit(), Error_Function_no_data_function, Error_Incorrect_call_external, Error_Routine_not_found_name, isExitEnabled(), NULLOBJECT, reportException(), RXEXF, RXEXFCAL, _RXEXF_FLAGS::rxfferr, _RXEXF_FLAGS::rxffnfnd, _RXEXF_FLAGS::rxffsub, _RXEXFCAL_PARM::rxfnc_argc, _RXEXFCAL_PARM::rxfnc_argv, _RXEXFCAL_PARM::rxfnc_flags, _RXEXFCAL_PARM::rxfnc_name, _RXEXFCAL_PARM::rxfnc_retc, and RexxString::toRxstring().
Referenced by RexxActivation::externalCall().
callTerminalInputExit()
bool Activity::callTerminalInputExit (RexxActivation * activation, RexxString *& inputstring)
Request input from the terminal input exit.
Parameters
activation The activation context.
inputstring The returned intput string.
Returns
The handled indicator.
Definition at line 2430 of file Activity-trace.cpp.
References callExit(), DEFRXSTRING, isExitEnabled(), MAKERXSTRING, new_string(), SystemInterpreter::releaseResultMemory(), RXSIO, RXSIOTRD, _RXSIOTRD_PARM::rxsiotrd_retc, and _RXSTRING::strptr.
Referenced by lineIn().
callTerminationExit()
void Activity::callTerminationExit (RexxActivation * activation)
Call the termination exit for a top-level program.
Parameters
activation The activaiton context.
Definition at line 2370 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), RXTER, and RXTEREXT.
Referenced by RexxActivation::exitFrom(), RexxActivation::implicitExit(), RexxActivation::raiseExit(), and RexxActivation::returnFrom().
callTraceExit()
bool Activity::callTraceExit (RexxActivation * activation, RexxString * traceoutput)
Call the trace output I/O exit.
Parameters
activation The activation context.
traceoutput The trace line.
Returns
The handled flag.
Definition at line 2409 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), RXSIO, _RXSIOSAY_PARM::rxsio_string, RXSIOTRC, and RexxString::toRxstring().
Referenced by traceOutput().
callTraceTestExit()
bool Activity::callTraceTestExit (RexxActivation * activation, bool currentsetting)
Call the trace exit checking for a change in trace setting.
Parameters
activation The activation context.
currentsetting The current trace setting.
Returns
The handled flag.
Definition at line 2993 of file Activity-trace.cpp.
References callExit(), RexxActivation::externalTraceOff(), RexxActivation::externalTraceOn(), isExitEnabled(), _RXTRC_FLAGS::rxftrace, RXTRC, _RXTRCTST_PARM::rxtrc_flags, and RXTRCTST.
Referenced by RexxActivation::processClauseBoundary().
callValueExit()
bool Activity::callValueExit (RexxActivation * activation, RexxString * selector, RexxString * variableName, RexxObject * newValue, ProtectedObject & value)
Call the VALUE() bif exit.
Parameters
activation The current activation context.
selector The value variable pool selector.
variableName The name of the variable.
newValue A potential new value.
value The returned old value.
Returns
The handled flag.
Definition at line 3067 of file Activity-trace.cpp.
References callExit(), isExitEnabled(), RXVALUE, RXVALUECALL, _RXVALCALL_PARM::selector, _RXVALCALL_PARM::value, and _RXVALCALL_PARM::variable_name.
checkActivationStack()
void Activity::checkActivationStack ()
Check the activation stack to see if we need to expand the size.
Definition at line 1542 of file Activity-trace.cpp.
References ACT_STACK_SIZE, activations, activationStackSize, new_internalstack(), InternalStack::peek(), InternalStack::push(), and stackFrameDepth.
Referenced by createNewActivationStack(), and pushStackFrame().
checkCondition()
bool Activity::checkCondition (RexxString * condition)
Test if a condition will be trapped before creating a condition object for it.
Parameters
condition The name of the condition being raised
Returns
true if this will be trapped, false otherwise.
Definition at line 642 of file Activity-trace.cpp.
References getTopStackFrame(), isOfClass, and ActivationBase::isStackBase().
Referenced by raiseCondition().
checkDeadLock()
void Activity::checkDeadLock (Activity * targetActivity)
Check for a circular wait dead lock error
Parameters
targetActivity The target activity.
Definition at line 1993 of file Activity-trace.cpp.
References checkDeadLock(), Error_Execution_deadlock, isOfClass, OREF_NULL, reportException(), and waitingObject.
Referenced by checkDeadLock(), VariableDictionary::reserve(), and MessageClass::wait().
checkRequires()
void Activity::checkRequires (RexxString * name)
Check for a circular requires reference and raise an error if it occurs.
Parameters
name The name of the requires files
Definition at line 3660 of file Activity-trace.cpp.
References Error_Execution_circular_requires, HashCollection::hasIndex(), reportException(), and requiresTable.
Referenced by InterpreterInstance::loadRequires().
checkStackSpace()
void Activity::checkStackSpace ()
Definition at line 2260 of file Activity-trace.cpp.
References Error_Control_stack_full, reportException(), stackcheck, and stackLimit.
Referenced by RexxCode::call(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxActivation::interpret(), RexxObject::messageSend(), LanguageParser::parseMessageSubterm(), and LanguageParser::parseSubTerm().
cleanupActivityResources()
void Activity::cleanupActivityResources ()
Do cleanup of activity resources when an activity is completely shutdown and discarded.
Definition at line 280 of file Activity-trace.cpp.
References cleanupMutexes(), clearLocalReferences(), SysSemaphore::close(), SysActivity::close(), currentThread, guardSem, and runSem.
Referenced by ActivityManager::activityEnded(), ActivityManager::poolActivity(), ActivityManager::returnActivity(), and ActivityManager::returnRootActivity().
cleanupMutexes()
void Activity::cleanupMutexes ()
Cleanup any held mutexes on activity termination.
Definition at line 3637 of file Activity-trace.cpp.
References HashCollection::allIndexes(), HashCollection::empty(), MutexSemaphoreClass::forceLockRelease(), heldMutexes, and OREF_NULL.
Referenced by cleanupActivityResources(), and runThread().
cleanupStackFrame()
void Activity::cleanupStackFrame (ActivationBase * poppedStackFrame)
Clean up a popped stack frame.
Parameters
poppedStackFrame
Definition at line 1675 of file Activity-trace.cpp.
References RexxInternalObject::setHasNoReferences(), and ActivationBase::termination().
Referenced by popStackFrame().
clearCurrentCondition()
void Activity::clearCurrentCondition () inline
Definition at line 328 of file Activity.hpp.
References conditionobj, and OREF_NULL.
Referenced by run(), and RexxActivation::trap().
clearGuardWait()
void Activity::clearGuardWait () inline
Definition at line 299 of file Activity.hpp.
References guardSem, and SysSemaphore::reset().
clearLocalReferences()
void Activity::clearLocalReferences ()
Clear any local references held by the root member of the activation stack.
Definition at line 302 of file Activity-trace.cpp.
References NativeActivation::clearLocalReferences(), and getApiContext().
Referenced by cleanupActivityResources(), and InterpreterInstance::terminate().
clearRunWait()
void Activity::clearRunWait () inline
Definition at line 298 of file Activity.hpp.
References dispatchPosted, SysSemaphore::reset(), and runSem.
Referenced by ActivityManager::addWaitingActivity().
clearWaitingForApiAccess()
void Activity::clearWaitingForApiAccess () inline
Definition at line 245 of file Activity.hpp.
References waitingForApiAccess.
Referenced by requestApiAccess().
clearWaitingForDispatch()
void Activity::clearWaitingForDispatch () inline
Definition at line 242 of file Activity.hpp.
References waitingForDispatch.
Referenced by ActivityManager::addWaitingActivity(), and ActivityManager::addWaitingApiActivity().
createCallContext()
void Activity::createCallContext (CallContext & context, NativeActivation * owner)
Set up a call context for use before a call out.
Parameters
context The method context to initialize.
owner The native activation that owns this context.
Definition at line 3488 of file Activity-trace.cpp.
References callContextFunctions, CallContext::context, RexxCallContext_::functions, RexxCallContext_::threadContext, ActivityContext::threadContext, CallContext::threadContext, and threadContext.
Referenced by NativeActivation::callNativeRoutine().
createConditionObject()
DirectoryClass * Activity::createConditionObject (RexxString * condition, RexxObject * rc, RexxObject * description, RexxObject * additional, RexxObject * result)
Create a condition object from the provided information.
Parameters
condition The name of the raised condition.
rc The rc value (can be null)
description The description string.
additional Additional information.
result result information.
Returns
The constructed condition object (a directory).
Definition at line 717 of file Activity-trace.cpp.
References generateProgramInformation(), new_directory(), OREF_NULL, DirectoryClass::put(), and TheFalseObject.
Referenced by callCommandExit(), SecurityManager::checkCommand(), RexxActivation::command(), CommandHandlerDispatcher::complete(), RexxActivation::raise(), and raiseCondition().
createExceptionObject()
DirectoryClass * Activity::createExceptionObject (RexxErrorCodes errcode, RexxString * description, ArrayClass * additional, RexxObject * result)
Create a new error exception object for a SYNTAX error
Parameters
errcode The error code to raise.
description The description string.
additional Message substitution information.
result The result object.
Returns
The created exception dictionary.
Definition at line 982 of file Activity-trace.cpp.
References buildMessage(), Error_Execution_error_condition, generateProgramInformation(), Interpreter::getMessageText(), MESSAGE, new_array(), new_directory(), new_integer(), new_string(), OREF_NULL, DirectoryClass::put(), reportException(), TheFalseObject, TheNilObject, and work.
Referenced by raiseException().
createExitContext()
void Activity::createExitContext (ExitContext & context, NativeActivation * owner)
Set up an exit context for use before a call out.
Parameters
context The method context to initialize.
owner The native activation that owns this context.
Definition at line 3503 of file Activity-trace.cpp.
References ExitContext::context, exitContextFunctions, RexxExitContext_::functions, RexxExitContext_::threadContext, ActivityContext::threadContext, ExitContext::threadContext, and threadContext.
Referenced by ContextCommandHandlerDispatcher::run(), RedirectingCommandHandlerDispatcher::run(), and ContextExitHandlerDispatcher::run().
createMethodContext()
void Activity::createMethodContext (MethodContext & context, NativeActivation * owner)
Set up a method context for use before a call out.
Parameters
context The method context to initialize.
owner The native activation that owns this context.
Definition at line 3473 of file Activity-trace.cpp.
References MethodContext::context, RexxMethodContext_::functions, methodContextFunctions, RexxMethodContext_::threadContext, ActivityContext::threadContext, MethodContext::threadContext, and threadContext.
Referenced by NativeActivation::run().
createNewActivationStack()
void Activity::createNewActivationStack ()
Create a new set of activation stack frames on this activity. The new frame will have a NativeActivation that's marked as a stack base frame. Additional call frames are pushed on top of that activation. Any operations that unwind the stack frames will stop when they hit the activation stack base.
Definition at line 1615 of file Activity-trace.cpp.
References activations, checkActivationStack(), ActivityManager::newNativeActivation(), InternalStack::push(), NativeActivation::setStackBase(), stackFrameDepth, and updateFrameMarkers().
Referenced by Activity(), MemoryObject::createImage(), nestAttach(), run(), and setupAttachedActivity().
createRedirectorContext()
void Activity::createRedirectorContext (RedirectorContext & context, NativeActivation * owner)
Set up an exit context for use with a I/O redirection command
Parameters
context The method context to initialize.
owner The native activation that owns this context.
Definition at line 3518 of file Activity-trace.cpp.
References RedirectorContext::activity, RedirectorContext::context, RexxIORedirectorContext_::functions, ioRedirectorContextFunctions, and RedirectorContext::redirectorContext.
Referenced by RedirectingCommandHandlerDispatcher::run().
deactivate()
void Activity::deactivate () inline
Definition at line 236 of file Activity.hpp.
References nestedCount.
Referenced by Interpreter::createInstance(), exitCurrentThread(), and runThread().
detachInstance()
void Activity::detachInstance ()
Cleanup the resources for a detached activity, including removing the suspended state from a pushed activity nest.
Definition at line 1859 of file Activity-trace.cpp.
References attachCount, conditionobj, dispatchMessage, instance, nestedActivity, newThreadAttached, oldActivity, OREF_NULL, setSuspended(), and waitingObject.
Referenced by InterpreterInstance::poolActivity(), and ActivityManager::returnRootActivity().
detachThread()
void Activity::detachThread ()
Detach a thread from the interpreter instance,
Definition at line 1849 of file Activity-trace.cpp.
References InterpreterInstance::detachThread(), and instance.
Referenced by DetachThread().
disableExit()
void Activity::disableExit (int exitNum) inline protected
Definition at line 353 of file Activity.hpp.
References ExitHandler::disable(), and getExitHandler().
Referenced by callExit().
display()
void Activity::display (DirectoryClass * exobj)
Display information from an exception object.
Parameters
exobj The exception object.
Definition at line 1408 of file Activity-trace.cpp.
References currentRexxFrame, RexxActivation::displayUsingTraceOutput(), DirectoryClass::get(), ArrayClass::get(), Interpreter::getMessageText(), ListClass::makeArray(), MESSAGE, Message_Translations_error, Message_Translations_line, Message_Translations_running, Interpreter::messageNumber(), OREF_NULL, RexxInternalObject::requestString(), ArrayClass::size(), and TheNilObject.
Referenced by displayCondition().
displayCondition()
wholenumber_t Activity::displayCondition (DirectoryClass * errorInfo)
Display error information and traceback lines for a Syntax condition.
Parameters
errorInfo The condition object with the error information
Returns
The major error code for the syntax error, if this is indeed a syntax conditon.
Definition at line 530 of file Activity-trace.cpp.
References display(), Error_Interpretation, DirectoryClass::get(), RexxString::isEqual(), RexxInternalObject::numberValue(), and OREF_NULL.
Referenced by DisplayCondition(), and error().
displayDebug()
void Activity::displayDebug (DirectoryClass * exobj)
Display information about an error in interactive debug.
Parameters
exobj The exception object.
Returns
Definition at line 1486 of file Activity-trace.cpp.
References RexxString::concat(), RexxString::concatWith(), RexxString::concatWithCstring(), currentRexxFrame, RexxActivation::displayUsingTraceOutput(), DirectoryClass::get(), Interpreter::getMessageText(), MESSAGE, Message_Translations_debug_error, OREF_NULL, and TheNilObject.
Referenced by RexxActivation::trap().
enterCurrentThread()
void Activity::enterCurrentThread ()
Enter the current thread for an API call.
Definition at line 330 of file Activity-trace.cpp.
References activate(), and requestApiAccess().
Referenced by ApiContext::ApiContext(), and ActivityManager::getActivity().
enterKernel()
void Activity::enterKernel ()
Recover the kernel access and pop the native activation created by activity_exit_kernel from the activity stack.
Definition at line 1963 of file Activity-trace.cpp.
References popStackFrame(), and requestAccess().
Referenced by CalloutBlock::~CalloutBlock().
error() [1/2]
wholenumber_t Activity::error ()
Force error termination on an activity, returning the resulting REXX error code.
Returns
The resulting Rexx error code.
Definition at line 478 of file Activity-trace.cpp.
References conditionobj, displayCondition(), ActivationBase::isStackBase(), popStackFrame(), and topStackFrame.
Referenced by MemoryObject::createImage(), MessageDispatcher::handleError(), RexxStartDispatcher::handleError(), TranslateDispatcher::handleError(), run(), and runThread().
error() [2/2]
wholenumber_t Activity::error (ActivationBase * activation, DirectoryClass * errorInfo)
Force error termination on an activity, returning the resulting REXX error code.
Parameters
activation The activation raising the error.
errorInfo The directory containing the error condition information.
Returns
The Rexx error code.
Definition at line 500 of file Activity-trace.cpp.
References conditionobj, displayCondition(), OREF_NULL, popStackFrame(), and topStackFrame.
errorNumber()
wholenumber_t Activity::errorNumber (DirectoryClass * conditionObject)
Extract an error number from a syntax condition object.
Parameters
conditionObject The condition object for the extract.
Returns
The RC value associated with the condition.
Definition at line 564 of file Activity-trace.cpp.
References Error_Interpretation, DirectoryClass::get(), RexxInternalObject::numberValue(), and OREF_NULL.
Referenced by ActivityDispatcher::handleError().
exitCurrentThread()
void Activity::exitCurrentThread ()
We're leaving the current thread. So we need to deactivate this.
Definition at line 312 of file Activity-trace.cpp.
References MemoryObject::checkUninitQueue(), deactivate(), isInactive(), memoryObject, and releaseAccess().
Referenced by InterpreterInstance::terminate(), ApiContext::~ApiContext(), InstanceBlock::~InstanceBlock(), and NativeContextBlock::~NativeContextBlock().
exitKernel()
void Activity::exitKernel ()
Release the kernel access because code is going to "leave" the kernel. This prepares for this by adding a native activation on to the stack to act as a server for the external call. This way new native methods do not need to be created just to get an activation created
Definition at line 1945 of file Activity-trace.cpp.
References currentRexxFrame, NativeActivation::enableVariablepool(), ActivityManager::newNativeActivation(), pushStackFrame(), and releaseAccess().
Referenced by CalloutBlock::CalloutBlock().
generateCallerStackFrame()
StackFrameClass * Activity::generateCallerStackFrame (bool skipFirst)
Generate the caller's stack frame.
Parameters
skipFirst Determines if we should skip the first frame: false for reply in RexxActivation::run(...), true for Message::start() and in the general case.
Returns
The stackframe of the caller which caused a spawned activity.
Definition at line 1171 of file Activity-trace.cpp.
References activationFrames, ActivationFrame::createStackFrame(), and ActivationFrame::next.
Referenced by setCallerStackFrameAsStringTable().
generateProgramInformation()
void Activity::generateProgramInformation (DirectoryClass * exobj)
Add program location-specific information to a condition object.
Parameters
exobj The exception object being constructed.
Definition at line 1074 of file Activity-trace.cpp.
References activationFrames, ListClass::append(), ActivationFrame::createStackFrame(), ActivationFrame::getPackage(), StackFrameClass::getTraceLine(), new_list(), ActivationFrame::next, OREF_NULL, DirectoryClass::put(), and TheNilObject.
Referenced by createConditionObject(), and createExceptionObject().
generateRandomNumberSeed()
void Activity::generateRandomNumberSeed ()
Generate a fresh random number seed.
Definition at line 436 of file Activity-trace.cpp.
References currentThread, SysProcess::getPid(), SysActivity::getThreadID(), and randomSeed.
Referenced by Activity(), and run().
generateStackFrames()
ArrayClass * Activity::generateStackFrames (bool skipFirst)
Generate a list of stack frames for an Exception object.
Parameters
skipFirst Determines if we should skip the first frame. Used primarily for the RexxContext stackFrames() method to avoid returning the stackframes method as the first item.
Returns
An array of the stack frames in the call context.
Definition at line 1135 of file Activity-trace.cpp.
References activationFrames, ArrayClass::append(), ActivationFrame::createStackFrame(), new_array(), and ActivationFrame::next.
Referenced by RexxActivation::getStackFrames().
getActivationDepth()
size_t Activity::getActivationDepth () inline
Definition at line 293 of file Activity.hpp.
References stackFrameDepth.
getActivationLevel()
size_t Activity::getActivationLevel () inline
Definition at line 239 of file Activity.hpp.
References nestedCount.
Referenced by NativeActivation::callNativeRoutine(), NativeActivation::callRegisteredRoutine(), messageSubstitution(), run(), NativeActivation::run(), and runThread().
getApiContext()
NativeActivation* Activity::getApiContext () inline
Definition at line 304 of file Activity.hpp.
References topStackFrame.
Referenced by ApiContext::ApiContext(), clearLocalReferences(), contextToActivation(), and run().
getCurrentCondition()
DirectoryClass* Activity::getCurrentCondition () inline
Definition at line 327 of file Activity.hpp.
References conditionobj.
getCurrentRexxFrame()
RexxActivation* Activity::getCurrentRexxFrame () inline
Definition at line 291 of file Activity.hpp.
References currentRexxFrame.
Referenced by RexxActivation::exitFrom(), NativeActivation::fetchNext(), MethodClass::newMethodObject(), BaseExecutable::processNewExecutableArgs(), BaseExecutable::processNewFileExecutableArgs(), raiseCondition(), raiseException(), and reraiseException().
getEffectiveSecurityManager()
SecurityManager * Activity::getEffectiveSecurityManager ()
Retrieve the current security manager instance.
Returns
the security manager instance in effect for the activity.
Definition at line 3097 of file Activity-trace.cpp.
References InterpreterInstance::getSecurityManager(), ActivationBase::getSecurityManager(), instance, OREF_NULL, and topStackFrame.
Referenced by PackageManager::loadRequires(), and RexxObject::processProtectedMethod().
getExitHandler()
ExitHandler& Activity::getExitHandler (int exitNum) inline protected
Definition at line 351 of file Activity.hpp.
References InterpreterInstance::getExitHandler(), and instance.
Referenced by callExit(), disableExit(), isExitEnabled(), and setExitHandler().
getIdntfr()
uint32_t Activity::getIdntfr ()
Definition at line 108 of file Activity-trace.cpp.
References counter(), currentThread, SysActivity::getThreadID(), and threadIDs.
Referenced by RexxActivation::createTraceObject(), RexxInstructionGuard::execute(), guardWait(), and setCallerStackFrameAsStringTable().
getInstance()
InterpreterInstance* Activity::getInstance () inline
Definition at line 229 of file Activity.hpp.
References instance.
Referenced by RexxActivation::createTraceObject(), PackageClass::findProgramRexx(), GetInterpreterInstance(), LoadPackage(), LoadPackageFromData(), PackageClass::loadRequires(), PackageClass::newRexx(), ReleaseGlobalReference(), RequestGlobalReference(), RexxActivation::RexxActivation(), RexxStartDispatcher::run(), RexxActivation::run(), and RoutineClass::runProgram().
getInstanceSecurityManager()
SecurityManager * Activity::getInstanceSecurityManager ()
Return the security manager in effect for this instance.
Returns
The globally defined security manager.
Definition at line 3118 of file Activity-trace.cpp.
References InterpreterInstance::getSecurityManager(), and instance.
Referenced by NativeActivation::callNativeRoutine(), NativeActivation::callRegisteredRoutine(), RexxActivation::getEffectiveSecurityManager(), RexxActivation::RexxActivation(), and NativeActivation::run().
getLastMessageName()
RexxString * Activity::getLastMessageName ()
Get the name of the last message invocation.
Returns
The last message name.
Definition at line 3592 of file Activity-trace.cpp.
References activationFrames, and ActivationFrame::messageName().
Referenced by lastMessageName().
getLocal()
DirectoryClass * Activity::getLocal ()
Retrieve the .local directory for the current activity.
Returns
The .local directory.
Definition at line 2279 of file Activity-trace.cpp.
References InterpreterInstance::getLocal(), and instance.
Referenced by ActivityManager::getLocal(), and GetLocalEnvironment().
getLocalEnvironment()
RexxObject * Activity::getLocalEnvironment (RexxString * name)
Retrieve a value from the instance local environment.
Parameters
name The name of the .local object.
Returns
The object stored at the given name.
Definition at line 3554 of file Activity-trace.cpp.
References InterpreterInstance::getLocalEnvironment(), and instance.
Referenced by ActivityManager::getLocalEnvironment(), RexxActivation::getLocalEnvironment(), lineIn(), pullInput(), queue(), sayOutput(), traceInput(), and traceOutput().
getNestedActivity()
Activity* Activity::getNestedActivity () inline
Definition at line 254 of file Activity.hpp.
References nestedActivity.
Referenced by ActivityManager::returnActivity().
getNumericSettings()
const NumericSettings* Activity::getNumericSettings () inline
Definition at line 294 of file Activity.hpp.
References numericSettings.
getRandomSeed()
uint64_t Activity::getRandomSeed ()
Get a new random seed value for a new activation.
Returns
A random seed value. Each call will return a unique value.
Definition at line 463 of file Activity-trace.cpp.
References randomSeed.
Referenced by RexxActivation::RexxActivation().
getThreadContext()
RexxThreadContext* Activity::getThreadContext () inline
Definition at line 303 of file Activity.hpp.
References ActivityContext::threadContext, and threadContext.
Referenced by InterpreterInstance::attachThread(), and InterpreterInstance::getRootThreadContext().
getTopStackFrame()
ActivationBase* Activity::getTopStackFrame () inline
Definition at line 292 of file Activity.hpp.
References topStackFrame.
Referenced by checkCondition(), RexxObject::checkPackage(), RexxObject::checkPrivate(), RexxObject::checkRestrictedMethod(), MessageClass::dispatch(), NativeContextBlock::NativeContextBlock(), raiseCondition(), raiseException(), raisePropagate(), MessageClass::sendNotification(), and unwindToFrame().
guardPost()
void Activity::guardPost ()
Post a guard expression wake up notice
Definition at line 2062 of file Activity-trace.cpp.
References guardSem, OREF_NULL, SysSemaphore::post(), and waitingObject.
Referenced by RexxVariable::notify(), VariableDictionary::release(), and MessageClass::sendNotification().
guardSet()
void Activity::guardSet ()
Clear a guard expression semaphore in preparation to perform a guard wait
Definition at line 2073 of file Activity-trace.cpp.
References guardSem, and SysSemaphore::reset().
Referenced by RexxInstructionGuard::execute(), NativeActivation::guardOffWhenUpdated(), NativeActivation::guardOnWhenUpdated(), and NativeActivation::guardWait().
guardWait()
void Activity::guardWait ()
Wait for a guard post event
Definition at line 2045 of file Activity-trace.cpp.
References getIdntfr(), releaseAccess(), requestAccess(), and waitForGuardPermission().
Referenced by NativeActivation::guardWait(), and RexxActivation::guardWait().
halt()
bool Activity::halt (RexxString * d)
Tap the current running activation on this activity to halt as soon as possible.
Parameters
d The description string for the halt.
Returns
true if we have an activation to tell to stop, false if the activity's not really working.
Definition at line 2136 of file Activity-trace.cpp.
References currentRexxFrame, and RexxActivation::halt().
Referenced by MessageClass::halt(), ActivityManager::haltActivity(), InterpreterInstance::haltAllActivities(), and HaltThread().
hasRunPermission()
bool Activity::hasRunPermission () inline
Definition at line 287 of file Activity.hpp.
References dispatchPosted.
Referenced by ActivityManager::dispatchNext().
inheritSettings()
void Activity::inheritSettings (Activity * parent)
Inherit all activity-specific settings from a parent activity.
Parameters
parent The source of the setting information.
Definition at line 3461 of file Activity-trace.cpp.
References clauseExitUsed.
Referenced by ActivityManager::createNewActivity().
initializeThreadContext()
void Activity::initializeThreadContext () static
Complete initialization of the thread context function vector by filling in the constant objects.
Definition at line 1837 of file Activity-trace.cpp.
References RexxThreadInterface::RexxFalse, RexxThreadInterface::RexxNil, RexxThreadInterface::RexxNullString, RexxThreadInterface::RexxTrue, TheFalseObject, TheNilObject, TheTrueObject, and threadContextFunctions.
Referenced by MemoryObject::createImage(), and MemoryObject::restoreImage().
isActive()
bool Activity::isActive () inline
Definition at line 237 of file Activity.hpp.
References nestedCount.
Referenced by InterpreterInstance::haltAllActivities(), InterpreterInstance::removeInactiveActivities(), InterpreterInstance::terminate(), and InterpreterInstance::traceAllActivities().
isAttached()
bool Activity::isAttached () inline
Definition at line 255 of file Activity.hpp.
References attachCount.
Referenced by InterpreterInstance::detachThread().
isClauseExitUsed()
bool Activity::isClauseExitUsed () inline
Definition at line 195 of file Activity.hpp.
References clauseExitUsed.
Referenced by RexxActivation::run().
isExitEnabled()
bool Activity::isExitEnabled (int exitNum) inline protected
Definition at line 352 of file Activity.hpp.
References getExitHandler(), and ExitHandler::isEnabled().
Referenced by callCommandExit(), callDebugInputExit(), callFunctionExit(), callHaltClearExit(), callHaltTestExit(), callInitializationExit(), callNovalueExit(), callObjectFunctionExit(), callPullExit(), callPushExit(), callQueueNameExit(), callQueueSizeExit(), callSayExit(), callScriptingExit(), callTerminalInputExit(), callTerminationExit(), callTraceExit(), callTraceTestExit(), callValueExit(), and queryTrcHlt().
isInactive()
bool Activity::isInactive () inline
Definition at line 238 of file Activity.hpp.
References nestedCount.
Referenced by exitCurrentThread().
isInterpreterRoot()
bool Activity::isInterpreterRoot () inline
Definition at line 251 of file Activity.hpp.
References interpreterRoot.
isNestable()
bool Activity::isNestable () inline
Definition at line 248 of file Activity.hpp.
References waitingOnSemaphore.
Referenced by InterpreterInstance::attachThread().
isNestedAttach()
bool Activity::isNestedAttach () inline
Definition at line 234 of file Activity.hpp.
References attachCount, and newThreadAttached.
Referenced by InterpreterInstance::detachThread().
isSameActivityStack()
bool Activity::isSameActivityStack (Activity * target)
Check to see if the target activity is part of the same activity stack on a thread.
Parameters
target The activity to check.
Returns
true if the target is the same as the argument activity or if the argument activity is a parent activity to the argument activity due to AttachThread nesting.
Definition at line 1980 of file Activity-trace.cpp.
References isThread(), and threadIdMethod().
Referenced by VariableDictionary::reserve().
isSuspended()
bool Activity::isSuspended () inline
Definition at line 241 of file Activity.hpp.
References suspended.
Referenced by InterpreterInstance::findActivity(), and ActivityManager::findActivity().
isThread()
bool Activity::isThread (thread_id_t id) inline
Definition at line 194 of file Activity.hpp.
References currentThread, and SysActivity::equals().
Referenced by InterpreterInstance::findActivity(), ActivityManager::findActivity(), and isSameActivityStack().
isWaiting()
bool Activity::isWaiting () inline
Definition at line 249 of file Activity.hpp.
References waitingForDispatch, and waitingOnSemaphore.
isWaitingForApiAccess()
bool Activity::isWaitingForApiAccess () inline
Definition at line 247 of file Activity.hpp.
References waitingForApiAccess.
Referenced by ActivityManager::returnWaitingActivity(), and ActivityManager::suspendDispatch().
isWaitingForDispatch()
bool Activity::isWaitingForDispatch () inline
Definition at line 244 of file Activity.hpp.
References waitingForDispatch.
Referenced by ActivityManager::handleNestedActivity(), and ActivityManager::returnActivity().
joinKernelQueue()
void Activity::joinKernelQueue ()
kill()
void Activity::kill (DirectoryClass * conditionObj)
Kill a running activity,
Parameters
conditionObj The condition object associated with the kill reason.
Definition at line 2095 of file Activity-trace.cpp.
References conditionobj, and UnhandledCondition.
Referenced by raisePropagate().
lineIn()
RexxString * Activity::lineIn (RexxActivation * activation)
Read a line from the input stream.
Parameters
activation The activation context.
Returns
The input string.
Definition at line 3280 of file Activity-trace.cpp.
References callTerminalInputExit(), getLocalEnvironment(), OREF_NULL, RexxObject::sendMessage(), and TheNilObject.
Referenced by RexxActivation::lineIn(), and pullInput().
lineOut()
RexxObject * Activity::lineOut (RexxString * line)
Write a line to the real default output stream.
Parameters
line The line to write.
Returns
Returns the residual count of 0 as an integer.
Definition at line 3264 of file Activity-trace.cpp.
References IntegerZero, line, and line_end.
Referenced by sayOutput(), and traceOutput().
live()
void Activity::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 121 of file Activity-trace.cpp.
References activations, conditionobj, currentExit, currentRexxFrame, dispatchMessage, frameStack, heldMutexes, instance, ActivationStack::live(), ProtectedBase::mark(), memory_mark, nestedActivity, ProtectedBase::next, oldActivity, protectedObjects, requiresTable, topStackFrame, and waitingObject.
liveGeneral()
void Activity::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 154 of file Activity-trace.cpp.
References activations, conditionobj, currentExit, currentRexxFrame, dispatchMessage, frameStack, heldMutexes, instance, ActivationStack::liveGeneral(), ProtectedBase::markGeneral(), memory_mark_general, nestedActivity, oldActivity, protectedObjects, requiresTable, topStackFrame, and waitingObject.
messageSubstitution()
RexxString * Activity::messageSubstitution (RexxString * message, ArrayClass * additional)
Perform any required message substitutions on the secondary error message.
Parameters
message The error text. Substitution parameters are marked inside the messages.
additional The array of values to substitute.
Returns
The formatted string.
Definition at line 1240 of file Activity-trace.cpp.
References RexxInternalObject::defaultName(), ArrayClass::get(), getActivationLevel(), RexxString::getChar(), RexxString::getLength(), RexxString::getStringData(), new_string(), OREF_NULL, RexxString::pos(), requestingString, restoreActivationLevel(), ArrayClass::size(), stackcheck, and RexxInternalObject::stringValue().
Referenced by buildMessage(), and reraiseException().
nestAttach()
void Activity::nestAttach ()
Handle a nested attach on an Activity. In this situation, a program has exited the Rexx code to native code, which then has used AttachThread() to access API services. We Reuse the activity, but push another NativeActivation instance on to the stack to anchor allocated objects.
Definition at line 1889 of file Activity-trace.cpp.
References attachCount, createNewActivationStack(), releaseAccess(), and requestAccess().
Referenced by InterpreterInstance::attachThread().
operator delete()
void Activity::operator delete (void *) inline
Definition at line 105 of file Activity.hpp.
operator new()
void * Activity::operator new (size_t size)
Allocate storage for a new activity object.
Parameters
size The size to allocate.
Returns
Storate for an activity object.
Definition at line 99 of file Activity-trace.cpp.
References new_object(), and T_Activity.
popStackFrame() [1/2]
void Activity::popStackFrame (ActivationBase * target)
Pop entries off the stack frame upto and including the target activation.
Parameters
target The target for the pop operation.
Definition at line 1690 of file Activity-trace.cpp.
References activations, cleanupStackFrame(), InternalStack::pop(), stackFrameDepth, and updateFrameMarkers().
popStackFrame() [2/2]
void Activity::popStackFrame (bool reply)
Pop the top activation from the frame stack.
Parameters
reply Indicates we're popping the frame for a reply operation. In that case, we can't return the frame to the activation cache.
Definition at line 1639 of file Activity-trace.cpp.
References activations, ActivationBase::isStackBase(), InternalStack::pop(), InternalStack::push(), RexxInternalObject::setHasNoReferences(), stackFrameDepth, and updateFrameMarkers().
Referenced by NativeActivation::callNativeRoutine(), NativeActivation::callRegisteredRoutine(), enterKernel(), error(), RexxActivation::exitFrom(), RexxActivation::raise(), raiseException(), RexxActivation::raiseExit(), raisePropagate(), returnAttach(), run(), NativeActivation::run(), RexxActivation::run(), and unwindToFrame().
postDispatch()
void Activity::postDispatch ()
Post an activities run semaphore
Definition at line 2082 of file Activity-trace.cpp.
References dispatchPosted, SysSemaphore::post(), and runSem.
Referenced by ActivityManager::dispatchNext(), ActivityManager::returnWaitingActivity(), and waitForDispatch().
previous()
RexxObject* Activity::previous ()
pullInput()
RexxString * Activity::pullInput (RexxActivation * activation)
Read a line for the pull instruction.
Parameters
activation The activation context.
Returns
The read input string.
Definition at line 3233 of file Activity-trace.cpp.
References callPullExit(), getLocalEnvironment(), lineIn(), OREF_NULL, RexxObject::sendMessage(), and TheNilObject.
Referenced by RexxActivation::pullInput().
pushStackFrame()
void Activity::pushStackFrame (ActivationBase * new_activation)
Push a Rexx code activation on to the stack frame.
Parameters
new_activation The new activation to add.
Definition at line 1591 of file Activity-trace.cpp.
References activations, checkActivationStack(), ActivationBase::isStackBase(), InternalStack::push(), ActivationBase::setPreviousStackFrame(), stackFrameDepth, topStackFrame, and updateFrameMarkers().
Referenced by NativeRoutine::call(), RegisteredRoutine::call(), RexxCode::call(), RexxActivation::debugInterpret(), exitKernel(), RexxActivation::internalCall(), RexxActivation::internalCallTrap(), RexxActivation::interpret(), RexxCode::run(), NativeMethod::run(), run(), and RexxActivation::run().
queryTrcHlt()
void Activity::queryTrcHlt ()
Determine if Halt or Trace System exits are set and set a flag to indicate this.
Definition at line 2301 of file Activity-trace.cpp.
References clauseExitUsed, isExitEnabled(), RXHLT, and RXTRC.
Referenced by setupExits().
queue()
void Activity::queue (RexxActivation * activation, RexxString * line, QueueOrder order)
Write a line to the current output queue.
Parameters
activation The current activation context.
line The line to push/queue
order The queuing order.
Definition at line 3314 of file Activity-trace.cpp.
References callPushExit(), getLocalEnvironment(), line, OREF_NULL, QUEUE_LIFO, and RexxObject::sendMessage().
Referenced by RexxActivation::queue().
raiseCondition() [1/2]
bool Activity::raiseCondition (DirectoryClass * conditionObj)
Process condition trapping for a condition or syntax error.
Parameters
conditionObj The condition object that describes the condition.
Returns
true if this was trapped, false otherwise. If trapped via a SIGNAL ON, this will NOT return to here.
Definition at line 677 of file Activity-trace.cpp.
References DirectoryClass::get(), getTopStackFrame(), isOfClass, and ActivationBase::isStackBase().
raiseCondition() [2/2]
bool Activity::raiseCondition (RexxString * condition, RexxObject * rc, RexxObject * description, RexxObject * additional, RexxObject * result)
Raise a condition, with potential trapping. Also checks for potential ::OPTIONS condition overrides.
Parameters
condition The condition name.
rc The rc value
description The description value.
additional the exception additional information.
result The condition result info.
Returns
true if this was trapped via CALL ON, false for untrapped conditions.
Definition at line 590 of file Activity-trace.cpp.
References checkCondition(), createConditionObject(), Error_Execution_error_syntax, Error_Execution_failure_syntax, Error_Execution_lostdigits_syntax, Error_Execution_nostring_syntax, Error_Execution_notready_syntax, getCurrentRexxFrame(), RexxActivation::isErrorSyntaxEnabled(), RexxActivation::isFailureSyntaxEnabled(), RexxActivation::isLostdigitsSyntaxEnabled(), RexxActivation::isNostringSyntaxEnabled(), RexxActivation::isNotreadySyntaxEnabled(), OREF_NULL, reportException(), and RexxString::strCompare().
Referenced by CallThrowCondition(), RexxActivation::command(), ExitThrowCondition(), RexxActivation::processClauseBoundary(), NativeActivation::raiseCondition(), RaiseCondition(), raiseException(), reportCondition(), RexxInternalObject::requestString(), and ThrowCondition().
raiseException()
void Activity::raiseException (RexxErrorCodes errcode, RexxString * description, ArrayClass * additional, RexxObject * result)
Raise an exception on the current activity.
Parameters
errcode The syntax error code.
description The associated description string.
additional The message substitution parameters.
result The message result.
Definition at line 915 of file Activity-trace.cpp.
References conditionobj, createExceptionObject(), getCurrentRexxFrame(), getTopStackFrame(), RexxActivation::isForwarded(), OREF_NULL, popStackFrame(), DirectoryClass::put(), raiseCondition(), raisePropagate(), RecursiveStringError, requestingString, TheTrueObject, and unwindToFrame().
Referenced by LanguageParser::error(), LanguageParser::errorLine(), LanguageParser::errorPosition(), LanguageParser::errorToken(), RexxActivation::raise(), reportAnException(), and reportException().
raisePropagate()
void Activity::raisePropagate (DirectoryClass * conditionObj)
Propagate a condition down the chain of activations
Parameters
conditionObj The condition object.
Definition at line 1373 of file Activity-trace.cpp.
References DirectoryClass::get(), getTopStackFrame(), ActivationBase::isStackBase(), kill(), OREF_NULL, popStackFrame(), DirectoryClass::put(), TheTrueObject, and ActivationBase::trap().
Referenced by raiseException(), and reraiseException().
releaseAccess()
void Activity::releaseAccess ()
Release exclusive access to the kernel
Definition at line 2185 of file Activity-trace.cpp.
References ActivityManager::currentActivity, ActivityManager::releaseAccess(), and Numerics::setDefaultSettings().
Referenced by InterpreterInstance::attachThread(), NativeActivation::callNativeRoutine(), NativeActivation::callRegisteredRoutine(), Interpreter::createInstance(), InterpreterInstance::detachThread(), exitCurrentThread(), exitKernel(), guardWait(), nestAttach(), NativeActivation::run(), runThread(), UnsafeBlock::UnsafeBlock(), waitReserve(), and yieldControl().
releaseStackFrame()
void Activity::releaseStackFrame (RexxInternalObject ** frame) inline
Definition at line 317 of file Activity.hpp.
References frameStack, and ActivationStack::releaseFrame().
Referenced by RexxActivation::run(), and RexxActivation::termination().
relinquish()
void Activity::relinquish ()
Relinquish to other system processes
Definition at line 2106 of file Activity-trace.cpp.
References ActivityManager::relinquish().
Referenced by RexxActivation::run().
removeMutex()
void Activity::removeMutex (MutexSemaphoreClass * sem)
Remove a mutex from the activity held list
Parameters
sem the semaphore to remove
Definition at line 3618 of file Activity-trace.cpp.
References HashCollection::hasIndex(), heldMutexes, nestedActivity, OREF_NULL, HashCollection::remove(), and removeMutex().
Referenced by MutexSemaphoreClass::close(), MutexSemaphoreClass::release(), and removeMutex().
removeRunningRequires()
void Activity::removeRunningRequires (RexxInternalObject * program) inline
Definition at line 296 of file Activity.hpp.
References HashCollection::remove(), and requiresTable.
Referenced by InstallingPackage::~InstallingPackage().
reportAnException() [1/17]
void Activity::reportAnException (RexxErrorCodes errcode)
Simple raise a specific error number function.
Parameters
errcode
Definition at line 752 of file Activity-trace.cpp.
References OREF_NULL, and raiseException().
reportAnException() [2/17]
void Activity::reportAnException (RexxErrorCodes errcode, const char * string)
Definition at line 833 of file Activity-trace.cpp.
References new_string().
Referenced by reportAnException(), and reportException().
reportAnException() [3/17]
void Activity::reportAnException (RexxErrorCodes errcode, const char * string1, const char * string2)
Raise an error using aASCII-A string as a substitutions parameters
Parameters
errcode The error code.
string The substitution value.
Definition at line 846 of file Activity-trace.cpp.
References new_string(), and reportAnException().
reportAnException() [4/17]
void Activity::reportAnException (RexxErrorCodes errcode, const char * string, RexxObject * obj)
Definition at line 883 of file Activity-trace.cpp.
References new_string(), and reportAnException().
reportAnException() [5/17]
void Activity::reportAnException (RexxErrorCodes errcode, const char * substitution1, RexxObject * substitution2, const char * substitution3, RexxObject * substitution4)
Raise an error with four object substitutions in the message.
Parameters
errcode The error code.
substitution1 The substitution value.
substitution2 Another substitution value.
Definition at line 828 of file Activity-trace.cpp.
References new_array(), new_string(), OREF_NULL, and raiseException().
reportAnException() [6/17]
void Activity::reportAnException (RexxErrorCodes errcode, const char * string, RexxObject * obj, wholenumber_t integer)
Definition at line 865 of file Activity-trace.cpp.
References new_integer(), new_string(), and reportAnException().
reportAnException() [7/17]
void Activity::reportAnException (RexxErrorCodes errcode, const char * string, wholenumber_t integer)
Definition at line 852 of file Activity-trace.cpp.
References new_integer(), new_string(), and reportAnException().
reportAnException() [8/17]
void Activity::reportAnException (RexxErrorCodes errcode, const char * string, wholenumber_t integer, RexxObject * obj)
Definition at line 859 of file Activity-trace.cpp.
References new_integer(), new_string(), and reportAnException().
reportAnException() [9/17]
void Activity::reportAnException (RexxErrorCodes errcode, RexxObject * substitution1)
Raise an error with a single object substitution in the message.
Parameters
errcode The error code.
substitution1 The substitution value.
Definition at line 766 of file Activity-trace.cpp.
References new_array(), OREF_NULL, and raiseException().
reportAnException() [10/17]
void Activity::reportAnException (RexxErrorCodes errcode, RexxObject * obj, const char * string)
Definition at line 877 of file Activity-trace.cpp.
References new_string(), and reportAnException().
reportAnException() [11/17]
void Activity::reportAnException (RexxErrorCodes errcode, RexxObject * substitution1, RexxObject * substitution2)
Raise an error with two object substitutions in the message.
Parameters
errcode The error code.
substitution1 The substitution value.
substitution2 Another substitution value.
Definition at line 781 of file Activity-trace.cpp.
References new_array(), OREF_NULL, and raiseException().
reportAnException() [12/17]
void Activity::reportAnException (RexxErrorCodes errcode, RexxObject * substitution1, RexxObject * substitution2, RexxObject * substitution3)
Raise an error with three object substitutions in the message.
Parameters
errcode The error code.
substitution1 The substitution value.
substitution2 Another substitution value.
Definition at line 797 of file Activity-trace.cpp.
References new_array(), OREF_NULL, and raiseException().
reportAnException() [13/17]
void Activity::reportAnException (RexxErrorCodes errcode, RexxObject * substitution1, RexxObject * substitution2, RexxObject * substitution3, RexxObject * substitution4)
Raise an error with four object substitutions in the message.
Parameters
errcode The error code.
substitution1 The substitution value.
substitution2 Another substitution value.
Definition at line 812 of file Activity-trace.cpp.
References new_array(), OREF_NULL, and raiseException().
reportAnException() [14/17]
void Activity::reportAnException (RexxErrorCodes errcode, RexxObject * obj, wholenumber_t integer)
Definition at line 871 of file Activity-trace.cpp.
References new_integer(), and reportAnException().
reportAnException() [15/17]
void Activity::reportAnException (RexxErrorCodes errcode, wholenumber_t integer)
Definition at line 889 of file Activity-trace.cpp.
References new_integer(), and reportAnException().
reportAnException() [16/17]
void Activity::reportAnException (RexxErrorCodes errcode, wholenumber_t a1, RexxObject * a2)
Definition at line 900 of file Activity-trace.cpp.
References new_integer(), and reportAnException().
reportAnException() [17/17]
void Activity::reportAnException (RexxErrorCodes errcode, wholenumber_t integer, wholenumber_t integer2)
Definition at line 894 of file Activity-trace.cpp.
References new_integer(), and reportAnException().
requestAccess()
void Activity::requestAccess ()
Acquire exclusive access to the kernel
Definition at line 2200 of file Activity-trace.cpp.
References ActivityManager::addWaitingActivity(), ActivityManager::lockKernelImmediate(), and setupCurrentActivity().
Referenced by NativeActivation::callNativeRoutine(), NativeActivation::callRegisteredRoutine(), RexxActivation::debugInterpret(), enterKernel(), guardWait(), nestAttach(), RexxActivation::processTraps(), run(), NativeActivation::run(), RexxActivation::run(), runThread(), waitReserve(), yieldControl(), and UnsafeBlock::~UnsafeBlock().
requestApiAccess()
void Activity::requestApiAccess ()
Acquire priority API exclusive access to the kernel
Definition at line 2216 of file Activity-trace.cpp.
References ActivityManager::addWaitingApiActivity(), clearWaitingForApiAccess(), ActivityManager::lockKernelImmediate(), setupCurrentActivity(), and setWaitingForApiAccess().
Referenced by enterCurrentThread(), and InterpreterInstance::enterOnCurrentThread().
reraiseException()
void Activity::reraiseException (DirectoryClass * exobj)
Reraise an exception object in a prior context.
Parameters
exobj The exception object with the syntax information.
Definition at line 1324 of file Activity-trace.cpp.
References RexxActivation::currentLine(), DirectoryClass::get(), getCurrentRexxFrame(), Interpreter::getMessageText(), MESSAGE, Interpreter::messageNumber(), messageSubstitution(), new_integer(), OREF_NULL, DirectoryClass::put(), raisePropagate(), DirectoryClass::remove(), and work.
Referenced by NativeActivation::checkConditions(), RexxActivation::raise(), and MessageClass::result().
reset()
void Activity::reset ()
Initialize an Activity object that's being recycled for another use.
Definition at line 411 of file Activity-trace.cpp.
References activate().
Referenced by ActivityManager::createNewActivity().
resolveCommandHandler()
CommandHandler * Activity::resolveCommandHandler (RexxString * name)
Resolve a command handler from the interpreter instance.
Parameters
name The name of the command environment.
Returns
A configured command environment, or OREF_NULL if the target environment is not found.
Definition at line 3569 of file Activity-trace.cpp.
References instance, and InterpreterInstance::resolveCommandHandler().
Referenced by RexxActivation::command().
resolveProgramName()
RexxString * Activity::resolveProgramName (RexxString * name, RexxString * dir, RexxString * ext, ResolveType type)
Resolve a program using the activity context information.
Parameters
name The name we're interested in.
dir A parent directory to use as part of the search.
ext Any parent extension name.
type The resolve type, RESOLVE_DEFAULT or RESOLVE_REQUIRES.
Returns
The fully resolved file name, if it exists. Returns OREF_NULL for non-located files.
Definition at line 3541 of file Activity-trace.cpp.
References instance, InterpreterInstance::resolveProgramName(), and type.
Referenced by MemoryObject::createImage(), LoadPackage(), PackageClass::resolveProgramName(), RexxStartDispatcher::run(), CallProgramDispatcher::run(), and TranslateDispatcher::run().
restoreActivationLevel()
void Activity::restoreActivationLevel (size_t l) inline
Definition at line 240 of file Activity.hpp.
References nestedCount.
Referenced by NativeActivation::callNativeRoutine(), NativeActivation::callRegisteredRoutine(), messageSubstitution(), run(), NativeActivation::run(), and runThread().
returnAttach()
void Activity::returnAttach ()
Return from a nested attach. We need to pop our dummy native activation from the stack so that objects in the local reference table can be GC'd.
Definition at line 1910 of file Activity-trace.cpp.
References activations, attachCount, ActivationBase::isStackBase(), InternalStack::pop(), popStackFrame(), RexxInternalObject::setHasNoReferences(), stackFrameDepth, topStackFrame, and updateFrameMarkers().
Referenced by InterpreterInstance::detachThread().
run() [1/5]
void Activity::run ()
Release an activity to run
Definition at line 1513 of file Activity-trace.cpp.
References guardSem, SysSemaphore::post(), runSem, and yield().
Referenced by ExitHandler::call(), CommandHandler::call(), CallProgram(), CallRoutine(), ActivityDispatcher::invoke(), LibraryPackage::loadPackage(), StreamObjectInputSource::read(), run(), RexxActivation::run(), runThread(), MemoryObject::runUninits(), MessageClass::start(), and LibraryPackage::unload().
run() [2/5]
void Activity::run (ActivityDispatcher & target)
Run a task that needs to enter the interpreter on a thread. The activity will set up the root activation and run the task under that context to ensure proper error handling and kernel access.
Parameters
target The dispatcher object that implements the call out.
Definition at line 3355 of file Activity-trace.cpp.
References MemoryObject::checkUninitQueue(), clearCurrentCondition(), ActivityDispatcher::conditionData, conditionobj, createNewActivationStack(), ActivityManager::currentActivity, currentThread, error(), errorRecoveryStack, generateRandomNumberSeed(), getActivationLevel(), getApiContext(), SysActivity::getStackBase(), ActivityDispatcher::handleError(), memoryObject, ActivityManager::newNativeActivation(), OREF_NULL, pushStackFrame(), requestAccess(), restoreActivationLevel(), NativeActivation::run(), NativeActivation::setConditionInfo(), stackFrameDepth, stackLimit, and unwindToDepth().
run() [3/5]
void Activity::run (CallbackDispatcher & target)
Run a task under the context of an activity. This will be a task that calls out from the interpreter, which the kernel lock released during the call.
Parameters
target The dispatcher object that implements the call out.
Definition at line 3419 of file Activity-trace.cpp.
References currentRexxFrame, NativeActivation::enableVariablepool(), ActivityManager::newNativeActivation(), popStackFrame(), pushStackFrame(), and NativeActivation::run().
run() [4/5]
void Activity::run (MessageClass * target)
Run a message object on a spawned thread.
Parameters
target The target message object.
Definition at line 1530 of file Activity-trace.cpp.
References dispatchMessage, and run().
run() [5/5]
void Activity::run (TrappingDispatcher & target)
Run a task under the context of an activity. This will be a task that runs with a nested error trapping without releasing the kernel lock.
Parameters
target The dispatcher object that implements the call out.
Definition at line 3442 of file Activity-trace.cpp.
References currentRexxFrame, ActivityManager::newNativeActivation(), popStackFrame(), pushStackFrame(), and NativeActivation::run().
runThread()
void Activity::runThread ()
The main entry point for spawned activities.
Definition at line 183 of file Activity-trace.cpp.
References ActivityManager::activityEnded(), MemoryObject::checkUninitQueue(), cleanupMutexes(), ActivityManager::currentActivity, currentThread, deactivate(), ActivationBase::dispatch(), dispatchMessage, error(), errorRecoveryStack, exit, getActivationLevel(), SysActivity::getStackBase(), guardSem, instance, memoryObject, OREF_NULL, InterpreterInstance::poolActivity(), releaseAccess(), requestAccess(), SysSemaphore::reset(), restoreActivationLevel(), run(), runSem, stackcheck, stackLimit, topStackFrame, and waitForRunPermission().
sayOutput()
void Activity::sayOutput (RexxActivation * activation, RexxString * line)
Write out a line of say output
Parameters
activation The current activation context.
line The output line.
Definition at line 3172 of file Activity-trace.cpp.
References callSayExit(), getLocalEnvironment(), line, lineOut(), OREF_NULL, RexxObject::sendMessage(), and TheNilObject.
Referenced by RexxActivation::sayOutput().
setCallerStackFrameAsStringTable()
void Activity::setCallerStackFrameAsStringTable (Activity * oldActivity, Activity * newActivity, bool skipFirst) static
Generates and saves a StringTable to store stackFrame infos of oldActivity in newActivity (for TraceObject), used by MessageClass::start().
Definition at line 1193 of file Activity-trace.cpp.
References generateCallerStackFrame(), getIdntfr(), RexxActivation::getStackFrameAsStringTable(), new_integer(), oldActivity, and spawnerStackFrameInfo.
Referenced by RexxActivation::run(), and MessageClass::start().
setExitHandler() [1/3]
void Activity::setExitHandler (int exitNum, const char * e) inline
Definition at line 330 of file Activity.hpp.
References getExitHandler(), and ExitHandler::resolve().
setExitHandler() [2/3]
void Activity::setExitHandler (int exitNum, REXXPFN e) inline
Definition at line 329 of file Activity.hpp.
References getExitHandler(), and ExitHandler::setEntryPoint().
setExitHandler() [3/3]
void Activity::setExitHandler (RXSYSEXIT & e) inline
Definition at line 331 of file Activity.hpp.
References getExitHandler(), ExitHandler::resolve(), _RXSYSEXIT::sysexit_code, and _RXSYSEXIT::sysexit_name.
setInterpreterRoot()
void Activity::setInterpreterRoot () inline
Definition at line 252 of file Activity.hpp.
References interpreterRoot.
Referenced by ActivityManager::getRootActivity().
setNestedActivity()
void Activity::setNestedActivity (Activity * a) inline
Definition at line 253 of file Activity.hpp.
References nestedActivity.
Referenced by ActivityManager::handleNestedActivity().
setSuspended()
void Activity::setSuspended (bool s) inline
Definition at line 250 of file Activity.hpp.
References suspended.
Referenced by detachInstance(), ActivityManager::handleNestedActivity(), and ActivityManager::returnActivity().
setTrace()
bool Activity::setTrace (bool on)
Tap the current running activation to turn on tracing as soon as possible.
Parameters
on Indicates whether we are turning trace on or off.
Returns
true if we have an activation to tell to stop, false if the activity's not really working.
Definition at line 2159 of file Activity-trace.cpp.
References currentRexxFrame, RexxActivation::externalTraceOff(), and RexxActivation::externalTraceOn().
Referenced by ActivityManager::setActivityTrace(), SetThreadTrace(), and InterpreterInstance::traceAllActivities().
setupAttachedActivity()
void Activity::setupAttachedActivity (InterpreterInstance * interpreter)
Set up an activity as a root activity used either for a main interpreter thread or an attached thread.
Parameters
interpreter The interpreter instance this thread belongs to.
Definition at line 1785 of file Activity-trace.cpp.
References addToInstance(), attachCount, createNewActivationStack(), and newThreadAttached.
Referenced by InterpreterInstance::attachThread(), and InterpreterInstance::initialize().
setupCurrentActivity()
void Activity::setupCurrentActivity ()
Perform final setup for an activity as the current activity. This assumes the kernel lock has already been obtained.
Definition at line 2251 of file Activity-trace.cpp.
References ActivityManager::currentActivity, numericSettings, and Numerics::setCurrentSettings().
Referenced by ActivityManager::addWaitingActivity(), ActivityManager::addWaitingApiActivity(), ActivityManager::attachThread(), ActivityManager::getRootActivity(), requestAccess(), and requestApiAccess().
setupExits()
void Activity::setupExits ()
Process for copying the exit definitions from the hosting instance.
Definition at line 1826 of file Activity-trace.cpp.
References queryTrcHlt().
Referenced by addToInstance(), and InterpreterInstance::initialize().
setWaitingForApiAccess()
void Activity::setWaitingForApiAccess () inline
Definition at line 246 of file Activity.hpp.
References waitingForApiAccess.
Referenced by requestApiAccess().
setWaitingForDispatch()
void Activity::setWaitingForDispatch () inline
Definition at line 243 of file Activity.hpp.
References waitingForDispatch.
Referenced by ActivityManager::addWaitingActivity(), and ActivityManager::addWaitingApiActivity().
spawnReply()
Activity * Activity::spawnReply ()
Create a new activity for processing a method reply instruction.
Returns
The newly created activity.
Definition at line 426 of file Activity-trace.cpp.
References instance, and InterpreterInstance::spawnActivity().
Referenced by RexxActivation::run(), and MessageClass::start().
terminatePoolActivity()
void Activity::terminatePoolActivity ()
Mark this FREE activity for termination. Set its exit flag to 1 and POST its run semaphore.
Definition at line 3340 of file Activity-trace.cpp.
References exit, SysSemaphore::post(), and runSem.
Referenced by ActivityManager::clearActivityPool(), and InterpreterInstance::removeInactiveActivities().
threadIdMethod()
thread_id_t Activity::threadIdMethod ()
Return the activity's thread id.
Returns
Definition at line 2291 of file Activity-trace.cpp.
References currentThread, and SysActivity::getThreadID().
Referenced by isSameActivityStack().
traceInput()
RexxString * Activity::traceInput (RexxActivation * activation)
Read a line of interactive debug.
Parameters
activation The activation context.
Returns
The debug input string.
Definition at line 3198 of file Activity-trace.cpp.
References callDebugInputExit(), getLocalEnvironment(), OREF_NULL, RexxObject::sendMessage(), and TheNilObject.
Referenced by RexxActivation::doDebugPause().
traceOutput()
void Activity::traceOutput (RexxActivation * activation, RexxString * line, StringTable * traceObject)
Write out a line of trace output.
Parameters
activation The current activation context.
line The output line
Definition at line 3131 of file Activity-trace.cpp.
References callTraceExit(), HashCollection::get(), getLocalEnvironment(), line, lineOut(), OREF_NULL, RexxInternalObject::requestString(), RexxObject::sendMessage(), and TheNilObject.
Referenced by RexxActivation::processTraceInfo().
unwindStackFrame()
void Activity::unwindStackFrame ()
Unwind the stack frames back to the base frame.
Definition at line 1714 of file Activity-trace.cpp.
References activations, ActivationBase::isStackBase(), InternalStack::pop(), InternalStack::push(), stackFrameDepth, and updateFrameMarkers().
unwindToDepth()
void Activity::unwindToDepth (size_t depth)
Unwind the stack frame down to a given depth.
Parameters
depth The target frame depth.
Definition at line 1746 of file Activity-trace.cpp.
References activations, InternalStack::pop(), stackFrameDepth, and updateFrameMarkers().
Referenced by run().
unwindToFrame()
void Activity::unwindToFrame (RexxActivation * frame)
Unwind to a particular stack frame, terminating each frame in turn;
Parameters
frame The target frame
Definition at line 1766 of file Activity-trace.cpp.
References getTopStackFrame(), and popStackFrame().
Referenced by raiseException(), and RexxActivation::run().
updateFrameMarkers()
void Activity::updateFrameMarkers ()
Update the top of the stack markers after a push or a pop operation on the stack frame.
Definition at line 1565 of file Activity-trace.cpp.
References activations, ActivityManager::currentActivity, currentRexxFrame, ActivationBase::findRexxContext(), ActivationBase::getNumericSettings(), InternalStack::getTop(), numericSettings, Numerics::setCurrentSettings(), and topStackFrame.
Referenced by createNewActivationStack(), popStackFrame(), pushStackFrame(), returnAttach(), unwindStackFrame(), and unwindToDepth().
validateThread()
void Activity::validateThread ()
Validate that an API call is occuring on the correct thread.
Definition at line 3578 of file Activity-trace.cpp.
References currentThread, Error_Execution_invalid_thread, reportException(), and SysActivity::validateThread().
Referenced by ApiContext::ApiContext().
waitForDispatch()
bool Activity::waitForDispatch () inline
Definition at line 269 of file Activity.hpp.
References MaxDispatchWait, postDispatch(), runSem, SysSemaphore::wait(), and waitingOnSemaphore.
Referenced by ActivityManager::addWaitingActivity().
waitForGuardPermission()
void Activity::waitForGuardPermission () inline
Definition at line 288 of file Activity.hpp.
References guardSem, SysSemaphore::wait(), and waitingOnSemaphore.
Referenced by guardWait(), and waitReserve().
waitForKernel()
void Activity::waitForKernel ()
Perform the actual wait for kernel access for this activity;
Definition at line 2236 of file Activity-trace.cpp.
References ActivityManager::lockKernel(), and waitingOnSemaphore.
Referenced by ActivityManager::addWaitingActivity(), and ActivityManager::addWaitingApiActivity().
waitForRunPermission()
void Activity::waitForRunPermission () inline
Definition at line 286 of file Activity.hpp.
References runSem, SysSemaphore::wait(), and waitingOnSemaphore.
Referenced by runThread().
waitReserve()
void Activity::waitReserve (RexxInternalObject * resource)
Wait for a new run event to occur
Parameters
resource The object we're waiting on (used for deadlock detection)
Definition at line 2028 of file Activity-trace.cpp.
References guardSem, releaseAccess(), requestAccess(), SysSemaphore::reset(), waitForGuardPermission(), and waitingObject.
Referenced by VariableDictionary::reserve(), and MessageClass::wait().
yield()
void Activity::yield ()
Tap the current running activation on this activity to give up control at the next reasonsable boundary.
Definition at line 2115 of file Activity-trace.cpp.
References currentRexxFrame, and RexxActivation::yield().
Referenced by ActivityManager::addWaitingActivity(), run(), and ActivityManager::yieldCurrentActivity().
yieldControl()
void Activity::yieldControl () inline
Definition at line 184 of file Activity.hpp.
References releaseAccess(), and requestAccess().
Referenced by RexxVariable::notify().
Friends And Related Function Documentation
ActivationFrame
friend class ActivationFrame friend
Definition at line 93 of file Activity.hpp.
ProtectedBase
friend class ProtectedBase friend
Definition at line 92 of file Activity.hpp.
Member Data Documentation
activationFrames
ActivationFrame* Activity::activationFrames protected
Definition at line 405 of file Activity.hpp.
Referenced by ActivationFrame::ActivationFrame(), ActivationFrame::disableFrame(), generateCallerStackFrame(), generateProgramInformation(), generateStackFrames(), and getLastMessageName().
activations
InternalStack* Activity::activations protected
Definition at line 369 of file Activity.hpp.
Referenced by Activity(), checkActivationStack(), createNewActivationStack(), live(), liveGeneral(), popStackFrame(), pushStackFrame(), returnAttach(), unwindStackFrame(), unwindToDepth(), and updateFrameMarkers().
activationStackSize
size_t Activity::activationStackSize protected
Definition at line 370 of file Activity.hpp.
Referenced by Activity(), and checkActivationStack().
attachCount
size_t Activity::attachCount protected
Definition at line 399 of file Activity.hpp.
Referenced by detachInstance(), isAttached(), isNestedAttach(), nestAttach(), returnAttach(), and setupAttachedActivity().
callContextFunctions
CallContextInterface Activity::callContextFunctions static protected
Initial value:
=
{
    CALL_INTERFACE_VERSION,
    GetCallArguments,
    GetCallArgument,
    GetRoutineName,
    GetCurrentRoutine,
    SetContextVariable,
    GetContextVariable,
    DropContextVariable,
    GetAllContextVariables,
    ResolveStemVariable,
    InvalidRoutine,
    GetContextDigits,
    GetContextFuzz,
    GetContextForm,
    GetCallerContext,
    FindCallContextClass,
    GetContextVariableReference,
    CallThrowException0,
    CallThrowException1,
    CallThrowException2,
    CallThrowException,
    CallThrowCondition,
}
The interface vector for call context callbacks.
Definition at line 412 of file Activity.hpp.
Referenced by createCallContext().
clauseExitUsed
bool Activity::clauseExitUsed protected
Definition at line 402 of file Activity.hpp.
Referenced by inheritSettings(), isClauseExitUsed(), and queryTrcHlt().
conditionobj
DirectoryClass* Activity::conditionobj protected
Definition at line 360 of file Activity.hpp.
Referenced by clearCurrentCondition(), detachInstance(), error(), getCurrentCondition(), kill(), live(), liveGeneral(), raiseException(), and run().
currentExit
RexxString* Activity::currentExit protected
Definition at line 382 of file Activity.hpp.
Referenced by live(), and liveGeneral().
currentRexxFrame
RexxActivation* Activity::currentRexxFrame protected
Definition at line 380 of file Activity.hpp.
Referenced by display(), displayDebug(), exitKernel(), getCurrentRexxFrame(), halt(), live(), liveGeneral(), run(), setTrace(), updateFrameMarkers(), and yield().
currentThread
SysActivity Activity::currentThread protected
Definition at line 386 of file Activity.hpp.
Referenced by Activity(), cleanupActivityResources(), generateRandomNumberSeed(), getIdntfr(), isThread(), run(), runThread(), threadIdMethod(), and validateThread().
dispatchMessage
MessageClass* Activity::dispatchMessage protected
Definition at line 362 of file Activity.hpp.
Referenced by detachInstance(), live(), liveGeneral(), run(), and runThread().
dispatchPosted
bool Activity::dispatchPosted protected
Definition at line 397 of file Activity.hpp.
Referenced by clearRunWait(), hasRunPermission(), and postDispatch().
errorRecoveryStack
const size_t Activity::errorRecoveryStack = 1024 * (32 + (4 * sizeof(void *))) static protected
Definition at line 422 of file Activity.hpp.
Referenced by Activity(), run(), and runThread().
exit
bool Activity::exit protected
Definition at line 390 of file Activity.hpp.
Referenced by runThread(), and terminatePoolActivity().
exitContextFunctions
ExitContextInterface Activity::exitContextFunctions static protected
Initial value:
=
{
    EXIT_INTERFACE_VERSION,
    SetExitContextVariable,
    GetExitContextVariable,
    DropExitContextVariable,
    GetAllExitContextVariables,
    GetExitCallerContext,
    GetExitContextVariableReference,
    ExitThrowException0,
    ExitThrowException1,
    ExitThrowException2,
    ExitThrowException,
    ExitThrowCondition,
}
The interface vector for exit handler callbacks.
Definition at line 413 of file Activity.hpp.
Referenced by createExitContext().
frameStack
ActivationStack Activity::frameStack protected
Definition at line 359 of file Activity.hpp.
Referenced by Activity(), allocateFrame(), allocateLocalVariableFrame(), allocateStackFrame(), live(), liveGeneral(), and releaseStackFrame().
guardSem
SysSemaphore Activity::guardSem protected
Definition at line 385 of file Activity.hpp.
Referenced by Activity(), cleanupActivityResources(), clearGuardWait(), guardPost(), guardSet(), run(), runThread(), waitForGuardPermission(), and waitReserve().
heldMutexes
IdentityTable* Activity::heldMutexes protected
Definition at line 407 of file Activity.hpp.
Referenced by addMutex(), cleanupMutexes(), live(), liveGeneral(), and removeMutex().
instance
InterpreterInstance* Activity::instance protected
Definition at line 356 of file Activity.hpp.
Referenced by addToInstance(), detachInstance(), detachThread(), getEffectiveSecurityManager(), getExitHandler(), getInstance(), getInstanceSecurityManager(), getLocal(), getLocalEnvironment(), live(), liveGeneral(), resolveCommandHandler(), resolveProgramName(), runThread(), and spawnReply().
interpreterRoot
bool Activity::interpreterRoot protected
Definition at line 393 of file Activity.hpp.
Referenced by isInterpreterRoot(), and setInterpreterRoot().
ioRedirectorContextFunctions
IORedirectorInterface Activity::ioRedirectorContextFunctions static protected
Initial value:
=
{
    REDIRECT_INTERFACE_VERSION,
    ReadInput,
    ReadInputBuffer,
    WriteOutput,
    WriteError,
    WriteOutputBuffer,
    WriteErrorBuffer,
    IsInputRedirected,
    IsOutputRedirected,
    IsErrorRedirected,
    AreOutputAndErrorSameTarget,
    IsRedirectionRequested,
}
The interface vector for command handler I/O redirection callbacks.
Definition at line 414 of file Activity.hpp.
Referenced by createRedirectorContext().
MaxDispatchWait
const uint32_t Activity::MaxDispatchWait = 50 static protected
Definition at line 349 of file Activity.hpp.
Referenced by waitForDispatch().
methodContextFunctions
MethodContextInterface Activity::methodContextFunctions static protected
Initial value:
=
{
    METHOD_INTERFACE_VERSION,
    GetMethodArguments,
    GetMethodArgument,
    GetMessageName,
    GetCurrentMethod,
    GetSelf,
    GetSuper,
    GetScope,
    SetObjectVariable,
    GetObjectVariable,
    DropObjectVariable,
    ForwardMessage,
    SetGuardOn,
    SetGuardOff,
    FindContextClass,
    GetCSelf,
    AllocateObjectMemory,
    FreeObjectMemory,
    ReallocateObjectMemory,
    GetObjectVariableReference,
    SetGuardOnWhenUpdated,
    SetGuardOffWhenUpdated,
    ThrowException0,
    ThrowException1,
    ThrowException2,
    ThrowException,
    ThrowCondition,
}
Definition at line 411 of file Activity.hpp.
Referenced by createMethodContext().
nestedActivity
Activity* Activity::nestedActivity protected
Definition at line 406 of file Activity.hpp.
Referenced by detachInstance(), getNestedActivity(), live(), liveGeneral(), removeMutex(), and setNestedActivity().
nestedCount
size_t Activity::nestedCount protected
Definition at line 398 of file Activity.hpp.
Referenced by activate(), deactivate(), getActivationLevel(), isActive(), isInactive(), and restoreActivationLevel().
newThreadAttached
bool Activity::newThreadAttached protected
Definition at line 400 of file Activity.hpp.
Referenced by detachInstance(), isNestedAttach(), and setupAttachedActivity().
numericSettings
const NumericSettings* Activity::numericSettings protected
Definition at line 387 of file Activity.hpp.
Referenced by Activity(), getNumericSettings(), setupCurrentActivity(), and updateFrameMarkers().
oldActivity
Activity* Activity::oldActivity protected
Definition at line 358 of file Activity.hpp.
Referenced by detachInstance(), live(), liveGeneral(), and setCallerStackFrameAsStringTable().
protectedObjects
ProtectedBase* Activity::protectedObjects protected
Definition at line 404 of file Activity.hpp.
Referenced by live(), liveGeneral(), ProtectedBase::ProtectedBase(), and ProtectedBase::~ProtectedBase().
randomSeed
uint64_t Activity::randomSeed protected
Definition at line 403 of file Activity.hpp.
Referenced by generateRandomNumberSeed(), and getRandomSeed().
requestingString
bool Activity::requestingString protected
Definition at line 391 of file Activity.hpp.
Referenced by messageSubstitution(), and raiseException().
requiresTable
StringTable* Activity::requiresTable protected
Definition at line 361 of file Activity.hpp.
Referenced by Activity(), addRunningRequires(), checkRequires(), live(), liveGeneral(), and removeRunningRequires().
runSem
SysSemaphore Activity::runSem protected
Definition at line 384 of file Activity.hpp.
Referenced by Activity(), cleanupActivityResources(), clearRunWait(), postDispatch(), run(), runThread(), terminatePoolActivity(), waitForDispatch(), and waitForRunPermission().
spawnerStackFrameInfo
StringTable* Activity::spawnerStackFrameInfo
Definition at line 166 of file Activity.hpp.
Referenced by setCallerStackFrameAsStringTable().
stackcheck
bool Activity::stackcheck protected
Definition at line 389 of file Activity.hpp.
Referenced by Activity(), checkStackSpace(), messageSubstitution(), and runThread().
stackFrameDepth
size_t Activity::stackFrameDepth protected
Definition at line 371 of file Activity.hpp.
Referenced by checkActivationStack(), createNewActivationStack(), getActivationDepth(), popStackFrame(), pushStackFrame(), returnAttach(), run(), unwindStackFrame(), and unwindToDepth().
stackLimit
char* Activity::stackLimit protected
Definition at line 401 of file Activity.hpp.
Referenced by Activity(), checkStackSpace(), run(), and runThread().
suspended
bool Activity::suspended protected
Definition at line 392 of file Activity.hpp.
Referenced by isSuspended(), and setSuspended().
threadContext
ActivityContext Activity::threadContext protected
Definition at line 357 of file Activity.hpp.
Referenced by addToInstance(), createCallContext(), createExitContext(), createMethodContext(), and getThreadContext().
threadContextFunctions
RexxThreadInterface Activity::threadContextFunctions static protected
Definition at line 410 of file Activity.hpp.
Referenced by addToInstance(), and initializeThreadContext().
topStackFrame
ActivationBase* Activity::topStackFrame protected
Definition at line 381 of file Activity.hpp.
Referenced by error(), getApiContext(), getEffectiveSecurityManager(), getTopStackFrame(), live(), liveGeneral(), pushStackFrame(), returnAttach(), runThread(), and updateFrameMarkers().
waitingForApiAccess
bool Activity::waitingForApiAccess protected
Definition at line 394 of file Activity.hpp.
Referenced by clearWaitingForApiAccess(), isWaitingForApiAccess(), and setWaitingForApiAccess().
waitingForDispatch
bool Activity::waitingForDispatch protected
Definition at line 395 of file Activity.hpp.
Referenced by clearWaitingForDispatch(), isWaiting(), isWaitingForDispatch(), and setWaitingForDispatch().
waitingObject
RexxInternalObject* Activity::waitingObject protected
Definition at line 383 of file Activity.hpp.
Referenced by checkDeadLock(), detachInstance(), guardPost(), live(), liveGeneral(), and waitReserve().
waitingOnSemaphore
bool Activity::waitingOnSemaphore protected
Definition at line 396 of file Activity.hpp.
Referenced by isNestable(), isWaiting(), waitForDispatch(), waitForGuardPermission(), waitForKernel(), and waitForRunPermission().
The documentation for this class was generated from the following files:
Activity.hpp
Activity-trace.cpp
Activity.cpp
ThreadContextStubs.cpp
CallContextStubs.cpp
MethodContextStubs.cpp