ooRexx: LanguageParser Class Reference
LanguageParser Class Reference
#include <LanguageParser.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
LanguageParser (RexxString *name, ProgramSource *s)
LanguageParser (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void translate ()
void compileSource ()
void initializeForParsing ()
void initializeForDirectives ()
void initializeForTranslation ()
void resolveDependencies ()
void flushControl (RexxInstruction *)
RexxCode * translateBlock ()
RexxCode * translateInterpret (PackageClass *sourceContext, StringTable *contextLabels)
RexxInternalObject * translateConstantExpression (RexxToken *token, RexxErrorCodes error)
RoutineClass * generateProgram (PackageClass *sourceContext=OREF_NULL)
RoutineClass * generateRoutine (PackageClass *sourceContext=OREF_NULL)
MethodClass * generateMethod (PackageClass *sourceContext=OREF_NULL)
PackageClass * generatePackage (PackageClass *sourceContext=OREF_NULL)
PackageClass * getPackage ()
void installPackage ()
StackFrameClass * createStackFrame ()
void holdObject (RexxInternalObject *object)
void scanComment ()
RexxToken * scanSymbol ()
RexxToken * scanLiteral ()
void nextLine ()
void conditionalNextLine ()
bool checkMarker (RexxString *marker)
RexxString * getStringLine ()
void position (size_t, size_t)
bool nextClause ()
RexxToken * sourceNextToken (RexxToken *)
bool nextSpecial (unsigned int, SourceLocation &)
CharacterClass locateToken (unsigned int &, bool)
RexxString * packHexLiteral (size_t, size_t)
RexxString * packBinaryLiteral (size_t, size_t)
RexxToken * getToken (int term, RexxErrorCodes error=Error_None)
unsigned int getChar ()
unsigned int getChar (size_t o)
unsigned int nextChar ()
unsigned int getNextChar ()
unsigned int followingChar ()
void stepPosition ()
void stepPosition (size_t o)
bool moreChars ()
bool haveNextChar ()
bool moreLines ()
void truncateLine ()
void needVariable (RexxToken *)
void needVariableOrDotSymbol (RexxToken *)
const SourceLocation & getLocation ()
void startLocation (SourceLocation &)
void endLocation (SourceLocation &)
void setLocation (SourceLocation &)
void previousToken ()
void firstToken ()
void trimClause ()
size_t markPosition ()
void resetPosition (size_t p)
RexxVariableBase * addSimpleVariable (RexxString *)
RexxStemVariable * addStem (RexxString *)
RexxCompoundVariable * addCompound (RexxString *)
void expose (RexxString *)
void localVariable (RexxString *)
void autoExpose ()
RexxString * commonString (RexxString *)
RexxInternalObject * addText (RexxToken *)
RexxVariableBase * addVariable (RexxToken *)
RexxVariableBase * requiredVariable (RexxToken *, const char *)
void addClause (RexxInstruction *)
void resolveCalls ()
void addLabel (RexxInstruction *, RexxString *)
RexxInstruction * findLabel (RexxString *)
void setGuard ()
ArrayClass * getGuard ()
void addBlock ()
RexxVariableBase * getRetriever (RexxString *)
ArrayClass * words (RexxString *)
void reclaimClause ()
bool atEnd ()
void setInterpret ()
bool isInterpret ()
bool noClauseAvailable ()
bool clauseAvailable ()
RexxToken * nextToken ()
RexxToken * nextReal ()
void requiredEndOfClause (RexxErrorCodes error)
RexxInternalObject * requiredLogicalExpression (int terminators, RexxErrorCodes error)
RexxInternalObject * requiredExpression (int terminators, RexxErrorCodes error)
bool capturingGuardVariables ()
bool isExposed (RexxString *varName)
void captureGuardVariable (RexxString *varname, RexxVariableBase *retriever)
void requireLanguageLevel (LanguageLevel l)
RexxInstruction * nextInstruction ()
size_t processVariableList (InstructionKeyword)
RexxInstruction * addressNew ()
RexxInstruction * assignmentNew (RexxToken *)
RexxInstruction * assignmentOpNew (RexxToken *, RexxToken *)
RexxInstruction * callOnNew (InstructionSubKeyword type)
RexxInstruction * dynamicCallNew (RexxToken *token)
RexxInstruction * qualifiedCallNew (RexxToken *token)
RexxInstruction * callNew ()
RexxInstruction * commandNew ()
RexxInstruction * doNew ()
RexxInstruction * newControlledLoop (RexxString *label, RexxVariableBase *countVariable, RexxToken *nameToken)
RexxInstruction * newDoOverLoop (RexxString *label, RexxVariableBase *countVariable, RexxToken *nameToken)
RexxInstruction * newDoWithLoop (RexxString *label, RexxVariableBase *countVariable, RexxToken *nameToken)
RexxInstruction * newSimpleDo (RexxString *label)
RexxInstruction * newLoopForever (RexxString *label, RexxVariableBase *countVariable)
RexxInstruction * newLoopWhile (RexxString *label, RexxVariableBase *countVariable, WhileUntilLoop &conditional)
RexxInstruction * newLoopUntil (RexxString *label, RexxVariableBase *countVariable, WhileUntilLoop &conditional)
RexxInstruction * parseForeverLoop (RexxString *label, RexxVariableBase *countVariable)
RexxInstruction * parseCountLoop (RexxString *label, RexxVariableBase *countVariable)
RexxInstruction * createLoop (bool isLoop)
RexxInstruction * dropNew ()
RexxInstruction * elseNew (RexxToken *)
RexxInstruction * endNew ()
RexxInstruction * endIfNew (RexxInstructionIf *)
RexxInstruction * exitNew ()
RexxInstruction * exposeNew ()
RexxInstruction * forwardNew ()
RexxInstruction * guardNew ()
RexxInstruction * ifNew ()
RexxInstruction * whenNew ()
RexxInstruction * interpretNew ()
RexxInstruction * labelNew (RexxToken *name, RexxToken *colon)
RexxInstruction * leaveNew (InstructionKeyword type)
RexxInstruction * messageNew (RexxExpressionMessage *)
RexxInstruction * doubleMessageNew (RexxExpressionMessage *msg)
RexxInstruction * messageAssignmentNew (RexxExpressionMessage *, RexxInternalObject *)
RexxInstruction * messageAssignmentOpNew (RexxExpressionMessage *, RexxToken *, RexxInternalObject *)
RexxInstruction * nopNew ()
RexxInstruction * numericNew ()
RexxInstruction * optionsNew ()
RexxInstruction * otherwiseNew (RexxToken *)
RexxInstruction * parseNew (InstructionSubKeyword)
RexxInstruction * procedureNew ()
RexxInstruction * pushNew ()
RexxInstruction * queueNew ()
RexxInstruction * raiseNew ()
RexxInstruction * replyNew ()
RexxInstruction * returnNew ()
RexxInstruction * sayNew ()
RexxInstruction * selectNew ()
RexxInstruction * dynamicSignalNew ()
RexxInstruction * signalOnNew (InstructionSubKeyword type)
RexxInstruction * signalNew ()
RexxInstruction * thenNew (RexxToken *, RexxInstructionIf *)
RexxInstruction * traceNew ()
RexxInstruction * useNew ()
RexxInstruction * useLocalNew ()
void addReference (RexxInternalObject *reference)
void pushDo (RexxInstruction *i)
RexxInstruction * popDo ()
RexxInstruction * topDo ()
RexxInstruction * topBlockInstruction ()
InstructionKeyword topDoType ()
bool topDoIsType (InstructionKeyword t)
bool topDoIsType (InstructionKeyword t1, InstructionKeyword t2)
RexxInstruction * sourceNewObject (size_t size, RexxBehaviour *_behaviour, InstructionKeyword type)
RexxInstruction * sourceNewObject (size_t size, size_t count, size_t itemSize, RexxBehaviour *_behaviour, InstructionKeyword type)
void nextDirective ()
void routineDirective ()
void requiresDirective ()
void libraryDirective (RexxString *name, RexxToken *token)
void methodDirective ()
void classDirective ()
void attributeDirective ()
void constantDirective ()
void annotateDirective ()
void optionsDirective ()
void resourceDirective ()
void addInstalledClass (RexxString *name, RexxClass *classObject, bool publicClass)
void addInstalledRoutine (RexxString *name, RoutineClass *routineObject, bool publicRoutine)
void processAnnotation (RexxToken *token, StringTable *table)
void processAttributeAnnotations (RexxString *getterName)
ClassResolver * parseClassReference (RexxErrorCodes error)
void checkDirective (RexxErrorCodes errorCode)
bool hasBody ()
void decodeExternalMethod (RexxString *methodName, RexxString *externalSpec, RexxString *&library, RexxString *&procedure)
MethodClass * createNativeMethod (RexxString *name, RexxString *library, RexxString *procedure)
void createMethod (RexxString *name, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod, bool isAttribute)
void createAttributeGetterMethod (RexxString *name, RexxVariableBase *retriever, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod)
void createAttributeSetterMethod (RexxString *name, RexxVariableBase *retriever, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod)
void createDelegateMethod (RexxString *name, RexxVariableBase *retriever, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod, bool isAttribute)
void createConstantGetterMethod (RexxString *name, RexxObject *value, RexxInternalObject *expression, SourceLocation &location)
void createAbstractMethod (RexxString *name, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod, bool isAttribute)
void checkDuplicateMethod (RexxString *name, bool classMethod, RexxErrorCodes errorMsg)
void addMethod (RexxString *name, MethodClass *method, bool classMethod)
bool isDuplicateClass (RexxString *name)
bool isDuplicateRoutine (RexxString *name)
void addClassDirective (RexxString *name, ClassDirective *directive)
ClassDirective * findClassDirective (RexxString *name)
RoutineClass * findRoutine (RexxString *name)
MethodClass * findMethod (RexxString *name)
MethodClass * findClassMethod (RexxString *name)
MethodClass * findInstanceMethod (RexxString *name)
RexxInternalObject * parseConstantExpression ()
RexxInternalObject * parenExpression (RexxToken *)
RexxInternalObject * parseExpression (int)
RexxInternalObject * parseSubExpression (int)
RexxInternalObject * parseFullSubExpression (int)
size_t parseArgList (RexxToken *, int)
ArrayClass * parseArgArray (RexxToken *, int)
size_t parseCaseWhenList (int terminators)
RexxInternalObject * parseFunction (RexxToken *, RexxToken *)
RexxInternalObject * parseQualifiedSymbol (RexxString *namespaceName)
RexxInternalObject * parseCollectionMessage (RexxToken *, RexxInternalObject *)
RexxInternalObject * parseMessage (RexxInternalObject *, bool, int)
RexxInternalObject * parseMessageTerm ()
RexxInternalObject * parseVariableOrMessageTerm ()
RexxInternalObject * parseMessageSubterm (int)
RexxInternalObject * parseSubTerm (int)
RexxInternalObject * parseLoopConditional (InstructionSubKeyword &, RexxErrorCodes)
RexxInternalObject * parseLogical (int terminators)
void pushOperator (RexxToken *operatorToken)
RexxToken * popOperator ()
RexxToken * topOperator ()
void pushTerm (RexxInternalObject *)
void pushSubTerm (RexxInternalObject *)
RexxInternalObject * requiredTerm (RexxToken *token, RexxErrorCodes errorCode=Error_Invalid_expression_general)
RexxInternalObject * popTerm ()
RexxInternalObject * popSubTerm ()
RexxInternalObject * popNTerms (size_t)
CommandIOConfiguration * parseAddressWith ()
bool checkRedirectNormal (RexxToken *token)
OutputOption::Enum parseRedirectOutputOptions ()
void parseRedirectOptions (RexxInternalObject *&source, RedirectionType::Enum &type)
RexxInternalObject * parseVariableReferenceTerm ()
void error (RexxErrorCodes)
void error (RexxErrorCodes, RexxObject *)
void error (RexxErrorCodes, RexxObject *, RexxObject *)
void error (RexxErrorCodes, RexxObject *, RexxObject *, RexxObject *)
void error (RexxErrorCodes errorcode, const SourceLocation &location, ArrayClass *subs)
void errorLine (RexxErrorCodes, RexxInstruction *)
void errorPosition (RexxErrorCodes, RexxToken *)
void errorToken (RexxErrorCodes, RexxToken *)
void blockError (RexxInstruction *)
void syntaxError (RexxErrorCodes errorcode, RexxInstruction *i)
void blockSyntaxError (RexxInstruction *i)
void syntaxErrorAt (RexxErrorCodes errorcode, RexxToken *token)
void syntaxError (RexxErrorCodes errorcode, RexxObject *a1)
void syntaxError (RexxErrorCodes errorcode, RexxObject *a1, RexxObject *a2)
void syntaxError (RexxErrorCodes errorcode, const char *a1, RexxObject *a2)
void syntaxError (RexxErrorCodes errorcode, RexxObject *a1, RexxObject *a2, RexxObject *a3)
void syntaxError (RexxErrorCodes errorcode, RexxToken *token)
void syntaxError (RexxErrorCodes errorcode)
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static bool canExecute (LanguageLevel l)
static StringSymbolType scanSymbol (RexxString *string)
static bool isSymbolCharacter (unsigned int ch)
static int translateChar (unsigned int ch)
static MethodClass * createMethod (RexxString *name, ArrayClass *source, PackageClass *sourceContext)
static MethodClass * createMethod (RexxString *name, BufferClass *source)
static MethodClass * createMethod (RexxString *name, PackageClass *sourceContext)
static RoutineClass * createRoutine (RexxString *name, ArrayClass *source, PackageClass *sourceContext)
static RoutineClass * createRoutine (RexxString *name, BufferClass *source, PackageClass *sourceContext)
static RoutineClass * createRoutine (RexxString *name, PackageClass *sourceContext)
static RoutineClass * createProgram (RexxString *name, BufferClass *source)
static RoutineClass * createProgram (RexxString *name, ArrayClass *source, PackageClass *sourceContext)
static RoutineClass * createProgram (RexxString *name)
static RoutineClass * restoreFromMacroSpace (RexxString *name)
static RoutineClass * processInstore (PRXSTRING instore, RexxString *name)
static RexxCode * translateInterpret (RexxString *interpretString, PackageClass *sourceContext, StringTable *labels, size_t lineNumber)
static RoutineClass * createProgramFromFile (RexxString *filename)
static PackageClass * createPackage (RexxString *filename)
static PackageClass * createPackage (RexxString *name, ArrayClass *source, PackageClass *sourceContext=OREF_NULL)
static PackageClass * createPackage (RexxString *name, BufferClass *source)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static pbuiltin builtinTable []
static const unsigned int INVALID_CHARACTER = 0x100
static const size_t MAX_SYMBOL_LENGTH = 250
Protected Attributes
RexxString * name
ProgramSource * source
PackageClass * package
FlagSet< ParsingFlags, 32 > flags
const char * current
size_t currentLength
size_t lineCount
RexxClause * clause
SourceLocation clauseLocation
size_t lineNumber
size_t lineOffset
RexxCode * mainSection
PushThroughStack * holdStack
StringTable * literals
StringTable * dotVariables
StringTable * strings
QueueClass * control
QueueClass * terms
QueueClass * subTerms
QueueClass * operators
ClassDirective * activeClass
StringTable * classDependencies
StringTable * unattachedMethods
StringTable * routines
StringTable * publicRoutines
StringTable * resources
ArrayClass * requires
ArrayClass * libraries
ArrayClass * classes
RexxInstruction * firstInstruction
RexxInstruction * lastInstruction
RexxInstruction * currentInstruction
StringTable * variables
StringTable * labels
IdentityTable * guardVariables
StringTable * exposedVariables
StringTable * localVariables
ArrayClass * calls
size_t currentStack
size_t maxStack
size_t variableIndex
size_t constantMaxStack
size_t constantVariableIndex
StringTable * constantVariables
Static Protected Attributes
static const size_t HOLDSIZE = 30
static int characterTable []
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Main class for parsing Rexx source into an executable entity.
Definition at line 102 of file LanguageParser.hpp.
Constructor & Destructor Documentation
LanguageParser() [1/2]
LanguageParser::LanguageParser (RexxString * n, ProgramSource * s)
Construct a program source object.
Parameters
p The source package we're parsing code for.
s The provider for the actual program source.
Definition at line 476 of file LanguageParser.cpp.
References name, and source.
Referenced by createMethod(), createProgram(), createRoutine(), and translateInterpret().
LanguageParser() [2/2]
LanguageParser::LanguageParser (RESTORETYPE restoreType) inline
Definition at line 109 of file LanguageParser.hpp.
Member Function Documentation
addBlock()
void LanguageParser::addBlock ()
addClassDirective()
void LanguageParser::addClassDirective (RexxString * name, ClassDirective * directive)
Add a class directive to the definition set.
Parameters
name The new class directive.
directive
Definition at line 270 of file DirectiveParser.cpp.
References ArrayClass::append(), classDependencies, classes, name, and HashCollection::put().
Referenced by classDirective().
addClause()
void LanguageParser::addClause (RexxInstruction * instruction)
Add a new instruction to the code execution chain. Instructions are a linear chain of instruction objects, with all branching handled by additional links within instructions.
Parameters
instruction The new instruction to add.
Definition at line 2540 of file LanguageParser.cpp.
References lastInstruction, and RexxInstruction::setNext().
Referenced by flushControl(), and translateBlock().
addCompound()
RexxCompoundVariable * LanguageParser::addCompound (RexxString * name)
Add a compound variable reference to our variable tables. This is a two part operation...first we make sure the stem variable is added, which uses a specific slot. Then we use that information to create a retriever for the specific compound variable.
Parameters
name The name of the compound variable.
Returns
A retriever for this variable.
Definition at line 2123 of file LanguageParser.cpp.
References addSimpleVariable(), addStem(), commonString(), HashCollection::get(), RexxStemVariable::getIndex(), RexxString::getLength(), RexxString::getStringData(), name, new_string(), OREF_NULL, QueueClass::push(), HashCollection::put(), subTerms, and variables.
Referenced by addText().
addInstalledClass()
void LanguageParser::addInstalledClass (RexxString * name, RexxClass * classObject, bool publicClass)
addInstalledRoutine()
void LanguageParser::addInstalledRoutine (RexxString * name, RoutineClass * routineObject, bool publicRoutine)
addLabel()
void LanguageParser::addLabel (RexxInstruction * label, RexxString * labelname)
Add a label to our global table. Note, in Rexx it is not an error to have duplicate labels, but only the first can be used as a target. We do not overwrite a given name if it is already in the table.
Parameters
label The label instruction to add.
labelname The label name.
Definition at line 2558 of file LanguageParser.cpp.
References HashCollection::hasIndex(), labels, and HashCollection::put().
Referenced by labelNew().
addMethod()
void LanguageParser::addMethod (RexxString * name, MethodClass * method, bool classMethod)
Add a new method to this compilation.
Parameters
name The directory name of the method.
method The method object.
classMethod The class/instance method indicator.
Definition at line 610 of file DirectiveParser.cpp.
References activeClass, ClassDirective::addMethod(), name, OREF_NULL, package, StringHashCollection::setEntry(), BaseExecutable::setPackageObject(), and unattachedMethods.
Referenced by attributeDirective(), createAbstractMethod(), createAttributeGetterMethod(), createAttributeSetterMethod(), createConstantGetterMethod(), createDelegateMethod(), createMethod(), and methodDirective().
addReference()
void LanguageParser::addReference (RexxInternalObject * reference) inline
Definition at line 305 of file LanguageParser.hpp.
References ArrayClass::addLast(), and calls.
Referenced by callNew(), callOnNew(), parseFunction(), signalNew(), and signalOnNew().
addressNew()
RexxInstruction * LanguageParser::addressNew ()
Parse an ADDRESS instruction and create an executable instruction object.
Returns
An instruction object that can perform this function.
Definition at line 563 of file InstructionParser.cpp.
References Error_Invalid_expression_address, RexxToken::isEndOfClause(), RexxToken::isSymbolOrLiteral(), new_instruction, nextReal(), nextToken(), OREF_NULL, parseAddressWith(), parseExpression(), previousToken(), requiredExpression(), SUBKEY_VALUE, SUBKEY_WITH, RexxToken::subKeyword(), TERM_EOC, TERM_KEYWORD, TERM_WITH, and RexxToken::value().
Referenced by nextInstruction().
addSimpleVariable()
RexxVariableBase * LanguageParser::addSimpleVariable (RexxString * varname)
Resolve a variable name to a single common retriever object per code block.
Parameters
varname The name of the target variable.
Returns
A retrieve object for accessing the variable. This will identify a variable slot in the code stack frame.
Definition at line 2038 of file LanguageParser.cpp.
References captureGuardVariable(), HashCollection::get(), isInterpret(), OREF_NULL, HashCollection::put(), variableIndex, and variables.
Referenced by addCompound(), addText(), and parseVariableReferenceTerm().
addStem()
RexxStemVariable * LanguageParser::addStem (RexxString * stemName)
Add a stem variable instance to the execution instance. This is like the addVariable, but the retriever in question is for a Stem variable.
Parameters
stemName The name of the stem (including the period).
Returns
A retriever for the specified variable.
Definition at line 2083 of file LanguageParser.cpp.
References captureGuardVariable(), HashCollection::get(), isInterpret(), OREF_NULL, HashCollection::put(), variableIndex, and variables.
Referenced by addCompound(), addText(), and parseVariableReferenceTerm().
addText()
RexxInternalObject * LanguageParser::addText (RexxToken * token)
Definition at line 2329 of file LanguageParser.cpp.
References addCompound(), addSimpleVariable(), addStem(), commonString(), dotVariables, Error_Interpretation_switch, RexxString::extract(), HashCollection::get(), RexxString::getLength(), RexxToken::isIntegerConstant(), literals, name, RexxInternalObject::numberString(), OREF_NULL, HashCollection::put(), reportException(), RexxInternalObject::requestInteger(), Numerics::REXXINTEGER_DIGITS, RexxString::setNumberString(), RexxToken::subtype(), SYMBOL_COMPOUND, SYMBOL_CONSTANT, SYMBOL_DOTSYMBOL, SYMBOL_DUMMY, SYMBOL_STEM, SYMBOL_VARIABLE, TheNilObject, TOKEN_LITERAL, TOKEN_SYMBOL, RexxToken::type(), and RexxToken::value().
Referenced by addVariable(), parseConstantExpression(), parseMessage(), parseNew(), parseRedirectOptions(), parseSubTerm(), parseVariableOrMessageTerm(), processVariableList(), and useNew().
addVariable()
RexxVariableBase * LanguageParser::addVariable (RexxToken * token)
Handle adding a variable to a program. This verifies that the token is a valid variable, then creates a retriever that can be used in an expression to obtain the variable value.
Parameters
token The token holding the variable name.
Returns
A retriever object that can be used as an expression term.
Definition at line 2290 of file LanguageParser.cpp.
References addText(), and needVariable().
Referenced by assignmentNew(), assignmentOpNew(), createLoop(), newControlledLoop(), newDoOverLoop(), parseNew(), processVariableList(), requiredVariable(), and useLocalNew().
annotateDirective()
void LanguageParser::annotateDirective ()
Process an ::ANNOTATE directive in a source file.
Definition at line 1891 of file DirectiveParser.cpp.
References commonString(), CONSTANT, Error_Invalid_subkeyword_annotation, Error_Symbol_expected_annotation_type, Error_Symbol_or_string_directive_option, Error_Translation_missing_annotation_target, findClassDirective(), findMethod(), findRoutine(), PackageClass::getAnnotations(), BaseExecutable::getAnnotations(), ClassDirective::getAnnotations(), MethodClass::isConstant(), RexxToken::isEndOfClause(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), name, nextReal(), OREF_NULL, package, processAnnotation(), processAttributeAnnotations(), RexxToken::subDirective(), SUBDIRECTIVE_ATTRIBUTE, SUBDIRECTIVE_CLASS, SUBDIRECTIVE_CONSTANT, SUBDIRECTIVE_METHOD, SUBDIRECTIVE_PACKAGE, SUBDIRECTIVE_ROUTINE, syntaxError(), and RexxToken::upperValue().
Referenced by nextDirective().
assignmentNew()
RexxInstruction * LanguageParser::assignmentNew (RexxToken * target)
Create a new variable assignment instruction.
Parameters
target This is the token holding the name of the variable name for the assignment.
Returns
An assignment instruction object.
Definition at line 909 of file InstructionParser.cpp.
References addVariable(), Error_Invalid_expression_assign, needVariable(), new_instruction, requiredExpression(), and TERM_EOC.
Referenced by nextInstruction().
assignmentOpNew()
RexxInstruction * LanguageParser::assignmentOpNew (RexxToken * target, RexxToken * operation)
Create a special assignment op of the form "variable (op)= expr".
Parameters
target The assignment target variable.
operation The operator token. classId is TOKEN_ASSIGNMENT, the subclass is the type of the operation to perform.
Returns
The constructed instruction object.
Definition at line 934 of file InstructionParser.cpp.
References addVariable(), Error_Invalid_expression_assign, needVariable(), new_instruction, requiredExpression(), RexxToken::subtype(), and TERM_EOC.
Referenced by nextInstruction().
atEnd()
bool LanguageParser::atEnd () inline
Definition at line 197 of file LanguageParser.hpp.
References flags, moreLines(), and reclaimed.
Referenced by translate().
attributeDirective()
void LanguageParser::attributeDirective ()
Process a ::ATTRIBUTE directive in a source file.
Definition at line 1408 of file DirectiveParser.cpp.
References addMethod(), ATTRIBUTE_BOTH, ATTRIBUTE_GET, ATTRIBUTE_SET, checkDirective(), checkDuplicateMethod(), commonString(), RexxString::concatWithCstring(), createAbstractMethod(), createAttributeGetterMethod(), createAttributeSetterMethod(), createDelegateMethod(), createMethod(), createNativeMethod(), decodeExternalMethod(), DEFAULT_ACCESS_SCOPE, DEFAULT_GUARD, DEFAULT_PROTECTION, Error_Invalid_subkeyword_attribute, Error_Symbol_expected_delegate, Error_Symbol_or_string_attribute, Error_Symbol_or_string_external, Error_Translation_abstract_attribute, Error_Translation_body_error, Error_Translation_delegate_attribute, Error_Translation_duplicate_attribute, Error_Translation_external_attribute, getRetriever(), GUARDED_METHOD, hasBody(), RexxToken::isEndOfClause(), RexxToken::isLiteral(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), name, nextReal(), OREF_NULL, PACKAGE_SCOPE, PRIVATE_SCOPE, PROTECTED_METHOD, PUBLIC_SCOPE, RexxToken::subDirective(), SUBDIRECTIVE_ABSTRACT, SUBDIRECTIVE_CLASS, SUBDIRECTIVE_DELEGATE, SUBDIRECTIVE_EXTERNAL, SUBDIRECTIVE_GET, SUBDIRECTIVE_GUARDED, SUBDIRECTIVE_PACKAGE, SUBDIRECTIVE_PRIVATE, SUBDIRECTIVE_PROTECTED, SUBDIRECTIVE_PUBLIC, SUBDIRECTIVE_SET, SUBDIRECTIVE_UNGUARDED, SUBDIRECTIVE_UNPROTECTED, syntaxError(), UNGUARDED_METHOD, UNPROTECTED_METHOD, RexxString::upper(), and RexxToken::value().
Referenced by nextDirective().
autoExpose()
void LanguageParser::autoExpose ()
We have a USE LOCAL specified, so turn on the auto expose.
Definition at line 2228 of file LanguageParser.cpp.
References localVariables, new_string_table(), and HashCollection::put().
Referenced by useLocalNew().
blockError()
void LanguageParser::blockError (RexxInstruction * instruction)
Raise an error for an unclosed block instruction.
Parameters
instruction The unclosed instruction.
Definition at line 4176 of file LanguageParser.cpp.
References clauseLocation, Error_Incomplete_do_do, Error_Incomplete_do_else, Error_Incomplete_do_loop, Error_Incomplete_do_otherwise, Error_Incomplete_do_select, Error_Incomplete_do_then, Error_Interpretation_switch, RexxInstruction::getLocation(), RexxInstruction::getType(), KEYWORD_DO, KEYWORD_ELSE, KEYWORD_IF, KEYWORD_IFTHEN, KEYWORD_LOOP, KEYWORD_LOOP_CONTROLLED, KEYWORD_LOOP_CONTROLLED_UNTIL, KEYWORD_LOOP_CONTROLLED_WHILE, KEYWORD_LOOP_COUNT, KEYWORD_LOOP_COUNT_UNTIL, KEYWORD_LOOP_COUNT_WHILE, KEYWORD_LOOP_FOREVER, KEYWORD_LOOP_OVER, KEYWORD_LOOP_OVER_FOR, KEYWORD_LOOP_OVER_FOR_UNTIL, KEYWORD_LOOP_OVER_FOR_WHILE, KEYWORD_LOOP_OVER_UNTIL, KEYWORD_LOOP_OVER_WHILE, KEYWORD_LOOP_UNTIL, KEYWORD_LOOP_WHILE, KEYWORD_LOOP_WITH, KEYWORD_LOOP_WITH_FOR, KEYWORD_LOOP_WITH_FOR_UNTIL, KEYWORD_LOOP_WITH_FOR_WHILE, KEYWORD_LOOP_WITH_UNTIL, KEYWORD_LOOP_WITH_WHILE, KEYWORD_OTHERWISE, KEYWORD_SELECT, KEYWORD_SELECT_CASE, KEYWORD_SIMPLE_BLOCK, KEYWORD_WHEN, KEYWORD_WHEN_CASE, KEYWORD_WHENTHEN, lastInstruction, reportException(), and syntaxError().
Referenced by blockSyntaxError().
blockSyntaxError()
void LanguageParser::blockSyntaxError (RexxInstruction * i) inline
Definition at line 402 of file LanguageParser.hpp.
References blockError().
Referenced by translateBlock().
callNew()
RexxInstruction * LanguageParser::callNew ()
Finish parsing of a CALL instruction. There are 3 distinct forms of the Call instruction, with a different execution object for each form.
Returns
An executable call instruction object.
Definition at line 1147 of file InstructionParser.cpp.
References addReference(), RexxToken::builtin(), callOnNew(), dynamicCallNew(), Error_Symbol_or_string_call, RexxToken::isEndOfClause(), RexxToken::isLeftParen(), RexxToken::isLiteral(), RexxToken::isSymbol(), RexxToken::isType(), new_variable_instruction, nextReal(), nextToken(), OREF_NULL, parseArgList(), previousToken(), qualifiedCallNew(), SUBKEY_OFF, SUBKEY_ON, RexxToken::subKeyword(), subTerms, syntaxError(), TERM_EOC, TOKEN_COLON, and RexxToken::value().
Referenced by nextInstruction().
callOnNew()
RexxInstruction * LanguageParser::callOnNew (InstructionSubKeyword type)
Parse a CALL ON or CALL OFF instruction.
Parameters
type The target instruction type (CALL_ON or CALL_OFF).
Returns
An executable instruction object for te target instruction.
Definition at line 961 of file InstructionParser.cpp.
References addReference(), commonString(), RexxString::concatToCstring(), RexxToken::condition(), CONDITION_LOSTDIGITS, CONDITION_NOMETHOD, CONDITION_NONE, CONDITION_NOSTRING, CONDITION_NOVALUE, CONDITION_PROPAGATE, CONDITION_SYNTAX, CONDITION_USER, Error_Invalid_data_condition, Error_Invalid_data_name, Error_Invalid_subkeyword_calloff, Error_Invalid_subkeyword_callon, Error_Invalid_subkeyword_callonname, Error_Symbol_expected_off, Error_Symbol_expected_on, Error_Symbol_expected_user, Error_Symbol_or_string_name, RexxToken::isEndOfClause(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), new_instruction, nextReal(), NO_BUILTIN, OREF_NULL, requiredEndOfClause(), RexxToken::resolveBuiltin(), SUBKEY_NAME, SUBKEY_ON, RexxToken::subKeyword(), syntaxError(), type, and RexxToken::value().
Referenced by callNew().
canExecute()
bool LanguageParser::canExecute (LanguageLevel l) static
Test if this version of the interpreter can handle executing a program created with a given language level.
Parameters
l The target language level.
Returns
True if the given level is within the range supported by this interpreter version.
Definition at line 823 of file LanguageParser.cpp.
References MaximumLanguageLevel, and MinimumLanguageLevel.
Referenced by ProgramMetaData::validate().
captureGuardVariable()
void LanguageParser::captureGuardVariable (RexxString * varname, RexxVariableBase * retriever)
Perform a variable capture operation if we're evaluating a GUARD WHEN expression.
Parameters
varname The name of the variable
retriever The associated variable retriever.
Definition at line 2011 of file LanguageParser.cpp.
References capturingGuardVariables(), guardVariables, isExposed(), and HashCollection::put().
Referenced by addSimpleVariable(), and addStem().
capturingGuardVariables()
bool LanguageParser::capturingGuardVariables () inline
Definition at line 238 of file LanguageParser.hpp.
References guardVariables, and OREF_NULL.
Referenced by captureGuardVariable().
checkDirective()
void LanguageParser::checkDirective (RexxErrorCodes errorCode)
Verify that no code follows a directive except for more directive instructions.
Parameters
errorCode The error code to issue if this condition was violated.
Definition at line 154 of file DirectiveParser.cpp.
References clauseAvailable(), clauseLocation, firstToken(), RexxToken::isType(), nextClause(), nextReal(), reclaimClause(), syntaxError(), and TOKEN_DCOLON.
Referenced by attributeDirective(), constantDirective(), methodDirective(), and routineDirective().
checkDuplicateMethod()
void LanguageParser::checkDuplicateMethod (RexxString * name, bool classMethod, RexxErrorCodes errorMsg)
check for a duplicate method.
Parameters
name The name to check.
classMethod Indicates whether this is a check for a CLASS or INSTANCE method.
errorMsg The error code to use if there is a duplicate.
Definition at line 507 of file DirectiveParser.cpp.
References activeClass, ClassDirective::checkDuplicateMethod(), StringHashCollection::entry(), Error_Translation_missing_class, name, OREF_NULL, syntaxError(), and unattachedMethods.
Referenced by attributeDirective(), constantDirective(), and methodDirective().
checkMarker()
bool LanguageParser::checkMarker (RexxString * marker)
Check the current line against the end marker to see if this is a match.
Parameters
marker The marker string to check.
Returns
true if this line begins with the marker, false otherwise.
Definition at line 955 of file LanguageParser.cpp.
References current, currentLength, RexxString::getLength(), and RexxString::getStringData().
Referenced by resourceDirective().
checkRedirectNormal()
bool LanguageParser::checkRedirectNormal (RexxToken * token)
Check if this source or target is specified as NORMAL, which resets to default.
Returns
true if the next keyword is NORMAL, false for anything else.
Definition at line 782 of file InstructionParser.cpp.
References RexxToken::isSymbol(), SUBKEY_NORMAL, and RexxToken::subKeyword().
Referenced by parseAddressWith().
classDirective()
void LanguageParser::classDirective ()
Process a ::CLASS directive for a source file.
Definition at line 334 of file DirectiveParser.cpp.
References activeClass, addClassDirective(), ClassDirective::addInherits(), clause, commonString(), constantMaxStack, constantVariableIndex, constantVariables, DEFAULT_ACCESS_SCOPE, Error_Invalid_subkeyword_class, Error_Symbol_or_string_class, Error_Symbol_or_string_inherit, Error_Symbol_or_string_metaclass, Error_Symbol_or_string_mixinclass, Error_Symbol_or_string_subclass, Error_Translation_duplicate_class, RexxLocalVariables::FIRST_VARIABLE_INDEX, ClassDirective::getMetaClass(), ClassDirective::getSubClass(), ClassDirective::isAbstract(), isDuplicateClass(), RexxToken::isEndOfClause(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), name, nextReal(), OREF_NULL, parseClassReference(), previousToken(), PRIVATE_SCOPE, PUBLIC_SCOPE, ClassDirective::setAbstract(), ClassDirective::setMetaClass(), ClassDirective::setMixinClass(), ClassDirective::setPublic(), ClassDirective::setSubClass(), RexxToken::subDirective(), SUBDIRECTIVE_ABSTRACT, SUBDIRECTIVE_INHERIT, SUBDIRECTIVE_METACLASS, SUBDIRECTIVE_MIXINCLASS, SUBDIRECTIVE_PRIVATE, SUBDIRECTIVE_PUBLIC, SUBDIRECTIVE_SUBCLASS, syntaxError(), type, RexxString::upper(), and RexxToken::value().
Referenced by nextDirective().
clauseAvailable()
bool LanguageParser::clauseAvailable () inline
Definition at line 202 of file LanguageParser.hpp.
References flags, and noClause.
Referenced by checkDirective(), and hasBody().
commandNew()
RexxInstruction * LanguageParser::commandNew ()
Parse and create a COMMAND instruction.
Returns
A COMMAND instruction instance.
Definition at line 1241 of file InstructionParser.cpp.
References new_instruction, parseExpression(), and TERM_EOC.
Referenced by nextInstruction().
commonString()
RexxString * LanguageParser::commonString (RexxString * string)
Compress all string tokens needed by a group of programs into a single, common set of strings. It is fairly common for a program to have duplicate versions of strings in the form of variable names, etc. This ensures there is just a single version of these available.
Parameters
string The string to add to the set.
Returns
The commonized string. If this string is already in the common table, the previously added one will be returned.
Definition at line 2265 of file LanguageParser.cpp.
References HashCollection::get(), OREF_NULL, HashCollection::put(), and strings.
Referenced by addCompound(), addText(), annotateDirective(), attributeDirective(), callOnNew(), classDirective(), constantDirective(), methodDirective(), parseClassReference(), parseMessage(), processAttributeAnnotations(), raiseNew(), resourceDirective(), scanLiteral(), scanSymbol(), signalOnNew(), and words().
compileSource()
void LanguageParser::compileSource ()
Compile our configured source into executable code.
Definition at line 733 of file LanguageParser.cpp.
References initializeForParsing(), and translate().
Referenced by generateMethod(), generatePackage(), generateProgram(), generateRoutine(), and translateInterpret().
conditionalNextLine()
void LanguageParser::conditionalNextLine ()
Advance the current position to the next line, but only if we are not already positioned at the first character.
Definition at line 935 of file LanguageParser.cpp.
References lineOffset, and nextLine().
Referenced by resourceDirective().
constantDirective()
void LanguageParser::constantDirective ()
Process a CONSTANT directive in a source file.
Definition at line 1805 of file DirectiveParser.cpp.
References activeClass, checkDirective(), checkDuplicateMethod(), clause, commonString(), RexxString::concat(), createConstantGetterMethod(), Error_Invalid_data_constant_dir, Error_Invalid_expression_missing_constant, Error_Symbol_or_string_constant, Error_Symbol_or_string_constant_value, Error_Translation_constant_body, Error_Translation_duplicate_constant, RexxClause::getLocation(), RexxToken::isEndOfClause(), RexxToken::isLeftParen(), RexxToken::isOperator(), RexxToken::isSubtype(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), name, nextReal(), RexxInternalObject::numberString(), OPERATOR_PLUS, OPERATOR_SUBTRACT, OREF_NULL, previousToken(), requiredEndOfClause(), SYMBOL_CONSTANT, syntaxError(), translateConstantExpression(), RexxString::upper(), and RexxToken::value().
Referenced by nextDirective().
createAbstractMethod()
void LanguageParser::createAbstractMethod (RexxString * name, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod, bool isAttribute)
Create an abstract method.
Parameters
name The name of the method.
classMethod Indicates we're adding a class or instance method.
privateMethod The method's private attribute.
protectedMethod The method's protected attribute.
guardedMethod The method's guarded attribute.
isAttribute The method attribute status.
Definition at line 2444 of file DirectiveParser.cpp.
References addMethod(), and name.
Referenced by attributeDirective(), and methodDirective().
createAttributeGetterMethod()
void LanguageParser::createAttributeGetterMethod (RexxString * name, RexxVariableBase * retriever, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod)
Create an ATTRIBUTE "get" method.
Parameters
name The name of the attribute.
retriever
classMethod Indicates we're adding a class or instance method.
privateMethod The method's private attribute.
protectedMethod The method's protected attribute.
guardedMethod The method's guarded attribute.
Definition at line 2359 of file DirectiveParser.cpp.
References addMethod(), and name.
Referenced by attributeDirective(), and methodDirective().
createAttributeSetterMethod()
void LanguageParser::createAttributeSetterMethod (RexxString * name, RexxVariableBase * retriever, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod)
Create an ATTRIBUTE "set" method.
Parameters
name The name of the attribute.
classMethod Indicates we're adding a class or instance method.
privateMethod The method's private attribute.
protectedMethod The method's protected attribute.
guardedMethod The method's guarded attribute.
Definition at line 2415 of file DirectiveParser.cpp.
References addMethod(), and name.
Referenced by attributeDirective(), and methodDirective().
createConstantGetterMethod()
void LanguageParser::createConstantGetterMethod (RexxString * name, RexxObject * value, RexxInternalObject * expression, SourceLocation & location)
Create a CONSTANT "get" method.
Parameters
name The name of the attribute.
value A potential expression that needs to be evaluated at run time.
expression An expression to evaluate if this is the dynamic form.
location The clause location information.
Definition at line 2469 of file DirectiveParser.cpp.
References activeClass, ClassDirective::addConstantMethod(), addMethod(), clause, constantMaxStack, constantVariableIndex, Error_Translation_constant_no_class, name, OREF_NULL, package, and syntaxError().
Referenced by constantDirective().
createDelegateMethod()
void LanguageParser::createDelegateMethod (RexxString * name, RexxVariableBase * retriever, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod, bool isAttribute)
Create a DELEGATE method.
Parameters
name The name of the method.
retriever The retriever for the target variable.
classMethod Indicates we're adding a class or instance method.
privateMethod The method's private attribute.
protectedMethod The method's protected attribute.
guardedMethod The method's guarded attribute.
isAttribute Indicates whether this is an attribute method.
Definition at line 2389 of file DirectiveParser.cpp.
References addMethod(), and name.
Referenced by attributeDirective(), and methodDirective().
createLoop()
RexxInstruction * LanguageParser::createLoop (bool isLoop)
Create a new instruction object for a DO or LOOP instruction.
Parameters
newDo
isLoop indicates whether this is a DO or a LOOP instruction.
Returns
An appropriate instruction object for the type of block construct.
Definition at line 1994 of file InstructionParser.cpp.
References addVariable(), WhileUntilLoop::conditional, Error_Invalid_do_simple_do_counter, Error_Invalid_expression_general, Error_None, Error_Symbol_expected_counter, Error_Symbol_expected_LABEL, RexxToken::isEndOfClause(), RexxToken::isSubtype(), RexxString::isSymbol(), RexxToken::isSymbol(), markPosition(), name, newControlledLoop(), newDoOverLoop(), newDoWithLoop(), newLoopForever(), newLoopUntil(), newLoopWhile(), newSimpleDo(), nextReal(), OPERATOR_EQUAL, OPERATOR_STRICT_EQUAL, OREF_NULL, parseCountLoop(), parseForeverLoop(), parseLoopConditional(), previousToken(), resetPosition(), SUBKEY_COUNTER, SUBKEY_FOREVER, SUBKEY_INDEX, SUBKEY_ITEM, SUBKEY_LABEL, SUBKEY_NONE, SUBKEY_OVER, SUBKEY_UNTIL, SUBKEY_WHILE, SUBKEY_WITH, RexxToken::subKeyword(), and syntaxError().
Referenced by nextInstruction().
createMethod() [1/4]
MethodClass * LanguageParser::createMethod (RexxString * name, ArrayClass * source, PackageClass * sourceContext) static
Static method for creating a new MethodClass instance.
Parameters
name The name given to the method and package.
source The code source as an array of strings.
sourceContext A parent source context that this method will inherit a package environment from.
Returns
An executable method object.
Definition at line 98 of file LanguageParser.cpp.
References ENCODED_NEEDLE, LanguageParser(), name, new_buffer(), OREF_NULL, parser(), MethodClass::restore(), source, RexxString::strCompare(), and RexxInternalObject::stringValue().
createMethod() [2/4]
void LanguageParser::createMethod (RexxString * name, bool classMethod, AccessFlag privateMethod, ProtectedFlag protectedMethod, GuardFlag guardedMethod, bool isAttribute)
Create a Rexx method body.
Parameters
name The name of the attribute.
classMethod Indicates whether we are creating a class or instance method.
privateMethod The method's private attribute.
protectedMethod The method's protected attribute.
guardedMethod The method's guarded attribute.
isAttribute Indicates if this is an attribute method.
Definition at line 2324 of file DirectiveParser.cpp.
References addMethod(), name, and translateBlock().
Referenced by attributeDirective(), MethodClass::newFileRexx(), NewMethod(), MethodClass::newMethodObject(), and MethodClass::newRexx().
createMethod() [3/4]
MethodClass * LanguageParser::createMethod (RexxString * name, BufferClass * source) static
Static method for creating a new MethodClass instance.
Parameters
name The name given to the method and package.
source The code source as a buffer
sourceContext A parent source context that this method will inherit a package environment from.
Returns
An executable method object.
Definition at line 134 of file LanguageParser.cpp.
References LanguageParser(), name, parser(), and source.
createMethod() [4/4]
MethodClass * LanguageParser::createMethod (RexxString * name, PackageClass * sourceContext) static
Static method for creating a new MethodClass instance from a file.
Parameters
name The filename to read the method source from.
sourceContext A parent source context that this method will inherit a package environment from.
Returns
An executable method object.
Definition at line 155 of file LanguageParser.cpp.
References Error_Program_unreadable_name, RexxString::getStringData(), LanguageParser(), name, OREF_NULL, parser(), FileProgramSource::readProgram(), reportException(), and MethodClass::restore().
createNativeMethod()
MethodClass * LanguageParser::createNativeMethod (RexxString * name, RexxString * library, RexxString * procedure)
Create a native method from a specification.
Parameters
name The method name.
library The library containing the method.
procedure The name of the procedure within the package.
Returns
A method object representing this method.
Definition at line 1330 of file DirectiveParser.cpp.
References Error_External_name_not_found_method, name, OREF_NULL, package, PackageManager::resolveMethod(), and syntaxError().
Referenced by attributeDirective(), and methodDirective().
createPackage() [1/3]
PackageClass * LanguageParser::createPackage (RexxString * filename) static
Create a package object from an array source.
Parameters
filename The package name
Returns
A resulting Package object, if possible.
Definition at line 428 of file LanguageParser.cpp.
References createProgramFromFile(), and BaseExecutable::getPackage().
createPackage() [2/3]
PackageClass * LanguageParser::createPackage (RexxString * name, ArrayClass * source, PackageClass * sourceContext = OREF_NULL) static
Retrieve a package object from a file. This will first attempt to restore a previously translated image, then will try to translate the source if that fails.
Parameters
filename The target file name.
Returns
A resulting Routine object, if possible.
Definition at line 398 of file LanguageParser.cpp.
References createProgram(), BaseExecutable::getPackage(), name, and source.
createPackage() [3/3]
PackageClass * LanguageParser::createPackage (RexxString * name, BufferClass * source) static
Retrieve a package object from a file. This will first attempt to restore a previously translated image, then will try to translate the source if that fails.
Parameters
filename The target file name.
Returns
A resulting Routine object, if possible.
Definition at line 414 of file LanguageParser.cpp.
References createProgram(), BaseExecutable::getPackage(), name, and source.
createProgram() [1/3]
RoutineClass * LanguageParser::createProgram (RexxString * name) static
Static method for creating a new RoutineClass instance as a top-level program (no install step is run)
Parameters
name The name given to the routine and package.
source The buffer containing the source.
Returns
An executable method object.
Definition at line 348 of file LanguageParser.cpp.
References LanguageParser(), name, and parser().
createProgram() [2/3]
RoutineClass * LanguageParser::createProgram (RexxString * name, ArrayClass * source, PackageClass * sourceContext) static
Static method for creating a new RoutineClass instance as a top-level program (no install step is run)
Parameters
name The name given to the routine and package.
source The buffer containing the source.
Returns
An executable method object.
Definition at line 314 of file LanguageParser.cpp.
References ENCODED_NEEDLE, LanguageParser(), name, new_buffer(), OREF_NULL, parser(), RoutineClass::restore(), source, RexxString::strCompare(), and RexxInternalObject::stringValue().
createProgram() [3/3]
RoutineClass * LanguageParser::createProgram (RexxString * name, BufferClass * source) static
Static method for creating a new RoutineClass instance as a top-level program (no install step is run)
Parameters
name The name given to the routine and package.
source The buffer containing the source.
Returns
An executable method object.
Definition at line 289 of file LanguageParser.cpp.
References LanguageParser(), name, OREF_NULL, parser(), RoutineClass::restore(), and source.
Referenced by MemoryObject::createImage(), createPackage(), createProgramFromFile(), processInstore(), and TranslateDispatcher::run().
createProgramFromFile()
RoutineClass * LanguageParser::createProgramFromFile (RexxString * filename) static
Retrieve a routine object from a file. This will first attempt to restore a previously translated image, then will try to translate the source if that fails.
Parameters
filename The target file name.
Returns
A resulting Routine object, if possible.
Definition at line 367 of file LanguageParser.cpp.
References createProgram(), Error_Program_unreadable_name, RexxString::getStringData(), OREF_NULL, FileProgramSource::readProgram(), reportException(), and RoutineClass::restore().
Referenced by RexxActivation::callExternalRexx(), createPackage(), RexxStartDispatcher::run(), and CallProgramDispatcher::run().
createRoutine() [1/3]
RoutineClass * LanguageParser::createRoutine (RexxString * name, ArrayClass * source, PackageClass * sourceContext) static
Static method for creating a new RoutineClass instance.
Parameters
name The name given to the routine and package.
source The code source as an array of strings.
sourceContext A parent source context that this method will inherit a package environment from.
Returns
An executable method object.
Definition at line 195 of file LanguageParser.cpp.
References ENCODED_NEEDLE, LanguageParser(), name, new_buffer(), OREF_NULL, parser(), RoutineClass::restore(), source, RexxString::strCompare(), and RexxInternalObject::stringValue().
Referenced by createRoutine(), RoutineClass::newFileRexx(), RoutineClass::newRexx(), and NewRoutine().
createRoutine() [2/3]
RoutineClass * LanguageParser::createRoutine (RexxString * name, BufferClass * source, PackageClass * sourceContext) static
Static method for creating a new RoutineClass instance.
Parameters
name The name given to the routine and package.
source The code source as a buffer
sourceContext A parent source context that this method will inherit a package environment from.
Returns
An executable method object.
Definition at line 264 of file LanguageParser.cpp.
References LanguageParser(), name, OREF_NULL, parser(), RoutineClass::restore(), and source.
createRoutine() [3/3]
RoutineClass * LanguageParser::createRoutine (RexxString * name, PackageClass * sourceContext) static
Static method for creating a new RoutineClass instance from a file.
Parameters
name The filename to read the routine source from.
sourceContext A parent source context that this routine will inherit a package environment from.
Returns
An executable routine object.
Definition at line 231 of file LanguageParser.cpp.
References createRoutine(), Error_Program_unreadable_name, RexxString::getStringData(), name, OREF_NULL, FileProgramSource::readProgram(), reportException(), and RoutineClass::restore().
createStackFrame()
StackFrameClass * LanguageParser::createStackFrame ()
Create a stack frame for this parsing context.
Returns
a stack frame instance for error reporting
Definition at line 862 of file LanguageParser.cpp.
References clauseLocation, StackFrameClass::FRAME_COMPILE, SourceLocation::getLineNumber(), OREF_NULL, package, PackageClass::programName, and PackageClass::traceBack().
Referenced by CompileActivationFrame::createStackFrame().
decodeExternalMethod()
void LanguageParser::decodeExternalMethod (RexxString * methodName, RexxString * externalSpec, RexxString *& library, RexxString *& procedure)
Decode an external library method specification.
Parameters
methodName The internal name of the method (uppercased).
externalSpec The external specification string.
library The returned library name.
procedure The returned package name.
Definition at line 1354 of file DirectiveParser.cpp.
References Error_Translation_bad_external, OREF_NULL, syntaxError(), and words().
Referenced by attributeDirective(), and methodDirective().
doNew()
RexxInstruction* LanguageParser::doNew ()
doubleMessageNew()
RexxInstruction * LanguageParser::doubleMessageNew (RexxExpressionMessage * msg)
Create a new Message instruction object for a double tilde message type.
Parameters
_message the message expression term...used as a standalone instruction.
Returns
A message object.
Definition at line 2873 of file InstructionParser.cpp.
References RexxExpressionMessage::argumentCount, and new_variable_instruction.
Referenced by nextInstruction().
dropNew()
RexxInstruction * LanguageParser::dropNew ()
Build a drop instruction object.
Returns
An executable object.
Definition at line 2205 of file InstructionParser.cpp.
References KEYWORD_DROP, new_variable_instruction, processVariableList(), and subTerms.
Referenced by nextInstruction().
dynamicCallNew()
RexxInstruction * LanguageParser::dynamicCallNew (RexxToken * token)
Process a call of the form CALL (expr), which has a dynamically determined call target.
Parameters
token The first token of the expression (with the opening paren of the name expression.)
Returns
A new object for executing this call.
Definition at line 1082 of file InstructionParser.cpp.
References Error_Invalid_expression_call, new_variable_instruction, OREF_NULL, parenExpression(), parseArgList(), subTerms, syntaxError(), and TERM_EOC.
Referenced by callNew().
dynamicSignalNew()
RexxInstruction * LanguageParser::dynamicSignalNew ()
We've encountered a SIGNAL VALUE or an implicit SIGNAL value version of a SIGNAL instruction. This has a separate instruction object tailored to that function, so complete parsing of this instruction and return an instance of that instruction object.
Returns
An instruction object for processing a SIGNAL VALUE
Definition at line 3899 of file InstructionParser.cpp.
References Error_Invalid_expression_signal, new_instruction, requiredExpression(), and TERM_EOC.
Referenced by signalNew().
elseNew()
RexxInstruction * LanguageParser::elseNew (RexxToken * token)
We've encountered an ELSE in the source. Just create an ELSE instruction object. Wiring this up with the corresponding IF/THEN takes place when this is added to the instruction chain, as well as handling errors for misplaced instructions.
Parameters
token The token for the ELSE keyword. Used for setting the instruction location.
Returns
A new ELSE instruction object.
Definition at line 2230 of file InstructionParser.cpp.
References new_instruction.
Referenced by nextInstruction().
endIfNew()
RexxInstruction * LanguageParser::endIfNew (RexxInstructionIf * parent)
Create an END IF instruction. The EndIf is a dummy instruction that is attached to the end of the instruction following the THEN of an IF or WHEN. This branches to the appropriate location after that instruction completes. For example, branching around an ELSE or to the end of a SELECT block.
This is created when the pending control stack is processed when the previous instruction completes.
Parameters
parent The parent instruction.
Returns
The new instruction object.
Definition at line 2285 of file InstructionParser.cpp.
References new_instruction.
Referenced by flushControl().
endLocation()
void LanguageParser::endLocation (SourceLocation & location)
Save the current scanning location.
Parameters
location A location object to store this in.
Definition at line 147 of file Scanner.cpp.
References lineNumber, lineOffset, and SourceLocation::setEnd().
Referenced by nextSpecial(), scanLiteral(), and scanSymbol().
endNew()
RexxInstruction * LanguageParser::endNew ()
Create a new END instruction. This only parses the instruction syntax and creates the new instruction object. Matching up with its matching block instruction occurs when it is added to the instruction chain.
Returns
An END instruction object.
Definition at line 2246 of file InstructionParser.cpp.
References Error_Invalid_data_end, Error_Symbol_expected_end, RexxToken::isEndOfClause(), RexxToken::isSymbol(), name, new_instruction, nextReal(), OREF_NULL, requiredEndOfClause(), syntaxError(), and RexxToken::value().
Referenced by nextInstruction().
error() [1/5]
void LanguageParser::error (RexxErrorCodes errorcode, const SourceLocation & location, ArrayClass * subs)
Raise an error message using specifically provided location information.
Parameters
errorcode The error message to raise.
location The location of the instruction in error.
subs The message substitutions.
Definition at line 4079 of file LanguageParser.cpp.
References clauseLocation, ActivityManager::currentActivity, OREF_NULL, and Activity::raiseException().
error() [2/5]
void LanguageParser::error (RexxErrorCodes errorcode)
Raise a simple error message, using the current clause location information.
Parameters
errorcode The error message to raise.
Definition at line 4065 of file LanguageParser.cpp.
References ActivityManager::currentActivity, OREF_NULL, and Activity::raiseException().
Referenced by parseClassReference(), requiredEndOfClause(), requiredExpression(), requiredLogicalExpression(), syntaxError(), and translateConstantExpression().
error() [3/5]
void LanguageParser::error (RexxErrorCodes errorcode, RexxObject * value)
Issue an error message with a single substitution value.
Parameters
errorcode The error to issue.
value The substitution value.
Definition at line 4137 of file LanguageParser.cpp.
References ActivityManager::currentActivity, new_array(), OREF_NULL, and Activity::raiseException().
error() [4/5]
void LanguageParser::error (RexxErrorCodes errorcode, RexxObject * value1, RexxObject * value2)
Issue an error message with two substitution values.
Parameters
errorcode The error number to issue.
value1 The first substitution object.
value2 The second substitution object.
Definition at line 4150 of file LanguageParser.cpp.
References ActivityManager::currentActivity, new_array(), OREF_NULL, and Activity::raiseException().
error() [5/5]
void LanguageParser::error (RexxErrorCodes errorcode, RexxObject * value1, RexxObject * value2, RexxObject * value3)
Issue an error message with three substitution values.
Parameters
errorcode The error number to issue.
value1 The first substitution object.
value2 The second substitution object.
value3 The third substitution object.
Definition at line 4164 of file LanguageParser.cpp.
References ActivityManager::currentActivity, new_array(), OREF_NULL, and Activity::raiseException().
errorLine()
void LanguageParser::errorLine (RexxErrorCodes errorcode, RexxInstruction * instruction)
Raise an error where one of the error message substitutions is the line number location of another instruction.
Parameters
errorcode The error to issue
instruction The instruction used to obtain the line number for the message.
Definition at line 4097 of file LanguageParser.cpp.
References ActivityManager::currentActivity, RexxInstruction::getLineNumber(), new_array(), new_integer(), OREF_NULL, and Activity::raiseException().
Referenced by syntaxError().
errorPosition()
void LanguageParser::errorPosition (RexxErrorCodes errorcode, RexxToken * token)
Raise an error using a Token location for the message substitution.
Parameters
errorcode The error to issue.
token The source token for the location.
Definition at line 4110 of file LanguageParser.cpp.
References ActivityManager::currentActivity, SourceLocation::getLineNumber(), RexxToken::getLocation(), SourceLocation::getOffset(), new_array(), new_integer(), OREF_NULL, and Activity::raiseException().
Referenced by syntaxErrorAt().
errorToken()
void LanguageParser::errorToken (RexxErrorCodes errorcode, RexxToken * token)
Raise an error using the value of the token as a substitution parameter.
Parameters
errorcode The error code to issue.
token The token used for the substitution information.
Definition at line 4125 of file LanguageParser.cpp.
References ActivityManager::currentActivity, RexxToken::displayValue(), new_array(), OREF_NULL, and Activity::raiseException().
Referenced by syntaxError().
exitNew()
RexxInstruction * LanguageParser::exitNew ()
Parse an EXIT instruction and return an executable instruction object for this exit.
Returns
A instance of the EXIT instruction.
Definition at line 2299 of file InstructionParser.cpp.
References new_instruction, parseExpression(), and TERM_EOC.
Referenced by nextInstruction().
expose()
void LanguageParser::expose (RexxString * name)
Add a variable name to the list of variables exposed by a method.
Parameters
name The name of the variable.
Definition at line 2214 of file LanguageParser.cpp.
References exposedVariables, name, new_string_table(), OREF_NULL, and HashCollection::put().
Referenced by processVariableList().
exposeNew()
RexxInstruction * LanguageParser::exposeNew ()
Parse and create a new EXPOSE instruction
Returns
The configured instruction instance.
Definition at line 2315 of file InstructionParser.cpp.
References Error_Translation_expose, Error_Translation_expose_interpret, isInterpret(), RexxInstruction::isType(), KEYWORD_EXPOSE, KEYWORD_FIRST, lastInstruction, new_variable_instruction, processVariableList(), subTerms, and syntaxError().
Referenced by nextInstruction().
findClassDirective()
ClassDirective * LanguageParser::findClassDirective (RexxString * name)
Retrieve a currently processed class directive.
Parameters
name The name from the ::class directive.
Returns
The class directive object or OREF_NULL if the named class is not found.
Definition at line 230 of file DirectiveParser.cpp.
References classDependencies, StringHashCollection::entry(), and name.
Referenced by annotateDirective().
findClassMethod()
MethodClass * LanguageParser::findClassMethod (RexxString * name)
Locate the most recently created class method with a given name in this context.
Parameters
name The name to check.
Definition at line 586 of file DirectiveParser.cpp.
References activeClass, ClassDirective::findClassMethod(), name, and OREF_NULL.
Referenced by processAttributeAnnotations().
findInstanceMethod()
MethodClass * LanguageParser::findInstanceMethod (RexxString * name)
Locate the most recently created instance method with a given name in this context.
Parameters
name The name to check.
Definition at line 563 of file DirectiveParser.cpp.
References activeClass, StringHashCollection::entry(), ClassDirective::findInstanceMethod(), name, OREF_NULL, and unattachedMethods.
Referenced by processAttributeAnnotations().
findLabel()
RexxInstruction * LanguageParser::findLabel (RexxString * labelname)
Locate a label for a name match.
Parameters
labelname The label name.
Returns
The label instruction, or OREF_NULL if the label doesn't exist
Definition at line 2574 of file LanguageParser.cpp.
References HashCollection::get(), labels, and OREF_NULL.
findMethod()
MethodClass * LanguageParser::findMethod (RexxString * name)
Locate the most recently created method with a given name in this context.
Parameters
name The name to check.
Definition at line 540 of file DirectiveParser.cpp.
References activeClass, StringHashCollection::entry(), ClassDirective::findMethod(), name, OREF_NULL, and unattachedMethods.
Referenced by annotateDirective().
findRoutine()
RoutineClass * LanguageParser::findRoutine (RexxString * name)
Test if a routine directive is defining a duplicate routine.
Parameters
name The name from the ::routine directive.
Returns
true if routine with this name has already been encounterd.
Definition at line 258 of file DirectiveParser.cpp.
References StringHashCollection::entry(), name, and routines.
Referenced by annotateDirective().
firstToken()
void LanguageParser::firstToken () inline
Definition at line 172 of file LanguageParser.hpp.
References clause, and RexxClause::firstToken().
Referenced by checkDirective(), hasBody(), nextInstruction(), parseArgArray(), and parseArgList().
flushControl()
void LanguageParser::flushControl (RexxInstruction * instruction)
Flush an pending instructions from the control stack for a new added instruction.
Parameters
instruction The newly added instruction.
Definition at line 1915 of file LanguageParser.cpp.
References addClause(), endIfNew(), KEYWORD_ELSE, KEYWORD_IFTHEN, KEYWORD_WHENTHEN, OREF_NULL, popDo(), pushDo(), topDoType(), and type.
Referenced by translateBlock().
followingChar()
unsigned int LanguageParser::followingChar () inline
Definition at line 156 of file LanguageParser.hpp.
References getNextChar(), haveNextChar(), and INVALID_CHARACTER.
Referenced by locateToken().
forwardNew()
RexxInstruction * LanguageParser::forwardNew ()
Parse and create a new FORWARD instruction object.
Returns
The new instruction object.
Definition at line 2427 of file InstructionParser.cpp.
References Error_Invalid_expression_forward_arguments, Error_Invalid_expression_forward_class, Error_Invalid_expression_forward_message, Error_Invalid_expression_forward_to, Error_Invalid_expression_raise_list, Error_Invalid_subkeyword_arguments, Error_Invalid_subkeyword_continue, Error_Invalid_subkeyword_forward_class, Error_Invalid_subkeyword_forward_option, Error_Invalid_subkeyword_message, Error_Invalid_subkeyword_to, Error_Translation_forward_interpret, RexxToken::isEndOfClause(), isInterpret(), RexxToken::isLeftParen(), RexxToken::isSymbol(), new_instruction, nextReal(), OREF_NULL, parseArgArray(), parseConstantExpression(), pushSubTerm(), SUBKEY_ARGUMENTS, SUBKEY_ARRAY, SUBKEY_CLASS, SUBKEY_CONTINUE, SUBKEY_MESSAGE, SUBKEY_TO, RexxToken::subKeyword(), syntaxError(), and TERM_RIGHT.
Referenced by nextInstruction().
generateMethod()
MethodClass * LanguageParser::generateMethod (PackageClass * sourceContext = OREF_NULL)
Generate a method object from a source collection.
Parameters
sourceContext An optional source context used to add additional visibility to dynamically generated methods.
Returns
A method object represented by the leading code block of the source. Ideally, this code should not contain directives, but since this was allowed in the past, we need to continue to allow this.
Definition at line 590 of file LanguageParser.cpp.
References compileSource(), PackageClass::inheritPackageContext(), PackageClass::initCode, installPackage(), PackageClass::mainExecutable, mainSection, name, OREF_NULL, and package.
generatePackage()
PackageClass * LanguageParser::generatePackage (PackageClass * sourceContext = OREF_NULL)
Load a package and return the source object for the package. We create the main executable as a Routine object, but also leave the initialization code in place for the package loader to use.
Returns
A package object representing the package.
Definition at line 711 of file LanguageParser.cpp.
References compileSource(), PackageClass::inheritPackageContext(), PackageClass::initCode, PackageClass::mainExecutable, mainSection, name, and package.
generateProgram()
RoutineClass * LanguageParser::generateProgram (PackageClass * sourceContext = OREF_NULL)
Generate a routine object as a top-level program.
Returns
A routine object represented by the leading code block of the source. This will not have an installs performed at this time.
Definition at line 653 of file LanguageParser.cpp.
References compileSource(), PackageClass::inheritPackageContext(), PackageClass::initCode, PackageClass::mainExecutable, mainSection, name, and package.
generateRoutine()
RoutineClass * LanguageParser::generateRoutine (PackageClass * sourceContext = OREF_NULL)
Generate a routine object from a source collection.
Parameters
sourceContext An optional source context used to add additional visibility to dynamically generated methods.
Returns
A routine object represented by the leading code block of the source. Ideally, this code should not contain directives, but since this was allowed in the past, we need to continue to allow this.
Definition at line 624 of file LanguageParser.cpp.
References compileSource(), PackageClass::inheritPackageContext(), PackageClass::initCode, installPackage(), PackageClass::mainExecutable, mainSection, name, OREF_NULL, and package.
getChar() [1/2]
unsigned int LanguageParser::getChar () inline
Definition at line 152 of file LanguageParser.hpp.
References current, and lineOffset.
Referenced by locateToken(), nextSpecial(), scanComment(), scanLiteral(), and scanSymbol().
getChar() [2/2]
unsigned int LanguageParser::getChar (size_t o) inline
Definition at line 153 of file LanguageParser.hpp.
References current.
getGuard()
ArrayClass * LanguageParser::getGuard ()
Complete guard variable collection and return the table of variable names.
Returns
An array of the guard variable names.
Definition at line 2608 of file LanguageParser.cpp.
References guardVariables, HashCollection::makeArray(), and OREF_NULL.
Referenced by guardNew().
getLocation()
const SourceLocation& LanguageParser::getLocation () inline
Definition at line 167 of file LanguageParser.hpp.
References clauseLocation.
getNextChar()
unsigned int LanguageParser::getNextChar () inline
Definition at line 155 of file LanguageParser.hpp.
References current, and lineOffset.
Referenced by followingChar(), and scanLiteral().
getPackage()
PackageClass* LanguageParser::getPackage () inline
Definition at line 130 of file LanguageParser.hpp.
References package.
Referenced by CompileActivationFrame::getPackage().
getRetriever()
RexxVariableBase * LanguageParser::getRetriever (RexxString * name)
Build a retriever for a string name. This will be a version that uses dynamic lookup for variables rather than using pre-assigned slots. Generally used for dynamic lookups such as from the variable pool interface.
Parameters
name The variable name.
Returns
A retriever object for looking up this value.
Definition at line 2503 of file LanguageParser.cpp.
References VariableDictionary::buildCompoundVariable(), Error_Translation_invalid_attribute, RexxString::isSymbol(), name, OREF_NULL, STRING_COMPOUND_NAME, STRING_NAME, STRING_STEM, and syntaxError().
Referenced by attributeDirective(), and methodDirective().
getStringLine()
RexxString * LanguageParser::getStringLine ()
Extract the current line as a string object.
Returns
The current line as a string object.
Definition at line 974 of file LanguageParser.cpp.
References current, currentLength, and new_string().
Referenced by resourceDirective().
getToken()
RexxToken * LanguageParser::getToken (int terminators, RexxErrorCodes errorcode = Error_None)
Get a token from the clause, combining terminator checks and error reporting if we don't get a terminator.
Parameters
terminators The terminators for the current context.
errorcode The error to issue if no token is found. The error code is optional, and if not specified, OREF_NULL is returned.
Returns
The parsed off token.
Definition at line 3335 of file LanguageParser.cpp.
References RexxToken::isTerminator(), nextToken(), OREF_NULL, previousToken(), and syntaxError().
Referenced by parseMessage().
guardNew()
RexxInstruction * LanguageParser::guardNew ()
Parse and create a guard expression.
Returns
A constructed executable GUARD instruction.
Definition at line 2578 of file InstructionParser.cpp.
References Error_Invalid_expression_guard, Error_Invalid_subkeyword_guard, Error_Invalid_subkeyword_guard_on, Error_Translation_guard_expose, Error_Translation_guard_interpret, getGuard(), RexxToken::isEndOfClause(), isInterpret(), RexxToken::isSymbol(), new_variable_instruction, nextReal(), OREF_NULL, requiredLogicalExpression(), setGuard(), SUBKEY_OFF, SUBKEY_ON, SUBKEY_WHEN, RexxToken::subKeyword(), syntaxError(), and TERM_EOC.
Referenced by nextInstruction().
hasBody()
bool LanguageParser::hasBody ()
Test if a directive is followed by a body of Rexx code instead of another directive or the end of the source.
Returns
True if there is a non-directive clause following the current clause.
Definition at line 189 of file DirectiveParser.cpp.
References clauseAvailable(), firstToken(), RexxToken::isType(), nextClause(), nextReal(), reclaimClause(), and TOKEN_DCOLON.
Referenced by attributeDirective().
haveNextChar()
bool LanguageParser::haveNextChar () inline
Definition at line 160 of file LanguageParser.hpp.
References currentLength, and lineOffset.
Referenced by followingChar(), and scanSymbol().
holdObject()
void LanguageParser::holdObject (RexxInternalObject * object) inline
Definition at line 134 of file LanguageParser.hpp.
References holdStack, and PushThroughStack::push().
Referenced by parenExpression(), parseCollectionMessage(), parseConstantExpression(), parseMessage(), popNTerms(), popSubTerm(), popTerm(), requiredTerm(), and translateConstantExpression().
ifNew()
RexxInstruction * LanguageParser::ifNew ()
Create a new IF or WHEN instruction object. These share the same implementation class, but get wired together differently.
Parameters
type The type of instruction to create.
Returns
A an executable IF instruction object.
Definition at line 2678 of file InstructionParser.cpp.
References Error_Invalid_expression_if, new_instruction, nextReal(), previousToken(), pushSubTerm(), requiredLogicalExpression(), and TERM_IF.
Referenced by nextInstruction().
initializeForDirectives()
void LanguageParser::initializeForDirectives ()
Initialize the global tables used for keeping track of directive information.
Definition at line 833 of file LanguageParser.cpp.
References activeClass, classDependencies, classes, libraries, new_array(), new_string_table(), OREF_NULL, publicRoutines, requires, resources, routines, and unattachedMethods.
Referenced by translate().
initializeForParsing()
void LanguageParser::initializeForParsing ()
Initialize the parser before starting the parse operation. NOTE: This is a transient object, which will never be stored in the oldspace, so we don't need to use OrefSet.
Definition at line 749 of file LanguageParser.cpp.
References clause, control, dotVariables, ProgramSource::getFirstLine(), MemoryObject::getGlobalStrings(), ProgramSource::getLineCount(), HOLDSIZE, holdStack, lineCount, lineNumber, literals, memoryObject, new_queue(), new_string_table(), operators, OREF_NULL, package, position(), HashCollection::put(), PackageClass::setup(), source, strings, subTerms, terms, TheFalseObject, TheNilObject, and TheTrueObject.
Referenced by compileSource().
initializeForTranslation()
void LanguageParser::initializeForTranslation ()
Initialize all of the fields that need to start clean for a new translation section.
Definition at line 1133 of file LanguageParser.cpp.
References calls, currentStack, exposedVariables, RexxLocalVariables::FIRST_VARIABLE_INDEX, firstInstruction, flags, guardVariables, labels, lastInstruction, localVariables, maxStack, new_array(), new_string_table(), noClause, OREF_NULL, TheCommonRetrievers, variableIndex, and variables.
Referenced by translateBlock(), and translateConstantExpression().
installPackage()
void LanguageParser::installPackage ()
Have the generated package process the package installation step at completion of parsing.
Definition at line 851 of file LanguageParser.cpp.
References PackageClass::install(), and package.
Referenced by generateMethod(), and generateRoutine().
interpretNew()
RexxInstruction * LanguageParser::interpretNew ()
Create a new interpret instruction instance.
Returns
An executable INTERPRET instruction.
Definition at line 2772 of file InstructionParser.cpp.
References Error_Invalid_expression_interpret, INTERPRET, new_instruction, requiredExpression(), and TERM_EOC.
Referenced by nextInstruction().
isDuplicateClass()
bool LanguageParser::isDuplicateClass (RexxString * name)
Test if a class directive is defining a duplicate class.
Parameters
name The name from the ::class directive.
Returns
true if a class with this name has already been encounterd.
Definition at line 217 of file DirectiveParser.cpp.
References classDependencies, StringHashCollection::hasEntry(), and name.
Referenced by classDirective().
isDuplicateRoutine()
bool LanguageParser::isDuplicateRoutine (RexxString * name)
Test if a routine directive is defining a duplicate routine.
Parameters
name The name from the ::routine directive.
Returns
true if routine with this name has already been encounterd.
Definition at line 244 of file DirectiveParser.cpp.
References StringHashCollection::hasEntry(), name, and routines.
Referenced by routineDirective().
isExposed()
bool LanguageParser::isExposed (RexxString * varName)
Test if a named variable has been previously exposed.
Parameters
varName The variable name.
Returns
True if the variable has been exposed, false otherwise.
Definition at line 1987 of file LanguageParser.cpp.
References exposedVariables, HashCollection::hasIndex(), localVariables, and OREF_NULL.
Referenced by captureGuardVariable().
isInterpret()
bool LanguageParser::isInterpret () inline
Definition at line 200 of file LanguageParser.hpp.
References flags, and interpret.
Referenced by addSimpleVariable(), addStem(), exposeNew(), forwardNew(), guardNew(), nextInstruction(), replyNew(), and useLocalNew().
isSymbolCharacter()
static bool LanguageParser::isSymbolCharacter (unsigned int ch) inline static
Definition at line 415 of file LanguageParser.hpp.
References characterTable.
Referenced by VariableDictionary::getDirectVariableRetriever(), scanLiteral(), scanSymbol(), and sourceNextToken().
labelNew()
RexxInstruction * LanguageParser::labelNew (RexxToken * nameToken, RexxToken * colonToken)
Create a new label object.
Parameters
nameToken The token that identifies the label name.
colonToken The token marking the colon.
Returns
A new label object.
Definition at line 2792 of file InstructionParser.cpp.
References addLabel(), SourceLocation::getEndLine(), SourceLocation::getEndOffset(), RexxToken::getLocation(), name, new_instruction, RexxInstruction::setEnd(), and RexxToken::value().
Referenced by nextInstruction().
leaveNew()
RexxInstruction * LanguageParser::leaveNew (InstructionKeyword type)
Create a new ITERATE or LEAVE instruction. These two instructions share an implementation class.
Parameters
type The type of instruction we're creating
Returns
The instruction instance.
Definition at line 2822 of file InstructionParser.cpp.
References Error_Invalid_data_iterate, Error_Invalid_data_leave, Error_Symbol_expected_iterate, Error_Symbol_expected_leave, RexxToken::isEndOfClause(), RexxToken::isSymbol(), KEYWORD_LEAVE, name, new_instruction, nextReal(), OREF_NULL, requiredEndOfClause(), syntaxError(), type, and RexxToken::value().
Referenced by nextInstruction().
libraryDirective()
void LanguageParser::libraryDirective (RexxString * name, RexxToken * token)
live()
void LanguageParser::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 491 of file LanguageParser.cpp.
References activeClass, calls, classDependencies, classes, clause, constantVariables, control, currentInstruction, dotVariables, exposedVariables, firstInstruction, guardVariables, holdStack, labels, lastInstruction, libraries, literals, localVariables, mainSection, memory_mark, name, operators, package, publicRoutines, requires, resources, routines, source, strings, subTerms, terms, unattachedMethods, and variables.
liveGeneral()
void LanguageParser::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 538 of file LanguageParser.cpp.
References activeClass, calls, classDependencies, classes, clause, constantVariables, control, currentInstruction, dotVariables, exposedVariables, firstInstruction, guardVariables, holdStack, labels, lastInstruction, libraries, literals, localVariables, mainSection, memory_mark_general, name, operators, package, publicRoutines, requires, resources, routines, source, strings, subTerms, terms, unattachedMethods, and variables.
localVariable()
void LanguageParser::localVariable (RexxString * name)
Add a variable name to the list of explicitly declared to be local.
Parameters
name The name of the variable.
Definition at line 2246 of file LanguageParser.cpp.
References localVariables, name, and HashCollection::put().
Referenced by useLocalNew().
locateToken()
CharacterClass LanguageParser::locateToken (unsigned int & character, bool blanksSignificant)
Locate the next "real" token in the parsing stream, skipping extra blanks and comments.
Parameters
character If this is a "normal" character, this is the character value.
blanksSignificant Indicates if blank characters should be considered as significant in the current context.
Returns
A type of the next token character. If the type is NORMAL_CHAR, the character is also returned in the character reference argument.
Definition at line 270 of file Scanner.cpp.
References CLAUSE_EOF, CLAUSE_EOL, followingChar(), getChar(), INVALID_CHARACTER, lineNumber, lineOffset, moreChars(), moreLines(), nextLine(), NORMAL_CHAR, position(), scanComment(), SIGNIFICANT_BLANK, stepPosition(), and truncateLine().
Referenced by nextSpecial(), and sourceNextToken().
markPosition()
size_t LanguageParser::markPosition () inline
Definition at line 174 of file LanguageParser.hpp.
References clause, and RexxClause::mark().
Referenced by createLoop(), and parseMessageTerm().
messageAssignmentNew()
RexxInstruction * LanguageParser::messageAssignmentNew (RexxExpressionMessage * msg, RexxInternalObject * expr)
Create a new message assignment object.
Parameters
msg The message term that is the expression target.
expr The expression to be evaluated for the assignment value.
Returns
A new instruction to process this assignment.
Definition at line 2891 of file InstructionParser.cpp.
References RexxExpressionMessage::argumentCount, RexxExpressionMessage::makeAssignment(), MESSAGE, and new_variable_instruction.
Referenced by nextInstruction().
messageAssignmentOpNew()
RexxInstruction * LanguageParser::messageAssignmentOpNew (RexxExpressionMessage * msg, RexxToken * operation, RexxInternalObject * expr)
Create a message term pseudo assignment instruction for a shortcut operator. The instruction is of the form "messageTerm (op)= expr".
Parameters
message The target message term.
operation The operation to perform in the expansion.
expression The expression (which is the right-hand term of the eventual expression).
Returns
The constructed message operator.
Definition at line 2915 of file InstructionParser.cpp.
References RexxExpressionMessage::argumentCount, RexxInternalObject::copy(), RexxExpressionMessage::makeAssignment(), MESSAGE, new_variable_instruction, and RexxToken::subtype().
Referenced by nextInstruction().
messageNew()
RexxInstruction * LanguageParser::messageNew (RexxExpressionMessage * msg)
Create a new Message instruction object.
Parameters
_message the message expression term...used as a standalone instruction.
Returns
A message object.
Definition at line 2855 of file InstructionParser.cpp.
References RexxExpressionMessage::argumentCount, MESSAGE, and new_variable_instruction.
Referenced by nextInstruction().
methodDirective()
void LanguageParser::methodDirective ()
Process a ::METHOD directive in a source file.
Definition at line 629 of file DirectiveParser.cpp.
References addMethod(), checkDirective(), checkDuplicateMethod(), commonString(), RexxString::concatWithCstring(), createAbstractMethod(), createAttributeGetterMethod(), createAttributeSetterMethod(), createDelegateMethod(), createNativeMethod(), decodeExternalMethod(), DEFAULT_ACCESS_SCOPE, DEFAULT_GUARD, DEFAULT_PROTECTION, Error_Invalid_subkeyword_method, Error_Symbol_expected_delegate, Error_Symbol_or_string_external, Error_Symbol_or_string_method, Error_Translation_abstract_method, Error_Translation_attribute_method, Error_Translation_delegate_method, Error_Translation_duplicate_method, Error_Translation_external_method, getRetriever(), GUARDED_METHOD, RexxToken::isEndOfClause(), RexxToken::isLiteral(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), name, nextReal(), OREF_NULL, PACKAGE_SCOPE, PRIVATE_SCOPE, PROTECTED_METHOD, PUBLIC_SCOPE, RexxToken::subDirective(), SUBDIRECTIVE_ABSTRACT, SUBDIRECTIVE_ATTRIBUTE, SUBDIRECTIVE_CLASS, SUBDIRECTIVE_DELEGATE, SUBDIRECTIVE_EXTERNAL, SUBDIRECTIVE_GUARDED, SUBDIRECTIVE_PACKAGE, SUBDIRECTIVE_PRIVATE, SUBDIRECTIVE_PROTECTED, SUBDIRECTIVE_PUBLIC, SUBDIRECTIVE_UNGUARDED, SUBDIRECTIVE_UNPROTECTED, syntaxError(), translateBlock(), UNGUARDED_METHOD, UNPROTECTED_METHOD, RexxString::upper(), and RexxToken::value().
Referenced by nextDirective().
moreChars()
bool LanguageParser::moreChars () inline
Definition at line 159 of file LanguageParser.hpp.
References currentLength, and lineOffset.
Referenced by locateToken(), scanComment(), scanLiteral(), and scanSymbol().
moreLines()
bool LanguageParser::moreLines () inline
Definition at line 161 of file LanguageParser.hpp.
References lineCount, and lineNumber.
Referenced by atEnd(), locateToken(), resourceDirective(), and scanComment().
needVariable()
void LanguageParser::needVariable (RexxToken * token)
Validate that a given token is a variable (i.e., a symbol that does not begin with a digit).
Parameters
token The target token.
Definition at line 881 of file LanguageParser.cpp.
References Error_Invalid_variable_number, Error_Invalid_variable_period, RexxString::getChar(), RexxToken::isVariable(), syntaxError(), and RexxToken::value().
Referenced by addVariable(), assignmentNew(), assignmentOpNew(), and parseVariableOrMessageTerm().
needVariableOrDotSymbol()
void LanguageParser::needVariableOrDotSymbol (RexxToken * token)
Validate that a token is a variable or the literal dot (e.g. the tokens allowed in a parsing template).
Parameters
token The target token.
Definition at line 906 of file LanguageParser.cpp.
References Error_Invalid_variable_number, RexxToken::isDotSymbol(), RexxToken::isVariable(), and syntaxError().
newControlledLoop()
RexxInstruction * LanguageParser::newControlledLoop (RexxString * label, RexxVariableBase * countVariable, RexxToken * nameToken)
Parse and create the variants of a controlled DO/LOOP instruction (Loop i = 1 to 5 by 2 for 10). This can also include a WHILE or UNTIL modifier (but not both).
Parameters
label Any label obtained from the LABEL keyword.
c A variable name for setting a counter (optional)
nameToken The control variable name token.
Returns
A constructed instruction object of the appropriate type.
Definition at line 1265 of file InstructionParser.cpp.
References addVariable(), WhileUntilLoop::conditional, control, Error_Interpretation_switch, Error_Invalid_do_duplicate, Error_Invalid_expression_by, Error_Invalid_expression_control, Error_Invalid_expression_for, Error_Invalid_expression_to, Error_None, EXP_BY, EXP_FOR, EXP_TO, RexxToken::isEndOfClause(), new_instruction, nextReal(), OREF_NULL, parseLoopConditional(), previousToken(), pushSubTerm(), reportException(), requiredExpression(), SUBKEY_BY, SUBKEY_FOR, SUBKEY_NONE, SUBKEY_TO, SUBKEY_UNTIL, SUBKEY_WHILE, RexxToken::subKeyword(), syntaxError(), TERM_CONTROL, and RexxToken::value().
Referenced by createLoop().
newDoOverLoop()
RexxInstruction * LanguageParser::newDoOverLoop (RexxString * label, RexxVariableBase * countVariable, RexxToken * nameToken)
Parse and create the variants of a DO OVER loop instruction. This can also include a WHILE or UNTIL modifier (but not both).
Parameters
label Any label obtained from the LABEL keyword.
nameToken The control variable name token.
Returns
A constructed instruction object of the appropriate type.
Definition at line 1432 of file InstructionParser.cpp.
References addVariable(), WhileUntilLoop::conditional, control, Error_Interpretation_switch, Error_Invalid_do_duplicate, Error_Invalid_expression_for, Error_Invalid_expression_over, Error_None, ForLoop::forCount, RexxToken::isEndOfClause(), new_instruction, nextReal(), OREF_NULL, parseLoopConditional(), previousToken(), pushSubTerm(), reportException(), requiredExpression(), SUBKEY_FOR, SUBKEY_NONE, SUBKEY_UNTIL, SUBKEY_WHILE, RexxToken::subKeyword(), syntaxError(), TERM_CONTROL, TERM_OVER, and RexxToken::value().
Referenced by createLoop().
newDoWithLoop()
RexxInstruction * LanguageParser::newDoWithLoop (RexxString * label, RexxVariableBase * countVariable, RexxToken * token)
Parse and create the variants of a DO WITH loop instruction. This can also include a WHILE or UNTIL modifier (but not both).
Parameters
label Any label obtained from the LABEL keyword.
Returns
A constructed instruction object of the appropriate type.
Definition at line 1582 of file InstructionParser.cpp.
References WhileUntilLoop::conditional, Error_Interpretation_switch, Error_Invalid_do_duplicate, Error_Invalid_do_with_no_control, Error_Invalid_do_with_no_over, Error_Invalid_expression_for, Error_Invalid_expression_over, Error_None, ForLoop::forCount, WithLoop::indexVar, RexxToken::isEndOfClause(), RexxToken::isSymbol(), WithLoop::itemVar, new_instruction, nextReal(), OREF_NULL, parseLoopConditional(), previousToken(), pushSubTerm(), reportException(), requiredExpression(), requiredVariable(), SUBKEY_FOR, SUBKEY_INDEX, SUBKEY_ITEM, SUBKEY_NONE, SUBKEY_OVER, SUBKEY_UNTIL, SUBKEY_WHILE, RexxToken::subKeyword(), WithLoop::supplierSource, syntaxError(), TERM_CONTROL, and TERM_OVER.
Referenced by createLoop().
newLoopForever()
RexxInstruction * LanguageParser::newLoopForever (RexxString * label, RexxVariableBase * countVariable)
Create an instance of a DO FOREVER loop.
Parameters
label The optional block label.
countVariable The optional counter variable.
Returns
An instruction object for a do block.
Definition at line 1806 of file InstructionParser.cpp.
References new_instruction.
Referenced by createLoop(), and parseForeverLoop().
newLoopUntil()
RexxInstruction * LanguageParser::newLoopUntil (RexxString * label, RexxVariableBase * countVariable, WhileUntilLoop & conditional)
Create an instance of a DO WHILE loop.
Parameters
label The optional block label.
countVariable The optional counter variable.
Returns
An instruction object for a do block.
Definition at line 1840 of file InstructionParser.cpp.
References new_instruction.
Referenced by createLoop(), and parseForeverLoop().
newLoopWhile()
RexxInstruction * LanguageParser::newLoopWhile (RexxString * label, RexxVariableBase * countVariable, WhileUntilLoop & conditional)
Create an instance of a DO WHILE loop.
Parameters
label The optional block label.
countVariable The optional counter variable.
Returns
An instruction object for a do block.
Definition at line 1823 of file InstructionParser.cpp.
References new_instruction.
Referenced by createLoop(), and parseForeverLoop().
newSimpleDo()
RexxInstruction * LanguageParser::newSimpleDo (RexxString * label)
Create an instance of a simple DO block.
Parameters
label The optional block label.
Returns
An instruction object for a do block.
Definition at line 1789 of file InstructionParser.cpp.
References new_instruction.
Referenced by createLoop().
nextChar()
unsigned int LanguageParser::nextChar () inline
Definition at line 154 of file LanguageParser.hpp.
References current, and lineOffset.
Referenced by scanComment().
nextClause()
bool LanguageParser::nextClause ()
Extract a clause from the source and return as a clause object. The clause object contains a list of all of the tokens contained within the clause and is used by the parser to determine the type of instruction and create the instruction parse tree.
Returns
true if we managed to get a clause, false otherwise.
Definition at line 1005 of file LanguageParser.cpp.
References clause, clauseLocation, flags, RexxClause::getLocation(), RexxToken::getLocation(), RexxToken::isEndOfClause(), RexxToken::isEndOfFile(), lineNumber, lineOffset, RexxClause::newClause(), noClause, OREF_NULL, reclaimed, SourceLocation::setEnd(), RexxClause::setLocation(), RexxClause::setStart(), and sourceNextToken().
Referenced by checkDirective(), hasBody(), nextDirective(), translate(), and translateBlock().
nextDirective()
void LanguageParser::nextDirective ()
Parse a directive instruction.
Definition at line 64 of file DirectiveParser.cpp.
References annotateDirective(), attributeDirective(), classDirective(), constantDirective(), DIRECTIVE_ANNOTATE, DIRECTIVE_ATTRIBUTE, DIRECTIVE_CLASS, DIRECTIVE_CONSTANT, DIRECTIVE_METHOD, DIRECTIVE_OPTIONS, DIRECTIVE_REQUIRES, DIRECTIVE_RESOURCE, DIRECTIVE_ROUTINE, Error_Symbol_expected_directive, Error_Translation_bad_directive, RexxToken::isSymbol(), RexxToken::isType(), RexxToken::keyDirective(), methodDirective(), nextClause(), nextReal(), noClauseAvailable(), optionsDirective(), requiresDirective(), resourceDirective(), routineDirective(), syntaxError(), and TOKEN_DCOLON.
Referenced by translate().
nextInstruction()
RexxInstruction * LanguageParser::nextInstruction ()
Process an individual Rexx clause and decide what type of instruction it represents.
Returns
An executable instruction object, or OREF_NULL if we've reached the end of a code block.
Definition at line 122 of file InstructionParser.cpp.
References addressNew(), assignmentNew(), assignmentOpNew(), callNew(), commandNew(), createLoop(), currentStack, doubleMessageNew(), dropNew(), elseNew(), ArrayClass::empty(), endNew(), Error_Interpretation_switch, Error_Invalid_expression_general, Error_Unexpected_label_interpret, Error_Unexpected_then_then, exitNew(), exposeNew(), firstToken(), forwardNew(), guardNew(), ifNew(), interpretNew(), RexxExpressionMessage::isDoubleTilde(), RexxToken::isEndOfClause(), isInterpret(), RexxToken::isSubtype(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), RexxToken::isType(), RexxToken::keyword(), KEYWORD_ADDRESS, KEYWORD_ARG, KEYWORD_CALL, KEYWORD_DO, KEYWORD_DROP, KEYWORD_ELSE, KEYWORD_END, KEYWORD_EXIT, KEYWORD_EXPOSE, KEYWORD_FORWARD, KEYWORD_GUARD, KEYWORD_IF, KEYWORD_INTERPRET, KEYWORD_ITERATE, KEYWORD_LEAVE, KEYWORD_LOOP, KEYWORD_NONE, KEYWORD_NOP, KEYWORD_NUMERIC, KEYWORD_OPTIONS, KEYWORD_OTHERWISE, KEYWORD_PARSE, KEYWORD_PROCEDURE, KEYWORD_PULL, KEYWORD_PUSH, KEYWORD_QUEUE, KEYWORD_RAISE, KEYWORD_REPLY, KEYWORD_RETURN, KEYWORD_SAY, KEYWORD_SELECT, KEYWORD_SIGNAL, KEYWORD_THEN, KEYWORD_TRACE, KEYWORD_USE, KEYWORD_WHEN, labelNew(), leaveNew(), messageAssignmentNew(), messageAssignmentOpNew(), messageNew(), nextReal(), nextToken(), nopNew(), numericNew(), OPERATOR_EQUAL, OPERATOR_STRICT_EQUAL, optionsNew(), OREF_NULL, otherwiseNew(), parseExpression(), parseMessageTerm(), parseNew(), previousToken(), procedureNew(), pushNew(), queueNew(), raiseNew(), reclaimClause(), replyNew(), reportException(), returnNew(), sayNew(), selectNew(), signalNew(), SUBKEY_ARG, SUBKEY_NONE, SUBKEY_PULL, subTerms, syntaxError(), TERM_EOC, terms, TOKEN_ASSIGNMENT, TOKEN_COLON, TOKEN_DCOLON, traceNew(), trimClause(), useNew(), and whenNew().
Referenced by translateBlock().
nextLine()
void LanguageParser::nextLine ()
Advance the current position to the next line.
Definition at line 919 of file LanguageParser.cpp.
References clause, lineNumber, lineOffset, OREF_NULL, position(), and RexxClause::setEnd().
Referenced by conditionalNextLine(), locateToken(), resourceDirective(), scanComment(), and sourceNextToken().
nextReal()
RexxToken* LanguageParser::nextReal () inline
Definition at line 204 of file LanguageParser.hpp.
References clause, and RexxClause::nextRealToken().
Referenced by addressNew(), annotateDirective(), attributeDirective(), callNew(), callOnNew(), checkDirective(), classDirective(), constantDirective(), createLoop(), endNew(), forwardNew(), guardNew(), hasBody(), ifNew(), leaveNew(), methodDirective(), newControlledLoop(), newDoOverLoop(), newDoWithLoop(), nextDirective(), nextInstruction(), numericNew(), optionsDirective(), parseAddressWith(), parseArgList(), parseCaseWhenList(), parseClassReference(), parseConstantExpression(), parseExpression(), parseLogical(), parseLoopConditional(), parseNew(), parseRedirectOptions(), parseRedirectOutputOptions(), parseSubExpression(), parseVariableOrMessageTerm(), parseVariableReferenceTerm(), procedureNew(), processAnnotation(), processAttributeAnnotations(), processVariableList(), raiseNew(), requiredEndOfClause(), requiresDirective(), resourceDirective(), routineDirective(), selectNew(), signalNew(), signalOnNew(), traceNew(), translateBlock(), useLocalNew(), useNew(), and whenNew().
nextSpecial()
bool LanguageParser::nextSpecial (unsigned int target, SourceLocation & location)
Find the next special character and validate against a target character.
Parameters
target The type of special we expect to find.
location A location object to record the object location against.
Returns
true if we found the special, false otherwise.
Definition at line 175 of file Scanner.cpp.
References CLAUSE_EOF, CLAUSE_EOL, endLocation(), getChar(), locateToken(), and stepPosition().
Referenced by sourceNextToken().
nextToken()
RexxToken* LanguageParser::nextToken () inline
Definition at line 203 of file LanguageParser.hpp.
References clause, and RexxClause::next().
Referenced by addressNew(), callNew(), getToken(), nextInstruction(), parenExpression(), parseArgList(), parseCaseWhenList(), parseConstantExpression(), parseFullSubExpression(), parseLogical(), parseMessageSubterm(), parseMessageTerm(), parseNew(), parseQualifiedSymbol(), parseSubExpression(), parseSubTerm(), qualifiedCallNew(), raiseNew(), and translateConstantExpression().
noClauseAvailable()
bool LanguageParser::noClauseAvailable () inline
Definition at line 201 of file LanguageParser.hpp.
References flags, and noClause.
Referenced by nextDirective(), and translateBlock().
nopNew()
RexxInstruction * LanguageParser::nopNew ()
Create a nop object.
Returns
a NOP instruction object.
Definition at line 2942 of file InstructionParser.cpp.
References Error_Invalid_data_nop, new_instruction, and requiredEndOfClause().
Referenced by nextInstruction().
numericNew()
RexxInstruction * LanguageParser::numericNew ()
Parse a NUMERIC instruction and create a processing instruction object.
Returns
A NUMERIC instruction object.
Definition at line 2959 of file InstructionParser.cpp.
References Error_Invalid_data_form, Error_Invalid_expression_form, Error_Invalid_subkeyword_form, Error_Invalid_subkeyword_numeric, Error_Symbol_expected_numeric, RexxToken::isEndOfClause(), RexxToken::isSymbol(), new_instruction, nextReal(), numeric_digits, numeric_engineering, numeric_form, numeric_form_default, numeric_fuzz, numeric_scientific, OREF_NULL, parseExpression(), previousToken(), requiredEndOfClause(), requiredExpression(), SUBKEY_DIGITS, SUBKEY_ENGINEERING, SUBKEY_FORM, SUBKEY_FUZZ, SUBKEY_SCIENTIFIC, SUBKEY_VALUE, RexxToken::subKeyword(), syntaxError(), TERM_EOC, and type.
Referenced by nextInstruction().
operator delete()
void LanguageParser::operator delete (void *) inline
Definition at line 106 of file LanguageParser.hpp.
operator new()
void * LanguageParser::operator new (size_t size)
Allocate a new LanguageParser item
Parameters
size The base object size.
Returns
The storage for creating a LanguageParser.
Definition at line 464 of file LanguageParser.cpp.
References new_object(), and T_LanguageParser.
optionsDirective()
void LanguageParser::optionsDirective ()
Process a ::OPTIONS directive in a source file.
Definition at line 948 of file DirectiveParser.cpp.
References Numerics::ARGUMENT_DIGITS, PackageClass::disableErrorSyntax(), PackageClass::disableFailureSyntax(), PackageClass::disableLostdigitsSyntax(), PackageClass::disableNostringSyntax(), PackageClass::disableNotreadySyntax(), PackageClass::disableNovalueSyntax(), PackageClass::disableProlog(), PackageClass::enableErrorSyntax(), PackageClass::enableFailureSyntax(), PackageClass::enableLostdigitsSyntax(), PackageClass::enableNostringSyntax(), PackageClass::enableNotreadySyntax(), PackageClass::enableNovalueSyntax(), PackageClass::enableProlog(), Error_Expression_result_digits, Error_Invalid_subkeyword_following, Error_Invalid_subkeyword_form, Error_Invalid_subkeyword_options, Error_Invalid_trace_trace, Error_Invalid_whole_number_digits, Error_Invalid_whole_number_fuzz, Error_Symbol_expected_after_keyword, Error_Symbol_expected_form, Error_Symbol_or_string_digits_value, Error_Symbol_or_string_fuzz_value, Error_Symbol_or_string_trace_value, Numerics::FORM_ENGINEERING, Numerics::FORM_SCIENTIFIC, PackageClass::getDigits(), PackageClass::getFuzz(), RexxToken::isEndOfClause(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), new_string(), nextReal(), package, TraceSetting::parseTraceSetting(), reportException(), RexxInternalObject::requestUnsignedNumber(), PackageClass::setDigits(), PackageClass::setForm(), PackageClass::setFuzz(), PackageClass::setTraceSetting(), RexxToken::subDirective(), SUBDIRECTIVE_ALL, SUBDIRECTIVE_CONDITION, SUBDIRECTIVE_DIGITS, SUBDIRECTIVE_ERROR, SUBDIRECTIVE_FAILURE, SUBDIRECTIVE_FORM, SUBDIRECTIVE_FUZZ, SUBDIRECTIVE_LOSTDIGITS, SUBDIRECTIVE_NOPROLOG, SUBDIRECTIVE_NOSTRING, SUBDIRECTIVE_NOTREADY, SUBDIRECTIVE_NOVALUE, SUBDIRECTIVE_PROLOG, SUBDIRECTIVE_SYNTAX, SUBDIRECTIVE_TRACE, SUBKEY_ENGINEERING, SUBKEY_SCIENTIFIC, RexxToken::subKeyword(), syntaxError(), and RexxToken::value().
Referenced by nextDirective().
optionsNew()
RexxInstruction * LanguageParser::optionsNew ()
Parse and create an instance of the OPTIONS instruction.
Returns
An executable OPTIONS instance.
Definition at line 3068 of file InstructionParser.cpp.
References Error_Invalid_expression_options, new_instruction, requiredExpression(), and TERM_EOC.
Referenced by nextInstruction().
otherwiseNew()
RexxInstruction * LanguageParser::otherwiseNew (RexxToken * token)
Create a new Otherwise instruction object.
Parameters
token The token for the OTHERWISE keyword.
Returns
An executable OTHERWISE instruction object.
Definition at line 3087 of file InstructionParser.cpp.
References new_instruction.
Referenced by nextInstruction().
packBinaryLiteral()
RexxString * LanguageParser::packBinaryLiteral (size_t start, size_t length)
Convert and check a binary constant, packing it down into a string object.
Parameters
start the start of the string data in the current source line.
length The length of the raw string data.
Returns
A Rexx string packed into 8-bit character form.
Definition at line 573 of file Scanner.cpp.
References clause, clauseLocation, current, Error_Invalid_hex_binblank, Error_Invalid_hex_invbin, Error_Invalid_hex_invbin_group, RexxClause::getLocation(), new_integer(), new_string(), RexxString::putChar(), raw_string(), and syntaxError().
Referenced by scanLiteral().
packHexLiteral()
RexxString * LanguageParser::packHexLiteral (size_t start, size_t length)
Convert and check a hex constant, packing it down into a string object.
Parameters
start the start of the string data in the current source line.
length The length of the raw string data.
Returns
A Rexx string packed into 8-bit character form.
Definition at line 419 of file Scanner.cpp.
References clause, clauseLocation, current, Error_Invalid_hex_hexblank, Error_Invalid_hex_invhex, Error_Invalid_hex_invhex_group, RexxClause::getLocation(), new_integer(), new_string(), RexxString::putChar(), raw_string(), and syntaxError().
Referenced by scanLiteral().
parenExpression()
RexxInternalObject * LanguageParser::parenExpression (RexxToken * start)
Evaluate a "parenthetical" expression for REXX instruction values. A parenthetical expression is an expression enclosed in parentheses.
Parameters
start The starting token of the expression. This will be the opening paren and is used for error reporting.
Returns
The parsed expression.
Definition at line 2691 of file LanguageParser.cpp.
References Error_Unmatched_parenthesis_paren, holdObject(), nextToken(), parseSubExpression(), syntaxErrorAt(), and TERM_RIGHT.
Referenced by dynamicCallNew(), and parseNew().
parseAddressWith()
CommandIOConfiguration * LanguageParser::parseAddressWith ()
Complete processing of an ADDRESS instruction that has specified WITH I/O redirection.
Parameters
environment The already parsed environment string
command The expression for the command to issue
Returns
A new instruction object.
Definition at line 671 of file InstructionParser.cpp.
References checkRedirectNormal(), RedirectionType::DEFAULT, Error_Invalid_subkeyword_address_error, Error_Invalid_subkeyword_address_input, Error_Invalid_subkeyword_address_output, Error_Invalid_subkeyword_address_with_option, Error_Symbol_expected_address_with, RexxToken::isEndOfClause(), RexxToken::isSymbol(), nextReal(), RedirectionType::NORMAL, parseRedirectOptions(), parseRedirectOutputOptions(), previousToken(), SUBKEY_ERROR, SUBKEY_INPUT, SUBKEY_OUTPUT, RexxToken::subKeyword(), and syntaxError().
Referenced by addressNew().
parseArgArray()
ArrayClass * LanguageParser::parseArgArray (RexxToken * firstToken, int terminators)
Parse off multiple arguments for a some sort of call, function, or method invocation, returning them as an array.
Parameters
firstToken The first token of the expresssion.
terminators The set of terminators that will end the list.
Returns
An array object holding the argument expressions.
Definition at line 3042 of file LanguageParser.cpp.
References firstToken(), new_array(), parseArgList(), QueueClass::pop(), ArrayClass::put(), and subTerms.
Referenced by forwardNew(), and raiseNew().
parseArgList()
size_t LanguageParser::parseArgList (RexxToken * firstToken, int terminators)
Perform the parsing of a list of arguments where each argument is separated by commas. Each argument expression is pushed on to the term stack in last-to-first order, with omitted arguments represented by OREF_NULL.
Parameters
firstToken The first token of the expression list, which is really the delimiter that opens the list.
terminators The list of terminators for this expression type.
Returns
The count of argument expressions we found. Note that an empty expression following a final "," does not count as a real argument.
Definition at line 3079 of file LanguageParser.cpp.
References Error_Unmatched_parenthesis_paren, Error_Unmatched_parenthesis_square, firstToken(), RexxToken::isComma(), RexxToken::isRightBracket(), RexxToken::isRightParen(), nextReal(), nextToken(), OREF_NULL, parseSubExpression(), QueueClass::pop(), previousToken(), pushSubTerm(), subTerms, syntaxErrorAt(), TERM_RIGHT, and TERM_SQRIGHT.
Referenced by callNew(), dynamicCallNew(), parseArgArray(), parseCollectionMessage(), parseFunction(), parseMessage(), parseQualifiedSymbol(), and qualifiedCallNew().
parseCaseWhenList()
size_t LanguageParser::parseCaseWhenList (int terminators)
Perform the parsing of a list of expressions for a SELECT CASE WHEN expression. This is a list of one or more expressions separated by commas. Omitted expressions are not allowed. Each argument expression is pushed on to the term stack in last-to-first order.
Parameters
firstToken The first token of the expression list, which is really the delimiter that opens the list.
terminators The list of terminators for this expression type.
Returns
The count of argument expressions we found.
Definition at line 3164 of file LanguageParser.cpp.
References Error_Invalid_expression_case_when_list, RexxToken::isComma(), nextReal(), nextToken(), OREF_NULL, parseSubExpression(), previousToken(), pushSubTerm(), and syntaxError().
Referenced by whenNew().
parseClassReference()
ClassResolver * LanguageParser::parseClassReference (RexxErrorCodes error)
Parse a class reference for a ::CLASS directive. This could be a subclass, mixinclass, metaclass, or inherits class name.
Parameters
error The error to raise for nothing there.
Returns
A ClassResolver to look up the class reference.
Definition at line 287 of file DirectiveParser.cpp.
References commonString(), error(), Error_Symbol_expected_namespace_class, RexxToken::isLiteral(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), RexxToken::isType(), name, nextReal(), OREF_NULL, previousToken(), syntaxError(), TOKEN_COLON, RexxToken::upperValue(), and RexxToken::value().
Referenced by classDirective().
parseCollectionMessage()
RexxInternalObject * LanguageParser::parseCollectionMessage (RexxToken * token, RexxInternalObject * target)
Parse a collection message expression term. This is if the form term[args], and follows much the same parsing rules as function calls.
Parameters
token The token that starts the argument list (the square bracket)
target The target for the message term.
terminators Our terminators.
Returns
A message expression object.
Definition at line 3305 of file LanguageParser.cpp.
References holdObject(), OREF_NULL, parseArgList(), subTerms, and TERM_SQRIGHT.
Referenced by parseMessageSubterm(), parseMessageTerm(), and parseSubExpression().
parseConstantExpression()
RexxInternalObject * LanguageParser::parseConstantExpression ()
Parse out a "constant" expression for a Rexx instruction. a constant expression is a literal string, a constant symbol, or an expression enclosed in parentheses. Most new instructions use constant expressions, since they are not terminated by instruction subkeywords, and thus more immune to breakage when new options are added.
Returns
An object that can be used to evaluate this option expression.
Definition at line 2628 of file LanguageParser.cpp.
References addText(), Error_Invalid_expression_general, Error_Unmatched_parenthesis_paren, holdObject(), RexxToken::isConstant(), RexxToken::isEndOfClause(), RexxToken::isLeftParen(), RexxToken::isLiteral(), nextReal(), nextToken(), OREF_NULL, parseFullSubExpression(), previousToken(), syntaxError(), syntaxErrorAt(), and TERM_RIGHT.
Referenced by forwardNew(), parseRedirectOptions(), raiseNew(), and useNew().
parseCountLoop()
RexxInstruction * LanguageParser::parseCountLoop (RexxString * label, RexxVariableBase * countVariable)
Parse a DO count loop. This will be either just DO count (most common), but can also have WHILE or UNTIL modifiers.
Parameters
label The instruction label.
Returns
An instruction of the appropriate type.
Definition at line 1916 of file InstructionParser.cpp.
References WhileUntilLoop::conditional, Error_Interpretation_switch, Error_None, ForLoop::forCount, new_instruction, OREF_NULL, parseExpression(), parseLoopConditional(), pushSubTerm(), reportException(), SUBKEY_NONE, SUBKEY_UNTIL, SUBKEY_WHILE, and TERM_COND.
Referenced by createLoop().
parseExpression()
RexxInternalObject * LanguageParser::parseExpression (int terminators)
Parse off an expression, stopping when one of the possible set of terminator tokens is reached. The terminator token is placed back on the token queue.
Parameters
terminators An int containing the bit flag versions of the terminators.
Returns
An executable expression object.
Definition at line 2720 of file LanguageParser.cpp.
References nextReal(), parseFullSubExpression(), and previousToken().
Referenced by addressNew(), commandNew(), exitNew(), nextInstruction(), numericNew(), parseCountLoop(), parseNew(), pushNew(), queueNew(), replyNew(), requiredExpression(), returnNew(), sayNew(), and traceNew().
parseForeverLoop()
RexxInstruction * LanguageParser::parseForeverLoop (RexxString * label, RexxVariableBase * countVariable)
Parse a DO FOREVER loop. This will be either just DO FOREVER (most common), but can also have WHILE or UNTIL modifiers, which makes them identical to DO WHILE and DO UNTIL.
Parameters
label The instruction label.
countVariable The optional counter variable.
Returns
An instruction of the appropriate type.
Definition at line 1860 of file InstructionParser.cpp.
References WhileUntilLoop::conditional, Error_Interpretation_switch, Error_Invalid_do_forever, newLoopForever(), newLoopUntil(), newLoopWhile(), OREF_NULL, parseLoopConditional(), reportException(), SUBKEY_NONE, SUBKEY_UNTIL, and SUBKEY_WHILE.
Referenced by createLoop().
parseFullSubExpression()
RexxInternalObject * LanguageParser::parseFullSubExpression (int terminators)
Perform the parsing of an expression where the expression can be treated as a comma-separated list of subexpressions. If we have just a simple single subexpression, the return value is the parsed subexpression. If a comma is found as a terminator, then we turn this expression into an operator that will create an array object from the list of expressions. Omitted expressions are allowed and no effort is made to remove trailing null expressions.
Parameters
terminators The list of terminators for this expression type.
Returns
Either a simple expression, or an expression object for creating an array item.
Definition at line 2750 of file LanguageParser.cpp.
References RexxToken::isComma(), nextToken(), parseSubExpression(), popSubTerm(), previousToken(), pushSubTerm(), and subTerms.
Referenced by parseConstantExpression(), parseExpression(), and parseSubTerm().
parseFunction()
RexxInternalObject * LanguageParser::parseFunction (RexxToken * token, RexxToken * name)
Parse off a function call and create an expression object that can process the call.
Parameters
token The token that marks the start of the argument list.
name The function name token.
Returns
A function expression object that can invoke this function.
Definition at line 3222 of file LanguageParser.cpp.
References addReference(), name, parseArgList(), subTerms, and TERM_RIGHT.
Referenced by parseSubTerm().
parseLogical()
RexxInternalObject * LanguageParser::parseLogical (int terminators)
Parse off a "logical list expression", consisting of a list of conditionals separated by commas.
Returns
OREF_NULL if no expressions is found, a single expression element if a single expression is located, and a complex logical expression operator for a list of expressions.
Definition at line 4260 of file LanguageParser.cpp.
References Error_Invalid_expression_logical_list, RexxToken::isComma(), nextReal(), nextToken(), OREF_NULL, parseSubExpression(), QueueClass::pop(), previousToken(), pushSubTerm(), subTerms, and syntaxError().
Referenced by requiredLogicalExpression().
parseLoopConditional()
RexxInternalObject * LanguageParser::parseLoopConditional (InstructionSubKeyword & conditionType, RexxErrorCodes error_message)
Allow for WHILE or UNTIL keywords following some other looping construct. This returns SUBKEY_WHILE or SUBKEY_UNTIL to flag the caller that a conditional has been used.
Parameters
condition_type An option pointer for a place to return the condition type (WHILE or UNTIL)
error_message
Returns
A parsed out expression object.
Definition at line 4582 of file InstructionParser.cpp.
References Error_Invalid_do_whileuntil, Error_Invalid_expression_until, Error_Invalid_expression_while, RexxToken::isEndOfClause(), RexxToken::isSymbol(), nextReal(), OREF_NULL, pushSubTerm(), requiredEndOfClause(), requiredLogicalExpression(), SUBKEY_NONE, SUBKEY_UNTIL, SUBKEY_WHILE, RexxToken::subKeyword(), syntaxError(), and TERM_COND.
Referenced by createLoop(), newControlledLoop(), newDoOverLoop(), newDoWithLoop(), parseCountLoop(), and parseForeverLoop().
parseMessage()
RexxInternalObject * LanguageParser::parseMessage (RexxInternalObject * target, bool doubleTilde, int terminators)
Parse a message send term within an expression.
Parameters
target The target object term for the message send.
doubleTilde Indicates whether this is the "~" or "~~" form of operation.
terminators Expression terminators.
Returns
An object to execute the message send.
Definition at line 3365 of file LanguageParser.cpp.
References addText(), commonString(), Error_Symbol_expected_colon, Error_Symbol_or_string_tilde, getToken(), holdObject(), RexxToken::isLeftParen(), RexxToken::isSymbolOrLiteral(), RexxToken::isType(), RexxToken::isVariableOrDot(), OREF_NULL, parseArgList(), popTerm(), previousToken(), pushTerm(), subTerms, syntaxError(), TERM_RIGHT, TOKEN_COLON, RexxString::upper(), and RexxToken::value().
Referenced by parseMessageSubterm(), parseMessageTerm(), and parseSubExpression().
parseMessageSubterm()
RexxInternalObject * LanguageParser::parseMessageSubterm (int terminators)
Handle a potential message subterm in the context of an expression. This is similar to messageTerm(), but this occurs after we've already determined we need an expression and need an expression term.
Parameters
terminators Terminators for this subexpression context.
Returns
An object to represent this message term. Returns OREF_NULL if no suitable term is found.
Definition at line 3613 of file LanguageParser.cpp.
References Activity::checkStackSpace(), ActivityManager::currentActivity, Error_Invalid_expression_general, Error_Invalid_expression_prefix, RexxToken::isLeftBracket(), RexxToken::isMessageOperator(), RexxToken::isOperator(), RexxToken::isTerminator(), RexxToken::isType(), nextToken(), OPERATOR_BACKSLASH, OPERATOR_GREATERTHAN, OPERATOR_LESSTHAN, OPERATOR_PLUS, OPERATOR_SUBTRACT, OREF_NULL, parseCollectionMessage(), parseMessage(), parseSubTerm(), parseVariableReferenceTerm(), popTerm(), previousToken(), pushTerm(), RexxToken::subtype(), syntaxError(), TERM_EOC, and TOKEN_DTILDE.
Referenced by parseSubExpression().
parseMessageTerm()
RexxInternalObject * LanguageParser::parseMessageTerm ()
Parse off an instruction leading message term element. This is an important step, as it is used to determine what sort of instruction we have. If the instruction starts with a message term, then this is a messaging instruction. Part of the instruction type determination at the beginning of each clause.
Returns
The message term execution element.
Definition at line 3496 of file LanguageParser.cpp.
References RexxToken::isLeftBracket(), RexxToken::isLeftParen(), RexxToken::isMessageOperator(), RexxToken::isSimpleVariable(), RexxToken::isTerminator(), RexxToken::isType(), markPosition(), nextToken(), OREF_NULL, parseCollectionMessage(), parseMessage(), parseSubTerm(), popTerm(), previousToken(), pushTerm(), resetPosition(), TERM_EOC, and TOKEN_DTILDE.
Referenced by nextInstruction(), and parseVariableOrMessageTerm().
parseNew()
RexxInstruction * LanguageParser::parseNew (InstructionSubKeyword argPull)
Parse a PARSE instruction.
Parameters
argPull Indicates if this is an ARG or PULL operation.
Returns
An executable instruction object.
Definition at line 3102 of file InstructionParser.cpp.
References addText(), addVariable(), Error_Invalid_expression_parse, Error_Invalid_subkeyword_parse, Error_Invalid_template_missing, Error_Invalid_template_position, Error_Invalid_template_trigger, Error_Invalid_template_with, Error_Symbol_expected_parse, Error_Symbol_expected_var, Error_Variable_expected_PARSE, RexxToken::isComma(), RexxToken::isDot(), RexxToken::isEndOfClause(), RexxToken::isLeftParen(), RexxToken::isLiteral(), ProtectedObject::isNull(), RexxToken::isNumericSymbol(), RexxToken::isOperator(), RexxToken::isSymbol(), RexxToken::isVariable(), new_variable_instruction, nextReal(), nextToken(), OPERATOR_EQUAL, OPERATOR_GREATERTHAN, OPERATOR_LESSTHAN, OPERATOR_PLUS, OPERATOR_SUBTRACT, OREF_NULL, parenExpression(), parse_caseless, parse_lower, parse_upper, parseExpression(), RexxToken::parseOption(), parseVariableOrMessageTerm(), previousToken(), QueueClass::push(), SUBKEY_ARG, SUBKEY_CASELESS, SUBKEY_LINEIN, SUBKEY_LOWER, SUBKEY_NONE, SUBKEY_PULL, SUBKEY_SOURCE, SUBKEY_UPPER, SUBKEY_VALUE, SUBKEY_VAR, SUBKEY_VERSION, SUBKEY_WITH, RexxToken::subKeyword(), subTerms, RexxToken::subtype(), syntaxError(), TERM_KEYWORD, TERM_WITH, terms, TRIGGER_ABSOLUTE, TRIGGER_END, TRIGGER_MINUS, TRIGGER_MINUS_LENGTH, TRIGGER_MIXED, TRIGGER_NONE, TRIGGER_PLUS, TRIGGER_PLUS_LENGTH, and TRIGGER_STRING.
Referenced by nextInstruction().
parseQualifiedSymbol()
RexxInternalObject * LanguageParser::parseQualifiedSymbol (RexxString * namespaceName)
Parse off a qualified symbol. This can either be a class lookup or a qualified function call. the call.
Parameters
n
Returns
An expression object that can process this qualified lookup type.
Definition at line 3257 of file LanguageParser.cpp.
References Error_Symbol_expected_qualified_symbol, RexxToken::isLeftParen(), RexxToken::isSymbol(), nextToken(), parseArgList(), previousToken(), subTerms, syntaxError(), TERM_RIGHT, and RexxToken::value().
Referenced by parseSubTerm().
parseRedirectOptions()
void LanguageParser::parseRedirectOptions (RexxInternalObject *& source, RedirectionType::Enum & type)
Parse the different redirection options on ADDRESS WITH
Parameters
ioType The type of I/O stream we're redirecting
source A reference to the field for the evaluated target
type The type of redirection to apply
Definition at line 834 of file InstructionParser.cpp.
References addText(), Error_Invalid_expression_missing_general, Error_Invalid_subkeyword_address_with_io_option, Error_Symbol_expected_after_stem_keyword, RexxToken::isStem(), RexxToken::isSymbol(), nextReal(), OREF_NULL, parseConstantExpression(), source, RedirectionType::STEM_VARIABLE, RedirectionType::STREAM_NAME, SUBKEY_STEM, SUBKEY_STREAM, SUBKEY_USING, RexxToken::subKeyword(), syntaxError(), type, and RedirectionType::USING_OBJECT.
Referenced by parseAddressWith().
parseRedirectOutputOptions()
OutputOption::Enum LanguageParser::parseRedirectOutputOptions ()
Check for potential APPEND/REPLACE options on an ADDRESS WITH OUTPUT or ERROR keyword.
Returns
The output option (including DEFAULT_REPLACE if nothing was specified)
Definition at line 795 of file InstructionParser.cpp.
References OutputOption::APPEND, OutputOption::DEFAULT, RexxToken::isSymbol(), nextReal(), previousToken(), OutputOption::REPLACE, SUBKEY_APPEND, SUBKEY_REPLACE, and RexxToken::subKeyword().
Referenced by parseAddressWith().
parseSubExpression()
RexxInternalObject * LanguageParser::parseSubExpression (int terminators)
Parse off a sub- expression, stopping when one of the possible set of terminator tokens is reached. The terminator token is placed back on the token queue. This is generally called in the context of parsing different bits of an expression and is frequently called recursively. Note that this subexpression parse will always terminate on a comma...the calling context will then determine how that comma is processed.
Parameters
terminators an int containing flags that indicate what terminators should be used to stop parsing this subexpression.
Returns
Definition at line 2811 of file LanguageParser.cpp.
References Error_Invalid_expression_general, Error_Unexpected_comma_bracket, Error_Unexpected_comma_paren, SourceLocation::getLineNumber(), RexxToken::getLocation(), SourceLocation::getOffset(), RexxToken::isSubtype(), RexxToken::isTerminator(), RexxToken::isType(), nextReal(), nextToken(), OPERATOR_ABUTTAL, OPERATOR_BACKSLASH, OPERATOR_BLANK, OREF_NULL, parseCollectionMessage(), parseMessage(), parseMessageSubterm(), popOperator(), popTerm(), RexxToken::precedence(), previousToken(), pushOperator(), pushTerm(), requiredTerm(), SourceLocation::setEnd(), RexxToken::subtype(), syntaxError(), TheNilObject, TOKEN_ASSIGNMENT, TOKEN_BLANK, TOKEN_DTILDE, TOKEN_LEFT, TOKEN_LITERAL, TOKEN_OPERATOR, TOKEN_RIGHT, TOKEN_SQLEFT, TOKEN_SQRIGHT, TOKEN_SYMBOL, TOKEN_TILDE, topOperator(), and RexxToken::type().
Referenced by parenExpression(), parseArgList(), parseCaseWhenList(), parseFullSubExpression(), and parseLogical().
parseSubTerm()
RexxInternalObject * LanguageParser::parseSubTerm (int terminators)
Parse off a subterm of an expression, from simple ones like variable names and literals, to more complex such as message sends.
Parameters
terminators The expression terminator context.
Returns
An executable object for the message term.
Definition at line 3753 of file LanguageParser.cpp.
References addText(), Activity::checkStackSpace(), ActivityManager::currentActivity, Error_Invalid_expression_general, Error_Unexpected_comma_bracket, Error_Unexpected_comma_comma, Error_Unexpected_comma_paren, Error_Unmatched_parenthesis_paren, RexxToken::isLeftParen(), RexxToken::isTerminator(), RexxToken::isType(), nextToken(), OPERATOR_BACKSLASH, OPERATOR_GREATERTHAN, OPERATOR_LESSTHAN, OPERATOR_PLUS, OPERATOR_SUBTRACT, OREF_NULL, parseFullSubExpression(), parseFunction(), parseQualifiedSymbol(), parseVariableReferenceTerm(), previousToken(), RexxToken::subtype(), syntaxError(), syntaxErrorAt(), TERM_RIGHT, TOKEN_COLON, TOKEN_COMMA, TOKEN_LEFT, TOKEN_LITERAL, TOKEN_OPERATOR, TOKEN_RIGHT, TOKEN_SQRIGHT, TOKEN_SYMBOL, RexxToken::type(), and RexxToken::value().
Referenced by parseMessageSubterm(), and parseMessageTerm().
parseVariableOrMessageTerm()
RexxInternalObject * LanguageParser::parseVariableOrMessageTerm ()
Parse off a single variable symbol or a message term that can be used for an assignment.
NOTE: If this is a message term, then the message term will be configured as an assignment term.
Returns
The object for an assignment target, or OREF_NULL if something other than a variable or a message term was found. On return, the clause position pointer will either be unchanged or positioned at the next token of the clause.
Definition at line 3457 of file LanguageParser.cpp.
References addText(), RexxToken::isSymbol(), needVariable(), nextReal(), OREF_NULL, parseMessageTerm(), and previousToken().
Referenced by parseNew(), and useNew().
parseVariableReferenceTerm()
RexxInternalObject * LanguageParser::parseVariableReferenceTerm ()
Parse off a variable reference term.
Returns
A variable reference term object
Definition at line 3719 of file LanguageParser.cpp.
References addSimpleVariable(), addStem(), Error_Symbol_expected_after_prefix_reference, RexxToken::isNonCompoundVariable(), RexxToken::isSimpleVariable(), RexxToken::isSymbol(), nextReal(), OREF_NULL, syntaxError(), and RexxToken::value().
Referenced by parseMessageSubterm(), and parseSubTerm().
popDo()
RexxInstruction* LanguageParser::popDo () inline
Definition at line 307 of file LanguageParser.hpp.
References control, and QueueClass::pull().
Referenced by flushControl(), and translateBlock().
popNTerms()
RexxInternalObject * LanguageParser::popNTerms (size_t count)
Pop multiple items off of the term stack.
Parameters
count The count of items to pop.
Returns
The last object popped.
Definition at line 3999 of file LanguageParser.cpp.
References currentStack, holdObject(), OREF_NULL, QueueClass::pop(), and terms.
popOperator()
RexxToken* LanguageParser::popOperator () inline
Definition at line 376 of file LanguageParser.hpp.
References operators, and QueueClass::pull().
Referenced by parseSubExpression().
popSubTerm()
RexxInternalObject * LanguageParser::popSubTerm ()
Pop a term off of the expression sub term stack.
Returns
The popped object.
Definition at line 3954 of file LanguageParser.cpp.
References currentStack, holdObject(), QueueClass::pop(), and subTerms.
Referenced by parseFullSubExpression().
popTerm()
RexxInternalObject * LanguageParser::popTerm ()
Pop a term off of the expression stack.
Returns
The popped object.
Definition at line 3916 of file LanguageParser.cpp.
References currentStack, holdObject(), QueueClass::pop(), and terms.
Referenced by parseMessage(), parseMessageSubterm(), parseMessageTerm(), and parseSubExpression().
position()
void LanguageParser::position (size_t line, size_t offset)
Move the current scan position to a new source location.
Parameters
line The target line number.
offset The offset within the new line.
Definition at line 986 of file LanguageParser.cpp.
References current, currentLength, ProgramSource::getLine(), line, lineNumber, lineOffset, and source.
Referenced by initializeForParsing(), locateToken(), and nextLine().
previousToken()
void LanguageParser::previousToken () inline
Definition at line 171 of file LanguageParser.hpp.
References clause, and RexxClause::previous().
Referenced by addressNew(), callNew(), classDirective(), constantDirective(), createLoop(), getToken(), ifNew(), newControlledLoop(), newDoOverLoop(), newDoWithLoop(), nextInstruction(), numericNew(), parseAddressWith(), parseArgList(), parseCaseWhenList(), parseClassReference(), parseConstantExpression(), parseExpression(), parseFullSubExpression(), parseLogical(), parseMessage(), parseMessageSubterm(), parseMessageTerm(), parseNew(), parseQualifiedSymbol(), parseRedirectOutputOptions(), parseSubExpression(), parseSubTerm(), parseVariableOrMessageTerm(), requiredEndOfClause(), signalNew(), traceNew(), translateBlock(), useNew(), and whenNew().
procedureNew()
RexxInstruction * LanguageParser::procedureNew ()
Parse a PROCEDURE instruction.
Returns
An executable instruction object.
Definition at line 3447 of file InstructionParser.cpp.
References Error_Invalid_subkeyword_procedure, RexxToken::isEndOfClause(), KEYWORD_PROCEDURE, new_variable_instruction, nextReal(), processVariableList(), SUBKEY_EXPOSE, RexxToken::subKeyword(), subTerms, and syntaxError().
Referenced by nextInstruction().
processAnnotation()
void LanguageParser::processAnnotation (RexxToken * token, StringTable * table)
Parse off a single name/value pair on a package attribute.
Parameters
token The current token, which should be the name of an annotation.
table The target annotation table.
Definition at line 2160 of file DirectiveParser.cpp.
References RexxString::concat(), Error_Symbol_expected_annotation_attribute, Error_Symbol_or_string_package_attribute_bad_value, Error_Symbol_or_string_package_attribute_missing, RexxToken::isEndOfClause(), RexxToken::isOperator(), RexxToken::isSubtype(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), name, nextReal(), OPERATOR_PLUS, OPERATOR_SUBTRACT, OREF_NULL, HashCollection::put(), SYMBOL_CONSTANT, syntaxError(), and RexxToken::value().
Referenced by annotateDirective(), and processAttributeAnnotations().
processAttributeAnnotations()
void LanguageParser::processAttributeAnnotations (RexxString * getterName)
Process potential attribute annotations. This will annotate both methods of an annotate pair (or the ones that actually exist). At least one of the annotation methods must exist. Both methods must be at the same scope (i.e., class or instance). Instance methods are checked first, then class methods.
Parameters
getterName The name of the attribute.
Definition at line 2082 of file DirectiveParser.cpp.
References commonString(), RexxString::concatWithCstring(), Error_Translation_missing_annotation_target, findClassMethod(), findInstanceMethod(), BaseExecutable::getAnnotations(), MethodClass::isAttribute(), RexxToken::isEndOfClause(), new_string_table(), nextReal(), OREF_NULL, processAnnotation(), and syntaxError().
Referenced by annotateDirective().
processInstore()
RoutineClass * LanguageParser::processInstore (PRXSTRING instore, RexxString * name) static
Process handling of instore execution arguments.
Parameters
instore The instore descriptor.
name The name of the program.
Returns
An executable top-level program object (a routine, actually)
Definition at line 4327 of file LanguageParser.cpp.
References createProgram(), RexxString::getStringData(), Protected< objType >::isNull(), name, new_buffer(), OREF_NULL, RoutineClass::restore(), restoreFromMacroSpace(), and RexxQueryMacro().
Referenced by RexxStartDispatcher::run(), TranslateDispatcher::run(), and TranslateInstoreDispatcher::run().
processVariableList()
size_t LanguageParser::processVariableList (InstructionKeyword type)
Process a list of variables for PROCEDURE, DROP, and EXPOSE.
Parameters
type The type of instruction we're parsing for.
Returns
The count of variables. The variable retrievers are pushed onto the subTerm stack.
Definition at line 4469 of file InstructionParser.cpp.
References addText(), addVariable(), Error_Invalid_variable_number, Error_Invalid_variable_period, Error_Symbol_expected_drop, Error_Symbol_expected_expose, Error_Symbol_expected_varref, Error_Variable_reference_extra, Error_Variable_reference_missing, expose(), RexxToken::isEndOfClause(), RexxToken::isLeftParen(), RexxToken::isRightParen(), RexxToken::isSubtype(), RexxToken::isSymbol(), KEYWORD_DROP, KEYWORD_EXPOSE, nextReal(), pushSubTerm(), QueueClass::queue(), subTerms, SYMBOL_CONSTANT, SYMBOL_DOTSYMBOL, SYMBOL_DUMMY, syntaxError(), type, and RexxToken::value().
Referenced by dropNew(), exposeNew(), and procedureNew().
pushDo()
void LanguageParser::pushDo (RexxInstruction * i) inline
Definition at line 306 of file LanguageParser.hpp.
References control, and QueueClass::push().
Referenced by flushControl(), and translateBlock().
pushNew()
RexxInstruction * LanguageParser::pushNew ()
Create an instance of the PUSH instruction.
Returns
An executable instruction object.
Definition at line 3493 of file InstructionParser.cpp.
References new_instruction, parseExpression(), and TERM_EOC.
Referenced by nextInstruction().
pushOperator()
void LanguageParser::pushOperator (RexxToken * operatorToken) inline
Definition at line 375 of file LanguageParser.hpp.
References operators, and QueueClass::push().
Referenced by parseSubExpression().
pushSubTerm()
void LanguageParser::pushSubTerm (RexxInternalObject * term)
Push a term on to the expression sub term stack. The subterms normally contribute to the total required stack size, so make sure we account for these when calculating the total required stack size. Only use this method of pushing the term when the max stack size is affected.
Parameters
term The term object.
Definition at line 3937 of file LanguageParser.cpp.
References currentStack, maxStack, QueueClass::push(), and subTerms.
Referenced by forwardNew(), ifNew(), newControlledLoop(), newDoOverLoop(), newDoWithLoop(), parseArgList(), parseCaseWhenList(), parseCountLoop(), parseFullSubExpression(), parseLogical(), parseLoopConditional(), processVariableList(), raiseNew(), useLocalNew(), and whenNew().
pushTerm()
void LanguageParser::pushTerm (RexxInternalObject * term)
Push a term on to the expression term stack.
Parameters
term The term object.
Definition at line 3899 of file LanguageParser.cpp.
References currentStack, maxStack, QueueClass::push(), and terms.
Referenced by parseMessage(), parseMessageSubterm(), parseMessageTerm(), and parseSubExpression().
qualifiedCallNew()
RexxInstruction * LanguageParser::qualifiedCallNew (RexxToken * token)
Process a call of the form CALL namespace:name, which is restricted to public routines in the named namespace.
Parameters
token The first token of the expression (with the opening paren of the name expression.)
Returns
A new object for executing this call.
Definition at line 1112 of file InstructionParser.cpp.
References Error_Symbol_expected_qualified_call, RexxToken::isSymbol(), new_variable_instruction, nextToken(), OREF_NULL, parseArgList(), subTerms, syntaxError(), TERM_EOC, and RexxToken::value().
Referenced by callNew().
queueNew()
RexxInstruction * LanguageParser::queueNew ()
Create an instance of the QUEUE instruction.
Returns
An executable instruction object.
Definition at line 3476 of file InstructionParser.cpp.
References new_instruction, parseExpression(), and TERM_EOC.
Referenced by nextInstruction().
raiseNew()
RexxInstruction * LanguageParser::raiseNew ()
Parse a RAISE instruction and return a new executable object.
Returns
An instructon object that can execute this RAISE instruction.
Definition at line 3512 of file InstructionParser.cpp.
References commonString(), RexxString::concatToCstring(), RexxToken::condition(), CONDITION_ERROR, CONDITION_FAILURE, CONDITION_HALT, CONDITION_LOSTDIGITS, CONDITION_NOMETHOD, CONDITION_NOSTRING, CONDITION_NOTREADY, CONDITION_NOVALUE, CONDITION_PROPAGATE, CONDITION_SYNTAX, CONDITION_USER, Error_Invalid_expression_general, Error_Invalid_expression_raise_additional, Error_Invalid_expression_raise_description, Error_Invalid_expression_raise_list, Error_Invalid_subkeyword_additional, Error_Invalid_subkeyword_description, Error_Invalid_subkeyword_raise, Error_Invalid_subkeyword_raiseoption, Error_Invalid_subkeyword_result, Error_Symbol_expected_raise, Error_Symbol_expected_user, flags, RexxToken::isEndOfClause(), RexxToken::isLeftParen(), RexxToken::isSymbol(), new_instruction, new_variable_instruction, nextReal(), nextToken(), OREF_NULL, parseArgArray(), parseConstantExpression(), pushSubTerm(), raise_array, raise_exit, raise_propagate, raise_return, raise_syntax, ArrayClass::size(), SUBKEY_ADDITIONAL, SUBKEY_ARRAY, SUBKEY_DESCRIPTION, SUBKEY_EXIT, SUBKEY_RETURN, RexxToken::subKeyword(), syntaxError(), TERM_RIGHT, and RexxToken::value().
Referenced by nextInstruction().
reclaimClause()
void LanguageParser::reclaimClause () inline
Definition at line 196 of file LanguageParser.hpp.
References flags, and reclaimed.
Referenced by checkDirective(), hasBody(), and nextInstruction().
replyNew()
RexxInstruction * LanguageParser::replyNew ()
Create an instance of the REPLY instruction.
Returns
An executable instruction instance.
Definition at line 3752 of file InstructionParser.cpp.
References Error_Translation_reply_interpret, isInterpret(), new_instruction, parseExpression(), syntaxError(), and TERM_EOC.
Referenced by nextInstruction().
requiredEndOfClause()
void LanguageParser::requiredEndOfClause (RexxErrorCodes error) inline
Definition at line 205 of file LanguageParser.hpp.
References error(), RexxToken::isEndOfClause(), nextReal(), previousToken(), and syntaxError().
Referenced by callOnNew(), constantDirective(), endNew(), leaveNew(), nopNew(), numericNew(), parseLoopConditional(), resourceDirective(), signalNew(), signalOnNew(), and traceNew().
requiredExpression()
RexxInternalObject* LanguageParser::requiredExpression (int terminators, RexxErrorCodes error) inline
Definition at line 228 of file LanguageParser.hpp.
References error(), OREF_NULL, parseExpression(), and syntaxError().
Referenced by addressNew(), assignmentNew(), assignmentOpNew(), dynamicSignalNew(), interpretNew(), newControlledLoop(), newDoOverLoop(), newDoWithLoop(), numericNew(), optionsNew(), selectNew(), traceNew(), and translateConstantExpression().
requiredLogicalExpression()
RexxInternalObject* LanguageParser::requiredLogicalExpression (int terminators, RexxErrorCodes error) inline
Definition at line 218 of file LanguageParser.hpp.
References error(), OREF_NULL, parseLogical(), and syntaxError().
Referenced by guardNew(), ifNew(), parseLoopConditional(), and whenNew().
requiredTerm()
RexxInternalObject * LanguageParser::requiredTerm (RexxToken * token, RexxErrorCodes errorCode = Error_Invalid_expression_general)
Pop a term item off of the execution stack. Will raise an error if this is not there.
Parameters
token The token giving the context location. Used to identify the error position.
errorCode The error code. The default is the generic syntax error.
Returns
The object popped off of the stack.
Definition at line 3976 of file LanguageParser.cpp.
References currentStack, holdObject(), OREF_NULL, QueueClass::pop(), syntaxError(), and terms.
Referenced by parseSubExpression().
requiredVariable()
RexxVariableBase * LanguageParser::requiredVariable (RexxToken * token, const char * keyword)
Handle adding a variable to a program. This verifies that the token is a valid variable, then creates a retriever that can be used in an expression to obtain the variable value.
Parameters
token The token holding the variable name.
Returns
A retriever object that can be used as an expression term.
Definition at line 2309 of file LanguageParser.cpp.
References addVariable(), Error_Symbol_expected_after_keyword, RexxToken::isSymbol(), new_string(), and syntaxError().
Referenced by newDoWithLoop().
requireLanguageLevel()
void LanguageParser::requireLanguageLevel (LanguageLevel l)
Mark the package that it requires at least the given language level to execute.
Parameters
l The new language level.
Definition at line 804 of file LanguageParser.cpp.
References PackageClass::getLanguageLevel(), package, and PackageClass::setLanguageLevel().
requiresDirective()
void LanguageParser::requiresDirective ()
Process a ::REQUIRES directive.
Definition at line 2730 of file DirectiveParser.cpp.
References ArrayClass::append(), clause, Error_Invalid_subkeyword_requires, Error_Symbol_expected_namespace, Error_Symbol_or_string_requires, Error_Translation_reserved_namespace, RexxToken::isEndOfClause(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), libraries, name, nextReal(), OREF_NULL, requires, RexxString::strCompare(), RexxToken::subDirective(), SUBDIRECTIVE_LIBRARY, SUBDIRECTIVE_NAMESPACE, syntaxError(), and RexxToken::value().
Referenced by nextDirective().
resetPosition()
void LanguageParser::resetPosition (size_t p) inline
Definition at line 175 of file LanguageParser.hpp.
References clause, and RexxClause::reset().
Referenced by createLoop(), parseMessageTerm(), and translateBlock().
resolveCalls()
void LanguageParser::resolveCalls ()
Attempt to resolve and deferred function or call instructions.
Definition at line 1686 of file LanguageParser.cpp.
References calls, ArrayClass::get(), isOfClass, ArrayClass::items(), and labels.
Referenced by translateBlock(), and translateConstantExpression().
resolveDependencies()
void LanguageParser::resolveDependencies ()
Resolve dependencies between ::CLASS directives, rearranging the order of the directives to preserve relative ordering wherever possible. Classes with no dependencies in this source file will be done first, followed by those with dependencies in the appropriate order
Definition at line 1797 of file LanguageParser.cpp.
References ClassDirective::addDependencies(), ArrayClass::append(), classDependencies, PackageClass::classes, classes, clauseLocation, ArrayClass::deleteItem(), ClassDirective::dependenciesResolved(), Error_Execution_cyclic, ArrayClass::get(), RexxInstruction::getLocation(), ClassDirective::getName(), ArrayClass::isEmpty(), HashCollection::isEmpty(), ArrayClass::items(), PackageClass::libraries, libraries, name, new_array(), OREF_NULL, package, PackageClass::publicRoutines, publicRoutines, ClassDirective::removeDependency(), PackageClass::requires, requires, PackageClass::resources, resources, PackageClass::routines, routines, PackageClass::setNeedsInstallation(), syntaxError(), PackageClass::unattachedMethods, and unattachedMethods.
Referenced by translate().
resourceDirective()
void LanguageParser::resourceDirective ()
Process a ::RESOURCE directive in a source file.
Definition at line 2217 of file DirectiveParser.cpp.
References checkMarker(), commonString(), conditionalNextLine(), Error_Invalid_data_resource_dir, Error_Invalid_subkeyword_resource, Error_Symbol_or_string_resource, Error_Symbol_or_string_resource_end, Error_Translation_duplicate_resource, Error_Translation_missing_resource_end, getStringLine(), HashCollection::hasIndex(), RexxToken::isEndOfClause(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), moreLines(), name, new_array(), nextLine(), nextReal(), HashCollection::put(), requiredEndOfClause(), resources, RexxToken::subDirective(), SUBDIRECTIVE_END, syntaxError(), RexxString::upper(), and RexxToken::value().
Referenced by nextDirective().
restoreFromMacroSpace()
RoutineClass * LanguageParser::restoreFromMacroSpace (RexxString * name) static
Create a routine from a macrospace source.
Parameters
name The name of the macrospace item.
Returns
The inflatted macrospace routine.
Definition at line 4381 of file LanguageParser.cpp.
References RexxString::getStringData(), MAKERXSTRING, name, SystemInterpreter::releaseResultMemory(), RoutineClass::restore(), RexxResolveMacroFunction(), and _RXSTRING::strptr.
Referenced by processInstore().
returnNew()
RexxInstruction * LanguageParser::returnNew ()
Parse and create a RETURN instruction.
Returns
An instance of the RETURN instruction.
Definition at line 3775 of file InstructionParser.cpp.
References new_instruction, parseExpression(), and TERM_EOC.
Referenced by nextInstruction().
routineDirective()
void LanguageParser::routineDirective ()
Process a ::routine directive in a source file.
Definition at line 2516 of file DirectiveParser.cpp.
References checkDirective(), DEFAULT_ACCESS_SCOPE, Error_External_name_not_found_routine, Error_Invalid_subkeyword_class, Error_Invalid_subkeyword_routine, Error_Symbol_or_string_external, Error_Symbol_or_string_routine, Error_Translation_bad_external, Error_Translation_duplicate_routine, Error_Translation_external_routine, isDuplicateRoutine(), RexxToken::isEndOfClause(), RexxToken::isLiteral(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), name, nextReal(), OREF_NULL, package, PRIVATE_SCOPE, PUBLIC_SCOPE, publicRoutines, PackageManager::resolveRoutine(), routines, StringHashCollection::setEntry(), BaseExecutable::setPackageObject(), RexxToken::subDirective(), SUBDIRECTIVE_EXTERNAL, SUBDIRECTIVE_PRIVATE, SUBDIRECTIVE_PUBLIC, syntaxError(), translateBlock(), RexxToken::value(), and words().
Referenced by nextDirective().
sayNew()
RexxInstruction * LanguageParser::sayNew ()
Parse and create a SAY instruction.
Returns
An executable instance of the SAY instruction.
Definition at line 3792 of file InstructionParser.cpp.
References new_instruction, parseExpression(), and TERM_EOC.
Referenced by nextInstruction().
scanComment()
void LanguageParser::scanComment ()
Scan over a Rexx comment, including checking for comment nesting.
Definition at line 202 of file Scanner.cpp.
References clause, clauseLocation, Error_Unmatched_quote_comment, getChar(), RexxClause::getLocation(), lineNumber, lineOffset, moreChars(), moreLines(), new_integer(), nextChar(), nextLine(), RexxClause::setEnd(), stepPosition(), and syntaxError().
Referenced by locateToken().
scanLiteral()
RexxToken * LanguageParser::scanLiteral ()
Scan off a literal string (including hex or binary literals), and return as a literal token.
Returns
A token representing the literal.
Definition at line 1579 of file Scanner.cpp.
References clause, clauseLocation, commonString(), current, endLocation(), Error_Unmatched_quote_double, Error_Unmatched_quote_single, getChar(), RexxClause::getLocation(), getNextChar(), isSymbolCharacter(), lineNumber, lineOffset, LITERAL_BIN, LITERAL_HEX, LITERAL_STRING, moreChars(), new_string(), RexxClause::newToken(), packBinaryLiteral(), packHexLiteral(), RexxString::putChar(), raw_string(), RexxClause::setEnd(), startLocation(), stepPosition(), syntaxError(), TOKEN_LITERAL, and type.
Referenced by sourceNextToken().
scanSymbol() [1/2]
RexxToken * LanguageParser::scanSymbol ()
Scan a symbol from the source and return a token identifying the type of symbol (constant, dot, variable, etc.).
Returns
A token object describing the symbol.
Definition at line 1207 of file Scanner.cpp.
References clause, clauseLocation, commonString(), endLocation(), Error_Name_too_long_name, EXP_DIGIT, EXP_E, EXP_EDIGIT, EXP_ESIGN, EXP_EXCLUDED, EXP_POINT, EXP_SPOINT, EXP_START, getChar(), RexxString::getChar(), RexxClause::getLocation(), haveNextChar(), INTEGER_CONSTANT, lineNumber, lineOffset, MAX_SYMBOL_LENGTH, moreChars(), RexxClause::newToken(), RexxString::putChar(), raw_string(), Numerics::REXXINTEGER_DIGITS, RexxClause::setEnd(), RexxToken::setNumeric(), RexxString::setUpperOnly(), startLocation(), stepPosition(), SUBTYPE_NONE, SYMBOL_COMPOUND, SYMBOL_CONSTANT, SYMBOL_DOTSYMBOL, SYMBOL_DUMMY, SYMBOL_STEM, SYMBOL_VARIABLE, syntaxError(), TOKEN_SYMBOL, and translateChar().
Referenced by RexxString::isSymbol(), and sourceNextToken().
scanSymbol() [2/2]
StringSymbolType LanguageParser::scanSymbol (RexxString * string) static
Scans a string for symbol validity and returns a type indicator as to what type of symbol.
Parameters
string The string to scan.
Returns
A type indicator indicating what sort of symbol we're looking at.
Definition at line 1760 of file Scanner.cpp.
References RexxString::getChar(), Utilities::isDigit(), isSymbolCharacter(), MAX_SYMBOL_LENGTH, STRING_BAD_VARIABLE, STRING_COMPOUND_NAME, STRING_LITERAL, STRING_LITERAL_DOT, STRING_NAME, STRING_NUMERIC, STRING_STEM, and Utilities::toUpper().
selectNew()
RexxInstruction * LanguageParser::selectNew ()
Parse and create a suitable SELECT instruction object. This has different objects for standard SELECT and SELECT CASE instructions.
Returns
An executable SELECT instruction object.
Definition at line 3811 of file InstructionParser.cpp.
References Error_Invalid_expression_select_case, Error_Invalid_subkeyword_select, Error_Symbol_expected_LABEL, RexxToken::isEndOfClause(), RexxToken::isSymbol(), new_instruction, nextReal(), OREF_NULL, requiredExpression(), SUBKEY_CASE, SUBKEY_LABEL, RexxToken::subKeyword(), syntaxError(), TERM_EOC, and RexxToken::value().
Referenced by nextInstruction().
setGuard()
void LanguageParser::setGuard ()
We're about to process a WHEN expression on a GUARD instruction, so we need to turn on variable capture so we know what exposed variables are referenced in the expression.
Definition at line 2591 of file LanguageParser.cpp.
References guardVariables, new_identity_table(), and OREF_NULL.
Referenced by guardNew().
setInterpret()
void LanguageParser::setInterpret () inline
Definition at line 199 of file LanguageParser.hpp.
References flags, interpret, and noDirectives.
Referenced by translateInterpret().
setLocation()
void LanguageParser::setLocation (SourceLocation & location)
Save the current scanning location for a single character..
Parameters
location A location object to store this in.
Definition at line 159 of file Scanner.cpp.
References lineNumber, lineOffset, and SourceLocation::setLocation().
signalNew()
RexxInstruction * LanguageParser::signalNew ()
Finish parsing a SIGNAL instruction and return an appropriate instruction object. The SIGNAL instruction performs several distinct functions, so there are 3 separate instruction objects tailored to thos functions.
Returns
An instruction object for processing a SIGNAL.
Definition at line 4035 of file InstructionParser.cpp.
References addReference(), dynamicSignalNew(), Error_Invalid_data_signal, Error_Symbol_or_string_signal, RexxToken::isEndOfClause(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), new_instruction, nextReal(), OREF_NULL, previousToken(), requiredEndOfClause(), signalOnNew(), SUBKEY_OFF, SUBKEY_ON, SUBKEY_VALUE, RexxToken::subKeyword(), syntaxError(), and RexxToken::value().
Referenced by nextInstruction().
signalOnNew()
RexxInstruction * LanguageParser::signalOnNew (InstructionSubKeyword type)
Complete parsing of a SIGNAL ON or SIGNAL OFF instruction. This also has a separate instruction object for executing this function.
Parameters
type The keyword type of the ON or OFF function.
Returns
A new instruction object.
Definition at line 3925 of file InstructionParser.cpp.
References addReference(), commonString(), RexxString::concatToCstring(), RexxToken::condition(), CONDITION_NONE, CONDITION_PROPAGATE, CONDITION_USER, Error_Invalid_data_condition, Error_Invalid_data_name, Error_Invalid_subkeyword_signaloff, Error_Invalid_subkeyword_signalon, Error_Invalid_subkeyword_signalonname, Error_Symbol_expected_off, Error_Symbol_expected_on, Error_Symbol_expected_user, Error_Symbol_or_string_name, RexxToken::isEndOfClause(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), new_instruction, nextReal(), OREF_NULL, requiredEndOfClause(), SUBKEY_NAME, SUBKEY_ON, RexxToken::subKeyword(), syntaxError(), type, and RexxToken::value().
Referenced by signalNew().
sourceNewObject() [1/2]
RexxInstruction * LanguageParser::sourceNewObject (size_t size, RexxBehaviour * _behaviour, InstructionKeyword type)
Create a "raw" executable instruction object. Allocation/creation of instruction objects are handled a little differently, and goes in stages: 1) Have RexxMemory allocate a Rexx object of the appropriate size. 2) Set the object behaviour to be the table for the target instruction. 3) Call the in-memory new() method on this object using the RexxInstruction() constructor. This does base initialization of the object as an instruction object. This version is returned to the caller, with this instruction anchored in the parser object to protect it from garbage collection, which is handy if its constructor needs to allocate any additional objects.
Step 4) happens once the caller receives this object instance. It agains calls the new() in-memory allocator for the final instruction class. The constructor fills in any instruction specific information, as well as changing the object virtual function table to the final version. The information we set up here will remain untouched.
Parameters
size The size of the object (can be variable for some instructions).
_behaviour The Rexx object behaviour.
type The type identifiers for the instruction (see RexxToken InstructionKeyword enum).
Returns
A newly created instruction object with basic instruction initialization.
Definition at line 498 of file InstructionParser.cpp.
References clause, currentInstruction, new_object(), RexxInternalObject::setBehaviour(), and type.
Referenced by sourceNewObject().
sourceNewObject() [2/2]
RexxInstruction * LanguageParser::sourceNewObject (size_t size, size_t count, size_t itemSize, RexxBehaviour * _behaviour, InstructionKeyword type)
Create a "raw" executable instruction object of variable size. Allocation/creation of instruction objects are handled a little differently, and goes in stages: 1) Have RexxMemory allocate a Rexx object of the appropriate size. 2) Set the object behaviour to be the table for the target instruction. 3) Call the in-memory new() method on this object using the RexxInstruction() constructor. This does base initialization of the object as an instruction object. This version is returned to the caller, with this instruction anchored in the parser object to protect it from garbage collection, which is handy if its constructor needs to allocate any additional objects.
Step 4) happens once the caller receives this object instance. It agains calls the new() in-memory allocator for the final instruction class. The constructor fills in any instruction specific information, as well as changing the object virtual function table to the final version. The information we set up here will remain untouched.
Parameters
size The base size of the object type.
count The count of extra items to add to the object instance.
itemSize The size of the extra items to add.
_behaviour The Rexx object behaviour.
type The type identifiers for the instruction (see RexxToken InstructionKeyword enum).
Returns
A newly created instruction object with basic instruction initialization.
Definition at line 538 of file InstructionParser.cpp.
References sourceNewObject(), and type.
sourceNextToken()
RexxToken * LanguageParser::sourceNextToken (RexxToken * previous)
Extract a token from the source and create a new token object. The token type and sub-type are set in the token, and any string value extracted.
Parameters
previous Any previous token, necessary for determining if a blank is significant. This can be NULL.
Returns
A new Token object representing the class of token.
Definition at line 719 of file Scanner.cpp.
References SourceLocation::adjustEnd(), CHECK_ASSIGNMENT, clause, CLAUSE_EOF, CLAUSE_EOL, CLAUSEEND_EOF, CLAUSEEND_EOL, CLAUSEEND_SEMICOLON, clauseLocation, currentLength, Error_Invalid_character_char, RexxClause::getLocation(), RexxToken::isBlankSignificant(), isSymbolCharacter(), lineNumber, lineOffset, locateToken(), new_string(), RexxClause::newToken(), nextLine(), nextSpecial(), NORMAL_CHAR, OPERATOR, OPERATOR_BLANK, OREF_NULL, scanLiteral(), scanSymbol(), RexxClause::setEnd(), SourceLocation::setEndOffset(), SIGNIFICANT_BLANK, startLocation(), stepPosition(), syntaxError(), TOKEN_BLANK, TOKEN_COLON, TOKEN_COMMA, TOKEN_DCOLON, TOKEN_DTILDE, TOKEN_EOC, TOKEN_LEFT, TOKEN_RIGHT, TOKEN_SQLEFT, TOKEN_SQRIGHT, TOKEN_TILDE, and translateChar().
Referenced by nextClause().
startLocation()
void LanguageParser::startLocation (SourceLocation & location)
Save the current scanning location as a start position
Parameters
location A location object to store this in.
Definition at line 136 of file Scanner.cpp.
References lineNumber, lineOffset, and SourceLocation::setStart().
Referenced by scanLiteral(), scanSymbol(), and sourceNextToken().
stepPosition() [1/2]
void LanguageParser::stepPosition () inline
Definition at line 157 of file LanguageParser.hpp.
References lineOffset.
Referenced by locateToken(), nextSpecial(), scanComment(), scanLiteral(), scanSymbol(), and sourceNextToken().
stepPosition() [2/2]
void LanguageParser::stepPosition (size_t o) inline
Definition at line 158 of file LanguageParser.hpp.
References lineOffset.
syntaxError() [1/7]
void LanguageParser::syntaxError (RexxErrorCodes errorcode) inline
Definition at line 409 of file LanguageParser.hpp.
References error().
syntaxError() [2/7]
void LanguageParser::syntaxError (RexxErrorCodes errorcode, const char * a1, RexxObject * a2) inline
Definition at line 406 of file LanguageParser.hpp.
References error(), and new_string().
syntaxError() [3/7]
void LanguageParser::syntaxError (RexxErrorCodes errorcode, RexxInstruction * i) inline
Definition at line 401 of file LanguageParser.hpp.
References errorLine().
Referenced by annotateDirective(), attributeDirective(), blockError(), callNew(), callOnNew(), checkDirective(), checkDuplicateMethod(), classDirective(), constantDirective(), createConstantGetterMethod(), createLoop(), createNativeMethod(), decodeExternalMethod(), dynamicCallNew(), endNew(), exposeNew(), forwardNew(), getRetriever(), getToken(), guardNew(), leaveNew(), methodDirective(), needVariable(), needVariableOrDotSymbol(), newControlledLoop(), newDoOverLoop(), newDoWithLoop(), nextDirective(), nextInstruction(), numericNew(), optionsDirective(), packBinaryLiteral(), packHexLiteral(), parseAddressWith(), parseCaseWhenList(), parseClassReference(), parseConstantExpression(), parseLogical(), parseLoopConditional(), parseMessage(), parseMessageSubterm(), parseNew(), parseQualifiedSymbol(), parseRedirectOptions(), parseSubExpression(), parseSubTerm(), parseVariableReferenceTerm(), procedureNew(), processAnnotation(), processAttributeAnnotations(), processVariableList(), qualifiedCallNew(), raiseNew(), replyNew(), requiredEndOfClause(), requiredExpression(), requiredLogicalExpression(), requiredTerm(), requiredVariable(), requiresDirective(), resolveDependencies(), resourceDirective(), routineDirective(), scanComment(), scanLiteral(), scanSymbol(), selectNew(), signalNew(), signalOnNew(), sourceNextToken(), traceNew(), translate(), translateBlock(), useLocalNew(), useNew(), and whenNew().
syntaxError() [4/7]
void LanguageParser::syntaxError (RexxErrorCodes errorcode, RexxObject * a1) inline
Definition at line 404 of file LanguageParser.hpp.
References error().
syntaxError() [5/7]
void LanguageParser::syntaxError (RexxErrorCodes errorcode, RexxObject * a1, RexxObject * a2) inline
Definition at line 405 of file LanguageParser.hpp.
References error().
syntaxError() [6/7]
void LanguageParser::syntaxError (RexxErrorCodes errorcode, RexxObject * a1, RexxObject * a2, RexxObject * a3) inline
Definition at line 407 of file LanguageParser.hpp.
References error().
syntaxError() [7/7]
void LanguageParser::syntaxError (RexxErrorCodes errorcode, RexxToken * token) inline
Definition at line 408 of file LanguageParser.hpp.
References errorToken().
syntaxErrorAt()
void LanguageParser::syntaxErrorAt (RexxErrorCodes errorcode, RexxToken * token) inline
Definition at line 403 of file LanguageParser.hpp.
References errorPosition().
Referenced by parenExpression(), parseArgList(), parseConstantExpression(), parseSubTerm(), and translateConstantExpression().
thenNew()
RexxInstruction * LanguageParser::thenNew (RexxToken * token, RexxInstructionIf * parent)
Create a new THEN instruction object.
Parameters
token The THEN token (used for location information).
parent The parent IF or WHEN instruction we're part of.
Returns
An executable instruction object.
Definition at line 4110 of file InstructionParser.cpp.
References new_instruction.
Referenced by translateBlock().
topBlockInstruction()
RexxInstruction * LanguageParser::topBlockInstruction ()
Locate the top block instruction in the control stack. This involves skipping over any THEN instructions waiting for resolution.
Returns
The top block instruction or OREF_NULL if none are active.
Definition at line 1768 of file LanguageParser.cpp.
References control, ArrayClass::get(), RexxInstruction::isBlock(), ArrayClass::lastIndex(), and OREF_NULL.
Referenced by whenNew().
topDo()
RexxInstruction* LanguageParser::topDo () inline
Definition at line 308 of file LanguageParser.hpp.
References control, and QueueClass::peek().
Referenced by translateBlock().
topDoIsType() [1/2]
bool LanguageParser::topDoIsType (InstructionKeyword t) inline
Definition at line 311 of file LanguageParser.hpp.
References control, and QueueClass::peek().
Referenced by translateBlock().
topDoIsType() [2/2]
bool LanguageParser::topDoIsType (InstructionKeyword t1, InstructionKeyword t2) inline
Definition at line 312 of file LanguageParser.hpp.
References topDoIsType().
Referenced by topDoIsType().
topDoType()
InstructionKeyword LanguageParser::topDoType () inline
Definition at line 310 of file LanguageParser.hpp.
References control, and QueueClass::peek().
Referenced by flushControl(), and translateBlock().
topOperator()
RexxToken* LanguageParser::topOperator () inline
Definition at line 377 of file LanguageParser.hpp.
References operators, and QueueClass::peek().
Referenced by parseSubExpression().
traceNew()
RexxInstruction * LanguageParser::traceNew ()
Parse and create a new Trace instruction object.
Returns
A Trace instruction object.
Definition at line 4124 of file InstructionParser.cpp.
References Error_Invalid_data_trace, Error_Invalid_expression_general, Error_Invalid_expression_trace, Error_Invalid_trace_trace, Error_Invalid_whole_number_trace, RexxToken::isEndOfClause(), RexxToken::isLiteral(), RexxToken::isSubtype(), RexxToken::isSymbol(), RexxToken::isSymbolOrLiteral(), new_instruction, new_string(), nextReal(), number_digits(), OPERATOR_PLUS, OPERATOR_SUBTRACT, OREF_NULL, parseExpression(), TraceSetting::parseTraceSetting(), previousToken(), RexxInternalObject::requestNumber(), requiredEndOfClause(), requiredExpression(), TraceSetting::setDefault(), SUBKEY_VALUE, RexxToken::subKeyword(), syntaxError(), TERM_EOC, and RexxToken::value().
Referenced by nextInstruction().
translate()
void LanguageParser::translate ()
Translate a source object into executable code. This translates the main code section and stores it in the mainSection field. If permitted (i.e, not an interpret), this will also process any additional directives and associated code sections.
Definition at line 1089 of file LanguageParser.cpp.
References activeClass, atEnd(), ActivityManager::currentActivity, Error_Translation_directive_interpret, flags, initializeForDirectives(), mainSection, nextClause(), nextDirective(), noDirectives, OREF_NULL, package, PackageClass::packageSettings, resolveDependencies(), PackageSetting::setDefault(), syntaxError(), and translateBlock().
Referenced by compileSource().
translateBlock()
RexxCode * LanguageParser::translateBlock ()
Translate a block of REXX code (delimited by possible directive instructions
Returns
A RexxCode object for this block.
Definition at line 1172 of file LanguageParser.cpp.
References addClause(), blockSyntaxError(), clause, Error_Incomplete_do_else, Error_Incomplete_do_then, Error_Then_expected_if, Error_Then_expected_when, Error_Unexpected_end_else, Error_Unexpected_end_nodo, Error_Unexpected_end_then, Error_Unexpected_label_do, Error_Unexpected_label_if, Error_Unexpected_label_select, Error_Unexpected_then_else, Error_Unexpected_when_otherwise, Error_When_expected_whenotherwise, firstInstruction, flushControl(), ProgramSource::getLine(), ProgramSource::getLineCount(), SourceLocation::getLineNumber(), RexxClause::getLocation(), SourceLocation::getOffset(), RexxInstruction::getType(), initializeForTranslation(), RexxInstruction::isBlock(), RexxInstruction::isControl(), HashCollection::isEmpty(), RexxToken::isEndOfClause(), RexxInstruction::isType(), RexxToken::keyword(), KEYWORD_DO, KEYWORD_ELSE, KEYWORD_END, KEYWORD_ENDTHEN, KEYWORD_ENDWHEN, KEYWORD_FIRST, KEYWORD_IF, KEYWORD_IFTHEN, KEYWORD_LABEL, KEYWORD_LOOP, KEYWORD_LOOP_CONTROLLED, KEYWORD_LOOP_CONTROLLED_UNTIL, KEYWORD_LOOP_CONTROLLED_WHILE, KEYWORD_LOOP_COUNT, KEYWORD_LOOP_COUNT_UNTIL, KEYWORD_LOOP_COUNT_WHILE, KEYWORD_LOOP_FOREVER, KEYWORD_LOOP_OVER, KEYWORD_LOOP_OVER_FOR, KEYWORD_LOOP_OVER_FOR_UNTIL, KEYWORD_LOOP_OVER_FOR_WHILE, KEYWORD_LOOP_OVER_UNTIL, KEYWORD_LOOP_OVER_WHILE, KEYWORD_LOOP_UNTIL, KEYWORD_LOOP_WHILE, KEYWORD_LOOP_WITH, KEYWORD_LOOP_WITH_FOR, KEYWORD_LOOP_WITH_FOR_UNTIL, KEYWORD_LOOP_WITH_FOR_WHILE, KEYWORD_LOOP_WITH_UNTIL, KEYWORD_LOOP_WITH_WHILE, KEYWORD_OTHERWISE, KEYWORD_SELECT, KEYWORD_SELECT_CASE, KEYWORD_SIMPLE_BLOCK, KEYWORD_THEN, KEYWORD_WHEN, KEYWORD_WHEN_CASE, KEYWORD_WHENTHEN, labels, lastInstruction, lineNumber, lineOffset, maxStack, new_string(), nextClause(), RexxInstruction::nextInstruction, nextInstruction(), nextReal(), noClauseAvailable(), OREF_NULL, package, popDo(), previousToken(), pushDo(), resetPosition(), resolveCalls(), SourceLocation::setEnd(), SourceLocation::setLineNumber(), SourceLocation::setStart(), source, syntaxError(), thenNew(), topDo(), topDoIsType(), topDoType(), trimClause(), type, and variableIndex.
Referenced by createMethod(), methodDirective(), routineDirective(), and translate().
translateChar()
static int LanguageParser::translateChar (unsigned int ch) inline static
Definition at line 424 of file LanguageParser.hpp.
References characterTable.
Referenced by VariableDictionary::getDirectVariableRetriever(), scanSymbol(), and sourceNextToken().
translateConstantExpression()
RexxInternalObject * LanguageParser::translateConstantExpression (RexxToken * token, RexxErrorCodes error)
Translate an expression of REXX code on a directive (already have an active clause, not translating a block yet)
Parameters
token The left paren delimiter for the expression. Required for error reporting.
Returns
A translated expression for this directive.
Definition at line 1721 of file LanguageParser.cpp.
References constantMaxStack, constantVariableIndex, constantVariables, error(), Error_Unmatched_parenthesis_paren, holdObject(), initializeForTranslation(), maxStack, nextToken(), OREF_NULL, requiredExpression(), resolveCalls(), syntaxErrorAt(), TERM_RIGHT, variableIndex, and variables.
Referenced by constantDirective().
translateInterpret() [1/2]
RexxCode * LanguageParser::translateInterpret (PackageClass * sourceContext, StringTable * contextLabels)
Translate an interpret string.
Parameters
contextlabels The labels for the interpreting source program.
Returns
A RexxCode object resulting from the compilation of this interpret line.
Definition at line 682 of file LanguageParser.cpp.
References compileSource(), PackageClass::inheritPackageContext(), labels, mainSection, package, and setInterpret().
Referenced by RexxCode::interpret().
translateInterpret() [2/2]
RexxCode * LanguageParser::translateInterpret (RexxString * interpretString, PackageClass * sourceContext, StringTable * labels, size_t lineNumber) static
Translate a single string value for an interpret instruction.
Parameters
interpretString The string to interpret.
labels The labels from the interpret context.
lineNumber The line number of the interpret location.
Returns
The interpreted code.
Definition at line 446 of file LanguageParser.cpp.
References PackageClass::getProgramName(), labels, LanguageParser(), lineNumber, new_array(), and parser().
trimClause()
void LanguageParser::trimClause () inline
Definition at line 173 of file LanguageParser.hpp.
References clause, and RexxClause::trim().
Referenced by nextInstruction(), and translateBlock().
truncateLine()
void LanguageParser::truncateLine () inline
Definition at line 162 of file LanguageParser.hpp.
References currentLength, and lineOffset.
Referenced by locateToken().
useLocalNew()
RexxInstruction * LanguageParser::useLocalNew ()
Parse and create a new USE LOCAL instruction
Returns
The configured instruction instance.
Definition at line 2349 of file InstructionParser.cpp.
References addVariable(), autoExpose(), Error_Invalid_variable_number, Error_Invalid_variable_period, Error_Symbol_expected_use_local, Error_Translation_use_local, Error_Translation_use_local_compound, Error_Translation_use_local_interpret, RexxToken::isEndOfClause(), isInterpret(), RexxToken::isSubtype(), RexxToken::isSymbol(), RexxInstruction::isType(), KEYWORD_FIRST, lastInstruction, localVariable(), new_variable_instruction, nextReal(), pushSubTerm(), subTerms, SYMBOL_COMPOUND, SYMBOL_CONSTANT, SYMBOL_DOTSYMBOL, SYMBOL_DUMMY, syntaxError(), and RexxToken::value().
Referenced by useNew().
useNew()
RexxInstruction * LanguageParser::useNew ()
Parse a USE ARG or USE STRICT ARG instruction.
Returns
The executable instruction object.
Definition at line 4267 of file InstructionParser.cpp.
References addText(), Error_Invalid_expression_use_arg_default, Error_Invalid_subkeyword_use, Error_Invalid_subkeyword_use_strict, Error_Symbol_expected_after_use_arg_reference, Error_Translation_use_arg_ellipsis, Error_Translation_use_arg_reference_no_default, Error_Variable_expected_USE, Error_Variable_reference_use, RexxToken::isComma(), RexxToken::isEndOfClause(), RexxToken::isNonCompoundVariable(), RexxToken::isOperator(), RexxToken::isSubtype(), RexxToken::isSymbol(), new_queue(), new_variable_instruction, nextReal(), OPERATOR_EQUAL, OPERATOR_GREATERTHAN, OPERATOR_LESSTHAN, OREF_NULL, parseConstantExpression(), parseVariableOrMessageTerm(), previousToken(), RexxString::strCompare(), SUBKEY_ARG, SUBKEY_LOCAL, SUBKEY_STRICT, RexxToken::subKeyword(), syntaxError(), useLocalNew(), and RexxToken::value().
Referenced by nextInstruction().
whenNew()
RexxInstruction * LanguageParser::whenNew ()
Create a new IF or WHEN instruction object. These share the same implementation class, but get wired together differently.
Parameters
type The type of instruction to create.
Returns
A an executable IF instruction object.
Definition at line 2708 of file InstructionParser.cpp.
References Error_Invalid_expression_when, Error_Unexpected_when_when, RexxInstruction::isType(), KEYWORD_SELECT, KEYWORD_SELECT_CASE, new_instruction, new_variable_instruction, nextReal(), OREF_NULL, parseCaseWhenList(), previousToken(), pushSubTerm(), requiredLogicalExpression(), subTerms, syntaxError(), TERM_IF, and topBlockInstruction().
Referenced by nextInstruction().
words()
ArrayClass * LanguageParser::words (RexxString * string)
Break up a string into an array of words for parsing and interpretation. The first word will be uppercased, and all of the strings will be added to the common string pool.
Parameters
string The string we break up.
Returns
An array of the words.
Definition at line 4028 of file LanguageParser.cpp.
References commonString(), ArrayClass::get(), ArrayClass::items(), OREF_NULL, and ArrayClass::put().
Referenced by decodeExternalMethod(), and routineDirective().
Member Data Documentation
activeClass
ClassDirective* LanguageParser::activeClass protected
Definition at line 486 of file LanguageParser.hpp.
Referenced by addMethod(), checkDuplicateMethod(), classDirective(), constantDirective(), createConstantGetterMethod(), findClassMethod(), findInstanceMethod(), findMethod(), initializeForDirectives(), live(), liveGeneral(), and translate().
builtinTable
pbuiltin LanguageParser::builtinTable static
Definition at line 452 of file LanguageParser.hpp.
Referenced by RexxExpressionFunction::evaluate(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), and RexxInstructionCallOn::trap().
calls
ArrayClass* LanguageParser::calls protected
Definition at line 506 of file LanguageParser.hpp.
Referenced by addReference(), initializeForTranslation(), live(), liveGeneral(), and resolveCalls().
characterTable
int LanguageParser::characterTable static protected
Definition at line 516 of file LanguageParser.hpp.
Referenced by isSymbolCharacter(), and translateChar().
classDependencies
StringTable* LanguageParser::classDependencies protected
Definition at line 487 of file LanguageParser.hpp.
Referenced by addClassDirective(), findClassDirective(), initializeForDirectives(), isDuplicateClass(), live(), liveGeneral(), and resolveDependencies().
classes
ArrayClass* LanguageParser::classes protected
Definition at line 494 of file LanguageParser.hpp.
Referenced by addClassDirective(), initializeForDirectives(), live(), liveGeneral(), and resolveDependencies().
clause
RexxClause* LanguageParser::clause protected
Definition at line 472 of file LanguageParser.hpp.
Referenced by classDirective(), constantDirective(), createConstantGetterMethod(), firstToken(), initializeForParsing(), live(), liveGeneral(), markPosition(), nextClause(), nextLine(), nextReal(), nextToken(), packBinaryLiteral(), packHexLiteral(), previousToken(), requiresDirective(), resetPosition(), scanComment(), scanLiteral(), scanSymbol(), sourceNewObject(), sourceNextToken(), translateBlock(), and trimClause().
clauseLocation
SourceLocation LanguageParser::clauseLocation protected
Definition at line 473 of file LanguageParser.hpp.
Referenced by blockError(), checkDirective(), createStackFrame(), error(), getLocation(), nextClause(), packBinaryLiteral(), packHexLiteral(), resolveDependencies(), scanComment(), scanLiteral(), scanSymbol(), and sourceNextToken().
constantMaxStack
size_t LanguageParser::constantMaxStack protected
Definition at line 511 of file LanguageParser.hpp.
Referenced by classDirective(), createConstantGetterMethod(), and translateConstantExpression().
constantVariableIndex
size_t LanguageParser::constantVariableIndex protected
Definition at line 512 of file LanguageParser.hpp.
Referenced by classDirective(), createConstantGetterMethod(), and translateConstantExpression().
constantVariables
StringTable* LanguageParser::constantVariables protected
Definition at line 513 of file LanguageParser.hpp.
Referenced by classDirective(), live(), liveGeneral(), and translateConstantExpression().
control
QueueClass* LanguageParser::control protected
Definition at line 482 of file LanguageParser.hpp.
Referenced by initializeForParsing(), live(), liveGeneral(), newControlledLoop(), newDoOverLoop(), popDo(), pushDo(), topBlockInstruction(), topDo(), topDoIsType(), and topDoType().
current
const char* LanguageParser::current protected
Definition at line 469 of file LanguageParser.hpp.
Referenced by checkMarker(), getChar(), getNextChar(), getStringLine(), nextChar(), packBinaryLiteral(), packHexLiteral(), position(), and scanLiteral().
currentInstruction
RexxInstruction* LanguageParser::currentInstruction protected
Definition at line 500 of file LanguageParser.hpp.
Referenced by live(), liveGeneral(), and sourceNewObject().
currentLength
size_t LanguageParser::currentLength protected
Definition at line 470 of file LanguageParser.hpp.
Referenced by checkMarker(), getStringLine(), haveNextChar(), moreChars(), position(), sourceNextToken(), and truncateLine().
currentStack
size_t LanguageParser::currentStack protected
Definition at line 508 of file LanguageParser.hpp.
Referenced by initializeForTranslation(), nextInstruction(), popNTerms(), popSubTerm(), popTerm(), pushSubTerm(), pushTerm(), and requiredTerm().
dotVariables
StringTable* LanguageParser::dotVariables protected
Definition at line 480 of file LanguageParser.hpp.
Referenced by addText(), initializeForParsing(), live(), and liveGeneral().
exposedVariables
StringTable* LanguageParser::exposedVariables protected
Definition at line 504 of file LanguageParser.hpp.
Referenced by expose(), initializeForTranslation(), isExposed(), live(), and liveGeneral().
firstInstruction
RexxInstruction* LanguageParser::firstInstruction protected
Definition at line 498 of file LanguageParser.hpp.
Referenced by initializeForTranslation(), live(), liveGeneral(), and translateBlock().
flags
FlagSet<ParsingFlags, 32> LanguageParser::flags protected
Definition at line 468 of file LanguageParser.hpp.
Referenced by atEnd(), clauseAvailable(), initializeForTranslation(), isInterpret(), nextClause(), noClauseAvailable(), raiseNew(), reclaimClause(), setInterpret(), and translate().
guardVariables
IdentityTable* LanguageParser::guardVariables protected
Definition at line 503 of file LanguageParser.hpp.
Referenced by captureGuardVariable(), capturingGuardVariables(), getGuard(), initializeForTranslation(), live(), liveGeneral(), and setGuard().
HOLDSIZE
const size_t LanguageParser::HOLDSIZE = 30 static protected
Definition at line 463 of file LanguageParser.hpp.
Referenced by initializeForParsing().
holdStack
PushThroughStack* LanguageParser::holdStack protected
Definition at line 478 of file LanguageParser.hpp.
Referenced by holdObject(), initializeForParsing(), live(), and liveGeneral().
INVALID_CHARACTER
const unsigned int LanguageParser::INVALID_CHARACTER = 0x100 static
Definition at line 455 of file LanguageParser.hpp.
Referenced by followingChar(), and locateToken().
labels
StringTable* LanguageParser::labels protected
Definition at line 502 of file LanguageParser.hpp.
Referenced by addLabel(), findLabel(), initializeForTranslation(), live(), liveGeneral(), resolveCalls(), translateBlock(), and translateInterpret().
lastInstruction
RexxInstruction* LanguageParser::lastInstruction protected
Definition at line 499 of file LanguageParser.hpp.
Referenced by addClause(), blockError(), exposeNew(), initializeForTranslation(), live(), liveGeneral(), translateBlock(), and useLocalNew().
libraries
ArrayClass* LanguageParser::libraries protected
Definition at line 493 of file LanguageParser.hpp.
Referenced by initializeForDirectives(), live(), liveGeneral(), requiresDirective(), and resolveDependencies().
lineCount
size_t LanguageParser::lineCount protected
Definition at line 471 of file LanguageParser.hpp.
Referenced by initializeForParsing(), and moreLines().
lineNumber
size_t LanguageParser::lineNumber protected
Definition at line 474 of file LanguageParser.hpp.
Referenced by endLocation(), initializeForParsing(), locateToken(), moreLines(), nextClause(), nextLine(), position(), scanComment(), scanLiteral(), scanSymbol(), setLocation(), sourceNextToken(), startLocation(), translateBlock(), and translateInterpret().
lineOffset
size_t LanguageParser::lineOffset protected
Definition at line 475 of file LanguageParser.hpp.
Referenced by conditionalNextLine(), endLocation(), getChar(), getNextChar(), haveNextChar(), locateToken(), moreChars(), nextChar(), nextClause(), nextLine(), position(), scanComment(), scanLiteral(), scanSymbol(), setLocation(), sourceNextToken(), startLocation(), stepPosition(), translateBlock(), and truncateLine().
literals
StringTable* LanguageParser::literals protected
Definition at line 479 of file LanguageParser.hpp.
Referenced by addText(), initializeForParsing(), live(), and liveGeneral().
localVariables
StringTable* LanguageParser::localVariables protected
Definition at line 505 of file LanguageParser.hpp.
Referenced by autoExpose(), initializeForTranslation(), isExposed(), live(), liveGeneral(), and localVariable().
mainSection
RexxCode* LanguageParser::mainSection protected
Definition at line 477 of file LanguageParser.hpp.
Referenced by generateMethod(), generatePackage(), generateProgram(), generateRoutine(), live(), liveGeneral(), translate(), and translateInterpret().
MAX_SYMBOL_LENGTH
const size_t LanguageParser::MAX_SYMBOL_LENGTH = 250 static
Definition at line 458 of file LanguageParser.hpp.
Referenced by CompoundVariableTail::init(), and scanSymbol().
maxStack
size_t LanguageParser::maxStack protected
Definition at line 509 of file LanguageParser.hpp.
Referenced by initializeForTranslation(), pushSubTerm(), pushTerm(), translateBlock(), and translateConstantExpression().
name
RexxString* LanguageParser::name protected
Definition at line 465 of file LanguageParser.hpp.
Referenced by addClassDirective(), addCompound(), addMethod(), addText(), annotateDirective(), attributeDirective(), checkDuplicateMethod(), classDirective(), constantDirective(), createAbstractMethod(), createAttributeGetterMethod(), createAttributeSetterMethod(), createConstantGetterMethod(), createDelegateMethod(), createLoop(), createMethod(), createNativeMethod(), createPackage(), createProgram(), createRoutine(), endNew(), expose(), findClassDirective(), findClassMethod(), findInstanceMethod(), findMethod(), findRoutine(), generateMethod(), generatePackage(), generateProgram(), generateRoutine(), getRetriever(), isDuplicateClass(), isDuplicateRoutine(), labelNew(), LanguageParser(), leaveNew(), live(), liveGeneral(), localVariable(), methodDirective(), parseClassReference(), parseFunction(), processAnnotation(), processInstore(), requiresDirective(), resolveDependencies(), resourceDirective(), restoreFromMacroSpace(), and routineDirective().
operators
QueueClass* LanguageParser::operators protected
Definition at line 485 of file LanguageParser.hpp.
Referenced by initializeForParsing(), live(), liveGeneral(), popOperator(), pushOperator(), and topOperator().
package
PackageClass* LanguageParser::package protected
Definition at line 467 of file LanguageParser.hpp.
Referenced by addMethod(), annotateDirective(), createConstantGetterMethod(), createNativeMethod(), createStackFrame(), generateMethod(), generatePackage(), generateProgram(), generateRoutine(), getPackage(), initializeForParsing(), installPackage(), live(), liveGeneral(), optionsDirective(), requireLanguageLevel(), resolveDependencies(), routineDirective(), translate(), translateBlock(), and translateInterpret().
publicRoutines
StringTable* LanguageParser::publicRoutines protected
Definition at line 490 of file LanguageParser.hpp.
Referenced by initializeForDirectives(), live(), liveGeneral(), resolveDependencies(), and routineDirective().
requires
ArrayClass* LanguageParser::requires protected
Definition at line 492 of file LanguageParser.hpp.
Referenced by initializeForDirectives(), live(), liveGeneral(), requiresDirective(), and resolveDependencies().
resources
StringTable* LanguageParser::resources protected
Definition at line 491 of file LanguageParser.hpp.
Referenced by initializeForDirectives(), live(), liveGeneral(), resolveDependencies(), and resourceDirective().
routines
StringTable* LanguageParser::routines protected
Definition at line 489 of file LanguageParser.hpp.
Referenced by findRoutine(), initializeForDirectives(), isDuplicateRoutine(), live(), liveGeneral(), resolveDependencies(), and routineDirective().
source
ProgramSource* LanguageParser::source protected
Definition at line 466 of file LanguageParser.hpp.
Referenced by createMethod(), createPackage(), createProgram(), createRoutine(), initializeForParsing(), LanguageParser(), live(), liveGeneral(), parseRedirectOptions(), position(), and translateBlock().
strings
StringTable* LanguageParser::strings protected
Definition at line 481 of file LanguageParser.hpp.
Referenced by commonString(), initializeForParsing(), live(), and liveGeneral().
subTerms
QueueClass* LanguageParser::subTerms protected
Definition at line 484 of file LanguageParser.hpp.
Referenced by addCompound(), callNew(), dropNew(), dynamicCallNew(), exposeNew(), initializeForParsing(), live(), liveGeneral(), nextInstruction(), parseArgArray(), parseArgList(), parseCollectionMessage(), parseFullSubExpression(), parseFunction(), parseLogical(), parseMessage(), parseNew(), parseQualifiedSymbol(), popSubTerm(), procedureNew(), processVariableList(), pushSubTerm(), qualifiedCallNew(), useLocalNew(), and whenNew().
terms
QueueClass* LanguageParser::terms protected
Definition at line 483 of file LanguageParser.hpp.
Referenced by initializeForParsing(), live(), liveGeneral(), nextInstruction(), parseNew(), popNTerms(), popTerm(), pushTerm(), and requiredTerm().
unattachedMethods
StringTable* LanguageParser::unattachedMethods protected
Definition at line 488 of file LanguageParser.hpp.
Referenced by addMethod(), checkDuplicateMethod(), findInstanceMethod(), findMethod(), initializeForDirectives(), live(), liveGeneral(), and resolveDependencies().
variableIndex
size_t LanguageParser::variableIndex protected
Definition at line 510 of file LanguageParser.hpp.
Referenced by addSimpleVariable(), addStem(), initializeForTranslation(), translateBlock(), and translateConstantExpression().
variables
StringTable* LanguageParser::variables protected
Definition at line 501 of file LanguageParser.hpp.
Referenced by addCompound(), addSimpleVariable(), addStem(), initializeForTranslation(), live(), liveGeneral(), and translateConstantExpression().
The documentation for this class was generated from the following files:
LanguageParser.hpp
LanguageParser.cpp
DirectiveParser.cpp
Scanner.cpp
InstructionParser.cpp
BuiltinFunctions.cpp