ooRexx: ServerRegistrationManager Class Reference
ServerRegistrationManager Class Reference
#include <RegistrationManager.hpp>
Public Member Functions
ServerRegistrationManager ()
void terminateServer ()
void freeProcessRegistrations (SessionID session)
void dispatch (ServiceMessage &message)
void cleanupProcessResources (SessionID session)
bool isStoppable ()
Protected Attributes
RegistrationTable functions
RegistrationTable exits
RegistrationTable commandHandlers
SysMutex lock
Detailed Description
Definition at line 46 of file RegistrationManager.hpp.
Constructor & Destructor Documentation
ServerRegistrationManager()
ServerRegistrationManager::ServerRegistrationManager () inline
Definition at line 49 of file RegistrationManager.hpp.
References SysMutex::create(), and lock.
Member Function Documentation
cleanupProcessResources()
void ServerRegistrationManager::cleanupProcessResources (SessionID session)
Perform any cleanup of process-specific resources when the process terminates.
Parameters
session The session id of the session going away.
Definition at line 129 of file RegistrationManager.cpp.
References freeProcessRegistrations().
Referenced by APIServerInstance::cleanupProcessResources().
dispatch()
void ServerRegistrationManager::dispatch (ServiceMessage & message)
Dispatch a registration operation to the appropriate subsystem handler.
Parameters
message The inbound message.
Definition at line 64 of file RegistrationManager.cpp.
References commandHandlers, RegistrationTable::dropCallback(), RegistrationTable::dropLibraryCallback(), ExitAPI, exits, ServiceMessage::freeMessageData(), FunctionAPI, functions, INVALID_OPERATION, ServiceMessage::operation, ServiceMessage::parameter1, RegistrationTable::queryCallback(), RegistrationTable::queryLibraryCallback(), REGISTER_DROP, REGISTER_DROP_LIBRARY, REGISTER_ENTRYPOINT, REGISTER_LIBRARY, REGISTER_LOAD_LIBRARY, REGISTER_QUERY, REGISTER_QUERY_LIBRARY, RegistrationTable::registerCallback(), RegistrationTable::registerLibraryCallback(), ServiceMessage::setExceptionInfo(), SubcomAPI, UPDATE_CALLBACK, and RegistrationTable::updateCallback().
Referenced by APIServerInstance::dispatch().
freeProcessRegistrations()
void ServerRegistrationManager::freeProcessRegistrations (SessionID session)
It will remove all the registration entries for a specific process
Parameters
session The session identifier.
Definition at line 49 of file RegistrationManager.cpp.
References commandHandlers, exits, RegistrationTable::freeProcessEntries(), and functions.
Referenced by cleanupProcessResources().
isStoppable()
bool ServerRegistrationManager::isStoppable () inline
Definition at line 56 of file RegistrationManager.hpp.
References commandHandlers, exits, functions, and RegistrationTable::isEmpty().
Referenced by APIServerInstance::isStoppable().
terminateServer()
void ServerRegistrationManager::terminateServer ()
Member Data Documentation
commandHandlers
RegistrationTable ServerRegistrationManager::commandHandlers protected
Definition at line 64 of file RegistrationManager.hpp.
Referenced by dispatch(), freeProcessRegistrations(), and isStoppable().
exits
RegistrationTable ServerRegistrationManager::exits protected
Definition at line 63 of file RegistrationManager.hpp.
Referenced by dispatch(), freeProcessRegistrations(), and isStoppable().
functions
RegistrationTable ServerRegistrationManager::functions protected
Definition at line 62 of file RegistrationManager.hpp.
Referenced by dispatch(), freeProcessRegistrations(), and isStoppable().
lock
SysMutex ServerRegistrationManager::lock protected
Definition at line 65 of file RegistrationManager.hpp.
Referenced by ServerRegistrationManager().
The documentation for this class was generated from the following files:
RegistrationManager.hpp
RegistrationManager.cpp