ooRexx: RegistrationData Class Reference
RegistrationData Class Reference
#include <RegistrationTable.hpp>
Public Member Functions
RegistrationData (const char *n, const char *m, SessionID s, ServiceRegistrationData *regData)
RegistrationData (const char *n, SessionID s, ServiceRegistrationData *regData)
~RegistrationData ()
bool matches (const char *n, const char *m)
bool matches (const char *n, SessionID s)
bool matches (const char *n)
bool hasReferences ()
bool isLibrary ()
bool isEntryPoint ()
void getRegistrationData (ServiceRegistrationData &regData)
void addSessionReference (SessionID s)
void removeSessionReference (SessionID s)
SessionCookie * findSessionReference (SessionID s)
void removeSessionReference (SessionCookie *s)
Public Attributes
RegistrationData * next
const char * name
const char * moduleName
const char * procedureName
uintptr_t userData [2]
uintptr_t entryPoint
size_t dropAuthority
SessionID owner
SessionCookie * references
Detailed Description
Definition at line 66 of file RegistrationTable.hpp.
Constructor & Destructor Documentation
RegistrationData() [1/2]
RegistrationData::RegistrationData (const char * n, const char * m, SessionID s, ServiceRegistrationData * regData)
Create registration data for a library registration item.
Parameters
n The callback name.
m The callback library.
regData The additional registration data sent with the message.
Definition at line 49 of file RegistrationTable.cpp.
References dropAuthority, ServiceRegistrationData::dropAuthority, dupString(), entryPoint, moduleName, name, next, owner, procedureName, ServiceRegistrationData::procedureName, references, userData, and ServiceRegistrationData::userData.
RegistrationData() [2/2]
RegistrationData::RegistrationData (const char * n, SessionID s, ServiceRegistrationData * regData)
Register an inprocess item.
Parameters
n The name of the callback.
s The session id.
regData The service registration data.
Definition at line 70 of file RegistrationTable.cpp.
References dropAuthority, ServiceRegistrationData::dropAuthority, dupString(), entryPoint, ServiceRegistrationData::entryPoint, moduleName, name, next, owner, procedureName, references, userData, and ServiceRegistrationData::userData.
~RegistrationData()
RegistrationData::~RegistrationData ()
Destructor for a registration data item.
Definition at line 87 of file RegistrationTable.cpp.
References moduleName, name, SessionCookie::next, procedureName, and references.
Member Function Documentation
addSessionReference()
void RegistrationData::addSessionReference (SessionID s)
Add an additional reference to a session.
Parameters
s The session id to add.
Definition at line 139 of file RegistrationTable.cpp.
References SessionCookie::addReference(), findSessionReference(), SessionCookie::next, and references.
Referenced by RegistrationTable::registerLibraryCallback().
findSessionReference()
SessionCookie * RegistrationData::findSessionReference (SessionID s)
Locate a session reference cound.
Parameters
s The target session identifier.
Returns
The session cookie associated with the session, or NULL if the session has not been tracked yet.
Definition at line 180 of file RegistrationTable.cpp.
References SessionCookie::next, references, and SessionCookie::session.
Referenced by addSessionReference(), and removeSessionReference().
getRegistrationData()
void RegistrationData::getRegistrationData (ServiceRegistrationData & regData)
Copy the registration information into a message data item to be returned to the client.
Parameters
regData The returned registration data.
Definition at line 109 of file RegistrationTable.cpp.
References dropAuthority, ServiceRegistrationData::dropAuthority, entryPoint, ServiceRegistrationData::entryPoint, ServiceRegistrationData::MAX_NAME_LENGTH, moduleName, ServiceRegistrationData::moduleName, procedureName, ServiceRegistrationData::procedureName, Utilities::strncpy(), userData, and ServiceRegistrationData::userData.
Referenced by RegistrationTable::queryCallback(), and RegistrationTable::queryLibraryCallback().
hasReferences()
bool RegistrationData::hasReferences () inline
Definition at line 76 of file RegistrationTable.hpp.
References references.
Referenced by RegistrationTable::dropCallback(), and RegistrationTable::dropLibraryCallback().
isEntryPoint()
bool RegistrationData::isEntryPoint () inline
Definition at line 78 of file RegistrationTable.hpp.
References moduleName.
Referenced by RegistrationTable::dropLibraryCallback().
isLibrary()
bool RegistrationData::isLibrary () inline
Definition at line 77 of file RegistrationTable.hpp.
References moduleName.
matches() [1/3]
bool RegistrationData::matches (const char * n) inline
Definition at line 75 of file RegistrationTable.hpp.
References name, and Utilities::strCaselessCompare().
matches() [2/3]
bool RegistrationData::matches (const char * n, const char * m) inline
Definition at line 73 of file RegistrationTable.hpp.
References moduleName, name, and Utilities::strCaselessCompare().
Referenced by RegistrationTable::locate().
matches() [3/3]
bool RegistrationData::matches (const char * n, SessionID s) inline
Definition at line 74 of file RegistrationTable.hpp.
References name, owner, and Utilities::strCaselessCompare().
removeSessionReference() [1/2]
void RegistrationData::removeSessionReference (SessionCookie * s)
Remove a session reference cookie from the chain.
Parameters
s The cookie to remove.
Definition at line 199 of file RegistrationTable.cpp.
References SessionCookie::next, and references.
removeSessionReference() [2/2]
void RegistrationData::removeSessionReference (SessionID s)
Decrement a session reference count.
Parameters
s The session identifier.
Definition at line 160 of file RegistrationTable.cpp.
References findSessionReference(), and SessionCookie::removeReference().
Referenced by RegistrationTable::dropCallback(), and RegistrationTable::dropLibraryCallback().
Member Data Documentation
dropAuthority
size_t RegistrationData::dropAuthority
Definition at line 92 of file RegistrationTable.hpp.
Referenced by RegistrationTable::dropCallback(), RegistrationTable::dropLibraryCallback(), getRegistrationData(), and RegistrationData().
entryPoint
uintptr_t RegistrationData::entryPoint
Definition at line 91 of file RegistrationTable.hpp.
Referenced by getRegistrationData(), RegistrationData(), and RegistrationTable::updateCallback().
moduleName
const char* RegistrationData::moduleName
Definition at line 88 of file RegistrationTable.hpp.
Referenced by getRegistrationData(), isEntryPoint(), isLibrary(), matches(), RegistrationData(), and ~RegistrationData().
name
const char* RegistrationData::name
Definition at line 87 of file RegistrationTable.hpp.
Referenced by matches(), RegistrationData(), and ~RegistrationData().
next
RegistrationData* RegistrationData::next
Definition at line 86 of file RegistrationTable.hpp.
Referenced by RegistrationTable::freeProcessEntries(), RegistrationTable::locate(), RegistrationTable::registerCallback(), RegistrationTable::registerLibraryCallback(), RegistrationData(), RegistrationTable::remove(), and RegistrationTable::reorderBlocks().
owner
SessionID RegistrationData::owner
Definition at line 93 of file RegistrationTable.hpp.
Referenced by RegistrationTable::dropCallback(), RegistrationTable::dropLibraryCallback(), RegistrationTable::freeProcessEntries(), matches(), RegistrationTable::queryCallback(), and RegistrationData().
procedureName
const char* RegistrationData::procedureName
Definition at line 89 of file RegistrationTable.hpp.
Referenced by getRegistrationData(), RegistrationData(), and ~RegistrationData().
references
SessionCookie* RegistrationData::references
Definition at line 94 of file RegistrationTable.hpp.
Referenced by addSessionReference(), findSessionReference(), hasReferences(), RegistrationData(), removeSessionReference(), and ~RegistrationData().
userData
uintptr_t RegistrationData::userData[2]
Definition at line 90 of file RegistrationTable.hpp.
Referenced by getRegistrationData(), and RegistrationData().
The documentation for this class was generated from the following files:
RegistrationTable.hpp
RegistrationTable.cpp