ooRexx: RedirectionDispatcher Class Reference
RedirectionDispatcher Class Reference
Public Member Functions
RedirectionDispatcher (TrapInvoker &t)
virtual ~RedirectionDispatcher ()
virtual void handleError (DirectoryClass *conditionObj)
Public Member Functions inherited from ConditionTrappingDispatcher
ConditionTrappingDispatcher (TrapInvoker &t)
virtual ~ConditionTrappingDispatcher ()
void run () override
void handleError (wholenumber_t, DirectoryClass *) override
void handleError (DirectoryClass *) override
bool trapConditions () override
bool errorOccurred ()
bool conditionOccurred ()
DirectoryClass * getCondition ()
Public Member Functions inherited from TrappingDispatcher
TrappingDispatcher ()
virtual ~TrappingDispatcher ()
void setContext (Activity *act, NativeActivation *a)
Additional Inherited Members
Public Attributes inherited from TrappingDispatcher
wholenumber_t rc
Protected Attributes inherited from ConditionTrappingDispatcher
TrapInvoker & invoker
wholenumber_t errorCode
Protected Attributes inherited from TrappingDispatcher
Activity * activity
NativeActivation * activation
DirectoryClass * conditionData
Detailed Description
A dispatcher for trapping and handling conditions and errors from method calls used in redirection. This will ensure the errors get propagated to the base native activation for the command call.
Definition at line 62 of file InputRedirector.cpp.
Constructor & Destructor Documentation
RedirectionDispatcher()
RedirectionDispatcher::RedirectionDispatcher (TrapInvoker & t) inline
Definition at line 65 of file InputRedirector.cpp.
~RedirectionDispatcher()
virtual RedirectionDispatcher::~RedirectionDispatcher () inline virtual
Definition at line 69 of file InputRedirector.cpp.
Member Function Documentation
handleError()
virtual void RedirectionDispatcher::handleError (DirectoryClass * c) inline virtual
Default handler for any error conditions. This just sets the condition information in the dispatch unit.
Parameters
c The condition information for the error.
Reimplemented from TrappingDispatcher.
Definition at line 71 of file InputRedirector.cpp.
References TrappingDispatcher::activation, DirectoryClass::get(), ActivationBase::getPreviousStackFrame(), ConditionTrappingDispatcher::handleError(), and RexxString::strCompare().
The documentation for this class was generated from the following file:
InputRedirector.cpp