ooRexx: StemClass Class Reference
StemClass Class Reference
#include <StemClass.hpp>
Public Member Functions
void * operator new (size_t)
StemClass (RexxString *)
StemClass (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
void processUnknown (RexxErrorCodes error, RexxString *, RexxObject **, size_t, ProtectedObject &) override
void copyFrom (CompoundVariableTable &_tails)
bool numberValue (wholenumber_t &result, wholenumber_t precision) override
bool numberValue (wholenumber_t &result) override
bool unsignedNumberValue (size_t &result, wholenumber_t precision) override
bool unsignedNumberValue (size_t &result) override
bool doubleValue (double &result) override
NumberString * numberString () override
RexxInteger * integerValue (wholenumber_t) override
RexxString * stringValue () override
RexxString * makeString () override
ArrayClass * makeArray () override
ArrayClass * allItems ()
ArrayClass * allIndexes ()
SupplierClass * supplier ()
DirectoryClass * toDirectory ()
RexxObject * request (RexxString *)
RexxObject * empty ()
RexxObject * isEmptyRexx ()
bool isEmpty ()
size_t items ()
void dropValue ()
RexxInternalObject * getStemValue ()
RexxInternalObject * bracket (RexxObject **, size_t)
RexxObject * bracketEqual (RexxObject **, size_t)
RexxObject * hasIndex (RexxObject **, size_t)
RexxInternalObject * remove (RexxObject **, size_t)
RexxObject * hasItem (RexxInternalObject *)
RexxObject * index (RexxInternalObject *)
RexxObject * itemsRexx ()
RexxObject * unknownRexx (RexxString *message, ArrayClass *arguments)
RexxInternalObject * removeItem (RexxInternalObject *)
RexxInternalObject * removeItemRexx (RexxObject *)
RexxString * tail (ArrayClass *, size_t)
RexxObject * newRexx (RexxObject **, size_t)
RexxObject * evaluateCompoundVariableValue (RexxActivation *context, RexxString *stemVariableName, CompoundVariableTail &resolved_tail)
RexxObject * getCompoundVariableValue (CompoundVariableTail &resolved_tail)
RexxObject * getCompoundVariableRealValue (CompoundVariableTail &resolved_tail)
RexxObject * realCompoundVariableValue (CompoundVariableTail &resolved_tail)
CompoundTableElement * getCompoundVariable (CompoundVariableTail &name)
CompoundTableElement * exposeCompoundVariable (CompoundVariableTail &name)
CompoundTableElement * findCompoundVariable (CompoundVariableTail &name)
CompoundTableElement * findByValue (RexxInternalObject *target)
void dropCompoundVariable (CompoundVariableTail &name)
void setCompoundVariable (CompoundVariableTail &name, RexxObject *value)
void setValue (RexxObject *value)
ArrayClass * tailArray ()
RexxObject * handleNovalue (RexxActivation *context, RexxString *name, RexxObject *defaultValue, CompoundTableElement *variable)
void expose (CompoundTableElement *variable)
bool sort (RexxString *prefix, int order, int type, size_t start, size_t end, size_t firstcol, size_t lastcol)
void mergeSort (SortData *sd, int(*comparator)(SortData *, RexxString *, RexxString *), RexxString **strings, RexxString **working, size_t left, size_t right)
void merge (SortData *sd, int(*comparator)(SortData *, RexxString *, RexxString *), RexxString **strings, RexxString **working, size_t left, size_t mid, size_t right)
size_t find (SortData *sd, int(*comparator)(SortData *, RexxString *, RexxString *), RexxString **strings, RexxString *val, int bnd, size_t left, size_t right)
void arraycopy (RexxString **source, size_t start, RexxString **target, size_t index, size_t count)
bool compoundVariableExists (CompoundVariableTail &resolved_tail)
RexxString * getName ()
RexxObject * getValue ()
CompoundTableElement * first ()
RexxString * createCompoundName (CompoundVariableTail &tailPart)
void init ()
bool hasValue ()
void setElement (const char *tail, RexxObject *value)
void setElement (size_t tail, RexxObject *value)
void dropElement (const char *tail)
void dropElement (size_t tail)
void dropElement (CompoundVariableTail &tail)
RexxObject * getElement (size_t tail)
RexxObject * getElement (const char *tail)
RexxObject * getElement (CompoundVariableTail &tail)
RexxObject * getFullElement (size_t tail)
RexxObject * getFullElement (CompoundVariableTail &tail)
CompoundVariableTable::TableIterator iterator ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
HashCode hash () override
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
RexxString * stemName
CompoundVariableTable tails
RexxObject * value
bool dropped
Friends
class CompoundVariableTable
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Implementation of a Stem Object.
Definition at line 65 of file StemClass.hpp.
Constructor & Destructor Documentation
StemClass() [1/2]
StemClass::StemClass (RexxString * name)
Initialize a stem instance.
Parameters
name The name of the stem (optional)
Definition at line 118 of file StemClass.cpp.
References ARG_ONE, dropped, CompoundVariableTable::init(), optionalStringArgument(), stemName, tails, and value.
Referenced by newRexx().
StemClass() [2/2]
StemClass::StemClass (RESTORETYPE restoreType) inline
Definition at line 72 of file StemClass.hpp.
Member Function Documentation
allIndexes()
ArrayClass * StemClass::allIndexes ()
Create an array of all indexes of the stem.
Returns
An array of all tail names used in the stem.
Definition at line 1095 of file StemClass.cpp.
References tailArray().
Referenced by MemoryObject::createImage().
allItems()
ArrayClass * StemClass::allItems ()
Return all items in the stem.
Returns
An array of all items in the stem.
Definition at line 986 of file StemClass.cpp.
References CompoundVariableTable::first(), RexxVariable::getVariableValue(), items(), new_array(), CompoundVariableTable::next(), OREF_NULL, ArrayClass::put(), and tails.
Referenced by MemoryObject::createImage().
arraycopy()
void StemClass::arraycopy (RexxString ** source, size_t start, RexxString ** target, size_t index, size_t count)
copy segments of one array into another.
Parameters
source The source array
start The starting index of the source copy
target The target array
index The target copy index
count The number of items to count.
Definition at line 1515 of file StemClass.cpp.
References index(), and RexxObject::start().
Referenced by merge().
bracket()
RexxInternalObject * StemClass::bracket (RexxObject ** tailElements, size_t argCount)
Perform a lookup on a stem object.
Parameters
tailElements The array of tail elements used to construct the tail. All tail elements are constants at this point.
argCount The count of tail arguments.
Returns
The compound variable lookup value.
Definition at line 295 of file StemClass.cpp.
References evaluateCompoundVariableValue(), OREF_NULL, stemName, and value.
Referenced by MemoryObject::createImage().
bracketEqual()
RexxObject * StemClass::bracketEqual (RexxObject ** tailElements, size_t argCount)
Resolve the "stem.[a,b,c]=" to the equivalent stem.a.b.c= form, with all of the indices taken as constants
Parameters
tailElements The array of arguments. the first argument is the assigned value. All additional arguments are the tail pieces.
argCount The count of arguments.
Returns
Returns nothing.
Definition at line 465 of file StemClass.cpp.
References ARG_ONE, CompoundVariableTable::clear(), dropped, Error_Execution_nostem, Error_Incorrect_method_noarg, getCompoundVariable(), IntegerOne, isStem(), OREF_NULL, reportException(), requiredArgument(), RexxVariable::set(), setField, tails, and value.
Referenced by MemoryObject::createImage().
compoundVariableExists()
bool StemClass::compoundVariableExists (CompoundVariableTail & resolved_tail) inline
Definition at line 139 of file StemClass.hpp.
References OREF_NULL, and realCompoundVariableValue().
Referenced by RexxActivation::localCompoundVariableExists().
copy()
RexxInternalObject * StemClass::copy () override virtual
Copy a stem collection object.
Returns
A copy of the stem object.
Reimplemented from RexxObject.
Definition at line 137 of file StemClass.cpp.
References RexxObject::copy(), and tails.
copyFrom()
void StemClass::copyFrom (CompoundVariableTable & source)
Copy the tails from another stem object into this stem.
Parameters
source The source tail collection.
Definition at line 152 of file StemClass.cpp.
References CompoundVariableTable::copyFrom(), CompoundVariableTable::init(), and tails.
createCompoundName()
RexxString * StemClass::createCompoundName (CompoundVariableTail & tailPart)
Create a full compound name from a constructed compound taile.
Parameters
tailPart The constructed tail element.
Returns
The fully resolved string name of the element.
Definition at line 1339 of file StemClass.cpp.
References CompoundVariableTail::createCompoundName(), and stemName.
createInstance()
void StemClass::createInstance () static
Create initial class object at bootstrap time.
Definition at line 65 of file StemClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
doubleValue()
bool StemClass::doubleValue (double & result) override virtual
Convert the stem default value to a numeric value.
Parameters
result the place to put the converted number.
Returns
true if this converted, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 596 of file StemClass.cpp.
References RexxInternalObject::doubleValue(), and value.
dropCompoundVariable()
void StemClass::dropCompoundVariable (CompoundVariableTail & name)
Mark a variable as dropped.
Parameters
name The target compound name.
Definition at line 734 of file StemClass.cpp.
References RexxVariable::drop(), and getCompoundVariable().
Referenced by VariableDictionary::dropCompoundVariable(), and RexxActivation::dropLocalCompoundVariable().
dropElement() [1/3]
void StemClass::dropElement (CompoundVariableTail & resolved_tail)
Drop an element using a resolved tail value.
Parameters
resolved_tail The target tail element.
Definition at line 1322 of file StemClass.cpp.
References RexxVariable::drop(), findCompoundVariable(), and OREF_NULL.
dropElement() [2/3]
void StemClass::dropElement (const char * tail)
Drop an array element for an API class.
Parameters
tail The direct tail value.
Definition at line 1309 of file StemClass.cpp.
References tail().
Referenced by dropElement().
dropElement() [3/3]
void StemClass::dropElement (size_t tail)
Drop an array element for an API class.
Parameters
tail The direct tail value.
Definition at line 1298 of file StemClass.cpp.
References dropElement(), and tail().
dropValue()
void StemClass::dropValue ()
Drop the stem value and revert to the default initial name.
Definition at line 223 of file StemClass.cpp.
References dropped, setField, stemName, and value.
empty()
RexxObject * StemClass::empty ()
Empty the stem. This also clears dropped and exposed tails,
Returns
Nothing.
Definition at line 1060 of file StemClass.cpp.
References CompoundVariableTable::clear(), and tails.
Referenced by MemoryObject::createImage(), and StemOutputTarget::init().
evaluateCompoundVariableValue()
RexxObject * StemClass::evaluateCompoundVariableValue (RexxActivation * context, RexxString * stemVariableName, CompoundVariableTail & resolved_tail)
Retrieve a compound variable, returning the default value if the variable does not exist. This includes NOVALUE handling.
Parameters
context The current execution context.
stemVariableName The name of the stem variable (needed to compose default value)
resolved_tail The resolved tail.
Returns
The variable value.
Definition at line 790 of file StemClass.cpp.
References CompoundVariableTail::createCompoundName(), dropped, findCompoundVariable(), RexxVariable::getVariableValue(), handleNovalue(), OREF_NULL, stemName, and value.
Referenced by bracket(), RexxActivation::evaluateLocalCompoundVariable(), and VariableDictionary::getCompoundVariableValue().
expose()
void StemClass::expose (CompoundTableElement * old_variable)
Complete a hook up for exposing a compound variable.
Parameters
old_variable The old variable entry in the orignal stem.
Definition at line 972 of file StemClass.cpp.
References CompoundVariableTable::findEntry(), RexxVariable::getName(), new_variable(), and tails.
Referenced by RexxCompoundVariable::expose(), and RexxCompoundVariable::procedureExpose().
exposeCompoundVariable()
CompoundTableElement * StemClass::exposeCompoundVariable (CompoundVariableTail & name)
Perform an expose operation on a Compound variable.
Parameters
name The compound tail name.
Returns
The corresponding table element.
Definition at line 681 of file StemClass.cpp.
References dropped, CompoundVariableTable::findEntry(), RexxVariable::getVariableValue(), OREF_NULL, CompoundTableElement::realVariable(), RexxVariable::set(), tails, and value.
Referenced by RexxCompoundVariable::expose(), and RexxActivation::exposeLocalCompoundVariable().
find()
size_t StemClass::find (SortData * sd, int(*)(SortData *, RexxString *, RexxString *) comparator, RexxString ** strings, RexxString * val, int limit, size_t left, size_t right)
Finds the place in the given range of specified sorted array, where the element should be inserted for getting sorted array. Uses exponential search algorithm.
Parameters
sd The sort descriptor
comparator The comparator used to compare pairs of elements.
strings The input set of strings.
val object to be inserted
bnd possible values 0,-1. "-1" - val is located at index more then elements equals to val. "0" - val is located at index less then elements equals to val.
left The left bound of the insert operation.
right The right bound for the insert.
Returns
The insertion point.
Definition at line 1541 of file StemClass.cpp.
Referenced by merge().
findByValue()
CompoundTableElement * StemClass::findByValue (RexxInternalObject * target)
Locate a stem item by value.
Returns
The compound item for the located element.
Definition at line 1013 of file StemClass.cpp.
References RexxInternalObject::equalValue(), CompoundVariableTable::first(), RexxVariable::getVariableValue(), CompoundVariableTable::next(), OREF_NULL, and tails.
Referenced by hasItem(), index(), and removeItem().
findCompoundVariable()
CompoundTableElement * StemClass::findCompoundVariable (CompoundVariableTail & name)
Get an item from the variable dictionary, without creating a new variable if it doesn't exist.
Parameters
name The target tail name.
Returns
the target table element, or OREF_NULL if the variable doesn't exist.
Definition at line 717 of file StemClass.cpp.
References CompoundVariableTable::findEntry(), OREF_NULL, CompoundTableElement::realVariable(), and tails.
Referenced by dropElement(), evaluateCompoundVariableValue(), getCompoundVariableRealValue(), getCompoundVariableValue(), getElement(), getFullElement(), hasIndex(), realCompoundVariableValue(), remove(), and sort().
first()
CompoundTableElement* StemClass::first () inline
Definition at line 142 of file StemClass.hpp.
References CompoundVariableTable::first(), and tails.
flatten()
void StemClass::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxObject.
Definition at line 195 of file StemClass.cpp.
References cleanUpFlatten, flattenCompoundTable, flattenRef, setUpFlatten, stemName, and value.
getCompoundVariable()
CompoundTableElement * StemClass::getCompoundVariable (CompoundVariableTail & name)
Get an item from the variable dictionary, adding a new empty variable entry if it wasn't found.
Parameters
name The target tail name.
Returns
The variable object corresponding to the the variable entry.
Definition at line 668 of file StemClass.cpp.
References CompoundVariableTable::findEntry(), CompoundTableElement::realVariable(), and tails.
Referenced by bracketEqual(), dropCompoundVariable(), VariableDictionary::getCompoundVariable(), RexxActivation::getLocalCompoundVariable(), setCompoundVariable(), and setElement().
getCompoundVariableRealValue()
RexxObject * StemClass::getCompoundVariableRealValue (CompoundVariableTail & resolved_tail)
Evaluate the real value of a compound variable. The real value is either its explicitly assigned value or a stem assigned value. This returns OREF_NULL if neither is available. This does not raise NOVALUE conditions.
Parameters
resolved_tail The target tail value.
Returns
The variable value, or OREF_NULL if the variable does not have an explicit value.
Definition at line 887 of file StemClass.cpp.
References dropped, findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, and value.
Referenced by VariableDictionary::getCompoundVariableRealValue(), and RexxActivation::getLocalCompoundVariableRealValue().
getCompoundVariableValue()
RexxObject * StemClass::getCompoundVariableValue (CompoundVariableTail & resolved_tail)
Retrieve a compound variable, returning the default value if the variable does not exist. This does NOT raise NOVALUE conditions
Parameters
resolved_tail The resolved compound tail.
Returns
The variable value, or OREF_NULL if the variable is not set.
Definition at line 846 of file StemClass.cpp.
References CompoundVariableTail::createCompoundName(), dropped, findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, stemName, and value.
Referenced by RexxActivation::getLocalCompoundVariableValue().
getElement() [1/3]
RexxObject * StemClass::getElement (CompoundVariableTail & resolved_tail)
Resolve a compound variable as a result of an api call.
Parameters
resolved_tail The resolved tail value.
Returns
The variable value. Returns OREF_NULL if not assigned or dropped.
Definition at line 1240 of file StemClass.cpp.
References findCompoundVariable(), RexxVariable::getVariableValue(), and OREF_NULL.
getElement() [2/3]
RexxObject * StemClass::getElement (const char * tail)
Evaluate an array element for an API class.
Parameters
tail The direct tail value.
Returns
The object value. If the stem element does not exist or has been dropped, this returns OREF_NULL.
Definition at line 1223 of file StemClass.cpp.
References getElement(), and tail().
getElement() [3/3]
RexxObject * StemClass::getElement (size_t tail)
Evaluate an array element for an API class.
Parameters
tail The direct tail value.
Returns
The object value. If the stem element does not exist or has been dropped, this returns OREF_NULL.
Definition at line 1207 of file StemClass.cpp.
References tail().
Referenced by getElement(), StemInputSource::init(), StemOutputTarget::init(), and toUnicode().
getFullElement() [1/2]
RexxObject * StemClass::getFullElement (CompoundVariableTail & resolved_tail)
Resolve a compound variable as a result of an api call.
Parameters
resolved_tail The resolved tail value.
Returns
The variable value. Returns default value if not assigned or dropped.
Definition at line 1278 of file StemClass.cpp.
References findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, and value.
getFullElement() [2/2]
RexxObject * StemClass::getFullElement (size_t tail)
Evaluate an array element including default value resolution
Parameters
tail The direct tail value.
Returns
The object value. If the stem element does not exist or has been dropped, this returns the default value.
Definition at line 1261 of file StemClass.cpp.
References tail().
Referenced by StemInputSource::read().
getName()
RexxString* StemClass::getName () inline
Definition at line 140 of file StemClass.hpp.
References stemName.
Referenced by StemInputSource::init(), StemOutputTarget::init(), and remove().
getStemValue()
RexxInternalObject * StemClass::getStemValue ()
Retrieve the assigned stem value.
Returns
The default stem value.
Definition at line 236 of file StemClass.cpp.
References value.
getValue()
RexxObject* StemClass::getValue () inline
Definition at line 141 of file StemClass.hpp.
References value.
Referenced by RexxVariable::isAliasable().
handleNovalue()
RexxObject * StemClass::handleNovalue (RexxActivation * context, RexxString * name, RexxObject * defaultValue, CompoundTableElement * variable)
Process a nonvalue condition for a stem variable retrieval. If a context is provided, the novalue is handled in its context.
Parameters
context The variable context.
name The fully resolved variable name.
defaultValue The default value to use.
variable The variable entry
Returns
Either the name, or a novalue handler replacement value.
Definition at line 952 of file StemClass.cpp.
References RexxActivation::handleNovalueEvent(), and OREF_NULL.
Referenced by evaluateCompoundVariableValue().
hasIndex()
RexxObject * StemClass::hasIndex (RexxObject ** tailElements, size_t argCount)
Test if this compound variable has a given index.
Parameters
tails The set of tail expressions.
argCount The argument count
Returns
True if the fully resolved tail exists in the stem, false otherwise.
Definition at line 317 of file StemClass.cpp.
References booleanObject(), findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, and TheTrueObject.
Referenced by MemoryObject::createImage().
hasItem()
RexxObject * StemClass::hasItem (RexxInternalObject * target)
Search for any index that matches the target object.
Parameters
target The object of interest.
Returns
.true if the object is in the collection, .false otherwise.
Definition at line 377 of file StemClass.cpp.
References booleanObject(), findByValue(), and OREF_NULL.
Referenced by MemoryObject::createImage().
hasValue()
bool StemClass::hasValue () inline
Definition at line 145 of file StemClass.hpp.
References dropped.
Referenced by VariableDictionary::VariableIterator::VariableIterator().
index()
RexxObject * StemClass::index (RexxInternalObject * target)
Return the index for a target item.
Parameters
target The target object.
Returns
The tail name for the match, or .nil if it was not found.
Definition at line 430 of file StemClass.cpp.
References findByValue(), RexxVariable::getName(), OREF_NULL, and TheNilObject.
Referenced by arraycopy(), and MemoryObject::createImage().
init()
void StemClass::init () inline
Definition at line 144 of file StemClass.hpp.
References CompoundVariableTable::init(), and tails.
integerValue()
RexxInteger * StemClass::integerValue (wholenumber_t precision) override virtual
Convert the stem to an integer value.
Parameters
precision The precision to convert under.
Returns
The Integer object or OREF_NULL if not valid.
Reimplemented from RexxInternalObject.
Definition at line 620 of file StemClass.cpp.
References RexxInternalObject::integerValue(), and value.
isEmpty()
bool StemClass::isEmpty ()
Test if the stem is empty.
Returns
True if the stem is empty, false otherwise.
Definition at line 1083 of file StemClass.cpp.
References items().
Referenced by RexxVariable::isAliasable(), and isEmptyRexx().
isEmptyRexx()
RexxObject * StemClass::isEmptyRexx ()
Test if the stem is empty.
Returns
True if the stem is empty, false otherwise.
Definition at line 1072 of file StemClass.cpp.
References booleanObject(), and isEmpty().
Referenced by MemoryObject::createImage().
items()
size_t StemClass::items ()
Get the count of non-dropped items in the stem.
Returns
The number of non-dropped items.
Definition at line 1035 of file StemClass.cpp.
References CompoundVariableTable::first(), RexxVariable::getVariableValue(), CompoundVariableTable::next(), OREF_NULL, and tails.
Referenced by allItems(), isEmpty(), itemsRexx(), and tailArray().
itemsRexx()
RexxObject * StemClass::itemsRexx ()
Return the number of items set in the collection.
Returns
The count of items in the collection, not counting the default value.
Definition at line 447 of file StemClass.cpp.
References items(), and new_integer().
Referenced by MemoryObject::createImage().
iterator()
CompoundVariableTable::TableIterator StemClass::iterator ()
Retrieve an iterator for the stem object.
Returns
An iterator for traversing the stem object.
Definition at line 1747 of file StemClass.cpp.
References CompoundVariableTable::iterator(), and tails.
Referenced by VariableDictionary::VariableIterator::VariableIterator().
live()
void StemClass::live (size_t liveMark) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxObject.
Definition at line 167 of file StemClass.cpp.
References markCompoundTable, memory_mark, stemName, and value.
liveGeneral()
void StemClass::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxObject.
Definition at line 181 of file StemClass.cpp.
References markGeneralCompoundTable, memory_mark_general, stemName, and value.
makeArray()
ArrayClass * StemClass::makeArray () override virtual
Extract an array of tail items.
Returns
An array of all tails in the stem.
Reimplemented from RexxInternalObject.
Definition at line 517 of file StemClass.cpp.
References tailArray().
Referenced by request().
makeString()
RexxString * StemClass::makeString () override virtual
Handle a primitive-level MAKESTRING request by forwarding it to the default value.
Returns
Reimplemented from RexxInternalObject.
Definition at line 506 of file StemClass.cpp.
References RexxInternalObject::makeString(), and value.
merge()
void StemClass::merge (SortData * sd, int(*)(SortData *, RexxString *, RexxString *) comparator, RexxString ** strings, RexxString ** working, size_t left, size_t mid, size_t right)
Perform a merge of two sort partitions.
Parameters
sd The sort descriptor.
comparator The comparator used to compare elements.
strings The input strings.
working A working array used for the merge operations.
left The left bound for the merge.
mid The midpoint for the merge.
right The right bound of merge (inclusive).
Definition at line 1446 of file StemClass.cpp.
References arraycopy(), and find().
Referenced by mergeSort().
mergeSort()
void StemClass::mergeSort (SortData * sd, int(*)(SortData *, RexxString *, RexxString *) comparator, RexxString ** strings, RexxString ** working, size_t left, size_t right)
The merge sort routine. This will partition the data in to two sections, mergesort each partition, then merge the two partitions together.
Parameters
sd The sort information.
comparator The comparator object used for the compares.
strings The input set of strings.
working The working array (same size as the sorted array).
left The left bound of the partition.
right The right bounds of the parition.
Definition at line 1409 of file StemClass.cpp.
References merge().
Referenced by sort().
newRexx()
RexxObject * StemClass::newRexx (RexxObject ** init_args, size_t argCount)
Allocate a new Stem object from Rexx code.
Parameters
init_args The standard variable argument pointer.
argCount The count of arguments.
Returns
A new stem instance.
Definition at line 92 of file StemClass.cpp.
References RexxClass::completeNewObject(), RexxClass::processNewArgs(), and StemClass().
Referenced by MemoryObject::createImage().
numberString()
NumberString * StemClass::numberString () override virtual
Convert this stem object to a number string value.
Returns
A number string object, or OREF_NULL if non-numeric
Reimplemented from RexxInternalObject.
Definition at line 607 of file StemClass.cpp.
References RexxInternalObject::numberString(), and value.
numberValue() [1/2]
bool StemClass::numberValue (wholenumber_t & result) override virtual
Convert the stem default value to a numeric value.
Parameters
result the place to put the converted number.
Returns
true if this converted, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 556 of file StemClass.cpp.
References RexxInternalObject::numberValue(), and value.
numberValue() [2/2]
bool StemClass::numberValue (wholenumber_t & result, wholenumber_t digits) override virtual
Convert the stem default value to a numeric value.
Parameters
result the place to put the converted number.
digits The precision to convert under.
Returns
true if this converted, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 543 of file StemClass.cpp.
References RexxInternalObject::numberValue(), and value.
operator new()
void * StemClass::operator new (size_t size)
Allocate memory for a new stem instance.
Parameters
size The size of the object.
Returns
Backing storage for an object.
Definition at line 78 of file StemClass.cpp.
References new_object(), and T_Stem.
processUnknown()
void StemClass::processUnknown (RexxErrorCodes error, RexxString * messageName, RexxObject ** arguments, size_t count, ProtectedObject & result) override virtual
Process an unknown message condition on an object. This is an optimized bypass for the Object default method that can bypass creating an array for the arguments and sending the UNKNOWN message to the object. Since many things funnel through the integer unknown method, this is a big optimization.
Parameters
messageName The target message name.
arguments The message arguments.
count The count of arguments.
result The return result protected object.
Reimplemented from RexxObject.
Definition at line 277 of file StemClass.cpp.
References RexxObject::messageSend(), and value.
realCompoundVariableValue()
RexxObject * StemClass::realCompoundVariableValue (CompoundVariableTail & resolved_tail)
Retrieve a compound variable, returning the default value if the variable does not exist. This does not handle NOVALUEs.
Parameters
resolved_tail The resolved tail.
Returns
The real assigned value (no default processing)
Definition at line 918 of file StemClass.cpp.
References dropped, findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, and value.
Referenced by compoundVariableExists().
remove()
RexxInternalObject * StemClass::remove (RexxObject ** tailElements, size_t argCount)
Remove an item from the collection. This is essentially equivalent to a drop operation on the stem variable.
Parameters
tails The set of tail indexes.
argCount The number of indexes.
Returns
The removed object. If nothing was removed, this returns .nil.
Definition at line 343 of file StemClass.cpp.
References RexxVariable::drop(), findCompoundVariable(), getName(), RexxVariable::getVariableValue(), OREF_NULL, setField, TheNilObject, and value.
Referenced by MemoryObject::createImage().
removeItem()
RexxInternalObject * StemClass::removeItem (RexxInternalObject * target)
Remove the target object from the stem.
Parameters
target The target object.
Returns
The removed object (same as target).
Definition at line 407 of file StemClass.cpp.
References RexxVariable::drop(), findByValue(), RexxVariable::getVariableValue(), OREF_NULL, and TheNilObject.
Referenced by removeItemRexx().
removeItemRexx()
RexxInternalObject * StemClass::removeItemRexx (RexxObject * target)
Remove the target object from the stem.
Parameters
target The target object.
Returns
The removed object (same as target).
Definition at line 391 of file StemClass.cpp.
References ARG_ONE, removeItem(), and requiredArgument().
Referenced by MemoryObject::createImage().
request()
RexxObject * StemClass::request (RexxString * requestclass)
Forward all request requests to the target value. We handle some of these directly, the rest are passed on to the default value.
Parameters
requestclass The name of the class for the request.
Returns
The appropriate result for the request.
Definition at line 635 of file StemClass.cpp.
References ARG_ONE, isStem(), makeArray(), RexxObject::sendMessage(), stringArgument(), RexxString::upper(), and value.
Referenced by MemoryObject::createImage().
setCompoundVariable()
void StemClass::setCompoundVariable (CompoundVariableTail & name, RexxObject * newValue)
Set a new variable value
Parameters
name The target name.
newValue The new value to assign.
Definition at line 747 of file StemClass.cpp.
References getCompoundVariable(), and RexxVariable::set().
Referenced by RexxActivation::assignLocalCompoundVariable(), VariableDictionary::setCompoundVariable(), and RexxActivation::setLocalCompoundVariable().
setElement() [1/2]
void StemClass::setElement (const char * tail, RexxObject * newValue)
Set a single stem variable object using a simple string value tail as a result of an api call.
Parameters
tail The index of the target value.
value The new value to assign.
Definition at line 1176 of file StemClass.cpp.
References getCompoundVariable(), RexxVariable::set(), and tail().
Referenced by StemOutputTarget::init(), toUnicode(), and StemOutputTarget::writeLine().
setElement() [2/2]
void StemClass::setElement (size_t tail, RexxObject * newValue)
Set a single stem variable object using a simple string value tail as a result of an api call.
Parameters
tail The index of the target value.
value The new value to assign.
Definition at line 1191 of file StemClass.cpp.
References getCompoundVariable(), RexxVariable::set(), and tail().
setValue()
void StemClass::setValue (RexxObject * newValue)
Set a new stem default value.
Parameters
_value The new value to set.
Definition at line 213 of file StemClass.cpp.
References dropped, setField, and value.
Referenced by RexxVariable::setStem().
sort()
bool StemClass::sort (RexxString * prefix, int order, int type, size_t _first, size_t last, size_t firstcol, size_t lastcol)
Sort elements of a stem variable as if it was an array. This routine assumes that element ".0" of the stem contains a size value for the array portion of the elements, and that tail indices ".start" to ".end", inclusive all exist in the tail. Sorting will be performed on the string values of all elements, and in the final result, all values will be replaced by the string values.
Parameters
prefix
order
type
_first
last
firstcol
lastcol
Returns
Definition at line 1605 of file StemClass.cpp.
References SortData::columnLength, compare_asc(), compare_asc_cols(), compare_asc_i(), compare_asc_i_cols(), compare_desc(), compare_desc_cols(), compare_desc_i(), compare_desc_i_cols(), ArrayClass::data(), Numerics::DEFAULT_DIGITS, Error_Incorrect_call_stem_range, Error_Incorrect_call_stem_size, Error_Incorrect_call_stem_sparse_array, findCompoundVariable(), ArrayClass::get(), RexxVariable::getVariableValue(), Numerics::MAX_WHOLENUMBER, mergeSort(), new_array(), OREF_NULL, ArrayClass::put(), reportException(), RexxInternalObject::requestString(), RexxVariable::set(), SORT_ASCENDING, SORT_CASEIGNORE, SORT_CASESENSITIVE, SortData::startColumn, type, and RexxInternalObject::unsignedNumberValue().
Referenced by RexxStemVariable::sort(), and NativeActivation::stemSort().
stringValue()
RexxString * StemClass::stringValue () override virtual
Get the string value for the stem, which is just the string value of our default value.
Returns
The associated string value.
Reimplemented from RexxObject.
Definition at line 529 of file StemClass.cpp.
References RexxObject::stringValue(), and value.
supplier()
SupplierClass * StemClass::supplier ()
Create a supplier for the stem, returning the tail names as the indexes and the values as the items.
Returns
A supplier instance.
Definition at line 1107 of file StemClass.cpp.
References CompoundVariableTable::first(), RexxVariable::getName(), RexxVariable::getVariableValue(), new_array(), new_supplier(), CompoundVariableTable::next(), OREF_NULL, ArrayClass::put(), and tails.
Referenced by MemoryObject::createImage().
tail()
RexxString* StemClass::tail (ArrayClass * , size_t)
Referenced by dropElement(), getElement(), getFullElement(), and setElement().
tailArray()
ArrayClass * StemClass::tailArray ()
Return all indices as an array
Returns
An array of the assigned tails.
Definition at line 759 of file StemClass.cpp.
References ArrayClass::append(), CompoundVariableTable::first(), RexxVariable::getName(), RexxVariable::getVariableValue(), items(), new_array(), CompoundVariableTable::next(), OREF_NULL, and tails.
Referenced by allIndexes(), and makeArray().
toDirectory()
DirectoryClass * StemClass::toDirectory ()
Create a directory from the stem. Each tail with an assigned value will be an entry within the directory.
Returns
A directory instance.
Definition at line 1150 of file StemClass.cpp.
References CompoundVariableTable::first(), RexxVariable::getName(), RexxVariable::getVariableValue(), new_directory(), CompoundVariableTable::next(), OREF_NULL, DirectoryClass::put(), and tails.
Referenced by MemoryObject::createImage().
unknownRexx()
RexxObject * StemClass::unknownRexx (RexxString * message, ArrayClass * arguments)
Process UNKNOWN messages for a string hash collection object, forwarding them to the string value. We need this and processUnknown because the collections are documented as having an UNKNKOWN method.
Parameters
message The message target.
arguments The message arguments.
Returns
The message result.
Definition at line 253 of file StemClass.cpp.
References ARG_ONE, ARG_TWO, arrayArgument(), RexxObject::sendMessage(), stringArgument(), and value.
Referenced by MemoryObject::createImage().
unsignedNumberValue() [1/2]
bool StemClass::unsignedNumberValue (size_t & result) override virtual
Convert the stem default value to a numeric value.
Parameters
result the place to put the converted number.
Returns
true if this converted, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 583 of file StemClass.cpp.
References RexxInternalObject::unsignedNumberValue(), and value.
unsignedNumberValue() [2/2]
bool StemClass::unsignedNumberValue (size_t & result, wholenumber_t digits) override virtual
Convert the stem default value to a numeric value.
Parameters
result the place to put the converted number.
digits The precision to convert under.
Returns
true if this converted, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 570 of file StemClass.cpp.
References RexxInternalObject::unsignedNumberValue(), and value.
Friends And Related Function Documentation
CompoundVariableTable
friend class CompoundVariableTable friend
Definition at line 67 of file StemClass.hpp.
Member Data Documentation
classInstance
RexxClass * StemClass::classInstance = OREF_NULL static
Definition at line 161 of file StemClass.hpp.
dropped
bool StemClass::dropped protected
Definition at line 168 of file StemClass.hpp.
Referenced by bracketEqual(), dropValue(), evaluateCompoundVariableValue(), exposeCompoundVariable(), getCompoundVariableRealValue(), getCompoundVariableValue(), hasValue(), realCompoundVariableValue(), setValue(), and StemClass().
stemName
RexxString* StemClass::stemName protected
Definition at line 165 of file StemClass.hpp.
Referenced by bracket(), createCompoundName(), dropValue(), evaluateCompoundVariableValue(), flatten(), getCompoundVariableValue(), getName(), live(), liveGeneral(), and StemClass().
tails
CompoundVariableTable StemClass::tails protected
Definition at line 166 of file StemClass.hpp.
Referenced by allItems(), bracketEqual(), copy(), copyFrom(), empty(), expose(), exposeCompoundVariable(), findByValue(), findCompoundVariable(), first(), getCompoundVariable(), init(), items(), iterator(), StemClass(), supplier(), tailArray(), and toDirectory().
value
RexxObject* StemClass::value protected
Definition at line 167 of file StemClass.hpp.
Referenced by bracket(), bracketEqual(), doubleValue(), dropValue(), evaluateCompoundVariableValue(), exposeCompoundVariable(), flatten(), getCompoundVariableRealValue(), getCompoundVariableValue(), getFullElement(), getStemValue(), getValue(), integerValue(), live(), liveGeneral(), makeString(), numberString(), numberValue(), processUnknown(), realCompoundVariableValue(), remove(), request(), setValue(), StemClass(), stringValue(), unknownRexx(), and unsignedNumberValue().
The documentation for this class was generated from the following files:
StemClass.hpp
StemClass.cpp