ooRexx: Interpreter Class Reference
Interpreter Class Reference
#include <Interpreter.hpp>
Public Types
enum InterpreterStartupMode { SAVE_IMAGE_MODE = 0 , RUN_MODE = 1 }
Static Public Member Functions
static void init ()
static void live (size_t)
static void liveGeneral (MarkReason reason)
static void processStartup ()
static void processShutdown ()
static void getResourceLock ()
static void releaseResourceLock ()
static void getDispatchLock ()
static void releaseDispatchLock ()
static void createLocks ()
static void closeLocks ()
static int createInstance (RexxInstance *&instance, RexxThreadContext *&threadContext, RexxOption *options)
static bool terminateInterpreter ()
static void startInterpreter (InterpreterStartupMode mode, const char *imageTarget)
static bool isTerminated ()
static bool isActive ()
static bool lastInstance ()
static InterpreterInstance * createInterpreterInstance (RexxOption *options)
static InterpreterInstance * createInterpreterInstance ()
static bool terminateInterpreterInstance (InterpreterInstance *instance)
static bool isInstanceActive (InterpreterInstance *instance)
static RexxString * getVersionString ()
static void initLocal ()
static size_t getInterpreterVersion ()
static size_t getLanguageLevel ()
static RexxString * getMessageText (wholenumber_t code)
static int getWordSize ()
static bool isBigEndian ()
static void logicError (const char *desc)
static wholenumber_t messageNumber (RexxString *)
static bool haltAllActivities (RexxString *)
static void decodeConditionData (DirectoryClass *conditionObj, RexxCondition *condData)
static RexxClass * findClass (RexxString *className)
static RexxString * getCurrentQueue ()
static RexxString * qualifyFileSystemName (RexxString *name)
Static Public Attributes
static RexxObject * localServer = OREF_NULL
static const char * languageLevel = "6.05"
Static Protected Attributes
static SysMutex resourceLock
static SysMutex dispatchLock
static int initializations
static QueueClass * interpreterInstances = OREF_NULL
static bool active = false
static RexxString * versionNumber = OREF_NULL
Detailed Description
Definition at line 58 of file Interpreter.hpp.
Member Enumeration Documentation
InterpreterStartupMode
enum Interpreter::InterpreterStartupMode
Enumerator
SAVE_IMAGE_MODE
RUN_MODE
Definition at line 61 of file Interpreter.hpp.
Member Function Documentation
closeLocks()
static void Interpreter::closeLocks () inline static
Definition at line 86 of file Interpreter.hpp.
References SysMutex::close(), dispatchLock, and resourceLock.
Referenced by processShutdown().
createInstance()
int Interpreter::createInstance (RexxInstance *& instance, RexxThreadContext *& threadContext, RexxOption * options) static
Create a new instance and return the instance context pointers and thread context pointer for the instance.
Parameters
instance The returned instance pointer.
threadContext The returned thread context pointer.
options Options to apply to this interpreter instance.
Returns
0 if the instance was created ok.
Definition at line 287 of file Interpreter.cpp.
References createInterpreterInstance(), Activity::deactivate(), InterpreterInstance::getInstanceContext(), InterpreterInstance::getRootActivity(), InterpreterInstance::getRootThreadContext(), Activity::releaseAccess(), and RXAPI_MEMFAIL.
Referenced by RexxCreateInterpreter().
createInterpreterInstance() [1/2]
static InterpreterInstance* Interpreter::createInterpreterInstance () inline static
Definition at line 99 of file Interpreter.hpp.
References createInterpreterInstance().
Referenced by MemoryObject::createImage(), createInstance(), createInterpreterInstance(), InstanceBlock::InstanceBlock(), and NativeContextBlock::NativeContextBlock().
createInterpreterInstance() [2/2]
InterpreterInstance * Interpreter::createInterpreterInstance (RexxOption * options) static
Create a new interpreter instance. An interpreter instance is an accessible set of threads that constitutes an interpreter environment for the purposes API access.
Parameters
exits The set of exits to use for this invocation.
defaultEnvironment The default addressible environment.
Returns
The new interpreter instance.
Definition at line 322 of file Interpreter.cpp.
References ArrayClass::append(), ActivityManager::getRootActivity(), interpreterInstances, OREF_NULL, RUN_MODE, and startInterpreter().
createLocks()
static void Interpreter::createLocks () inline static
Definition at line 79 of file Interpreter.hpp.
References SysMutex::create(), dispatchLock, and resourceLock.
Referenced by processStartup().
decodeConditionData()
void Interpreter::decodeConditionData (DirectoryClass * conditionObj, RexxCondition * condData) static
Decode a condition directory into a easier to use structure form for a native code user. This breaks the directory into its component pieces, including converting values into primitive form using just a single API call.
Parameters
conditionObj A directory object containing the condition information.
pRexxCondData The condition data structure that is populated with the condition information.
Definition at line 502 of file Interpreter.cpp.
References RexxCondition::additional, RexxCondition::code, RexxCondition::conditionName, RexxCondition::description, RexxCondition::errortext, DirectoryClass::get(), RexxCondition::message, MESSAGE, messageNumber(), OREF_NULL, RexxCondition::position, RexxCondition::program, and RexxCondition::rc.
Referenced by DecodeConditionInfo().
findClass()
RexxClass * Interpreter::findClass (RexxString * className) static
Default class resolution processing done without benefit of a program context.
Parameters
className The class name.
Returns
A resolved class object (if any).
Definition at line 562 of file Interpreter.cpp.
References ActivityManager::getLocalEnvironment(), OREF_NULL, TheEnvironment, TheRexxPackage, and RexxString::upper().
Referenced by NativeActivation::findCallerClass(), BaseCode::findClass(), and NativeActivation::findClass().
getCurrentQueue()
RexxString * Interpreter::getCurrentQueue () static
Return the current queue name.
Returns
The name of the current queue.
Definition at line 599 of file Interpreter.cpp.
References ActivityManager::getLocalEnvironment(), OREF_NULL, and RexxObject::sendMessage().
Referenced by Activity::callFunctionExit(), NativeActivation::callRegisteredRoutine(), and NativeActivation::variablePoolFetchPrivate().
getDispatchLock()
static void Interpreter::getDispatchLock () inline static
Definition at line 77 of file Interpreter.hpp.
References dispatchLock, and SysMutex::request().
Referenced by DispatchSection::DispatchSection(), and DispatchSection::reacquire().
getInterpreterVersion()
size_t Interpreter::getInterpreterVersion () static
Get the interpreter version level as a binary number to be returned in the APIs.
Returns
The binary interpreter version level.
Definition at line 95 of file Version.cpp.
References REXX_CURRENT_INTERPRETER_VERSION.
Referenced by InterpreterVersion().
getLanguageLevel()
size_t Interpreter::getLanguageLevel () static
Return the current language level implemented by this interpreter version.
Returns
The current defined language level.
Definition at line 106 of file Version.cpp.
References REXX_CURRENT_LANGUAGE_LEVEL.
Referenced by LanguageLevel().
getMessageText()
RexxString * Interpreter::getMessageText (wholenumber_t code) static
Retrieve the message text for a give error code.
Parameters
code The Rexx error code
Returns
The error message associated with that code.
Definition at line 775 of file Interpreter.cpp.
References new_string(), OREF_NULL, and RexxGetErrorMessage().
Referenced by Activity::buildMessage(), BUILTIN(), Activity::createExceptionObject(), Activity::display(), Activity::displayDebug(), RexxActivation::doDebugPause(), and Activity::reraiseException().
getResourceLock()
static void Interpreter::getResourceLock () inline static
Definition at line 75 of file Interpreter.hpp.
References SysMutex::request(), and resourceLock.
Referenced by ResourceSection::reacquire(), and ResourceSection::ResourceSection().
getVersionString()
RexxString * Interpreter::getVersionString () static
Generate a version number string for the interpreter.
Returns
The interpreter version string.
Definition at line 60 of file Version.cpp.
References languageLevel, new_string(), OREF_NULL, versionNumber, and work.
Referenced by MemoryObject::createImage(), RexxInstructionParse::execute(), RexxInfo::initialize(), and NativeActivation::variablePoolFetchPrivate().
getWordSize()
static int Interpreter::getWordSize () inline static
Definition at line 108 of file Interpreter.hpp.
Referenced by ProgramMetaData::ProgramMetaData(), and ProgramMetaData::validate().
haltAllActivities()
bool Interpreter::haltAllActivities (RexxString * name) static
Tell the interpreter to have all of the instances halt its activities.
Definition at line 395 of file Interpreter.cpp.
References ArrayClass::get(), InterpreterInstance::haltAllActivities(), interpreterInstances, and ArrayClass::items().
Referenced by SystemInterpreter::processSignal(), and signalHandler().
init()
void Interpreter::init () static
Initialize the interpreter subsystem.
Definition at line 82 of file Interpreter.cpp.
References interpreterInstances, and new_queue().
Referenced by MemoryObject::createImage(), and MemoryObject::restore().
initLocal()
void Interpreter::initLocal () static
Initialize an instance .local object.
Definition at line 189 of file Interpreter.cpp.
References localServer, RexxObject::messageSend(), new_string(), and OREF_NULL.
Referenced by InterpreterInstance::initialize().
isActive()
static bool Interpreter::isActive () inline static
Definition at line 96 of file Interpreter.hpp.
References active.
Referenced by RexxHaltThread(), RexxResetThreadTrace(), RexxSetThreadTrace(), startInterpreter(), and terminateInterpreter().
isBigEndian()
static bool Interpreter::isBigEndian () inline static
Definition at line 113 of file Interpreter.hpp.
References LITEND.
Referenced by ProgramMetaData::ProgramMetaData(), and ProgramMetaData::validate().
isInstanceActive()
bool Interpreter::isInstanceActive (InterpreterInstance * instance) static
Verify that an instance pointer is if fact a valid, active instance.
Parameters
instance The instance to check
Returns
true if this is in our list, false otherwise.
Definition at line 384 of file Interpreter.cpp.
References ArrayClass::hasItem(), and interpreterInstances.
Referenced by InterpreterInstance::terminate().
isTerminated()
static bool Interpreter::isTerminated () inline static
Definition at line 95 of file Interpreter.hpp.
References active.
lastInstance()
bool Interpreter::lastInstance () static
Quick test if we're down to just a single interpreter instance.
Returns
true if we're down to a single interpreter instance.
Definition at line 270 of file Interpreter.cpp.
References interpreterInstances, and ArrayClass::items().
Referenced by InterpreterInstance::terminate().
live()
void Interpreter::live (size_t liveMark) static
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Definition at line 93 of file Interpreter.cpp.
References interpreterInstances, localServer, memory_mark, and versionNumber.
Referenced by MemoryObject::live().
liveGeneral()
void Interpreter::liveGeneral (MarkReason reason) static
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Definition at line 106 of file Interpreter.cpp.
References interpreterInstances, localServer, memory_mark_general, SAVINGIMAGE, and versionNumber.
Referenced by MemoryObject::liveGeneral().
logicError()
void Interpreter::logicError (const char * desc) static
Raise a fatal logic error
Parameters
desc The error description.
Definition at line 618 of file Interpreter.cpp.
References RC_LOGIC_ERROR.
Referenced by ListContents::allocateSlot(), HashContents::append(), DeadObjectPool::checkObjectGrain(), DeadObjectPool::checkObjectOverlap(), MemoryObject::createImage(), HashContents::insert(), MemoryObject::loadImage(), DirectoryClass::makeProxy(), MemoryObject::mark(), MarkHandler::mark(), ImageSaveMarkHandler::mark(), LibraryPackage::reload(), CPPCode::resolveExportedMethod(), and MemoryObject::temporaryObject().
messageNumber()
wholenumber_t Interpreter::messageNumber (RexxString * errorcode) static
Parse out the error code string into the messagecode value
Parameters
errorcode The string version of the error code.
Returns
The composite error code number.
Definition at line 640 of file Interpreter.cpp.
References Error_Expression_result_raise, RexxString::getLength(), RexxString::getStringData(), new_string(), RexxString::numberValue(), reportException(), and RexxString::stringValue().
Referenced by decodeConditionData(), Activity::display(), RexxInstructionRaise::execute(), and Activity::reraiseException().
processShutdown()
void Interpreter::processShutdown () static
Handle end of process shutdown.
Definition at line 132 of file Interpreter.cpp.
References ActivityManager::closeLocks(), and closeLocks().
processStartup()
void Interpreter::processStartup () static
Perform new process initialization.
Definition at line 120 of file Interpreter.cpp.
References ActivityManager::createLocks(), and createLocks().
Referenced by SystemInterpreter::processShutdown(), and SystemInterpreter::processStartup().
qualifyFileSystemName()
RexxString * Interpreter::qualifyFileSystemName (RexxString * name) static
Qualify a stream name for this system.
Parameters
name The string stream name
Returns
A string object containing the fully qualified stream name.
Definition at line 681 of file Interpreter.cpp.
References RexxString::getStringData(), and new_string().
Referenced by CommandIOConfiguration::createInputSource(), CommandIOConfiguration::createOutputTarget(), and RexxActivation::resolveStream().
releaseDispatchLock()
static void Interpreter::releaseDispatchLock () inline static
Definition at line 78 of file Interpreter.hpp.
References dispatchLock, and SysMutex::release().
Referenced by DispatchSection::release(), and DispatchSection::~DispatchSection().
releaseResourceLock()
static void Interpreter::releaseResourceLock () inline static
Definition at line 76 of file Interpreter.hpp.
References SysMutex::release(), and resourceLock.
Referenced by ResourceSection::release(), and ResourceSection::~ResourceSection().
startInterpreter()
void Interpreter::startInterpreter (InterpreterStartupMode mode, const char * imageTarget) static
Perform interpreter startup processing.
Parameters
mode The startup mode. This indicates whether we're saving the image or in shutdown mode.
Definition at line 145 of file Interpreter.cpp.
References active, MemoryObject::initialize(), interpreterInstances, isActive(), localServer, memoryObject, RexxObject::messageSend(), new_queue(), new_string(), OREF_NULL, RexxCreateSessionQueue(), RUN_MODE, SystemInterpreter::startInterpreter(), and TheRexxPackage.
Referenced by createInterpreterInstance(), RexxCreateInterpreterImage(), and RexxInitialize().
terminateInterpreter()
bool Interpreter::terminateInterpreter () static
Terminate the global interpreter environment, shutting down all of the interpreter instances that we can and releasing the object heap memory.
Returns
true if everything was shutdown, false if there are reasons why this can't be shutdown.
Definition at line 209 of file Interpreter.cpp.
References interpreterInstances, isActive(), ArrayClass::items(), MemoryObject::lastChanceUninit(), memoryObject, RexxDeleteSessionQueue(), SystemInterpreter::terminateInterpreter(), and PackageManager::unload().
Referenced by RexxCompileProgram(), RexxStart(), RexxTerminate(), and Terminate().
terminateInterpreterInstance()
bool Interpreter::terminateInterpreterInstance (InterpreterInstance * instance) static
Shutdown an interpreter instance and remove it from the list of accessible items.
Parameters
instance The instance we're shutting down.
Returns
true if this instance was in a state that could be terminated.
Definition at line 366 of file Interpreter.cpp.
References interpreterInstances, and ArrayClass::removeItem().
Referenced by InterpreterInstance::terminate().
Member Data Documentation
active
bool Interpreter::active = false static protected
Definition at line 143 of file Interpreter.hpp.
Referenced by isActive(), isTerminated(), and startInterpreter().
dispatchLock
SysMutex Interpreter::dispatchLock static protected
Definition at line 140 of file Interpreter.hpp.
Referenced by closeLocks(), createLocks(), getDispatchLock(), and releaseDispatchLock().
initializations
int Interpreter::initializations static protected
Definition at line 141 of file Interpreter.hpp.
interpreterInstances
QueueClass * Interpreter::interpreterInstances = OREF_NULL static protected
Definition at line 142 of file Interpreter.hpp.
Referenced by createInterpreterInstance(), haltAllActivities(), init(), isInstanceActive(), lastInstance(), live(), liveGeneral(), startInterpreter(), terminateInterpreter(), and terminateInterpreterInstance().
languageLevel
const char * Interpreter::languageLevel = "6.05" static
Definition at line 131 of file Interpreter.hpp.
Referenced by getVersionString(), and RexxInfo::initialize().
localServer
RexxObject * Interpreter::localServer = OREF_NULL static
Definition at line 130 of file Interpreter.hpp.
Referenced by initLocal(), live(), liveGeneral(), and startInterpreter().
resourceLock
SysMutex Interpreter::resourceLock static protected
Definition at line 139 of file Interpreter.hpp.
Referenced by closeLocks(), createLocks(), getResourceLock(), and releaseResourceLock().
versionNumber
RexxString * Interpreter::versionNumber = OREF_NULL static protected
Definition at line 144 of file Interpreter.hpp.
Referenced by getVersionString(), live(), and liveGeneral().
The documentation for this class was generated from the following files:
Interpreter.hpp
Interpreter.cpp
Version.cpp