ooRexx: TraceSetting Class Reference
TraceSetting Class Reference
#include <TraceSetting.hpp>
Public Types
enum TraceFlag {
traceOff , traceNormal , traceDebug , traceAll ,
traceResults , traceIntermediates , traceCommands , traceLabels ,
traceErrors , traceFailures , pauseInstructions , pauseLabels ,
pauseCommands , debugToggle
}
typedef FlagSet< TraceFlag, 32 > TraceFlags
Public Member Functions
TraceSetting ()
void clear ()
bool tracingResults () const
bool tracingIntermediates () const
bool isDebug () const
bool tracingAll () const
bool tracingErrors () const
bool tracingFailures () const
bool tracingLabels () const
bool tracingCommands () const
bool pausingInstructions () const
bool pausingLabels () const
bool pausingCommands () const
bool isDebugToggle () const
bool isTraceOff () const
void resetDebug ()
void setDebug ()
void toggleDebug ()
void setTraceOff ()
void merge (const TraceSetting &s)
void set (const TraceSetting &s)
bool isNoSetting () const
void setDefault ()
void setTraceAll ()
void setTraceCommands ()
void setTraceLabels ()
void setTraceErrors ()
void setTraceFailures ()
void setTraceNormal ()
void setTraceResults ()
void setTraceIntermediates ()
void flipDebug ()
void setDebugToggle ()
void setExternalTrace ()
RexxString * toString ()
bool parseTraceSetting (RexxString *value, char &badOption)
Static Public Attributes
static const TraceFlags defaultTraceFlags
static const TraceFlags traceAllFlags
static const TraceFlags traceResultsFlags
static const TraceFlags traceIntermediatesFlags
Protected Attributes
TraceFlags flags
Detailed Description
A class for processing different trace settings as set by the TRACE command.
Definition at line 57 of file TraceSetting.hpp.
Member Typedef Documentation
TraceFlags
typedef FlagSet<TraceFlag, 32> TraceSetting::TraceFlags
The type for trace flags. We create a few constant versions of these for simple setting and testing.
Definition at line 88 of file TraceSetting.hpp.
Member Enumeration Documentation
TraceFlag
enum TraceSetting::TraceFlag
Flag settings within the trace flags.
Enumerator
traceOff
traceNormal
traceDebug
traceAll
traceResults
traceIntermediates
traceCommands
traceLabels
traceErrors
traceFailures
pauseInstructions
pauseLabels
pauseCommands
debugToggle
Definition at line 66 of file TraceSetting.hpp.
Constructor & Destructor Documentation
TraceSetting()
TraceSetting::TraceSetting () inline
Definition at line 61 of file TraceSetting.hpp.
Member Function Documentation
clear()
void TraceSetting::clear () inline
Definition at line 97 of file TraceSetting.hpp.
References flags, and FlagSet< TEnum, TMaxFlags >::reset().
Referenced by parseTraceSetting().
flipDebug()
void TraceSetting::flipDebug () inline
Definition at line 268 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::flip(), and traceDebug.
isDebug()
bool TraceSetting::isDebug () const inline
Definition at line 100 of file TraceSetting.hpp.
References flags, and traceDebug.
Referenced by RexxActivation::inDebug(), PackageSetting::isDebug(), merge(), set(), RexxActivation::setTrace(), toggleDebug(), and toString().
isDebugToggle()
bool TraceSetting::isDebugToggle () const inline
Definition at line 109 of file TraceSetting.hpp.
References debugToggle, and flags.
Referenced by RexxActivation::setTrace().
isNoSetting()
bool TraceSetting::isNoSetting () const inline
Test if we have no explict value set.
Returns
True if all flags are off.
Definition at line 188 of file TraceSetting.hpp.
References flags, and FlagSet< TEnum, TMaxFlags >::none().
Referenced by parseTraceSetting(), and RexxActivation::setTrace().
isTraceOff()
bool TraceSetting::isTraceOff () const inline
Definition at line 110 of file TraceSetting.hpp.
References flags, and traceOff.
Referenced by merge(), parseTraceSetting(), and RexxActivation::setTrace().
merge()
void TraceSetting::merge (const TraceSetting & s) inline
Definition at line 149 of file TraceSetting.hpp.
References flags, isDebug(), isTraceOff(), setDebug(), and setTraceOff().
parseTraceSetting()
bool TraceSetting::parseTraceSetting (RexxString * value, char & badOption)
Parse a trace setting value into a decoded setting and the RexxActivation debug flag set to allow new trace settings to be processed more quickly.
Parameters
value The string source of the trace setting.
newSetting The returned setting in binary form.
debugFlags The debug flag representation of the trace setting.
Definition at line 133 of file TraceSetting.cpp.
References clear(), RexxString::getChar(), RexxString::getLength(), isNoSetting(), isTraceOff(), setDebug(), setDebugToggle(), setTraceAll(), setTraceCommands(), setTraceErrors(), setTraceFailures(), setTraceIntermediates(), setTraceLabels(), setTraceNormal(), setTraceOff(), setTraceResults(), and Utilities::toUpper().
Referenced by LanguageParser::optionsDirective(), RexxActivation::setTrace(), and LanguageParser::traceNew().
pausingCommands()
bool TraceSetting::pausingCommands () const inline
Definition at line 108 of file TraceSetting.hpp.
References flags, and pauseCommands.
Referenced by RexxActivation::pauseCommand().
pausingInstructions()
bool TraceSetting::pausingInstructions () const inline
Definition at line 106 of file TraceSetting.hpp.
References flags, and pauseInstructions.
Referenced by RexxActivation::pausingInstructions().
pausingLabels()
bool TraceSetting::pausingLabels () const inline
Definition at line 107 of file TraceSetting.hpp.
References flags, and pauseLabels.
Referenced by RexxActivation::pauseLabel().
resetDebug()
void TraceSetting::resetDebug () inline
Definition at line 113 of file TraceSetting.hpp.
References flags, pauseCommands, pauseInstructions, pauseLabels, FlagSet< TEnum, TMaxFlags >::reset(), and traceDebug.
Referenced by RexxActivation::resetDebug(), and toggleDebug().
set()
void TraceSetting::set (const TraceSetting & s) inline
Definition at line 171 of file TraceSetting.hpp.
References flags, isDebug(), and setDebug().
Referenced by RexxActivation::setTrace().
setDebug()
void TraceSetting::setDebug () inline
Definition at line 119 of file TraceSetting.hpp.
References flags, pauseCommands, pauseInstructions, pauseLabels, traceDebug, tracingAll(), tracingCommands(), and tracingLabels().
Referenced by merge(), parseTraceSetting(), set(), setExternalTrace(), and toggleDebug().
setDebugToggle()
void TraceSetting::setDebugToggle () inline
Definition at line 274 of file TraceSetting.hpp.
References debugToggle, flags, and FlagSet< TEnum, TMaxFlags >::reset().
Referenced by parseTraceSetting().
setDefault()
void TraceSetting::setDefault () inline
Definition at line 194 of file TraceSetting.hpp.
References defaultTraceFlags, flags, and FlagSet< TEnum, TMaxFlags >::reset().
Referenced by PackageSetting::setDefault(), and LanguageParser::traceNew().
setExternalTrace()
void TraceSetting::setExternalTrace () inline
Definition at line 281 of file TraceSetting.hpp.
References setDebug(), and setTraceResults().
Referenced by RexxActivation::enableExternalTrace().
setTraceAll()
void TraceSetting::setTraceAll () inline
Definition at line 203 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::reset(), and traceAllFlags.
Referenced by parseTraceSetting().
setTraceCommands()
void TraceSetting::setTraceCommands () inline
Definition at line 210 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::reset(), and traceCommands.
Referenced by parseTraceSetting().
setTraceErrors()
void TraceSetting::setTraceErrors () inline
Definition at line 226 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::reset(), traceErrors, and traceFailures.
Referenced by parseTraceSetting().
setTraceFailures()
void TraceSetting::setTraceFailures () inline
Definition at line 235 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::reset(), and traceFailures.
Referenced by parseTraceSetting().
setTraceIntermediates()
void TraceSetting::setTraceIntermediates () inline
Definition at line 260 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::reset(), and traceIntermediatesFlags.
Referenced by parseTraceSetting().
setTraceLabels()
void TraceSetting::setTraceLabels () inline
Definition at line 218 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::reset(), and traceLabels.
Referenced by parseTraceSetting().
setTraceNormal()
void TraceSetting::setTraceNormal () inline
Definition at line 243 of file TraceSetting.hpp.
References defaultTraceFlags, flags, and FlagSet< TEnum, TMaxFlags >::reset().
Referenced by parseTraceSetting().
setTraceOff()
void TraceSetting::setTraceOff () inline
Definition at line 141 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::reset(), and traceOff.
Referenced by RexxActivation::clearTraceSettings(), RexxActivation::disableExternalTrace(), merge(), parseTraceSetting(), and RexxActivation::setTrace().
setTraceResults()
void TraceSetting::setTraceResults () inline
Definition at line 252 of file TraceSetting.hpp.
References flags, FlagSet< TEnum, TMaxFlags >::reset(), and traceResultsFlags.
Referenced by parseTraceSetting(), and setExternalTrace().
toggleDebug()
void TraceSetting::toggleDebug () inline
Definition at line 128 of file TraceSetting.hpp.
References isDebug(), resetDebug(), and setDebug().
Referenced by RexxActivation::setTrace().
toString()
RexxString * TraceSetting::toString ()
Format an encoded trace setting back into human readable form.
Parameters
setting The source setting.
Returns
The string representation of the trace setting.
Definition at line 62 of file TraceSetting.cpp.
References flags, isDebug(), new_string(), traceAll, traceCommands, traceErrors, traceFailures, traceIntermediates, traceLabels, traceNormal, traceOff, and traceResults.
Referenced by PackageSetting::getTrace().
tracingAll()
bool TraceSetting::tracingAll () const inline
Definition at line 101 of file TraceSetting.hpp.
References flags, and traceAll.
Referenced by setDebug(), and RexxActivation::tracingAll().
tracingCommands()
bool TraceSetting::tracingCommands () const inline
Definition at line 105 of file TraceSetting.hpp.
References flags, and traceCommands.
Referenced by setDebug(), and RexxActivation::tracingCommands().
tracingErrors()
bool TraceSetting::tracingErrors () const inline
Definition at line 102 of file TraceSetting.hpp.
References flags, and traceErrors.
Referenced by RexxActivation::tracingErrors().
tracingFailures()
bool TraceSetting::tracingFailures () const inline
Definition at line 103 of file TraceSetting.hpp.
References flags, and traceFailures.
Referenced by RexxActivation::tracingFailures().
tracingIntermediates()
bool TraceSetting::tracingIntermediates () const inline
Definition at line 99 of file TraceSetting.hpp.
References flags, and traceIntermediates.
Referenced by RexxActivation::inheritPackageSettings(), and RexxActivation::setTrace().
tracingLabels()
bool TraceSetting::tracingLabels () const inline
Definition at line 104 of file TraceSetting.hpp.
References flags, and traceLabels.
Referenced by RexxInstructionTrace::nonDynamicTracingLabels(), setDebug(), RexxActivation::traceLabel(), and RexxActivation::tracingLabels().
tracingResults()
bool TraceSetting::tracingResults () const inline
Definition at line 98 of file TraceSetting.hpp.
References flags, and traceResults.
Referenced by RexxActivation::tracingResults().
Member Data Documentation
defaultTraceFlags
const TraceSetting::TraceFlags TraceSetting::defaultTraceFlags static
Definition at line 90 of file TraceSetting.hpp.
Referenced by setDefault(), and setTraceNormal().
flags
TraceFlags TraceSetting::flags protected
Definition at line 294 of file TraceSetting.hpp.
Referenced by clear(), flipDebug(), isDebug(), isDebugToggle(), isNoSetting(), isTraceOff(), merge(), pausingCommands(), pausingInstructions(), pausingLabels(), resetDebug(), set(), setDebug(), setDebugToggle(), setDefault(), setTraceAll(), setTraceCommands(), setTraceErrors(), setTraceFailures(), setTraceIntermediates(), setTraceLabels(), setTraceNormal(), setTraceOff(), setTraceResults(), toString(), tracingAll(), tracingCommands(), tracingErrors(), tracingFailures(), tracingIntermediates(), tracingLabels(), and tracingResults().
traceAllFlags
const TraceSetting::TraceFlags TraceSetting::traceAllFlags static
Definition at line 93 of file TraceSetting.hpp.
Referenced by setTraceAll().
traceIntermediatesFlags
const TraceSetting::TraceFlags TraceSetting::traceIntermediatesFlags static
Definition at line 95 of file TraceSetting.hpp.
Referenced by setTraceIntermediates().
traceResultsFlags
const TraceSetting::TraceFlags TraceSetting::traceResultsFlags static
Definition at line 94 of file TraceSetting.hpp.
Referenced by setTraceResults().
The documentation for this class was generated from the following files:
TraceSetting.hpp
TraceSetting.cpp