ooRexx: UseVariable Class Reference
UseVariable Class Reference
#include <UseInstruction.hpp>
Public Member Functions
void handleArgument (RexxActivation *context, ExpressionStack *stack, RexxObject *argument, size_t argumentPos, bool isStrict)
void handleReferenceArgument (RexxActivation *context, ExpressionStack *stack, RexxObject *argument, size_t argumentPos)
Public Attributes
RexxVariableBase * variable
RexxInternalObject * defaultValue
Detailed Description
Definition at line 49 of file UseInstruction.hpp.
Member Function Documentation
handleArgument()
void UseVariable::handleArgument (RexxActivation * context, ExpressionStack * stack, RexxObject * argument, size_t argumentPos, bool isStrict)
Handle the assignment for an individual USE arg variable.
Parameters
arg The argument value passed to this activation.
isStrict
Definition at line 60 of file UseInstruction.cpp.
References RexxVariableBase::assign(), defaultValue, RexxVariableBase::drop(), Error_Incorrect_call_noarg, Error_Incorrect_method_noarg, RexxInternalObject::evaluate(), RexxActivation::getCallname(), handleReferenceArgument(), RexxActivation::inMethod(), isOfClass, OREF_NULL, ExpressionStack::pop(), reportException(), RexxActivation::traceResult(), and variable.
Referenced by RexxInstructionUse::execute().
handleReferenceArgument()
void UseVariable::handleReferenceArgument (RexxActivation * context, ExpressionStack * stack, RexxObject * argument, size_t argumentPos)
Handle the hook up between a veriable reference passed as an argument and a local variable.
Parameters
context The execution context.
stack the current execution stack.
argument The argument to process (must be a VariableReference)
argumentPos The argument position
Definition at line 129 of file UseInstruction.cpp.
References UseArgVariableRef::aliasVariable(), Error_Invalid_argument_no_reference, Error_Invalid_argument_variable_reference, Error_Invalid_argument_variable_reference_simple, Error_Invalid_argument_variable_reference_stem, VariableReference::getName(), UseArgVariableRef::getName(), VariableReference::getVariable(), VariableReference::isStem(), UseArgVariableRef::isStem(), isVariableReference(), OREF_NULL, reportException(), RexxActivation::traceVariableAlias(), and variable.
Referenced by handleArgument().
Member Data Documentation
defaultValue
RexxInternalObject* UseVariable::defaultValue
Definition at line 53 of file UseInstruction.hpp.
Referenced by handleArgument(), and RexxInstructionUse::RexxInstructionUse().
variable
RexxVariableBase* UseVariable::variable
Definition at line 52 of file UseInstruction.hpp.
Referenced by handleArgument(), handleReferenceArgument(), and RexxInstructionUse::RexxInstructionUse().
The documentation for this class was generated from the following files:
UseInstruction.hpp
UseInstruction.cpp