ooRexx: RexxString::StringBuilder Class Reference
RexxString::StringBuilder Class Reference
#include <StringClass.hpp>
Public Member Functions
StringBuilder ()
StringBuilder (char *b)
StringBuilder (RexxString *s)
void init (RexxString *s)
void append (const char *d, size_t l)
void append (const char *d)
void append (char c)
void append (RexxString *s)
void pad (char c, size_t l)
Protected Attributes
char * current
Detailed Description
A class for constructing a string value from a sequence of append steps.
Definition at line 85 of file StringClass.hpp.
Constructor & Destructor Documentation
StringBuilder() [1/3]
RexxString::StringBuilder::StringBuilder () inline
Definition at line 88 of file StringClass.hpp.
StringBuilder() [2/3]
RexxString::StringBuilder::StringBuilder (char * b) inline
Definition at line 89 of file StringClass.hpp.
StringBuilder() [3/3]
RexxString::StringBuilder::StringBuilder (RexxString * s) inline
Definition at line 90 of file StringClass.hpp.
Member Function Documentation
append() [1/4]
void RexxString::StringBuilder::append (char c) inline
Definition at line 95 of file StringClass.hpp.
References current.
append() [2/4]
void RexxString::StringBuilder::append (const char * d) inline
Definition at line 94 of file StringClass.hpp.
References current.
append() [3/4]
void RexxString::StringBuilder::append (const char * d, size_t l) inline
Definition at line 93 of file StringClass.hpp.
References current.
Referenced by RexxString::WordIterator::append(), RexxString::WordIterator::appendRemainder(), BUILTIN(), RexxString::caselessChangeStr(), RexxString::center(), RexxString::changeStr(), RexxString::concat(), RexxString::concatBlank(), RexxString::concatRexx(), RexxString::concatToCstring(), RexxString::concatWith(), RexxString::concatWithCstring(), RexxString::copies(), RexxString::delstr(), RexxString::delWord(), RexxString::insert(), RexxString::left(), RexxString::overlay(), RexxString::replaceAt(), RexxString::right(), RexxActivation::sourceString(), and StringUtil::substr().
append() [4/4]
void RexxString::StringBuilder::append (RexxString * s) inline
Definition at line 108 of file StringClass.hpp.
References append(), RexxString::getLength(), and RexxString::getStringData().
Referenced by append().
init()
void RexxString::StringBuilder::init (RexxString * s) inline
Definition at line 92 of file StringClass.hpp.
References current, and RexxString::getWritableData().
Referenced by BUILTIN().
pad()
void RexxString::StringBuilder::pad (char c, size_t l) inline
Definition at line 109 of file StringClass.hpp.
References current.
Referenced by RexxString::center(), RexxString::insert(), RexxString::left(), RexxString::overlay(), RexxString::replaceAt(), RexxString::right(), RexxString::space(), and StringUtil::substr().
Member Data Documentation
current
char* RexxString::StringBuilder::current protected
Definition at line 112 of file StringClass.hpp.
Referenced by append(), init(), and pad().
The documentation for this class was generated from the following file:
StringClass.hpp