ooRexx: SysThread Class Reference
SysThread Class Reference
#include <SysThread.hpp>
Public Types
enum { THREAD_STACK_SIZE = 1024*512 }
enum { THREAD_STACK_SIZE = 1024*512 }
Public Member Functions
SysThread ()
virtual ~SysThread ()
virtual void attachThread ()
virtual void dispatch ()
void terminate ()
void startup ()
void shutdown ()
void yield ()
bool equals (SysThread &other)
void waitForTermination ()
SysThread ()
virtual ~SysThread ()
SysThread (thread_id_t threadID)
virtual void attachThread ()
virtual void dispatch ()
void terminate ()
void startup ()
void shutdown ()
void yield ()
uintptr_t threadID ()
bool equals (SysThread &other)
size_t hash ()
void waitForTermination ()
Static Public Member Functions
static void sleep (int msecs)
static int longSleep (uint64_t microseconds)
static uint64_t getMillisecondTicks ()
static int createThread (pthread_t &id, bool &idValid, size_t stackSize, void *(*startRoutine)(void *), void *startArgument)
static void sleep (int msecs)
static int longSleep (uint64_t microseconds)
static uint64_t getMillisecondTicks ()
static int createThread (HANDLE &threadHandle, DWORD &threadId, size_t stackSize, LPTHREAD_START_ROUTINE, void *startArgument)
Protected Member Functions
void createThread ()
void createThread ()
Protected Attributes
bool valid
bool attached
pthread_t _threadID
HANDLE _threadHandle
DWORD _threadID
Detailed Description
A wrapper around a posix-style thread.
A wrapper anound a Windows-style thread.
Definition at line 60 of file unix/SysThread.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
THREAD_STACK_SIZE
Definition at line 65 of file unix/SysThread.hpp.
anonymous enum
anonymous enum
Enumerator
THREAD_STACK_SIZE
Definition at line 62 of file windows/SysThread.hpp.
Constructor & Destructor Documentation
SysThread() [1/3]
SysThread::SysThread () inline
Definition at line 70 of file unix/SysThread.hpp.
~SysThread() [1/2]
virtual SysThread::~SysThread () inline virtual
Definition at line 71 of file unix/SysThread.hpp.
SysThread() [2/3]
SysThread::SysThread () inline
Definition at line 67 of file windows/SysThread.hpp.
~SysThread() [2/2]
virtual SysThread::~SysThread () inline virtual
Definition at line 68 of file windows/SysThread.hpp.
SysThread() [3/3]
SysThread::SysThread (thread_id_t threadID) inline
Definition at line 70 of file windows/SysThread.hpp.
References _threadID, and threadID().
Member Function Documentation
attachThread() [1/2]
void SysThread::attachThread () virtual
attach an activity to an existing thread
Definition at line 55 of file unix/SysThread.cpp.
References _threadID, attached, and valid.
attachThread() [2/2]
virtual void SysThread::attachThread () virtual
createThread() [1/4]
void SysThread::createThread () protected
create a new thread
Definition at line 113 of file unix/SysThread.cpp.
References _threadID, attached, call_thread_function(), THREAD_STACK_SIZE, and valid.
Referenced by SysActivity::create(), APIServerThread::start(), ReaderThread::start(), InputWriterThread::start(), and ErrorReaderThread::start().
createThread() [2/4]
void SysThread::createThread () protected
createThread() [3/4]
int SysThread::createThread (HANDLE & threadHandle, DWORD & threadId, size_t stackSize, LPTHREAD_START_ROUTINE startRoutine, void * startArgument) static
Create a new thread.
Parameters
threadHandle The handle of the created thread
threadId The id of the created thread
stackSize The required stack size
startRoutine The thread startup routine.
startArgument The typeless argument passed to the startup routine.
Returns
The success/failure return code.
Definition at line 88 of file windows/SysThread.cpp.
createThread() [4/4]
int SysThread::createThread (pthread_t & id, bool & idValid, size_t stackSize, void *(*)(void *) startRoutine, void * startArgument) static
Create a new thread.
Parameters
threadNumber The returned thread ID
stackSize The required stack size
startRoutine The thread startup routine.
startArgument The typeless argument passed to the startup routine.
Returns
The success/failure return code.
Definition at line 141 of file unix/SysThread.cpp.
dispatch() [1/2]
void SysThread::dispatch () virtual
This is a dummy method intended for subclass overrides. This dispatches the code on the new thread.
Reimplemented in InputWriterThread, ErrorReaderThread, InputWriterThread, ReaderThread, and APIServerThread.
Definition at line 63 of file unix/SysThread.cpp.
dispatch() [2/2]
virtual void SysThread::dispatch () virtual
Reimplemented in InputWriterThread, ErrorReaderThread, InputWriterThread, ReaderThread, and APIServerThread.
equals() [1/2]
bool SysThread::equals (SysThread & other)
Test whether two threads are the same.
Parameters
other The other thread object.
Returns
True if they are the same thread, false if not.
Definition at line 99 of file unix/SysThread.cpp.
References _threadID.
equals() [2/2]
bool SysThread::equals (SysThread & other)
getMillisecondTicks() [1/2]
static uint64_t SysThread::getMillisecondTicks () inline static
Definition at line 84 of file unix/SysThread.hpp.
Referenced by ActivityManager::lockKernel(), and ActivityManager::relinquishIfNeeded().
getMillisecondTicks() [2/2]
static uint64_t SysThread::getMillisecondTicks () inline static
Definition at line 92 of file windows/SysThread.hpp.
hash()
size_t SysThread::hash () inline
Definition at line 86 of file windows/SysThread.hpp.
References _threadHandle.
longSleep() [1/2]
int SysThread::longSleep (uint64_t microseconds) static
Platform wrapper around a sleep function that can sleep for long periods of time. .
Parameters
microseconds The number of microseconds to delay.
Returns
The success/failure return code.
Platform wrapper around a sleep function that can sleep for long periods of time. .
Parameters
microseconds The number of microseconds to delay.
Using Sleep with a long timeout risks sleeping on a thread with a message queue, which can make the system sluggish, or possibly deadlocked. If the sleep is longer than 333 milliseconds use a window timer to avoid this risk.
Definition at line 191 of file unix/SysThread.cpp.
Referenced by SysProcess::playSpeaker(), and RexxRoutine1().
longSleep() [2/2]
static int SysThread::longSleep (uint64_t microseconds) static
shutdown() [1/2]
void SysThread::shutdown ()
Perform any platform-specific thread shutdown activities.
Definition at line 84 of file unix/SysThread.cpp.
shutdown() [2/2]
void SysThread::shutdown ()
sleep() [1/2]
void SysThread::sleep (int msecs) static
Platform wrapper around a simple sleep function.
Parameters
msecs The number of milliseconds to sleep.
Definition at line 176 of file unix/SysThread.cpp.
Referenced by LocalAPIManager::establishServerConnection().
sleep() [2/2]
static void SysThread::sleep (int msecs) static
startup() [1/2]
void SysThread::startup ()
Do any thread-specific startup activity.
Definition at line 78 of file unix/SysThread.cpp.
startup() [2/2]
void SysThread::startup ()
terminate() [1/2]
void SysThread::terminate ()
Do any platform specific termination
Definition at line 68 of file unix/SysThread.cpp.
References _threadID, attached, and valid.
Referenced by APIServer::cleanupTerminatedSessions(), APIServerThread::~APIServerThread(), ErrorReaderThread::~ErrorReaderThread(), InputWriterThread::~InputWriterThread(), and ReaderThread::~ReaderThread().
terminate() [2/2]
void SysThread::terminate ()
threadID()
uintptr_t SysThread::threadID () inline
Definition at line 81 of file windows/SysThread.hpp.
References _threadID.
Referenced by SysThread().
waitForTermination() [1/2]
void SysThread::waitForTermination ()
Wait for the thread to terminate
Definition at line 160 of file unix/SysThread.cpp.
References _threadID, attached, and valid.
Referenced by ioCommandHandler(), and sysCommandNT().
waitForTermination() [2/2]
void SysThread::waitForTermination ()
yield() [1/2]
void SysThread::yield ()
yield control to other threads.
Definition at line 90 of file unix/SysThread.cpp.
yield() [2/2]
void SysThread::yield ()
Member Data Documentation
_threadHandle
HANDLE SysThread::_threadHandle protected
Definition at line 105 of file windows/SysThread.hpp.
Referenced by hash().
_threadID [1/2]
pthread_t SysThread::_threadID protected
Definition at line 98 of file unix/SysThread.hpp.
Referenced by attachThread(), createThread(), equals(), SysThread(), terminate(), threadID(), and waitForTermination().
_threadID [2/2]
DWORD SysThread::_threadID protected
Definition at line 106 of file windows/SysThread.hpp.
attached
bool SysThread::attached protected
Definition at line 97 of file unix/SysThread.hpp.
Referenced by attachThread(), createThread(), terminate(), and waitForTermination().
valid
bool SysThread::valid protected
Definition at line 96 of file unix/SysThread.hpp.
Referenced by attachThread(), createThread(), terminate(), and waitForTermination().
The documentation for this class was generated from the following files:
unix/SysThread.hpp
windows/SysThread.hpp
unix/SysThread.cpp
windows/SysThread.cpp