ooRexx: SysSearchPath Class Reference
SysSearchPath Class Reference
#include <SysInterpreterInstance.hpp>
Public Member Functions
SysSearchPath (const char *parent, const char *extension)
~SysSearchPath ()
void addPath (const char *p)
SysSearchPath (const char *parent, const char *extension)
~SysSearchPath ()
void addPath (const char *p)
Public Attributes
FileNameBuffer path
Detailed Description
Definition at line 76 of file unix/SysInterpreterInstance.hpp.
Constructor & Destructor Documentation
SysSearchPath() [1/2]
SysSearchPath::SysSearchPath (const char * parentDir, const char * extensionPath)
Build a search path used for this resolution step.
Parameters
parentDir The location of the program calling us (can be null).
extensionPath The system extension path (can be null).
Initialize a path searcher.
Parameters
parentDir The parent dirctory for the search.
extensionPath The system extension path.
Definition at line 123 of file unix/SysInterpreterInstance.cpp.
References addPath().
~SysSearchPath() [1/2]
SysSearchPath::~SysSearchPath () inline
Definition at line 80 of file unix/SysInterpreterInstance.hpp.
SysSearchPath() [2/2]
SysSearchPath::SysSearchPath (const char * parent, const char * extension)
~SysSearchPath() [2/2]
SysSearchPath::~SysSearchPath () inline
Definition at line 80 of file windows/SysInterpreterInstance.hpp.
Member Function Documentation
addPath() [1/2]
void SysSearchPath::addPath (const char * p) inline
Definition at line 82 of file unix/SysInterpreterInstance.hpp.
References FileNameBuffer::appendPathSeparator(), and path.
Referenced by SysSearchPath().
addPath() [2/2]
void SysSearchPath::addPath (const char * p) inline
Definition at line 82 of file windows/SysInterpreterInstance.hpp.
References FileNameBuffer::appendPathSeparator(), and path.
Member Data Documentation
path
FileNameBuffer SysSearchPath::path
Definition at line 92 of file unix/SysInterpreterInstance.hpp.
Referenced by addPath().
The documentation for this class was generated from the following files:
unix/SysInterpreterInstance.hpp
windows/SysInterpreterInstance.hpp
unix/SysInterpreterInstance.cpp
windows/SysInterpreterInstance.cpp