ooRexx: NormalSegmentSet Class Reference
NormalSegmentSet Class Reference
#include <MemorySegment.hpp>
Public Member Functions
NormalSegmentSet ()
NormalSegmentSet (MemoryObject *memory)
virtual ~NormalSegmentSet ()
void dumpMemoryProfile (FILE *outfile) override
RexxInternalObject * allocateObject (size_t allocationLength)
RexxInternalObject * handleAllocationFailure (size_t allocationLength)
DeadObject * donateObject (size_t allocationLength) override
void getInitialSet ()
size_t suggestMemoryExpansion () override
Public Member Functions inherited from MemorySegmentSet
MemorySegmentSet (MemoryObject *memObject, SegmentSetID id, const char *setName)
MemorySegmentSet ()
virtual ~MemorySegmentSet ()
void removeSegment (MemorySegment *segment)
void removeSegmentAndStorage (MemorySegment *segment)
void add (MemorySegment *segment)
MemorySegment * first ()
MemorySegment * next (MemorySegment *segment)
void transferSegment (MemorySegment *segment)
void dumpSegments (FILE *keyfile, FILE *dumpfile)
void addSegment (MemorySegment *segment)
void sweep ()
void sweepSingleSegment (MemorySegment *sweepSegment)
bool is (SegmentSetID id)
void gatherStats (MemoryStats *memStats, SegmentStats *stats)
MemorySegment * largestActiveSegment ()
Protected Member Functions
void addDeadObject (DeadObject *object) override
void addDeadObject (char *object, size_t length) override
void prepareForSweep () override
void completeSweepOperation () override
Protected Member Functions inherited from MemorySegmentSet
RexxInternalObject * splitDeadObject (DeadObject *object, size_t allocationLength, size_t splitMinimum)
void insertSegment (MemorySegment *segment)
void adjustMemorySize ()
bool newSegment (size_t requestLength, size_t minimumLength)
virtual MemorySegment * allocateSegment (size_t requestLength, size_t minimumLength)
float freeMemoryPercentage ()
size_t totalFreeMemory ()
size_t calculateSegmentAllocation (size_t n)
void addSegments (size_t requiredSpace)
void validateObject (RexxInternalObject *o)
Private Member Functions
size_t mapLengthToDeadPool (size_t length)
RexxInternalObject * findLargeDeadObject (size_t allocationLength)
size_t recommendedMemorySize ()
void checkObjectOverlap (DeadObject *obj)
RexxInternalObject * findObject (size_t allocationLength)
RexxInternalObject * splitNormalDeadObject (DeadObject *object, size_t allocationLength, size_t deadLength)
Static Private Member Functions
static size_t lengthToDeadPool (size_t l)
static size_t deadPoolToLength (size_t d)
Private Attributes
DeadObjectPool largeDead
DeadObjectPool subpools [DeadPools]
size_t lastUsedSubpool [DeadPools+1]
MemorySegment * recoverSegment
Static Private Attributes
static const size_t FirstDeadPool = Memory::MinimumObjectSize / Memory::ObjectGrain
static const size_t LargestSubpool = 512
static const size_t LastDeadPool = LargestSubpool / Memory::ObjectGrain
static const size_t DeadPools = LastDeadPool + 1
static const double NormalMemoryExpansionThreshold = .30
static const size_t RecoverSegmentSize = ((MemorySegment::SegmentSize/2) - MemorySegment::MemorySegmentOverhead)
static const size_t InitialNormalSegmentSpace = ((MemorySegment::SegmentSize * 12) - MemorySegment::MemorySegmentOverhead)
Additional Inherited Members
Public Types inherited from MemorySegmentSet
enum SegmentSetID {
SET_UNINITIALIZED , SET_NORMAL , SET_LARGEBLOCK , SET_OLDSPACE ,
SET_SINGLEOBJECT
}
Static Public Attributes inherited from MemorySegmentSet
static const size_t MinimumSegmentSize = (MemorySegment::SegmentSize/2)
static const size_t MinimumSegmentDeadSpace = (MinimumSegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentSize = (MemorySegment::SegmentSize * 4)
static const size_t SegmentDeadSpace = (MemorySegment::SegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentDeadSpace = (LargeSegmentSize - MemorySegment::MemorySegmentOverhead)
Protected Attributes inherited from MemorySegmentSet
MemorySegment anchor
size_t count
size_t liveObjectBytes
size_t deadObjectBytes
SegmentSetID owner
const char * name
MemoryObject * memory
Detailed Description
The segment set used for "normal" allocations. This segment set will be used for smaller allocations, particularly ones that can be allocated from one of the small allocation pools.
Definition at line 333 of file MemorySegment.hpp.
Constructor & Destructor Documentation
NormalSegmentSet() [1/2]
NormalSegmentSet::NormalSegmentSet () inline
Definition at line 338 of file MemorySegment.hpp.
NormalSegmentSet() [2/2]
NormalSegmentSet::NormalSegmentSet (MemoryObject * mem)
Constructor for the normal segment pool.
Parameters
mem The master memory object.
Definition at line 241 of file MemorySegment.cpp.
References DeadPools, deadPoolToLength(), DeadObjectPool::emptySingle(), lastUsedSubpool, MemorySegmentSet::memory, MemoryObject::newSegment(), recoverSegment, RecoverSegmentSize, DeadObjectPool::setID(), and subpools.
~NormalSegmentSet()
virtual NormalSegmentSet::~NormalSegmentSet () inline virtual
Definition at line 340 of file MemorySegment.hpp.
Member Function Documentation
addDeadObject() [1/2]
void NormalSegmentSet::addDeadObject (char * object, size_t length) override protected virtual
Add a section of memory as a dead object to our pool.
Parameters
object The address of the memory.
length The length of the dead memory.
Reimplemented from MemorySegmentSet.
Definition at line 521 of file MemorySegment.cpp.
References DeadObjectPool::add(), DeadObjectPool::addSingle(), largeDead, LargestSubpool, lastUsedSubpool, lengthToDeadPool(), and subpools.
addDeadObject() [2/2]
void NormalSegmentSet::addDeadObject (DeadObject * object) override protected virtual
Add a dead object to the segment set during the sweep operation.
Parameters
object The newly dead object.
Reimplemented from MemorySegmentSet.
Definition at line 427 of file MemorySegment.cpp.
References DeadObjectPool::add(), DeadObjectPool::addSingle(), largeDead, LargestSubpool, lastUsedSubpool, lengthToDeadPool(), and subpools.
allocateObject()
RexxInternalObject* NormalSegmentSet::allocateObject (size_t allocationLength) inline
Definition at line 343 of file MemorySegment.hpp.
References DeadPools, DeadObjectPool::findFit(), DeadObjectPool::getFirstSingle(), largeDead, lastUsedSubpool, lengthToDeadPool(), Memory::MinimumObjectSize, OREF_NULL, splitNormalDeadObject(), and subpools.
Referenced by findObject(), and MemoryObject::newObject().
checkObjectOverlap()
void NormalSegmentSet::checkObjectOverlap (DeadObject * obj) private
do dead object overlap validation checking.
Parameters
obj The object to check.
Definition at line 193 of file MemorySegment.cpp.
References DeadObjectPool::checkObjectOverlap(), DeadPools, FirstDeadPool, largeDead, and subpools.
completeSweepOperation()
void NormalSegmentSet::completeSweepOperation () override protected virtual
Handle all segment set post sweep activities.
Reimplemented from MemorySegmentSet.
Definition at line 853 of file MemorySegment.cpp.
References DeadPools, FirstDeadPool, lastUsedSubpool, and subpools.
deadPoolToLength()
static size_t NormalSegmentSet::deadPoolToLength (size_t d) inline static private
Definition at line 473 of file MemorySegment.hpp.
References Memory::ObjectGrain.
Referenced by NormalSegmentSet().
donateObject()
DeadObject * NormalSegmentSet::donateObject (size_t allocationLength) override virtual
Search the cache of dead objects for an object of sufficient size to fulfill this request. This just uses normal large block allocation strategy to decide on the block to donate, give a best fit for the allocation.
Parameters
allocationLength The required object size
Returns
A DeadObject of the required size.
Reimplemented from MemorySegmentSet.
Definition at line 612 of file MemorySegment.cpp.
References findLargeDeadObject().
dumpMemoryProfile()
void NormalSegmentSet::dumpMemoryProfile (FILE * outfile) override virtual
Dump profile informaton about the normal allocation segment set
Parameters
outfile The target dump file.
Reimplemented from MemorySegmentSet.
Definition at line 173 of file MemorySegment.cpp.
References DeadPools, DeadObjectPool::dumpMemoryProfile(), FirstDeadPool, largeDead, and subpools.
findLargeDeadObject()
RexxInternalObject * NormalSegmentSet::findLargeDeadObject (size_t allocationLength) private
Search the segment set for a block of the requested length. If a block is found, the block will be subdivided if necessary, with the remainder portion placed back on the proper chain.
Parameters
allocationLength The required object length (already rounded to an appropriate grain size).
Returns
An appropriately sized object or NULL if one was not found.
Definition at line 1092 of file MemorySegment.cpp.
References DeadObjectPool::findFit(), largeDead, Memory::MinimumObjectSize, OREF_NULL, and MemorySegmentSet::splitDeadObject().
Referenced by donateObject().
findObject()
RexxInternalObject * NormalSegmentSet::findObject (size_t allocationLength) private
Find a dead object in the caches for the NormalSegmentSet.
Parameters
allocationLength The required allocation size.
Returns
A located object or NULL if unable to allocate.
Definition at line 1117 of file MemorySegment.cpp.
References allocateObject().
Referenced by handleAllocationFailure().
getInitialSet()
void NormalSegmentSet::getInitialSet ()
Set up the intial normal memory allocation.
Definition at line 275 of file MemorySegment.cpp.
References InitialNormalSegmentSpace, and MemorySegmentSet::newSegment().
Referenced by MemoryObject::initialize().
handleAllocationFailure()
RexxInternalObject * NormalSegmentSet::handleAllocationFailure (size_t allocationLength)
Handle an allocation failure for a request that was directed to the normal allocation segment set.
Parameters
allocationLength The length of the failing allocation attempt.
Returns
An allocated object, or NULL if this still fails after the all failure methods have been attempted.
Definition at line 1135 of file MemorySegment.cpp.
References MemorySegmentSet::addSegment(), MemorySegmentSet::addSegments(), MemorySegmentSet::adjustMemorySize(), MemoryObject::collect(), Error_System_resources, findObject(), line_end, MemorySegmentSet::memory, OREF_NULL, recoverSegment, reportException(), MemoryObject::scavengeSegmentSets(), MemorySegment::SegmentSize, and MemoryObject::verboseMessage().
Referenced by MemoryObject::newObject().
lengthToDeadPool()
static size_t NormalSegmentSet::lengthToDeadPool (size_t l) inline static private
Definition at line 471 of file MemorySegment.hpp.
References Memory::ObjectGrain.
Referenced by addDeadObject(), allocateObject(), and splitNormalDeadObject().
mapLengthToDeadPool()
size_t NormalSegmentSet::mapLengthToDeadPool (size_t length) inline private
Definition at line 475 of file MemorySegment.hpp.
References Memory::ObjectGrain.
prepareForSweep()
void NormalSegmentSet::prepareForSweep () override protected virtual
Handle all segment set pre-sweep initialization.
Reimplemented from MemorySegmentSet.
Definition at line 814 of file MemorySegment.cpp.
References DeadPools, DeadObjectPool::empty(), DeadObjectPool::emptySingle(), FirstDeadPool, largeDead, MemorySegmentSet::prepareForSweep(), and subpools.
recommendedMemorySize()
size_t NormalSegmentSet::recommendedMemorySize () inline private
Definition at line 477 of file MemorySegment.hpp.
References MemorySegmentSet::liveObjectBytes, and NormalMemoryExpansionThreshold.
Referenced by suggestMemoryExpansion().
splitNormalDeadObject()
RexxInternalObject* NormalSegmentSet::splitNormalDeadObject (DeadObject * object, size_t allocationLength, size_t deadLength) inline private
Definition at line 480 of file MemorySegment.hpp.
References DeadObjectPool::add(), DeadObjectPool::addSingle(), largeDead, LargestSubpool, lastUsedSubpool, lengthToDeadPool(), and subpools.
Referenced by allocateObject().
suggestMemoryExpansion()
size_t NormalSegmentSet::suggestMemoryExpansion () override virtual
Decide if we should add additional segments to the normal heap based on the amount of free space we have after a garbage collection. If we're starting to run full, then we should expand the heap to prevent recycling the garbage collector to reclaim minimal amounts of storage that is immediately reused, causing another GC cycle.
Returns
A recommended expansion size.
Reimplemented from MemorySegmentSet.
Definition at line 666 of file MemorySegment.cpp.
References MemorySegmentSet::deadObjectBytes, MemorySegmentSet::freeMemoryPercentage(), line_end, MemorySegmentSet::liveObjectBytes, MemorySegmentSet::memory, NormalMemoryExpansionThreshold, recommendedMemorySize(), and MemoryObject::verboseMessage().
Member Data Documentation
DeadPools
const size_t NormalSegmentSet::DeadPools = LastDeadPool + 1 static private
Definition at line 460 of file MemorySegment.hpp.
Referenced by allocateObject(), checkObjectOverlap(), completeSweepOperation(), dumpMemoryProfile(), NormalSegmentSet(), and prepareForSweep().
FirstDeadPool
const size_t NormalSegmentSet::FirstDeadPool = Memory::MinimumObjectSize / Memory::ObjectGrain static private
Definition at line 453 of file MemorySegment.hpp.
Referenced by checkObjectOverlap(), completeSweepOperation(), dumpMemoryProfile(), and prepareForSweep().
InitialNormalSegmentSpace
const size_t NormalSegmentSet::InitialNormalSegmentSpace = ((MemorySegment::SegmentSize * 12) - MemorySegment::MemorySegmentOverhead) static private
Definition at line 467 of file MemorySegment.hpp.
Referenced by getInitialSet().
largeDead
DeadObjectPool NormalSegmentSet::largeDead private
Definition at line 519 of file MemorySegment.hpp.
Referenced by addDeadObject(), allocateObject(), checkObjectOverlap(), dumpMemoryProfile(), findLargeDeadObject(), prepareForSweep(), and splitNormalDeadObject().
LargestSubpool
const size_t NormalSegmentSet::LargestSubpool = 512 static private
Definition at line 455 of file MemorySegment.hpp.
Referenced by addDeadObject(), and splitNormalDeadObject().
LastDeadPool
const size_t NormalSegmentSet::LastDeadPool = LargestSubpool / Memory::ObjectGrain static private
Definition at line 457 of file MemorySegment.hpp.
lastUsedSubpool
size_t NormalSegmentSet::lastUsedSubpool[DeadPools+1] private
Definition at line 521 of file MemorySegment.hpp.
Referenced by addDeadObject(), allocateObject(), completeSweepOperation(), NormalSegmentSet(), and splitNormalDeadObject().
NormalMemoryExpansionThreshold
const double NormalSegmentSet::NormalMemoryExpansionThreshold = .30 static private
Definition at line 463 of file MemorySegment.hpp.
Referenced by recommendedMemorySize(), and suggestMemoryExpansion().
recoverSegment
MemorySegment* NormalSegmentSet::recoverSegment private
Definition at line 522 of file MemorySegment.hpp.
Referenced by handleAllocationFailure(), and NormalSegmentSet().
RecoverSegmentSize
const size_t NormalSegmentSet::RecoverSegmentSize = ((MemorySegment::SegmentSize/2) - MemorySegment::MemorySegmentOverhead) static private
Definition at line 465 of file MemorySegment.hpp.
Referenced by NormalSegmentSet().
subpools
DeadObjectPool NormalSegmentSet::subpools[DeadPools] private
Definition at line 520 of file MemorySegment.hpp.
Referenced by addDeadObject(), allocateObject(), checkObjectOverlap(), completeSweepOperation(), dumpMemoryProfile(), NormalSegmentSet(), prepareForSweep(), and splitNormalDeadObject().
The documentation for this class was generated from the following files:
MemorySegment.hpp
MemorySegment.cpp