ooRexx: NativeActivationFrame Class Reference
NativeActivationFrame Class Reference
#include <ActivationFrame.hpp>
Public Member Functions
NativeActivationFrame (Activity *a, NativeActivation *context)
RexxString * messageName () override
BaseExecutable * executable () override
StackFrameClass * createStackFrame () override
PackageClass * getPackage () override
Public Member Functions inherited from ActivationFrame
ActivationFrame (Activity *a)
void disableFrame ()
~ActivationFrame ()
Protected Attributes
NativeActivation * activation
Protected Attributes inherited from ActivationFrame
ActivationFrame * next
Activity * activity
Detailed Description
A stack frame representing running native code.
Definition at line 122 of file ActivationFrame.hpp.
Constructor & Destructor Documentation
NativeActivationFrame()
NativeActivationFrame::NativeActivationFrame (Activity * a, NativeActivation * context) inline
Definition at line 125 of file ActivationFrame.hpp.
Member Function Documentation
createStackFrame()
StackFrameClass * NativeActivationFrame::createStackFrame () override virtual
Implements ActivationFrame.
Definition at line 80 of file ActivationFrame.cpp.
References activation, and NativeActivation::createStackFrame().
executable()
BaseExecutable * NativeActivationFrame::executable () override virtual
Implements ActivationFrame.
Definition at line 75 of file ActivationFrame.cpp.
References activation, and ActivationBase::getExecutableObject().
getPackage()
PackageClass * NativeActivationFrame::getPackage () override virtual
Implements ActivationFrame.
Definition at line 85 of file ActivationFrame.cpp.
References activation, and NativeActivation::getPackageObject().
messageName()
RexxString * NativeActivationFrame::messageName () override virtual
Implements ActivationFrame.
Definition at line 70 of file ActivationFrame.cpp.
References activation, and NativeActivation::getMessageName().
Member Data Documentation
activation
NativeActivation* NativeActivationFrame::activation protected
Definition at line 134 of file ActivationFrame.hpp.
Referenced by createStackFrame(), executable(), getPackage(), and messageName().
The documentation for this class was generated from the following files:
ActivationFrame.hpp
ActivationFrame.cpp