ooRexx: MutableBuffer Class Reference
MutableBuffer Class Reference
#include <MutableBufferClass.hpp>
Public Member Functions
void * operator new (size_t size)
MutableBuffer ()
MutableBuffer (size_t, size_t)
MutableBuffer (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *envelope) override
RexxInternalObject * copy () override
void ensureCapacity (size_t addedLength)
RexxObject * lengthRexx ()
MutableBuffer * appendRexx (RexxObject **args, size_t argc)
MutableBuffer * setTextRexx (RexxObject *)
void setText (RexxString *)
MutableBuffer * insert (RexxObject *, RexxObject *, RexxObject *, RexxObject *)
MutableBuffer * overlay (RexxObject *, RexxObject *, RexxObject *, RexxObject *)
MutableBuffer * bracketsEqual (RexxObject *str, RexxObject *pos, RexxObject *len)
MutableBuffer * replaceAt (RexxObject *str, RexxObject *pos, RexxObject *len, RexxObject *pad)
MutableBuffer * mydelete (RexxObject *, RexxObject *)
RexxString * substr (RexxInteger *startPosition, RexxInteger *len, RexxString *pad)
RexxString * brackets (RexxInteger *startPosition, RexxInteger *len)
RexxInteger * lastPos (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxInteger * posRexx (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxObject * containsRexx (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxInteger * caselessLastPos (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxInteger * caselessPos (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxObject * caselessContains (RexxString *needle, RexxInteger *_start, RexxInteger *_range)
RexxString * subchar (RexxInteger *startPosition)
RexxInteger * getBufferSize ()
RexxObject * setBufferSize (RexxInteger *)
ArrayClass * makeArrayRexx (RexxString *div)
ArrayClass * makeArray () override
RexxString * makeString () override
RexxString * primitiveMakeString () override
RexxString * stringValue () override
RexxInteger * countStrRexx (RexxString *needle)
RexxInteger * caselessCountStrRexx (RexxString *needle)
MutableBuffer * changeStr (RexxString *needle, RexxString *newNeedle, RexxInteger *countArg)
MutableBuffer * caselessChangeStr (RexxString *needle, RexxString *newNeedle, RexxInteger *countArg)
MutableBuffer * upper (RexxInteger *_start, RexxInteger *_length)
MutableBuffer * lower (RexxInteger *_start, RexxInteger *_length)
MutableBuffer * translate (RexxString *tableo, RexxString *tablei, RexxString *pad, RexxInteger *, RexxInteger *)
RexxObject * match (RexxInteger *start_, RexxString *other, RexxInteger *offset_, RexxInteger *len_)
RexxObject * caselessMatch (RexxInteger *start_, RexxString *other, RexxInteger *offset_, RexxInteger *len_)
RexxObject * startsWithRexx (RexxString *other)
RexxObject * endsWithRexx (RexxString *other)
RexxObject * caselessStartsWithRexx (RexxString *other)
RexxObject * caselessEndsWithRexx (RexxString *other)
bool primitiveMatch (size_t start, RexxString *other, size_t offset, size_t len)
bool primitiveCaselessMatch (size_t start, RexxString *other, size_t offset, size_t len)
RexxObject * matchChar (RexxInteger *position_, RexxString *matchSet)
RexxObject * caselessMatchChar (RexxInteger *position_, RexxString *matchSet)
RexxInteger * verify (RexxString *, RexxString *, RexxInteger *, RexxInteger *)
RexxString * subWord (RexxInteger *, RexxInteger *)
ArrayClass * subWords (RexxInteger *, RexxInteger *)
RexxString * word (RexxInteger *)
RexxInteger * wordIndex (RexxInteger *)
RexxInteger * wordLength (RexxInteger *)
RexxInteger * words ()
RexxInteger * wordPos (RexxString *, RexxInteger *)
RexxInteger * caselessWordPos (RexxString *, RexxInteger *)
RexxObject * containsWord (RexxString *, RexxInteger *)
RexxObject * caselessContainsWord (RexxString *, RexxInteger *)
MutableBuffer * delWord (RexxInteger *position, RexxInteger *plength)
MutableBuffer * space (RexxInteger *space_count, RexxString *pad)
const char * getStringData ()
size_t getLength ()
char * getData ()
void append (char c)
void append (const char *string, size_t l)
void append (RexxString *s)
void append (const char *string)
void copyData (size_t offset, const char *string, size_t l)
void openGap (size_t offset, size_t _size, size_t tailSize)
void closeGap (size_t offset, size_t _size, size_t tailSize)
void adjustGap (size_t offset, size_t _size, size_t _newSize)
void setData (size_t offset, char character, size_t l)
size_t setDataLength (size_t l)
char getChar (size_t offset)
size_t getCapacity ()
char * setCapacity (size_t newLength)
MutableBuffer * newRexx (RexxObject **, size_t)
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
HashCode hash () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static const size_t DEFAULT_BUFFER_LENGTH = 256
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
size_t bufferLength
size_t defaultSize
size_t dataLength
BufferClass * data
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
A string-like object where in-place updating of the data is permitted.
Definition at line 55 of file MutableBufferClass.hpp.
Constructor & Destructor Documentation
MutableBuffer() [1/3]
MutableBuffer::MutableBuffer ()
Default constructor.
Definition at line 142 of file MutableBufferClass.cpp.
References bufferLength, data, DEFAULT_BUFFER_LENGTH, defaultSize, new_buffer(), and OREF_NULL.
Referenced by newRexx().
MutableBuffer() [2/3]
MutableBuffer::MutableBuffer (size_t l, size_t d)
Constructor with explicitly set size and default.
Parameters
l Initial length.
d The explicit default size.
Definition at line 161 of file MutableBufferClass.cpp.
References bufferLength, data, defaultSize, new_buffer(), and OREF_NULL.
MutableBuffer() [3/3]
MutableBuffer::MutableBuffer (RESTORETYPE restoreType) inline
Definition at line 62 of file MutableBufferClass.hpp.
Member Function Documentation
adjustGap()
void MutableBuffer::adjustGap (size_t offset, size_t _size, size_t _newSize) inline
Definition at line 141 of file MutableBufferClass.hpp.
References BufferClassBase::adjustGap(), data, and dataLength.
Referenced by replaceAt().
append() [1/4]
void MutableBuffer::append (char c)
Append a character to this buffer.
Parameters
c The character to append.
Definition at line 399 of file MutableBufferClass.cpp.
References copyData(), dataLength, and ensureCapacity().
Referenced by StringUtil::encodeBase64(), InputRedirector::readBuffered(), and setText().
append() [2/4]
void MutableBuffer::append (const char * string) inline
Definition at line 137 of file MutableBufferClass.hpp.
References append().
Referenced by append().
append() [3/4]
void MutableBuffer::append (const char * d, size_t l)
Append a value to this buffer.
Parameters
d The data to append.
l The length of the data to append.
Definition at line 384 of file MutableBufferClass.cpp.
References copyData(), dataLength, and ensureCapacity().
append() [4/4]
void MutableBuffer::append (RexxString * s) inline
Definition at line 136 of file MutableBufferClass.hpp.
References append(), RexxString::getLength(), and RexxString::getStringData().
Referenced by append().
appendRexx()
MutableBuffer * MutableBuffer::appendRexx (RexxObject ** args, size_t argc)
Append a value to this buffer.
Parameters
obj The object to append.
Returns
returns the same buffer.
Definition at line 323 of file MutableBufferClass.cpp.
References ARG_ONE, copyData(), dataLength, ensureCapacity(), OREF_NULL, and stringArgument().
Referenced by MemoryObject::createImage().
brackets()
RexxString * MutableBuffer::brackets (RexxInteger * argposition, RexxInteger * arglength)
Extract a substring from the the buffer data, using brackets semantics.
Parameters
argposition The starting position of the substring.
arglength The length to extract.
pad An optional pad character.
Returns
The extraced substring, as a string.
Definition at line 787 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::substr().
Referenced by MemoryObject::createImage().
bracketsEqual()
MutableBuffer * MutableBuffer::bracketsEqual (RexxObject * str, RexxObject * pos, RexxObject * len)
Replace a target substring within a string with a new string value. This is similar overlay, but replacing might cause the characters following the replacement position to be shifted to the left or right. This is the "[]=" form.
Parameters
str The replacement string.
pos The target position (required).
len The target length (optional). If not specified, the length of the replacement string is used, and this is essentially an overlay operation.
Returns
The target mutablebuffer object.
Definition at line 545 of file MutableBufferClass.cpp.
References OREF_NULL, and replaceAt().
Referenced by MemoryObject::createImage().
caselessChangeStr()
MutableBuffer * MutableBuffer::caselessChangeStr (RexxString * needle, RexxString * newNeedle, RexxInteger * countArg)
Do an inplace caseless changeStr operation on a mutablebuffer.
Parameters
needle The search needle.
newNeedle The replacement string.
countArg The number of occurrences to replace.
Returns
The target MutableBuffer
Definition at line 1136 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessCountStr(), StringUtil::caselessPos(), copyData(), dataLength, ensureCapacity(), getLength(), RexxString::getLength(), getStringData(), RexxString::getStringData(), Numerics::MAX_WHOLENUMBER, openGap(), optionalNonNegative(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessContains()
RexxObject * MutableBuffer::caselessContains (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Perform a caseless search for a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
range The length of the range to search in.
Returns
.true if the string is found, .false otherwise.
Definition at line 869 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, booleanObject(), StringUtil::caselessPos(), getLength(), getStringData(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessContainsWord()
RexxObject * MutableBuffer::caselessContainsWord (RexxString * phrase, RexxInteger * pstart)
Perform a caseless wordpos search on a string object.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 1887 of file MutableBufferClass.cpp.
References booleanObject(), StringUtil::caselessWordPos(), getLength(), and getStringData().
Referenced by MemoryObject::createImage().
caselessCountStrRexx()
RexxInteger * MutableBuffer::caselessCountStrRexx (RexxString * needle)
Count occurrences of one string in another, using caseless comparisons.
Parameters
needle The target search needle.
Returns
The count of the characters.
Definition at line 955 of file MutableBufferClass.cpp.
References ARG_ONE, StringUtil::caselessCountStr(), getLength(), getStringData(), Numerics::MAX_WHOLENUMBER, new_integer(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessEndsWithRexx()
RexxObject * MutableBuffer::caselessEndsWithRexx (RexxString * other)
Test if a string ends with another string
Parameters
other The other compare string.
Returns
True if the string starts with the other, false otherwise.
Definition at line 1590 of file MutableBufferClass.cpp.
References booleanObject(), getLength(), RexxString::getLength(), primitiveCaselessMatch(), stringArgument(), and TheFalseObject.
Referenced by MemoryObject::createImage().
caselessLastPos()
RexxInteger * MutableBuffer::caselessLastPos (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Perform a caseless search for the last position of a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
Returns
The index of the located string. Returns 0 if no matches are found.
Definition at line 890 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessLastPos(), getLength(), getStringData(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessMatch()
RexxObject * MutableBuffer::caselessMatch (RexxInteger * start_, RexxString * other, RexxInteger * offset_, RexxInteger * len_)
Test if regions within two strings match.
Parameters
start_ The starting compare position within the target string. This must be within the bounds of the string.
other The other compare string.
offset_ The starting offset of the compare string. This must be within the string bounds. The default start postion is 1.
len_ The length of the compare substring. The length and the offset must specify a valid substring of other. If not specified, this defaults to the substring from the offset to the end of the string.
Returns
True if the two regions match, false for any mismatch.
Definition at line 1505 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, booleanObject(), getLength(), RexxString::getLength(), optionalLengthArgument(), optionalPositionArgument(), OREF_NULL, positionArgument(), primitiveCaselessMatch(), stringArgument(), and TheFalseObject.
Referenced by MemoryObject::createImage().
caselessMatchChar()
RexxObject * MutableBuffer::caselessMatchChar (RexxInteger * position_, RexxString * matchSet)
Compare a single character at a give position against a set of characters to see if any of the characters is a match.
Parameters
position_ The character position
matchSet The set to compare against.
Returns
true if the character at the give position is any of the characters, false if none of them match.
Definition at line 1705 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, getChar(), RexxString::getChar(), getLength(), RexxString::getLength(), positionArgument(), stringArgument(), TheFalseObject, TheTrueObject, and Utilities::toUpper().
Referenced by MemoryObject::createImage().
caselessPos()
RexxInteger * MutableBuffer::caselessPos (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Perform a caseless search for a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
range The length of the range to search in.
Returns
The index of the located string. Returns 0 if no matches are found.
Definition at line 851 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessPos(), getLength(), getStringData(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessStartsWithRexx()
RexxObject * MutableBuffer::caselessStartsWithRexx (RexxString * other)
Test if a string starts with another string
Parameters
other The other compare string.
Returns
True if the string starts with the other, false otherwise.
Definition at line 1555 of file MutableBufferClass.cpp.
References booleanObject(), RexxString::getLength(), primitiveCaselessMatch(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessWordPos()
RexxInteger * MutableBuffer::caselessWordPos (RexxString * phrase, RexxInteger * pstart)
Perform a caseless wordpos search on a string object.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 1873 of file MutableBufferClass.cpp.
References StringUtil::caselessWordPos(), getLength(), getStringData(), and new_integer().
Referenced by MemoryObject::createImage().
changeStr()
MutableBuffer * MutableBuffer::changeStr (RexxString * needle, RexxString * newNeedle, RexxInteger * countArg)
Do an inplace changeStr operation on a mutablebuffer.
Parameters
needle The search needle.
newNeedle The replacement string.
countArg The number of occurrences to replace.
Returns
The target MutableBuffer
Definition at line 971 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, copyData(), StringUtil::countStr(), dataLength, ensureCapacity(), getLength(), RexxString::getLength(), getStringData(), RexxString::getStringData(), Numerics::MAX_WHOLENUMBER, openGap(), optionalNonNegative(), StringUtil::pos(), and stringArgument().
Referenced by MemoryObject::createImage().
closeGap()
void MutableBuffer::closeGap (size_t offset, size_t _size, size_t tailSize) inline
Definition at line 140 of file MutableBufferClass.hpp.
References BufferClassBase::closeGap(), and data.
Referenced by delWord(), and mydelete().
containsRexx()
RexxObject * MutableBuffer::containsRexx (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Test if the buffer contains a given string within a specified range.
Parameters
needle The search needle.
pstart the starting position.
range The length of the search range.
Returns
.true if the string is found, .false otherwise
Definition at line 819 of file MutableBufferClass.cpp.
References StringUtil::containsRexx(), getLength(), and getStringData().
Referenced by MemoryObject::createImage().
containsWord()
RexxObject * MutableBuffer::containsWord (RexxString * phrase, RexxInteger * pstart)
Test if the buffer contains a given word phrase.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 1859 of file MutableBufferClass.cpp.
References booleanObject(), getLength(), getStringData(), and StringUtil::wordPos().
Referenced by MemoryObject::createImage().
copy()
RexxInternalObject * MutableBuffer::copy () override virtual
copy an object
Returns
A copy of the object.
Reimplemented from RexxInternalObject.
Definition at line 217 of file MutableBufferClass.cpp.
References bufferLength, RexxObject::copy(), copyData(), data, BufferClass::getData(), and new_buffer().
copyData()
void MutableBuffer::copyData (size_t offset, const char * string, size_t l) inline
Definition at line 138 of file MutableBufferClass.hpp.
References BufferClassBase::copyData(), and data.
Referenced by append(), appendRexx(), caselessChangeStr(), changeStr(), copy(), insert(), overlay(), replaceAt(), and space().
countStrRexx()
RexxInteger * MutableBuffer::countStrRexx (RexxString * needle)
Count occurrences of one string in another.
Parameters
needle The needle string to count.
Returns
The count of occurrences of the string in the buffer.
Definition at line 940 of file MutableBufferClass.cpp.
References ARG_ONE, StringUtil::countStr(), getLength(), getStringData(), Numerics::MAX_WHOLENUMBER, new_integer(), and stringArgument().
Referenced by MemoryObject::createImage().
createInstance()
void MutableBuffer::createInstance () static
Create initial class object at bootstrap time.
Definition at line 62 of file MutableBufferClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
delWord()
MutableBuffer * MutableBuffer::delWord (RexxInteger * position, RexxInteger * plength)
Perform a delword operation on a mutable buffer
Parameters
position The position to delete.
plength The number of words to delete
Returns
Always returns the target mutable buffer.
Definition at line 1901 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, closeGap(), dataLength, getData(), getLength(), getStringData(), Numerics::MAX_WHOLENUMBER, optionalLengthArgument(), positionArgument(), RexxString::WordIterator::scanPosition(), RexxString::WordIterator::skipBlanks(), RexxString::WordIterator::skipWords(), and RexxString::WordIterator::wordPointer().
Referenced by MemoryObject::createImage().
endsWithRexx()
RexxObject * MutableBuffer::endsWithRexx (RexxString * other)
Test if a string ends with another string
Parameters
other The other compare string.
Returns
True if the string starts with the other, false otherwise.
Definition at line 1569 of file MutableBufferClass.cpp.
References booleanObject(), getLength(), RexxString::getLength(), primitiveMatch(), stringArgument(), and TheFalseObject.
Referenced by MemoryObject::createImage().
ensureCapacity()
void MutableBuffer::ensureCapacity (size_t addedLength)
Ensure that the MutableBuffer has sufficient space for an append operation.
Parameters
addedLength The additional length required.
Definition at line 236 of file MutableBufferClass.cpp.
References bufferLength, data, dataLength, BufferClass::expand(), and setField.
Referenced by append(), appendRexx(), caselessChangeStr(), changeStr(), insert(), overlay(), replaceAt(), setCapacity(), and space().
flatten()
void MutableBuffer::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxVirtualBase.
Definition at line 201 of file MutableBufferClass.cpp.
References cleanUpFlatten, data, flattenRef, and setUpFlatten.
getBufferSize()
RexxInteger* MutableBuffer::getBufferSize () inline
Definition at line 91 of file MutableBufferClass.hpp.
References bufferLength, and new_integer().
Referenced by MemoryObject::createImage().
getCapacity()
size_t MutableBuffer::getCapacity () inline
Definition at line 145 of file MutableBufferClass.hpp.
References bufferLength.
Referenced by setDataLength().
getChar()
char MutableBuffer::getChar (size_t offset) inline
Definition at line 144 of file MutableBufferClass.hpp.
References getData().
Referenced by caselessMatchChar(), and matchChar().
getData()
char* MutableBuffer::getData () inline
Definition at line 133 of file MutableBufferClass.hpp.
References data, and BufferClass::getData().
Referenced by delWord(), getChar(), lower(), setCapacity(), space(), translate(), and upper().
getLength()
size_t MutableBuffer::getLength () inline
Definition at line 132 of file MutableBufferClass.hpp.
References dataLength.
Referenced by brackets(), caselessChangeStr(), caselessContains(), caselessContainsWord(), caselessCountStrRexx(), caselessEndsWithRexx(), caselessLastPos(), caselessMatch(), caselessMatchChar(), caselessPos(), caselessWordPos(), changeStr(), containsRexx(), containsWord(), countStrRexx(), delWord(), endsWithRexx(), lastPos(), lower(), makeArrayRexx(), match(), matchChar(), posRexx(), primitiveCaselessMatch(), primitiveMatch(), InputRedirector::readBuffered(), setDataLength(), space(), subchar(), substr(), subWord(), subWords(), translate(), upper(), verify(), word(), wordIndex(), wordLength(), wordPos(), and words().
getStringData()
const char* MutableBuffer::getStringData () inline
Definition at line 131 of file MutableBufferClass.hpp.
References data, and BufferClass::getData().
Referenced by brackets(), caselessChangeStr(), caselessContains(), caselessContainsWord(), caselessCountStrRexx(), caselessLastPos(), caselessPos(), caselessWordPos(), changeStr(), containsRexx(), containsWord(), countStrRexx(), delWord(), lastPos(), makeArrayRexx(), posRexx(), primitiveCaselessMatch(), primitiveMatch(), InputRedirector::readBuffered(), subchar(), substr(), subWord(), subWords(), verify(), word(), wordIndex(), wordLength(), wordPos(), and words().
insert()
MutableBuffer * MutableBuffer::insert (RexxObject * str, RexxObject * pos, RexxObject * len, RexxObject * pad)
insert string at given position
Parameters
str The string to insert.
pos The starting position.
len The insertion length.
pad Any pad character.
Returns
The same mutable buffer object.
Definition at line 420 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, copyData(), dataLength, ensureCapacity(), RexxString::getLength(), RexxString::getStringData(), openGap(), optionalLengthArgument(), optionalNonNegative(), optionalPadArgument(), setData(), and stringArgument().
Referenced by MemoryObject::createImage().
lastPos()
RexxInteger * MutableBuffer::lastPos (RexxString * needle, RexxInteger * _start, RexxInteger * _range)
Perform a search for the last position of a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
Returns
The index of the located string. Returns 0 if no matches are found.
Definition at line 835 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::lastPosRexx().
Referenced by MemoryObject::createImage().
lengthRexx()
RexxObject * MutableBuffer::lengthRexx ()
Return the length of the data in the buffer currently.
Returns
The current length, as an Integer object.
Definition at line 310 of file MutableBufferClass.cpp.
References dataLength, and new_integer().
Referenced by MemoryObject::createImage().
live()
void MutableBuffer::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 177 of file MutableBufferClass.cpp.
References data, and memory_mark.
liveGeneral()
void MutableBuffer::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 189 of file MutableBufferClass.cpp.
References data, and memory_mark_general.
lower()
MutableBuffer * MutableBuffer::lower (RexxInteger * _start, RexxInteger * _length)
Rexx exported method stub for the lower() method.
Parameters
start The optional starting location. Defaults to the first character if not specified.
length The length to convert. Defaults to the segment from the start position to the end of the string.
Returns
A new string object with the case conversion applied.
Definition at line 1301 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, getData(), getLength(), optionalLengthArgument(), optionalPositionArgument(), and Utilities::toLower().
Referenced by MemoryObject::createImage().
makeArray()
ArrayClass * MutableBuffer::makeArray () override virtual
Baseclass optimization for handling request array calls.
Returns
The string object converted to an array using default arguments.
Reimplemented from RexxInternalObject.
Definition at line 728 of file MutableBufferClass.cpp.
References RexxObject::makeArrayRexx(), and OREF_NULL.
makeArrayRexx()
ArrayClass * MutableBuffer::makeArrayRexx (RexxString * div)
Split buffer data into an array into an array
Parameters
div The optional separator string.
Returns
An array of the split data.
Definition at line 927 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::makearray().
makeString()
RexxString * MutableBuffer::makeString () override virtual
Handle a REQUEST('STRING') request for a mutablebuffer object
Returns
the string value of the buffer.
Reimplemented from RexxInternalObject.
Definition at line 717 of file MutableBufferClass.cpp.
References data, dataLength, BufferClass::getData(), and new_string().
Referenced by primitiveMakeString(), and stringValue().
match()
RexxObject * MutableBuffer::match (RexxInteger * start_, RexxString * other, RexxInteger * offset_, RexxInteger * len_)
Test if regions within two strings match.
Parameters
start_ The starting compare position within the target string. This must be within the bounds of the string.
other The other compare string.
offset_ The starting offset of the compare string. This must be within the string bounds. The default start postion is 1.
len_ The length of the compare substring. The length and the offset must specify a valid substring of other. If not specified, this defaults to the substring from the offset to the end of the string.
Returns
True if the two regions match, false for any mismatch.
Definition at line 1460 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, booleanObject(), getLength(), RexxString::getLength(), optionalLengthArgument(), optionalPositionArgument(), OREF_NULL, positionArgument(), primitiveMatch(), stringArgument(), and TheFalseObject.
Referenced by MemoryObject::createImage().
matchChar()
RexxObject * MutableBuffer::matchChar (RexxInteger * position_, RexxString * matchSet)
Compare a single character at a give position against a set of characters to see if any of the characters is a match.
Parameters
position_ The character position
matchSet The set to compare against.
Returns
true if the character at the give position is any of the characters, false if none of them match.
Definition at line 1668 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, getChar(), RexxString::getChar(), getLength(), RexxString::getLength(), positionArgument(), stringArgument(), TheFalseObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
mydelete()
MutableBuffer * MutableBuffer::mydelete (RexxObject * _start, RexxObject * len)
Delete a character range in the buffer.
Parameters
_start The starting delete position.
len The length to delete.
Returns
The same buffer.
Definition at line 647 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, closeGap(), data, dataLength, BufferClassBase::getDataLength(), optionalLengthArgument(), and optionalPositionArgument().
Referenced by MemoryObject::createImage().
newRexx()
MutableBuffer * MutableBuffer::newRexx (RexxObject ** args, size_t argc)
Allocate a MutableBuffer object from Rexx code.
Parameters
args The pointer to the arrays.
argc The count of arguments.
Returns
A new mutable buffer object.
Definition at line 90 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, bufferLength, RexxClass::completeNewObject(), DEFAULT_BUFFER_LENGTH, defaultSize, RexxString::getLength(), RexxString::getStringData(), MutableBuffer(), optionalLengthArgument(), and stringArgument().
Referenced by MemoryObject::createImage().
openGap()
void MutableBuffer::openGap (size_t offset, size_t _size, size_t tailSize) inline
Definition at line 139 of file MutableBufferClass.hpp.
References data, and BufferClassBase::openGap().
Referenced by caselessChangeStr(), changeStr(), insert(), and space().
operator new()
void * MutableBuffer::operator new (size_t size)
Create a new mutable buffer object from a potential subclass.
Parameters
size The size of the buffer object.
Returns
A new instance of a mutable buffer, with the default class behaviour.
Definition at line 76 of file MutableBufferClass.cpp.
References new_object(), and T_MutableBuffer.
overlay()
MutableBuffer * MutableBuffer::overlay (RexxObject * str, RexxObject * pos, RexxObject * len, RexxObject * pad)
Overlay a string value on the buffer data.
Parameters
str The string to overlay.
pos The position to start the overlay.
len The length of the overlay.
pad An optional pad character.
Returns
The same mutable buffer.
Definition at line 493 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, copyData(), dataLength, ensureCapacity(), RexxString::getLength(), RexxString::getStringData(), optionalLengthArgument(), optionalPadArgument(), optionalPositionArgument(), setData(), and stringArgument().
Referenced by MemoryObject::createImage().
posRexx()
RexxInteger * MutableBuffer::posRexx (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Perform a search for a string within the buffer.
Parameters
needle The search needle.
pstart the starting position.
range The length of the search range.
Returns
The index of the located string. Returns 0 if no matches are found.
Definition at line 803 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::posRexx().
Referenced by MemoryObject::createImage().
primitiveCaselessMatch()
bool MutableBuffer::primitiveCaselessMatch (size_t _start, RexxString * other, size_t offset, size_t len)
Perform a caselesee compare of regions of two string objects. Returns true if the two regions match, returns false for mismatches.
Parameters
start The starting offset within the target string.
other The source string for the compare.
offset The offset of the substring of the other string to use.
len The length of the substring to compare.
Returns
True if the regions match, false otherwise.
Definition at line 1642 of file MutableBufferClass.cpp.
References StringUtil::caselessCompare(), getLength(), getStringData(), and RexxString::getStringData().
Referenced by caselessEndsWithRexx(), caselessMatch(), and caselessStartsWithRexx().
primitiveMakeString()
RexxString * MutableBuffer::primitiveMakeString () override virtual
Handle the primitive class makeString optimization. This is required because MutableBuffer implements a STRING method.
Returns
The string value of the buffer
Reimplemented from RexxInternalObject.
Definition at line 753 of file MutableBufferClass.cpp.
References makeString().
primitiveMatch()
bool MutableBuffer::primitiveMatch (size_t _start, RexxString * other, size_t offset, size_t len)
Perform a compare of regions of two string objects. Returns true if the two regions match, returns false for mismatches.
Parameters
start The starting offset within the target string.
other The source string for the compare.
offset The offset of the substring of the other string to use.
len The length of the substring to compare.
Returns
True if the regions match, false otherwise.
Definition at line 1615 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and RexxString::getStringData().
Referenced by endsWithRexx(), match(), and startsWithRexx().
replaceAt()
MutableBuffer * MutableBuffer::replaceAt (RexxObject * str, RexxObject * pos, RexxObject * len, RexxObject * pad)
Replace a target substring within a string with a new string value. This is similar overlay, but replacing might cause the characters following the replacement position to be shifted to the left or right.
Parameters
str The replacement string.
pos The target position (required).
len The target length (optional). If not specified, the length of the replacement string is used, and this is essentially an overlay operation.
pad A padding character if padding is required. The default pad is a ' '. Padding only occurs if the replacement position is beyond the current data length.
Returns
The target mutablebuffer object.
Definition at line 570 of file MutableBufferClass.cpp.
References adjustGap(), copyData(), dataLength, ensureCapacity(), RexxString::getStringData(), optionalLengthArgument(), optionalPadArgument(), positionArgument(), setData(), and stringArgument().
Referenced by bracketsEqual(), and MemoryObject::createImage().
setBufferSize()
RexxObject * MutableBuffer::setBufferSize (RexxInteger * size)
Set the size of the buffer.
Parameters
size The size to set.
Returns
Returns the same mutable buffer.
Definition at line 679 of file MutableBufferClass.cpp.
References ARG_ONE, bufferLength, BufferClassBase::copyData(), data, dataLength, defaultSize, BufferClass::getData(), lengthArgument(), new_buffer(), and setField.
Referenced by MemoryObject::createImage().
setCapacity()
char * MutableBuffer::setCapacity (size_t newLength)
Set the capacity of the buffer.
Parameters
newLength The new buffer length
Returns
The pointer to the data area in the buffer.
Definition at line 292 of file MutableBufferClass.cpp.
References bufferLength, ensureCapacity(), and getData().
setData()
void MutableBuffer::setData (size_t offset, char character, size_t l) inline
Definition at line 142 of file MutableBufferClass.hpp.
References data, and BufferClassBase::setData().
Referenced by insert(), overlay(), replaceAt(), setDataLength(), and space().
setDataLength()
size_t MutableBuffer::setDataLength (size_t newLength)
Set the length of the data in the buffer. The limit is the current capacity of the buffer. If the length is extended beyond the current length, the extra characters of the buffer will be filled with nulls.
Parameters
newLength The new datalength. This is capped to the capacity of the buffer.
Returns
The actual length the data has been set to. If the target length is greater than the capacity, the capacity value is returned.
Definition at line 264 of file MutableBufferClass.cpp.
References dataLength, getCapacity(), getLength(), and setData().
setText()
void MutableBuffer::setText (RexxString * string)
Primitive level method for setting a mutable buffer to a given text value.
Parameters
string The new string value for the buffer.
Definition at line 369 of file MutableBufferClass.cpp.
References append(), dataLength, RexxString::getLength(), and RexxString::getStringData().
Referenced by setTextRexx().
setTextRexx()
MutableBuffer * MutableBuffer::setTextRexx (RexxObject * obj)
Rexx method for setting a mutable buffer to a given text value.
Parameters
obj The argument object.
Returns
Always returns the mutablebuffer instance.
Definition at line 355 of file MutableBufferClass.cpp.
References ARG_ONE, setText(), and stringArgument().
Referenced by MemoryObject::createImage().
space()
MutableBuffer * MutableBuffer::space (RexxInteger * space_count, RexxString * pad)
Do an inplace space() operation on a mutable buffer.
Parameters
space_count The number of pad characters between each word
pad The pad character
Returns
The target MutableBuffer
Definition at line 1962 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, copyData(), dataLength, ensureCapacity(), getData(), getLength(), RexxString::WordIterator::next(), openGap(), optionalLengthArgument(), optionalPadArgument(), setData(), RexxString::WordIterator::wordLength(), and RexxString::WordIterator::wordPointer().
Referenced by MemoryObject::createImage().
startsWithRexx()
RexxObject * MutableBuffer::startsWithRexx (RexxString * other)
Test if a string starts with another string
Parameters
other The other compare string.
Returns
True if the string starts with the other, false otherwise.
Definition at line 1541 of file MutableBufferClass.cpp.
References booleanObject(), RexxString::getLength(), primitiveMatch(), and stringArgument().
Referenced by MemoryObject::createImage().
stringValue()
RexxString * MutableBuffer::stringValue () override virtual
Return the primitive string value of this object
Returns
this always just forwards to makeString
Reimplemented from RexxInternalObject.
Definition at line 740 of file MutableBufferClass.cpp.
References makeString().
subchar()
RexxString * MutableBuffer::subchar (RexxInteger * positionArg)
Extract a single character from a string object. Returns a null string if the specified position is beyond the bounds of the string.
Parameters
positionArg The position of the target character. Must be a positive whole number.
Returns
Returns the single character at the target position. Returns a null string if the position is beyond the end of the string.
Definition at line 914 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::subchar().
Referenced by MemoryObject::createImage().
substr()
RexxString * MutableBuffer::substr (RexxInteger * argposition, RexxInteger * arglength, RexxString * pad)
Extract a substring from the the buffer data.
Parameters
argposition The starting position of the substring.
arglength The length to extract.
pad An optional pad character.
Returns
The extraced substring, as a string.
Definition at line 770 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::substr().
Referenced by MemoryObject::createImage().
subWord()
RexxString * MutableBuffer::subWord (RexxInteger * position, RexxInteger * plength)
Perform a subword extraction from a mutable buffer.
Parameters
position The first word to be extracted.
plength The number of words to extract.
Returns
The substring containing the extacted words.
Definition at line 1758 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::subWord().
Referenced by MemoryObject::createImage().
subWords()
ArrayClass * MutableBuffer::subWords (RexxInteger * position, RexxInteger * plength)
Returns an array of all words contained in the given range of the string, using the same extraction rules used for subWord() and word().
Parameters
position The optional starting position. If not provided, extraction starts with the first word.
plength The number of words to extract. If omitted, will extract from the starting postion to the end of the string.
Returns
An array containing the extracted words. If no words are available within the given range, this returns an empty array.
Definition at line 1778 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::subWords().
Referenced by MemoryObject::createImage().
translate()
MutableBuffer * MutableBuffer::translate (RexxString * tableo, RexxString * tablei, RexxString * pad, RexxInteger * _start, RexxInteger * _range)
translate characters in the buffer using a translation table.
Parameters
tableo The output table specification
tablei The input table specification
pad An optional padding character (default is a space).
_start The starting position to translate.
_range The length to translate
Returns
The target mutable buffer.
Definition at line 1382 of file MutableBufferClass.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, getData(), getLength(), RexxString::getLength(), RexxString::getStringData(), StringUtil::memPos(), optionalLengthArgument(), optionalPadArgument(), optionalPositionArgument(), optionalStringArgument(), OREF_NULL, and upper().
Referenced by MemoryObject::createImage().
upper()
MutableBuffer * MutableBuffer::upper (RexxInteger * _start, RexxInteger * _length)
Rexx exported method stub for the upper() method.
Parameters
start The optional starting location. Defaults to the first character if not specified.
length The length to convert. Defaults to the segment from the start position to the end of the string.
Returns
A new string object with the case conversion applied.
Definition at line 1341 of file MutableBufferClass.cpp.
References ARG_ONE, ARG_TWO, getData(), getLength(), optionalLengthArgument(), optionalPositionArgument(), and Utilities::toUpper().
Referenced by MemoryObject::createImage(), and translate().
verify()
RexxInteger * MutableBuffer::verify (RexxString * ref, RexxString * option, RexxInteger * _start, RexxInteger * range)
Perform a character verify operation on a mutable buffer.
Parameters
ref The reference string.
option The match/nomatch option.
_start The start position for the verify.
range The range to search
Returns
The offset of the first match/mismatch within the buffer.
Definition at line 1744 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::verify().
Referenced by MemoryObject::createImage().
word()
RexxString * MutableBuffer::word (RexxInteger * position)
Extract a given word from a mutable buffer.
Parameters
position The target word position.
Returns
The extracted word, as a string.
Definition at line 1791 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::word().
Referenced by MemoryObject::createImage().
wordIndex()
RexxInteger * MutableBuffer::wordIndex (RexxInteger * position)
return the index of a given word position in a mutable buffer
Parameters
position The target word position.
Returns
The position of the target word.
Definition at line 1805 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::wordIndex().
Referenced by MemoryObject::createImage().
wordLength()
RexxInteger * MutableBuffer::wordLength (RexxInteger * position)
return the length of a given word position in a mutable buffer
Parameters
position The target word position.
Returns
The length of the target word.
Definition at line 1820 of file MutableBufferClass.cpp.
References getLength(), getStringData(), and StringUtil::wordLength().
Referenced by MemoryObject::createImage().
wordPos()
RexxInteger * MutableBuffer::wordPos (RexxString * phrase, RexxInteger * pstart)
Perform a wordpos search on a mutablebuffer object.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 1845 of file MutableBufferClass.cpp.
References getLength(), getStringData(), new_integer(), and StringUtil::wordPos().
Referenced by MemoryObject::createImage().
words()
RexxInteger * MutableBuffer::words ()
Return the count of words in the buffer.
Returns
The buffer word count.
Definition at line 1830 of file MutableBufferClass.cpp.
References getLength(), getStringData(), new_integer(), and StringUtil::wordCount().
Referenced by MemoryObject::createImage().
Member Data Documentation
bufferLength
size_t MutableBuffer::bufferLength protected
Definition at line 157 of file MutableBufferClass.hpp.
Referenced by copy(), ensureCapacity(), getBufferSize(), getCapacity(), MutableBuffer(), newRexx(), setBufferSize(), and setCapacity().
classInstance
RexxClass * MutableBuffer::classInstance = OREF_NULL static
Definition at line 153 of file MutableBufferClass.hpp.
data
BufferClass* MutableBuffer::data protected
Definition at line 160 of file MutableBufferClass.hpp.
Referenced by adjustGap(), closeGap(), copy(), copyData(), ensureCapacity(), flatten(), getData(), getStringData(), live(), liveGeneral(), makeString(), MutableBuffer(), mydelete(), openGap(), setBufferSize(), and setData().
dataLength
size_t MutableBuffer::dataLength protected
Definition at line 159 of file MutableBufferClass.hpp.
Referenced by adjustGap(), append(), appendRexx(), caselessChangeStr(), changeStr(), delWord(), ensureCapacity(), getLength(), insert(), lengthRexx(), makeString(), mydelete(), overlay(), replaceAt(), setBufferSize(), setDataLength(), setText(), and space().
DEFAULT_BUFFER_LENGTH
const size_t MutableBuffer::DEFAULT_BUFFER_LENGTH = 256 static
Definition at line 150 of file MutableBufferClass.hpp.
Referenced by MutableBuffer(), and newRexx().
defaultSize
size_t MutableBuffer::defaultSize protected
Definition at line 158 of file MutableBufferClass.hpp.
Referenced by MutableBuffer(), newRexx(), and setBufferSize().
The documentation for this class was generated from the following files:
MutableBufferClass.hpp
MutableBufferClass.cpp