ooRexx: CompoundVariableTable Class Reference
CompoundVariableTable Class Reference
#include <CompoundVariableTable.hpp>
Classes
class TableIterator
Public Member Functions
CompoundVariableTable ()
void copyFrom (CompoundVariableTable &other)
void init (StemClass *parent)
void clear ()
CompoundTableElement * get (CompoundVariableTail &name)
CompoundTableElement * findEntry (CompoundVariableTail &tail)
CompoundTableElement * findEntry (CompoundVariableTail &tail, bool create)
CompoundTableElement * findEntry (RexxString *tail, bool create=false)
void balance (CompoundTableElement *node)
void moveNode (CompoundTableElement *&anchor, bool toright)
CompoundTableElement * first ()
CompoundTableElement * findLeaf (CompoundTableElement *node)
CompoundTableElement * next (CompoundTableElement *node)
void setParent (StemClass *parent)
void setRoot (CompoundTableElement *newRoot)
TableIterator iterator ()
Protected Attributes
CompoundTableElement * root
StemClass * parent
Friends
class StemClass
Detailed Description
Compound table object embedded within a Stem object. This is not a Rexx internal object, but rather a helper object used as a field within another object
Definition at line 72 of file CompoundVariableTable.hpp.
Constructor & Destructor Documentation
CompoundVariableTable()
CompoundVariableTable::CompoundVariableTable () inline
Definition at line 104 of file CompoundVariableTable.hpp.
Member Function Documentation
balance()
void CompoundVariableTable::balance (CompoundTableElement * node)
Balance the compound variable tree.
Parameters
node The location of the just inserted node. We balance from here.
Definition at line 197 of file CompoundVariableTable.cpp.
References CompoundTableElement::isRightChild(), CompoundTableElement::leftDepth, moveNode(), OREF_NULL, CompoundTableElement::parent, CompoundTableElement::rightDepth, and root.
Referenced by findEntry().
clear()
void CompoundVariableTable::clear ()
Clear the entire table.
Definition at line 89 of file CompoundVariableTable.cpp.
References OREF_NULL, and setRoot().
Referenced by StemClass::bracketEqual(), and StemClass::empty().
copyFrom()
void CompoundVariableTable::copyFrom (CompoundVariableTable & other)
Copy all of the entries from another compound table into this table.
Parameters
other The source tail collection.
Definition at line 70 of file CompoundVariableTable.cpp.
References findEntry(), first(), RexxVariable::getName(), next(), OREF_NULL, CompoundTableElement::setValue(), and RexxVariable::variableValue.
Referenced by StemClass::copyFrom().
findEntry() [1/3]
CompoundTableElement * CompoundVariableTable::findEntry (CompoundVariableTail & tail)
Search for a compound entry. This version is optimized for "find-but-don't create" usage.
Parameters
tail The tail name we're searching for.
Returns
The located position, if any.
Definition at line 475 of file CompoundVariableTable.cpp.
References CompoundVariableTail::compare(), RexxVariable::getName(), CompoundTableElement::left, OREF_NULL, CompoundTableElement::right, and root.
Referenced by copyFrom(), StemClass::expose(), StemClass::exposeCompoundVariable(), StemClass::findCompoundVariable(), findEntry(), get(), and StemClass::getCompoundVariable().
findEntry() [2/3]
CompoundTableElement * CompoundVariableTable::findEntry (CompoundVariableTail & tail, bool create)
Locate a compound variable item and optionally create a new table entry if not found.
Parameters
tail The constructed tail for comparisons.
create indicates whether we create a new entry if this is not found.
Returns
The entry for the given name, or NULL if not found and not asked to create the entry.
Definition at line 124 of file CompoundVariableTable.cpp.
References balance(), CompoundVariableTail::compare(), RexxVariable::getName(), CompoundTableElement::left, CompoundVariableTail::makeString(), new_compoundElement(), OREF_NULL, CompoundTableElement::right, root, CompoundTableElement::setChild(), CompoundTableElement::setParent(), and setRoot().
findEntry() [3/3]
CompoundTableElement * CompoundVariableTable::findEntry (RexxString * tail, bool create = false)
Locate an entry in the compound table.
Parameters
tail The string name of the tail.
create a flag indicating whether we should create a new element if this is not found. True indicates we're setting a value in the table.
Returns
The located (or created) element. Returns NULL if not located and create is false.
Definition at line 107 of file CompoundVariableTable.cpp.
References findEntry().
findLeaf()
CompoundTableElement * CompoundVariableTable::findLeaf (CompoundTableElement * node)
Find a the "first" leaf node starting from a given node. The first node is the one that first in iteration order, which will be the deepest node. Since we balance, this will either be the left-mode node or the right child of the left-most node.
Parameters
node The starting node.
Returns
The final end node.
Definition at line 369 of file CompoundVariableTable.cpp.
References CompoundTableElement::left, OREF_NULL, and CompoundTableElement::right.
Referenced by first(), and next().
first()
CompoundTableElement * CompoundVariableTable::first ()
Find the first node of the traversal.
Returns
The "first" node in search order.
Definition at line 343 of file CompoundVariableTable.cpp.
References findLeaf(), OREF_NULL, and root.
Referenced by StemClass::allItems(), copyFrom(), StemClass::findByValue(), StemClass::first(), StemClass::items(), StemClass::supplier(), CompoundVariableTable::TableIterator::TableIterator(), StemClass::tailArray(), and StemClass::toDirectory().
get()
CompoundTableElement* CompoundVariableTable::get (CompoundVariableTail & name) inline
Definition at line 110 of file CompoundVariableTable.hpp.
References findEntry().
init()
void CompoundVariableTable::init (StemClass * parentStem)
Initialize a compound table when a Stem object is created.
Parameters
parentStem Our stem parent.
Definition at line 57 of file CompoundVariableTable.cpp.
References OREF_NULL, setParent(), and setRoot().
Referenced by StemClass::copyFrom(), StemClass::init(), and StemClass::StemClass().
iterator()
TableIterator CompoundVariableTable::iterator () inline
Definition at line 122 of file CompoundVariableTable.hpp.
Referenced by StemClass::iterator().
moveNode()
void CompoundVariableTable::moveNode (CompoundTableElement *& anchor, bool toright)
Move a node of the tree.
Parameters
anchor The anchor position for the movement (which might get updated).
toright A flag indicating movement to the right or left.
Definition at line 273 of file CompoundVariableTable.cpp.
References CompoundTableElement::isLeftChild(), CompoundTableElement::left, CompoundTableElement::leftDepth, OREF_NULL, CompoundTableElement::parent, CompoundTableElement::right, CompoundTableElement::rightDepth, CompoundTableElement::setLeft(), CompoundTableElement::setParent(), CompoundTableElement::setRight(), setRoot(), and work.
Referenced by balance().
next()
CompoundTableElement * CompoundVariableTable::next (CompoundTableElement * node)
Step to the "next" node while iterating.
Parameters
node The node we're moving from.
Returns
The next node in iteration order.
Definition at line 405 of file CompoundVariableTable.cpp.
References findLeaf(), CompoundTableElement::isRightChild(), OREF_NULL, CompoundTableElement::parent, and CompoundTableElement::right.
Referenced by StemClass::allItems(), copyFrom(), StemClass::findByValue(), StemClass::items(), CompoundVariableTable::TableIterator::next(), StemClass::supplier(), StemClass::tailArray(), and StemClass::toDirectory().
setParent()
void CompoundVariableTable::setParent (StemClass * parentStem)
Set the parent for a compound table. N.B., this cannot be an inline method because of circular header file dependencies between CompoundVariableTable and StemClass.
Parameters
parentStem The owning Stem object.
Definition at line 442 of file CompoundVariableTable.cpp.
References setOtherField.
Referenced by init().
setRoot()
void CompoundVariableTable::setRoot (CompoundTableElement * newRoot)
Set the root node for a compound table. N.B., this cannot be an inline method because of circular header file dependencies between CompoundVariableTable and StemClass.
Parameters
newRoot The new root node.
Definition at line 459 of file CompoundVariableTable.cpp.
References parent, and setOtherField.
Referenced by clear(), findEntry(), init(), and moveNode().
Friends And Related Function Documentation
StemClass
friend class StemClass friend
Definition at line 74 of file CompoundVariableTable.hpp.
Member Data Documentation
parent
StemClass* CompoundVariableTable::parent protected
Definition at line 127 of file CompoundVariableTable.hpp.
Referenced by setRoot().
root
CompoundTableElement* CompoundVariableTable::root protected
Definition at line 126 of file CompoundVariableTable.hpp.
Referenced by balance(), findEntry(), and first().
The documentation for this class was generated from the following files:
CompoundVariableTable.hpp
CompoundVariableTable.cpp