ooRexx: NumericSettings Class Reference
NumericSettings Class Reference
#include <Numerics.hpp>
Public Member Functions
NumericSettings ()
void setDefault ()
void setDigits (wholenumber_t d)
wholenumber_t getDigits () const
void setForm (bool f)
bool getForm () const
void setFuzz (wholenumber_t f)
wholenumber_t getFuzz () const
Protected Attributes
wholenumber_t digits
wholenumber_t fuzz
bool form
Detailed Description
A class for processing different numeric settings
Definition at line 55 of file Numerics.hpp.
Constructor & Destructor Documentation
NumericSettings()
NumericSettings::NumericSettings ()
Initialize a NumericSettings object.
Definition at line 117 of file Numerics.cpp.
References setDefault().
Member Function Documentation
getDigits()
wholenumber_t NumericSettings::getDigits () const inline
Definition at line 64 of file Numerics.hpp.
References digits.
Referenced by Numerics::digits(), and PackageSetting::getDigits().
getForm()
bool NumericSettings::getForm () const inline
Definition at line 66 of file Numerics.hpp.
References form.
Referenced by Numerics::form(), and PackageSetting::getForm().
getFuzz()
wholenumber_t NumericSettings::getFuzz () const inline
Definition at line 68 of file Numerics.hpp.
References fuzz.
Referenced by Numerics::fuzz(), and PackageSetting::getFuzz().
setDefault()
void NumericSettings::setDefault ()
Set the default numeric settings.
Definition at line 126 of file Numerics.cpp.
References Numerics::DEFAULT_DIGITS, Numerics::DEFAULT_FORM, Numerics::DEFAULT_FUZZ, digits, form, and fuzz.
Referenced by NumericSettings(), and PackageSetting::setDefault().
setDigits()
void NumericSettings::setDigits (wholenumber_t d) inline
Definition at line 63 of file Numerics.hpp.
References digits.
Referenced by PackageSetting::setDigits().
setForm()
void NumericSettings::setForm (bool f) inline
Definition at line 65 of file Numerics.hpp.
References form.
Referenced by PackageSetting::setForm().
setFuzz()
void NumericSettings::setFuzz (wholenumber_t f) inline
Definition at line 67 of file Numerics.hpp.
References fuzz.
Referenced by PackageSetting::setFuzz().
Member Data Documentation
digits
wholenumber_t NumericSettings::digits protected
Definition at line 72 of file Numerics.hpp.
Referenced by getDigits(), setDefault(), and setDigits().
form
bool NumericSettings::form protected
Definition at line 74 of file Numerics.hpp.
Referenced by getForm(), setDefault(), and setForm().
fuzz
wholenumber_t NumericSettings::fuzz protected
Definition at line 73 of file Numerics.hpp.
Referenced by getFuzz(), setDefault(), and setFuzz().
The documentation for this class was generated from the following files:
Numerics.hpp
Numerics.cpp