ooRexx: RexxInstructionCallOn Class Reference
RexxInstructionCallOn Class Reference
#include <CallInstruction.hpp>
Public Member Functions
RexxInstructionCallOn (RexxString *, RexxString *, BuiltinCode)
RexxInstructionCallOn (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
void execute (RexxActivation *, ExpressionStack *) override
void resolve (StringTable *) override
void trap (RexxActivation *context, DirectoryClass *conditionObj) override
Public Member Functions inherited from RexxInstructionTrapBase
RexxInstructionTrapBase ()
Public Member Functions inherited from RexxInstructionCallBase
RexxInstructionCallBase ()
Public Member Functions inherited from RexxInstruction
void * operator new (size_t)
void operator delete (void *)
RexxInstruction (RexxClause *clause, InstructionKeyword type)
RexxInstruction (RESTORETYPE restoreType)
RexxInstruction ()
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
virtual bool isBlock ()
virtual bool isControl ()
const SourceLocation & getLocation ()
void setLocation (const SourceLocation &l)
void setNext (RexxInstruction *next)
RexxInstruction * next ()
bool isLast ()
void setStart (size_t line, size_t off)
void setEnd (size_t line, size_t off)
void setType (InstructionKeyword type)
InstructionKeyword getType ()
bool isType (InstructionKeyword type)
size_t getLineNumber ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Protected Attributes
BuiltinCode builtinIndex
Protected Attributes inherited from RexxInstructionTrapBase
RexxString * conditionName
Protected Attributes inherited from RexxInstructionCallBase
RexxString * targetName
RexxInstruction * targetInstruction
Additional Inherited Members
Static Public Member Functions inherited from RexxInstruction
static void evaluateArguments (RexxActivation *context, ExpressionStack *stack, RexxInternalObject **argArray, size_t argCount)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInstruction
InstructionKeyword instructionType
SourceLocation instructionLocation
RexxInstruction * nextInstruction
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
An instruction object to handle the basics of the CALL ON/OFF instruction.
Definition at line 181 of file CallInstruction.hpp.
Constructor & Destructor Documentation
RexxInstructionCallOn() [1/2]
RexxInstructionCallOn::RexxInstructionCallOn (RexxString * condition, RexxString * name, BuiltinCode builtin_index)
Construct a Call ON instruction object.
Parameters
condition The name of the condition trap
name The name of the call target (NULL if this is CALL OFF)
builtin_index An index for a potential builtin function call.
Definition at line 486 of file CallInstruction.cpp.
References OREF_NULL.
RexxInstructionCallOn() [2/2]
RexxInstructionCallOn::RexxInstructionCallOn (RESTORETYPE restoreType) inline
Definition at line 185 of file CallInstruction.hpp.
Member Function Documentation
execute()
void RexxInstructionCallOn::execute (RexxActivation * context, ExpressionStack * stack) override virtual
Execute a CALL ON/OFF instruction. This either activates or deactivates the call trap. Calling of a target only happens when a trap is activated.
Parameters
context The current program context.
stack The current context evaluation stack.
Reimplemented from RexxInstruction.
Definition at line 570 of file CallInstruction.cpp.
References OREF_NULL, RexxActivation::traceInstruction(), RexxActivation::trapOff(), and RexxActivation::trapOn().
flatten()
void RexxInstructionCallOn::flatten (Envelope * envelope) override virtual
Flatten a source object.
Parameters
envelope The envelope that will hold the flattened object.
Reimplemented from RexxVirtualBase.
Definition at line 532 of file CallInstruction.cpp.
References cleanUpFlatten, flattenRef, RexxInstruction::nextInstruction, and setUpFlatten.
live()
void RexxInstructionCallOn::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 501 of file CallInstruction.cpp.
References memory_mark, and RexxInstruction::nextInstruction.
liveGeneral()
void RexxInstructionCallOn::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 517 of file CallInstruction.cpp.
References memory_mark_general, and RexxInstruction::nextInstruction.
resolve()
void RexxInstructionCallOn::resolve (StringTable * labels) override virtual
Resolve a call target at the end of block processing.
Parameters
labels The table of label instructions in the current context.
Implements RexxInstructionCallBase.
Definition at line 549 of file CallInstruction.cpp.
References HashCollection::get(), and OREF_NULL.
trap()
void RexxInstructionCallOn::trap (RexxActivation * context, DirectoryClass * conditionObj) override virtual
Process a trapped condition.
Parameters
context The trapping context.
conditionObj The condition object associated with the condition.
Reimplemented from RexxInstructionTrapBase.
Definition at line 597 of file CallInstruction.cpp.
References LanguageParser::builtinTable, RexxActivation::externalCall(), RexxActivation::getStack(), RexxActivation::internalCallTrap(), NO_BUILTIN, OREF_NULL, ExpressionStack::push(), RexxActivation::trapDelay(), and RexxActivation::trapUndelay().
Member Data Documentation
builtinIndex
BuiltinCode RexxInstructionCallOn::builtinIndex protected
Definition at line 198 of file CallInstruction.hpp.
The documentation for this class was generated from the following files:
CallInstruction.hpp
CallInstruction.cpp