ooRexx: RexxToken Class Reference
RexxToken Class Reference
#include <Token.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
RexxToken ()
RexxToken (TokenClass c, SourceLocation &l, TokenSubclass sc=SUBTYPE_NONE, RexxString *v=OREF_NULL)
RexxToken (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void setStart (size_t l, size_t o)
void setEnd (size_t l, size_t o)
size_t getLineNumber ()
bool isType (TokenClass t)
bool isType (TokenClass t1, TokenClass t2)
bool isType (TokenClass t1, TokenClass t2, TokenClass t3)
bool isSubtype (TokenSubclass t)
bool isSubtype (TokenSubclass t1, TokenSubclass t2)
TokenClass type ()
TokenSubclass subtype ()
RexxString * value ()
RexxString * upperValue ()
void setType (TokenClass t)
void setSubtype (TokenSubclass t)
void setValue (RexxString *v)
bool isVariable ()
bool isStem ()
bool isNonCompoundVariable ()
bool isSimpleVariable ()
bool isVariableOrDot ()
bool isDotSymbol ()
bool isDot ()
bool isLiteral ()
bool isSymbolOrLiteral ()
bool isConstant ()
bool isNumericSymbol ()
bool isIntegerConstant ()
bool isSymbol ()
bool isOperator ()
bool isOperator (TokenSubclass t)
bool isBlank ()
bool isComma ()
bool isLeftParen ()
bool isRightParen ()
bool isLeftBracket ()
bool isRightBracket ()
bool isEndOfClause ()
bool isEndOfFile ()
bool isBlankSignificant ()
bool isMessageOperator ()
void setNumeric (TokenSubclass v)
const SourceLocation & getLocation ()
void setLocation (const SourceLocation &l)
void checkAssignment (LanguageParser *parser, RexxString *newValue)
int precedence ()
bool isTerminator (int)
RexxString * displayValue ()
InstructionKeyword keyword ()
InstructionSubKeyword subKeyword ()
BuiltinCode builtin ()
ConditionKeyword condition ()
InstructionSubKeyword parseOption ()
DirectiveKeyword keyDirective ()
DirectiveSubKeyword subDirective ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static BuiltinCode resolveBuiltin (RexxString *value)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Protected Member Functions
static int resolveKeyword (RexxString *token, KeywordEntry *table, size_t table_size)
Protected Attributes
RexxString * stringValue
TokenClass classId
TokenSubclass subclass
TokenSubclass numeric
SourceLocation tokenLocation
Static Protected Attributes
static KeywordEntry directives []
static KeywordEntry keywordInstructions []
static KeywordEntry subKeywords []
static KeywordEntry builtinFunctions []
static KeywordEntry conditionKeywords []
static KeywordEntry parseOptions []
static KeywordEntry subDirectives []
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 537 of file Token.hpp.
Constructor & Destructor Documentation
RexxToken() [1/3]
RexxToken::RexxToken () inline
Definition at line 543 of file Token.hpp.
RexxToken() [2/3]
RexxToken::RexxToken (TokenClass c, SourceLocation & l, TokenSubclass sc = SUBTYPE_NONE, RexxString * v = OREF_NULL) inline
Definition at line 544 of file Token.hpp.
RexxToken() [3/3]
RexxToken::RexxToken (RESTORETYPE restoreType) inline
Definition at line 547 of file Token.hpp.
Member Function Documentation
builtin()
BuiltinCode RexxToken::builtin ()
Resolve a token to a builtin identifier.
Returns
The builtin code.
Definition at line 520 of file KeywordConstants.cpp.
References builtinFunctions, isSymbolOrLiteral(), NO_BUILTIN, resolveKeyword(), stringValue, and tabSize.
Referenced by LanguageParser::callNew().
checkAssignment()
void RexxToken::checkAssignment (LanguageParser * parser, RexxString * newValue)
Check and update this token for the special assignment forms (+=, -=, etc.).
Parameters
source The source for the original operator token.
Definition at line 93 of file Token.cpp.
References classId, parser(), stringValue, TOKEN_ASSIGNMENT, and tokenLocation.
condition()
ConditionKeyword RexxToken::condition ()
Resolve a condition name to a keyword code.
Returns
The keyword code corresponding to the condition name.
Definition at line 536 of file KeywordConstants.cpp.
References CONDITION_NONE, conditionKeywords, isSymbol(), resolveKeyword(), stringValue, and tabSize.
Referenced by LanguageParser::callOnNew(), LanguageParser::raiseNew(), and LanguageParser::signalOnNew().
displayValue()
RexxString * RexxToken::displayValue ()
Get a display value for a token. For all symbols, literals, and operators, this is just the string value already set in the token. For others, we generate a string object automatically.
Returns
The string display value of the token.
Definition at line 308 of file Token.cpp.
References classId, new_string(), OREF_NULL, stringValue, TOKEN_BLANK, TOKEN_COLON, TOKEN_COMMA, TOKEN_DCOLON, TOKEN_DTILDE, TOKEN_EOC, TOKEN_LEFT, TOKEN_RIGHT, TOKEN_SQLEFT, TOKEN_SQRIGHT, and TOKEN_TILDE.
Referenced by LanguageParser::errorToken().
getLineNumber()
size_t RexxToken::getLineNumber () inline
Definition at line 554 of file Token.hpp.
References SourceLocation::getLineNumber(), and tokenLocation.
getLocation()
const SourceLocation& RexxToken::getLocation () inline
Definition at line 595 of file Token.hpp.
References tokenLocation.
Referenced by LanguageParser::errorPosition(), LanguageParser::labelNew(), LanguageParser::nextClause(), LanguageParser::parseSubExpression(), RexxInstructionCaseWhen::RexxInstructionCaseWhen(), RexxInstructionElse::RexxInstructionElse(), RexxInstructionIf::RexxInstructionIf(), RexxInstructionOtherwise::RexxInstructionOtherwise(), and RexxInstructionThen::RexxInstructionThen().
isBlank()
bool RexxToken::isBlank () inline
Definition at line 583 of file Token.hpp.
References classId, and TOKEN_BLANK.
Referenced by RexxClause::nextRealToken().
isBlankSignificant()
bool RexxToken::isBlankSignificant () inline
Definition at line 591 of file Token.hpp.
References classId, TOKEN_LITERAL, TOKEN_RIGHT, TOKEN_SQRIGHT, and TOKEN_SYMBOL.
Referenced by LanguageParser::sourceNextToken().
isComma()
bool RexxToken::isComma () inline
Definition at line 584 of file Token.hpp.
References classId, and TOKEN_COMMA.
Referenced by LanguageParser::parseArgList(), LanguageParser::parseCaseWhenList(), LanguageParser::parseFullSubExpression(), LanguageParser::parseLogical(), LanguageParser::parseNew(), and LanguageParser::useNew().
isConstant()
bool RexxToken::isConstant () inline
Definition at line 577 of file Token.hpp.
References classId, subclass, SYMBOL_COMPOUND, SYMBOL_STEM, SYMBOL_VARIABLE, and TOKEN_SYMBOL.
Referenced by LanguageParser::parseConstantExpression().
isDot()
bool RexxToken::isDot () inline
Definition at line 574 of file Token.hpp.
References subclass, and SYMBOL_DUMMY.
Referenced by LanguageParser::parseNew().
isDotSymbol()
bool RexxToken::isDotSymbol () inline
Definition at line 573 of file Token.hpp.
References subclass, and SYMBOL_DOTSYMBOL.
Referenced by LanguageParser::needVariableOrDotSymbol().
isEndOfClause()
bool RexxToken::isEndOfClause () inline
Definition at line 589 of file Token.hpp.
References classId, and TOKEN_EOC.
Referenced by LanguageParser::addressNew(), LanguageParser::annotateDirective(), LanguageParser::attributeDirective(), LanguageParser::callNew(), LanguageParser::callOnNew(), LanguageParser::classDirective(), LanguageParser::constantDirective(), LanguageParser::createLoop(), LanguageParser::endNew(), LanguageParser::forwardNew(), LanguageParser::guardNew(), isEndOfFile(), LanguageParser::leaveNew(), LanguageParser::methodDirective(), LanguageParser::newControlledLoop(), LanguageParser::newDoOverLoop(), LanguageParser::newDoWithLoop(), LanguageParser::nextClause(), LanguageParser::nextInstruction(), LanguageParser::numericNew(), LanguageParser::optionsDirective(), LanguageParser::parseAddressWith(), LanguageParser::parseConstantExpression(), LanguageParser::parseLoopConditional(), LanguageParser::parseNew(), LanguageParser::procedureNew(), LanguageParser::processAnnotation(), LanguageParser::processAttributeAnnotations(), LanguageParser::processVariableList(), LanguageParser::raiseNew(), LanguageParser::requiredEndOfClause(), LanguageParser::requiresDirective(), LanguageParser::resourceDirective(), LanguageParser::routineDirective(), LanguageParser::selectNew(), LanguageParser::signalNew(), LanguageParser::signalOnNew(), LanguageParser::traceNew(), LanguageParser::translateBlock(), LanguageParser::useLocalNew(), and LanguageParser::useNew().
isEndOfFile()
bool RexxToken::isEndOfFile () inline
Definition at line 590 of file Token.hpp.
References CLAUSEEND_EOF, isEndOfClause(), and isSubtype().
Referenced by LanguageParser::nextClause().
isIntegerConstant()
bool RexxToken::isIntegerConstant () inline
Definition at line 579 of file Token.hpp.
References INTEGER_CONSTANT, and numeric.
Referenced by LanguageParser::addText().
isLeftBracket()
bool RexxToken::isLeftBracket () inline
Definition at line 587 of file Token.hpp.
References classId, and TOKEN_SQLEFT.
Referenced by LanguageParser::parseMessageSubterm(), and LanguageParser::parseMessageTerm().
isLeftParen()
bool RexxToken::isLeftParen () inline
Definition at line 585 of file Token.hpp.
References classId, and TOKEN_LEFT.
Referenced by LanguageParser::callNew(), LanguageParser::constantDirective(), LanguageParser::forwardNew(), LanguageParser::parseConstantExpression(), LanguageParser::parseMessage(), LanguageParser::parseMessageTerm(), LanguageParser::parseNew(), LanguageParser::parseQualifiedSymbol(), LanguageParser::parseSubTerm(), LanguageParser::processVariableList(), and LanguageParser::raiseNew().
isLiteral()
bool RexxToken::isLiteral () inline
Definition at line 575 of file Token.hpp.
References classId, and TOKEN_LITERAL.
Referenced by LanguageParser::attributeDirective(), LanguageParser::callNew(), LanguageParser::methodDirective(), LanguageParser::parseClassReference(), LanguageParser::parseConstantExpression(), LanguageParser::parseNew(), LanguageParser::routineDirective(), and LanguageParser::traceNew().
isMessageOperator()
bool RexxToken::isMessageOperator () inline
Definition at line 593 of file Token.hpp.
References classId, TOKEN_DTILDE, TOKEN_SQLEFT, and TOKEN_TILDE.
Referenced by LanguageParser::parseMessageSubterm(), and LanguageParser::parseMessageTerm().
isNonCompoundVariable()
bool RexxToken::isNonCompoundVariable () inline
Definition at line 570 of file Token.hpp.
References subclass, SYMBOL_STEM, and SYMBOL_VARIABLE.
Referenced by LanguageParser::parseVariableReferenceTerm(), and LanguageParser::useNew().
isNumericSymbol()
bool RexxToken::isNumericSymbol () inline
Definition at line 578 of file Token.hpp.
References subclass, and SYMBOL_CONSTANT.
Referenced by LanguageParser::parseNew().
isOperator() [1/2]
bool RexxToken::isOperator () inline
Definition at line 581 of file Token.hpp.
References classId, and TOKEN_OPERATOR.
Referenced by LanguageParser::constantDirective(), LanguageParser::parseMessageSubterm(), LanguageParser::parseNew(), LanguageParser::processAnnotation(), and LanguageParser::useNew().
isOperator() [2/2]
bool RexxToken::isOperator (TokenSubclass t) inline
Definition at line 582 of file Token.hpp.
References isSubtype(), isType(), and TOKEN_OPERATOR.
isRightBracket()
bool RexxToken::isRightBracket () inline
Definition at line 588 of file Token.hpp.
References classId, and TOKEN_SQRIGHT.
Referenced by LanguageParser::parseArgList().
isRightParen()
bool RexxToken::isRightParen () inline
Definition at line 586 of file Token.hpp.
References classId, and TOKEN_RIGHT.
Referenced by LanguageParser::parseArgList(), and LanguageParser::processVariableList().
isSimpleVariable()
bool RexxToken::isSimpleVariable () inline
Definition at line 571 of file Token.hpp.
References subclass, and SYMBOL_VARIABLE.
Referenced by isTerminator(), LanguageParser::parseMessageTerm(), and LanguageParser::parseVariableReferenceTerm().
isStem()
bool RexxToken::isStem () inline
Definition at line 569 of file Token.hpp.
References subclass, and SYMBOL_STEM.
Referenced by LanguageParser::parseRedirectOptions().
isSubtype() [1/2]
bool RexxToken::isSubtype (TokenSubclass t) inline
Definition at line 559 of file Token.hpp.
References subclass.
Referenced by LanguageParser::constantDirective(), LanguageParser::createLoop(), isEndOfFile(), isOperator(), LanguageParser::nextInstruction(), LanguageParser::parseSubExpression(), LanguageParser::processAnnotation(), LanguageParser::processVariableList(), LanguageParser::traceNew(), LanguageParser::useLocalNew(), and LanguageParser::useNew().
isSubtype() [2/2]
bool RexxToken::isSubtype (TokenSubclass t1, TokenSubclass t2) inline
Definition at line 560 of file Token.hpp.
References subclass.
isSymbol()
bool RexxToken::isSymbol () inline
Definition at line 580 of file Token.hpp.
References classId, and TOKEN_SYMBOL.
Referenced by LanguageParser::annotateDirective(), LanguageParser::attributeDirective(), LanguageParser::callNew(), LanguageParser::callOnNew(), LanguageParser::checkRedirectNormal(), LanguageParser::classDirective(), condition(), LanguageParser::constantDirective(), LanguageParser::createLoop(), LanguageParser::endNew(), LanguageParser::forwardNew(), LanguageParser::guardNew(), keyDirective(), keyword(), LanguageParser::leaveNew(), LanguageParser::methodDirective(), LanguageParser::newDoWithLoop(), LanguageParser::nextDirective(), LanguageParser::nextInstruction(), LanguageParser::numericNew(), LanguageParser::optionsDirective(), LanguageParser::parseAddressWith(), LanguageParser::parseClassReference(), LanguageParser::parseLoopConditional(), LanguageParser::parseNew(), parseOption(), LanguageParser::parseQualifiedSymbol(), LanguageParser::parseRedirectOptions(), LanguageParser::parseRedirectOutputOptions(), LanguageParser::parseVariableOrMessageTerm(), LanguageParser::parseVariableReferenceTerm(), LanguageParser::processAnnotation(), LanguageParser::processVariableList(), LanguageParser::qualifiedCallNew(), LanguageParser::raiseNew(), LanguageParser::requiredVariable(), LanguageParser::requiresDirective(), LanguageParser::resourceDirective(), LanguageParser::routineDirective(), LanguageParser::selectNew(), LanguageParser::signalNew(), LanguageParser::signalOnNew(), subDirective(), subKeyword(), LanguageParser::traceNew(), LanguageParser::useLocalNew(), and LanguageParser::useNew().
isSymbolOrLiteral()
bool RexxToken::isSymbolOrLiteral () inline
Definition at line 576 of file Token.hpp.
References classId, TOKEN_LITERAL, and TOKEN_SYMBOL.
Referenced by LanguageParser::addressNew(), LanguageParser::annotateDirective(), LanguageParser::attributeDirective(), builtin(), LanguageParser::callOnNew(), LanguageParser::classDirective(), LanguageParser::constantDirective(), LanguageParser::methodDirective(), LanguageParser::nextInstruction(), LanguageParser::optionsDirective(), LanguageParser::parseClassReference(), LanguageParser::parseMessage(), LanguageParser::processAnnotation(), LanguageParser::requiresDirective(), LanguageParser::resourceDirective(), LanguageParser::routineDirective(), LanguageParser::signalNew(), LanguageParser::signalOnNew(), and LanguageParser::traceNew().
isTerminator()
bool RexxToken::isTerminator (int terminators)
Test if a token qualifies as a terminator in the current parsing context.
Parameters
terminators The list of terminators.
Returns
true if this is a terminator, false if it doesn't match one of the terminator classes.
Definition at line 189 of file Token.cpp.
References classId, isSimpleVariable(), SUBKEY_BY, SUBKEY_FOR, SUBKEY_THEN, SUBKEY_TO, SUBKEY_UNTIL, SUBKEY_WHILE, SUBKEY_WITH, subKeyword(), TERM_BY, TERM_FOR, TERM_KEYWORD, TERM_RIGHT, TERM_SQRIGHT, TERM_THEN, TERM_TO, TERM_WHILE, TERM_WITH, TOKEN_COMMA, TOKEN_EOC, TOKEN_RIGHT, TOKEN_SQRIGHT, and TOKEN_SYMBOL.
Referenced by LanguageParser::getToken(), LanguageParser::parseMessageSubterm(), LanguageParser::parseMessageTerm(), LanguageParser::parseSubExpression(), and LanguageParser::parseSubTerm().
isType() [1/3]
bool RexxToken::isType (TokenClass t) inline
Definition at line 556 of file Token.hpp.
References classId.
Referenced by LanguageParser::callNew(), LanguageParser::checkDirective(), LanguageParser::hasBody(), isOperator(), LanguageParser::nextDirective(), LanguageParser::nextInstruction(), LanguageParser::parseClassReference(), LanguageParser::parseMessage(), LanguageParser::parseMessageSubterm(), LanguageParser::parseMessageTerm(), LanguageParser::parseSubExpression(), and LanguageParser::parseSubTerm().
isType() [2/3]
bool RexxToken::isType (TokenClass t1, TokenClass t2) inline
Definition at line 557 of file Token.hpp.
References classId.
isType() [3/3]
bool RexxToken::isType (TokenClass t1, TokenClass t2, TokenClass t3) inline
Definition at line 558 of file Token.hpp.
References classId.
isVariable()
bool RexxToken::isVariable () inline
Definition at line 568 of file Token.hpp.
References subclass, SYMBOL_COMPOUND, SYMBOL_STEM, and SYMBOL_VARIABLE.
Referenced by isVariableOrDot(), LanguageParser::needVariable(), LanguageParser::needVariableOrDotSymbol(), and LanguageParser::parseNew().
isVariableOrDot()
bool RexxToken::isVariableOrDot () inline
Definition at line 572 of file Token.hpp.
References isVariable(), subclass, and SYMBOL_DOTSYMBOL.
Referenced by LanguageParser::parseMessage().
keyDirective()
DirectiveKeyword RexxToken::keyDirective ()
Resolve a token to a directve name.
Returns
The code for the directive.
Definition at line 566 of file KeywordConstants.cpp.
References DIRECTIVE_NONE, directives, isSymbol(), resolveKeyword(), stringValue, and tabSize.
Referenced by LanguageParser::nextDirective().
keyword()
InstructionKeyword RexxToken::keyword ()
Resolve a token to a keyword value.
Returns
The keyword identifier.
Definition at line 505 of file KeywordConstants.cpp.
References isSymbol(), KEYWORD_NONE, keywordInstructions, resolveKeyword(), stringValue, and tabSize.
Referenced by LanguageParser::nextInstruction(), and LanguageParser::translateBlock().
live()
void RexxToken::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 68 of file Token.cpp.
References memory_mark, and stringValue.
liveGeneral()
void RexxToken::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 81 of file Token.cpp.
References memory_mark_general, and stringValue.
operator delete()
void RexxToken::operator delete (void *) inline
Definition at line 541 of file Token.hpp.
operator new()
void * RexxToken::operator new (size_t size)
Create a new Token object.
Parameters
size The size of the object.
Returns
Storage for a new instance of a Token.
Definition at line 57 of file Token.cpp.
References new_object(), and T_Token.
parseOption()
InstructionSubKeyword RexxToken::parseOption ()
Resolve a token to a parse option keyword.
Returns
The corresponding keyword code.
Definition at line 551 of file KeywordConstants.cpp.
References isSymbol(), parseOptions, resolveKeyword(), stringValue, SUBKEY_NONE, and tabSize.
Referenced by LanguageParser::parseNew().
precedence()
int RexxToken::precedence ()
Determine a Token's operator precedence.
Returns
A numeric ranking for operator characters.
Definition at line 111 of file Token.cpp.
References OPERATOR_ABUTTAL, OPERATOR_AND, OPERATOR_BACKSLASH, OPERATOR_BACKSLASH_EQUAL, OPERATOR_BACKSLASH_GREATERTHAN, OPERATOR_BACKSLASH_LESSTHAN, OPERATOR_BLANK, OPERATOR_CONCATENATE, OPERATOR_DIVIDE, OPERATOR_EQUAL, OPERATOR_GREATERTHAN, OPERATOR_GREATERTHAN_EQUAL, OPERATOR_GREATERTHAN_LESSTHAN, OPERATOR_INTDIV, OPERATOR_LESSTHAN, OPERATOR_LESSTHAN_EQUAL, OPERATOR_LESSTHAN_GREATERTHAN, OPERATOR_MULTIPLY, OPERATOR_OR, OPERATOR_PLUS, OPERATOR_POWER, OPERATOR_REMAINDER, OPERATOR_STRICT_BACKSLASH_EQUAL, OPERATOR_STRICT_BACKSLASH_GREATERTHAN, OPERATOR_STRICT_BACKSLASH_LESSTHAN, OPERATOR_STRICT_EQUAL, OPERATOR_STRICT_GREATERTHAN, OPERATOR_STRICT_GREATERTHAN_EQUAL, OPERATOR_STRICT_LESSTHAN, OPERATOR_STRICT_LESSTHAN_EQUAL, OPERATOR_SUBTRACT, OPERATOR_XOR, and subclass.
Referenced by LanguageParser::parseSubExpression().
resolveBuiltin()
BuiltinCode RexxToken::resolveBuiltin (RexxString * value) static
Resolve a builtin name to a function code.
Parameters
value The value to check.
Returns
The corresponding builtin code.
Definition at line 599 of file KeywordConstants.cpp.
References builtinFunctions, resolveKeyword(), tabSize, and value().
Referenced by LanguageParser::callOnNew(), and RexxInstructionDynamicCall::execute().
resolveKeyword()
int RexxToken::resolveKeyword (RexxString * token, KeywordEntry * table, size_t tableSize) static protected
Resolve a token to a potential subkeyword.
Parameters
token The token to resolve.
Table The table to search.
Table_Size The size of the table.
Returns
The numeric identifier for the constant. Returns 0 if not found in the target table.
Definition at line 412 of file KeywordConstants.cpp.
References RexxString::getLength(), RexxString::getStringData(), and KeywordEntry::keywordCode.
Referenced by builtin(), condition(), keyDirective(), keyword(), parseOption(), resolveBuiltin(), subDirective(), and subKeyword().
setEnd()
void RexxToken::setEnd (size_t l, size_t o) inline
Definition at line 553 of file Token.hpp.
References SourceLocation::setEnd(), and tokenLocation.
setLocation()
void RexxToken::setLocation (const SourceLocation & l) inline
Definition at line 596 of file Token.hpp.
References tokenLocation.
setNumeric()
void RexxToken::setNumeric (TokenSubclass v) inline
Definition at line 594 of file Token.hpp.
References numeric.
Referenced by LanguageParser::scanSymbol().
setStart()
void RexxToken::setStart (size_t l, size_t o) inline
Definition at line 552 of file Token.hpp.
References SourceLocation::setStart(), and tokenLocation.
setSubtype()
void RexxToken::setSubtype (TokenSubclass t) inline
Definition at line 566 of file Token.hpp.
References subclass.
setType()
void RexxToken::setType (TokenClass t) inline
Definition at line 565 of file Token.hpp.
References classId.
setValue()
void RexxToken::setValue (RexxString * v) inline
Definition at line 567 of file Token.hpp.
References stringValue.
subDirective()
DirectiveSubKeyword RexxToken::subDirective ()
Resolve a token to a subkeyword on a directive instruction.
Returns
The code for the sub keyword.
Definition at line 581 of file KeywordConstants.cpp.
References isSymbol(), resolveKeyword(), stringValue, SUBDIRECTIVE_NONE, subDirectives, and tabSize.
Referenced by LanguageParser::annotateDirective(), LanguageParser::attributeDirective(), LanguageParser::classDirective(), LanguageParser::methodDirective(), LanguageParser::optionsDirective(), LanguageParser::requiresDirective(), LanguageParser::resourceDirective(), and LanguageParser::routineDirective().
subKeyword()
InstructionSubKeyword RexxToken::subKeyword ()
Resolve a token value to a subkeyword identifier.
Returns
The subkeyword identifier.
Definition at line 490 of file KeywordConstants.cpp.
References isSymbol(), resolveKeyword(), stringValue, SUBKEY_NONE, subKeywords, and tabSize.
Referenced by LanguageParser::addressNew(), LanguageParser::callNew(), LanguageParser::callOnNew(), LanguageParser::checkRedirectNormal(), LanguageParser::createLoop(), LanguageParser::forwardNew(), LanguageParser::guardNew(), isTerminator(), LanguageParser::newControlledLoop(), LanguageParser::newDoOverLoop(), LanguageParser::newDoWithLoop(), LanguageParser::numericNew(), LanguageParser::optionsDirective(), LanguageParser::parseAddressWith(), LanguageParser::parseLoopConditional(), LanguageParser::parseNew(), LanguageParser::parseRedirectOptions(), LanguageParser::parseRedirectOutputOptions(), LanguageParser::procedureNew(), LanguageParser::raiseNew(), LanguageParser::selectNew(), LanguageParser::signalNew(), LanguageParser::signalOnNew(), LanguageParser::traceNew(), and LanguageParser::useNew().
subtype()
TokenSubclass RexxToken::subtype () inline
Definition at line 562 of file Token.hpp.
References subclass.
Referenced by LanguageParser::addText(), LanguageParser::assignmentOpNew(), LanguageParser::messageAssignmentOpNew(), LanguageParser::parseMessageSubterm(), LanguageParser::parseNew(), LanguageParser::parseSubExpression(), and LanguageParser::parseSubTerm().
type()
TokenClass RexxToken::type () inline
Definition at line 561 of file Token.hpp.
References classId.
Referenced by LanguageParser::addText(), LanguageParser::parseSubExpression(), and LanguageParser::parseSubTerm().
upperValue()
RexxString * RexxToken::upperValue ()
Upper case the string value.
Returns
The upper case string value of the token.
Definition at line 294 of file Token.cpp.
References stringValue, and RexxString::upper().
Referenced by LanguageParser::annotateDirective(), and LanguageParser::parseClassReference().
value()
RexxString* RexxToken::value () inline
Definition at line 563 of file Token.hpp.
References stringValue.
Referenced by LanguageParser::addressNew(), LanguageParser::addText(), LanguageParser::attributeDirective(), LanguageParser::callNew(), LanguageParser::callOnNew(), LanguageParser::classDirective(), LanguageParser::constantDirective(), LanguageParser::endNew(), LanguageParser::labelNew(), LanguageParser::leaveNew(), LanguageParser::methodDirective(), LanguageParser::needVariable(), LanguageParser::newControlledLoop(), LanguageParser::newDoOverLoop(), LanguageParser::optionsDirective(), LanguageParser::parseClassReference(), LanguageParser::parseMessage(), LanguageParser::parseQualifiedSymbol(), LanguageParser::parseSubTerm(), LanguageParser::parseVariableReferenceTerm(), LanguageParser::processAnnotation(), LanguageParser::processVariableList(), LanguageParser::qualifiedCallNew(), LanguageParser::raiseNew(), LanguageParser::requiresDirective(), resolveBuiltin(), LanguageParser::resourceDirective(), LanguageParser::routineDirective(), LanguageParser::selectNew(), LanguageParser::signalNew(), LanguageParser::signalOnNew(), LanguageParser::traceNew(), LanguageParser::useLocalNew(), and LanguageParser::useNew().
Member Data Documentation
builtinFunctions
KeywordEntry RexxToken::builtinFunctions static protected
Definition at line 625 of file Token.hpp.
Referenced by builtin(), and resolveBuiltin().
classId
TokenClass RexxToken::classId protected
Definition at line 616 of file Token.hpp.
Referenced by checkAssignment(), displayValue(), isBlank(), isBlankSignificant(), isComma(), isConstant(), isEndOfClause(), isLeftBracket(), isLeftParen(), isLiteral(), isMessageOperator(), isOperator(), isRightBracket(), isRightParen(), isSymbol(), isSymbolOrLiteral(), isTerminator(), isType(), setType(), and type().
conditionKeywords
KeywordEntry RexxToken::conditionKeywords static protected
Initial value:
=
{
    KeywordEntry("ANY",            CONDITION_ANY),
    KeywordEntry("ERROR",          CONDITION_ERROR),
    KeywordEntry("FAILURE",        CONDITION_FAILURE),
    KeywordEntry("HALT",           CONDITION_HALT),
    KeywordEntry("LOSTDIGITS",     CONDITION_LOSTDIGITS),
    KeywordEntry("NOMETHOD",       CONDITION_NOMETHOD),
    KeywordEntry("NOSTRING",       CONDITION_NOSTRING),
    KeywordEntry("NOTREADY",       CONDITION_NOTREADY),
    KeywordEntry("NOVALUE",        CONDITION_NOVALUE),
    KeywordEntry("PROPAGATE",      CONDITION_PROPAGATE),
    KeywordEntry("SYNTAX",         CONDITION_SYNTAX),
    KeywordEntry("USER",           CONDITION_USER),
}
Definition at line 626 of file Token.hpp.
Referenced by condition().
directives
KeywordEntry RexxToken::directives static protected
Initial value:
=
{
    KeywordEntry("ANNOTATE",    DIRECTIVE_ANNOTATE),
    KeywordEntry("ATTRIBUTE",   DIRECTIVE_ATTRIBUTE),
    KeywordEntry("CLASS",       DIRECTIVE_CLASS),
    KeywordEntry("CONSTANT",    DIRECTIVE_CONSTANT),
    KeywordEntry("METHOD",      DIRECTIVE_METHOD),
    KeywordEntry("OPTIONS",     DIRECTIVE_OPTIONS),
    KeywordEntry("REQUIRES",    DIRECTIVE_REQUIRES),
    KeywordEntry("RESOURCE",    DIRECTIVE_RESOURCE),
    KeywordEntry("ROUTINE",     DIRECTIVE_ROUTINE),
}
Definition at line 622 of file Token.hpp.
Referenced by keyDirective().
keywordInstructions
KeywordEntry RexxToken::keywordInstructions static protected
Definition at line 623 of file Token.hpp.
Referenced by keyword().
numeric
TokenSubclass RexxToken::numeric protected
Definition at line 618 of file Token.hpp.
Referenced by isIntegerConstant(), and setNumeric().
parseOptions
KeywordEntry RexxToken::parseOptions static protected
Initial value:
=
{
    KeywordEntry("ARG",           SUBKEY_ARG),
    KeywordEntry("CASELESS",      SUBKEY_CASELESS),
    KeywordEntry("LINEIN",        SUBKEY_LINEIN),
    KeywordEntry("LOWER",         SUBKEY_LOWER),
    KeywordEntry("PULL",          SUBKEY_PULL),
    KeywordEntry("SOURCE",        SUBKEY_SOURCE),
    KeywordEntry("UPPER",         SUBKEY_UPPER),
    KeywordEntry("VALUE",         SUBKEY_VALUE),
    KeywordEntry("VAR",           SUBKEY_VAR),
    KeywordEntry("VERSION",       SUBKEY_VERSION),
}
Definition at line 627 of file Token.hpp.
Referenced by parseOption().
stringValue
RexxString* RexxToken::stringValue protected
Definition at line 615 of file Token.hpp.
Referenced by builtin(), checkAssignment(), condition(), displayValue(), keyDirective(), keyword(), live(), liveGeneral(), parseOption(), setValue(), subDirective(), subKeyword(), upperValue(), and value().
subclass
TokenSubclass RexxToken::subclass protected
Definition at line 617 of file Token.hpp.
Referenced by isConstant(), isDot(), isDotSymbol(), isNonCompoundVariable(), isNumericSymbol(), isSimpleVariable(), isStem(), isSubtype(), isVariable(), isVariableOrDot(), precedence(), setSubtype(), and subtype().
subDirectives
KeywordEntry RexxToken::subDirectives static protected
Definition at line 628 of file Token.hpp.
Referenced by subDirective().
subKeywords
KeywordEntry RexxToken::subKeywords static protected
Definition at line 624 of file Token.hpp.
Referenced by subKeyword().
tokenLocation
SourceLocation RexxToken::tokenLocation protected
Definition at line 619 of file Token.hpp.
Referenced by checkAssignment(), getLineNumber(), getLocation(), setEnd(), setLocation(), and setStart().
The documentation for this class was generated from the following files:
Token.hpp
KeywordConstants.cpp
Token.cpp