ooRexx: VariableDictionary Class Reference
VariableDictionary Class Reference
#include <VariableDictionary.hpp>
Classes
class VariableIterator
Public Member Functions
void * operator new (size_t size)
void operator delete (void *)
VariableDictionary (size_t capacity)
VariableDictionary (RexxClass *scope)
VariableDictionary (RESTORETYPE restoreType)
StringHashContents * allocateContents (size_t bucketSize, size_t capacity)
void initialize (size_t capacity=DefaultObjectDictionarySize)
void expandContents ()
void expandContents (size_t capacity)
void ensureCapacity (size_t delta)
void checkFull ()
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *envelope) override
RexxInternalObject * copy () override
void copyValues ()
VariableDictionary * deepCopy ()
RexxObject * realValue (RexxString *name)
StemClass * getStem (RexxString *stemName)
RexxVariable * createStemVariable (RexxString *stemName)
RexxVariable * createVariable (RexxString *stemName)
void addVariable (RexxString *name, RexxVariable *variable)
RexxVariable * resolveVariable (RexxString *name)
RexxVariable * getVariable (RexxString *name)
RexxVariable * getStemVariable (RexxString *stemName)
void setCompoundVariable (RexxString *stemName, RexxInternalObject **tail, size_t tailCount, RexxObject *value)
void dropCompoundVariable (RexxString *stemName, RexxInternalObject **tail, size_t tailCount)
StringTable * getAllVariables ()
DirectoryClass * getVariableDirectory ()
void remove (RexxString *n)
void set (RexxString *, RexxObject *)
void drop (RexxString *)
void dropStemVariable (RexxString *)
void reserve (Activity *)
void release (Activity *)
bool transfer (Activity *)
CompoundTableElement * getCompoundVariable (RexxString *stemName, RexxInternalObject **tail, size_t tailCount)
RexxObject * getCompoundVariableValue (RexxString *stemName, RexxInternalObject **tail, size_t tailCount)
RexxObject * getCompoundVariableRealValue (RexxString *stem, RexxInternalObject **tail, size_t tailCount)
RexxObject * realStemValue (RexxString *stemName)
uint32_t getIdntfr ()
unsigned short getReserveCount ()
bool isScope (RexxClass *otherScope)
VariableDictionary * getNextDictionary ()
Activity * getReservingActivity ()
void setNextDictionary (VariableDictionary *next)
VariableIterator iterator ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static RexxVariableBase * getVariableRetriever (RexxString *variable)
static RexxVariableBase * getDirectVariableRetriever (RexxString *variable)
static RexxVariableBase * buildCompoundVariable (RexxString *variable_name, bool direct)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static const size_t DefaultObjectDictionarySize = 7
Protected Attributes
Activity * reservingActivity
StringHashContents * contents
ArrayClass * waitingActivities
unsigned short flags
unsigned short reserveCount
VariableDictionary * nextDictionary
RexxClass * scope
uint32_t idntfr
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
A variable dictionary, used both for object variables and dynamic access to context variables.
Definition at line 61 of file VariableDictionary.hpp.
Constructor & Destructor Documentation
VariableDictionary() [1/3]
VariableDictionary::VariableDictionary (size_t capacity)
construct a variable dictionary with a given size.
Parameters
capacity The required capacity.
Definition at line 95 of file VariableDictionary.cpp.
References initialize().
Referenced by new_objectVariableDictionary(), and new_variableDictionary().
VariableDictionary() [2/3]
VariableDictionary::VariableDictionary (RexxClass * s)
construct a variable dictionary for a given scope.
Parameters
s The scope associated with this instance.
Definition at line 106 of file VariableDictionary.cpp.
References DefaultObjectDictionarySize, initialize(), and scope.
VariableDictionary() [3/3]
VariableDictionary::VariableDictionary (RESTORETYPE restoreType) inline
Definition at line 134 of file VariableDictionary.hpp.
Member Function Documentation
addVariable()
void VariableDictionary::addVariable (RexxString * name, RexxVariable * variable)
Insert a variable into the dictionary hash table. This is used for inserting both stem and regular variables.
Parameters
variable The variable object backing the variable.
name The variable name.
Definition at line 457 of file VariableDictionary.cpp.
References checkFull(), contents, and HashContents::put().
Referenced by RexxLocalVariables::aliasVariable(), RexxLocalVariables::createDictionary(), createStemVariable(), createVariable(), RexxLocalVariables::findVariable(), RexxLocalVariables::lookupStemVariable(), RexxLocalVariables::lookupVariable(), RexxLocalVariables::putVariable(), and RexxLocalVariables::updateVariable().
allocateContents()
StringHashContents * VariableDictionary::allocateContents (size_t bucketSize, size_t totalSize)
Virtual method for allocating a new contents item for this collection. Collections with special requirements should override this and return the appropriate subclass.
Parameters
bucketSize The bucket size of the collection.
totalSize The total capacity of the collection.
Returns
A new HashContents object appropriate for this collection type.
Definition at line 192 of file VariableDictionary.cpp.
Referenced by expandContents(), and initialize().
buildCompoundVariable()
RexxVariableBase * VariableDictionary::buildCompoundVariable (RexxString * variable_name, bool direct) static
Build a retriever for a compound variable (either direct or symbolic)
Parameters
variable_name The full name of the variable.
direct Indicates whether we build this with direct or symbolic rules. For direct rules, everything after the first period is used as a literal tail value. for symbolic rules, we need to evaluate each of the tail sections.
Returns
A retriever for this variable.
Definition at line 917 of file VariableDictionary.cpp.
References RexxString::extract(), RexxString::getChar(), RexxString::getLength(), and new_queue().
Referenced by getDirectVariableRetriever(), LanguageParser::getRetriever(), and getVariableRetriever().
checkFull()
void VariableDictionary::checkFull ()
If the hash collection thinks it is time to expand, then increase the contents size.
Definition at line 253 of file VariableDictionary.cpp.
References contents, expandContents(), and HashContents::isFull().
Referenced by addVariable().
copy()
RexxInternalObject * VariableDictionary::copy () override virtual
Copy a variable dictionary.
Returns
The new dictionary.
Reimplemented from RexxInternalObject.
Definition at line 267 of file VariableDictionary.cpp.
References RexxInternalObject::clone(), contents, and RexxInternalObject::copy().
Referenced by deepCopy().
copyValues()
void VariableDictionary::copyValues ()
Copy all of the values in a variable dictionary. This copies the variable objects, but does not copy the values stored in the variables.
Definition at line 308 of file VariableDictionary.cpp.
References contents, and HashContents::copyValues().
createStemVariable()
RexxVariable * VariableDictionary::createStemVariable (RexxString * stemName)
Create a stem variable and add it to the variable context.
Parameters
stemName The name of the stem.
Returns
The backing variable object.
Definition at line 473 of file VariableDictionary.cpp.
References addVariable(), new_variable(), and RexxVariable::set().
Referenced by getStemVariable().
createVariable()
RexxVariable * VariableDictionary::createVariable (RexxString * name)
Create a new variable item and add it to the dictionary.
Parameters
name The variable name.
Returns
The backing variable object.
Definition at line 494 of file VariableDictionary.cpp.
References addVariable(), and new_variable().
Referenced by getVariable().
deepCopy()
VariableDictionary * VariableDictionary::deepCopy ()
Perform a deep copy of a variable dictionary. This copies the object, all variable objects stored in the object, AND any variable dictionaries chained off of this one in an object's variable set.
Returns
A complete chain copy of the object.
Definition at line 285 of file VariableDictionary.cpp.
References copy(), deepCopy(), nextDictionary, and OREF_NULL.
Referenced by deepCopy().
drop()
void VariableDictionary::drop (RexxString * name)
Drop the value of a named variable in the method dictionary.
Parameters
name The string name of the variable.
Definition at line 340 of file VariableDictionary.cpp.
References RexxVariable::drop(), OREF_NULL, and resolveVariable().
dropCompoundVariable()
void VariableDictionary::dropCompoundVariable (RexxString * stemName, RexxInternalObject ** tail, size_t tailCount)
Drop a compound variable in the dictionary.
Parameters
stemName The name of the stem.
tail The tail elements.
tailCount The count of tail elements.
value The value to set.
Definition at line 712 of file VariableDictionary.cpp.
References StemClass::dropCompoundVariable(), and getStem().
Referenced by RexxCompoundVariable::drop().
dropStemVariable()
void VariableDictionary::dropStemVariable (RexxString * name)
Drop the value of a named variable in the method dictionary.
Parameters
name The string name of the variable.
Definition at line 356 of file VariableDictionary.cpp.
References RexxVariable::drop(), OREF_NULL, resolveVariable(), and RexxVariable::set().
Referenced by RexxStemVariable::drop().
ensureCapacity()
void VariableDictionary::ensureCapacity (size_t delta)
Ensure that the collection has sufficient space for a mass incoming addition.
Parameters
delta The number of entries we wish to add.
Definition at line 237 of file VariableDictionary.cpp.
References HashContents::capacity(), contents, expandContents(), and HashContents::hasCapacity().
expandContents() [1/2]
void VariableDictionary::expandContents ()
Expand the contents of a collection. We try for double the size.
Definition at line 202 of file VariableDictionary.cpp.
References HashContents::capacity(), and contents.
Referenced by checkFull(), and ensureCapacity().
expandContents() [2/2]
void VariableDictionary::expandContents (size_t capacity)
Expand the contents of a collection to a given bucket capacity.
Definition at line 213 of file VariableDictionary.cpp.
References allocateContents(), HashCollection::calculateBucketSize(), contents, HashContents::empty(), RexxInternalObject::isOldSpace(), HashContents::reMerge(), and setField.
flatten()
void VariableDictionary::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxVirtualBase.
Definition at line 148 of file VariableDictionary.cpp.
References cleanUpFlatten, contents, flattenRef, nextDictionary, OREF_NULL, scope, and setUpFlatten.
getAllVariables()
StringTable * VariableDictionary::getAllVariables ()
Get all of the variables in the local context. This returns just the top-level variables (i.e., simple variables and stems).
Returns
A StringTable of the variables.
Definition at line 636 of file VariableDictionary.cpp.
References contents, RexxVariable::getName(), RexxVariable::getVariableValue(), VariableDictionary::VariableIterator::isAvailable(), HashContents::items(), iterator(), HashContents::iterator(), new_string_table(), VariableDictionary::VariableIterator::next(), OREF_NULL, and VariableDictionary::VariableIterator::value().
getCompoundVariable()
CompoundTableElement * VariableDictionary::getCompoundVariable (RexxString * stemName, RexxInternalObject ** tail, size_t tailCount)
Retrieve a compound variable, returning OREF_NULL if the variable does not exist.
Parameters
stemName The name of the stem variable.
tail The elements used to construct the compound variable tail.
tailCount The number of tail sections.
Returns
The value of the compound variable, or OREF_NULL if it does not exist.
Definition at line 381 of file VariableDictionary.cpp.
References StemClass::getCompoundVariable(), and getStem().
getCompoundVariableRealValue()
RexxObject * VariableDictionary::getCompoundVariableRealValue (RexxString * stem, RexxInternalObject ** tail, size_t tailCount)
Retrieve the "real" value of a compound variable. This return OREF_NULL for any situation where the compound variable name would be returned.
Parameters
stem The name of the stem.
tail The set of tails used for the lookup.
tailCount The number of tail elements.
Returns
Either the variable value, or OREF_NULL for unassigned variables.
Definition at line 425 of file VariableDictionary.cpp.
References StemClass::getCompoundVariableRealValue(), and getStem().
Referenced by RexxCompoundVariable::getRealValue().
getCompoundVariableValue()
RexxObject * VariableDictionary::getCompoundVariableValue (RexxString * stemName, RexxInternalObject ** tail, size_t tailCount)
Retrieve a compound variable, returning default value if the variable does not exist. This does not raise NOVALUE.
Parameters
stemName The name of the stem variable.
tail The elements used to construct the compound variable tail.
tailCount The number of tail sections.
Returns
The variable value, including substituting of the string name of the variable if it does not exist.
Definition at line 402 of file VariableDictionary.cpp.
References StemClass::evaluateCompoundVariableValue(), getStem(), and OREF_NULL.
Referenced by RexxCompoundVariable::getValue().
getDirectVariableRetriever()
RexxVariableBase * VariableDictionary::getDirectVariableRetriever (RexxString * variable) static
Return a retriever for a variable using direct access (i.e. no substitution in compound variable tails)
Parameters
variable The full name of the variable. The tail portion of any compound variables is taken as a literal.
Returns
A retriever for the variable type.
Definition at line 789 of file VariableDictionary.cpp.
References buildCompoundVariable(), RexxString::getChar(), RexxString::getLength(), LanguageParser::isSymbolCharacter(), OREF_NULL, and LanguageParser::translateChar().
Referenced by NativeActivation::variablePoolGetVariable().
getIdntfr()
uint32_t VariableDictionary::getIdntfr ()
Definition at line 70 of file VariableDictionary.cpp.
References counter(), and idntfr.
getNextDictionary()
VariableDictionary* VariableDictionary::getNextDictionary () inline
Definition at line 211 of file VariableDictionary.hpp.
References nextDictionary.
Referenced by RexxObject::getObjectVariable(), and RexxObject::getObjectVariables().
getReserveCount()
unsigned short VariableDictionary::getReserveCount () inline
Definition at line 208 of file VariableDictionary.hpp.
References reserveCount.
Referenced by RexxActivation::getReserveCount().
getReservingActivity()
Activity* VariableDictionary::getReservingActivity () inline
Definition at line 212 of file VariableDictionary.hpp.
References reservingActivity.
getStem()
StemClass* VariableDictionary::getStem (RexxString * stemName) inline
Definition at line 153 of file VariableDictionary.hpp.
References getStemVariable(), and RexxVariable::getVariableValue().
Referenced by dropCompoundVariable(), RexxCompoundVariable::expose(), getCompoundVariable(), getCompoundVariableRealValue(), getCompoundVariableValue(), RexxStemVariable::getRealValue(), RexxStemVariable::getValue(), realStemValue(), and setCompoundVariable().
getStemVariable()
RexxVariable* VariableDictionary::getStemVariable (RexxString * stemName) inline
Definition at line 178 of file VariableDictionary.hpp.
References createStemVariable(), OREF_NULL, and resolveVariable().
Referenced by RexxStemVariable::clearGuard(), RexxStemVariable::expose(), getStem(), RexxStemVariable::getVariableReference(), RexxLocalVariables::lookupStemVariable(), RexxStemVariable::set(), and RexxStemVariable::setGuard().
getVariable()
RexxVariable* VariableDictionary::getVariable (RexxString * name) inline
Definition at line 165 of file VariableDictionary.hpp.
References createVariable(), OREF_NULL, and resolveVariable().
Referenced by RexxSimpleVariable::clearGuard(), RexxSimpleVariable::drop(), RexxSimpleVariable::expose(), RexxLocalVariables::findVariable(), RexxSimpleVariable::getRealValue(), RexxSimpleVariable::getValue(), RexxSimpleVariable::getVariableReference(), RexxLocalVariables::lookupVariable(), set(), RexxSimpleVariable::set(), and RexxSimpleVariable::setGuard().
getVariableDirectory()
DirectoryClass * VariableDictionary::getVariableDirectory ()
Get all of the variables in the local context. This returns just the top-level variables (i.e., simple variables and stems).
Returns
A directory of the variables
Definition at line 664 of file VariableDictionary.cpp.
References contents, RexxVariable::getName(), RexxVariable::getVariableValue(), VariableDictionary::VariableIterator::isAvailable(), HashContents::items(), iterator(), HashContents::iterator(), new_directory(), VariableDictionary::VariableIterator::next(), OREF_NULL, and VariableDictionary::VariableIterator::value().
Referenced by RexxActivation::getAllLocalVariables().
getVariableRetriever()
RexxVariableBase * VariableDictionary::getVariableRetriever (RexxString * variable) static
Generate a variable retriever to access a variable from a string name. Used for dynamic access such as the value function or the variable pool interface.
Parameters
variable The variable name.
Returns
An appropriate variable retriever. Returns NULL if the name is not a valid variable name.
Definition at line 732 of file VariableDictionary.cpp.
References buildCompoundVariable(), RexxString::extract(), RexxString::getChar(), RexxString::getLength(), RexxString::isSymbol(), OREF_NULL, STRING_BAD_VARIABLE, STRING_COMPOUND_NAME, STRING_LITERAL, STRING_LITERAL_DOT, STRING_NAME, STRING_NUMERIC, STRING_STEM, and RexxString::upper().
Referenced by BUILTIN(), NativeActivation::dropContextVariable(), NativeActivation::getContextStem(), NativeActivation::getContextVariable(), NativeActivation::getContextVariableReference(), NativeActivation::getObjectVariableRetriever(), RexxVariableReference::list(), NativeActivation::setContextVariable(), and NativeActivation::variablePoolGetVariable().
initialize()
void VariableDictionary::initialize (size_t capacity = DefaultObjectDictionarySize)
Initialize the list contents, either directly from the low level constructor or from the INIT method.
Parameters
capacity The requested capacity.
Definition at line 171 of file VariableDictionary.cpp.
References allocateContents(), HashCollection::calculateBucketSize(), contents, and OREF_NULL.
Referenced by VariableDictionary().
isScope()
bool VariableDictionary::isScope (RexxClass * otherScope) inline
Definition at line 210 of file VariableDictionary.hpp.
References scope.
Referenced by RexxObject::getObjectVariables().
iterator()
VariableDictionary::VariableIterator VariableDictionary::iterator ()
Retrieve an iterator for this variable dictionary. This iterates over both the simple variables and the stem variables.
Returns
An iterator instance for this dictionary.
Definition at line 998 of file VariableDictionary.cpp.
Referenced by NativeActivation::fetchNext(), getAllVariables(), and getVariableDirectory().
live()
void VariableDictionary::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 118 of file VariableDictionary.cpp.
References contents, memory_mark, nextDictionary, reservingActivity, scope, and waitingActivities.
liveGeneral()
void VariableDictionary::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 133 of file VariableDictionary.cpp.
References contents, memory_mark_general, nextDictionary, reservingActivity, scope, and waitingActivities.
operator delete()
void VariableDictionary::operator delete (void *) inline
Definition at line 130 of file VariableDictionary.hpp.
operator new()
void * VariableDictionary::operator new (size_t size)
Create a new variable dictionary object.
Parameters
size the size of the object.
Returns
Storage for creating the object.
Definition at line 84 of file VariableDictionary.cpp.
References new_object(), and T_VariableDictionary.
realStemValue()
RexxObject * VariableDictionary::realStemValue (RexxString * stemName)
Retrieve the "real" value of a stem variable. OREF_NULL is returned if the stem does not exist.
Parameters
stemName The stem name.
Returns
The backing stem object, or OREF_NULL if this stem variable has not been used in this context.
Definition at line 444 of file VariableDictionary.cpp.
References getStem().
realValue()
RexxObject * VariableDictionary::realValue (RexxString * name)
Retrieve a variable's value WITHOUT returning the default variable name if it doesn't exist.
Parameters
name The variable name.
Returns
The true assigned value of the variable.
Definition at line 323 of file VariableDictionary.cpp.
References RexxVariable::getVariableValue(), OREF_NULL, and resolveVariable().
Referenced by RexxObject::getObjectVariable().
release()
void VariableDictionary::release (Activity * activity)
Release the lock on an object's variable dictionary.
Parameters
activity The activity owning the lock.
Definition at line 564 of file VariableDictionary.cpp.
References Activity::guardPost(), ArrayClass::isEmpty(), OREF_NULL, ArrayClass::removeFirst(), reserveCount, reservingActivity, and waitingActivities.
Referenced by NativeActivation::guardOff(), RexxActivation::guardOff(), RexxObject::guardOff(), NativeActivation::guardWait(), RexxActivation::guardWait(), AttributeGetterCode::run(), AttributeSetterCode::run(), DelegateCode::run(), and transfer().
remove()
void VariableDictionary::remove (RexxString * n) inline
Definition at line 192 of file VariableDictionary.hpp.
References contents, and HashContents::remove().
reserve()
void VariableDictionary::reserve (Activity * activity)
Reserve a scope on an object, waiting for completion if this is already reserved by another activity
Parameters
activity The activity reserving the scope.
Definition at line 522 of file VariableDictionary.cpp.
References ArrayClass::append(), Activity::checkDeadLock(), Activity::isSameActivityStack(), new_array(), OREF_NULL, reserveCount, reservingActivity, setField, waitingActivities, and Activity::waitReserve().
Referenced by RexxActivation::getObjectVariables(), NativeActivation::guardOn(), RexxActivation::guardOn(), RexxObject::guardOn(), NativeActivation::guardWait(), RexxActivation::guardWait(), NativeActivation::methodVariables(), AttributeGetterCode::run(), AttributeSetterCode::run(), DelegateCode::run(), and RexxActivation::run().
resolveVariable()
RexxVariable* VariableDictionary::resolveVariable (RexxString * name) inline
Definition at line 159 of file VariableDictionary.hpp.
References contents, and HashContents::get().
Referenced by drop(), dropStemVariable(), RexxLocalVariables::findVariable(), getStemVariable(), getVariable(), RexxLocalVariables::lookupStemVariable(), RexxLocalVariables::lookupVariable(), and realValue().
set()
void VariableDictionary::set (RexxString * name, RexxObject * value)
Set a new variable value.
Parameters
name The variable name.
value The value object.
Definition at line 508 of file VariableDictionary.cpp.
References getVariable(), and RexxVariable::set().
Referenced by RexxObject::setObjectVariable().
setCompoundVariable()
void VariableDictionary::setCompoundVariable (RexxString * stemName, RexxInternalObject ** tail, size_t tailCount, RexxObject * value)
Set a compound variable in the dictionary.
Parameters
stemName The name of the stem.
tail The tail elements.
tailCount The count of tail elements.
value The value to set.
Definition at line 694 of file VariableDictionary.cpp.
References getStem(), and StemClass::setCompoundVariable().
Referenced by RexxCompoundVariable::set().
setNextDictionary()
void VariableDictionary::setNextDictionary (VariableDictionary * next)
Chain up a dictionary associated with an object. An object has a single variable dictionary for each scope, but only a single anchoring field in the object. The multiple scopes are handled by chaining the variable dictionaries together.
Parameters
next The next dictionary in our chain.
Definition at line 624 of file VariableDictionary.cpp.
References nextDictionary, and setField.
Referenced by RexxObject::addObjectVariables(), and RexxObject::getObjectVariables().
transfer()
bool VariableDictionary::transfer (Activity * activity)
Transfer the variable dictionary lock to another activity. Occurs when a reply has been issued.
Parameters
activity The new activity.
Returns
true if the reservation could transfer, false if there is nesting taking place that prevents this from occurring.
Definition at line 594 of file VariableDictionary.cpp.
References release(), reserveCount, and reservingActivity.
Referenced by RexxActivation::run().
Member Data Documentation
contents
StringHashContents* VariableDictionary::contents protected
Definition at line 226 of file VariableDictionary.hpp.
Referenced by addVariable(), checkFull(), copy(), copyValues(), ensureCapacity(), expandContents(), flatten(), getAllVariables(), getVariableDirectory(), initialize(), live(), liveGeneral(), remove(), resolveVariable(), and VariableDictionary::VariableIterator::VariableIterator().
DefaultObjectDictionarySize
const size_t VariableDictionary::DefaultObjectDictionarySize = 7 static
Definition at line 217 of file VariableDictionary.hpp.
Referenced by VariableDictionary().
flags
unsigned short VariableDictionary::flags protected
Definition at line 228 of file VariableDictionary.hpp.
idntfr
uint32_t VariableDictionary::idntfr protected
Definition at line 232 of file VariableDictionary.hpp.
Referenced by getIdntfr().
nextDictionary
VariableDictionary* VariableDictionary::nextDictionary protected
Definition at line 230 of file VariableDictionary.hpp.
Referenced by deepCopy(), flatten(), getNextDictionary(), live(), liveGeneral(), and setNextDictionary().
reserveCount
unsigned short VariableDictionary::reserveCount protected
Definition at line 229 of file VariableDictionary.hpp.
Referenced by getReserveCount(), release(), reserve(), and transfer().
reservingActivity
Activity* VariableDictionary::reservingActivity protected
Definition at line 225 of file VariableDictionary.hpp.
Referenced by getReservingActivity(), live(), liveGeneral(), release(), reserve(), and transfer().
scope
RexxClass* VariableDictionary::scope protected
Definition at line 231 of file VariableDictionary.hpp.
Referenced by flatten(), isScope(), live(), liveGeneral(), and VariableDictionary().
waitingActivities
ArrayClass* VariableDictionary::waitingActivities protected
Definition at line 227 of file VariableDictionary.hpp.
Referenced by live(), liveGeneral(), release(), and reserve().
The documentation for this class was generated from the following files:
VariableDictionary.hpp
VariableDictionary.cpp