ooRexx: SysFileSystem Class Reference
SysFileSystem Class Reference
#include <SysFileSystem.hpp>
Public Types
enum { MaximumPathLength = MAXIMUM_PATH_LENGTH , MaximumFileNameLength = MAXIMUM_FILENAME_LENGTH , MaximumFileNameBuffer = MAXIMUM_PATH_LENGTH + MAXIMUM_FILENAME_LENGTH }
enum { MaximumPathLength = MAXIMUM_PATH_LENGTH , MaximumFileNameLength = MAXIMUM_FILENAME_LENGTH , MaximumFileNameBuffer = MAXIMUM_PATH_LENGTH + MAXIMUM_FILENAME_LENGTH }
enum FiletimeType { FiletimeAccess , FiletimeWrite , FiletimeCreation }
Static Public Member Functions
static bool searchFileName (const char *name, FileNameBuffer &fileName)
static void qualifyStreamName (const char *unqualifiedName, FileNameBuffer &qualifiedName)
static bool fileExists (const char *name)
static bool searchName (const char *name, const char *path, const char *extension, FileNameBuffer &resolvedName)
static bool searchPath (const char *name, const char *path, FileNameBuffer &resolvedName)
static bool primitiveSearchName (const char *name, const char *path, const char *extension, FileNameBuffer &resolvedName)
static bool checkCurrentFile (const char *name, FileNameBuffer &resolvedName)
static bool hasExtension (const char *name)
static bool hasDirectory (const char *name)
static bool canonicalizeName (FileNameBuffer &resolvedName)
static bool normalizePathName (const char *name, FileNameBuffer &resolvedName)
static RexxString * extractDirectory (RexxString *file)
static RexxString * extractExtension (RexxString *file)
static RexxString * extractFile (RexxString *file)
static int deleteFile (const char *name)
static int deleteDirectory (const char *name)
static bool isDirectory (const char *name)
static bool isReadOnly (const char *name)
static bool isWriteOnly (const char *name)
static bool canWrite (const char *name)
static bool canRead (const char *name)
static bool isFile (const char *name)
static bool isLink (const char *name)
static bool exists (const char *name)
static int64_t getLastModifiedDate (const char *name)
static int64_t getLastAccessDate (const char *name)
static bool setLastModifiedDate (const char *name, int64_t time)
static bool setLastAccessDate (const char *name, int64_t time)
static uint64_t getFileLength (const char *name)
static bool makeDirectory (const char *name)
static bool isHidden (const char *name)
static bool setFileReadOnly (const char *name)
static bool setFileWritable (const char *name)
static bool isCaseSensitive ()
static bool isCaseSensitive (const char *name)
static int getRoots (FileNameBuffer &roots)
static const char * getSeparator ()
static const char * getPathSeparator ()
static const char * getLineEnd ()
static bool getCurrentDirectory (FileNameBuffer &directory)
static bool setCurrentDirectory (const char *directory)
static int copyFile (const char *fromFile, const char *toFile)
static int moveFile (const char *fromFile, const char *toFile)
static bool resolveTilde (FileNameBuffer &name)
static const char * getPathStart (const char *name)
static const char * getPathEnd (const char *name)
static bool getTemporaryPath (FileNameBuffer &temporary)
static bool searchFileName (const char *name, FileNameBuffer &fullName)
static bool searchOnPath (const char *name, const char *path, const char *extension, FileNameBuffer &resolvedName)
static bool searchPath (const char *name, const char *path, FileNameBuffer &resolvedName)
static void qualifyStreamName (const char *unqualifiedName, FileNameBuffer &qualifiedName)
static bool getFullPathName (const char *name, FileNameBuffer &resolvedName)
static DWORD getFileAttributes (const char *name)
static bool getFiletime (const char *name, FiletimeType type, FILETIME *time)
static bool fileExists (const char *name)
static bool hasExtension (const char *name)
static bool hasDirectory (const char *name)
static RexxString * extractDirectory (RexxString *file)
static RexxString * extractExtension (RexxString *file)
static RexxString * extractFile (RexxString *file)
static bool searchName (const char *name, const char *path, const char *extension, FileNameBuffer &resolvedName)
static bool primitiveSearchName (const char *name, const char *path, const char *extension, FileNameBuffer &resolvedName)
static bool checkCurrentFile (const char *name, FileNameBuffer &resolvedName)
static void getLongName (FileNameBuffer &name)
static void getProperPathCase (FileNameBuffer &name)
static int deleteFile (const char *name)
static int deleteDirectory (const char *name)
static bool isDirectory (const char *name)
static bool isReadOnly (const char *name)
static bool isWriteOnly (const char *name)
static bool canWrite (const char *name)
static bool canRead (const char *name)
static bool isFile (const char *name)
static bool isLink (const char *name)
static bool exists (const char *name)
static int64_t getLastModifiedDate (const char *name)
static int64_t getLastAccessDate (const char *name)
static bool setLastModifiedDate (const char *name, int64_t time)
static bool setLastAccessDate (const char *name, int64_t time)
static int64_t getFileLength (const char *name)
static bool makeDirectory (const char *name)
static bool isHidden (const char *name)
static bool setFileReadOnly (const char *name)
static bool setFileWritable (const char *name)
static bool isCaseSensitive ()
static bool isCaseSensitive (const char *name)
static int getRoots (FileNameBuffer &roots)
static const char * getSeparator ()
static const char * getPathSeparator ()
static const char * getLineEnd ()
static bool getCurrentDirectory (FileNameBuffer &directory)
static bool setCurrentDirectory (const char *directory)
static int copyFile (const char *fromFile, const char *toFile)
static int moveFile (const char *fromFile, const char *toFile)
static const char * getPathStart (const char *name)
static const char * getPathEnd (const char *name)
static bool getTemporaryPath (FileNameBuffer &temporary)
Static Public Attributes
static const char EOF_Marker = 0x1A
static const char * EOL_Marker = "\n"
static const char PathDelimiter = '/'
static const char NewLine = '\n'
static const char CarriageReturn = '\r'
static int stdinHandle = 0
static int stdoutHandle = 1
static int stderrHandle = 2
Detailed Description
Definition at line 87 of file unix/SysFileSystem.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MaximumPathLength
MaximumFileNameLength
MaximumFileNameBuffer
Definition at line 90 of file unix/SysFileSystem.hpp.
anonymous enum
anonymous enum
Enumerator
MaximumPathLength
MaximumFileNameLength
MaximumFileNameBuffer
Definition at line 57 of file windows/SysFileSystem.hpp.
FiletimeType
enum SysFileSystem::FiletimeType
Enumerator
FiletimeAccess
FiletimeWrite
FiletimeCreation
Definition at line 65 of file windows/SysFileSystem.hpp.
Member Function Documentation
canonicalizeName()
bool SysFileSystem::canonicalizeName (FileNameBuffer & name) static
Process a file name to add the current working directory or the home directory, as needed, then remove all of the . and .. elements.
Parameters
name The current working name.
Returns
true if this was valid enough to normalize.
Definition at line 613 of file unix/SysFileSystem.cpp.
References getCurrentDirectory(), FileNameBuffer::isEmpty(), normalizePathName(), resolveTilde(), and FileNameBuffer::startsWith().
Referenced by TreeFinder::adjustDirectory(), checkCurrentFile(), qualifyStreamName(), searchFileName(), and searchPath().
canRead() [1/2]
bool SysFileSystem::canRead (const char * name) static
Test is a file is readable .
Parameters
name The target file name.
Returns
true if the file can be read.
Test is a file is read only.
Parameters
name The target file name.
Returns
true if the file is marked as read-only.
Definition at line 831 of file unix/SysFileSystem.cpp.
Referenced by RexxMethod1().
canRead() [2/2]
static bool SysFileSystem::canRead (const char * name) static
canWrite() [1/2]
bool SysFileSystem::canWrite (const char * name) static
Test if the process can write to the file. This is not the same as being read only
Parameters
name The target file name.
Returns
true if the file is only writeable. false if read operations are permitted.
Test if a file is writable
Parameters
name The target file name.
Returns
true if the file exists and can be opened for write operations.
Definition at line 861 of file unix/SysFileSystem.cpp.
Referenced by deleteFile(), and RexxMethod1().
canWrite() [2/2]
static bool SysFileSystem::canWrite (const char * name) static
checkCurrentFile() [1/2]
bool SysFileSystem::checkCurrentFile (const char * name, FileNameBuffer & resolvedName) static
Try to locate a file using just the raw name passed in, as opposed to searching along a path for the name.
Parameters
name The name to use for the search.
resolvedName The buffer for the returned name.
Returns
true if the file was located, false otherwise.
Try to locate a file using just the raw name passed in, as opposed to searching along a path for the name.
Parameters
name The name to use for the search.
resolvedName The returned resolved name.
resolvedNameLength The length of the resolved name buffer
Returns
An RexxString version of the file name, iff the file was located. Returns OREF_NULL if the file did not exist.
Definition at line 438 of file unix/SysFileSystem.cpp.
References canonicalizeName().
Referenced by primitiveSearchName(), and searchPath().
checkCurrentFile() [2/2]
static bool SysFileSystem::checkCurrentFile (const char * name, FileNameBuffer & resolvedName) static
copyFile() [1/2]
int SysFileSystem::copyFile (const char * fromFile, const char * toFile) static
Implementation of a copy file operation.
Parameters
fromFile The from file of the copy operation
toFile The to file of the copy operation.
Returns
Any error codes.
Definition at line 1728 of file unix/SysFileSystem.cpp.
References copyFileDereferenceSymbolicLinks().
Referenced by RexxRoutine2().
copyFile() [2/2]
static int SysFileSystem::copyFile (const char * fromFile, const char * toFile) static
deleteDirectory() [1/2]
int SysFileSystem::deleteDirectory (const char * name) static
Delete a directory from the file system.
Parameters
name The name of the target directory.
Returns
The return code from the delete operation.
Definition at line 788 of file unix/SysFileSystem.cpp.
Referenced by RexxMethod1(), and RexxRoutine1().
deleteDirectory() [2/2]
static int SysFileSystem::deleteDirectory (const char * name) static
deleteFile() [1/2]
int SysFileSystem::deleteFile (const char * name) static
Delete a file from the file system.
Parameters
name The fully qualified name of the file.
Returns
The return code from the delete operation.
Definition at line 771 of file unix/SysFileSystem.cpp.
References canWrite().
Referenced by RexxMethod1(), and RexxRoutine1().
deleteFile() [2/2]
static int SysFileSystem::deleteFile (const char * name) static
exists() [1/2]
bool SysFileSystem::exists (const char * name) static
Test if a file or directory exists using a fully qualified name.
Parameters
name The target file or directory name.
Returns
True if the file or directory exists, false if it is unknown.
Definition at line 893 of file unix/SysFileSystem.cpp.
Referenced by getUniqueFileName(), isCaseSensitive(), isHidden(), RexxMethod1(), and RexxRoutine1().
exists() [2/2]
static bool SysFileSystem::exists (const char * name) static
extractDirectory() [1/2]
RexxString * SysFileSystem::extractDirectory (RexxString * file) static
Extract directory information from a file name.
Parameters
file The input file name. If this represents a real source file, this will be fully resolved.
Returns
The directory portion of the file name. If the file name does not include a directory portion, then OREF_NULL is returned.
Definition at line 224 of file unix/SysFileSystem.cpp.
References RexxString::getLength(), RexxString::getStringData(), new_string(), and OREF_NULL.
Referenced by PackageClass::extractNameInformation().
extractDirectory() [2/2]
static RexxString* SysFileSystem::extractDirectory (RexxString * file) static
extractExtension() [1/2]
RexxString * SysFileSystem::extractExtension (RexxString * file) static
Extract extension information from a file name.
Parameters
file The input file name. If this represents a real source file, this will be fully resolved.
Returns
The extension portion of the file name. If the file name does not include an extension portion, then OREF_NULL is returned.
Definition at line 256 of file unix/SysFileSystem.cpp.
References RexxString::getLength(), RexxString::getStringData(), new_string(), and OREF_NULL.
Referenced by PackageClass::extractNameInformation().
extractExtension() [2/2]
static RexxString* SysFileSystem::extractExtension (RexxString * file) static
extractFile() [1/2]
RexxString * SysFileSystem::extractFile (RexxString * file) static
Extract file information from a file name.
Parameters
file The input file name. If this represents a real source file, this will be fully resolved.
Returns
The file portion of the file name. If the file name does not include a directory portion, then the entire string is returned
Definition at line 292 of file unix/SysFileSystem.cpp.
References RexxString::getLength(), RexxString::getStringData(), and new_string().
Referenced by PackageClass::extractNameInformation().
extractFile() [2/2]
static RexxString* SysFileSystem::extractFile (RexxString * file) static
fileExists() [1/2]
bool SysFileSystem::fileExists (const char * name) static
Test if a given file exists.
Parameters
fname The target file name.
Returns
true if the file exists, false otherwise.
Check to see if a file with a given name exists.
Parameters
name The name to check.
Returns
True if the file exists, false otherwise.
Definition at line 198 of file unix/SysFileSystem.cpp.
Referenced by moveFile(), searchFileName(), StreamInfo::streamExists(), StreamInfo::streamOpen(), and temporaryFilename().
fileExists() [2/2]
static bool SysFileSystem::fileExists (const char * name) static
getCurrentDirectory() [1/2]
bool SysFileSystem::getCurrentDirectory (FileNameBuffer & directory) static
Retrieve the current working directory into a FileNameBuffer.
Parameters
directory The return directory name.
Returns
true if this was retrieved, false otherwise.
Definition at line 1378 of file unix/SysFileSystem.cpp.
References FileNameBuffer::capacity(), and FileNameBuffer::expandCapacity().
Referenced by SystemInterpreter::buildEnvlist(), canonicalizeName(), TreeFinder::expandNonPath2fullPath(), RexxRoutine1(), RexxRoutine3(), and searchFileName().
getCurrentDirectory() [2/2]
static bool SysFileSystem::getCurrentDirectory (FileNameBuffer & directory) static
getFileAttributes()
DWORD SysFileSystem::getFileAttributes (const char * name) static
Get attribute flags for a file with the given name.
Parameters
name The name to check.
Returns
File attribute flags if the file exists, INVALID_FILE_ATTRIBUTES otherwise.
Definition at line 247 of file windows/SysFileSystem.cpp.
Referenced by RexxRoutine1().
getFileLength() [1/2]
int64_t SysFileSystem::getFileLength (const char * name) static
Retrieve the size of a file.
Parameters
name The name of the target file.
Returns
the 64-bit file size.
Retrieve the size of a file.
Parameters
name The name of the target file.
Returns
the 64-bit file size, or zero if not a valid file
Definition at line 1069 of file unix/SysFileSystem.cpp.
Referenced by RexxMethod1().
getFileLength() [2/2]
static int64_t SysFileSystem::getFileLength (const char * name) static
getFiletime()
bool SysFileSystem::getFiletime (const char * name, FiletimeType type, FILETIME * time) static
Get the FILETIME for a file with the given name.
Parameters
name The name to check.
type The type of FILETIME to return. Can be FiletimeAccess, FiletimeWrite, or FiletimeCreation
time The returned FILETIME.
Returns
true if the file exists, false otherwise.
Definition at line 280 of file windows/SysFileSystem.cpp.
References FiletimeAccess, FiletimeWrite, and type.
Referenced by RexxRoutine2().
getFullPathName()
bool SysFileSystem::getFullPathName (const char * name, FileNameBuffer & fullName) static
Get the full path name of a file.
Parameters
name The source name
fullName a buffer for returning the resolved name
Returns
true if this could be resolved, false otherwise.
Definition at line 136 of file windows/SysFileSystem.cpp.
References FileNameBuffer::capacity(), FileNameBuffer::ensureCapacity(), and getLongName().
getLastAccessDate() [1/2]
int64_t SysFileSystem::getLastAccessDate (const char * name) static
Get the file last access date as a file time value.
Parameters
name The target name.
Returns
the file time value for the modified date, or -999999999999999999 for any errors. The time is returned in microseconds.
Get the file last access data as a file time value.
Parameters
name The target name.
Returns
the file time value for the last access date, or -999999999999999999 for any errors.
Definition at line 1040 of file unix/SysFileSystem.cpp.
References NoTimeStamp, and utcToLocal().
Referenced by RexxMethod1().
getLastAccessDate() [2/2]
static int64_t SysFileSystem::getLastAccessDate (const char * name) static
getLastModifiedDate() [1/2]
int64_t SysFileSystem::getLastModifiedDate (const char * name) static
Get the last modified file date as a file time value.
Parameters
name The target name.
Returns
the file time value for the modified date, or -999999999999999999 for any errors. The time is returned in microseconds.
Get the last modified file date as a file time value.
Parameters
name The target name.
Returns
the file time value for the modified date, or -999999999999999999 for any errors.
Definition at line 1010 of file unix/SysFileSystem.cpp.
References NoTimeStamp, and utcToLocal().
Referenced by RexxMethod1().
getLastModifiedDate() [2/2]
static int64_t SysFileSystem::getLastModifiedDate (const char * name) static
getLineEnd() [1/2]
const char * SysFileSystem::getLineEnd () static
Return the string used as a line-end separator.
Returns
The ASCII-Z version of the line end sequence.
Definition at line 1365 of file unix/SysFileSystem.cpp.
Referenced by RexxInfo::initialize().
getLineEnd() [2/2]
static const char* SysFileSystem::getLineEnd () static
getLongName()
void SysFileSystem::getLongName (FileNameBuffer & fullName) static
Get the actual name value of a located file, in the exact case used on the harddrive.
Parameters
fullName The buffer used for the name.
size The size of the buffer.
Definition at line 622 of file windows/SysFileSystem.cpp.
References FileNameBuffer::at(), FileNameBuffer::capacity(), FileNameBuffer::ensureCapacity(), getProperPathCase(), and FileNameBuffer::length().
Referenced by getFullPathName(), and searchOnPath().
getPathEnd() [1/2]
const char * SysFileSystem::getPathEnd (const char * name) static
Locate the last directory delimiter in a file spec name
Parameters
name The give name.
Returns
The location of the last directory delimiter, or NULL if one is not found.
Definition at line 1811 of file unix/SysFileSystem.cpp.
References PathDelimiter.
Referenced by RexxRoutine2().
getPathEnd() [2/2]
static const char* SysFileSystem::getPathEnd (const char * name) static
getPathSeparator() [1/2]
const char * SysFileSystem::getPathSeparator () static
Return the separator used for separating search path elements
Returns
The ASCII-Z version of the path separator.
Definition at line 1354 of file unix/SysFileSystem.cpp.
Referenced by FileNameBuffer::appendPathSeparator(), RexxInfo::initialize(), RexxMethod0(), and RexxRoutine3().
getPathSeparator() [2/2]
static const char* SysFileSystem::getPathSeparator () static
getPathStart() [1/2]
const char * SysFileSystem::getPathStart (const char * name) static
Locate the last directory delimiter in a file spec name
Parameters
name The give name.
Returns
The location of the last directory delimiter, or NULL if one is not found.
Definition at line 1825 of file unix/SysFileSystem.cpp.
Referenced by RexxRoutine2().
getPathStart() [2/2]
static const char* SysFileSystem::getPathStart (const char * name) static
getProperPathCase()
void SysFileSystem::getProperPathCase (FileNameBuffer & fullName) static
Resolve as much of the path as we can to obtain the path in Unfortunately, GetLongPathName() will preserve original case for both the file names and portions of the the path, so we need to step back through all of the elements of the path and resolve the actual case name of the element.
Parameters
fullName The source path name. This will be overwritten with the correct path on return.
Definition at line 675 of file windows/SysFileSystem.cpp.
Referenced by getLongName().
getRoots() [1/2]
int SysFileSystem::getRoots (FileNameBuffer & roots) static
Retrieve the file system root elements. On Windows, each of the drives is a root element.
Returns
The number of roots located.
Definition at line 1330 of file unix/SysFileSystem.cpp.
Referenced by RexxMethod0().
getRoots() [2/2]
static int SysFileSystem::getRoots (FileNameBuffer & roots) static
getSeparator() [1/2]
const char * SysFileSystem::getSeparator () static
Return the separator used for separating path names.
Returns
The ASCII-Z version of the path separator.
Definition at line 1343 of file unix/SysFileSystem.cpp.
Referenced by RexxInfo::initialize(), and RexxMethod0().
getSeparator() [2/2]
static const char* SysFileSystem::getSeparator () static
getTemporaryPath() [1/2]
bool SysFileSystem::getTemporaryPath (FileNameBuffer & temporary) static
Retrieve the location where temporary files should be stored. This will be the value of environment variable TMPDIR, if defined, or /tmp.
Returns
true if successful, false otherwise.
Retrieve the location where temporary files should be stored. This will be the value of environment variable TMP, TEMP, or USERPROFILE, if defined, otherwise the current working directory.
Returns
true if successful, false otherwise.
Definition at line 1837 of file unix/SysFileSystem.cpp.
References SystemInterpreter::getEnvironmentVariable().
Referenced by RexxMethod0().
getTemporaryPath() [2/2]
static bool SysFileSystem::getTemporaryPath (FileNameBuffer & temporary) static
hasDirectory() [1/2]
bool SysFileSystem::hasDirectory (const char * name) static
Test if a filename has a directory portion
Parameters
name The name to check.
Returns
true if a directory was found on the file, false if there is no directory.
Definition at line 355 of file unix/SysFileSystem.cpp.
Referenced by primitiveSearchName(), and searchPath().
hasDirectory() [2/2]
static bool SysFileSystem::hasDirectory (const char * name) static
hasExtension() [1/2]
bool SysFileSystem::hasExtension (const char * name) static
Test if a filename has an extension.
Parameters
name The name to check.
Returns
true if an extension was found on the file, false if there is no extension.
Definition at line 322 of file unix/SysFileSystem.cpp.
Referenced by InterpreterInstance::resolveProgramName().
hasExtension() [2/2]
static bool SysFileSystem::hasExtension (const char * name) static
isCaseSensitive() [1/4]
bool SysFileSystem::isCaseSensitive () static
indicate whether the file system is case sensitive.
Returns
true if root (/) is case-sensitive.
indicate whether the file system is case sensitive.
Returns
For Windows, the case-sensitivity of the Windows system directory is returned, typically C:\Windows\system32
Definition at line 1251 of file unix/SysFileSystem.cpp.
Referenced by RexxInfo::getCaseSensitiveFiles(), RexxActivation::getStreams(), RexxMethod0(), RexxMethod1(), samePaths(), and SysFileIterator::SysFileIterator().
isCaseSensitive() [2/4]
static bool SysFileSystem::isCaseSensitive () static
isCaseSensitive() [3/4]
bool SysFileSystem::isCaseSensitive (const char * name) static
test if an individual file is a case sensitive name
Most Unix file systems by default are case-sensitive (with the exception of e. g. Darwin). But since Linux kernel 5.2 a per-directory case-insensitivity is supported on ext4 file systems. On Darwin, partitions may be configured to be case sensitive.
Returns
true if the given file is located within a case-sensitive directory.
Test if a file or directory is case-sensitive.
On Windows, case-sensitivity is defined on a per-directory basis. Once a directory has been set as case-sensitive, files in this directory and any newly created subdirectories within this directory become case-sensitive. Existing subdirectories and files within those existing subdirectories stay as they are.
Returns
true if this is a case-sensitive directory, or a file within a case-sensitive directory, false otherwise.
Definition at line 1267 of file unix/SysFileSystem.cpp.
References exists().
isCaseSensitive() [4/4]
static bool SysFileSystem::isCaseSensitive (const char * name) static
isDirectory() [1/2]
bool SysFileSystem::isDirectory (const char * name) static
Test if a given file name is for a directory.
Parameters
name The target name.
Returns
true if the file is a directory, false for any other type of entity.
Definition at line 802 of file unix/SysFileSystem.cpp.
Referenced by LineReader::open(), RexxMethod1(), and RexxRoutine1().
isDirectory() [2/2]
static bool SysFileSystem::isDirectory (const char * name) static
isFile() [1/2]
bool SysFileSystem::isFile (const char * name) static
Test if a give file name is for a real file (not a directory).
Parameters
name The target file name.
Returns
true if the file is a real file, false if some other filesystem entity.
Definition at line 877 of file unix/SysFileSystem.cpp.
Referenced by RexxMethod1(), and RexxRoutine1().
isFile() [2/2]
static bool SysFileSystem::isFile (const char * name) static
isHidden() [1/2]
bool SysFileSystem::isHidden (const char * name) static
Test if a given file or directory is hidden.
Parameters
name The target name.
Returns
true if the file or directory is hidden, false otherwise.
Definition at line 1100 of file unix/SysFileSystem.cpp.
References exists().
Referenced by RexxMethod1().
isHidden() [2/2]
static bool SysFileSystem::isHidden (const char * name) static
isLink() [1/2]
bool SysFileSystem::isLink (const char * name) static
Determine if the given file is a symbolic link to another file.
Parameters
name The file name.
Returns
True if the file is considered a link, false if this is the real file object.
Definition at line 910 of file unix/SysFileSystem.cpp.
Referenced by RexxRoutine1().
isLink() [2/2]
static bool SysFileSystem::isLink (const char * name) static
isReadOnly() [1/2]
bool SysFileSystem::isReadOnly (const char * name) static
Test is a file is read only.
Parameters
name The target file name.
Returns
true if the file is marked as read-only.
Test is a file is read only.
Parameters
name The target file name.
Returns
true if the file can be opened for reading
Definition at line 818 of file unix/SysFileSystem.cpp.
isReadOnly() [2/2]
static bool SysFileSystem::isReadOnly (const char * name) static
isWriteOnly() [1/2]
bool SysFileSystem::isWriteOnly (const char * name) static
Test if a file is marked as write-only.
Parameters
name The target file name.
Returns
true if the file is only writeable. false if read operations are permitted.
Definition at line 846 of file unix/SysFileSystem.cpp.
isWriteOnly() [2/2]
static bool SysFileSystem::isWriteOnly (const char * name) static
makeDirectory() [1/2]
bool SysFileSystem::makeDirectory (const char * name) static
Create a directory in the file system.
Parameters
name The target name.
Returns
The success/failure flag.
Definition at line 1087 of file unix/SysFileSystem.cpp.
Referenced by RexxMethod1().
makeDirectory() [2/2]
static bool SysFileSystem::makeDirectory (const char * name) static
moveFile() [1/2]
int SysFileSystem::moveFile (const char * fromFile, const char * toFile) static
Move a file from one location to another. This is typically just a rename, but if necessary, the file will be copied and the original unlinked.
Parameters
fromFile The file we're copying from.
toFile The target file.
Returns
0 if this was successful, otherwise the system error code.
Definition at line 1744 of file unix/SysFileSystem.cpp.
References copyFileDontDereferenceSymbolicLinks(), fileExists(), samePaths(), and temporaryFilename().
Referenced by RexxMethod2(), and RexxRoutine2().
moveFile() [2/2]
static int SysFileSystem::moveFile (const char * fromFile, const char * toFile) static
normalizePathName()
bool SysFileSystem::normalizePathName (const char * name, FileNameBuffer & resolvedName) static
Normalize an absolute Unix path name. Removes duplicate and trailing slashes, resolves and removes ./ or ../ This works for any path name, whether the resovled name exists or not.
Parameters
name The path name to normalize.
resolved On success the normalized name is returned here.
Returns
True on success, otherwise false.
@assumes Name is null-terminated and that resolved is an adequate buffer.
Definition at line 672 of file unix/SysFileSystem.cpp.
References FileNameBuffer::at().
Referenced by canonicalizeName().
primitiveSearchName() [1/2]
bool SysFileSystem::primitiveSearchName (const char * name, const char * path, const char * extension, FileNameBuffer & resolvedName) static
Do a search for a single variation of a filename.
Parameters
name The name to search for.
path The path to search over
extension A potential extension to add to the file name (can be NULL).
resolvedName The buffer used to return the resolved file name.
Returns
true if the file was located. A true returns indicates the resolved file name has been placed in the provided buffer.
Do a search for a single variation of a filename.
NOTE: This version does not do anything with the kernel lock, so it is callable before the first activity is set up.
Parameters
name The name to search for.
path The path to be searched on
extension A potential extension to add to the file name (can be NULL).
resolvedName The buffer used to return the resolved file name.
Returns
true if the file was located. A true returns indicates the resolved file name has been placed in the provided buffer.
Definition at line 396 of file unix/SysFileSystem.cpp.
References checkCurrentFile(), hasDirectory(), searchPath(), and Utilities::strlower().
Referenced by MemoryObject::loadImage(), and searchName().
primitiveSearchName() [2/2]
static bool SysFileSystem::primitiveSearchName (const char * name, const char * path, const char * extension, FileNameBuffer & resolvedName) static
qualifyStreamName() [1/2]
void SysFileSystem::qualifyStreamName (const char * unqualifiedName, FileNameBuffer & qualifiedName) static
Get the fully qualified name for a file.
Parameters
name The input file name.
fullName The return full file name
Generate a fully qualified stream name.
Parameters
unqualifiedName The starting name.
qualifiedName The fully expanded and canonicalized file name.
Definition at line 172 of file unix/SysFileSystem.cpp.
References canonicalizeName(), and FileNameBuffer::length().
Referenced by getUniqueFileName(), MethodQualifiedName::MethodQualifiedName(), QualifiedName::QualifiedName(), StreamInfo::resolveStreamName(), and RoutineQualifiedName::RoutineQualifiedName().
qualifyStreamName() [2/2]
static void SysFileSystem::qualifyStreamName (const char * unqualifiedName, FileNameBuffer & qualifiedName) static
resolveTilde()
bool SysFileSystem::resolveTilde (FileNameBuffer & name) static
resolve the user home directory portion of a file name
Parameters
name The current working name. This is updated in place.
nameLength The length of the working buffer
Returns
true if this was valid enough to normalize.
Definition at line 541 of file unix/SysFileSystem.cpp.
References FileNameBuffer::at(), and FileNameBuffer::set().
Referenced by canonicalizeName().
searchFileName() [1/2]
bool SysFileSystem::searchFileName (const char * name, FileNameBuffer & fullName) static
Search for a given filename, returning the fully resolved name if it is found.
Parameters
name The original name.
fullName A pointer to the buffer where the resolved name is returned.
Returns
True if the file was found, false otherwise.
Search for a given filename, returning the fully resolved name if it is found.
Parameters
name The input search name.
fullName The returned fully resolved name.
fullNameLength length of the full name return buffer
Returns
True if the file was located, false otherwise.
Definition at line 91 of file unix/SysFileSystem.cpp.
References FileNameBuffer::at(), canonicalizeName(), fileExists(), getCurrentDirectory(), and FileNameBuffer::set().
searchFileName() [2/2]
static bool SysFileSystem::searchFileName (const char * name, FileNameBuffer & fullName) static
searchName() [1/2]
bool SysFileSystem::searchName (const char * name, const char * path, const char * extension, FileNameBuffer & resolvedName) static
Do a search for a single variation of a filename.
Parameters
name The name to search for.
path The path to search over (can be NULL)
extension A potential extension to add to the file name (can be NULL).
resolvedName The buffer used to return the resolved file name.
Returns
true if the file was located. A true returns indicates the resolved file name has been placed in the provided buffer.
Do a search for a single variation of a filename.
Parameters
name The name to search for.
path The path to search on (can be NULL)
extension A potential extension to add to the file name (can be NULL).
resolvedName The buffer used to return the resolved file name.
Returns
true if the file was located. A true returns indicates the resolved file name has been placed in the provided buffer.
Definition at line 377 of file unix/SysFileSystem.cpp.
References primitiveSearchName().
Referenced by InterpreterInstance::resolveProgramName().
searchName() [2/2]
static bool SysFileSystem::searchName (const char * name, const char * path, const char * extension, FileNameBuffer & resolvedName) static
searchOnPath()
bool SysFileSystem::searchOnPath (const char * name, const char * path, const char * extension, FileNameBuffer & fullName) static
Primitive search path with retry for buffer size problems.
Parameters
name The name to search for
resolvedName The buffer for the return result
Returns
true if there was a hit, false otherwise.
Definition at line 180 of file windows/SysFileSystem.cpp.
References FileNameBuffer::capacity(), FileNameBuffer::ensureCapacity(), and getLongName().
searchPath() [1/2]
bool SysFileSystem::searchPath (const char * name, const char * path, FileNameBuffer & resolvedName) static
Do a path search for a file.
Parameters
name The name to search for.
path The search path to use.
resolvedName A buffer used for returning the resolved name.
Returns
Returns true if the file was located. If true, the resolvedName buffer will contain the returned name.
Definition at line 473 of file unix/SysFileSystem.cpp.
References canonicalizeName(), checkCurrentFile(), FileNameBuffer::endsWith(), hasDirectory(), and FileNameBuffer::set().
Referenced by primitiveSearchName(), RexxMethod2(), and RexxRoutine3().
searchPath() [2/2]
static bool SysFileSystem::searchPath (const char * name, const char * path, FileNameBuffer & resolvedName) static
setCurrentDirectory() [1/2]
bool SysFileSystem::setCurrentDirectory (const char * directory) static
Set the current working directory
Parameters
directory The new directory set.
Returns
True if this worked, false for any failures
Definition at line 1406 of file unix/SysFileSystem.cpp.
Referenced by RexxRoutine1().
setCurrentDirectory() [2/2]
static bool SysFileSystem::setCurrentDirectory (const char * directory) static
setFileReadOnly() [1/2]
bool SysFileSystem::setFileReadOnly (const char * name) static
Set the read-only attribute on a file or directory.
Parameters
name The target name.
Returns
true if the attribute was set, false otherwise.
Definition at line 1208 of file unix/SysFileSystem.cpp.
Referenced by RexxMethod1().
setFileReadOnly() [2/2]
static bool SysFileSystem::setFileReadOnly (const char * name) static
setFileWritable() [1/2]
bool SysFileSystem::setFileWritable (const char * name) static
Set the write attribute on a file or directory.
Parameters
name The target name.
Returns
true if the attribute was set, false otherwise.
Set the read-only attribute on a file or directory.
Parameters
name The target name.
Returns
true if the attribute was set, false otherwise.
Definition at line 1230 of file unix/SysFileSystem.cpp.
Referenced by RexxMethod1().
setFileWritable() [2/2]
static bool SysFileSystem::setFileWritable (const char * name) static
setLastAccessDate() [1/2]
bool SysFileSystem::setLastAccessDate (const char * name, int64_t time) static
Set the last access date for a file.
Parameters
name The target name.
time The new file time (in ticks).
Returns
true if the filedate was set correctly, false otherwise.
Set the last access date for a file.
Parameters
name The target name.
time The new file time.
Returns
true if the filedate was set correctly, false otherwise.
Open the path ensuring GENERIC_WRITE and FILE_FLAG_BACKUP_SEMANTICS if it's a directory. The directory modification is only supported on some platforms (NT, Windows2000).
Definition at line 1169 of file unix/SysFileSystem.cpp.
References localToUtc().
Referenced by RexxMethod2().
setLastAccessDate() [2/2]
static bool SysFileSystem::setLastAccessDate (const char * name, int64_t time) static
setLastModifiedDate() [1/2]
bool SysFileSystem::setLastModifiedDate (const char * name, int64_t time) static
Set the last modified date for a file.
Parameters
name The file or directory name.
time The new file time in local time given as microseconds since 0001-01-01T00:00:00
Returns
true if the filedate was set correctly, false otherwise.
Set the last modified date for a file.
Parameters
name The target name.
time The new file time.
Returns
true if the filedate was set correctly, false otherwise.
Open the path ensuring GENERIC_WRITE and FILE_FLAG_BACKUP_SEMANTICS if it's a directory. The directory modification is only supported on some platforms (NT, Windows2000).
Definition at line 1130 of file unix/SysFileSystem.cpp.
References localToUtc().
Referenced by RexxMethod2().
setLastModifiedDate() [2/2]
static bool SysFileSystem::setLastModifiedDate (const char * name, int64_t time) static
Member Data Documentation
CarriageReturn
static const char SysFileSystem::CarriageReturn = '\r' static
Definition at line 101 of file unix/SysFileSystem.hpp.
EOF_Marker
static const char SysFileSystem::EOF_Marker = 0x1A static
Definition at line 97 of file unix/SysFileSystem.hpp.
EOL_Marker
static const char * SysFileSystem::EOL_Marker = "\n" static
Definition at line 98 of file unix/SysFileSystem.hpp.
Referenced by InputRedirector::readBuffered().
NewLine
static const char SysFileSystem::NewLine = '\n' static
Definition at line 100 of file unix/SysFileSystem.hpp.
PathDelimiter
static const char SysFileSystem::PathDelimiter = '/' static
Definition at line 99 of file unix/SysFileSystem.hpp.
Referenced by FileNameBuffer::addFinalPathDelimiter(), TreeFinder::expandPath2fullPath(), getPathEnd(), FileNameBuffer::locatePathDelimiter(), and TreeFinder::recursiveFindFile().
stderrHandle
int SysFileSystem::stderrHandle = 2 static
Definition at line 74 of file windows/SysFileSystem.hpp.
stdinHandle
int SysFileSystem::stdinHandle = 0 static
Definition at line 72 of file windows/SysFileSystem.hpp.
stdoutHandle
int SysFileSystem::stdoutHandle = 1 static
Definition at line 73 of file windows/SysFileSystem.hpp.
The documentation for this class was generated from the following files:
unix/SysFileSystem.hpp
windows/SysFileSystem.hpp
unix/SysFileSystem.cpp
windows/SysFileSystem.cpp