ooRexx: CompoundVariableTable::TableIterator Class Reference
CompoundVariableTable::TableIterator Class Reference
#include <CompoundVariableTable.hpp>
Public Member Functions
TableIterator ()
~TableIterator ()
bool isAvailable ()
RexxObject * value ()
CompoundTableElement * variable ()
RexxString * name ()
RexxString * name (RexxString *stemName)
void replace (RexxObject *v)
void next ()
Private Member Functions
TableIterator (CompoundVariableTable *c)
Private Attributes
CompoundVariableTable * contents
CompoundTableElement * current
Friends
class CompoundVariableTable
Detailed Description
an iterator for iterating over all entries of the table
Definition at line 79 of file CompoundVariableTable.hpp.
Constructor & Destructor Documentation
TableIterator() [1/2]
CompoundVariableTable::TableIterator::TableIterator () inline
Definition at line 84 of file CompoundVariableTable.hpp.
~TableIterator()
CompoundVariableTable::TableIterator::~TableIterator () inline
Definition at line 85 of file CompoundVariableTable.hpp.
TableIterator() [2/2]
CompoundVariableTable::TableIterator::TableIterator (CompoundVariableTable * c) inline private
Definition at line 97 of file CompoundVariableTable.hpp.
References contents, current, and CompoundVariableTable::first().
Member Function Documentation
isAvailable()
bool CompoundVariableTable::TableIterator::isAvailable () inline
Definition at line 87 of file CompoundVariableTable.hpp.
References current, and OREF_NULL.
Referenced by VariableDictionary::VariableIterator::isAvailable().
name() [1/2]
RexxString * CompoundVariableTable::TableIterator::name ()
Get the name from a compound table iterator.
Returns
The current variable name.
Definition at line 520 of file CompoundVariableTable.cpp.
name() [2/2]
RexxString * CompoundVariableTable::TableIterator::name (RexxString * stemName)
Get the full compound name from a compound table iterator.
Returns
The current variable name.
Definition at line 531 of file CompoundVariableTable.cpp.
next()
void CompoundVariableTable::TableIterator::next () inline
Definition at line 93 of file CompoundVariableTable.hpp.
References contents, current, and CompoundVariableTable::next().
replace()
void CompoundVariableTable::TableIterator::replace (RexxObject * v)
Get the full compound name from a compound table iterator.
Returns
The current variable name.
Definition at line 542 of file CompoundVariableTable.cpp.
value()
RexxObject * CompoundVariableTable::TableIterator::value ()
Get the value from a compound table iterator.
Returns
The current variable value.
Definition at line 509 of file CompoundVariableTable.cpp.
References current, and RexxVariable::getVariableValue().
variable()
CompoundTableElement* CompoundVariableTable::TableIterator::variable () inline
Definition at line 89 of file CompoundVariableTable.hpp.
References current.
Friends And Related Function Documentation
CompoundVariableTable
friend class CompoundVariableTable friend
Definition at line 81 of file CompoundVariableTable.hpp.
Member Data Documentation
contents
CompoundVariableTable* CompoundVariableTable::TableIterator::contents private
Definition at line 100 of file CompoundVariableTable.hpp.
Referenced by next(), and TableIterator().
current
CompoundTableElement* CompoundVariableTable::TableIterator::current private
Definition at line 101 of file CompoundVariableTable.hpp.
Referenced by isAvailable(), next(), TableIterator(), value(), and variable().
The documentation for this class was generated from the following files:
CompoundVariableTable.hpp
CompoundVariableTable.cpp