ooRexx: MacroTable Class Reference
MacroTable Class Reference
#include <MacroSpaceManager.hpp>
Public Member Functions
MacroTable ()
void clear ()
MacroItem * locate (const char *name)
MacroItem * remove (const char *name)
void reorder (MacroItem *current, MacroItem *previous)
void removeMacro (MacroItem *current, MacroItem *previous)
size_t macroCount ()
bool iterating ()
void startIteration ()
bool hasMore ()
MacroItem * getNext ()
void add (MacroItem *macro)
bool isEmpty ()
Protected Attributes
MacroItem * macros
MacroItem * iterator
Detailed Description
Definition at line 66 of file MacroSpaceManager.hpp.
Constructor & Destructor Documentation
MacroTable()
MacroTable::MacroTable () inline
Definition at line 70 of file MacroSpaceManager.hpp.
References iterator, and macros.
Member Function Documentation
add()
void MacroTable::add (MacroItem * macro) inline
Definition at line 133 of file MacroSpaceManager.hpp.
References iterator, macros, and MacroItem::next.
Referenced by ServerMacroSpaceManager::addMacro().
clear()
void MacroTable::clear ()
Clear the macro table.
Definition at line 78 of file MacroSpaceManager.cpp.
References iterator, macros, and MacroItem::next.
Referenced by ServerMacroSpaceManager::clear().
getNext()
MacroItem* MacroTable::getNext () inline
Definition at line 121 of file MacroSpaceManager.hpp.
References iterator, and MacroItem::next.
Referenced by ServerMacroSpaceManager::nextDescriptor(), and ServerMacroSpaceManager::nextImage().
hasMore()
bool MacroTable::hasMore () inline
Definition at line 120 of file MacroSpaceManager.hpp.
References iterator.
isEmpty()
bool MacroTable::isEmpty () inline
Definition at line 140 of file MacroSpaceManager.hpp.
References macros.
Referenced by ServerMacroSpaceManager::isStoppable().
iterating()
bool MacroTable::iterating () inline
Definition at line 118 of file MacroSpaceManager.hpp.
References iterator.
locate()
MacroItem * MacroTable::locate (const char * name)
locate a named macro item.
Parameters
name The required macro item.
Returns
The located macro item entry.
Definition at line 99 of file MacroSpaceManager.cpp.
References macros, MacroItem::name, MacroItem::next, reorder(), and Utilities::strCaselessCompare().
Referenced by ServerMacroSpaceManager::addMacro(), ServerMacroSpaceManager::deleteMacro(), ServerMacroSpaceManager::getDescriptor(), ServerMacroSpaceManager::getImage(), ServerMacroSpaceManager::queryMacro(), and ServerMacroSpaceManager::reorderMacro().
macroCount()
size_t MacroTable::macroCount () inline
Definition at line 106 of file MacroSpaceManager.hpp.
References macros, and MacroItem::next.
Referenced by ServerMacroSpaceManager::iterateMacros().
remove()
MacroItem * MacroTable::remove (const char * name)
locate and remove a named macro space
Parameters
name The name of the target macro.
Returns
The removed table item, or NULL if this is not found.
Definition at line 126 of file MacroSpaceManager.cpp.
References iterator, macros, MacroItem::name, MacroItem::next, removeMacro(), and Utilities::strCaselessCompare().
Referenced by ServerMacroSpaceManager::deleteMacro().
removeMacro()
void MacroTable::removeMacro (MacroItem * current, MacroItem * previous) inline
Definition at line 93 of file MacroSpaceManager.hpp.
References macros, and MacroItem::next.
Referenced by remove().
reorder()
void MacroTable::reorder (MacroItem * current, MacroItem * previous) inline
Definition at line 82 of file MacroSpaceManager.hpp.
References macros, and MacroItem::next.
Referenced by locate().
startIteration()
void MacroTable::startIteration () inline
Definition at line 119 of file MacroSpaceManager.hpp.
References iterator, and macros.
Referenced by ServerMacroSpaceManager::iterateMacros().
Member Data Documentation
iterator
MacroItem* MacroTable::iterator protected
Definition at line 147 of file MacroSpaceManager.hpp.
Referenced by add(), clear(), getNext(), hasMore(), iterating(), MacroTable(), remove(), and startIteration().
macros
MacroItem* MacroTable::macros protected
Definition at line 146 of file MacroSpaceManager.hpp.
Referenced by add(), clear(), isEmpty(), locate(), macroCount(), MacroTable(), remove(), removeMacro(), reorder(), and startIteration().
The documentation for this class was generated from the following files:
MacroSpaceManager.hpp
MacroSpaceManager.cpp