ooRexx: BaseCode Class Reference
BaseCode Class Reference
#include <BaseCode.hpp>
Public Member Functions
virtual void run (Activity *, MethodClass *, RexxObject *, RexxString *, RexxObject **, size_t, ProtectedObject &)
virtual void call (Activity *, RoutineClass *, RexxString *, RexxObject **, size_t, RexxString *, RexxString *, ActivationContext, ProtectedObject &)
virtual void call (Activity *, RoutineClass *, RexxString *, RexxObject **, size_t, ProtectedObject &)
virtual ArrayClass * getSource ()
virtual RexxObject * setSecurityManager (RexxObject *manager)
virtual PackageClass * getPackageObject ()
virtual RexxClass * findClass (RexxString *className)
virtual BaseCode * setPackageObject (PackageClass *s)
virtual PackageClass * getPackage ()
bool isSamePackage (PackageClass *p)
ProgramSource * detachSource ()
void attachSource (ProgramSource *)
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void live (size_t)
virtual void liveGeneral (MarkReason reason)
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Public Attributes
PackageClass * package
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Base class for a code object. Code objects can be invoked as methods, or called.
Definition at line 58 of file BaseCode.hpp.
Member Function Documentation
attachSource()
void BaseCode::attachSource (ProgramSource * s)
Attach the code to a program source object.
Parameters
s The source program source object.
Definition at line 231 of file BaseCode.cpp.
References PackageClass::attachSource(), OREF_NULL, and package.
Referenced by BaseExecutable::attachSource().
call() [1/2]
void BaseCode::call (Activity * activity, RoutineClass * routine, RexxString * msgname, RexxObject ** arguments, size_t argcount, ProtectedObject & result) virtual
Simplified call form used for calling from Rexx code to native code.
Parameters
activity The current activity.
msgname The name of the call.
arguments the call arguments.
argcount The count of arguments.
result The returned result.
Reimplemented in NativeRoutine, RegisteredRoutine, and RexxCode.
Definition at line 106 of file BaseCode.cpp.
References Error_Interpretation, and reportException().
call() [2/2]
void BaseCode::call (Activity * activity, RoutineClass * routine, RexxString * msgname, RexxObject ** arguments, size_t argcount, RexxString * ct, RexxString * env, ActivationContext context, ProtectedObject & result) virtual
Invoke a code element as a call target. This form is generally only used for calls from Rexx code to Rexx code or for top level program invocation.
Parameters
activity The activity we're running under.
msgname The name of the program or name used to invoke the routine.
arguments The arguments to the method.
argcount The count of arguments.
ct The call context.
env The current address environment.
context The type of call being made (program call, internal call, interpret, etc.)
result The returned result.
Reimplemented in RexxCode.
Definition at line 89 of file BaseCode.cpp.
Referenced by RoutineClass::call(), RoutineClass::callRexx(), RoutineClass::callWithRexx(), and RoutineClass::runProgram().
detachSource()
ProgramSource * BaseCode::detachSource ()
Detach the source from a code object.
Definition at line 216 of file BaseCode.cpp.
References PackageClass::detachSource(), OREF_NULL, and package.
Referenced by BaseExecutable::detachSource().
findClass()
RexxClass * BaseCode::findClass (RexxString * className) virtual
Default class resolution...which only looks in the environment or .local.
Parameters
className The target class name.
Returns
The resolved class object, or OREF_NULL if this is not known.
Definition at line 161 of file BaseCode.cpp.
References PackageClass::findClass(), Interpreter::findClass(), OREF_NULL, and package.
Referenced by BaseExecutable::findClass().
getPackage()
PackageClass * BaseCode::getPackage () virtual
Retrieve the package associated with a code object. Returns OREF_NULL if this code object doesn't have a package source.
Returns
The associated package, or OREF_NULL.
Definition at line 207 of file BaseCode.cpp.
References getPackageObject().
Referenced by isSamePackage().
getPackageObject()
PackageClass * BaseCode::getPackageObject () virtual
Retrieve the source object associated with a code object.
Returns
Definition at line 147 of file BaseCode.cpp.
References package.
Referenced by getPackage(), BaseExecutable::getPackageObject(), RexxActivation::RexxActivation(), and RexxActivation::traceClause().
getSource()
ArrayClass * BaseCode::getSource () virtual
Return source informaton for a BaseCode object. If not representing an element in a source file, this returns an empty array.
Returns
A null array.
Reimplemented in RexxCode.
Definition at line 120 of file BaseCode.cpp.
References TheNullArray.
Referenced by BaseExecutable::getSource(), and BaseExecutable::source().
isSamePackage()
bool BaseCode::isSamePackage (PackageClass * p) inline
Definition at line 73 of file BaseCode.hpp.
References getPackage().
Referenced by MethodClass::isSamePackage().
run()
void BaseCode::run (Activity * activity, MethodClass * method, RexxObject * receiver, RexxString * msgname, RexxObject ** arguments, size_t argCount, ProtectedObject & result) virtual
Run this code as a method invocation.
Parameters
activity The current activity.
method The method we're invoking.
receiver The method target object.
msgname The name the method was invoked under.
argCount The count of arguments.
arguments The argument pointer.
result The returned result.
Reimplemented in CPPCode, AttributeGetterCode, AttributeSetterCode, ConstantGetterCode, AbstractCode, DelegateCode, RexxCode, and NativeMethod.
Definition at line 67 of file BaseCode.cpp.
References Error_Interpretation, and reportException().
Referenced by MethodClass::run().
setPackageObject()
BaseCode * BaseCode::setPackageObject (PackageClass * s) virtual
Set a source object into a code context. The default implementation is just to return the same object without setting a source. This is used mostly for attaching a source context to native code methods and routines defined on directives.
Parameters
s The new source object.
Returns
Either the same object, or a new copy of the code object.
Reimplemented in NativeCode.
Definition at line 193 of file BaseCode.cpp.
References package, and setField.
Referenced by ClassDirective::resolveConstants(), and BaseExecutable::setPackageObject().
setSecurityManager()
RexxObject * BaseCode::setSecurityManager (RexxObject * manager) virtual
Set the security manager in the code source context.
Parameters
manager The new security manager.
Returns
Returns true if the manager could be set. Non-Rexx code objects just return false unconditionally.
Reimplemented in RexxCode.
Definition at line 135 of file BaseCode.cpp.
References TheFalseObject.
Referenced by MethodClass::setSecurityManager(), and RoutineClass::setSecurityManager().
Member Data Documentation
package
PackageClass* BaseCode::package
Definition at line 77 of file BaseCode.hpp.
Referenced by attachSource(), detachSource(), RexxCode::extract(), findClass(), RexxCode::findRoutine(), AttributeGetterCode::flatten(), ConstantGetterCode::flatten(), AbstractCode::flatten(), DelegateCode::flatten(), RexxCode::flatten(), NativeCode::flatten(), RexxCode::getLocalRoutines(), RexxCode::getMethods(), getPackageObject(), RexxCode::getProgramName(), RexxCode::getPublicRoutines(), RexxCode::getResources(), RexxCode::getRoutines(), NativeCode::getSecurityManager(), RexxCode::getSecurityManager(), RexxCode::getSource(), RexxCode::install(), RexxCode::interpret(), RexxCode::isTraceable(), CPPCode::live(), AttributeGetterCode::live(), ConstantGetterCode::live(), AbstractCode::live(), DelegateCode::live(), NativeCode::live(), RexxCode::live(), CPPCode::liveGeneral(), AttributeGetterCode::liveGeneral(), ConstantGetterCode::liveGeneral(), DelegateCode::liveGeneral(), NativeCode::liveGeneral(), RexxCode::liveGeneral(), AbstractCode::liveGeneral(), RexxCode::mergeRequired(), RexxCode::resolveProgramName(), setPackageObject(), NativeCode::setPackageObject(), and RexxCode::setSecurityManager().
The documentation for this class was generated from the following files:
BaseCode.hpp
BaseCode.cpp