ooRexx: QueueClass Class Reference
QueueClass Class Reference
#include <QueueClass.hpp>
Public Member Functions
void * operator new (size_t, size_t=DefaultArraySize, size_t=DefaultArraySize)
QueueClass ()
QueueClass (RESTORETYPE restoreType)
RexxString * primitiveMakeString () override
RexxString * makeString () override
bool validateIndex (RexxObject **index, size_t indexCount, size_t argPosition, size_t boundsError, size_t &position) override
void checkInsertIndex (size_t position) override
RexxObject * pullRexx ()
RexxObject * pushRexx (RexxObject *item)
RexxObject * queueRexx (RexxObject *item)
RexxInternalObject * peek ()
RexxObject * putRexx (RexxObject *value, RexxObject *index)
RexxObject * deleteRexx (RexxObject *index)
RexxObject * initRexx (RexxObject *initialSize)
RexxInternalObject * pop ()
RexxInternalObject * pull ()
void push (RexxInternalObject *obj)
void queue (RexxInternalObject *obj)
RexxInternalObject * remove (size_t index) override
RexxObject * newRexx (RexxObject **init_args, size_t argCount)
QueueClass * ofRexx (RexxObject **args, size_t argCount)
Public Member Functions inherited from ArrayClass
void * operator new (size_t, size_t=DefaultArraySize, size_t=DefaultArraySize)
void operator delete (void *)
ArrayClass (RESTORETYPE restoreType)
ArrayClass ()
ArrayClass (RexxInternalObject *o1)
ArrayClass (RexxInternalObject *o1, RexxInternalObject *o2)
ArrayClass (RexxInternalObject *o1, RexxInternalObject *o2, RexxInternalObject *o3)
ArrayClass (RexxInternalObject *o1, RexxInternalObject *o2, RexxInternalObject *o3, RexxInternalObject *o4)
ArrayClass (RexxInternalObject **o, size_t c)
ArrayClass (NumberArray *d)
~ArrayClass ()
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
ArrayClass * makeArray () override
ArrayClass * allItems ()
ArrayClass * allIndexes ()
RexxString * toString (RexxString *, RexxString *)
RexxInternalObject * getRexx (RexxObject **, size_t)
RexxInternalObject * safeGet (size_t pos)
void put (RexxInternalObject *eref, size_t pos)
RexxObject * putRexx (RexxObject **, size_t)
void putApi (RexxInternalObject *eref, size_t pos)
RexxInternalObject * removeRexx (RexxObject **, size_t)
RexxInternalObject * removeItem (RexxInternalObject *target)
RexxInternalObject * removeItemRexx (RexxObject *target)
RexxObject * appendRexx (RexxObject *)
size_t append (RexxInternalObject *)
void appendAll (ArrayClass *)
void setExpansion (RexxObject *expansion)
RexxInteger * available (size_t position)
bool validateIndex (RexxObject *i, size_t start, size_t flags, size_t &p)
bool validateSingleDimensionIndex (RexxObject **index, size_t indexCount, size_t argPosition, size_t boundsError, size_t &position)
bool validateMultiDimensionIndex (RexxObject **index, size_t indexCount, size_t argPosition, size_t boundsError, size_t &position)
ArrayClass * allocateArrayOfClass (size_t size)
RexxInteger * sizeRexx ()
RexxObject * firstRexx ()
RexxObject * lastRexx ()
RexxInternalObject * getFirstItem ()
RexxInternalObject * getLastItem ()
size_t lastIndex ()
size_t firstIndex ()
size_t nextIndex (size_t index)
RexxObject * nextRexx (RexxObject **, size_t)
size_t previousIndex (size_t index)
RexxObject * previousRexx (RexxObject **, size_t)
ArrayClass * section (size_t, size_t)
ArrayClass * sectionRexx (RexxObject *, RexxObject *)
RexxObject * hasIndexRexx (RexxObject **, size_t)
size_t items ()
RexxObject * itemsRexx ()
RexxObject * dimensionRexx (RexxObject *)
ArrayClass * getDimensionsRexx ()
size_t getDimensions ()
size_t dimensionSize (size_t i)
SupplierClass * supplier ()
RexxObject * join (ArrayClass *)
void extend (size_t)
size_t indexOf (RexxInternalObject *)
RexxObject * indexRexx (RexxObject *target)
void extendMulti (RexxObject **, size_t, size_t)
void resize ()
void ensureSpace (size_t newSize)
bool isFixedDimension ()
RexxObject * newRexx (RexxObject **, size_t)
RexxObject * ofRexx (RexxObject **, size_t)
RexxObject * empty ()
bool isEmpty ()
RexxObject * isEmptyRexx ()
RexxObject * fillRexx (RexxObject *)
void fill (RexxInternalObject *)
RexxObject * hasItemRexx (RexxObject *)
bool hasItem (RexxInternalObject *target)
bool hasIdentityItem (RexxInternalObject *target)
wholenumber_t sortCompare (RexxObject *comparator, RexxInternalObject *left, RexxInternalObject *right)
ArrayClass * stableSortRexx ()
ArrayClass * stableSortWithRexx (RexxObject *comparator)
RexxObject * insertRexx (RexxObject *value, RexxObject *index)
size_t insert (RexxInternalObject *value, size_t index)
RexxInternalObject * deleteRexx (RexxObject *index)
RexxInternalObject * deleteItem (size_t index)
size_t addLast (RexxInternalObject *item)
size_t addFirst (RexxInternalObject *item)
RexxInternalObject * removeLast ()
RexxInternalObject * removeFirst ()
size_t insertAfter (RexxInternalObject *item, size_t index)
ArrayClass * array ()
size_t size ()
bool isOccupied (size_t pos)
bool isInbounds (size_t pos)
bool hasIndex (size_t pos)
void updateLastItem ()
void setArrayItem (size_t position, RexxInternalObject *value)
void clearArrayItem (size_t position)
void copyArrayItem (size_t position, RexxInternalObject *value)
void setOrClearArrayItem (size_t position, RexxInternalObject *value)
void zeroItem (size_t position)
void clearItem (size_t position)
void setSortItem (size_t position, RexxInternalObject *value)
void setItem (size_t position, RexxInternalObject *value)
void checkMultiDimensional (const char *methodName)
void shrink (size_t amount)
void checkSetItemCount (size_t pos)
void checkClearLastItem (size_t pos)
void checkClearItemCount (size_t pos)
void checkLastItem (size_t pos)
RexxInternalObject * get (size_t pos)
RexxInternalObject ** data ()
RexxInternalObject ** data (size_t pos)
RexxObject ** messageArgs ()
size_t messageArgCount ()
ArrayClass * getExpansion ()
size_t findSingleIndexItem (RexxInternalObject *item)
RexxObject * indexToArray (size_t idx)
RexxObject * convertIndex (size_t idx)
bool isMultiDimensional ()
bool isSingleDimensional ()
bool hasExpanded ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
HashCode hash () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from ArrayClass
static ArrayClass * allocateNewObject (size_t size, size_t items, size_t maxSize, size_t type)
static size_t validateSize (RexxObject *size, size_t position)
static ArrayClass * createMultidimensional (RexxObject **dims, size_t count, RexxClass *)
static ArrayClass * createMultidimensional (ArrayClass *dims, RexxClass *c)
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from ArrayClass
static RexxClass * classInstance = OREF_NULL
static ArrayClass * nullArray = OREF_NULL
static const size_t DefaultArraySize = 16
static const size_t MaxFixedArraySize = (Numerics::MAX_WHOLENUMBER / 10) + 1
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Additional Inherited Members
Public Types inherited from ArrayClass
enum {
RaiseBoundsInvalid = 0x00000001 , RaiseBoundsTooMany = 0x00000002 , ExtendUpper = 0x00000004 , IndexAccess = RaiseBoundsTooMany ,
IndexUpdate = IndexAccess | RaiseBoundsInvalid | ExtendUpper
}
Public Attributes inherited from ArrayClass
enum ArrayClass:: { ... } IndexFlags
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from ArrayClass
void mergeSort (BaseSortComparator &comparator, ArrayClass *working, size_t left, size_t right)
void merge (BaseSortComparator &comparator, ArrayClass *working, size_t left, size_t mid, size_t right)
size_t find (BaseSortComparator &comparator, RexxInternalObject *val, int bnd, size_t left, size_t right)
void openGap (size_t index, size_t elements)
void closeGap (size_t index, size_t elements)
RexxInternalObject ** slotAddress (size_t index)
size_t dataSize ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Static Protected Member Functions inherited from ArrayClass
static void arraycopy (ArrayClass *source, size_t start, ArrayClass *target, size_t index, size_t count)
Protected Attributes inherited from ArrayClass
size_t arraySize
size_t maximumSize
size_t lastItem
size_t itemCount
NumberArray * dimensions
ArrayClass * expansionArray
RexxInternalObject * objects [1]
Static Protected Attributes inherited from ArrayClass
static const size_t MinimumArraySize = 8
static const size_t ExpansionDoubleLimit = 2000
Detailed Description
Definition at line 49 of file QueueClass.hpp.
Constructor & Destructor Documentation
QueueClass() [1/2]
QueueClass::QueueClass () inline
Definition at line 55 of file QueueClass.hpp.
Referenced by newRexx().
QueueClass() [2/2]
QueueClass::QueueClass (RESTORETYPE restoreType) inline
Definition at line 56 of file QueueClass.hpp.
Member Function Documentation
checkInsertIndex()
void QueueClass::checkInsertIndex (size_t position) override virtual
Validate the insertion index for a queue collection. For queues, the position must be location of an existing item within the bounds of the queue, unlike an array which can insert at empty slots or beyond the existing bounds.
Parameters
position The insertion index position.
Reimplemented from ArrayClass.
Definition at line 113 of file QueueClass.cpp.
References Error_Incorrect_method_queue_index, ArrayClass::lastItem, and reportException().
Referenced by putRexx().
createInstance()
void QueueClass::createInstance () static
Create initial class object at bootstrap time.
Definition at line 59 of file QueueClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
deleteRexx()
RexxObject * QueueClass::deleteRexx (RexxObject * index)
Delete an element from the given index location, shifting the item indexes as required.
Parameters
index The target index. This can be a single number or an array containing a single number.
Returns
The object that has been deleted. Returns .nil if the target index does not exist.
Definition at line 238 of file QueueClass.cpp.
References ARG_ONE, ArrayClass::deleteItem(), ArrayClass::IndexAccess, requiredArgument(), resultOrNil(), and validateIndex().
Referenced by MemoryObject::createImage().
initRexx()
RexxObject * QueueClass::initRexx (RexxObject * initialSize)
The init method for this class. This does delayed initialization of this object until a INIT message is received during initialization.
Parameters
initialSize The initial list size (optional)
Returns
Always returns nothing
Definition at line 261 of file QueueClass.cpp.
References ARG_ONE, ArrayClass::DefaultArraySize, ArrayClass::ensureSpace(), optionalLengthArgument(), and OREF_NULL.
makeString()
RexxString * QueueClass::makeString () override virtual
Handle a string conversion REQUEST for a Queue object we need to override this because Queue doesn't define a makeString() method
Returns
Always return .nil
Reimplemented from ArrayClass.
Definition at line 343 of file QueueClass.cpp.
References TheNilObject.
newRexx()
RexxObject * QueueClass::newRexx (RexxObject ** init_args, size_t argCount)
Create an instance of a queue object from Rexx code.
Parameters
init_args The pointer to the arguments.
argCount The count of arguments.
Returns
A new instance of the queue class.
Definition at line 282 of file QueueClass.cpp.
References RexxClass::completeNewObject(), and QueueClass().
Referenced by MemoryObject::createImage(), and ofRexx().
ofRexx()
QueueClass * QueueClass::ofRexx (RexxObject ** args, size_t argCount)
Create an instance of the queue class and fill it with objects.
Parameters
args The argument pointer.
argCount The count of arguments.
Returns
An instance of the queue class populated with objects.
Definition at line 306 of file QueueClass.cpp.
References Error_Incorrect_method_noarg, newRexx(), OREF_NULL, and reportException().
Referenced by MemoryObject::createImage().
operator new()
void * QueueClass::operator new (size_t size, size_t capacity = DefaultArraySize, size_t maxSize = DefaultArraySize)
Create an instance of the Queue class.
Parameters
size The base size of the object.
Returns
An initialized queue object.
Definition at line 72 of file QueueClass.cpp.
References ArrayClass::allocateNewObject(), and T_Queue.
peek()
RexxInternalObject * QueueClass::peek ()
Return the first item of the queue without removing it.
Returns
The first object from the queue.
Definition at line 170 of file QueueClass.cpp.
References ArrayClass::getFirstItem().
Referenced by MemoryObject::createImage(), LanguageParser::topDo(), LanguageParser::topDoIsType(), LanguageParser::topDoType(), and LanguageParser::topOperator().
pop()
RexxInternalObject* QueueClass::pop () inline
Definition at line 71 of file QueueClass.hpp.
References ArrayClass::deleteItem().
Referenced by LanguageParser::parseArgArray(), LanguageParser::parseArgList(), LanguageParser::parseLogical(), LanguageParser::popNTerms(), LanguageParser::popSubTerm(), LanguageParser::popTerm(), pullRexx(), LanguageParser::requiredTerm(), RexxInstructionDrop::RexxInstructionDrop(), and RexxInstructionUse::RexxInstructionUse().
primitiveMakeString()
RexxString * QueueClass::primitiveMakeString () override virtual
Handle a string conversion REQUEST for a Queue object we need to override this because Queue doesn't define a makeString() method
Returns
Always return .nil
Reimplemented from ArrayClass.
Definition at line 331 of file QueueClass.cpp.
References TheNilObject.
pull()
RexxInternalObject* QueueClass::pull () inline
Definition at line 72 of file QueueClass.hpp.
References ArrayClass::deleteItem().
Referenced by ActivityManager::clearActivityPool(), ActivityManager::createNewActivity(), RexxInstructionSelect::matchEnd(), RexxActivation::mergeTraps(), LanguageParser::popDo(), RexxActivation::popEnvironment(), LanguageParser::popOperator(), RexxActivation::processTraps(), and InterpreterInstance::removeInactiveActivities().
pullRexx()
RexxObject * QueueClass::pullRexx ()
Pull an item off of the stack, returning .nil if no items are available
Returns
The popped item, or .nil if the queue is empty.
Definition at line 128 of file QueueClass.cpp.
References pop(), and resultOrNil().
Referenced by MemoryObject::createImage().
push()
void QueueClass::push (RexxInternalObject * obj) inline
Definition at line 73 of file QueueClass.hpp.
References ArrayClass::addFirst().
Referenced by LanguageParser::addCompound(), RexxInstructionSelect::addWhen(), LanguageParser::parseNew(), LanguageParser::pushDo(), RexxActivation::pushEnvironment(), LanguageParser::pushOperator(), pushRexx(), LanguageParser::pushSubTerm(), and LanguageParser::pushTerm().
pushRexx()
RexxObject * QueueClass::pushRexx (RexxObject * item)
Push an item on to the queue.
Parameters
item The item to add.
Returns
Returns nothing.
Definition at line 141 of file QueueClass.cpp.
References ARG_ONE, OREF_NULL, push(), and requiredArgument().
Referenced by MemoryObject::createImage().
putRexx()
RexxObject * QueueClass::putRexx (RexxObject * value, RexxObject * index)
The Rexx stub for the Queue PUT method. replaces the Array version because it has slightly different semantics for index validation. The only valid indexes are those within range and the size is not adjusted for a put out of bounds.
Parameters
arguments The array of all arguments sent to the method (variable arguments allowed here...the first argument is the item being added, all other arguments are the index).
argCount The number of arguments in the method call.
Returns
Always return nothing.
Definition at line 190 of file QueueClass.cpp.
References ARG_ONE, ARG_TWO, checkInsertIndex(), Error_Incorrect_method_index, ArrayClass::IndexAccess, OREF_NULL, ArrayClass::put(), reportException(), requiredArgument(), and validateIndex().
Referenced by MemoryObject::createImage().
queue()
void QueueClass::queue (RexxInternalObject * obj) inline
Definition at line 74 of file QueueClass.hpp.
References ArrayClass::addLast().
Referenced by LanguageParser::processVariableList(), and queueRexx().
queueRexx()
RexxObject * QueueClass::queueRexx (RexxObject * item)
Queue an item on this queue.
Parameters
item The item to add to the queue.
Returns
Returns nothing.
Definition at line 156 of file QueueClass.cpp.
References ARG_ONE, OREF_NULL, queue(), and requiredArgument().
Referenced by MemoryObject::createImage().
remove()
RexxInternalObject * QueueClass::remove (size_t index) override virtual
Remove an object from the array. This redefines remove() to be a delete operation.
Parameters
index The target index position.
Returns
The removed object, if any. Returns OREF_NULL if there is no item at that index.
Reimplemented from ArrayClass.
Definition at line 222 of file QueueClass.cpp.
References ArrayClass::deleteItem().
validateIndex()
bool QueueClass::validateIndex (RexxObject ** index, size_t indexCount, size_t argPosition, size_t boundsError, size_t & position) override virtual
Process and validate a queue index. This overrides the base array class validation to disable the multi-dimensional support. If the index is out of bounds in any dimension it will either return false or raise an error, depending on the bounds checking parameter.
Parameters
index The array of objects representing the index.
indexCount The count of index items.
argPosition The argument position (used for error reporting)
boundsError Flags indicating how bounds errors should be handled.
position The returned flattened index pointing to the actual item in the array.
Returns
true if this was a valid index (within bounds) based on the bounds checking flags.
Reimplemented from ArrayClass.
Definition at line 98 of file QueueClass.cpp.
References ArrayClass::validateSingleDimensionIndex().
Referenced by deleteRexx(), and putRexx().
Member Data Documentation
classInstance
RexxClass * QueueClass::classInstance = OREF_NULL static
Definition at line 81 of file QueueClass.hpp.
The documentation for this class was generated from the following files:
QueueClass.hpp
QueueClass.cpp