ooRexx: ConditionTrappingDispatcher Class Reference
ConditionTrappingDispatcher Class Reference
#include <ConditionTrappingDispatcher.hpp>
Public Member Functions
ConditionTrappingDispatcher (TrapInvoker &t)
virtual ~ConditionTrappingDispatcher ()
void run () override
void handleError (wholenumber_t, DirectoryClass *) override
void handleError (DirectoryClass *) override
bool trapConditions () override
bool errorOccurred ()
bool conditionOccurred ()
DirectoryClass * getCondition ()
Public Member Functions inherited from TrappingDispatcher
TrappingDispatcher ()
virtual ~TrappingDispatcher ()
void setContext (Activity *act, NativeActivation *a)
Protected Attributes
TrapInvoker & invoker
wholenumber_t errorCode
Protected Attributes inherited from TrappingDispatcher
Activity * activity
NativeActivation * activation
DirectoryClass * conditionData
Additional Inherited Members
Public Attributes inherited from TrappingDispatcher
wholenumber_t rc
Detailed Description
A generalized dispatcher that allows internal code to make a call with condition trapping.
Definition at line 70 of file ConditionTrappingDispatcher.hpp.
Constructor & Destructor Documentation
ConditionTrappingDispatcher()
ConditionTrappingDispatcher::ConditionTrappingDispatcher (TrapInvoker & t) inline
Definition at line 73 of file ConditionTrappingDispatcher.hpp.
~ConditionTrappingDispatcher()
virtual ConditionTrappingDispatcher::~ConditionTrappingDispatcher () inline virtual
Definition at line 74 of file ConditionTrappingDispatcher.hpp.
Member Function Documentation
conditionOccurred()
bool ConditionTrappingDispatcher::conditionOccurred () inline
Definition at line 82 of file ConditionTrappingDispatcher.hpp.
References TrappingDispatcher::conditionData, and OREF_NULL.
Referenced by StreamObjectInputSource::read().
errorOccurred()
bool ConditionTrappingDispatcher::errorOccurred () inline
Definition at line 81 of file ConditionTrappingDispatcher.hpp.
References errorCode.
getCondition()
DirectoryClass* ConditionTrappingDispatcher::getCondition () inline
Definition at line 83 of file ConditionTrappingDispatcher.hpp.
References TrappingDispatcher::conditionData.
handleError() [1/2]
void ConditionTrappingDispatcher::handleError (DirectoryClass * c) override virtual
handler for any error conditions. This just swallows the error.
Parameters
c The condition information for the error.
Reimplemented from TrappingDispatcher.
Definition at line 79 of file ConditionTrappingDispatcher.cpp.
References TrappingDispatcher::activation, NativeActivation::clearException(), and TrappingDispatcher::conditionData.
handleError() [2/2]
void ConditionTrappingDispatcher::handleError (wholenumber_t r, DirectoryClass * c) override virtual
handler for any error conditions. This just swallows the error.
Parameters
c The condition information for the error.
Reimplemented from TrappingDispatcher.
Definition at line 63 of file ConditionTrappingDispatcher.cpp.
References TrappingDispatcher::activation, NativeActivation::clearException(), TrappingDispatcher::conditionData, and errorCode.
Referenced by RedirectionDispatcher::handleError().
run()
void ConditionTrappingDispatcher::run () override virtual
Just invoke the supplied invoker object...this issues the method call, we handle all of the trapping
Reimplemented from TrappingDispatcher.
Definition at line 51 of file ConditionTrappingDispatcher.cpp.
References TrapInvoker::invoke(), and invoker.
trapConditions()
bool ConditionTrappingDispatcher::trapConditions () inline override virtual
Reimplemented from TrappingDispatcher.
Definition at line 79 of file ConditionTrappingDispatcher.hpp.
Member Data Documentation
errorCode
wholenumber_t ConditionTrappingDispatcher::errorCode protected
Definition at line 87 of file ConditionTrappingDispatcher.hpp.
Referenced by errorOccurred(), and handleError().
invoker
TrapInvoker& ConditionTrappingDispatcher::invoker protected
Definition at line 86 of file ConditionTrappingDispatcher.hpp.
Referenced by run().
The documentation for this class was generated from the following files:
ConditionTrappingDispatcher.hpp
ConditionTrappingDispatcher.cpp