ooRexx: Memory Class Reference
Memory Class Reference
#include <Memory.hpp>
Static Public Member Functions
static bool isObjectGrained (RexxObject *o)
static bool isGrained (void *o)
static bool isValidSize (size_t s)
static size_t roundUp (size_t n, size_t to)
static size_t roundDown (size_t n, size_t to)
static size_t roundObjectBoundary (size_t n)
static size_t roundLargeObjectAllocation (size_t n)
static size_t roundObjectResize (size_t n)
static size_t roundPageSize (size_t n)
Static Public Attributes
static const size_t DefaultOld2NewSize = 512
static const size_t DefaultGlobalReferenceSize = 64
static const size_t ObjectGrain = sizeof(void *) * 2
static const size_t LargeAllocationUnit = 128 * ObjectGrain
static const size_t VeryLargeObjectGrain = 32 * ObjectGrain
static const size_t MinimumObjectSize = 3 * ObjectGrain
static const size_t MaximumObjectSize = SIZE_MAX - ObjectGrain
static const size_t LiveStackSize = 64 * 1024
static const size_t SaveStackSize = 10
static const size_t MaxImageSize = 3000000
static const size_t PageSize = 4096
Detailed Description
Holding place for Memory-related constants and functions. Most things in here are protected, with classes that need the information defined as friends. Anything needed on a global basis is public.
Definition at line 55 of file Memory.hpp.
Member Function Documentation
isGrained()
static bool Memory::isGrained (void * o) inline static
Definition at line 60 of file Memory.hpp.
References ObjectGrain.
isObjectGrained()
static bool Memory::isObjectGrained (RexxObject * o) inline static
Definition at line 59 of file Memory.hpp.
References ObjectGrain.
Referenced by DeadObjectPool::checkObjectGrain().
isValidSize()
static bool Memory::isValidSize (size_t s) inline static
Definition at line 61 of file Memory.hpp.
References MinimumObjectSize, and ObjectGrain.
Referenced by RexxInternalObject::isValid().
roundDown()
static size_t Memory::roundDown (size_t n, size_t to) inline static
Definition at line 64 of file Memory.hpp.
roundLargeObjectAllocation()
static size_t Memory::roundLargeObjectAllocation (size_t n) inline static
Definition at line 67 of file Memory.hpp.
References LargeAllocationUnit, and roundUp().
Referenced by OldSpaceSegmentSet::allocateObject().
roundObjectBoundary()
static size_t Memory::roundObjectBoundary (size_t n) inline static
Definition at line 66 of file Memory.hpp.
References ObjectGrain, and roundUp().
Referenced by MemoryObject::MemoryObject(), MemoryObject::newObject(), MemoryObject::oldObject(), RexxBehaviour::restore(), and MemoryObject::temporaryObject().
roundObjectResize()
static size_t Memory::roundObjectResize (size_t n) inline static
Definition at line 68 of file Memory.hpp.
References ObjectGrain, and roundUp().
Referenced by MemoryObject::reSize().
roundPageSize()
static size_t Memory::roundPageSize (size_t n) inline static
Definition at line 69 of file Memory.hpp.
References PageSize, and roundUp().
roundUp()
static size_t Memory::roundUp (size_t n, size_t to) inline static
Definition at line 63 of file Memory.hpp.
Referenced by LiveStack::ensureSpace(), roundLargeObjectAllocation(), roundObjectBoundary(), roundObjectResize(), roundPageSize(), and MemorySegment::roundSegmentBoundary().
Member Data Documentation
DefaultGlobalReferenceSize
const size_t Memory::DefaultGlobalReferenceSize = 64 static
Definition at line 77 of file Memory.hpp.
Referenced by MemoryObject::initialize().
DefaultOld2NewSize
const size_t Memory::DefaultOld2NewSize = 512 static
Definition at line 73 of file Memory.hpp.
Referenced by MemoryObject::restore().
LargeAllocationUnit
const size_t Memory::LargeAllocationUnit = 128 * ObjectGrain static
Definition at line 84 of file Memory.hpp.
Referenced by LargeSegmentSet::allocateObject(), OldSpaceSegmentSet::findObject(), and roundLargeObjectAllocation().
LiveStackSize
const size_t Memory::LiveStackSize = 64 * 1024 static
Definition at line 104 of file Memory.hpp.
Referenced by LiveStack::ensureSpace(), MemoryObject::initialize(), MemoryObject::liveStackFull(), and Envelope::pack().
MaxImageSize
const size_t Memory::MaxImageSize = 3000000 static
Definition at line 109 of file Memory.hpp.
Referenced by ImageSaveMarkHandler::mark(), and MemoryObject::saveImage().
MaximumObjectSize
const size_t Memory::MaximumObjectSize = SIZE_MAX - ObjectGrain static
Definition at line 96 of file Memory.hpp.
Referenced by SegmentStats::clear(), and DeadObjectPool::findSmallestFit().
MinimumObjectSize
const size_t Memory::MinimumObjectSize = 3 * ObjectGrain static
Definition at line 92 of file Memory.hpp.
Referenced by NormalSegmentSet::allocateObject(), RexxInternalObject::dumpObject(), NormalSegmentSet::findLargeDeadObject(), isValidSize(), MemoryObject::newObject(), and MemoryObject::reSize().
ObjectGrain
const size_t Memory::ObjectGrain = sizeof(void *) * 2 static
Definition at line 81 of file Memory.hpp.
Referenced by NormalSegmentSet::deadPoolToLength(), RexxInternalObject::dumpObject(), isGrained(), isObjectGrained(), isValidSize(), NormalSegmentSet::lengthToDeadPool(), NormalSegmentSet::mapLengthToDeadPool(), roundObjectBoundary(), and roundObjectResize().
PageSize
const size_t Memory::PageSize = 4096 static
Definition at line 111 of file Memory.hpp.
Referenced by roundPageSize().
SaveStackSize
const size_t Memory::SaveStackSize = 10 static
Definition at line 107 of file Memory.hpp.
Referenced by MemoryObject::setUpMemoryTables().
VeryLargeObjectGrain
const size_t Memory::VeryLargeObjectGrain = 32 * ObjectGrain static
Definition at line 87 of file Memory.hpp.
Referenced by DeadObjectPool::findBestFit().
The documentation for this class was generated from the following file:
Memory.hpp