ooRexx: IOContext Class Reference
IOContext Class Reference
#include <CommandIOContext.hpp>
Public Member Functions
IOContext (CommandIOContext *c)
~IOContext ()
void cleanup ()
Public Attributes
CommandIOContext * context
Detailed Description
A stack-based IO context object used to ensure proper post-command cleanup .
Definition at line 93 of file CommandIOContext.hpp.
Constructor & Destructor Documentation
IOContext()
IOContext::IOContext (CommandIOContext * c) inline
Initialize a context smart pointer from an command context
Parameters
c The source context.
Definition at line 101 of file CommandIOContext.hpp.
References context.
~IOContext()
IOContext::~IOContext () inline
Destructor for an io context. performs post-command cleanup on the context
Definition at line 110 of file CommandIOContext.hpp.
References cleanup().
Member Function Documentation
cleanup()
void IOContext::cleanup () inline
Perform cleanup on our terms.
Definition at line 118 of file CommandIOContext.hpp.
References CommandIOContext::cleanup(), context, and OREF_NULL.
Referenced by ~IOContext().
Member Data Documentation
context
CommandIOContext* IOContext::context
Definition at line 128 of file CommandIOContext.hpp.
Referenced by cleanup(), and IOContext().
The documentation for this class was generated from the following file:
CommandIOContext.hpp