ooRexx: PackageManager Class Reference
PackageManager Class Reference
#include <PackageManager.hpp>
Static Public Member Functions
static void live (size_t liveMark)
static void liveGeneral (MarkReason reason)
static void initialize ()
static ArrayClass * getImageData ()
static void restore (ArrayClass *imageArray)
static void restore ()
static LibraryPackage * getLibrary (RexxString *name)
static LibraryPackage * loadLibrary (RexxString *name)
static void unload ()
static NativeMethod * resolveMethod (RexxString *packageName, RexxString *methodName)
static NativeMethod * loadMethod (RexxString *packageName, RexxString *methodName)
static RoutineClass * resolveRoutine (RexxString *function, RexxString *packageName, RexxString *procedure)
static RoutineClass * resolveRoutine (RexxString *packageName, RexxString *function)
static RoutineClass * loadRoutine (RexxString *packageName, RexxString *function)
static RoutineClass * resolveRoutine (RexxString *function)
static RoutineClass * createRegisteredRoutine (RexxString *function)
static RoutineClass * getLoadedRoutine (RexxString *function)
static PNATIVEMETHOD resolveMethodEntry (RexxString *package, RexxString *name)
static PNATIVEROUTINE resolveRoutineEntry (RexxString *package, RexxString *name)
static PREGISTEREDROUTINE resolveRegisteredRoutineEntry (RexxString *package, RexxString *name)
static void addPackageRoutine (RexxString *name, RoutineClass *func)
static void loadInternalPackage (RexxString *name, RexxPackageEntry *p)
static bool registerPackage (RexxString *name, RexxPackageEntry *p)
static RexxObject * addRegisteredRoutine (RexxString *name, RexxString *module, RexxString *proc)
static RexxObject * dropRegisteredRoutine (RexxString *name)
static RexxObject * queryRegisteredRoutine (RexxString *name)
static bool callNativeRoutine (Activity *activity, RexxString *name, RexxObject **arguments, size_t argcount, ProtectedObject &result)
static PackageClass * loadRequires (Activity *activity, RexxString *shortName, RexxString *resolvedName, Protected< PackageClass > &package)
static PackageClass * getMacroSpaceRequires (Activity *activity, RexxString *name, Protected< PackageClass > &package, RexxObject *securityManager)
static PackageClass * getRequiresFile (Activity *activity, RexxString *name, RexxObject *securityManager, Protected< PackageClass > &result)
static PackageClass * loadRequires (Activity *activity, RexxString *name, ArrayClass *data, Protected< PackageClass > &result)
static PackageClass * loadRequires (Activity *activity, RexxString *name, const char *data, size_t length, Protected< PackageClass > &result)
Protected Types
enum {
IMAGE_PACKAGES = 1 , IMAGE_PACKAGE_ROUTINES , IMAGE_REGISTERED_ROUTINES , IMAGE_REQUIRES ,
IMAGE_ARRAY_SIZE = IMAGE_REQUIRES
}
Static Protected Member Functions
static PackageClass * checkRequiresCache (RexxString *name, Protected< PackageClass > &package)
static void addToRequiresCache (RexxString *name, PackageClass *package)
Static Protected Attributes
static StringTable * imagePackages = OREF_NULL
static StringTable * imagePackageRoutines = OREF_NULL
static StringTable * imageRegisteredRoutines = OREF_NULL
static StringTable * imageLoadedRequires = OREF_NULL
static StringTable * packages = OREF_NULL
static StringTable * packageRoutines = OREF_NULL
static StringTable * registeredRoutines = OREF_NULL
static StringTable * loadedRequires = OREF_NULL
static RexxPackageEntry * rexxPackage = &rexx_package_entry
static RexxPackageEntry * rexxutilPackage = &rexxutil_package_entry
Detailed Description
Definition at line 60 of file PackageManager.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
IMAGE_PACKAGES
IMAGE_PACKAGE_ROUTINES
IMAGE_REGISTERED_ROUTINES
IMAGE_REQUIRES
IMAGE_ARRAY_SIZE
Definition at line 104 of file PackageManager.hpp.
Member Function Documentation
addPackageRoutine()
void PackageManager::addPackageRoutine (RexxString * name, RoutineClass * func) static
Add a function to the package-defined functions table.
Parameters
name The name of the function.
func
Definition at line 524 of file PackageManager.cpp.
References packageRoutines, and HashCollection::put().
Referenced by LibraryPackage::loadRoutines().
addRegisteredRoutine()
RexxObject * PackageManager::addRegisteredRoutine (RexxString * name, RexxString * module, RexxString * proc) static
Process the basics of RxFuncAdd(). This will return 0 if the function can be resolved and is callable, 1 otherwise. If the target function is not in a loadable package file, this will also do the global registration.
Parameters
name The name of the registered function.
module The name of the library containing the function.
proc The target procedure name (ignored if the target library is a self-loading one).
Returns
0 if the function registration worked and the function is callable. 1 otherwise.
Remarks
Note that we return TheFalseObject (0) if the function is resolved and callable and TheTrueObject (1) for failure. This is because RxFuncAdd() directly returns this result. RxFuncAdd() is documented to return 0 on success and 1 on failure.
Definition at line 548 of file PackageManager.cpp.
References booleanObject(), getLoadedRoutine(), OREF_NULL, resolveRoutine(), TheFalseObject, and RexxString::upper().
Referenced by BUILTIN().
addToRequiresCache()
void PackageManager::addToRequiresCache (RexxString * name, PackageClass * package) static protected
Add a package to the requires cache
Parameters
name The name of the package.
package The package we're caching
Definition at line 921 of file PackageManager.cpp.
References loadedRequires, and HashCollection::put().
Referenced by getMacroSpaceRequires(), getRequiresFile(), and loadRequires().
callNativeRoutine()
bool PackageManager::callNativeRoutine (Activity * activity, RexxString * name, RexxObject ** arguments, size_t argcount, ProtectedObject & result) static
Attempt to call a native code function. This will call either new-style package functions or old-style registered functions.
Parameters
activity The activity we're running under.
name The target name of the routine.
arguments The function arguments.
argcount The argument count.
result The return result.
Returns
true if we located and successfully called this function. false means the function is not located as a native function.
Definition at line 674 of file PackageManager.cpp.
References HashCollection::get(), OREF_NULL, packageRoutines, resolveRoutine(), and RexxString::upper().
Referenced by SystemInterpreter::invokeExternalFunction().
checkRequiresCache()
PackageClass * PackageManager::checkRequiresCache (RexxString * name, Protected< PackageClass > & package) static protected
Check for a package already in the requires cache.
Parameters
name The name of the target.
Returns
The PackageClass instance, if any.
Definition at line 895 of file PackageManager.cpp.
References HashCollection::get(), Protected< objType >::isNull(), loadedRequires, OREF_NULL, and HashCollection::remove().
createRegisteredRoutine()
RoutineClass * PackageManager::createRegisteredRoutine (RexxString * function) static
Create a new registered function entry and add to the function cache.
Parameters
function
Returns
Definition at line 448 of file PackageManager.cpp.
References OREF_NULL, HashCollection::put(), registeredRoutines, and RexxResolveRoutine().
Referenced by resolveRoutine().
dropRegisteredRoutine()
RexxObject * PackageManager::dropRegisteredRoutine (RexxString * name) static
Drop a registered function.
Parameters
name Name of the registered function.
Returns
True if this was deregistered from the global table, false otherwise.
Definition at line 586 of file PackageManager.cpp.
References booleanObject(), RexxString::getStringData(), registeredRoutines, HashCollection::remove(), RexxDeregisterFunction(), and RexxString::upper().
Referenced by BUILTIN().
getImageData()
ArrayClass * PackageManager::getImageData () static
Return the information that needs to be saved in the saved image.
Returns
An array of the items added to the saved image.
Definition at line 98 of file PackageManager.cpp.
References IMAGE_ARRAY_SIZE, IMAGE_PACKAGE_ROUTINES, IMAGE_PACKAGES, IMAGE_REGISTERED_ROUTINES, IMAGE_REQUIRES, loadedRequires, new_array(), packageRoutines, packages, ArrayClass::put(), and registeredRoutines.
Referenced by MemoryObject::saveImage().
getLibrary()
LibraryPackage * PackageManager::getLibrary (RexxString * name) static
Resolve a named package, dynamically loading the package if not already in the table.
Parameters
name The name of the library associated with this package.
Returns
A resolved package...throws an exception if the package is not loadable.
Definition at line 206 of file PackageManager.cpp.
References Error_Execution_library, and reportException().
Referenced by RexxActivation::loadLibrary(), and InterpreterInstance::processOptions().
getLoadedRoutine()
RoutineClass * PackageManager::getLoadedRoutine (RexxString * function) static
Locate an already loaded function.
Parameters
function The function name.
Returns
A function activator for this function, if it can be resolved.
Definition at line 424 of file PackageManager.cpp.
References HashCollection::get(), OREF_NULL, packageRoutines, and registeredRoutines.
Referenced by addRegisteredRoutine(), queryRegisteredRoutine(), and resolveRoutine().
getMacroSpaceRequires()
PackageClass * PackageManager::getMacroSpaceRequires (Activity * activity, RexxString * name, Protected< PackageClass > & package, RexxObject * securityManager) static
Retrieve a ::REQUIRES file from the macrospace.
Parameters
activity The current activity.
name The target name.
result The returned Routine object for the package.
securityManager A security manager to associated with the package.
Returns
The located ::REQUIRES file.
Definition at line 798 of file PackageManager.cpp.
References addToRequiresCache(), RexxActivation::getMacroCode(), and OREF_NULL.
Referenced by loadRequires().
getRequiresFile()
PackageClass * PackageManager::getRequiresFile (Activity * activity, RexxString * name, RexxObject * securityManager, Protected< PackageClass > & package) static
Retrieve a file version of a ::REQUIRES file.
Parameters
activity The current activity.
name The fully resolved file name.
result The return routine object.
Returns
The loaded Package instance.
Definition at line 824 of file PackageManager.cpp.
References addToRequiresCache(), and OREF_NULL.
Referenced by loadRequires().
initialize()
void PackageManager::initialize () static
Initialize the package manager global state.
Definition at line 79 of file PackageManager.cpp.
References loadedRequires, loadInternalPackage(), new_string_table(), packageRoutines, packages, registeredRoutines, rexxPackage, and rexxutilPackage.
Referenced by MemoryObject::createImage().
live()
void PackageManager::live (size_t liveMark) static
Normal live marking.
Definition at line 169 of file PackageManager.cpp.
References loadedRequires, memory_mark, packageRoutines, packages, and registeredRoutines.
Referenced by MemoryObject::live().
liveGeneral()
void PackageManager::liveGeneral (MarkReason reason) static
Generalized live marking.
Definition at line 188 of file PackageManager.cpp.
References loadedRequires, memory_mark_general, packageRoutines, packages, and registeredRoutines.
Referenced by MemoryObject::liveGeneral().
loadInternalPackage()
void PackageManager::loadInternalPackage (RexxString * name, RexxPackageEntry * p) static
Load an internal package into our list. This does not load a library, but links package routines ones already contained inside the interpreter.
Parameters
name Name of the package...this is probably "REXX" or "REXXUTIL".
p The package descriptor with the method and function list.
Definition at line 482 of file PackageManager.cpp.
References packages, and HashCollection::put().
Referenced by initialize(), and registerPackage().
loadLibrary()
LibraryPackage * PackageManager::loadLibrary (RexxString * name) static
Attempt to load a library without raising an error. Returns a LibraryPackage object for the library if the load was successful.
Parameters
name The target library name.
Returns
A LibraryPackage object for the library, or OREF_NULL if was not resolvable.
Definition at line 229 of file PackageManager.cpp.
References OREF_NULL, packages, HashCollection::put(), and HashCollection::remove().
Referenced by LoadLibraryPackage().
loadMethod()
NativeMethod * PackageManager::loadMethod (RexxString * packageName, RexxString * methodName) static
Quietly create a Native method from a registered package.
Parameters
packageName The name of the package the library is loaded from.
methodName The name of the procedure to resolve from the package.
Returns
A Native method that represents this package entry. Returns NULL if not found.
Definition at line 284 of file PackageManager.cpp.
References OREF_NULL.
Referenced by MethodClass::loadExternalMethod().
loadRequires() [1/3]
PackageClass * PackageManager::loadRequires (Activity * activity, RexxString * name, ArrayClass * data, Protected< PackageClass > & package) static
Loade a requires file from an array source. NOTE: This is not cached like the other requires files, nor is it loaded from the cache.
Parameters
activity The current activity.
name The package name
result The returned package object.
Returns
The returned package instance.
Definition at line 852 of file PackageManager.cpp.
loadRequires() [2/3]
PackageClass * PackageManager::loadRequires (Activity * activity, RexxString * name, const char * data, size_t length, Protected< PackageClass > & package) static
Loade a requires file from an in-store source. NOTE: This is not cached like the other requires files
Parameters
activity The current activity.
name The fully resolved file name.
result The return routine object.
Returns
The returned package instance.
Definition at line 869 of file PackageManager.cpp.
References addToRequiresCache(), Protected< objType >::isNull(), and new_buffer().
loadRequires() [3/3]
PackageClass * PackageManager::loadRequires (Activity * activity, RexxString * shortName, RexxString * resolvedName, Protected< PackageClass > & package) static
Retrieve a ::REQUIRES file. This will cache the entries so that the same requires entry is returned for every request.
Parameters
activity The current activity.
shortName The short name of the package.
resolvedName The fully resolved name of a potential package file. The short name is used for checking in the MacroSpace, the long name is used for file searches.
result The return package routine.
Returns
The package routine (also returned in the result protected object).
Definition at line 716 of file PackageManager.cpp.
References SecurityManager::checkRequiresAccess(), Activity::getEffectiveSecurityManager(), getMacroSpaceRequires(), getRequiresFile(), RexxString::getStringData(), Protected< objType >::isNull(), OREF_NULL, RexxQueryMacro(), and RXMACRO_SEARCH_BEFORE.
loadRoutine()
RoutineClass * PackageManager::loadRoutine (RexxString * packageName, RexxString * function) static
Quietly load a package function. This goes explicitly to a loaded package to resolve the name rather than relying on the global cache. This will resolve to the same routine object as the global cache, but this prevents us from picking one a different one in case of a name conflict.
Parameters
packageName The package name.
function The function name.
Returns
A routine object for this function.
Definition at line 400 of file PackageManager.cpp.
References OREF_NULL.
Referenced by RoutineClass::loadExternalRoutine().
queryRegisteredRoutine()
RexxObject * PackageManager::queryRegisteredRoutine (RexxString * name) static
The query method backing RxFuncQuery(). This checks both our local tables and the global tables to see if something has been registered.
Parameters
name Target name.
Returns
True if the external function exists in our local tables or in the global registry.
Definition at line 618 of file PackageManager.cpp.
References booleanObject(), getLoadedRoutine(), RexxString::getStringData(), OREF_NULL, RexxQueryFunction(), TheFalseObject, and RexxString::upper().
Referenced by BUILTIN().
registerPackage()
bool PackageManager::registerPackage (RexxString * name, RexxPackageEntry * p) static
Register an in-process library package.
Parameters
name The name to register under.
p The package table information.
Returns
true if this was successfully registered, false if a package is already registered under the name.
Definition at line 504 of file PackageManager.cpp.
References HashCollection::get(), loadInternalPackage(), OREF_NULL, and packages.
Referenced by InterpreterInstance::processOptions(), and RegisterLibrary().
resolveMethod()
NativeMethod * PackageManager::resolveMethod (RexxString * packageName, RexxString * methodName) static
Create a Native method from a registered package.
Parameters
packageName The name of the package the library is loaded from.
methodName The name of the procedure to resolve from the package.
Returns
A Native method that represents this package entry. Returns NULL if not found.
Definition at line 262 of file PackageManager.cpp.
References LibraryPackage::resolveMethod().
Referenced by LanguageParser::createNativeMethod().
resolveMethodEntry()
PNATIVEMETHOD PackageManager::resolveMethodEntry (RexxString * packageName, RexxString * name) static
Resolve an entry point for a package method entry (used on a restore or reflatten);
Parameters
name Name of the target method.
Returns
The target entry point.
Definition at line 940 of file PackageManager.cpp.
References Error_Execution_library_method, and reportException().
Referenced by NativeMethod::run().
resolveRegisteredRoutineEntry()
PREGISTEREDROUTINE PackageManager::resolveRegisteredRoutineEntry (RexxString * packageName, RexxString * name) static
Resolve an entry point for a package function entry (used on a restore or reflatten);
Parameters
name Name of the target function.
Returns
The target entry point.
Definition at line 982 of file PackageManager.cpp.
References Error_Execution_library_routine, RexxString::getStringData(), OREF_NULL, reportException(), and RexxResolveRoutine().
Referenced by RegisteredRoutine::call().
resolveRoutine() [1/3]
RoutineClass * PackageManager::resolveRoutine (RexxString * function) static
Resolve a registered function.
Parameters
function The function name.
Returns
A function activator for this function, if it can be resolved.
Definition at line 347 of file PackageManager.cpp.
References createRegisteredRoutine(), getLoadedRoutine(), and OREF_NULL.
resolveRoutine() [2/3]
RoutineClass * PackageManager::resolveRoutine (RexxString * function, RexxString * packageName, RexxString * procedure) static
Resolve a package function activator.
Parameters
function The function name.
package The package/library name.
procedure Procedure name. Only used if directly loaded from a library file.
Returns
A function activator for this function, if it can be resolved.
Definition at line 312 of file PackageManager.cpp.
References createRegisteredRoutine(), HashCollection::get(), RexxString::getStringData(), OREF_NULL, registeredRoutines, and RexxRegisterFunctionDll().
Referenced by addRegisteredRoutine(), callNativeRoutine(), and LanguageParser::routineDirective().
resolveRoutine() [3/3]
RoutineClass * PackageManager::resolveRoutine (RexxString * packageName, RexxString * function) static
Resolve a package function. This goes explicitly to a loaded package to resolve the name rather than relying on the global cache. This will resolve to the same routine object as the global cache, but this prevents us from picking one a different one in case of a name conflict.
Parameters
packageName The package name.
function The function name.
Returns
A routine object for this function.
Definition at line 376 of file PackageManager.cpp.
References LibraryPackage::resolveRoutine().
resolveRoutineEntry()
PNATIVEROUTINE PackageManager::resolveRoutineEntry (RexxString * packageName, RexxString * name) static
Resolve an entry point for a package function entry (used on a restore or reflatten);
Parameters
name Name of the target function.
Returns
The target entry point.
Definition at line 961 of file PackageManager.cpp.
References Error_Execution_library_method, and reportException().
Referenced by NativeRoutine::call().
restore() [1/2]
void PackageManager::restore () static
Restore the saved image data to operational status
Definition at line 129 of file PackageManager.cpp.
References HashCollection::copy(), imageLoadedRequires, imagePackageRoutines, imagePackages, imageRegisteredRoutines, HashContents::TableIterator::isAvailable(), HashCollection::iterator(), loadedRequires, packageRoutines, packages, registeredRoutines, LibraryPackage::reload(), rexxPackage, and rexxutilPackage.
Referenced by MemoryObject::restore(), and MemoryObject::restoreImage().
restore() [2/2]
void PackageManager::restore (ArrayClass * imageArray) static
Restore the saved image data.
Parameters
imageArray The array we placed in the save image originally.
Definition at line 115 of file PackageManager.cpp.
References ArrayClass::get(), IMAGE_PACKAGE_ROUTINES, IMAGE_PACKAGES, IMAGE_REGISTERED_ROUTINES, IMAGE_REQUIRES, imageLoadedRequires, imagePackageRoutines, imagePackages, and imageRegisteredRoutines.
unload()
void PackageManager::unload () static
Unload all of the libraries loaded in this Rexx process.
Definition at line 642 of file PackageManager.cpp.
References HashCollection::copy(), imageLoadedRequires, imagePackageRoutines, imagePackages, imageRegisteredRoutines, HashContents::TableIterator::isAvailable(), HashCollection::iterator(), loadedRequires, packageRoutines, packages, registeredRoutines, and LibraryPackage::unload().
Referenced by Interpreter::terminateInterpreter().
Member Data Documentation
imageLoadedRequires
StringTable * PackageManager::imageLoadedRequires = OREF_NULL static protected
Definition at line 116 of file PackageManager.hpp.
Referenced by restore(), and unload().
imagePackageRoutines
StringTable * PackageManager::imagePackageRoutines = OREF_NULL static protected
Definition at line 114 of file PackageManager.hpp.
Referenced by restore(), and unload().
imagePackages
StringTable * PackageManager::imagePackages = OREF_NULL static protected
Definition at line 113 of file PackageManager.hpp.
Referenced by restore(), and unload().
imageRegisteredRoutines
StringTable * PackageManager::imageRegisteredRoutines = OREF_NULL static protected
Definition at line 115 of file PackageManager.hpp.
Referenced by restore(), and unload().
loadedRequires
StringTable * PackageManager::loadedRequires = OREF_NULL static protected
Definition at line 122 of file PackageManager.hpp.
Referenced by addToRequiresCache(), checkRequiresCache(), getImageData(), initialize(), live(), liveGeneral(), restore(), and unload().
packageRoutines
StringTable * PackageManager::packageRoutines = OREF_NULL static protected
Definition at line 120 of file PackageManager.hpp.
Referenced by addPackageRoutine(), callNativeRoutine(), getImageData(), getLoadedRoutine(), initialize(), live(), liveGeneral(), restore(), and unload().
packages
StringTable * PackageManager::packages = OREF_NULL static protected
Definition at line 119 of file PackageManager.hpp.
Referenced by getImageData(), initialize(), live(), liveGeneral(), loadInternalPackage(), loadLibrary(), registerPackage(), restore(), and unload().
registeredRoutines
StringTable * PackageManager::registeredRoutines = OREF_NULL static protected
Definition at line 121 of file PackageManager.hpp.
Referenced by createRegisteredRoutine(), dropRegisteredRoutine(), getImageData(), getLoadedRoutine(), initialize(), live(), liveGeneral(), resolveRoutine(), restore(), and unload().
rexxPackage
RexxPackageEntry * PackageManager::rexxPackage = &rexx_package_entry static protected
Definition at line 124 of file PackageManager.hpp.
Referenced by initialize(), and restore().
rexxutilPackage
RexxPackageEntry * PackageManager::rexxutilPackage = &rexxutil_package_entry static protected
Definition at line 125 of file PackageManager.hpp.
Referenced by initialize(), and restore().
The documentation for this class was generated from the following files:
PackageManager.hpp
InternalPackage.cpp
RexxUtilCommon.cpp
PackageManager.cpp