ooRexx: LargeSegmentSet Class Reference
LargeSegmentSet Class Reference
#include <MemorySegment.hpp>
Public Member Functions
LargeSegmentSet ()
LargeSegmentSet (MemoryObject *memory)
virtual ~LargeSegmentSet ()
void dumpMemoryProfile (FILE *outfile) override
RexxInternalObject * handleAllocationFailure (size_t allocationLength)
RexxInternalObject * allocateObject (size_t allocationLength)
DeadObject * donateObject (size_t allocationLength) override
void getInitialSet ()
Public Member Functions inherited from MemorySegmentSet
MemorySegmentSet (MemoryObject *memObject, SegmentSetID id, const char *setName)
MemorySegmentSet ()
virtual ~MemorySegmentSet ()
void removeSegment (MemorySegment *segment)
void removeSegmentAndStorage (MemorySegment *segment)
void add (MemorySegment *segment)
MemorySegment * first ()
MemorySegment * next (MemorySegment *segment)
void transferSegment (MemorySegment *segment)
void dumpSegments (FILE *keyfile, FILE *dumpfile)
void addSegment (MemorySegment *segment)
void sweep ()
void sweepSingleSegment (MemorySegment *sweepSegment)
bool is (SegmentSetID id)
void gatherStats (MemoryStats *memStats, SegmentStats *stats)
MemorySegment * largestActiveSegment ()
Protected Member Functions
void addDeadObject (DeadObject *object) override
void addDeadObject (char *object, size_t length) override
MemorySegment * allocateSegment (size_t requestLength, size_t minimumLength) override
size_t suggestMemoryExpansion () override
void expandSegmentSet (size_t allocationLength)
void prepareForSweep () override
void completeSweepOperation () override
Protected Member Functions inherited from MemorySegmentSet
RexxInternalObject * splitDeadObject (DeadObject *object, size_t allocationLength, size_t splitMinimum)
void insertSegment (MemorySegment *segment)
void adjustMemorySize ()
bool newSegment (size_t requestLength, size_t minimumLength)
float freeMemoryPercentage ()
size_t totalFreeMemory ()
size_t calculateSegmentAllocation (size_t n)
void addSegments (size_t requiredSpace)
void validateObject (RexxInternalObject *o)
Static Protected Attributes
static const size_t InitialLargeSegmentSpace = (LargeSegmentSize - MemorySegment::MemorySegmentOverhead)
Private Member Functions
size_t recommendedMemorySize ()
RexxInternalObject * findObject (size_t allocationLength)
Private Attributes
DeadObjectPool deadCache
size_t requests
size_t smallestObject
size_t largestObject
Static Private Attributes
static const double LargeMemoryExpansionThreshold = .40
Additional Inherited Members
Public Types inherited from MemorySegmentSet
enum SegmentSetID {
SET_UNINITIALIZED , SET_NORMAL , SET_LARGEBLOCK , SET_OLDSPACE ,
SET_SINGLEOBJECT
}
Static Public Attributes inherited from MemorySegmentSet
static const size_t MinimumSegmentSize = (MemorySegment::SegmentSize/2)
static const size_t MinimumSegmentDeadSpace = (MinimumSegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentSize = (MemorySegment::SegmentSize * 4)
static const size_t SegmentDeadSpace = (MemorySegment::SegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentDeadSpace = (LargeSegmentSize - MemorySegment::MemorySegmentOverhead)
Protected Attributes inherited from MemorySegmentSet
MemorySegment anchor
size_t count
size_t liveObjectBytes
size_t deadObjectBytes
SegmentSetID owner
const char * name
MemoryObject * memory
Detailed Description
A segment set used for allocating "larger" objects, but not necessarily the largest objects.
Definition at line 530 of file MemorySegment.hpp.
Constructor & Destructor Documentation
LargeSegmentSet() [1/2]
LargeSegmentSet::LargeSegmentSet () inline
Definition at line 535 of file MemorySegment.hpp.
LargeSegmentSet() [2/2]
LargeSegmentSet::LargeSegmentSet (MemoryObject * mem)
Constructor for the large segment pool.
Parameters
mem The hosting memory object.
Definition at line 210 of file MemorySegment.cpp.
~LargeSegmentSet()
virtual LargeSegmentSet::~LargeSegmentSet () inline virtual
Definition at line 537 of file MemorySegment.hpp.
Member Function Documentation
addDeadObject() [1/2]
void LargeSegmentSet::addDeadObject (char * object, size_t length) override protected virtual
Add a block of storage to the dead object chains
Parameters
object The pointer to the start of the object.
length The length of the object.
Reimplemented from MemorySegmentSet.
Definition at line 471 of file MemorySegment.cpp.
References DeadObjectPool::addSortedBySize(), deadCache, largestObject, and smallestObject.
addDeadObject() [2/2]
void LargeSegmentSet::addDeadObject (DeadObject * object) override protected virtual
Add a dead object to the segment set.
Parameters
object The newly swept up dead object.
Reimplemented from MemorySegmentSet.
Definition at line 383 of file MemorySegment.cpp.
References DeadObjectPool::addSortedBySize(), and deadCache.
allocateObject()
RexxInternalObject* LargeSegmentSet::allocateObject (size_t allocationLength) inline
Definition at line 541 of file MemorySegment.hpp.
References deadCache, DeadObjectPool::findBestFit(), Memory::LargeAllocationUnit, OREF_NULL, requests, and MemorySegmentSet::splitDeadObject().
Referenced by findObject(), and MemoryObject::newObject().
allocateSegment()
MemorySegment * LargeSegmentSet::allocateSegment (size_t requestLength, size_t minimumLength) override protected virtual
Allocate a segment for the larget segment set.
Parameters
requestLength The requested segment size.
minimumLength The minimum size we can take as a fallback.
Returns
The newly allocated segment or NULL if there was an allocation failure.
Reimplemented from MemorySegmentSet.
Definition at line 318 of file MemorySegment.cpp.
References MemorySegmentSet::memory, and MemoryObject::newLargeSegment().
completeSweepOperation()
void LargeSegmentSet::completeSweepOperation () override protected virtual
Handle post-sweep processing for the set.
Reimplemented from MemorySegmentSet.
Definition at line 892 of file MemorySegment.cpp.
References largestObject, line_end, MemorySegmentSet::memory, smallestObject, and MemoryObject::verboseMessage().
donateObject()
DeadObject * LargeSegmentSet::donateObject (size_t allocationLength) override virtual
Search the cache of dead objects for an object of sufficient size to fulfill this request. This just uses normal large block allocation strategy to decide on the block to donate, give a best fit for the allocation.
Parameters
allocationLength The required object size
Returns
A DeadObject of the required size.
Reimplemented from MemorySegmentSet.
Definition at line 632 of file MemorySegment.cpp.
References deadCache, and DeadObjectPool::findSmallestFit().
dumpMemoryProfile()
void LargeSegmentSet::dumpMemoryProfile (FILE * outfile) override virtual
Dump profile informaton about the large allocation segment set
Parameters
outfile The target dump file.
Reimplemented from MemorySegmentSet.
Definition at line 140 of file MemorySegment.cpp.
References deadCache, and DeadObjectPool::dumpMemoryProfile().
expandSegmentSet()
void LargeSegmentSet::expandSegmentSet (size_t allocationLength) protected
The large allocation heap only handles requests up to the size of a Normal segment. Therefore, we will always add in large segment increments. If that fails, we will try adding a segment just slightly larger than the request size.
Parameters
allocationLength The allocation size that caused the allocation failure.
Definition at line 1432 of file MemorySegment.cpp.
References MemorySegmentSet::LargeSegmentDeadSpace, line_end, MemorySegmentSet::memory, MemorySegmentSet::newSegment(), MemorySegment::roundSegmentBoundary(), and MemoryObject::verboseMessage().
Referenced by handleAllocationFailure().
findObject()
RexxInternalObject * LargeSegmentSet::findObject (size_t allocationLength) private
Locate an object is the dead object cache maintained for large object allocations.
Parameters
allocationLength The required object size.
Returns
A located object form the dead space or NULL if unable to allocate.
Definition at line 1200 of file MemorySegment.cpp.
References allocateObject().
Referenced by handleAllocationFailure().
getInitialSet()
void LargeSegmentSet::getInitialSet ()
Set up the intial normal memory allocation.
Definition at line 285 of file MemorySegment.cpp.
References InitialLargeSegmentSpace, and MemorySegmentSet::newSegment().
Referenced by MemoryObject::initialize().
handleAllocationFailure()
RexxInternalObject * LargeSegmentSet::handleAllocationFailure (size_t allocationLength)
Handle a first-attempt allocation failure from the large block segment set. This will decide whether to expand and/or perofrom a garbage collection in order to allocate a block of the requested size.
Parameters
allocationLength The size of the object that caused the original allocation failure.
Returns
An allocated object. If unable to allocate, this raised the resource exception.
Definition at line 1218 of file MemorySegment.cpp.
References MemorySegmentSet::adjustMemorySize(), MemoryObject::collect(), Error_System_resources, expandSegmentSet(), findObject(), line_end, MemorySegmentSet::memory, OREF_NULL, reportException(), requests, MemoryObject::scavengeSegmentSets(), and MemoryObject::verboseMessage().
Referenced by MemoryObject::newObject().
prepareForSweep()
void LargeSegmentSet::prepareForSweep () override protected virtual
Handle all segment set pre-sweep initialization.
Reimplemented from MemorySegmentSet.
Definition at line 831 of file MemorySegment.cpp.
References deadCache, DeadObjectPool::empty(), largestObject, MemorySegmentSet::prepareForSweep(), requests, and smallestObject.
recommendedMemorySize()
size_t LargeSegmentSet::recommendedMemorySize () inline private
Definition at line 580 of file MemorySegment.hpp.
References LargeMemoryExpansionThreshold, and MemorySegmentSet::liveObjectBytes.
Referenced by suggestMemoryExpansion().
suggestMemoryExpansion()
size_t LargeSegmentSet::suggestMemoryExpansion () override protected virtual
Decide if we should add additional segments to the normal heap based on the amount of free space we have after a garbage collection. If we're starting to run full, then we should expand the heap to prevent recycling the garbage collector to reclaim minimal amounts of storage that is immediately reused, causing another GC cycle.
Returns
A recommended expansion size.
Reimplemented from MemorySegmentSet.
Definition at line 701 of file MemorySegment.cpp.
References MemorySegmentSet::deadObjectBytes, MemorySegmentSet::freeMemoryPercentage(), LargeMemoryExpansionThreshold, line_end, MemorySegmentSet::liveObjectBytes, MemorySegmentSet::memory, recommendedMemorySize(), and MemoryObject::verboseMessage().
Member Data Documentation
deadCache
DeadObjectPool LargeSegmentSet::deadCache private
Definition at line 584 of file MemorySegment.hpp.
Referenced by addDeadObject(), allocateObject(), donateObject(), dumpMemoryProfile(), and prepareForSweep().
InitialLargeSegmentSpace
const size_t LargeSegmentSet::InitialLargeSegmentSpace = (LargeSegmentSize - MemorySegment::MemorySegmentOverhead) static protected
Definition at line 566 of file MemorySegment.hpp.
Referenced by getInitialSet().
LargeMemoryExpansionThreshold
const double LargeSegmentSet::LargeMemoryExpansionThreshold = .40 static private
Definition at line 579 of file MemorySegment.hpp.
Referenced by recommendedMemorySize(), and suggestMemoryExpansion().
largestObject
size_t LargeSegmentSet::largestObject private
Definition at line 587 of file MemorySegment.hpp.
Referenced by addDeadObject(), completeSweepOperation(), and prepareForSweep().
requests
size_t LargeSegmentSet::requests private
Definition at line 585 of file MemorySegment.hpp.
Referenced by allocateObject(), handleAllocationFailure(), and prepareForSweep().
smallestObject
size_t LargeSegmentSet::smallestObject private
Definition at line 586 of file MemorySegment.hpp.
Referenced by addDeadObject(), completeSweepOperation(), and prepareForSweep().
The documentation for this class was generated from the following files:
MemorySegment.hpp
MemorySegment.cpp