ooRexx: ArrayClass::WithSortComparator Class Reference
ArrayClass::WithSortComparator Class Reference
#include <ArrayClass.hpp>
Public Member Functions
WithSortComparator (RexxObject *c)
wholenumber_t compare (RexxInternalObject *first, RexxInternalObject *second) override
Public Member Functions inherited from ArrayClass::BaseSortComparator
BaseSortComparator ()
Protected Attributes
RexxObject * comparator
Detailed Description
Sorting comparator that uses a comparator object.
Definition at line 124 of file ArrayClass.hpp.
Constructor & Destructor Documentation
WithSortComparator()
ArrayClass::WithSortComparator::WithSortComparator (RexxObject * c) inline
Definition at line 127 of file ArrayClass.hpp.
Member Function Documentation
compare()
wholenumber_t ArrayClass::WithSortComparator::compare (RexxInternalObject * first, RexxInternalObject * second) override virtual
Reimplemented from ArrayClass::BaseSortComparator.
Definition at line 2897 of file ArrayClass.cpp.
References Numerics::DEFAULT_DIGITS, Error_Invalid_whole_number_compare, Error_No_result_object_message, ProtectedObject::isNull(), RexxInternalObject::numberValue(), reportException(), and RexxObject::sendMessage().
Member Data Documentation
comparator
RexxObject* ArrayClass::WithSortComparator::comparator protected
Definition at line 130 of file ArrayClass.hpp.
The documentation for this class was generated from the following files:
ArrayClass.hpp
ArrayClass.cpp