ooRexx: WhileUntilLoop Class Reference
WhileUntilLoop Class Reference
#include <DoBlockComponents.hpp>
Public Member Functions
WhileUntilLoop ()
void live (size_t liveMark)
void liveGeneral (MarkReason reason)
bool checkWhile (RexxActivation *context, ExpressionStack *stack)
bool checkUntil (RexxActivation *context, ExpressionStack *stack)
Public Attributes
RexxInternalObject * conditional
Detailed Description
An embedded object that can process WHILE or UNTIL loop conditionals.
Definition at line 183 of file DoBlockComponents.hpp.
Constructor & Destructor Documentation
WhileUntilLoop()
WhileUntilLoop::WhileUntilLoop () inline
Definition at line 186 of file DoBlockComponents.hpp.
Member Function Documentation
checkUntil()
bool WhileUntilLoop::checkUntil (RexxActivation * context, ExpressionStack * stack)
Evaluate a UNTIL condition, return true if the condition is true or false if it evaluates false. The meaning of these is the reverse for the UNTIL. This is optimized for the UNTIL cases.
Parameters
context The current execution context.
stack The current evaluation stack.
Returns
true if the WHILE condition passes, false if it fails.
Definition at line 302 of file DoBlockComponents.cpp.
References conditional, Error_Logical_value_until, RexxInternalObject::evaluate(), TheFalseObject, TheTrueObject, RexxActivation::traceKeywordResult(), and RexxInternalObject::truthValue().
Referenced by RexxInstructionDoOverUntil::iterate(), RexxInstructionDoOverForUntil::iterate(), RexxInstructionControlledDoUntil::iterate(), RexxInstructionDoUntil::iterate(), RexxInstructionDoCountUntil::iterate(), RexxInstructionDoWithUntil::iterate(), and RexxInstructionDoWithForUntil::iterate().
checkWhile()
bool WhileUntilLoop::checkWhile (RexxActivation * context, ExpressionStack * stack)
Evaluate a WHILE condition, return true if the condition should continue and false if the WHILE condition failed.
Parameters
context The current execution context.
stack The current evaluation stack.
Returns
true if the WHILE condition passes, false if it fails.
Definition at line 268 of file DoBlockComponents.cpp.
References conditional, Error_Logical_value_while, RexxInternalObject::evaluate(), TheFalseObject, TheTrueObject, RexxActivation::traceKeywordResult(), and RexxInternalObject::truthValue().
Referenced by RexxInstructionDoOverWhile::iterate(), RexxInstructionDoOverForWhile::iterate(), RexxInstructionControlledDoWhile::iterate(), RexxInstructionDoWhile::iterate(), RexxInstructionDoCountWhile::iterate(), RexxInstructionDoWithWhile::iterate(), and RexxInstructionDoWithForWhile::iterate().
live()
void WhileUntilLoop::live (size_t liveMark) inline
Definition at line 189 of file DoBlockComponents.hpp.
References conditional, and memory_mark.
Referenced by RexxInstructionDoOverUntil::live(), RexxInstructionDoOverForUntil::live(), RexxInstructionControlledDoUntil::live(), RexxInstructionDoWhile::live(), RexxInstructionDoCountUntil::live(), RexxInstructionDoWithUntil::live(), and RexxInstructionDoWithForUntil::live().
liveGeneral()
void WhileUntilLoop::liveGeneral (MarkReason reason) inline
Definition at line 194 of file DoBlockComponents.hpp.
References conditional, and memory_mark_general.
Referenced by RexxInstructionDoOverUntil::liveGeneral(), RexxInstructionDoOverForUntil::liveGeneral(), RexxInstructionControlledDoUntil::liveGeneral(), RexxInstructionDoWhile::liveGeneral(), RexxInstructionDoCountUntil::liveGeneral(), RexxInstructionDoWithUntil::liveGeneral(), and RexxInstructionDoWithForUntil::liveGeneral().
Member Data Documentation
conditional
RexxInternalObject* WhileUntilLoop::conditional
Definition at line 202 of file DoBlockComponents.hpp.
Referenced by checkUntil(), checkWhile(), LanguageParser::createLoop(), RexxInstructionDoOverUntil::flatten(), RexxInstructionDoOverForUntil::flatten(), RexxInstructionControlledDoUntil::flatten(), RexxInstructionDoWhile::flatten(), RexxInstructionDoCountUntil::flatten(), RexxInstructionDoWithUntil::flatten(), RexxInstructionDoWithForUntil::flatten(), live(), liveGeneral(), LanguageParser::newControlledLoop(), LanguageParser::newDoOverLoop(), LanguageParser::newDoWithLoop(), LanguageParser::parseCountLoop(), and LanguageParser::parseForeverLoop().
The documentation for this class was generated from the following files:
DoBlockComponents.hpp
DoBlockComponents.cpp