ooRexx: TranslateDispatcher Class Reference
TranslateDispatcher Class Reference
#include <TranslateDispatcher.hpp>
Public Member Functions
TranslateDispatcher ()
virtual ~TranslateDispatcher ()
void run () override
void handleError (wholenumber_t, DirectoryClass *) override
Public Member Functions inherited from ActivityDispatcher
ActivityDispatcher ()
virtual ~ActivityDispatcher ()
virtual void handleError (DirectoryClass *)
virtual void invoke ()
virtual void invoke (RexxOption *)
virtual void invoke (PRXSYSEXIT exits, const char *env)
void setContext (Activity *act, NativeActivation *a)
Public Attributes
const char * programName
PRXSTRING instore
const char * outputName
bool encode
Public Attributes inherited from ActivityDispatcher
wholenumber_t rc
DirectoryClass * conditionData
Additional Inherited Members
Protected Attributes inherited from ActivityDispatcher
Activity * activity
NativeActivation * activation
Detailed Description
Definition at line 45 of file TranslateDispatcher.hpp.
Constructor & Destructor Documentation
TranslateDispatcher()
TranslateDispatcher::TranslateDispatcher () inline
Definition at line 48 of file TranslateDispatcher.hpp.
~TranslateDispatcher()
virtual TranslateDispatcher::~TranslateDispatcher () inline virtual
Definition at line 49 of file TranslateDispatcher.hpp.
Member Function Documentation
handleError()
void TranslateDispatcher::handleError (wholenumber_t r, DirectoryClass * c) override virtual
Default handler for any error conditions. This just sets the condition information in the dispatch unit.
Parameters
c The condition information for the error.
Reimplemented from ActivityDispatcher.
Definition at line 106 of file TranslateDispatcher.cpp.
References ActivityDispatcher::activation, ActivityDispatcher::activity, ActivityDispatcher::conditionData, Activity::error(), ActivityDispatcher::handleError(), and ActivityDispatcher::rc.
run()
void TranslateDispatcher::run () override virtual
Default virtual method for handling a run() methods on an activity dispatcher.
Reimplemented from ActivityDispatcher.
Definition at line 53 of file TranslateDispatcher.cpp.
References ActivityDispatcher::activity, LanguageParser::createProgram(), encode, Error_Program_unreadable_name, Error_Program_unreadable_notfound, instore, new_string(), OREF_NULL, outputName, LanguageParser::processInstore(), programName, reportException(), RESOLVE_DEFAULT, and Activity::resolveProgramName().
Member Data Documentation
encode
bool TranslateDispatcher::encode
Definition at line 57 of file TranslateDispatcher.hpp.
Referenced by RexxCompileProgram(), RexxStart(), and run().
instore
PRXSTRING TranslateDispatcher::instore
Definition at line 55 of file TranslateDispatcher.hpp.
Referenced by RexxCompileProgram(), RexxStart(), and run().
outputName
const char* TranslateDispatcher::outputName
Definition at line 56 of file TranslateDispatcher.hpp.
Referenced by RexxCompileProgram(), RexxStart(), and run().
programName
const char* TranslateDispatcher::programName
Definition at line 54 of file TranslateDispatcher.hpp.
Referenced by RexxCompileProgram(), RexxStart(), and run().
The documentation for this class was generated from the following files:
TranslateDispatcher.hpp
TranslateDispatcher.cpp