ooRexx: UninitDispatcher Class Reference
UninitDispatcher Class Reference
#include <UninitDispatcher.hpp>
Public Member Functions
UninitDispatcher (RexxInternalObject *t)
virtual ~UninitDispatcher ()
void run () override
void handleError (wholenumber_t, DirectoryClass *) override
void handleError (DirectoryClass *) override
Public Member Functions inherited from TrappingDispatcher
TrappingDispatcher ()
virtual ~TrappingDispatcher ()
virtual bool trapConditions ()
void setContext (Activity *act, NativeActivation *a)
Protected Attributes
RexxInternalObject * target
Protected Attributes inherited from TrappingDispatcher
Activity * activity
NativeActivation * activation
DirectoryClass * conditionData
Additional Inherited Members
Public Attributes inherited from TrappingDispatcher
wholenumber_t rc
Detailed Description
Definition at line 52 of file UninitDispatcher.hpp.
Constructor & Destructor Documentation
UninitDispatcher()
UninitDispatcher::UninitDispatcher (RexxInternalObject * t) inline
Definition at line 55 of file UninitDispatcher.hpp.
~UninitDispatcher()
virtual UninitDispatcher::~UninitDispatcher () inline virtual
Definition at line 56 of file UninitDispatcher.hpp.
Member Function Documentation
handleError() [1/2]
void UninitDispatcher::handleError (DirectoryClass * c) override virtual
handler for any error conditions. This just swallows the error.
Parameters
c The condition information for the error.
Reimplemented from TrappingDispatcher.
Definition at line 77 of file UninitDispatcher.cpp.
References TrappingDispatcher::activation, and NativeActivation::clearException().
handleError() [2/2]
void UninitDispatcher::handleError (wholenumber_t r, DirectoryClass * c) override virtual
handler for any error conditions. This just swallows the error.
Parameters
c The condition information for the error.
Reimplemented from TrappingDispatcher.
Definition at line 64 of file UninitDispatcher.cpp.
References TrappingDispatcher::activation, and NativeActivation::clearException().
run()
void UninitDispatcher::run () override virtual
Just invoke the uninit method on the object with appropriate error condition handling.
Reimplemented from TrappingDispatcher.
Definition at line 52 of file UninitDispatcher.cpp.
References target, and RexxInternalObject::uninit().
Member Data Documentation
target
RexxInternalObject* UninitDispatcher::target protected
Definition at line 63 of file UninitDispatcher.hpp.
Referenced by run().
The documentation for this class was generated from the following files:
UninitDispatcher.hpp
UninitDispatcher.cpp