ooRexx: RexxString::WordIterator Class Reference
RexxString::WordIterator Class Reference
#include <StringClass.hpp>
Public Member Functions
WordIterator (const char *b, size_t l)
WordIterator (RexxString *s)
void skipBlanks (const char *&string, size_t &scanLength)
void skipNonBlanks (const char *&string, size_t &scanLength)
bool next ()
bool skipWords (size_t count)
void skipBlanks ()
bool compare (WordIterator &other)
bool caselessCompare (WordIterator &other)
size_t wordLength ()
const char * wordPointer ()
const char * wordEndPointer ()
void append (StringBuilder &builder)
void appendRemainder (StringBuilder &builder)
const char * scanPosition ()
size_t length ()
Protected Attributes
const char * currentWord
const char * nextPosition
size_t currentWordLength
size_t scanLength
Detailed Description
A class for iterating through the words of a string.
Definition at line 135 of file StringClass.hpp.
Constructor & Destructor Documentation
WordIterator() [1/2]
RexxString::WordIterator::WordIterator (const char * b, size_t l) inline
Definition at line 138 of file StringClass.hpp.
WordIterator() [2/2]
RexxString::WordIterator::WordIterator (RexxString * s) inline
Definition at line 139 of file StringClass.hpp.
Member Function Documentation
append()
void RexxString::WordIterator::append (StringBuilder & builder) inline
Definition at line 305 of file StringClass.hpp.
References RexxString::StringBuilder::append(), currentWord, and currentWordLength.
Referenced by RexxString::space().
appendRemainder()
void RexxString::WordIterator::appendRemainder (StringBuilder & builder) inline
Definition at line 306 of file StringClass.hpp.
References RexxString::StringBuilder::append(), nextPosition, and scanLength.
Referenced by RexxString::delWord().
caselessCompare()
bool RexxString::WordIterator::caselessCompare (WordIterator & other) inline
Compare the current word in two iterators.
Parameters
other The other comparison.
Returns
true if the words match, false otherwise
Definition at line 289 of file StringClass.hpp.
References StringUtil::caselessCompare(), currentWord, currentWordLength, wordLength(), and wordPointer().
Referenced by StringUtil::caselessWordPos().
compare()
bool RexxString::WordIterator::compare (WordIterator & other) inline
Compare the current word in two iterators.
Parameters
other The other comparison.
Returns
true if the words match, false otherwise
Definition at line 269 of file StringClass.hpp.
References currentWord, currentWordLength, wordLength(), and wordPointer().
Referenced by StringUtil::wordPos().
length()
size_t RexxString::WordIterator::length () inline
Definition at line 308 of file StringClass.hpp.
References scanLength.
Referenced by RexxString::delWord(), skipBlanks(), and skipNonBlanks().
next()
bool RexxString::WordIterator::next () inline
Scan forward to the next word in the string.
Returns
true if a word was found, false if we've run out out words.
Definition at line 197 of file StringClass.hpp.
References currentWord, currentWordLength, nextPosition, scanLength, skipBlanks(), and skipNonBlanks().
Referenced by StringUtil::caselessWordPos(), skipWords(), RexxString::space(), MutableBuffer::space(), StringUtil::subWords(), StringUtil::wordPos(), and StringUtil::words().
scanPosition()
const char* RexxString::WordIterator::scanPosition () inline
Definition at line 307 of file StringClass.hpp.
References nextPosition.
Referenced by MutableBuffer::delWord().
skipBlanks() [1/2]
void RexxString::WordIterator::skipBlanks () inline
Definition at line 256 of file StringClass.hpp.
References nextPosition, and scanLength.
Referenced by next().
skipBlanks() [2/2]
void RexxString::WordIterator::skipBlanks (const char *& string, size_t & scanLength) inline
Skip leading blanks in a string.
Parameters
String The target string.
scanLength The length of the string segment.
Definition at line 148 of file StringClass.hpp.
References length(), and scanLength.
Referenced by RexxString::delWord(), and MutableBuffer::delWord().
skipNonBlanks()
void RexxString::WordIterator::skipNonBlanks (const char *& string, size_t & scanLength) inline
Skip non-blank characters to the next whitespace char.
Parameters
String The source string.
scanLength The string length (update on return);
Definition at line 174 of file StringClass.hpp.
References length(), and scanLength.
Referenced by next().
skipWords()
bool RexxString::WordIterator::skipWords (size_t count) inline
Skip over a given number of words. Returns true if the count was reached before the end of the string, false if the end is reached first.
Parameters
count The count to skip.
Returns
true if count words were found.
Definition at line 241 of file StringClass.hpp.
References next().
Referenced by StringUtil::caselessWordPos(), RexxString::delWord(), MutableBuffer::delWord(), StringUtil::subWord(), StringUtil::subWords(), StringUtil::word(), StringUtil::wordIndex(), StringUtil::wordLength(), and StringUtil::wordPos().
wordEndPointer()
const char* RexxString::WordIterator::wordEndPointer () inline
Definition at line 304 of file StringClass.hpp.
References currentWord, and currentWordLength.
Referenced by StringUtil::subWord().
wordLength()
size_t RexxString::WordIterator::wordLength () inline
Definition at line 302 of file StringClass.hpp.
References currentWordLength.
Referenced by caselessCompare(), compare(), MutableBuffer::space(), StringUtil::subWords(), StringUtil::word(), StringUtil::wordLength(), and StringUtil::words().
wordPointer()
const char* RexxString::WordIterator::wordPointer () inline
Definition at line 303 of file StringClass.hpp.
References currentWord.
Referenced by caselessCompare(), compare(), RexxString::delWord(), MutableBuffer::delWord(), MutableBuffer::space(), StringUtil::subWord(), StringUtil::subWords(), StringUtil::word(), StringUtil::wordIndex(), and StringUtil::words().
Member Data Documentation
currentWord
const char* RexxString::WordIterator::currentWord protected
Definition at line 311 of file StringClass.hpp.
Referenced by append(), caselessCompare(), compare(), next(), wordEndPointer(), and wordPointer().
currentWordLength
size_t RexxString::WordIterator::currentWordLength protected
Definition at line 313 of file StringClass.hpp.
Referenced by append(), caselessCompare(), compare(), next(), wordEndPointer(), and wordLength().
nextPosition
const char* RexxString::WordIterator::nextPosition protected
Definition at line 312 of file StringClass.hpp.
Referenced by appendRemainder(), next(), scanPosition(), and skipBlanks().
scanLength
size_t RexxString::WordIterator::scanLength protected
Definition at line 314 of file StringClass.hpp.
Referenced by appendRemainder(), length(), next(), skipBlanks(), and skipNonBlanks().
The documentation for this class was generated from the following file:
StringClass.hpp