ooRexx: HashContents::TableIterator Class Reference
HashContents::TableIterator Class Reference
#include <HashContents.hpp>
Public Member Functions
TableIterator ()
~TableIterator ()
bool isAvailable ()
RexxInternalObject * value ()
RexxInternalObject * index ()
void replace (RexxInternalObject *v)
void next ()
void removeAndAdvance ()
Private Member Functions
TableIterator (HashContents *c, ItemLink p, ItemLink n)
Private Attributes
HashContents * contents
ItemLink position
ItemLink nextBucket
Friends
class HashContents
Detailed Description
an iterator for iterating over all entries of the table
Definition at line 102 of file HashContents.hpp.
Constructor & Destructor Documentation
TableIterator() [1/2]
HashContents::TableIterator::TableIterator () inline
Definition at line 107 of file HashContents.hpp.
~TableIterator()
HashContents::TableIterator::~TableIterator () inline
Definition at line 108 of file HashContents.hpp.
TableIterator() [2/2]
HashContents::TableIterator::TableIterator (HashContents * c, ItemLink p, ItemLink n) inline private
Definition at line 119 of file HashContents.hpp.
Member Function Documentation
index()
RexxInternalObject* HashContents::TableIterator::index () inline
Definition at line 112 of file HashContents.hpp.
References contents, HashContents::entryIndex(), and position.
Referenced by MethodDictionary::addInstanceMethods(), MethodDictionary::addMethods(), DirectoryClass::allItems(), RexxBehaviour::defineMethods(), DirectoryClass::getIndex(), MethodDictionary::getMethods(), RexxClass::inheritInstanceMethods(), MethodDictionary::mergeMethods(), RexxVariable::notify(), MethodDictionary::replaceMethods(), and DirectoryClass::supplier().
isAvailable()
bool HashContents::TableIterator::isAvailable () inline
Definition at line 110 of file HashContents.hpp.
References HashContents::NoMore, and position.
Referenced by MethodDictionary::addInstanceMethods(), MethodDictionary::addMethod(), MethodDictionary::addMethods(), DirectoryClass::allItems(), MemoryObject::checkUninit(), RexxActivation::closeStreams(), RexxObject::defineInstanceMethods(), RexxBehaviour::defineMethods(), MethodDictionary::findSuperMethod(), DirectoryClass::getIndex(), MethodDictionary::getMethods(), RexxClass::inheritInstanceMethods(), VariableDictionary::VariableIterator::isAvailable(), MethodDictionary::mergeMethods(), RexxVariable::notify(), Envelope::rehash(), MethodDictionary::replaceMethods(), PackageManager::restore(), MemoryObject::runUninits(), MethodDictionary::setMethodScope(), DirectoryClass::supplier(), PackageManager::unload(), and VariableDictionary::VariableIterator::VariableIterator().
next()
void HashContents::TableIterator::next () inline
Definition at line 114 of file HashContents.hpp.
References contents, HashContents::iterateNext(), nextBucket, and position.
Referenced by MethodDictionary::addInstanceMethods(), MethodDictionary::addMethod(), MethodDictionary::addMethods(), DirectoryClass::allItems(), RexxBehaviour::defineMethods(), MethodDictionary::findSuperMethod(), DirectoryClass::getIndex(), MethodDictionary::getMethods(), RexxClass::inheritInstanceMethods(), MethodDictionary::mergeMethods(), RexxVariable::notify(), Envelope::rehash(), MethodDictionary::replaceMethods(), MethodDictionary::setMethodScope(), DirectoryClass::supplier(), and VariableDictionary::VariableIterator::VariableIterator().
removeAndAdvance()
void HashContents::TableIterator::removeAndAdvance () inline
Definition at line 115 of file HashContents.hpp.
References contents, HashContents::iterateNextAndRemove(), nextBucket, and position.
replace()
void HashContents::TableIterator::replace (RexxInternalObject * v) inline
Definition at line 113 of file HashContents.hpp.
References contents, position, and HashContents::setValue().
Referenced by MethodDictionary::addMethod(), and MethodDictionary::setMethodScope().
value()
RexxInternalObject* HashContents::TableIterator::value () inline
Definition at line 111 of file HashContents.hpp.
References contents, HashContents::entryValue(), and position.
Referenced by MethodDictionary::addInstanceMethods(), MethodDictionary::addMethod(), MethodDictionary::addMethods(), DirectoryClass::allItems(), RexxBehaviour::defineMethods(), MethodDictionary::findSuperMethod(), DirectoryClass::getIndex(), MethodDictionary::getMethods(), RexxClass::inheritInstanceMethods(), MethodDictionary::mergeMethods(), Envelope::rehash(), MethodDictionary::replaceMethods(), MethodDictionary::setMethodScope(), DirectoryClass::supplier(), and VariableDictionary::VariableIterator::VariableIterator().
Friends And Related Function Documentation
HashContents
friend class HashContents friend
Definition at line 104 of file HashContents.hpp.
Member Data Documentation
contents
HashContents* HashContents::TableIterator::contents private
Definition at line 122 of file HashContents.hpp.
Referenced by index(), next(), removeAndAdvance(), replace(), and value().
nextBucket
ItemLink HashContents::TableIterator::nextBucket private
Definition at line 124 of file HashContents.hpp.
Referenced by next(), and removeAndAdvance().
position
ItemLink HashContents::TableIterator::position private
Definition at line 123 of file HashContents.hpp.
Referenced by index(), isAvailable(), next(), removeAndAdvance(), replace(), and value().
The documentation for this class was generated from the following file:
HashContents.hpp