ooRexx: ImageSaveMarkHandler Class Reference
ImageSaveMarkHandler Class Reference
#include <RexxMemory.hpp>
Public Member Functions
ImageSaveMarkHandler (MemoryObject *m, size_t mw, char *b, size_t o)
void mark (RexxInternalObject **pMarkObject, RexxInternalObject *markObject) override
Public Attributes
MemoryObject * memory
size_t markWord
char * imageBuffer
size_t imageOffset
Detailed Description
A mark handler for handling image save flattening.
Definition at line 430 of file RexxMemory.hpp.
Constructor & Destructor Documentation
ImageSaveMarkHandler()
ImageSaveMarkHandler::ImageSaveMarkHandler (MemoryObject * m, size_t mw, char * b, size_t o) inline
Definition at line 433 of file RexxMemory.hpp.
Member Function Documentation
mark()
void ImageSaveMarkHandler::mark (RexxInternalObject ** pMarkObject, RexxInternalObject * markObject) override virtual
pure virtual method for handling the mark operation during an image save.
Parameters
pMarkObject The pointer to the field being marked.
markObject The object being marked.
Reimplemented from MarkHandler.
Definition at line 1894 of file RexxMemory.cpp.
References RexxInternalObject::behaviour, RexxInternalObject::clearObjectMark(), RexxInternalObject::getObjectSize(), RexxBehaviour::getSavedPrimitiveBehaviour(), imageBuffer, imageOffset, RexxBehaviour::isNonPrimitive(), RexxInternalObject::isObjectLive(), RexxBehaviour::isTransientClass(), Interpreter::logicError(), MemoryObject::logObjectStats(), markWord, Memory::MaxImageSize, memory, MemoryObject::pushLiveStack(), RexxInternalObject::setNonPrimitive(), RexxInternalObject::setObjectLive(), and RexxInternalObject::setPrimitive().
Member Data Documentation
imageBuffer
char* ImageSaveMarkHandler::imageBuffer
Definition at line 440 of file RexxMemory.hpp.
Referenced by mark().
imageOffset
size_t ImageSaveMarkHandler::imageOffset
Definition at line 441 of file RexxMemory.hpp.
Referenced by mark(), and MemoryObject::saveImage().
markWord
size_t ImageSaveMarkHandler::markWord
Definition at line 439 of file RexxMemory.hpp.
Referenced by mark().
memory
MemoryObject* ImageSaveMarkHandler::memory
Definition at line 438 of file RexxMemory.hpp.
Referenced by mark().
The documentation for this class was generated from the following files:
RexxMemory.hpp
RexxMemory.cpp