ooRexx: WithLoop Class Reference
WithLoop Class Reference
#include <DoBlockComponents.hpp>
Public Member Functions
WithLoop ()
void live (size_t liveMark)
void liveGeneral (MarkReason reason)
void setup (RexxActivation *context, ExpressionStack *stack, DoBlock *doblock)
bool checkIteration (RexxActivation *context, ExpressionStack *stack, DoBlock *doblock, bool first)
Public Attributes
RexxVariableBase * indexVar
RexxVariableBase * itemVar
RexxInternalObject * supplierSource
Detailed Description
An embedded object that can process WITH iteration loops.
Definition at line 209 of file DoBlockComponents.hpp.
Constructor & Destructor Documentation
WithLoop()
WithLoop::WithLoop () inline
Definition at line 212 of file DoBlockComponents.hpp.
Member Function Documentation
checkIteration()
bool WithLoop::checkIteration (RexxActivation * context, ExpressionStack * stack, DoBlock * doblock, bool first)
Handle the loop iteration for a WITH loop.
Parameters
context The current execution context.
stack The evaluation stack.
doblock The do block context.
first The first iteration indicator.
Returns
true if the loop should iterate, false otherwise.
Definition at line 365 of file DoBlockComponents.cpp.
References RexxVariableBase::assign(), DoBlock::getSupplier(), indexVar, itemVar, SupplierClass::loopAvailable(), SupplierClass::loopIndex(), SupplierClass::loopItem(), SupplierClass::loopNext(), and OREF_NULL.
Referenced by RexxInstructionDoWith::iterate(), RexxInstructionDoWithFor::iterate(), RexxInstructionDoWithUntil::iterate(), RexxInstructionDoWithForUntil::iterate(), RexxInstructionDoWithWhile::iterate(), and RexxInstructionDoWithForWhile::iterate().
live()
void WithLoop::live (size_t liveMark) inline
Definition at line 215 of file DoBlockComponents.hpp.
References indexVar, itemVar, memory_mark, and supplierSource.
Referenced by RexxInstructionDoWith::live(), RexxInstructionDoWithFor::live(), RexxInstructionDoWithUntil::live(), and RexxInstructionDoWithForUntil::live().
liveGeneral()
void WithLoop::liveGeneral (MarkReason reason) inline
Definition at line 222 of file DoBlockComponents.hpp.
References indexVar, itemVar, memory_mark_general, and supplierSource.
Referenced by RexxInstructionDoWith::liveGeneral(), RexxInstructionDoWithFor::liveGeneral(), RexxInstructionDoWithUntil::liveGeneral(), and RexxInstructionDoWithForUntil::liveGeneral().
setup()
void WithLoop::setup (RexxActivation * context, ExpressionStack * stack, DoBlock * doblock)
Set up for execution of a DO WITH loop.
Parameters
context The current execution context.
stack The current evaluation stack.
doblock The context doblock useds to store loop state data.
Definition at line 332 of file DoBlockComponents.cpp.
References Error_Execution_no_supplier, RexxInternalObject::evaluate(), isOfClassType, OREF_NULL, reportException(), RexxObject::sendMessage(), DoBlock::setSupplier(), supplierSource, and RexxActivation::traceKeywordResult().
Referenced by RexxInstructionDoWith::setup(), and RexxInstructionDoWithFor::setup().
Member Data Documentation
indexVar
RexxVariableBase* WithLoop::indexVar
Definition at line 232 of file DoBlockComponents.hpp.
Referenced by checkIteration(), RexxInstructionDoWith::flatten(), RexxInstructionDoWithFor::flatten(), RexxInstructionDoWithUntil::flatten(), RexxInstructionDoWithForUntil::flatten(), live(), liveGeneral(), and LanguageParser::newDoWithLoop().
itemVar
RexxVariableBase* WithLoop::itemVar
Definition at line 233 of file DoBlockComponents.hpp.
Referenced by checkIteration(), RexxInstructionDoWith::flatten(), RexxInstructionDoWithFor::flatten(), RexxInstructionDoWithUntil::flatten(), RexxInstructionDoWithForUntil::flatten(), live(), liveGeneral(), and LanguageParser::newDoWithLoop().
supplierSource
RexxInternalObject* WithLoop::supplierSource
Definition at line 235 of file DoBlockComponents.hpp.
Referenced by RexxInstructionDoWith::flatten(), RexxInstructionDoWithFor::flatten(), RexxInstructionDoWithUntil::flatten(), RexxInstructionDoWithForUntil::flatten(), live(), liveGeneral(), LanguageParser::newDoWithLoop(), and setup().
The documentation for this class was generated from the following files:
DoBlockComponents.hpp
DoBlockComponents.cpp