ooRexx: ManagedRxstring Class Reference
ManagedRxstring Class Reference
#include <Rxstring.hpp>
Public Member Functions
ManagedRxstring ()
ManagedRxstring (size_t size)
~ManagedRxstring ()
void setStringSize (size_t size)
void ensureCapacity (size_t size)
char * allocateResult (size_t size)
Additional Inherited Members
Public Attributes inherited from Rxstring
size_t strlength
char * strptr
Detailed Description
Definition at line 53 of file Rxstring.hpp.
Constructor & Destructor Documentation
ManagedRxstring() [1/2]
ManagedRxstring::ManagedRxstring () inline
Definition at line 56 of file Rxstring.hpp.
References Rxstring::strlength, and Rxstring::strptr.
ManagedRxstring() [2/2]
ManagedRxstring::ManagedRxstring (size_t size) inline
Definition at line 62 of file Rxstring.hpp.
References setStringSize().
~ManagedRxstring()
ManagedRxstring::~ManagedRxstring () inline
Definition at line 67 of file Rxstring.hpp.
References SysAPIManager::releaseMemory(), and Rxstring::strptr.
Member Function Documentation
allocateResult()
char* ManagedRxstring::allocateResult (size_t size) inline
Definition at line 95 of file Rxstring.hpp.
References SysAPIManager::allocateMemory(), MEMORY_ERROR, and Rxstring::strptr.
Referenced by setStringSize().
ensureCapacity()
void ManagedRxstring::ensureCapacity (size_t size) inline
Definition at line 82 of file Rxstring.hpp.
References SysAPIManager::releaseMemory(), setStringSize(), Rxstring::strlength, and Rxstring::strptr.
Referenced by MacroSpaceFile::read(), and LocalMacroSpaceManager::readRxstringFromFile().
setStringSize()
void ManagedRxstring::setStringSize (size_t size) inline
Definition at line 75 of file Rxstring.hpp.
References allocateResult(), and Rxstring::strlength.
Referenced by ensureCapacity(), and ManagedRxstring().
The documentation for this class was generated from the following file:
Rxstring.hpp