ooRexx: StringUtil Class Reference
StringUtil Class Reference
#include <StringUtil.hpp>
Static Public Member Functions
static RexxString * substr (const char *, size_t, RexxInteger *, RexxInteger *, RexxString *)
static RexxString * substr (const char *, size_t, RexxInteger *, RexxInteger *)
static RexxInteger * posRexx (const char *stringData, size_t length, RexxString *needle, RexxInteger *pstart, RexxInteger *range)
static RexxObject * containsRexx (const char *stringData, size_t length, RexxString *needle, RexxInteger *pstart, RexxInteger *range)
static size_t pos (const char *stringData, size_t haystack_length, RexxString *needle, size_t _start, size_t _range)
static size_t caselessPos (const char *stringData, size_t haystack_length, RexxString *needle, size_t _start, size_t _range)
static RexxInteger * lastPosRexx (const char *stringData, size_t haystackLen, RexxString *needle, RexxInteger *_start, RexxInteger *_range)
static size_t lastPos (const char *stringData, size_t hastackLen, RexxString *needle, size_t _start, size_t _range)
static const char * lastPos (const char *needle, size_t needleLen, const char *haystack, size_t haystackLen)
static RexxString * subchar (const char *stringData, size_t stringLength, RexxInteger *positionArg)
static ArrayClass * makearray (const char *start, size_t length, RexxString *separator)
static size_t caselessLastPos (const char *stringData, size_t hastackLen, RexxString *needle, size_t _start, size_t range)
static const char * caselessLastPos (const char *needle, size_t needleLen, const char *haystack, size_t haystackLen)
static int caselessCompare (const char *, const char *, size_t)
static char packByte (const char *String)
static void unpackNibble (int Val, char *p)
static char packNibble (const char *String)
static RexxString * packHex (const char *String, size_t StringLength)
static size_t copyGroupedChars (char *destination, const char *source, size_t length, size_t count, char set[256], size_t &scannedSize)
static size_t validateGroupedSet (const char *string, size_t length, char set[256], int modulus, bool hex)
static bool validateGroupedSetQuiet (const char *string, size_t length, char set[256], int modulus, size_t &packedSize)
static const char * validateStrictSet (const char *string, char set[256], size_t length)
static RexxObject * dataType (RexxString *String, char Option)
static size_t wordCount (const char *String, size_t StringLength)
static size_t countStr (const char *hayStack, size_t hayStackLength, RexxString *needle, size_t maxCount)
static size_t caselessCountStr (const char *hayStack, size_t hayStackLength, RexxString *needle, size_t maxCount)
static size_t memPos (const char *string, size_t length, char target)
static RexxInteger * verify (const char *data, size_t stringLen, RexxString *ref, RexxString *option, RexxInteger *_start, RexxInteger *range)
static RexxString * subWord (const char *data, size_t length, RexxInteger *position, RexxInteger *plength)
static ArrayClass * subWords (const char *data, size_t length, RexxInteger *position, RexxInteger *plength)
static RexxString * word (const char *data, size_t length, RexxInteger *position)
static RexxInteger * wordIndex (const char *data, size_t length, RexxInteger *position)
static RexxInteger * wordLength (const char *data, size_t length, RexxInteger *position)
static size_t wordPos (const char *data, size_t length, RexxString *phrase, RexxInteger *pstart)
static size_t caselessWordPos (const char *data, size_t length, RexxString *phrase, RexxInteger *pstart)
static ArrayClass * words (const char *data, size_t length)
static const char * locateSeparator (const char *start, const char *end, const char *sepData, size_t sepLength)
static bool decodeBase64 (const char *source, size_t inputLength, char *destination, size_t &outputLength)
static void encodeBase64 (const char *source, size_t inputLength, MutableBuffer *destination, size_t chunkSize)
static bool matchCharacter (char ch, const char *charSet, size_t len)
Detailed Description
Definition at line 54 of file StringUtil.hpp.
Member Function Documentation
caselessCompare()
int StringUtil::caselessCompare (const char * string1, const char * string2, size_t length) static
Perform a caseless comparison of two strings
Parameters
string1 The first string to compare.
string2 The second string.
length The length to compare.
Returns
0 if the two strings are equal, -1 if the first is less than the second, and 1 if the first string is the greater.
Definition at line 654 of file StringUtil.cpp.
References Utilities::toUpper().
Referenced by RexxString::caselessAbbrev(), RexxString::WordIterator::caselessCompare(), caselessLastPos(), caselessPos(), RexxString::primitiveCaselessCompareTo(), RexxString::primitiveCaselessIsEqual(), MutableBuffer::primitiveCaselessMatch(), RexxString::primitiveCaselessMatch(), RexxStart(), and RexxString::sortCaselessCompare().
caselessCountStr()
size_t StringUtil::caselessCountStr (const char * hayStack, size_t hayStackLength, RexxString * needle, size_t maxCount) static
Count the (caseless) occurences of a string within another string.
Parameters
hayStack Pointer to the haystack data.
hayStackLength Length of the haystack data.
needle The needle we're searching for
maxCount The maximum number of occurences to search for.
Returns
The count of needle occurrences located in the string.
Definition at line 1220 of file StringUtil.cpp.
References caselessPos(), and RexxString::getLength().
Referenced by RexxString::caselessChangeStr(), MutableBuffer::caselessChangeStr(), RexxString::caselessCountStrRexx(), and MutableBuffer::caselessCountStrRexx().
caselessLastPos() [1/2]
const char * StringUtil::caselessLastPos (const char * needle, size_t needleLen, const char * haystack, size_t haystackLen) static
Absolutely most primitive version of a caseless lastpos search. This version searches directly in a buffer rather than a Rexx String.
Parameters
needle Pointer to the needle string.
needleLen Length of the needle string.
haystack The pointer to the haystack string.
haystackLen The length of the haystack string.
Returns
A pointer to the match location or NULL if there is no match.
Definition at line 455 of file StringUtil.cpp.
References caselessCompare().
caselessLastPos() [2/2]
size_t StringUtil::caselessLastPos (const char * stringData, size_t haystackLen, RexxString * needle, size_t _start, size_t range) static
Primitive level caseless lastpos search within a string buffer.
Parameters
stringData The maystack buffer.
haystack_length The length of the haystack.
needle The search needle.
_start The starting position.
Returns
The offset of the located needle, or 0 if the needle doesn't exist.
Definition at line 418 of file StringUtil.cpp.
References RexxString::getLength(), and RexxString::getStringData().
Referenced by MutableBuffer::caselessLastPos(), RexxString::caselessLastPos(), and RexxString::caselessLastPosRexx().
caselessPos()
size_t StringUtil::caselessPos (const char * stringData, size_t haystack_length, RexxString * needle, size_t _start, size_t _range) static
Primitive level search within a string buffer.
Parameters
stringData The haystack buffer.
haystack_length The length of the haystack.
needle The search needle.
_start The starting offset (i.e. 0 means first byte).
_range The number of bytes to search (counting from _start).
Returns
The position of the located needle, or 0 if the needle doesn't exist.
Definition at line 268 of file StringUtil.cpp.
References caselessCompare(), RexxString::getLength(), and RexxString::getStringData().
Referenced by MutableBuffer::caselessChangeStr(), RexxString::caselessContains(), MutableBuffer::caselessContains(), caselessCountStr(), RexxString::caselessPos(), MutableBuffer::caselessPos(), and RexxString::caselessPosRexx().
caselessWordPos()
size_t StringUtil::caselessWordPos (const char * data, size_t length, RexxString * phrase, RexxInteger * pstart) static
Execute a caseless wordpos search on a buffer of data.
Parameters
data the source data buffer.
length the length of the buffer
phrase the search phrase.
pstart the starting position.
Returns
the location of the start of the search phrase.
Definition at line 1651 of file StringUtil.cpp.
References ARG_ONE, ARG_TWO, RexxString::WordIterator::caselessCompare(), RexxString::getLength(), RexxString::getStringData(), RexxString::WordIterator::next(), optionalPositionArgument(), RexxString::WordIterator::skipWords(), stringArgument(), and wordCount().
Referenced by MutableBuffer::caselessContainsWord(), RexxString::caselessContainsWord(), MutableBuffer::caselessWordPos(), and RexxString::caselessWordPos().
containsRexx()
RexxObject * StringUtil::containsRexx (const char * stringData, size_t length, RexxString * needle, RexxInteger * pstart, RexxInteger * range) static
Locate a string within the designated string buffer.
Parameters
stringData The stringData to search within.
length The length of the string data.
needle The needle to search for.
pstart The starting position.
range The length of the string to search within.
Returns
.true if the string is found, .false otherwise.
Definition at line 162 of file StringUtil.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, booleanObject(), optionalLengthArgument(), optionalPositionArgument(), pos(), and stringArgument().
Referenced by RexxString::containsRexx(), and MutableBuffer::containsRexx().
copyGroupedChars()
size_t StringUtil::copyGroupedChars (char * destination, const char * source, size_t length, size_t count, char set[256], size_t & scannedSize) static
Copy at most count characters from set from source to destination.
Parameters
destination The string where the characters are packed.
source The source for the string data.
length The length of the input string.
count The number of valid characters in the string.
set The mapped set of allowed characters.
scannedSize The returned scan size.
Returns
number of characters copied
Definition at line 827 of file StringUtil.cpp.
Referenced by RexxString::b2x(), and packHex().
countStr()
size_t StringUtil::countStr (const char * hayStack, size_t hayStackLength, RexxString * needle, size_t maxCount) static
Count the occurences of a string within another string.
Parameters
hayStack Pointer to the haystack data.
hayStackLength Length of the haystack data.
needle The needle we're searching for
maxCount The maximum number of occurences to search for.
Returns
The count of needle occurrences located in the string.
Definition at line 1180 of file StringUtil.cpp.
References RexxString::getLength(), and pos().
Referenced by RexxString::changeStr(), MutableBuffer::changeStr(), RexxString::countStrRexx(), and MutableBuffer::countStrRexx().
dataType()
RexxObject * StringUtil::dataType (RexxString * string, char option) static
Perform primitive datatype validation.
Parameters
String The target string.
Option The type of data to validate.
Returns
True if this is of the indicated type, false for any mismatch.
Definition at line 1050 of file StringUtil.cpp.
References RexxString::ALPHANUM_LOOKUP, Numerics::ARGUMENT_DIGITS, booleanObject(), RexxString::DATATYPE_9DIGITS, RexxString::DATATYPE_ALPHANUMERIC, RexxString::DATATYPE_BINARY, RexxString::DATATYPE_HEX, RexxString::DATATYPE_INTERNAL_WHOLE, RexxString::DATATYPE_LOGICAL, RexxString::DATATYPE_LOWERCASE, RexxString::DATATYPE_MIXEDCASE, RexxString::DATATYPE_NUMBER, RexxString::DATATYPE_SYMBOL, RexxString::DATATYPE_UPPERCASE, RexxString::DATATYPE_VARIABLE, RexxString::DATATYPE_WHOLE_NUMBER, RexxString::DIGITS_BIN_LOOKUP, RexxString::DIGITS_HEX_LOOKUP, Error_Incorrect_method_option, IntegerZero, NumberString::isInteger(), RexxString::isSymbol(), RexxString::LOWER_ALPHA_LOOKUP, RexxString::MIXED_ALPHA_LOOKUP, new_string(), NumberString::numberString(), RexxString::numberValue(), OREF_NULL, NumberString::plus(), reportException(), STRING_BAD_VARIABLE, STRING_COMPOUND_NAME, STRING_NAME, STRING_STEM, TheFalseObject, Utilities::toUpper(), type, RexxString::UPPER_ALPHA_LOOKUP, validateGroupedSetQuiet(), and validateStrictSet().
Referenced by RexxString::dataType().
decodeBase64()
bool StringUtil::decodeBase64 (const char * source, size_t inputLength, char * destination, size_t & outputLength) static
Reverse the effect of an encodebase64 operation, converting a string in Base64 format into a "normal" character string. This supports Base64 encoding as described by RFC 2045, but does not allow (ignore) characters outside of the base64 alphabet. See https://tools.ietf.org/html/rfc2045#page-24
Parameters
input Pointer to the data to decode
inputLength The length of the input to decode
output The output buffer (which can be the same as the input if decoding in place.
outputLength The final decoded length, which will be <= to the input length
Returns
true if this was decoded successfully, false if there were any decoding errors.
Definition at line 1743 of file StringUtil.cpp.
References RexxString::DIGITS_BASE64_LOOKUP.
Referenced by ProgramMetaData::processRestoreData().
encodeBase64()
void StringUtil::encodeBase64 (const char * source, size_t inputLength, MutableBuffer * destination, size_t chunkSize) static
Convert the character string into the same string with the characters converted into a Base64 encoding.
Parameters
data Pointer to the data to encode.
dataLength The length of the source data
output A mutable buffer into which the data are written
chunkSize The size of chunks to be used in the encoding. A line break is added after each chunk at 4-byte boundaries.
Definition at line 1886 of file StringUtil.cpp.
References MutableBuffer::append(), and RexxString::DIGITS_BASE64.
Referenced by ProgramMetaData::write().
lastPos() [1/2]
const char * StringUtil::lastPos (const char * needle, size_t needleLen, const char * haystack, size_t haystackLen) static
Absolutely most primitive version of a lastpos search. This version searches directly in a buffer rather than a Rexx String.
Parameters
needle Pointer to the needle string.
needleLen Length of the needle string.
haystack The pointer to the haystack string.
haystackLen The length of the haystack string.
Returns
A pointer to the match location or NULL if there is no match.
Definition at line 379 of file StringUtil.cpp.
lastPos() [2/2]
size_t StringUtil::lastPos (const char * stringData, size_t haystackLen, RexxString * needle, size_t _start, size_t range) static
Primitive level lastpos search within a string buffer.
Parameters
stringData The maystack buffer.
haystack_length The length of the haystack.
needle The search needle.
_start The starting position.
Returns
The offset of the located needle, or 0 if the needle doesn't exist.
Definition at line 341 of file StringUtil.cpp.
References RexxString::getLength(), and RexxString::getStringData().
Referenced by RexxString::lastPos(), and lastPosRexx().
lastPosRexx()
RexxInteger * StringUtil::lastPosRexx (const char * stringData, size_t haystackLen, RexxString * needle, RexxInteger * _start, RexxInteger * _range) static
Locate the last positon of a string within the designated string buffer.
Parameters
stringData The stringData to search within.
length The length of the string data.
needle The needle to search for.
pstart The starting position.
Returns
An integer object giving the located position.
Definition at line 318 of file StringUtil.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, lastPos(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by MutableBuffer::lastPos(), and RexxString::lastPosRexx().
locateSeparator()
const char * StringUtil::locateSeparator (const char * start, const char * end, const char * sepData, size_t sepLength) static
Search for a separator within a string segment.
Parameters
start The start position for the scan.
end The last possible position for a scan (taking the length of the separator into account).
sepData The separator data
sepLength the length of the separator.
Returns
The next match position, or null for no match.
Definition at line 519 of file StringUtil.cpp.
Referenced by makearray().
makearray()
ArrayClass * StringUtil::makearray (const char * start, size_t length, RexxString * separator) static
Carve the string buffer up into an array of string values.
Parameters
start The starting position of the buffer.
length The length of the buffer.
separator The optional separator character.
Returns
An array of all strings within the buffer, with the target delimiter removed.
Definition at line 545 of file StringUtil.cpp.
References ARG_ONE, RexxString::getLength(), RexxString::getStringData(), locateSeparator(), new_array(), new_string(), OREF_NULL, ArrayClass::put(), and stringArgument().
Referenced by RexxString::makeArrayRexx(), and MutableBuffer::makeArrayRexx().
matchCharacter()
static bool StringUtil::matchCharacter (char ch, const char * charSet, size_t len) inline static
Definition at line 98 of file StringUtil.hpp.
Referenced by RexxString::strip(), and verify().
memPos()
size_t StringUtil::memPos (const char * string, size_t length, char target) static
Locate the first occurrence of a character in a string.
Parameters
string The search string.
length The length of the search string.
target The target character.
Returns
The match offset, or SIZE_MAX if this is not found.
Definition at line 1258 of file StringUtil.cpp.
References SIZE_MAX.
Referenced by BUILTIN(), RexxString::translate(), and MutableBuffer::translate().
packByte()
char StringUtil::packByte (const char * string) static
The value of the buffer contents interpreted as the binary expansion of a byte, with most significant bit in string[0] and least significant bit in string[7].
Parameters
string The string to pack (must be 8 digits)
Returns
The single packed character.
Definition at line 687 of file StringUtil.cpp.
Referenced by packNibble().
packHex()
RexxString * StringUtil::packHex (const char * string, size_t stringLength) static
pack a string of 'hex' digits in place
take two alpha chars and make into one byte
Parameters
String The string to pack
StringLength The length of the string.
Returns
The resulting packed string.
Definition at line 868 of file StringUtil.cpp.
References copyGroupedChars(), RexxString::DIGITS_HEX_LOOKUP, RexxString::getWritableData(), RexxString::packByte2(), raw_string(), and validateGroupedSet().
Referenced by NumberString::d2xD2c(), RexxString::x2c(), and RexxString::x2dC2d().
packNibble()
char StringUtil::packNibble (const char * string) static
The value of the buffer contents interpreted as the binary expansion of a byte, with most significant bit in string[0] and least significant bit in string[7].
Parameters
string Pack 4 characters into a hex string value.
Returns
The hex character representing the nibble value.
Definition at line 713 of file StringUtil.cpp.
References packByte().
Referenced by RexxString::b2x().
pos()
size_t StringUtil::pos (const char * stringData, size_t haystack_length, RexxString * needle, size_t _start, size_t _range) static
Primitive level search within a string buffer.
Parameters
stringData The haystack buffer.
haystack_length The length of the haystack.
needle The search needle.
_start The starting offset (i.e. 0 means first byte).
_range The number of bytes to search (counting from _start).
Returns
The position of the located needle, or 0 if the needle doesn't exist.
Definition at line 206 of file StringUtil.cpp.
References RexxString::getLength(), and RexxString::getStringData().
Referenced by MutableBuffer::changeStr(), containsRexx(), countStr(), RexxString::pos(), and posRexx().
posRexx()
RexxInteger * StringUtil::posRexx (const char * stringData, size_t length, RexxString * needle, RexxInteger * pstart, RexxInteger * range) static
Test if a given string contains the designated substring
Parameters
stringData The stringData to search within.
length The length of the string data.
needle The needle to search for.
pstart The starting position.
range The length of the string to search within.
Returns
An integer object giving the located position.
Definition at line 184 of file StringUtil.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, new_integer(), optionalLengthArgument(), optionalPositionArgument(), pos(), and stringArgument().
Referenced by RexxString::posRexx(), and MutableBuffer::posRexx().
subchar()
RexxString * StringUtil::subchar (const char * stringData, size_t stringLength, RexxInteger * positionArg) static
Extract an individual character from a string buffer, returned as a string object.
Parameters
stringData The string buffer.
stringLength The length of the buffer.
positionArg The target position.
Returns
The target character, as a string value.
Definition at line 494 of file StringUtil.cpp.
References ARG_ONE, new_string(), and positionArgument().
Referenced by RexxString::subchar(), and MutableBuffer::subchar().
substr() [1/2]
RexxString * StringUtil::substr (const char * string, size_t stringLength, RexxInteger * _position, RexxInteger * _length) static
Extract a substring from a data buffer, using the "[]" semantics
Parameters
string The data buffer.
stringLength The length of the buffer.
_position The position argument for the starting position.
_length The substring length argument.
Returns
The extracted substring.
Definition at line 128 of file StringUtil.cpp.
References ARG_ONE, ARG_TWO, new_string(), optionalLengthArgument(), and positionArgument().
substr() [2/2]
RexxString * StringUtil::substr (const char * string, size_t stringLength, RexxInteger * _position, RexxInteger * _length, RexxString * pad) static
Extract a substring from a data buffer.
Parameters
string The data buffer.
stringLength The length of the buffer.
_position The position argument for the starting position.
_length The substring length argument.
pad The padding argument.
Returns
The extracted substring.
Definition at line 66 of file StringUtil.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, ARG_THREE, ARG_TWO, optionalLengthArgument(), optionalPadArgument(), RexxString::StringBuilder::pad(), positionArgument(), and raw_string().
Referenced by RexxString::brackets(), MutableBuffer::brackets(), RexxString::substr(), and MutableBuffer::substr().
subWord()
RexxString * StringUtil::subWord (const char * data, size_t length, RexxInteger * position, RexxInteger * plength) static
Do a subword operation on a buffer of data
Parameters
data The start of the data buffer.
length The length of the buffer
position The starting word position.
plength the count of words to return.
Returns
The string containing the indicated subwords.
Definition at line 1360 of file StringUtil.cpp.
References ARG_ONE, ARG_TWO, Numerics::MAX_WHOLENUMBER, new_string(), optionalLengthArgument(), positionArgument(), RexxString::WordIterator::skipWords(), RexxString::WordIterator::wordEndPointer(), RexxString::WordIterator::wordPointer(), and wordPos().
Referenced by MutableBuffer::subWord(), and RexxString::subWord().
subWords()
ArrayClass * StringUtil::subWords (const char * data, size_t length, RexxInteger * position, RexxInteger * plength) static
Do a wordList operation on a buffer of data
Parameters
data The start of the data buffer.
length The length of the buffer
position The starting word position.
plength the count of words to return.
Returns
The array containing the indicated subwords.
Definition at line 1405 of file StringUtil.cpp.
References ARG_ONE, ARG_TWO, Numerics::MAX_WHOLENUMBER, new_array(), new_string(), RexxString::WordIterator::next(), optionalLengthArgument(), optionalPositionArgument(), RexxString::WordIterator::skipWords(), RexxString::WordIterator::wordLength(), RexxString::WordIterator::wordPointer(), and wordPos().
Referenced by MutableBuffer::subWords(), and RexxString::subWords().
unpackNibble()
void StringUtil::unpackNibble (int Val, char * p) static
convert nibble to 4 '0'/'1' chars
p[0], ..., p[3]: the four '0'/'1' chars representing the nibble
No terminating null character is produced
Parameters
Val The nibble to unpack.
p The location to unpack into.
Definition at line 921 of file StringUtil.cpp.
Referenced by RexxString::x2b().
validateGroupedSet()
size_t StringUtil::validateGroupedSet (const char * string, size_t length, char set[256], int modulus, bool hex) static
Validate blocks in string
A string is considered valid if it consists of zero or more characters belonging to the character set, in groups of size modulus. The first group may have fewer than modulus characters. The groups are optionally separated by one or more whitespace chars.
Parameters
string The string to validate.
length The string length.
set The set of valid characters.
modulus The size of the smallest allowed grouping.
hex Indicates this is a hex or binary string. Used for issuing the correct error message.
Returns
The number of valid digits found.
This version raises errors for invalid characters. See also validateGroupedSetQuiet().
Definition at line 744 of file StringUtil.cpp.
References RexxString::ch_SPACE, RexxString::ch_TAB, Error_Incorrect_method_binblank, Error_Incorrect_method_hexblank, Error_Incorrect_method_invbin, Error_Incorrect_method_invbin_group, Error_Incorrect_method_invhex, Error_Incorrect_method_invhex_group, IntegerOne, new_string(), and reportException().
Referenced by RexxString::b2x(), packHex(), and RexxString::x2b().
validateGroupedSetQuiet()
bool StringUtil::validateGroupedSetQuiet (const char * string, size_t length, char set[256], int modulus, size_t & count) static
Validate blocks in string
A string is considered valid if it consists of zero or more characters belonging to the character set, in groups of size modulus. The first group may have fewer than modulus characters. The groups are optionally separated by one or more whitespace chars.
Parameters
string The string to validate.
length The string length.
set The set of valid characters.
modulus The size of the smallest allowed grouping.
count The number of valid digits found.
Returns
true for a valid string, false otherwise.
This is the "quiet" version, it does not raise errors. See also validateGroupedSet()
Definition at line 974 of file StringUtil.cpp.
References RexxString::ch_SPACE, and RexxString::ch_TAB.
Referenced by dataType().
validateStrictSet()
const char * StringUtil::validateStrictSet (const char * string, char set[256], size_t length) static
Validate that string contains characters only from given set.
Parameters
string The string to search.
set The character set.
length The length to search.
Returns
NULL if all chars match, otherwise the position of the failed match.
Definition at line 939 of file StringUtil.cpp.
Referenced by dataType().
verify()
RexxInteger * StringUtil::verify (const char * data, size_t stringLen, RexxString * ref, RexxString * option, RexxInteger * _start, RexxInteger * range) static
Perform a verify operation on a section of data.
Parameters
data The data pointer
stringLen The length of the string to match
ref The reference search string.
option The match/nomatch option.
_start The starting offset for the match.
Returns
The match/nomatch position, or 0 if nothing was found.
Definition at line 1283 of file StringUtil.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, RexxString::getLength(), RexxString::getStringData(), IntegerZero, matchCharacter(), new_integer(), optionalLengthArgument(), optionalOptionArgument(), optionalPositionArgument(), stringArgument(), RexxString::VERIFY_MATCH, and RexxString::VERIFY_NOMATCH.
Referenced by MutableBuffer::verify(), and RexxString::verify().
word()
RexxString * StringUtil::word (const char * data, size_t length, RexxInteger * position) static
Extract a word from a buffer
Parameters
data The data pointer
length the length of the data buffer.
position the target word position.
Returns
The string value of the word at the indicated position.
Definition at line 1452 of file StringUtil.cpp.
References ARG_ONE, new_string(), positionArgument(), RexxString::WordIterator::skipWords(), RexxString::WordIterator::wordLength(), RexxString::WordIterator::wordPointer(), and wordPos().
Referenced by MutableBuffer::word(), and RexxString::word().
wordCount()
size_t StringUtil::wordCount (const char * string, size_t stringLength) static
Count the number of words in a string.
Parameters
string The string to count.
stringLength The length of the string.
Returns
The count of white-space delimited words.
Definition at line 1148 of file StringUtil.cpp.
References counter().
Referenced by caselessWordPos(), wordPos(), MutableBuffer::words(), and RexxString::words().
wordIndex()
RexxInteger * StringUtil::wordIndex (const char * data, size_t length, RexxInteger * position) static
Return the index position for a given word
Parameters
data The data containing the words
length The length of the data buffer
position The target word position
Returns
The offset of the start of the indicated word.
Definition at line 1509 of file StringUtil.cpp.
References ARG_ONE, IntegerZero, new_integer(), positionArgument(), RexxString::WordIterator::skipWords(), RexxString::WordIterator::wordPointer(), and wordPos().
Referenced by MutableBuffer::wordIndex(), and RexxString::wordIndex().
wordLength()
RexxInteger * StringUtil::wordLength (const char * data, size_t length, RexxInteger * position) static
Return the length of the word located at a given index.
Parameters
data The data containing the word list.
length The length of the data buffer
position The target word position.
Returns
The length of the given word at the target index. Returns 0 if no word is found.
Definition at line 1537 of file StringUtil.cpp.
References ARG_ONE, IntegerZero, new_integer(), positionArgument(), RexxString::WordIterator::skipWords(), RexxString::WordIterator::wordLength(), and wordPos().
Referenced by MutableBuffer::wordLength(), and RexxString::wordLength().
wordPos()
size_t StringUtil::wordPos (const char * data, size_t length, RexxString * phrase, RexxInteger * pstart) static
Execute a wordpos search on a buffer of data.
Parameters
data the source data buffer.
length the length of the buffer
phrase the search phrase.
pstart the starting position.
Returns
the location of the start of the search phrase.
Definition at line 1565 of file StringUtil.cpp.
References ARG_ONE, ARG_TWO, RexxString::WordIterator::compare(), RexxString::getLength(), RexxString::getStringData(), RexxString::WordIterator::next(), optionalPositionArgument(), RexxString::WordIterator::skipWords(), stringArgument(), and wordCount().
Referenced by MutableBuffer::containsWord(), RexxString::containsWord(), subWord(), subWords(), word(), wordIndex(), wordLength(), MutableBuffer::wordPos(), and RexxString::wordPos().
words()
ArrayClass * StringUtil::words (const char * data, size_t length) static
Extract all words from a buffer
Parameters
data The data pointer
length the length of the data buffer.
position the target word position.
Returns
The string value of the word at the indicated position.
Definition at line 1483 of file StringUtil.cpp.
References new_array(), new_string(), RexxString::WordIterator::next(), RexxString::WordIterator::wordLength(), and RexxString::WordIterator::wordPointer().
Referenced by MethodClass::loadExternalMethod(), and RoutineClass::loadExternalRoutine().
The documentation for this class was generated from the following files:
StringUtil.hpp
StringUtil.cpp