ooRexx: doubleQueue Class Reference
doubleQueue Class Reference
#include <dblqueue.hpp>
Public Member Functions
doubleQueue (int n)
~doubleQueue ()
void push (int value)
void put (int value)
int pop ()
bool isEmpty ()
Private Member Functions
void enlarge ()
Private Attributes
int * memory
int size
int head
int tail
Detailed Description
Definition at line 44 of file dblqueue.hpp.
Constructor & Destructor Documentation
doubleQueue()
doubleQueue::doubleQueue (int n)
Definition at line 45 of file dblqueue.cpp.
References memory, put(), SCAN, and size.
~doubleQueue()
doubleQueue::~doubleQueue ()
Definition at line 52 of file dblqueue.cpp.
References memory.
Member Function Documentation
enlarge()
void doubleQueue::enlarge () private
Definition at line 106 of file dblqueue.cpp.
References head, memory, size, and tail.
Referenced by push(), and put().
isEmpty()
bool doubleQueue::isEmpty () inline
Definition at line 52 of file dblqueue.hpp.
References head, memory, SCAN, and tail.
Referenced by automaton::match().
pop()
int doubleQueue::pop ()
Definition at line 87 of file dblqueue.cpp.
References head, memory, and tail.
Referenced by automaton::match().
push()
void doubleQueue::push (int value)
Definition at line 62 of file dblqueue.cpp.
References enlarge(), head, and memory.
Referenced by automaton::match().
put()
void doubleQueue::put (int value)
Definition at line 74 of file dblqueue.cpp.
References enlarge(), memory, size, and tail.
Referenced by doubleQueue(), and automaton::match().
Member Data Documentation
head
int doubleQueue::head private
Definition at line 74 of file dblqueue.hpp.
Referenced by enlarge(), isEmpty(), pop(), and push().
memory
int* doubleQueue::memory private
Definition at line 72 of file dblqueue.hpp.
Referenced by doubleQueue(), enlarge(), isEmpty(), pop(), push(), put(), and ~doubleQueue().
size
int doubleQueue::size private
Definition at line 73 of file dblqueue.hpp.
Referenced by doubleQueue(), enlarge(), and put().
tail
int doubleQueue::tail private
Definition at line 75 of file dblqueue.hpp.
Referenced by enlarge(), isEmpty(), pop(), and put().
The documentation for this class was generated from the following files:
dblqueue.hpp
dblqueue.cpp