ooRexx: ActivationBase Class Reference
ActivationBase Class Reference abstract
#include <ActivationBase.hpp>
Public Types
enum GuardStatus { SCOPE_RELEASED = 0 , SCOPE_RESERVED = 1 }
Public Member Functions
ActivationBase ()
ActivationBase (RESTORETYPE restoreType)
virtual RexxObject * dispatch ()
virtual wholenumber_t digits ()
virtual wholenumber_t fuzz ()
virtual bool form ()
virtual const NumericSettings * getNumericSettings ()
virtual RexxActivation * getRexxContext ()
virtual RexxActivation * findRexxContext ()
virtual void setDigits (wholenumber_t)
virtual void setFuzz (wholenumber_t)
virtual void setForm (bool)
virtual bool trap (RexxString *, DirectoryClass *)
virtual bool willTrap (RexxString *)
virtual void setObjNotify (MessageClass *)
virtual void termination ()
virtual SecurityManager * getSecurityManager ()=0
virtual bool isForwarded ()
virtual bool isStackBase ()
virtual bool isRexxContext ()
virtual RexxObject * getReceiver ()
virtual PackageClass * getPackage ()
void setPreviousStackFrame (ActivationBase *p)
ActivationBase * getPreviousStackFrame ()
BaseExecutable * getExecutable ()
BaseExecutable * getExecutableObject ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void live (size_t)
virtual void liveGeneral (MarkReason reason)
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Protected Attributes
ActivationBase * previous
BaseExecutable * executable
GuardStatus objectScope
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Base class for the different activation types. This defines the common interface that the activation subclasses must implement.
Definition at line 61 of file ActivationBase.hpp.
Member Enumeration Documentation
GuardStatus
enum ActivationBase::GuardStatus
Enumerator
SCOPE_RELEASED
SCOPE_RESERVED
Definition at line 66 of file ActivationBase.hpp.
Constructor & Destructor Documentation
ActivationBase() [1/2]
ActivationBase::ActivationBase () inline
Definition at line 72 of file ActivationBase.hpp.
ActivationBase() [2/2]
ActivationBase::ActivationBase (RESTORETYPE restoreType) inline
Definition at line 73 of file ActivationBase.hpp.
Member Function Documentation
digits()
virtual wholenumber_t ActivationBase::digits () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 75 of file ActivationBase.hpp.
References Numerics::DEFAULT_DIGITS.
dispatch()
virtual RexxObject* ActivationBase::dispatch () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 74 of file ActivationBase.hpp.
Referenced by Activity::runThread().
findRexxContext()
virtual RexxActivation* ActivationBase::findRexxContext () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 80 of file ActivationBase.hpp.
References OREF_NULL.
Referenced by NativeActivation::findRexxContext(), and Activity::updateFrameMarkers().
form()
virtual bool ActivationBase::form () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 77 of file ActivationBase.hpp.
References Numerics::DEFAULT_FORM.
fuzz()
virtual wholenumber_t ActivationBase::fuzz () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 76 of file ActivationBase.hpp.
References Numerics::DEFAULT_FUZZ.
getExecutable()
BaseExecutable* ActivationBase::getExecutable () inline
Definition at line 97 of file ActivationBase.hpp.
References executable.
Referenced by GetCurrentMethod(), GetCurrentRoutine(), RexxContext::getExecutable(), NativeActivation::getRexxContextExecutable(), RexxActivation::RexxActivation(), and RexxActivation::traceEntryOrExit().
getExecutableObject()
BaseExecutable* ActivationBase::getExecutableObject () inline
Definition at line 98 of file ActivationBase.hpp.
References executable.
Referenced by NativeActivation::createStackFrame(), RexxActivation::createStackFrame(), RexxActivationFrame::executable(), and NativeActivationFrame::executable().
getNumericSettings()
virtual const NumericSettings* ActivationBase::getNumericSettings () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 78 of file ActivationBase.hpp.
References Numerics::getDefaultSettings().
Referenced by Activity::updateFrameMarkers().
getPackage()
virtual PackageClass* ActivationBase::getPackage () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 93 of file ActivationBase.hpp.
References OREF_NULL.
Referenced by RexxObject::checkPackage().
getPreviousStackFrame()
ActivationBase* ActivationBase::getPreviousStackFrame () inline
Definition at line 96 of file ActivationBase.hpp.
References previous.
Referenced by NativeActivation::accessCallerContext(), NativeActivation::checkConditions(), RexxActivation::getStreams(), RedirectionDispatcher::handleError(), RexxActivation::senderActivation(), RexxActivation::trap(), and RexxActivation::willTrap().
getReceiver()
virtual RexxObject* ActivationBase::getReceiver () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 92 of file ActivationBase.hpp.
References OREF_NULL.
Referenced by RexxObject::checkPrivate(), and RexxObject::checkRestrictedMethod().
getRexxContext()
virtual RexxActivation* ActivationBase::getRexxContext () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 79 of file ActivationBase.hpp.
References OREF_NULL.
getSecurityManager()
virtual SecurityManager* ActivationBase::getSecurityManager () pure virtual
Implemented in NativeActivation, and RexxActivation.
Referenced by Activity::getEffectiveSecurityManager().
isForwarded()
virtual bool ActivationBase::isForwarded () inline virtual
Reimplemented in RexxActivation.
Definition at line 89 of file ActivationBase.hpp.
Referenced by RexxActivation::trap(), and RexxActivation::willTrap().
isRexxContext()
virtual bool ActivationBase::isRexxContext () inline virtual
Reimplemented in RexxActivation.
Definition at line 91 of file ActivationBase.hpp.
Referenced by RexxActivation::getStreams().
isStackBase()
virtual bool ActivationBase::isStackBase () inline virtual
Reimplemented in NativeActivation.
Definition at line 90 of file ActivationBase.hpp.
Referenced by Activity::checkCondition(), Activity::error(), Activity::popStackFrame(), Activity::pushStackFrame(), Activity::raiseCondition(), Activity::raisePropagate(), Activity::returnAttach(), and Activity::unwindStackFrame().
setDigits()
virtual void ActivationBase::setDigits (wholenumber_t) inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 81 of file ActivationBase.hpp.
setForm()
virtual void ActivationBase::setForm (bool) inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 83 of file ActivationBase.hpp.
setFuzz()
virtual void ActivationBase::setFuzz (wholenumber_t) inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 82 of file ActivationBase.hpp.
setObjNotify()
virtual void ActivationBase::setObjNotify (MessageClass *) inline virtual
Reimplemented in RexxActivation.
Definition at line 86 of file ActivationBase.hpp.
Referenced by MessageClass::dispatch(), and MessageClass::sendNotification().
setPreviousStackFrame()
void ActivationBase::setPreviousStackFrame (ActivationBase * p) inline
Definition at line 95 of file ActivationBase.hpp.
References previous.
Referenced by Activity::pushStackFrame().
termination()
virtual void ActivationBase::termination () inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 87 of file ActivationBase.hpp.
Referenced by Activity::cleanupStackFrame().
trap()
virtual bool ActivationBase::trap (RexxString * , DirectoryClass *) inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 84 of file ActivationBase.hpp.
Referenced by NativeActivation::checkConditions(), RexxActivation::raise(), Activity::raisePropagate(), and RexxActivation::trap().
willTrap()
virtual bool ActivationBase::willTrap (RexxString *) inline virtual
Reimplemented in NativeActivation, and RexxActivation.
Definition at line 85 of file ActivationBase.hpp.
Referenced by RexxActivation::senderActivation(), and RexxActivation::willTrap().
Member Data Documentation
executable
BaseExecutable* ActivationBase::executable protected
Definition at line 103 of file ActivationBase.hpp.
Referenced by NativeActivation::callNativeRoutine(), NativeActivation::callRegisteredRoutine(), NativeActivation::createStackFrame(), NativeActivation::dispatch(), NativeActivation::findClass(), RexxActivation::formatSourcelessTraceLine(), RexxActivation::getEffectivePackageObject(), getExecutable(), getExecutableObject(), NativeActivation::getMethod(), RexxActivation::getMethod(), RexxActivation::getPackage(), NativeActivation::getPackageObject(), NativeActivation::getScope(), NativeActivation::live(), RexxActivation::live(), NativeActivation::liveGeneral(), RexxActivation::liveGeneral(), NativeActivation::methodVariables(), RexxActivation::RexxActivation(), NativeActivation::run(), and RexxActivation::traceEntryOrExit().
objectScope
GuardStatus ActivationBase::objectScope protected
Definition at line 104 of file ActivationBase.hpp.
Referenced by RexxActivation::getObjectVariables(), NativeActivation::guardOff(), RexxActivation::guardOff(), NativeActivation::guardOn(), RexxActivation::guardOn(), NativeActivation::guardWait(), RexxActivation::guardWait(), RexxActivation::isObjectScopeLocked(), NativeActivation::methodVariables(), RexxActivation::RexxActivation(), and RexxActivation::run().
previous
ActivationBase* ActivationBase::previous protected
Definition at line 102 of file ActivationBase.hpp.
Referenced by NativeActivation::findRexxContext(), getPreviousStackFrame(), NativeActivation::live(), RexxActivation::live(), NativeActivation::liveGeneral(), RexxActivation::liveGeneral(), and setPreviousStackFrame().
The documentation for this class was generated from the following file:
ActivationBase.hpp