ooRexx: TranslateInstoreDispatcher Class Reference
TranslateInstoreDispatcher Class Reference
#include <TranslateDispatcher.hpp>
Public Member Functions
TranslateInstoreDispatcher ()
virtual ~TranslateInstoreDispatcher ()
void run () override
void handleError (wholenumber_t, DirectoryClass *) override
Public Member Functions inherited from ActivityDispatcher
ActivityDispatcher ()
virtual ~ActivityDispatcher ()
virtual void handleError (DirectoryClass *)
virtual void invoke ()
virtual void invoke (RexxOption *)
virtual void invoke (PRXSYSEXIT exits, const char *env)
void setContext (Activity *act, NativeActivation *a)
Public Attributes
const char * programName
CONSTRXSTRING * source
RXSTRING * image
Public Attributes inherited from ActivityDispatcher
wholenumber_t rc
DirectoryClass * conditionData
Additional Inherited Members
Protected Attributes inherited from ActivityDispatcher
Activity * activity
NativeActivation * activation
Detailed Description
Definition at line 61 of file TranslateDispatcher.hpp.
Constructor & Destructor Documentation
TranslateInstoreDispatcher()
TranslateInstoreDispatcher::TranslateInstoreDispatcher () inline
Definition at line 64 of file TranslateDispatcher.hpp.
~TranslateInstoreDispatcher()
virtual TranslateInstoreDispatcher::~TranslateInstoreDispatcher () inline virtual
Definition at line 65 of file TranslateDispatcher.hpp.
Member Function Documentation
handleError()
void TranslateInstoreDispatcher::handleError (wholenumber_t r, DirectoryClass * c) override virtual
Default handler for any error conditions. This just sets the condition information in the dispatch unit.
Parameters
c The condition information for the error.
Reimplemented from ActivityDispatcher.
Definition at line 153 of file TranslateDispatcher.cpp.
References ActivityDispatcher::handleError(), and ActivityDispatcher::rc.
run()
void TranslateInstoreDispatcher::run () override virtual
Default virtual method for handling a run() methods on an activity dispatcher.
Reimplemented from ActivityDispatcher.
Definition at line 120 of file TranslateDispatcher.cpp.
References Error_Program_unreadable_name, image, MAKERXSTRING, new_string(), OREF_NULL, LanguageParser::processInstore(), programName, reportException(), source, _RXSTRING::strlength, _CONSTRXSTRING::strlength, _RXSTRING::strptr, and _CONSTRXSTRING::strptr.
Member Data Documentation
image
RXSTRING* TranslateInstoreDispatcher::image
Definition at line 72 of file TranslateDispatcher.hpp.
Referenced by RexxTranslateInstoreProgram(), and run().
programName
const char* TranslateInstoreDispatcher::programName
Definition at line 70 of file TranslateDispatcher.hpp.
Referenced by RexxTranslateInstoreProgram(), and run().
source
CONSTRXSTRING* TranslateInstoreDispatcher::source
Definition at line 71 of file TranslateDispatcher.hpp.
Referenced by RexxTranslateInstoreProgram(), and run().
The documentation for this class was generated from the following files:
TranslateDispatcher.hpp
TranslateDispatcher.cpp