ooRexx: CompoundTableElement Class Reference
CompoundTableElement Class Reference
#include <CompoundTableElement.hpp>
Public Member Functions
void * operator new (size_t size)
void operator delete (void *)
CompoundTableElement (RexxString *name)
CompoundTableElement (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
CompoundTableElement * realVariable ()
void setParent (CompoundTableElement *parentElement)
void setLeft (CompoundTableElement *leftChild)
void setRight (CompoundTableElement *rightChild)
bool isRightChild (CompoundTableElement *n)
bool isLeftChild (CompoundTableElement *n)
void setChild (int rc, CompoundTableElement *child)
void expose (CompoundTableElement *real)
RexxString * createCompoundName (RexxString *stemName)
void setValue (RexxObject *value)
Public Member Functions inherited from RexxVariable
void * operator new (size_t)
void operator delete (void *)
RexxVariable ()
RexxVariable (RexxString *n)
RexxVariable (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
void inform (Activity *)
void drop ()
void notify ()
void uninform (Activity *)
void setStem (RexxObject *)
void set (RexxObject *value)
void setValue (RexxObject *value)
void setCreator (RexxActivation *creatorActivation)
bool isLocal ()
bool isAliasable ()
RexxObject * getVariableValue ()
RexxObject * getResolvedValue ()
RexxString * getName ()
void setName (RexxString *name)
bool isDropped ()
RexxVariable * getNext ()
bool isStem ()
VariableReference * createReference ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static CompoundTableElement * newInstance (RexxString *name)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Attributes
CompoundTableElement * left
CompoundTableElement * right
CompoundTableElement * parent
unsigned short leftDepth
unsigned short rightDepth
CompoundTableElement * realElement
Protected Attributes inherited from RexxVariable
RexxString * variableName
RexxObject * variableValue
RexxActivation * creator
IdentityTable * dependents
Friends
class CompoundVariableTable
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 51 of file CompoundTableElement.hpp.
Constructor & Destructor Documentation
CompoundTableElement() [1/2]
CompoundTableElement::CompoundTableElement (RexxString * name) inline
Definition at line 59 of file CompoundTableElement.hpp.
References RexxVariable::variableName.
CompoundTableElement() [2/2]
CompoundTableElement::CompoundTableElement (RESTORETYPE restoreType) inline
Definition at line 60 of file CompoundTableElement.hpp.
Member Function Documentation
createCompoundName()
RexxString* CompoundTableElement::createCompoundName (RexxString * stemName) inline
Definition at line 86 of file CompoundTableElement.hpp.
References RexxString::concat(), and RexxVariable::getName().
expose()
void CompoundTableElement::expose (CompoundTableElement * real) inline
Definition at line 85 of file CompoundTableElement.hpp.
References realElement, and setField.
flatten()
void CompoundTableElement::flatten (Envelope * envelope) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 106 of file CompoundTableElement.cpp.
References cleanUpFlatten, RexxVariable::creator, RexxVariable::dependents, flattenRef, left, OREF_NULL, parent, realElement, right, setUpFlatten, RexxVariable::variableName, and RexxVariable::variableValue.
isLeftChild()
bool CompoundTableElement::isLeftChild (CompoundTableElement * n) inline
Definition at line 72 of file CompoundTableElement.hpp.
References left.
Referenced by CompoundVariableTable::moveNode().
isRightChild()
bool CompoundTableElement::isRightChild (CompoundTableElement * n) inline
Definition at line 71 of file CompoundTableElement.hpp.
References right.
Referenced by CompoundVariableTable::balance(), and CompoundVariableTable::next().
live()
void CompoundTableElement::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 68 of file CompoundTableElement.cpp.
References RexxVariable::creator, RexxVariable::dependents, left, memory_mark, parent, realElement, right, RexxVariable::variableName, and RexxVariable::variableValue.
liveGeneral()
void CompoundTableElement::liveGeneral (MarkReason reason) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 86 of file CompoundTableElement.cpp.
References RexxVariable::creator, RexxVariable::dependents, left, memory_mark_general, parent, realElement, right, RexxVariable::variableName, and RexxVariable::variableValue.
newInstance()
static CompoundTableElement* CompoundTableElement::newInstance (RexxString * name) static
operator delete()
void CompoundTableElement::operator delete (void *) inline
Definition at line 57 of file CompoundTableElement.hpp.
operator new()
void * CompoundTableElement::operator new (size_t size)
Allocate a new compound table element object.
Parameters
size The size of the object.
Returns
Storage for creating the object.
Definition at line 57 of file CompoundTableElement.cpp.
References new_object(), and T_CompoundElement.
realVariable()
CompoundTableElement* CompoundTableElement::realVariable () inline
Definition at line 66 of file CompoundTableElement.hpp.
References OREF_NULL, and realElement.
Referenced by StemClass::exposeCompoundVariable(), StemClass::findCompoundVariable(), and StemClass::getCompoundVariable().
setChild()
void CompoundTableElement::setChild (int rc, CompoundTableElement * child) inline
Definition at line 74 of file CompoundTableElement.hpp.
References setLeft(), and setRight().
Referenced by CompoundVariableTable::findEntry().
setLeft()
void CompoundTableElement::setLeft (CompoundTableElement * leftChild) inline
Definition at line 68 of file CompoundTableElement.hpp.
References left, and setField.
Referenced by CompoundVariableTable::moveNode(), and setChild().
setParent()
void CompoundTableElement::setParent (CompoundTableElement * parentElement) inline
Definition at line 67 of file CompoundTableElement.hpp.
References parent, and setField.
Referenced by CompoundVariableTable::findEntry(), and CompoundVariableTable::moveNode().
setRight()
void CompoundTableElement::setRight (CompoundTableElement * rightChild) inline
Definition at line 69 of file CompoundTableElement.hpp.
References right, and setField.
Referenced by CompoundVariableTable::moveNode(), and setChild().
setValue()
void CompoundTableElement::setValue (RexxObject * value) inline
Definition at line 87 of file CompoundTableElement.hpp.
References RexxVariable::set().
Referenced by CompoundVariableTable::copyFrom().
Friends And Related Function Documentation
CompoundVariableTable
friend class CompoundVariableTable friend
Definition at line 53 of file CompoundTableElement.hpp.
Member Data Documentation
left
CompoundTableElement* CompoundTableElement::left protected
Definition at line 93 of file CompoundTableElement.hpp.
Referenced by CompoundVariableTable::findEntry(), CompoundVariableTable::findLeaf(), flatten(), isLeftChild(), live(), liveGeneral(), CompoundVariableTable::moveNode(), and setLeft().
leftDepth
unsigned short CompoundTableElement::leftDepth protected
Definition at line 96 of file CompoundTableElement.hpp.
Referenced by CompoundVariableTable::balance(), and CompoundVariableTable::moveNode().
parent
CompoundTableElement* CompoundTableElement::parent protected
Definition at line 95 of file CompoundTableElement.hpp.
Referenced by CompoundVariableTable::balance(), flatten(), live(), liveGeneral(), CompoundVariableTable::moveNode(), CompoundVariableTable::next(), and setParent().
realElement
CompoundTableElement* CompoundTableElement::realElement protected
Definition at line 98 of file CompoundTableElement.hpp.
Referenced by expose(), flatten(), live(), liveGeneral(), and realVariable().
right
CompoundTableElement* CompoundTableElement::right protected
Definition at line 94 of file CompoundTableElement.hpp.
Referenced by CompoundVariableTable::findEntry(), CompoundVariableTable::findLeaf(), flatten(), isRightChild(), live(), liveGeneral(), CompoundVariableTable::moveNode(), CompoundVariableTable::next(), and setRight().
rightDepth
unsigned short CompoundTableElement::rightDepth protected
Definition at line 97 of file CompoundTableElement.hpp.
Referenced by CompoundVariableTable::balance(), and CompoundVariableTable::moveNode().
The documentation for this class was generated from the following files:
CompoundTableElement.hpp
CompoundTableElement.cpp