ooRexx: LocalAPISubsystem Class Reference
LocalAPISubsystem Class Reference
#include <LocalAPISubsystem.hpp>
Public Member Functions
virtual ~LocalAPISubsystem ()
virtual void initializeLocal (LocalAPIManager *a)
virtual void terminateProcess ()
virtual RexxReturnCode processServiceException (ServiceException *e)
Protected Attributes
LocalAPIManager * apiManager
Detailed Description
Definition at line 47 of file LocalAPISubsystem.hpp.
Constructor & Destructor Documentation
~LocalAPISubsystem()
virtual LocalAPISubsystem::~LocalAPISubsystem () inline virtual
Definition at line 50 of file LocalAPISubsystem.hpp.
Member Function Documentation
initializeLocal()
virtual void LocalAPISubsystem::initializeLocal (LocalAPIManager * a) inline virtual
Reimplemented in LocalQueueManager.
Definition at line 52 of file LocalAPISubsystem.hpp.
References apiManager.
Referenced by LocalQueueManager::initializeLocal(), and LocalAPIManager::initProcess().
processServiceException()
virtual RexxReturnCode LocalAPISubsystem::processServiceException (ServiceException * e) inline virtual
Reimplemented in LocalMacroSpaceManager, LocalQueueManager, and LocalRegistrationManager.
Definition at line 61 of file LocalAPISubsystem.hpp.
References CONNECTION_FAILURE, ServiceException::getErrorCode(), RXAPI_MEMFAIL, and RXAPI_NORXAPI.
terminateProcess()
virtual void LocalAPISubsystem::terminateProcess () inline virtual
Reimplemented in LocalQueueManager.
Definition at line 57 of file LocalAPISubsystem.hpp.
Referenced by LocalAPIManager::terminateProcess(), and LocalQueueManager::terminateProcess().
Member Data Documentation
apiManager
LocalAPIManager* LocalAPISubsystem::apiManager protected
Definition at line 75 of file LocalAPISubsystem.hpp.
Referenced by initializeLocal().
The documentation for this class was generated from the following file:
LocalAPISubsystem.hpp