ooRexx: TokenDefinition Class Reference
TokenDefinition Class Reference
#include <StreamCommandParser.h>
Public Member Functions
TokenDefinition (const char *t, size_t l, ParseAction *a)
TokenDefinition (int(*a)(TokenDefinition *, StreamToken &, void *))
bool isValid ()
int callUnknown (StreamToken &tokenizer, void *parms)
Public Attributes
const char * token
size_t minlength
ParseAction * actions
int(* actionRoutine)(TokenDefinition *, StreamToken &, void *)
Detailed Description
Definition at line 163 of file StreamCommandParser.h.
Constructor & Destructor Documentation
TokenDefinition() [1/2]
TokenDefinition::TokenDefinition (const char * t, size_t l, ParseAction * a) inline
Definition at line 166 of file StreamCommandParser.h.
References actionRoutine, actions, minlength, and token.
TokenDefinition() [2/2]
TokenDefinition::TokenDefinition (int(*)(TokenDefinition *, StreamToken &, void *) a) inline
Definition at line 174 of file StreamCommandParser.h.
References actionRoutine, actions, minlength, and token.
Member Function Documentation
callUnknown()
int TokenDefinition::callUnknown (StreamToken & tokenizer, void * parms) inline
Definition at line 183 of file StreamCommandParser.h.
References actionRoutine.
Referenced by parser().
isValid()
bool TokenDefinition::isValid () inline
Definition at line 182 of file StreamCommandParser.h.
References token.
Referenced by parser().
Member Data Documentation
actionRoutine
int(* TokenDefinition::actionRoutine) (TokenDefinition *, StreamToken &, void *)
Definition at line 192 of file StreamCommandParser.h.
Referenced by callUnknown(), and TokenDefinition().
actions
ParseAction* TokenDefinition::actions
Definition at line 189 of file StreamCommandParser.h.
Referenced by parser(), and TokenDefinition().
minlength
size_t TokenDefinition::minlength
Definition at line 188 of file StreamCommandParser.h.
Referenced by parser(), and TokenDefinition().
token
const char* TokenDefinition::token
Definition at line 187 of file StreamCommandParser.h.
Referenced by isValid(), parser(), and TokenDefinition().
The documentation for this class was generated from the following file:
StreamCommandParser.h