ooRexx: DoBlock Class Reference
DoBlock Class Reference
#include <DoBlock.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
DoBlock (RexxActivation *context, RexxBlockInstruction *i)
DoBlock (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
RexxBlockInstruction * getParent ()
void setPrevious (DoBlock *block)
DoBlock * getPrevious ()
void setControl (RexxVariableBase *v)
void setTo (RexxObject *value)
void setBy (RexxObject *value)
void setFor (size_t value)
void setOverIndex (size_t value)
void setCase (RexxObject *value)
void setSupplier (RexxObject *value)
void setCompare (TokenSubclass value)
RexxObject * getCase ()
RexxObject * getSupplier ()
size_t getIndent ()
bool checkFor ()
bool checkControl (RexxActivation *context, ExpressionStack *stack, bool increment)
bool checkOver (RexxActivation *context, ExpressionStack *stack)
void newIteration ()
void setCounter (RexxActivation *context)
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Protected Attributes
DoBlock * previous
RexxBlockInstruction * parent
size_t indent
RexxVariableBase * control
RexxObject * to
RexxObject * by
size_t overIndex
size_t forCount
TokenSubclass compare
RexxVariableBase * countVariable
uint64_t counter
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
A container for state of active block instructions (DO LOOP, or SELECT)
Definition at line 56 of file DoBlock.hpp.
Constructor & Destructor Documentation
DoBlock() [1/2]
DoBlock::DoBlock (RexxActivation * context, RexxBlockInstruction * _parent)
Construct a runtime DO block instance.
Parameters
_parent The instruction this represents.
Definition at line 68 of file DoBlock.cpp.
References RexxVariableBase::assign(), countVariable, RexxBlockInstruction::getCountVariable(), RexxActivation::getIndent(), indent, IntegerZero, OREF_NULL, parent, and RexxActivation::traceKeywordResult().
DoBlock() [2/2]
DoBlock::DoBlock (RESTORETYPE restoreType) inline
Definition at line 64 of file DoBlock.hpp.
Member Function Documentation
checkControl()
bool DoBlock::checkControl (RexxActivation * context, ExpressionStack * stack, bool increment)
Perform control variable checks on a DO/LOOP iteration.
Parameters
context The current execution context.
stack The current evaluation stack.
increment a flag indicating whether to increment the value or not. This will be true on the first loop iteration and false on all further iterations.
Returns
True if the loop should continue, false if we've hit a termination condition.
Definition at line 182 of file DoBlock.cpp.
References RexxVariableBase::assign(), by, checkFor(), compare, control, RexxInternalObject::evaluate(), forCount, RexxInternalObject::getValue(), OPERATOR_PLUS, OREF_NULL, SIZE_MAX, TheTrueObject, to, and RexxActivation::traceResult().
Referenced by RexxInstructionControlledDo::iterate(), RexxInstructionControlledDoUntil::iterate(), and RexxInstructionControlledDoWhile::iterate().
checkFor()
bool DoBlock::checkFor () inline
Definition at line 84 of file DoBlock.hpp.
References counter, and forCount.
Referenced by checkControl(), RexxInstructionDoOverFor::iterate(), RexxInstructionDoOverForUntil::iterate(), RexxInstructionDoOverForWhile::iterate(), RexxInstructionDoCount::iterate(), RexxInstructionDoCountUntil::iterate(), RexxInstructionDoCountWhile::iterate(), RexxInstructionDoWithFor::iterate(), RexxInstructionDoWithForUntil::iterate(), and RexxInstructionDoWithForWhile::iterate().
checkOver()
bool DoBlock::checkOver (RexxActivation * context, ExpressionStack * stack)
Process an interation of a DO OVER loop.
Parameters
context The current execution context.
stack The current evaluation stack.
Returns
true if we should perform this iteration of the loop, false otherwise.
Definition at line 144 of file DoBlock.cpp.
References RexxVariableBase::assign(), control, ArrayClass::get(), ArrayClass::lastIndex(), OREF_NULL, overIndex, TheNilObject, and to.
Referenced by RexxInstructionDoOver::iterate(), RexxInstructionDoOverFor::iterate(), RexxInstructionDoOverUntil::iterate(), RexxInstructionDoOverForUntil::iterate(), RexxInstructionDoOverWhile::iterate(), and RexxInstructionDoOverForWhile::iterate().
getCase()
RexxObject* DoBlock::getCase () inline
Definition at line 81 of file DoBlock.hpp.
References to.
Referenced by RexxInstructionCaseWhen::execute().
getIndent()
size_t DoBlock::getIndent () inline
Definition at line 83 of file DoBlock.hpp.
References indent.
Referenced by RexxInstructionEnd::execute(), RexxActivation::iterate(), RexxActivation::popBlockInstruction(), RexxBaseBlockInstruction::terminate(), and RexxInstructionSelect::terminate().
getParent()
RexxBlockInstruction* DoBlock::getParent () inline
Definition at line 69 of file DoBlock.hpp.
References parent.
Referenced by RexxInstructionEnd::execute(), RexxActivation::iterate(), and RexxActivation::leaveLoop().
getPrevious()
DoBlock* DoBlock::getPrevious () inline
Definition at line 71 of file DoBlock.hpp.
References previous.
Referenced by RexxActivation::popBlockInstruction().
getSupplier()
RexxObject* DoBlock::getSupplier () inline
Definition at line 82 of file DoBlock.hpp.
References to.
Referenced by WithLoop::checkIteration().
live()
void DoBlock::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 88 of file DoBlock.cpp.
References by, control, countVariable, memory_mark, parent, previous, and to.
liveGeneral()
void DoBlock::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 106 of file DoBlock.cpp.
References by, control, countVariable, memory_mark_general, parent, previous, and to.
newIteration()
void DoBlock::newIteration () inline
Definition at line 87 of file DoBlock.hpp.
References counter.
Referenced by RexxInstructionBaseLoop::reExecute().
operator delete()
void DoBlock::operator delete (void *) inline
Definition at line 61 of file DoBlock.hpp.
operator new()
void * DoBlock::operator new (size_t size)
Allocate a new DoBlock object.
Parameters
size The object size
Returns
Storage for this object allocated from the Rexx object heap.
Definition at line 57 of file DoBlock.cpp.
References new_object(), and T_DoBlock.
setBy()
void DoBlock::setBy (RexxObject * value) inline
Definition at line 75 of file DoBlock.hpp.
References by.
Referenced by ControlledLoop::setup().
setCase()
void DoBlock::setCase (RexxObject * value) inline
Definition at line 78 of file DoBlock.hpp.
References to.
Referenced by RexxInstructionSelectCase::execute().
setCompare()
void DoBlock::setCompare (TokenSubclass value) inline
Definition at line 80 of file DoBlock.hpp.
References compare.
Referenced by ControlledLoop::setup().
setControl()
void DoBlock::setControl (RexxVariableBase * v) inline
Definition at line 73 of file DoBlock.hpp.
References control.
Referenced by ControlledLoop::setup(), and OverLoop::setup().
setCounter()
void DoBlock::setCounter (RexxActivation * context)
Handle a new iteration of a loop, with setting of the counter variable, if required.
Parameters
context The current execution context,
Definition at line 122 of file DoBlock.cpp.
References RexxVariableBase::assign(), counter, countVariable, OREF_NULL, RexxActivation::traceKeywordResult(), and Numerics::uint64ToObject().
Referenced by RexxInstructionBaseLoop::reExecute().
setFor()
void DoBlock::setFor (size_t value) inline
Definition at line 76 of file DoBlock.hpp.
References forCount.
Referenced by ControlledLoop::setup(), and ForLoop::setup().
setOverIndex()
void DoBlock::setOverIndex (size_t value) inline
Definition at line 77 of file DoBlock.hpp.
References overIndex.
Referenced by OverLoop::setup().
setPrevious()
void DoBlock::setPrevious (DoBlock * block) inline
Definition at line 70 of file DoBlock.hpp.
References previous.
Referenced by RexxActivation::pushBlockInstruction().
setSupplier()
void DoBlock::setSupplier (RexxObject * value) inline
Definition at line 79 of file DoBlock.hpp.
References to.
Referenced by WithLoop::setup().
setTo()
void DoBlock::setTo (RexxObject * value) inline
Definition at line 74 of file DoBlock.hpp.
References to.
Referenced by ControlledLoop::setup(), and OverLoop::setup().
Member Data Documentation
by
RexxObject* DoBlock::by protected
Definition at line 102 of file DoBlock.hpp.
Referenced by checkControl(), live(), liveGeneral(), and setBy().
compare
TokenSubclass DoBlock::compare protected
Definition at line 105 of file DoBlock.hpp.
Referenced by checkControl(), and setCompare().
control
RexxVariableBase* DoBlock::control protected
Definition at line 100 of file DoBlock.hpp.
Referenced by checkControl(), checkOver(), live(), liveGeneral(), and setControl().
counter
uint64_t DoBlock::counter protected
Definition at line 107 of file DoBlock.hpp.
Referenced by checkFor(), newIteration(), and setCounter().
countVariable
RexxVariableBase* DoBlock::countVariable protected
Definition at line 106 of file DoBlock.hpp.
Referenced by DoBlock(), live(), liveGeneral(), and setCounter().
forCount
size_t DoBlock::forCount protected
Definition at line 104 of file DoBlock.hpp.
Referenced by checkControl(), checkFor(), and setFor().
indent
size_t DoBlock::indent protected
Definition at line 95 of file DoBlock.hpp.
Referenced by DoBlock(), and getIndent().
overIndex
size_t DoBlock::overIndex protected
Definition at line 103 of file DoBlock.hpp.
Referenced by checkOver(), and setOverIndex().
parent
RexxBlockInstruction* DoBlock::parent protected
Definition at line 94 of file DoBlock.hpp.
Referenced by DoBlock(), getParent(), live(), and liveGeneral().
previous
DoBlock* DoBlock::previous protected
Definition at line 93 of file DoBlock.hpp.
Referenced by getPrevious(), live(), liveGeneral(), and setPrevious().
to
RexxObject* DoBlock::to protected
Definition at line 101 of file DoBlock.hpp.
Referenced by checkControl(), checkOver(), getCase(), getSupplier(), live(), liveGeneral(), setCase(), setSupplier(), and setTo().
The documentation for this class was generated from the following files:
DoBlock.hpp
DoBlock.cpp