ooRexx: StemHandler Class Reference
StemHandler Class Reference
#include <RexxUtilCommon.hpp>
Public Member Functions
StemHandler (RexxCallContext *c, RexxStemObject s=NULLOBJECT)
StemHandler (RexxCallContext *c, RexxObjectPtr s, int position)
~StemHandler ()
void complete ()
void setStem (RexxObjectPtr stemArgument, int position)
void addList (const char *values)
void addValue (const char *value)
void addValue (const char *value, size_t valueLen)
Protected Attributes
RexxCallContext * context
RexxStemObject stem
size_t arrayCount
RexxArrayObject array
bool isArray
Detailed Description
Simple class for managing returning results as a stem or an array object.
Definition at line 168 of file RexxUtilCommon.hpp.
Constructor & Destructor Documentation
StemHandler() [1/2]
StemHandler::StemHandler (RexxCallContext * c, RexxStemObject s = NULLOBJECT) inline
Definition at line 171 of file RexxUtilCommon.hpp.
StemHandler() [2/2]
StemHandler::StemHandler (RexxCallContext * c, RexxObjectPtr s, int position) inline
Definition at line 173 of file RexxUtilCommon.hpp.
References setStem().
~StemHandler()
StemHandler::~StemHandler () inline
Definition at line 178 of file RexxUtilCommon.hpp.
References complete().
Member Function Documentation
addList()
void StemHandler::addList (const char * values) inline
Definition at line 216 of file RexxUtilCommon.hpp.
References addValue().
Referenced by RexxRoutine4().
addValue() [1/2]
void StemHandler::addValue (const char * value) inline
Definition at line 227 of file RexxUtilCommon.hpp.
Referenced by addList(), TreeFinder::addResult(), RexxRoutine1(), and RexxRoutine4().
addValue() [2/2]
void StemHandler::addValue (const char * value, size_t valueLen) inline
Definition at line 232 of file RexxUtilCommon.hpp.
References array, arrayCount, context, isArray, and stem.
complete()
void StemHandler::complete () inline
Definition at line 183 of file RexxUtilCommon.hpp.
References arrayCount, context, isArray, NULLOBJECT, and stem.
Referenced by RexxRoutine1(), ~StemHandler(), and TreeFinder::~TreeFinder().
setStem()
void StemHandler::setStem (RexxObjectPtr stemArgument, int position) inline
Definition at line 192 of file RexxUtilCommon.hpp.
References array, context, isArray, NULLOBJECT, Rexx_Error_Incorrect_call_noarray_nostem, and stem.
Referenced by RexxRoutine4(), and StemHandler().
Member Data Documentation
array
RexxArrayObject StemHandler::array protected
Definition at line 250 of file RexxUtilCommon.hpp.
Referenced by addValue(), and setStem().
arrayCount
size_t StemHandler::arrayCount protected
Definition at line 249 of file RexxUtilCommon.hpp.
Referenced by addValue(), and complete().
context
RexxCallContext* StemHandler::context protected
Definition at line 247 of file RexxUtilCommon.hpp.
Referenced by addValue(), complete(), and setStem().
isArray
bool StemHandler::isArray protected
Definition at line 251 of file RexxUtilCommon.hpp.
Referenced by addValue(), complete(), and setStem().
stem
RexxStemObject StemHandler::stem protected
Definition at line 248 of file RexxUtilCommon.hpp.
Referenced by addValue(), complete(), and setStem().
The documentation for this class was generated from the following file:
RexxUtilCommon.hpp