ooRexx: OldSpaceSegmentSet Class Reference
OldSpaceSegmentSet Class Reference
#include <MemorySegment.hpp>
Public Member Functions
OldSpaceSegmentSet ()
OldSpaceSegmentSet (MemoryObject *memory)
virtual ~OldSpaceSegmentSet ()
RexxInternalObject * allocateObject (size_t allocationLength)
void markOldSpaceObjects ()
Public Member Functions inherited from MemorySegmentSet
MemorySegmentSet (MemoryObject *memObject, SegmentSetID id, const char *setName)
MemorySegmentSet ()
virtual ~MemorySegmentSet ()
void removeSegment (MemorySegment *segment)
void removeSegmentAndStorage (MemorySegment *segment)
void add (MemorySegment *segment)
MemorySegment * first ()
MemorySegment * next (MemorySegment *segment)
void transferSegment (MemorySegment *segment)
void dumpSegments (FILE *keyfile, FILE *dumpfile)
void addSegment (MemorySegment *segment)
void sweep ()
void sweepSingleSegment (MemorySegment *sweepSegment)
bool is (SegmentSetID id)
void gatherStats (MemoryStats *memStats, SegmentStats *stats)
MemorySegment * largestActiveSegment ()
virtual void dumpMemoryProfile (FILE *outfile)
virtual DeadObject * donateObject (size_t allocationLength)
Protected Member Functions
void addDeadObject (DeadObject *object) override
void addDeadObject (char *object, size_t length) override
RexxInternalObject * findObject (size_t allocationLength)
Protected Member Functions inherited from MemorySegmentSet
RexxInternalObject * splitDeadObject (DeadObject *object, size_t allocationLength, size_t splitMinimum)
void insertSegment (MemorySegment *segment)
virtual size_t suggestMemoryExpansion ()
virtual void prepareForSweep ()
virtual void completeSweepOperation ()
void adjustMemorySize ()
bool newSegment (size_t requestLength, size_t minimumLength)
virtual MemorySegment * allocateSegment (size_t requestLength, size_t minimumLength)
float freeMemoryPercentage ()
size_t totalFreeMemory ()
size_t calculateSegmentAllocation (size_t n)
void addSegments (size_t requiredSpace)
void validateObject (RexxInternalObject *o)
Private Attributes
DeadObjectPool deadCache
Additional Inherited Members
Public Types inherited from MemorySegmentSet
enum SegmentSetID {
SET_UNINITIALIZED , SET_NORMAL , SET_LARGEBLOCK , SET_OLDSPACE ,
SET_SINGLEOBJECT
}
Static Public Attributes inherited from MemorySegmentSet
static const size_t MinimumSegmentSize = (MemorySegment::SegmentSize/2)
static const size_t MinimumSegmentDeadSpace = (MinimumSegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentSize = (MemorySegment::SegmentSize * 4)
static const size_t SegmentDeadSpace = (MemorySegment::SegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentDeadSpace = (LargeSegmentSize - MemorySegment::MemorySegmentOverhead)
Protected Attributes inherited from MemorySegmentSet
MemorySegment anchor
size_t count
size_t liveObjectBytes
size_t deadObjectBytes
SegmentSetID owner
const char * name
MemoryObject * memory
Detailed Description
The segment set for the oldspace containing the ooRexx image.
Definition at line 632 of file MemorySegment.hpp.
Constructor & Destructor Documentation
OldSpaceSegmentSet() [1/2]
OldSpaceSegmentSet::OldSpaceSegmentSet () inline
Definition at line 637 of file MemorySegment.hpp.
OldSpaceSegmentSet() [2/2]
OldSpaceSegmentSet::OldSpaceSegmentSet (MemoryObject * mem)
Constructor for the oldspace segment pool.
Parameters
mem The master memory object instance
Definition at line 230 of file MemorySegment.cpp.
~OldSpaceSegmentSet()
virtual OldSpaceSegmentSet::~OldSpaceSegmentSet () inline virtual
Definition at line 639 of file MemorySegment.hpp.
Member Function Documentation
addDeadObject() [1/2]
void OldSpaceSegmentSet::addDeadObject (char * object, size_t length) override protected virtual
Add a section of memory as a dead object to our pool.
Parameters
object The address of the memory.
length The length of the dead memory.
Reimplemented from MemorySegmentSet.
Definition at line 508 of file MemorySegment.cpp.
References DeadObjectPool::addSortedBySize(), and deadCache.
addDeadObject() [2/2]
void OldSpaceSegmentSet::addDeadObject (DeadObject * object) override protected virtual
Add a dead object to the segment set during the sweep operation.
Parameters
object The newly dead object.
Reimplemented from MemorySegmentSet.
Definition at line 415 of file MemorySegment.cpp.
References DeadObjectPool::addSortedBySize(), and deadCache.
allocateObject()
RexxInternalObject * OldSpaceSegmentSet::allocateObject (size_t requestLength)
Allocate an object from the old space. This is a very simple management strategy, with no heroic efforts made to locate memory. Since objects here can only come from the OldSpace area, there is no garbage collection forced for failures.
Parameters
requestLength The required object length.
Returns
An object of appropriate size or NULL if not enough space.
Definition at line 1380 of file MemorySegment.cpp.
References findObject(), MemorySegmentSet::newSegment(), OREF_NULL, and Memory::roundLargeObjectAllocation().
Referenced by MemoryObject::oldObject().
findObject()
RexxInternalObject * OldSpaceSegmentSet::findObject (size_t allocationLength) protected
Locate an object is the dead object cache maintained for old space object allocations.
Parameters
allocationLength The required object size
Returns
An allocated object, or NULL if not enough there.
Definition at line 1306 of file MemorySegment.cpp.
References deadCache, DeadObjectPool::findFit(), Memory::LargeAllocationUnit, OREF_NULL, and MemorySegmentSet::splitDeadObject().
Referenced by allocateObject().
markOldSpaceObjects()
void OldSpaceSegmentSet::markOldSpaceObjects ()
Perform a marking operation on all OldSpace objects
Definition at line 1492 of file MemorySegment.cpp.
References MemorySegmentSet::first(), and MemorySegmentSet::next().
Member Data Documentation
deadCache
DeadObjectPool OldSpaceSegmentSet::deadCache private
Definition at line 651 of file MemorySegment.hpp.
Referenced by addDeadObject(), and findObject().
The documentation for this class was generated from the following files:
MemorySegment.hpp
MemorySegment.cpp