ooRexx: FileNameBuffer Class Reference
FileNameBuffer Class Reference
#include <FileNameBuffer.hpp>
Public Member Functions
FileNameBuffer (size_t initial=0)
FileNameBuffer (const FileNameBuffer &o)
~FileNameBuffer ()
void init (size_t initial)
virtual void handleMemoryError ()
size_t capacity ()
size_t length ()
operator char * ()
operator const char * ()
void ensureCapacity (size_t size)
void ensureAdditionalCapacity (const char *add)
void expandCapacity (size_t c)
void shiftLeft (size_t l)
void truncate (size_t l)
void empty ()
FileNameBuffer & operator= (const char *s)
FileNameBuffer & operator= (const FileNameBuffer &s)
FileNameBuffer & operator= (char *s)
FileNameBuffer & operator+= (const char *s)
FileNameBuffer & operator+= (char *s)
FileNameBuffer & operator+= (char c)
FileNameBuffer & operator+= (FileNameBuffer &s)
FileNameBuffer & set (const char *s, size_t l)
FileNameBuffer & append (const char *s, size_t l)
bool operator== (const char *s)
bool operator!= (const char *s)
char & at (size_t pos)
bool startsWith (char c)
bool startsWith (const char *s)
bool endsWith (char c)
bool endsWith (const char *s)
bool isEmpty ()
void appendPathSeparator ()
void addFinalPathDelimiter ()
size_t locatePathDelimiter (size_t start=0)
Protected Attributes
char * buffer
size_t bufferSize
Detailed Description
A class for performing safer file name resolution that is expandable if needed. Replaces the use of fixed-sized buffers for file operations.
NOTE: This can only be used within code that runs while the interpreter has control.
Definition at line 52 of file FileNameBuffer.hpp.
Constructor & Destructor Documentation
FileNameBuffer() [1/2]
FileNameBuffer::FileNameBuffer (size_t initial = 0)
Constructor for a filename buffer. Performs initial setup
Parameters
size The initial size. If zero, then the default size is used.
Definition at line 48 of file FileNameBuffer.cpp.
References init().
FileNameBuffer() [2/2]
FileNameBuffer::FileNameBuffer (const FileNameBuffer & o)
Copy constructor for a FileNameBuffer object
Parameters
o The source object.
Definition at line 59 of file FileNameBuffer.cpp.
References buffer, bufferSize, and init().
~FileNameBuffer()
FileNameBuffer::~FileNameBuffer () inline
Definition at line 57 of file FileNameBuffer.hpp.
References buffer.
Member Function Documentation
addFinalPathDelimiter()
void FileNameBuffer::addFinalPathDelimiter () inline
Definition at line 262 of file FileNameBuffer.hpp.
References endsWith(), and SysFileSystem::PathDelimiter.
Referenced by TreeFinder::expandNonPath2fullPath(), TreeFinder::fixupFilePath(), and RexxRoutine1().
append()
FileNameBuffer& FileNameBuffer::append (const char * s, size_t l) inline
Definition at line 185 of file FileNameBuffer.hpp.
References buffer, ensureCapacity(), and length().
appendPathSeparator()
void FileNameBuffer::appendPathSeparator () inline
Definition at line 252 of file FileNameBuffer.hpp.
References endsWith(), SysFileSystem::getPathSeparator(), and isEmpty().
Referenced by SysSearchPath::addPath().
at()
char& FileNameBuffer::at (size_t pos) inline
Definition at line 207 of file FileNameBuffer.hpp.
References buffer, and ensureCapacity().
Referenced by TreeFinder::findDirectoryEnd(), SysFileSystem::getLongName(), SysFileSystem::normalizePathName(), SysFileSystem::resolveTilde(), RexxRoutine1(), and SysFileSystem::searchFileName().
capacity()
size_t FileNameBuffer::capacity () inline
Definition at line 70 of file FileNameBuffer.hpp.
References bufferSize.
Referenced by SysFileSystem::getCurrentDirectory(), SysFileSystem::getFullPathName(), SysFileSystem::getLongName(), RexxRoutine1(), and SysFileSystem::searchOnPath().
empty()
void FileNameBuffer::empty () inline
Definition at line 114 of file FileNameBuffer.hpp.
References buffer.
endsWith() [1/2]
bool FileNameBuffer::endsWith (char c) inline
Definition at line 230 of file FileNameBuffer.hpp.
References buffer, and length().
Referenced by addFinalPathDelimiter(), TreeFinder::adjustDirectory(), appendPathSeparator(), TreeFinder::expandPath2fullPath(), RexxRoutine1(), and SysFileSystem::searchPath().
endsWith() [2/2]
bool FileNameBuffer::endsWith (const char * s) inline
Definition at line 235 of file FileNameBuffer.hpp.
References buffer, and length().
ensureAdditionalCapacity()
void FileNameBuffer::ensureAdditionalCapacity (const char * add) inline
Definition at line 87 of file FileNameBuffer.hpp.
References buffer, and ensureCapacity().
Referenced by operator+=().
ensureCapacity()
void FileNameBuffer::ensureCapacity (size_t c)
Destructor to perform out of scope cleanup.
Definition at line 96 of file FileNameBuffer.cpp.
References buffer, bufferSize, and handleMemoryError().
Referenced by append(), at(), ensureAdditionalCapacity(), expandCapacity(), SysFileSystem::getFullPathName(), SysFileSystem::getLongName(), operator+=(), operator=(), RexxRoutine1(), SysFileSystem::searchOnPath(), and set().
expandCapacity()
void FileNameBuffer::expandCapacity (size_t c) inline
Definition at line 88 of file FileNameBuffer.hpp.
References bufferSize, and ensureCapacity().
Referenced by SysFileSystem::getCurrentDirectory().
handleMemoryError()
void FileNameBuffer::handleMemoryError () virtual
Handle a memory error. Base implementation is for just raising a normal exception. This can only be used within internal code when the kernel lock is held.
Reimplemented in RoutineFileNameBuffer, MethodFileNameBuffer, and AutoFileNameBuffer.
Definition at line 124 of file FileNameBuffer.cpp.
References Error_System_resources, and reportException().
Referenced by ensureCapacity(), AutoFileNameBuffer::handleMemoryError(), and init().
init()
void FileNameBuffer::init (size_t initial)
Do the initial setup for a FileNameBuffer object.
Parameters
initial The initial capacity.
Definition at line 71 of file FileNameBuffer.cpp.
References buffer, bufferSize, handleMemoryError(), and SysFileSystem::MaximumPathLength.
Referenced by FileNameBuffer().
isEmpty()
bool FileNameBuffer::isEmpty () inline
Definition at line 247 of file FileNameBuffer.hpp.
References buffer.
Referenced by appendPathSeparator(), and SysFileSystem::canonicalizeName().
length()
size_t FileNameBuffer::length () inline
Definition at line 71 of file FileNameBuffer.hpp.
References buffer.
Referenced by append(), SystemInterpreter::buildEnvlist(), endsWith(), TreeFinder::findDirectoryEnd(), SysFileSystem::getLongName(), locatePathDelimiter(), operator+=(), SysFileSystem::qualifyStreamName(), TreeFinder::recursiveFindFile(), StreamInfo::resolveStreamName(), RexxMethod1(), RexxRoutine1(), RexxRoutine2(), RexxRoutine3(), shiftLeft(), startsWith(), truncate(), and TreeFinder::validateFileSpec().
locatePathDelimiter()
size_t FileNameBuffer::locatePathDelimiter (size_t start = 0) inline
Definition at line 270 of file FileNameBuffer.hpp.
References buffer, length(), and SysFileSystem::PathDelimiter.
operator char *()
FileNameBuffer::operator char * () inline
Definition at line 74 of file FileNameBuffer.hpp.
References buffer.
operator const char *()
FileNameBuffer::operator const char * () inline
Definition at line 80 of file FileNameBuffer.hpp.
References buffer.
operator!=()
bool FileNameBuffer::operator!= (const char * s) inline
Definition at line 199 of file FileNameBuffer.hpp.
References buffer.
operator+=() [1/4]
FileNameBuffer& FileNameBuffer::operator+= (char * s) inline
Definition at line 155 of file FileNameBuffer.hpp.
References buffer, bufferSize, and ensureAdditionalCapacity().
operator+=() [2/4]
FileNameBuffer& FileNameBuffer::operator+= (char c) inline
Definition at line 162 of file FileNameBuffer.hpp.
References buffer, ensureCapacity(), and length().
operator+=() [3/4]
FileNameBuffer& FileNameBuffer::operator+= (const char * s) inline
Definition at line 148 of file FileNameBuffer.hpp.
References buffer, bufferSize, and ensureAdditionalCapacity().
Referenced by AutoFileNameBuffer::operator+=().
operator+=() [4/4]
FileNameBuffer& FileNameBuffer::operator+= (FileNameBuffer & s) inline
Definition at line 172 of file FileNameBuffer.hpp.
operator=() [1/3]
FileNameBuffer& FileNameBuffer::operator= (char * s) inline
Definition at line 141 of file FileNameBuffer.hpp.
References buffer, bufferSize, and ensureCapacity().
operator=() [2/3]
FileNameBuffer& FileNameBuffer::operator= (const char * s) inline
Definition at line 119 of file FileNameBuffer.hpp.
References buffer, bufferSize, and ensureCapacity().
Referenced by RoutineFileNameBuffer::operator=(), MethodFileNameBuffer::operator=(), and AutoFileNameBuffer::operator=().
operator=() [3/3]
FileNameBuffer& FileNameBuffer::operator= (const FileNameBuffer & s) inline
Definition at line 126 of file FileNameBuffer.hpp.
References buffer, bufferSize, and ensureCapacity().
operator==()
bool FileNameBuffer::operator== (const char * s) inline
Definition at line 194 of file FileNameBuffer.hpp.
References buffer.
set()
FileNameBuffer& FileNameBuffer::set (const char * s, size_t l) inline
Definition at line 177 of file FileNameBuffer.hpp.
References buffer, and ensureCapacity().
Referenced by TreeFinder::expandPath2fullPath(), SysFileSystem::resolveTilde(), SysFileSystem::searchFileName(), and SysFileSystem::searchPath().
shiftLeft()
void FileNameBuffer::shiftLeft (size_t l) inline
Definition at line 89 of file FileNameBuffer.hpp.
References buffer, and length().
startsWith() [1/2]
bool FileNameBuffer::startsWith (char c) inline
Definition at line 213 of file FileNameBuffer.hpp.
References buffer.
Referenced by TreeFinder::adjustDirectory(), and SysFileSystem::canonicalizeName().
startsWith() [2/2]
bool FileNameBuffer::startsWith (const char * s) inline
Definition at line 218 of file FileNameBuffer.hpp.
References buffer, and length().
truncate()
void FileNameBuffer::truncate (size_t l) inline
Definition at line 104 of file FileNameBuffer.hpp.
References buffer, and length().
Referenced by getUniqueFileName(), and RexxRoutine1().
Member Data Documentation
buffer
char* FileNameBuffer::buffer protected
Definition at line 284 of file FileNameBuffer.hpp.
Referenced by append(), at(), empty(), endsWith(), ensureAdditionalCapacity(), ensureCapacity(), FileNameBuffer(), init(), isEmpty(), length(), locatePathDelimiter(), operator char *(), operator const char *(), operator!=(), operator+=(), operator=(), RoutineFileNameBuffer::operator==(), MethodFileNameBuffer::operator==(), operator==(), set(), shiftLeft(), startsWith(), truncate(), and ~FileNameBuffer().
bufferSize
size_t FileNameBuffer::bufferSize protected
Definition at line 285 of file FileNameBuffer.hpp.
Referenced by capacity(), ensureCapacity(), expandCapacity(), FileNameBuffer(), init(), operator+=(), and operator=().
The documentation for this class was generated from the following files:
FileNameBuffer.hpp
FileNameBuffer.cpp