ooRexx: ProgramMetaData Class Reference
ProgramMetaData Class Reference
#include <ProgramMetaData.hpp>
Public Member Functions
void * operator new (size_t size, BufferClass *buff)
void operator delete (void *p)
ProgramMetaData (LanguageLevel, BufferClass *)
ProgramMetaData (LanguageLevel, size_t)
size_t getDataSize ()
size_t getHeaderSize ()
char * getImageData ()
size_t getImageSize ()
bool validate (RexxString *fileName)
void write (SysFile &target, BufferClass *program, bool encode)
Static Public Member Functions
static RoutineClass * restore (RexxString *fileName, BufferClass *buffer)
static bool processRestoreData (RexxString *fileName, BufferClass *data, ProgramMetaData *&metaData)
Static Public Attributes
static const size_t encodingChunkLength = 72
Protected Types
enum { MAGICNUMBER = 11111 , METAVERSION = 43 }
Protected Attributes
char fileTag [16]
uint16_t magicNumber
uint16_t imageVersion
uint16_t wordSize
uint16_t bigEndian
uint32_t requiredLevel
uint32_t reserved
size_t pad
size_t imageSize
char imageData [4]
Detailed Description
Definition at line 48 of file ProgramMetaData.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
MAGICNUMBER
METAVERSION
Definition at line 71 of file ProgramMetaData.hpp.
Constructor & Destructor Documentation
ProgramMetaData() [1/2]
ProgramMetaData::ProgramMetaData (LanguageLevel level, BufferClass * image)
Initialize the meta data directly from a buffer.
Parameters
level The language level required for the code stored in the buffer.
image The image buffer.
Definition at line 83 of file ProgramMetaData.cpp.
References bigEndian, compiledHeader, fileTag, BufferClass::getData(), BufferClassBase::getDataLength(), Interpreter::getWordSize(), imageData, imageSize, imageVersion, Interpreter::isBigEndian(), MAGICNUMBER, magicNumber, METAVERSION, requiredLevel, reserved, and wordSize.
ProgramMetaData() [2/2]
ProgramMetaData::ProgramMetaData (LanguageLevel level, size_t bufferSize)
Initialize the meta data for a given data size.
Parameters
level The language level required for the saved program.
bufferSize The size of the program data.
Definition at line 110 of file ProgramMetaData.cpp.
References bigEndian, compiledHeader, fileTag, Interpreter::getWordSize(), imageSize, imageVersion, Interpreter::isBigEndian(), MAGICNUMBER, magicNumber, METAVERSION, requiredLevel, reserved, and wordSize.
Member Function Documentation
getDataSize()
size_t ProgramMetaData::getDataSize ()
Get the final size of a copied buffer
Returns
The data image size.
Definition at line 135 of file ProgramMetaData.cpp.
References imageData, and imageSize.
Referenced by RoutineClass::save().
getHeaderSize()
size_t ProgramMetaData::getHeaderSize ()
Get the final size of a copied buffer
Returns
The data image size.
Definition at line 146 of file ProgramMetaData.cpp.
References imageData.
Referenced by write().
getImageData()
char * ProgramMetaData::getImageData ()
Return a pointer to the inline image data.
Returns
The pointer to the image data following the metadata header.
Definition at line 157 of file ProgramMetaData.cpp.
References imageData.
Referenced by restore().
getImageSize()
size_t ProgramMetaData::getImageSize () inline
Definition at line 60 of file ProgramMetaData.hpp.
References imageSize.
Referenced by restore().
operator delete()
void ProgramMetaData::operator delete (void * p) inline
Definition at line 52 of file ProgramMetaData.hpp.
References SystemInterpreter::releaseResultMemory().
operator new()
void * ProgramMetaData::operator new (size_t size, BufferClass * buff)
Allocate a combined metadata object with the flattened program data after it.
Parameters
size The size of the object
buff The appended buffer.
Returns
The storage allocated for the new instance.
Definition at line 70 of file ProgramMetaData.cpp.
References SystemInterpreter::allocateResultMemory().
processRestoreData()
bool ProgramMetaData::processRestoreData (RexxString * fileName, BufferClass * buffer, ProgramMetaData *& metaData) static
If restore data was base64 encoded, decode and copy the decoded data to the appropriate place in the received buffer
Parameters
fileName The name of the file being checked
buffer The buffer object containing the program data. If this is a compiled program that has been string encoded, the data will be decoded in place.
metaData The pointer to the start of the saved metadata.
Returns
true if this is a compiled program, false if this needs to be translated.
Definition at line 287 of file ProgramMetaData.cpp.
References compiledHeader, StringUtil::decodeBase64(), encodedHeader, Error_Program_unreadable_invalid_encoding, BufferClass::getData(), BufferClassBase::getDataLength(), OREF_NULL, reportException(), and Utilities::strnchr().
Referenced by restore().
restore()
RoutineClass * ProgramMetaData::restore (RexxString * name, BufferClass * buffer) static
Restore a saved program from the metadata.
Parameters
name The program name being restored
buffer A buffer object that contains the image data
Returns
The restored Routine object, or NULL if this was not a saved program image.
Definition at line 171 of file ProgramMetaData.cpp.
References getImageData(), getImageSize(), OREF_NULL, processRestoreData(), RoutineClass::restore(), and validate().
Referenced by MethodClass::restore(), and RoutineClass::restore().
validate()
bool ProgramMetaData::validate (RexxString * fileName)
Validate that this saved program image is valid for this interpreter.
Parameters
fileName The filename this metadata belongs to. Used for errors.
Returns
true if this is good data, false otherwise.
Definition at line 204 of file ProgramMetaData.cpp.
References bigEndian, LanguageParser::canExecute(), compiledHeader, Error_Program_unreadable_version, fileTag, Interpreter::getWordSize(), imageVersion, Interpreter::isBigEndian(), MAGICNUMBER, magicNumber, METAVERSION, reportException(), requiredLevel, and wordSize.
Referenced by restore().
write()
void ProgramMetaData::write (SysFile & target, BufferClass * program, bool encode)
Write the metadata to a file.
Parameters
handle The handle of the output file.
program The program buffer data (also written out).
Definition at line 231 of file ProgramMetaData.cpp.
References StringUtil::encodeBase64(), encodedHeader, encodingChunkLength, BufferClass::getData(), BufferClassBase::getDataLength(), getHeaderSize(), raw_string(), standardShebang, and SysFile::write().
Referenced by RoutineClass::save().
Member Data Documentation
bigEndian
uint16_t ProgramMetaData::bigEndian protected
Definition at line 82 of file ProgramMetaData.hpp.
Referenced by ProgramMetaData(), and validate().
encodingChunkLength
const size_t ProgramMetaData::encodingChunkLength = 72 static
Definition at line 68 of file ProgramMetaData.hpp.
Referenced by write().
fileTag
char ProgramMetaData::fileTag[16] protected
Definition at line 78 of file ProgramMetaData.hpp.
Referenced by ProgramMetaData(), and validate().
imageData
char ProgramMetaData::imageData[4] protected
Definition at line 94 of file ProgramMetaData.hpp.
Referenced by getDataSize(), getHeaderSize(), getImageData(), and ProgramMetaData().
imageSize
size_t ProgramMetaData::imageSize protected
Definition at line 93 of file ProgramMetaData.hpp.
Referenced by getDataSize(), getImageSize(), and ProgramMetaData().
imageVersion
uint16_t ProgramMetaData::imageVersion protected
Definition at line 80 of file ProgramMetaData.hpp.
Referenced by ProgramMetaData(), and validate().
magicNumber
uint16_t ProgramMetaData::magicNumber protected
Definition at line 79 of file ProgramMetaData.hpp.
Referenced by ProgramMetaData(), and validate().
pad
size_t ProgramMetaData::pad protected
Definition at line 86 of file ProgramMetaData.hpp.
requiredLevel
uint32_t ProgramMetaData::requiredLevel protected
Definition at line 83 of file ProgramMetaData.hpp.
Referenced by ProgramMetaData(), and validate().
reserved
uint32_t ProgramMetaData::reserved protected
Definition at line 84 of file ProgramMetaData.hpp.
Referenced by ProgramMetaData().
wordSize
uint16_t ProgramMetaData::wordSize protected
Definition at line 81 of file ProgramMetaData.hpp.
Referenced by ProgramMetaData(), and validate().
The documentation for this class was generated from the following files:
ProgramMetaData.hpp
ProgramMetaData.cpp