ooRexx: RexxActivation Class Reference
RexxActivation Class Reference
#include <RexxActivation.hpp>
Public Types
enum ExecutionState { ACTIVE , REPLIED , RETURNED }
enum TracePrefix {
TRACE_PREFIX_CLAUSE , TRACE_PREFIX_ERROR , TRACE_PREFIX_RESULT , TRACE_PREFIX_DUMMY ,
TRACE_PREFIX_VARIABLE , TRACE_PREFIX_DOTVARIABLE , TRACE_PREFIX_LITERAL , TRACE_PREFIX_FUNCTION ,
TRACE_PREFIX_PREFIX , TRACE_PREFIX_OPERATOR , TRACE_PREFIX_COMPOUND , TRACE_PREFIX_MESSAGE ,
TRACE_PREFIX_ARGUMENT , TRACE_PREFIX_ASSIGNMENT , TRACE_PREFIX_INVOCATION , TRACE_PREFIX_NAMESPACE ,
TRACE_PREFIX_KEYWORD , TRACE_PREFIX_ALIAS , TRACE_PREFIX_INVOCATION_EXIT , TRACE_OUTPUT_SOURCE = 30 ,
TRACE_OUTPUT
}
Public Types inherited from ActivationBase
enum GuardStatus { SCOPE_RELEASED = 0 , SCOPE_RESERVED = 1 }
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
RexxActivation (RESTORETYPE restoreType)
RexxActivation ()
RexxActivation (Activity *_activity, MethodClass *_method, RexxCode *_code)
RexxActivation (Activity *_activity, RoutineClass *_routine, RexxCode *_code, RexxString *calltype, RexxString *env, ActivationContext context)
RexxActivation (Activity *_activity, RexxActivation *_parent, RexxCode *_code, ActivationContext context)
void live (size_t) override
void liveGeneral (MarkReason reason) override
uint32_t getIdntfr ()
RexxObject * dispatch () override
wholenumber_t digits () override
wholenumber_t fuzz () override
bool form () override
void setDigits (wholenumber_t) override
void setFuzz (wholenumber_t) override
void setForm (bool) override
bool trap (RexxString *, DirectoryClass *) override
bool willTrap (RexxString *) override
void setObjNotify (MessageClass *) override
void termination () override
SecurityManager * getSecurityManager () override
bool isForwarded () override
const NumericSettings * getNumericSettings () override
RexxActivation * getRexxContext () override
RexxActivation * findRexxContext () override
RexxObject * getReceiver () override
bool isRexxContext () override
PackageClass * getPackage () override
MethodClass * getMethod ()
void inheritPackageSettings ()
void allocateStackFrame ()
void allocateLocalVariables ()
void guardOff ()
bool isInterpret ()
bool isInternalCall ()
bool isMethod ()
bool isRoutine ()
bool isProgram ()
bool isTopLevelCall ()
bool isProgramLevelCall ()
bool isInternalLevelCall ()
bool isProgramOrMethod ()
bool isMethodOrRoutine ()
RexxObject * run (RexxObject *_receiver, RexxString *msgname, RexxObject **_arglist, size_t _argcount, RexxInstruction *start, ProtectedObject &resultObj)
RexxObject * run (RexxObject **_arglist, size_t _argcount, ProtectedObject &_result)
void reply (RexxObject *)
RexxObject * forward (RexxObject *, RexxString *, RexxClass *, RexxObject **, size_t, bool)
void returnFrom (RexxObject *result)
void exitFrom (RexxObject *)
void procedureExpose (RexxVariableBase **variables, size_t count)
void expose (RexxVariableBase **variables, size_t count)
void autoExpose (RexxVariableBase **variables, size_t count)
void setTrace (const TraceSetting &)
void setTrace (RexxString *)
void raise (RexxString *, RexxObject *, RexxString *, RexxObject *, RexxObject *, DirectoryClass *)
void toggleAddress ()
void guardOn ()
void raiseExit (RexxString *, RexxObject *, RexxString *, RexxObject *, RexxObject *, DirectoryClass *)
ActivationBase * senderActivation (RexxString *conditionName)
RexxActivation * external ()
void interpret (RexxString *)
void signalTo (RexxInstruction *)
void guardWait ()
void debugSkip (wholenumber_t)
RexxString * traceSetting ()
void iterate (RexxString *)
void leaveLoop (RexxString *)
void trapOn (RexxString *, RexxInstructionTrapBase *, bool)
void trapOff (RexxString *, bool)
void setAddress (RexxString *, CommandIOConfiguration *config)
void signalValue (RexxString *)
RexxString * trapState (RexxString *)
void trapDelay (RexxString *)
void trapUndelay (RexxString *)
bool callExternalRexx (RexxString *, RexxObject **, size_t, RexxString *, ProtectedObject &)
RexxObject * externalCall (RoutineClass *&, RexxString *, RexxObject **, size_t, RexxString *, ProtectedObject &)
RexxObject * externalCall (RexxString *, RoutineClass *, RexxObject **, size_t, RexxString *, ProtectedObject &)
RexxObject * internalCall (RexxString *, RexxInstruction *, RexxObject **, size_t, ProtectedObject &)
RexxObject * internalCallTrap (RexxString *, RexxInstruction *, DirectoryClass *, ProtectedObject &)
bool callMacroSpaceFunction (RexxString *, RexxObject **, size_t, RexxString *, int, ProtectedObject &)
RexxString * resolveProgramName (RexxString *name, ResolveType type)
RexxClass * findClass (RexxString *name)
RexxObject * resolveDotVariable (RexxString *name, RexxObject *&)
void command (RexxString *, RexxString *, CommandIOConfiguration *config)
int64_t getElapsed ()
RexxDateTime getTime ()
RexxInteger * random (RexxInteger *, RexxInteger *, RexxInteger *)
size_t currentLine ()
void arguments (RexxObject *)
void traceValue (RexxObject *, TracePrefix)
void traceCompoundValue (TracePrefix prefix, RexxString *stemName, RexxInternalObject **tails, size_t tailCount, CompoundVariableTail &tail)
void traceCompoundValue (TracePrefix prefix, RexxString *stem, RexxInternalObject **tails, size_t tailCount, const char *marker, RexxObject *value)
void traceTaggedValue (TracePrefix prefix, const char *tagPrefix, bool quoteTag, RexxString *tag, const char *marker, RexxObject *value)
void traceOperatorValue (TracePrefix prefix, const char *tag, RexxObject *value)
void traceSourceString ()
void traceClause (RexxInstruction *, TracePrefix)
void traceEntry ()
void traceEntryOrExit (TracePrefix)
void resetElapsed ()
RexxString * formatTrace (RexxInstruction *, PackageClass *)
RexxString * getTraceBack ()
DirectoryClass * local ()
RexxString * formatSourcelessTraceLine (RexxString *packageName)
ArrayClass * getStackFrames (bool skipFirst)
void implicitExit ()
void unwindTrap (RexxActivation *)
RexxString * sourceString ()
StringTable * getPublicRoutines ()
void debugInterpret (RexxString *)
bool doDebugPause ()
void processClauseBoundary ()
bool halt (RexxString *)
void externalTraceOn ()
void externalTraceOff ()
void yield ()
void propagateExit (RexxObject *)
void setDefaultAddress (RexxString *)
bool internalMethod ()
void loadRequires (RequiresDirective *)
void loadLibrary (RexxString *target, RexxInstruction *instruction, PackageClass *package)
RexxObject * rexxVariable (RexxString *)
void pushEnvironment (RexxObject *)
RexxObject * popEnvironment ()
bool processTraps ()
void mergeTraps (QueueClass *)
uint64_t getRandomSeed (RexxInteger *)
VariableDictionary * getObjectVariables ()
StringTable * getLabels ()
RexxString * getProgramName ()
const char * displayProgramName ()
RexxObject * popControl ()
void pushControl (RexxObject *)
void closeStreams ()
void checkTrapTable ()
void checkIOConfigTable ()
CommandIOConfiguration * getIOConfig (RexxString *environment)
void addIOConfig (RexxString *environment, CommandIOConfiguration *config)
CommandIOContext * resolveAddressIOConfig (RexxString *address, CommandIOConfiguration *localConfig)
RexxObject * resolveStream (RexxString *name, bool input, Protected< RexxString > &fullName, bool *added)
StringTable * getStreams ()
RexxObject * novalueHandler (RexxString *)
RexxVariableBase * retriever (RexxString *)
RexxVariableBase * directRetriever (RexxString *)
RexxObject * handleNovalueEvent (RexxString *name, RexxObject *defaultValue, RexxVariable *variable)
PackageClass * getPackageObject ()
PackageClass * getEffectivePackageObject ()
RexxObject * getLocalEnvironment (RexxString *name)
void setReturnStatus (ReturnStatus status)
void setCallType (RexxString *type)
void pushBlockInstruction (DoBlock *block)
void popBlockInstruction ()
DoBlock * topBlockInstruction ()
void terminateBlockInstruction (size_t _indent)
void terminateBlockInstruction ()
void newBlockInstruction (DoBlock *block)
void removeBlockInstruction ()
void addBlockInstruction ()
bool hasActiveBlockInstructions ()
bool inMethod ()
void indent ()
void unindent ()
void unindentTwice ()
void setIndent (size_t v)
size_t getIndent ()
bool tracingIntermediates ()
Activity * getActivity ()
RexxString * getMessageName ()
RexxString * getCallname ()
RexxInstruction * getCurrent ()
void getSettings (ActivationSettings &s)
void putSettings (ActivationSettings &s)
RexxString * getAddress ()
DirectoryClass * getConditionObj ()
void setConditionObj (DirectoryClass *condition)
RexxInstruction * getNext ()
void setNext (RexxInstruction *v)
void setCurrent (RexxInstruction *v)
ExpressionStack * getStack ()
void traceIntermediate (RexxObject *v, TracePrefix p)
void traceArgument (RexxObject *v)
void traceVariable (RexxString *n, RexxObject *v)
void traceDotVariable (RexxString *n, RexxObject *v)
void traceSpecialDotVariable (RexxString *n, RexxObject *v)
void traceFunction (RexxString *n, RexxObject *v)
void traceMessage (RexxString *n, RexxObject *v)
void traceOperator (const char *n, RexxObject *v)
void tracePrefix (const char *n, RexxObject *v)
void traceAssignment (RexxString *n, RexxObject *v)
void traceClassResolution (RexxString *n, RexxString *c, RexxObject *v)
void traceCompoundName (RexxString *stemVar, RexxInternalObject **tails, size_t tailCount, CompoundVariableTail &tail)
void traceCompoundName (RexxString *stemVar, RexxInternalObject **tails, size_t tailCount, RexxString *tail)
void traceCompound (RexxString *stemVar, RexxInternalObject **tails, size_t tailCount, RexxObject *value)
void traceCompoundAssignment (RexxString *stemVar, RexxInternalObject **tails, size_t tailCount, RexxObject *value)
void clearTraceSettings ()
bool tracingResults ()
bool tracingAll ()
bool tracingLabels ()
bool inDebug ()
void traceResult (RexxObject *v)
void traceKeywordResult (RexxString *k, RexxObject *v)
void traceVariableAlias (RexxString *k, RexxString *v)
void traceResultValue (RexxObject *v)
bool tracingInstructions ()
bool tracingErrors ()
bool tracingFailures ()
void traceInstruction (RexxInstruction *v)
void traceLabel (RexxInstruction *v)
void traceCommand (RexxInstruction *v)
bool tracingCommands ()
bool pausingInstructions ()
void pauseInstruction ()
int conditionalPauseInstruction ()
void pauseLabel ()
void pauseCommand ()
void resetDebug ()
bool isErrorSyntaxEnabled ()
void disableErrorSyntax ()
bool isFailureSyntaxEnabled ()
void disableFailureSyntax ()
bool isLostdigitsSyntaxEnabled ()
void disableLostdigitsSyntax ()
bool isNostringSyntaxEnabled ()
void disableNostringSyntax ()
bool isNotreadySyntaxEnabled ()
void disableNotreadySyntax ()
bool isNovalueSyntaxEnabled ()
void disableNovalueSyntax ()
void stopExecution (ExecutionState state)
bool noTracing (RexxObject *value)
bool noTracing ()
SecurityManager * getEffectiveSecurityManager ()
bool isTopLevel ()
bool isGuarded ()
void setGuarded ()
bool isObjectScopeLocked ()
unsigned short getReserveCount ()
VariableDictionary * getVariableDictionary ()
void enableExternalTrace ()
void disableExternalTrace ()
bool isElapsedTimerReset ()
void setElapsedTimerInvalid ()
void setElapsedTimerValid ()
RexxObject ** getMethodArgumentList ()
size_t getMethodArgumentCount ()
RexxObject * getMethodArgument (size_t position)
ArrayClass * getArguments ()
RexxObject ** getProgramArgumentlist ()
size_t getProgramArgumentCount ()
RexxObject * getProgramArgument (size_t position)
RexxObject * getContextObject ()
RexxObject * getContextLine ()
size_t getContextLineNumber ()
RexxObject * getContextReturnStatus ()
StackFrameClass * createStackFrame ()
VariableDictionary * getLocalVariables ()
DirectoryClass * getAllLocalVariables ()
RexxVariable * getLocalVariable (RexxString *name, size_t index)
RexxVariable * getLocalStemVariable (RexxString *name, size_t index)
StemClass * getLocalStem (RexxString *name, size_t index)
void dropLocalStem (RexxString *name, size_t index)
bool localStemVariableExists (RexxString *stemName, size_t index)
bool localVariableExists (RexxString *name, size_t index)
void putLocalVariable (RexxVariable *variable, size_t index)
void updateLocalVariable (RexxVariable *variable)
void setLocalVariable (RexxString *name, size_t index, RexxObject *value)
void dropLocalVariable (RexxString *name, size_t index)
void aliasLocalVariable (RexxString *name, size_t index, RexxVariable *variable)
RexxObject * evaluateLocalCompoundVariable (RexxString *stemName, size_t index, RexxInternalObject **tail, size_t tailCount)
RexxObject * getLocalCompoundVariableValue (RexxString *stemName, size_t index, RexxInternalObject **tail, size_t tailCount)
RexxObject * getLocalCompoundVariableRealValue (RexxString *localstem, size_t index, RexxInternalObject **tail, size_t tailCount)
CompoundTableElement * getLocalCompoundVariable (RexxString *stemName, size_t index, RexxInternalObject **tail, size_t tailCount)
CompoundTableElement * exposeLocalCompoundVariable (RexxString *stemName, size_t index, RexxInternalObject **tail, size_t tailCount)
bool localCompoundVariableExists (RexxString *stemName, size_t index, RexxInternalObject **tail, size_t tailCount)
void assignLocalCompoundVariable (RexxString *stemName, size_t index, RexxInternalObject **tail, size_t tailCount, RexxObject *value)
void setLocalCompoundVariable (RexxString *stemName, size_t index, RexxInternalObject **tail, size_t tailCount, RexxObject *value)
void dropLocalCompoundVariable (RexxString *stemName, size_t index, RexxInternalObject **tail, size_t tailCount)
bool novalueEnabled ()
RexxVariable * newLocalVariable (RexxString *name)
void cleanupLocalVariables ()
void setLocalVariableDictionary (VariableDictionary *dict)
void sayOutput (RexxString *line)
RexxString * pullInput ()
RexxString * lineIn ()
void queue (RexxString *, Activity::QueueOrder)
StringTable * getFileNames ()
void removeFileName (RexxString *name)
bool notCaseSensitive ()
void displayUsingTraceOutput (Activity *, RexxString *)
Public Member Functions inherited from ActivationBase
ActivationBase ()
ActivationBase (RESTORETYPE restoreType)
virtual bool isStackBase ()
void setPreviousStackFrame (ActivationBase *p)
ActivationBase * getPreviousStackFrame ()
BaseExecutable * getExecutable ()
BaseExecutable * getExecutableObject ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual void flatten (Envelope *)
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static RoutineClass * getMacroCode (RexxString *macroName)
static uint64_t RANDOMIZE (uint64_t seed)
static StringTable * getStackFrameAsStringTable (StackFrameClass *)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static const size_t yieldInstructions = 50
static const uint64_t RANDOM_FACTOR = 25214903917LL
static const uint64_t RANDOM_ADDER = 11LL
static const size_t SIZE_BITS = sizeof(void *) * 8
static const size_t DefaultRandomMin = 0
static const size_t DefaultRandomMax = 999
static const size_t MaxRandomRange = 999999999
static const char * VALUE_MARKER = " => "
static const char * ASSIGNMENT_MARKER = " <= "
Protected Member Functions
void processTraceInfo (Activity *, RexxString *traceLine, TracePrefix tracePrefix, RexxString *tag, RexxObject *value)
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Static Protected Member Functions
static StringTable * createTraceObject (Activity *, RexxActivation *, RexxString *line, TracePrefix tracePrefix, RexxString *tag, RexxObject *value)
Protected Attributes
ActivationSettings settings
ExpressionStack stack
RexxCode * code
PackageClass * packageObject
RexxClass * scope
RexxObject * receiver
Activity * activity
RexxActivation * parent
RexxObject ** argList
size_t argCount
DoBlock * doStack
RexxInstruction * current
RexxInstruction * next
bool debugPause
bool clauseBoundary
bool traceEntryAllowed
bool traceEntryDone
RexxObject * result
ArrayClass * trapInfo
RexxContext * contextObject
ExecutionState executionState
ActivationContext activationContext
MessageClass * notifyObject
QueueClass * environmentList
QueueClass * conditionQueue
uint64_t randomSeed
bool randomSet
size_t blockNest
size_t instructionCount
uint32_t idntfr
Protected Attributes inherited from ActivationBase
ActivationBase * previous
BaseExecutable * executable
GuardStatus objectScope
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Detailed Description
An activation of a section of Rexx code.
Definition at line 74 of file RexxActivation.hpp.
Member Enumeration Documentation
ExecutionState
enum RexxActivation::ExecutionState
Enumerator
ACTIVE
REPLIED
RETURNED
Definition at line 79 of file RexxActivation.hpp.
TracePrefix
enum RexxActivation::TracePrefix
An enumeration of the different trace prefixes. The trace prefix table must match these.
Enumerator
TRACE_PREFIX_CLAUSE
TRACE_PREFIX_ERROR
TRACE_PREFIX_RESULT
TRACE_PREFIX_DUMMY
TRACE_PREFIX_VARIABLE
TRACE_PREFIX_DOTVARIABLE
TRACE_PREFIX_LITERAL
TRACE_PREFIX_FUNCTION
TRACE_PREFIX_PREFIX
TRACE_PREFIX_OPERATOR
TRACE_PREFIX_COMPOUND
TRACE_PREFIX_MESSAGE
TRACE_PREFIX_ARGUMENT
TRACE_PREFIX_ASSIGNMENT
TRACE_PREFIX_INVOCATION
TRACE_PREFIX_NAMESPACE
TRACE_PREFIX_KEYWORD
TRACE_PREFIX_ALIAS
TRACE_PREFIX_INVOCATION_EXIT
TRACE_OUTPUT_SOURCE
TRACE_OUTPUT
Definition at line 90 of file RexxActivation.hpp.
Constructor & Destructor Documentation
RexxActivation() [1/5]
RexxActivation::RexxActivation (RESTORETYPE restoreType) inline
Definition at line 121 of file RexxActivation.hpp.
RexxActivation() [2/5]
RexxActivation::RexxActivation ()
Initialize an activation for direct caching in the activation cache. At this time, this is not an executable activation
Definition at line 117 of file RexxActivation.cpp.
References RexxInternalObject::setHasNoReferences().
RexxActivation() [3/5]
RexxActivation::RexxActivation (Activity * _activity, MethodClass * _method, RexxCode * _code)
Initialize an activation for a method invocation.
Parameters
_activity The activity we're running under.
_method The method being invoked.
_code The code to execute.
Definition at line 130 of file RexxActivation.cpp.
References activationContext, ACTIVE, activity, allocateLocalVariables(), allocateStackFrame(), ActivationSettings::alternateAddress, ActivationSettings::calltype, RexxInternalObject::clearObject(), code, ActivationSettings::currentAddress, ActivationBase::executable, executionState, InterpreterInstance::getDefaultEnvironment(), Activity::getInstance(), Activity::getInstanceSecurityManager(), BaseExecutable::getPackageObject(), Activity::getRandomSeed(), MethodClass::getScope(), RexxCode::getSecurityManager(), inheritPackageSettings(), ActivationSettings::intermediateTrace, MethodClass::isGuarded(), METHODCALL, ActivationBase::objectScope, OREF_NULL, packageObject, parent, ActivationSettings::parentCode, randomSeed, scope, ActivationBase::SCOPE_RELEASED, ActivationSettings::securityManager, setGuarded(), and settings.
RexxActivation() [4/5]
RexxActivation::RexxActivation (Activity * _activity, RoutineClass * _routine, RexxCode * _code, RexxString * calltype, RexxString * env, ActivationContext context)
Create a top-level activation of Rexx code. This will either a toplevel program or an external call.
Parameters
_activity The current thread we're running on.
_routine The routine to invoke.
_code The code object to be executed.
calltype Type type of call being made (function or subroutine)
env The default address environment
context The type of call context.
Definition at line 267 of file RexxActivation.cpp.
References activationContext, ACTIVE, activity, allocateLocalVariables(), allocateStackFrame(), ActivationSettings::alternateAddress, ActivationSettings::calltype, RexxInternalObject::clearObject(), code, ActivationSettings::currentAddress, ActivationBase::executable, executionState, InterpreterInstance::getDefaultEnvironment(), Activity::getInstance(), Activity::getInstanceSecurityManager(), BaseExecutable::getPackageObject(), Activity::getRandomSeed(), RexxCode::getSecurityManager(), inheritPackageSettings(), ActivationSettings::intermediateTrace, ActivationBase::objectScope, OREF_NULL, packageObject, parent, ActivationSettings::parentCode, randomSeed, ActivationBase::SCOPE_RELEASED, ActivationSettings::securityManager, setDefaultAddress(), and settings.
RexxActivation() [5/5]
RexxActivation::RexxActivation (Activity * _activity, RexxActivation * _parent, RexxCode * _code, ActivationContext context)
Create a new Rexx activation for an internal level call. An internal level call is an internal call, a call trap, an Interpret statement, or a debug pause execution.
Parameters
_activity The current activity.
_parent The parent activation.
_code The code to be executed. For interpret and debug pauses, this is a new code object. For call activations, this is the parent code object.
context The type of call being made.
Definition at line 192 of file RexxActivation.cpp.
References activationContext, ACTIVE, activity, allocateStackFrame(), RexxInternalObject::clearObject(), code, DEBUGPAUSE, debugPause, ActivationBase::executable, executionState, ActivationBase::getExecutable(), BaseCode::getPackageObject(), BaseExecutable::getPackageObject(), ActivationSettings::intermediateTrace, INTERNALCALL, INTERPRET, isInterpret(), ActivationSettings::localVariables, ActivationBase::objectScope, packageObject, parent, putSettings(), ActivationBase::SCOPE_RELEASED, RexxLocalVariables::setNested(), ActivationSettings::setReplyIssued(), settings, ActivationSettings::setTrapsCopied(), ActivationSettings::timeStamp, ActivationSettings::traceIndent, and RexxDateTime::valid.
Member Function Documentation
addBlockInstruction()
void RexxActivation::addBlockInstruction () inline
Definition at line 315 of file RexxActivation.hpp.
References blockNest, and indent().
Referenced by RexxInstructionSimpleDo::execute().
addIOConfig()
void RexxActivation::addIOConfig (RexxString * environment, CommandIOConfiguration * config)
Add an i/o configuration to the config table.
Parameters
environment The name of the address environment
config The config we're adding
Definition at line 1672 of file RexxActivation.cpp.
References checkIOConfigTable(), ActivationSettings::ioConfigs, HashCollection::put(), settings, and RexxString::upper().
Referenced by setAddress().
aliasLocalVariable()
void RexxActivation::aliasLocalVariable (RexxString * name, size_t index, RexxVariable * variable) inline
Definition at line 546 of file RexxActivation.hpp.
References RexxLocalVariables::aliasVariable(), ActivationSettings::localVariables, and settings.
Referenced by RexxStemVariable::alias(), and RexxSimpleVariable::alias().
allocateLocalVariables()
void RexxActivation::allocateLocalVariables ()
Allocate a new local variable frame.
Definition at line 410 of file RexxActivation.cpp.
References activity, Activity::allocateLocalVariableFrame(), code, RexxCode::getLocalVariableSize(), RexxLocalVariables::init(), ActivationSettings::localVariables, and settings.
Referenced by RexxActivation().
allocateStackFrame()
void RexxActivation::allocateStackFrame ()
Allocate a stack frame for this activation to use for the evaluation stack.
Definition at line 397 of file RexxActivation.cpp.
References activity, Activity::allocateStackFrame(), code, RexxCode::getMaxStackSize(), RexxInternalObject::setHasNoReferences(), RexxInternalObject::setHasReferences(), and stack.
Referenced by RexxActivation().
arguments()
void RexxActivation::arguments (RexxObject *)
Referenced by callExternalRexx(), callMacroSpaceFunction(), createStackFrame(), externalCall(), forward(), and internalCall().
assignLocalCompoundVariable()
void RexxActivation::assignLocalCompoundVariable (RexxString * stemName, size_t index, RexxInternalObject ** tail, size_t tailCount, RexxObject * value)
Perform an assignment to a compound variable in the local context.
Parameters
stemName The stem variable name.
index The index of the stem variable (if known)
tail The array of tail elements.
tailCount The count of tail elements.
value The value to assign.
Definition at line 4894 of file RexxActivation.cpp.
References getLocalStem(), StemClass::setCompoundVariable(), traceCompoundAssignment(), traceCompoundName(), and tracingIntermediates().
Referenced by RexxCompoundVariable::assign().
autoExpose()
void RexxActivation::autoExpose (RexxVariableBase ** variables, size_t count)
Turn on autoexpose as the result of a USE LOCAL instruction.
Parameters
variables The list of variables to declose as local variables.
count The variable count.
Definition at line 1269 of file RexxActivation.cpp.
References getLocalVariable(), getObjectVariables(), RexxInternalObject::getRealValue(), ActivationSettings::localVariables, RexxLocalVariables::setAutoExpose(), settings, VARIABLE_RC, VARIABLE_RESULT, VARIABLE_SELF, VARIABLE_SIGL, and VARIABLE_SUPER.
Referenced by RexxInstructionUseLocal::execute().
callExternalRexx()
bool RexxActivation::callExternalRexx (RexxString * target, RexxObject ** arguments, size_t argcount, RexxString * calltype, ProtectedObject & resultObj)
Call an external program as a function or subroutine.
Parameters
target The target function name.
parent The name of the parent program (used for resolving extensions).
_arguments The arguments to the call.
_argcount The count of arguments for the call.
calltype The type of call (FUNCTION or SUBROUTINE)
resultObj The returned result.
Returns
True if an external program was located and called. false for any failures.
Definition at line 3094 of file RexxActivation.cpp.
References activity, arguments(), callExternalRexx(), LanguageParser::createProgramFromFile(), ActivationSettings::currentAddress, EXTERNALCALL, isInterpret(), Protected< objType >::isNull(), RexxCode::mergeRequired(), parent, ActivationSettings::parentCode, RESOLVE_DEFAULT, resolveProgramName(), and settings.
Referenced by callExternalRexx(), and SystemInterpreter::invokeExternalFunction().
callMacroSpaceFunction()
bool RexxActivation::callMacroSpaceFunction (RexxString * target, RexxObject ** arguments, size_t argcount, RexxString * calltype, int order, ProtectedObject & _result)
Attempt to call a function stored in the macrospace.
Parameters
target The target function name.
arguments The argument pointer.
argcount The count of arguments,
calltype The type of call (FUNCTION or SUBROUTINE)
order The macrospace order flag.
result The function result.
Returns
true if the macrospace function was located and called.
Definition at line 2962 of file RexxActivation.cpp.
References activity, arguments(), EXTERNALCALL, getMacroCode(), getPackageObject(), RexxString::getStringData(), PackageClass::mergeRequired(), OREF_NULL, and RexxQueryMacro().
Referenced by SystemInterpreter::invokeExternalFunction().
checkIOConfigTable()
void RexxActivation::checkIOConfigTable ()
Create/copy an io config table as needed
Definition at line 1624 of file RexxActivation.cpp.
References HashCollection::copy(), ActivationSettings::ioConfigs, isInternalCall(), ActivationSettings::isIOConfigCopied(), new_string_table(), OREF_NULL, ActivationSettings::setIOConfigCopied(), and settings.
Referenced by addIOConfig().
checkTrapTable()
void RexxActivation::checkTrapTable ()
Create/copy a trap table as needed
Definition at line 1497 of file RexxActivation.cpp.
References ActivationSettings::areTrapsCopied(), HashCollection::copy(), isInternalCall(), new_string_table(), OREF_NULL, settings, ActivationSettings::setTrapsCopied(), and ActivationSettings::traps.
Referenced by trapDelay(), trapOff(), trapOn(), and trapUndelay().
cleanupLocalVariables()
void RexxActivation::cleanupLocalVariables () inline
Definition at line 571 of file RexxActivation.hpp.
References RexxLocalVariables::getNestedDictionary(), isInternalLevelCall(), RexxLocalVariables::isNested(), ActivationSettings::localVariables, parent, setLocalVariableDictionary(), and settings.
Referenced by termination().
clearTraceSettings()
void RexxActivation::clearTraceSettings () inline
Definition at line 364 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, ActivationSettings::packageSettings, settings, TraceSetting::setTraceOff(), and PackageSetting::traceSettings.
closeStreams()
void RexxActivation::closeStreams ()
Close any streams opened by the I/O builtin functions
Definition at line 4674 of file RexxActivation.cpp.
References HashContents::TableIterator::isAvailable(), isProgramOrMethod(), HashCollection::iterator(), OREF_NULL, result, settings, and ActivationSettings::streams.
Referenced by termination().
command()
void RexxActivation::command (RexxString * address, RexxString * commandString, CommandIOConfiguration * ioConfig)
Issue a command to a named host evironment
Parameters
address The target address
commandString The command to issue
ioConfig A potential I/O redirection setup for this command.
Definition at line 4335 of file RexxActivation.cpp.
References activity, CommandHandler::call(), Activity::callCommandExit(), RexxString::concatToCstring(), RexxString::concatWithCstring(), Activity::createConditionObject(), current, debugPause, doDebugPause(), Error_Execution_error_syntax, Error_Execution_failure_syntax, DirectoryClass::get(), inDebug(), isErrorSyntaxEnabled(), isFailureSyntaxEnabled(), new_integer(), RexxInternalObject::numberValue(), OREF_NULL, DirectoryClass::put(), Activity::raiseCondition(), reportException(), resolveAddressIOConfig(), Activity::resolveCommandHandler(), RETURN_STATUS_ERROR, RETURN_STATUS_FAILURE, RETURN_STATUS_NORMAL, RXSUBCOM_NOTREG, setLocalVariable(), setReturnStatus(), RexxString::strCompare(), RexxObject::stringValue(), TheFalseObject, TRACE_PREFIX_CLAUSE, TRACE_PREFIX_ERROR, TRACE_PREFIX_RESULT, traceClause(), traceValue(), tracingAll(), tracingCommands(), tracingErrors(), tracingFailures(), and VARIABLE_RC.
Referenced by RexxInstructionAddress::execute(), and RexxInstructionCommand::execute().
conditionalPauseInstruction()
int RexxActivation::conditionalPauseInstruction () inline
Definition at line 382 of file RexxActivation.hpp.
References doDebugPause(), and pausingInstructions().
Referenced by RexxInstructionInterpret::execute(), RexxInstructionSelect::execute(), RexxInstructionSelectCase::execute(), and RexxBlockInstruction::handleDebugPause().
createStackFrame()
StackFrameClass * RexxActivation::createStackFrame ()
Create a stack frame for exception tracebacks.
Returns
A StackFrame instance for this activation.
Definition at line 4989 of file RexxActivation.cpp.
References arguments(), StackFrameClass::FRAME_INTERNAL_CALL, StackFrameClass::FRAME_INTERPRET, StackFrameClass::FRAME_METHOD, StackFrameClass::FRAME_PROGRAM, StackFrameClass::FRAME_ROUTINE, getArguments(), getContextLineNumber(), getContextObject(), ActivationBase::getExecutableObject(), getIdntfr(), getMessageName(), getTraceBack(), isInternalCall(), isInterpret(), isMethod(), isProgram(), isRoutine(), OREF_NULL, receiver, and type.
Referenced by RexxActivationFrame::createStackFrame(), and createTraceObject().
createTraceObject()
StringTable * RexxActivation::createTraceObject (Activity * activity, RexxActivation * activation, RexxString * traceline, TracePrefix tracePrefix, RexxString * tag, RexxObject * value) static protected
Create an instance of TraceObject and fill in trace information, depending on the tracePrefix.
Parameters
traceLine a RexxString
tracePrefix a TracePrefix enum
tag a RexxString, e.g. the variable name
value a RexxObject
Returns
the created TraceObject (a StringTable)
Definition at line 5143 of file RexxActivation.cpp.
References activity, createStackFrame(), Activity::getIdntfr(), getIdntfr(), InterpreterInstance::getIdntfr(), Activity::getInstance(), getReceiver(), getReserveCount(), getRexxPackageTraceObject(), getStackFrameAsStringTable(), getVariableDictionary(), isGuarded(), isMethod(), isObjectScopeLocked(), RexxObject::messageSend(), new_integer(), new_string_table(), OREF_NULL, RexxInternalObject::requestString(), result, TheFalseObject, TheNilObject, TheTrueObject, TRACE_PREFIX_ASSIGNMENT, TRACE_PREFIX_INVOCATION, TRACE_PREFIX_KEYWORD, TRACE_PREFIX_VARIABLE, and tracePrefix().
Referenced by processTraceInfo().
currentLine()
size_t RexxActivation::currentLine ()
Return the line number of the current instruction
Returns
The line number of the current instruction.
Definition at line 1197 of file RexxActivation.cpp.
References current, RexxInstruction::getLineNumber(), and OREF_NULL.
Referenced by Activity::reraiseException().
debugInterpret()
void RexxActivation::debugInterpret (RexxString * codestring)
Interpret a string of debug input.
Parameters
codestring The code string to interpret
Definition at line 2759 of file RexxActivation.cpp.
References activity, argCount, argList, code, current, ActivityManager::currentActivity, DEBUGPAUSE, debugPause, RexxInstruction::getLineNumber(), RexxCode::interpret(), ActivationSettings::messageName, ActivityManager::newActivation(), OREF_NULL, Activity::pushStackFrame(), receiver, Activity::requestAccess(), run(), and settings.
Referenced by doDebugPause().
debugSkip()
void RexxActivation::debugSkip (wholenumber_t skipCount)
Process a numeric "debug skip" TRACE instruction to suppress pauses or tracing for a given number of instructions.
Parameters
skipCount The number of clauses to skip.
Definition at line 905 of file RexxActivation.cpp.
References debugPause, Error_Invalid_trace_debug, reportException(), ActivationSettings::setDebugBypass(), settings, ActivationSettings::setTraceSuppressed(), and ActivationSettings::traceSkip.
Referenced by RexxInstructionTrace::execute().
digits()
wholenumber_t RexxActivation::digits () override virtual
Return the current digits setting
Returns
The package digits setting
Reimplemented from ActivationBase.
Definition at line 2188 of file RexxActivation.cpp.
References PackageSetting::getDigits(), ActivationSettings::packageSettings, and settings.
Referenced by NativeActivation::digits(), RexxInstructionNumeric::execute(), RexxContext::getDigits(), and ForLoop::setup().
directRetriever()
RexxVariableBase* RexxActivation::directRetriever (RexxString *)
disableErrorSyntax()
void RexxActivation::disableErrorSyntax () inline
Definition at line 391 of file RexxActivation.hpp.
References PackageSetting::disableErrorSyntax(), ActivationSettings::packageSettings, and settings.
Referenced by trapOff(), and trapOn().
disableExternalTrace()
void RexxActivation::disableExternalTrace ()
Turn on external trace at program startup (e.g, because RXTRACE is set)
Definition at line 4106 of file RexxActivation.cpp.
References setTrace(), and TraceSetting::setTraceOff().
Referenced by processClauseBoundary().
disableFailureSyntax()
void RexxActivation::disableFailureSyntax () inline
Definition at line 393 of file RexxActivation.hpp.
References PackageSetting::disableFailureSyntax(), ActivationSettings::packageSettings, and settings.
Referenced by trapOff(), and trapOn().
disableLostdigitsSyntax()
void RexxActivation::disableLostdigitsSyntax () inline
Definition at line 395 of file RexxActivation.hpp.
References PackageSetting::disableLostdigitsSyntax(), ActivationSettings::packageSettings, and settings.
Referenced by trapOff(), and trapOn().
disableNostringSyntax()
void RexxActivation::disableNostringSyntax () inline
Definition at line 397 of file RexxActivation.hpp.
References PackageSetting::disableNostringSyntax(), ActivationSettings::packageSettings, and settings.
Referenced by trapOff(), and trapOn().
disableNotreadySyntax()
void RexxActivation::disableNotreadySyntax () inline
Definition at line 399 of file RexxActivation.hpp.
References PackageSetting::disableNotreadySyntax(), ActivationSettings::packageSettings, and settings.
Referenced by trapOff(), and trapOn().
disableNovalueSyntax()
void RexxActivation::disableNovalueSyntax () inline
Definition at line 401 of file RexxActivation.hpp.
References PackageSetting::disableNovalueSyntax(), ActivationSettings::packageSettings, and settings.
Referenced by trapOff(), and trapOn().
dispatch()
RexxObject * RexxActivation::dispatch () override virtual
Re-dispatch an activation after a REPLY
Returns
The result object.
Reimplemented from ActivationBase.
Definition at line 435 of file RexxActivation.cpp.
References argCount, argList, ActivationSettings::messageName, OREF_NULL, receiver, run(), and settings.
displayProgramName()
const char * RexxActivation::displayProgramName ()
Handy method for displaying the current program name in the debugger.
Returns
The string name of the program source.
Definition at line 4543 of file RexxActivation.cpp.
References code, RexxCode::getProgramName(), and RexxString::getStringData().
displayUsingTraceOutput()
void RexxActivation::displayUsingTraceOutput (Activity * activity, RexxString * traceLine)
Outputs the line using the trace output destination.
Parameters
traceLine the trace line to display
Definition at line 5238 of file RexxActivation.cpp.
References activity, NULLOBJECT, processTraceInfo(), and TRACE_OUTPUT.
Referenced by Activity::display(), and Activity::displayDebug().
doDebugPause()
bool RexxActivation::doDebugPause ()
Process an individual debug pause for an instruction
Returns
true if the instruction should re-execute, false otherwise.
Definition at line 4182 of file RexxActivation.cpp.
References activity, code, current, debugInterpret(), debugPause, RexxString::getChar(), RexxString::getLength(), Interpreter::getMessageText(), ActivationSettings::isDebugBypassed(), RexxCode::isTraceable(), Message_Translations_debug_prompt, next, NULLOBJECT, processTraceInfo(), ActivationSettings::setDebugBypass(), ActivationSettings::setDebugPromptIssued(), settings, ActivationSettings::setTraceSuppressed(), TRACE_OUTPUT, Activity::traceInput(), ActivationSettings::traceSkip, and ActivationSettings::wasDebugPromptIssued().
Referenced by command(), conditionalPauseInstruction(), pauseCommand(), pauseInstruction(), and pauseLabel().
dropLocalCompoundVariable()
void RexxActivation::dropLocalCompoundVariable (RexxString * stemName, size_t index, RexxInternalObject ** tail, size_t tailCount)
Drop a compound variable in the local context.
Parameters
stemName The name of the stem variable.
index The index (if known)
tail The array of tail elements.
tailCount The count of tail elements.
Definition at line 4934 of file RexxActivation.cpp.
References StemClass::dropCompoundVariable(), and getLocalStem().
Referenced by RexxCompoundVariable::drop().
dropLocalStem()
void RexxActivation::dropLocalStem (RexxString * name, size_t index) inline
Definition at line 501 of file RexxActivation.hpp.
References getLocalStemVariable(), and RexxVariable::set().
Referenced by RexxStemVariable::drop().
dropLocalVariable()
void RexxActivation::dropLocalVariable (RexxString * name, size_t index) inline
Definition at line 540 of file RexxActivation.hpp.
References RexxVariable::drop(), and getLocalVariable().
Referenced by RexxSimpleVariable::drop(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxInstructionForward::execute(), and RexxInstructionMessage::execute().
enableExternalTrace()
void RexxActivation::enableExternalTrace ()
Turn on external trace at program startup (e.g, because RXTRACE is set)
Definition at line 4093 of file RexxActivation.cpp.
References TraceSetting::setExternalTrace(), and setTrace().
Referenced by processClauseBoundary(), and SysInterpreterInstance::setupProgram().
evaluateLocalCompoundVariable()
RexxObject * RexxActivation::evaluateLocalCompoundVariable (RexxString * stemName, size_t index, RexxInternalObject ** tail, size_t tailCount)
Evaluate a compound variable from the local context.
Parameters
stemName The name of the stem.
index The stem variable index (if known)
tail The evaluated tail.
tailCount The count of tail elements.
Returns
The value of the variable.
Definition at line 4774 of file RexxActivation.cpp.
References StemClass::evaluateCompoundVariableValue(), getLocalStem(), traceCompound(), traceCompoundName(), and tracingIntermediates().
Referenced by RexxCompoundVariable::evaluate().
exitFrom()
void RexxActivation::exitFrom (RexxObject * resultObj)
Process a REXX exit instruction
Parameters
resultObj The result object from the exit (optional)
Definition at line 1375 of file RexxActivation.cpp.
References activity, Activity::callTerminationExit(), ActivityManager::currentActivity, Error_Execution_reply_exit, exitFrom(), Activity::getCurrentRexxFrame(), isProgramLevelCall(), ActivationSettings::isReplyIssued(), isTopLevel(), isTopLevelCall(), OREF_NULL, Activity::popStackFrame(), reportException(), resetDebug(), result, RETURNED, settings, stopExecution(), and termination().
Referenced by RexxInstructionExit::execute(), exitFrom(), implicitExit(), and raiseExit().
expose()
void RexxActivation::expose (RexxVariableBase ** variables, size_t count)
Expose variables for an EXPOSE instruction
Parameters
variables The list of variables to expose.
count The variable count.
Definition at line 1249 of file RexxActivation.cpp.
References RexxVariableBase::expose(), and getObjectVariables().
Referenced by RexxInstructionExpose::execute().
exposeLocalCompoundVariable()
CompoundTableElement * RexxActivation::exposeLocalCompoundVariable (RexxString * stemName, size_t index, RexxInternalObject ** tail, size_t tailCount)
Expose a compound variable in the local context.
Parameters
stemName The stem variable name.
index The slot index of the stem variable (if known)
tail The array of tail elements.
tailCount The count of tail elements.
Returns
The variable value (or OREF_NULL if not found)
Definition at line 4857 of file RexxActivation.cpp.
References StemClass::exposeCompoundVariable(), and getLocalStem().
Referenced by RexxCompoundVariable::procedureExpose().
external()
RexxActivation * RexxActivation::external ()
Return the top level external activation
Returns
The main external call (a top level call or an external routine invocation)
Definition at line 1687 of file RexxActivation.cpp.
References external(), isInternalLevelCall(), and parent.
Referenced by external().
externalCall() [1/2]
RexxObject * RexxActivation::externalCall (RexxString * target, RoutineClass * routine, RexxObject ** arguments, size_t argcount, RexxString * calltype, ProtectedObject & resultObj)
Call an already resolved external routine. This occurs if a first call has suceeded using a package level resource. This short cuts the full call chain
Parameters
target The target function name.
routine The resolved routine object
_argcount The count of arguments for the call.
_stack The expression stack holding the arguments.
calltype The type of call (FUNCTION or SUBROUTINE)
resultObj The returned result.
Returns
The function result (also returned in the resultObj protected object reference.
Definition at line 3010 of file RexxActivation.cpp.
References activity, arguments(), RoutineClass::call(), EXTERNALCALL, and OREF_NULL.
externalCall() [2/2]
RexxObject * RexxActivation::externalCall (RoutineClass *& routine, RexxString * target, RexxObject ** arguments, size_t argcount, RexxString * calltype, ProtectedObject & resultObj)
Main method for performing an external routine call. This orchestrates the search order for locating an external routine.
Parameters
target The target function name.
resolvedTarget The resolved routine object for the call (if any), which is passed back for caching.
arguments The pointer to the call arguments.
argcount The count of arguments.
calltype The type of call (FUNCTION or SUBROUTINE)
resultObj The returned result.
Returns
The function result (also returned in the resultObj protected object reference.
Definition at line 3035 of file RexxActivation.cpp.
References activity, arguments(), RoutineClass::call(), Activity::callFunctionExit(), Activity::callObjectFunctionExit(), Activity::callScriptingExit(), Error_Routine_not_found_name, EXTERNALCALL, RexxCode::findRoutine(), SystemInterpreter::invokeExternalFunction(), OREF_NULL, ActivationSettings::parentCode, reportException(), and settings.
Referenced by RexxExpressionFunction::evaluate(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), and RexxInstructionCallOn::trap().
externalTraceOff()
void RexxActivation::externalTraceOff ()
Flip on the externally activated TRACE OFF bit.
Definition at line 4169 of file RexxActivation.cpp.
References clauseBoundary, ActivationSettings::setExternalTraceOff(), and settings.
Referenced by Activity::callTraceTestExit(), and Activity::setTrace().
externalTraceOn()
void RexxActivation::externalTraceOn ()
Flip ON the externally activated TRACE bit.
Definition at line 4158 of file RexxActivation.cpp.
References clauseBoundary, ActivationSettings::setExternalTraceOn(), and settings.
Referenced by Activity::callTraceTestExit(), and Activity::setTrace().
findClass()
RexxClass * RexxActivation::findClass (RexxString * name)
Resolve a class in this activation's context.
Parameters
name The name to resolve.
Returns
The resolved class, or OREF_NULL if not found.
Definition at line 3190 of file RexxActivation.cpp.
References PackageClass::findClass(), getPackageObject(), RexxObject::isInstanceOf(), OREF_NULL, and TheClassClass.
Referenced by NativeActivation::findCallerClass().
findRexxContext()
RexxActivation * RexxActivation::findRexxContext () override virtual
Return the Rexx context this operates under. Depending on the context, this could be null.
Returns
The parent Rexx context.
Reimplemented from ActivationBase.
Definition at line 2281 of file RexxActivation.cpp.
form()
bool RexxActivation::form () override virtual
Return the current form setting
Returns
The package form setting
Reimplemented from ActivationBase.
Definition at line 2210 of file RexxActivation.cpp.
References PackageSetting::getForm(), ActivationSettings::packageSettings, and settings.
Referenced by NativeActivation::form(), and RexxContext::getForm().
formatSourcelessTraceLine()
RexxString * RexxActivation::formatSourcelessTraceLine (RexxString * packageName)
Format a more informative trace line when giving traceback information for code when no source code is available.
Parameters
packageName The package name to use (could be "REXX" for internal code)
Returns
A formatted descriptive string for the invocation.
Definition at line 5040 of file RexxActivation.cpp.
References activity, Activity::buildMessage(), ActivationBase::executable, getMessageName(), isMethod(), isRoutine(), Message_Translations_sourceless_method_invocation, Message_Translations_sourceless_program_invocation, Message_Translations_sourceless_routine_invocation, and new_array().
Referenced by PackageClass::traceBack().
formatTrace()
RexxString * RexxActivation::formatTrace (RexxInstruction * instruction, PackageClass * package)
Format a source line for traceback or tracing
Parameters
instruction The target instruction.
package The package this instruction belongs to.
Returns
The formatted traceback line.
Definition at line 4014 of file RexxActivation.cpp.
References RexxInstruction::getLocation(), MAX_TRACEBACK_INDENT, OREF_NULL, settings, PackageClass::traceBack(), and ActivationSettings::traceIndent.
Referenced by getTraceBack(), and traceClause().
forward()
RexxObject * RexxActivation::forward (RexxObject * target, RexxString * message, RexxClass * superClass, RexxObject ** arguments, size_t argcount, bool continuing)
Process a forward instruction.
Parameters
target The target object.
message The message name.
superClass The superclass override (if any)
arguments The message arguments.
argcount The count of message arguments.
continuing The continue flag.
Returns
The message result.
Definition at line 1303 of file RexxActivation.cpp.
References argCount, argList, arguments(), Error_Execution_reply_exit, ActivationSettings::isReplyIssued(), ActivationSettings::messageName, RexxObject::messageSend(), OREF_NULL, receiver, reportException(), resetDebug(), result, RETURNED, ActivationSettings::setForwarded(), settings, stopExecution(), and termination().
Referenced by RexxInstructionForward::execute().
fuzz()
wholenumber_t RexxActivation::fuzz () override virtual
Return the current fuzz setting
Returns
The package fuzz setting
Reimplemented from ActivationBase.
Definition at line 2199 of file RexxActivation.cpp.
References PackageSetting::getFuzz(), ActivationSettings::packageSettings, and settings.
Referenced by RexxInstructionNumeric::execute(), NativeActivation::fuzz(), and RexxContext::getFuzz().
getActivity()
Activity* RexxActivation::getActivity () inline
Definition at line 324 of file RexxActivation.hpp.
References activity.
Referenced by RexxStemVariable::clearGuard(), QualifiedFunction::evaluate(), RexxInstructionQualifiedCall::execute(), RexxInstructionGuard::execute(), RequiresDirective::install(), InstallingPackage::InstallingPackage(), PackageClass::processInstall(), RexxStemVariable::setGuard(), and toUnicode().
getAddress()
RexxString* RexxActivation::getAddress () inline
Definition at line 330 of file RexxActivation.hpp.
References ActivationSettings::currentAddress, and settings.
Referenced by RexxInstructionCommand::execute().
getAllLocalVariables()
DirectoryClass* RexxActivation::getAllLocalVariables () inline
Definition at line 471 of file RexxActivation.hpp.
References getLocalVariables(), and VariableDictionary::getVariableDirectory().
Referenced by NativeActivation::getAllContextVariables(), and RexxContext::getVariables().
getArguments()
ArrayClass* RexxActivation::getArguments () inline
Definition at line 443 of file RexxActivation.hpp.
References argCount, argList, and new_array().
Referenced by createStackFrame().
getCallname()
RexxString* RexxActivation::getCallname () inline
Definition at line 326 of file RexxActivation.hpp.
References ActivationSettings::messageName, and settings.
Referenced by RexxInstructionUse::execute(), RexxContext::getName(), and UseVariable::handleArgument().
getConditionObj()
DirectoryClass* RexxActivation::getConditionObj () inline
Definition at line 331 of file RexxActivation.hpp.
References ActivationSettings::conditionObj, and settings.
Referenced by RexxInstructionRaise::execute(), and RexxContext::getCondition().
getContextLine()
RexxObject * RexxActivation::getContextLine ()
Return the line context information for a context.
Returns
The current execution line.
Definition at line 2893 of file RexxActivation.cpp.
References current, getContextLine(), RexxInstruction::getLineNumber(), isInterpret(), new_integer(), and parent.
Referenced by getContextLine(), and RexxContext::getLine().
getContextLineNumber()
size_t RexxActivation::getContextLineNumber ()
Return the line context information for a context.
Returns
The current execution line.
Definition at line 2914 of file RexxActivation.cpp.
References current, getContextLineNumber(), RexxInstruction::getLineNumber(), isInterpret(), and parent.
Referenced by createStackFrame(), and getContextLineNumber().
getContextObject()
RexxObject * RexxActivation::getContextObject ()
Get the context object for this activation.
Returns
The created context object.
Definition at line 2876 of file RexxActivation.cpp.
References contextObject, and OREF_NULL.
Referenced by createStackFrame(), RexxActivationFrame::getContextObject(), NativeActivation::getRexxContextObject(), and rexxVariable().
getContextReturnStatus()
RexxObject * RexxActivation::getContextReturnStatus ()
Return the RS context information for a activation.
Returns
The current execution line.
Definition at line 2937 of file RexxActivation.cpp.
References ActivationSettings::isReturnStatusSet(), new_integer(), ActivationSettings::returnStatus, settings, and TheNilObject.
Referenced by RexxContext::getRS().
getCurrent()
RexxInstruction* RexxActivation::getCurrent () inline
Definition at line 327 of file RexxActivation.hpp.
References current.
getEffectivePackageObject()
PackageClass* RexxActivation::getEffectivePackageObject () inline
Definition at line 287 of file RexxActivation.hpp.
References ActivationBase::executable, BaseExecutable::getPackageObject(), isInterpret(), and packageObject.
Referenced by RexxActivationFrame::getPackage().
getEffectiveSecurityManager()
SecurityManager * RexxActivation::getEffectiveSecurityManager ()
Get the security manager in used by this activation.
Returns
Either the defined security manager or the instance-global security manager.
Definition at line 4960 of file RexxActivation.cpp.
References activity, Activity::getInstanceSecurityManager(), OREF_NULL, ActivationSettings::securityManager, and settings.
Referenced by Activity::callCommandExit(), Activity::callObjectFunctionExit(), and resolveStream().
getElapsed()
int64_t RexxActivation::getElapsed ()
Retrieve the current elapsed time counter start time, starting the counter from the current time stamp if this is the first call
Returns
The elapsed time counter.
Definition at line 3397 of file RexxActivation.cpp.
References ActivationSettings::elapsedTime, RexxDateTime::getUTCBaseTime(), settings, and ActivationSettings::timeStamp.
getFileNames()
StringTable * RexxActivation::getFileNames ()
Return the associated object variables fileNames table
Returns
The table of opened streams file names.
Definition at line 5083 of file RexxActivation.cpp.
References ActivationSettings::fileNames, new_string_table(), OREF_NULL, and settings.
Referenced by resolveStream().
getIdntfr()
uint32_t RexxActivation::getIdntfr ()
Definition at line 94 of file RexxActivation.cpp.
References counter(), and idntfr.
Referenced by createStackFrame(), createTraceObject(), and RexxInstructionGuard::execute().
getIndent()
size_t RexxActivation::getIndent () inline
Definition at line 322 of file RexxActivation.hpp.
References settings, and ActivationSettings::traceIndent.
Referenced by DoBlock::DoBlock().
getIOConfig()
CommandIOConfiguration * RexxActivation::getIOConfig (RexxString * environment)
Retrieve the IO configuration for an address enviroment, if it exists
Parameters
environment The name of the environment
Returns
The configuration (if any) associated with the environment name.
Definition at line 1650 of file RexxActivation.cpp.
References HashCollection::get(), ActivationSettings::ioConfigs, OREF_NULL, settings, and RexxString::upper().
Referenced by resolveAddressIOConfig().
getLabels()
StringTable * RexxActivation::getLabels ()
Return the directory of labels for this block of code.
Returns
The string table of labels (returns null if there are no labels in this code section)
Definition at line 4554 of file RexxActivation.cpp.
References code, and RexxCode::getLabels().
Referenced by RexxInstructionDynamicCall::execute(), and signalValue().
getLocalCompoundVariable()
CompoundTableElement * RexxActivation::getLocalCompoundVariable (RexxString * stemName, size_t index, RexxInternalObject ** tail, size_t tailCount)
Get the value of a compound variable from the local context.
Parameters
stemName The stem variable name.
index The slot index of the stem variable (if known)
tail The array of tail elements.
tailCount The count of tail elements.
Returns
The variable value (or OREF_NULL if not found)
Definition at line 4838 of file RexxActivation.cpp.
References StemClass::getCompoundVariable(), and getLocalStem().
Referenced by RexxCompoundVariable::clearGuard(), and RexxCompoundVariable::setGuard().
getLocalCompoundVariableRealValue()
RexxObject * RexxActivation::getLocalCompoundVariableRealValue (RexxString * localstem, size_t index, RexxInternalObject ** tail, size_t tailCount)
Get the value of a compound variable from the local context.
Parameters
stemName The stem variable name.
index The slot index of the stem variable (if known)
tail The array of tail elements.
tailCount The count of tail elements.
Returns
The variable value (or OREF_NULL if not found)
Definition at line 4819 of file RexxActivation.cpp.
References StemClass::getCompoundVariableRealValue(), and getLocalStem().
Referenced by RexxCompoundVariable::getRealValue().
getLocalCompoundVariableValue()
RexxObject * RexxActivation::getLocalCompoundVariableValue (RexxString * stemName, size_t index, RexxInternalObject ** tail, size_t tailCount)
Get the value of a compound variable from the local context.
Parameters
stemName The stem variable name.
index The slot index of the stem variable (if known)
tail The array of tail elements.
tailCount The count of tail elements.
Returns
The variable value (or OREF_NULL if not found)
Definition at line 4800 of file RexxActivation.cpp.
References StemClass::getCompoundVariableValue(), and getLocalStem().
Referenced by RexxCompoundVariable::getValue().
getLocalEnvironment()
RexxObject * RexxActivation::getLocalEnvironment (RexxString * name)
Retrieve a value from the instance local environment.
Parameters
name The name of the .local object.
Returns
The object stored at the given name.
Definition at line 4978 of file RexxActivation.cpp.
References activity, and Activity::getLocalEnvironment().
Referenced by novalueHandler(), and resolveStream().
getLocalStem()
StemClass* RexxActivation::getLocalStem (RexxString * name, size_t index) inline
Definition at line 496 of file RexxActivation.hpp.
References getLocalStemVariable(), and RexxVariable::getVariableValue().
Referenced by assignLocalCompoundVariable(), dropLocalCompoundVariable(), RexxStemVariable::evaluate(), evaluateLocalCompoundVariable(), RexxCompoundVariable::expose(), exposeLocalCompoundVariable(), getLocalCompoundVariable(), getLocalCompoundVariableRealValue(), getLocalCompoundVariableValue(), RexxStemVariable::getRealValue(), RexxStemVariable::getValue(), localCompoundVariableExists(), RexxCompoundVariable::procedureExpose(), setLocalCompoundVariable(), and RexxStemVariable::sort().
getLocalStemVariable()
RexxVariable* RexxActivation::getLocalStemVariable (RexxString * name, size_t index) inline
Definition at line 486 of file RexxActivation.hpp.
References RexxLocalVariables::get(), ActivationSettings::localVariables, RexxLocalVariables::lookupStemVariable(), OREF_NULL, and settings.
Referenced by RexxStemVariable::assign(), RexxStemVariable::clearGuard(), dropLocalStem(), getLocalStem(), RexxStemVariable::getVariableReference(), RexxStemVariable::procedureExpose(), RexxStemVariable::set(), and RexxStemVariable::setGuard().
getLocalVariable()
RexxVariable* RexxActivation::getLocalVariable (RexxString * name, size_t index) inline
Definition at line 476 of file RexxActivation.hpp.
References RexxLocalVariables::get(), ActivationSettings::localVariables, RexxLocalVariables::lookupVariable(), OREF_NULL, and settings.
Referenced by autoExpose(), RexxSimpleVariable::clearGuard(), dropLocalVariable(), RexxSimpleVariable::evaluate(), RexxSimpleVariable::getRealValue(), RexxSimpleVariable::getValue(), RexxSimpleVariable::getVariableReference(), RexxSimpleVariable::procedureExpose(), RexxSimpleVariable::setGuard(), and setLocalVariable().
getLocalVariables()
VariableDictionary* RexxActivation::getLocalVariables () inline
Definition at line 466 of file RexxActivation.hpp.
References RexxLocalVariables::getDictionary(), ActivationSettings::localVariables, and settings.
Referenced by NativeActivation::fetchNext(), and getAllLocalVariables().
getMacroCode()
RoutineClass * RexxActivation::getMacroCode (RexxString * macroName) static
Retrieve a macro image file from the macro space.
Parameters
macroName The name of the macro to retrieve.
Returns
If available, the unflattened method image.
Definition at line 3141 of file RexxActivation.cpp.
References RexxString::getStringData(), OREF_NULL, SystemInterpreter::releaseResultMemory(), RoutineClass::restore(), RexxResolveMacroFunction(), and _RXSTRING::strptr.
Referenced by callMacroSpaceFunction(), and PackageManager::getMacroSpaceRequires().
getMessageName()
RexxString* RexxActivation::getMessageName () inline
Definition at line 325 of file RexxActivation.hpp.
References ActivationSettings::messageName, and settings.
Referenced by createStackFrame(), formatSourcelessTraceLine(), RexxActivationFrame::messageName(), and traceEntryOrExit().
getMethod()
MethodClass * RexxActivation::getMethod ()
Get the active method object (if a method call)
Returns
The frame method object. Returns OREF_NULL if this is not a message activation.
Definition at line 2331 of file RexxActivation.cpp.
References ActivationBase::executable, getMethod(), isInterpret(), isMethod(), OREF_NULL, and parent.
Referenced by getMethod().
getMethodArgument()
RexxObject* RexxActivation::getMethodArgument (size_t position) inline
Definition at line 431 of file RexxActivation.hpp.
References argList, getMethodArgumentCount(), and OREF_NULL.
getMethodArgumentCount()
size_t RexxActivation::getMethodArgumentCount () inline
Definition at line 430 of file RexxActivation.hpp.
References argCount.
Referenced by RexxInstructionParse::execute(), RexxInstructionUse::execute(), RexxContext::getArgs(), and getMethodArgument().
getMethodArgumentList()
RexxObject** RexxActivation::getMethodArgumentList () inline
Definition at line 429 of file RexxActivation.hpp.
References argList.
Referenced by RexxInstructionParse::execute(), RexxInstructionUse::execute(), and RexxContext::getArgs().
getNext()
RexxInstruction* RexxActivation::getNext () inline
Definition at line 333 of file RexxActivation.hpp.
References next.
getNumericSettings()
const NumericSettings * RexxActivation::getNumericSettings () override virtual
Get the numeric settings for the current context.
Returns
The new numeric settings.
Reimplemented from ActivationBase.
Definition at line 2303 of file RexxActivation.cpp.
References PackageSetting::numericSettings, ActivationSettings::packageSettings, and settings.
Referenced by NativeActivation::getNumericSettings().
getObjectVariables()
VariableDictionary * RexxActivation::getObjectVariables ()
Return the object variables dictionary for the current scope level.
Returns
the target object variables.
Definition at line 1881 of file RexxActivation.cpp.
References activity, RexxObject::getObjectVariables(), isGuarded(), ActivationBase::objectScope, ActivationSettings::objectVariables, OREF_NULL, receiver, VariableDictionary::reserve(), scope, ActivationBase::SCOPE_RESERVED, and settings.
Referenced by autoExpose(), and expose().
getPackage()
PackageClass * RexxActivation::getPackage () override virtual
Retrieve the package for the current execution context.
Returns
The Package holding the code for the current execution context.
Reimplemented from ActivationBase.
Definition at line 4758 of file RexxActivation.cpp.
References ActivationBase::executable, and BaseExecutable::getPackage().
Referenced by RexxInstructionNumeric::execute(), RexxContext::getPackage(), MethodClass::newMethodObject(), BaseExecutable::processNewExecutableArgs(), BaseExecutable::processNewFileExecutableArgs(), and traceEntryOrExit().
getPackageObject()
PackageClass* RexxActivation::getPackageObject () inline
Definition at line 286 of file RexxActivation.hpp.
References packageObject.
Referenced by callMacroSpaceFunction(), findClass(), getTraceBack(), and resolveDotVariable().
getProgramArgument()
RexxObject* RexxActivation::getProgramArgument (size_t position) inline
Definition at line 448 of file RexxActivation.hpp.
References getProgramArgumentCount(), OREF_NULL, ActivationSettings::parentArgList, and settings.
Referenced by NativeActivation::variablePoolFetchPrivate().
getProgramArgumentCount()
size_t RexxActivation::getProgramArgumentCount () inline
Definition at line 446 of file RexxActivation.hpp.
References ActivationSettings::parentArgCount, and settings.
Referenced by getProgramArgument(), and NativeActivation::variablePoolFetchPrivate().
getProgramArgumentlist()
RexxObject** RexxActivation::getProgramArgumentlist () inline
Definition at line 445 of file RexxActivation.hpp.
References ActivationSettings::parentArgList, and settings.
getProgramName()
RexxString * RexxActivation::getProgramName ()
Return the name of the current program file
Returns
The string name of the program source.
Definition at line 4531 of file RexxActivation.cpp.
References code, and RexxCode::getProgramName().
getPublicRoutines()
StringTable * RexxActivation::getPublicRoutines ()
Retrieve the directory of public routines associated with the current activation.
Returns
A directory of the public routines.
Definition at line 4600 of file RexxActivation.cpp.
References code, and RexxCode::getPublicRoutines().
getRandomSeed()
uint64_t RexxActivation::getRandomSeed (RexxInteger * seed)
Get the random seed for the random number generator.
Parameters
seed The starter seed (optional)
Returns
The new seed value to use for the random numbers.
Definition at line 3426 of file RexxActivation.cpp.
References Error_Incorrect_call_nonnegative, getRandomSeed(), RexxInteger::getValue(), IntegerThree, isInternalLevelCall(), OREF_NULL, parent, RANDOMIZE(), randomSeed, and reportException().
Referenced by getRandomSeed(), and random().
getReceiver()
RexxObject * RexxActivation::getReceiver () override virtual
Get the message receiver
Returns
The message receiver. Returns OREF_NULL if this is not a message activation.
Reimplemented from ActivationBase.
Definition at line 2315 of file RexxActivation.cpp.
References getReceiver(), isInterpret(), parent, and receiver.
Referenced by createTraceObject(), and getReceiver().
getReserveCount()
unsigned short RexxActivation::getReserveCount () inline
Definition at line 418 of file RexxActivation.hpp.
References VariableDictionary::getReserveCount(), and getVariableDictionary().
Referenced by createTraceObject().
getRexxContext()
RexxActivation * RexxActivation::getRexxContext () override virtual
Return the Rexx context this operates under. Depending on the context, this could be null.
Returns
The parent Rexx context.
Reimplemented from ActivationBase.
Definition at line 2269 of file RexxActivation.cpp.
getSecurityManager()
SecurityManager * RexxActivation::getSecurityManager () override virtual
Get the security manager in effect for a given context.
Returns
The security manager defined for this activation context.
Implements ActivationBase.
Definition at line 4948 of file RexxActivation.cpp.
References ActivationSettings::securityManager, and settings.
getSettings()
void RexxActivation::getSettings (ActivationSettings & s) inline
Definition at line 328 of file RexxActivation.hpp.
References settings.
Referenced by run().
getStack()
ExpressionStack* RexxActivation::getStack () inline
Definition at line 337 of file RexxActivation.hpp.
References stack.
Referenced by RexxExpressionMessage::assign(), RexxVariableReference::list(), and RexxInstructionCallOn::trap().
getStackFrameAsStringTable()
StringTable * RexxActivation::getStackFrameAsStringTable (StackFrameClass * stackFrame) static
Creates a StringTable with all entries from the supplied StackFrame object. The executable object may not be present anymore, if its reference gets used much later, e.g. in the case that a trace log gets created and analyzed after the activity and the executable are potentially gone out of scope. Therefore executable related information is explicitly queried and saved in form of strings in the string table (executable's hashId, executable's name, executable's package's name; if excutable is a method, then its scope's hashId, its scope's name, its scope's package).
In the case the target is available it is an ooRexx object that will remain available as long as it gets referred to (e.g. because of being stored in an array like this one).
using the identityHash of the StackFrame entries EXECUTABLE and TARGET if they are not .nil.
Parameters
stackFrame the StackFrame object to use, may be NULLOBJECT
Returns
a StringTable with all the entries of stackFrame, if available
Definition at line 5265 of file RexxActivation.cpp.
References new_string_table(), NULLOBJECT, result, and RexxObject::sendMessage().
Referenced by createTraceObject(), and Activity::setCallerStackFrameAsStringTable().
getStackFrames()
ArrayClass * RexxActivation::getStackFrames (bool skipFirst)
Generate the stack frames for the current context.
Returns
A list of the stackframes.
Definition at line 5072 of file RexxActivation.cpp.
References activity, and Activity::generateStackFrames().
Referenced by RexxContext::getStackFrames().
getStreams()
StringTable * RexxActivation::getStreams ()
Return the associated object variables stream table
Returns
The table of opened streams.
Definition at line 2022 of file RexxActivation.cpp.
References ActivationSettings::caseInsensitive, ActivationBase::getPreviousStackFrame(), SysFileSystem::isCaseSensitive(), isProgramOrMethod(), ActivationBase::isRexxContext(), new_string_table(), OREF_NULL, settings, and ActivationSettings::streams.
Referenced by removeFileName(), and resolveStream().
getTime()
RexxDateTime RexxActivation::getTime ()
Retrieve the current activation timestamp, retrieving a new timestamp if this is the first call for a clause
Returns
A RexxDateTime object with the full time stamp.
Definition at line 3363 of file RexxActivation.cpp.
References ActivationSettings::elapsedTime, SystemInterpreter::getCurrentTime(), RexxDateTime::getUTCBaseTime(), isElapsedTimerReset(), setElapsedTimerValid(), settings, ActivationSettings::timeStamp, and RexxDateTime::valid.
getTraceBack()
RexxString * RexxActivation::getTraceBack ()
Get a traceback line for the current instruction.
Returns
The formatted string traceback.
Definition at line 3351 of file RexxActivation.cpp.
References current, formatTrace(), and getPackageObject().
Referenced by createStackFrame().
getVariableDictionary()
VariableDictionary* RexxActivation::getVariableDictionary () inline
Definition at line 419 of file RexxActivation.hpp.
References RexxObject::getObjectVariables(), receiver, and scope.
Referenced by createTraceObject(), and getReserveCount().
guardOff()
void RexxActivation::guardOff () inline
Definition at line 157 of file RexxActivation.hpp.
References activity, ActivationBase::objectScope, ActivationSettings::objectVariables, VariableDictionary::release(), ActivationBase::SCOPE_RELEASED, ActivationBase::SCOPE_RESERVED, and settings.
Referenced by RexxInstructionGuard::execute(), and termination().
guardOn()
void RexxActivation::guardOn ()
Turn on the activation guarded state
Definition at line 2166 of file RexxActivation.cpp.
References activity, RexxObject::getObjectVariables(), ActivationBase::objectScope, ActivationSettings::objectVariables, OREF_NULL, receiver, VariableDictionary::reserve(), scope, ActivationBase::SCOPE_RELEASED, ActivationBase::SCOPE_RESERVED, and settings.
Referenced by RexxInstructionGuard::execute().
guardWait()
void RexxActivation::guardWait ()
Wait for a variable in a guard expression to get updated.
Definition at line 3323 of file RexxActivation.cpp.
References activity, Activity::guardWait(), ActivationBase::objectScope, ActivationSettings::objectVariables, VariableDictionary::release(), VariableDictionary::reserve(), ActivationBase::SCOPE_RELEASED, ActivationBase::SCOPE_RESERVED, and settings.
Referenced by RexxInstructionGuard::execute().
halt()
bool RexxActivation::halt (RexxString * description)
Halt the activation
Parameters
description The description for the halt condition (if any).
Returns
true if this halt was recognized, false if there is a previous halt condition still to be processed.
Definition at line 4124 of file RexxActivation.cpp.
References clauseBoundary, ActivationSettings::haltDescription, ActivationSettings::haveHaltCondition(), ActivationSettings::setHaltCondition(), and settings.
Referenced by Activity::callHaltTestExit(), and Activity::halt().
handleNovalueEvent()
RexxObject * RexxActivation::handleNovalueEvent (RexxString * name, RexxObject * defaultValue, RexxVariable * variable)
Process a NOVALUE event for a variable.
Parameters
name The variable name triggering the event.
variable The resolved variable object for the variable.
Returns
A value for that variable.
Definition at line 2618 of file RexxActivation.cpp.
References activity, Activity::callNovalueExit(), Error_Execution_unassigned_variable, isNovalueSyntaxEnabled(), novalueEnabled(), novalueHandler(), reportException(), reportNovalue(), RexxVariable::set(), and TheNilObject.
Referenced by RexxSimpleVariable::evaluate(), and StemClass::handleNovalue().
hasActiveBlockInstructions()
bool RexxActivation::hasActiveBlockInstructions () inline
Definition at line 316 of file RexxActivation.hpp.
References blockNest.
Referenced by RexxInstructionEnd::execute(), and RexxInstructionOtherwise::execute().
implicitExit()
void RexxActivation::implicitExit ()
Process a "fall off the end" exit condition
Definition at line 1422 of file RexxActivation.cpp.
References activity, Activity::callTerminationExit(), executionState, exitFrom(), isInterpret(), isProgramLevelCall(), isTopLevelCall(), OREF_NULL, and RETURNED.
Referenced by run().
inDebug()
bool RexxActivation::inDebug () inline
Definition at line 368 of file RexxActivation.hpp.
References debugPause, TraceSetting::isDebug(), ActivationSettings::packageSettings, settings, and PackageSetting::traceSettings.
Referenced by command(), RexxInstructionTrace::execute(), and traceClause().
indent()
void RexxActivation::indent () inline
Definition at line 318 of file RexxActivation.hpp.
References settings, and ActivationSettings::traceIndent.
Referenced by addBlockInstruction(), RexxInstructionElse::execute(), RexxInstructionOtherwise::execute(), RexxInstructionThen::execute(), and RexxInstructionBaseLoop::reExecute().
inheritPackageSettings()
void RexxActivation::inheritPackageSettings ()
Inherit the settings from our package object.
Definition at line 421 of file RexxActivation.cpp.
References PackageClass::getSettings(), ActivationSettings::intermediateTrace, packageObject, ActivationSettings::packageSettings, settings, PackageSetting::traceSettings, and TraceSetting::tracingIntermediates().
Referenced by RexxActivation().
inMethod()
bool RexxActivation::inMethod () inline
Definition at line 317 of file RexxActivation.hpp.
References activationContext, and METHODCALL.
Referenced by RexxInstructionExpose::execute(), RexxInstructionForward::execute(), RexxInstructionGuard::execute(), RexxInstructionReply::execute(), RexxInstructionUse::execute(), RexxInstructionUseLocal::execute(), and UseVariable::handleArgument().
internalCall()
RexxObject * RexxActivation::internalCall (RexxString * name, RexxInstruction * target, RexxObject ** arguments, size_t argcount, ProtectedObject & returnObject)
Process an internal function or subroutine call.
Parameters
name The name of the target label.
target The target instruction where we start executing (this is the label)
_argcount The count of arguments
_stack The context stack holding the arguments
returnObject A holder for the return value
Returns
The return value object
Definition at line 3275 of file RexxActivation.cpp.
References activity, arguments(), current, RexxInstruction::getLineNumber(), INTERNALCALL, new_integer(), ActivityManager::newActivation(), ActivationSettings::parentCode, Activity::pushStackFrame(), receiver, run(), setLocalVariable(), settings, and VARIABLE_SIGL.
Referenced by RexxExpressionFunction::evaluate(), RexxInstructionCall::execute(), and RexxInstructionDynamicCall::execute().
internalCallTrap()
RexxObject * RexxActivation::internalCallTrap (RexxString * name, RexxInstruction * target, DirectoryClass * conditionObj, ProtectedObject & resultObj)
Processing a call to an internal trap subroutine.
Parameters
name The label name of the internal call.
target The target instruction for the call (the label)
conditionObj The associated condition object
resultObj A holder for a result object
Returns
Any return result
Definition at line 3301 of file RexxActivation.cpp.
References activity, current, RexxInstruction::getLineNumber(), INTERNALCALL, new_integer(), ActivityManager::newActivation(), OREF_NULL, ActivationSettings::parentCode, ExpressionStack::push(), Activity::pushStackFrame(), run(), setConditionObj(), setLocalVariable(), settings, stack, and VARIABLE_SIGL.
Referenced by RexxInstructionCallOn::trap().
internalMethod()
bool RexxActivation::internalMethod ()
interpret()
void RexxActivation::interpret (RexxString * codestring)
Translate and interpret a string of data as a piece of Rexx code within the current program context.
Parameters
codestring The source code string.
Definition at line 2738 of file RexxActivation.cpp.
References activity, argCount, argList, Activity::checkStackSpace(), code, current, ActivityManager::currentActivity, RexxInstruction::getLineNumber(), INTERPRET, RexxCode::interpret(), ActivityManager::newActivation(), OREF_NULL, Activity::pushStackFrame(), and run().
Referenced by RexxInstructionInterpret::execute().
isElapsedTimerReset()
bool RexxActivation::isElapsedTimerReset () inline
Definition at line 424 of file RexxActivation.hpp.
References ActivationSettings::isElapsedTimerReset(), and settings.
Referenced by getTime().
isErrorSyntaxEnabled()
bool RexxActivation::isErrorSyntaxEnabled () inline
Definition at line 390 of file RexxActivation.hpp.
References PackageSetting::isErrorSyntaxEnabled(), ActivationSettings::packageSettings, and settings.
Referenced by command(), Activity::raiseCondition(), trapOff(), and trapOn().
isFailureSyntaxEnabled()
bool RexxActivation::isFailureSyntaxEnabled () inline
Definition at line 392 of file RexxActivation.hpp.
References PackageSetting::isFailureSyntaxEnabled(), ActivationSettings::packageSettings, and settings.
Referenced by command(), Activity::raiseCondition(), trapOff(), and trapOn().
isForwarded()
bool RexxActivation::isForwarded () inline override virtual
Reimplemented from ActivationBase.
Definition at line 144 of file RexxActivation.hpp.
References ActivationSettings::isForwarded(), and settings.
Referenced by Activity::raiseException().
isGuarded()
bool RexxActivation::isGuarded () inline
Definition at line 415 of file RexxActivation.hpp.
References ActivationSettings::isGuarded(), and settings.
Referenced by createTraceObject(), getObjectVariables(), and run().
isInternalCall()
bool RexxActivation::isInternalCall () inline
Definition at line 169 of file RexxActivation.hpp.
References activationContext, and INTERNALCALL.
Referenced by checkIOConfigTable(), checkTrapTable(), createStackFrame(), and run().
isInternalLevelCall()
bool RexxActivation::isInternalLevelCall () inline
Definition at line 175 of file RexxActivation.hpp.
References activationContext, and INTERNAL_LEVEL_CALL.
Referenced by cleanupLocalVariables(), external(), and getRandomSeed().
isInterpret()
bool RexxActivation::isInterpret () inline
Definition at line 168 of file RexxActivation.hpp.
References activationContext, and INTERPRET.
Referenced by callExternalRexx(), createStackFrame(), getContextLine(), getContextLineNumber(), getEffectivePackageObject(), getMethod(), getReceiver(), implicitExit(), resolveDotVariable(), returnFrom(), RexxActivation(), rexxVariable(), run(), setDigits(), setForm(), setFuzz(), signalTo(), sourceString(), traceEntry(), traceEntryOrExit(), trap(), and unwindTrap().
isLostdigitsSyntaxEnabled()
bool RexxActivation::isLostdigitsSyntaxEnabled () inline
Definition at line 394 of file RexxActivation.hpp.
References PackageSetting::isLostdigitsSyntaxEnabled(), ActivationSettings::packageSettings, and settings.
Referenced by Activity::raiseCondition(), trapOff(), and trapOn().
isMethod()
bool RexxActivation::isMethod () inline
Definition at line 170 of file RexxActivation.hpp.
References activationContext, and METHODCALL.
Referenced by createStackFrame(), createTraceObject(), formatSourcelessTraceLine(), getMethod(), isMethodOrRoutine(), and traceEntryOrExit().
isMethodOrRoutine()
bool RexxActivation::isMethodOrRoutine () inline
Definition at line 177 of file RexxActivation.hpp.
References isMethod(), and isRoutine().
Referenced by run(), termination(), and traceEntry().
isNostringSyntaxEnabled()
bool RexxActivation::isNostringSyntaxEnabled () inline
Definition at line 396 of file RexxActivation.hpp.
References PackageSetting::isNostringSyntaxEnabled(), ActivationSettings::packageSettings, and settings.
Referenced by Activity::raiseCondition(), trapOff(), and trapOn().
isNotreadySyntaxEnabled()
bool RexxActivation::isNotreadySyntaxEnabled () inline
Definition at line 398 of file RexxActivation.hpp.
References PackageSetting::isNotreadySyntaxEnabled(), ActivationSettings::packageSettings, and settings.
Referenced by Activity::raiseCondition(), trapOff(), and trapOn().
isNovalueSyntaxEnabled()
bool RexxActivation::isNovalueSyntaxEnabled () inline
Definition at line 400 of file RexxActivation.hpp.
References PackageSetting::isNovalueSyntaxEnabled(), ActivationSettings::packageSettings, and settings.
Referenced by handleNovalueEvent().
isObjectScopeLocked()
bool RexxActivation::isObjectScopeLocked () inline
Definition at line 417 of file RexxActivation.hpp.
References ActivationBase::objectScope, and ActivationBase::SCOPE_RESERVED.
Referenced by createTraceObject().
isProgram()
bool RexxActivation::isProgram () inline
Definition at line 172 of file RexxActivation.hpp.
References activationContext, and PROGRAMCALL.
Referenced by createStackFrame().
isProgramLevelCall()
bool RexxActivation::isProgramLevelCall () inline
Definition at line 174 of file RexxActivation.hpp.
References activationContext, and PROGRAM_LEVEL_CALL.
Referenced by exitFrom(), implicitExit(), raiseExit(), returnFrom(), and run().
isProgramOrMethod()
bool RexxActivation::isProgramOrMethod () inline
Definition at line 176 of file RexxActivation.hpp.
References activationContext, and PROGRAM_OR_METHOD.
Referenced by closeStreams(), and getStreams().
isRexxContext()
bool RexxActivation::isRexxContext () override virtual
Indicate whether this activation is a Rexx context or not.
Returns
true if this is a Rexx context, false otherwise.
Reimplemented from ActivationBase.
Definition at line 2292 of file RexxActivation.cpp.
isRoutine()
bool RexxActivation::isRoutine () inline
Definition at line 171 of file RexxActivation.hpp.
References activationContext, and EXTERNALCALL.
Referenced by createStackFrame(), formatSourcelessTraceLine(), and isMethodOrRoutine().
isTopLevel()
bool RexxActivation::isTopLevel () inline
Definition at line 414 of file RexxActivation.hpp.
References activationContext, and TOP_LEVEL_CALL.
Referenced by exitFrom().
isTopLevelCall()
bool RexxActivation::isTopLevelCall () inline
Definition at line 173 of file RexxActivation.hpp.
References activationContext, and TOP_LEVEL_CALL.
Referenced by exitFrom(), implicitExit(), popEnvironment(), pushEnvironment(), raiseExit(), and run().
iterate()
void RexxActivation::iterate (RexxString * name)
Process a REXX ITERATE instruction
Parameters
name The optional block name for the iterate.
Definition at line 1080 of file RexxActivation.cpp.
References Error_Invalid_leave_iterate, Error_Invalid_leave_iterate_name, Error_Invalid_leave_iteratevar, DoBlock::getIndent(), DoBlock::getParent(), RexxBlockInstruction::isLabel(), RexxBlockInstruction::isLoop(), OREF_NULL, popBlockInstruction(), reportException(), setIndent(), stack, and topBlockInstruction().
Referenced by RexxInstructionLeave::execute().
leaveLoop()
void RexxActivation::leaveLoop (RexxString * name)
Process a REXX LEAVE instruction
Parameters
name The potential matching label name (can be null)
Definition at line 1144 of file RexxActivation.cpp.
References Error_Invalid_leave_leave, Error_Invalid_leave_leavevar, DoBlock::getParent(), RexxBlockInstruction::isLabel(), RexxBlockInstruction::isLoop(), OREF_NULL, popBlockInstruction(), reportException(), RexxBlockInstruction::terminate(), and topBlockInstruction().
Referenced by RexxInstructionLeave::execute().
lineIn()
RexxString * RexxActivation::lineIn ()
Handle PARSE LINEIN input
Definition at line 4717 of file RexxActivation.cpp.
References activity, and Activity::lineIn().
Referenced by RexxInstructionParse::execute().
live()
void RexxActivation::live (size_t liveMark) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 328 of file RexxActivation.cpp.
References activity, argCount, argList, code, conditionQueue, contextObject, current, doStack, environmentList, ActivationBase::executable, ActivationSettings::live(), ExpressionStack::live(), memory_mark, memory_mark_array, next, notifyObject, packageObject, parent, ActivationBase::previous, receiver, result, scope, settings, stack, and trapInfo.
liveGeneral()
void RexxActivation::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 363 of file RexxActivation.cpp.
References activity, argCount, argList, code, conditionQueue, contextObject, current, doStack, environmentList, ActivationBase::executable, ActivationSettings::liveGeneral(), ExpressionStack::liveGeneral(), memory_mark_general, memory_mark_general_array, next, notifyObject, packageObject, parent, ActivationBase::previous, receiver, result, scope, settings, stack, and trapInfo.
loadLibrary()
void RexxActivation::loadLibrary (RexxString * target, RexxInstruction * instruction, PackageClass * package)
Load a package defined by a ::REQUIRES name LIBRARY directive.
Parameters
target The name of the package.
instruction The ::REQUIRES directive being loaded.
package The package that is loading this library
Definition at line 3251 of file RexxActivation.cpp.
References current, PackageManager::getLibrary(), and PackageClass::mergeLibrary().
Referenced by LibraryDirective::install().
loadRequires()
void RexxActivation::loadRequires (RequiresDirective * instruction)
Does not actually load a package for a requires, but sets the requires instruction as the current instruction for error reporting.
Parameters
instruction The directive instruction being processed.
Definition at line 3235 of file RexxActivation.cpp.
References current.
Referenced by RequiresDirective::install().
local()
DirectoryClass* RexxActivation::local ()
localCompoundVariableExists()
bool RexxActivation::localCompoundVariableExists (RexxString * stemName, size_t index, RexxInternalObject ** tail, size_t tailCount)
Test if a compound variable exists in the local context.
Parameters
stemName The stem variable name.
index The slot index of the stem variable (if known)
tail The array of tail elements.
tailCount The count of tail elements.
Returns
true if the variable exists, false if not.
Definition at line 4876 of file RexxActivation.cpp.
References StemClass::compoundVariableExists(), and getLocalStem().
Referenced by RexxCompoundVariable::exists().
localStemVariableExists()
bool RexxActivation::localStemVariableExists (RexxString * stemName, size_t index) inline
Definition at line 508 of file RexxActivation.hpp.
References RexxLocalVariables::find(), ActivationSettings::localVariables, OREF_NULL, and settings.
Referenced by RexxStemVariable::exists().
localVariableExists()
bool RexxActivation::localVariableExists (RexxString * name, size_t index) inline
Definition at line 516 of file RexxActivation.hpp.
References RexxLocalVariables::find(), RexxVariable::getVariableValue(), ActivationSettings::localVariables, OREF_NULL, and settings.
Referenced by RexxSimpleVariable::exists().
mergeTraps()
void RexxActivation::mergeTraps (QueueClass * sourceConditionQueue)
Merge a list of trapped conditions from an interpret into the parent activation's queues.
Parameters
sourceConditionQueue The interpret activations condition queue.
Definition at line 2658 of file RexxActivation.cpp.
References ArrayClass::append(), conditionQueue, ArrayClass::isEmpty(), OREF_NULL, and QueueClass::pull().
Referenced by run(), trap(), and unwindTrap().
newBlockInstruction()
void RexxActivation::newBlockInstruction (DoBlock * block) inline
Definition at line 309 of file RexxActivation.hpp.
References blockNest, pushBlockInstruction(), settings, and ActivationSettings::traceIndent.
Referenced by RexxInstructionSimpleDo::execute(), RexxInstructionBaseLoop::execute(), RexxInstructionSelect::execute(), and RexxInstructionSelectCase::execute().
newLocalVariable()
RexxVariable* RexxActivation::newLocalVariable (RexxString * name) inline
Definition at line 564 of file RexxActivation.hpp.
References new_variable(), and RexxVariable::setCreator().
Referenced by RexxLocalVariables::lookupStemVariable(), and RexxLocalVariables::lookupVariable().
notCaseSensitive()
bool RexxActivation::notCaseSensitive () inline
Definition at line 590 of file RexxActivation.hpp.
References ActivationSettings::caseInsensitive, and settings.
Referenced by removeFileName(), and resolveStream().
noTracing() [1/2]
bool RexxActivation::noTracing () inline
Definition at line 411 of file RexxActivation.hpp.
References code, debugPause, RexxCode::isTraceable(), ActivationSettings::isTraceSuppressed(), and settings.
Referenced by traceClause(), traceCompoundValue(), traceOperatorValue(), traceTaggedValue(), and traceValue().
noTracing() [2/2]
bool RexxActivation::noTracing (RexxObject * value) inline
Definition at line 410 of file RexxActivation.hpp.
References code, debugPause, RexxCode::isTraceable(), ActivationSettings::isTraceSuppressed(), OREF_NULL, and settings.
novalueEnabled()
bool RexxActivation::novalueEnabled () inline
Definition at line 562 of file RexxActivation.hpp.
References RexxLocalVariables::getNovalue(), ActivationSettings::localVariables, and settings.
Referenced by handleNovalueEvent().
novalueHandler()
RexxObject * RexxActivation::novalueHandler (RexxString * name)
process unitialized variable overrides
Parameters
name The uninitialized variable name.
Returns
The handler return result.
Definition at line 4739 of file RexxActivation.cpp.
References getLocalEnvironment(), OREF_NULL, result, resultOrNil(), RexxObject::sendMessage(), and TheNilObject.
Referenced by handleNovalueEvent().
operator delete()
void RexxActivation::operator delete (void *) inline
Definition at line 119 of file RexxActivation.hpp.
operator new()
void * RexxActivation::operator new (size_t size)
Create a new activation object
Parameters
size Base size of the object.
Returns
Storage for building an activation object.
Definition at line 107 of file RexxActivation.cpp.
References new_object(), and T_Activation.
pauseCommand()
void RexxActivation::pauseCommand () inline
Definition at line 384 of file RexxActivation.hpp.
References doDebugPause(), ActivationSettings::packageSettings, TraceSetting::pausingCommands(), settings, and PackageSetting::traceSettings.
pauseInstruction()
void RexxActivation::pauseInstruction () inline
Definition at line 381 of file RexxActivation.hpp.
References doDebugPause(), and pausingInstructions().
Referenced by ConstantDirective::execute(), RexxInstructionAddress::execute(), RexxInstructionAssignment::execute(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxInstructionDrop::execute(), RexxInstructionExpose::execute(), RexxInstructionForward::execute(), RexxInstructionIf::execute(), RexxInstructionLeave::execute(), RexxInstructionMessage::execute(), RexxInstructionNop::execute(), RexxInstructionNumeric::execute(), RexxInstructionOptions::execute(), RexxInstructionParse::execute(), RexxInstructionProcedure::execute(), RexxInstructionQueue::execute(), RexxInstructionReply::execute(), RexxInstructionSay::execute(), RexxInstructionTrace::execute(), RexxInstructionUse::execute(), RexxInstructionUseLocal::execute(), and RexxInstructionCaseWhen::execute().
pauseLabel()
void RexxActivation::pauseLabel () inline
Definition at line 383 of file RexxActivation.hpp.
References doDebugPause(), ActivationSettings::packageSettings, TraceSetting::pausingLabels(), settings, and PackageSetting::traceSettings.
Referenced by RexxInstructionLabel::execute(), run(), termination(), and traceEntry().
pausingInstructions()
bool RexxActivation::pausingInstructions () inline
Definition at line 380 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, TraceSetting::pausingInstructions(), settings, and PackageSetting::traceSettings.
Referenced by conditionalPauseInstruction(), and pauseInstruction().
popBlockInstruction()
void RexxActivation::popBlockInstruction () inline
Definition at line 297 of file RexxActivation.hpp.
References doStack, DoBlock::getIndent(), DoBlock::getPrevious(), removeBlockInstruction(), RexxInternalObject::setHasNoReferences(), settings, and ActivationSettings::traceIndent.
Referenced by RexxInstructionBaseLoop::endLoop(), iterate(), leaveLoop(), and terminateBlockInstruction().
popControl()
RexxObject* RexxActivation::popControl ()
popEnvironment()
RexxObject * RexxActivation::popEnvironment ()
return the top level local Environemnt
Returns
Pop the top local environment and restore it.
Definition at line 4649 of file RexxActivation.cpp.
References environmentList, isTopLevelCall(), parent, popEnvironment(), QueueClass::pull(), and TheNilObject.
Referenced by popEnvironment(), and SystemInterpreter::popEnvironment().
procedureExpose()
void RexxActivation::procedureExpose (RexxVariableBase ** variables, size_t count)
Execute a procedure expose instruction.
Parameters
variables The list of variables to expose.
count The count of variables to expose.
Definition at line 1218 of file RexxActivation.cpp.
References activity, Activity::allocateLocalVariableFrame(), Error_Unexpected_procedure_call, ActivationSettings::isProcedureValid(), ActivationSettings::localVariables, parent, RexxLocalVariables::procedure(), RexxVariableBase::procedureExpose(), reportException(), ActivationSettings::setProcedureValid(), and settings.
Referenced by RexxInstructionProcedure::execute().
processClauseBoundary()
void RexxActivation::processClauseBoundary ()
Handle all clause boundary processing (raising of halt conditions, turning on of external traces, and calling of halt and trace clause boundary exits
Definition at line 4032 of file RexxActivation.cpp.
References activity, Activity::callHaltTestExit(), Activity::callTraceTestExit(), clauseBoundary, conditionQueue, disableExternalTrace(), enableExternalTrace(), Error_Program_interrupted_condition, ActivationSettings::haltDescription, ActivationSettings::haveClauseExits(), ActivationSettings::haveExternalTraceOff(), ActivationSettings::haveExternalTraceOn(), ActivationSettings::haveHaltCondition(), ArrayClass::isEmpty(), OREF_NULL, processTraps(), Activity::raiseCondition(), reportException(), ActivationSettings::setExternalTraceOff(), ActivationSettings::setExternalTraceOn(), ActivationSettings::setHaltCondition(), and settings.
Referenced by run().
processTraceInfo()
void RexxActivation::processTraceInfo (Activity * activity, RexxString * traceLine, TracePrefix tracePrefix, RexxString * tag, RexxObject * value) protected
Processes trace information and outputs it.
Parameters
traceLine the trace line to display
tracePrefix the kind of trace taking place
tag optional RexxString, e.g. the traced variable name
value optional RexxObject, e.g. the traced variable value
Definition at line 5225 of file RexxActivation.cpp.
References activity, createTraceObject(), RexxString::stringTrace(), Activity::traceOutput(), and tracePrefix().
Referenced by displayUsingTraceOutput(), doDebugPause(), traceClause(), traceCompoundValue(), traceEntryOrExit(), traceOperatorValue(), traceSourceString(), traceTaggedValue(), and traceValue().
processTraps()
bool RexxActivation::processTraps ()
process pending condition traps before going on to execute a clause
Returns
true if a trap handler may have raised another condition.
Definition at line 830 of file RexxActivation.cpp.
References activity, ArrayClass::append(), conditionQueue, ActivityManager::currentActivity, DirectoryClass::get(), TrapHandler::getConditionObject(), TrapHandler::isDelayed(), ArrayClass::items(), OREF_NULL, QueueClass::pull(), Activity::requestAccess(), setLocalVariable(), TrapHandler::trap(), and VARIABLE_RC.
Referenced by processClauseBoundary(), and run().
propagateExit()
void RexxActivation::propagateExit (RexxObject *)
pullInput()
RexxString * RexxActivation::pullInput ()
Handle PULL or PARSE PULL input
Definition at line 4708 of file RexxActivation.cpp.
References activity, and Activity::pullInput().
Referenced by RexxInstructionParse::execute().
pushBlockInstruction()
void RexxActivation::pushBlockInstruction (DoBlock * block) inline
Definition at line 296 of file RexxActivation.hpp.
References doStack, and DoBlock::setPrevious().
Referenced by newBlockInstruction().
pushControl()
void RexxActivation::pushControl (RexxObject *)
pushEnvironment()
void RexxActivation::pushEnvironment (RexxObject * environment)
Push the new environment buffer onto the environment list.
Parameters
environment The new saved environment.
Definition at line 4623 of file RexxActivation.cpp.
References environmentList, isTopLevelCall(), new_queue(), parent, QueueClass::push(), and pushEnvironment().
Referenced by SystemInterpreter::pushEnvironment(), and pushEnvironment().
putLocalVariable()
void RexxActivation::putLocalVariable (RexxVariable * variable, size_t index) inline
Definition at line 524 of file RexxActivation.hpp.
References ActivationSettings::localVariables, RexxLocalVariables::putVariable(), and settings.
Referenced by RexxStemVariable::expose(), RexxSimpleVariable::expose(), RexxStemVariable::procedureExpose(), and RexxSimpleVariable::procedureExpose().
putSettings()
void RexxActivation::putSettings (ActivationSettings & s) inline
Definition at line 329 of file RexxActivation.hpp.
References settings.
Referenced by RexxActivation(), and unwindTrap().
queue()
void RexxActivation::queue (RexxString * line, Activity::QueueOrder order)
Handle PUSH/QUEUE output
Definition at line 4726 of file RexxActivation.cpp.
References activity, line, and Activity::queue().
Referenced by RexxInstructionQueue::execute().
raise()
void RexxActivation::raise (RexxString * condition, RexxObject * rc, RexxString * description, RexxObject * additional, RexxObject * resultObj, DirectoryClass * conditionobj)
Raise a condition in the context.
Parameters
condition the condition name,
rc The rc value for the condition.
description The condition description.
additional any condition additional information.
resultObj The result object associated with the raise.
conditionobj The condition object used for a propagate.
Definition at line 1759 of file RexxActivation.cpp.
References activity, Activity::createConditionObject(), ActivityManager::currentActivity, Error_No_method_name, Error_No_method_unhandled, Error_Program_interrupted_condition, DirectoryClass::get(), RexxInternalObject::getValue(), OREF_NULL, Activity::popStackFrame(), DirectoryClass::put(), Activity::raiseException(), reportException(), Activity::reraiseException(), result, returnFrom(), senderActivation(), RexxString::strCompare(), termination(), TheFalseObject, TheTrueObject, and ActivationBase::trap().
Referenced by RexxInstructionRaise::execute().
raiseExit()
void RexxActivation::raiseExit (RexxString * condition, RexxObject * rc, RexxString * description, RexxObject * additional, RexxObject * resultObj, DirectoryClass * conditionobj)
Raise a condition using exit semantics for the returned value.
Parameters
condition The condition to raise.
rc The RC value for the condition.
description The condition description
additional The addtional information for the condition.
resultObj The result object.
conditionobj Any propagated condition object.
Definition at line 1714 of file RexxActivation.cpp.
References activity, Activity::callTerminationExit(), exitFrom(), isProgramLevelCall(), isTopLevelCall(), OREF_NULL, parent, Activity::popStackFrame(), raiseExit(), and termination().
Referenced by RexxInstructionRaise::execute(), and raiseExit().
random()
RexxInteger * RexxActivation::random (RexxInteger * randmin, RexxInteger * randmax, RexxInteger * randseed)
Process the random function, using the current activation seed value.
Parameters
randmin The lower bounds of the range
randmax The upper bounds of the range.
randseed The optional seed value.
Returns
A new random number.
Definition at line 3471 of file RexxActivation.cpp.
References DefaultRandomMax, DefaultRandomMin, Error_Incorrect_call_random, Error_Incorrect_call_random_range, getRandomSeed(), RexxInteger::getValue(), MaxRandomRange, new_integer(), OREF_NULL, reportException(), and work.
RANDOMIZE()
static uint64_t RexxActivation::RANDOMIZE (uint64_t seed) inline static
Definition at line 597 of file RexxActivation.hpp.
References RANDOM_ADDER, and RANDOM_FACTOR.
Referenced by getRandomSeed().
removeBlockInstruction()
void RexxActivation::removeBlockInstruction () inline
Definition at line 310 of file RexxActivation.hpp.
References blockNest, and unindent().
Referenced by RexxInstructionEnd::execute(), RexxBlockInstruction::handleDebugPause(), and popBlockInstruction().
removeFileName()
void RexxActivation::removeFileName (RexxString * fullName)
Remove a filename from the short name lookup table
Parameters
fullName The fully qualified name
Definition at line 5100 of file RexxActivation.cpp.
References ActivationSettings::fileNames, getStreams(), notCaseSensitive(), OREF_NULL, HashCollection::remove(), HashCollection::removeItem(), and settings.
reply()
void RexxActivation::reply (RexxObject * resultObj)
Process a REXX REPLY instruction
Parameters
resultObj The reply result object.
Definition at line 1023 of file RexxActivation.cpp.
References Error_Execution_reply, ActivationSettings::isReplyIssued(), REPLIED, reportException(), result, ActivationSettings::setReplyIssued(), settings, and stopExecution().
Referenced by RexxInstructionReply::execute().
resetDebug()
void RexxActivation::resetDebug () inline
Definition at line 385 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, TraceSetting::resetDebug(), ActivationSettings::setDebugBypass(), settings, and PackageSetting::traceSettings.
Referenced by exitFrom(), forward(), and returnFrom().
resetElapsed()
void RexxActivation::resetElapsed ()
Reset the elapsed time counter for the activation.
Definition at line 3411 of file RexxActivation.cpp.
References setElapsedTimerInvalid().
resolveAddressIOConfig()
CommandIOContext * RexxActivation::resolveAddressIOConfig (RexxString * address, CommandIOConfiguration * localConfig)
resolve an IO configuration from an address name.
Parameters
address The address environment name
localConfig The configuration that may have been specified on an ADDRESS instruction.
Returns
The IO context created by the potential merger of local and global IO configurations.
Definition at line 4308 of file RexxActivation.cpp.
References CommandIOConfiguration::createIOContext(), getIOConfig(), OREF_NULL, and stack.
Referenced by command().
resolveDotVariable()
RexxObject * RexxActivation::resolveDotVariable (RexxString * name, RexxObject *& cachedValue)
Resolve a class in this activation's context.
Parameters
name The name to resolve.
Returns
The resolved class, or OREF_NULL if not found.
Definition at line 3211 of file RexxActivation.cpp.
References PackageClass::findClass(), getPackageObject(), isInterpret(), parent, and resolveDotVariable().
Referenced by RexxDotVariable::evaluate(), RexxDotVariable::getValue(), and resolveDotVariable().
resolveProgramName()
RexxString * RexxActivation::resolveProgramName (RexxString * name, ResolveType type)
This is resolved in the context of the calling program.
Parameters
name The name to resolve.
type The resolve type, RESOLVE_DEFAULT or RESOLVE_REQUIRES.
Returns
The fully resolved program name, or OREF_NULL if this can't be located.
Definition at line 3177 of file RexxActivation.cpp.
References activity, code, RexxCode::resolveProgramName(), and type.
Referenced by callExternalRexx().
resolveStream()
RexxObject * RexxActivation::resolveStream (RexxString * name, bool input, Protected< RexxString > & fullName, bool * added)
Resolve a stream name for a BIF call.
Parameters
name The name of the stream.
stack The expression stack.
input The input/output flag.
fullName The returned full name of the stream.
added A flag indicating we added this. Set this pointer to NULL for a lookup without adding to the stream table.
Returns
The backing stream object for the name.
Definition at line 1911 of file RexxActivation.cpp.
References SecurityManager::checkStreamAccess(), HashCollection::get(), getEffectiveSecurityManager(), getFileNames(), RexxString::getLength(), getLocalEnvironment(), getStreams(), notCaseSensitive(), OREF_NULL, HashCollection::put(), Interpreter::qualifyFileSystemName(), result, RexxObject::sendMessage(), RexxString::strCaselessCompare(), and TheRexxPackage.
retriever()
RexxVariableBase* RexxActivation::retriever (RexxString *)
returnFrom()
void RexxActivation::returnFrom (RexxObject * resultObj)
process a REXX RETURN instruction
Parameters
resultObj the return result object.
Definition at line 1043 of file RexxActivation.cpp.
References activity, Activity::callTerminationExit(), Error_Execution_reply_return, isInterpret(), isProgramLevelCall(), ActivationSettings::isReplyIssued(), OREF_NULL, parent, reportException(), resetDebug(), result, RETURNED, returnFrom(), settings, and stopExecution().
Referenced by RexxInstructionReturn::execute(), raise(), and returnFrom().
rexxVariable()
RexxObject * RexxActivation::rexxVariable (RexxString * name)
Return a Rexx-defined "dot" variable name
Parameters
name The target variable name.
Returns
The variable value or OREF_NULL if this is not one of the special variables.
Definition at line 2815 of file RexxActivation.cpp.
References RexxString::concatToCstring(), current, getContextObject(), RexxInstruction::getLineNumber(), RexxCode::getMethods(), RexxCode::getResources(), RexxCode::getRoutines(), isInterpret(), ActivationSettings::isReturnStatusSet(), new_integer(), OREF_NULL, parent, ActivationSettings::parentCode, ActivationSettings::returnStatus, rexxVariable(), settings, and RexxString::strCompare().
Referenced by RexxDotVariable::evaluate(), RexxDotVariable::getValue(), and rexxVariable().
run() [1/2]
RexxObject* RexxActivation::run (RexxObject ** _arglist, size_t _argcount, ProtectedObject & _result) inline
Definition at line 181 of file RexxActivation.hpp.
References OREF_NULL, and run().
run() [2/2]
RexxObject * RexxActivation::run (RexxObject * _receiver, RexxString * name, RexxObject ** _arglist, size_t _argcount, RexxInstruction * start, ProtectedObject & resultObj)
Run some Rexx code...this is it! This is the heart of the interpreter that makes the whole thing run!
Parameters
_receiver The target receiver object (if a method call)
name The message, routine, or program name.
_arglist The argument list.
_argcount The count of arguments.
start The starting instruction.
resultObj A protected object for returning a result.
Returns
The execution result (also returned via the protected object.)
Definition at line 456 of file RexxActivation.cpp.
References ACTIVE, activity, Activity::allocateFrame(), argCount, argList, Activity::callInitializationExit(), MemoryObject::checkUninitQueue(), clauseBoundary, ExpressionStack::clear(), RexxLocalVariables::clearNested(), code, conditionQueue, current, ActivityManager::currentActivity, debugPause, ActivationFrame::disableFrame(), RexxInstruction::execute(), executionState, RexxCode::getFirstInstruction(), ExpressionStack::getFrame(), Activity::getInstance(), RexxObject::getObjectVariables(), getSettings(), RexxInstruction::getType(), ActivationSettings::hasTransferFailed(), implicitExit(), RexxCode::install(), instructionCount, Activity::isClauseExitUsed(), ArrayClass::isEmpty(), isGuarded(), isInternalCall(), isInterpret(), isMethodOrRoutine(), RexxLocalVariables::isNested(), RexxInternalObject::isOldSpace(), isProgramLevelCall(), isTopLevelCall(), RexxInstruction::isType(), KEYWORD_EXPOSE, KEYWORD_LABEL, KEYWORD_PROCEDURE, ActivationSettings::localVariables, memoryObject, mergeTraps(), ActivationSettings::messageName, RexxLocalVariables::migrate(), ExpressionStack::migrate(), next, RexxInstruction::nextInstruction, ActivationBase::objectScope, ActivationSettings::objectVariables, OREF_NULL, parent, ActivationSettings::parentArgCount, ActivationSettings::parentArgList, pauseLabel(), Activity::popStackFrame(), processClauseBoundary(), processTraps(), Activity::pushStackFrame(), receiver, Activity::releaseStackFrame(), Activity::relinquish(), ActivityManager::relinquishIfNeeded(), REPLIED, Activity::requestAccess(), VariableDictionary::reserve(), result, RETURNED, Activity::run(), scope, ActivationBase::SCOPE_RESERVED, Activity::setCallerStackFrameAsStringTable(), ActivationSettings::setHaveClauseExits(), setLocalVariable(), ActivationSettings::setProcedureValid(), settings, ActivationSettings::setTransferFailed(), InterpreterInstance::setupProgram(), Activity::spawnReply(), stack, stopExecution(), RexxObject::superScope(), termination(), ActivationSettings::timeStamp, TRACE_PREFIX_INVOCATION_EXIT, traceEntry(), traceEntryAllowed, traceEntryDone, traceEntryOrExit(), tracingAll(), tracingLabels(), VariableDictionary::transfer(), Activity::unwindToFrame(), RexxDateTime::valid, VARIABLE_SELF, VARIABLE_SUPER, and yieldInstructions.
Referenced by RexxCode::call(), debugInterpret(), dispatch(), internalCall(), internalCallTrap(), interpret(), RexxCode::run(), and run().
sayOutput()
void RexxActivation::sayOutput (RexxString * line)
Handle SAY output for a SAY instruction.
Parameters
line The line to write out.
Definition at line 4699 of file RexxActivation.cpp.
References activity, line, and Activity::sayOutput().
Referenced by RexxInstructionSay::execute().
senderActivation()
ActivationBase * RexxActivation::senderActivation (RexxString * conditionName)
Retrieve the activation that activated this activation (whew) with the intent of doing condition trapping.
Returns
The parent activation.
Definition at line 2712 of file RexxActivation.cpp.
References ActivationBase::getPreviousStackFrame(), isOfClass, OREF_NULL, and ActivationBase::willTrap().
Referenced by raise().
setAddress()
void RexxActivation::setAddress (RexxString * address, CommandIOConfiguration * config)
Set the new current address, moving the current one to the alternate address
Parameters
address The new address setting. The current setting becomes the alternate.
Definition at line 2108 of file RexxActivation.cpp.
References addIOConfig(), ActivationSettings::alternateAddress, ActivationSettings::currentAddress, OREF_NULL, and settings.
Referenced by RexxInstructionAddress::execute().
setCallType()
void RexxActivation::setCallType (RexxString * type) inline
Definition at line 295 of file RexxActivation.hpp.
References ActivationSettings::calltype, settings, and type.
setConditionObj()
void RexxActivation::setConditionObj (DirectoryClass * condition) inline
Definition at line 332 of file RexxActivation.hpp.
References ActivationSettings::conditionObj, and settings.
Referenced by internalCallTrap(), and RexxInstructionSignalOn::trap().
setCurrent()
void RexxActivation::setCurrent (RexxInstruction * v) inline
Definition at line 335 of file RexxActivation.hpp.
References current.
Referenced by ClassDirective::install().
setDefaultAddress()
void RexxActivation::setDefaultAddress (RexxString * address)
Set up a default address environment so that both the primary and the alternate address are the same value
Parameters
address The new default address name.
Definition at line 2128 of file RexxActivation.cpp.
References ActivationSettings::alternateAddress, ActivationSettings::currentAddress, and settings.
Referenced by RexxActivation().
setDigits()
void RexxActivation::setDigits (wholenumber_t digitsVal) override virtual
Set a new digits setting
Parameters
digitsVal The new digits value.
Reimplemented from ActivationBase.
Definition at line 2221 of file RexxActivation.cpp.
References isInterpret(), ActivationSettings::packageSettings, parent, PackageSetting::setDigits(), setDigits(), and settings.
Referenced by RexxInstructionNumeric::execute(), NativeActivation::setDigits(), and setDigits().
setElapsedTimerInvalid()
void RexxActivation::setElapsedTimerInvalid () inline
Definition at line 425 of file RexxActivation.hpp.
References ActivationSettings::setElapsedTimerReset(), and settings.
Referenced by resetElapsed().
setElapsedTimerValid()
void RexxActivation::setElapsedTimerValid () inline
Definition at line 426 of file RexxActivation.hpp.
References ActivationSettings::setElapsedTimerReset(), and settings.
Referenced by getTime().
setForm()
void RexxActivation::setForm (bool formVal) override virtual
Set a new form setting
Parameters
formVal The new form setting
Reimplemented from ActivationBase.
Definition at line 2252 of file RexxActivation.cpp.
References isInterpret(), ActivationSettings::packageSettings, parent, PackageSetting::setForm(), setForm(), and settings.
Referenced by RexxInstructionNumeric::execute(), NativeActivation::setForm(), and setForm().
setFuzz()
void RexxActivation::setFuzz (wholenumber_t fuzzVal) override virtual
Set a new fuzz setting
Parameters
fuzzVal The new fuzz value.
Reimplemented from ActivationBase.
Definition at line 2237 of file RexxActivation.cpp.
References isInterpret(), ActivationSettings::packageSettings, parent, PackageSetting::setFuzz(), setFuzz(), and settings.
Referenced by RexxInstructionNumeric::execute(), NativeActivation::setFuzz(), and setFuzz().
setGuarded()
void RexxActivation::setGuarded () inline
Definition at line 416 of file RexxActivation.hpp.
References ActivationSettings::setGuarded(), and settings.
Referenced by RexxActivation().
setIndent()
void RexxActivation::setIndent (size_t v) inline
Definition at line 321 of file RexxActivation.hpp.
References settings, and ActivationSettings::traceIndent.
Referenced by RexxInstructionEnd::execute(), and iterate().
setLocalCompoundVariable()
void RexxActivation::setLocalCompoundVariable (RexxString * stemName, size_t index, RexxInternalObject ** tail, size_t tailCount, RexxObject * value)
set a compound variable in the local context.
Parameters
stemName The stem variable name.
index The index of the stem variable (if known)
tail The array of tail elements.
tailCount The count of tail elements.
value The value to assign.
Definition at line 4917 of file RexxActivation.cpp.
References getLocalStem(), and StemClass::setCompoundVariable().
Referenced by RexxCompoundVariable::set().
setLocalVariable()
void RexxActivation::setLocalVariable (RexxString * name, size_t index, RexxObject * value) inline
Definition at line 534 of file RexxActivation.hpp.
References getLocalVariable(), and RexxVariable::set().
Referenced by RexxSimpleVariable::assign(), command(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxInstructionForward::execute(), RexxInstructionMessage::execute(), internalCall(), internalCallTrap(), processTraps(), run(), RexxSimpleVariable::set(), and signalTo().
setLocalVariableDictionary()
void RexxActivation::setLocalVariableDictionary (VariableDictionary * dict) inline
Definition at line 582 of file RexxActivation.hpp.
References ActivationSettings::localVariables, RexxLocalVariables::setDictionary(), and settings.
Referenced by cleanupLocalVariables().
setNext()
void RexxActivation::setNext (RexxInstruction * v) inline
Definition at line 334 of file RexxActivation.hpp.
References next.
Referenced by RexxInstructionBaseLoop::endLoop(), RexxInstructionEndIf::execute(), RexxInstructionIf::execute(), RexxInstructionCaseWhen::execute(), RexxBlockInstruction::handleDebugPause(), RexxInstructionBaseLoop::reExecute(), RexxBaseBlockInstruction::terminate(), and RexxInstructionSelect::terminate().
setObjNotify()
void RexxActivation::setObjNotify (MessageClass * notify) override virtual
Set an error notification tag on the activation.
Parameters
notify The notification object.
Reimplemented from ActivationBase.
Definition at line 4611 of file RexxActivation.cpp.
References notifyObject.
setReturnStatus()
void RexxActivation::setReturnStatus (ReturnStatus status)
Set the return status flag for an activation context.
Parameters
status The new status value.
Definition at line 4519 of file RexxActivation.cpp.
References ActivationSettings::returnStatus, ActivationSettings::setReturnStatus(), and settings.
Referenced by command().
setTrace() [1/2]
void RexxActivation::setTrace (const TraceSetting & source)
Set a new trace setting for the context.
Parameters
source The trace setting source.
Definition at line 961 of file RexxActivation.cpp.
References debugPause, ActivationSettings::intermediateTrace, TraceSetting::isDebug(), TraceSetting::isDebugToggle(), TraceSetting::isNoSetting(), TraceSetting::isTraceOff(), ActivationSettings::packageSettings, TraceSetting::set(), ActivationSettings::setDebugBypass(), ActivationSettings::setDebugPromptIssued(), settings, TraceSetting::setTraceOff(), ActivationSettings::setTraceSuppressed(), TraceSetting::toggleDebug(), traceEntry(), PackageSetting::traceSettings, ActivationSettings::traceSkip, and TraceSetting::tracingIntermediates().
Referenced by disableExternalTrace(), enableExternalTrace(), RexxInstructionTrace::execute(), and setTrace().
setTrace() [2/2]
void RexxActivation::setTrace (RexxString * setting)
Set the trace using a dynamically evaluated string.
Parameters
setting The new trace setting.
Definition at line 941 of file RexxActivation.cpp.
References Error_Invalid_trace_trace, new_string(), TraceSetting::parseTraceSetting(), reportException(), and setTrace().
signalTo()
void RexxActivation::signalTo (RexxInstruction * target)
Signal to a target instruction
Parameters
target The target of the signal instruction.
Definition at line 2065 of file RexxActivation.cpp.
References blockNest, current, doStack, RexxInstruction::getLineNumber(), isInterpret(), new_integer(), next, OREF_NULL, parent, RETURNED, setLocalVariable(), settings, signalTo(), stopExecution(), ActivationSettings::traceIndent, and VARIABLE_SIGL.
Referenced by RexxInstructionSignal::execute(), signalTo(), signalValue(), and RexxInstructionSignalOn::trap().
signalValue()
void RexxActivation::signalValue (RexxString * name)
Signal to a computed label target
Parameters
name The computed string name.
Definition at line 2140 of file RexxActivation.cpp.
References Error_Label_not_found_name, HashCollection::get(), getLabels(), OREF_NULL, reportException(), and signalTo().
Referenced by RexxInstructionDynamicSignal::execute().
sourceString()
RexxString * RexxActivation::sourceString ()
Create the source string returned by parse source
Returns
The constructed source string.
Definition at line 4565 of file RexxActivation.cpp.
References RexxString::StringBuilder::append(), ActivationSettings::calltype, code, RexxString::getLength(), SystemInterpreter::getPlatformName(), RexxCode::getProgramName(), isInterpret(), parent, raw_string(), settings, and sourceString().
Referenced by RexxInstructionParse::execute(), sourceString(), traceSourceString(), and NativeActivation::variablePoolFetchPrivate().
stopExecution()
void RexxActivation::stopExecution (ExecutionState state) inline
Definition at line 404 of file RexxActivation.hpp.
References executionState, next, and OREF_NULL.
Referenced by exitFrom(), forward(), reply(), returnFrom(), run(), and signalTo().
terminateBlockInstruction() [1/2]
void RexxActivation::terminateBlockInstruction () inline
Definition at line 308 of file RexxActivation.hpp.
References popBlockInstruction().
terminateBlockInstruction() [2/2]
void RexxActivation::terminateBlockInstruction (size_t _indent) inline
Definition at line 307 of file RexxActivation.hpp.
References popBlockInstruction(), settings, and ActivationSettings::traceIndent.
Referenced by RexxInstructionEndIf::execute(), RexxInstructionEnd::execute(), RexxBaseBlockInstruction::terminate(), and RexxInstructionSelect::terminate().
termination()
void RexxActivation::termination () override virtual
do any cleanup due to a program terminating.
Reimplemented from ActivationBase.
Definition at line 1444 of file RexxActivation.cpp.
References activity, argCount, argList, cleanupLocalVariables(), closeStreams(), contextObject, RexxContext::detach(), environmentList, ExpressionStack::getFrame(), ArrayClass::getLastItem(), guardOff(), ArrayClass::isEmpty(), ActivationSettings::isForwarded(), isMethodOrRoutine(), OREF_NULL, pauseLabel(), Activity::releaseStackFrame(), SystemInterpreter::restoreEnvironment(), ActivationSettings::setForwarded(), settings, stack, TRACE_PREFIX_INVOCATION_EXIT, traceEntryDone, traceEntryOrExit(), tracingAll(), and tracingLabels().
Referenced by exitFrom(), forward(), raise(), raiseExit(), and run().
toggleAddress()
void RexxActivation::toggleAddress ()
Toggle the address setting between the current and alternate
Definition at line 2093 of file RexxActivation.cpp.
References ActivationSettings::alternateAddress, ActivationSettings::currentAddress, and settings.
Referenced by RexxInstructionAddress::execute().
topBlockInstruction()
DoBlock* RexxActivation::topBlockInstruction () inline
Definition at line 306 of file RexxActivation.hpp.
References doStack.
Referenced by RexxInstructionEnd::execute(), RexxInstructionCaseWhen::execute(), iterate(), and leaveLoop().
traceArgument()
void RexxActivation::traceArgument (RexxObject * v) inline
Definition at line 341 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_ARGUMENT, and traceValue().
Referenced by RexxExpressionList::evaluate(), RexxInstruction::evaluateArguments(), RexxInstructionForward::execute(), and RexxInstructionRaise::execute().
traceAssignment()
void RexxActivation::traceAssignment (RexxString * n, RexxObject * v) inline
Definition at line 356 of file RexxActivation.hpp.
References ASSIGNMENT_MARKER, ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_ASSIGNMENT, and traceTaggedValue().
Referenced by RexxExpressionMessage::assign(), RexxStemVariable::assign(), and RexxSimpleVariable::assign().
traceClassResolution()
void RexxActivation::traceClassResolution (RexxString * n, RexxString * c, RexxObject * v) inline
Definition at line 358 of file RexxActivation.hpp.
References RexxString::concatWith(), ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_NAMESPACE, traceTaggedValue(), and VALUE_MARKER.
Referenced by ClassResolver::evaluate().
traceClause()
void RexxActivation::traceClause (RexxInstruction * clause, TracePrefix prefix)
Trace an individual line of a source file
Parameters
clause the clause to trace.
prefix
Definition at line 4274 of file RexxActivation.cpp.
References activity, code, formatTrace(), BaseCode::getPackageObject(), inDebug(), line, noTracing(), NULLOBJECT, OREF_NULL, processTraceInfo(), settings, traceSourceString(), and ActivationSettings::wasSourceTraced().
Referenced by command(), traceCommand(), traceInstruction(), and traceLabel().
traceCommand()
void RexxActivation::traceCommand (RexxInstruction * v) inline
Definition at line 378 of file RexxActivation.hpp.
References TRACE_PREFIX_CLAUSE, traceClause(), and tracingCommands().
Referenced by RexxInstructionAddress::execute(), and RexxInstructionCommand::execute().
traceCompound()
void RexxActivation::traceCompound (RexxString * stemVar, RexxInternalObject ** tails, size_t tailCount, RexxObject * value) inline
Definition at line 362 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_VARIABLE, traceCompoundValue(), and VALUE_MARKER.
Referenced by evaluateLocalCompoundVariable().
traceCompoundAssignment()
void RexxActivation::traceCompoundAssignment (RexxString * stemVar, RexxInternalObject ** tails, size_t tailCount, RexxObject * value) inline
Definition at line 363 of file RexxActivation.hpp.
References ASSIGNMENT_MARKER, ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_ASSIGNMENT, and traceCompoundValue().
Referenced by assignLocalCompoundVariable().
traceCompoundName() [1/2]
void RexxActivation::traceCompoundName (RexxString * stemVar, RexxInternalObject ** tails, size_t tailCount, CompoundVariableTail & tail) inline
Definition at line 360 of file RexxActivation.hpp.
References CompoundVariableTail::createCompoundName(), ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_COMPOUND, traceCompoundValue(), and VALUE_MARKER.
Referenced by assignLocalCompoundVariable(), evaluateLocalCompoundVariable(), RexxCompoundVariable::expose(), and RexxCompoundVariable::procedureExpose().
traceCompoundName() [2/2]
void RexxActivation::traceCompoundName (RexxString * stemVar, RexxInternalObject ** tails, size_t tailCount, RexxString * tail) inline
Definition at line 361 of file RexxActivation.hpp.
References RexxString::concat(), ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_COMPOUND, traceCompoundValue(), and VALUE_MARKER.
traceCompoundValue() [1/2]
void RexxActivation::traceCompoundValue (TracePrefix prefix, RexxString * stemName, RexxInternalObject ** tails, size_t tailCount, const char * marker, RexxObject * value)
Trace a compound variable entry that's of the form 'tag => "value"'.
Parameters
prefix The trace prefix tag to use.
stem The stem name of the compound.
tails The array of tail elements (unresolved).
tailCount The count of tail elements.
value The associated trace value.
Definition at line 3914 of file RexxActivation.cpp.
References activity, CompoundVariableTail::getLength(), RexxString::getLength(), CompoundVariableTail::getTail(), INDENT_SPACING, noTracing(), NULLOBJECT, PREFIX_LENGTH, PREFIX_OFFSET, processTraceInfo(), RexxString::put(), RexxString::putChar(), raw_string(), RexxString::set(), settings, RexxObject::stringValue(), TRACE_OVERHEAD, trace_prefix_table, and ActivationSettings::traceIndent.
traceCompoundValue() [2/2]
void RexxActivation::traceCompoundValue (TracePrefix prefix, RexxString * stemName, RexxInternalObject ** tails, size_t tailCount, CompoundVariableTail & tail)
Trace a compound variable entry that's of the form 'tag => "value"'.
Parameters
prefix The trace prefix tag to use.
stem The stem name of the compound.
tails The array of tail elements (unresolved).
tailCount The count of tail elements.
value The resolved tail element
Definition at line 3897 of file RexxActivation.cpp.
References CompoundVariableTail::createCompoundName(), and VALUE_MARKER.
Referenced by traceCompound(), traceCompoundAssignment(), and traceCompoundName().
traceDotVariable()
void RexxActivation::traceDotVariable (RexxString * n, RexxObject * v) inline
Definition at line 344 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_DOTVARIABLE, traceTaggedValue(), and VALUE_MARKER.
Referenced by RexxDotVariable::evaluate().
traceEntry()
void RexxActivation::traceEntry ()
Trace program entry for a method or routine
Definition at line 3598 of file RexxActivation.cpp.
References current, RexxInstruction::getType(), isInterpret(), isMethodOrRoutine(), KEYWORD_EXPOSE, KEYWORD_TRACE, RexxInstruction::nextInstruction, RexxInstructionTrace::nonDynamicTracingLabels(), OREF_NULL, parent, pauseLabel(), TRACE_PREFIX_INVOCATION, traceEntryAllowed, traceEntryDone, traceEntryOrExit(), tracingAll(), and tracingLabels().
Referenced by run(), and setTrace().
traceEntryOrExit()
void RexxActivation::traceEntryOrExit (TracePrefix tp)
Trace program entry or exit for a method or routine
Definition at line 3651 of file RexxActivation.cpp.
References activity, Activity::buildMessage(), ActivationBase::executable, ActivationBase::getExecutable(), RexxString::getLength(), getMessageName(), BaseExecutable::getName(), getPackage(), PackageClass::getProgramName(), RexxString::getStringData(), INSTRUCTION_OVERHEAD, isInterpret(), isMethod(), Message_Translations_method_invocation, Message_Translations_routine_invocation, new_array(), NULLOBJECT, OREF_NULL, parent, PREFIX_LENGTH, PREFIX_OFFSET, processTraceInfo(), RexxString::put(), raw_string(), RexxString::set(), ActivationSettings::setSourceTraced(), settings, and trace_prefix_table.
Referenced by run(), termination(), and traceEntry().
traceFunction()
void RexxActivation::traceFunction (RexxString * n, RexxObject * v) inline
Definition at line 348 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_FUNCTION, traceTaggedValue(), and VALUE_MARKER.
Referenced by RexxExpressionFunction::evaluate(), and QualifiedFunction::evaluate().
traceInstruction()
void RexxActivation::traceInstruction (RexxInstruction * v) inline
Definition at line 376 of file RexxActivation.hpp.
References TRACE_PREFIX_CLAUSE, traceClause(), and tracingAll().
Referenced by ConstantDirective::execute(), RexxInstructionAddress::execute(), RexxInstructionAssignment::execute(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxInstructionCallOn::execute(), RexxInstructionSimpleDo::execute(), RexxInstructionBaseLoop::execute(), RexxInstructionDrop::execute(), RexxInstructionElse::execute(), RexxInstructionEnd::execute(), RexxInstructionExit::execute(), RexxInstructionExpose::execute(), RexxInstructionForward::execute(), RexxInstructionGuard::execute(), RexxInstructionIf::execute(), RexxInstructionInterpret::execute(), RexxInstructionLeave::execute(), RexxInstructionMessage::execute(), RexxInstructionNop::execute(), RexxInstructionNumeric::execute(), RexxInstructionOptions::execute(), RexxInstructionOtherwise::execute(), RexxInstructionParse::execute(), RexxInstructionProcedure::execute(), RexxInstructionQueue::execute(), RexxInstructionRaise::execute(), RexxInstructionReply::execute(), RexxInstructionReturn::execute(), RexxInstructionSay::execute(), RexxInstructionSelect::execute(), RexxInstructionSelectCase::execute(), RexxInstructionSignal::execute(), RexxInstructionDynamicSignal::execute(), RexxInstructionSignalOn::execute(), RexxInstructionThen::execute(), RexxInstructionTrace::execute(), RexxInstructionUse::execute(), RexxInstructionUseLocal::execute(), RexxInstructionCaseWhen::execute(), and RexxInstructionBaseLoop::reExecute().
traceIntermediate()
void RexxActivation::traceIntermediate (RexxObject * v, TracePrefix p) inline
Definition at line 340 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, and traceValue().
Referenced by RexxInteger::evaluate(), NumberString::evaluate(), RexxString::evaluate(), and ParseTrigger::parse().
traceKeywordResult()
void RexxActivation::traceKeywordResult (RexxString * k, RexxObject * v) inline
Definition at line 370 of file RexxActivation.hpp.
References TRACE_PREFIX_KEYWORD, traceTaggedValue(), tracingResults(), and VALUE_MARKER.
Referenced by WhileUntilLoop::checkUntil(), WhileUntilLoop::checkWhile(), CommandIOConfiguration::createInputSource(), CommandIOConfiguration::createOutputTarget(), DoBlock::DoBlock(), RexxInstructionForward::execute(), RexxInstructionGuard::execute(), RexxInstructionNumeric::execute(), RexxInstructionParse::execute(), RexxInstructionRaise::execute(), RexxInstructionSelectCase::execute(), RexxInstructionDynamicSignal::execute(), RexxInstructionTrace::execute(), DoBlock::setCounter(), ControlledLoop::setup(), OverLoop::setup(), WithLoop::setup(), and ForLoop::setup().
traceLabel()
void RexxActivation::traceLabel (RexxInstruction * v) inline
Definition at line 377 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, settings, TRACE_PREFIX_CLAUSE, traceClause(), PackageSetting::traceSettings, and TraceSetting::tracingLabels().
Referenced by RexxInstructionLabel::execute().
traceMessage()
void RexxActivation::traceMessage (RexxString * n, RexxObject * v) inline
Definition at line 350 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_MESSAGE, traceTaggedValue(), and VALUE_MARKER.
Referenced by RexxExpressionMessage::evaluate(), and RexxInstructionMessage::execute().
traceOperator()
void RexxActivation::traceOperator (const char * n, RexxObject * v) inline
Definition at line 352 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_OPERATOR, and traceOperatorValue().
Referenced by RexxBinaryOperator::evaluate(), and VariableReferenceOp::evaluate().
traceOperatorValue()
void RexxActivation::traceOperatorValue (TracePrefix prefix, const char * tag, RexxObject * value)
Trace an entry that's of the form 'tag => "value"'.
Parameters
prefix The trace prefix tag to use.
tagPrefix Any prefix string added to the tag. Use mostly for adding the "." to traced environment variables.
quoteTag Indicates whether the tag should be quoted or not. Operator names are quoted.
tag The tag name.
value The associated trace value.
Definition at line 3825 of file RexxActivation.cpp.
References activity, RexxString::getLength(), INDENT_SPACING, noTracing(), NULLOBJECT, PREFIX_LENGTH, PREFIX_OFFSET, processTraceInfo(), RexxString::put(), RexxString::putChar(), QUOTES_OVERHEAD, raw_string(), RexxString::set(), settings, RexxObject::stringValue(), TRACE_OVERHEAD, trace_prefix_table, ActivationSettings::traceIndent, and VALUE_MARKER.
Referenced by traceOperator(), and tracePrefix().
tracePrefix()
void RexxActivation::tracePrefix (const char * n, RexxObject * v) inline
Definition at line 354 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_PREFIX, and traceOperatorValue().
Referenced by createTraceObject(), RexxUnaryOperator::evaluate(), and processTraceInfo().
traceResult()
void RexxActivation::traceResult (RexxObject * v) inline
Definition at line 369 of file RexxActivation.hpp.
References TRACE_PREFIX_RESULT, traceValue(), and tracingResults().
Referenced by RexxExpressionMessage::assign(), DoBlock::checkControl(), RexxExpressionList::evaluate(), RexxExpressionLogical::evaluate(), RexxInstructionExpression::evaluateExpression(), RexxInstructionExpression::evaluateStringExpression(), ConstantDirective::execute(), RexxInstructionAddress::execute(), RexxInstructionAssignment::execute(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxInstructionForward::execute(), RexxInstructionIf::execute(), RexxInstructionCaseWhen::execute(), UseVariable::handleArgument(), ParseTrigger::integerTrigger(), RexxTarget::next(), ParseTrigger::parse(), and ParseTrigger::stringTrigger().
traceResultValue()
void RexxActivation::traceResultValue (RexxObject * v) inline
Definition at line 372 of file RexxActivation.hpp.
References TRACE_PREFIX_RESULT, and traceValue().
Referenced by RexxInstructionAddress::execute(), and RexxInstructionCommand::execute().
traceSetting()
RexxString * RexxActivation::traceSetting ()
Generate a string version of the current trace setting.
Returns
The current trace setting formatted into a human-readable string.
Definition at line 929 of file RexxActivation.cpp.
References PackageSetting::getTrace(), ActivationSettings::packageSettings, and settings.
traceSourceString()
void RexxActivation::traceSourceString ()
Trace the source string at debug mode start
Definition at line 3980 of file RexxActivation.cpp.
References activity, RexxString::getLength(), RexxString::getStringData(), INSTRUCTION_OVERHEAD, NULLOBJECT, PREFIX_LENGTH, PREFIX_OFFSET, processTraceInfo(), RexxString::put(), RexxString::putChar(), raw_string(), RexxString::set(), ActivationSettings::setSourceTraced(), settings, sourceString(), TRACE_OUTPUT_SOURCE, TRACE_PREFIX_ERROR, trace_prefix_table, and ActivationSettings::wasSourceTraced().
Referenced by traceClause().
traceSpecialDotVariable()
void RexxActivation::traceSpecialDotVariable (RexxString * n, RexxObject * v) inline
Definition at line 346 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_DOTVARIABLE, traceTaggedValue(), and VALUE_MARKER.
Referenced by SpecialDotVariable::evaluate().
traceTaggedValue()
void RexxActivation::traceTaggedValue (TracePrefix prefix, const char * tagPrefix, bool quoteTag, RexxString * tag, const char * marker, RexxObject * value)
Trace an entry that's of the form 'tag => "value"'.
Parameters
prefix The trace prefix tag to use.
tagPrefix Any prefix string added to the tag. Use mostly for adding the "." to traced environment variables.
quoteTag Indicates whether the tag should be quoted or not. Operator names are quoted.
tag The tag name.
marker An additional string marker for the value.
value The associated trace value.
Definition at line 3736 of file RexxActivation.cpp.
References activity, RexxString::getLength(), INDENT_SPACING, noTracing(), PREFIX_LENGTH, PREFIX_OFFSET, processTraceInfo(), RexxString::put(), RexxString::putChar(), QUOTES_OVERHEAD, raw_string(), RexxString::set(), settings, RexxObject::stringValue(), TRACE_OVERHEAD, trace_prefix_table, and ActivationSettings::traceIndent.
Referenced by traceAssignment(), traceClassResolution(), traceDotVariable(), traceFunction(), traceKeywordResult(), traceMessage(), traceSpecialDotVariable(), traceVariable(), and traceVariableAlias().
traceValue()
void RexxActivation::traceValue (RexxObject * value, TracePrefix prefix)
Trace an intermediate or result value.
Parameters
value the value to trace.
prefix The prefix value for the item.
Definition at line 3701 of file RexxActivation.cpp.
References activity, RexxString::getLength(), RexxString::getStringData(), INDENT_SPACING, noTracing(), NULLOBJECT, PREFIX_LENGTH, PREFIX_OFFSET, processTraceInfo(), RexxString::put(), RexxString::putChar(), raw_string(), RexxString::set(), settings, RexxObject::stringValue(), TRACE_OVERHEAD, trace_prefix_table, and ActivationSettings::traceIndent.
Referenced by command(), traceArgument(), traceIntermediate(), traceResult(), and traceResultValue().
traceVariable()
void RexxActivation::traceVariable (RexxString * n, RexxObject * v) inline
Definition at line 342 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, settings, TRACE_PREFIX_VARIABLE, traceTaggedValue(), and VALUE_MARKER.
Referenced by RexxStemVariable::evaluate(), and RexxSimpleVariable::evaluate().
traceVariableAlias()
void RexxActivation::traceVariableAlias (RexxString * k, RexxString * v) inline
Definition at line 371 of file RexxActivation.hpp.
References TRACE_PREFIX_ALIAS, traceTaggedValue(), tracingResults(), and VALUE_MARKER.
Referenced by UseVariable::handleReferenceArgument().
tracingAll()
bool RexxActivation::tracingAll () inline
Definition at line 366 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, settings, PackageSetting::traceSettings, and TraceSetting::tracingAll().
Referenced by command(), run(), termination(), traceEntry(), traceInstruction(), and tracingInstructions().
tracingCommands()
bool RexxActivation::tracingCommands () inline
Definition at line 379 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, settings, PackageSetting::traceSettings, and TraceSetting::tracingCommands().
Referenced by command(), RexxInstructionAddress::execute(), RexxInstructionCommand::execute(), and traceCommand().
tracingErrors()
bool RexxActivation::tracingErrors () inline
Definition at line 374 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, settings, PackageSetting::traceSettings, and TraceSetting::tracingErrors().
Referenced by command().
tracingFailures()
bool RexxActivation::tracingFailures () inline
Definition at line 375 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, settings, PackageSetting::traceSettings, and TraceSetting::tracingFailures().
Referenced by command().
tracingInstructions()
bool RexxActivation::tracingInstructions () inline
Definition at line 373 of file RexxActivation.hpp.
References tracingAll().
Referenced by RexxInstructionAssignment::execute().
tracingIntermediates()
bool RexxActivation::tracingIntermediates () inline
Definition at line 323 of file RexxActivation.hpp.
References ActivationSettings::intermediateTrace, and settings.
Referenced by assignLocalCompoundVariable(), evaluateLocalCompoundVariable(), and ParseTrigger::parse().
tracingLabels()
bool RexxActivation::tracingLabels () inline
Definition at line 367 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, settings, PackageSetting::traceSettings, and TraceSetting::tracingLabels().
Referenced by run(), termination(), and traceEntry().
tracingResults()
bool RexxActivation::tracingResults () inline
Definition at line 365 of file RexxActivation.hpp.
References ActivationSettings::packageSettings, settings, PackageSetting::traceSettings, and TraceSetting::tracingResults().
Referenced by ParseTrigger::parse(), traceKeywordResult(), traceResult(), and traceVariableAlias().
trap()
bool RexxActivation::trap (RexxString * condition, DirectoryClass * exceptionObject) override virtual
Check the activation to see if this is trapping a condition. For SIGNAL traps, control goes back to the point of the trap via throw. For CALL ON traps, the condition is saved, and the method returns true to indicate the trap was handled.
Parameters
condition The name of the raised condition.
exceptionObject The exception object associated with the condition.
Returns
true if the condition was trapped and handled, false otherwise.
Reimplemented from ActivationBase.
Definition at line 2419 of file RexxActivation.cpp.
References activity, ANY, ArrayClass::append(), Activity::callHaltClearExit(), TrapHandler::canHandle(), clauseBoundary, Activity::clearCurrentCondition(), conditionQueue, debugPause, Activity::displayDebug(), MessageClass::error(), HashCollection::get(), ActivationBase::getPreviousStackFrame(), TrapHandler::instructionName(), ActivationBase::isForwarded(), ActivationSettings::isForwarded(), isInterpret(), isOfClass, TrapHandler::isSignal(), mergeTraps(), new_queue(), notifyObject, OREF_NULL, parent, DirectoryClass::put(), TrapHandler::setConditionObject(), settings, RexxString::strCompare(), ActivationBase::trap(), ActivationSettings::traps, and unwindTrap().
trapDelay()
void RexxActivation::trapDelay (RexxString * condition)
Put a trap into the delay state while executing a CALL ON.
Parameters
condition The condition name.
Definition at line 2378 of file RexxActivation.cpp.
References checkTrapTable(), TrapHandler::disable(), HashCollection::get(), OREF_NULL, settings, and ActivationSettings::traps.
Referenced by RexxInstructionCallOn::trap().
trapOff()
void RexxActivation::trapOff (RexxString * condition, bool signal)
Disable a condition trap
Parameters
condition The name of the condition we're turning off.
Definition at line 1572 of file RexxActivation.cpp.
References ANY, checkTrapTable(), disableErrorSyntax(), disableFailureSyntax(), disableLostdigitsSyntax(), disableNostringSyntax(), disableNotreadySyntax(), disableNovalueSyntax(), HashCollection::hasIndex(), isErrorSyntaxEnabled(), isFailureSyntaxEnabled(), isLostdigitsSyntaxEnabled(), isNostringSyntaxEnabled(), isNotreadySyntaxEnabled(), ActivationSettings::localVariables, HashCollection::remove(), RexxLocalVariables::setNovalueOff(), settings, RexxString::strCompare(), and ActivationSettings::traps.
Referenced by RexxInstructionCallOn::execute(), RexxInstructionSignalOn::execute(), and RexxInstructionSignalOn::trap().
trapOn()
void RexxActivation::trapOn (RexxString * condition, RexxInstructionTrapBase * handler, bool signal)
Activate a condition trap.
Parameters
condition The condition name being trapped.
handler The instruction handling the trap.
Definition at line 1520 of file RexxActivation.cpp.
References ANY, checkTrapTable(), disableErrorSyntax(), disableFailureSyntax(), disableLostdigitsSyntax(), disableNostringSyntax(), disableNotreadySyntax(), disableNovalueSyntax(), isErrorSyntaxEnabled(), isFailureSyntaxEnabled(), isLostdigitsSyntaxEnabled(), isNostringSyntaxEnabled(), isNotreadySyntaxEnabled(), ActivationSettings::localVariables, HashCollection::put(), RexxLocalVariables::setNovalueOn(), settings, RexxString::strCompare(), and ActivationSettings::traps.
Referenced by RexxInstructionCallOn::execute(), and RexxInstructionSignalOn::execute().
trapState()
RexxString * RexxActivation::trapState (RexxString * condition)
Return the current state for a trap as either ON, OFF, or DELAY
Parameters
condition The condition name.
Returns
The trap state, either ON, OFF, or DELAY.
Definition at line 2354 of file RexxActivation.cpp.
References HashCollection::get(), TrapHandler::getState(), OREF_NULL, settings, and ActivationSettings::traps.
trapUndelay()
void RexxActivation::trapUndelay (RexxString * condition)
Remove a trap from the DELAY state
Parameters
condition The condition being processed.
Definition at line 2395 of file RexxActivation.cpp.
References checkTrapTable(), TrapHandler::enable(), HashCollection::get(), OREF_NULL, settings, and ActivationSettings::traps.
Referenced by RexxInstructionCallOn::trap().
unindent()
void RexxActivation::unindent () inline
Definition at line 319 of file RexxActivation.hpp.
References settings, and ActivationSettings::traceIndent.
Referenced by RexxInstructionBaseLoop::endLoop(), RexxInstructionEnd::execute(), and removeBlockInstruction().
unindentTwice()
void RexxActivation::unindentTwice () inline
Definition at line 320 of file RexxActivation.hpp.
References settings, and ActivationSettings::traceIndent.
Referenced by RexxInstructionEndIf::execute().
unwindTrap()
void RexxActivation::unwindTrap (RexxActivation * child)
Unwind a chain of interpret activations to process a SIGNAL ON or PROPAGATE condition trap. This ensures that the SIGNAL or PROPAGATE returns to the correct condition level
Parameters
child The child activity.
Definition at line 2687 of file RexxActivation.cpp.
References conditionQueue, isInterpret(), mergeTraps(), parent, putSettings(), settings, and unwindTrap().
Referenced by trap(), and unwindTrap().
updateLocalVariable()
void RexxActivation::updateLocalVariable (RexxVariable * variable) inline
Definition at line 529 of file RexxActivation.hpp.
References ActivationSettings::localVariables, settings, and RexxLocalVariables::updateVariable().
Referenced by RexxStemVariable::procedureExpose().
willTrap()
bool RexxActivation::willTrap (RexxString * condition) override virtual
Check the activation to see if this is trapping a condition. This does not process the trap, but merely indicates that this activation WILL trap the condition. This is a preliminary check that allows a condition to be raised without having to construct a condition object first. This can be critical for conditions that are not normally trapped, like NOSTRING or LOSTDIGITS.
Parameters
condition The name of the raised condition.
exceptionObject The exception object associated with the condition.
Returns
true if the condition was trapped and handled, false otherwise.
Reimplemented from ActivationBase.
Definition at line 2550 of file RexxActivation.cpp.
References ANY, TrapHandler::canHandle(), debugPause, HashCollection::get(), ActivationBase::getPreviousStackFrame(), ActivationBase::isForwarded(), ActivationSettings::isForwarded(), isOfClass, OREF_NULL, settings, RexxString::strCompare(), ActivationSettings::traps, and ActivationBase::willTrap().
yield()
void RexxActivation::yield ()
Flip ON the externally activated TRACE bit.
Definition at line 4148 of file RexxActivation.cpp.
References instructionCount, and yieldInstructions.
Referenced by Activity::yield().
Member Data Documentation
activationContext
ActivationContext RexxActivation::activationContext protected
Definition at line 643 of file RexxActivation.hpp.
Referenced by inMethod(), isInternalCall(), isInternalLevelCall(), isInterpret(), isMethod(), isProgram(), isProgramLevelCall(), isProgramOrMethod(), isRoutine(), isTopLevel(), isTopLevelCall(), and RexxActivation().
activity
Activity* RexxActivation::activity protected
Definition at line 626 of file RexxActivation.hpp.
Referenced by allocateLocalVariables(), allocateStackFrame(), callExternalRexx(), callMacroSpaceFunction(), command(), createTraceObject(), debugInterpret(), displayUsingTraceOutput(), doDebugPause(), exitFrom(), externalCall(), formatSourcelessTraceLine(), getActivity(), getEffectiveSecurityManager(), getLocalEnvironment(), getObjectVariables(), getStackFrames(), guardOff(), guardOn(), guardWait(), handleNovalueEvent(), implicitExit(), internalCall(), internalCallTrap(), interpret(), lineIn(), live(), liveGeneral(), procedureExpose(), processClauseBoundary(), processTraceInfo(), processTraps(), pullInput(), queue(), raise(), raiseExit(), resolveProgramName(), returnFrom(), RexxActivation(), run(), sayOutput(), termination(), traceClause(), traceCompoundValue(), traceEntryOrExit(), traceOperatorValue(), traceSourceString(), traceTaggedValue(), traceValue(), and trap().
argCount
size_t RexxActivation::argCount protected
Definition at line 629 of file RexxActivation.hpp.
Referenced by debugInterpret(), dispatch(), forward(), getArguments(), getMethodArgumentCount(), interpret(), live(), liveGeneral(), run(), and termination().
argList
RexxObject** RexxActivation::argList protected
Definition at line 628 of file RexxActivation.hpp.
Referenced by debugInterpret(), dispatch(), forward(), getArguments(), getMethodArgument(), getMethodArgumentList(), interpret(), live(), liveGeneral(), run(), and termination().
ASSIGNMENT_MARKER
const char * RexxActivation::ASSIGNMENT_MARKER = " <= " static
Definition at line 609 of file RexxActivation.hpp.
Referenced by traceAssignment(), and traceCompoundAssignment().
blockNest
size_t RexxActivation::blockNest protected
Definition at line 651 of file RexxActivation.hpp.
Referenced by addBlockInstruction(), hasActiveBlockInstructions(), newBlockInstruction(), removeBlockInstruction(), and signalTo().
clauseBoundary
bool RexxActivation::clauseBoundary protected
Definition at line 634 of file RexxActivation.hpp.
Referenced by externalTraceOff(), externalTraceOn(), halt(), processClauseBoundary(), run(), and trap().
code
RexxCode* RexxActivation::code protected
Definition at line 622 of file RexxActivation.hpp.
Referenced by allocateLocalVariables(), allocateStackFrame(), debugInterpret(), displayProgramName(), doDebugPause(), getLabels(), getProgramName(), getPublicRoutines(), interpret(), live(), liveGeneral(), noTracing(), resolveProgramName(), RexxActivation(), run(), sourceString(), and traceClause().
conditionQueue
QueueClass* RexxActivation::conditionQueue protected
Definition at line 648 of file RexxActivation.hpp.
Referenced by live(), liveGeneral(), mergeTraps(), processClauseBoundary(), processTraps(), run(), trap(), and unwindTrap().
contextObject
RexxContext* RexxActivation::contextObject protected
Definition at line 639 of file RexxActivation.hpp.
Referenced by getContextObject(), live(), liveGeneral(), and termination().
current
RexxInstruction* RexxActivation::current protected
Definition at line 631 of file RexxActivation.hpp.
Referenced by command(), currentLine(), debugInterpret(), doDebugPause(), getContextLine(), getContextLineNumber(), getCurrent(), getTraceBack(), internalCall(), internalCallTrap(), interpret(), live(), liveGeneral(), loadLibrary(), loadRequires(), rexxVariable(), run(), setCurrent(), signalTo(), and traceEntry().
debugPause
bool RexxActivation::debugPause protected
Definition at line 633 of file RexxActivation.hpp.
Referenced by command(), debugInterpret(), debugSkip(), doDebugPause(), inDebug(), noTracing(), RexxActivation(), run(), setTrace(), trap(), and willTrap().
DefaultRandomMax
const size_t RexxActivation::DefaultRandomMax = 999 static
Definition at line 603 of file RexxActivation.hpp.
Referenced by random().
DefaultRandomMin
const size_t RexxActivation::DefaultRandomMin = 0 static
Definition at line 602 of file RexxActivation.hpp.
Referenced by random().
doStack
DoBlock* RexxActivation::doStack protected
Definition at line 630 of file RexxActivation.hpp.
Referenced by live(), liveGeneral(), popBlockInstruction(), pushBlockInstruction(), signalTo(), and topBlockInstruction().
environmentList
QueueClass* RexxActivation::environmentList protected
Definition at line 646 of file RexxActivation.hpp.
Referenced by live(), liveGeneral(), popEnvironment(), pushEnvironment(), and termination().
executionState
ExecutionState RexxActivation::executionState protected
Definition at line 641 of file RexxActivation.hpp.
Referenced by implicitExit(), RexxActivation(), run(), and stopExecution().
idntfr
uint32_t RexxActivation::idntfr protected
Definition at line 653 of file RexxActivation.hpp.
Referenced by getIdntfr().
instructionCount
size_t RexxActivation::instructionCount protected
Definition at line 652 of file RexxActivation.hpp.
Referenced by run(), and yield().
MaxRandomRange
const size_t RexxActivation::MaxRandomRange = 999999999 static
Definition at line 604 of file RexxActivation.hpp.
Referenced by random().
next
RexxInstruction* RexxActivation::next protected
Definition at line 632 of file RexxActivation.hpp.
Referenced by doDebugPause(), getNext(), live(), liveGeneral(), run(), setNext(), signalTo(), and stopExecution().
notifyObject
MessageClass* RexxActivation::notifyObject protected
Definition at line 644 of file RexxActivation.hpp.
Referenced by live(), liveGeneral(), setObjNotify(), and trap().
packageObject
PackageClass* RexxActivation::packageObject protected
Definition at line 623 of file RexxActivation.hpp.
Referenced by getEffectivePackageObject(), getPackageObject(), inheritPackageSettings(), live(), liveGeneral(), and RexxActivation().
parent
RexxActivation* RexxActivation::parent protected
Definition at line 627 of file RexxActivation.hpp.
Referenced by callExternalRexx(), cleanupLocalVariables(), external(), getContextLine(), getContextLineNumber(), getMethod(), getRandomSeed(), getReceiver(), live(), liveGeneral(), popEnvironment(), procedureExpose(), pushEnvironment(), raiseExit(), resolveDotVariable(), returnFrom(), RexxActivation(), rexxVariable(), run(), setDigits(), setForm(), setFuzz(), signalTo(), sourceString(), traceEntry(), traceEntryOrExit(), trap(), and unwindTrap().
RANDOM_ADDER
const uint64_t RexxActivation::RANDOM_ADDER = 11LL static
Definition at line 595 of file RexxActivation.hpp.
Referenced by RANDOMIZE().
RANDOM_FACTOR
const uint64_t RexxActivation::RANDOM_FACTOR = 25214903917LL static
Definition at line 594 of file RexxActivation.hpp.
Referenced by RANDOMIZE().
randomSeed
uint64_t RexxActivation::randomSeed protected
Definition at line 649 of file RexxActivation.hpp.
Referenced by getRandomSeed(), and RexxActivation().
randomSet
bool RexxActivation::randomSet protected
Definition at line 650 of file RexxActivation.hpp.
receiver
RexxObject* RexxActivation::receiver protected
Definition at line 625 of file RexxActivation.hpp.
Referenced by createStackFrame(), debugInterpret(), dispatch(), forward(), getObjectVariables(), getReceiver(), getVariableDictionary(), guardOn(), internalCall(), live(), liveGeneral(), and run().
result
RexxObject* RexxActivation::result protected
Definition at line 637 of file RexxActivation.hpp.
Referenced by closeStreams(), createTraceObject(), exitFrom(), forward(), getStackFrameAsStringTable(), live(), liveGeneral(), novalueHandler(), raise(), reply(), resolveStream(), returnFrom(), and run().
scope
RexxClass* RexxActivation::scope protected
Definition at line 624 of file RexxActivation.hpp.
Referenced by getObjectVariables(), getVariableDictionary(), guardOn(), live(), liveGeneral(), RexxActivation(), and run().
settings
ActivationSettings RexxActivation::settings protected
Definition at line 620 of file RexxActivation.hpp.
Referenced by addIOConfig(), aliasLocalVariable(), allocateLocalVariables(), autoExpose(), callExternalRexx(), checkIOConfigTable(), checkTrapTable(), cleanupLocalVariables(), clearTraceSettings(), closeStreams(), debugInterpret(), debugSkip(), digits(), disableErrorSyntax(), disableFailureSyntax(), disableLostdigitsSyntax(), disableNostringSyntax(), disableNotreadySyntax(), disableNovalueSyntax(), dispatch(), doDebugPause(), exitFrom(), externalCall(), externalTraceOff(), externalTraceOn(), form(), formatTrace(), forward(), fuzz(), getAddress(), getCallname(), getConditionObj(), getContextReturnStatus(), getEffectiveSecurityManager(), getElapsed(), getFileNames(), getIndent(), getIOConfig(), getLocalStemVariable(), getLocalVariable(), getLocalVariables(), getMessageName(), getNumericSettings(), getObjectVariables(), getProgramArgument(), getProgramArgumentCount(), getProgramArgumentlist(), getSecurityManager(), getSettings(), getStreams(), getTime(), guardOff(), guardOn(), guardWait(), halt(), inDebug(), indent(), inheritPackageSettings(), internalCall(), internalCallTrap(), isElapsedTimerReset(), isErrorSyntaxEnabled(), isFailureSyntaxEnabled(), isForwarded(), isGuarded(), isLostdigitsSyntaxEnabled(), isNostringSyntaxEnabled(), isNotreadySyntaxEnabled(), isNovalueSyntaxEnabled(), live(), liveGeneral(), localStemVariableExists(), localVariableExists(), newBlockInstruction(), notCaseSensitive(), noTracing(), novalueEnabled(), pauseCommand(), pauseLabel(), pausingInstructions(), popBlockInstruction(), procedureExpose(), processClauseBoundary(), putLocalVariable(), putSettings(), removeFileName(), reply(), resetDebug(), returnFrom(), RexxActivation(), rexxVariable(), run(), setAddress(), setCallType(), setConditionObj(), setDefaultAddress(), setDigits(), setElapsedTimerInvalid(), setElapsedTimerValid(), setForm(), setFuzz(), setGuarded(), setIndent(), setLocalVariableDictionary(), setReturnStatus(), setTrace(), signalTo(), sourceString(), terminateBlockInstruction(), termination(), toggleAddress(), traceArgument(), traceAssignment(), traceClassResolution(), traceClause(), traceCompound(), traceCompoundAssignment(), traceCompoundName(), traceCompoundValue(), traceDotVariable(), traceEntryOrExit(), traceFunction(), traceIntermediate(), traceLabel(), traceMessage(), traceOperator(), traceOperatorValue(), tracePrefix(), traceSetting(), traceSourceString(), traceSpecialDotVariable(), traceTaggedValue(), traceValue(), traceVariable(), tracingAll(), tracingCommands(), tracingErrors(), tracingFailures(), tracingIntermediates(), tracingLabels(), tracingResults(), trap(), trapDelay(), trapOff(), trapOn(), trapState(), trapUndelay(), unindent(), unindentTwice(), unwindTrap(), updateLocalVariable(), and willTrap().
SIZE_BITS
const size_t RexxActivation::SIZE_BITS = sizeof(void *) * 8 static
Definition at line 599 of file RexxActivation.hpp.
stack
ExpressionStack RexxActivation::stack protected
Definition at line 621 of file RexxActivation.hpp.
Referenced by allocateStackFrame(), getStack(), internalCallTrap(), iterate(), live(), liveGeneral(), resolveAddressIOConfig(), run(), and termination().
traceEntryAllowed
bool RexxActivation::traceEntryAllowed protected
Definition at line 635 of file RexxActivation.hpp.
Referenced by run(), and traceEntry().
traceEntryDone
bool RexxActivation::traceEntryDone protected
Definition at line 636 of file RexxActivation.hpp.
Referenced by run(), termination(), and traceEntry().
trapInfo
ArrayClass* RexxActivation::trapInfo protected
Definition at line 638 of file RexxActivation.hpp.
Referenced by live(), and liveGeneral().
VALUE_MARKER
const char * RexxActivation::VALUE_MARKER = " => " static
Definition at line 607 of file RexxActivation.hpp.
Referenced by traceClassResolution(), traceCompound(), traceCompoundName(), traceCompoundValue(), traceDotVariable(), traceFunction(), traceKeywordResult(), traceMessage(), traceOperatorValue(), traceSpecialDotVariable(), traceVariable(), and traceVariableAlias().
yieldInstructions
const size_t RexxActivation::yieldInstructions = 50 static
Definition at line 592 of file RexxActivation.hpp.
Referenced by run(), and yield().
The documentation for this class was generated from the following files:
RexxActivation.hpp
RexxActivation.cpp
RexxActivation-trace.cpp