ooRexx: ArrayClass::ElementCopier Class Reference
ArrayClass::ElementCopier Class Reference
#include <ArrayClass.hpp>
Public Member Functions
void copy ()
void copyElements (size_t newDimension, size_t oldOffset, size_t newOffset)
void copyBlocks (size_t dimension, size_t oldOffset, size_t newOffset)
void getBlockSizes (size_t dimension, size_t &oldBlock, size_t &newBlock)
Public Attributes
ArrayClass * newArray
ArrayClass * oldArray
size_t totalDimensions
Detailed Description
Array internal class for performing recursive copies for multi-dimensional arrays
Definition at line 71 of file ArrayClass.hpp.
Member Function Documentation
copy()
void ArrayClass::ElementCopier::copy ()
The start of the copying process.
Definition at line 2289 of file ArrayClass.cpp.
References copyElements(), and totalDimensions.
Referenced by ArrayClass::extendMulti().
copyBlocks()
void ArrayClass::ElementCopier::copyBlocks (size_t dimension, size_t oldOffset, size_t newOffset)
The the actual process of copying blocks from the old array to the new array. This only occurs when we've reached the second dimention level, which involves us copying a series of one-dimensional arrays (with potential size expansion).
Parameters
oldOffset The offset in the old array to copy from
newOffset The offset in the new array to copy to
Definition at line 2357 of file ArrayClass.cpp.
copyElements()
void ArrayClass::ElementCopier::copyElements (size_t newDimension, size_t oldOffset, size_t newOffset)
Recursive routine to copy element from one multiDim array to another. This works in reverse order, drilling down to the highest level, copying, and then unwinding to get the higher dimensions.
Parameters
parm The copy parameters, which are updated through each recursion level.
newDimension
Definition at line 2306 of file ArrayClass.cpp.
Referenced by copy().
getBlockSizes()
void ArrayClass::ElementCopier::getBlockSizes (size_t dimension, size_t & oldBlock, size_t & newBlock)
Calculate both the old and new block sizes from a starting dimension number.
Parameters
dimension The dimension number
oldBlock The returned size of the block for the old array
newBlock The returned size of the block for the new array.
Definition at line 2405 of file ArrayClass.cpp.
Member Data Documentation
newArray
ArrayClass* ArrayClass::ElementCopier::newArray
Definition at line 80 of file ArrayClass.hpp.
Referenced by ArrayClass::extendMulti().
oldArray
ArrayClass* ArrayClass::ElementCopier::oldArray
Definition at line 81 of file ArrayClass.hpp.
Referenced by ArrayClass::extendMulti().
totalDimensions
size_t ArrayClass::ElementCopier::totalDimensions
Definition at line 82 of file ArrayClass.hpp.
Referenced by copy(), and ArrayClass::extendMulti().
The documentation for this class was generated from the following files:
ArrayClass.hpp
ArrayClass.cpp