ooRexx: MessageClass Class Reference
MessageClass Class Reference
#include <MessageClass.hpp>
Public Types
enum MessageFlag {
flagResultReturned , flagRaiseError , flagErrorReported , flagAllNotified ,
flagStartPending , flagMsgActivated
}
Public Member Functions
void * operator new (size_t)
MessageClass (RexxObject *, RexxString *, RexxClass *, ArrayClass *)
MessageClass (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
RexxObject * notify (RexxObject *)
RexxObject * result ()
RexxObject * wait ()
RexxObject * send ()
RexxObject * dispatch ()
RexxObject * start ()
MessageClass * reply ()
RexxObject * startRexx (RexxObject **, size_t)
RexxObject * startWithRexx (RexxObject *, ArrayClass *)
RexxObject * replyRexx (RexxObject **, size_t)
RexxObject * replyWithRexx (RexxObject *, ArrayClass *)
RexxObject * sendRexx (RexxObject **, size_t)
RexxObject * sendWithRexx (RexxObject *, ArrayClass *)
RexxObject * completed ()
void sendNotification ()
void error (DirectoryClass *)
RexxObject * messageTarget ()
RexxString * messageName ()
ArrayClass * arguments ()
RexxObject * hasError ()
RexxObject * hasResult ()
RexxObject * errorCondition ()
RexxObject * newRexx (RexxObject **, size_t)
Activity * getActivity ()
RexxObject * messageCompleted (RexxObject *messageSource)
RexxObject * halt (RexxString *description)
bool isActivated ()
bool isComplete ()
bool resultReturned ()
bool raiseError ()
bool errorReported ()
bool allNotified ()
bool startPending ()
void setResultReturned ()
void setRaiseError ()
void setErrorReported ()
void setAllNotified ()
void clearStartPending ()
void setStartPending ()
void setMsgActivated ()
void clearCompletion ()
void checkReuse ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
HashCode hash () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
RexxObject * receiver
RexxObject * target
RexxString * message
RexxClass * startscope
ArrayClass * args
RexxObject * resultObject
ArrayClass * interestedParties
DirectoryClass * condition
Activity * startActivity
ArrayClass * waitingActivities
FlagSet< MessageFlag, 32 > dataFlags
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
A dispatchable message object.
Definition at line 52 of file MessageClass.hpp.
Member Enumeration Documentation
MessageFlag
enum MessageClass::MessageFlag
Internal flag values.
Enumerator
flagResultReturned
flagRaiseError
flagErrorReported
flagAllNotified
flagStartPending
flagMsgActivated
Definition at line 59 of file MessageClass.hpp.
Constructor & Destructor Documentation
MessageClass() [1/2]
MessageClass::MessageClass (RexxObject * _target, RexxString * msgName, RexxClass * scope, ArrayClass * _args)
Create a new message object.
Parameters
_target The receiver object.
messageName The invoked message name.
scope The starting scope (can be OREF_NULL).
_args An array of arguments to the message.
Definition at line 95 of file MessageClass.cpp.
References args, message, receiver, startscope, and target.
Referenced by newRexx().
MessageClass() [2/2]
MessageClass::MessageClass (RESTORETYPE restoreType) inline
Definition at line 72 of file MessageClass.hpp.
Member Function Documentation
allNotified()
bool MessageClass::allNotified () inline
Definition at line 111 of file MessageClass.hpp.
References dataFlags, and flagAllNotified.
Referenced by notify().
arguments()
ArrayClass * MessageClass::arguments ()
Return a copy of the message argument array.
Returns
A copy of the message arguments array.
Definition at line 799 of file MessageClass.cpp.
References args, and ArrayClass::copy().
Referenced by MemoryObject::createImage(), replyRexx(), replyWithRexx(), sendRexx(), sendWithRexx(), startRexx(), and startWithRexx().
checkReuse()
void MessageClass::checkReuse ()
Verify we're not reusing a message object incorrectly.
Definition at line 360 of file MessageClass.cpp.
References ActivityManager::currentActivity, Error_Execution_message_reuse, isActivated(), reportException(), startActivity, and startPending().
Referenced by reply(), send(), and start().
clearCompletion()
void MessageClass::clearCompletion ()
Clear all of the state related to message completion.
Definition at line 382 of file MessageClass.cpp.
References clearField, condition, dataFlags, flagAllNotified, flagErrorReported, flagRaiseError, flagResultReturned, and resultObject.
Referenced by copy(), reply(), send(), and start().
clearStartPending()
void MessageClass::clearStartPending () inline
Definition at line 117 of file MessageClass.hpp.
References dataFlags, flagMsgActivated, and flagStartPending.
Referenced by copy().
completed()
RexxObject * MessageClass::completed ()
Give the message completion status.
Returns
.true if this has completed, .false otherwise.
Definition at line 721 of file MessageClass.cpp.
References booleanObject(), raiseError(), and resultReturned().
Referenced by MemoryObject::createImage().
copy()
RexxInternalObject * MessageClass::copy () override virtual
Copy a message object.
Returns
A new copy of the object, with internal state set to a clean state.
Reimplemented from RexxObject.
Definition at line 182 of file MessageClass.cpp.
References clearCompletion(), clearStartPending(), ArrayClass::copy(), RexxObject::copy(), interestedParties, OREF_NULL, startActivity, and waitingActivities.
Referenced by reply().
createInstance()
void MessageClass::createInstance () static
Create initial class object at bootstrap time.
Definition at line 78 of file MessageClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
dispatch()
RexxObject * MessageClass::dispatch ()
Dispatch the message object via a send()
Returns
The result object.
Definition at line 421 of file MessageClass.cpp.
References args, ActivityManager::currentActivity, ArrayClass::data(), Activity::getTopStackFrame(), message, RexxObject::messageSend(), OREF_NULL, receiver, result(), resultObject, sendNotification(), setField, ActivationBase::setObjNotify(), setResultReturned(), ArrayClass::size(), startActivity, and startscope.
Referenced by MessageDispatcher::run(), and send().
error()
void MessageClass::error (DirectoryClass * _condition)
Receive an error notificatiion from an activation.
Parameters
_condition The error condition object.
Definition at line 705 of file MessageClass.cpp.
References condition, sendNotification(), setField, and setRaiseError().
Referenced by MessageDispatcher::handleError(), and RexxActivation::trap().
errorCondition()
RexxObject * MessageClass::errorCondition ()
Return any error condition information associated with the message. This method will not block until completion, and will return .nil if the message is still running.
Returns
Any condition object from a terminating error, or .nil if there was no error or the message is still running.
Definition at line 763 of file MessageClass.cpp.
References condition, and resultOrNil().
Referenced by MemoryObject::createImage().
errorReported()
bool MessageClass::errorReported () inline
Definition at line 110 of file MessageClass.hpp.
References dataFlags, and flagErrorReported.
flatten()
void MessageClass::flatten (Envelope * envelope) override virtual
Flatten a source object.
Parameters
envelope The envelope that will hold the flattened object.
Reimplemented from RexxObject.
Definition at line 157 of file MessageClass.cpp.
References args, cleanUpFlatten, condition, flattenRef, interestedParties, message, receiver, resultObject, setUpFlatten, startActivity, startscope, target, and waitingActivities.
getActivity()
Activity* MessageClass::getActivity () inline
Definition at line 102 of file MessageClass.hpp.
References startActivity.
halt()
RexxObject * MessageClass::halt (RexxString * description)
Definition at line 805 of file MessageClass.cpp.
References booleanObject(), Activity::halt(), optionalStringArgument(), OREF_NULL, startActivity, and TheFalseObject.
Referenced by MemoryObject::createImage().
hasError()
RexxObject * MessageClass::hasError ()
Check to see if a message has an error condition. Return false if the message has not completed yet.
Returns
True if the message has terminated with an error condition, false if it is still running or has completed without error.
Definition at line 735 of file MessageClass.cpp.
References booleanObject(), and raiseError().
Referenced by MemoryObject::createImage().
hasResult()
RexxObject * MessageClass::hasResult ()
Check to see if a message has a result available. Returns false if the message has not completed yet.
Returns
True if the message has completed with a returned result, false if it is still running or has completed without returning a result.
Definition at line 749 of file MessageClass.cpp.
References booleanObject(), OREF_NULL, and resultObject.
Referenced by MemoryObject::createImage().
isActivated()
bool MessageClass::isActivated () inline
Definition at line 106 of file MessageClass.hpp.
References dataFlags, and flagMsgActivated.
Referenced by checkReuse().
isComplete()
bool MessageClass::isComplete () inline
Definition at line 107 of file MessageClass.hpp.
References raiseError(), and resultReturned().
Referenced by wait().
live()
void MessageClass::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxObject.
Definition at line 113 of file MessageClass.cpp.
References args, condition, interestedParties, memory_mark, message, receiver, resultObject, startActivity, startscope, target, and waitingActivities.
liveGeneral()
void MessageClass::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxObject.
Definition at line 136 of file MessageClass.cpp.
References args, condition, interestedParties, memory_mark_general, message, receiver, resultObject, startActivity, startscope, target, and waitingActivities.
messageCompleted()
RexxObject * MessageClass::messageCompleted (RexxObject * messageSource)
Field a message completion message notification. This triggers the message object to fire.
Parameters
messageSource The source of the notification message (ignored for message objects).
Returns
always returns OREF_NULL
Definition at line 692 of file MessageClass.cpp.
References OREF_NULL, and send().
Referenced by MemoryObject::createImage().
messageName()
RexxString * MessageClass::messageName ()
Return the name of the message.
Returns
The string name of the message.
Definition at line 788 of file MessageClass.cpp.
References message.
Referenced by MemoryObject::createImage().
messageTarget()
RexxObject * MessageClass::messageTarget ()
Retrieve the target of the message object. This will be either the target object specified when the message object is created or a target override object specified on SEND or START.
Returns
The current message target.
Definition at line 776 of file MessageClass.cpp.
References receiver.
Referenced by MemoryObject::createImage().
newRexx()
RexxObject * MessageClass::newRexx (RexxObject ** msgArgs, size_t argCount)
Create a message object from Rexx code.
Parameters
msgArgs The pointer to the new arguments.
argCount The argument count.
Returns
A new instance of the .Message class.
Definition at line 827 of file MessageClass.cpp.
References arrayArgument(), RexxClass::completeNewObject(), RexxObject::decodeMessageName(), Error_Incorrect_method_maxarg, Error_Incorrect_method_minarg, IntegerFour, IntegerTwo, MessageClass(), new_array(), optionArgument(), OREF_NULL, reportException(), and requiredArgument().
Referenced by MemoryObject::createImage().
notify()
RexxObject * MessageClass::notify (RexxObject * notificationTarget)
Add a message object to the completion notification list.
Parameters
_message The message object wishing to be notified.
Returns
Instruction message type that returns nothing.
Definition at line 209 of file MessageClass.cpp.
References allNotified(), ArrayClass::append(), classArgument(), interestedParties, new_array(), OREF_NULL, result(), RexxObject::sendMessage(), and TheRexxPackage.
Referenced by MemoryObject::createImage().
operator new()
void * MessageClass::operator new (size_t size)
Create an instance of a message object.
Parameters
size The base size of the object.
Returns
The storage for the object in question.
Definition at line 69 of file MessageClass.cpp.
References new_object(), and T_Message.
raiseError()
bool MessageClass::raiseError () inline
Definition at line 109 of file MessageClass.hpp.
References dataFlags, and flagRaiseError.
Referenced by completed(), hasError(), isComplete(), and result().
reply()
MessageClass * MessageClass::reply ()
Execute this message asynchronously by spawning a new thread and dispatching this message on the new thread.
Parameters
_receiver The optional receiver object.
Returns
returns nothing as a instruction message send.
Definition at line 622 of file MessageClass.cpp.
References checkReuse(), clearCompletion(), copy(), receiver, startscope, and RexxObject::validateScopeOverride().
Referenced by replyRexx(), and replyWithRexx().
replyRexx()
RexxObject * MessageClass::replyRexx (RexxObject ** arguments, size_t argCount)
Do a dynamic invocation of an object method.
Parameters
arguments The variable arguments passed to the method. The first argument is a required message target, which can be either a string method name or an array containing a name/scope pair. The remainder of the arguments are the message arguments.
argCount
Returns
The method result.
Definition at line 565 of file MessageClass.cpp.
References args, arguments(), new_array(), OREF_NULL, receiver, reply(), and setField.
Referenced by MemoryObject::createImage().
replyWithRexx()
RexxObject * MessageClass::replyWithRexx (RexxObject * newReceiver, ArrayClass * arguments)
Do a dynamic invocation of an object method.
Parameters
receiver An optional receiver target
arguments An array of arguments to used with the message invocation.
Returns
The method result.
Definition at line 597 of file MessageClass.cpp.
References args, arguments(), arrayArgument(), OREF_NULL, receiver, reply(), and setField.
Referenced by MemoryObject::createImage().
result()
RexxObject * MessageClass::result ()
Return the message result object. This will wait if the message has not completed.
Returns
The result object (if any)
Definition at line 279 of file MessageClass.cpp.
References condition, ActivityManager::currentActivity, raiseError(), Activity::reraiseException(), resultObject, resultOrNil(), and wait().
Referenced by MemoryObject::createImage(), dispatch(), notify(), and sendNotification().
resultReturned()
bool MessageClass::resultReturned () inline
Definition at line 108 of file MessageClass.hpp.
References dataFlags, and flagResultReturned.
Referenced by completed(), and isComplete().
send()
RexxObject * MessageClass::send ()
Send a message to the target receiver object (optional).
Parameters
_receiver The optional receiver object.
Returns
Returns the message result.
Definition at line 401 of file MessageClass.cpp.
References checkReuse(), clearCompletion(), dispatch(), receiver, startscope, and RexxObject::validateScopeOverride().
Referenced by messageCompleted(), sendRexx(), and sendWithRexx().
sendNotification()
void MessageClass::sendNotification ()
Notify all interested parties after this message completed.
Definition at line 645 of file MessageClass.cpp.
References ActivityManager::currentActivity, ArrayClass::get(), Activity::getTopStackFrame(), Activity::guardPost(), interestedParties, ArrayClass::items(), ArrayClass::lastIndex(), OREF_NULL, result(), RexxObject::sendMessage(), setAllNotified(), ActivationBase::setObjNotify(), and waitingActivities.
Referenced by dispatch(), and error().
sendRexx()
RexxObject * MessageClass::sendRexx (RexxObject ** arguments, size_t argCount)
Do a dynamic invocation of an object method.
Parameters
arguments The variable arguments passed to the method. The first argument is a required message target, which can be either a string method name or an array containing a name/scope pair. The remainder of the arguments are the message arguments.
argCount
Returns
The method result.
Definition at line 308 of file MessageClass.cpp.
References args, arguments(), new_array(), OREF_NULL, receiver, send(), and setField.
Referenced by MemoryObject::createImage().
sendWithRexx()
RexxObject * MessageClass::sendWithRexx (RexxObject * newReceiver, ArrayClass * arguments)
Do a dynamic invocation of an object method.
Parameters
receiver An optional receiver target
arguments An array of arguments to used with the message invocation.
Returns
The method result.
Definition at line 340 of file MessageClass.cpp.
References args, arguments(), arrayArgument(), OREF_NULL, receiver, send(), and setField.
Referenced by MemoryObject::createImage().
setAllNotified()
void MessageClass::setAllNotified () inline
Definition at line 116 of file MessageClass.hpp.
References dataFlags, and flagAllNotified.
Referenced by sendNotification().
setErrorReported()
void MessageClass::setErrorReported () inline
Definition at line 115 of file MessageClass.hpp.
References dataFlags, and flagErrorReported.
setMsgActivated()
void MessageClass::setMsgActivated () inline
Definition at line 119 of file MessageClass.hpp.
References dataFlags, and flagMsgActivated.
Referenced by setStartPending().
setRaiseError()
void MessageClass::setRaiseError () inline
Definition at line 114 of file MessageClass.hpp.
References dataFlags, and flagRaiseError.
Referenced by error().
setResultReturned()
void MessageClass::setResultReturned () inline
Definition at line 113 of file MessageClass.hpp.
References dataFlags, and flagResultReturned.
Referenced by dispatch().
setStartPending()
void MessageClass::setStartPending () inline
Definition at line 118 of file MessageClass.hpp.
References dataFlags, flagStartPending, and setMsgActivated().
Referenced by start().
start()
RexxObject * MessageClass::start ()
Execute this message asynchronously by spawning a new thread and dispatching this message on the new thread.
Parameters
_receiver The optional receiver object.
Returns
returns nothing as a instruction message send.
Definition at line 522 of file MessageClass.cpp.
References checkReuse(), clearCompletion(), ActivityManager::currentActivity, OREF_NULL, receiver, Activity::run(), Activity::setCallerStackFrameAsStringTable(), setField, setStartPending(), Activity::spawnReply(), startActivity, startscope, and RexxObject::validateScopeOverride().
Referenced by startRexx(), and startWithRexx().
startPending()
bool MessageClass::startPending () inline
Definition at line 112 of file MessageClass.hpp.
References dataFlags, and flagStartPending.
Referenced by checkReuse().
startRexx()
RexxObject * MessageClass::startRexx (RexxObject ** arguments, size_t argCount)
Do a dynamic invocation of an object method.
Parameters
arguments The variable arguments passed to the method. The first argument is a required message target, which can be either a string method name or an array containing a name/scope pair. The remainder of the arguments are the message arguments.
argCount
Returns
The method result.
Definition at line 465 of file MessageClass.cpp.
References args, arguments(), new_array(), OREF_NULL, receiver, setField, and start().
Referenced by MemoryObject::createImage().
startWithRexx()
RexxObject * MessageClass::startWithRexx (RexxObject * newReceiver, ArrayClass * arguments)
Do a dynamic invocation of an object method.
Parameters
receiver An optional receiver target
arguments An array of arguments to used with the message invocation.
Returns
The method result.
Definition at line 497 of file MessageClass.cpp.
References args, arguments(), arrayArgument(), OREF_NULL, receiver, setField, and start().
Referenced by MemoryObject::createImage().
wait()
RexxObject * MessageClass::wait ()
Wait until message completion, either because the message has completed execution or because it terminated with an error.
Returns
Always return nothing.
Definition at line 240 of file MessageClass.cpp.
References ArrayClass::append(), Activity::checkDeadLock(), ActivityManager::currentActivity, isComplete(), new_array(), OREF_NULL, setField, startActivity, waitingActivities, and Activity::waitReserve().
Referenced by MemoryObject::createImage(), and result().
Member Data Documentation
args
ArrayClass* MessageClass::args protected
Definition at line 132 of file MessageClass.hpp.
Referenced by arguments(), dispatch(), flatten(), live(), liveGeneral(), MessageClass(), replyRexx(), replyWithRexx(), sendRexx(), sendWithRexx(), startRexx(), and startWithRexx().
classInstance
RexxClass * MessageClass::classInstance = OREF_NULL static
Definition at line 124 of file MessageClass.hpp.
condition
DirectoryClass* MessageClass::condition protected
Definition at line 135 of file MessageClass.hpp.
Referenced by clearCompletion(), error(), errorCondition(), flatten(), live(), liveGeneral(), and result().
dataFlags
FlagSet<MessageFlag, 32> MessageClass::dataFlags protected
Definition at line 138 of file MessageClass.hpp.
Referenced by allNotified(), clearCompletion(), clearStartPending(), errorReported(), isActivated(), raiseError(), resultReturned(), setAllNotified(), setErrorReported(), setMsgActivated(), setRaiseError(), setResultReturned(), setStartPending(), and startPending().
interestedParties
ArrayClass* MessageClass::interestedParties protected
Definition at line 134 of file MessageClass.hpp.
Referenced by copy(), flatten(), live(), liveGeneral(), notify(), and sendNotification().
message
RexxString* MessageClass::message protected
Definition at line 130 of file MessageClass.hpp.
Referenced by dispatch(), flatten(), live(), liveGeneral(), MessageClass(), and messageName().
receiver
RexxObject* MessageClass::receiver protected
Definition at line 128 of file MessageClass.hpp.
Referenced by dispatch(), flatten(), live(), liveGeneral(), MessageClass(), messageTarget(), reply(), replyRexx(), replyWithRexx(), send(), sendRexx(), sendWithRexx(), start(), startRexx(), and startWithRexx().
resultObject
RexxObject* MessageClass::resultObject protected
Definition at line 133 of file MessageClass.hpp.
Referenced by clearCompletion(), dispatch(), flatten(), hasResult(), live(), liveGeneral(), and result().
startActivity
Activity* MessageClass::startActivity protected
Definition at line 136 of file MessageClass.hpp.
Referenced by checkReuse(), copy(), dispatch(), flatten(), getActivity(), halt(), live(), liveGeneral(), start(), and wait().
startscope
RexxClass* MessageClass::startscope protected
Definition at line 131 of file MessageClass.hpp.
Referenced by dispatch(), flatten(), live(), liveGeneral(), MessageClass(), reply(), send(), and start().
target
RexxObject* MessageClass::target protected
Definition at line 129 of file MessageClass.hpp.
Referenced by flatten(), live(), liveGeneral(), and MessageClass().
waitingActivities
ArrayClass* MessageClass::waitingActivities protected
Definition at line 137 of file MessageClass.hpp.
Referenced by copy(), flatten(), live(), liveGeneral(), sendNotification(), and wait().
The documentation for this class was generated from the following files:
MessageClass.hpp
MessageClass.cpp