ooRexx: RoutineFileNameBuffer Class Reference
RoutineFileNameBuffer Class Reference
#include <ExternalFileBuffer.hpp>
Public Member Functions
RoutineFileNameBuffer (RexxCallContext *c, size_t initial=0)
void handleMemoryError () override
RoutineFileNameBuffer & operator= (const char *s)
RoutineFileNameBuffer & operator= (char *s)
RoutineFileNameBuffer & operator= (FileNameBuffer &s)
bool operator== (const char *s)
Public Member Functions inherited from FileNameBuffer
FileNameBuffer (size_t initial=0)
FileNameBuffer (const FileNameBuffer &o)
~FileNameBuffer ()
void init (size_t initial)
size_t capacity ()
size_t length ()
operator char * ()
operator const char * ()
void ensureCapacity (size_t size)
void ensureAdditionalCapacity (const char *add)
void expandCapacity (size_t c)
void shiftLeft (size_t l)
void truncate (size_t l)
void empty ()
FileNameBuffer & operator= (const char *s)
FileNameBuffer & operator= (const FileNameBuffer &s)
FileNameBuffer & operator= (char *s)
FileNameBuffer & operator+= (const char *s)
FileNameBuffer & operator+= (char *s)
FileNameBuffer & operator+= (char c)
FileNameBuffer & operator+= (FileNameBuffer &s)
FileNameBuffer & set (const char *s, size_t l)
FileNameBuffer & append (const char *s, size_t l)
bool operator== (const char *s)
bool operator!= (const char *s)
char & at (size_t pos)
bool startsWith (char c)
bool startsWith (const char *s)
bool endsWith (char c)
bool endsWith (const char *s)
bool isEmpty ()
void appendPathSeparator ()
void addFinalPathDelimiter ()
size_t locatePathDelimiter (size_t start=0)
Protected Attributes
RexxCallContext * context
Protected Attributes inherited from FileNameBuffer
char * buffer
size_t bufferSize
Detailed Description
A class for performing safer file name resolution that is expandable if needed. Replaces the use of fixed-sized buffers for file operations.
Definition at line 49 of file ExternalFileBuffer.hpp.
Constructor & Destructor Documentation
RoutineFileNameBuffer()
RoutineFileNameBuffer::RoutineFileNameBuffer (RexxCallContext * c, size_t initial = 0) inline
Definition at line 52 of file ExternalFileBuffer.hpp.
Member Function Documentation
handleMemoryError()
void RoutineFileNameBuffer::handleMemoryError () inline override virtual
Handle a memory error. Base implementation is for just raising a normal exception. This can only be used within internal code when the kernel lock is held.
Reimplemented from FileNameBuffer.
Definition at line 54 of file ExternalFileBuffer.hpp.
References context, and Rexx_Error_System_resources.
operator=() [1/3]
RoutineFileNameBuffer& RoutineFileNameBuffer::operator= (char * s) inline
Definition at line 64 of file ExternalFileBuffer.hpp.
References FileNameBuffer::operator=().
operator=() [2/3]
RoutineFileNameBuffer& RoutineFileNameBuffer::operator= (const char * s) inline
Definition at line 58 of file ExternalFileBuffer.hpp.
References FileNameBuffer::operator=().
operator=() [3/3]
RoutineFileNameBuffer& RoutineFileNameBuffer::operator= (FileNameBuffer & s) inline
Definition at line 70 of file ExternalFileBuffer.hpp.
References FileNameBuffer::operator=().
operator==()
bool RoutineFileNameBuffer::operator== (const char * s) inline
Definition at line 76 of file ExternalFileBuffer.hpp.
References FileNameBuffer::buffer.
Member Data Documentation
context
RexxCallContext* RoutineFileNameBuffer::context protected
Definition at line 83 of file ExternalFileBuffer.hpp.
Referenced by handleMemoryError().
The documentation for this class was generated from the following file:
ExternalFileBuffer.hpp