ooRexx: ApiContext Class Reference
ApiContext Class Reference
#include <ContextApi.hpp>
Public Member Functions
ApiContext (RexxThreadContext *c)
ApiContext (RexxThreadContext *c, bool blocking)
ApiContext (RexxCallContext *c)
ApiContext (RexxCallContext *c, bool blocking)
ApiContext (RexxExitContext *c)
ApiContext (RexxIORedirectorContext *c)
ApiContext (RexxIORedirectorContext *c, bool blocking)
ApiContext (RexxMethodContext *c)
ApiContext (RexxMethodContext *c, bool blocking)
~ApiContext ()
RexxObjectPtr ret (RexxInternalObject *o)
Public Attributes
Activity * activity
NativeActivation * context
bool releaseLock
bool clearConditions
Detailed Description
A stack-based API context object used for API stubs.
Definition at line 56 of file ContextApi.hpp.
Constructor & Destructor Documentation
ApiContext() [1/9]
ApiContext::ApiContext (RexxThreadContext * c) inline
Initialize an API context from a thread context.
Parameters
c The source context.
Definition at line 64 of file ContextApi.hpp.
References activity, clearConditions, context, contextToActivity(), NativeActivation::enableConditionTraps(), Activity::enterCurrentThread(), Activity::getApiContext(), releaseLock, and Activity::validateThread().
ApiContext() [2/9]
ApiContext::ApiContext (RexxThreadContext * c, bool blocking) inline
Initialize an API context from a thread context. this is a nonblocking context. The extra argument allows the overloads to work. Note: a non-blocking context can can only be used to retrieve information from a an inmutable object. For example, getting the size of a string object is ok, but not getting the size of an array object, since the current holder of the lock could be simultaneously updating the array.
Parameters
c The source context.
Definition at line 92 of file ContextApi.hpp.
References activity, clearConditions, context, contextToActivity(), NativeActivation::enableConditionTraps(), Activity::getApiContext(), and releaseLock.
ApiContext() [3/9]
ApiContext::ApiContext (RexxCallContext * c) inline
Initialize an API context from a call context.
Parameters
c The source context.
Definition at line 108 of file ContextApi.hpp.
References activity, clearConditions, context, contextToActivation(), contextToActivity(), NativeActivation::enableConditionTraps(), Activity::enterCurrentThread(), releaseLock, and Activity::validateThread().
ApiContext() [4/9]
ApiContext::ApiContext (RexxCallContext * c, bool blocking) inline
Definition at line 135 of file ContextApi.hpp.
References activity, clearConditions, context, contextToActivity(), NativeActivation::enableConditionTraps(), Activity::getApiContext(), and releaseLock.
ApiContext() [5/9]
ApiContext::ApiContext (RexxExitContext * c) inline
Initialize an API context from an exit context.
Parameters
c The source context.
Definition at line 153 of file ContextApi.hpp.
References activity, clearConditions, context, contextToActivation(), contextToActivity(), NativeActivation::enableConditionTraps(), Activity::enterCurrentThread(), releaseLock, and Activity::validateThread().
ApiContext() [6/9]
ApiContext::ApiContext (RexxIORedirectorContext * c) inline
Initialize an API context from an exit context.
Parameters
c The source context.
Definition at line 174 of file ContextApi.hpp.
References activity, clearConditions, context, contextToActivation(), contextToActivity(), NativeActivation::enableConditionTraps(), Activity::enterCurrentThread(), releaseLock, and Activity::validateThread().
ApiContext() [7/9]
ApiContext::ApiContext (RexxIORedirectorContext * c, bool blocking) inline
Initialize an API context from an exit context.
Parameters
c The source context.
Definition at line 194 of file ContextApi.hpp.
References activity, context, contextToActivation(), contextToActivity(), NativeActivation::enableConditionTraps(), and releaseLock.
ApiContext() [8/9]
ApiContext::ApiContext (RexxMethodContext * c) inline
Initialize an API context from a method context.
Parameters
c The source context.
Definition at line 210 of file ContextApi.hpp.
References activity, clearConditions, context, contextToActivation(), contextToActivity(), NativeActivation::enableConditionTraps(), Activity::enterCurrentThread(), releaseLock, and Activity::validateThread().
ApiContext() [9/9]
ApiContext::ApiContext (RexxMethodContext * c, bool blocking) inline
Initialize an API context from a method context. this is a nonblocking context. The extra argument allows the overloads to work. Note: a non-blocking context can can only be used to retrieve information from a an inmutable object. For example, getting the size of a string object is ok, but not getting the size of an array object, since the current holder of the lock could be simultaneously updating the array.
Parameters
c The source context.
Definition at line 238 of file ContextApi.hpp.
References activity, clearConditions, context, contextToActivity(), NativeActivation::enableConditionTraps(), Activity::getApiContext(), and releaseLock.
~ApiContext()
ApiContext::~ApiContext () inline
Destructor for an API context. Releases the interpreter access lock on exit.
Definition at line 254 of file ContextApi.hpp.
References activity, NativeActivation::clearCondition(), clearConditions, context, NativeActivation::disableConditionTraps(), Activity::exitCurrentThread(), and releaseLock.
Member Function Documentation
ret()
RexxObjectPtr ApiContext::ret (RexxInternalObject * o) inline
Definition at line 271 of file ContextApi.hpp.
References context, and NativeActivation::createLocalReference().
Referenced by ArrayAt(), ArrayOfFour(), ArrayOfOne(), ArrayOfThree(), ArrayOfTwo(), CallProgram(), CallRoutine(), DirectoryAt(), DirectoryRemove(), DoubleToObject(), DoubleToObjectWithPrecision(), FindCallContextClass(), FindClass(), FindClassFromPackage(), FindContextClass(), ForwardMessage(), GetAllContextVariables(), GetAllExitContextVariables(), GetAllStemElements(), GetCallerContext(), GetConditionInfo(), GetExitCallerContext(), GetMethodPackage(), GetPackageClasses(), GetPackageMethods(), GetPackagePublicClasses(), GetPackagePublicRoutines(), GetPackageRoutines(), GetRoutinePackage(), GetStemArrayElement(), GetStemElement(), GetStemValue(), Int32ToObject(), Int64ToObject(), IntptrToObject(), LoadPackage(), LoadPackageFromData(), NewArray(), NewBuffer(), NewBufferString(), NewDirectory(), NewMethod(), NewMutableBuffer(), NewPointer(), NewRoutine(), NewStem(), NewString(), NewStringFromAsciiz(), NewStringTable(), NewSupplier(), ObjectToString(), ObjectToStringValue(), SendMessage0(), SendMessage1(), SendMessage2(), SendMessageArray(), SendMessageScoped(), SetGuardOffWhenUpdated(), SetGuardOnWhenUpdated(), StringLower(), StringSizeToObject(), StringTableAt(), StringTableRemove(), StringUpper(), SupplierIndex(), SupplierItem(), UintptrToObject(), UnsignedInt32ToObject(), UnsignedInt64ToObject(), ValuesToObject(), ValueToObject(), VariableReferenceName(), VariableReferenceValue(), and WholeNumberToObject().
Member Data Documentation
activity
Activity* ApiContext::activity
The activity used for the API callback.
Definition at line 280 of file ContextApi.hpp.
Referenced by ApiContext(), CallProgram(), CallRoutine(), CallThrowCondition(), DetachThread(), DisplayCondition(), ExitThrowCondition(), ForwardMessage(), GetLocalEnvironment(), HaltThread(), LoadPackage(), LoadPackageFromData(), RaiseCondition(), ReleaseGlobalReference(), RequestGlobalReference(), SetThreadTrace(), ThrowCondition(), and ~ApiContext().
clearConditions
bool ApiContext::clearConditions
Indicates whether conditions should be cleared on return.
Definition at line 294 of file ContextApi.hpp.
Referenced by ApiContext(), and ~ApiContext().
context
NativeActivation* ApiContext::context
The top-level API context.
Definition at line 284 of file ContextApi.hpp.
Referenced by AllocateObjectMemory(), ApiContext(), CallThrowCondition(), CheckCondition(), ClearCondition(), DisplayCondition(), DropContextVariable(), DropExitContextVariable(), DropObjectVariable(), ExitThrowCondition(), FindCallContextClass(), FindClass(), FindContextClass(), ForwardMessage(), FreeObjectMemory(), GetAllContextVariables(), GetAllExitContextVariables(), GetCallArgument(), GetCallArguments(), GetCallerContext(), GetConditionInfo(), GetContextDigits(), GetContextForm(), GetContextFuzz(), GetContextVariable(), GetContextVariableReference(), GetCSelf(), GetCurrentMethod(), GetCurrentRoutine(), GetExitCallerContext(), GetExitContextVariable(), GetExitContextVariableReference(), GetInterpreterInstance(), GetMessageName(), GetMethodArgument(), GetMethodArguments(), GetObjectVariable(), GetObjectVariableReference(), GetRoutineName(), GetScope(), GetSelf(), GetSuper(), InvalidRoutine(), IsOfType(), ObjectToValue(), RaiseCondition(), ReadInput(), ReadInputBuffer(), ReallocateObjectMemory(), ReleaseLocalReference(), ResolveStemVariable(), ret(), SetContextVariable(), SetExitContextVariable(), SetGuardOff(), SetGuardOffWhenUpdated(), SetGuardOn(), SetGuardOnWhenUpdated(), SetObjectVariable(), ThrowCondition(), ValuesToObject(), ValueToObject(), WriteError(), WriteErrorBuffer(), WriteOutput(), WriteOutputBuffer(), and ~ApiContext().
releaseLock
bool ApiContext::releaseLock
Indicates whether we need to release the lock on return.
Definition at line 289 of file ContextApi.hpp.
Referenced by ApiContext(), and ~ApiContext().
The documentation for this class was generated from the following file:
ContextApi.hpp