ooRexx: Numerics Class Reference
Numerics Class Reference
#include <Numerics.hpp>
Static Public Member Functions
static RexxObject * wholenumberToObject (wholenumber_t v)
static RexxObject * stringsizeToObject (size_t v)
static RexxObject * int64ToObject (int64_t v)
static RexxObject * uint64ToObject (uint64_t v)
static RexxObject * uintptrToObject (uintptr_t v)
static RexxObject * intptrToObject (intptr_t v)
static bool objectToWholeNumber (RexxObject *o, wholenumber_t &result, wholenumber_t max, wholenumber_t min)
static bool objectToStringSize (RexxObject *o, size_t &result, size_t max)
static bool objectToSignedInteger (RexxObject *o, ssize_t &result, ssize_t max, ssize_t min)
static bool objectToUnsignedInteger (RexxObject *o, size_t &result, size_t max)
static bool objectToInt64 (RexxObject *o, int64_t &result)
static bool objectToUnsignedInt64 (RexxObject *o, uint64_t &result)
static bool objectToUintptr (RexxObject *source, uintptr_t &result)
static bool objectToIntptr (RexxObject *source, intptr_t &result)
static RexxObject * int64Object (RexxObject *source)
static size_t formatWholeNumber (wholenumber_t integer, char *dest)
static size_t formatStringSize (size_t integer, char *dest)
static size_t formatInt64 (int64_t integer, char *dest)
static size_t formatUnsignedInt64 (uint64_t integer, char *dest)
static size_t normalizeWholeNumber (wholenumber_t integer, char *dest)
static wholenumber_t digits ()
static wholenumber_t fuzz ()
static bool form ()
static void setCurrentSettings (const NumericSettings *s)
static const NumericSettings * setDefaultSettings ()
static const NumericSettings * getDefaultSettings ()
static wholenumber_t maxValueForDigits (wholenumber_t d)
static wholenumber_t maxBitsForDigits (wholenumber_t d)
static RexxString * pointerToString (void *)
static bool isValid (wholenumber_t v)
static bool isValid32Bit (int64_t v)
static bool isValid (wholenumber_t v, wholenumber_t digits)
static bool isValid64Bit (int64_t v, wholenumber_t digits)
Static Public Attributes
static const wholenumber_t MAX_WHOLENUMBER = 999999999
static const wholenumber_t MIN_WHOLENUMBER = -999999999
static const wholenumber_t ARGUMENT_DIGITS = 9
static const wholenumber_t SIZE_DIGITS = 10
static const wholenumber_t REXXINTEGER_DIGITS = Numerics::ARGUMENT_DIGITS
static const wholenumber_t MIN_REXXINTEGER = MIN_WHOLENUMBER
static const wholenumber_t MAX_REXXINTEGER = MAX_WHOLENUMBER
static const wholenumber_t REXXINTEGER_BITS = 32
static const wholenumber_t MAX_EXPONENT = 999999999
static const wholenumber_t MIN_EXPONENT = -999999999
static const wholenumber_t DEFAULT_DIGITS = 9
static const size_t MAX_STRINGSIZE = MAX_WHOLENUMBER
static const wholenumber_t DIGITS64 = 20
static const bool FORM_SCIENTIFIC = false
static const bool FORM_ENGINEERING = true
static const wholenumber_t DEFAULT_FUZZ = 0
static const bool DEFAULT_FORM = FORM_SCIENTIFIC
static const wholenumber_t validMaxWhole []
static const wholenumber_t validMaxWholeBits []
Static Protected Attributes
static const NumericSettings * settings = &Numerics::defaultSettings
static const NumericSettings defaultSettings
Detailed Description
A class for holding all numeric-based settings and some numeric oriented static methods.
Definition at line 82 of file Numerics.hpp.
Member Function Documentation
digits()
static wholenumber_t Numerics::digits () inline static
Definition at line 154 of file Numerics.hpp.
References NumericSettings::getDigits(), and settings.
Referenced by isValid(), isValid64Bit(), and number_digits().
form()
static bool Numerics::form () inline static
Definition at line 156 of file Numerics.hpp.
References NumericSettings::getForm(), and settings.
Referenced by number_form().
formatInt64()
size_t Numerics::formatInt64 (int64_t integer, char * dest) static
Do portable formatting of an int64_t value into an ascii string.
Parameters
integer The value to convert.
dest The location to store the formatted string.
Returns
The length of the converted number.
Definition at line 733 of file Numerics.cpp.
Referenced by RexxDateTime::formatBaseTime(), RexxDateTime::formatTimeZone(), and RexxDateTime::formatUnixTime().
formatStringSize()
size_t Numerics::formatStringSize (size_t integer, char * dest) static
Do portable formatting of a stringsize value into an ascii string.
Parameters
integer The value to convert.
dest The location to store the formatted string.
Returns
The length of the converted number.
Definition at line 692 of file Numerics.cpp.
Referenced by NumberString::formatUnsignedNumber().
formatUnsignedInt64()
size_t Numerics::formatUnsignedInt64 (uint64_t integer, char * dest) static
Do portable formatting of a uint64_t value into an ascii string.
Parameters
integer The value to convert.
dest The location to store the formatted string.
Returns
The length of the converted number.
Definition at line 798 of file Numerics.cpp.
formatWholeNumber()
size_t Numerics::formatWholeNumber (wholenumber_t integer, char * dest) static
Do portable formatting of a wholenumber value into an ascii string.
Parameters
integer The value to convert.
dest The location to store the formatted string.
Returns
The length of the converted number.
Definition at line 565 of file Numerics.cpp.
Referenced by CompoundVariableTail::buildTail(), RexxInteger::copyIntoTail(), NumberString::formatExponent(), NumberString::formatInternal(), and RexxInteger::primitiveMakeString().
fuzz()
static wholenumber_t Numerics::fuzz () inline static
Definition at line 155 of file Numerics.hpp.
References NumericSettings::getFuzz(), and settings.
Referenced by number_fuzz().
getDefaultSettings()
static const NumericSettings* Numerics::getDefaultSettings () inline static
Definition at line 159 of file Numerics.hpp.
References defaultSettings.
Referenced by Activity::Activity(), ActivationBase::getNumericSettings(), and NativeActivation::getNumericSettings().
int64Object()
RexxObject * Numerics::int64Object (RexxObject * source) static
Validate that an object can be converted to an int64_t value
Parameters
source The source object.
Returns
Returns an object that has been validated as a valid int64_t value and can be passed to a native routine. Returns null if this object is not valid.
Definition at line 445 of file Numerics.cpp.
References DIGITS64, NumberString::int64Value(), isInteger(), RexxInternalObject::numberString(), and OREF_NULL.
Referenced by ExpressionStack::optionalBigIntegerArg(), and ExpressionStack::requiredBigIntegerArg().
int64ToObject()
RexxObject * Numerics::int64ToObject (int64_t v) static
Convert a signed int64 object into the appropriate Rexx object type.
Parameters
v The value to convert.
Returns
The Rexx object version of this number.
Definition at line 142 of file Numerics.cpp.
References MIN_WHOLENUMBER, new_integer(), and new_numberstringFromInt64().
Referenced by Int64ToObject(), NativeActivation::int64Value(), and NativeActivation::valueToObject().
intptrToObject()
RexxObject * Numerics::intptrToObject (intptr_t v) static
Convert an signed ptr value into the appropriate Rexx object type.
Parameters
v The value to convert.
Returns
The Rexx object version of this number.
Definition at line 860 of file Numerics.cpp.
References MAX_WHOLENUMBER, MIN_WHOLENUMBER, new_integer(), and new_numberstringFromWholenumber().
Referenced by IntptrToObject().
isValid() [1/2]
static bool Numerics::isValid (wholenumber_t v) inline static
Definition at line 186 of file Numerics.hpp.
References MIN_WHOLENUMBER.
Referenced by RexxInteger::abs(), RexxInteger::ceiling(), RexxInteger::comp(), RexxInteger::d2c(), RexxInteger::d2x(), RexxInteger::divide(), RexxInteger::floor(), RexxInteger::integerDivide(), RexxInteger::Max(), RexxInteger::Min(), RexxInteger::minus(), RexxInteger::modulo(), RexxInteger::multiply(), RexxInteger::numberValue(), RexxInteger::plus(), RexxInteger::power(), RexxInteger::remainder(), RexxInteger::round(), RexxInteger::trunc(), and RexxInteger::unsignedNumberValue().
isValid() [2/2]
static bool Numerics::isValid (wholenumber_t v, wholenumber_t digits) inline static
Definition at line 191 of file Numerics.hpp.
References digits(), REXXINTEGER_DIGITS, and validMaxWhole.
isValid32Bit()
static bool Numerics::isValid32Bit (int64_t v) inline static
Definition at line 190 of file Numerics.hpp.
References INT32_MIN.
isValid64Bit()
static bool Numerics::isValid64Bit (int64_t v, wholenumber_t digits) inline static
Definition at line 192 of file Numerics.hpp.
References digits(), REXXINTEGER_DIGITS, and validMaxWhole.
maxBitsForDigits()
static wholenumber_t Numerics::maxBitsForDigits (wholenumber_t d) inline static
Definition at line 172 of file Numerics.hpp.
References REXXINTEGER_DIGITS, and validMaxWholeBits.
Referenced by RexxInteger::multiply(), and RexxInteger::power().
maxValueForDigits()
static wholenumber_t Numerics::maxValueForDigits (wholenumber_t d) inline static
Definition at line 160 of file Numerics.hpp.
References REXXINTEGER_DIGITS, and validMaxWhole.
Referenced by NumberString::numberValue(), RexxInteger::power(), and NumberString::unsignedNumberValue().
normalizeWholeNumber()
size_t Numerics::normalizeWholeNumber (wholenumber_t integer, char * dest) static
Do portable formatting of a wholenumber value into numberstring format.
Parameters
integer The value to convert.
dest The location to store the formatted string.
Returns
The length of the converted number.
Definition at line 630 of file Numerics.cpp.
Referenced by NumberString::formatNumber().
objectToInt64()
bool Numerics::objectToInt64 (RexxObject * source, int64_t & result) static
Convert an object into a signed int64 value.
Parameters
source The source object.
result The returned converted value.
Returns
true if the number converted properly, false for any conversion errors.
Definition at line 412 of file Numerics.cpp.
References DIGITS64, NumberString::int64Value(), isInteger(), RexxInternalObject::numberString(), and OREF_NULL.
Referenced by BUILTIN(), NativeActivation::int64Value(), ObjectToInt64(), and NativeActivation::objectToValue().
objectToIntptr()
bool Numerics::objectToIntptr (RexxObject * source, intptr_t & result) static
Convert an object into an intptr_t values. Used for values that are numbers masking as pointers.
Parameters
source The source object.
result The returned value.
Returns
true if this converted, false for any conversion failures.
Definition at line 542 of file Numerics.cpp.
References INTPTR_MAX, INTPTR_MIN, and objectToSignedInteger().
Referenced by ObjectToIntptr(), and NativeActivation::objectToValue().
objectToSignedInteger()
bool Numerics::objectToSignedInteger (RexxObject * source, ssize_t & result, ssize_t maxValue, ssize_t minValue) static
Convert an object into a signed integer value.
Parameters
source The source object.
result The returned converted value.
maxValue The maximum range value for the target.
minValue The minimum range value for this number.
Returns
true if the number converted properly, false for any conversion errors.
Definition at line 272 of file Numerics.cpp.
References NumberString::int64Value(), isInteger(), RexxInternalObject::numberString(), OREF_NULL, and SIZE_DIGITS.
Referenced by NativeActivation::nonnegativeWholeNumberValue(), ObjectToInt32(), objectToIntptr(), NativeActivation::objectToValue(), NativeActivation::positiveWholeNumberValue(), and NativeActivation::signedIntegerValue().
objectToStringSize()
bool Numerics::objectToStringSize (RexxObject * source, size_t & result, size_t maxValue) static
Convert an object into an unsigned number value.
Parameters
source The source object.
result The returned converted value.
maxValue The maximum range value for the target.
Returns
true if the number converted properly, false for any conversion errors.
Definition at line 315 of file Numerics.cpp.
References ARGUMENT_DIGITS, isInteger(), RexxInternalObject::numberString(), OREF_NULL, and NumberString::unsignedInt64Value().
Referenced by ObjectToStringSize(), and NativeActivation::objectToValue().
objectToUintptr()
bool Numerics::objectToUintptr (RexxObject * source, uintptr_t & result) static
Convert an object into an uintptr_t values. Used for values that are numbers masking as pointers.
Parameters
source The source object.
result The returned value.
Returns
true if this converted, false for any conversion failures.
Definition at line 519 of file Numerics.cpp.
References objectToUnsignedInteger(), and UINTPTR_MAX.
Referenced by ObjectToUintptr(), and NativeActivation::objectToValue().
objectToUnsignedInt64()
bool Numerics::objectToUnsignedInt64 (RexxObject * source, uint64_t & result) static
Convert an object into an unsigned int64 value.
Parameters
source The source object.
result The returned converted value.
Returns
true if the number converted properly, false for any conversion errors.
Definition at line 481 of file Numerics.cpp.
References DIGITS64, isInteger(), RexxInternalObject::numberString(), OREF_NULL, and NumberString::unsignedInt64Value().
Referenced by ObjectToUnsignedInt64(), NativeActivation::objectToValue(), and NativeActivation::unsignedInt64Value().
objectToUnsignedInteger()
bool Numerics::objectToUnsignedInteger (RexxObject * source, size_t & result, size_t maxValue) static
Convert an object into an unsigned number value.
Parameters
source The source object.
result The returned converted value.
maxValue The maximum range value for the target.
Returns
true if the number converted properly, false for any conversion errors.
Definition at line 364 of file Numerics.cpp.
References isInteger(), RexxInternalObject::numberString(), OREF_NULL, SIZE_DIGITS, and NumberString::unsignedInt64Value().
Referenced by objectToUintptr(), ObjectToUnsignedInt32(), NativeActivation::objectToValue(), and NativeActivation::unsignedIntegerValue().
objectToWholeNumber()
bool Numerics::objectToWholeNumber (RexxObject * source, wholenumber_t & result, wholenumber_t maxValue, wholenumber_t minValue) static
Convert an object into a whole number value.
Parameters
source The source object.
result The returned converted value.
maxValue The maximum range value for the target.
minValue The minimum range value for this number.
Returns
true if the number converted properly, false for any conversion errors.
Definition at line 229 of file Numerics.cpp.
References ARGUMENT_DIGITS, NumberString::int64Value(), isInteger(), RexxInternalObject::numberString(), and OREF_NULL.
Referenced by NativeActivation::objectToValue(), and ObjectToWholeNumber().
pointerToString()
RexxString * Numerics::pointerToString (void * p) static
Format a pointer into a string value using a consistent formatting style.
Parameters
p The pointer valut to format.
Returns
The pointer as a string value in the format 0xnnnnnnnn.
Definition at line 882 of file Numerics.cpp.
References new_string().
Referenced by PointerClass::stringValue(), and NativeActivation::valueToObject().
setCurrentSettings()
static void Numerics::setCurrentSettings (const NumericSettings * s) inline static
Definition at line 157 of file Numerics.hpp.
References settings.
Referenced by Activity::setupCurrentActivity(), and Activity::updateFrameMarkers().
setDefaultSettings()
static const NumericSettings* Numerics::setDefaultSettings () inline static
Definition at line 158 of file Numerics.hpp.
References defaultSettings, and settings.
Referenced by Activity::releaseAccess().
stringsizeToObject()
RexxObject * Numerics::stringsizeToObject (size_t v) static
Convert an unsigned number value into the appropriate Rexx object type.
Parameters
v The value to convert.
Returns
The Rexx object version of this number.
Definition at line 205 of file Numerics.cpp.
References MAX_WHOLENUMBER, new_integer(), and new_numberstringFromStringsize().
Referenced by StringSizeToObject(), UnsignedInt32ToObject(), NativeActivation::unsignedIntegerValue(), and NativeActivation::valueToObject().
uint64ToObject()
RexxObject * Numerics::uint64ToObject (uint64_t v) static
Convert a signed int64 object into the appropriate Rexx object type.
Parameters
v The value to convert.
Returns
The Rexx object version of this number.
Definition at line 163 of file Numerics.cpp.
References MAX_WHOLENUMBER, new_integer(), and new_numberstringFromUint64().
Referenced by DoBlock::setCounter(), UnsignedInt64ToObject(), NativeActivation::unsignedInt64Value(), and NativeActivation::valueToObject().
uintptrToObject()
RexxObject * Numerics::uintptrToObject (uintptr_t v) static
Convert an unsigned ptr value into the appropriate Rexx object type.
Parameters
v The value to convert.
Returns
The Rexx object version of this number.
Definition at line 838 of file Numerics.cpp.
References MAX_WHOLENUMBER, new_integer(), and new_numberstringFromStringsize().
Referenced by UintptrToObject().
wholenumberToObject()
RexxObject * Numerics::wholenumberToObject (wholenumber_t v) static
Convert an signed number value into the appropriate Rexx object type.
Parameters
v The value to convert.
Returns
The Rexx object version of this number.
Definition at line 184 of file Numerics.cpp.
References MIN_WHOLENUMBER, new_integer(), and new_numberstringFromWholenumber().
Referenced by Int32ToObject(), NativeActivation::signedIntegerValue(), NativeActivation::valueToObject(), and WholeNumberToObject().
Member Data Documentation
ARGUMENT_DIGITS
const wholenumber_t Numerics::ARGUMENT_DIGITS = 9 static
Definition at line 98 of file Numerics.hpp.
Referenced by NumberString::createUnsignedValue(), StringUtil::dataType(), RexxInfo::getInternalDigits(), StemInputSource::init(), StemOutputTarget::init(), lengthArgument(), NumberString::newInstanceFromStringsize(), NumberString::newInstanceFromWholenumber(), nonNegativeArgument(), numberArgument(), objectToStringSize(), objectToWholeNumber(), ExpressionStack::optionalIntegerArg(), LanguageParser::optionsDirective(), positionArgument(), ExpressionStack::requiredIntegerArg(), and ListClass::validateIndex().
DEFAULT_DIGITS
const wholenumber_t Numerics::DEFAULT_DIGITS = 9 static
Definition at line 115 of file Numerics.hpp.
Referenced by NumberStringBase::checkOverflow(), ArrayClass::WithSortComparator::compare(), ActivationBase::digits(), NativeActivation::digits(), RexxInfo::getDigits(), NumberString::numberValue(), NumericSettings::setDefault(), ForLoop::setup(), StemClass::sort(), NumberString::stringValue(), and NumberString::unsignedNumberValue().
DEFAULT_FORM
const bool Numerics::DEFAULT_FORM = FORM_SCIENTIFIC static
Definition at line 125 of file Numerics.hpp.
Referenced by ActivationBase::form(), NativeActivation::form(), and NumericSettings::setDefault().
DEFAULT_FUZZ
const wholenumber_t Numerics::DEFAULT_FUZZ = 0 static
Definition at line 124 of file Numerics.hpp.
Referenced by ActivationBase::fuzz(), NativeActivation::fuzz(), RexxInfo::getFuzz(), and NumericSettings::setDefault().
defaultSettings
const NumericSettings Numerics::defaultSettings static protected
Definition at line 198 of file Numerics.hpp.
Referenced by getDefaultSettings(), and setDefaultSettings().
DIGITS64
const wholenumber_t Numerics::DIGITS64 = 20 static
Definition at line 120 of file Numerics.hpp.
Referenced by NumberString::createUnsignedInt64Value(), int64Object(), NumberString::newInstanceFromInt64(), NumberString::newInstanceFromUint64(), objectToInt64(), and objectToUnsignedInt64().
FORM_ENGINEERING
const bool Numerics::FORM_ENGINEERING = true static
Definition at line 122 of file Numerics.hpp.
Referenced by RexxInstructionNumeric::execute(), NumberString::formatInternal(), LanguageParser::optionsDirective(), and NumberString::plus().
FORM_SCIENTIFIC
const bool Numerics::FORM_SCIENTIFIC = false static
Definition at line 121 of file Numerics.hpp.
Referenced by BUILTIN(), RexxInstructionNumeric::execute(), PackageClass::formRexx(), RexxContext::getForm(), LanguageParser::optionsDirective(), NumberString::plus(), and NumberString::setNumericSettings().
MAX_EXPONENT
const wholenumber_t Numerics::MAX_EXPONENT = 999999999 static
Definition at line 113 of file Numerics.hpp.
Referenced by NumberStringBuilder::addExponentDigit(), NumberStringBase::checkOverflow(), NumberStringBuilder::finish(), RexxInfo::getMaxExponent(), NumberString::power(), and NumberString::stringValue().
MAX_REXXINTEGER
const wholenumber_t Numerics::MAX_REXXINTEGER = MAX_WHOLENUMBER static
Definition at line 106 of file Numerics.hpp.
MAX_STRINGSIZE
const size_t Numerics::MAX_STRINGSIZE = MAX_WHOLENUMBER static
Definition at line 117 of file Numerics.hpp.
Referenced by NativeActivation::objectToValue(), and NativeActivation::processArguments().
MAX_WHOLENUMBER
const wholenumber_t Numerics::MAX_WHOLENUMBER = 999999999 static
Definition at line 94 of file Numerics.hpp.
Referenced by RexxString::caselessChangeStr(), MutableBuffer::caselessChangeStr(), RexxString::caselessCountStrRexx(), MutableBuffer::caselessCountStrRexx(), RexxString::changeStr(), MutableBuffer::changeStr(), RexxString::countStrRexx(), MutableBuffer::countStrRexx(), RexxString::delWord(), MutableBuffer::delWord(), RexxInfo::getInternalMaxNumber(), intptrToObject(), NativeActivation::nonnegativeWholeNumberValue(), RexxInteger::numberValue(), ObjectToStringSize(), NativeActivation::objectToValue(), ObjectToWholeNumber(), NativeActivation::positiveWholeNumberValue(), NativeActivation::processArguments(), RexxRoutine7(), StemClass::sort(), stringsizeToObject(), StringUtil::subWord(), StringUtil::subWords(), uint64ToObject(), uintptrToObject(), and RexxInteger::unsignedNumberValue().
MIN_EXPONENT
const wholenumber_t Numerics::MIN_EXPONENT = -999999999 static
Definition at line 114 of file Numerics.hpp.
Referenced by NumberStringBase::checkOverflow(), and RexxInfo::getMinExponent().
MIN_REXXINTEGER
const wholenumber_t Numerics::MIN_REXXINTEGER = MIN_WHOLENUMBER static
Definition at line 105 of file Numerics.hpp.
MIN_WHOLENUMBER
const wholenumber_t Numerics::MIN_WHOLENUMBER = -999999999 static
Definition at line 95 of file Numerics.hpp.
Referenced by RexxInfo::getInternalMinNumber(), int64ToObject(), intptrToObject(), isValid(), NativeActivation::objectToValue(), ObjectToWholeNumber(), NativeActivation::processArguments(), and wholenumberToObject().
REXXINTEGER_BITS
const wholenumber_t Numerics::REXXINTEGER_BITS = 32 static
Definition at line 110 of file Numerics.hpp.
REXXINTEGER_DIGITS
const wholenumber_t Numerics::REXXINTEGER_DIGITS = Numerics::ARGUMENT_DIGITS static
Definition at line 104 of file Numerics.hpp.
Referenced by LanguageParser::addText(), NumberString::Division(), isValid(), isValid64Bit(), maxBitsForDigits(), maxValueForDigits(), RexxInteger::power(), LanguageParser::scanSymbol(), NumberString::truncInternal(), and RexxString::x2dC2d().
settings
const NumericSettings * Numerics::settings = &Numerics::defaultSettings static protected
Definition at line 197 of file Numerics.hpp.
Referenced by digits(), form(), fuzz(), setCurrentSettings(), and setDefaultSettings().
SIZE_DIGITS
const wholenumber_t Numerics::SIZE_DIGITS = 10 static
Definition at line 100 of file Numerics.hpp.
Referenced by objectToSignedInteger(), and objectToUnsignedInteger().
validMaxWhole
const wholenumber_t Numerics::validMaxWhole static
Initial value:
= {0,
                                           9,
                                           99,
                                           999,
                                           9999,
                                           99999,
                                           999999,
                                           9999999,
                                           99999999,
                                           999999999}
Definition at line 127 of file Numerics.hpp.
Referenced by isValid(), isValid64Bit(), and maxValueForDigits().
validMaxWholeBits
const wholenumber_t Numerics::validMaxWholeBits static
Initial value:
=
  {0, 4, 7, 10, 14, 17, 20, 24, 27, 30}
Definition at line 128 of file Numerics.hpp.
Referenced by maxBitsForDigits().
The documentation for this class was generated from the following files:
Numerics.hpp
Numerics.cpp