ooRexx: ServerQueueManager Class Reference
ServerQueueManager Class Reference
#include <QueueManager.hpp>
Public Member Functions
ServerQueueManager ()
void terminateServer ()
void addToSessionQueue (ServiceMessage &message)
void addToNamedQueue (ServiceMessage &message)
void pullFromSessionQueue (ServiceMessage &message)
void pullFromNamedQueue (ServiceMessage &message)
void createSessionQueue (ServiceMessage &message)
DataQueue * getSessionQueue (SessionID session)
void createSessionQueue (SessionID session)
void createUniqueQueue (ServiceMessage &message)
void createNamedQueue (ServiceMessage &message)
void openNamedQueue (ServiceMessage &message)
void queryNamedQueue (ServiceMessage &message)
void nestSessionQueue (ServiceMessage &message)
void deleteSessionQueue (ServiceMessage &message)
void deleteSessionQueue (DataQueue *queue)
void deleteNamedQueue (ServiceMessage &message)
void clearSessionQueue (ServiceMessage &message)
void clearNamedQueue (ServiceMessage &message)
void getSessionQueueCount (ServiceMessage &message)
void getNamedQueueCount (ServiceMessage &message)
void dispatch (ServiceMessage &message)
void cleanupProcessResources (SessionID session)
bool isStoppable ()
Protected Attributes
QueueTable namedQueues
QueueTable sessionQueues
SysMutex lock
Friends
class DataQueue
class QueueTable
Detailed Description
Definition at line 239 of file QueueManager.hpp.
Constructor & Destructor Documentation
ServerQueueManager()
ServerQueueManager::ServerQueueManager () inline
Definition at line 244 of file QueueManager.hpp.
References SysMutex::create(), and lock.
Member Function Documentation
addToNamedQueue()
void ServerQueueManager::addToNamedQueue (ServiceMessage & message)
Definition at line 476 of file QueueManager.cpp.
References DataQueue::add(), QueueTable::locate(), ServiceMessage::nameArg, namedQueues, QUEUE_DOES_NOT_EXIST, and ServiceMessage::setResult().
Referenced by dispatch().
addToSessionQueue()
void ServerQueueManager::addToSessionQueue (ServiceMessage & message)
Definition at line 463 of file QueueManager.cpp.
References DataQueue::add(), getSessionQueue(), and ServiceMessage::parameter3.
Referenced by dispatch().
cleanupProcessResources()
void ServerQueueManager::cleanupProcessResources (SessionID session)
Definition at line 932 of file QueueManager.cpp.
References deleteSessionQueue(), QueueTable::locate(), and sessionQueues.
Referenced by APIServerInstance::cleanupProcessResources().
clearNamedQueue()
void ServerQueueManager::clearNamedQueue (ServiceMessage & message)
Definition at line 847 of file QueueManager.cpp.
References DataQueue::clear(), QueueTable::locate(), ServiceMessage::nameArg, namedQueues, QUEUE_DOES_NOT_EXIST, QUEUE_EXISTS, and ServiceMessage::setResult().
Referenced by dispatch().
clearSessionQueue()
void ServerQueueManager::clearSessionQueue (ServiceMessage & message)
Definition at line 832 of file QueueManager.cpp.
References DataQueue::clear(), getSessionQueue(), ServiceMessage::parameter1, QUEUE_EXISTS, and ServiceMessage::setResult().
Referenced by dispatch().
createNamedQueue()
void ServerQueueManager::createNamedQueue (ServiceMessage & message)
Definition at line 629 of file QueueManager.cpp.
References QueueTable::add(), createUniqueQueue(), DataQueue, DUPLICATE_QUEUE_NAME, QueueTable::locate(), ServiceMessage::nameArg, namedQueues, QUEUE_CREATED, and ServiceMessage::setResult().
Referenced by dispatch().
createSessionQueue() [1/2]
void ServerQueueManager::createSessionQueue (ServiceMessage & message)
Definition at line 579 of file QueueManager.cpp.
References ServiceMessage::parameter1, QUEUE_CREATED, and ServiceMessage::setResult().
Referenced by dispatch(), and nestSessionQueue().
createSessionQueue() [2/2]
void ServerQueueManager::createSessionQueue (SessionID session)
Definition at line 556 of file QueueManager.cpp.
References QueueTable::add(), DataQueue::addReference(), DataQueue, QueueTable::locate(), and sessionQueues.
createUniqueQueue()
void ServerQueueManager::createUniqueQueue (ServiceMessage & message)
Create a queue with a unique name.
Parameters
message The inbound service message.
Definition at line 593 of file QueueManager.cpp.
References QueueTable::add(), DataQueue, QueueTable::locate(), ServiceMessage::nameArg, namedQueues, ServiceMessage::NAMESIZE, ServiceMessage::parameter1, and DataQueue::setName().
Referenced by createNamedQueue().
deleteNamedQueue()
void ServerQueueManager::deleteNamedQueue (ServiceMessage & message)
Definition at line 766 of file QueueManager.cpp.
References DataQueue::hasWaiters(), QueueTable::locate(), ServiceMessage::nameArg, namedQueues, QUEUE_DELETED, QUEUE_DOES_NOT_EXIST, QUEUE_IN_USE, QueueTable::remove(), and ServiceMessage::setResult().
Referenced by dispatch().
deleteSessionQueue() [1/2]
void ServerQueueManager::deleteSessionQueue (DataQueue * queue)
Definition at line 748 of file QueueManager.cpp.
References DataQueue::hasWaiters(), QueueTable::remove(), DataQueue::removeReference(), and sessionQueues.
deleteSessionQueue() [2/2]
void ServerQueueManager::deleteSessionQueue (ServiceMessage & message)
Definition at line 725 of file QueueManager.cpp.
References getSessionQueue(), ServiceMessage::parameter1, QUEUE_DELETED, QUEUE_IN_USE, QueueTable::remove(), sessionQueues, and ServiceMessage::setResult().
Referenced by cleanupProcessResources(), and dispatch().
dispatch()
void ServerQueueManager::dispatch (ServiceMessage & message)
Dispatch a queue manager message to the appropriate action.
Parameters
message The inbound message from the client.
Definition at line 870 of file QueueManager.cpp.
References ADD_TO_NAMED_QUEUE, ADD_TO_SESSION_QUEUE, addToNamedQueue(), addToSessionQueue(), CLEAR_NAMED_QUEUE, CLEAR_SESSION_QUEUE, clearNamedQueue(), clearSessionQueue(), CREATE_NAMED_QUEUE, CREATE_SESSION_QUEUE, createNamedQueue(), createSessionQueue(), DELETE_NAMED_QUEUE, DELETE_SESSION_QUEUE, deleteNamedQueue(), deleteSessionQueue(), GET_NAMED_QUEUE_COUNT, GET_SESSION_QUEUE_COUNT, getNamedQueueCount(), getSessionQueueCount(), INVALID_OPERATION, lock, NEST_SESSION_QUEUE, nestSessionQueue(), OPEN_NAMED_QUEUE, openNamedQueue(), ServiceMessage::operation, PULL_FROM_NAMED_QUEUE, PULL_FROM_SESSION_QUEUE, pullFromNamedQueue(), pullFromSessionQueue(), QUERY_NAMED_QUEUE, queryNamedQueue(), and ServiceMessage::setExceptionInfo().
Referenced by APIServerInstance::dispatch().
getNamedQueueCount()
void ServerQueueManager::getNamedQueueCount (ServiceMessage & message)
Definition at line 810 of file QueueManager.cpp.
References DataQueue::getItemCount(), QueueTable::locate(), ServiceMessage::nameArg, namedQueues, ServiceMessage::parameter1, QUEUE_DOES_NOT_EXIST, QUEUE_EXISTS, and ServiceMessage::setResult().
Referenced by dispatch().
getSessionQueue()
DataQueue * ServerQueueManager::getSessionQueue (SessionID session)
Definition at line 535 of file QueueManager.cpp.
References QueueTable::add(), DataQueue, QueueTable::locate(), lock, and sessionQueues.
Referenced by addToSessionQueue(), clearSessionQueue(), deleteSessionQueue(), getSessionQueueCount(), and pullFromSessionQueue().
getSessionQueueCount()
void ServerQueueManager::getSessionQueueCount (ServiceMessage & message)
Definition at line 795 of file QueueManager.cpp.
References getSessionQueue(), ServiceMessage::parameter1, QUEUE_EXISTS, and ServiceMessage::setResult().
Referenced by dispatch().
isStoppable()
bool ServerQueueManager::isStoppable () inline
Definition at line 268 of file QueueManager.hpp.
References QueueTable::isEmpty(), namedQueues, and sessionQueues.
Referenced by APIServerInstance::isStoppable().
nestSessionQueue()
void ServerQueueManager::nestSessionQueue (ServiceMessage & message)
Definition at line 710 of file QueueManager.cpp.
References createSessionQueue(), ServiceMessage::parameter1, ServiceMessage::parameter2, QUEUE_OK, and ServiceMessage::setResult().
Referenced by dispatch().
openNamedQueue()
void ServerQueueManager::openNamedQueue (ServiceMessage & message)
Definition at line 665 of file QueueManager.cpp.
References QueueTable::add(), DataQueue, QueueTable::locate(), ServiceMessage::nameArg, namedQueues, QUEUE_CREATED, QUEUE_EXISTS, and ServiceMessage::setResult().
Referenced by dispatch().
pullFromNamedQueue()
void ServerQueueManager::pullFromNamedQueue (ServiceMessage & message)
Definition at line 512 of file QueueManager.cpp.
References ServiceMessage::nameArg, namedQueues, DataQueue::pull(), QUEUE_DOES_NOT_EXIST, ServiceMessage::setResult(), and QueueTable::synchronizedLocate().
Referenced by dispatch().
pullFromSessionQueue()
void ServerQueueManager::pullFromSessionQueue (ServiceMessage & message)
Definition at line 499 of file QueueManager.cpp.
References getSessionQueue(), ServiceMessage::parameter3, and DataQueue::pull().
Referenced by dispatch().
queryNamedQueue()
void ServerQueueManager::queryNamedQueue (ServiceMessage & message)
Definition at line 689 of file QueueManager.cpp.
References QueueTable::locate(), ServiceMessage::nameArg, namedQueues, QUEUE_DOES_NOT_EXIST, QUEUE_EXISTS, and ServiceMessage::setResult().
Referenced by dispatch().
terminateServer()
void ServerQueueManager::terminateServer ()
Friends And Related Function Documentation
DataQueue
friend class DataQueue friend
Definition at line 241 of file QueueManager.hpp.
Referenced by createNamedQueue(), createSessionQueue(), createUniqueQueue(), getSessionQueue(), and openNamedQueue().
QueueTable
friend class QueueTable friend
Definition at line 242 of file QueueManager.hpp.
Member Data Documentation
lock
SysMutex ServerQueueManager::lock protected
Definition at line 277 of file QueueManager.hpp.
Referenced by dispatch(), getSessionQueue(), DataQueue::pull(), DataQueue::pullData(), ServerQueueManager(), and QueueTable::synchronizedLocate().
namedQueues
QueueTable ServerQueueManager::namedQueues protected
Definition at line 275 of file QueueManager.hpp.
Referenced by addToNamedQueue(), clearNamedQueue(), createNamedQueue(), createUniqueQueue(), deleteNamedQueue(), getNamedQueueCount(), isStoppable(), openNamedQueue(), pullFromNamedQueue(), and queryNamedQueue().
sessionQueues
QueueTable ServerQueueManager::sessionQueues protected
Definition at line 276 of file QueueManager.hpp.
Referenced by cleanupProcessResources(), createSessionQueue(), deleteSessionQueue(), getSessionQueue(), and isStoppable().
The documentation for this class was generated from the following files:
QueueManager.hpp
QueueManager.cpp