ooRexx: AutoFileNameBuffer Class Reference
AutoFileNameBuffer Class Reference
#include <FileNameBuffer.hpp>
Public Member Functions
AutoFileNameBuffer (FileNameBuffer &b)
AutoFileNameBuffer & operator= (const char *s)
AutoFileNameBuffer & operator= (char *s)
AutoFileNameBuffer & operator= (char s)
AutoFileNameBuffer & operator+= (FileNameBuffer &s)
AutoFileNameBuffer & operator+= (const char *s)
AutoFileNameBuffer & operator+= (char *s)
AutoFileNameBuffer & operator+= (char s)
void handleMemoryError () override
Public Member Functions inherited from FileNameBuffer
FileNameBuffer (size_t initial=0)
FileNameBuffer (const FileNameBuffer &o)
~FileNameBuffer ()
void init (size_t initial)
size_t capacity ()
size_t length ()
operator char * ()
operator const char * ()
void ensureCapacity (size_t size)
void ensureAdditionalCapacity (const char *add)
void expandCapacity (size_t c)
void shiftLeft (size_t l)
void truncate (size_t l)
void empty ()
FileNameBuffer & operator= (const char *s)
FileNameBuffer & operator= (const FileNameBuffer &s)
FileNameBuffer & operator= (char *s)
FileNameBuffer & operator+= (const char *s)
FileNameBuffer & operator+= (char *s)
FileNameBuffer & operator+= (char c)
FileNameBuffer & operator+= (FileNameBuffer &s)
FileNameBuffer & set (const char *s, size_t l)
FileNameBuffer & append (const char *s, size_t l)
bool operator== (const char *s)
bool operator!= (const char *s)
char & at (size_t pos)
bool startsWith (char c)
bool startsWith (const char *s)
bool endsWith (char c)
bool endsWith (const char *s)
bool isEmpty ()
void appendPathSeparator ()
void addFinalPathDelimiter ()
size_t locatePathDelimiter (size_t start=0)
Private Attributes
FileNameBuffer & parent
Additional Inherited Members
Protected Attributes inherited from FileNameBuffer
char * buffer
size_t bufferSize
Detailed Description
A version of a FileNameBuffer that uses a parent FileNameBuffer for handling allocation error.
Definition at line 322 of file FileNameBuffer.hpp.
Constructor & Destructor Documentation
AutoFileNameBuffer()
AutoFileNameBuffer::AutoFileNameBuffer (FileNameBuffer & b) inline
Definition at line 325 of file FileNameBuffer.hpp.
Member Function Documentation
handleMemoryError()
void AutoFileNameBuffer::handleMemoryError () inline override virtual
Handle a memory error. Base implementation is for just raising a normal exception. This can only be used within internal code when the kernel lock is held.
Reimplemented from FileNameBuffer.
Definition at line 371 of file FileNameBuffer.hpp.
References FileNameBuffer::handleMemoryError(), and parent.
operator+=() [1/4]
AutoFileNameBuffer& AutoFileNameBuffer::operator+= (char * s) inline
Definition at line 359 of file FileNameBuffer.hpp.
References FileNameBuffer::operator+=().
operator+=() [2/4]
AutoFileNameBuffer& AutoFileNameBuffer::operator+= (char s) inline
Definition at line 365 of file FileNameBuffer.hpp.
References FileNameBuffer::operator+=().
operator+=() [3/4]
AutoFileNameBuffer& AutoFileNameBuffer::operator+= (const char * s) inline
Definition at line 353 of file FileNameBuffer.hpp.
References FileNameBuffer::operator+=().
operator+=() [4/4]
AutoFileNameBuffer& AutoFileNameBuffer::operator+= (FileNameBuffer & s) inline
Definition at line 347 of file FileNameBuffer.hpp.
References FileNameBuffer::operator+=().
operator=() [1/3]
AutoFileNameBuffer& AutoFileNameBuffer::operator= (char * s) inline
Definition at line 335 of file FileNameBuffer.hpp.
References FileNameBuffer::operator=().
operator=() [2/3]
AutoFileNameBuffer& AutoFileNameBuffer::operator= (char s) inline
Definition at line 341 of file FileNameBuffer.hpp.
References FileNameBuffer::operator=().
operator=() [3/3]
AutoFileNameBuffer& AutoFileNameBuffer::operator= (const char * s) inline
Definition at line 329 of file FileNameBuffer.hpp.
References FileNameBuffer::operator=().
Member Data Documentation
parent
FileNameBuffer& AutoFileNameBuffer::parent private
Definition at line 374 of file FileNameBuffer.hpp.
Referenced by handleMemoryError().
The documentation for this class was generated from the following file:
FileNameBuffer.hpp