ooRexx: InstanceBlock Class Reference
InstanceBlock Class Reference
#include <Interpreter.hpp>
Public Member Functions
InstanceBlock ()
InstanceBlock (RexxOption *options)
InstanceBlock (PRXSYSEXIT exits, const char *env)
~InstanceBlock ()
Public Attributes
Activity * activity
InterpreterInstance * instance
Detailed Description
Definition at line 238 of file Interpreter.hpp.
Constructor & Destructor Documentation
InstanceBlock() [1/3]
InstanceBlock::InstanceBlock ()
Manage a context where a new interpreter instance is created for the purposes of acquiring an activity, and the activity is released and the instance is terminated upon leaving the block.
Definition at line 416 of file Interpreter.cpp.
References activity, Interpreter::createInterpreterInstance(), InterpreterInstance::getRootActivity(), and instance.
InstanceBlock() [2/3]
InstanceBlock::InstanceBlock (RexxOption * options)
Manage a context where a new interpreter instance is created for the purposes of acquiring an activity, and the activity is released and the instance is terminated upon leaving the block.
Definition at line 431 of file Interpreter.cpp.
References activity, Interpreter::createInterpreterInstance(), InterpreterInstance::getRootActivity(), and instance.
InstanceBlock() [3/3]
InstanceBlock::InstanceBlock (PRXSYSEXIT exits, const char * env)
Manage a context where a new interpreter instance is created for the purposes of acquiring an activity, and the activity is released and the instance is terminated upon leaving the block.
Definition at line 446 of file Interpreter.cpp.
References activity, Interpreter::createInterpreterInstance(), InterpreterInstance::getRootActivity(), INITIAL_ADDRESS_ENVIRONMENT, instance, RexxOption::option, RexxOption::optionName, and REGISTERED_EXITS.
~InstanceBlock()
InstanceBlock::~InstanceBlock ()
Release the kernal access and cleanup when the context block goes out of scope.
Definition at line 481 of file Interpreter.cpp.
References activity, Activity::exitCurrentThread(), instance, and InterpreterInstance::terminate().
Member Data Documentation
activity
Activity* InstanceBlock::activity
Definition at line 246 of file Interpreter.hpp.
Referenced by InstanceBlock(), ActivityDispatcher::invoke(), and ~InstanceBlock().
instance
InterpreterInstance* InstanceBlock::instance
Definition at line 247 of file Interpreter.hpp.
Referenced by InstanceBlock(), and ~InstanceBlock().
The documentation for this class was generated from the following files:
Interpreter.hpp
Interpreter.cpp