ooRexx: RexxInteger Class Reference
RexxInteger Class Reference
#include <IntegerClass.hpp>
Public Member Functions
RexxInteger (RESTORETYPE restoreType)
RexxInteger (wholenumber_t intValue)
void * operator new (size_t)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
HashCode getHashValue () override
bool numberValue (wholenumber_t &result, wholenumber_t precision) override
bool numberValue (wholenumber_t &result) override
bool unsignedNumberValue (size_t &result, wholenumber_t precision) override
bool unsignedNumberValue (size_t &result) override
bool doubleValue (double &result) override
void processUnknown (RexxErrorCodes error, RexxString *, RexxObject **, size_t, ProtectedObject &) override
wholenumber_t compareTo (RexxInternalObject *) override
NumberString * numberString () override
RexxInteger * integerValue (wholenumber_t) override
RexxString * makeString () override
void copyIntoTail (CompoundVariableTail *) override
bool hasMethod (RexxString *) override
RexxString * primitiveMakeString () override
RexxString * stringValue () override
ArrayClass * makeArray () override
bool truthValue (RexxErrorCodes) override
bool logicalValue (logical_t &) override
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
bool isEqual (RexxInternalObject *) override
wholenumber_t strictComp (RexxObject *)
bool strictEquality (RexxObject *)
wholenumber_t comp (RexxObject *other)
RexxObject * equal (RexxObject *)
RexxObject * strictEqual (RexxObject *)
RexxObject * notEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *)
RexxObject * isGreaterThan (RexxObject *)
RexxObject * isLessThan (RexxObject *)
RexxObject * isGreaterOrEqual (RexxObject *)
RexxObject * isLessOrEqual (RexxObject *)
RexxObject * strictGreaterThan (RexxObject *)
RexxObject * strictLessThan (RexxObject *)
RexxObject * strictGreaterOrEqual (RexxObject *)
RexxObject * strictLessOrEqual (RexxObject *)
RexxObject * hashCode ()
RexxObject * plus (RexxInteger *)
RexxObject * minus (RexxInteger *)
RexxObject * multiply (RexxInteger *)
RexxObject * divide (RexxInteger *)
RexxObject * integerDivide (RexxInteger *)
RexxObject * remainder (RexxInteger *)
RexxObject * modulo (RexxInteger *)
RexxObject * power (RexxObject *)
RexxObject * notOp ()
RexxObject * operatorNot (RexxObject *)
RexxObject * andOp (RexxObject *)
RexxObject * orOp (RexxObject *)
RexxObject * xorOp (RexxObject *)
RexxObject * choiceRexx (RexxObject *, RexxObject *)
RexxObject * abs ()
RexxObject * sign ()
RexxObject * Max (RexxObject **, size_t)
RexxObject * Min (RexxObject **, size_t)
RexxObject * trunc (RexxObject *)
RexxObject * floor ()
RexxObject * ceiling ()
RexxObject * round ()
RexxObject * format (RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * d2c (RexxInteger *)
RexxObject * d2x (RexxInteger *)
RexxObject * evaluate (RexxActivation *, ExpressionStack *) override
RexxObject * getValue (RexxActivation *) override
RexxObject * getValue (VariableDictionary *) override
RexxObject * getRealValue (RexxActivation *) override
RexxObject * getRealValue (VariableDictionary *) override
RexxString * concat (RexxString *)
RexxString * concatBlank (RexxString *)
void setString (RexxString *string)
RexxClass * classObject ()
wholenumber_t getValue ()
wholenumber_t wholeNumber ()
size_t stringSize ()
RexxString * getStringrep ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
RexxInternalObject * copy () override
HashCode hash () override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
HashCode identityHash ()
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static PCPPM operatorMethods []
static RexxIntegerClass * classInstance = OREF_NULL
static RexxInteger * falseObject = OREF_NULL
static RexxInteger * trueObject = OREF_NULL
static RexxInteger * nullPointer = OREF_NULL
static RexxInteger * integerZero = OREF_NULL
static RexxInteger * integerOne = OREF_NULL
static RexxInteger * integerTwo = OREF_NULL
static RexxInteger * integerThree = OREF_NULL
static RexxInteger * integerFour = OREF_NULL
static RexxInteger * integerFive = OREF_NULL
static RexxInteger * integerSix = OREF_NULL
static RexxInteger * integerSeven = OREF_NULL
static RexxInteger * integerEight = OREF_NULL
static RexxInteger * integerNine = OREF_NULL
static RexxInteger * integerMinusOne = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
RexxString * stringrep
wholenumber_t value
Static Protected Attributes
static wholenumber_t validMaxWhole []
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 53 of file IntegerClass.hpp.
Constructor & Destructor Documentation
RexxInteger() [1/2]
RexxInteger::RexxInteger (RESTORETYPE restoreType) inline
Definition at line 56 of file IntegerClass.hpp.
RexxInteger() [2/2]
RexxInteger::RexxInteger (wholenumber_t intValue) inline
Definition at line 57 of file IntegerClass.hpp.
References value.
Member Function Documentation
abs()
RexxObject * RexxInteger::abs ()
Take the absolute value of an integer object
Returns
The abs() result.
Definition at line 1527 of file IntegerClass.cpp.
References NumberString::abs(), Numerics::isValid(), new_integer(), number_digits(), numberString(), and value.
Referenced by MemoryObject::createImage().
andOp()
RexxObject * RexxInteger::andOp (RexxObject * other)
Logically AND two objects together
Parameters
other The other object for the AND
Returns
The logical result.
Definition at line 1454 of file IntegerClass.cpp.
References ARG_ONE, booleanObject(), Error_Logical_value_method, requiredArgument(), TheFalseObject, RexxInternalObject::truthValue(), and truthValue().
Referenced by MemoryObject::createImage().
ceiling()
RexxObject * RexxInteger::ceiling ()
Calculate the ceiling value for a numeric value
Returns
The ceiling value.
Definition at line 1730 of file IntegerClass.cpp.
References NumberString::ceiling(), Numerics::isValid(), number_digits(), numberString(), and value.
Referenced by MemoryObject::createImage().
choiceRexx()
RexxObject * RexxInteger::choiceRexx (RexxObject * trueResult, RexxObject * falseResult)
Implement an expression choice method. The target object is evaluated as a logical value, and if it evaluates to true, returns the first argument as a result. If it evaluates to false, it returns the second argument.
Parameters
trueResult The value to return for a true result.
falseResult The falue to return for a false result
Returns
Either the true value or the false value based on the value of the target object.
Definition at line 1513 of file IntegerClass.cpp.
References Error_Logical_value_method, requiredArgument(), and truthValue().
Referenced by MemoryObject::createImage().
classObject()
RexxClass * RexxInteger::classObject ()
An override for retrieving the class object. We lie and pretend we're the string class.
Returns
The associated class object.
Definition at line 2037 of file IntegerClass.cpp.
References TheStringClass.
Referenced by MemoryObject::createImage().
comp()
wholenumber_t RexxInteger::comp (RexxObject * other)
Do a comparison operation between an Integer object and another object.
Parameters
other The other object.
Returns
<0, 0, or >0 to give appropriate ordering
Definition at line 1188 of file IntegerClass.cpp.
References ARG_ONE, NumberString::comp(), isInteger(), Numerics::isValid(), number_digits(), number_fuzz(), numberString(), requiredArgument(), and value.
Referenced by equal(), isGreaterOrEqual(), isGreaterThan(), isLessOrEqual(), isLessThan(), and notEqual().
compareTo()
wholenumber_t RexxInteger::compareTo (RexxInternalObject * other) override virtual
Wrapper around the compareTo() method that does string sort comparisons.
Parameters
other The other comparison object
Returns
-1, 0, 1 depending on the comparison result.
Reimplemented from RexxInternalObject.
Definition at line 466 of file IntegerClass.cpp.
References RexxString::compareTo(), and stringValue().
concat()
RexxString * RexxInteger::concat (RexxString * other)
Concatenate an object to an Integer
Parameters
other The other object for the concatenation.
Returns
The concatenation result.
Definition at line 539 of file IntegerClass.cpp.
References RexxString::concatRexx(), and stringValue().
concatBlank()
RexxString * RexxInteger::concatBlank (RexxString * other)
Blank concatenation method for an integer object.
Parameters
other The other concatenation value.
Returns
Definition at line 525 of file IntegerClass.cpp.
References RexxString::concatBlank(), and stringValue().
copyIntoTail()
void RexxInteger::copyIntoTail (CompoundVariableTail * tail) override virtual
Copy the value of an integer into a compound variable name
Parameters
tail The compound tail we're adding to.
Reimplemented from RexxInternalObject.
Definition at line 218 of file IntegerClass.cpp.
References CompoundVariableTail::append(), RexxString::copyIntoTail(), Numerics::formatWholeNumber(), OREF_NULL, stringrep, and value.
createInstance()
void RexxInteger::createInstance () static
Create the integer class and set up the integer cache
Definition at line 2062 of file IntegerClass.cpp.
References CLASS_CREATE_SPECIAL, and TheIntegerClass.
Referenced by MemoryObject::createImage().
d2c()
RexxObject * RexxInteger::d2c (RexxInteger * lengthObject)
Convert a decimal number string into a character string
Parameters
length The target length for the converted string.
Returns
The converted string value.
Definition at line 1786 of file IntegerClass.cpp.
References NumberString::d2xD2c(), getValue(), isInteger(), Numerics::isValid(), length_in_bits(), number_digits(), numberString(), OREF_NULL, RexxString::StringBuilderRtL::put(), raw_string(), and value.
Referenced by MemoryObject::createImage().
d2x()
RexxObject * RexxInteger::d2x (RexxInteger * lengthObject)
Convert a decimal number string into a hexadecimal string
Parameters
length The length for the conversion.
Returns
The converted string.
Definition at line 1844 of file IntegerClass.cpp.
References NumberString::d2xD2c(), getValue(), RexxString::intToHexDigit(), isInteger(), Numerics::isValid(), length_in_bits(), number_digits(), numberString(), OREF_NULL, RexxString::StringBuilderRtL::put(), raw_string(), and value.
Referenced by MemoryObject::createImage().
divide()
RexxObject * RexxInteger::divide (RexxInteger * other)
Divide an integer object by another object.
Parameters
other The other object.
Returns
The divide result
Definition at line 725 of file IntegerClass.cpp.
References getValue(), integer_forward, isInteger(), Numerics::isValid(), new_integer(), number_digits(), OREF_NULL, and value.
Referenced by MemoryObject::createImage().
doubleValue()
bool RexxInteger::doubleValue (double & result) override virtual
Convert an integer object into a double value.
Parameters
value The returned value.
Returns
true if this converted ok, false for any errors. This always returns true for the Integer class.
Reimplemented from RexxInternalObject.
Definition at line 263 of file IntegerClass.cpp.
References wholeNumber().
equal()
RexxObject * RexxInteger::equal (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1262 of file IntegerClass.cpp.
References booleanObject(), comp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
evaluate()
RexxObject * RexxInteger::evaluate (RexxActivation * context, ExpressionStack * stack) override virtual
Perform expression evaluation for an integer term.
Parameters
context The current exection context.
stack The current evaluation stack.
Returns
The evaluation result.
Reimplemented from RexxInternalObject.
Definition at line 1909 of file IntegerClass.cpp.
References ExpressionStack::push(), RexxActivation::TRACE_PREFIX_LITERAL, and RexxActivation::traceIntermediate().
flatten()
void RexxInteger::flatten (Envelope * envelope) override virtual
Flatten a source object.
Parameters
envelope The envelope that will hold the flattened object.
Reimplemented from RexxObject.
Definition at line 126 of file IntegerClass.cpp.
References cleanUpFlatten, flattenRef, setUpFlatten, and stringrep.
floor()
RexxObject * RexxInteger::floor ()
Calculate the floor value for a numeric value
Returns
The floor value.
Definition at line 1711 of file IntegerClass.cpp.
References NumberString::floor(), Numerics::isValid(), number_digits(), numberString(), and value.
Referenced by MemoryObject::createImage().
format()
RexxObject * RexxInteger::format (RexxObject * integers, RexxObject * decimals, RexxObject * mathExp, RexxObject * expTrigger)
Act as a front end for the actual FORMAT REXX method
Parameters
integers The number of integers requested
decimals The number decimals to include
mathExp The mathexp value.
expTrigger The exptrigger result.
Returns
The formatted number.
Definition at line 1772 of file IntegerClass.cpp.
References NumberString::formatRexx(), and numberString().
Referenced by MemoryObject::createImage().
getHashValue()
HashCode RexxInteger::getHashValue () override virtual
Get the primitive hash value of this String object.
Returns
The calculated string hash for the string.
Reimplemented from RexxInternalObject.
Definition at line 81 of file IntegerClass.cpp.
References RexxString::getHashValue(), and stringValue().
getRealValue() [1/2]
RexxObject * RexxInteger::getRealValue (RexxActivation * context) override virtual
Polymorphic getRealValue function used with expression terms
Parameters
context The execution context.
Returns
The term result (which is this object).
Reimplemented from RexxInternalObject.
Definition at line 1957 of file IntegerClass.cpp.
getRealValue() [2/2]
RexxObject * RexxInteger::getRealValue (VariableDictionary * context) override virtual
Polymorphic getRealValue function used with expression terms
Parameters
context The variable dictionary used to resolve variables.
Returns
The term result (which is this object).
Reimplemented from RexxInternalObject.
Definition at line 1971 of file IntegerClass.cpp.
getStringrep()
RexxString* RexxInteger::getStringrep () inline
Definition at line 148 of file IntegerClass.hpp.
References stringrep.
Referenced by RexxString::integerValue().
getValue() [1/3]
wholenumber_t RexxInteger::getValue () inline
Definition at line 145 of file IntegerClass.hpp.
References value.
Referenced by trunc().
getValue() [2/3]
RexxObject * RexxInteger::getValue (RexxActivation * context) override virtual
Polymorphic getValue function used with expression terms
Parameters
context The execution context.
Returns
The term result (which is this object).
Reimplemented from RexxInternalObject.
Definition at line 1926 of file IntegerClass.cpp.
Referenced by BUILTIN(), d2c(), d2x(), divide(), RexxActivation::getRandomSeed(), integerDivide(), modulo(), multiply(), RexxActivation::random(), and remainder().
getValue() [3/3]
RexxObject * RexxInteger::getValue (VariableDictionary * context) override virtual
Polymorphic getValue function used with expression terms
Parameters
context The variable dictionary used to resolve variables.
Returns
The term result (which is this object).
Reimplemented from RexxInternalObject.
Definition at line 1941 of file IntegerClass.cpp.
hashCode()
RexxObject * RexxInteger::hashCode ()
Exported version of the HASHCODE method for retrieving the object's hash.
Returns
A string version of the hash (generally holds binary characters).
Definition at line 1219 of file IntegerClass.cpp.
References RexxObject::hash(), and new_string().
Referenced by MemoryObject::createImage().
hasMethod()
bool RexxInteger::hasMethod (RexxString * methodName) override virtual
Spoofed version of the standard hasMethod method. This will forward the request to the object's string representation.
Parameters
methodName The target name of the method.
Returns
.true if the object has the method, .false otherwise.
Reimplemented from RexxObject.
Definition at line 167 of file IntegerClass.cpp.
References RexxObject::hasMethod(), and stringValue().
instanceMethod()
MethodClass * RexxInteger::instanceMethod (RexxString * method_name) override virtual
Retrieve the method instance for an object's defined method.
Parameters
method_name The method name.
Returns
The method object that implements the object method.
Reimplemented from RexxObject.
Definition at line 495 of file IntegerClass.cpp.
References RexxObject::instanceMethod(), and stringValue().
instanceMethods()
SupplierClass * RexxInteger::instanceMethods (RexxClass * class_object) override virtual
Return a supplier containing the methods implemented by an object. Depending on the argument, this is either A) all of the methods, B) just the explicitly set instance methods, or C) the methods provided by a given class.
Parameters
class_object The target class object (optional).
Returns
A supplier with the appropriate method set.
Reimplemented from RexxObject.
Definition at line 512 of file IntegerClass.cpp.
References RexxObject::instanceMethods(), and stringValue().
integerDivide()
RexxObject * RexxInteger::integerDivide (RexxInteger * other)
Perform an integer division operation.
Parameters
other The other value for the divide.
Returns
The division result
Definition at line 784 of file IntegerClass.cpp.
References getValue(), integer_forward, isInteger(), Numerics::isValid(), new_integer(), number_digits(), OREF_NULL, and value.
Referenced by MemoryObject::createImage().
integerValue()
RexxInteger * RexxInteger::integerValue (wholenumber_t digits) override virtual
Convert an integer to an integer (real easy!)
Parameters
digits The digits setting.
Returns
The integer value of this integer...which is us.
Reimplemented from RexxInternalObject.
Definition at line 364 of file IntegerClass.cpp.
isEqual()
bool RexxInteger::isEqual (RexxInternalObject * other) override virtual
Primitive strict equal\not equal method. This determines only strict equality, not greater or less than values.
Parameters
other the other object.
Returns
The comparison result
Reimplemented from RexxInternalObject.
Definition at line 1117 of file IntegerClass.cpp.
References RexxString::isEqual(), isInteger(), stringValue(), and value.
isGreaterOrEqual()
RexxObject * RexxInteger::isGreaterOrEqual (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1330 of file IntegerClass.cpp.
References booleanObject(), comp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
isGreaterThan()
RexxObject * RexxInteger::isGreaterThan (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1296 of file IntegerClass.cpp.
References booleanObject(), comp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
isInstanceOf()
bool RexxInteger::isInstanceOf (RexxClass * other) override virtual
Override for the normal isinstanceof method. This version allows the IntegerClass to "lie" about being a string.
Parameters
other The comparison class
Returns
True if the string value is an instance of the target class.
Reimplemented from RexxObject.
Definition at line 481 of file IntegerClass.cpp.
References RexxObject::isInstanceOf(), and stringValue().
isLessOrEqual()
RexxObject * RexxInteger::isLessOrEqual (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1347 of file IntegerClass.cpp.
References booleanObject(), comp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
isLessThan()
RexxObject * RexxInteger::isLessThan (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1313 of file IntegerClass.cpp.
References booleanObject(), comp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
live()
void RexxInteger::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxObject.
Definition at line 92 of file IntegerClass.cpp.
References memory_mark, and stringrep.
liveGeneral()
void RexxInteger::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxObject.
Definition at line 106 of file IntegerClass.cpp.
References memory_mark_general, RexxString::numberString(), PREPARINGIMAGE, stringrep, and stringValue().
logicalValue()
bool RexxInteger::logicalValue (logical_t & result) override virtual
Convert an object to a logical value without raising an error.
Parameters
result The converted value.
Returns
true if this converted ok, false for an invalid logical.
Reimplemented from RexxInternalObject.
Definition at line 411 of file IntegerClass.cpp.
References value.
makeArray()
ArrayClass * RexxInteger::makeArray () override virtual
Override for the default object makearray method.
Returns
The results of our string representation's makearray.
Reimplemented from RexxInternalObject.
Definition at line 153 of file IntegerClass.cpp.
References RexxString::makeArray(), and stringValue().
makeString()
RexxString * RexxInteger::makeString () override virtual
Handle a REQUEST('STRING') request for a REXX integer object
Returns
The string value of the integer object.
Reimplemented from RexxInternalObject.
Definition at line 142 of file IntegerClass.cpp.
References stringValue().
Max()
RexxObject * RexxInteger::Max (RexxObject ** args, size_t argCount)
Perform MAX function on integer objects
Parameters
args The array of arguments
argCount The count of arguments
Returns
The largest of the numbers.
Definition at line 1576 of file IntegerClass.cpp.
References isInteger(), Numerics::isValid(), NumberString::Max(), number_digits(), numberString(), requiredArgument(), and value.
Referenced by MemoryObject::createImage().
Min()
RexxObject * RexxInteger::Min (RexxObject ** args, size_t argCount)
Perform MIN function on integer objects
Parameters
args The array of arguments
argCount The count of arguments
Returns
The smallest of the numbers.
Definition at line 1632 of file IntegerClass.cpp.
References isInteger(), Numerics::isValid(), NumberString::Min(), number_digits(), numberString(), requiredArgument(), and value.
Referenced by MemoryObject::createImage().
minus()
RexxObject * RexxInteger::minus (RexxInteger * other)
Subtract another object from this integer.
Parameters
other The other object.
Returns
The subtraction or unary minus result.
Definition at line 601 of file IntegerClass.cpp.
References integer_forward, isInteger(), Numerics::isValid(), new_integer(), number_digits(), OREF_NULL, and value.
Referenced by MemoryObject::createImage().
modulo()
RexxObject * RexxInteger::modulo (RexxInteger * other)
Integer object modulo operation. There is no universal agreement how to calculate modulo for floating point arguments or for negative divisors, so we restrict the dividend to a whole number and the divisor to a positive whole number.
Parameters
other The divisor object.
Returns
The module result.
Definition at line 859 of file IntegerClass.cpp.
References getValue(), integer_forward, IntegerOne, IntegerZero, isInteger(), Numerics::isValid(), new_integer(), number_digits(), OREF_NULL, and value.
Referenced by MemoryObject::createImage().
multiply()
RexxObject * RexxInteger::multiply (RexxInteger * other)
Multiply an integer by another object.
Parameters
other The other object.
Returns
The multiplication result.
Definition at line 650 of file IntegerClass.cpp.
References getValue(), integer_forward, IntegerZero, isInteger(), Numerics::isValid(), length_in_bits(), Numerics::maxBitsForDigits(), new_integer(), number_digits(), OREF_NULL, and value.
Referenced by MemoryObject::createImage().
notEqual()
RexxObject * RexxInteger::notEqual (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1279 of file IntegerClass.cpp.
References booleanObject(), comp(), TheNilObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
notOp()
RexxObject * RexxInteger::notOp ()
Perform the logical not of an integer object
Returns
The logical not on the object truth value.
Definition at line 1430 of file IntegerClass.cpp.
References booleanObject(), Error_Logical_value_method, and truthValue().
Referenced by MemoryObject::createImage().
numberString()
NumberString * RexxInteger::numberString () override virtual
Convert an integer into a number string.
Returns
The number string version of the integer.
Reimplemented from RexxInternalObject.
Definition at line 239 of file IntegerClass.cpp.
References new_numberstringFromWholenumber(), RexxString::numberString(), OREF_NULL, stringrep, and value.
Referenced by abs(), ceiling(), comp(), d2c(), d2x(), floor(), format(), Max(), Min(), round(), and trunc().
numberValue() [1/2]
bool RexxInteger::numberValue (wholenumber_t & result) override virtual
Convert an integer object into a whole number value using the default digits setting.
Parameters
result The returned result.
Returns
true if the number converts ok under the current digits setting. false for any conversion errors.
Reimplemented from RexxInternalObject.
Definition at line 280 of file IntegerClass.cpp.
References Numerics::MAX_WHOLENUMBER, and value.
numberValue() [2/2]
bool RexxInteger::numberValue (wholenumber_t & result, wholenumber_t digits) override virtual
Convert an integer object into a whole number value using the current digits setting.
Parameters
result The returned result.
digits The digits setting to apply to the conversion.
Returns
true if the number converts ok under the current digits setting. false for any conversion errors.
Reimplemented from RexxInternalObject.
Definition at line 302 of file IntegerClass.cpp.
References Numerics::isValid(), and value.
operator new()
void * RexxInteger::operator new (size_t size)
Create a new integer object
Parameters
size The size of the object.
Returns
The storage for a new integer object.
Definition at line 2050 of file IntegerClass.cpp.
References new_object(), RexxInternalObject::setHasNoReferences(), and T_Integer.
operatorNot()
RexxObject * RexxInteger::operatorNot (RexxObject * dummy)
Perform the logical not of an integer object
Returns
The logical not on the object truth value.
Definition at line 1441 of file IntegerClass.cpp.
References booleanObject(), Error_Logical_value_method, and truthValue().
orOp()
RexxObject * RexxInteger::orOp (RexxObject * other)
Logically OR two objects together
Parameters
other The OR operand
Returns
The logical result.
Definition at line 1470 of file IntegerClass.cpp.
References ARG_ONE, booleanObject(), Error_Logical_value_method, requiredArgument(), TheTrueObject, RexxInternalObject::truthValue(), and truthValue().
Referenced by MemoryObject::createImage().
plus()
RexxObject * RexxInteger::plus (RexxInteger * other)
Add an integer to another object.
Parameters
other The argument object.
Returns
The addition result.
Definition at line 552 of file IntegerClass.cpp.
References integer_forward, isInteger(), Numerics::isValid(), new_integer(), number_digits(), OREF_NULL, and value.
Referenced by MemoryObject::createImage().
power()
RexxObject * RexxInteger::power (RexxObject * other)
Integer power operation.
Parameters
other The power exponent
Returns
the exponent result.
Definition at line 898 of file IntegerClass.cpp.
References RexxInternalObject::getValue(), integer_forward, integerMinusOne, integerOne, integerZero, isInteger(), Numerics::isValid(), length_in_bits(), Numerics::maxBitsForDigits(), Numerics::maxValueForDigits(), new_integer(), number_digits(), OREF_NULL, Numerics::REXXINTEGER_DIGITS, RexxIntegerMaxBase, RexxIntegerMaxPower, and value.
Referenced by MemoryObject::createImage().
primitiveMakeString()
RexxString * RexxInteger::primitiveMakeString () override virtual
Low level processing for a REQUEST('STRING') request.
Returns
The string representation for this object.
Reimplemented from RexxInternalObject.
Definition at line 179 of file IntegerClass.cpp.
References Numerics::formatWholeNumber(), new_string(), OREF_NULL, setField, RexxInternalObject::setHasReferences(), stringrep, and value.
Referenced by stringValue().
processUnknown()
void RexxInteger::processUnknown (RexxErrorCodes error, RexxString * messageName, RexxObject ** arguments, size_t count, ProtectedObject & result) override virtual
Process an unknown message condition on an object. This is an optimized bypass for the Object default method that can bypass creating an array for the arguments and sending the UNKNOWN message to the object. Since many things funnel through the integer unknown method, this is a big optimization.
Parameters
messageName The target message name.
arguments The message arguments.
count The count of arguments.
result The return result protected object.
Reimplemented from RexxObject.
Definition at line 451 of file IntegerClass.cpp.
References RexxObject::messageSend(), and stringValue().
remainder()
RexxObject * RexxInteger::remainder (RexxInteger * other)
Integer object remainder operation.
Parameters
other The divider object.
Returns
The remainder result.
Definition at line 815 of file IntegerClass.cpp.
References getValue(), integer_forward, IntegerMinusOne, IntegerOne, IntegerZero, isInteger(), Numerics::isValid(), new_integer(), number_digits(), OREF_NULL, and value.
Referenced by MemoryObject::createImage().
round()
RexxObject * RexxInteger::round ()
Calculate the round value for a numeric value
Returns
The round value.
Definition at line 1749 of file IntegerClass.cpp.
References Numerics::isValid(), number_digits(), numberString(), NumberString::round(), and value.
Referenced by MemoryObject::createImage().
setString()
void RexxInteger::setString (RexxString * string)
Set the integer string value.
Parameters
string The new string value.
Definition at line 375 of file IntegerClass.cpp.
References setField, RexxInternalObject::setHasReferences(), and stringrep.
Referenced by RexxString::integerValue().
sign()
RexxObject * RexxInteger::sign ()
SIGN() function on an integer object
Returns
One, zero, or minus one.
Definition at line 1551 of file IntegerClass.cpp.
References IntegerMinusOne, IntegerOne, IntegerZero, and value.
Referenced by MemoryObject::createImage().
strictComp()
wholenumber_t RexxInteger::strictComp (RexxObject * other)
Compare the two values.
return <0 if other is greater than this return 0 if this equals other return >0 if this is greater than other
Parameters
other The other object for the comparison.
Returns
The comparison result.
Definition at line 1143 of file IntegerClass.cpp.
References ARG_ONE, RexxString::primitiveStrictComp(), requiredArgument(), and stringValue().
Referenced by strictGreaterOrEqual(), strictGreaterThan(), strictLessOrEqual(), and strictLessThan().
strictEqual()
RexxObject * RexxInteger::strictEqual (RexxObject * other)
Perform the primitive level "==" compare, including the hash value processing.
Parameters
other The other comparison result.
Returns
.true or .false
Definition at line 1235 of file IntegerClass.cpp.
References booleanObject(), strictEquality(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
strictEquality()
bool RexxInteger::strictEquality (RexxObject * other)
Compare the two values, testing just for strict equality
Parameters
other The other object for the comparison.
Returns
The comparison result.
Definition at line 1162 of file IntegerClass.cpp.
References ARG_ONE, isInteger(), RexxString::primitiveIsEqual(), requiredArgument(), stringValue(), and value.
Referenced by strictEqual(), and strictNotEqual().
strictGreaterOrEqual()
RexxObject * RexxInteger::strictGreaterOrEqual (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1398 of file IntegerClass.cpp.
References booleanObject(), strictComp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
strictGreaterThan()
RexxObject * RexxInteger::strictGreaterThan (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1364 of file IntegerClass.cpp.
References booleanObject(), strictComp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
strictLessOrEqual()
RexxObject * RexxInteger::strictLessOrEqual (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1415 of file IntegerClass.cpp.
References booleanObject(), strictComp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
strictLessThan()
RexxObject * RexxInteger::strictLessThan (RexxObject * other)
A compare operation
Parameters
other The other comparison object
Returns
.true or .false
Definition at line 1381 of file IntegerClass.cpp.
References booleanObject(), strictComp(), TheFalseObject, and TheNilObject.
Referenced by MemoryObject::createImage().
strictNotEqual()
RexxObject * RexxInteger::strictNotEqual (RexxObject * other)
Definition at line 1245 of file IntegerClass.cpp.
References booleanObject(), strictEquality(), TheNilObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
stringSize()
size_t RexxInteger::stringSize () inline
Definition at line 147 of file IntegerClass.hpp.
References value.
stringValue()
RexxString * RexxInteger::stringValue () override virtual
Return a string value for an integer object.
Returns
The object string value.
Reimplemented from RexxObject.
Definition at line 206 of file IntegerClass.cpp.
References primitiveMakeString().
Referenced by compareTo(), concat(), concatBlank(), getHashValue(), hasMethod(), RexxIntegerClass::initCache(), instanceMethod(), instanceMethods(), isEqual(), isInstanceOf(), liveGeneral(), makeArray(), makeString(), processUnknown(), strictComp(), and strictEquality().
trunc()
RexxObject * RexxInteger::trunc (RexxObject * decimals)
Act as a front end for the actual TRUNC REXX method
Parameters
decimals The number of decimals to truncate to.
Returns
The truncation result.
Definition at line 1690 of file IntegerClass.cpp.
References getValue(), isInteger(), Numerics::isValid(), number_digits(), numberString(), OREF_NULL, NumberString::trunc(), and value.
Referenced by MemoryObject::createImage().
truthValue()
bool RexxInteger::truthValue (RexxErrorCodes errorcode) override virtual
Determine the truth value of an integer object
Parameters
errorcode The error code to issue.
Returns
either true or false, based on the validation.
Reimplemented from RexxInternalObject.
Definition at line 389 of file IntegerClass.cpp.
References reportException(), and value.
Referenced by andOp(), choiceRexx(), notOp(), operatorNot(), orOp(), and xorOp().
unsignedNumberValue() [1/2]
bool RexxInteger::unsignedNumberValue (size_t & result) override virtual
Convert an integer object into an unsigned whole number value using the default digits setting.
Parameters
result The returned result.
Returns
true if the number converts ok under the current digits setting. false for any conversion errors.
Reimplemented from RexxInternalObject.
Definition at line 323 of file IntegerClass.cpp.
References Numerics::MAX_WHOLENUMBER, and wholeNumber().
unsignedNumberValue() [2/2]
bool RexxInteger::unsignedNumberValue (size_t & result, wholenumber_t digits) override virtual
Convert an integer object into an unsigned whole number value using the current digits setting.
Parameters
result The returned result.
digits The digits setting to apply to the conversion.
Returns
true if the number converts ok under the current digits setting. false for any conversion errors.
Reimplemented from RexxInternalObject.
Definition at line 345 of file IntegerClass.cpp.
References Numerics::isValid(), value, and wholeNumber().
wholeNumber()
wholenumber_t RexxInteger::wholeNumber () inline
Definition at line 146 of file IntegerClass.hpp.
References value.
Referenced by doubleValue(), and unsignedNumberValue().
xorOp()
RexxObject * RexxInteger::xorOp (RexxObject * other)
Logically XOR two objects together
Parameters
other The XOR operand
Returns
The logical result.
Definition at line 1485 of file IntegerClass.cpp.
References ARG_ONE, booleanObject(), Error_Logical_value_method, requiredArgument(), RexxInternalObject::truthValue(), and truthValue().
Referenced by MemoryObject::createImage().
Member Data Documentation
classInstance
RexxIntegerClass * RexxInteger::classInstance = OREF_NULL static
Definition at line 152 of file IntegerClass.hpp.
falseObject
RexxInteger * RexxInteger::falseObject = OREF_NULL static
Definition at line 154 of file IntegerClass.hpp.
integerEight
RexxInteger * RexxInteger::integerEight = OREF_NULL static
Definition at line 166 of file IntegerClass.hpp.
integerFive
RexxInteger * RexxInteger::integerFive = OREF_NULL static
Definition at line 163 of file IntegerClass.hpp.
integerFour
RexxInteger * RexxInteger::integerFour = OREF_NULL static
Definition at line 162 of file IntegerClass.hpp.
integerMinusOne
RexxInteger * RexxInteger::integerMinusOne = OREF_NULL static
Definition at line 168 of file IntegerClass.hpp.
Referenced by power().
integerNine
RexxInteger * RexxInteger::integerNine = OREF_NULL static
Definition at line 167 of file IntegerClass.hpp.
integerOne
RexxInteger * RexxInteger::integerOne = OREF_NULL static
Definition at line 159 of file IntegerClass.hpp.
Referenced by power().
integerSeven
RexxInteger * RexxInteger::integerSeven = OREF_NULL static
Definition at line 165 of file IntegerClass.hpp.
integerSix
RexxInteger * RexxInteger::integerSix = OREF_NULL static
Definition at line 164 of file IntegerClass.hpp.
integerThree
RexxInteger * RexxInteger::integerThree = OREF_NULL static
Definition at line 161 of file IntegerClass.hpp.
integerTwo
RexxInteger * RexxInteger::integerTwo = OREF_NULL static
Definition at line 160 of file IntegerClass.hpp.
integerZero
RexxInteger * RexxInteger::integerZero = OREF_NULL static
Definition at line 158 of file IntegerClass.hpp.
Referenced by power().
nullPointer
RexxInteger * RexxInteger::nullPointer = OREF_NULL static
Definition at line 156 of file IntegerClass.hpp.
operatorMethods
PCPPM RexxInteger::operatorMethods static
Definition at line 151 of file IntegerClass.hpp.
stringrep
RexxString* RexxInteger::stringrep protected
Definition at line 172 of file IntegerClass.hpp.
Referenced by copyIntoTail(), flatten(), getStringrep(), live(), liveGeneral(), numberString(), primitiveMakeString(), and setString().
trueObject
RexxInteger * RexxInteger::trueObject = OREF_NULL static
Definition at line 155 of file IntegerClass.hpp.
validMaxWhole
wholenumber_t RexxInteger::validMaxWhole[] static protected
Definition at line 175 of file IntegerClass.hpp.
value
wholenumber_t RexxInteger::value protected
Definition at line 173 of file IntegerClass.hpp.
Referenced by abs(), ceiling(), comp(), copyIntoTail(), d2c(), d2x(), divide(), floor(), getValue(), integerDivide(), isEqual(), logicalValue(), Max(), Min(), minus(), modulo(), multiply(), numberString(), numberValue(), plus(), power(), primitiveMakeString(), remainder(), RexxInteger(), round(), sign(), strictEquality(), stringSize(), trunc(), truthValue(), unsignedNumberValue(), and wholeNumber().
The documentation for this class was generated from the following files:
IntegerClass.hpp
IntegerClass.cpp