ooRexx: ListClass Class Reference
ListClass Class Reference
#include <ListClass.hpp>
Public Member Functions
void * operator new (size_t)
ListClass (RESTORETYPE restoreType)
ListClass (size_t capacity=DefaultListSize)
ListClass (bool fromRexx)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
ArrayClass * makeArray () override
ArrayClass * requestArray () override
void put (RexxInternalObject *value, size_t index)
RexxInternalObject * get (size_t index)
ListClass * section (size_t index, size_t count)
size_t insert (RexxInternalObject *value, size_t insertionPoint)
size_t addLast (RexxInternalObject *value)
size_t addFirst (RexxInternalObject *value)
size_t append (RexxInternalObject *value)
RexxInternalObject * remove (size_t index)
RexxInternalObject * firstItem ()
RexxInternalObject * lastItem ()
size_t firstIndex ()
size_t lastIndex ()
size_t nextIndex (size_t index)
size_t previousIndex (size_t _index)
bool hasIndex (size_t index)
bool hasItem (RexxInternalObject *target)
ArrayClass * allItems ()
void empty ()
bool isEmpty ()
ArrayClass * allIndexes ()
size_t getIndex (RexxInternalObject *target)
RexxInternalObject * removeItem (RexxInternalObject *target)
SupplierClass * supplier ()
size_t items ()
ArrayClass * weakReferenceArray ()
RexxObject * initRexx (RexxObject *initialSize)
RexxInternalObject * putRexx (RexxObject *value, RexxObject *argIndex)
RexxInternalObject * getRexx (RexxObject *argIndex)
RexxObject * sectionRexx (RexxObject *argIndex, RexxObject *count)
RexxObject * insertRexx (RexxObject *value, RexxObject *index)
RexxObject * appendRexx (RexxObject *value)
RexxObject * removeRexx (RexxObject *index)
RexxObject * firstItemRexx ()
RexxObject * lastItemRexx ()
RexxObject * firstRexx ()
RexxObject * lastRexx ()
RexxObject * nextRexx (RexxObject *index)
RexxObject * previousRexx (RexxObject *index)
RexxObject * hasIndexRexx (RexxObject *index)
RexxObject * emptyRexx ()
RexxObject * isEmptyRexx ()
RexxObject * indexRexx (RexxObject *target)
RexxInternalObject * removeItemRexx (RexxObject *target)
RexxObject * itemsRexx ()
RexxObject * hasItemRexx (RexxObject *target)
ListClass * newRexx (RexxObject **, size_t)
ListClass * ofRexx (RexxObject **, size_t)
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
HashCode hash () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
static const size_t DefaultListSize = 8
static const size_t ExpansionDoubleLimit = 2000
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Member Functions
void initialize (size_t capacity=DefaultListSize)
ListContents::ItemLink validateIndex (RexxObject *index, size_t position)
ListContents::ItemLink validateInsertionIndex (RexxObject *index, size_t position)
ListContents::ItemLink requiredIndex (RexxObject *index, size_t position)
void expandContents ()
void expandContents (size_t capacity)
void ensureCapacity (size_t delta)
void checkFull ()
RexxObject * indexObject (ListContents::ItemLink index)
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Protected Attributes
ListContents * contents
Friends
class ListTable
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Detailed Description
Definition at line 51 of file ListClass.hpp.
Constructor & Destructor Documentation
ListClass() [1/3]
ListClass::ListClass (RESTORETYPE restoreType) inline
Definition at line 57 of file ListClass.hpp.
Referenced by newRexx(), and section().
ListClass() [2/3]
ListClass::ListClass (size_t capacity = DefaultListSize)
construct a list object with the given size.
Parameters
capacity The required capacity.
Definition at line 86 of file ListClass.cpp.
References initialize().
ListClass() [3/3]
ListClass::ListClass (bool fromRexx) inline
Definition at line 59 of file ListClass.hpp.
Member Function Documentation
addFirst()
size_t ListClass::addFirst (RexxInternalObject * value)
Add a value to the front of the list.
Parameters
value The value to add.
Returns
The index of the new item.
Definition at line 502 of file ListClass.cpp.
References ListContents::AtBeginning, checkFull(), contents, and ListContents::insert().
Referenced by RexxClass::addSubClass().
addLast()
size_t ListClass::addLast (RexxInternalObject * value)
Add an object to the end of the list.
Parameters
value The value to add.
Returns
The insertion index.
Definition at line 486 of file ListClass.cpp.
References ListContents::AtEnd, checkFull(), contents, and ListContents::insert().
allIndexes()
ArrayClass * ListClass::allIndexes ()
Return an array containing all elements contained in the list, in sorted order.
Returns
An array with the list elements.
Definition at line 832 of file ListClass.cpp.
References ListContents::allIndexes(), and contents.
Referenced by MemoryObject::createImage().
allItems()
ArrayClass * ListClass::allItems ()
Return an array containing all elements contained in the list, in sorted order.
Returns
An array with the list elements.
Definition at line 777 of file ListClass.cpp.
References ListContents::allItems(), and contents.
Referenced by MemoryObject::createImage(), makeArray(), and requestArray().
append()
size_t ListClass::append (RexxInternalObject * value)
Append an item after the last item in the list.
Parameters
value The value to append.
Returns
The index of the appended item.
Definition at line 518 of file ListClass.cpp.
References checkFull(), contents, and ListContents::insertAtEnd().
Referenced by appendRexx(), and Activity::generateProgramInformation().
appendRexx()
RexxObject * ListClass::appendRexx (RexxObject * value)
The rexx version of the append method.
Parameters
value The value to append.
Returns
An object version of the index.
Definition at line 534 of file ListClass.cpp.
References append(), ARG_ONE, new_integer(), and requiredArgument().
Referenced by MemoryObject::createImage().
checkFull()
void ListClass::checkFull () protected
If the contents think it is time to expand, then increase the contents size.
Definition at line 317 of file ListClass.cpp.
References contents, expandContents(), and ListContents::isFull().
Referenced by addFirst(), addLast(), append(), insert(), and put().
copy()
RexxInternalObject * ListClass::copy () override virtual
Create a copy of a list table item.
Returns
The object copy.
Reimplemented from RexxObject.
Definition at line 176 of file ListClass.cpp.
References contents, RexxInternalObject::copy(), and RexxObject::copy().
createInstance()
void ListClass::createInstance () static
Create initial class object at bootstrap time.
Definition at line 62 of file ListClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
empty()
void ListClass::empty ()
Low-level API for emptying a list.
Definition at line 798 of file ListClass.cpp.
References contents, and ListContents::empty().
Referenced by emptyRexx().
emptyRexx()
RexxObject * ListClass::emptyRexx ()
Empty all of the items from a list.
Returns
No return value.
Definition at line 788 of file ListClass.cpp.
References empty().
Referenced by MemoryObject::createImage().
ensureCapacity()
void ListClass::ensureCapacity (size_t delta) protected
Ensure that the collection has sufficient space for a mass incoming addition.
Parameters
delta The number of entries we wish to add.
Definition at line 299 of file ListClass.cpp.
References ListContents::capacity(), contents, expandContents(), ExpansionDoubleLimit, and ListContents::hasCapacity().
expandContents() [1/2]
void ListClass::expandContents () protected
Expand the contents of a collection. We try for double the size.
Definition at line 268 of file ListClass.cpp.
References ListContents::capacity(), contents, and ExpansionDoubleLimit.
Referenced by checkFull(), and ensureCapacity().
expandContents() [2/2]
void ListClass::expandContents (size_t capacity) protected
Expand the contents of a collection to a given bucket capacity.
Definition at line 282 of file ListClass.cpp.
References contents, ListContents::mergeInto(), and setField.
firstIndex()
size_t ListClass::firstIndex ()
Low level access to the firstItem function.
Returns
The first index in the list or NoMore if the list is empty.
Definition at line 630 of file ListClass.cpp.
References contents, and ListContents::firstIndex().
Referenced by firstRexx().
firstItem()
RexxInternalObject * ListClass::firstItem ()
Low level access to the firstItem function.
Returns
The first item in the list or OREF_NULL if the list is empty.
Definition at line 584 of file ListClass.cpp.
References contents, and ListContents::getFirstItem().
Referenced by firstItemRexx().
firstItemRexx()
RexxObject * ListClass::firstItemRexx ()
Return the first item in the list.
Returns
The item, or .nil if the list is empty.
Definition at line 573 of file ListClass.cpp.
References firstItem(), and resultOrNil().
Referenced by MemoryObject::createImage().
firstRexx()
RexxObject * ListClass::firstRexx ()
Get the index of the first item in the list.
Returns
The index value, or the .nil if the list is empty.
Definition at line 618 of file ListClass.cpp.
References firstIndex(), and indexObject().
Referenced by MemoryObject::createImage().
flatten()
void ListClass::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxObject.
Definition at line 160 of file ListClass.cpp.
References cleanUpFlatten, contents, flattenRef, and setUpFlatten.
get()
RexxInternalObject * ListClass::get (size_t index)
Low level API for getting a value from the list
Parameters
index The index position (non-validated).
Definition at line 392 of file ListClass.cpp.
References contents, and ListContents::get().
Referenced by getRexx().
getIndex()
size_t ListClass::getIndex (RexxInternalObject * target)
Get the index associated with a value stored in the list.
Parameters
target The search item.
Returns
The index, or NoMore if no matching item is found.
Definition at line 863 of file ListClass.cpp.
References contents, and ListContents::getIndex().
Referenced by indexRexx().
getRexx()
RexxInternalObject * ListClass::getRexx (RexxObject * argIndex)
Get a value from the list at the provided index.
Parameters
index The target index.
Returns
returns nothing.
Definition at line 379 of file ListClass.cpp.
References ARG_TWO, get(), resultOrNil(), and validateIndex().
Referenced by MemoryObject::createImage().
hasIndex()
bool ListClass::hasIndex (size_t index)
Low-level test of index existance.
Parameters
index The target index.
Returns
true if the index exists, false otherwise.
Definition at line 743 of file ListClass.cpp.
References contents, and ListContents::isIndexValid().
Referenced by hasIndexRexx().
hasIndexRexx()
RexxObject * ListClass::hasIndexRexx (RexxObject * argIndex)
Test if the list has a given index value.
Parameters
index The target index.
Returns
True if this is a valid index in this list, false otherwise.
Definition at line 729 of file ListClass.cpp.
References ARG_ONE, booleanObject(), hasIndex(), and validateIndex().
Referenced by MemoryObject::createImage().
hasItem()
bool ListClass::hasItem (RexxInternalObject * target)
Test of the list contains a given target object.
Parameters
target The target object.
Returns
true if the object is found, false otherwise.
Definition at line 892 of file ListClass.cpp.
References contents, and ListContents::hasItem().
hasItemRexx()
RexxObject * ListClass::hasItemRexx (RexxObject * target)
Tests whether there is an object with the given value in the list.
Parameters
target The target value.
Returns
.true if there is a match, .false otherwise.
Definition at line 877 of file ListClass.cpp.
References ARG_ONE, booleanObject(), contents, ListContents::hasItem(), and requiredArgument().
Referenced by MemoryObject::createImage().
indexObject()
RexxObject * ListClass::indexObject (ListContents::ItemLink index) protected
Utility method for formatting an index value into an object.
Parameters
index The index to return.
Returns
Either an integer version of the index or TheNilObject if the index is out of bounds.
Definition at line 333 of file ListClass.cpp.
References new_integer(), ListContents::NoMore, and TheNilObject.
Referenced by firstRexx(), indexRexx(), lastRexx(), nextRexx(), and previousRexx().
indexRexx()
RexxObject * ListClass::indexRexx (RexxObject * target)
Return the index of the first item with a matching value in the list. Returns .nil if the object is not found.
Parameters
target The target object.
Returns
The index of the item, or .nil.
Definition at line 846 of file ListClass.cpp.
References ARG_ONE, getIndex(), indexObject(), and requiredArgument().
Referenced by MemoryObject::createImage().
initialize()
void ListClass::initialize (size_t capacity = DefaultListSize) protected
Initialize the list contents, either directly from the low level constructor or from the INIT method.
Parameters
capacity The requested capacity.
Definition at line 117 of file ListClass.cpp.
References contents, DefaultListSize, and OREF_NULL.
Referenced by initRexx(), and ListClass().
initRexx()
RexxObject * ListClass::initRexx (RexxObject * initialSize)
The init method for this class. This does delayed initialization of this object until a INIT message is received during initialization.
Parameters
initialSize The initial list size (optional)
Returns
Always returns nothing
Definition at line 102 of file ListClass.cpp.
References ARG_ONE, DefaultListSize, initialize(), optionalLengthArgument(), and OREF_NULL.
insert()
size_t ListClass::insert (RexxInternalObject * value, size_t insertionPoint)
Primitive insert operation to a List.
Parameters
insertionPoint The non-validated insertion index. NoLink means add to the list end.
Returns
The index of the added item.
Definition at line 470 of file ListClass.cpp.
References checkFull(), contents, and ListContents::insert().
Referenced by insertRexx().
insertRexx()
RexxObject * ListClass::insertRexx (RexxObject * value, RexxObject * index)
Add a new element to the list at the given insertion point. TheNilObject indicates it should be added to the list end
Parameters
value The value to insert
index The index value for the insertion point.
Returns
The index for the inserted item.
Definition at line 451 of file ListClass.cpp.
References ARG_TWO, insert(), new_integer(), and validateInsertionIndex().
Referenced by MemoryObject::createImage().
isEmpty()
bool ListClass::isEmpty ()
Test if a list is empty.
Returns
True if the list is empty, false otherwise
Definition at line 820 of file ListClass.cpp.
References contents, and ListContents::isEmpty().
Referenced by isEmptyRexx().
isEmptyRexx()
RexxObject * ListClass::isEmptyRexx ()
Test if a list is empty.
Returns
True if the list is empty, false otherwise
Definition at line 809 of file ListClass.cpp.
References booleanObject(), and isEmpty().
Referenced by MemoryObject::createImage().
items()
size_t ListClass::items ()
Low-level items function.
Returns
The count of items in the list.
Definition at line 954 of file ListClass.cpp.
References contents, and ListContents::items().
Referenced by itemsRexx().
itemsRexx()
RexxObject * ListClass::itemsRexx ()
The Rexx version of the list items() method.
Returns
The count of items in the list.
Definition at line 943 of file ListClass.cpp.
References items(), and new_integer().
Referenced by MemoryObject::createImage().
lastIndex()
size_t ListClass::lastIndex ()
Low level access to the firstItem function.
Returns
The last index in the list or NoMore if the list is empty.
Definition at line 653 of file ListClass.cpp.
References contents, and ListContents::lastIndex().
Referenced by lastRexx().
lastItem()
RexxInternalObject * ListClass::lastItem ()
Low level access to the lastItem function.
Returns
The last item in the list or OREF_NULL if the list is empty.
Definition at line 607 of file ListClass.cpp.
References contents, and ListContents::getLastItem().
Referenced by lastItemRexx().
lastItemRexx()
RexxObject * ListClass::lastItemRexx ()
Rexx access to the first item of the list.
Returns
The first item, or .nil if the list is empty.
Definition at line 595 of file ListClass.cpp.
References lastItem(), and resultOrNil().
Referenced by MemoryObject::createImage().
lastRexx()
RexxObject * ListClass::lastRexx ()
Get the index of the last item in the list.
Returns
The index value, or the .nil if the list is empty.
Definition at line 641 of file ListClass.cpp.
References indexObject(), and lastIndex().
Referenced by MemoryObject::createImage().
live()
void ListClass::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxObject.
Definition at line 136 of file ListClass.cpp.
References contents, and memory_mark.
liveGeneral()
void ListClass::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxObject.
Definition at line 148 of file ListClass.cpp.
References contents, and memory_mark_general.
makeArray()
ArrayClass * ListClass::makeArray () override virtual
Process a request to convert this list to an array.
Returns
An array containing all of the list items, in the current order.
Reimplemented from RexxInternalObject.
Definition at line 765 of file ListClass.cpp.
References allItems().
Referenced by Activity::display().
newRexx()
ListClass * ListClass::newRexx (RexxObject ** init_args, size_t argCount)
Rexx method for allocating a List item.
Parameters
init_args The new args.
argCount The count of arguments.
Returns
A new List instance.
Definition at line 980 of file ListClass.cpp.
References RexxClass::completeNewObject(), and ListClass().
Referenced by MemoryObject::createImage(), and ofRexx().
nextIndex()
size_t ListClass::nextIndex (size_t index)
A low-level next() method for internal usage. This works directly off the index values without needing to create object instances. This is critical for some of the internal data structures implemented as lists.
Parameters
index The target item index.
Returns
The index of the next item, or NoMore if there is no next item.
Definition at line 698 of file ListClass.cpp.
References contents, and ListContents::nextIndex().
Referenced by nextRexx().
nextRexx()
RexxObject * ListClass::nextRexx (RexxObject * argIndex)
Step from a given index to the next element in the list.
Parameters
index The starting index
Returns
The indext of the next item, or .nil if their is no next item.
Definition at line 666 of file ListClass.cpp.
References ARG_ONE, indexObject(), nextIndex(), and validateIndex().
Referenced by MemoryObject::createImage().
ofRexx()
ListClass * ListClass::ofRexx (RexxObject ** args, size_t argCount)
Create a list item and populate with the argument items.
Parameters
args Pointer to the arguments.
argCount The number of arguments.
Returns
The populated list object.
Definition at line 1010 of file ListClass.cpp.
References Error_Incorrect_method_noarg, newRexx(), OREF_NULL, and reportException().
Referenced by MemoryObject::createImage().
operator new()
void * ListClass::operator new (size_t size)
Create a new list object
Parameters
size the size of the object.
Returns
Storage for creating the object.
Definition at line 75 of file ListClass.cpp.
References new_object(), and T_List.
previousIndex()
size_t ListClass::previousIndex (size_t index)
A low-level previous() method for internal usage. This works directly off the index values without needing to create object instances. This is critical for some of the internal data structures implemented as lists.
Parameters
_index The target item index.
Returns
The index of the previous item, or NoMore if there is no previous item.
Definition at line 715 of file ListClass.cpp.
References contents, and ListContents::previousIndex().
Referenced by previousRexx().
previousRexx()
RexxObject * ListClass::previousRexx (RexxObject * argIndex)
Step from a given index to the next element in the list.
Parameters
index The starting index
Returns
The indext of the next item, or .nil if their is no next item.
Definition at line 680 of file ListClass.cpp.
References ARG_ONE, indexObject(), previousIndex(), and validateIndex().
Referenced by MemoryObject::createImage().
put()
void ListClass::put (RexxInternalObject * value, size_t index)
Low level API for putting a value into the list.
Parameters
value The value to put.
index The index position (non-validated).
Definition at line 363 of file ListClass.cpp.
References checkFull(), contents, and ListContents::put().
Referenced by putRexx().
putRexx()
RexxInternalObject * ListClass::putRexx (RexxObject * value, RexxObject * argIndex)
Put a value into the list, replacing the existing value.
Parameters
value The value to insert.
index The target index.
Returns
returns nothing.
Definition at line 347 of file ListClass.cpp.
References ARG_TWO, OREF_NULL, put(), and requiredIndex().
Referenced by MemoryObject::createImage().
remove()
RexxInternalObject * ListClass::remove (size_t index)
The low-level remove API
Parameters
index The target index to remove.
Returns
The removed object, or OREF_NULL if this index does not exist.
Definition at line 562 of file ListClass.cpp.
References contents, and ListContents::remove().
Referenced by removeRexx().
removeItem()
RexxInternalObject * ListClass::removeItem (RexxInternalObject * target)
Remove an Item from the list.
Parameters
target The search item.
Returns
The existing item.
Definition at line 921 of file ListClass.cpp.
References contents, and ListContents::removeItem().
Referenced by removeItemRexx(), and RexxClass::removeSubclass().
removeItemRexx()
RexxInternalObject * ListClass::removeItemRexx (RexxObject * target)
Removes an item from the collection.
Parameters
target The target value.
Returns
The target item.
Definition at line 905 of file ListClass.cpp.
References ARG_ONE, removeItem(), requiredArgument(), and resultOrNil().
Referenced by MemoryObject::createImage().
removeRexx()
RexxObject * ListClass::removeRexx (RexxObject * argIndex)
Remove an item at the given index from the list.
Parameters
index The index to remove.
Returns
The removed item.
Definition at line 547 of file ListClass.cpp.
References ARG_ONE, remove(), resultOrNil(), and validateIndex().
Referenced by MemoryObject::createImage().
requestArray()
ArrayClass * ListClass::requestArray () override virtual
Process a request to convert this list to an array.
Returns
An array containing all of the list items, in the current order.
Reimplemented from RexxInternalObject.
Definition at line 754 of file ListClass.cpp.
References allItems().
requiredIndex()
ListContents::ItemLink ListClass::requiredIndex (RexxObject * index, size_t position) protected
Convert an argument value into an index position that MUST be in the table.
Parameters
index The argument index value.
position The argument position for the index.
Returns
The converted index position.
Definition at line 251 of file ListClass.cpp.
References Error_Incorrect_method_index, ListContents::NoLink, reportException(), and validateIndex().
Referenced by putRexx(), sectionRexx(), and validateInsertionIndex().
section()
ListClass * ListClass::section (size_t index, size_t count)
Low-level section method for a list.
Parameters
index The starting index (non-validated)
count The count of items to include.
Returns
A new list item containing the requested items.
Definition at line 424 of file ListClass.cpp.
References contents, ListContents::get(), ListClass(), ListContents::nextIndex(), and ListContents::NoMore.
Referenced by sectionRexx().
sectionRexx()
RexxObject * ListClass::sectionRexx (RexxObject * argIndex, RexxObject * count)
Snip out a section of the list.
Parameters
argIndex The starting list index.
count The count of items to include in the section.
Returns
A new list object filled with the subset items.
Definition at line 406 of file ListClass.cpp.
References ARG_ONE, ARG_TWO, counter(), optionalLengthArgument(), requiredIndex(), section(), and SIZE_MAX.
Referenced by MemoryObject::createImage().
supplier()
SupplierClass * ListClass::supplier ()
Return a supplier for iterating over the list contents.
Returns
A supplier for the current list.
Definition at line 932 of file ListClass.cpp.
References contents, and ListContents::supplier().
Referenced by MemoryObject::createImage().
validateIndex()
ListContents::ItemLink ListClass::validateIndex (RexxObject * index, size_t position) protected
Convert a provided index value into the target item in the contents.
Parameters
index The provided index.
position The argument position
Returns
The validated location of the targetted entry.
Definition at line 195 of file ListClass.cpp.
References Numerics::ARGUMENT_DIGITS, contents, Error_Incorrect_method_index, ListContents::isIndexValid(), ListContents::NoLink, reportException(), requiredArgument(), and RexxInternalObject::unsignedNumberValue().
Referenced by getRexx(), hasIndexRexx(), nextRexx(), previousRexx(), removeRexx(), and requiredIndex().
validateInsertionIndex()
ListContents::ItemLink ListClass::validateInsertionIndex (RexxObject * index, size_t position) protected
Convert a provided index value into the target item in the contents. For this version, .nil is a valid index and is indicated by returning NoLink. Otherwise, this must point to a real value
Parameters
index The provided index.
position The argument position
Returns
The validated location of the targetted entry.
Definition at line 226 of file ListClass.cpp.
References ListContents::AtBeginning, ListContents::AtEnd, OREF_NULL, requiredIndex(), and TheNilObject.
Referenced by insertRexx().
weakReferenceArray()
ArrayClass * ListClass::weakReferenceArray ()
Scan the list and dereference the weak references, returning an array of all of the active objects.
Returns
An array with the active references.
Definition at line 966 of file ListClass.cpp.
References contents, and ListContents::weakReferenceArray().
Referenced by RexxClass::getSubClasses().
Friends And Related Function Documentation
ListTable
friend class ListTable friend
Definition at line 53 of file ListClass.hpp.
Member Data Documentation
classInstance
RexxClass * ListClass::classInstance = OREF_NULL static
Definition at line 124 of file ListClass.hpp.
contents
ListContents* ListClass::contents protected
Definition at line 146 of file ListClass.hpp.
Referenced by addFirst(), addLast(), allIndexes(), allItems(), append(), checkFull(), copy(), empty(), ensureCapacity(), expandContents(), firstIndex(), firstItem(), flatten(), get(), getIndex(), hasIndex(), hasItem(), hasItemRexx(), initialize(), insert(), isEmpty(), items(), lastIndex(), lastItem(), live(), liveGeneral(), nextIndex(), previousIndex(), put(), remove(), removeItem(), section(), supplier(), validateIndex(), and weakReferenceArray().
DefaultListSize
const size_t ListClass::DefaultListSize = 8 static
Definition at line 127 of file ListClass.hpp.
Referenced by initialize(), and initRexx().
ExpansionDoubleLimit
const size_t ListClass::ExpansionDoubleLimit = 2000 static
Definition at line 130 of file ListClass.hpp.
Referenced by ensureCapacity(), and expandContents().
The documentation for this class was generated from the following files:
ListClass.hpp
ListClass.cpp