ooRexx: MethodClass Class Reference
MethodClass Class Reference
#include <MethodClass.hpp>
Public Member Functions
void * operator new (size_t)
MethodClass (RexxString *name, BaseCode *_code)
MethodClass (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
void run (Activity *, RexxObject *, RexxString *, RexxObject **, size_t, ProtectedObject &)
MethodClass * newScope (RexxClass *)
void setScope (RexxClass *)
RexxObject * setUnguardedRexx ()
RexxObject * setGuardedRexx ()
RexxObject * setPrivateRexx ()
RexxObject * setProtectedRexx ()
RexxObject * setSecurityManager (RexxObject *)
RexxObject * isGuardedRexx ()
RexxObject * isPrivateRexx ()
RexxObject * isPackageRexx ()
RexxObject * isProtectedRexx ()
RexxObject * isAbstractRexx ()
RexxObject * isConstantRexx ()
RexxObject * isAttributeRexx ()
bool isGuarded ()
bool isPrivate ()
bool isProtected ()
bool isPackageScope ()
bool isSpecial ()
bool isConstant ()
bool isAttribute ()
bool isAbstract ()
void setUnguarded ()
void setGuarded ()
void setPrivate ()
void setPackageScope ()
void setProtected ()
void setUnprotected ()
void setPublic ()
void setConstant ()
void setAttribute ()
void setAbstract ()
void setAttribute (bool v)
void setAttributes (AccessFlag access, ProtectedFlag _protected, GuardFlag _guarded)
RexxClass * getScope ()
RexxString * getScopeName ()
RexxObject * getScopeRexx ()
bool isScope (RexxClass *s)
BaseCode * getCode ()
MethodClass * newRexx (RexxObject **, size_t)
MethodClass * newFileRexx (RexxString *, PackageClass *)
MethodClass * loadExternalMethod (RexxString *methodName, RexxString *descriptor)
bool isSamePackage (PackageClass *p)
Public Member Functions inherited from BaseExecutable
RexxInternalObject * copy () override
PackageClass * getPackageObject ()
BaseCode * getCode ()
ArrayClass * getSource ()
PackageClass * getPackage ()
ArrayClass * source ()
RexxClass * findClass (RexxString *className)
BaseExecutable * setPackageObject (PackageClass *s)
RexxString * getName ()
ProgramSource * detachSource ()
void attachSource (ProgramSource *s)
StringTable * getAnnotations ()
RexxString * getAnnotation (RexxString *name)
RexxObject * getAnnotationRexx (RexxObject *name)
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
HashCode hash () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Static Public Member Functions
static MethodClass * restore (RexxString *fileName, BufferClass *buffer)
static MethodClass * newMethodObject (RexxString *, RexxObject *, RexxClass *, const char *)
static void createInstance ()
Static Public Member Functions inherited from BaseExecutable
static ArrayClass * processExecutableSource (RexxObject *source, const char *position)
static void processNewExecutableArgs (RexxObject **&init_args, size_t &argCount, RexxString *&name, Protected< ArrayClass > &sourceArray, PackageClass *&sourceContext)
static void processNewFileExecutableArgs (RexxString *&filename, PackageClass *&sourceContext)
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Types
enum MethodFlags {
PRIVATE_FLAG , UNGUARDED_FLAG , PROTECTED_FLAG , ATTRIBUTE_METHOD ,
CONSTANT_METHOD , ABSTRACT_METHOD , PACKAGE_FLAG
}
Protected Attributes
FlagSet< MethodFlags, 32 > methodFlags
RexxClass * scope
Protected Attributes inherited from BaseExecutable
RexxString * executableName
BaseCode * code
StringTable * annotations
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Base class for method object. This is the frontend for The different types of executable code objects.
Definition at line 85 of file MethodClass.hpp.
Member Enumeration Documentation
MethodFlags
enum MethodClass::MethodFlags protected
Enumerator
PRIVATE_FLAG
UNGUARDED_FLAG
PROTECTED_FLAG
ATTRIBUTE_METHOD
CONSTANT_METHOD
ABSTRACT_METHOD
PACKAGE_FLAG
Definition at line 156 of file MethodClass.hpp.
Constructor & Destructor Documentation
MethodClass() [1/2]
MethodClass::MethodClass (RexxString * name, BaseCode * codeObj)
Initialize a Routine object from a generated code object. Generally used for routines generated from ::METHOD directives.
Parameters
name The routine name.
codeObj The associated code object.
Definition at line 99 of file MethodClass.cpp.
References BaseExecutable::code, and BaseExecutable::executableName.
Referenced by loadExternalMethod(), and restore().
MethodClass() [2/2]
MethodClass::MethodClass (RESTORETYPE restoreType) inline
Definition at line 91 of file MethodClass.hpp.
Member Function Documentation
createInstance()
void MethodClass::createInstance () static
Create initial class object at bootstrap time.
Definition at line 73 of file MethodClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
flatten()
void MethodClass::flatten (Envelope * envelope) override virtual
Flatten a source object.
Parameters
envelope The envelope that will hold the flattened object.
Reimplemented from RexxVirtualBase.
Definition at line 143 of file MethodClass.cpp.
References BaseExecutable::annotations, cleanUpFlatten, BaseExecutable::code, BaseExecutable::executableName, flattenRef, scope, and setUpFlatten.
getCode()
BaseCode* MethodClass::getCode () inline
Definition at line 140 of file MethodClass.hpp.
References BaseExecutable::code.
getScope()
RexxClass* MethodClass::getScope () inline
Definition at line 135 of file MethodClass.hpp.
References scope.
Referenced by MethodDictionary::addMethod(), RexxObject::checkPrivate(), MethodDictionary::findSuperMethod(), getScopeRexx(), MethodDictionary::replaceMethods(), RexxActivation::RexxActivation(), AttributeGetterCode::run(), AttributeSetterCode::run(), and DelegateCode::run().
getScopeName()
RexxString * MethodClass::getScopeName ()
Retrieve a string name for the method scope. If the scope is .nil, then ".NIL" is returned, otherwise the class name is used.
Returns
A string name for the scope.
Definition at line 373 of file MethodClass.cpp.
References RexxClass::getId(), scope, and TheNilObject.
Referenced by InternalActivationFrame::createStackFrame().
getScopeRexx()
RexxObject * MethodClass::getScopeRexx ()
Returns the defining class scope for a method. Returns .nil for any method not defined by a class scope.
Returns
The scope class or .nil.
Definition at line 361 of file MethodClass.cpp.
References getScope(), and resultOrNil().
Referenced by MemoryObject::createImage().
isAbstract()
bool MethodClass::isAbstract () inline
Definition at line 121 of file MethodClass.hpp.
References ABSTRACT_METHOD, and methodFlags.
Referenced by isAbstractRexx().
isAbstractRexx()
RexxObject * MethodClass::isAbstractRexx ()
Indicate if this is an abstract method
Returns
.true if the method is abstract. .false otherwise.
Definition at line 323 of file MethodClass.cpp.
References booleanObject(), and isAbstract().
Referenced by MemoryObject::createImage().
isAttribute()
bool MethodClass::isAttribute () inline
Definition at line 120 of file MethodClass.hpp.
References ATTRIBUTE_METHOD, and methodFlags.
Referenced by isAttributeRexx(), and LanguageParser::processAttributeAnnotations().
isAttributeRexx()
RexxObject * MethodClass::isAttributeRexx ()
Indicate if this method was defined as an attribute method (using ::attribute or ::method attribute)
Returns
.true if the method is defined as an attribute. .false otherwise.
Definition at line 336 of file MethodClass.cpp.
References booleanObject(), and isAttribute().
Referenced by MemoryObject::createImage().
isConstant()
bool MethodClass::isConstant () inline
Definition at line 119 of file MethodClass.hpp.
References CONSTANT_METHOD, and methodFlags.
Referenced by LanguageParser::annotateDirective(), and isConstantRexx().
isConstantRexx()
RexxObject * MethodClass::isConstantRexx ()
Indicate if this method was defined as a constant method (using ::constant)
Returns
.true if the method is defined as an attribute. .false otherwise.
Definition at line 349 of file MethodClass.cpp.
References booleanObject(), and isConstant().
Referenced by MemoryObject::createImage().
isGuarded()
bool MethodClass::isGuarded () inline
Definition at line 114 of file MethodClass.hpp.
References methodFlags, and UNGUARDED_FLAG.
Referenced by isGuardedRexx(), NativeActivation::methodVariables(), RexxActivation::RexxActivation(), AttributeGetterCode::run(), AttributeSetterCode::run(), and DelegateCode::run().
isGuardedRexx()
RexxObject * MethodClass::isGuardedRexx ()
Return the Guarded setting for a method object.
Returns
.true if the method is guarded. .false otherwise.
Definition at line 278 of file MethodClass.cpp.
References booleanObject(), and isGuarded().
Referenced by MemoryObject::createImage().
isPackageRexx()
RexxObject * MethodClass::isPackageRexx ()
Return the Package setting for a method object.
Returns
.true if the method is package scope. .false otherwise.
Definition at line 301 of file MethodClass.cpp.
References booleanObject(), and isPackageScope().
Referenced by MemoryObject::createImage().
isPackageScope()
bool MethodClass::isPackageScope () inline
Definition at line 117 of file MethodClass.hpp.
References methodFlags, and PACKAGE_FLAG.
Referenced by isPackageRexx(), and RexxObject::messageSend().
isPrivate()
bool MethodClass::isPrivate () inline
Definition at line 115 of file MethodClass.hpp.
References methodFlags, and PRIVATE_FLAG.
Referenced by isPrivateRexx(), and RexxObject::messageSend().
isPrivateRexx()
RexxObject * MethodClass::isPrivateRexx ()
Return the Private setting for a method object.
Returns
.true if the method is private. .false otherwise.
Definition at line 289 of file MethodClass.cpp.
References booleanObject(), and isPrivate().
Referenced by MemoryObject::createImage().
isProtected()
bool MethodClass::isProtected () inline
Definition at line 116 of file MethodClass.hpp.
References methodFlags, and PROTECTED_FLAG.
Referenced by isProtectedRexx(), and RexxObject::messageSend().
isProtectedRexx()
RexxObject * MethodClass::isProtectedRexx ()
Return the Protected setting for a method object.
Returns
.true if the method is protected. .false otherwise.
Definition at line 312 of file MethodClass.cpp.
References booleanObject(), and isProtected().
Referenced by MemoryObject::createImage().
isSamePackage()
bool MethodClass::isSamePackage (PackageClass * p) inline
Definition at line 147 of file MethodClass.hpp.
References BaseExecutable::code, and BaseCode::isSamePackage().
Referenced by RexxObject::checkPackage().
isScope()
bool MethodClass::isScope (RexxClass * s) inline
Definition at line 138 of file MethodClass.hpp.
References scope.
Referenced by MethodDictionary::addMethod(), and MethodDictionary::getMethods().
isSpecial()
bool MethodClass::isSpecial () inline
Definition at line 118 of file MethodClass.hpp.
References methodFlags, PACKAGE_FLAG, PRIVATE_FLAG, and PROTECTED_FLAG.
Referenced by RexxObject::messageSend().
live()
void MethodClass::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 111 of file MethodClass.cpp.
References BaseExecutable::annotations, BaseExecutable::code, BaseExecutable::executableName, memory_mark, and scope.
liveGeneral()
void MethodClass::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 128 of file MethodClass.cpp.
References BaseExecutable::annotations, BaseExecutable::code, BaseExecutable::executableName, memory_mark_general, and scope.
loadExternalMethod()
MethodClass * MethodClass::loadExternalMethod (RexxString * methodName, RexxString * libraryDescriptor)
Create a method from an external library source.
Parameters
methodName The method name.
libraryDescriptor
Returns
The resolved method object, or OREF_NULL if unable to load the routine.
Definition at line 560 of file MethodClass.cpp.
References Error_Translation_bad_external, PackageManager::loadMethod(), MethodClass(), OREF_NULL, reportException(), stringArgument(), TheNilObject, and StringUtil::words().
Referenced by MemoryObject::createImage().
newFileRexx()
MethodClass * MethodClass::newFileRexx (RexxString * filename, PackageClass * sourceContext)
Create a method object from a file.
Parameters
filename The target file name.
scope The scope that the new method object will be given.
Returns
The created method object.
Definition at line 533 of file MethodClass.cpp.
References RexxClass::completeNewObject(), LanguageParser::createMethod(), and BaseExecutable::processNewFileExecutableArgs().
Referenced by MemoryObject::createImage().
newMethodObject()
MethodClass * MethodClass::newMethodObject (RexxString * pgmname, RexxObject * source, RexxClass * scope, const char * position) static
Static method used for constructing new method objects in various contexts (such as the define method on the Class class).
Parameters
pgmname The name of the method we're creating.
source The method source (either a string or an array).
scope The scope that the new method object will be given.
position The position used for reporting errors. This is the position of the source argument for the calling method context.
Returns
The constructed method object.
Definition at line 453 of file MethodClass.cpp.
References LanguageParser::createMethod(), ActivityManager::currentActivity, Error_Incorrect_method_no_method_type, Activity::getCurrentRexxFrame(), RexxActivation::getPackage(), isMethod(), newScope(), OREF_NULL, BaseExecutable::processExecutableSource(), reportException(), scope, setScope(), and BaseExecutable::source().
Referenced by RexxClass::createMethodDictionary(), RexxClass::defineMethod(), RexxObject::run(), RexxObject::setMethod(), and DirectoryClass::setMethodRexx().
newRexx()
MethodClass * MethodClass::newRexx (RexxObject ** init_args, size_t argCount)
Create a new method from REXX code contained in a string or an array
Parameters
init_args The array of arguments to the new method.
argCount The argument count.
Returns
A new method object.
Definition at line 499 of file MethodClass.cpp.
References RexxClass::completeNewObject(), LanguageParser::createMethod(), and BaseExecutable::processNewExecutableArgs().
Referenced by MemoryObject::createImage().
newScope()
MethodClass * MethodClass::newScope (RexxClass * newClass)
Change the scope of a method object. This also returns a new method object.
Parameters
_scope The new scope.
Returns
The new method object with the new scope.
Definition at line 183 of file MethodClass.cpp.
References BaseExecutable::copy(), OREF_NULL, scope, setField, and setOtherField.
Referenced by MethodDictionary::addMethods(), RexxClass::defineClassMethod(), RexxObject::defineInstanceMethod(), RexxObject::defineInstanceMethods(), newMethodObject(), MethodDictionary::replaceMethods(), and MethodDictionary::setMethodScope().
operator new()
void * MethodClass::operator new (size_t size)
Allocate a new Method object.
Parameters
size The base size of the method object.
Returns
The storage for a method object.
Definition at line 86 of file MethodClass.cpp.
References new_object(), and T_Method.
restore()
MethodClass * MethodClass::restore (RexxString * fileName, BufferClass * buffer) static
Restore a program from a simple buffer.
Parameters
fileName The file name of the program we're restoring from.
buffer The source buffer. This contains all of the saved metadata ahead of the the flattened object.
Returns
The inflated Method object, if valid.
Definition at line 427 of file MethodClass.cpp.
References MethodClass(), OREF_NULL, and ProgramMetaData::restore().
Referenced by LanguageParser::createMethod().
run()
void MethodClass::run (Activity * activity, RexxObject * receiver, RexxString * msgname, RexxObject ** argPtr, size_t count, ProtectedObject & result)
Invoke this method on an object.
Parameters
activity The current activity.
receiver The receiver object.
msgname The message name.
argPtr The argument pointer.
count The argument count.
result The result object used to pass a result back.
Definition at line 167 of file MethodClass.cpp.
References BaseExecutable::code, and BaseCode::run().
Referenced by DirectoryClass::allItems(), DirectoryClass::getIndex(), RexxObject::messageSend(), DirectoryClass::methodTableValue(), RexxObject::processProtectedMethod(), RexxObject::processUnknown(), DirectoryClass::supplier(), and DirectoryClass::unknownValue().
setAbstract()
void MethodClass::setAbstract () inline
Definition at line 132 of file MethodClass.hpp.
References ABSTRACT_METHOD, and methodFlags.
setAttribute() [1/2]
void MethodClass::setAttribute () inline
Definition at line 131 of file MethodClass.hpp.
References ATTRIBUTE_METHOD, and methodFlags.
setAttribute() [2/2]
void MethodClass::setAttribute (bool v) inline
Definition at line 133 of file MethodClass.hpp.
References ATTRIBUTE_METHOD, and methodFlags.
setAttributes()
void MethodClass::setAttributes (AccessFlag _access, ProtectedFlag _protected, GuardFlag _guarded)
Set the entire set of method attributes with one call. Used during source compilation.
Parameters
_access The access setting.
_protected The protected setting.
_guarded The guarded setting.
Definition at line 387 of file MethodClass.cpp.
References PACKAGE_SCOPE, PRIVATE_SCOPE, PROTECTED_METHOD, setPackageScope(), setPrivate(), setProtected(), setUnguarded(), and UNGUARDED_METHOD.
setConstant()
void MethodClass::setConstant () inline
Definition at line 130 of file MethodClass.hpp.
References CONSTANT_METHOD, and methodFlags.
setGuarded()
void MethodClass::setGuarded () inline
Definition at line 124 of file MethodClass.hpp.
References methodFlags, and UNGUARDED_FLAG.
Referenced by setGuardedRexx().
setGuardedRexx()
RexxObject * MethodClass::setGuardedRexx ()
Change the guarded state of the method from Rexx code.
Returns
No return value.
Definition at line 242 of file MethodClass.cpp.
References OREF_NULL, and setGuarded().
Referenced by MemoryObject::createImage().
setPackageScope()
void MethodClass::setPackageScope () inline
Definition at line 126 of file MethodClass.hpp.
References methodFlags, and PACKAGE_FLAG.
Referenced by setAttributes().
setPrivate()
void MethodClass::setPrivate () inline
Definition at line 125 of file MethodClass.hpp.
References methodFlags, and PRIVATE_FLAG.
Referenced by MemoryObject::definePrivateMethod(), setAttributes(), and setPrivateRexx().
setPrivateRexx()
RexxObject * MethodClass::setPrivateRexx ()
Flag the method as being private from Rexx code.
Returns
No return value.
Definition at line 254 of file MethodClass.cpp.
References OREF_NULL, and setPrivate().
Referenced by MemoryObject::createImage().
setProtected()
void MethodClass::setProtected () inline
Definition at line 127 of file MethodClass.hpp.
References methodFlags, and PROTECTED_FLAG.
Referenced by MemoryObject::defineProtectedMethod(), setAttributes(), and setProtectedRexx().
setProtectedRexx()
RexxObject * MethodClass::setProtectedRexx ()
Turn on a method's protected state from Rexx code.
Returns
No return value.
Definition at line 266 of file MethodClass.cpp.
References OREF_NULL, and setProtected().
Referenced by MemoryObject::createImage().
setPublic()
void MethodClass::setPublic () inline
Definition at line 129 of file MethodClass.hpp.
References methodFlags, and PRIVATE_FLAG.
setScope()
void MethodClass::setScope (RexxClass * _scope)
Internal method to just set the scope for the method.
Parameters
_scope The new scope.
Definition at line 219 of file MethodClass.cpp.
References scope, and setField.
Referenced by RexxClass::createMethodDictionary(), and newMethodObject().
setSecurityManager()
RexxObject * MethodClass::setSecurityManager (RexxObject * manager)
Associate a security manager with a method's source.
Parameters
manager The security manager instance.
Returns
The return code from setting this on the code object.
Definition at line 209 of file MethodClass.cpp.
References BaseExecutable::code, and BaseCode::setSecurityManager().
Referenced by MemoryObject::createImage().
setUnguarded()
void MethodClass::setUnguarded () inline
Definition at line 123 of file MethodClass.hpp.
References methodFlags, and UNGUARDED_FLAG.
Referenced by MemoryObject::defineUnguardedMethod(), setAttributes(), and setUnguardedRexx().
setUnguardedRexx()
RexxObject * MethodClass::setUnguardedRexx ()
Change the guarded state of the method from Rexx code.
Returns
No return value.
Definition at line 230 of file MethodClass.cpp.
References OREF_NULL, and setUnguarded().
Referenced by MemoryObject::createImage().
setUnprotected()
void MethodClass::setUnprotected () inline
Definition at line 128 of file MethodClass.hpp.
References methodFlags, and PROTECTED_FLAG.
Member Data Documentation
classInstance
RexxClass * MethodClass::classInstance = OREF_NULL static
Definition at line 152 of file MethodClass.hpp.
methodFlags
FlagSet<MethodFlags, 32> MethodClass::methodFlags protected
Definition at line 167 of file MethodClass.hpp.
Referenced by isAbstract(), isAttribute(), isConstant(), isGuarded(), isPackageScope(), isPrivate(), isProtected(), isSpecial(), setAbstract(), setAttribute(), setConstant(), setGuarded(), setPackageScope(), setPrivate(), setProtected(), setPublic(), setUnguarded(), and setUnprotected().
scope
RexxClass* MethodClass::scope protected
Definition at line 168 of file MethodClass.hpp.
Referenced by flatten(), getScope(), getScopeName(), isScope(), live(), liveGeneral(), newMethodObject(), newScope(), and setScope().
The documentation for this class was generated from the following files:
MethodClass.hpp
MethodClass.cpp