ooRexx: VariableDictionary::VariableIterator Class Reference
VariableDictionary::VariableIterator Class Reference
#include <VariableDictionary.hpp>
Public Member Functions
VariableIterator ()
~VariableIterator ()
bool isAvailable ()
RexxObject * value ()
RexxString * name ()
void next ()
void terminate ()
bool isActive ()
Private Member Functions
VariableIterator (VariableDictionary *d)
Private Attributes
VariableDictionary * dictionary
HashContents::TableIterator dictionaryIterator
StemClass * currentStem
CompoundVariableTable::TableIterator stemIterator
bool returnStemValue
Friends
class VariableDictionary
Detailed Description
an iterator for iterating over all entries of the variable dictionary. This will iterate over both simple and compound variables.
Definition at line 70 of file VariableDictionary.hpp.
Constructor & Destructor Documentation
VariableIterator() [1/2]
VariableDictionary::VariableIterator::VariableIterator () inline
Definition at line 75 of file VariableDictionary.hpp.
~VariableIterator()
VariableDictionary::VariableIterator::~VariableIterator () inline
Definition at line 76 of file VariableDictionary.hpp.
VariableIterator() [2/2]
VariableDictionary::VariableIterator::VariableIterator (VariableDictionary * d) private
constructor for an index iterator
Parameters
d The dictionary we're created from.
Definition at line 1010 of file VariableDictionary.cpp.
References VariableDictionary::contents, currentStem, dictionary, dictionaryIterator, RexxVariable::getVariableValue(), StemClass::hasValue(), HashContents::TableIterator::isAvailable(), RexxVariable::isStem(), StemClass::iterator(), HashContents::iterator(), HashContents::TableIterator::next(), OREF_NULL, returnStemValue, stemIterator, and HashContents::TableIterator::value().
Member Function Documentation
isActive()
bool VariableDictionary::VariableIterator::isActive () inline
Definition at line 112 of file VariableDictionary.hpp.
References dictionary, and OREF_NULL.
Referenced by NativeActivation::fetchNext().
isAvailable()
bool VariableDictionary::VariableIterator::isAvailable () inline
Definition at line 78 of file VariableDictionary.hpp.
References currentStem, dictionary, dictionaryIterator, CompoundVariableTable::TableIterator::isAvailable(), HashContents::TableIterator::isAvailable(), OREF_NULL, returnStemValue, and stemIterator.
Referenced by NativeActivation::fetchNext(), VariableDictionary::getAllVariables(), and VariableDictionary::getVariableDirectory().
name()
RexxString * VariableDictionary::VariableIterator::name ()
Return the name of the current variable.
Returns
The variable name.
Definition at line 1133 of file VariableDictionary.cpp.
References OREF_NULL.
Referenced by NativeActivation::fetchNext().
next()
void VariableDictionary::VariableIterator::next ()
Step to the next position while iterating through a variable dictionary.
Definition at line 1048 of file VariableDictionary.cpp.
References RexxVariable::getVariableValue(), RexxVariable::isDropped(), RexxVariable::isStem(), and OREF_NULL.
Referenced by NativeActivation::fetchNext(), VariableDictionary::getAllVariables(), and VariableDictionary::getVariableDirectory().
terminate()
void VariableDictionary::VariableIterator::terminate () inline
Definition at line 105 of file VariableDictionary.hpp.
References currentStem, dictionary, and OREF_NULL.
Referenced by NativeActivation::fetchNext(), and NativeActivation::resetNext().
value()
RexxObject * VariableDictionary::VariableIterator::value ()
Retrieve the value of the current variable.
Returns
Return the name of the current variable.
Definition at line 1111 of file VariableDictionary.cpp.
References RexxInternalObject::getValue(), and OREF_NULL.
Referenced by NativeActivation::fetchNext(), VariableDictionary::getAllVariables(), and VariableDictionary::getVariableDirectory().
Friends And Related Function Documentation
VariableDictionary
friend class VariableDictionary friend
Definition at line 72 of file VariableDictionary.hpp.
Member Data Documentation
currentStem
StemClass* VariableDictionary::VariableIterator::currentStem private
Definition at line 123 of file VariableDictionary.hpp.
Referenced by isAvailable(), terminate(), and VariableIterator().
dictionary
VariableDictionary* VariableDictionary::VariableIterator::dictionary private
Definition at line 121 of file VariableDictionary.hpp.
Referenced by isActive(), isAvailable(), terminate(), and VariableIterator().
dictionaryIterator
HashContents::TableIterator VariableDictionary::VariableIterator::dictionaryIterator private
Definition at line 122 of file VariableDictionary.hpp.
Referenced by isAvailable(), and VariableIterator().
returnStemValue
bool VariableDictionary::VariableIterator::returnStemValue private
Definition at line 125 of file VariableDictionary.hpp.
Referenced by isAvailable(), and VariableIterator().
stemIterator
CompoundVariableTable::TableIterator VariableDictionary::VariableIterator::stemIterator private
Definition at line 124 of file VariableDictionary.hpp.
Referenced by isAvailable(), and VariableIterator().
The documentation for this class was generated from the following files:
VariableDictionary.hpp
VariableDictionary.cpp