ooRexx: InputWriterThread Class Reference
InputWriterThread Class Reference
Public Member Functions
InputWriterThread ()
~InputWriterThread ()
void start (int _pipe)
virtual void dispatch ()
InputWriterThread ()
~InputWriterThread ()
void start (HANDLE _pipe)
virtual void dispatch ()
void shutdown ()
Public Member Functions inherited from SysThread
SysThread ()
virtual ~SysThread ()
virtual void attachThread ()
void terminate ()
void startup ()
void shutdown ()
void yield ()
bool equals (SysThread &other)
void waitForTermination ()
SysThread ()
virtual ~SysThread ()
SysThread (thread_id_t threadID)
virtual void attachThread ()
void terminate ()
void startup ()
void shutdown ()
void yield ()
uintptr_t threadID ()
bool equals (SysThread &other)
size_t hash ()
void waitForTermination ()
Public Attributes
int pipe
const char * inputBuffer
size_t bufferLength
int error
bool wasShutdown
HANDLE pipe
Additional Inherited Members
Public Types inherited from SysThread
enum { THREAD_STACK_SIZE = 1024*512 }
enum { THREAD_STACK_SIZE = 1024*512 }
Static Public Member Functions inherited from SysThread
static void sleep (int msecs)
static int longSleep (uint64_t microseconds)
static uint64_t getMillisecondTicks ()
static int createThread (pthread_t &id, bool &idValid, size_t stackSize, void *(*startRoutine)(void *), void *startArgument)
static void sleep (int msecs)
static int longSleep (uint64_t microseconds)
static uint64_t getMillisecondTicks ()
static int createThread (HANDLE &threadHandle, DWORD &threadId, size_t stackSize, LPTHREAD_START_ROUTINE, void *startArgument)
Protected Member Functions inherited from SysThread
void createThread ()
void createThread ()
Protected Attributes inherited from SysThread
bool valid
bool attached
pthread_t _threadID
HANDLE _threadHandle
DWORD _threadID
Detailed Description
Definition at line 81 of file unix/SystemCommands.cpp.
Constructor & Destructor Documentation
InputWriterThread() [1/2]
InputWriterThread::InputWriterThread () inline
Definition at line 85 of file unix/SystemCommands.cpp.
~InputWriterThread() [1/2]
InputWriterThread::~InputWriterThread () inline
Definition at line 87 of file unix/SystemCommands.cpp.
References SysThread::terminate().
InputWriterThread() [2/2]
InputWriterThread::InputWriterThread () inline
Definition at line 81 of file windows/SystemCommands.cpp.
~InputWriterThread() [2/2]
InputWriterThread::~InputWriterThread () inline
Definition at line 83 of file windows/SystemCommands.cpp.
References SysThread::terminate().
Member Function Documentation
dispatch() [1/2]
virtual void InputWriterThread::dispatch () inline virtual
This is a dummy method intended for subclass overrides. This dispatches the code on the new thread.
Reimplemented from SysThread.
Definition at line 95 of file unix/SystemCommands.cpp.
References bufferLength, error, inputBuffer, and pipe.
dispatch() [2/2]
virtual void InputWriterThread::dispatch () inline virtual
This is a dummy method intended for subclass overrides. This dispatches the code on the new thread.
Reimplemented from SysThread.
Definition at line 90 of file windows/SystemCommands.cpp.
References bufferLength, error, inputBuffer, pipe, and wasShutdown.
shutdown()
void InputWriterThread::shutdown () inline
Definition at line 105 of file windows/SystemCommands.cpp.
References wasShutdown.
Referenced by sysCommandNT().
start() [1/2]
void InputWriterThread::start (HANDLE _pipe) inline
Definition at line 85 of file windows/SystemCommands.cpp.
References SysThread::createThread(), and pipe.
start() [2/2]
void InputWriterThread::start (int _pipe) inline
Definition at line 89 of file unix/SystemCommands.cpp.
References SysThread::createThread(), and pipe.
Referenced by ioCommandHandler(), and sysCommandNT().
Member Data Documentation
bufferLength
size_t InputWriterThread::bufferLength
Definition at line 117 of file unix/SystemCommands.cpp.
Referenced by dispatch(), ioCommandHandler(), and sysCommandNT().
error
int InputWriterThread::error
Definition at line 118 of file unix/SystemCommands.cpp.
Referenced by dispatch(), ioCommandHandler(), and sysCommandNT().
inputBuffer
const char * InputWriterThread::inputBuffer
Definition at line 116 of file unix/SystemCommands.cpp.
Referenced by dispatch(), ioCommandHandler(), and sysCommandNT().
pipe [1/2]
int InputWriterThread::pipe
Definition at line 115 of file unix/SystemCommands.cpp.
Referenced by dispatch(), and start().
pipe [2/2]
HANDLE InputWriterThread::pipe
Definition at line 115 of file windows/SystemCommands.cpp.
wasShutdown
bool InputWriterThread::wasShutdown
Definition at line 112 of file windows/SystemCommands.cpp.
Referenced by dispatch(), and shutdown().
The documentation for this class was generated from the following files:
unix/SystemCommands.cpp
windows/SystemCommands.cpp