ooRexx: RexxVariable Class Reference
RexxVariable Class Reference
#include <RexxVariable.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
RexxVariable ()
RexxVariable (RexxString *n)
RexxVariable (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
void inform (Activity *)
void drop ()
void notify ()
void uninform (Activity *)
void setStem (RexxObject *)
void set (RexxObject *value)
void setValue (RexxObject *value)
void setCreator (RexxActivation *creatorActivation)
bool isLocal ()
bool isAliasable ()
RexxObject * getVariableValue ()
RexxObject * getResolvedValue ()
RexxString * getName ()
void setName (RexxString *name)
bool isDropped ()
RexxVariable * getNext ()
bool isStem ()
VariableReference * createReference ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Protected Attributes
RexxString * variableName
RexxObject * variableValue
RexxActivation * creator
IdentityTable * dependents
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 52 of file RexxVariable.hpp.
Constructor & Destructor Documentation
RexxVariable() [1/3]
RexxVariable::RexxVariable () inline
Definition at line 58 of file RexxVariable.hpp.
RexxVariable() [2/3]
RexxVariable::RexxVariable (RexxString * n) inline
Definition at line 59 of file RexxVariable.hpp.
RexxVariable() [3/3]
RexxVariable::RexxVariable (RESTORETYPE restoreType) inline
Definition at line 60 of file RexxVariable.hpp.
Member Function Documentation
createReference()
VariableReference * RexxVariable::createReference ()
Create a variable reference from this variable.
Returns
An object that provides an indirect reference to this variable.
Definition at line 251 of file RexxVariable.cpp.
Referenced by RexxStemVariable::getVariableReference(), and RexxSimpleVariable::getVariableReference().
drop()
void RexxVariable::drop ()
Drop a variable.
Definition at line 160 of file RexxVariable.cpp.
References dependents, HashCollection::isEmpty(), notify(), OREF_NULL, setField, and variableValue.
Referenced by VariableDictionary::drop(), RexxSimpleVariable::drop(), StemClass::dropCompoundVariable(), StemClass::dropElement(), RexxActivation::dropLocalVariable(), VariableDictionary::dropStemVariable(), StemClass::remove(), and StemClass::removeItem().
flatten()
void RexxVariable::flatten (Envelope * envelope) override virtual
Flatten a source object.
Parameters
envelope The envelope that will hold the flattened object.
Reimplemented from RexxVirtualBase.
Definition at line 101 of file RexxVariable.cpp.
References cleanUpFlatten, creator, dependents, flattenRef, setUpFlatten, variableName, and variableValue.
getName()
RexxString* RexxVariable::getName () inline
Definition at line 88 of file RexxVariable.hpp.
References variableName.
Referenced by CompoundVariableTable::copyFrom(), CompoundTableElement::createCompoundName(), RexxLocalVariables::createDictionary(), StemClass::expose(), RexxCompoundVariable::expose(), CompoundVariableTable::findEntry(), RexxLocalVariables::findVariable(), VariableDictionary::getAllVariables(), VariableReference::getName(), VariableDictionary::getVariableDirectory(), StemClass::index(), RexxLocalVariables::lookupStemVariable(), RexxLocalVariables::lookupVariable(), RexxCompoundVariable::procedureExpose(), RexxLocalVariables::putVariable(), StemClass::supplier(), StemClass::tailArray(), StemClass::toDirectory(), and RexxLocalVariables::updateVariable().
getNext()
RexxVariable* RexxVariable::getNext () inline
Definition at line 94 of file RexxVariable.hpp.
References variableValue.
getResolvedValue()
RexxObject* RexxVariable::getResolvedValue () inline
Definition at line 87 of file RexxVariable.hpp.
References OREF_NULL, variableName, and variableValue.
Referenced by VariableReference::doubleValue(), VariableReference::getValue(), VariableReference::integerValue(), VariableReference::numberString(), VariableReference::numberValue(), VariableReference::processUnknown(), VariableReference::request(), VariableReference::stringValue(), VariableReference::unknownRexx(), and VariableReference::unsignedNumberValue().
getVariableValue()
RexxObject* RexxVariable::getVariableValue () inline
Definition at line 86 of file RexxVariable.hpp.
References variableValue.
Referenced by StemClass::allItems(), RexxSimpleVariable::evaluate(), StemClass::evaluateCompoundVariableValue(), StemClass::exposeCompoundVariable(), StemClass::findByValue(), VariableDictionary::getAllVariables(), StemClass::getCompoundVariableRealValue(), StemClass::getCompoundVariableValue(), StemClass::getElement(), StemClass::getFullElement(), RexxActivation::getLocalStem(), RexxSimpleVariable::getRealValue(), VariableDictionary::getStem(), RexxSimpleVariable::getValue(), VariableDictionary::getVariableDirectory(), StemClass::hasIndex(), StemClass::items(), RexxActivation::localVariableExists(), VariableDictionary::VariableIterator::next(), StemClass::realCompoundVariableValue(), VariableDictionary::realValue(), StemClass::remove(), StemClass::removeItem(), StemClass::sort(), StemClass::supplier(), StemClass::tailArray(), StemClass::toDirectory(), CompoundVariableTable::TableIterator::value(), and VariableDictionary::VariableIterator::VariableIterator().
inform()
void RexxVariable::inform (Activity * informee)
Request that an activity be informed of any variable modifications.
Parameters
informee The requesting activity.
Definition at line 120 of file RexxVariable.cpp.
References dependents, new_identity_table(), OREF_NULL, HashCollection::put(), setField, and TheNilObject.
Referenced by RexxCompoundVariable::setGuard(), RexxStemVariable::setGuard(), and RexxSimpleVariable::setGuard().
isAliasable()
bool RexxVariable::isAliasable ()
Definition at line 257 of file RexxVariable.cpp.
References StemClass::getValue(), isDropped(), StemClass::isEmpty(), isLocal(), isStem(), variableName, and variableValue.
Referenced by RexxLocalVariables::aliasVariable().
isDropped()
bool RexxVariable::isDropped () inline
Definition at line 90 of file RexxVariable.hpp.
References OREF_NULL, and variableValue.
Referenced by isAliasable(), and VariableDictionary::VariableIterator::next().
isLocal()
bool RexxVariable::isLocal () inline
Definition at line 84 of file RexxVariable.hpp.
References creator, and OREF_NULL.
Referenced by isAliasable().
isStem()
bool RexxVariable::isStem () inline
Definition at line 95 of file RexxVariable.hpp.
References RexxString::endsWith(), and variableName.
Referenced by isAliasable(), VariableReference::isStem(), VariableDictionary::VariableIterator::next(), setStem(), setValue(), and VariableDictionary::VariableIterator::VariableIterator().
live()
void RexxVariable::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 71 of file RexxVariable.cpp.
References creator, dependents, memory_mark, variableName, and variableValue.
liveGeneral()
void RexxVariable::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxVirtualBase.
Definition at line 87 of file RexxVariable.cpp.
References creator, dependents, memory_mark_general, variableName, and variableValue.
notify()
void RexxVariable::notify ()
notify all waiting activities that a variable has been updated.
Definition at line 175 of file RexxVariable.cpp.
References ActivityManager::currentActivity, dependents, Activity::guardPost(), HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), HashCollection::iterator(), HashContents::TableIterator::next(), OREF_NULL, and Activity::yieldControl().
Referenced by drop(), and set().
operator delete()
void RexxVariable::operator delete (void *) inline
Definition at line 56 of file RexxVariable.hpp.
operator new()
void * RexxVariable::operator new (size_t size)
Allocate a new variable object.
Parameters
size The size of the object.
Returns
Storage for creating the object.
Definition at line 60 of file RexxVariable.cpp.
References new_object(), and T_Variable.
set()
void RexxVariable::set (RexxObject * value) inline
Definition at line 72 of file RexxVariable.hpp.
References dependents, notify(), OREF_NULL, setField, and variableValue.
Referenced by StemClass::bracketEqual(), VariableDictionary::createStemVariable(), RexxActivation::dropLocalStem(), VariableDictionary::dropStemVariable(), StemClass::exposeCompoundVariable(), RexxActivation::handleNovalueEvent(), RexxLocalVariables::lookupStemVariable(), VariableDictionary::set(), RexxSimpleVariable::set(), StemClass::setCompoundVariable(), StemClass::setElement(), RexxActivation::setLocalVariable(), setStem(), CompoundTableElement::setValue(), setValue(), and StemClass::sort().
setCreator()
void RexxVariable::setCreator (RexxActivation * creatorActivation) inline
Definition at line 83 of file RexxVariable.hpp.
References creator.
Referenced by RexxActivation::newLocalVariable().
setName()
void RexxVariable::setName (RexxString * name) inline
Definition at line 89 of file RexxVariable.hpp.
References setField, and variableName.
setStem()
void RexxVariable::setStem (RexxObject * value)
Set a variable to a stem value. This handles all of the details of stem-to-stem assignment and stem variable re-initialization.
Parameters
value The value to set.
Definition at line 227 of file RexxVariable.cpp.
References isStem(), set(), StemClass::setValue(), and variableName.
Referenced by RexxStemVariable::assign(), RexxStemVariable::set(), and setValue().
setValue()
void RexxVariable::setValue (RexxObject * value)
A "safe" assignment method that sorts out the differeces between simple variable vs. stem variable assignment.
Parameters
value The new value to assign.
Definition at line 204 of file RexxVariable.cpp.
References isStem(), set(), and setStem().
Referenced by VariableReference::setValue(), and VariableReference::setValueRexx().
uninform()
void RexxVariable::uninform (Activity * informee)
Remove a notification watch from a variable.
Parameters
informee The activity requesting removal.
Definition at line 140 of file RexxVariable.cpp.
References dependents, and HashCollection::remove().
Referenced by RexxCompoundVariable::clearGuard(), RexxStemVariable::clearGuard(), and RexxSimpleVariable::clearGuard().
Member Data Documentation
creator
RexxActivation* RexxVariable::creator protected
Definition at line 102 of file RexxVariable.hpp.
Referenced by CompoundTableElement::flatten(), flatten(), isLocal(), CompoundTableElement::live(), live(), CompoundTableElement::liveGeneral(), liveGeneral(), and setCreator().
dependents
IdentityTable* RexxVariable::dependents protected
Definition at line 103 of file RexxVariable.hpp.
Referenced by drop(), CompoundTableElement::flatten(), flatten(), inform(), CompoundTableElement::live(), live(), CompoundTableElement::liveGeneral(), liveGeneral(), notify(), set(), and uninform().
variableName
RexxString* RexxVariable::variableName protected
Definition at line 100 of file RexxVariable.hpp.
Referenced by CompoundTableElement::CompoundTableElement(), CompoundTableElement::flatten(), flatten(), getName(), getResolvedValue(), isAliasable(), isStem(), CompoundTableElement::live(), live(), CompoundTableElement::liveGeneral(), liveGeneral(), setName(), and setStem().
variableValue
RexxObject* RexxVariable::variableValue protected
Definition at line 101 of file RexxVariable.hpp.
Referenced by CompoundVariableTable::copyFrom(), drop(), CompoundTableElement::flatten(), flatten(), getNext(), getResolvedValue(), getVariableValue(), isAliasable(), isDropped(), CompoundTableElement::live(), live(), CompoundTableElement::liveGeneral(), liveGeneral(), and set().
The documentation for this class was generated from the following files:
RexxVariable.hpp
RexxVariable.cpp