ooRexx: DispatchSection Class Reference
DispatchSection Class Reference
#include <Interpreter.hpp>
Public Member Functions
DispatchSection ()
~DispatchSection ()
void release ()
void reacquire ()
Private Attributes
bool terminated
Detailed Description
Block control for access to the dispatch queue.
Definition at line 196 of file Interpreter.hpp.
Constructor & Destructor Documentation
DispatchSection()
DispatchSection::DispatchSection () inline
Definition at line 199 of file Interpreter.hpp.
References Interpreter::getDispatchLock(), and terminated.
~DispatchSection()
DispatchSection::~DispatchSection () inline
Definition at line 205 of file Interpreter.hpp.
References Interpreter::releaseDispatchLock(), and terminated.
Member Function Documentation
reacquire()
void DispatchSection::reacquire () inline
Definition at line 223 of file Interpreter.hpp.
References Interpreter::getDispatchLock(), and terminated.
Referenced by ActivityManager::addWaitingActivity(), ActivityManager::addWaitingApiActivity(), and ActivityManager::attachThread().
release()
void DispatchSection::release () inline
Definition at line 213 of file Interpreter.hpp.
References Interpreter::releaseDispatchLock(), and terminated.
Referenced by ActivityManager::addWaitingActivity(), ActivityManager::addWaitingApiActivity(), and ActivityManager::attachThread().
Member Data Documentation
terminated
bool DispatchSection::terminated private
Definition at line 234 of file Interpreter.hpp.
Referenced by DispatchSection(), reacquire(), release(), and ~DispatchSection().
The documentation for this class was generated from the following file:
Interpreter.hpp