ooRexx: ActivationFrame Class Reference
ActivationFrame Class Reference abstract
#include <ActivationFrame.hpp>
Public Member Functions
ActivationFrame (Activity *a)
void disableFrame ()
~ActivationFrame ()
virtual RexxString * messageName ()=0
virtual BaseExecutable * executable ()=0
virtual StackFrameClass * createStackFrame ()=0
virtual PackageClass * getPackage ()=0
Protected Attributes
ActivationFrame * next
Activity * activity
Friends
class Activity
Detailed Description
The base class for all stack frames.
Definition at line 53 of file ActivationFrame.hpp.
Constructor & Destructor Documentation
ActivationFrame()
ActivationFrame::ActivationFrame (Activity * a) inline
Definition at line 57 of file ActivationFrame.hpp.
References Activity::activationFrames, activity, and next.
~ActivationFrame()
ActivationFrame::~ActivationFrame () inline
Definition at line 81 of file ActivationFrame.hpp.
References disableFrame().
Member Function Documentation
createStackFrame()
virtual StackFrameClass* ActivationFrame::createStackFrame () pure virtual
Implemented in RexxActivationFrame, NativeActivationFrame, InternalActivationFrame, and CompileActivationFrame.
Referenced by Activity::generateCallerStackFrame(), Activity::generateProgramInformation(), and Activity::generateStackFrames().
disableFrame()
void ActivationFrame::disableFrame () inline
Definition at line 68 of file ActivationFrame.hpp.
References Activity::activationFrames, activity, next, and OREF_NULL.
Referenced by NativeActivation::run(), RexxActivation::run(), and ~ActivationFrame().
executable()
virtual BaseExecutable* ActivationFrame::executable () pure virtual
Implemented in RexxActivationFrame, NativeActivationFrame, InternalActivationFrame, and CompileActivationFrame.
getPackage()
virtual PackageClass* ActivationFrame::getPackage () pure virtual
Implemented in RexxActivationFrame, NativeActivationFrame, InternalActivationFrame, and CompileActivationFrame.
Referenced by Activity::generateProgramInformation().
messageName()
virtual RexxString* ActivationFrame::messageName () pure virtual
Implemented in RexxActivationFrame, NativeActivationFrame, InternalActivationFrame, and CompileActivationFrame.
Referenced by Activity::getLastMessageName().
Friends And Related Function Documentation
Activity
friend class Activity friend
Definition at line 55 of file ActivationFrame.hpp.
Member Data Documentation
activity
Activity* ActivationFrame::activity protected
Definition at line 95 of file ActivationFrame.hpp.
Referenced by ActivationFrame(), InternalActivationFrame::createStackFrame(), and disableFrame().
next
ActivationFrame* ActivationFrame::next protected
Definition at line 94 of file ActivationFrame.hpp.
Referenced by ActivationFrame(), disableFrame(), Activity::generateCallerStackFrame(), Activity::generateProgramInformation(), and Activity::generateStackFrames().
The documentation for this class was generated from the following file:
ActivationFrame.hpp