ooRexx: SysServerLocalSocketConnectionManager Class Reference
SysServerLocalSocketConnectionManager Class Reference
#include <SysCSStream.hpp>
Public Member Functions
SysServerLocalSocketConnectionManager ()
~SysServerLocalSocketConnectionManager ()
bool bind (const char *serviceName)
Public Member Functions inherited from SysServerSocketConnectionManager
SysServerSocketConnectionManager ()
~SysServerSocketConnectionManager ()
bool disconnect () override
ApiConnection * acceptConnection () override
SysServerSocketConnectionManager ()
~SysServerSocketConnectionManager ()
bool disconnect () override
ApiConnection * acceptConnection () override
Public Member Functions inherited from ServerConnectionManager
ServerConnectionManager ()
virtual ~ServerConnectionManager ()
CSErrorCodeT getError ()
bool isClean ()
Static Public Member Functions
static const char * generateServiceName ()
static void getServiceLocation (char *path, size_t len)
Protected Member Functions
bool checkServiceName (const char *serviceName)
Static Protected Attributes
static const char * userServiceName = NULL
Additional Inherited Members
Protected Attributes inherited from SysServerSocketConnectionManager
int c
const char * boundServiceName
SOCKET c
Protected Attributes inherited from ServerConnectionManager
CSErrorCodeT errcode
Detailed Description
Implementation class for a socket connection bound to an AF_UNIX stream
Definition at line 104 of file unix/SysCSStream.hpp.
Constructor & Destructor Documentation
SysServerLocalSocketConnectionManager()
SysServerLocalSocketConnectionManager::SysServerLocalSocketConnectionManager () inline
Definition at line 107 of file unix/SysCSStream.hpp.
~SysServerLocalSocketConnectionManager()
SysServerLocalSocketConnectionManager::~SysServerLocalSocketConnectionManager () inline
Definition at line 108 of file unix/SysCSStream.hpp.
Member Function Documentation
bind()
bool SysServerLocalSocketConnectionManager::bind (const char * serviceName)
Make a server connection.
Parameters
serviceName The service name to use for the connection.
Returns
True on an error, otherwise false
Definition at line 338 of file unix/SysCSStream.cpp.
References SysServerSocketConnectionManager::boundServiceName, SysServerSocketConnectionManager::c, checkServiceName(), CSERROR_CONNX_EXISTS, CSERROR_INTERNAL, CSERROR_OK, CSERROR_UNKNOWN, ServerConnectionManager::errcode, and Utilities::strncpy().
Referenced by main().
checkServiceName()
bool SysServerLocalSocketConnectionManager::checkServiceName (const char * serviceName) protected
Check for the availability of the file name used for this bound service, deleting stale versions if still there.
Parameters
serviceName The target file path
Returns
true if the file name is available for use, false otherwise.
Definition at line 396 of file unix/SysCSStream.cpp.
Referenced by bind().
generateServiceName()
const char * SysServerLocalSocketConnectionManager::generateServiceName () static
Generate a unique string to be used for interprocess communications for this userid.
Returns
A unique identifier used to create the named AF_UNIX services.
Definition at line 444 of file unix/SysCSStream.cpp.
References getServiceLocation(), and userServiceName.
Referenced by main(), and SysLocalAPIManager::newClientConnection().
getServiceLocation()
void SysServerLocalSocketConnectionManager::getServiceLocation (char * path, size_t len) static
Determine the location of the service name files generated for this user. The preferred location is in the XDG_RUNTIME_DIR, but the fallback is to use TMPDIR, and if not set, /tmp for the file. We don't create this in the user's home directory, as it is fairly common practice for home directories to be mounted on an NFS, which means the file would be visible cross system.
Parameters
path The buffer for the returned path.
len The length of the buffer
Definition at line 476 of file unix/SysCSStream.cpp.
Referenced by generateServiceName(), and main().
Member Data Documentation
userServiceName
const char * SysServerLocalSocketConnectionManager::userServiceName = NULL static protected
Definition at line 119 of file unix/SysCSStream.hpp.
Referenced by generateServiceName().
The documentation for this class was generated from the following files:
unix/SysCSStream.hpp
unix/SysCSStream.cpp