ooRexx: MethodDictionary Class Reference
MethodDictionary Class Reference
#include <MethodDictionary.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
MethodDictionary (RESTORETYPE restoreType)
MethodDictionary (size_t capacity=DefaultTableSize)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
MethodClass * getMethod (RexxString *methodName)
void addMethod (RexxString *methodName, MethodClass *method)
void replaceMethod (RexxString *methodName, MethodClass *method)
void replaceMethods (MethodDictionary *source, RexxClass *scope)
void replaceMethods (MethodDictionary *source, RexxClass *filterScope, RexxClass *scope)
void replaceMethods (StringTable *source, RexxClass *scope)
void addMethods (StringTable *source, RexxClass *scope)
bool removeMethod (RexxString *methodName)
void hideMethod (RexxString *methodName)
void removeInstanceMethod (RexxString *name)
void addInstanceMethod (RexxString *name, MethodClass *method)
void addInstanceMethods (MethodDictionary *source)
MethodClass * findSuperMethod (RexxString *name, RexxClass *startScope)
void setMethodScope (RexxClass *scope)
SupplierClass * getMethods (RexxClass *scope)
RexxClass * resolveSuperScope (RexxClass *)
void addScope (RexxClass *scope)
void mergeMethods (MethodDictionary *target)
void mergeScopes (MethodDictionary *target)
void merge (MethodDictionary *target)
bool hasScope (RexxClass *scope)
ArrayClass * allScopes ()
bool hasInstanceMethods ()
Public Member Functions inherited from StringHashCollection
StringHashCollection (size_t capacity)
StringHashCollection ()
HashContents * allocateContents (size_t bucketSize, size_t capacity) override
void validateIndex (RexxObject *&index) override
bool requiresRehash () override
virtual bool hasEntry (RexxString *entryName)
virtual void setEntry (RexxString *entryname, RexxInternalObject *entryobj)
virtual RexxInternalObject * entry (RexxString *index)
virtual RexxInternalObject * removeEntry (RexxString *index)
virtual RexxObject * unknown (RexxString *msgname, RexxObject **arguments, size_t count)
void processUnknown (RexxErrorCodes error, RexxString *, RexxObject **, size_t, ProtectedObject &) override
RexxObject * entryRexx (RexxObject *entryName)
RexxObject * hasEntryRexx (RexxObject *entryName)
RexxObject * setEntryRexx (RexxObject *entryname, RexxObject *entryobj)
RexxObject * removeEntryRexx (RexxObject *entryName)
RexxObject * unknownRexx (RexxString *message, ArrayClass *arguments)
Public Member Functions inherited from HashCollection
HashCollection ()
RexxInternalObject * unflatten (Envelope *) override
ArrayClass * makeArray () override
virtual void validateValueIndex (RexxObject *&value, RexxObject *&index)
void initialize (size_t capacity=DefaultTableSize)
void copyValues ()
void expandContents ()
void expandContents (size_t capacity)
void ensureCapacity (size_t delta)
void checkFull ()
HashContents::TableIterator iterator ()
HashContents::ReverseTableIterator reverseIterator ()
HashContents::IndexIterator iterator (RexxInternalObject *index)
virtual void mergeItem (RexxInternalObject *, RexxInternalObject *)
virtual RexxInternalObject * remove (RexxInternalObject *key)
virtual RexxInternalObject * get (RexxInternalObject *key)
virtual void put (RexxInternalObject *, RexxInternalObject *)
virtual RexxInternalObject * removeItem (RexxInternalObject *value)
virtual bool hasIndex (RexxInternalObject *)
virtual bool hasItem (RexxInternalObject *)
virtual RexxInternalObject * getIndex (RexxInternalObject *value)
virtual void empty ()
virtual SupplierClass * supplier ()
virtual ArrayClass * allItems ()
virtual ArrayClass * allIndexes ()
virtual size_t items ()
RexxObject * initRexx (RexxObject *)
RexxObject * removeRexx (RexxObject *)
RexxObject * getRexx (RexxObject *)
RexxObject * putRexx (RexxObject *, RexxObject *)
RexxObject * addRexx (RexxObject *, RexxObject *)
RexxObject * hasIndexRexx (RexxObject *)
RexxObject * hasItemRexx (RexxObject *)
RexxObject * removeItemRexx (RexxObject *value)
ArrayClass * allAtRexx (RexxObject *)
RexxObject * indexRexx (RexxObject *value)
SupplierClass * supplierRexx ()
ArrayClass * allItemsRexx ()
ArrayClass * allIndexesRexx ()
RexxObject * emptyRexx ()
RexxObject * isEmptyRexx ()
RexxObject * itemsRexx ()
void merge (HashCollection *)
void putAll (HashCollection *)
void reHash ()
ArrayClass * uniqueIndexes ()
bool isEmpty ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
HashCode hash () override
RexxString * stringValue () override
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Protected Attributes
StringTable * instanceMethods
ArrayClass * scopeList
IdentityTable * scopeOrders
Static Protected Attributes
static const size_t DefaultScopeListSize = 10
Additional Inherited Members
Static Public Member Functions inherited from HashCollection
static size_t calculateBucketSize (size_t capacity)
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from HashCollection
HashContents * contents
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Static Public Attributes inherited from HashCollection
static const size_t MinimumBucketSize = 17
static const size_t DefaultTableSize = 17
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Member Functions inherited from HashCollection
virtual void add (RexxInternalObject *, RexxInternalObject *)
virtual void addFront (RexxInternalObject *, RexxInternalObject *)
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Exported table class where indexing is done using object identity
Definition at line 55 of file MethodDictionary.hpp.
Constructor & Destructor Documentation
MethodDictionary() [1/2]
MethodDictionary::MethodDictionary (RESTORETYPE restoreType) inline
Definition at line 61 of file MethodDictionary.hpp.
MethodDictionary() [2/2]
MethodDictionary::MethodDictionary (size_t capacity = DefaultTableSize)
Initialize a MethodDictionary.
Parameters
capacity The desired capacity.
Definition at line 69 of file MethodDictionary.cpp.
References DefaultScopeListSize, instanceMethods, new_array(), new_identity_table(), OREF_NULL, scopeList, and scopeOrders.
Member Function Documentation
addInstanceMethod()
void MethodDictionary::addInstanceMethod (RexxString * name, MethodClass * method)
Add an instance method to the dictionary.
Parameters
name The name of the method.
method The target method object.
Definition at line 382 of file MethodDictionary.cpp.
References HashCollection::addFront(), HashCollection::hasIndex(), instanceMethods, new_string_table(), OREF_NULL, HashCollection::put(), HashCollection::remove(), and setField.
Referenced by RexxBehaviour::addInstanceMethod(), and addInstanceMethods().
addInstanceMethods()
void MethodDictionary::addInstanceMethods (MethodDictionary * source)
Merge a collection of methods into our object instance behaviour.
Parameters
source The source method dictionary.
Definition at line 413 of file MethodDictionary.cpp.
References addInstanceMethod(), HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), HashCollection::iterator(), HashContents::TableIterator::next(), and HashContents::TableIterator::value().
Referenced by RexxBehaviour::addInstanceMethods().
addMethod()
void MethodDictionary::addMethod (RexxString * methodName, MethodClass * method)
Add a method to the main method dictionary
Parameters
methodName The target method name.
method The method object to add.
Definition at line 164 of file MethodDictionary.cpp.
References HashCollection::addFront(), HashCollection::contents, MethodClass::getScope(), HashContents::TableIterator::isAvailable(), MethodClass::isScope(), HashCollection::iterator(), HashContents::iterator(), HashContents::TableIterator::next(), OREF_NULL, HashContents::TableIterator::replace(), TheNilObject, and HashContents::TableIterator::value().
Referenced by addMethods(), RexxClass::defineClassMethod(), RexxBehaviour::defineMethod(), RexxClass::inheritInstanceMethods(), and mergeMethods().
addMethods()
void MethodDictionary::addMethods (StringTable * source, RexxClass * scope)
Add a collection of methods on top of this dictionary. These methods will override any methods already defined in this dictionary.
Parameters
source The source method dictionary.
scope The added method scopes.
Definition at line 308 of file MethodDictionary.cpp.
References addMethod(), HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), isMethod(), HashCollection::iterator(), MethodClass::newScope(), HashContents::TableIterator::next(), and HashContents::TableIterator::value().
Referenced by RexxClass::defineMethods().
addScope()
void MethodDictionary::addScope (RexxClass * scope)
Add a scope to the scope table. This is done unconditionall
Parameters
scope The new scope to add.
Definition at line 594 of file MethodDictionary.cpp.
References ArrayClass::append(), ArrayClass::copy(), HashCollection::hasIndex(), HashCollection::put(), scopeList, and scopeOrders.
Referenced by RexxBehaviour::addScope(), and mergeScopes().
allScopes()
ArrayClass* MethodDictionary::allScopes () inline
Definition at line 90 of file MethodDictionary.hpp.
References scopeList.
Referenced by RexxBehaviour::allScopes(), and mergeScopes().
copy()
RexxInternalObject * MethodDictionary::copy () override virtual
Copy a method dictionary
Returns
A new instance of this collection.
Reimplemented from HashCollection.
Definition at line 146 of file MethodDictionary.cpp.
References HashCollection::contents, RexxInternalObject::copy(), ArrayClass::copy(), RexxObject::copy(), HashCollection::copy(), scopeList, and scopeOrders.
Referenced by RexxClass::copyInstanceMethods(), RexxBehaviour::copyMethodDictionary(), and RexxBehaviour::mergeMethodDictionary().
findSuperMethod()
MethodClass * MethodDictionary::findSuperMethod (RexxString * name, RexxClass * startScope)
Locate a method from the method dictionary with a specific starting scope.
Parameters
name The name of the target method.
startScope The starting scope value.
Definition at line 434 of file MethodDictionary.cpp.
References HashCollection::contents, HashCollection::get(), MethodClass::getScope(), ArrayClass::hasIdentityItem(), HashContents::TableIterator::isAvailable(), HashCollection::iterator(), HashContents::iterator(), HashContents::TableIterator::next(), OREF_NULL, scopeOrders, TheNilObject, and HashContents::TableIterator::value().
Referenced by RexxBehaviour::superMethod().
flatten()
void MethodDictionary::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from HashCollection.
Definition at line 126 of file MethodDictionary.cpp.
References cleanUpFlatten, HashCollection::contents, flattenRef, instanceMethods, scopeList, scopeOrders, and setUpFlatten.
getMethod()
MethodClass* MethodDictionary::getMethod (RexxString * methodName) inline
Definition at line 69 of file MethodDictionary.hpp.
References HashCollection::get().
Referenced by RexxBehaviour::getMethod(), RexxClass::method(), and RexxBehaviour::methodLookup().
getMethods()
SupplierClass * MethodDictionary::getMethods (RexxClass * scope)
Get all methods with the target scope, or all methods if the scope is omitted.
Parameters
scope The target scope (can be NULL)
Returns
A supplier to iterate over the requested methods.
Definition at line 507 of file MethodDictionary.cpp.
References HashCollection::contents, HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), isMethod(), MethodClass::isScope(), HashCollection::iterator(), HashContents::iterator(), new_array(), new_supplier(), HashContents::TableIterator::next(), OREF_NULL, ArrayClass::put(), and HashContents::TableIterator::value().
Referenced by RexxBehaviour::getMethods().
hasInstanceMethods()
bool MethodDictionary::hasInstanceMethods () inline
Definition at line 92 of file MethodDictionary.hpp.
References instanceMethods, and OREF_NULL.
Referenced by RexxBehaviour::hasInstanceMethods().
hasScope()
bool MethodDictionary::hasScope (RexxClass * scope)
Test if the method dictionary already accounts for a given scope class.
Parameters
scope The target scope object.
Returns
True if this scope has already been merged into this method dictionary, false otherwise.
Definition at line 682 of file MethodDictionary.cpp.
References HashCollection::hasIndex(), and scopeOrders.
Referenced by RexxBehaviour::hasScope().
hideMethod()
void MethodDictionary::hideMethod (RexxString * methodName)
Block a method from execution by inserting a .nil into the dictionary. This is only used while constructing the initial table and unconditionally places .nil under the target name.
Parameters
methodName The method name to hid.
Definition at line 348 of file MethodDictionary.cpp.
References HashCollection::put(), and TheNilObject.
Referenced by RexxBehaviour::hideMethod().
live()
void MethodDictionary::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from HashCollection.
Definition at line 96 of file MethodDictionary.cpp.
References HashCollection::contents, instanceMethods, memory_mark, scopeList, and scopeOrders.
liveGeneral()
void MethodDictionary::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from HashCollection.
Definition at line 111 of file MethodDictionary.cpp.
References HashCollection::contents, instanceMethods, memory_mark_general, scopeList, and scopeOrders.
merge()
void MethodDictionary::merge (MethodDictionary * source)
Merge all of the method and scope information in this method dictionary into the target dictionary.
Parameters
souce The target we're merging from.
Definition at line 666 of file MethodDictionary.cpp.
References mergeMethods(), and mergeScopes().
Referenced by RexxBehaviour::mergeMethodDictionary(), and RexxClass::subclass().
mergeMethods()
void MethodDictionary::mergeMethods (MethodDictionary * target)
Merge a dictionary's methods into our dictionary. The new methods take precedence.
Parameters
The target MethodDictionary.
Definition at line 620 of file MethodDictionary.cpp.
References addMethod(), HashCollection::ensureCapacity(), HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), HashCollection::items(), HashCollection::iterator(), HashContents::TableIterator::next(), HashCollection::reverseIterator(), and HashContents::TableIterator::value().
Referenced by merge().
mergeScopes()
void MethodDictionary::mergeScopes (MethodDictionary * source)
Merge the scopy information from a method dictionary into ours. We only add in new scope classes.
Parameters
source The source method dictionary
Definition at line 645 of file MethodDictionary.cpp.
References addScope(), allScopes(), ArrayClass::get(), and ArrayClass::items().
Referenced by merge().
operator delete()
void MethodDictionary::operator delete (void *) inline
Definition at line 59 of file MethodDictionary.hpp.
operator new()
void * MethodDictionary::operator new (size_t size)
Create a new table object.
Parameters
size the size of the object.
Returns
Storage for creating a table object.
Definition at line 58 of file MethodDictionary.cpp.
References new_object(), and T_MethodDictionary.
removeInstanceMethod()
void MethodDictionary::removeInstanceMethod (RexxString * name)
Reverse a SETMETHOD call on an object.
Parameters
name The name of the method to remove.
Definition at line 359 of file MethodDictionary.cpp.
References instanceMethods, OREF_NULL, and HashCollection::remove().
Referenced by RexxBehaviour::removeInstanceMethod().
removeMethod()
bool MethodDictionary::removeMethod (RexxString * methodName)
Remove a method from the main method dictionary
Parameters
methodName The target method name.
Returns
True if there was a method to remove, false otherwise.
Definition at line 334 of file MethodDictionary.cpp.
References OREF_NULL, and HashCollection::remove().
Referenced by RexxClass::deleteMethod(), RexxBehaviour::removeMethod(), and RexxClass::removeSetupMethods().
replaceMethod()
void MethodDictionary::replaceMethod (RexxString * methodName, MethodClass * method)
Add or completely replace a method in the method dictionary. This is used during construction of the primitive classes during image construction. We might be replacing a method inherited from another class, so we want to ensure that any existing method by that name is completely removed.
Parameters
methodName The target method name.
method The method object to add.
Definition at line 207 of file MethodDictionary.cpp.
References HashCollection::put().
Referenced by RexxClass::defineMethod(), RexxBehaviour::replaceMethod(), and replaceMethods().
replaceMethods() [1/3]
void MethodDictionary::replaceMethods (MethodDictionary * source, RexxClass * filterScope, RexxClass * scope)
Overlay a collection of methods on top of this dictionary.
Parameters
source The source method dictionary.
filterScope The filtering scope for the inherit operations. Only methods defined at the filtering scope will be copied to the target method dictionary.
scope The scope that will be assigned to the copied methods.
Definition at line 251 of file MethodDictionary.cpp.
References MethodClass::getScope(), HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), isMethod(), HashCollection::iterator(), MethodClass::newScope(), HashContents::TableIterator::next(), replaceMethod(), and HashContents::TableIterator::value().
replaceMethods() [2/3]
void MethodDictionary::replaceMethods (MethodDictionary * source, RexxClass * scope)
Overlay a collection of methods on top of this dictionary.
Parameters
source The source method dictionary.
scope The scope the copied methods will have in the target dictionary.
Definition at line 221 of file MethodDictionary.cpp.
References HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), isMethod(), HashCollection::iterator(), MethodClass::newScope(), HashContents::TableIterator::next(), replaceMethod(), and HashContents::TableIterator::value().
Referenced by RexxClass::defineMethodsRexx(), and RexxBehaviour::inheritInstanceMethods().
replaceMethods() [3/3]
void MethodDictionary::replaceMethods (StringTable * source, RexxClass * scope)
Overlay a collection of methods on top of this dictionary.
Parameters
source The source method dictionary.
Definition at line 281 of file MethodDictionary.cpp.
References HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), isMethod(), HashCollection::iterator(), MethodClass::newScope(), HashContents::TableIterator::next(), replaceMethod(), and HashContents::TableIterator::value().
resolveSuperScope()
RexxClass * MethodDictionary::resolveSuperScope (RexxClass * scope)
Retrieve the immediate super scope item from the behaviour class list. This determines what value is used for the super variable on method calls.
Parameters
scope The scope we're resolving.
Returns
The immediate superclass value (return .nil for the Object class).
Definition at line 569 of file MethodDictionary.cpp.
References HashCollection::get(), ArrayClass::getLastItem(), ArrayClass::isEmpty(), OREF_NULL, scopeOrders, and TheNilObject.
Referenced by RexxBehaviour::immediateSuperScope(), and RexxBehaviour::superScope().
setMethodScope()
void MethodDictionary::setMethodScope (RexxClass * scope)
Set all methods in the method dictionary to the target scope.
Parameters
scope The scope class.
Definition at line 477 of file MethodDictionary.cpp.
References HashCollection::contents, HashContents::TableIterator::isAvailable(), HashCollection::iterator(), HashContents::iterator(), MethodClass::newScope(), HashContents::TableIterator::next(), HashContents::TableIterator::replace(), TheNilObject, and HashContents::TableIterator::value().
Referenced by RexxClass::inheritInstanceMethods(), and RexxBehaviour::setMethodDictionaryScope().
Member Data Documentation
DefaultScopeListSize
const size_t MethodDictionary::DefaultScopeListSize = 10 static protected
Definition at line 96 of file MethodDictionary.hpp.
Referenced by MethodDictionary().
instanceMethods
StringTable* MethodDictionary::instanceMethods protected
Definition at line 98 of file MethodDictionary.hpp.
Referenced by addInstanceMethod(), flatten(), hasInstanceMethods(), live(), liveGeneral(), MethodDictionary(), and removeInstanceMethod().
scopeList
ArrayClass* MethodDictionary::scopeList protected
Definition at line 99 of file MethodDictionary.hpp.
Referenced by addScope(), allScopes(), copy(), flatten(), live(), liveGeneral(), and MethodDictionary().
scopeOrders
IdentityTable* MethodDictionary::scopeOrders protected
Definition at line 100 of file MethodDictionary.hpp.
Referenced by addScope(), copy(), findSuperMethod(), flatten(), hasScope(), live(), liveGeneral(), MethodDictionary(), and resolveSuperScope().
The documentation for this class was generated from the following files:
MethodDictionary.hpp
MethodDictionary.cpp