ooRexx: ObjectHeader Class Reference
ObjectHeader Class Reference
#include <ObjectClass.hpp>
Public Member Functions
ObjectHeader & operator= (ObjectHeader &h)
size_t getObjectSize ()
void setObjectSize (size_t l)
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
void clearObjectMark ()
void setObjectMark (size_t mark)
bool isObjectMarked (size_t mark)
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
void clear ()
void setOldSpace ()
void clearOldSpace ()
void setNewSpace ()
bool isOldSpace ()
bool isNewSpace ()
void setHasNoReferences ()
void setHasReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setNonPrimitive ()
void setPrimitive ()
bool isNonPrimitive ()
bool isPrimitive ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool isDeadObject ()
void setDeadObject ()
void clearDeadObject ()
void initHeader (size_t l, size_t mark)
void initHeader (size_t mark)
Protected Types
enum {
MarkBit1 = 0x0001 , MarkBit2 = 0x0002 , LiveMask = 0xFFFC , MarkMask = 0x0003 ,
ProxiedObject = 0x0004 , ProxyObject = 0x0008 , IsNonPrimitive = 0x0010 , NoRefBit = 0x0020 ,
OldSpaceBit = 0x0040 , UninitPending = 0x0080 , HasUninit = 0x0100 , DeadObject = 0x0200
}
Protected Attributes
size_t objectSize
union {
uint16_t flags
uintptr_t sizePadding
};
Friends
class MemoryObject
Detailed Description
The header that is at the beginning of every object instanct.
Definition at line 95 of file ObjectClass.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
MarkBit1
MarkBit2
LiveMask
MarkMask
ProxiedObject
ProxyObject
IsNonPrimitive
NoRefBit
OldSpaceBit
UninitPending
HasUninit
DeadObject
Definition at line 157 of file ObjectClass.hpp.
Member Function Documentation
clear()
void ObjectHeader::clear () inline
Definition at line 123 of file ObjectClass.hpp.
References flags, and objectSize.
clearDeadObject()
void ObjectHeader::clearDeadObject () inline
Definition at line 145 of file ObjectClass.hpp.
References flags.
clearHasUninit()
void ObjectHeader::clearHasUninit () inline
Definition at line 142 of file ObjectClass.hpp.
References flags, and HasUninit.
Referenced by RexxInternalObject::clearHasUninit().
clearObjectMark()
void ObjectHeader::clearObjectMark () inline
Definition at line 117 of file ObjectClass.hpp.
References flags, and LiveMask.
Referenced by RexxInternalObject::clearObjectMark(), and setObjectMark().
clearOldSpace()
void ObjectHeader::clearOldSpace () inline
Definition at line 126 of file ObjectClass.hpp.
References flags, and OldSpaceBit.
Referenced by setNewSpace().
getObjectSize()
size_t ObjectHeader::getObjectSize () inline
Definition at line 107 of file ObjectClass.hpp.
References objectSize.
Referenced by RexxInternalObject::getObjectSize(), DeadObject::getObjectSize(), DeadObject::isHeader(), and DeadObject::isReal().
hasNoReferences()
bool ObjectHeader::hasNoReferences () inline
Definition at line 133 of file ObjectClass.hpp.
References flags, and NoRefBit.
Referenced by RexxInternalObject::hasNoReferences().
hasReferences()
bool ObjectHeader::hasReferences () inline
Definition at line 132 of file ObjectClass.hpp.
References flags, and NoRefBit.
Referenced by RexxInternalObject::hasReferences().
hasUninit()
bool ObjectHeader::hasUninit () inline
Definition at line 140 of file ObjectClass.hpp.
References flags, and HasUninit.
Referenced by RexxInternalObject::hasUninit().
initHeader() [1/2]
void ObjectHeader::initHeader (size_t l, size_t mark) inline
Definition at line 146 of file ObjectClass.hpp.
References flags, MemoryObject::mark(), and objectSize.
Referenced by RexxObject::initializeNewObject(), and RexxInternalObject::setInitHeader().
initHeader() [2/2]
void ObjectHeader::initHeader (size_t mark) inline
Definition at line 151 of file ObjectClass.hpp.
References flags, and MemoryObject::mark().
isDeadObject()
bool ObjectHeader::isDeadObject () inline
Definition at line 143 of file ObjectClass.hpp.
References flags.
isNewSpace()
bool ObjectHeader::isNewSpace () inline
Definition at line 129 of file ObjectClass.hpp.
References flags, and OldSpaceBit.
Referenced by RexxInternalObject::isNewSpace().
isNonPrimitive()
bool ObjectHeader::isNonPrimitive () inline
Definition at line 136 of file ObjectClass.hpp.
References flags, and IsNonPrimitive.
Referenced by RexxInternalObject::isNonPrimitive().
isObjectDead()
bool ObjectHeader::isObjectDead (size_t mark) inline
Definition at line 122 of file ObjectClass.hpp.
References flags, MemoryObject::mark(), and MarkMask.
Referenced by RexxInternalObject::isObjectDead().
isObjectLive()
bool ObjectHeader::isObjectLive (size_t mark) inline
Definition at line 121 of file ObjectClass.hpp.
References flags, MemoryObject::mark(), and MarkMask.
Referenced by RexxInternalObject::isObjectLive().
isObjectMarked()
bool ObjectHeader::isObjectMarked (size_t mark) inline
Definition at line 120 of file ObjectClass.hpp.
References flags, and MemoryObject::mark().
Referenced by RexxInternalObject::isObjectMarked().
isOldSpace()
bool ObjectHeader::isOldSpace () inline
Definition at line 128 of file ObjectClass.hpp.
References flags, and OldSpaceBit.
Referenced by RexxInternalObject::isOldSpace().
isPrimitive()
bool ObjectHeader::isPrimitive () inline
Definition at line 137 of file ObjectClass.hpp.
References flags, and IsNonPrimitive.
Referenced by RexxInternalObject::isPrimitive().
isProxyObject()
bool ObjectHeader::isProxyObject () inline
Definition at line 116 of file ObjectClass.hpp.
References flags, and ProxyObject.
Referenced by RexxInternalObject::isProxyObject().
isReadyForUninit()
bool ObjectHeader::isReadyForUninit () inline
Definition at line 139 of file ObjectClass.hpp.
References flags, and UninitPending.
Referenced by RexxInternalObject::isReadyForUninit().
makeProxiedObject()
void ObjectHeader::makeProxiedObject () inline
Definition at line 113 of file ObjectClass.hpp.
References flags, and ProxiedObject.
Referenced by RexxInternalObject::makeProxiedObject().
makeProxyObject()
void ObjectHeader::makeProxyObject () inline
Definition at line 115 of file ObjectClass.hpp.
References flags, and ProxyObject.
Referenced by RexxInternalObject::makeProxyObject().
operator=()
ObjectHeader& ObjectHeader::operator= (ObjectHeader & h) inline
Definition at line 99 of file ObjectClass.hpp.
References flags, and objectSize.
requiresProxyObject()
bool ObjectHeader::requiresProxyObject () inline
Definition at line 114 of file ObjectClass.hpp.
References flags, and ProxiedObject.
Referenced by RexxInternalObject::requiresProxyObject().
setDeadObject()
void ObjectHeader::setDeadObject () inline
Definition at line 144 of file ObjectClass.hpp.
References DeadObject, and flags.
Referenced by DeadObject::DeadObject().
setHasNoReferences()
void ObjectHeader::setHasNoReferences () inline
Definition at line 130 of file ObjectClass.hpp.
References flags, and NoRefBit.
Referenced by RexxInternalObject::setHasNoReferences().
setHasReferences()
void ObjectHeader::setHasReferences () inline
Definition at line 131 of file ObjectClass.hpp.
References flags, and NoRefBit.
Referenced by RexxInternalObject::setHasReferences().
setHasUninit()
void ObjectHeader::setHasUninit () inline
Definition at line 141 of file ObjectClass.hpp.
References flags, and HasUninit.
Referenced by RexxInternalObject::setHasUninit().
setNewSpace()
void ObjectHeader::setNewSpace () inline
Definition at line 127 of file ObjectClass.hpp.
References clearOldSpace().
Referenced by RexxInternalObject::setNewSpace().
setNonPrimitive()
void ObjectHeader::setNonPrimitive () inline
Definition at line 134 of file ObjectClass.hpp.
References flags, and IsNonPrimitive.
Referenced by RexxInternalObject::setNonPrimitive().
setObjectMark()
void ObjectHeader::setObjectMark (size_t mark) inline
Definition at line 118 of file ObjectClass.hpp.
References clearObjectMark(), flags, and MemoryObject::mark().
Referenced by RexxInternalObject::setObjectLive(), and RexxInternalObject::setObjectMark().
setObjectSize()
void ObjectHeader::setObjectSize (size_t l) inline
Definition at line 108 of file ObjectClass.hpp.
References objectSize.
Referenced by DeadObject::DeadObject(), RexxBehaviour::RexxBehaviour(), DeadObject::setObjectSize(), and RexxInternalObject::setObjectSize().
setOldSpace()
void ObjectHeader::setOldSpace () inline
Definition at line 125 of file ObjectClass.hpp.
References flags, and OldSpaceBit.
Referenced by RexxInternalObject::setOldSpace().
setPrimitive()
void ObjectHeader::setPrimitive () inline
Definition at line 135 of file ObjectClass.hpp.
References flags, and IsNonPrimitive.
Referenced by RexxInternalObject::setPrimitive().
setReadyForUninit()
void ObjectHeader::setReadyForUninit () inline
Definition at line 138 of file ObjectClass.hpp.
References flags, and UninitPending.
Referenced by RexxInternalObject::setReadyForUninit().
Friends And Related Function Documentation
MemoryObject
friend class MemoryObject friend
Definition at line 97 of file ObjectClass.hpp.
Member Data Documentation
ObjectHeader::@3 { ... } union
flags
uint16_t ObjectHeader::flags
Definition at line 176 of file ObjectClass.hpp.
Referenced by clear(), clearDeadObject(), clearHasUninit(), clearObjectMark(), clearOldSpace(), hasNoReferences(), hasReferences(), hasUninit(), initHeader(), isDeadObject(), isNewSpace(), isNonPrimitive(), isObjectDead(), isObjectLive(), isObjectMarked(), isOldSpace(), isPrimitive(), isProxyObject(), isReadyForUninit(), makeProxiedObject(), makeProxyObject(), operator=(), requiresProxyObject(), setDeadObject(), setHasNoReferences(), setHasReferences(), setHasUninit(), setNonPrimitive(), setObjectMark(), setOldSpace(), setPrimitive(), and setReadyForUninit().
objectSize
size_t ObjectHeader::objectSize protected
Definition at line 173 of file ObjectClass.hpp.
Referenced by clear(), getObjectSize(), initHeader(), operator=(), and setObjectSize().
sizePadding
uintptr_t ObjectHeader::sizePadding
Definition at line 177 of file ObjectClass.hpp.
The documentation for this class was generated from the following file:
ObjectClass.hpp