ooRexx: TracingMarkHandler Class Reference
TracingMarkHandler Class Reference
#include <RexxMemory.hpp>
Public Member Functions
TracingMarkHandler (MemoryObject *m, size_t mw)
void mark (RexxInternalObject **pMarkObject, RexxInternalObject *markObject) override
Public Attributes
MemoryObject * memory
size_t markWord
Detailed Description
A mark handler for handling general live set tracing
Definition at line 448 of file RexxMemory.hpp.
Constructor & Destructor Documentation
TracingMarkHandler()
TracingMarkHandler::TracingMarkHandler (MemoryObject * m, size_t mw) inline
Definition at line 451 of file RexxMemory.hpp.
Member Function Documentation
mark()
void TracingMarkHandler::mark (RexxInternalObject ** field, RexxInternalObject * object) inline override virtual
Default mark handler mark method.
Parameters
field The field being marked.
object the object value in the field.
Reimplemented from MarkHandler.
Definition at line 454 of file RexxMemory.hpp.
References RexxInternalObject::isObjectLive(), markWord, memory, MemoryObject::pushLiveStack(), and RexxInternalObject::setObjectLive().
Member Data Documentation
markWord
size_t TracingMarkHandler::markWord
Definition at line 469 of file RexxMemory.hpp.
Referenced by mark().
memory
MemoryObject* TracingMarkHandler::memory
Definition at line 468 of file RexxMemory.hpp.
Referenced by mark().
The documentation for this class was generated from the following file:
RexxMemory.hpp