ooRexx: RexxString Class Reference
RexxString Class Reference
#include <StringClass.hpp>
Classes
struct lookupInit
class StringBuilder
class StringBuilderRtL
class WordIterator
Public Types
enum StringFlag {
STRING_HASLOWER , STRING_NOLOWER , STRING_HASUPPER , STRING_NOUPPER ,
STRING_NONNUMERIC
}
Public Member Functions
RexxString ()
RexxString (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *envelope) override
RexxInternalObject * unflatten (Envelope *) override
HashCode getHashValue () override
HashCode getStringHash ()
HashCode getObjectHashCode ()
bool numberValue (wholenumber_t &result, wholenumber_t precision) override
bool numberValue (wholenumber_t &result) override
bool unsignedNumberValue (size_t &result, wholenumber_t precision) override
bool unsignedNumberValue (size_t &result) override
bool doubleValue (double &result) override
NumberString * numberString () override
RexxInteger * integerValue (wholenumber_t) override
RexxString * makeString () override
ArrayClass * makeArray () override
RexxString * primitiveMakeString () override
void copyIntoTail (CompoundVariableTail *buffer) override
RexxString * stringValue () override
bool truthValue (RexxErrorCodes) override
bool logicalValue (logical_t &) override
bool isEqual (RexxInternalObject *) override
bool primitiveIsEqual (RexxObject *)
bool primitiveCaselessIsEqual (RexxObject *)
wholenumber_t strictComp (RexxObject *)
wholenumber_t comp (RexxObject *)
wholenumber_t primitiveStrictComp (RexxObject *)
wholenumber_t stringComp (RexxString *)
wholenumber_t compareTo (RexxInternalObject *) override
RexxObject * equal (RexxObject *)
RexxObject * strictEqual (RexxObject *)
RexxObject * notEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *)
RexxObject * isGreaterThan (RexxObject *)
RexxObject * isLessThan (RexxObject *)
RexxObject * isGreaterOrEqual (RexxObject *)
RexxObject * isLessOrEqual (RexxObject *)
RexxObject * strictGreaterThan (RexxObject *)
RexxObject * strictLessThan (RexxObject *)
RexxObject * strictGreaterOrEqual (RexxObject *)
RexxObject * strictLessOrEqual (RexxObject *)
size_t copyData (size_t, char *, size_t)
RexxObject * lengthRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concat (RexxString *)
RexxString * concatToCstring (const char *)
RexxString * concatWithCstring (const char *)
RexxString * concatBlank (RexxObject *)
bool checkLower ()
bool checkUpper ()
RexxString * upper ()
RexxString * upper (size_t, size_t)
RexxString * upperRexx (RexxInteger *, RexxInteger *)
RexxString * lower ()
RexxString * lower (size_t, size_t)
RexxString * lowerRexx (RexxInteger *, RexxInteger *)
RexxString * stringTrace ()
void setNumberString (NumberString *)
RexxString * concatWith (RexxString *, char)
RexxObject * plus (RexxObject *right)
RexxObject * minus (RexxObject *right)
RexxObject * multiply (RexxObject *right)
RexxObject * divide (RexxObject *right)
RexxObject * integerDivide (RexxObject *right)
RexxObject * remainder (RexxObject *right)
RexxObject * power (RexxObject *right)
RexxObject * abs ()
RexxObject * sign ()
RexxObject * notOp ()
RexxObject * operatorNot (RexxObject *)
RexxObject * andOp (RexxObject *)
RexxObject * orOp (RexxObject *)
RexxObject * xorOp (RexxObject *)
RexxObject * choiceRexx (RexxObject *trueResult, RexxObject *falseResult)
RexxObject * Max (RexxObject **args, size_t argCount)
RexxObject * Min (RexxObject **args, size_t argCount)
RexxObject * modulo (RexxObject *divisor)
RexxObject * trunc (RexxInteger *decimals)
RexxObject * floor ()
RexxObject * ceiling ()
RexxObject * round ()
RexxObject * format (RexxObject *Integers, RexxObject *Decimals, RexxObject *MathExp, RexxObject *ExpTrigger)
RexxObject * logicalOperation (RexxObject *, RexxObject *, unsigned int)
RexxString * extract (size_t offset, size_t sublength)
RexxObject * evaluate (RexxActivation *, ExpressionStack *) override
RexxObject * getValue (RexxActivation *) override
RexxObject * getValue (VariableDictionary *) override
RexxObject * getRealValue (RexxActivation *) override
RexxObject * getRealValue (VariableDictionary *) override
RexxString * center (RexxInteger *, RexxString *)
RexxString * delstr (RexxInteger *, RexxInteger *)
RexxString * insert (RexxString *, RexxInteger *, RexxInteger *, RexxString *)
RexxString * left (RexxInteger *, RexxString *)
RexxString * overlay (RexxString *, RexxInteger *, RexxInteger *, RexxString *)
RexxString * replaceAt (RexxString *, RexxInteger *, RexxInteger *, RexxString *)
RexxString * reverse ()
RexxString * right (RexxInteger *, RexxString *)
RexxString * strip (RexxString *, RexxString *)
RexxString * substr (RexxInteger *, RexxInteger *, RexxString *)
RexxString * brackets (RexxInteger *, RexxInteger *)
RexxString * subchar (RexxInteger *)
RexxString * delWord (RexxInteger *, RexxInteger *)
RexxString * space (RexxInteger *, RexxString *)
RexxString * subWord (RexxInteger *, RexxInteger *)
ArrayClass * subWords (RexxInteger *, RexxInteger *)
RexxString * word (RexxInteger *)
RexxInteger * wordIndex (RexxInteger *)
RexxInteger * wordLength (RexxInteger *)
RexxInteger * wordPos (RexxString *, RexxInteger *)
RexxInteger * caselessWordPos (RexxString *, RexxInteger *)
RexxObject * containsWord (RexxString *, RexxInteger *)
RexxObject * caselessContainsWord (RexxString *, RexxInteger *)
RexxInteger * words ()
RexxString * changeStr (RexxString *, RexxString *, RexxInteger *)
RexxString * caselessChangeStr (RexxString *, RexxString *, RexxInteger *)
RexxObject * abbrev (RexxString *, RexxInteger *)
RexxObject * caselessAbbrev (RexxString *, RexxInteger *)
RexxInteger * compare (RexxString *, RexxString *)
RexxInteger * caselessCompare (RexxString *, RexxString *)
RexxString * copies (RexxInteger *)
RexxObject * dataType (RexxString *)
RexxInteger * lastPosRexx (RexxString *, RexxInteger *, RexxInteger *)
RexxInteger * caselessLastPosRexx (RexxString *, RexxInteger *, RexxInteger *)
size_t lastPos (RexxString *needle, size_t start)
size_t caselessLastPos (RexxString *needle, size_t start)
const char * caselessLastPos (const char *needle, size_t needleLen, const char *haystack, size_t haystackLen)
RexxInteger * posRexx (RexxString *, RexxInteger *, RexxInteger *)
RexxInteger * caselessPosRexx (RexxString *, RexxInteger *, RexxInteger *)
RexxObject * containsRexx (RexxString *, RexxInteger *, RexxInteger *)
RexxObject * caselessContains (RexxString *, RexxInteger *, RexxInteger *)
size_t pos (RexxString *, size_t)
size_t caselessPos (RexxString *, size_t)
RexxString * translate (RexxString *, RexxString *, RexxString *, RexxInteger *, RexxInteger *)
RexxInteger * verify (RexxString *, RexxString *, RexxInteger *, RexxInteger *)
RexxInteger * countStrRexx (RexxString *)
RexxInteger * caselessCountStrRexx (RexxString *)
size_t caselessCountStr (RexxString *)
RexxString * bitAnd (RexxString *, RexxString *)
RexxString * bitOr (RexxString *, RexxString *)
RexxString * bitXor (RexxString *, RexxString *)
RexxString * b2x ()
RexxString * c2d (RexxInteger *)
RexxString * c2x ()
RexxString * encodeBase64 ()
RexxString * decodeBase64 ()
RexxString * d2c (RexxInteger *)
RexxString * d2x (RexxInteger *)
RexxString * x2b ()
RexxString * x2c ()
RexxString * x2d (RexxInteger *)
RexxString * x2dC2d (RexxInteger *, bool)
RexxObject * match (RexxInteger *start_, RexxString *other, RexxInteger *offset_, RexxInteger *len_)
RexxObject * caselessMatch (RexxInteger *start_, RexxString *other, RexxInteger *offset_, RexxInteger *len_)
RexxObject * startsWithRexx (RexxString *other)
RexxObject * endsWithRexx (RexxString *other)
RexxObject * caselessStartsWithRexx (RexxString *other)
RexxObject * caselessEndsWithRexx (RexxString *other)
bool primitiveMatch (size_t start, RexxString *other, size_t offset, size_t len)
bool primitiveCaselessMatch (size_t start, RexxString *other, size_t offset, size_t len)
RexxObject * matchChar (RexxInteger *position_, RexxString *matchSet)
RexxObject * caselessMatchChar (RexxInteger *position_, RexxString *matchSet)
RexxInteger * compareToRexx (RexxString *other, RexxInteger *start_, RexxInteger *len_)
RexxInteger * caselessCompareToRexx (RexxString *other, RexxInteger *start_, RexxInteger *len_)
wholenumber_t primitiveCompareTo (RexxString *other, size_t start, size_t len)
wholenumber_t primitiveCaselessCompareTo (RexxString *other, size_t start, size_t len)
wholenumber_t primitiveCompareTo (RexxString *other)
wholenumber_t primitiveCaselessCompareTo (RexxString *other)
RexxObject * equals (RexxString *other)
RexxObject * caselessEquals (RexxString *other)
ArrayClass * makeArrayRexx (RexxString *)
StringSymbolType isSymbol ()
RexxString * baseString ()
size_t getLength () const
bool isNullString () const
void setLength (size_t l)
void finish (size_t l)
const char * getStringData () const
char * getWritableData ()
void put (size_t s, const void *b, size_t l)
void put (size_t s, RexxString *o)
void set (size_t s, int c, size_t l)
char getChar (size_t p) const
char putChar (size_t p, char c)
bool upperOnly () const
bool hasLower () const
void setUpperOnly ()
void setHasLower ()
bool lowerOnly () const
bool hasUpper () const
void setLowerOnly ()
void setHasUpper ()
bool nonNumeric () const
void setNonNumeric ()
bool strCompare (const char *s) const
bool strCaselessCompare (const char *s) const
bool strCaselessCompare (RexxString *s) const
bool memCompare (const char *s, size_t l) const
bool memCompare (RexxString *other) const
bool strCompare (RexxString *other) const
void memCopy (char *s) const
void toRxstring (CONSTRXSTRING &r)
void toRxstring (RXSTRING &r)
void copyToRxstring (RXSTRING &r)
bool endsWith (char c) const
bool startsWith (char c) const
bool startsWith (const char *c) const
int sortCompare (RexxString *other)
int sortCaselessCompare (RexxString *other)
int sortCompare (RexxString *other, size_t startCol, size_t colLength)
int sortCaselessCompare (RexxString *other, size_t startCol, size_t colLength)
RexxString * newRexx (RexxObject **, size_t)
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxInternalObject * copy () override
HashCode hash () override
RexxString * stringValue () override
virtual void processUnknown (RexxErrorCodes, RexxString *, RexxObject **, size_t, ProtectedObject &)
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
HashCode identityHash ()
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Static Public Member Functions
static char intToHexDigit (int n)
static int hexDigitToInt (char ch)
static char packByte2 (const char *bytes)
static RexxString * newString (const char *, size_t)
static RexxString * newString (const char *, size_t, const char *, size_t)
static RexxString * rawString (size_t)
static RexxString * newUpperString (const char *, size_t)
static RexxString * newString (double d)
static RexxString * newString (double d, size_t precision)
static RexxString * newProxy (const char *)
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
static const char STRIP_BOTH = 'B'
static const char STRIP_LEADING = 'L'
static const char STRIP_TRAILING = 'T'
static const char DATATYPE_ALPHANUMERIC = 'A'
static const char DATATYPE_BINARY = 'B'
static const char DATATYPE_INTERNAL_WHOLE = 'I'
static const char DATATYPE_LOWERCASE = 'L'
static const char DATATYPE_MIXEDCASE = 'M'
static const char DATATYPE_NUMBER = 'N'
static const char DATATYPE_SYMBOL = 'S'
static const char DATATYPE_VARIABLE = 'V'
static const char DATATYPE_UPPERCASE = 'U'
static const char DATATYPE_WHOLE_NUMBER = 'W'
static const char DATATYPE_HEX = 'X'
static const char DATATYPE_9DIGITS = '9'
static const char DATATYPE_LOGICAL = 'O'
static const char VERIFY_MATCH = 'M'
static const char VERIFY_NOMATCH = 'N'
static const char ch_SPACE = ' '
static const char ch_TAB = '\t'
static const char ch_MINUS ='-'
static const char ch_PLUS ='+'
static const char ch_PERIOD ='.'
static const char ch_ZERO ='0'
static const char ch_ONE ='1'
static const char ch_FIVE ='5'
static const char ch_NINE ='9'
static const char * DIGITS_HEX = "0123456789ABCDEFabcdef"
static const char * ALPHANUM = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
static const char * DIGITS_BIN = "01"
static const char * LOWER_ALPHA = "abcdefghijklmnopqrstuvwxyz"
static const char * MIXED_ALPHA = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
static const char * UPPER_ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
static const char * DIGITS_BASE64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
static const char * ALNUM = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
static const char * ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
static const char * BLANK = "\t "
static const char * CNTRL = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x7f"
static const char * DIGIT = "0123456789"
static const char * GRAPH = "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
static const char * LOWER = RexxString::LOWER_ALPHA
static const char * PRINT = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
static const char * PUNCT = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
static const char * SPACE = "\t\n\v\f\r "
static const char * UPPER = RexxString::UPPER_ALPHA
static const char * XDIGIT = "0123456789ABCDEFabcdef"
static struct RexxString::lookupInit lookupInitializer
static char DIGITS_HEX_LOOKUP [256]
static char DIGITS_BASE64_LOOKUP [256]
static char DIGITS_BIN_LOOKUP [256]
static char ALPHANUM_LOOKUP [256]
static char LOWER_ALPHA_LOOKUP [256]
static char MIXED_ALPHA_LOOKUP [256]
static char UPPER_ALPHA_LOOKUP [256]
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
HashCode hashValue
size_t length
NumberString * numberStringValue
FlagSet< StringFlag, 32 > attributes
char stringData [4]
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 68 of file StringClass.hpp.
Member Enumeration Documentation
StringFlag
enum RexxString::StringFlag
Enumerator
STRING_HASLOWER
STRING_NOLOWER
STRING_HASUPPER
STRING_NOUPPER
STRING_NONNUMERIC
Definition at line 71 of file StringClass.hpp.
Constructor & Destructor Documentation
RexxString() [1/2]
RexxString::RexxString () inline
Definition at line 318 of file StringClass.hpp.
Referenced by newString(), newUpperString(), and rawString().
RexxString() [2/2]
RexxString::RexxString (RESTORETYPE restoreType) inline
Definition at line 319 of file StringClass.hpp.
Member Function Documentation
abbrev()
RexxObject * RexxString::abbrev (RexxString * info, RexxInteger * _length)
Test is a string is an abbreviation of a target string.
Parameters
info The test string. We're testing if info is an abbreviation of the receiving string.
_length The minumum length for being a valid abbreviation.
Returns
.true if this qualfies as an abbreviation, .false if not.
Definition at line 75 of file StringClassMisc.cpp.
References ARG_ONE, ARG_TWO, booleanObject(), getLength(), getStringData(), optionalLengthArgument(), stringArgument(), TheFalseObject, and TheTrueObject.
Referenced by BUILTIN(), and MemoryObject::createImage().
abs()
RexxObject * RexxString::abs ()
String absolute value...performed by NumberString
Returns
The absolute value result.
Definition at line 1073 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by BUILTIN(), and MemoryObject::createImage().
andOp()
RexxObject * RexxString::andOp (RexxObject * other)
Logical AND of a string with another logical value
Parameters
other The other value for the AND.
Returns
Either .true or .false
Definition at line 1957 of file StringClass.cpp.
References ARG_ONE, booleanObject(), Error_Logical_value_method, requiredArgument(), RexxInternalObject::truthValue(), and truthValue().
Referenced by NumberString::andOp(), and MemoryObject::createImage().
b2x()
RexxString * RexxString::b2x ()
Perform a B2X conversion on a character string.
Returns
The converted string value.
Definition at line 636 of file StringClassConversion.cpp.
References StringUtil::copyGroupedChars(), DIGITS_BIN_LOOKUP, getLength(), getStringData(), getWritableData(), isNullString(), length, StringUtil::packNibble(), raw_string(), and StringUtil::validateGroupedSet().
Referenced by MemoryObject::createImage().
baseString()
RexxString* RexxString::baseString () inline
Definition at line 537 of file StringClass.hpp.
References RexxInternalObject::isBaseClass(), and RexxInternalObject::requestString().
Referenced by logicalValue(), and truthValue().
bitAnd()
RexxString * RexxString::bitAnd (RexxString * string2, RexxString * pad)
String method for performing a BITAND operation.
Parameters
string2 The string to AND with (optional)
pad The optional pad character.
Returns
The ANDed string.
Definition at line 58 of file StringClassBit.cpp.
References ARG_ONE, ARG_TWO, getLength(), getStringData(), getWritableData(), optionalPadArgument(), optionalStringArgument(), and raw_string().
Referenced by BUILTIN(), and MemoryObject::createImage().
bitOr()
RexxString * RexxString::bitOr (RexxString * string2, RexxString * pad)
String method for performing a BITOR operation.
Parameters
string2 The string to OR with (optional)
pad The optional pad character.
Returns
The ORed string.
Definition at line 136 of file StringClassBit.cpp.
References ARG_ONE, ARG_TWO, getLength(), getStringData(), getWritableData(), optionalPadArgument(), optionalStringArgument(), and raw_string().
Referenced by BUILTIN(), and MemoryObject::createImage().
bitXor()
RexxString * RexxString::bitXor (RexxString * string2, RexxString * pad)
String method for performing a BITXOR operation.
Parameters
string2 The string to XOR with (optional)
pad The optional pad character.
Returns
The XORed string.
Definition at line 212 of file StringClassBit.cpp.
References ARG_ONE, ARG_TWO, getLength(), getStringData(), getWritableData(), optionalPadArgument(), optionalStringArgument(), and raw_string().
Referenced by BUILTIN(), and MemoryObject::createImage().
brackets()
RexxString * RexxString::brackets (RexxInteger * position, RexxInteger * _length)
Extract a substring from a target string, using brackets syntax.
Parameters
position The starting position of the extracted string.
_length The length to extract.
pad A padding character for padding out to the length, if necessary.
Returns
The extracted string value.
Definition at line 617 of file StringClassSub.cpp.
References getLength(), getStringData(), and StringUtil::substr().
Referenced by MemoryObject::createImage().
c2d()
RexxString * RexxString::c2d (RexxInteger * _length)
Common C2D processing routine
Parameters
_length The optional explicit length
Returns
The converted string.
Definition at line 375 of file StringClassConversion.cpp.
References x2dC2d().
Referenced by MemoryObject::createImage().
c2x()
RexxString * RexxString::c2x ()
Process the string C2X method/function
Returns
The character string, converted into its hex equivalent.
Definition at line 258 of file StringClassConversion.cpp.
References getLength(), getStringData(), getWritableData(), intToHexDigit(), and raw_string().
Referenced by MemoryObject::createImage().
caselessAbbrev()
RexxObject * RexxString::caselessAbbrev (RexxString * info, RexxInteger * _length)
Test is a string is an abbreviation of a target string.
Parameters
info The test string. We're testing if info is an abbreviation of the receiving string.
_length The minumum length for being a valid abbreviation.
Returns
.true if this qualfies as an abbreviation, .false if not.
Definition at line 117 of file StringClassMisc.cpp.
References ARG_ONE, ARG_TWO, booleanObject(), StringUtil::caselessCompare(), getLength(), getStringData(), optionalLengthArgument(), stringArgument(), TheFalseObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
caselessChangeStr()
RexxString * RexxString::caselessChangeStr (RexxString * needle, RexxString * newNeedle, RexxInteger * countArg)
Change occurrences of values in a string into another value.
Parameters
needle The search needle we're changing.
newNeedle The replacement string
countArg The optional count of occurrences to change.
Returns
A new string with the replacements made.
Definition at line 516 of file StringClassMisc.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessCountStr(), caselessPos(), getLength(), getStringData(), Numerics::MAX_WHOLENUMBER, optionalNonNegative(), raw_string(), RexxObject::start(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessCompare()
RexxInteger * RexxString::caselessCompare (RexxString * other, RexxString * pad)
Caseless version of the compare() method.
Parameters
string2 The string to compare to.
pad The padding character used for length mismatches.
Returns
0 if the two strings are equal (with padding applied), otherwise it returns the mismatch position.
Definition at line 224 of file StringClassMisc.cpp.
References ARG_ONE, ARG_TWO, getLength(), getStringData(), IntegerZero, new_integer(), optionalPadArgument(), stringArgument(), and Utilities::toUpper().
Referenced by MemoryObject::createImage().
caselessCompareToRexx()
RexxInteger * RexxString::caselessCompareToRexx (RexxString * other, RexxInteger * start_, RexxInteger * len_)
Do a sorting comparison of two strings.
Parameters
other The other compare string.
start_ The starting compare position within the target string.
len_ The length of the compare substring.
Returns
True if the two regions match, false for any mismatch.
Definition at line 1204 of file StringClassMisc.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, getLength(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), primitiveCaselessCompareTo(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessContains()
RexxObject * RexxString::caselessContains (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Do a caseless search for one string in another.
Parameters
needle The search string.
pstart The starting position for the search.
range A maximum range for the search.
Returns
.true if the string is found, .false otherwise.
Definition at line 632 of file StringClassMisc.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, booleanObject(), StringUtil::caselessPos(), getLength(), getStringData(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessContainsWord()
RexxObject * RexxString::caselessContainsWord (RexxString * phrase, RexxInteger * pstart)
Perform a caseless wordpos search on a string object.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 298 of file StringClassWord.cpp.
References booleanObject(), StringUtil::caselessWordPos(), getLength(), and getStringData().
Referenced by MemoryObject::createImage().
caselessCountStr()
size_t RexxString::caselessCountStr (RexxString *)
caselessCountStrRexx()
RexxInteger * RexxString::caselessCountStrRexx (RexxString * needle)
Caselessly count occurrences of one string in another.
Parameters
needle The search needle.
Returns
The string count.
Definition at line 434 of file StringClassMisc.cpp.
References ARG_ONE, StringUtil::caselessCountStr(), getLength(), getStringData(), Numerics::MAX_WHOLENUMBER, new_integer(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessEndsWithRexx()
RexxObject * RexxString::caselessEndsWithRexx (RexxString * other)
Test if a string ends with another string
Parameters
other The other compare string.
Returns
True if the string starts with the other, false otherwise.
Definition at line 923 of file StringClassMisc.cpp.
References booleanObject(), getLength(), primitiveCaselessMatch(), stringArgument(), and TheFalseObject.
Referenced by MemoryObject::createImage().
caselessEquals()
RexxObject * RexxString::caselessEquals (RexxString * other)
The string equals() method, which does a strict caseless compare with another string object.
Parameters
other The other string object.
Returns
True if the strings are equal, false for inequality.
Definition at line 1214 of file StringClass.cpp.
References booleanObject(), and primitiveCaselessIsEqual().
Referenced by MemoryObject::createImage().
caselessLastPos() [1/2]
const char* RexxString::caselessLastPos (const char * needle, size_t needleLen, const char * haystack, size_t haystackLen)
caselessLastPos() [2/2]
size_t RexxString::caselessLastPos (RexxString * needle, size_t _start)
Primitive implementation of a caseless lastpos search.
Parameters
needle The search needle.
start The starting position (origin 1).
Returns
Returns the last match position, searching back from the start position. The starting position is the right-most character of the past possible match (as if the string was truncated at start).
Definition at line 406 of file StringClassMisc.cpp.
References StringUtil::caselessLastPos(), getLength(), and getStringData().
caselessLastPosRexx()
RexxInteger * RexxString::caselessLastPosRexx (RexxString * needle, RexxInteger * _start, RexxInteger * _range)
Rexx exported version of the caselessLastPos() method.
Parameters
needle The search needle.
_start The starting position.
Returns
The match position. 0 means not found.
Definition at line 366 of file StringClassMisc.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessLastPos(), getLength(), getStringData(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessMatch()
RexxObject * RexxString::caselessMatch (RexxInteger * start_, RexxString * other, RexxInteger * offset_, RexxInteger * len_)
Test if regions within two strings match.
Parameters
start_ The starting compare position within the target string. This must be within the bounds of the string.
other The other compare string.
offset_ The starting offset of the compare string. This must be within the string bounds. The default start postion is 1.
len_ The length of the compare substring. The length and the offset must specify a valid substring of other. If not specified, this defaults to the substring from the offset to the end of the string.
Returns
True if the two regions match, false for any mismatch.
Definition at line 837 of file StringClassMisc.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, booleanObject(), getLength(), optionalLengthArgument(), optionalPositionArgument(), OREF_NULL, positionArgument(), primitiveCaselessMatch(), stringArgument(), and TheFalseObject.
Referenced by MemoryObject::createImage().
caselessMatchChar()
RexxObject * RexxString::caselessMatchChar (RexxInteger * position_, RexxString * matchSet)
Compare a single character at a give position against a set of characters to see if any of the characters is a match.
Parameters
position_ The character position
matchSet The set to compare against.
Returns
true if the character at the give position is any of the characters, false if none of them match.
Definition at line 1038 of file StringClassMisc.cpp.
References ARG_ONE, ARG_TWO, getChar(), getLength(), positionArgument(), stringArgument(), TheFalseObject, TheTrueObject, and Utilities::toUpper().
Referenced by MemoryObject::createImage().
caselessPos()
size_t RexxString::caselessPos (RexxString * needle, size_t _start)
Do a primitive level pos() search on a string.
Parameters
needle The search needle.
_start The starting position (origin 0)
Returns
The match position (origin 1). Returns 0 for no match.
Definition at line 664 of file StringClassMisc.cpp.
References StringUtil::caselessPos(), getLength(), and getStringData().
Referenced by caselessChangeStr().
caselessPosRexx()
RexxInteger * RexxString::caselessPosRexx (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Do a caseless search for one string in another.
Parameters
needle The search string.
pstart The starting position for the search.
range A maximum range for the search.
Returns
The index of any match position, or 0 if not found.
Definition at line 612 of file StringClassMisc.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::caselessPos(), getLength(), getStringData(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessStartsWithRexx()
RexxObject * RexxString::caselessStartsWithRexx (RexxString * other)
Test if a string starts with another string
Parameters
other The other compare string.
Returns
True if the string starts with the other, false otherwise.
Definition at line 888 of file StringClassMisc.cpp.
References booleanObject(), getLength(), primitiveCaselessMatch(), and stringArgument().
Referenced by MemoryObject::createImage().
caselessWordPos()
RexxInteger * RexxString::caselessWordPos (RexxString * phrase, RexxInteger * pstart)
Perform a caseless wordpos search on a string object.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 284 of file StringClassWord.cpp.
References StringUtil::caselessWordPos(), getLength(), getStringData(), and new_integer().
Referenced by MemoryObject::createImage().
ceiling()
RexxObject * RexxString::ceiling ()
The String class version of the ceiling method.
Returns
The formatted numeric version.
Definition at line 1160 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by MemoryObject::createImage().
center()
RexxString * RexxString::center (RexxInteger * _length, RexxString * pad)
The center/centre method for the string class.
Parameters
_length The length to center in.
pad The optional pad character
Returns
The centered string.
Definition at line 59 of file StringClassSub.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, ARG_TWO, getLength(), getStringData(), lengthArgument(), new_string(), optionalPadArgument(), RexxString::StringBuilder::pad(), and raw_string().
Referenced by MemoryObject::createImage().
changeStr()
RexxString * RexxString::changeStr (RexxString * needle, RexxString * newNeedle, RexxInteger * countArg)
Change occurrences of values in a string into another value.
Parameters
needle The search needle we're changing.
newNeedle The replacement string
countArg The optional count of occurrences to change.
Returns
A new string with the replacements made.
Definition at line 451 of file StringClassMisc.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, ARG_THREE, ARG_TWO, StringUtil::countStr(), getLength(), getStringData(), Numerics::MAX_WHOLENUMBER, optionalNonNegative(), pos(), raw_string(), RexxObject::start(), and stringArgument().
Referenced by BUILTIN(), and MemoryObject::createImage().
checkLower()
bool RexxString::checkLower ()
Tests for existence of lowercase characters
Returns
true if this string contains lowercase characters, false otherwise.
Definition at line 1538 of file StringClass.cpp.
References getLength(), getStringData(), Utilities::isLower(), setHasLower(), and setUpperOnly().
Referenced by upper().
checkUpper()
bool RexxString::checkUpper ()
Tests for existence of uppercase characters
Returns
true if this string contains uppercase characters, false otherwise.
Definition at line 1567 of file StringClass.cpp.
References getLength(), getStringData(), Utilities::isUpper(), setHasUpper(), and setLowerOnly().
Referenced by lower().
choiceRexx()
RexxObject * RexxString::choiceRexx (RexxObject * trueResult, RexxObject * falseResult)
Implement an expression choice method. The target object is evaluated as a logical value, and if it evaluates to true, returns the first argument as a result. If it evaluates to false, it returns the second argument.
Parameters
trueResult The value to return for a true result.
falseResult The falue to return for a false result
Returns
Either the true value or the false value based on the value of the target object.
Definition at line 2014 of file StringClass.cpp.
References Error_Logical_value_method, requiredArgument(), and truthValue().
Referenced by MemoryObject::createImage().
comp()
wholenumber_t RexxString::comp (RexxObject * other)
Do a value comparison of two strings for the non-strict comparisons. This returns for the compares:
a value < 0 when this is smaller than other a value 0 when this is equal to other a value > 0 when this is larger than other
Parameters
other The object we compare against.
Returns
the relative compare value (<0, 0, or >0)
Definition at line 753 of file StringClass.cpp.
References ARG_ONE, NumberString::comp(), number_fuzz(), RexxInternalObject::numberString(), numberString(), OREF_NULL, RexxInternalObject::requestString(), requiredArgument(), and stringComp().
Referenced by equal(), isGreaterOrEqual(), isGreaterThan(), isLessOrEqual(), isLessThan(), and notEqual().
compare()
RexxInteger * RexxString::compare (RexxString * other, RexxString * pad)
Compare two strings, returning the point where they differ.
Parameters
string2 the other comparison string.
pad The optional pad character.
Returns
The point of mismatch, or 0 if the two strings compare equal.
Definition at line 159 of file StringClassMisc.cpp.
References ARG_ONE, ARG_TWO, getLength(), getStringData(), IntegerZero, new_integer(), optionalPadArgument(), and stringArgument().
Referenced by BUILTIN(), and MemoryObject::createImage().
compareTo()
wholenumber_t RexxString::compareTo (RexxInternalObject * other) override virtual
Wrapper around the compareTo() method for doing sort comparisons of strings.
Parameters
other The other comparison object
Returns
-1, 0, 1 depending on the comparison result.
Reimplemented from RexxInternalObject.
Definition at line 727 of file StringClass.cpp.
References ARG_ONE, RexxInternalObject::compareTo(), RexxInternalObject::isBaseClass(), primitiveCompareTo(), and stringArgument().
Referenced by RexxInteger::compareTo(), and NumberString::compareTo().
compareToRexx()
RexxInteger * RexxString::compareToRexx (RexxString * other, RexxInteger * start_, RexxInteger * len_)
Do a sorting comparison of two strings.
Parameters
other The other compare string.
start_ The starting compare position within the target string.
len_ The length of the compare substring.
Returns
True if the two regions match, false for any mismatch.
Definition at line 1075 of file StringClassMisc.cpp.
References ARG_ONE, ARG_THREE, ARG_TWO, getLength(), new_integer(), optionalLengthArgument(), optionalPositionArgument(), primitiveCompareTo(), and stringArgument().
Referenced by MemoryObject::createImage().
concat()
RexxString * RexxString::concat (RexxString * other)
Concatenate two strings together.
Parameters
other the other string.
Returns
The concatenation result.
Definition at line 1328 of file StringClass.cpp.
References RexxString::StringBuilder::append(), getLength(), getStringData(), and raw_string().
Referenced by LanguageParser::constantDirective(), CompoundTableElement::createCompoundName(), Activity::displayDebug(), RexxExpressionMessage::makeAssignment(), LanguageParser::processAnnotation(), and RexxActivation::traceCompoundName().
concatBlank()
RexxString * RexxString::concatBlank (RexxObject * otherObj)
Concatenate two strings with a blank in between
Parameters
otherObj The other string.
Returns
The concatenated strings.
Definition at line 1446 of file StringClass.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, getLength(), getStringData(), raw_string(), RexxInternalObject::requestString(), and requiredArgument().
Referenced by NumberString::concatBlank(), RexxObject::concatBlank(), RexxInteger::concatBlank(), and MemoryObject::createImage().
concatRexx()
RexxString * RexxString::concatRexx (RexxObject * otherObj)
Rexx level concatenate...requires conversion and checking
Parameters
otherObj The other object for concatenation.
Returns
The concatenation result.
Definition at line 1363 of file StringClass.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, getLength(), getStringData(), raw_string(), RexxInternalObject::requestString(), and requiredArgument().
Referenced by NumberString::concat(), RexxInteger::concat(), RexxObject::concatRexx(), and MemoryObject::createImage().
concatToCstring()
RexxString * RexxString::concatToCstring (const char * other)
Concatenate a string object onto an ASCII-Z string
Parameters
other The ASCII-Z string we're concatenating with. Note, these are used internally, so we're assuming neither part is a null string.
Returns
The concatenate result.
Definition at line 1405 of file StringClass.cpp.
References RexxString::StringBuilder::append(), getLength(), getStringData(), and raw_string().
Referenced by BUILTIN(), LanguageParser::callOnNew(), RexxActivation::command(), RexxClass::defaultName(), RexxObject::defaultName(), RexxDotVariable::evaluate(), RexxDotVariable::getValue(), LanguageParser::raiseNew(), RexxActivation::rexxVariable(), and LanguageParser::signalOnNew().
concatWith()
RexxString * RexxString::concatWith (RexxString * other, char between)
Concatenate two strings with a single character between
Parameters
other The other string.
between The separator character.
Returns
The concatenated string result.
Definition at line 1932 of file StringClass.cpp.
References RexxString::StringBuilder::append(), getLength(), getStringData(), and raw_string().
Referenced by Activity::displayDebug(), and RexxActivation::traceClassResolution().
concatWithCstring()
RexxString * RexxString::concatWithCstring (const char * other)
Concatenate an ASCII-Z string onto a string object
Parameters
other The ASCII-Z string to concatenate.
Returns
The concatenated string.
Definition at line 1425 of file StringClass.cpp.
References RexxString::StringBuilder::append(), getLength(), getStringData(), and raw_string().
Referenced by LanguageParser::attributeDirective(), RexxActivation::command(), RexxClass::defaultName(), Activity::displayDebug(), NativeActivation::getContextStem(), LanguageParser::methodDirective(), and LanguageParser::processAttributeAnnotations().
containsRexx()
RexxObject * RexxString::containsRexx (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Test if a string contains a given string within a specified range.
Parameters
needle The search needle
pstart The starting search position.
range The length of the range
Returns
.true if the string is found, .false otherwise.
Definition at line 597 of file StringClassMisc.cpp.
References StringUtil::containsRexx(), getLength(), and getStringData().
Referenced by MemoryObject::createImage().
containsWord()
RexxObject * RexxString::containsWord (RexxString * phrase, RexxInteger * pstart)
Test if a string contains a given phrase
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 270 of file StringClassWord.cpp.
References booleanObject(), getLength(), getStringData(), and StringUtil::wordPos().
Referenced by MemoryObject::createImage().
copies()
RexxString * RexxString::copies (RexxInteger * _copies)
The copies method.
Parameters
_copies The number of copies of the string to make.
Returns
The string with the copies.
Definition at line 288 of file StringClassMisc.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, getLength(), getStringData(), nonNegativeArgument(), and raw_string().
Referenced by MemoryObject::createImage().
copyData()
size_t RexxString::copyData (size_t startPos, char * buffer, size_t bufl)
Get a section of a string and copy it into a buffer
Parameters
startPos The starting offset within the string.
buffer the location to copy to.
bufl The size of the buffer.
Returns
The actualy length copied.
Definition at line 599 of file StringClass.cpp.
References getLength(), and getStringData().
Referenced by StringGet().
copyIntoTail()
void RexxString::copyIntoTail (CompoundVariableTail * tail) override virtual
Copy a string value into to a compound variable tail.
Parameters
tail The target tail object.
Reimplemented from RexxInternalObject.
Definition at line 385 of file StringClass.cpp.
References CompoundVariableTail::append(), getLength(), and getStringData().
Referenced by CompoundVariableTail::buildTail(), CompoundVariableTail::buildUnresolvedTail(), RexxInteger::copyIntoTail(), and RexxInternalObject::copyIntoTail().
copyToRxstring()
void RexxString::copyToRxstring (RXSTRING & r)
Copy a string to an RXSTRING, with appropriate allocation of a new buffer if required.
Parameters
r
Definition at line 2088 of file StringClass.cpp.
References SystemInterpreter::allocateResultMemory(), getLength(), getStringData(), _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by RexxStartDispatcher::run().
countStrRexx()
RexxInteger * RexxString::countStrRexx (RexxString * needle)
Count occurrences of one string in another.
Parameters
needle The string we're counting
Returns
The count of occurrences in the target string.
Definition at line 419 of file StringClassMisc.cpp.
References ARG_ONE, StringUtil::countStr(), getLength(), getStringData(), Numerics::MAX_WHOLENUMBER, new_integer(), and stringArgument().
Referenced by BUILTIN(), and MemoryObject::createImage().
createInstance()
void RexxString::createInstance () static
Create initial class object at bootstrap time.
Definition at line 197 of file StringClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
d2c()
RexxString * RexxString::d2c (RexxInteger * _length)
Process the string D2C method/function
Parameters
_length The optional length argument.
Returns
The converted string.
Definition at line 298 of file StringClassConversion.cpp.
References NumberString::d2xD2c(), Error_Incorrect_method_d2c, numberString(), OREF_NULL, and reportException().
Referenced by MemoryObject::createImage().
d2x()
RexxString * RexxString::d2x (RexxInteger * _length)
Process the string D2X method/function
Parameters
_length The optional length argument.
Returns
The converted string value.
Definition at line 320 of file StringClassConversion.cpp.
References NumberString::d2xD2c(), Error_Incorrect_method_d2x, numberString(), OREF_NULL, and reportException().
Referenced by MemoryObject::createImage().
dataType()
RexxObject * RexxString::dataType (RexxString * pType)
String class DATATYPE method
Parameters
pType The requested type.
Returns
if a type is specified, returns .true or .false based on the type match. Otherwise, returns "NUM" or "CHAR".
Definition at line 328 of file StringClassMisc.cpp.
References ARG_ONE, StringUtil::dataType(), optionalOptionArgument(), OREF_NULL, TheTrueObject, and type.
Referenced by MemoryObject::createImage().
decodeBase64()
RexxString * RexxString::decodeBase64 ()
Reverse the effect of an encodebase64 operation, converting a string in Base64 format into a "normal" character string. This supports Base64 encoding as described by RFC 2045, but does not allow (ignore) characters outside of the base64 alphabet. See https://tools.ietf.org/html/rfc2045#page-24
Returns
The converted character string.
Definition at line 153 of file StringClassConversion.cpp.
References DIGITS_BASE64_LOOKUP, Error_Incorrect_method_invbase64, getLength(), getStringData(), getWritableData(), raw_string(), and reportException().
Referenced by MemoryObject::createImage().
delstr()
RexxString * RexxString::delstr (RexxInteger * position, RexxInteger * _length)
The delstr() method of the string class.
Parameters
position The starting postion
_length The length to delete.
Returns
The string after the deletion.
Definition at line 117 of file StringClassSub.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, ARG_TWO, getLength(), getStringData(), optionalLengthArgument(), optionalPositionArgument(), and raw_string().
Referenced by MemoryObject::createImage().
delWord()
RexxString * RexxString::delWord (RexxInteger * position, RexxInteger * plength)
Delete a word from a given postion.
Parameters
position The target word position.
plength The number of words to delete.
Returns
The string with the range of words deleted.
Definition at line 58 of file StringClassWord.cpp.
References RexxString::StringBuilder::append(), RexxString::WordIterator::appendRemainder(), ARG_ONE, ARG_TWO, getStringData(), isNullString(), RexxString::WordIterator::length(), Numerics::MAX_WHOLENUMBER, optionalLengthArgument(), positionArgument(), raw_string(), RexxString::WordIterator::skipBlanks(), RexxString::WordIterator::skipWords(), RexxString::WordIterator::wordPointer(), and wordPos().
Referenced by MemoryObject::createImage().
divide()
RexxObject * RexxString::divide (RexxObject * right_term)
String division...performed by NumberString
Parameters
right_term The other operator term.
Returns
The operator result
Definition at line 1011 of file StringClass.cpp.
References ArithmeticOperator.
Referenced by MemoryObject::createImage().
doubleValue()
bool RexxString::doubleValue (double & result) override virtual
Convert a string object to a double value. Returns false if it will not convert.
Parameters
result the return whole number result
Returns
true if this converted successfully.
Reimplemented from RexxInternalObject.
Definition at line 510 of file StringClass.cpp.
References NumberString::doubleValue(), numberString(), OREF_NULL, and strCompare().
Referenced by RexxInternalObject::doubleValue().
encodeBase64()
RexxString * RexxString::encodeBase64 ()
Convert the character string into the same string with the characters converted into a Base64 encoding.
Returns
The string reformatted into a Base64 encoding.
Definition at line 60 of file StringClassConversion.cpp.
References DIGITS_BASE64, getLength(), getStringData(), getWritableData(), and raw_string().
Referenced by MemoryObject::createImage().
endsWith()
bool RexxString::endsWith (char c) const inline
Definition at line 569 of file StringClass.hpp.
References length, and stringData.
Referenced by CompoundVariableTail::buildTail(), OutputRedirector::flushBuffer(), NativeActivation::getContextStem(), RexxVariable::isStem(), OutputRedirector::resolveBuffer(), and StringHashCollection::unknown().
endsWithRexx()
RexxObject * RexxString::endsWithRexx (RexxString * other)
Test if a string ends with another string
Parameters
other The other compare string.
Returns
True if the string starts with the other, false otherwise.
Definition at line 902 of file StringClassMisc.cpp.
References booleanObject(), getLength(), primitiveMatch(), stringArgument(), and TheFalseObject.
Referenced by MemoryObject::createImage().
equal()
RexxObject * RexxString::equal (RexxObject * other)
Definition at line 1256 of file StringClass.cpp.
References comp(), and CompareOperator.
Referenced by MemoryObject::createImage().
equals()
RexxObject * RexxString::equals (RexxString * other)
The string equals() method, which does a strict compare with another string object.
Parameters
other The other string object.
Returns
True if the strings are equal, false for inequality.
Definition at line 1200 of file StringClass.cpp.
References booleanObject(), and primitiveIsEqual().
Referenced by MemoryObject::createImage().
evaluate()
RexxObject * RexxString::evaluate (RexxActivation * context, ExpressionStack * stack) override virtual
Polymorphic method that makes string a polymorphic expression term for string literals.
Parameters
context The current execution context.
stack The current expression stack.
Returns
The string value.
Reimplemented from RexxInternalObject.
Definition at line 2072 of file StringClass.cpp.
References ExpressionStack::push(), RexxActivation::TRACE_PREFIX_LITERAL, and RexxActivation::traceIntermediate().
extract()
RexxString* RexxString::extract (size_t offset, size_t sublength) inline
Definition at line 431 of file StringClass.hpp.
References getStringData(), and newString().
Referenced by LanguageParser::addText(), VariableDictionary::buildCompoundVariable(), VariableDictionary::getVariableRetriever(), lower(), RexxTarget::remainder(), StringHashCollection::unknown(), and upper().
finish()
void RexxString::finish (size_t l) inline
Definition at line 541 of file StringClass.hpp.
References length.
Referenced by FinishBufferString().
flatten()
void RexxString::flatten (Envelope * envelope) override virtual
Flatten the object contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from RexxVirtualBase.
Definition at line 283 of file StringClass.cpp.
References cleanUpFlatten, flattenRef, numberStringValue, and setUpFlatten.
floor()
RexxObject * RexxString::floor ()
The String class version of the floor method.
Returns
The formatted numeric version.
Definition at line 1149 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by MemoryObject::createImage().
format()
RexxObject * RexxString::format (RexxObject * integers, RexxObject * decimals, RexxObject * mathExp, RexxObject * expTrigger)
String Format...performed by NumberString
Parameters
integers The number if integer positions.
decimals The number of decimals requested.
mathExp The size of the exponent
expTrigger The expontent trigger value.
Returns
The formatted number.
Definition at line 1186 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by BUILTIN(), and MemoryObject::createImage().
getChar()
char RexxString::getChar (size_t p) const inline
Definition at line 547 of file StringClass.hpp.
References stringData.
Referenced by VariableDictionary::buildCompoundVariable(), BUILTIN(), MutableBuffer::caselessMatchChar(), caselessMatchChar(), RexxObject::defaultName(), RexxActivation::doDebugPause(), VariableDictionary::getDirectVariableRetriever(), VariableDictionary::getVariableRetriever(), RexxVariableReference::list(), logicalValue(), MutableBuffer::matchChar(), matchChar(), Activity::messageSubstitution(), LanguageParser::needVariable(), optionArgument(), padArgument(), TraceSetting::parseTraceSetting(), and LanguageParser::scanSymbol().
getHashValue()
HashCode RexxString::getHashValue () override virtual
Get the primitive hash value of this String object.
Returns
The calculated string hash for the string.
Reimplemented from RexxInternalObject.
Definition at line 208 of file StringClass.cpp.
References getStringHash().
Referenced by RexxInteger::getHashValue(), and NumberString::getHashValue().
getLength()
size_t RexxString::getLength () const inline
Definition at line 538 of file StringClass.hpp.
References length.
Referenced by abbrev(), LanguageParser::addCompound(), LanguageParser::addText(), MutableBuffer::append(), RexxString::StringBuilder::append(), b2x(), bitAnd(), bitOr(), bitXor(), brackets(), BufferStringLength(), VariableDictionary::buildCompoundVariable(), CompoundVariableTail::buildTail(), BUILTIN(), c2x(), Activity::callCommandExit(), Activity::callFunctionExit(), Activity::callQueueNameExit(), caselessAbbrev(), caselessChangeStr(), MutableBuffer::caselessChangeStr(), caselessCompare(), caselessCompareToRexx(), caselessContains(), caselessContainsWord(), StringUtil::caselessCountStr(), caselessCountStrRexx(), MutableBuffer::caselessEndsWithRexx(), caselessEndsWithRexx(), StringUtil::caselessLastPos(), caselessLastPos(), caselessLastPosRexx(), MutableBuffer::caselessMatch(), caselessMatch(), MutableBuffer::caselessMatchChar(), caselessMatchChar(), StringUtil::caselessPos(), caselessPos(), caselessPosRexx(), RexxTarget::caselessSearch(), MutableBuffer::caselessStartsWithRexx(), caselessStartsWithRexx(), StringUtil::caselessWordPos(), caselessWordPos(), center(), changeStr(), MutableBuffer::changeStr(), checkLower(), LanguageParser::checkMarker(), checkPadArgument(), checkUpper(), CommandHandlerDispatcher::CommandHandlerDispatcher(), compare(), CompoundVariableTail::compare(), compareToRexx(), concat(), concatBlank(), concatRexx(), concatToCstring(), concatWith(), concatWithCstring(), containsRexx(), containsWord(), copies(), copyData(), copyIntoTail(), copyToRxstring(), NativeActivation::copyValue(), StringUtil::countStr(), countStrRexx(), CompoundVariableTail::createCompoundName(), decodeBase64(), delstr(), RexxActivation::doDebugPause(), encodeBase64(), MutableBuffer::endsWithRexx(), endsWithRexx(), SysFileSystem::extractDirectory(), SysFileSystem::extractExtension(), SysFileSystem::extractFile(), OutputRedirector::flushBuffer(), VariableDictionary::getDirectVariableRetriever(), getObjectHashCode(), getStringHash(), VariableDictionary::getVariableRetriever(), MutableBuffer::insert(), insert(), isEqual(), StringUtil::lastPos(), lastPos(), lastPosRexx(), left(), lengthRexx(), logicalValue(), lower(), lowerRexx(), StringUtil::makearray(), makeArrayRexx(), makeString(), MutableBuffer::match(), match(), MutableBuffer::matchChar(), matchChar(), Interpreter::messageNumber(), Activity::messageSubstitution(), MutableBuffer::newRexx(), newRexx(), numberString(), MutableBuffer::overlay(), overlay(), padArgument(), TraceSetting::parseTraceSetting(), StringUtil::pos(), pos(), posRexx(), primitiveCaselessCompareTo(), primitiveCaselessIsEqual(), primitiveCaselessMatch(), primitiveCompareTo(), primitiveIsEqual(), primitiveMatch(), primitiveStrictComp(), put(), ReadInput(), replaceAt(), OutputRedirector::resolveBuffer(), RexxToken::resolveKeyword(), RexxActivation::resolveStream(), reverse(), right(), RexxTarget::search(), MutableBuffer::setText(), RexxActivation::sourceString(), space(), MutableBuffer::startsWithRexx(), startsWithRexx(), strCaselessCompare(), strictComp(), stringComp(), StringLength(), stringTrace(), stringValue(), strip(), subchar(), substr(), subWord(), subWords(), toRxstring(), RexxActivation::traceCompoundValue(), RexxActivation::traceEntryOrExit(), RexxActivation::traceOperatorValue(), RexxActivation::traceSourceString(), RexxActivation::traceTaggedValue(), RexxActivation::traceValue(), translate(), MutableBuffer::translate(), truthValue(), StringHashCollection::unknown(), upper(), upperRexx(), CompoundVariableTail::useStringValue(), SystemInterpreter::validateAddressName(), StringUtil::verify(), verify(), word(), wordIndex(), wordLength(), StringUtil::wordPos(), wordPos(), words(), x2b(), x2c(), and x2dC2d().
getObjectHashCode()
HashCode RexxString::getObjectHashCode ()
Convert a string returned from an object HashCode() method into a binary hashcode suitable for the hash collections.
Returns
A binary hash code from a string value.
Definition at line 221 of file StringClass.cpp.
References getLength(), and getStringData().
Referenced by RexxObject::hash().
getRealValue() [1/2]
RexxObject * RexxString::getRealValue (RexxActivation * context) override virtual
Polymorphic get_value function used with expression terms
Parameters
context The current exection context.
Returns
The string value.
Reimplemented from RexxInternalObject.
Definition at line 2137 of file StringClass.cpp.
getRealValue() [2/2]
RexxObject * RexxString::getRealValue (VariableDictionary * context) override virtual
Polymorphic get_value function used with expression terms
Parameters
context The method dictionary context.
Returns
The string value.
Reimplemented from RexxInternalObject.
Definition at line 2151 of file StringClass.cpp.
getStringData()
const char* RexxString::getStringData () const inline
Definition at line 542 of file StringClass.hpp.
References stringData.
Referenced by abbrev(), LanguageParser::addCompound(), MutableBuffer::append(), RexxString::StringBuilder::append(), b2x(), bitAnd(), bitOr(), bitXor(), brackets(), BUILTIN(), c2x(), Activity::callCommandExit(), Activity::callFunctionExit(), RexxActivation::callMacroSpaceFunction(), Activity::callQueueNameExit(), NativeActivation::callRegisteredRoutine(), caselessAbbrev(), caselessChangeStr(), MutableBuffer::caselessChangeStr(), caselessCompare(), caselessContains(), caselessContainsWord(), caselessCountStrRexx(), StringUtil::caselessLastPos(), caselessLastPos(), caselessLastPosRexx(), StringUtil::caselessPos(), caselessPos(), caselessPosRexx(), StringUtil::caselessWordPos(), caselessWordPos(), center(), changeStr(), MutableBuffer::changeStr(), checkLower(), LanguageParser::checkMarker(), checkUpper(), CommandHandlerDispatcher::CommandHandlerDispatcher(), compare(), CompoundVariableTail::compare(), concat(), concatBlank(), concatRexx(), concatToCstring(), concatWith(), concatWithCstring(), containsRexx(), containsWord(), copies(), copyData(), copyIntoTail(), copyToRxstring(), NativeActivation::copyValue(), countStrRexx(), CompoundVariableTail::createCompoundName(), LanguageParser::createMethod(), LanguageParser::createProgramFromFile(), LanguageParser::createRoutine(), decodeBase64(), delstr(), delWord(), RexxActivation::displayProgramName(), NumberString::doubleValue(), PackageManager::dropRegisteredRoutine(), encodeBase64(), extract(), SysFileSystem::extractDirectory(), SysFileSystem::extractExtension(), SysFileSystem::extractFile(), OutputRedirector::flushBuffer(), RexxActivation::getMacroCode(), GetMessageName(), getObjectHashCode(), LibraryPackage::getPackageTable(), GetRoutineName(), RexxTarget::getWord(), MutableBuffer::insert(), insert(), isEqual(), StringUtil::lastPos(), lastPos(), lastPosRexx(), left(), PackageManager::loadRequires(), lower(), StringUtil::makearray(), makeArrayRexx(), RexxClass::makeProxy(), makeString(), Interpreter::messageNumber(), Activity::messageSubstitution(), MutableBuffer::newRexx(), newRexx(), numberString(), ObjectToStringValue(), NativeActivation::objectToValue(), MutableBuffer::overlay(), overlay(), NativeActivation::pointerString(), StringUtil::pos(), pos(), posRexx(), primitiveCaselessCompareTo(), primitiveCaselessIsEqual(), MutableBuffer::primitiveCaselessMatch(), primitiveCaselessMatch(), primitiveCompareTo(), primitiveIsEqual(), MutableBuffer::primitiveMatch(), primitiveMatch(), primitiveStrictComp(), NativeActivation::processArguments(), LanguageParser::processInstore(), put(), Interpreter::qualifyFileSystemName(), PackageManager::queryRegisteredRoutine(), ReadInput(), MutableBuffer::replaceAt(), replaceAt(), OutputRedirector::resolveBuffer(), InterpreterInstance::resolveCommandHandler(), RexxToken::resolveKeyword(), InterpreterInstance::resolveProgramName(), PackageManager::resolveRegisteredRoutineEntry(), PackageManager::resolveRoutine(), LanguageParser::restoreFromMacroSpace(), reverse(), right(), RexxObject::setMethod(), MutableBuffer::setText(), FileProgramSource::setup(), startsWith(), strCaselessCompare(), strictComp(), stringComp(), StringData(), stringTrace(), stringValue(), strip(), subchar(), substr(), subWord(), subWords(), toRxstring(), toUnicode(), RexxActivation::traceEntryOrExit(), RexxActivation::traceSourceString(), RexxActivation::traceValue(), translate(), MutableBuffer::translate(), truthValue(), upper(), StringUtil::verify(), verify(), word(), wordIndex(), wordLength(), StringUtil::wordPos(), wordPos(), words(), x2b(), and x2c().
getStringHash()
HashCode RexxString::getStringHash () inline
Definition at line 328 of file StringClass.hpp.
References getLength(), hashValue, and stringData.
Referenced by getHashValue().
getValue() [1/2]
RexxObject * RexxString::getValue (RexxActivation * context) override virtual
Polymorphic get_value function used with expression terms
Parameters
context The execution context.
Returns
The string object.
Reimplemented from RexxInternalObject.
Definition at line 2109 of file StringClass.cpp.
getValue() [2/2]
RexxObject * RexxString::getValue (VariableDictionary * context) override virtual
Polymorphic get_value function used with expression terms
Parameters
context The method dictionary context.
Returns
The string value.
Reimplemented from RexxInternalObject.
Definition at line 2123 of file StringClass.cpp.
getWritableData()
char* RexxString::getWritableData () inline
Definition at line 543 of file StringClass.hpp.
References stringData.
Referenced by b2x(), bitAnd(), bitOr(), bitXor(), BufferStringData(), CompoundVariableTail::buildTail(), c2x(), CompoundVariableTail::createCompoundName(), decodeBase64(), encodeBase64(), RexxString::StringBuilder::init(), lower(), newUpperString(), StringUtil::packHex(), put(), reverse(), stringTrace(), toRxstring(), translate(), upper(), CompoundVariableTail::useStringValue(), x2b(), and x2dC2d().
hasLower()
bool RexxString::hasLower () const inline
Definition at line 550 of file StringClass.hpp.
References attributes, and STRING_HASLOWER.
Referenced by upper().
hasUpper()
bool RexxString::hasUpper () const inline
Definition at line 554 of file StringClass.hpp.
References attributes, and STRING_HASUPPER.
Referenced by lower().
hexDigitToInt()
static int RexxString::hexDigitToInt (char ch) inline static
Definition at line 710 of file StringClass.hpp.
References DIGITS_HEX_LOOKUP.
Referenced by packByte2(), and x2b().
insert()
RexxString * RexxString::insert (RexxString * newStrObj, RexxInteger * position, RexxInteger * _length, RexxString * pad)
The String insert method.
Parameters
newStrObj The string to insert.
position The insert postion.
_length The optional insert length.
pad The optional padding character.
Returns
The string with the new string inserted.
Definition at line 170 of file StringClassSub.cpp.
References RexxString::StringBuilder::append(), ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, getLength(), getStringData(), optionalLengthArgument(), optionalPadArgument(), RexxString::StringBuilder::pad(), raw_string(), and stringArgument().
Referenced by BUILTIN(), and MemoryObject::createImage().
integerDivide()
RexxObject * RexxString::integerDivide (RexxObject * right_term)
String integer division...performed by NumberString
Parameters
right_term The other operator term.
Returns
The operator result
Definition at line 1024 of file StringClass.cpp.
References ArithmeticOperator.
Referenced by MemoryObject::createImage().
integerValue()
RexxInteger * RexxString::integerValue (wholenumber_t digits) override virtual
Convert a string object to an integer. Returns .nil for failures.
Parameters
digits The digits value for the conversion.
Returns
An integer version of this string.
Reimplemented from RexxInternalObject.
Definition at line 1873 of file StringClass.cpp.
References RexxInteger::getStringrep(), NumberString::integerValue(), numberString(), OREF_NULL, RexxInteger::setString(), and TheNilObject.
Referenced by RexxInternalObject::integerValue(), and RexxInternalObject::requestInteger().
intToHexDigit()
static char RexxString::intToHexDigit (int n) inline static
Definition at line 705 of file StringClass.hpp.
Referenced by c2x(), RexxInteger::d2x(), and NumberString::d2xD2c().
isEqual()
bool RexxString::isEqual (RexxInternalObject * otherObj) override virtual
Primitive strict equal\not equal method. This determines only strict equality, not greater or less than values.
Parameters
otherObj The other object for comparison.
Returns
true if the objects are equal, false otherwise.
Reimplemented from RexxInternalObject.
Definition at line 639 of file StringClass.cpp.
References Error_Logical_value_method, getLength(), getStringData(), RexxInternalObject::isBaseClass(), RexxInternalObject::requestString(), RexxObject::sendMessage(), TheNilObject, and RexxInternalObject::truthValue().
Referenced by Activity::displayCondition(), RexxInteger::isEqual(), NumberString::isEqual(), NativeActivation::trap(), and NativeActivation::willTrap().
isGreaterOrEqual()
RexxObject * RexxString::isGreaterOrEqual (RexxObject * other)
Definition at line 1285 of file StringClass.cpp.
References comp(), and CompareOperator.
Referenced by MemoryObject::createImage().
isGreaterThan()
RexxObject * RexxString::isGreaterThan (RexxObject * other)
Definition at line 1273 of file StringClass.cpp.
References comp(), and CompareOperator.
Referenced by MemoryObject::createImage().
isLessOrEqual()
RexxObject * RexxString::isLessOrEqual (RexxObject * other)
Definition at line 1291 of file StringClass.cpp.
References comp(), and CompareOperator.
Referenced by MemoryObject::createImage().
isLessThan()
RexxObject * RexxString::isLessThan (RexxObject * other)
Definition at line 1279 of file StringClass.cpp.
References comp(), and CompareOperator.
Referenced by MemoryObject::createImage().
isNullString()
bool RexxString::isNullString () const inline
Definition at line 539 of file StringClass.hpp.
References length.
Referenced by b2x(), delWord(), and optionArgument().
isSymbol()
StringSymbolType RexxString::isSymbol ()
Determine if a string is a valid symbol, and what type of symbol.
Returns
The indicator of its symbol status.
Definition at line 59 of file StringClassMisc.cpp.
References LanguageParser::scanSymbol().
Referenced by BUILTIN(), LanguageParser::createLoop(), StringUtil::dataType(), LanguageParser::getRetriever(), and VariableDictionary::getVariableRetriever().
lastPos()
size_t RexxString::lastPos (RexxString * needle, size_t _start)
Primitive implementation of a lastpos search.
Parameters
needle The search needle.
start The starting position (origin 1).
Returns
Returns the last match position, searching back from the start position. The starting position is the right-most character of the past possible match (as if the string was truncated at start).
Definition at line 389 of file StringClassMisc.cpp.
References getLength(), getStringData(), and StringUtil::lastPos().
lastPosRexx()
RexxInteger * RexxString::lastPosRexx (RexxString * needle, RexxInteger * _start, RexxInteger * _range)
Do a lastpos() search for a string.
Parameters
needle The search needle.
_start The starting position.
Returns
the offset of the match position (origin 1). Returns 0 if no match was found.
Definition at line 352 of file StringClassMisc.cpp.
References getLength(), getStringData(), and StringUtil::lastPosRexx().
Referenced by BUILTIN(), and MemoryObject::createImage().
left()
RexxString * RexxString::left (RexxInteger * _length, RexxString * pad)
Extract a substring relative to the left side of the target string.
Parameters
_length The length to extract.
pad The pad character for padding out to the given length.
Returns
The extracted string.
Definition at line 250 of file StringClassSub.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, ARG_TWO, getLength(), getStringData(), length, lengthArgument(), optionalPadArgument(), RexxString::StringBuilder::pad(), and raw_string().
Referenced by MemoryObject::createImage().
lengthRexx()
RexxObject * RexxString::lengthRexx ()
Return the length of a string as an integer object.
Returns
The string length.
Definition at line 625 of file StringClass.cpp.
References getLength(), and new_integer().
Referenced by BUILTIN(), and MemoryObject::createImage().
live()
void RexxString::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from RexxVirtualBase.
Definition at line 253 of file StringClass.cpp.
References memory_mark, and numberStringValue.
liveGeneral()
void RexxString::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from RexxVirtualBase.
Definition at line 265 of file StringClass.cpp.
References memory_mark_general, numberString(), numberStringValue, and PREPARINGIMAGE.
logicalOperation()
RexxObject* RexxString::logicalOperation (RexxObject * , RexxObject * , unsigned int)
logicalValue()
bool RexxString::logicalValue (logical_t & result) override virtual
Convert an object to a logical value without raising an error.
Parameters
result The converted value.
Returns
true if this converted ok, false for an invalid logical.
Reimplemented from RexxInternalObject.
Definition at line 1507 of file StringClass.cpp.
References baseString(), getChar(), and getLength().
Referenced by RexxInternalObject::logicalValue().
lower() [1/2]
RexxString * RexxString::lower ()
Translate a string to lower case
Returns
The translated string.
Definition at line 1687 of file StringClass.cpp.
References checkUpper(), getLength(), getStringData(), getWritableData(), hasUpper(), lowerOnly(), raw_string(), setLowerOnly(), and Utilities::toLower().
Referenced by lowerRexx(), and StringLower().
lower() [2/2]
RexxString * RexxString::lower (size_t offset, size_t _length)
Lowercase a portion of a Rexx string, returning a new string object. This method assumes the offset and length are already valid for this string object.
Parameters
start The starting offset of the segment to lowercase (origin 0).
length The length to lowercase.
Returns
A new string object with the case conversion applied.
Definition at line 1800 of file StringClass.cpp.
References extract(), getLength(), getWritableData(), and Utilities::toLower().
lowerOnly()
bool RexxString::lowerOnly () const inline
Definition at line 553 of file StringClass.hpp.
References attributes, and STRING_NOUPPER.
Referenced by lower().
lowerRexx()
RexxString * RexxString::lowerRexx (RexxInteger * _start, RexxInteger * _length)
Rexx exported method stub for the lower() method.
Parameters
start The optional starting location. Defaults to the first character if not specified.
length The length to convert. Defaults to the segment from the start position to the end of the string.
Returns
A new string object with the case conversion applied.
Definition at line 1732 of file StringClass.cpp.
References ARG_ONE, ARG_TWO, getLength(), lower(), optionalLengthArgument(), and optionalPositionArgument().
Referenced by MemoryObject::createImage().
makeArray()
ArrayClass * RexxString::makeArray () override virtual
Baseclass optimization for handling request array calls.
Returns
The string object converted to an array using default arguments.
Reimplemented from RexxInternalObject.
Definition at line 373 of file StringClass.cpp.
References RexxObject::makeArrayRexx(), and OREF_NULL.
Referenced by RexxInteger::makeArray(), and NumberString::makeArray().
makeArrayRexx()
ArrayClass * RexxString::makeArrayRexx (RexxString * div)
Split string into an array
Parameters
div The separator character.
Returns
An array if the string segments.
Definition at line 2031 of file StringClass.cpp.
References getLength(), getStringData(), and StringUtil::makearray().
makeString()
RexxString * RexxString::makeString () override virtual
Handle a REQUEST('STRING') request for a REXX string object
Returns
A string version of this string.
Reimplemented from RexxInternalObject.
Definition at line 353 of file StringClass.cpp.
References getLength(), getStringData(), RexxInternalObject::isBaseClass(), and new_string().
Referenced by stringArrayArgument().
match()
RexxObject * RexxString::match (RexxInteger * start_, RexxString * other, RexxInteger * offset_, RexxInteger * len_)
Test if regions within two strings match.
Parameters
start_ The starting compare position within the target string. This must be within the bounds of the string.
other The other compare string.
offset_ The starting offset of the compare string. This must be within the string bounds. The default start postion is 1.
len_ The length of the compare substring. The length and the offset must specify a valid substring of other. If not specified, this defaults to the substring from the offset to the end of the string.
Returns
True if the two regions match, false for any mismatch.
Definition at line 792 of file StringClassMisc.cpp.
References ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, booleanObject(), getLength(), optionalLengthArgument(), optionalPositionArgument(), OREF_NULL, positionArgument(), primitiveMatch(), stringArgument(), and TheFalseObject.
Referenced by MemoryObject::createImage().
matchChar()
RexxObject * RexxString::matchChar (RexxInteger * position_, RexxString * matchSet)
Compare a single character at a give position against a set of characters to see if any of the characters is a match.
Parameters
position_ The character position
matchSet The set to compare against.
Returns
true if the character at the give position is any of the characters, false if none of them match.
Definition at line 1001 of file StringClassMisc.cpp.
References ARG_ONE, ARG_TWO, getChar(), getLength(), positionArgument(), stringArgument(), TheFalseObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
Max()
RexxObject * RexxString::Max (RexxObject ** arguments, size_t argCount)
String max value...performed by NumberString
Parameters
arguments The variable list of Max arguments.
argCount The count of arguments.
Returns
The Max result.
Definition at line 1098 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by BUILTIN(), and MemoryObject::createImage().
memCompare() [1/2]
bool RexxString::memCompare (const char * s, size_t l) const inline
Definition at line 562 of file StringClass.hpp.
References length, and stringData.
Referenced by strCompare().
memCompare() [2/2]
bool RexxString::memCompare (RexxString * other) const inline
Definition at line 563 of file StringClass.hpp.
References length, and stringData.
memCopy()
void RexxString::memCopy (char * s) const inline
Definition at line 565 of file StringClass.hpp.
References length, and stringData.
Min()
RexxObject * RexxString::Min (RexxObject ** arguments, size_t argCount)
String min value...performed by NumberString
Parameters
arguments The variable list of Min arguments.
argCount The count of arguments.
Returns
The Min result.
Definition at line 1112 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by BUILTIN(), and MemoryObject::createImage().
minus()
RexxObject * RexxString::minus (RexxObject * right_term)
String subtraction...performed by NumberString
Parameters
right_term The other operator term.
Returns
The operator result
Definition at line 985 of file StringClass.cpp.
References ArithmeticOperator.
Referenced by MemoryObject::createImage().
modulo()
RexxObject * RexxString::modulo (RexxObject * divisor)
The String class version of the modulo method.
Parameters
divisor The divisor.
Returns
The module result.
Definition at line 1138 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by MemoryObject::createImage().
multiply()
RexxObject * RexxString::multiply (RexxObject * right_term)
String multiplication...performed by NumberString
Parameters
right_term The other operator term.
Returns
The operator result
Definition at line 998 of file StringClass.cpp.
References ArithmeticOperator.
Referenced by MemoryObject::createImage().
newProxy()
RexxString * RexxString::newProxy (const char * string) static
Create a proxy object from this string
Parameters
string The name of the proxy.
Returns
A string marked as a proxy object.
Definition at line 2331 of file StringClass.cpp.
References RexxInternalObject::makeProxyObject(), and new_string().
Referenced by new_proxy().
newRexx()
RexxString * RexxString::newRexx (RexxObject ** init_args, size_t argCount)
Create a new string value (used primarily for subclasses)
Parameters
init_args The standard new args.
argCount The argument count.
Returns
A new string object of the current class.
Definition at line 2349 of file StringClass.cpp.
References ARG_ONE, RexxClass::completeNewObject(), getLength(), getStringData(), new_string(), RexxClass::processNewArgs(), and stringArgument().
Referenced by MemoryObject::createImage().
newString() [1/4]
RexxString * RexxString::newString (const char * string, size_t length) static
Definition at line 2157 of file StringClass.cpp.
References hashValue, length, new_object(), put(), putChar(), RexxString(), RexxInternalObject::setHasNoReferences(), setLength(), and T_String.
Referenced by extract(), and new_string().
newString() [2/4]
RexxString * RexxString::newString (const char * s1, size_t l1, const char * s2, size_t l2) static
Allocate and initialize a new string object from a pair of data buffer.
Parameters
s1 Pointer to the first data buffer
l1 length of the first buffer
s2 pointer to the second buffer
l2 length of the second buffer
Returns
A string object that is the concatenation of the two buffers.
Definition at line 2192 of file StringClass.cpp.
References hashValue, new_object(), put(), putChar(), RexxString(), RexxInternalObject::setHasNoReferences(), setLength(), and T_String.
newString() [3/4]
RexxString * RexxString::newString (double number) static
Create a string from a double value
Parameters
number The starting number.
Returns
A string version of a double value.
Definition at line 2303 of file StringClass.cpp.
References new_numberstringFromDouble(), and NumberString::stringValue().
newString() [4/4]
RexxString * RexxString::newString (double number, size_t precision) static
Convert a double value to a string using the provided precision.
Parameters
number The number to convert.
precision The precision requested for the result.
Returns
A string value of the converted result.
Definition at line 2318 of file StringClass.cpp.
References new_numberstringFromDouble(), and NumberString::stringValue().
newUpperString()
RexxString * RexxString::newUpperString (const char * string, size_t length) static
Allocate an initialize a string object that will also contain only uppercase characters. This allows a creation and uppercase operation to be done in one shot, without requiring two string objects to be created.
Parameters
string The source string data.
length The length of the string data.
Returns
A newly constructed string object.
Definition at line 2256 of file StringClass.cpp.
References getWritableData(), hashValue, length, new_object(), putChar(), RexxString(), RexxInternalObject::setHasNoReferences(), setLength(), setUpperOnly(), T_String, and Utilities::toUpper().
Referenced by new_upper_string().
nonNumeric()
bool RexxString::nonNumeric () const inline
Definition at line 557 of file StringClass.hpp.
References attributes, and STRING_NONNUMERIC.
Referenced by numberString().
notEqual()
RexxObject * RexxString::notEqual (RexxObject * other)
Definition at line 1262 of file StringClass.cpp.
References booleanObject(), comp(), TheNilObject, and TheTrueObject.
Referenced by MemoryObject::createImage().
notOp()
RexxObject * RexxString::notOp ()
Logical NOT of a string
Returns
The logical not of the string truth value.
Definition at line 2043 of file StringClass.cpp.
References booleanObject(), Error_Logical_value_method, and truthValue().
Referenced by MemoryObject::createImage(), NumberString::notOp(), and NumberString::operatorNot().
numberString()
NumberString * RexxString::numberString () override virtual
Convert a String Object into a Number Object
Returns
The converted numeric value.
Reimplemented from RexxInternalObject.
Definition at line 548 of file StringClass.cpp.
References getLength(), getStringData(), RexxInternalObject::isBaseClass(), new_numberstring(), nonNumeric(), numberStringValue, OREF_NULL, RexxInternalObject::requestString(), setField, RexxInternalObject::setHasReferences(), setNonNumeric(), and NumberString::setString().
Referenced by comp(), d2c(), d2x(), doubleValue(), RexxIntegerClass::initCache(), integerValue(), RexxInteger::liveGeneral(), liveGeneral(), RexxInternalObject::numberString(), RexxInteger::numberString(), numberValue(), ForLoop::setup(), and unsignedNumberValue().
numberValue() [1/2]
bool RexxString::numberValue (wholenumber_t & result) override virtual
Convert a string object to a whole number value. Returns false if it will not convert.
Parameters
result the return whole number result
Returns
true if this converted successfully.
Reimplemented from RexxInternalObject.
Definition at line 438 of file StringClass.cpp.
References RexxInternalObject::isBaseClass(), numberString(), NumberString::numberValue(), numberValue(), OREF_NULL, and RexxInternalObject::requestString().
numberValue() [2/2]
bool RexxString::numberValue (wholenumber_t & result, wholenumber_t digits) override virtual
Convert a string object to a whole number value. Returns false if it will not convert.
Parameters
result the return whole number result
digits the digits value for the conversion.
Returns
true if this converted successfully.
Reimplemented from RexxInternalObject.
Definition at line 411 of file StringClass.cpp.
References RexxInternalObject::isBaseClass(), numberString(), NumberString::numberValue(), numberValue(), OREF_NULL, and RexxInternalObject::requestString().
Referenced by BUILTIN(), StringUtil::dataType(), Interpreter::messageNumber(), RexxInternalObject::numberValue(), numberValue(), and NativeActivation::variablePoolFetchPrivate().
operatorNot()
RexxObject * RexxString::operatorNot (RexxObject * other)
Logical NOT of a string. This is the operator version, which needs to take an argument that is not used.
Parameters
other The other value (which will be OREF_NULL)
Returns
The not of the string logical value.
Definition at line 2057 of file StringClass.cpp.
References booleanObject(), Error_Logical_value_method, and truthValue().
orOp()
RexxObject * RexxString::orOp (RexxObject * other)
Logical OR of a string with another logical value
Parameters
other The other OR object.
Returns
Either .true or .false based on the logical result.
Definition at line 1974 of file StringClass.cpp.
References ARG_ONE, booleanObject(), Error_Logical_value_method, requiredArgument(), RexxInternalObject::truthValue(), and truthValue().
Referenced by MemoryObject::createImage(), and NumberString::orOp().
overlay()
RexxString * RexxString::overlay (RexxString * newStrObj, RexxInteger * position, RexxInteger * _length, RexxString * pad)
Perform an overlay operation on a string.
Parameters
newStrObj The string being overlayed on the target string.
position The overlay position.
_length The optional length of the overlay.
pad The optional pad character
Returns
A new string with the overlay performed.
Definition at line 294 of file StringClassSub.cpp.
References RexxString::StringBuilder::append(), ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, getLength(), getStringData(), optionalLengthArgument(), optionalPadArgument(), optionalPositionArgument(), RexxString::StringBuilder::pad(), raw_string(), and stringArgument().
Referenced by BUILTIN(), and MemoryObject::createImage().
packByte2()
static char RexxString::packByte2 (const char * bytes) inline static
Definition at line 715 of file StringClass.hpp.
References hexDigitToInt().
Referenced by StringUtil::packHex().
plus()
RexxObject * RexxString::plus (RexxObject * right_term)
String addition...performed by NumberString
Parameters
right_term The other operator term.
Returns
The operator result
Definition at line 972 of file StringClass.cpp.
References ArithmeticOperator.
Referenced by MemoryObject::createImage().
pos()
size_t RexxString::pos (RexxString * needle, size_t _start)
Do a primitive level pos() search on a string.
Parameters
needle The search needle.
_start The starting position (origin 0)
Returns
The match position (origin 1). Returns 0 for no match.
Definition at line 650 of file StringClassMisc.cpp.
References getLength(), getStringData(), and StringUtil::pos().
Referenced by changeStr(), and Activity::messageSubstitution().
posRexx()
RexxInteger * RexxString::posRexx (RexxString * needle, RexxInteger * pstart, RexxInteger * range)
Search for an occurrence of one string in another.
Parameters
needle The search needle.
pstart The postion to start.
range The end range of the search.
Returns
0 if the string is not found or the position of the first match.
Definition at line 581 of file StringClassMisc.cpp.
References getLength(), getStringData(), and StringUtil::posRexx().
Referenced by BUILTIN(), and MemoryObject::createImage().
power()
RexxObject * RexxString::power (RexxObject * right_term)
String power operator...performed by NumberString
Parameters
right_term The other operator term.
Returns
The operator result
Definition at line 1050 of file StringClass.cpp.
References ArithmeticOperator.
Referenced by MemoryObject::createImage().
primitiveCaselessCompareTo() [1/2]
wholenumber_t RexxString::primitiveCaselessCompareTo (RexxString * other)
primitiveCaselessCompareTo() [2/2]
wholenumber_t RexxString::primitiveCaselessCompareTo (RexxString * other, size_t _start, size_t len)
Perform a compare of regions of two string objects. Returns -1, 0, 1 based on the relative ordering of the two strings.
Parameters
other The source string for the compare.
start The starting offset within the target string.
len The length of the substring to compare.
Returns
-1 if the target string is less than, 0 if the two strings are equal, 1 if the target string is the greater.
Definition at line 1228 of file StringClassMisc.cpp.
References StringUtil::caselessCompare(), getLength(), and getStringData().
Referenced by caselessCompareToRexx().
primitiveCaselessIsEqual()
bool RexxString::primitiveCaselessIsEqual (RexxObject * otherObj)
Primitive string caseless comparison.
Parameters
otherObj The other string to compare.
Returns
true if the strings compare, false otherwise.
Definition at line 699 of file StringClass.cpp.
References ARG_ONE, StringUtil::caselessCompare(), getLength(), getStringData(), RexxInternalObject::requestString(), requiredArgument(), and TheNilObject.
Referenced by caselessEquals().
primitiveCaselessMatch()
bool RexxString::primitiveCaselessMatch (size_t _start, RexxString * other, size_t offset, size_t len)
Perform a caselesee compare of regions of two string objects. Returns true if the two regions match, returns false for mismatches.
Parameters
start The starting offset within the target string.
other The source string for the compare.
offset The offset of the substring of the other string to use.
len The length of the substring to compare.
Returns
True if the regions match, false otherwise.
Definition at line 975 of file StringClassMisc.cpp.
References StringUtil::caselessCompare(), getLength(), and getStringData().
Referenced by caselessEndsWithRexx(), caselessMatch(), and caselessStartsWithRexx().
primitiveCompareTo() [1/2]
wholenumber_t RexxString::primitiveCompareTo (RexxString * other)
Perform a compare of regions of two string objects. Returns -1, 0, 1 based on the relative ordering of the two strings.
Parameters
other The source string for the compare.
Returns
-1 if the target string is less than, 0 if the two strings are equal, 1 if the target string is the greater.
Definition at line 1159 of file StringClassMisc.cpp.
References getLength(), and getStringData().
primitiveCompareTo() [2/2]
wholenumber_t RexxString::primitiveCompareTo (RexxString * other, size_t _start, size_t len)
Perform a compare of regions of two string objects. Returns -1, 0, 1 based on the relative ordering of the two strings.
Parameters
other The source string for the compare.
start The starting offset within the target string.
len The length of the substring to compare.
Returns
-1 if the target string is less than, 0 if the two strings are equal, 1 if the target string is the greater.
Definition at line 1097 of file StringClassMisc.cpp.
References getLength(), and getStringData().
Referenced by compareTo(), and compareToRexx().
primitiveIsEqual()
bool RexxString::primitiveIsEqual (RexxObject * otherObj)
Primitive strict equal\not equal method. This determines only strict equality, not greater or less than values.
Parameters
otherObj The comparison object.
Returns
true or false, depending on the string equality.
Definition at line 674 of file StringClass.cpp.
References ARG_ONE, getLength(), getStringData(), RexxInternalObject::requestString(), requiredArgument(), and TheNilObject.
Referenced by equals(), strictEqual(), RexxInteger::strictEquality(), and strictNotEqual().
primitiveMakeString()
RexxString * RexxString::primitiveMakeString () override virtual
Handle a REQUEST('STRING') request for a REXX string object
Returns
Just returns the target string object.
Reimplemented from RexxInternalObject.
Definition at line 396 of file StringClass.cpp.
primitiveMatch()
bool RexxString::primitiveMatch (size_t _start, RexxString * other, size_t offset, size_t len)
Perform a compare of regions of two string objects. Returns true if the two regions match, returns false for mismatches.
Parameters
start The starting offset within the target string.
other The source string for the compare.
offset The offset of the substring of the other string to use.
len The length of the substring to compare.
Returns
True if the regions match, false otherwise.
Definition at line 948 of file StringClassMisc.cpp.
References getLength(), and getStringData().
Referenced by endsWithRexx(), match(), and startsWithRexx().
primitiveStrictComp()
wholenumber_t RexxString::primitiveStrictComp (RexxObject * otherObj)
Do a strict comparison of two strings when called by either the Interger or NumberString class. This returns:
a value < 0 when this is smaller than other a value 0 when this is equal to other a value > 0 when this is larger than other
Parameters
otherObj The other comparison object.
Returns
The relative comparison result (<0, 0, >0)
Definition at line 920 of file StringClass.cpp.
References getLength(), getStringData(), and RexxInternalObject::requestString().
Referenced by RexxInteger::strictComp(), NumberString::strictComp(), strictGreaterOrEqual(), strictGreaterThan(), strictLessOrEqual(), and strictLessThan().
put() [1/2]
void RexxString::put (size_t s, const void * b, size_t l) inline
Definition at line 544 of file StringClass.hpp.
References getWritableData().
Referenced by newString(), PackageClass::traceBack(), RexxActivation::traceCompoundValue(), RexxActivation::traceEntryOrExit(), RexxActivation::traceOperatorValue(), RexxActivation::traceSourceString(), RexxActivation::traceTaggedValue(), and RexxActivation::traceValue().
put() [2/2]
void RexxString::put (size_t s, RexxString * o) inline
Definition at line 545 of file StringClass.hpp.
References getLength(), getStringData(), and put().
Referenced by put().
putChar()
char RexxString::putChar (size_t p, char c) inline
Definition at line 548 of file StringClass.hpp.
References stringData.
Referenced by newString(), newUpperString(), LanguageParser::packBinaryLiteral(), LanguageParser::packHexLiteral(), rawString(), LanguageParser::scanLiteral(), LanguageParser::scanSymbol(), RexxActivation::traceCompoundValue(), RexxActivation::traceOperatorValue(), RexxActivation::traceSourceString(), RexxActivation::traceTaggedValue(), and RexxActivation::traceValue().
rawString()
RexxString * RexxString::rawString (size_t length) static
Allocate (and initialize) an empty string object
Parameters
length The required lenth
Returns
A raw string object (no data initialization)
Definition at line 2224 of file StringClass.cpp.
References hashValue, length, new_object(), putChar(), RexxString(), RexxInternalObject::setHasNoReferences(), setLength(), and T_String.
Referenced by raw_string().
remainder()
RexxObject * RexxString::remainder (RexxObject * right_term)
String remainder division...performed by NumberString
Parameters
right_term The other operator term.
Returns
The operator result
Definition at line 1037 of file StringClass.cpp.
References ArithmeticOperator.
Referenced by MemoryObject::createImage().
replaceAt()
RexxString * RexxString::replaceAt (RexxString * newStrObj, RexxInteger * position, RexxInteger * _length, RexxString * pad)
Replace a substring starting at a given position and length with another string. This operation is essentially a delstr() followed by an insert() operation.
Parameters
newStrObj The replacement string
position The replacement position (required)
_length The length of string to replace (optional). If omitted, the length of the replacement string is used and this is essentially an overlay operation.
pad The padding character if padding is required. The default is a ' '
Returns
A new instance of the string with the value replace.
Definition at line 378 of file StringClassSub.cpp.
References RexxString::StringBuilder::append(), ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, getLength(), getStringData(), optionalLengthArgument(), optionalPadArgument(), RexxString::StringBuilder::pad(), positionArgument(), raw_string(), and stringArgument().
Referenced by MemoryObject::createImage().
reverse()
RexxString * RexxString::reverse ()
Reverse the byte positions in a string object.
Returns
The target string, reversed.
Definition at line 443 of file StringClassSub.cpp.
References getLength(), getStringData(), getWritableData(), length, and raw_string().
Referenced by MemoryObject::createImage().
right()
RexxString * RexxString::right (RexxInteger * _length, RexxString * pad)
Extract a substring of the target relative to the right end.
Parameters
_length The extract length.
pad The optional padding character.
Returns
The extracted substring.
Definition at line 487 of file StringClassSub.cpp.
References RexxString::StringBuilder::append(), ARG_ONE, ARG_TWO, getLength(), getStringData(), lengthArgument(), optionalPadArgument(), RexxString::StringBuilder::pad(), and raw_string().
Referenced by MemoryObject::createImage().
round()
RexxObject * RexxString::round ()
The String class version of the round method.
Returns
The formatted numeric version.
Definition at line 1170 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by MemoryObject::createImage().
set()
void RexxString::set (size_t s, int c, size_t l) inline
Definition at line 546 of file StringClass.hpp.
References stringData.
Referenced by PackageClass::traceBack(), RexxActivation::traceCompoundValue(), RexxActivation::traceEntryOrExit(), RexxActivation::traceOperatorValue(), RexxActivation::traceSourceString(), RexxActivation::traceTaggedValue(), and RexxActivation::traceValue().
setHasLower()
void RexxString::setHasLower () inline
Definition at line 552 of file StringClass.hpp.
References attributes, and STRING_HASLOWER.
Referenced by checkLower().
setHasUpper()
void RexxString::setHasUpper () inline
Definition at line 556 of file StringClass.hpp.
References attributes, and STRING_HASUPPER.
Referenced by checkUpper().
setLength()
void RexxString::setLength (size_t l) inline
Definition at line 540 of file StringClass.hpp.
References length.
Referenced by newString(), newUpperString(), and rawString().
setLowerOnly()
void RexxString::setLowerOnly () inline
Definition at line 555 of file StringClass.hpp.
References attributes, and STRING_NOUPPER.
Referenced by checkUpper(), and lower().
setNonNumeric()
void RexxString::setNonNumeric () inline
Definition at line 558 of file StringClass.hpp.
References attributes, and STRING_NONNUMERIC.
Referenced by numberString().
setNumberString()
void RexxString::setNumberString (NumberString * numberRep)
Attach a NumberString value to this string object for arithmetic optimization.
Parameters
numberRep The number representation.
Definition at line 1904 of file StringClass.cpp.
References numberStringValue, OREF_NULL, setField, RexxInternalObject::setHasNoReferences(), and RexxInternalObject::setHasReferences().
Referenced by LanguageParser::addText(), and NumberString::stringValue().
setUpperOnly()
void RexxString::setUpperOnly () inline
Definition at line 551 of file StringClass.hpp.
References attributes, and STRING_NOLOWER.
Referenced by checkLower(), newUpperString(), LanguageParser::scanSymbol(), and upper().
sign()
RexxObject * RexxString::sign ()
String sign value...performed by NumberString
Returns
The sign result.
Definition at line 1084 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by BUILTIN(), and MemoryObject::createImage().
sortCaselessCompare() [1/2]
int RexxString::sortCaselessCompare (RexxString * other) inline
Definition at line 595 of file StringClass.hpp.
References StringUtil::caselessCompare(), length, and stringData.
Referenced by compare_asc_i(), compare_asc_i_cols(), compare_desc_i(), and compare_desc_i_cols().
sortCaselessCompare() [2/2]
int RexxString::sortCaselessCompare (RexxString * other, size_t startCol, size_t colLength) inline
Definition at line 661 of file StringClass.hpp.
References StringUtil::caselessCompare(), length, and stringData.
sortCompare() [1/2]
int RexxString::sortCompare (RexxString * other) inline
Definition at line 573 of file StringClass.hpp.
References length, and stringData.
Referenced by compare_asc(), compare_asc_cols(), compare_desc(), and compare_desc_cols().
sortCompare() [2/2]
int RexxString::sortCompare (RexxString * other, size_t startCol, size_t colLength) inline
Definition at line 617 of file StringClass.hpp.
References length, and stringData.
space()
RexxString * RexxString::space (RexxInteger * space_count, RexxString * pad)
The String space method.
Parameters
space_count The number of spaces to insert between words.
pad The character to use for the word spacing.
Returns
The original string with the words separated by the new space count.
Definition at line 121 of file StringClassWord.cpp.
References RexxString::WordIterator::append(), ARG_ONE, ARG_TWO, counter(), getLength(), RexxString::WordIterator::next(), optionalLengthArgument(), optionalPadArgument(), RexxString::StringBuilder::pad(), and raw_string().
Referenced by MemoryObject::createImage().
startsWith() [1/2]
bool RexxString::startsWith (char c) const inline
Definition at line 570 of file StringClass.hpp.
References length, and stringData.
startsWith() [2/2]
bool RexxString::startsWith (const char * c) const inline
Definition at line 571 of file StringClass.hpp.
References getStringData(), and length.
startsWithRexx()
RexxObject * RexxString::startsWithRexx (RexxString * other)
Test if a string starts with another string
Parameters
other The other compare string.
Returns
True if the string starts with the other, false otherwise.
Definition at line 874 of file StringClassMisc.cpp.
References booleanObject(), getLength(), primitiveMatch(), and stringArgument().
Referenced by MemoryObject::createImage().
strCaselessCompare() [1/2]
bool RexxString::strCaselessCompare (const char * s) const inline
Definition at line 560 of file StringClass.hpp.
References length, Utilities::strCaselessCompare(), and stringData.
Referenced by BUILTIN(), check_queue(), RexxInstructionOptions::execute(), LibraryPackage::isPackage(), LibraryPackage::locateMethodEntry(), LibraryPackage::locateRoutineEntry(), RexxActivation::resolveStream(), and toUnicode().
strCaselessCompare() [2/2]
bool RexxString::strCaselessCompare (RexxString * s) const inline
Definition at line 561 of file StringClass.hpp.
References getLength(), getStringData(), length, Utilities::strCaselessCompare(), and stringData.
strCompare() [1/2]
bool RexxString::strCompare (const char * s) const inline
Definition at line 559 of file StringClass.hpp.
References memCompare().
Referenced by BUILTIN(), TrapHandler::canHandle(), NativeActivation::checkCondition(), NativeActivation::checkConditions(), NativeActivation::clearCondition(), RexxActivation::command(), LanguageParser::createMethod(), LanguageParser::createProgram(), LanguageParser::createRoutine(), RexxClass::defineMethod(), doubleValue(), RexxInstructionNumeric::execute(), RexxInstructionRaise::execute(), PackageClass::findNamespace(), RexxLocalVariables::findVariable(), ContextCommandHandlerDispatcher::handleError(), RedirectionDispatcher::handleError(), StreamInputSource::init(), StreamOutputTarget::init(), StreamOutputTarget::isSameTarget(), RexxLocalVariables::lookupStemVariable(), RexxLocalVariables::lookupVariable(), StreamOutputTarget::needsBuffering(), RexxActivation::raise(), Activity::raiseCondition(), LanguageParser::requiresDirective(), RexxActivation::rexxVariable(), RexxActivation::trap(), RexxActivation::trapOff(), RexxActivation::trapOn(), unflatten(), DirectoryClass::unsetMethodRexx(), RexxLocalVariables::updateVariable(), LanguageParser::useNew(), and RexxActivation::willTrap().
strCompare() [2/2]
bool RexxString::strCompare (RexxString * other) const inline
Definition at line 564 of file StringClass.hpp.
References length, and stringData.
strictComp()
wholenumber_t RexxString::strictComp (RexxObject * otherObj)
Do a strict comparison of two strings. This returns:
a value < 0 when this is smaller than other a value 0 when this is equal to other a value > 0 when this is larger than other
Parameters
otherObj The other comparison object.
Returns
The relative comparison result (<0, 0, >0)
Definition at line 874 of file StringClass.cpp.
References ARG_ONE, getLength(), getStringData(), and stringArgument().
strictEqual()
RexxObject * RexxString::strictEqual (RexxObject * other)
Strict ("==") equality operator...also returns the hash value if sent with no other object
Parameters
other The other comparison result.
Returns
.true if equal, .false otherwise.
Definition at line 1228 of file StringClass.cpp.
References booleanObject(), and primitiveIsEqual().
Referenced by MemoryObject::createImage().
strictGreaterOrEqual()
RexxObject * RexxString::strictGreaterOrEqual (RexxObject * other)
Definition at line 1309 of file StringClass.cpp.
References CompareOperator, and primitiveStrictComp().
Referenced by MemoryObject::createImage().
strictGreaterThan()
RexxObject * RexxString::strictGreaterThan (RexxObject * other)
Definition at line 1297 of file StringClass.cpp.
References CompareOperator, and primitiveStrictComp().
Referenced by MemoryObject::createImage().
strictLessOrEqual()
RexxObject * RexxString::strictLessOrEqual (RexxObject * other)
Definition at line 1315 of file StringClass.cpp.
References CompareOperator, and primitiveStrictComp().
Referenced by MemoryObject::createImage().
strictLessThan()
RexxObject * RexxString::strictLessThan (RexxObject * other)
Definition at line 1303 of file StringClass.cpp.
References CompareOperator, and primitiveStrictComp().
Referenced by MemoryObject::createImage().
strictNotEqual()
RexxObject * RexxString::strictNotEqual (RexxObject * other)
Strict ("\==") inequality operator
Parameters
other The other comparison operator.
Returns
.true if not equal, .false if equal.
Definition at line 1241 of file StringClass.cpp.
References booleanObject(), and primitiveIsEqual().
Referenced by MemoryObject::createImage().
stringComp()
wholenumber_t RexxString::stringComp (RexxString * second)
Do a value comparison of two strings for the non-strict comparisons. This returns for the compares:
a value < 0 when this is smaller than other a value 0 when this is equal to other a value > 0 when this is larger than other
NOTE: This version does not do the numeric portion of the compare, just the string portion. This allows numberstring to directly perform a string comparison without reattempting numeric conversions on the values.
Parameters
other The object we compare against.
Returns
the relative compare value (<0, 0, or >0)
Definition at line 795 of file StringClass.cpp.
References ch_SPACE, ch_TAB, getLength(), and getStringData().
Referenced by comp(), and NumberString::comp().
stringTrace()
RexxString * RexxString::stringTrace ()
Translate a string to "traceable" form, removing non-displayable characters
Returns
The translated string.
Definition at line 1638 of file StringClass.cpp.
References ch_SPACE, ch_TAB, RexxObject::copy(), getLength(), getStringData(), and getWritableData().
Referenced by RexxActivation::processTraceInfo().
stringValue()
RexxString * RexxString::stringValue () override virtual
Return the primitive string value of this object
Returns
Unless subclassed, directly returns the string value.
Reimplemented from RexxInternalObject.
Definition at line 334 of file StringClass.cpp.
References getLength(), getStringData(), RexxInternalObject::isBaseClass(), and new_string().
Referenced by Interpreter::messageNumber().
strip()
RexxString * RexxString::strip (RexxString * optionString, RexxString * stripchar)
Strip a set of leading and/or trailing characters from a string, returning a new string value, or if unchanged, the original string.
Parameters
optionString The option indicating where to strip characters.
stripchar The set of characters to strip.
Returns
A string instance with the target characters removed.
Definition at line 531 of file StringClassSub.cpp.
References ARG_ONE, ARG_TWO, getLength(), getStringData(), length, StringUtil::matchCharacter(), new_string(), optionalOptionArgument(), optionalStringArgument(), OREF_NULL, STRIP_BOTH, STRIP_LEADING, and STRIP_TRAILING.
Referenced by MemoryObject::createImage().
subchar()
RexxString * RexxString::subchar (RexxInteger * positionArg)
Extract a single character from a string object. Returns a null string if the specified position is beyond the bounds of the string.
Parameters
positionArg The position of the target character. Must be a positive whole number.
Returns
Returns the single character at the target position. Returns a null string if the position is beyond the end of the string.
Definition at line 637 of file StringClassSub.cpp.
References getLength(), getStringData(), and StringUtil::subchar().
Referenced by MemoryObject::createImage().
substr()
RexxString * RexxString::substr (RexxInteger * position, RexxInteger * _length, RexxString * pad)
Extract a substring from a target string.
Parameters
position The starting position of the extracted string.
_length The length to extract.
pad A padding character for padding out to the length, if necessary.
Returns
The extracted string value.
Definition at line 600 of file StringClassSub.cpp.
References getLength(), getStringData(), and StringUtil::substr().
Referenced by MemoryObject::createImage().
subWord()
RexxString * RexxString::subWord (RexxInteger * position, RexxInteger * plength)
Definition at line 180 of file StringClassWord.cpp.
References getLength(), getStringData(), and StringUtil::subWord().
Referenced by MemoryObject::createImage().
subWords()
ArrayClass * RexxString::subWords (RexxInteger * position, RexxInteger * plength)
Returns an array of all words contained in the given range of the string, using the same extraction rules used for subWord() and word().
Parameters
position The optional starting position. If not provided, extraction starts with the first word.
plength The number of words to extract. If omitted, will extract from the starting postion to the end of the string.
Returns
An array containing the extracted words. If no words are available within the given range, this returns an empty array.
Definition at line 200 of file StringClassWord.cpp.
References getLength(), getStringData(), and StringUtil::subWords().
Referenced by MemoryObject::createImage(), and RexxInstructionOptions::execute().
toRxstring() [1/2]
void RexxString::toRxstring (CONSTRXSTRING & r) inline
Definition at line 566 of file StringClass.hpp.
References getLength(), getStringData(), _CONSTRXSTRING::strlength, and _CONSTRXSTRING::strptr.
Referenced by Activity::callCommandExit(), Activity::callFunctionExit(), Activity::callObjectFunctionExit(), Activity::callPushExit(), NativeActivation::callRegisteredRoutine(), Activity::callSayExit(), Activity::callScriptingExit(), and Activity::callTraceExit().
toRxstring() [2/2]
void RexxString::toRxstring (RXSTRING & r) inline
Definition at line 567 of file StringClass.hpp.
References getLength(), getWritableData(), _RXSTRING::strlength, and _RXSTRING::strptr.
translate()
RexxString * RexxString::translate (RexxString * tableo, RexxString * tablei, RexxString * pad, RexxInteger * _start, RexxInteger * _range)
Translate characters in a string into another character.
Parameters
tableo The output translate table.
tablei The input translate table,
pad The pad character.
_start The starting position for the translate.
_range The length to apply the translation to.
Returns
The string with the translations applied.
Definition at line 681 of file StringClassMisc.cpp.
References ARG_FIVE, ARG_FOUR, ARG_ONE, ARG_THREE, ARG_TWO, getLength(), getStringData(), getWritableData(), StringUtil::memPos(), new_string(), optionalLengthArgument(), optionalPadArgument(), optionalPositionArgument(), optionalStringArgument(), OREF_NULL, and upperRexx().
Referenced by MemoryObject::createImage().
trunc()
RexxObject * RexxString::trunc (RexxInteger * decimals)
String Trunc...performed by NumberString
Parameters
decimals The number of decimals to truncate to.
Returns
The trunc result.
Definition at line 1125 of file StringClass.cpp.
References ArithmeticMethod.
Referenced by BUILTIN(), and MemoryObject::createImage().
truthValue()
bool RexxString::truthValue (RexxErrorCodes errorCode) override virtual
Determine the truth value of a string object, raising the given error if bad.
Parameters
errorCode The error code for bad booleans.
Returns
The true or false value of valid strings.
Reimplemented from RexxInternalObject.
Definition at line 1475 of file StringClass.cpp.
References baseString(), getLength(), getStringData(), and reportException().
Referenced by andOp(), choiceRexx(), notOp(), operatorNot(), orOp(), RexxInternalObject::truthValue(), and xorOp().
unflatten()
RexxInternalObject * RexxString::unflatten (Envelope * envelope) override virtual
unflatten an object
Parameters
envelope The envelope owning the object currently.
Returns
A potential replacement object if this is a proxy.
Reimplemented from RexxVirtualBase.
Definition at line 301 of file StringClass.cpp.
References RexxInternalObject::isProxyObject(), strCompare(), TheEnvironment, TheNilObject, TheRexxPackage, and RexxVirtualBase::unflatten().
unsignedNumberValue() [1/2]
bool RexxString::unsignedNumberValue (size_t & result) override virtual
Convert a string object to an unsigned number value. Returns false if it will not convert.
Parameters
result the return whole number result
Returns
true if this converted successfully.
Reimplemented from RexxInternalObject.
Definition at line 486 of file StringClass.cpp.
References RexxInternalObject::isBaseClass(), numberString(), OREF_NULL, RexxInternalObject::requestString(), NumberString::unsignedNumberValue(), and unsignedNumberValue().
unsignedNumberValue() [2/2]
bool RexxString::unsignedNumberValue (size_t & result, wholenumber_t digits) override virtual
Convert a string object to an unsigned number value. Returns false if it will not convert.
Parameters
result the return whole number result
digits the digits value for the conversion.
Returns
true if this converted successfully.
Reimplemented from RexxInternalObject.
Definition at line 463 of file StringClass.cpp.
References RexxInternalObject::isBaseClass(), numberString(), OREF_NULL, RexxInternalObject::requestString(), NumberString::unsignedNumberValue(), and unsignedNumberValue().
Referenced by RexxInternalObject::unsignedNumberValue(), and unsignedNumberValue().
upper() [1/2]
RexxString * RexxString::upper ()
Translate a string to uppercase...will only create a new string if characters actually have to be translated.
Returns
The string in uppercase.
Definition at line 1596 of file StringClass.cpp.
References checkLower(), getLength(), getStringData(), getWritableData(), hasLower(), raw_string(), setUpperOnly(), Utilities::toUpper(), and upperOnly().
Referenced by RexxActivation::addIOConfig(), PackageClass::addNamespace(), PackageManager::addRegisteredRoutine(), LanguageParser::attributeDirective(), BUILTIN(), PackageManager::callNativeRoutine(), LanguageParser::classDirective(), LanguageParser::constantDirective(), RexxObject::decodeMessageName(), RexxClass::defineClassMethod(), RexxClass::defineMethod(), RexxClass::deleteMethod(), PackageManager::dropRegisteredRoutine(), StringHashCollection::entry(), RexxInstructionForward::execute(), PackageClass::findClass(), Interpreter::findClass(), PackageClass::findNamespaceRexx(), PackageClass::findPublicClassRexx(), PackageClass::findRoutine(), PackageClass::findRoutineRexx(), RexxActivation::getIOConfig(), RexxBehaviour::getMethodObject(), VariableDictionary::getVariableRetriever(), StringHashCollection::hasEntry(), RexxObject::hasMethodRexx(), RexxObject::instanceMethod(), RexxClass::method(), LanguageParser::methodDirective(), LanguageParser::parseMessage(), PackageManager::queryRegisteredRoutine(), StringHashCollection::removeEntry(), StemClass::request(), RexxObject::requestRexx(), InterpreterInstance::resolveCommandHandler(), LanguageParser::resourceDirective(), StringHashCollection::setEntry(), RexxObject::setMethod(), DirectoryClass::setMethodRexx(), StringUpper(), RexxObject::unsetMethod(), DirectoryClass::unsetMethodRexx(), upperRexx(), and RexxToken::upperValue().
upper() [2/2]
RexxString * RexxString::upper (size_t offset, size_t _length)
Uppercase a portion of a Rexx string, returning a new string object. This method assumes the offset and length are already valid for this string object.
Parameters
start The starting offset of the segment to uppercase (origin 0).
length The length to lowercase.
Returns
A new string object with the case conversion applied.
Definition at line 1839 of file StringClass.cpp.
References extract(), getLength(), getWritableData(), and Utilities::toUpper().
upperOnly()
bool RexxString::upperOnly () const inline
Definition at line 549 of file StringClass.hpp.
References attributes, and STRING_NOLOWER.
Referenced by upper().
upperRexx()
RexxString * RexxString::upperRexx (RexxInteger * _start, RexxInteger * _length)
Rexx exported method stub for the upper() method.
Parameters
start The optional starting location. Defaults to the first character if not specified.
length The length to convert. Defaults to the segment from the start position to the end of the string.
Returns
A new string object with the case conversion applied.
Definition at line 1765 of file StringClass.cpp.
References ARG_ONE, ARG_TWO, getLength(), optionalLengthArgument(), optionalPositionArgument(), and upper().
Referenced by MemoryObject::createImage(), and translate().
verify()
RexxInteger * RexxString::verify (RexxString * ref, RexxString * option, RexxInteger * _start, RexxInteger * range)
Perform a verify operation on a string object.
Parameters
ref The reference set for the operation.
option The match/nomatch option.
_start The starting position.
range The search range.
Returns
The match/nomatch position, or zero.
Definition at line 771 of file StringClassMisc.cpp.
References getLength(), getStringData(), and StringUtil::verify().
Referenced by MemoryObject::createImage().
word()
RexxString * RexxString::word (RexxInteger * position)
Retrieve a specific word from a string.
Parameters
position The target word position.
Returns
The word at the given postion, or a null string if that word is not found.
Definition at line 214 of file StringClassWord.cpp.
References getLength(), getStringData(), and StringUtil::word().
Referenced by MemoryObject::createImage().
wordIndex()
RexxInteger * RexxString::wordIndex (RexxInteger * position)
Retrieve string position of a given word within a string.
Parameters
position The target word position.
Returns
The index of the target word, or zero if the string does not contain that many words.
Definition at line 228 of file StringClassWord.cpp.
References getLength(), getStringData(), and StringUtil::wordIndex().
Referenced by MemoryObject::createImage().
wordLength()
RexxInteger * RexxString::wordLength (RexxInteger * position)
Retrieve the length of a given word within a string.
Parameters
position The target word position.
Returns
The length of the word at that position, or zero of the string does not contain that many words.
Definition at line 242 of file StringClassWord.cpp.
References getLength(), getStringData(), and StringUtil::wordLength().
Referenced by MemoryObject::createImage().
wordPos()
RexxInteger * RexxString::wordPos (RexxString * phrase, RexxInteger * pstart)
Perform a wordpos search on a string object.
Parameters
phrase The search phrase
pstart The starting search position.
Returns
The index of the match location.
Definition at line 256 of file StringClassWord.cpp.
References getLength(), getStringData(), new_integer(), and StringUtil::wordPos().
Referenced by BUILTIN(), MemoryObject::createImage(), and delWord().
words()
RexxInteger * RexxString::words ()
Return the count of words within the string.
Returns
The total number of words in the string.
Definition at line 309 of file StringClassWord.cpp.
References getLength(), getStringData(), new_integer(), and StringUtil::wordCount().
Referenced by MemoryObject::createImage().
x2b()
RexxString * RexxString::x2b ()
A hex-to-binary conversion of a character string value.
Returns
The converted string.
Definition at line 691 of file StringClassConversion.cpp.
References ch_SPACE, ch_TAB, DIGITS_HEX_LOOKUP, getLength(), getStringData(), getWritableData(), hexDigitToInt(), raw_string(), StringUtil::unpackNibble(), and StringUtil::validateGroupedSet().
Referenced by MemoryObject::createImage().
x2c()
RexxString * RexxString::x2c ()
Process the string X2C method/function
Returns
The converted string value.
Definition at line 340 of file StringClassConversion.cpp.
References getLength(), getStringData(), and StringUtil::packHex().
Referenced by MemoryObject::createImage().
x2d()
RexxString * RexxString::x2d (RexxInteger * _length)
Process the string X2D method/function
Parameters
_length The output string length (required for negative values)
Returns
The converted string value.
Definition at line 361 of file StringClassConversion.cpp.
References x2dC2d().
Referenced by MemoryObject::createImage().
x2dC2d()
RexxString * RexxString::x2dC2d (RexxInteger * _length, bool type)
Common X2D/X2C processing routine
Parameters
_length The output length
type The conversion type. True is c2d, false is x2d.
Returns
The converted string.
Definition at line 390 of file StringClassConversion.cpp.
References NumberString::addToBaseTen(), ARG_ONE, RexxObject::copy(), Error_Incorrect_method_c2dbig, Error_Incorrect_method_x2dbig, BufferClass::getData(), getLength(), getWritableData(), IntegerZero, NumberString::multiplyBaseTen(), new_buffer(), new_integer(), number_digits(), optionalLengthArgument(), OREF_NULL, NumberString::OVERFLOWSPACE, StringUtil::packHex(), raw_string(), reportException(), Numerics::REXXINTEGER_DIGITS, and type.
Referenced by c2d(), and x2d().
xorOp()
RexxObject * RexxString::xorOp (RexxObject * other)
Logical XOR of a string with another logical value
Parameters
other The other value in the logical operation.
Returns
the XOR result.
Definition at line 1991 of file StringClass.cpp.
References ARG_ONE, booleanObject(), Error_Logical_value_method, requiredArgument(), RexxInternalObject::truthValue(), and truthValue().
Referenced by MemoryObject::createImage(), and NumberString::xorOp().
Member Data Documentation
ALNUM
const char * RexxString::ALNUM = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" static
Definition at line 786 of file StringClass.hpp.
Referenced by BUILTIN().
ALPHA
const char * RexxString::ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" static
Definition at line 787 of file StringClass.hpp.
Referenced by BUILTIN().
ALPHANUM
const char * RexxString::ALPHANUM = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" static
Definition at line 778 of file StringClass.hpp.
Referenced by RexxString::lookupInit::lookupInit().
ALPHANUM_LOOKUP
char RexxString::ALPHANUM_LOOKUP static
Definition at line 805 of file StringClass.hpp.
Referenced by StringUtil::dataType(), and RexxString::lookupInit::lookupInit().
attributes
FlagSet<StringFlag, 32> RexxString::attributes protected
Definition at line 816 of file StringClass.hpp.
Referenced by hasLower(), hasUpper(), lowerOnly(), nonNumeric(), setHasLower(), setHasUpper(), setLowerOnly(), setNonNumeric(), setUpperOnly(), and upperOnly().
BLANK
const char * RexxString::BLANK = "\t " static
Definition at line 788 of file StringClass.hpp.
Referenced by BUILTIN().
ch_FIVE
const char RexxString::ch_FIVE ='5' static
Definition at line 773 of file StringClass.hpp.
ch_MINUS
const char RexxString::ch_MINUS ='-' static
Definition at line 768 of file StringClass.hpp.
Referenced by NumberString::NumberBuilder::addExponentSign(), NumberString::NumberBuilder::addSign(), numberStringScan(), NumberString::parseNumber(), NumberStringBuilder::setExponentSign(), and NumberStringBuilder::setSign().
ch_NINE
const char RexxString::ch_NINE ='9' static
Definition at line 774 of file StringClass.hpp.
Referenced by numberStringScan(), and NumberString::parseNumber().
ch_ONE
const char RexxString::ch_ONE ='1' static
Definition at line 772 of file StringClass.hpp.
ch_PERIOD
const char RexxString::ch_PERIOD ='.' static
Definition at line 770 of file StringClass.hpp.
Referenced by NumberString::NumberBuilder::addDecimal(), numberStringScan(), and NumberString::parseNumber().
ch_PLUS
const char RexxString::ch_PLUS ='+' static
Definition at line 769 of file StringClass.hpp.
Referenced by NumberString::NumberBuilder::addExponentSign(), numberStringScan(), and NumberString::parseNumber().
ch_SPACE
const char RexxString::ch_SPACE = ' ' static
Definition at line 764 of file StringClass.hpp.
Referenced by numberStringScan(), NumberString::parseNumber(), stringComp(), stringTrace(), StringUtil::validateGroupedSet(), StringUtil::validateGroupedSetQuiet(), and x2b().
ch_TAB
const char RexxString::ch_TAB = '\t' static
Definition at line 765 of file StringClass.hpp.
Referenced by numberStringScan(), NumberString::parseNumber(), stringComp(), stringTrace(), StringUtil::validateGroupedSet(), StringUtil::validateGroupedSetQuiet(), and x2b().
ch_ZERO
const char RexxString::ch_ZERO ='0' static
Definition at line 771 of file StringClass.hpp.
Referenced by NumberStringBuilder::addDigit(), NumberString::NumberBuilder::addDigits(), NumberStringBuilder::addExponentDigit(), numberStringScan(), and NumberString::parseNumber().
classInstance
RexxClass * RexxString::classInstance = OREF_NULL static
Definition at line 737 of file StringClass.hpp.
CNTRL
const char * RexxString::CNTRL = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x7f" static
Definition at line 789 of file StringClass.hpp.
Referenced by BUILTIN().
DATATYPE_9DIGITS
const char RexxString::DATATYPE_9DIGITS = '9' static
Definition at line 756 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_ALPHANUMERIC
const char RexxString::DATATYPE_ALPHANUMERIC = 'A' static
Definition at line 745 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_BINARY
const char RexxString::DATATYPE_BINARY = 'B' static
Definition at line 746 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_HEX
const char RexxString::DATATYPE_HEX = 'X' static
Definition at line 755 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_INTERNAL_WHOLE
const char RexxString::DATATYPE_INTERNAL_WHOLE = 'I' static
Definition at line 747 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_LOGICAL
const char RexxString::DATATYPE_LOGICAL = 'O' static
Definition at line 757 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_LOWERCASE
const char RexxString::DATATYPE_LOWERCASE = 'L' static
Definition at line 748 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_MIXEDCASE
const char RexxString::DATATYPE_MIXEDCASE = 'M' static
Definition at line 749 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_NUMBER
const char RexxString::DATATYPE_NUMBER = 'N' static
Definition at line 750 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_SYMBOL
const char RexxString::DATATYPE_SYMBOL = 'S' static
Definition at line 751 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_UPPERCASE
const char RexxString::DATATYPE_UPPERCASE = 'U' static
Definition at line 753 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_VARIABLE
const char RexxString::DATATYPE_VARIABLE = 'V' static
Definition at line 752 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DATATYPE_WHOLE_NUMBER
const char RexxString::DATATYPE_WHOLE_NUMBER = 'W' static
Definition at line 754 of file StringClass.hpp.
Referenced by StringUtil::dataType().
DIGIT
const char * RexxString::DIGIT = "0123456789" static
Definition at line 790 of file StringClass.hpp.
Referenced by BUILTIN().
DIGITS_BASE64
const char * RexxString::DIGITS_BASE64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" static
Definition at line 783 of file StringClass.hpp.
Referenced by encodeBase64(), StringUtil::encodeBase64(), and RexxString::lookupInit::lookupInit().
DIGITS_BASE64_LOOKUP
char RexxString::DIGITS_BASE64_LOOKUP static
Definition at line 803 of file StringClass.hpp.
Referenced by decodeBase64(), StringUtil::decodeBase64(), and RexxString::lookupInit::lookupInit().
DIGITS_BIN
const char * RexxString::DIGITS_BIN = "01" static
Definition at line 779 of file StringClass.hpp.
Referenced by RexxString::lookupInit::lookupInit().
DIGITS_BIN_LOOKUP
char RexxString::DIGITS_BIN_LOOKUP static
Definition at line 804 of file StringClass.hpp.
Referenced by b2x(), StringUtil::dataType(), and RexxString::lookupInit::lookupInit().
DIGITS_HEX
const char * RexxString::DIGITS_HEX = "0123456789ABCDEFabcdef" static
Definition at line 777 of file StringClass.hpp.
Referenced by RexxString::lookupInit::lookupInit().
DIGITS_HEX_LOOKUP
char RexxString::DIGITS_HEX_LOOKUP static
Definition at line 802 of file StringClass.hpp.
Referenced by StringUtil::dataType(), hexDigitToInt(), RexxString::lookupInit::lookupInit(), StringUtil::packHex(), and x2b().
GRAPH
const char * RexxString::GRAPH = "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~" static
Definition at line 791 of file StringClass.hpp.
Referenced by BUILTIN().
hashValue
HashCode RexxString::hashValue protected
Definition at line 813 of file StringClass.hpp.
Referenced by getStringHash(), newString(), newUpperString(), and rawString().
length
size_t RexxString::length protected
Definition at line 814 of file StringClass.hpp.
Referenced by b2x(), endsWith(), finish(), getLength(), isNullString(), left(), memCompare(), memCopy(), newString(), newUpperString(), rawString(), reverse(), setLength(), sortCaselessCompare(), sortCompare(), startsWith(), strCaselessCompare(), strCompare(), and strip().
lookupInitializer
RexxString::lookupInit RexxString::lookupInitializer static
Definition at line 115 of file StringClass.cpp.
LOWER
const char * RexxString::LOWER = RexxString::LOWER_ALPHA static
Definition at line 792 of file StringClass.hpp.
Referenced by BUILTIN().
LOWER_ALPHA
const char * RexxString::LOWER_ALPHA = "abcdefghijklmnopqrstuvwxyz" static
Definition at line 780 of file StringClass.hpp.
Referenced by RexxString::lookupInit::lookupInit().
LOWER_ALPHA_LOOKUP
char RexxString::LOWER_ALPHA_LOOKUP static
Definition at line 806 of file StringClass.hpp.
Referenced by StringUtil::dataType(), and RexxString::lookupInit::lookupInit().
MIXED_ALPHA
const char * RexxString::MIXED_ALPHA = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" static
Definition at line 781 of file StringClass.hpp.
Referenced by RexxString::lookupInit::lookupInit().
MIXED_ALPHA_LOOKUP
char RexxString::MIXED_ALPHA_LOOKUP static
Definition at line 807 of file StringClass.hpp.
Referenced by StringUtil::dataType(), and RexxString::lookupInit::lookupInit().
numberStringValue
NumberString* RexxString::numberStringValue protected
Definition at line 815 of file StringClass.hpp.
Referenced by flatten(), live(), liveGeneral(), numberString(), and setNumberString().
operatorMethods
PCPPM RexxString::operatorMethods static
Definition at line 734 of file StringClass.hpp.
PRINT
const char * RexxString::PRINT = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~" static
Definition at line 793 of file StringClass.hpp.
Referenced by BUILTIN().
PUNCT
const char * RexxString::PUNCT = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~" static
Definition at line 794 of file StringClass.hpp.
Referenced by BUILTIN().
SPACE
const char * RexxString::SPACE = "\t\n\v\f\r " static
Definition at line 795 of file StringClass.hpp.
Referenced by BUILTIN().
stringData
char RexxString::stringData[4] protected
Definition at line 817 of file StringClass.hpp.
Referenced by endsWith(), getChar(), getStringData(), getStringHash(), getWritableData(), memCompare(), memCopy(), putChar(), set(), sortCaselessCompare(), sortCompare(), startsWith(), strCaselessCompare(), and strCompare().
STRIP_BOTH
const char RexxString::STRIP_BOTH = 'B' static
Definition at line 740 of file StringClass.hpp.
Referenced by strip().
STRIP_LEADING
const char RexxString::STRIP_LEADING = 'L' static
Definition at line 741 of file StringClass.hpp.
Referenced by strip().
STRIP_TRAILING
const char RexxString::STRIP_TRAILING = 'T' static
Definition at line 742 of file StringClass.hpp.
Referenced by strip().
UPPER
const char * RexxString::UPPER = RexxString::UPPER_ALPHA static
Definition at line 796 of file StringClass.hpp.
Referenced by BUILTIN().
UPPER_ALPHA
const char * RexxString::UPPER_ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" static
Definition at line 782 of file StringClass.hpp.
Referenced by RexxString::lookupInit::lookupInit().
UPPER_ALPHA_LOOKUP
char RexxString::UPPER_ALPHA_LOOKUP static
Definition at line 808 of file StringClass.hpp.
Referenced by StringUtil::dataType(), and RexxString::lookupInit::lookupInit().
VERIFY_MATCH
const char RexxString::VERIFY_MATCH = 'M' static
Definition at line 760 of file StringClass.hpp.
Referenced by StringUtil::verify().
VERIFY_NOMATCH
const char RexxString::VERIFY_NOMATCH = 'N' static
Definition at line 761 of file StringClass.hpp.
Referenced by StringUtil::verify().
XDIGIT
const char * RexxString::XDIGIT = "0123456789ABCDEFabcdef" static
Definition at line 797 of file StringClass.hpp.
Referenced by BUILTIN().
The documentation for this class was generated from the following files:
StringClass.hpp
StringClassBit.cpp
StringClassConversion.cpp
StringClassWord.cpp
StringClassSub.cpp
StringClassMisc.cpp
StringClass.cpp