ooRexx: RexxInstructionAddress Class Reference
RexxInstructionAddress Class Reference
#include <AddressInstruction.hpp>
Public Member Functions
void operator delete (void *)
RexxInstructionAddress ()
RexxInstructionAddress (RexxInternalObject *, RexxString *, RexxInternalObject *)
RexxInstructionAddress (RESTORETYPE restoreType)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
void execute (RexxActivation *, ExpressionStack *) override
virtual CommandIOConfiguration * getIOConfig ()
Public Member Functions inherited from RexxInstruction
void * operator new (size_t)
void operator delete (void *)
RexxInstruction (RexxClause *clause, InstructionKeyword type)
RexxInstruction (RESTORETYPE restoreType)
RexxInstruction ()
virtual bool isBlock ()
virtual bool isControl ()
const SourceLocation & getLocation ()
void setLocation (const SourceLocation &l)
void setNext (RexxInstruction *next)
RexxInstruction * next ()
bool isLast ()
void setStart (size_t line, size_t off)
void setEnd (size_t line, size_t off)
void setType (InstructionKeyword type)
InstructionKeyword getType ()
bool isType (InstructionKeyword type)
size_t getLineNumber ()
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * makeProxy (Envelope *)
virtual RexxInternalObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual RexxString * defaultName ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual ArrayClass * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual bool isInstanceOf (RexxClass *)
virtual MethodClass * instanceMethod (RexxString *)
virtual SupplierClass * instanceMethods (RexxClass *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxInternalObject * unflatten (Envelope *)
Public Attributes
RexxInternalObject * dynamicAddress
RexxString * environment
RexxInternalObject * command
Public Attributes inherited from RexxInstruction
InstructionKeyword instructionType
SourceLocation instructionLocation
RexxInstruction * nextInstruction
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Additional Inherited Members
Static Public Member Functions inherited from RexxInstruction
static void evaluateArguments (RexxActivation *context, ExpressionStack *stack, RexxInternalObject **argArray, size_t argCount)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 51 of file AddressInstruction.hpp.
Constructor & Destructor Documentation
RexxInstructionAddress() [1/3]
RexxInstructionAddress::RexxInstructionAddress () inline
Definition at line 56 of file AddressInstruction.hpp.
RexxInstructionAddress() [2/3]
RexxInstructionAddress::RexxInstructionAddress (RexxInternalObject * _expression, RexxString * _environment, RexxInternalObject * _command)
Constructor for an Address instruction object.
Parameters
_expression An optional expression for ADDRESS VALUE forms.
_environment A static environment name.
_command A command expression to be issued.
Definition at line 60 of file AddressInstruction.cpp.
References command, dynamicAddress, and environment.
RexxInstructionAddress() [3/3]
RexxInstructionAddress::RexxInstructionAddress (RESTORETYPE restoreType) inline
Definition at line 58 of file AddressInstruction.hpp.
Member Function Documentation
execute()
void RexxInstructionAddress::execute (RexxActivation * context, ExpressionStack * stack) override virtual
Execute an addres instruction.
Parameters
context The current program execution context.
stack The current evaluation stack.
Reimplemented from RexxInstruction.
Definition at line 127 of file AddressInstruction.cpp.
References RexxActivation::command(), command, dynamicAddress, environment, RexxInternalObject::evaluate(), getIOConfig(), OREF_NULL, RexxActivation::pauseInstruction(), ExpressionStack::push(), RexxInternalObject::requestString(), RexxActivation::setAddress(), RexxActivation::toggleAddress(), RexxActivation::traceCommand(), RexxActivation::traceInstruction(), RexxActivation::traceResult(), RexxActivation::traceResultValue(), RexxActivation::tracingCommands(), and SystemInterpreter::validateAddressName().
flatten()
void RexxInstructionAddress::flatten (Envelope * envelope) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxInstruction.
Definition at line 109 of file AddressInstruction.cpp.
References cleanUpFlatten, command, dynamicAddress, environment, flattenRef, RexxInstruction::nextInstruction, and setUpFlatten.
getIOConfig()
virtual CommandIOConfiguration* RexxInstructionAddress::getIOConfig () inline virtual
Reimplemented in RexxInstructionAddressWith.
Definition at line 65 of file AddressInstruction.hpp.
References OREF_NULL.
Referenced by execute().
live()
void RexxInstructionAddress::live (size_t liveMark) override virtual
Perform garbage collection on a live object.
Parameters
liveMark The current live mark.
Reimplemented from RexxInstruction.
Definition at line 75 of file AddressInstruction.cpp.
References command, dynamicAddress, environment, memory_mark, and RexxInstruction::nextInstruction.
liveGeneral()
void RexxInstructionAddress::liveGeneral (MarkReason reason) override virtual
Perform generalized live marking on an object. This is used when mark-and-sweep processing is needed for purposes other than garbage collection.
Parameters
reason The reason for the marking call.
Reimplemented from RexxInstruction.
Definition at line 92 of file AddressInstruction.cpp.
References command, dynamicAddress, environment, memory_mark_general, and RexxInstruction::nextInstruction.
operator delete()
void RexxInstructionAddress::operator delete (void *) inline
Definition at line 54 of file AddressInstruction.hpp.
Member Data Documentation
command
RexxInternalObject* RexxInstructionAddress::command
Definition at line 69 of file AddressInstruction.hpp.
Referenced by execute(), flatten(), RexxInstructionAddressWith::flatten(), live(), RexxInstructionAddressWith::live(), liveGeneral(), RexxInstructionAddressWith::liveGeneral(), and RexxInstructionAddress().
dynamicAddress
RexxInternalObject* RexxInstructionAddress::dynamicAddress
Definition at line 67 of file AddressInstruction.hpp.
Referenced by execute(), flatten(), RexxInstructionAddressWith::flatten(), live(), RexxInstructionAddressWith::live(), liveGeneral(), RexxInstructionAddressWith::liveGeneral(), and RexxInstructionAddress().
environment
RexxString* RexxInstructionAddress::environment
Definition at line 68 of file AddressInstruction.hpp.
Referenced by execute(), flatten(), RexxInstructionAddressWith::flatten(), live(), RexxInstructionAddressWith::live(), liveGeneral(), RexxInstructionAddressWith::liveGeneral(), and RexxInstructionAddress().
The documentation for this class was generated from the following files:
AddressInstruction.hpp
AddressInstruction.cpp