ooRexx: ControlledLoop Class Reference
ControlledLoop Class Reference
#include <DoBlockComponents.hpp>
Public Member Functions
ControlledLoop ()
void live (size_t liveMark)
void liveGeneral (MarkReason reason)
void operator= (const ControlledLoop &c)
void setup (RexxActivation *context, ExpressionStack *stack, DoBlock *doblock)
Public Member Functions inherited from ForLoop
ForLoop ()
void live (size_t liveMark)
void liveGeneral (MarkReason reason)
void setup (RexxActivation *context, ExpressionStack *stack, DoBlock *doblock, bool forKeyword)
Public Attributes
RexxVariableBase * control
RexxInternalObject * initial
RexxInternalObject * to
RexxInternalObject * by
uint8_t expressions [3]
Public Attributes inherited from ForLoop
RexxInternalObject * forCount
Detailed Description
An embedded object that manages the details of controlled loop execution (all keywords).
Definition at line 91 of file DoBlockComponents.hpp.
Constructor & Destructor Documentation
ControlledLoop()
ControlledLoop::ControlledLoop () inline
Definition at line 94 of file DoBlockComponents.hpp.
References EXP_NONE, and expressions.
Member Function Documentation
live()
void ControlledLoop::live (size_t liveMark) inline
Definition at line 103 of file DoBlockComponents.hpp.
References by, control, ForLoop::forCount, initial, memory_mark, and to.
Referenced by RexxInstructionControlledDo::live(), and RexxInstructionControlledDoUntil::live().
liveGeneral()
void ControlledLoop::liveGeneral (MarkReason reason) inline
Definition at line 111 of file DoBlockComponents.hpp.
References by, control, ForLoop::forCount, initial, memory_mark_general, and to.
Referenced by RexxInstructionControlledDo::liveGeneral(), and RexxInstructionControlledDoUntil::liveGeneral().
operator=()
void ControlledLoop::operator= (const ControlledLoop & c) inline
An assignment override that ensures that we don't pick up any padding from the assigned instance.
Parameters
c The assignment source.
Definition at line 125 of file DoBlockComponents.hpp.
References by, control, expressions, ForLoop::forCount, initial, and to.
setup()
void ControlledLoop::setup (RexxActivation * context, ExpressionStack * stack, DoBlock * doblock)
Set up for execution of a controlled loop.
Parameters
context The current execution context.
stack The current evaluation stack.
doblock The context doblock useds to store loop state data.
Definition at line 122 of file DoBlockComponents.cpp.
References RexxVariableBase::assign(), by, RexxObject::callOperatorMethod(), control, RexxInternalObject::evaluate(), EXP_BY, EXP_FOR, EXP_TO, expressions, ForLoop::forCount, initial, IntegerOne, IntegerZero, number_digits(), OPERATOR_GREATERTHAN, OPERATOR_LESSTHAN, OPERATOR_PLUS, OREF_NULL, DoBlock::setBy(), DoBlock::setCompare(), DoBlock::setControl(), DoBlock::setFor(), DoBlock::setTo(), ForLoop::setup(), SIZE_MAX, TheNilObject, TheTrueObject, to, and RexxActivation::traceKeywordResult().
Referenced by RexxInstructionControlledDo::setup().
Member Data Documentation
by
RexxInternalObject* ControlledLoop::by
Definition at line 146 of file DoBlockComponents.hpp.
Referenced by RexxInstructionControlledDo::flatten(), RexxInstructionControlledDoUntil::flatten(), live(), liveGeneral(), operator=(), and setup().
control
RexxVariableBase* ControlledLoop::control
Definition at line 143 of file DoBlockComponents.hpp.
Referenced by RexxInstructionControlledDo::flatten(), RexxInstructionControlledDoUntil::flatten(), live(), liveGeneral(), operator=(), and setup().
expressions
uint8_t ControlledLoop::expressions[3]
Definition at line 147 of file DoBlockComponents.hpp.
Referenced by ControlledLoop(), operator=(), and setup().
initial
RexxInternalObject* ControlledLoop::initial
Definition at line 144 of file DoBlockComponents.hpp.
Referenced by RexxInstructionControlledDo::flatten(), RexxInstructionControlledDoUntil::flatten(), live(), liveGeneral(), operator=(), and setup().
to
RexxInternalObject* ControlledLoop::to
Definition at line 145 of file DoBlockComponents.hpp.
Referenced by RexxInstructionControlledDo::flatten(), RexxInstructionControlledDoUntil::flatten(), live(), liveGeneral(), operator=(), and setup().
The documentation for this class was generated from the following files:
DoBlockComponents.hpp
DoBlockComponents.cpp