ooRexx: TreeFinder Class Reference
TreeFinder Class Reference
#include <RexxUtilCommon.hpp>
Classes
class AttributeMask
Public Types
enum OptionFlags {
RECURSE , DO_DIRS , DO_FILES , NAME_ONLY ,
EDITABLE_TIME , LONG_TIME , CASELESS , LONG_SIZE
}
enum TreeFinderException { InvalidFileName }
Public Member Functions
TreeFinder (RexxCallContext *c, const char *f, RexxObjectPtr sa, const char *opts, const char *targetAttr, const char *newAttr)
~TreeFinder ()
void findFiles ()
void validateFileSpec ()
void adjustDirectory ()
void validateFileSpecName ()
void parseMask (const char *mask, AttributeMask &flags, size_t argPos)
void badSFTOptsException (const char *actual)
void badMaskException (size_t pos, const char *actual)
void getOptions (const char *opts)
bool goodOpts (const char *opts)
void formatFile (const char *fileName)
void getFullPath ()
void expandNonPath2fullPath ()
void expandPath2fullPath (size_t lastSlashPos)
void adjustFileSpec ()
void checkFile (SysFileIterator::FileAttributes &attributes)
void recursiveFindFile (FileNameBuffer &path)
void addResult (const char *v)
int findDirectoryEnd ()
bool checkNonPathDrive ()
void fixupFilePath ()
bool includeDirs ()
bool includeFiles ()
bool acceptAll ()
bool nameOnly ()
bool longTime ()
bool editableTime ()
bool longSize ()
bool archiveSelected (bool onOff)
bool directorySelected (bool onOff)
bool hiddenSelected (bool onOff)
bool readOnlySelected (bool onOff)
bool systemSelected (bool onOff)
Protected Attributes
RexxCallContext * context
StemHandler stemArray
RoutineFileNameBuffer filePath
RoutineFileNameBuffer fileSpec
RoutineFileNameBuffer foundFile
RoutineFileNameBuffer foundFileLine
RoutineFileNameBuffer nameSpec
FlagSet< OptionFlags, 8 > options
AttributeMask targetAttributes
AttributeMask newAttributes
Detailed Description
Definition at line 260 of file RexxUtilCommon.hpp.
Member Enumeration Documentation
OptionFlags
enum TreeFinder::OptionFlags
Enumerator
RECURSE
DO_DIRS
DO_FILES
NAME_ONLY
EDITABLE_TIME
LONG_TIME
CASELESS
LONG_SIZE
Definition at line 264 of file RexxUtilCommon.hpp.
TreeFinderException
enum TreeFinder::TreeFinderException
A set of enumerations for catching exceptions that need to be reported as SysFileTree return values and not as Rexx error conditions.
Enumerator
InvalidFileName
Definition at line 280 of file RexxUtilCommon.hpp.
Constructor & Destructor Documentation
TreeFinder()
TreeFinder::TreeFinder (RexxCallContext * c, const char * f, RexxObjectPtr sa, const char * opts, const char * targetAttr, const char * newAttr)
Definition at line 311 of file RexxUtilCommon.cpp.
References fileSpec, getOptions(), newAttributes, parseMask(), targetAttributes, and validateFileSpec().
~TreeFinder()
TreeFinder::~TreeFinder ()
The destructor for the tree finder, which finalizes the return stem value.
Definition at line 331 of file RexxUtilCommon.cpp.
References StemHandler::complete(), and stemArray.
Member Function Documentation
acceptAll()
bool TreeFinder::acceptAll () inline
Definition at line 390 of file RexxUtilCommon.hpp.
References TreeFinder::AttributeMask::acceptAll(), and targetAttributes.
Referenced by checkInclusion().
addResult()
void TreeFinder::addResult (const char * v)
add a result to the return stem
Parameters
v The string value to add as the next stem element.
Definition at line 743 of file RexxUtilCommon.cpp.
References StemHandler::addValue(), and stemArray.
Referenced by checkFile().
adjustDirectory()
void TreeFinder::adjustDirectory ()
if this ends in a directory separator, add a *.* wildcard to the end
if this ends in a directory separator, add a * wildcard to the end
Definition at line 319 of file unix/SysRexxUtil.cpp.
References SysFileSystem::canonicalizeName(), FileNameBuffer::endsWith(), fileSpec, and FileNameBuffer::startsWith().
Referenced by validateFileSpec().
adjustFileSpec()
void TreeFinder::adjustFileSpec ()
Perform any platform-specific adjustments to the platform specification.
Definition at line 346 of file unix/SysRexxUtil.cpp.
Referenced by validateFileSpec().
archiveSelected()
bool TreeFinder::archiveSelected (bool onOff) inline
Definition at line 396 of file RexxUtilCommon.hpp.
References TreeFinder::AttributeMask::Archive, TreeFinder::AttributeMask::isSelected(), and targetAttributes.
Referenced by checkInclusion().
badMaskException()
void TreeFinder::badMaskException (size_t pos, const char * actual)
Throw an exception for an invalid mask argument.
Parameters
pos The argument position
actual The specified argument
Definition at line 442 of file RexxUtilCommon.cpp.
References context, and Rexx_Error_Incorrect_call_user_defined.
Referenced by parseMask().
badSFTOptsException()
void TreeFinder::badSFTOptsException (const char * actual)
Throw an error for bad options.
Parameters
actual The specified options string
Definition at line 426 of file RexxUtilCommon.cpp.
References context, and Rexx_Error_Incorrect_call_user_defined.
Referenced by getOptions().
checkFile()
void TreeFinder::checkFile (SysFileIterator::FileAttributes & attributes)
Checks if this file should be part of the included result and adds it to the result set if it should be returned.
Parameters
attributes The file attributes for the file we're checking.
Checks if this file should be part of the included result and adds it to the result set if it should be returned.
Definition at line 477 of file unix/SysRexxUtil.cpp.
References addResult(), DO_DIRS, DO_FILES, SysFileIterator::FileAttributes::findFileData, formatFileAttributes(), foundFile, foundFileLine, nameOnly(), and options.
Referenced by recursiveFindFile().
checkNonPathDrive()
bool TreeFinder::checkNonPathDrive ()
Perform platform-specific drive checks on the file spec. This only applies to Windows.
Returns
true if this was processed, false if additional work is required.
Definition at line 370 of file unix/SysRexxUtil.cpp.
Referenced by expandNonPath2fullPath().
directorySelected()
bool TreeFinder::directorySelected (bool onOff) inline
Definition at line 397 of file RexxUtilCommon.hpp.
References TreeFinder::AttributeMask::Directory, TreeFinder::AttributeMask::isSelected(), and targetAttributes.
Referenced by checkInclusion().
editableTime()
bool TreeFinder::editableTime () inline
Definition at line 393 of file RexxUtilCommon.hpp.
References EDITABLE_TIME, and options.
Referenced by formatFileAttributes().
expandNonPath2fullPath()
void TreeFinder::expandNonPath2fullPath ()
Create a path from a file spec that does not include path information.
Parameters
path The returned path
Definition at line 582 of file RexxUtilCommon.cpp.
References FileNameBuffer::addFinalPathDelimiter(), checkNonPathDrive(), filePath, fileSpec, SysFileSystem::getCurrentDirectory(), and nameSpec.
Referenced by getFullPath().
expandPath2fullPath()
void TreeFinder::expandPath2fullPath (size_t lastSlashPos)
Splits the the file spec into a path portion and a name portion. There is at least one directory delimiter in the fileSpec.
Parameters
lastSlashPos Position of the last directory character in the file spec.
Definition at line 626 of file RexxUtilCommon.cpp.
References FileNameBuffer::endsWith(), filePath, fileSpec, fixupFilePath(), nameSpec, SysFileSystem::PathDelimiter, and FileNameBuffer::set().
Referenced by getFullPath().
findDirectoryEnd()
int TreeFinder::findDirectoryEnd ()
Platform-specific TreeFinder method for locating the end of the fileSpec directory
Returns
The position of the end of the directory. -1 indicates the file spec does not contain a directory.
Definition at line 524 of file unix/SysRexxUtil.cpp.
References FileNameBuffer::at(), fileSpec, and FileNameBuffer::length().
Referenced by getFullPath().
findFiles()
void TreeFinder::findFiles ()
Main method for driving the validation of options and file names and then performing the file searches.
Returns
Any approriate error codes, or 0 for success.
Definition at line 344 of file RexxUtilCommon.cpp.
References filePath, getFullPath(), and recursiveFindFile().
Referenced by RexxRoutine5().
fixupFilePath()
void TreeFinder::fixupFilePath ()
Perform any platform-specific fixup that might be required with the supplied path.
Definition at line 543 of file unix/SysRexxUtil.cpp.
References FileNameBuffer::addFinalPathDelimiter(), context, and filePath.
Referenced by expandPath2fullPath().
formatFile()
void TreeFinder::formatFile (const char * fileName)
getFullPath()
void TreeFinder::getFullPath ()
This function expands the file spec into its full path name. The full path name is then split into the path portion and the file name portion. The path portion is then returned in filePath and the file name portion is returned in nameSpec.
The filePath portion will end with the PathDelimiter character if the filespec contains a path.
Definition at line 555 of file RexxUtilCommon.cpp.
References expandNonPath2fullPath(), expandPath2fullPath(), and findDirectoryEnd().
Referenced by findFiles().
getOptions()
void TreeFinder::getOptions (const char * opts)
Checks the validity of the options argument to SysFileTree and converts the character based argument to the proper set of flags.
Parameters
opts The call arguments
Definition at line 460 of file RexxUtilCommon.cpp.
References badSFTOptsException(), context, DO_DIRS, DO_FILES, goodOpts(), nullStringException(), and options.
Referenced by TreeFinder().
goodOpts()
bool TreeFinder::goodOpts (const char * opts)
Determines the options by converting the character based argument to the correct set of flags.
Parameters
opts The options string
Returns
true if the options were ok, false if any invalid options were encountered.
Definition at line 489 of file RexxUtilCommon.cpp.
References CASELESS, DO_DIRS, DO_FILES, EDITABLE_TIME, LONG_SIZE, LONG_TIME, NAME_ONLY, options, RECURSE, and Utilities::toUpper().
Referenced by getOptions().
hiddenSelected()
bool TreeFinder::hiddenSelected (bool onOff) inline
Definition at line 398 of file RexxUtilCommon.hpp.
References TreeFinder::AttributeMask::Hidden, TreeFinder::AttributeMask::isSelected(), and targetAttributes.
Referenced by checkInclusion().
includeDirs()
bool TreeFinder::includeDirs () inline
Definition at line 388 of file RexxUtilCommon.hpp.
References DO_DIRS, and options.
Referenced by checkInclusion().
includeFiles()
bool TreeFinder::includeFiles () inline
Definition at line 389 of file RexxUtilCommon.hpp.
References DO_FILES, and options.
Referenced by checkInclusion().
longSize()
bool TreeFinder::longSize () inline
Definition at line 394 of file RexxUtilCommon.hpp.
References LONG_SIZE, and options.
Referenced by formatFileAttributes().
longTime()
bool TreeFinder::longTime () inline
Definition at line 392 of file RexxUtilCommon.hpp.
References LONG_TIME, and options.
Referenced by formatFileAttributes().
nameOnly()
bool TreeFinder::nameOnly () inline
Definition at line 391 of file RexxUtilCommon.hpp.
References NAME_ONLY, and options.
Referenced by checkFile().
parseMask()
void TreeFinder::parseMask (const char * mask, AttributeMask & flags, size_t argPos)
Checks the validity of an attribute mask argument and converts the character based mask into an integer based mask.
Parameters
mask The mask specified on the call.
flags The set of flags to set.
argPos The argument position for error reporting
Definition at line 404 of file RexxUtilCommon.cpp.
References badMaskException(), and TreeFinder::AttributeMask::parseMask().
Referenced by TreeFinder().
readOnlySelected()
bool TreeFinder::readOnlySelected (bool onOff) inline
Definition at line 399 of file RexxUtilCommon.hpp.
References TreeFinder::AttributeMask::isSelected(), TreeFinder::AttributeMask::ReadOnly, and targetAttributes.
Referenced by checkInclusion().
recursiveFindFile()
void TreeFinder::recursiveFindFile (FileNameBuffer & path)
Finds all files matching a file specification, formats a file name line and adds the formatted line to a stem. Much of the data to complete this operation is contained in the treeData struct.
This is a recursive function that may search through subdirectories if the recurse option is used.
Parameters
path Current directory we are searching.
Definition at line 662 of file RexxUtilCommon.cpp.
References CASELESS, checkFile(), SysFileIterator::close(), context, foundFile, SysFileIterator::hasNext(), SysFileIterator::FileAttributes::isDirectory(), FileNameBuffer::length(), nameSpec, SysFileIterator::next(), options, SysFileSystem::PathDelimiter, and RECURSE.
Referenced by findFiles().
systemSelected()
bool TreeFinder::systemSelected (bool onOff) inline
Definition at line 400 of file RexxUtilCommon.hpp.
References TreeFinder::AttributeMask::isSelected(), TreeFinder::AttributeMask::System, and targetAttributes.
Referenced by checkInclusion().
validateFileSpec()
void TreeFinder::validateFileSpec ()
The file specification consists of the search string as sent by the Rexx user, with possibly some glob characters added.
If the file specification ends in a (back)slash or a period ('.') or two periods ('..'), then a wild card specification ('*') is appended.
However, note that there is also the case where a single '.' at the end of the file specification is not used as a directory specifier, but rather is tacked on to the end of a file name.
Windows has a sometimes used convention that a '.' at the end of a file name can be used to indicate the file has no extension. For example, given a file named: MyFile a command of "dir MyFile." will produce a listing of "MyFile".
In this case we want to leave the file specification alone. that is, do not append a '*'. A command of "dir *." will produce a directory listing of all files that do not have an extension.
Definition at line 376 of file RexxUtilCommon.cpp.
References adjustDirectory(), adjustFileSpec(), context, fileSpec, FileNameBuffer::length(), nullStringException(), and validateFileSpecName().
Referenced by TreeFinder().
validateFileSpecName()
void TreeFinder::validateFileSpecName ()
Tests for illegal file name characters in fileSpec. The only really forbidden characters in unix file names are '/' (which is allowed in the path) and '\0' (which is the string terminator. This is really a nop.
Tests for illegal file name characters in fileSpec
Note
Double quotes in the file spec is not valid, spaces in file names do not need to be within quotes in the string passed to the Windows API.
A ':' is only valid if it is the second character. Technically a '*' and a '?' are not valid characters for a file name, but they are okay for fSpec. Same thing for '\' and '/', they are not valid in a file name, but they are valid in fSpec. A '/' is iffy. The Windows API accepts '/' as a directory separator, but most Rexx programmers probably don't know that. Not sure if we should flag that as illegal or not.
Definition at line 358 of file unix/SysRexxUtil.cpp.
Referenced by validateFileSpec().
Member Data Documentation
context
RexxCallContext* TreeFinder::context protected
Definition at line 404 of file RexxUtilCommon.hpp.
Referenced by badMaskException(), badSFTOptsException(), fixupFilePath(), getOptions(), recursiveFindFile(), and validateFileSpec().
filePath
RoutineFileNameBuffer TreeFinder::filePath protected
Definition at line 406 of file RexxUtilCommon.hpp.
Referenced by expandNonPath2fullPath(), expandPath2fullPath(), findFiles(), and fixupFilePath().
fileSpec
RoutineFileNameBuffer TreeFinder::fileSpec protected
Definition at line 407 of file RexxUtilCommon.hpp.
Referenced by adjustDirectory(), expandNonPath2fullPath(), expandPath2fullPath(), findDirectoryEnd(), TreeFinder(), and validateFileSpec().
foundFile
RoutineFileNameBuffer TreeFinder::foundFile protected
Definition at line 408 of file RexxUtilCommon.hpp.
Referenced by checkFile(), and recursiveFindFile().
foundFileLine
RoutineFileNameBuffer TreeFinder::foundFileLine protected
Definition at line 409 of file RexxUtilCommon.hpp.
Referenced by checkFile().
nameSpec
RoutineFileNameBuffer TreeFinder::nameSpec protected
Definition at line 410 of file RexxUtilCommon.hpp.
Referenced by expandNonPath2fullPath(), expandPath2fullPath(), and recursiveFindFile().
newAttributes
AttributeMask TreeFinder::newAttributes protected
Definition at line 413 of file RexxUtilCommon.hpp.
Referenced by TreeFinder().
options
FlagSet<OptionFlags, 8> TreeFinder::options protected
Definition at line 411 of file RexxUtilCommon.hpp.
Referenced by checkFile(), editableTime(), getOptions(), goodOpts(), includeDirs(), includeFiles(), longSize(), longTime(), nameOnly(), and recursiveFindFile().
stemArray
StemHandler TreeFinder::stemArray protected
Definition at line 405 of file RexxUtilCommon.hpp.
Referenced by addResult(), and ~TreeFinder().
targetAttributes
AttributeMask TreeFinder::targetAttributes protected
Definition at line 412 of file RexxUtilCommon.hpp.
Referenced by acceptAll(), archiveSelected(), directorySelected(), hiddenSelected(), readOnlySelected(), systemSelected(), and TreeFinder().
The documentation for this class was generated from the following files:
RexxUtilCommon.hpp
unix/SysRexxUtil.cpp
windows/SysRexxUtil.cpp
RexxUtilCommon.cpp