ooRexx: SingleObjectSegmentSet Class Reference
SingleObjectSegmentSet Class Reference
#include <MemorySegment.hpp>
Public Member Functions
SingleObjectSegmentSet ()
SingleObjectSegmentSet (MemoryObject *memory)
virtual ~SingleObjectSegmentSet ()
void dumpMemoryProfile (FILE *outfile) override
RexxInternalObject * handleAllocationFailure (size_t allocationLength)
RexxInternalObject * allocateObject (size_t allocationLength)
Public Member Functions inherited from MemorySegmentSet
MemorySegmentSet (MemoryObject *memObject, SegmentSetID id, const char *setName)
MemorySegmentSet ()
virtual ~MemorySegmentSet ()
void removeSegment (MemorySegment *segment)
void removeSegmentAndStorage (MemorySegment *segment)
void add (MemorySegment *segment)
MemorySegment * first ()
MemorySegment * next (MemorySegment *segment)
void transferSegment (MemorySegment *segment)
void dumpSegments (FILE *keyfile, FILE *dumpfile)
void addSegment (MemorySegment *segment)
void sweep ()
void sweepSingleSegment (MemorySegment *sweepSegment)
bool is (SegmentSetID id)
void gatherStats (MemoryStats *memStats, SegmentStats *stats)
MemorySegment * largestActiveSegment ()
virtual DeadObject * donateObject (size_t allocationLength)
Protected Member Functions
void addDeadObject (DeadObject *object) override
void addDeadObject (char *object, size_t length) override
MemorySegment * allocateSegment (size_t requestLength, size_t minimumLength) override
void completeSweepOperation () override
Protected Member Functions inherited from MemorySegmentSet
RexxInternalObject * splitDeadObject (DeadObject *object, size_t allocationLength, size_t splitMinimum)
void insertSegment (MemorySegment *segment)
virtual size_t suggestMemoryExpansion ()
virtual void prepareForSweep ()
void adjustMemorySize ()
bool newSegment (size_t requestLength, size_t minimumLength)
float freeMemoryPercentage ()
size_t totalFreeMemory ()
size_t calculateSegmentAllocation (size_t n)
void addSegments (size_t requiredSpace)
void validateObject (RexxInternalObject *o)
Private Attributes
size_t allocationsSinceLastGC
size_t allocationCount
size_t returnCount
Static Private Attributes
static const size_t ForceGCThreshold = 4
Additional Inherited Members
Public Types inherited from MemorySegmentSet
enum SegmentSetID {
SET_UNINITIALIZED , SET_NORMAL , SET_LARGEBLOCK , SET_OLDSPACE ,
SET_SINGLEOBJECT
}
Static Public Attributes inherited from MemorySegmentSet
static const size_t MinimumSegmentSize = (MemorySegment::SegmentSize/2)
static const size_t MinimumSegmentDeadSpace = (MinimumSegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentSize = (MemorySegment::SegmentSize * 4)
static const size_t SegmentDeadSpace = (MemorySegment::SegmentSize - MemorySegment::MemorySegmentOverhead)
static const size_t LargeSegmentDeadSpace = (LargeSegmentSize - MemorySegment::MemorySegmentOverhead)
Protected Attributes inherited from MemorySegmentSet
MemorySegment anchor
size_t count
size_t liveObjectBytes
size_t deadObjectBytes
SegmentSetID owner
const char * name
MemoryObject * memory
Detailed Description
A segment set used for allocating the largest objects. We allocate a segment dedicated to each object and will return the segment when the object is garbage collected.
Definition at line 596 of file MemorySegment.hpp.
Constructor & Destructor Documentation
SingleObjectSegmentSet() [1/2]
SingleObjectSegmentSet::SingleObjectSegmentSet () inline
Definition at line 601 of file MemorySegment.hpp.
SingleObjectSegmentSet() [2/2]
SingleObjectSegmentSet::SingleObjectSegmentSet (MemoryObject * mem)
Constructor for a single object segment set.
Parameters
mem The hosting memory object.
Definition at line 220 of file MemorySegment.cpp.
~SingleObjectSegmentSet()
virtual SingleObjectSegmentSet::~SingleObjectSegmentSet () inline virtual
Definition at line 603 of file MemorySegment.hpp.
Member Function Documentation
addDeadObject() [1/2]
void SingleObjectSegmentSet::addDeadObject (char * object, size_t length) override protected virtual
Add a section of memory as a dead object to our pool.
Parameters
object The address of the memory.
length The length of the dead memory.
Reimplemented from MemorySegmentSet.
Definition at line 494 of file MemorySegment.cpp.
addDeadObject() [2/2]
void SingleObjectSegmentSet::addDeadObject (DeadObject * object) override protected virtual
Add a dead object to the segment set during the sweep operation.
Parameters
object The newly dead object.
Reimplemented from MemorySegmentSet.
Definition at line 395 of file MemorySegment.cpp.
allocateObject()
RexxInternalObject * SingleObjectSegmentSet::allocateObject (size_t requestLength)
Allocate an extremely large object. These are contained in a single segment so that we can release the large blocks of storage once the object is dead.
Parameters
requestLength The size of the required object.
Returns
A newly allocated object or NULL for an allocation failure.
Definition at line 1331 of file MemorySegment.cpp.
References allocateSegment(), allocationCount, allocationsSinceLastGC, MemorySegmentSet::anchor, MemorySegment::createDeadObject(), ForceGCThreshold, MemorySegment::insertBefore(), line_end, MemorySegmentSet::memory, MemorySegmentSet::name, MemorySegmentHeader::next, OREF_NULL, MemorySegment::size(), and MemoryObject::verboseMessage().
Referenced by handleAllocationFailure(), and MemoryObject::newObject().
allocateSegment()
MemorySegment * SingleObjectSegmentSet::allocateSegment (size_t requestLength, size_t minimumLength) override protected virtual
Allocate a memory segment for the SingleObject set. This will allocate the object to the minimum size.
Parameters
requestLength The requested length.
minimumLength The minimum length that will satisfy the request.
Returns
A new memory segment object, or NULL if this could not be allocated.
Reimplemented from MemorySegmentSet.
Definition at line 335 of file MemorySegment.cpp.
References MemorySegmentSet::memory, and MemoryObject::newLargeSegment().
Referenced by allocateObject().
completeSweepOperation()
void SingleObjectSegmentSet::completeSweepOperation () override protected virtual
Handle post-sweep processing for the set.
Reimplemented from MemorySegmentSet.
Definition at line 901 of file MemorySegment.cpp.
References MemorySegmentSet::first(), MemoryObject::freeSegment(), RexxInternalObject::getObjectSize(), MemorySegment::isEmpty(), line_end, MemorySegmentSet::memory, MemorySegmentSet::next(), MemorySegment::remove(), MemorySegment::size(), MemorySegment::startObject(), MemoryObject::transferSegmentToNormalSet(), and MemoryObject::verboseMessage().
dumpMemoryProfile()
void SingleObjectSegmentSet::dumpMemoryProfile (FILE * outfile) override virtual
Dump profile informaton about the single object allocation segment set
Parameters
outfile The target dump file.
Reimplemented from MemorySegmentSet.
Definition at line 156 of file MemorySegment.cpp.
References allocationCount, and returnCount.
handleAllocationFailure()
RexxInternalObject * SingleObjectSegmentSet::handleAllocationFailure (size_t allocationLength)
Handle a first-attempt allocation failure from the single object segment set. A failure here means we were unable to obtain a block of the required size from the system. Our only option now is to force a garbage collection which might free up enough memory that the system can fullfil the request.
Parameters
allocationLength The size of the object that caused the original allocation failure.
Returns
An allocated object. If unable to allocate, this raised the resource exception.
Definition at line 1277 of file MemorySegment.cpp.
References allocateObject(), allocationsSinceLastGC, MemoryObject::collect(), Error_System_resources, line_end, MemorySegmentSet::memory, OREF_NULL, reportException(), and MemoryObject::verboseMessage().
Referenced by MemoryObject::newObject().
Member Data Documentation
allocationCount
size_t SingleObjectSegmentSet::allocationCount private
Definition at line 624 of file MemorySegment.hpp.
Referenced by allocateObject(), and dumpMemoryProfile().
allocationsSinceLastGC
size_t SingleObjectSegmentSet::allocationsSinceLastGC private
Definition at line 623 of file MemorySegment.hpp.
Referenced by allocateObject(), and handleAllocationFailure().
ForceGCThreshold
const size_t SingleObjectSegmentSet::ForceGCThreshold = 4 static private
Definition at line 621 of file MemorySegment.hpp.
Referenced by allocateObject().
returnCount
size_t SingleObjectSegmentSet::returnCount private
Definition at line 625 of file MemorySegment.hpp.
Referenced by dumpMemoryProfile().
The documentation for this class was generated from the following files:
MemorySegment.hpp
MemorySegment.cpp