ooRexx: DirectoryClass Class Reference
DirectoryClass Class Reference
#include <DirectoryClass.hpp>
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
DirectoryClass (RESTORETYPE restoreType)
DirectoryClass (size_t capacity=HashCollection::DefaultTableSize)
DirectoryClass (bool fromRexx)
RexxObject * newRexx (RexxObject **, size_t)
void live (size_t) override
void liveGeneral (MarkReason reason) override
void flatten (Envelope *) override
RexxObject * makeProxy (Envelope *) override
RexxInternalObject * copy () override
size_t items () override
SupplierClass * supplier () override
ArrayClass * allIndexes () override
ArrayClass * allItems () override
bool hasIndex (RexxInternalObject *indexName) override
RexxInternalObject * remove (RexxInternalObject *entryname) override
RexxInternalObject * get (RexxInternalObject *index) override
void put (RexxInternalObject *value, RexxInternalObject *index) override
void empty () override
RexxInternalObject * getIndex (RexxInternalObject *target) override
bool hasItem (RexxInternalObject *target) override
RexxInternalObject * removeItem (RexxInternalObject *target) override
RexxInternalObject * setMethodRexx (RexxString *entryname, MethodClass *methodobj)
RexxInternalObject * unsetMethodRexx (RexxString *entryname)
RexxInternalObject * methodTableValue (RexxInternalObject *index)
RexxInternalObject * unknownValue (RexxInternalObject *index)
Public Member Functions inherited from StringHashCollection
StringHashCollection (size_t capacity)
StringHashCollection ()
HashContents * allocateContents (size_t bucketSize, size_t capacity) override
void validateIndex (RexxObject *&index) override
bool requiresRehash () override
virtual bool hasEntry (RexxString *entryName)
virtual void setEntry (RexxString *entryname, RexxInternalObject *entryobj)
virtual RexxInternalObject * entry (RexxString *index)
virtual RexxInternalObject * removeEntry (RexxString *index)
virtual RexxObject * unknown (RexxString *msgname, RexxObject **arguments, size_t count)
void processUnknown (RexxErrorCodes error, RexxString *, RexxObject **, size_t, ProtectedObject &) override
RexxObject * entryRexx (RexxObject *entryName)
RexxObject * hasEntryRexx (RexxObject *entryName)
RexxObject * setEntryRexx (RexxObject *entryname, RexxObject *entryobj)
RexxObject * removeEntryRexx (RexxObject *entryName)
RexxObject * unknownRexx (RexxString *message, ArrayClass *arguments)
Public Member Functions inherited from HashCollection
HashCollection ()
RexxInternalObject * unflatten (Envelope *) override
ArrayClass * makeArray () override
virtual void validateValueIndex (RexxObject *&value, RexxObject *&index)
void initialize (size_t capacity=DefaultTableSize)
void copyValues ()
void expandContents ()
void expandContents (size_t capacity)
void ensureCapacity (size_t delta)
void checkFull ()
HashContents::TableIterator iterator ()
HashContents::ReverseTableIterator reverseIterator ()
HashContents::IndexIterator iterator (RexxInternalObject *index)
virtual void mergeItem (RexxInternalObject *, RexxInternalObject *)
RexxObject * initRexx (RexxObject *)
RexxObject * removeRexx (RexxObject *)
RexxObject * getRexx (RexxObject *)
RexxObject * putRexx (RexxObject *, RexxObject *)
RexxObject * addRexx (RexxObject *, RexxObject *)
RexxObject * hasIndexRexx (RexxObject *)
RexxObject * hasItemRexx (RexxObject *)
RexxObject * removeItemRexx (RexxObject *value)
ArrayClass * allAtRexx (RexxObject *)
RexxObject * indexRexx (RexxObject *value)
SupplierClass * supplierRexx ()
ArrayClass * allItemsRexx ()
ArrayClass * allIndexesRexx ()
RexxObject * emptyRexx ()
RexxObject * isEmptyRexx ()
RexxObject * itemsRexx ()
void merge (HashCollection *)
void putAll (HashCollection *)
void reHash ()
ArrayClass * uniqueIndexes ()
bool isEmpty ()
Public Member Functions inherited from RexxObject
void * operator new (size_t)
void operator delete (void *)
RexxObject * newRexx (RexxObject **arguments, size_t argCount)
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
RexxObject * defineInstanceMethod (RexxString *, MethodClass *, RexxClass *)
RexxObject * deleteInstanceMethod (RexxString *msgname)
RexxString * defaultName () override
virtual bool hasMethod (RexxString *msg)
RexxObject * hasMethodRexx (RexxString *)
bool hasUninitMethod ()
RexxObject * initRexx ()
void uninit () override
HashCode hash () override
RexxString * stringValue () override
bool isInstanceOf (RexxClass *) override
MethodClass * instanceMethod (RexxString *) override
SupplierClass * instanceMethods (RexxClass *) override
RexxObject * isInstanceOfRexx (RexxClass *)
RexxObject * isNilRexx ()
MethodClass * instanceMethodRexx (RexxString *)
SupplierClass * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, MethodClass *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
MessageClass * start (RexxObject **, size_t)
MessageClass * startWith (RexxObject *, ArrayClass *)
RexxObject * send (RexxObject **, size_t)
RexxObject * sendWith (RexxObject *, ArrayClass *)
MessageClass * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount)
RexxObject * run (RexxObject **, size_t)
void checkUninit ()
RexxObject * messageSend (RexxString *, RexxObject **, size_t, ProtectedObject &)
RexxObject * messageSend (RexxString *, RexxObject **, size_t, RexxClass *, ProtectedObject &)
MethodClass * checkPrivate (MethodClass *, RexxErrorCodes &)
MethodClass * checkPackage (MethodClass *, RexxErrorCodes &)
void checkRestrictedMethod (const char *methodName)
void processProtectedMethod (RexxString *, MethodClass *, RexxObject **, size_t, ProtectedObject &)
RexxObject * sendMessage (RexxString *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxClass *, ArrayClass *, ProtectedObject &)
RexxObject * sendMessage (RexxString *message, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, ProtectedObject &result)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void validateScopeOverride (RexxClass *scope)
RexxObject * defineInstanceMethods (DirectoryClass *)
void setObjectVariable (RexxString *, RexxObject *, RexxClass *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxClass *)
void addObjectVariables (VariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxClass * superScope (RexxClass *)
MethodClass * superMethod (RexxString *, RexxClass *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
MethodClass * methodLookup (RexxString *name)
VariableDictionary * getObjectVariables (RexxClass *)
void guardOn (Activity *activity, RexxClass *scope)
void guardOff (Activity *activity, RexxClass *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
void * getCSelf ()
void * getCSelf (RexxClass *scope)
void * allocateObjectMemory (size_t size)
void freeObjectMemory (void *data)
void * reallocateObjectMemory (void *data, size_t newSize)
PointerTable * getMemoryTable ()
RexxObject * callOperatorMethod (size_t methodOffset, RexxObject *argument)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) VariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
RexxInternalObject * nextObject ()
RexxInternalObject * nextObject (size_t l)
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
bool checkVirtualFunctions ()
bool checkVirtualFunctions (void *c)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectType (size_t type)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
void setReadyForUninit ()
bool isReadyForUninit ()
bool hasUninit ()
void setHasUninit ()
void clearHasUninit ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool requiresProxyObject ()
void makeProxyObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
void dumpObject ()
bool isValid ()
virtual RexxObject * evaluate (RexxActivation *, ExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (VariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (VariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (RexxErrorCodes)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (CompoundVariableTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxInteger * integerValue (wholenumber_t)
virtual bool numberValue (wholenumber_t &result, wholenumber_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (size_t &result, wholenumber_t precision)
virtual bool unsignedNumberValue (size_t &result)
virtual bool doubleValue (double &result)
virtual NumberString * numberString ()
virtual bool isEqual (RexxInternalObject *)
virtual wholenumber_t compareTo (RexxInternalObject *)
bool equalValue (RexxInternalObject *other)
void requiresUninit ()
void removedUninit ()
RexxInternalObject * clone ()
RexxString * requiredString (size_t)
RexxString * requiredString (const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (size_t, wholenumber_t)
RexxInteger * requiredInteger (const char *, wholenumber_t)
wholenumber_t requiredNumber (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
wholenumber_t requiredNumber (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredPositive (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (size_t position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
size_t requiredNonNegative (const char *position, wholenumber_t precision=Numerics::ARGUMENT_DIGITS)
double requiredFloat (const char *position)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (wholenumber_t digits=Numerics::ARGUMENT_DIGITS)
bool requestNumber (wholenumber_t &, wholenumber_t)
bool requestUnsignedNumber (size_t &, wholenumber_t)
virtual ArrayClass * requestArray ()
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from HashCollection
static size_t calculateBucketSize (size_t capacity)
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, ProtectedObject &messageName, ProtectedObject &startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes
StringTable * methodTable
MethodClass * unknownMethod
Public Attributes inherited from HashCollection
HashContents * contents
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from HashCollection
static const size_t MinimumBucketSize = 17
static const size_t DefaultTableSize = 17
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Additional Inherited Members
Protected Member Functions inherited from HashCollection
virtual void add (RexxInternalObject *, RexxInternalObject *)
virtual void addFront (RexxInternalObject *, RexxInternalObject *)
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 49 of file DirectoryClass.hpp.
Constructor & Destructor Documentation
DirectoryClass() [1/3]
DirectoryClass::DirectoryClass (RESTORETYPE restoreType) inline
Definition at line 55 of file DirectoryClass.hpp.
Referenced by newRexx().
DirectoryClass() [2/3]
DirectoryClass::DirectoryClass (size_t capacity = HashCollection::DefaultTableSize) inline
Definition at line 56 of file DirectoryClass.hpp.
DirectoryClass() [3/3]
DirectoryClass::DirectoryClass (bool fromRexx) inline
Definition at line 57 of file DirectoryClass.hpp.
Member Function Documentation
allIndexes()
ArrayClass * DirectoryClass::allIndexes () override virtual
Create an array of all of the directory indices, including those of all the SETMETHOD methods.
Returns
An array containing all of the directory indices.
Reimplemented from HashCollection.
Definition at line 230 of file DirectoryClass.cpp.
References HashCollection::allIndexes(), HashContents::allIndexes(), HashCollection::contents, methodTable, and OREF_NULL.
allItems()
ArrayClass * DirectoryClass::allItems () override virtual
Create an array of all of the directory values, including the values of all the SETMETHOD methods
Returns
An array of all item values.
Reimplemented from HashCollection.
Definition at line 250 of file DirectoryClass.cpp.
References HashContents::allItems(), HashCollection::contents, ActivityManager::currentActivity, HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), HashCollection::iterator(), methodTable, HashContents::TableIterator::next(), OREF_NULL, MethodClass::run(), and HashContents::TableIterator::value().
copy()
RexxInternalObject * DirectoryClass::copy () override virtual
Copy a directory item.
Returns
A copy of the item.
Reimplemented from HashCollection.
Definition at line 153 of file DirectoryClass.cpp.
References HashCollection::copy(), methodTable, and OREF_NULL.
Referenced by BUILTIN().
createInstance()
void DirectoryClass::createInstance () static
Create initial class object at bootstrap time.
Definition at line 60 of file DirectoryClass.cpp.
References CLASS_CREATE.
Referenced by MemoryObject::createImage().
empty()
void DirectoryClass::empty () override virtual
Empty a hash table collection.
Reimplemented from HashCollection.
Definition at line 372 of file DirectoryClass.cpp.
References HashCollection::contents, HashCollection::empty(), HashContents::empty(), methodTable, OREF_NULL, setField, and unknownMethod.
flatten()
void DirectoryClass::flatten (Envelope * envelope) override virtual
Flatten the table contents as part of a saved program.
Parameters
envelope The envelope we're flattening into.
Reimplemented from HashCollection.
Definition at line 112 of file DirectoryClass.cpp.
References cleanUpFlatten, HashCollection::contents, flattenRef, methodTable, setUpFlatten, and unknownMethod.
get()
RexxInternalObject * DirectoryClass::get (RexxInternalObject * index) override virtual
Retrieve an item from a directory.
Parameters
_index The target index.
Returns
The result value, if available.
Reimplemented from HashCollection.
Definition at line 332 of file DirectoryClass.cpp.
References HashCollection::contents, HashContents::get(), methodTableValue(), OREF_NULL, and unknownValue().
Referenced by BUILTIN(), SecurityManager::checkCommand(), NativeActivation::checkConditions(), SecurityManager::checkEnvironmentAccess(), SecurityManager::checkFunctionCall(), SecurityManager::checkLocalAccess(), SecurityManager::checkProtectedMethod(), SecurityManager::checkRequiresAccess(), SecurityManager::checkStreamAccess(), RexxActivation::command(), Interpreter::decodeConditionData(), Activity::display(), Activity::displayCondition(), Activity::displayDebug(), Activity::errorNumber(), RexxInstructionRaise::execute(), InterpreterInstance::getLocalEnvironment(), ContextCommandHandlerDispatcher::handleError(), RedirectionDispatcher::handleError(), RexxActivation::processTraps(), RexxActivation::raise(), Activity::raiseCondition(), Activity::raisePropagate(), remove(), Activity::reraiseException(), and NativeActivation::setConditionInfo().
getIndex()
RexxInternalObject * DirectoryClass::getIndex (RexxInternalObject * target) override virtual
Retrieve an index for a given item. Which index is returned is indeterminate.
Parameters
target The target object.
Returns
The index for the target object NULL
Reimplemented from HashCollection.
Definition at line 393 of file DirectoryClass.cpp.
References HashCollection::contents, ActivityManager::currentActivity, RexxInternalObject::equalValue(), HashContents::getIndex(), HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), HashCollection::iterator(), methodTable, HashContents::TableIterator::next(), OREF_NULL, MethodClass::run(), and HashContents::TableIterator::value().
Referenced by hasItem(), and removeItem().
hasIndex()
bool DirectoryClass::hasIndex (RexxInternalObject * indexName) override virtual
Determine if the directory has an entry with this name (used without uppercasing). This is an override of the base virtual method.
Parameters
indexName The index name.
Returns
true if the index exists, false otherwise.
Reimplemented from HashCollection.
Definition at line 284 of file DirectoryClass.cpp.
References HashCollection::contents, HashCollection::hasIndex(), HashContents::hasIndex(), methodTable, and OREF_NULL.
hasItem()
bool DirectoryClass::hasItem (RexxInternalObject * target) override virtual
Test if a given item exists in the collection.
Parameters
target The target object.
Returns
.true if the object exists, .false otherwise.
Reimplemented from HashCollection.
Definition at line 435 of file DirectoryClass.cpp.
References getIndex(), and OREF_NULL.
items()
size_t DirectoryClass::items () override virtual
Return the count of items in the directory, including the number of methods added via set method calls
Returns
the count of items.
Reimplemented from HashCollection.
Definition at line 172 of file DirectoryClass.cpp.
References HashCollection::contents, HashCollection::items(), HashContents::items(), methodTable, and OREF_NULL.
live()
void DirectoryClass::live (size_t liveMark) override virtual
Normal garbage collection live marking
Parameters
liveMark The current live mark.
Reimplemented from HashCollection.
Definition at line 84 of file DirectoryClass.cpp.
References HashCollection::contents, memory_mark, methodTable, and unknownMethod.
liveGeneral()
void DirectoryClass::liveGeneral (MarkReason reason) override virtual
Generalized object marking.
Parameters
reason The reason for this live marking operation.
Reimplemented from HashCollection.
Definition at line 98 of file DirectoryClass.cpp.
References HashCollection::contents, memory_mark_general, methodTable, and unknownMethod.
makeProxy()
RexxObject * DirectoryClass::makeProxy (Envelope * envelope) override virtual
Make a proxy object for one of the special directories (e.g., the environment directory)
Parameters
envelope The envelope we're flattening into.
Returns
A string proxy name for this object.
Reimplemented from RexxInternalObject.
Definition at line 133 of file DirectoryClass.cpp.
References Interpreter::logicError(), new_proxy(), OREF_NULL, and TheEnvironment.
methodTableValue()
RexxInternalObject * DirectoryClass::methodTableValue (RexxInternalObject * index)
Retrieve a value from the method table, if there is one.
Parameters
index The target index.
Returns
The method table method result, or OREF_NULL if none.
Definition at line 566 of file DirectoryClass.cpp.
References ActivityManager::currentActivity, HashCollection::get(), methodTable, OREF_NULL, and MethodClass::run().
Referenced by get().
newRexx()
RexxObject * DirectoryClass::newRexx (RexxObject ** init_args, size_t argCount)
Create a directory object from Rexx code.
Parameters
init_args The arguments to the NEW method.
argCount The argument count.
Returns
A new directory object.
Definition at line 612 of file DirectoryClass.cpp.
References RexxClass::completeNewObject(), and DirectoryClass().
Referenced by MemoryObject::createImage().
operator delete()
void DirectoryClass::operator delete (void *) inline
Definition at line 53 of file DirectoryClass.hpp.
operator new()
void * DirectoryClass::operator new (size_t size)
Create a new directory object.
Parameters
size the size of the object.
Returns
Storage for creating a the object.
Definition at line 73 of file DirectoryClass.cpp.
References new_object(), and T_Directory.
put()
void DirectoryClass::put (RexxInternalObject * value, RexxInternalObject * index) override virtual
Override of the PUT method.
Parameters
value The value to put
index The index of the target value
Reimplemented from HashCollection.
Definition at line 356 of file DirectoryClass.cpp.
References methodTable, OREF_NULL, HashCollection::put(), and HashCollection::remove().
Referenced by SecurityManager::checkCommand(), SecurityManager::checkEnvironmentAccess(), SecurityManager::checkFunctionCall(), SecurityManager::checkLocalAccess(), SecurityManager::checkProtectedMethod(), SecurityManager::checkRequiresAccess(), SecurityManager::checkStreamAccess(), RexxActivation::command(), Activity::createConditionObject(), Activity::createExceptionObject(), Activity::generateProgramInformation(), RexxActivation::raise(), Activity::raiseException(), Activity::raisePropagate(), Activity::reraiseException(), StemClass::toDirectory(), and RexxActivation::trap().
remove()
RexxInternalObject * DirectoryClass::remove (RexxInternalObject * entryName) override virtual
Remove an object from a directory.
Parameters
entryname The directory index.
Returns
The removed object, if any.
Reimplemented from HashCollection.
Definition at line 308 of file DirectoryClass.cpp.
References HashCollection::contents, get(), methodTable, OREF_NULL, HashContents::remove(), and HashCollection::remove().
Referenced by removeItem(), and Activity::reraiseException().
removeItem()
RexxInternalObject * DirectoryClass::removeItem (RexxInternalObject * target) override virtual
Remove a given item from the collection.
Parameters
target The target object.
Returns
.true if the object exists, .false otherwise.
Reimplemented from HashCollection.
Definition at line 450 of file DirectoryClass.cpp.
References getIndex(), OREF_NULL, and remove().
setMethodRexx()
RexxInternalObject * DirectoryClass::setMethodRexx (RexxString * name, MethodClass * methodobj)
Set a method of executable code into a directory object.
Parameters
entryname The name this is set under
methodobj The associated method object.
Returns
Nothing.
Definition at line 480 of file DirectoryClass.cpp.
References clearField, HashCollection::contents, methodTable, new_string_table(), MethodClass::newMethodObject(), OREF_NULL, HashCollection::put(), HashContents::remove(), HashCollection::remove(), setField, stringArgument(), TheNilObject, unknownMethod, and RexxString::upper().
Referenced by MemoryObject::createImage().
supplier()
SupplierClass * DirectoryClass::supplier () override virtual
Create a supplier for a directory, including the results of all of the SETMETHOD methods as values
Returns
An appropriate supplier object.
Reimplemented from HashCollection.
Definition at line 191 of file DirectoryClass.cpp.
References SupplierClass::append(), HashCollection::contents, ActivityManager::currentActivity, HashContents::TableIterator::index(), HashContents::TableIterator::isAvailable(), HashCollection::items(), HashCollection::iterator(), methodTable, new_array(), HashContents::TableIterator::next(), OREF_NULL, MethodClass::run(), HashContents::supplier(), and HashContents::TableIterator::value().
unknownValue()
RexxInternalObject * DirectoryClass::unknownValue (RexxInternalObject * index)
Retrieve a value via a set UNKNOWN method, if there is one.
Parameters
index The index value.
Returns
The value returned from an unknown method, if there is one.
Definition at line 591 of file DirectoryClass.cpp.
References ActivityManager::currentActivity, OREF_NULL, MethodClass::run(), and unknownMethod.
Referenced by get().
unsetMethodRexx()
RexxInternalObject * DirectoryClass::unsetMethodRexx (RexxString * entryname)
unset a method of executable code into a directory object.
Parameters
entryname The name this is set under
Returns
Nothing.
Definition at line 536 of file DirectoryClass.cpp.
References clearField, methodTable, OREF_NULL, HashCollection::remove(), RexxString::strCompare(), stringArgument(), unknownMethod, and RexxString::upper().
Referenced by MemoryObject::createImage().
Member Data Documentation
classInstance
RexxClass * DirectoryClass::classInstance = OREF_NULL static
Definition at line 96 of file DirectoryClass.hpp.
methodTable
StringTable* DirectoryClass::methodTable
Definition at line 91 of file DirectoryClass.hpp.
Referenced by allIndexes(), allItems(), copy(), empty(), flatten(), getIndex(), hasIndex(), items(), live(), liveGeneral(), methodTableValue(), put(), remove(), setMethodRexx(), supplier(), and unsetMethodRexx().
unknownMethod
MethodClass* DirectoryClass::unknownMethod
Definition at line 92 of file DirectoryClass.hpp.
Referenced by empty(), flatten(), live(), liveGeneral(), setMethodRexx(), unknownValue(), and unsetMethodRexx().
The documentation for this class was generated from the following files:
DirectoryClass.hpp
DirectoryClass.cpp