ooRexx: SysAPIManager Class Reference
SysAPIManager Class Reference
#include <SysAPIManager.hpp>
Static Public Member Functions
static void * allocateMemory (size_t length)
static void releaseMemory (void *p)
static void * allocateMemory (size_t length)
static void releaseMemory (void *p)
Detailed Description
Definition at line 44 of file unix/SysAPIManager.hpp.
Member Function Documentation
allocateMemory() [1/2]
void * SysAPIManager::allocateMemory (size_t l) static
Allocate API memory on behalf of the allocate memory call.
Parameters
l The length of the required memory.
Returns
The pointer to the memory. Returns NULL for out of memory conditions.
Definition at line 49 of file unix/SysAPIManager.cpp.
Referenced by ManagedRxstring::allocateResult(), ServiceMessage::allocateResultMemory(), and RexxAllocateMemory().
allocateMemory() [2/2]
static void* SysAPIManager::allocateMemory (size_t length) static
releaseMemory() [1/2]
void SysAPIManager::releaseMemory (void * p) static
Free API memory.
Parameters
p Pointer to the memory location.
Definition at line 59 of file unix/SysAPIManager.cpp.
Referenced by ManagedRxstring::ensureCapacity(), ServiceMessage::releaseResultMemory(), RexxFreeMemory(), and ManagedRxstring::~ManagedRxstring().
releaseMemory() [2/2]
static void SysAPIManager::releaseMemory (void * p) static
The documentation for this class was generated from the following files:
unix/SysAPIManager.hpp
windows/SysAPIManager.hpp
unix/SysAPIManager.cpp
windows/SysAPIManager.cpp