ooRexx: RexxActivationFrame Class Reference
RexxActivationFrame Class Reference
#include <ActivationFrame.hpp>
Public Member Functions
RexxActivationFrame (Activity *a, RexxActivation *context)
RexxString * messageName () override
BaseExecutable * executable () override
StackFrameClass * createStackFrame () override
PackageClass * getPackage () override
RexxObject * getContextObject ()
Public Member Functions inherited from ActivationFrame
ActivationFrame (Activity *a)
void disableFrame ()
~ActivationFrame ()
Protected Attributes
RexxActivation * activation
Protected Attributes inherited from ActivationFrame
ActivationFrame * next
Activity * activity
Detailed Description
A stack frame representing running Rexx code.
Definition at line 102 of file ActivationFrame.hpp.
Constructor & Destructor Documentation
RexxActivationFrame()
RexxActivationFrame::RexxActivationFrame (Activity * a, RexxActivation * context) inline
Definition at line 105 of file ActivationFrame.hpp.
Member Function Documentation
createStackFrame()
StackFrameClass * RexxActivationFrame::createStackFrame () override virtual
Implements ActivationFrame.
Definition at line 55 of file ActivationFrame.cpp.
References activation, and RexxActivation::createStackFrame().
executable()
BaseExecutable * RexxActivationFrame::executable () override virtual
Implements ActivationFrame.
Definition at line 50 of file ActivationFrame.cpp.
References activation, and ActivationBase::getExecutableObject().
getContextObject()
RexxObject * RexxActivationFrame::getContextObject ()
Definition at line 65 of file ActivationFrame.cpp.
References activation, and RexxActivation::getContextObject().
getPackage()
PackageClass * RexxActivationFrame::getPackage () override virtual
Implements ActivationFrame.
Definition at line 60 of file ActivationFrame.cpp.
References activation, and RexxActivation::getEffectivePackageObject().
messageName()
RexxString * RexxActivationFrame::messageName () override virtual
Implements ActivationFrame.
Definition at line 45 of file ActivationFrame.cpp.
References activation, and RexxActivation::getMessageName().
Member Data Documentation
activation
RexxActivation* RexxActivationFrame::activation protected
Definition at line 115 of file ActivationFrame.hpp.
Referenced by createStackFrame(), executable(), getContextObject(), getPackage(), and messageName().
The documentation for this class was generated from the following files:
ActivationFrame.hpp
ActivationFrame.cpp