ooRexx: ProtectedObject Class Reference
ProtectedObject Class Reference
#include <ProtectedObject.hpp>
Public Member Functions
ProtectedObject ()
ProtectedObject (Activity *a)
ProtectedObject (RexxInternalObject *o)
ProtectedObject (RexxInternalObject *o, Activity *a)
~ProtectedObject ()
void mark (size_t liveMark) override
void markGeneral (int reason) override
ProtectedBase & operator= (RexxInternalObject *o)
bool operator== (RexxInternalObject *o)
bool operator!= (RexxInternalObject *o)
operator RexxObject * ()
operator RexxInternalObject * ()
operator RexxObjectPtr ()
operator RexxString * ()
operator MethodClass * ()
operator ArrayClass * ()
operator RexxClass * ()
operator RexxInstruction * ()
operator void * ()
bool isNull ()
RexxObject * operator-> ()
Public Member Functions inherited from ProtectedBase
ProtectedBase ()
ProtectedBase (Activity *a)
~ProtectedBase ()
Protected Attributes
RexxInternalObject * protectedObject
Protected Attributes inherited from ProtectedBase
ProtectedBase * next
Activity * activity
Detailed Description
Normal untyped ProtectedObject class. This protects an object reference from garbage collection.
Definition at line 70 of file ProtectedObject.hpp.
Constructor & Destructor Documentation
ProtectedObject() [1/4]
ProtectedObject::ProtectedObject () inline
Definition at line 73 of file ProtectedObject.hpp.
ProtectedObject() [2/4]
ProtectedObject::ProtectedObject (Activity * a) inline
Definition at line 74 of file ProtectedObject.hpp.
ProtectedObject() [3/4]
ProtectedObject::ProtectedObject (RexxInternalObject * o) inline
Definition at line 75 of file ProtectedObject.hpp.
ProtectedObject() [4/4]
ProtectedObject::ProtectedObject (RexxInternalObject * o, Activity * a) inline
Definition at line 76 of file ProtectedObject.hpp.
~ProtectedObject()
ProtectedObject::~ProtectedObject () inline
Definition at line 77 of file ProtectedObject.hpp.
Member Function Documentation
isNull()
bool ProtectedObject::isNull () inline
Definition at line 146 of file ProtectedObject.hpp.
References OREF_NULL, and protectedObject.
Referenced by SecurityManager::checkCommand(), ArrayClass::WithSortComparator::compare(), RexxInternalObject::compareTo(), RexxExpressionFunction::evaluate(), RexxExpressionMessage::evaluate(), QualifiedFunction::evaluate(), RexxInstructionCall::execute(), RexxInstructionDynamicCall::execute(), RexxInstructionQualifiedCall::execute(), RexxInstructionForward::execute(), RexxInstructionMessage::execute(), RexxObject::hash(), LanguageParser::parseNew(), and RexxStartDispatcher::run().
mark()
void ProtectedObject::mark (size_t liveMark) inline override virtual
Implements ProtectedBase.
Definition at line 79 of file ProtectedObject.hpp.
References memory_mark, and protectedObject.
markGeneral()
void ProtectedObject::markGeneral (int reason) inline override virtual
Implements ProtectedBase.
Definition at line 80 of file ProtectedObject.hpp.
References memory_mark_general, and protectedObject.
operator ArrayClass *()
ProtectedObject::operator ArrayClass * () inline
Definition at line 125 of file ProtectedObject.hpp.
References protectedObject.
operator MethodClass *()
ProtectedObject::operator MethodClass * () inline
Definition at line 120 of file ProtectedObject.hpp.
References protectedObject.
operator RexxClass *()
ProtectedObject::operator RexxClass * () inline
Definition at line 130 of file ProtectedObject.hpp.
References protectedObject.
operator RexxInstruction *()
ProtectedObject::operator RexxInstruction * () inline
Definition at line 136 of file ProtectedObject.hpp.
References protectedObject.
operator RexxInternalObject *()
ProtectedObject::operator RexxInternalObject * () inline
Definition at line 105 of file ProtectedObject.hpp.
References protectedObject.
operator RexxObject *()
ProtectedObject::operator RexxObject * () inline
Definition at line 99 of file ProtectedObject.hpp.
References protectedObject.
operator RexxObjectPtr()
ProtectedObject::operator RexxObjectPtr () inline
Definition at line 110 of file ProtectedObject.hpp.
References protectedObject.
operator RexxString *()
ProtectedObject::operator RexxString * () inline
Definition at line 115 of file ProtectedObject.hpp.
References protectedObject.
operator void *()
ProtectedObject::operator void * () inline
Definition at line 141 of file ProtectedObject.hpp.
References protectedObject.
operator!=()
bool ProtectedObject::operator!= (RexxInternalObject * o) inline
Definition at line 93 of file ProtectedObject.hpp.
References protectedObject.
operator->()
RexxObject* ProtectedObject::operator-> () inline
Definition at line 152 of file ProtectedObject.hpp.
References protectedObject.
operator=()
ProtectedBase& ProtectedObject::operator= (RexxInternalObject * o) inline
Definition at line 82 of file ProtectedObject.hpp.
References protectedObject.
operator==()
bool ProtectedObject::operator== (RexxInternalObject * o) inline
Definition at line 88 of file ProtectedObject.hpp.
References protectedObject.
Member Data Documentation
protectedObject
RexxInternalObject* ProtectedObject::protectedObject protected
Definition at line 158 of file ProtectedObject.hpp.
Referenced by ProtectedSet::add(), isNull(), mark(), markGeneral(), operator ArrayClass *(), operator MethodClass *(), operator RexxClass *(), operator RexxInstruction *(), operator RexxInternalObject *(), operator RexxObject *(), operator RexxObjectPtr(), operator RexxString *(), operator void *(), operator!=(), operator->(), operator=(), and operator==().
The documentation for this class was generated from the following file:
ProtectedObject.hpp