ooRexx: LineReader Class Reference
LineReader Class Reference
Public Member Functions
LineReader ()
~LineReader ()
bool open (const char *fileName)
bool getLine (const char *&line, size_t &size)
void close ()
Protected Attributes
const size_t InitialBufferSize = 0x01000
const size_t BufferExpansionSize = 0x01000
AutoFree buffer
size_t bufferSize
SysFile file
Detailed Description
A simple class for reading lines from a file.
Definition at line 69 of file RexxUtilCommon.cpp.
Constructor & Destructor Documentation
LineReader()
LineReader::LineReader () inline
Definition at line 72 of file RexxUtilCommon.cpp.
~LineReader()
LineReader::~LineReader () inline
Definition at line 74 of file RexxUtilCommon.cpp.
References close().
Member Function Documentation
close()
void LineReader::close () inline
Close the read operation.
Definition at line 146 of file RexxUtilCommon.cpp.
References SysFile::close(), and file.
Referenced by RexxRoutine4(), and ~LineReader().
getLine()
bool LineReader::getLine (const char *& line, size_t & size) inline
Read an entire line into buffer, expanding buffer as necessary.
Returns
true if a line could be read, false otherwise.
Definition at line 105 of file RexxUtilCommon.cpp.
References buffer, BufferExpansionSize, bufferSize, file, SysFile::gets(), line, and AutoFree::realloc().
Referenced by RexxRoutine4().
open()
bool LineReader::open (const char * fileName) inline
Open the file and set up for reading
Parameters
fileName The name of the file
Returns
true if we were able to open the file, false for any failures.
Definition at line 86 of file RexxUtilCommon.cpp.
References buffer, bufferSize, file, InitialBufferSize, SysFileSystem::isDirectory(), SysFile::open(), RX_O_RDONLY, RX_S_IREAD, and RX_SH_DENYWR.
Referenced by RexxRoutine4().
Member Data Documentation
buffer
AutoFree LineReader::buffer protected
Definition at line 158 of file RexxUtilCommon.cpp.
Referenced by getLine(), and open().
BufferExpansionSize
const size_t LineReader::BufferExpansionSize = 0x01000 protected
Definition at line 156 of file RexxUtilCommon.cpp.
Referenced by getLine().
bufferSize
size_t LineReader::bufferSize protected
Definition at line 159 of file RexxUtilCommon.cpp.
Referenced by getLine(), and open().
file
SysFile LineReader::file protected
Definition at line 160 of file RexxUtilCommon.cpp.
Referenced by close(), getLine(), and open().
InitialBufferSize
const size_t LineReader::InitialBufferSize = 0x01000 protected
Definition at line 154 of file RexxUtilCommon.cpp.
Referenced by open().
The documentation for this class was generated from the following file:
RexxUtilCommon.cpp