ooRexx: LiveStack Class Reference
LiveStack Class Reference
#include <MemoryStack.hpp>
Public Member Functions
void * operator new (size_t, size_t)
void operator delete (void *)
LiveStack (size_t size)
RexxInternalObject * get (size_t pos)
void push (RexxInternalObject *obj)
RexxInternalObject * pop ()
LiveStack * reallocate (size_t increment)
LiveStack * ensureSpace (size_t needed)
bool checkRoom ()
bool checkRoom (size_t needed)
size_t stackSize ()
RexxInternalObject * stackTop ()
void copyEntries (LiveStack *other)
void clear ()
Protected Attributes
size_t size
size_t top
RexxInternalObject * stack [1]
Detailed Description
A simple and fast stack object for doing memory management live marking. This has minimal overrun protections, so the using code needs to perform appropriate "stack is full" checks.
Definition at line 55 of file MemoryStack.hpp.
Constructor & Destructor Documentation
LiveStack()
LiveStack::LiveStack (size_t _size)
Allocate a live stack with the given number of slots.
Parameters
_size The stack size.
Definition at line 84 of file MemoryStack.cpp.
References size, and top.
Member Function Documentation
checkRoom() [1/2]
bool LiveStack::checkRoom () inline
Definition at line 115 of file MemoryStack.hpp.
References size, and top.
Referenced by MemoryObject::checkLiveStack().
checkRoom() [2/2]
bool LiveStack::checkRoom (size_t needed) inline
Definition at line 116 of file MemoryStack.hpp.
References size, and top.
clear()
void LiveStack::clear () inline
Definition at line 120 of file MemoryStack.hpp.
References size, and stack.
copyEntries()
void LiveStack::copyEntries (LiveStack * other) inline
Definition at line 119 of file MemoryStack.hpp.
References size, stack, and top.
Referenced by reallocate().
ensureSpace()
LiveStack * LiveStack::ensureSpace (size_t needed)
Ensure that the live stack is going to be large enough to fit all of the objects that might be marked from a large collection. This allows us to proactively expand the stack before a GC event is taking place, and potentially raise a real Rexx EOM condition before we're at a critical point.
Parameters
needed The number of live stack slots this object might require. It is assumed that the stack needs to be expanded at this point.
Returns
A newly allocated stack with the entries from this stack copied over to it.
Definition at line 124 of file MemoryStack.cpp.
References Memory::LiveStackSize, reallocate(), Memory::roundUp(), and size.
Referenced by MemoryObject::liveStackFull().
get()
RexxInternalObject* LiveStack::get (size_t pos) inline
Definition at line 65 of file MemoryStack.hpp.
References OREF_NULL, stack, and top.
operator delete()
void LiveStack::operator delete (void * storage)
Delete a LiveStack object.
Parameters
storage The pointer to the object storage
Definition at line 73 of file MemoryStack.cpp.
References MemoryObject::deleteTemporaryObject(), and memoryObject.
operator new()
void * LiveStack::operator new (size_t size, size_t stksize)
Create a new stack for the memory object from temporary memory.
Parameters
size The base size of the object.
stksize The number of items we wish to have in the stack.
temporary A dummy argument just to get this new method invoked... causes the stack to be allocated from temporary memory.
Returns
A newly allocated stack object.
Definition at line 59 of file MemoryStack.cpp.
References memoryObject, and MemoryObject::temporaryObject().
pop()
RexxInternalObject* LiveStack::pop () inline
Pop an item off of the stack. Has some underrun protection, but that's it.
Returns
The popped object (or OREF_NULL if we're empty)
Definition at line 101 of file MemoryStack.hpp.
References OREF_NULL, stack, and top.
Referenced by Envelope::pack(), and MemoryObject::popLiveStack().
push()
void LiveStack::push (RexxInternalObject * obj) inline
Push an object on to the stack
Parameters
obj The object to push
Returns
Definition at line 86 of file MemoryStack.hpp.
References stack, and top.
Referenced by Envelope::flattenReference(), Envelope::pack(), and MemoryObject::pushLiveStack().
reallocate()
LiveStack * LiveStack::reallocate (size_t delta)
Reallocate the stack to one that is larger by a given multiplier.
Parameters
delta The size to expand by
Returns
A newly allocated stack with the entries from this stack copied over to it.
Definition at line 100 of file MemoryStack.cpp.
References copyEntries(), and size.
Referenced by ensureSpace(), and MemoryObject::liveStackFull().
stackSize()
size_t LiveStack::stackSize () inline
Definition at line 117 of file MemoryStack.hpp.
References size.
stackTop()
RexxInternalObject* LiveStack::stackTop () inline
Definition at line 118 of file MemoryStack.hpp.
References OREF_NULL, stack, and top.
Member Data Documentation
size
size_t LiveStack::size protected
Definition at line 124 of file MemoryStack.hpp.
Referenced by checkRoom(), clear(), copyEntries(), ensureSpace(), LiveStack(), reallocate(), and stackSize().
stack
RexxInternalObject* LiveStack::stack[1] protected
Definition at line 126 of file MemoryStack.hpp.
Referenced by clear(), copyEntries(), get(), pop(), push(), and stackTop().
top
size_t LiveStack::top protected
Definition at line 125 of file MemoryStack.hpp.
Referenced by checkRoom(), copyEntries(), get(), LiveStack(), pop(), push(), and stackTop().
The documentation for this class was generated from the following files:
MemoryStack.hpp
MemoryStack.cpp