ooRexx: ApiConnection Class Reference
ApiConnection Class Reference abstract
#include <CSStream.hpp>
Public Member Functions
ApiConnection ()
virtual ~ApiConnection ()
CSErrorCodeT getError ()
bool isClean ()
char * getMessageBuffer (size_t size)
void returnMessageBuffer (void *)
virtual bool read (void *buf, size_t bufsize, size_t *bytesread)=0
virtual bool write (void *buf, size_t bufsize, size_t *byteswritten)=0
virtual bool write (void *buf, size_t bufsize, void *buf2, size_t buf2size, size_t *byteswritten)=0
virtual bool disconnect ()
Protected Types
enum { MAX_CACHED_BUFFER = 4096 }
Protected Attributes
CSErrorCodeT errcode
char * messageBuffer
Detailed Description
Base class for a client server connection. This manages the interface, while platform-specific overrides manage the communication details.
Definition at line 60 of file CSStream.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
MAX_CACHED_BUFFER
Definition at line 85 of file CSStream.hpp.
Constructor & Destructor Documentation
ApiConnection()
ApiConnection::ApiConnection () inline
Definition at line 63 of file CSStream.hpp.
~ApiConnection()
virtual ApiConnection::~ApiConnection () inline virtual
Definition at line 64 of file CSStream.hpp.
References disconnect(), and messageBuffer.
Member Function Documentation
disconnect()
virtual bool ApiConnection::disconnect () inline virtual
Reimplemented in SysSocketConnection, SysNamedPipeConnection, and SysSocketConnection.
Definition at line 82 of file CSStream.hpp.
Referenced by APIServer::processMessages(), and ~ApiConnection().
getError()
CSErrorCodeT ApiConnection::getError () inline
Definition at line 66 of file CSStream.hpp.
References errcode.
getMessageBuffer()
char * ApiConnection::getMessageBuffer (size_t size)
Get a buffer for sending a buffered message.
Parameters
size The required size.
Returns
A pointer to a buffer, or NULL if unable to allocate.
Definition at line 52 of file CSStream.cpp.
References MAX_CACHED_BUFFER, MEMORY_ERROR, and messageBuffer.
Referenced by SysSocketConnection::write(), and SysNamedPipeConnection::write().
isClean()
bool ApiConnection::isClean () inline
Definition at line 70 of file CSStream.hpp.
References CSERROR_OK, and errcode.
Referenced by LocalAPIManager::returnConnection().
read()
virtual bool ApiConnection::read (void * buf, size_t bufsize, size_t * bytesread) pure virtual
Implemented in SysSocketConnection, SysNamedPipeConnection, and SysSocketConnection.
Referenced by ServiceMessage::readMessage(), and ServiceMessage::readResult().
returnMessageBuffer()
void ApiConnection::returnMessageBuffer (void * buffer)
Return a message buffer after sending a message. This will either cache the buffer, or release it, depending upon how it was obtained in the first place.
Parameters
buffer The buffer to release.
Definition at line 84 of file CSStream.cpp.
References messageBuffer.
Referenced by SysSocketConnection::write(), and SysNamedPipeConnection::write().
write() [1/2]
virtual bool ApiConnection::write (void * buf, size_t bufsize, size_t * byteswritten) pure virtual
Implemented in SysSocketConnection, SysNamedPipeConnection, and SysSocketConnection.
Referenced by ServiceMessage::writeMessage(), and ServiceMessage::writeResult().
write() [2/2]
virtual bool ApiConnection::write (void * buf, size_t bufsize, void * buf2, size_t buf2size, size_t * byteswritten) pure virtual
Implemented in SysSocketConnection, SysNamedPipeConnection, and SysSocketConnection.
Member Data Documentation
errcode
CSErrorCodeT ApiConnection::errcode protected
Definition at line 91 of file CSStream.hpp.
Referenced by SysInetSocketConnection::connect(), SysNamedPipeConnection::connect(), SysLocalSocketConnection::connect(), SysSocketConnection::disconnect(), SysNamedPipeConnection::disconnect(), getError(), isClean(), SysSocketConnection::read(), SysNamedPipeConnection::read(), SysSocketConnection::write(), and SysNamedPipeConnection::write().
messageBuffer
char* ApiConnection::messageBuffer protected
Definition at line 92 of file CSStream.hpp.
Referenced by getMessageBuffer(), returnMessageBuffer(), and ~ApiConnection().
The documentation for this class was generated from the following files:
CSStream.hpp
CSStream.cpp