ooRexx: hostemu.h File Reference
hostemu.h File Reference
Classes
struct _EXECIO_OPTIONS
Macros
#define ERR_EXECIO_EOF 2
#define ERR_EXECIO_BAD_PLIST 24
#define ERR_EXECIO_NO_STORAGE 41
#define ERR_EXECIO_VAR_INVALID 2008
#define SYMTABLESIZE 15
#define EXECIO_STMT 0
#define HI_STMT 1
#define TE_STMT 2
#define TS_STMT 3
Typedefs
typedef struct _EXECIO_OPTIONS EXECIO_OPTIONS
Functions
int yyparse (void)
RexxReturnCode RexxEntry GrxHost (PCONSTRXSTRING command, unsigned short int *flags, PRXSTRING retc)
Variables
const char * szVersion
const char * szDate
EXECIO_OPTIONS ExecIO_Options
PCONSTRXSTRING prxCmd
long lCmdPtr
unsigned long ulNumSym
char * pszSymbol [SYMTABLESIZE]
long lStmtType
Macro Definition Documentation
ERR_EXECIO_BAD_PLIST
#define ERR_EXECIO_BAD_PLIST 24
Definition at line 87 of file hostemu.h.
ERR_EXECIO_EOF
#define ERR_EXECIO_EOF 2
Definition at line 86 of file hostemu.h.
ERR_EXECIO_NO_STORAGE
#define ERR_EXECIO_NO_STORAGE 41
Definition at line 88 of file hostemu.h.
ERR_EXECIO_VAR_INVALID
#define ERR_EXECIO_VAR_INVALID 2008
Definition at line 89 of file hostemu.h.
EXECIO_STMT
#define EXECIO_STMT 0
Definition at line 92 of file hostemu.h.
HI_STMT
#define HI_STMT 1
Definition at line 93 of file hostemu.h.
SYMTABLESIZE
#define SYMTABLESIZE 15
Definition at line 91 of file hostemu.h.
TE_STMT
#define TE_STMT 2
Definition at line 94 of file hostemu.h.
TS_STMT
#define TS_STMT 3
Definition at line 95 of file hostemu.h.
Typedef Documentation
EXECIO_OPTIONS
typedef struct _EXECIO_OPTIONS EXECIO_OPTIONS
Function Documentation
GrxHost()
RexxReturnCode RexxEntry GrxHost (PCONSTRXSTRING command, unsigned short int * flags, PRXSTRING retc)
Definition at line 251 of file unix/hostemu.cpp.
References _EXECIO_OPTIONS::aFilename, _EXECIO_OPTIONS::aStem, Delete_LL(), ERR_EXECIO_BAD_PLIST, ERR_EXECIO_NO_STORAGE, ExecIO_Options, ExecIO_Read_To_Queue(), ExecIO_Read_To_Stem(), EXECIO_STMT, ExecIO_Write_From_Queue(), ExecIO_Write_From_Stem(), _EXECIO_OPTIONS::fFinis, _LL::FileName, _EXECIO_OPTIONS::fRW, HI_STMT, hmtxExecIO, htmxExecIO, Insert_LL(), lCmdPtr, _EXECIO_OPTIONS::lDirection, _EXECIO_OPTIONS::lStartRcd, lStmtType, _LL::pFile, prxCmd, pszSymbol, RexxResetTrace(), RexxSetHalt(), RexxSetTrace(), RXSUBCOM_ERROR, RXSUBCOM_FAILURE, RXSUBCOM_OK, Search_LL(), _RXSTRING::strlength, _RXSTRING::strptr, TE_STMT, TS_STMT, ulNumSym, and yyparse().
Referenced by hostemu_loader().
yyparse()
int yyparse (void)
Definition at line 1203 of file cmdparse.cpp.
References _EXECIO_OPTIONS::aFilename, _EXECIO_OPTIONS::aStem, ExecIO_Options, EXECIO_STMT, _EXECIO_OPTIONS::fFinis, _EXECIO_OPTIONS::fRW, HI_STMT, isnumeric(), _EXECIO_OPTIONS::lDirection, _EXECIO_OPTIONS::lRcdCnt, _EXECIO_OPTIONS::lStartRcd, lStmtType, YYSTYPE::strval, TE_STMT, TS_STMT, YY_, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror(), YYFINAL, YYID, YYINITDEPTH, YYLAST, YYLEX, yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, yypact, YYPACT_NINF, yypgoto, YYPOPSTACK, yyr1, yyr2, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_ALLOC_MAXIMUM, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yystos, yytable, YYTABLE_NINF, YYTERROR, YYTRANSLATE, and yyalloc::yyvs_alloc.
Referenced by GrxHost().
Variable Documentation
ExecIO_Options
EXECIO_OPTIONS ExecIO_Options extern
Definition at line 58 of file unix/hostemu.cpp.
Referenced by ExecIO_Read_To_Queue(), ExecIO_Read_To_Stem(), ExecIO_Write_From_Queue(), ExecIO_Write_From_Stem(), GrxHost(), and yyparse().
lCmdPtr
long lCmdPtr extern
Definition at line 59 of file unix/hostemu.cpp.
Referenced by GrxHost(), and yylex().
lStmtType
long lStmtType extern
Definition at line 63 of file unix/hostemu.cpp.
Referenced by GrxHost(), and yyparse().
prxCmd
PCONSTRXSTRING prxCmd extern
Definition at line 57 of file unix/hostemu.cpp.
Referenced by GrxHost(), and yylex().
pszSymbol
char* pszSymbol[SYMTABLESIZE] extern
Definition at line 61 of file unix/hostemu.cpp.
Referenced by GrxHost(), and yylex().
szDate
const char* szDate extern
szVersion
const char* szVersion extern
ulNumSym
unsigned long ulNumSym extern
Definition at line 60 of file unix/hostemu.cpp.
Referenced by GrxHost(), and yylex().