ooRexx: orxclassicexits.cpp File Reference
orxclassicexits.cpp File Reference
#include "rexx.h"
#include "orxexits.hpp"
#include <string.h>
Functions
InstanceInfo * getApplicationData ()
void setContextVariable (const char *name, const char *value)
void getContextVariable (const char *name, RXSTRING *value)
void dropContextVariable (const char *name)
int RexxEntry TestFunctionExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestCommandExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestQueueExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestSessionIOExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestHaltExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestTraceExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestInitExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestTerminationExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestScriptFunctionExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestObjectFunctionExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestNovalueExit (int code, int subcode, PEXIT exitInfo)
int RexxEntry TestValueExit (int code, int subcode, PEXIT exitInfo)
RexxReturnCode RexxEntry TestSubcomHandler (CONSTRXSTRING *cmd, unsigned short *flags, PRXSTRING retstr)
void REXXENTRY deregisterSubcomHandler ()
void REXXENTRY registerSubcomHandler (void *data)
void REXXENTRY deregisterExits ()
void REXXENTRY registerExeExits (void *data)
void REXXENTRY registerDllExits (void *data)
bool REXXENTRY buildRegisteredExitList (InstanceInfo *instanceInfo, RXSYSEXIT *exitList)
void REXXENTRY invokeRexxStart (InstanceInfo *instanceInfo)
Function Documentation
buildRegisteredExitList()
bool REXXENTRY buildRegisteredExitList (InstanceInfo * instanceInfo, RXSYSEXIT * exitList)
Definition at line 675 of file orxclassicexits.cpp.
References InstanceInfo::cmd, counter(), InstanceInfo::exf, InstanceInfo::fnc, InstanceInfo::hlt, InstanceInfo::ini, InstanceInfo::ExitConfig::isEnabled(), InstanceInfo::msq, InstanceInfo::ofnc, RXCMD, RXEXF, RXFNC, RXHLT, RXINI, RXMSQ, RXNOVAL, RXOFNC, RXSIO, RXTER, RXTRC, RXVALUE, InstanceInfo::sio, _RXSYSEXIT::sysexit_code, _RXSYSEXIT::sysexit_name, InstanceInfo::ter, InstanceInfo::trc, InstanceInfo::val, and InstanceInfo::var.
Referenced by createInstance(), and invokeRexxStart().
deregisterExits()
void REXXENTRY deregisterExits ()
Definition at line 616 of file orxclassicexits.cpp.
References RexxDeregisterExit().
Referenced by invokeProgram(), invokeRexxStart(), registerDllExits(), and registerExeExits().
deregisterSubcomHandler()
void REXXENTRY deregisterSubcomHandler ()
Definition at line 600 of file orxclassicexits.cpp.
References RexxDeregisterSubcom().
Referenced by invokeProgram(), invokeRexxStart(), and registerSubcomHandler().
dropContextVariable()
void dropContextVariable (const char * name)
Definition at line 88 of file orxclassicexits.cpp.
References RexxVariablePool(), RXSHV_DROPV, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnamelen, _SHVBLOCK::shvnext, and _SHVBLOCK::shvret.
Referenced by TestFunctionExit().
getApplicationData()
InstanceInfo* getApplicationData ()
Definition at line 42 of file orxclassicexits.cpp.
References RexxQueryExit().
Referenced by TestCommandExit(), TestFunctionExit(), TestHaltExit(), TestInitExit(), TestNovalueExit(), TestObjectFunctionExit(), TestQueueExit(), TestScriptFunctionExit(), TestSessionIOExit(), TestTerminationExit(), TestTraceExit(), and TestValueExit().
getContextVariable()
void getContextVariable (const char * name, RXSTRING * value)
Definition at line 70 of file orxclassicexits.cpp.
References RexxVariablePool(), RXSHV_FETCH, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnamelen, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _SHVBLOCK::shvvaluelen, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by TestFunctionExit(), TestSubcomHandler(), and TestTerminationExit().
invokeRexxStart()
void REXXENTRY invokeRexxStart (InstanceInfo * instanceInfo)
Definition at line 773 of file orxclassicexits.cpp.
References InstanceInfo::argCount, InstanceInfo::arguments, buildRegisteredExitList(), InstanceInfo::code, deregisterExits(), deregisterSubcomHandler(), InstanceInfo::exitStyle, InstanceInfo::initialAddress, MAKERXSTRING, InstanceInfo::programName, InstanceInfo::rc, registerDllExits(), InstanceInfo::REGISTERED_DLL, registerSubcomHandler(), InstanceInfo::returnResult, RexxFreeMemory(), RexxStart(), RXCOMMAND, RXNOOFEXITS, and _RXSTRING::strptr.
Referenced by main(), and RexxMethod3().
registerDllExits()
void REXXENTRY registerDllExits (void * data)
Definition at line 653 of file orxclassicexits.cpp.
References deregisterExits(), RexxRegisterExitDll(), and RXEXIT_DROPPABLE.
Referenced by createInstance(), and invokeRexxStart().
registerExeExits()
void REXXENTRY registerExeExits (void * data)
Definition at line 632 of file orxclassicexits.cpp.
References deregisterExits(), RexxRegisterExitExe(), TestCommandExit(), TestFunctionExit(), TestHaltExit(), TestInitExit(), TestNovalueExit(), TestObjectFunctionExit(), TestQueueExit(), TestScriptFunctionExit(), TestSessionIOExit(), TestTerminationExit(), TestTraceExit(), and TestValueExit().
Referenced by createInstance().
registerSubcomHandler()
void REXXENTRY registerSubcomHandler (void * data)
Definition at line 606 of file orxclassicexits.cpp.
References deregisterSubcomHandler(), RexxRegisterSubcomExe(), and TestSubcomHandler().
Referenced by createInstance(), and invokeRexxStart().
setContextVariable()
void setContextVariable (const char * name, const char * value)
Definition at line 52 of file orxclassicexits.cpp.
References RexxVariablePool(), RXSHV_SET, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnamelen, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _SHVBLOCK::shvvaluelen, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by TestFunctionExit(), TestInitExit(), and TestSubcomHandler().
TestCommandExit()
int RexxEntry TestCommandExit (int code, int subcode, PEXIT exitInfo)
Definition at line 170 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::cmd, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::HALT, InstanceInfo::hlt, InstanceInfo::RAISE, _RXCMDHST_PARM::rxcmd_address, _RXCMDHST_PARM::rxcmd_command, _RXCMDHST_PARM::rxcmd_flags, _RXCMDHST_PARM::rxcmd_retc, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXCMD_FLAGS::rxfcerr, _RXCMD_FLAGS::rxfcfail, InstanceInfo::SKIP, _RXSTRING::strlength, _RXSTRING::strptr, InstanceInfo::TRACEOFF, InstanceInfo::TRACEON, and InstanceInfo::trc.
Referenced by registerExeExits().
TestFunctionExit()
int RexxEntry TestFunctionExit (int code, int subcode, PEXIT exitInfo)
Definition at line 104 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, dropContextVariable(), InstanceInfo::EXIT_ERROR, InstanceInfo::fnc, getApplicationData(), getContextVariable(), InstanceInfo::RAISE, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXFNC_FLAGS::rxfferr, _RXFNC_FLAGS::rxffnfnd, _RXFNC_FLAGS::rxffsub, _RXFNCCAL_PARM::rxfnc_argv, _RXFNCCAL_PARM::rxfnc_flags, _RXFNCCAL_PARM::rxfnc_name, _RXFNCCAL_PARM::rxfnc_retc, setContextVariable(), InstanceInfo::SKIP, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by registerExeExits().
TestHaltExit()
int RexxEntry TestHaltExit (int code, int subcode, PEXIT exitInfo)
Definition at line 378 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::HALT, InstanceInfo::hlt, InstanceInfo::NOHALT, InstanceInfo::RAISE, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXHLT_FLAGS::rxfhhalt, _RXHLTTST_PARM::rxhlt_flags, and InstanceInfo::SKIP.
Referenced by registerExeExits().
TestInitExit()
int RexxEntry TestInitExit (int code, int subcode, PEXIT exitInfo)
Definition at line 441 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::ini, InstanceInfo::RAISE, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, setContextVariable(), and InstanceInfo::SKIP.
Referenced by registerExeExits().
TestNovalueExit()
int RexxEntry TestNovalueExit (int code, int subcode, PEXIT exitInfo)
Definition at line 522 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::RAISE, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, InstanceInfo::SKIP, and InstanceInfo::var.
Referenced by registerExeExits().
TestObjectFunctionExit()
int RexxEntry TestObjectFunctionExit (int code, int subcode, PEXIT exitInfo)
Definition at line 504 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::ofnc, InstanceInfo::RAISE, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, and InstanceInfo::SKIP.
Referenced by registerExeExits().
TestQueueExit()
int RexxEntry TestQueueExit (int code, int subcode, PEXIT exitInfo)
Definition at line 242 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::msq, InstanceInfo::RAISE, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXMSQ_FLAGS::rxfmlifo, _RXMSQPSH_PARM::rxmsq_flags, _RXMSQPLL_PARM::rxmsq_retc, _RXMSQSIZ_PARM::rxmsq_size, _RXMSQPSH_PARM::rxmsq_value, RXMSQNAM, RXMSQPLL, RXMSQPSH, RXMSQSIZ, InstanceInfo::SKIP, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by registerExeExits().
TestScriptFunctionExit()
int RexxEntry TestScriptFunctionExit (int code, int subcode, PEXIT exitInfo)
Definition at line 486 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::exf, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::RAISE, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, and InstanceInfo::SKIP.
Referenced by registerExeExits().
TestSessionIOExit()
int RexxEntry TestSessionIOExit (int code, int subcode, PEXIT exitInfo)
Definition at line 310 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::ALL, InstanceInfo::CONSOLE, InstanceInfo::CONSOLE_DEBUG, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::RAISE, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXSIOSAY_PARM::rxsio_string, RXSIODTR, _RXSIODTR_PARM::rxsiodtr_retc, RXSIOSAY, RXSIOTRC, RXSIOTRD, _RXSIOTRD_PARM::rxsiotrd_retc, InstanceInfo::sio, InstanceInfo::SKIP, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by registerExeExits().
TestSubcomHandler()
RexxReturnCode RexxEntry TestSubcomHandler (CONSTRXSTRING * cmd, unsigned short * flags, PRXSTRING retstr)
Definition at line 561 of file orxclassicexits.cpp.
References getContextVariable(), RXSUBCOM_ERROR, RXSUBCOM_FAILURE, RXSUBCOM_OK, setContextVariable(), _RXSTRING::strlength, _RXSTRING::strptr, and _CONSTRXSTRING::strptr.
Referenced by registerSubcomHandler().
TestTerminationExit()
int RexxEntry TestTerminationExit (int code, int subcode, PEXIT exitInfo)
Definition at line 459 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, getApplicationData(), getContextVariable(), MAKERXSTRING, InstanceInfo::RAISE, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, InstanceInfo::SKIP, _RXSTRING::strptr, and InstanceInfo::ter.
Referenced by registerExeExits().
TestTraceExit()
int RexxEntry TestTraceExit (int code, int subcode, PEXIT exitInfo)
Definition at line 409 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::RAISE, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXTRC_FLAGS::rxftrace, _RXTRCTST_PARM::rxtrc_flags, InstanceInfo::SKIP, InstanceInfo::TRACEOFF, InstanceInfo::TRACEON, and InstanceInfo::trc.
Referenced by registerExeExits().
TestValueExit()
int RexxEntry TestValueExit (int code, int subcode, PEXIT exitInfo)
Definition at line 541 of file orxclassicexits.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, getApplicationData(), InstanceInfo::RAISE, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, InstanceInfo::SKIP, and InstanceInfo::val.
Referenced by registerExeExits().