ooRexx: orxclassic.cpp File Reference
orxclassic.cpp File Reference
#include <rexx.h>
#include <oorexxapi.h>
#include <string.h>
#include <stdio.h>
Functions
size_t REXXENTRY TestFunction (const char *Name, size_t Argc, CONSTRXSTRING Argv[], const char *Queuename, PRXSTRING Retstr)
RexxMethod2 (RexxObjectPtr, TestCreateQueue, OPTIONAL_CSTRING, qname, OPTIONAL_size_t, qnameLen)
RexxMethod1 (int, TestOpenQueue, CSTRING, qname)
RexxMethod1 (int, TestQueueExists, CSTRING, qname)
RexxMethod1 (int, TestDeleteQueue, CSTRING, qname)
RexxMethod1 (int, TestQueryQueue, CSTRING, qname)
RexxMethod3 (int, TestAddQueue, CSTRING, qname, RexxStringObject, data, int, type)
RexxMethod1 (int, TestPullFromQueue, CSTRING, qname)
RexxMethod1 (int, TestClearQueue, CSTRING, qname)
RexxMethod1 (int, TestAllocateFreeMemory, int, size)
RexxMethod0 (int, TestMVariablePool)
RexxRoutine1 (int, TestFVariablePool, RexxArrayObject, arr)
RexxRoutine1 (size_t, TestFNVariablePool, RexxArrayObject, arr)
RexxMethod3 (int, TestAddMacro, CSTRING, name, CSTRING, filename, size_t, srchpos)
RexxMethod1 (int, TestDropMacro, CSTRING, name)
RexxMethod2 (int, TestSaveMacroSpace, RexxArrayObject, names, CSTRING, filename)
RexxMethod2 (int, TestLoadMacroSpace, RexxArrayObject, names, CSTRING, filename)
RexxMethod1 (int, TestQueryMacro, CSTRING, name)
RexxMethod2 (int, TestReorderMacro, CSTRING, name, size_t, pos)
RexxMethod0 (int, TestClearMacroSpace)
RexxMethod1 (int, TestRegisterFunctionExe, CSTRING, name)
RexxMethod1 (int, TestDeregisterFunction, CSTRING, name)
RexxMethod1 (int, TestQueryFunction, CSTRING, name)
OOREXX_GET_PACKAGE (UnitTest)
Variables
RexxMethodEntry orxtest_methods []
RexxRoutineEntry orxtest_routines []
RexxPackageEntry UnitTest_package_entry
Function Documentation
OOREXX_GET_PACKAGE()
OOREXX_GET_PACKAGE (UnitTest)
RexxMethod0() [1/2]
RexxMethod0 (int , TestClearMacroSpace)
Definition at line 422 of file orxclassic.cpp.
References RexxClearMacroSpace().
RexxMethod0() [2/2]
RexxMethod0 (int , TestMVariablePool)
Definition at line 184 of file orxclassic.cpp.
References RexxVariablePool().
RexxMethod1() [1/12]
RexxMethod1 (int , TestAllocateFreeMemory , int , size)
Definition at line 173 of file orxclassic.cpp.
References RexxAllocateMemory(), and RexxFreeMemory().
RexxMethod1() [2/12]
RexxMethod1 (int , TestClearQueue , CSTRING , qname)
Definition at line 164 of file orxclassic.cpp.
References RexxClearQueue().
RexxMethod1() [3/12]
RexxMethod1 (int , TestDeleteQueue , CSTRING , qname)
Definition at line 100 of file orxclassic.cpp.
References RexxDeleteQueue().
RexxMethod1() [4/12]
RexxMethod1 (int , TestDeregisterFunction , CSTRING , name)
Definition at line 437 of file orxclassic.cpp.
References RexxDeregisterFunction().
RexxMethod1() [5/12]
RexxMethod1 (int , TestDropMacro , CSTRING , name)
Definition at line 361 of file orxclassic.cpp.
References RexxDropMacro().
RexxMethod1() [6/12]
RexxMethod1 (int , TestOpenQueue , CSTRING , qname)
Definition at line 79 of file orxclassic.cpp.
References RexxOpenQueue().
RexxMethod1() [7/12]
RexxMethod1 (int , TestPullFromQueue , CSTRING , qname)
Definition at line 135 of file orxclassic.cpp.
References _RexxQueueTime::day, _RexxQueueTime::hours, MAKERXSTRING, _RexxQueueTime::minutes, _RexxQueueTime::month, RexxPullFromQueue(), RXQUEUE_OK, _RexxQueueTime::seconds, _RXSTRING::strlength, _RXSTRING::strptr, _RexxQueueTime::weekday, _RexxQueueTime::year, and _RexxQueueTime::yearday.
RexxMethod1() [8/12]
RexxMethod1 (int , TestQueryFunction , CSTRING , name)
Definition at line 445 of file orxclassic.cpp.
References RexxQueryFunction().
RexxMethod1() [9/12]
RexxMethod1 (int , TestQueryMacro , CSTRING , name)
Definition at line 403 of file orxclassic.cpp.
References RexxQueryMacro().
RexxMethod1() [10/12]
RexxMethod1 (int , TestQueryQueue , CSTRING , qname)
Definition at line 109 of file orxclassic.cpp.
References RexxQueryQueue().
RexxMethod1() [11/12]
RexxMethod1 (int , TestQueueExists , CSTRING , qname)
Definition at line 91 of file orxclassic.cpp.
References RexxQueueExists().
RexxMethod1() [12/12]
RexxMethod1 (int , TestRegisterFunctionExe , CSTRING , name)
Definition at line 429 of file orxclassic.cpp.
References RexxRegisterFunctionExe(), and TestFunction().
RexxMethod2() [1/4]
RexxMethod2 (int , TestLoadMacroSpace , RexxArrayObject , names , CSTRING , filename)
Definition at line 386 of file orxclassic.cpp.
References RexxLoadMacroSpace().
RexxMethod2() [2/4]
RexxMethod2 (int , TestReorderMacro , CSTRING , name , size_t , pos)
Definition at line 413 of file orxclassic.cpp.
References RexxReorderMacro().
RexxMethod2() [3/4]
RexxMethod2 (int , TestSaveMacroSpace , RexxArrayObject , names , CSTRING , filename)
Definition at line 369 of file orxclassic.cpp.
References RexxSaveMacroSpace().
RexxMethod2() [4/4]
RexxMethod2 (RexxObjectPtr , TestCreateQueue , OPTIONAL_CSTRING , qname , OPTIONAL_size_t , qnameLen)
Definition at line 64 of file orxclassic.cpp.
References argumentExists, MAX_QUEUE_NAME_LENGTH, and RexxCreateQueue().
RexxMethod3() [1/2]
RexxMethod3 (int , TestAddMacro , CSTRING , name , CSTRING , filename , size_t , srchpos)
Definition at line 351 of file orxclassic.cpp.
References RexxAddMacro().
RexxMethod3() [2/2]
RexxMethod3 (int , TestAddQueue , CSTRING , qname , RexxStringObject , data , int , type)
Definition at line 121 of file orxclassic.cpp.
References MAKERXSTRING, RexxAddQueue(), and type.
RexxRoutine1() [1/2]
RexxRoutine1 (int , TestFVariablePool , RexxArrayObject , arr)
Definition at line 191 of file orxclassic.cpp.
References RexxFreeMemory(), RexxVariablePool(), RXSHV_DROPV, RXSHV_FETCH, RXSHV_PRIV, RXSHV_SET, RXSHV_SYDRO, RXSHV_SYFET, RXSHV_SYSET, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnamelen, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _SHVBLOCK::shvvaluelen, _RXSTRING::strlength, and _RXSTRING::strptr.
RexxRoutine1() [2/2]
RexxRoutine1 (size_t , TestFNVariablePool , RexxArrayObject , arr)
Definition at line 310 of file orxclassic.cpp.
References RexxFreeMemory(), RexxVariablePool(), RXSHV_LVAR, RXSHV_NEXTV, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnamelen, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _SHVBLOCK::shvvaluelen, _RXSTRING::strlength, and _RXSTRING::strptr.
TestFunction()
size_t REXXENTRY TestFunction (const char * Name, size_t Argc, CONSTRXSTRING Argv[], const char * Queuename, PRXSTRING Retstr)
Definition at line 44 of file orxclassic.cpp.
References _RXSTRING::strlength, _RXSTRING::strptr, and _CONSTRXSTRING::strptr.
Referenced by RexxMethod1().
Variable Documentation
orxtest_methods
RexxMethodEntry orxtest_methods[]
Initial value:
= {
    REXX_METHOD(TestCreateQueue,        TestCreateQueue),
    REXX_METHOD(TestOpenQueue,          TestOpenQueue),
    REXX_METHOD(TestQueueExists,        TestQueueExists),
    REXX_METHOD(TestDeleteQueue,        TestDeleteQueue),
    REXX_METHOD(TestQueryQueue,         TestQueryQueue),
    REXX_METHOD(TestAddQueue,           TestAddQueue),
    REXX_METHOD(TestPullFromQueue,      TestPullFromQueue),
    REXX_METHOD(TestClearQueue,         TestClearQueue),
    REXX_METHOD(TestAllocateFreeMemory, TestAllocateFreeMemory),
    REXX_METHOD(TestMVariablePool,      TestMVariablePool),
    REXX_METHOD(TestAddMacro,           TestAddMacro),
    REXX_METHOD(TestDropMacro,          TestDropMacro),
    REXX_METHOD(TestSaveMacroSpace,     TestSaveMacroSpace),
    REXX_METHOD(TestLoadMacroSpace,     TestLoadMacroSpace),
    REXX_METHOD(TestQueryMacro,         TestQueryMacro),
    REXX_METHOD(TestReorderMacro,       TestReorderMacro),
    REXX_METHOD(TestClearMacroSpace,    TestClearMacroSpace),
    REXX_METHOD(TestRegisterFunctionExe,TestRegisterFunctionExe),
    REXX_METHOD(TestDeregisterFunction, TestDeregisterFunction),
    REXX_METHOD(TestQueryFunction, TestQueryFunction),
}
Definition at line 454 of file orxclassic.cpp.
orxtest_routines
RexxRoutineEntry orxtest_routines[]
Initial value:
= {
    REXX_TYPED_ROUTINE(TestFVariablePool,  TestFVariablePool),
    REXX_TYPED_ROUTINE(TestFNVariablePool, TestFNVariablePool),
}
Definition at line 479 of file orxclassic.cpp.
UnitTest_package_entry
RexxPackageEntry UnitTest_package_entry
Initial value:
= {
    STANDARD_PACKAGE_HEADER
    REXX_INTERPRETER_4_0_0,
    "UnitTest",
    "1.0.0",
    NULL,
    NULL,
    orxtest_routines,
    orxtest_methods
}
Definition at line 486 of file orxclassic.cpp.