ooRexx: orxclassic1.c File Reference
orxclassic1.c File Reference
#include <rexx.h>
#include <string.h>
#include <stdio.h>
Functions
size_t REXXENTRY MyTestExtFunc (const char *Name, long Argc, CONSTRXSTRING Argv[], const char *Queuename, PRXSTRING Retstr)
size_t REXXENTRY TestExternalFunction (const char *Name, long Argc, CONSTRXSTRING Argv[], const char *Queuename, PRXSTRING Retstr)
RexxReturnCode REXXENTRY MyTestSubcomHandler (CONSTRXSTRING *Cmd, unsigned short *flags, PRXSTRING Retstr)
size_t REXXENTRY TestSubcomHandler (const char *Name, long Argc, CONSTRXSTRING Argv[], const char *Queuename, PRXSTRING Retstr)
Function Documentation
MyTestExtFunc()
size_t REXXENTRY MyTestExtFunc (const char * Name, long Argc, CONSTRXSTRING Argv[], const char * Queuename, PRXSTRING Retstr)
Definition at line 43 of file orxclassic1.c.
References RexxDeregisterFunction(), _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by TestExternalFunction().
MyTestSubcomHandler()
RexxReturnCode REXXENTRY MyTestSubcomHandler (CONSTRXSTRING * Cmd, unsigned short * flags, PRXSTRING Retstr)
Definition at line 110 of file orxclassic1.c.
References RXAUTOBUFLEN, RXSUBCOM_ERROR, RXSUBCOM_OK, _RXSTRING::strlength, _CONSTRXSTRING::strlength, _RXSTRING::strptr, and _CONSTRXSTRING::strptr.
Referenced by TestSubcomHandler().
TestExternalFunction()
size_t REXXENTRY TestExternalFunction (const char * Name, long Argc, CONSTRXSTRING Argv[], const char * Queuename, PRXSTRING Retstr)
Definition at line 60 of file orxclassic1.c.
References MyTestExtFunc(), RexxQueryFunction(), RexxRegisterFunctionDll(), RexxRegisterFunctionExe(), RXVALIDSTRING, _RXSTRING::strlength, and _RXSTRING::strptr.
TestSubcomHandler()
size_t REXXENTRY TestSubcomHandler (const char * Name, long Argc, CONSTRXSTRING Argv[], const char * Queuename, PRXSTRING Retstr)
Definition at line 124 of file orxclassic1.c.
References MyTestSubcomHandler(), RexxDeregisterSubcom(), RexxQuerySubcom(), RexxRegisterSubcomDll(), RexxRegisterSubcomExe(), RXSUBCOM_DROPPABLE, _RXSTRING::strlength, and _RXSTRING::strptr.