ooRexx: orxexits.hpp File Reference
orxexits.hpp File Reference
#include "oorexxapi.h"
#include <string.h>
Classes
class InstanceInfo
class InstanceInfo::ExitConfig
Functions
void REXXENTRY deregisterExits ()
void REXXENTRY registerExeExits (void *data)
void REXXENTRY registerDllExits (void *data)
void REXXENTRY registerSubcomHandler (void *data)
void REXXENTRY deregisterSubcomHandler ()
bool REXXENTRY buildRegisteredExitList (InstanceInfo *instanceInfo, RXSYSEXIT *exitList)
RexxReturnCode REXXENTRY createInstance (InstanceInfo *instanceInfo, RexxInstance *&instance, RexxThreadContext *&threadContext)
bool REXXENTRY buildContextExitList (InstanceInfo *instanceInfo, RexxContextExit *exitList)
void REXXENTRY invokeProgram (InstanceInfo *instanceInfo)
void REXXENTRY invokeRexxStart (InstanceInfo *instanceInfo)
void REXXENTRY buildInfo (InstanceInfo *instanceInfo, int argc, char **argv)
Function Documentation
buildContextExitList()
bool REXXENTRY buildContextExitList (InstanceInfo * instanceInfo, RexxContextExit * exitList)
Definition at line 705 of file orxinstance.cpp.
References InstanceInfo::cmd, counter(), InstanceInfo::exf, InstanceInfo::fnc, _RexxContextExit::handler, InstanceInfo::hlt, InstanceInfo::ini, InstanceInfo::ExitConfig::isEnabled(), InstanceInfo::msq, InstanceInfo::ofnc, RXCMD, RXEXF, RXFNC, RXHLT, RXINI, RXMSQ, RXNOVAL, RXOFNC, RXSIO, RXTER, RXTRC, RXVALUE, InstanceInfo::sio, _RexxContextExit::sysexit_code, InstanceInfo::ter, TestContextCommandExit(), TestContextFunctionExit(), TestContextHaltExit(), TestContextInitExit(), TestContextNovalueExit(), TestContextObjectFunctionExit(), TestContextQueueExit(), TestContextScriptFunctionExit(), TestContextSessionIOExit(), TestContextTerminationExit(), TestContextTraceExit(), TestContextValueExit(), InstanceInfo::trc, InstanceInfo::val, and InstanceInfo::var.
Referenced by createInstance().
buildInfo()
void REXXENTRY buildInfo (InstanceInfo * instanceInfo, int argc, char ** argv)
Definition at line 42 of file rexxinstance.cpp.
References InstanceInfo::argCount, InstanceInfo::arguments, InstanceInfo::callType, InstanceInfo::cmd, InstanceInfo::CONTEXT, InstanceInfo::exf, InstanceInfo::exitStyle, InstanceInfo::extensionPath, InstanceInfo::extensions, InstanceInfo::fnc, InstanceInfo::hlt, InstanceInfo::ini, InstanceInfo::initialAddress, InstanceInfo::INSTANCE, InstanceInfo::loadLibrary, InstanceInfo::msq, InstanceInfo::NONE, InstanceInfo::ofnc, InstanceInfo::programName, InstanceInfo::REGISTERED_DLL, InstanceInfo::REGISTERED_EXE, InstanceInfo::REXXSTART, InstanceInfo::sio, InstanceInfo::ter, InstanceInfo::trc, type, InstanceInfo::val, and InstanceInfo::var.
Referenced by main().
buildRegisteredExitList()
bool REXXENTRY buildRegisteredExitList (InstanceInfo * instanceInfo, RXSYSEXIT * exitList)
Definition at line 675 of file orxclassicexits.cpp.
References InstanceInfo::cmd, counter(), InstanceInfo::exf, InstanceInfo::fnc, InstanceInfo::hlt, InstanceInfo::ini, InstanceInfo::ExitConfig::isEnabled(), InstanceInfo::msq, InstanceInfo::ofnc, RXCMD, RXEXF, RXFNC, RXHLT, RXINI, RXMSQ, RXNOVAL, RXOFNC, RXSIO, RXTER, RXTRC, RXVALUE, InstanceInfo::sio, _RXSYSEXIT::sysexit_code, _RXSYSEXIT::sysexit_name, InstanceInfo::ter, InstanceInfo::trc, InstanceInfo::val, and InstanceInfo::var.
Referenced by createInstance(), and invokeRexxStart().
createInstance()
RexxReturnCode REXXENTRY createInstance (InstanceInfo * instanceInfo, RexxInstance *& instance, RexxThreadContext *& threadContext)
Definition at line 803 of file orxinstance.cpp.
References APPLICATION_DATA, buildContextExitList(), buildRegisteredExitList(), InstanceInfo::CONTEXT, DIRECT_ENVIRONMENTS, DIRECT_EXITS, InstanceInfo::exitStyle, InstanceInfo::extensionPath, InstanceInfo::extensions, EXTERNAL_CALL_EXTENSIONS, EXTERNAL_CALL_PATH, RexxContextEnvironment::handler, RexxRedirectingEnvironment::handler, INITIAL_ADDRESS_ENVIRONMENT, InstanceInfo::initialAddress, LOAD_REQUIRED_LIBRARY, InstanceInfo::loadLibrary, RexxContextEnvironment::name, RexxRedirectingEnvironment::name, RexxRegisteredEnvironment::name, RexxOption::option, RexxOption::optionName, REDIRECTING_ENVIRONMENTS, registerDllExits(), InstanceInfo::REGISTERED_DLL, REGISTERED_ENVIRONMENTS, InstanceInfo::REGISTERED_EXE, REGISTERED_EXITS, RexxRegisteredEnvironment::registeredName, registerExeExits(), registerSubcomHandler(), RexxCreateInterpreter(), RXNOOFEXITS, TestDirectCommandHandler(), and TestRedirectingCommandHandler().
Referenced by invokeProgram().
deregisterExits()
void REXXENTRY deregisterExits ()
Definition at line 616 of file orxclassicexits.cpp.
References RexxDeregisterExit().
Referenced by invokeProgram(), invokeRexxStart(), registerDllExits(), and registerExeExits().
deregisterSubcomHandler()
void REXXENTRY deregisterSubcomHandler ()
Definition at line 600 of file orxclassicexits.cpp.
References RexxDeregisterSubcom().
Referenced by invokeProgram(), invokeRexxStart(), and registerSubcomHandler().
invokeProgram()
void REXXENTRY invokeProgram (InstanceInfo * instanceInfo)
Definition at line 913 of file orxinstance.cpp.
References InstanceInfo::argCount, InstanceInfo::arguments, RexxCondition::code, InstanceInfo::code, createInstance(), deregisterExits(), deregisterSubcomHandler(), NULLOBJECT, InstanceInfo::programName, RexxCondition::rc, InstanceInfo::rc, and InstanceInfo::returnResult.
Referenced by main(), and RexxMethod3().
invokeRexxStart()
void REXXENTRY invokeRexxStart (InstanceInfo * instanceInfo)
Definition at line 773 of file orxclassicexits.cpp.
References InstanceInfo::argCount, InstanceInfo::arguments, buildRegisteredExitList(), InstanceInfo::code, deregisterExits(), deregisterSubcomHandler(), InstanceInfo::exitStyle, InstanceInfo::initialAddress, MAKERXSTRING, InstanceInfo::programName, InstanceInfo::rc, registerDllExits(), InstanceInfo::REGISTERED_DLL, registerSubcomHandler(), InstanceInfo::returnResult, RexxFreeMemory(), RexxStart(), RXCOMMAND, RXNOOFEXITS, and _RXSTRING::strptr.
Referenced by main(), and RexxMethod3().
registerDllExits()
void REXXENTRY registerDllExits (void * data)
Definition at line 653 of file orxclassicexits.cpp.
References deregisterExits(), RexxRegisterExitDll(), and RXEXIT_DROPPABLE.
Referenced by createInstance(), and invokeRexxStart().
registerExeExits()
void REXXENTRY registerExeExits (void * data)
Definition at line 632 of file orxclassicexits.cpp.
References deregisterExits(), RexxRegisterExitExe(), TestCommandExit(), TestFunctionExit(), TestHaltExit(), TestInitExit(), TestNovalueExit(), TestObjectFunctionExit(), TestQueueExit(), TestScriptFunctionExit(), TestSessionIOExit(), TestTerminationExit(), TestTraceExit(), and TestValueExit().
Referenced by createInstance().
registerSubcomHandler()
void REXXENTRY registerSubcomHandler (void * data)
Definition at line 606 of file orxclassicexits.cpp.
References deregisterSubcomHandler(), RexxRegisterSubcomExe(), and TestSubcomHandler().
Referenced by createInstance(), and invokeRexxStart().