ooRexx: orxfunction.cpp File Reference
orxfunction.cpp File Reference
#include <oorexxapi.h>
#include <string.h>
Functions
RexxRoutine0 (int, TestZeroIntArgs)
RexxRoutine1 (int, TestOneIntArg, int, arg1)
RexxRoutine2 (int, TestTwoIntArgs, int, arg1, int, arg2)
RexxRoutine3 (int, TestThreeIntArgs, int, arg1, int, arg2, int, arg3)
RexxRoutine4 (int, TestFourIntArgs, int, arg1, int, arg2, int, arg3, int, arg4)
RexxRoutine5 (int, TestFiveIntArgs, int, arg1, int, arg2, int, arg3, int, arg4, int, arg5)
RexxRoutine6 (int, TestSixIntArgs, int, arg1, int, arg2, int, arg3, int, arg4, int, arg5, int, arg6)
RexxRoutine7 (int, TestSevenIntArgs, int, arg1, int, arg2, int, arg3, int, arg4, int, arg5, int, arg6, int, arg7)
RexxRoutine8 (int, TestEightIntArgs, int, arg1, int, arg2, int, arg3, int, arg4, int, arg5, int, arg6, int, arg7, int, arg8)
RexxRoutine9 (int, TestNineIntArgs, int, arg1, int, arg2, int, arg3, int, arg4, int, arg5, int, arg6, int, arg7, int, arg8, int, arg9)
RexxRoutine10 (int, TestTenIntArgs, int, arg1, int, arg2, int, arg3, int, arg4, int, arg5, int, arg6, int, arg7, int, arg8, int, arg9, int, arg10)
RexxRoutine1 (int, TestIntArg, int, arg1)
RexxRoutine1 (int32_t, TestInt32Arg, int32_t, arg1)
RexxRoutine1 (uint32_t, TestUint32Arg, uint32_t, arg1)
RexxRoutine1 (int8_t, TestInt8Arg, int8_t, arg1)
RexxRoutine1 (uint8_t, TestUint8Arg, uint8_t, arg1)
RexxRoutine1 (int16_t, TestInt16Arg, int16_t, arg1)
RexxRoutine1 (uint16_t, TestUint16Arg, uint16_t, arg1)
RexxRoutine1 (int64_t, TestInt64Arg, int64_t, arg1)
RexxRoutine1 (uint64_t, TestUint64Arg, uint64_t, arg1)
RexxRoutine1 (intptr_t, TestIntPtrArg, intptr_t, arg1)
RexxRoutine1 (uintptr_t, TestUintPtrArg, uintptr_t, arg1)
RexxRoutine1 (wholenumber_t, TestWholeNumberArg, wholenumber_t, arg1)
RexxRoutine1 (positive_wholenumber_t, TestPositiveWholeNumberArg, positive_wholenumber_t, arg1)
RexxRoutine1 (wholenumber_t, TestNonnegativeWholeNumberArg, nonnegative_wholenumber_t, arg1)
RexxRoutine1 (stringsize_t, TestStringSizeArg, stringsize_t, arg1)
RexxRoutine1 (size_t, TestSizeArg, size_t, arg1)
RexxRoutine1 (ssize_t, TestSSizeArg, ssize_t, arg1)
RexxRoutine1 (logical_t, TestLogicalArg, logical_t, arg1)
RexxRoutine1 (float, TestFloatArg, float, arg1)
RexxRoutine1 (double, TestDoubleArg, double, arg1)
RexxRoutine1 (CSTRING, TestCstringArg, CSTRING, arg1)
RexxRoutine1 (CSTRING, TestOptionalCstringArg, OPTIONAL_CSTRING, arg1)
RexxRoutine1 (RexxStringObject, TestStringArg, RexxStringObject, arg1)
RexxRoutine1 (RexxStringObject, TestOptionalStringArg, OPTIONAL_RexxStringObject, arg1)
RexxRoutine0 (POINTER, TestPointerValue)
RexxRoutine1 (logical_t, TestPointerArg, POINTER, arg1)
RexxRoutine0 (POINTER, TestNullPointerValue)
RexxRoutine0 (POINTERSTRING, TestPointerStringValue)
RexxRoutine1 (logical_t, TestPointerStringArg, POINTERSTRING, arg1)
RexxRoutine0 (POINTERSTRING, TestNullPointerStringValue)
RexxRoutine1 (RexxStemObject, TestStemArg, RexxStemObject, arg1)
RexxRoutine2 (RexxObjectPtr, TestObjectToValue, RexxObjectPtr, arg1, int, type)
RexxRoutine1 (RexxArrayObject, TestArglistArg, ARGLIST, arg1)
RexxRoutine1 (CSTRING, TestNameArg, NAME, arg1)
RexxRoutine1 (RexxArrayObject, TestGetArguments, ARGLIST, arg1)
RexxRoutine2 (RexxObjectPtr, TestGetArgument, size_t, index, ARGLIST, arg1)
RexxRoutine0 (CSTRING, TestGetRoutineName)
RexxRoutine0 (RexxObjectPtr, TestGetRoutine)
RexxRoutine2 (int, TestSetContextVariable, CSTRING, name, RexxObjectPtr, value)
RexxRoutine1 (RexxObjectPtr, TestGetContextVariable, CSTRING, name)
RexxRoutine1 (int, TestDropContextVariable, CSTRING, name)
RexxRoutine0 (RexxObjectPtr, TestGetAllContextVariables)
RexxRoutine0 (stringsize_t, TestGetContextDigits)
RexxRoutine0 (stringsize_t, TestGetContextFuzz)
RexxRoutine0 (logical_t, TestGetContextForm)
RexxRoutine1 (RexxStemObject, TestResolveStemVariable, RexxObjectPtr, arg1)
RexxRoutine1 (RexxClassObject, TestFindContextClass, CSTRING, name)
RexxObjectPtr RexxEntry dHandler (RexxExitContext *context, RexxStringObject address, RexxStringObject command)
RexxObjectPtr RexxEntry rHandler (RexxExitContext *context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext *ioContext)
RexxObjectPtr RexxEntry ioHandler (RexxExitContext *context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext *ioContext)
RexxRoutine2 (RexxObjectPtr, TestAddCommandEnvironment, CSTRING, name, CSTRING, type)
RexxRoutine1 (int, TestRaiseException0, size_t, errNo)
RexxRoutine2 (int, TestRaiseException1, size_t, errNo, RexxObjectPtr, sub1)
RexxRoutine3 (int, TestRaiseException2, size_t, errNo, RexxObjectPtr, sub1, RexxObjectPtr, sub2)
RexxRoutine2 (int, TestRaiseException, size_t, errNo, RexxArrayObject, subs)
RexxRoutine1 (int, TestThrowException0, size_t, errNo)
RexxRoutine2 (int, TestThrowException1, size_t, errNo, RexxObjectPtr, sub1)
RexxRoutine3 (int, TestThrowException2, size_t, errNo, RexxObjectPtr, sub1, RexxObjectPtr, sub2)
RexxRoutine2 (int, TestThrowException, size_t, errNo, RexxArrayObject, subs)
RexxRoutine4 (int, TestThrowCondition, CSTRING, name, OPTIONAL_CSTRING, desc, OPTIONAL_RexxArrayObject, add, OPTIONAL_RexxObjectPtr, result)
RexxRoutine1 (RexxObjectPtr, TestNestedAttach, RexxObjectPtr, o)
OOREXX_GET_PACKAGE (UnitTest)
Variables
RexxRoutineEntry orxtest_funcs []
RexxPackageEntry UnitTest_package_entry
Function Documentation
dHandler()
RexxObjectPtr RexxEntry dHandler (RexxExitContext * context, RexxStringObject address, RexxStringObject command)
Definition at line 530 of file orxfunction.cpp.
Referenced by RexxRoutine2().
ioHandler()
RexxObjectPtr RexxEntry ioHandler (RexxExitContext * context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext * ioContext)
Definition at line 564 of file orxfunction.cpp.
Referenced by RexxRoutine2().
OOREXX_GET_PACKAGE()
OOREXX_GET_PACKAGE (UnitTest)
RexxRoutine0() [1/11]
RexxRoutine0 (CSTRING , TestGetRoutineName)
Definition at line 439 of file orxfunction.cpp.
RexxRoutine0() [2/11]
RexxRoutine0 (int , TestZeroIntArgs)
Definition at line 41 of file orxfunction.cpp.
RexxRoutine0() [3/11]
RexxRoutine0 (logical_t , TestGetContextForm)
Definition at line 498 of file orxfunction.cpp.
RexxRoutine0() [4/11]
RexxRoutine0 (POINTER , TestNullPointerValue)
Definition at line 352 of file orxfunction.cpp.
RexxRoutine0() [5/11]
RexxRoutine0 (POINTER , TestPointerValue)
Definition at line 336 of file orxfunction.cpp.
RexxRoutine0() [6/11]
RexxRoutine0 (POINTERSTRING , TestNullPointerStringValue)
Definition at line 374 of file orxfunction.cpp.
RexxRoutine0() [7/11]
RexxRoutine0 (POINTERSTRING , TestPointerStringValue)
Definition at line 358 of file orxfunction.cpp.
RexxRoutine0() [8/11]
RexxRoutine0 (RexxObjectPtr , TestGetAllContextVariables)
Definition at line 480 of file orxfunction.cpp.
RexxRoutine0() [9/11]
RexxRoutine0 (RexxObjectPtr , TestGetRoutine)
Definition at line 445 of file orxfunction.cpp.
RexxRoutine0() [10/11]
RexxRoutine0 (stringsize_t , TestGetContextDigits)
Definition at line 486 of file orxfunction.cpp.
RexxRoutine0() [11/11]
RexxRoutine0 (stringsize_t , TestGetContextFuzz)
Definition at line 492 of file orxfunction.cpp.
RexxRoutine1() [1/38]
RexxRoutine1 (CSTRING , TestCstringArg , CSTRING , arg1)
Definition at line 303 of file orxfunction.cpp.
RexxRoutine1() [2/38]
RexxRoutine1 (CSTRING , TestNameArg , NAME , arg1)
Definition at line 411 of file orxfunction.cpp.
RexxRoutine1() [3/38]
RexxRoutine1 (CSTRING , TestOptionalCstringArg , OPTIONAL_CSTRING , arg1)
Definition at line 310 of file orxfunction.cpp.
References argumentOmitted.
RexxRoutine1() [4/38]
RexxRoutine1 (double , TestDoubleArg , double , arg1)
Definition at line 296 of file orxfunction.cpp.
RexxRoutine1() [5/38]
RexxRoutine1 (float , TestFloatArg , float , arg1)
Definition at line 289 of file orxfunction.cpp.
RexxRoutine1() [6/38]
RexxRoutine1 (int , TestDropContextVariable , CSTRING , name)
Definition at line 472 of file orxfunction.cpp.
RexxRoutine1() [7/38]
RexxRoutine1 (int , TestIntArg , int , arg1)
Definition at line 162 of file orxfunction.cpp.
RexxRoutine1() [8/38]
RexxRoutine1 (int , TestOneIntArg , int , arg1)
Definition at line 47 of file orxfunction.cpp.
RexxRoutine1() [9/38]
RexxRoutine1 (int , TestRaiseException0 , size_t , errNo)
Definition at line 773 of file orxfunction.cpp.
RexxRoutine1() [10/38]
RexxRoutine1 (int , TestThrowException0 , size_t , errNo)
Definition at line 817 of file orxfunction.cpp.
RexxRoutine1() [11/38]
RexxRoutine1 (int16_t , TestInt16Arg , int16_t , arg1)
Definition at line 197 of file orxfunction.cpp.
RexxRoutine1() [12/38]
RexxRoutine1 (int32_t , TestInt32Arg , int32_t , arg1)
Definition at line 169 of file orxfunction.cpp.
RexxRoutine1() [13/38]
RexxRoutine1 (int64_t , TestInt64Arg , int64_t , arg1)
Definition at line 211 of file orxfunction.cpp.
RexxRoutine1() [14/38]
RexxRoutine1 (int8_t , TestInt8Arg , int8_t , arg1)
Definition at line 183 of file orxfunction.cpp.
RexxRoutine1() [15/38]
RexxRoutine1 (intptr_t , TestIntPtrArg , intptr_t , arg1)
Definition at line 225 of file orxfunction.cpp.
RexxRoutine1() [16/38]
RexxRoutine1 (logical_t , TestLogicalArg , logical_t , arg1)
Definition at line 282 of file orxfunction.cpp.
RexxRoutine1() [17/38]
RexxRoutine1 (logical_t , TestPointerArg , POINTER , arg1)
Definition at line 342 of file orxfunction.cpp.
RexxRoutine1() [18/38]
RexxRoutine1 (logical_t , TestPointerStringArg , POINTERSTRING , arg1)
Definition at line 364 of file orxfunction.cpp.
RexxRoutine1() [19/38]
RexxRoutine1 (positive_wholenumber_t , TestPositiveWholeNumberArg , positive_wholenumber_t , arg1)
Definition at line 246 of file orxfunction.cpp.
RexxRoutine1() [20/38]
RexxRoutine1 (RexxArrayObject , TestArglistArg , ARGLIST , arg1)
Definition at line 404 of file orxfunction.cpp.
RexxRoutine1() [21/38]
RexxRoutine1 (RexxArrayObject , TestGetArguments , ARGLIST , arg1)
Definition at line 418 of file orxfunction.cpp.
RexxRoutine1() [22/38]
RexxRoutine1 (RexxClassObject , TestFindContextClass , CSTRING , name)
Definition at line 516 of file orxfunction.cpp.
References NULLOBJECT, and Rexx_Error_Invalid_argument_user_defined.
RexxRoutine1() [23/38]
RexxRoutine1 (RexxObjectPtr , TestGetContextVariable , CSTRING , name)
Definition at line 460 of file orxfunction.cpp.
References NULLOBJECT, and Rexx_Error_Invalid_argument_user_defined.
RexxRoutine1() [24/38]
RexxRoutine1 (RexxObjectPtr , TestNestedAttach , RexxObjectPtr , o)
Definition at line 875 of file orxfunction.cpp.
References Rexx_Error_Execution_no_concurrency.
RexxRoutine1() [25/38]
RexxRoutine1 (RexxStemObject , TestResolveStemVariable , RexxObjectPtr , arg1)
Definition at line 504 of file orxfunction.cpp.
References NULLOBJECT, and Rexx_Error_Invalid_argument_user_defined.
RexxRoutine1() [26/38]
RexxRoutine1 (RexxStemObject , TestStemArg , RexxStemObject , arg1)
Definition at line 380 of file orxfunction.cpp.
RexxRoutine1() [27/38]
RexxRoutine1 (RexxStringObject , TestOptionalStringArg , OPTIONAL_RexxStringObject , arg1)
Definition at line 326 of file orxfunction.cpp.
References argumentOmitted.
RexxRoutine1() [28/38]
RexxRoutine1 (RexxStringObject , TestStringArg , RexxStringObject , arg1)
Definition at line 320 of file orxfunction.cpp.
RexxRoutine1() [29/38]
RexxRoutine1 (size_t , TestSizeArg , size_t , arg1)
Definition at line 268 of file orxfunction.cpp.
RexxRoutine1() [30/38]
RexxRoutine1 (ssize_t , TestSSizeArg , ssize_t , arg1)
Definition at line 275 of file orxfunction.cpp.
RexxRoutine1() [31/38]
RexxRoutine1 (stringsize_t , TestStringSizeArg , stringsize_t , arg1)
Definition at line 261 of file orxfunction.cpp.
RexxRoutine1() [32/38]
RexxRoutine1 (uint16_t , TestUint16Arg , uint16_t , arg1)
Definition at line 204 of file orxfunction.cpp.
RexxRoutine1() [33/38]
RexxRoutine1 (uint32_t , TestUint32Arg , uint32_t , arg1)
Definition at line 176 of file orxfunction.cpp.
RexxRoutine1() [34/38]
RexxRoutine1 (uint64_t , TestUint64Arg , uint64_t , arg1)
Definition at line 218 of file orxfunction.cpp.
RexxRoutine1() [35/38]
RexxRoutine1 (uint8_t , TestUint8Arg , uint8_t , arg1)
Definition at line 190 of file orxfunction.cpp.
RexxRoutine1() [36/38]
RexxRoutine1 (uintptr_t , TestUintPtrArg , uintptr_t , arg1)
Definition at line 232 of file orxfunction.cpp.
RexxRoutine1() [37/38]
RexxRoutine1 (wholenumber_t , TestNonnegativeWholeNumberArg , nonnegative_wholenumber_t , arg1)
Definition at line 253 of file orxfunction.cpp.
RexxRoutine1() [38/38]
RexxRoutine1 (wholenumber_t , TestWholeNumberArg , wholenumber_t , arg1)
Definition at line 239 of file orxfunction.cpp.
RexxRoutine10()
RexxRoutine10 (int , TestTenIntArgs , int , arg1 , int , arg2 , int , arg3 , int , arg4 , int , arg5 , int , arg6 , int , arg7 , int , arg8 , int , arg9 , int , arg10)
Definition at line 146 of file orxfunction.cpp.
RexxRoutine2() [1/9]
RexxRoutine2 (int , TestRaiseException , size_t , errNo , RexxArrayObject , subs)
Definition at line 806 of file orxfunction.cpp.
RexxRoutine2() [2/9]
RexxRoutine2 (int , TestRaiseException1 , size_t , errNo , RexxObjectPtr , sub1)
Definition at line 783 of file orxfunction.cpp.
RexxRoutine2() [3/9]
RexxRoutine2 (int , TestSetContextVariable , CSTRING , name , RexxObjectPtr , value)
Definition at line 451 of file orxfunction.cpp.
RexxRoutine2() [4/9]
RexxRoutine2 (int , TestThrowException , size_t , errNo , RexxArrayObject , subs)
Definition at line 850 of file orxfunction.cpp.
RexxRoutine2() [5/9]
RexxRoutine2 (int , TestThrowException1 , size_t , errNo , RexxObjectPtr , sub1)
Definition at line 827 of file orxfunction.cpp.
RexxRoutine2() [6/9]
RexxRoutine2 (int , TestTwoIntArgs , int , arg1 , int , arg2)
Definition at line 54 of file orxfunction.cpp.
RexxRoutine2() [7/9]
RexxRoutine2 (RexxObjectPtr , TestAddCommandEnvironment , CSTRING , name , CSTRING , type)
Definition at line 750 of file orxfunction.cpp.
References dHandler(), DIRECT_COMMAND_ENVIRONMENT, ioHandler(), NULLOBJECT, REDIRECTING_COMMAND_ENVIRONMENT, rHandler(), and type.
RexxRoutine2() [8/9]
RexxRoutine2 (RexxObjectPtr , TestGetArgument , size_t , index , ARGLIST , arg1)
Definition at line 424 of file orxfunction.cpp.
References NULLOBJECT, and Rexx_Error_Invalid_argument_user_defined.
RexxRoutine2() [9/9]
RexxRoutine2 (RexxObjectPtr , TestObjectToValue , RexxObjectPtr , arg1 , int , type)
Definition at line 387 of file orxfunction.cpp.
References NULLOBJECT, Rexx_Error_Invalid_argument_user_defined, _ValueDescriptor::type, and type.
RexxRoutine3() [1/3]
RexxRoutine3 (int , TestRaiseException2 , size_t , errNo , RexxObjectPtr , sub1 , RexxObjectPtr , sub2)
Definition at line 794 of file orxfunction.cpp.
RexxRoutine3() [2/3]
RexxRoutine3 (int , TestThreeIntArgs , int , arg1 , int , arg2 , int , arg3)
Definition at line 62 of file orxfunction.cpp.
RexxRoutine3() [3/3]
RexxRoutine3 (int , TestThrowException2 , size_t , errNo , RexxObjectPtr , sub1 , RexxObjectPtr , sub2)
Definition at line 838 of file orxfunction.cpp.
RexxRoutine4() [1/2]
RexxRoutine4 (int , TestFourIntArgs , int , arg1 , int , arg2 , int , arg3 , int , arg4)
Definition at line 71 of file orxfunction.cpp.
RexxRoutine4() [2/2]
RexxRoutine4 (int , TestThrowCondition , CSTRING , name , OPTIONAL_CSTRING , desc , OPTIONAL_RexxArrayObject , add , OPTIONAL_RexxObjectPtr , result)
Definition at line 861 of file orxfunction.cpp.
RexxRoutine5()
RexxRoutine5 (int , TestFiveIntArgs , int , arg1 , int , arg2 , int , arg3 , int , arg4 , int , arg5)
Definition at line 81 of file orxfunction.cpp.
RexxRoutine6()
RexxRoutine6 (int , TestSixIntArgs , int , arg1 , int , arg2 , int , arg3 , int , arg4 , int , arg5 , int , arg6)
Definition at line 92 of file orxfunction.cpp.
RexxRoutine7()
RexxRoutine7 (int , TestSevenIntArgs , int , arg1 , int , arg2 , int , arg3 , int , arg4 , int , arg5 , int , arg6 , int , arg7)
Definition at line 104 of file orxfunction.cpp.
RexxRoutine8()
RexxRoutine8 (int , TestEightIntArgs , int , arg1 , int , arg2 , int , arg3 , int , arg4 , int , arg5 , int , arg6 , int , arg7 , int , arg8)
Definition at line 117 of file orxfunction.cpp.
RexxRoutine9()
RexxRoutine9 (int , TestNineIntArgs , int , arg1 , int , arg2 , int , arg3 , int , arg4 , int , arg5 , int , arg6 , int , arg7 , int , arg8 , int , arg9)
Definition at line 131 of file orxfunction.cpp.
rHandler()
RexxObjectPtr RexxEntry rHandler (RexxExitContext * context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext * ioContext)
Definition at line 540 of file orxfunction.cpp.
Referenced by RexxRoutine2().
Variable Documentation
orxtest_funcs
RexxRoutineEntry orxtest_funcs[]
Definition at line 890 of file orxfunction.cpp.
UnitTest_package_entry
RexxPackageEntry UnitTest_package_entry
Initial value:
= {
    STANDARD_PACKAGE_HEADER
    REXX_INTERPRETER_4_0_0,
    "UnitTest",
    "1.0.0",
    NULL,
    NULL,
    orxtest_funcs,
    NULL
}
Definition at line 964 of file orxfunction.cpp.