ooRexx: orxinstance.cpp File Reference
orxinstance.cpp File Reference
#include "oorexxapi.h"
#include "orxexits.hpp"
Functions
RexxObjectPtr TestGetContextVariable (RexxExitContext *context, size_t argc, RexxObjectPtr *argv)
RexxObjectPtr TestSetContextVariable (RexxExitContext *context, size_t argc, RexxObjectPtr *argv)
RexxObjectPtr TestDropContextVariable (RexxExitContext *context, size_t argc, RexxObjectPtr *argv)
RexxObjectPtr TestGetAllContextVariables (RexxExitContext *context, size_t argc, RexxObjectPtr *argv)
RexxObjectPtr TestGetCallerContext (RexxExitContext *context, size_t argc, RexxObjectPtr *argv)
int invokeExitFunction (RexxExitContext *context, const char *name, PEXIT exitInfo)
int RexxEntry TestContextFunctionExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextCommandExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextQueueExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextSessionIOExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextHaltExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextTraceExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextInitExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextTerminationExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextScriptFunctionExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextObjectFunctionExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextNovalueExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
int RexxEntry TestContextValueExit (RexxExitContext *context, int code, int subcode, PEXIT exitInfo)
RexxObjectPtr RexxEntry TestDirectCommandHandler (RexxExitContext *context, RexxStringObject address, RexxStringObject command)
RexxObjectPtr RexxEntry TestRedirectingCommandHandler (RexxExitContext *context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext *ioContext)
bool REXXENTRY buildContextExitList (InstanceInfo *instanceInfo, RexxContextExit *exitList)
RexxReturnCode REXXENTRY createInstance (InstanceInfo *instanceInfo, RexxInstance *&instance, RexxThreadContext *&threadContext)
void REXXENTRY invokeProgram (InstanceInfo *instanceInfo)
Function Documentation
buildContextExitList()
bool REXXENTRY buildContextExitList (InstanceInfo * instanceInfo, RexxContextExit * exitList)
Definition at line 705 of file orxinstance.cpp.
References InstanceInfo::cmd, counter(), InstanceInfo::exf, InstanceInfo::fnc, _RexxContextExit::handler, InstanceInfo::hlt, InstanceInfo::ini, InstanceInfo::ExitConfig::isEnabled(), InstanceInfo::msq, InstanceInfo::ofnc, RXCMD, RXEXF, RXFNC, RXHLT, RXINI, RXMSQ, RXNOVAL, RXOFNC, RXSIO, RXTER, RXTRC, RXVALUE, InstanceInfo::sio, _RexxContextExit::sysexit_code, InstanceInfo::ter, TestContextCommandExit(), TestContextFunctionExit(), TestContextHaltExit(), TestContextInitExit(), TestContextNovalueExit(), TestContextObjectFunctionExit(), TestContextQueueExit(), TestContextScriptFunctionExit(), TestContextSessionIOExit(), TestContextTerminationExit(), TestContextTraceExit(), TestContextValueExit(), InstanceInfo::trc, InstanceInfo::val, and InstanceInfo::var.
Referenced by createInstance().
createInstance()
RexxReturnCode REXXENTRY createInstance (InstanceInfo * instanceInfo, RexxInstance *& instance, RexxThreadContext *& threadContext)
Definition at line 803 of file orxinstance.cpp.
References APPLICATION_DATA, buildContextExitList(), buildRegisteredExitList(), InstanceInfo::CONTEXT, DIRECT_ENVIRONMENTS, DIRECT_EXITS, InstanceInfo::exitStyle, InstanceInfo::extensionPath, InstanceInfo::extensions, EXTERNAL_CALL_EXTENSIONS, EXTERNAL_CALL_PATH, RexxContextEnvironment::handler, RexxRedirectingEnvironment::handler, INITIAL_ADDRESS_ENVIRONMENT, InstanceInfo::initialAddress, LOAD_REQUIRED_LIBRARY, InstanceInfo::loadLibrary, RexxContextEnvironment::name, RexxRedirectingEnvironment::name, RexxRegisteredEnvironment::name, RexxOption::option, RexxOption::optionName, REDIRECTING_ENVIRONMENTS, registerDllExits(), InstanceInfo::REGISTERED_DLL, REGISTERED_ENVIRONMENTS, InstanceInfo::REGISTERED_EXE, REGISTERED_EXITS, RexxRegisteredEnvironment::registeredName, registerExeExits(), registerSubcomHandler(), RexxCreateInterpreter(), RXNOOFEXITS, TestDirectCommandHandler(), and TestRedirectingCommandHandler().
Referenced by invokeProgram().
invokeExitFunction()
int invokeExitFunction (RexxExitContext * context, const char * name, PEXIT exitInfo)
Definition at line 69 of file orxinstance.cpp.
References NULLOBJECT, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, _RXOFNC_FLAGS::rxfferr, _RXOFNC_FLAGS::rxffnfnd, _RXOFNC_FLAGS::rxffsub, _RXOFNCCAL_PARM::rxfnc_argc, _RXOFNCCAL_PARM::rxfnc_argv, _RXOFNCCAL_PARM::rxfnc_flags, _RXOFNCCAL_PARM::rxfnc_name, _RXOFNCCAL_PARM::rxfnc_retc, TestDropContextVariable(), TestGetAllContextVariables(), TestGetCallerContext(), TestGetContextVariable(), and TestSetContextVariable().
Referenced by TestContextObjectFunctionExit(), and TestContextScriptFunctionExit().
invokeProgram()
void REXXENTRY invokeProgram (InstanceInfo * instanceInfo)
Definition at line 913 of file orxinstance.cpp.
References InstanceInfo::argCount, InstanceInfo::arguments, RexxCondition::code, InstanceInfo::code, createInstance(), deregisterExits(), deregisterSubcomHandler(), NULLOBJECT, InstanceInfo::programName, RexxCondition::rc, InstanceInfo::rc, and InstanceInfo::returnResult.
Referenced by main(), and RexxMethod3().
TestContextCommandExit()
int RexxEntry TestContextCommandExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 188 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::cmd, InstanceInfo::EXIT_ERROR, InstanceInfo::HALT, InstanceInfo::hlt, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, _RXCMDHST_PARM::rxcmd_address, _RXCMDHST_PARM::rxcmd_command, _RXCMDHST_PARM::rxcmd_flags, _RXCMDHST_PARM::rxcmd_retc, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXCMD_FLAGS::rxfcerr, _RXCMD_FLAGS::rxfcfail, InstanceInfo::SKIP, _RXSTRING::strlength, _RXSTRING::strptr, InstanceInfo::TRACEOFF, InstanceInfo::TRACEON, and InstanceInfo::trc.
Referenced by buildContextExitList().
TestContextFunctionExit()
int RexxEntry TestContextFunctionExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 137 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, InstanceInfo::fnc, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXFNC_FLAGS::rxfferr, _RXFNC_FLAGS::rxffnfnd, _RXFNC_FLAGS::rxffsub, _RXFNCCAL_PARM::rxfnc_flags, _RXFNCCAL_PARM::rxfnc_name, _RXFNCCAL_PARM::rxfnc_retc, InstanceInfo::SKIP, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by buildContextExitList().
TestContextHaltExit()
int RexxEntry TestContextHaltExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 399 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, InstanceInfo::HALT, InstanceInfo::hlt, InstanceInfo::NOHALT, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXHLT_FLAGS::rxfhhalt, _RXHLTTST_PARM::rxhlt_flags, and InstanceInfo::SKIP.
Referenced by buildContextExitList().
TestContextInitExit()
int RexxEntry TestContextInitExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 464 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, InstanceInfo::ini, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, and InstanceInfo::SKIP.
Referenced by buildContextExitList().
TestContextNovalueExit()
int RexxEntry TestContextNovalueExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 554 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, InstanceInfo::SKIP, _RXVARNOVALUE_PARM::value, InstanceInfo::var, and _RXVARNOVALUE_PARM::variable_name.
Referenced by buildContextExitList().
TestContextObjectFunctionExit()
int RexxEntry TestContextObjectFunctionExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 536 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, invokeExitFunction(), InstanceInfo::ofnc, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, and InstanceInfo::SKIP.
Referenced by buildContextExitList().
TestContextQueueExit()
int RexxEntry TestContextQueueExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 260 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, InstanceInfo::msq, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXMSQ_FLAGS::rxfmlifo, _RXMSQPSH_PARM::rxmsq_flags, _RXMSQPLL_PARM::rxmsq_retc, _RXMSQSIZ_PARM::rxmsq_size, _RXMSQPSH_PARM::rxmsq_value, RXMSQNAM, RXMSQPLL, RXMSQPSH, RXMSQSIZ, InstanceInfo::SKIP, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by buildContextExitList().
TestContextScriptFunctionExit()
int RexxEntry TestContextScriptFunctionExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 518 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::exf, InstanceInfo::EXIT_ERROR, invokeExitFunction(), InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, and InstanceInfo::SKIP.
Referenced by buildContextExitList().
TestContextSessionIOExit()
int RexxEntry TestContextSessionIOExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 329 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::ALL, InstanceInfo::CONSOLE, InstanceInfo::CONSOLE_DEBUG, InstanceInfo::EXIT_ERROR, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXSIOSAY_PARM::rxsio_string, RXSIODTR, _RXSIODTR_PARM::rxsiodtr_retc, RXSIOSAY, RXSIOTRC, RXSIOTRD, _RXSIOTRD_PARM::rxsiotrd_retc, InstanceInfo::sio, InstanceInfo::SKIP, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by buildContextExitList().
TestContextTerminationExit()
int RexxEntry TestContextTerminationExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 494 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, InstanceInfo::SKIP, and InstanceInfo::ter.
Referenced by buildContextExitList().
TestContextTraceExit()
int RexxEntry TestContextTraceExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 431 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXTRC_FLAGS::rxftrace, _RXTRCTST_PARM::rxtrc_flags, InstanceInfo::SKIP, InstanceInfo::TRACEOFF, InstanceInfo::TRACEON, and InstanceInfo::trc.
Referenced by buildContextExitList().
TestContextValueExit()
int RexxEntry TestContextValueExit (RexxExitContext * context, int code, int subcode, PEXIT exitInfo)
Definition at line 583 of file orxinstance.cpp.
References InstanceInfo::ExitConfig::action, InstanceInfo::EXIT_ERROR, InstanceInfo::RAISE, Rexx_Error_System_service_user_defined, RXEXIT_HANDLED, RXEXIT_NOT_HANDLED, RXEXIT_RAISE_ERROR, _RXVALCALL_PARM::selector, InstanceInfo::SKIP, InstanceInfo::val, _RXVALCALL_PARM::value, and _RXVALCALL_PARM::variable_name.
Referenced by buildContextExitList().
TestDirectCommandHandler()
RexxObjectPtr RexxEntry TestDirectCommandHandler (RexxExitContext * context, RexxStringObject address, RexxStringObject command)
Definition at line 616 of file orxinstance.cpp.
References NULLOBJECT, and Rexx_Error_System_service_user_defined.
Referenced by createInstance().
TestDropContextVariable()
RexxObjectPtr TestDropContextVariable (RexxExitContext * context, size_t argc, RexxObjectPtr * argv)
Definition at line 52 of file orxinstance.cpp.
Referenced by invokeExitFunction().
TestGetAllContextVariables()
RexxObjectPtr TestGetAllContextVariables (RexxExitContext * context, size_t argc, RexxObjectPtr * argv)
Definition at line 58 of file orxinstance.cpp.
Referenced by invokeExitFunction().
TestGetCallerContext()
RexxObjectPtr TestGetCallerContext (RexxExitContext * context, size_t argc, RexxObjectPtr * argv)
Definition at line 63 of file orxinstance.cpp.
Referenced by invokeExitFunction().
TestGetContextVariable()
RexxObjectPtr TestGetContextVariable (RexxExitContext * context, size_t argc, RexxObjectPtr * argv)
Definition at line 41 of file orxinstance.cpp.
Referenced by invokeExitFunction().
TestRedirectingCommandHandler()
RexxObjectPtr RexxEntry TestRedirectingCommandHandler (RexxExitContext * context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext * ioContext)
Definition at line 652 of file orxinstance.cpp.
References NULLOBJECT, and Rexx_Error_System_service_user_defined.
Referenced by createInstance().
TestSetContextVariable()
RexxObjectPtr TestSetContextVariable (RexxExitContext * context, size_t argc, RexxObjectPtr * argv)
Definition at line 46 of file orxinstance.cpp.
Referenced by invokeExitFunction().