ooRexx: rexxpaws.cpp File Reference
rexxpaws.cpp File Reference
#include <windows.h>
#include <oorexxapi.h>
#include <malloc.h>
#include <stdio.h>
#include <string.h>
#include "ArgumentParser.h"
Functions
int __cdecl main (int argc, char *argv[])
LONG REXXENTRY MY_IOEXIT (LONG ExitNumber, LONG Subfunction, PEXIT ParmBlock)
static void __cdecl do_pause_at_exit (void)
void __cdecl set_pause_at_exit (void)
Function Documentation
do_pause_at_exit()
static void __cdecl do_pause_at_exit (void) static
Definition at line 63 of file rexxpaws.cpp.
Referenced by set_pause_at_exit().
main()
int __cdecl main (int argc, char * argv[])
Definition at line 79 of file rexxpaws.cpp.
References RexxCreateInterpreter(), and set_pause_at_exit().
MY_IOEXIT()
LONG REXXENTRY MY_IOEXIT (LONG ExitNumber, LONG Subfunction, PEXIT ParmBlock)
set_pause_at_exit()
void __cdecl set_pause_at_exit (void)
Definition at line 71 of file rexxpaws.cpp.
References do_pause_at_exit().
Referenced by main().