ooRexx: rexxhide.cpp File Reference
rexxhide.cpp File Reference
#include <windows.h>
#include <oorexxapi.h>
#include <malloc.h>
#include <string.h>
#include <stdio.h>
#include <io.h>
#include <time.h>
#include "ArgumentParser.h"
Functions
int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Function Documentation
WinMain()
int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Definition at line 58 of file rexxhide.cpp.
References RexxCondition::code, CommandLineToArgvA(), RexxCondition::errortext, getArguments(), RexxCondition::message, RexxCondition::position, RexxCondition::program, RexxCondition::rc, RexxCreateInterpreter(), _CONSTRXSTRING::strlength, and _CONSTRXSTRING::strptr.