ooRexx: rxsock.h File Reference
rxsock.h File Reference
#include "oorexxapi.h"
Classes
class StemManager
Typedefs
typedef struct sockaddr_in sockaddr_in
typedef struct in_addr in_addr
Functions
void stripBlanks (char *string)
void stemToIntArray (RexxCallContext *context, RexxObjectPtr stem, int &count, int *&arr)
void intArrayToStem (RexxCallContext *context, RexxObjectPtr stem, int count, int *arr)
void stemToSockAddr (RexxCallContext *context, StemManager &stem, sockaddr_in *pSockAddr)
void sockAddrToStem (RexxCallContext *context, sockaddr_in *pSockAddr, StemManager &stem)
void hostEntToStem (RexxCallContext *context, struct hostent *pHostEnt, StemManager &stem)
int stringToSockOpt (const char *pszOptName)
void setErrno (RexxCallContext *context, bool noError)
int caselessCompare (const char *op1, const char *op2)
Typedef Documentation
in_addr
typedef struct in_addr in_addr
Definition at line 1 of file rxsock.h.
sockaddr_in
typedef struct sockaddr_in sockaddr_in
Definition at line 1 of file rxsock.h.
Function Documentation
caselessCompare()
int caselessCompare (const char * op1, const char * op2)
Definition at line 102 of file rxsock.cpp.
Referenced by RexxRoutine3(), RexxRoutine4(), RexxRoutine5(), stemToSockAddr(), and stringToSockOpt().
hostEntToStem()
void hostEntToStem (RexxCallContext * context, struct hostent * pHostEnt, StemManager & stem)
Definition at line 358 of file rxsock.cpp.
References StemManager::setValue().
Referenced by RexxRoutine2(), and RexxRoutine3().
intArrayToStem()
void intArrayToStem (RexxCallContext * context, RexxObjectPtr stem, int count, int * arr)
Definition at line 226 of file rxsock.cpp.
References StemManager::resolveStem(), and StemManager::setValue().
Referenced by RexxRoutine4().
setErrno()
void setErrno (RexxCallContext * context, bool noError)
Definition at line 447 of file rxsock.cpp.
Referenced by RexxRoutine0(), RexxRoutine1(), RexxRoutine2(), RexxRoutine3(), RexxRoutine4(), and RexxRoutine5().
sockAddrToStem()
void sockAddrToStem (RexxCallContext * context, sockaddr_in * pSockAddr, StemManager & stem)
Definition at line 337 of file rxsock.cpp.
References StemManager::setValue().
Referenced by RexxRoutine2(), and RexxRoutine5().
stemToIntArray()
void stemToIntArray (RexxCallContext * context, RexxObjectPtr stem, int & count, int *& arr)
Definition at line 167 of file rxsock.cpp.
References StemManager::getValue(), NULLOBJECT, and StemManager::resolveStem().
Referenced by RexxRoutine4().
stemToSockAddr()
void stemToSockAddr (RexxCallContext * context, StemManager & stem, sockaddr_in * pSockAddr)
Definition at line 255 of file rxsock.cpp.
References caselessCompare(), getStemElement(), and stripBlanks().
Referenced by RexxRoutine2(), RexxRoutine4(), and RexxRoutine5().
stringToSockOpt()
int stringToSockOpt (const char * pszOptName)
Definition at line 416 of file rxsock.cpp.
References caselessCompare(), and SO_USELOOPBACK.
Referenced by RexxRoutine4().
stripBlanks()
void stripBlanks (char * string)
Definition at line 118 of file rxsock.cpp.
Referenced by RexxRoutine3(), and stemToSockAddr().