ooRexx: SysFileSystem.cpp File Reference
unix/SysFileSystem.cpp File Reference
#include "RexxCore.h"
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <utime.h>
#include <pwd.h>
#include <errno.h>
#include <fnmatch.h>
#include "SysFileSystem.hpp"
#include "Utilities.hpp"
#include "ActivityManager.hpp"
#include "FileNameBuffer.hpp"
Functions
bool utcToLocal (time_t utc, int64_t *loc)
bool localToUtc (int64_t loc, time_t *utc)
bool samePaths (const char *path1, const char *path2)
int copyFileDereferenceSymbolicLinks (const char *fromFile, const char *toFile, bool preserveTimestamps, bool preserveMode)
char * temporaryFilename (const char *filename, int &errInfo)
int copyFileDontDereferenceSymbolicLinks (const char *fromFile, const char *toFile, bool force, bool preserveTimestamps, bool preserveMode)
Variables
const int64_t StatEpoch = 62135596800
const int64_t NoTimeStamp = -999999999999999999
Function Documentation
copyFileDereferenceSymbolicLinks()
int copyFileDereferenceSymbolicLinks (const char * fromFile, const char * toFile, bool preserveTimestamps, bool preserveMode)
Copy a file to another file location with dereferencing of symbolic links. If the source file is a symbolic link, the actual file copied is the target of the symbolic link. If the destination file already exists and is a symbolic link, the target of the symbolic link is overwritten by the source file. If the destination file does not exist then it is created with the access mode of the source file (if possible).
Parameters
fromFile The file we're copying from.
toFile The file we're copying to
preserveTimestamps if true, the copied file will have the same timestamps.
preserveMode If true, the file modes are preserved in the new file.
Returns
0 if successful, or an error code for any failure.
Definition at line 1467 of file unix/SysFileSystem.cpp.
References AutoClose::close(), and samePaths().
Referenced by SysFileSystem::copyFile(), and copyFileDontDereferenceSymbolicLinks().
copyFileDontDereferenceSymbolicLinks()
int copyFileDontDereferenceSymbolicLinks (const char * fromFile, const char * toFile, bool force, bool preserveTimestamps, bool preserveMode)
Copy a file without dereferencing the symbolic links. If the source file is a symbolic link, the actual file copied is the symbolic link itself. If the destination file already exists and is a symbolic link, the target of the symbolic link is not overwritten by the source file.
again, the source and the target cannot be the same
Parameters
fromFile The file to copy from.
toFile The file to copy to
force Force the rename if the target exists as a symbolic link
preserveTimestamps preserve the time stamps (if possible)
preserveMode Preserve the file mode (if possible)
Returns
0 if successful, or the appropriate error code.
Definition at line 1610 of file unix/SysFileSystem.cpp.
References copyFileDereferenceSymbolicLinks(), samePaths(), and temporaryFilename().
Referenced by SysFileSystem::moveFile().
localToUtc()
bool localToUtc (int64_t loc, time_t * utc)
helper function to convert local time to UTC time.
Parameters
time Local time in microseconds since 0001-01-01T00:00:00.
utc Calendar time (UTC) in seconds elapsed since 1970-01-01T00:00:00Z.
Returns
true if local time can be converted to UTC, false otherwise.
Definition at line 976 of file unix/SysFileSystem.cpp.
References StatEpoch.
Referenced by SysFileSystem::setLastAccessDate(), and SysFileSystem::setLastModifiedDate().
samePaths()
bool samePaths (const char * path1, const char * path2)
Check to see if two paths are identical
Parameters
path1 The the first path to check
path2 The second path to check.
Returns
true if these paths map to the same existing file, false if they are distinct.
Definition at line 1421 of file unix/SysFileSystem.cpp.
References SysFileSystem::isCaseSensitive().
Referenced by copyFileDereferenceSymbolicLinks(), copyFileDontDereferenceSymbolicLinks(), and SysFileSystem::moveFile().
temporaryFilename()
char* temporaryFilename (const char * filename, int & errInfo)
Definition at line 1551 of file unix/SysFileSystem.cpp.
References SysFileSystem::fileExists().
Referenced by copyFileDontDereferenceSymbolicLinks(), and SysFileSystem::moveFile().
utcToLocal()
bool utcToLocal (time_t utc, int64_t * loc)
helper function to convert UTC time to local time.
Parameters
utc Calendar time (UTC) in seconds elapsed since 1970-01-01T00:00:00Z.
loc Local time in microseconds since 0001-01-01T00:00:00.
Returns
true if local time can be converted to UTC, false otherwise.
Definition at line 927 of file unix/SysFileSystem.cpp.
References if(), and StatEpoch.
Referenced by SysFileSystem::getLastAccessDate(), and SysFileSystem::getLastModifiedDate().
Variable Documentation
NoTimeStamp
const int64_t NoTimeStamp = -999999999999999999
Definition at line 80 of file unix/SysFileSystem.cpp.
Referenced by SysFileSystem::getLastAccessDate(), and SysFileSystem::getLastModifiedDate().
StatEpoch
const int64_t StatEpoch = 62135596800
Definition at line 79 of file unix/SysFileSystem.cpp.
Referenced by localToUtc(), and utcToLocal().