ooRexx: rexxapi3.c File Reference
unix/rexxapi3/rexxapi3.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <rexx.h>
Macros
#define INVALID_ROUTINE 40 /* Raise Rexx error */
#define VALID_ROUTINE 0 /* Successful completion */
Functions
RexxReturnCode REXXENTRY ApiLoadFuncs3 (const char *name, size_t numargs, CONSTRXSTRING args[], const char *queuename, PRXSTRING retstr)
RexxReturnCode REXXENTRY ApiDeregFunc3 (const char *name, size_t numargs, CONSTRXSTRING args[], const char *queuename, PRXSTRING retstr)
RexxReturnCode REXXENTRY Api_Read_All_Variables_From_REXX_VP (const char *name, size_t numargs, CONSTRXSTRING args[], const char *queuename, PRXSTRING retstr)
RexxReturnCode REXXENTRY Api_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP (const char *name, size_t numargs, CONSTRXSTRING args[], const char *queuename, PRXSTRING retstr)
Variables
static const char * ApiFncTable []
Macro Definition Documentation
INVALID_ROUTINE
#define INVALID_ROUTINE 40 /* Raise Rexx error */
Definition at line 58 of file unix/rexxapi3/rexxapi3.c.
VALID_ROUTINE
#define VALID_ROUTINE 0 /* Successful completion */
Definition at line 59 of file unix/rexxapi3/rexxapi3.c.
Function Documentation
Api_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP()
RexxReturnCode REXXENTRY Api_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP (const char * name, size_t numargs, CONSTRXSTRING args[], const char * queuename, PRXSTRING retstr)
Definition at line 265 of file unix/rexxapi3/rexxapi3.c.
References INVALID_ROUTINE, RexxFreeMemory(), RexxVariablePool(), RXSHV_LVAR, RXSHV_MEMFL, RXSHV_SYFET, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnext, _SHVBLOCK::shvvalue, _RXSTRING::strlength, _RXSTRING::strptr, and VALID_ROUTINE.
Api_Read_All_Variables_From_REXX_VP()
RexxReturnCode REXXENTRY Api_Read_All_Variables_From_REXX_VP (const char * name, size_t numargs, CONSTRXSTRING args[], const char * queuename, PRXSTRING retstr)
Definition at line 165 of file unix/rexxapi3/rexxapi3.c.
References INVALID_ROUTINE, RexxFreeMemory(), RexxVariablePool(), RXSHV_LVAR, RXSHV_MEMFL, RXSHV_NEXTV, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _RXSTRING::strlength, _RXSTRING::strptr, and VALID_ROUTINE.
ApiDeregFunc3()
RexxReturnCode REXXENTRY ApiDeregFunc3 (const char * name, size_t numargs, CONSTRXSTRING args[], const char * queuename, PRXSTRING retstr)
Definition at line 121 of file unix/rexxapi3/rexxapi3.c.
References ApiFncTable, INVALID_ROUTINE, RexxDeregisterFunction(), _RXSTRING::strlength, and VALID_ROUTINE.
ApiLoadFuncs3()
RexxReturnCode REXXENTRY ApiLoadFuncs3 (const char * name, size_t numargs, CONSTRXSTRING args[], const char * queuename, PRXSTRING retstr)
Definition at line 90 of file unix/rexxapi3/rexxapi3.c.
References ApiFncTable, RexxRegisterFunctionDll(), and VALID_ROUTINE.
Variable Documentation
ApiFncTable
const char* ApiFncTable[] static
Initial value:
=
   {
      "Api_Exchange_Data",
      "ApiDeregFunc3",
      "Api_Read_All_Variables_From_REXX_VP",
      "Api_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP"
   }
Definition at line 71 of file unix/rexxapi3/rexxapi3.c.
Referenced by ApiDeregFunc3(), and ApiLoadFuncs3().