ooRexx: SystemCommands.cpp File Reference
unix/SystemCommands.cpp File Reference
#include <string.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <spawn.h>
#include "RexxCore.h"
#include "StringClass.hpp"
#include "Activity.hpp"
#include "ActivityManager.hpp"
#include "SystemInterpreter.hpp"
#include "InterpreterInstance.hpp"
#include "SysInterpreterInstance.hpp"
#include "SysThread.hpp"
#include "RexxInternalApis.h"
#include <sys/types.h>
#include <pwd.h>
#include <limits.h>
#include <errno.h>
Classes
class InputWriterThread
class ErrorReaderThread
Macros
#define SYSINITIALADDRESS "sh"
#define MAX_COMMAND_ARGS 400
#define UNKNOWN_COMMAND 127 /* unknown command return code */
#define EXPORT_FLAG 1
#define SET_FLAG 2
#define UNSET_FLAG 3
#define MAX_VALUE 1280
Functions
bool sys_process_export (RexxExitContext *context, const char *cmd, RexxObjectPtr &rc, int flag)
char * unquote (const char *s)
bool sys_process_cd (RexxExitContext *context, const char *cmd, RexxObjectPtr rc)
bool scan_cmd (const char *parm_cmd, char **argPtr)
logical_t handleCommandInternally (RexxExitContext *context, char *cmd, RexxObjectPtr rc)
RexxObjectPtr ErrorRedirection (RexxExitContext *context, int errCode)
RexxObjectPtr ErrorFailure (RexxExitContext *context, CSTRING commandString)
RexxObjectPtr RexxEntry ioCommandHandler (RexxExitContext *context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext *ioContext)
Variables
int putflag
Macro Definition Documentation
EXPORT_FLAG
#define EXPORT_FLAG 1
Definition at line 73 of file unix/SystemCommands.cpp.
MAX_COMMAND_ARGS
#define MAX_COMMAND_ARGS 400
Definition at line 70 of file unix/SystemCommands.cpp.
MAX_VALUE
#define MAX_VALUE 1280
Definition at line 76 of file unix/SystemCommands.cpp.
SET_FLAG
#define SET_FLAG 2
Definition at line 74 of file unix/SystemCommands.cpp.
SYSINITIALADDRESS
#define SYSINITIALADDRESS "sh"
Definition at line 68 of file unix/SystemCommands.cpp.
UNKNOWN_COMMAND
#define UNKNOWN_COMMAND 127 /* unknown command return code */
Definition at line 71 of file unix/SystemCommands.cpp.
UNSET_FLAG
#define UNSET_FLAG 3
Definition at line 75 of file unix/SystemCommands.cpp.
Function Documentation
ErrorFailure()
RexxObjectPtr ErrorFailure (RexxExitContext * context, CSTRING commandString)
Raises a FAILURE condition.
Parameters
context The Exit context.
command The command name and arguments.
Definition at line 801 of file unix/SystemCommands.cpp.
References NULLOBJECT, and UNKNOWN_COMMAND.
Referenced by ioCommandHandler().
ErrorRedirection()
RexxObjectPtr ErrorRedirection (RexxExitContext * context, int errCode)
Raises syntax error 98.923 Address command redirection failed.
Parameters
context The Exit context.
errCode The operating system error code.
Definition at line 787 of file unix/SystemCommands.cpp.
References Error_Execution_address_redirection_failed, and NULLOBJECT.
Referenced by ioCommandHandler().
handleCommandInternally()
logical_t handleCommandInternally (RexxExitContext * context, char * cmd, RexxObjectPtr rc)
Try to handle special commands like "cd" or "export" internally. This will work if we have a simple commend with no redirection, piping, or such.
Parameters
context The Exit oontext.
cmd The command string.
rc The operating system return code.
Returns
True if command was handled, false otherwise.
Definition at line 721 of file unix/SystemCommands.cpp.
References EXPORT_FLAG, SET_FLAG, sys_process_cd(), sys_process_export(), and UNSET_FLAG.
Referenced by ioCommandHandler().
ioCommandHandler()
RexxObjectPtr RexxEntry ioCommandHandler (RexxExitContext * context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext * ioContext)
A redirecting test command handler.
Parameters
context The Exit context.
address The environment name.
command The command name and arguments.
ioContext The IO Redirector context.
Definition at line 817 of file unix/SystemCommands.cpp.
References InputWriterThread::bufferLength, ErrorReaderThread::bufferLength, InputWriterThread::error, ErrorReaderThread::error, ErrorReaderThread::errorBuffer, ErrorFailure(), ErrorRedirection(), getEnvironment(), handleCommandInternally(), InputWriterThread::inputBuffer, MAX_COMMAND_ARGS, NULLOBJECT, scan_cmd(), InputWriterThread::start(), ErrorReaderThread::start(), Utilities::strCaselessCompare(), Utilities::strlower(), SYSSHELLPATH, UNKNOWN_COMMAND, and SysThread::waitForTermination().
Referenced by SysInterpreterInstance::registerCommandHandlers().
scan_cmd()
bool scan_cmd (const char * parm_cmd, char ** argPtr)
Breaks up a command string into whitespace-delimited pieces. Whitespace- delimited double-quoted strings are treated as a single argument.
Parameters
parm_cmd The command string.
argPtr The "argv" array.
Returns
True if command parsed successfully, else false.
Definition at line 638 of file unix/SystemCommands.cpp.
References MAX_COMMAND_ARGS.
Referenced by ioCommandHandler().
sys_process_cd()
bool sys_process_cd (RexxExitContext * context, const char * cmd, RexxObjectPtr rc)
Definition at line 494 of file unix/SystemCommands.cpp.
References unquote().
Referenced by handleCommandInternally().
sys_process_export()
bool sys_process_export (RexxExitContext * context, const char * cmd, RexxObjectPtr & rc, int flag)
Definition at line 201 of file unix/SystemCommands.cpp.
References EXPORT_FLAG, getEnvironment(), MAX_VALUE, putflag, SET_FLAG, and UNSET_FLAG.
Referenced by handleCommandInternally().
unquote()
char* unquote (const char * s)
Definition at line 455 of file unix/SystemCommands.cpp.
Referenced by sys_process_cd().
Variable Documentation
putflag
int putflag extern
Definition at line 90 of file unix/ExternalFunctions.cpp.
Referenced by SystemInterpreter::restoreEnvironment(), and sys_process_export().