ooRexx: APIService.cpp File Reference
unix/APIService.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <signal.h>
#include <pwd.h>
#include <errno.h>
#include "APIServer.hpp"
#include "SysCSStream.hpp"
Functions
void Stop (int signo)
int acquireLock (const char *lockFileName)
void releaseLock (const char *lockFileName, int lockFd)
int main (int argc, char *argv[])
Variables
APIServer apiServer
Function Documentation
acquireLock()
int acquireLock (const char * lockFileName)
Acquire a lock on a special file to ensure we are the only running rxapi process for this user.
Returns
The file descriptor for the lock file or -1 for any failure obtaining the lock.
Definition at line 79 of file unix/APIService.cpp.
Referenced by main().
main()
int main (int argc, char * argv[])
The rxapi main entry point.
Parameters
argc The command line arguments
argv The arguments
Returns
The completion return code.
Definition at line 124 of file unix/APIService.cpp.
References acquireLock(), apiServer, SysServerLocalSocketConnectionManager::bind(), SysServerLocalSocketConnectionManager::generateServiceName(), SysServerLocalSocketConnectionManager::getServiceLocation(), APIServer::initServer(), APIServer::listenForConnections(), releaseLock(), Stop(), and APIServer::terminateServer().
releaseLock()
void releaseLock (const char * lockFileName, int lockFd)
Release the lock on the lock file.
Parameters
lockFileName The name of the lock file.
lockFd The file descriptor of the file.
Definition at line 106 of file unix/APIService.cpp.
Referenced by main().
Stop()
void Stop (int signo)
Handle a server stop request
Parameters
signo The signal number (not used)
Definition at line 64 of file unix/APIService.cpp.
References apiServer, and APIServer::terminateServer().
Referenced by main().
Variable Documentation
apiServer
APIServer apiServer
Definition at line 55 of file unix/APIService.cpp.
Referenced by main(), and Stop().