ooRexx: SysRexxUtil.cpp File Reference
unix/SysRexxUtil.cpp File Reference
#include "oorexxapi.h"
#include <sys/wait.h>
#include <sys/ipc.h>
#include <memory.h>
#include <fcntl.h>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <limits.h>
#include <math.h>
#include <sys/stat.h>
#include <errno.h>
#include <stddef.h>
#include <sys/types.h>
#include <sys/utsname.h>
#include <pthread.h>
#include <semaphore.h>
#include <signal.h>
#include <time.h>
#include <netdb.h>
#include <dirent.h>
#include <sys/time.h>
#include <utime.h>
#include <termios.h>
#include <fnmatch.h>
#include <libgen.h>
#include "RexxUtilCommon.hpp"
#include "Utilities.hpp"
#include "RexxInternalApis.h"
Classes
struct RxSemData
Macros
#define REXXMESSAGEFILE "rexx.cat"
#define ERROR_NOMEM "2" /* Insufficient memory */
#define stty(a, b) (void)tcsetattr(a,TCSANOW,b) /* simple set attr. */
#define gtty(a, b) (void)tcgetattr(a,b) /* simple get attr. */
#define discard_input(a) tcflush(a,TCIFLUSH) /* simple flush */
#define restore_tty(a) stty(ttyfd,a) /* new settings STDIN */
#define SEM_WAIT_PERIOD 100 /* POSIX says this should be 10ms */
Typedefs
typedef struct RxSemData RXSEMDATA
Functions
void restore_terminal (int signal)
int getkey (char *ret, bool echo)
char typeOfEntry (mode_t m)
void formatFileAttributes (TreeFinder *finder, FileNameBuffer &foundFileLine, SysFileIterator::FileAttributes &attributes)
RexxRoutine0 (int, SysCls)
RexxRoutine2 (int, SysMkDir, CSTRING, path, OPTIONAL_int32_t, mode)
RexxRoutine0 (RexxStringObject, SysVersion)
RexxRoutine2 (RexxObjectPtr, SysCreateEventSem, OPTIONAL_CSTRING, name, OPTIONAL_CSTRING, reset)
RexxRoutine1 (uintptr_t, SysOpenEventSem, CSTRING, name)
RexxRoutine1 (int, SysResetEventSem, uintptr_t, vhandle)
RexxRoutine1 (int, SysPostEventSem, uintptr_t, vhandle)
RexxRoutine1 (int, SysCloseEventSem, uintptr_t, vhandle)
RexxRoutine2 (int, SysWaitEventSem, uintptr_t, vhandle, OPTIONAL_int, timeout)
RexxRoutine1 (RexxObjectPtr, SysCreateMutexSem, OPTIONAL_CSTRING, name)
RexxRoutine1 (uintptr_t, SysOpenMutexSem, CSTRING, name)
RexxRoutine2 (int, SysRequestMutexSem, uintptr_t, vhandle, OPTIONAL_int, timeout)
RexxRoutine1 (int, SysReleaseMutexSem, uintptr_t, vhandle)
RexxRoutine1 (int, SysCloseMutexSem, uintptr_t, vhandle)
RexxRoutine2 (int, SysSetPriority, OPTIONAL_int32_t, cls, int32_t, prio)
char * getErrorMessage (const char *repository, int setnum, int msgnum)
RexxRoutine3 (RexxStringObject, SysGetMessage, positive_wholenumber_t, msgnum, OPTIONAL_CSTRING, msgfile, ARGLIST, args)
RexxRoutine4 (RexxStringObject, SysGetMessageX, positive_wholenumber_t, setnum, positive_wholenumber_t, msgnum, OPTIONAL_CSTRING, msgfile, ARGLIST, args)
RexxRoutine1 (RexxStringObject, SysGetKey, OPTIONAL_CSTRING, echoArg)
RexxRoutine0 (int, SysFork)
RexxRoutine0 (int, SysWait)
RexxRoutine1 (RexxStringObject, SysCreatePipe, OPTIONAL_CSTRING, blocking)
RexxRoutine2 (RexxObjectPtr, SysGetFileDateTime, CSTRING, file, OPTIONAL_CSTRING, timesel)
RexxRoutine3 (int, SysSetFileDateTime, CSTRING, filename, OPTIONAL_CSTRING, newdateSet, OPTIONAL_CSTRING, newtimeSet)
RexxRoutine1 (RexxObjectPtr, SysQueryProcess, OPTIONAL_CSTRING, selector)
RexxRoutine1 (RexxStringObject, SysGetErrorText, int32_t, errnum)
Variables
struct termios in_orig
Macro Definition Documentation
discard_input
#define discard_input (a) tcflush(a,TCIFLUSH) /* simple flush */
Definition at line 190 of file unix/SysRexxUtil.cpp.
ERROR_NOMEM
#define ERROR_NOMEM "2" /* Insufficient memory */
Definition at line 182 of file unix/SysRexxUtil.cpp.
gtty
#define gtty (a, b) (void)tcgetattr(a,b) /* simple get attr. */
Definition at line 189 of file unix/SysRexxUtil.cpp.
restore_tty
#define restore_tty (a) stty(ttyfd,a) /* new settings STDIN */
Definition at line 191 of file unix/SysRexxUtil.cpp.
REXXMESSAGEFILE
#define REXXMESSAGEFILE "rexx.cat"
Definition at line 175 of file unix/SysRexxUtil.cpp.
SEM_WAIT_PERIOD
#define SEM_WAIT_PERIOD 100 /* POSIX says this should be 10ms */
Definition at line 800 of file unix/SysRexxUtil.cpp.
stty
#define stty (a, b) (void)tcsetattr(a,TCSANOW,b) /* simple set attr. */
Definition at line 188 of file unix/SysRexxUtil.cpp.
Typedef Documentation
RXSEMDATA
typedef struct RxSemData RXSEMDATA
Function Documentation
formatFileAttributes()
void formatFileAttributes (TreeFinder * finder, FileNameBuffer & foundFileLine, SysFileIterator::FileAttributes & attributes)
Format the system-specific file time, attribute mask, and size for the given file.
Parameters
fileName The name of the file.
Definition at line 382 of file unix/SysRexxUtil.cpp.
References TreeFinder::editableTime(), SysFileIterator::FileAttributes::findFileData, TreeFinder::longSize(), TreeFinder::longTime(), and typeOfEntry().
Referenced by TreeFinder::checkFile().
getErrorMessage()
char* getErrorMessage (const char * repository, int setnum, int msgnum)
Retrieve an error message from the repository
Parameters
repository The named repository (can be null, which means retrieve the rexx error message)
setnum The setnumber in the catalog to use
msgnum The target message number
Returns
The error message text or NULL if not found.
Definition at line 1107 of file unix/SysRexxUtil.cpp.
References RexxGetErrorMessageByNumber(), and REXXMESSAGEFILE.
Referenced by RexxRoutine3(), and RexxRoutine4().
getkey()
int getkey (char * ret, bool echo)
Definition at line 216 of file unix/SysRexxUtil.cpp.
References gtty, in_orig, restore_terminal(), restore_tty, and stty.
Referenced by RexxRoutine1().
restore_terminal()
void restore_terminal (int signal)
Definition at line 204 of file unix/SysRexxUtil.cpp.
References in_orig, and stty.
Referenced by getkey().
RexxRoutine0() [1/4]
RexxRoutine0 (int , SysCls)
Definition at line 562 of file unix/SysRexxUtil.cpp.
RexxRoutine0() [2/4]
RexxRoutine0 (int , SysFork)
Definition at line 1252 of file unix/SysRexxUtil.cpp.
RexxRoutine0() [3/4]
RexxRoutine0 (int , SysWait)
Definition at line 1267 of file unix/SysRexxUtil.cpp.
RexxRoutine0() [4/4]
RexxRoutine0 (RexxStringObject , SysVersion)
Definition at line 598 of file unix/SysRexxUtil.cpp.
References NULLOBJECT.
RexxRoutine1() [1/12]
RexxRoutine1 (int , SysCloseEventSem , uintptr_t , vhandle)
Definition at line 761 of file unix/SysRexxUtil.cpp.
References RxSemData::handle, and RxSemData::named.
RexxRoutine1() [2/12]
RexxRoutine1 (int , SysCloseMutexSem , uintptr_t , vhandle)
Definition at line 1038 of file unix/SysRexxUtil.cpp.
References RxSemData::handle, and RxSemData::named.
RexxRoutine1() [3/12]
RexxRoutine1 (int , SysPostEventSem , uintptr_t , vhandle)
Definition at line 737 of file unix/SysRexxUtil.cpp.
References RxSemData::handle.
RexxRoutine1() [4/12]
RexxRoutine1 (int , SysReleaseMutexSem , uintptr_t , vhandle)
Definition at line 997 of file unix/SysRexxUtil.cpp.
References RxSemData::handle.
RexxRoutine1() [5/12]
RexxRoutine1 (int , SysResetEventSem , uintptr_t , vhandle)
Definition at line 718 of file unix/SysRexxUtil.cpp.
References RxSemData::handle.
RexxRoutine1() [6/12]
RexxRoutine1 (RexxObjectPtr , SysCreateMutexSem , OPTIONAL_CSTRING , name)
Definition at line 868 of file unix/SysRexxUtil.cpp.
References RxSemData::handle, and RxSemData::named.
RexxRoutine1() [7/12]
RexxRoutine1 (RexxObjectPtr , SysQueryProcess , OPTIONAL_CSTRING , selector)
Definition at line 1472 of file unix/SysRexxUtil.cpp.
References NULLOBJECT.
RexxRoutine1() [8/12]
RexxRoutine1 (RexxStringObject , SysCreatePipe , OPTIONAL_CSTRING , blocking)
Definition at line 1285 of file unix/SysRexxUtil.cpp.
References invalidOptionException().
RexxRoutine1() [9/12]
RexxRoutine1 (RexxStringObject , SysGetErrorText , int32_t , errnum)
Definition at line 1620 of file unix/SysRexxUtil.cpp.
RexxRoutine1() [10/12]
RexxRoutine1 (RexxStringObject , SysGetKey , OPTIONAL_CSTRING , echoArg)
Definition at line 1220 of file unix/SysRexxUtil.cpp.
References getkey(), and invalidOptionException().
RexxRoutine1() [11/12]
RexxRoutine1 (uintptr_t , SysOpenEventSem , CSTRING , name)
Definition at line 689 of file unix/SysRexxUtil.cpp.
References RxSemData::handle, and RxSemData::named.
RexxRoutine1() [12/12]
RexxRoutine1 (uintptr_t , SysOpenMutexSem , CSTRING , name)
Definition at line 916 of file unix/SysRexxUtil.cpp.
References RxSemData::handle, and RxSemData::named.
RexxRoutine2() [1/6]
RexxRoutine2 (int , SysMkDir , CSTRING , path , OPTIONAL_int32_t , mode)
SysMkDir creates a directory. No intermediate directories are created.
Parameters
path The directory path.
mode Optional file mode. Valid values are 0 .. 511.
Returns
zero if the directory was created successfully, else errno.
Definition at line 576 of file unix/SysRexxUtil.cpp.
References argumentOmitted.
RexxRoutine2() [2/6]
RexxRoutine2 (int , SysRequestMutexSem , uintptr_t , vhandle , OPTIONAL_int , timeout)
Definition at line 945 of file unix/SysRexxUtil.cpp.
References RxSemData::handle, and SEM_WAIT_PERIOD.
RexxRoutine2() [3/6]
RexxRoutine2 (int , SysSetPriority , OPTIONAL_int32_t , cls , int32_t , prio)
Definition at line 1092 of file unix/SysRexxUtil.cpp.
RexxRoutine2() [4/6]
RexxRoutine2 (int , SysWaitEventSem , uintptr_t , vhandle , OPTIONAL_int , timeout)
Definition at line 813 of file unix/SysRexxUtil.cpp.
References RxSemData::handle, and SEM_WAIT_PERIOD.
RexxRoutine2() [5/6]
RexxRoutine2 (RexxObjectPtr , SysCreateEventSem , OPTIONAL_CSTRING , name , OPTIONAL_CSTRING , reset)
Definition at line 642 of file unix/SysRexxUtil.cpp.
References RxSemData::handle, and RxSemData::named.
RexxRoutine2() [6/6]
RexxRoutine2 (RexxObjectPtr , SysGetFileDateTime , CSTRING , file , OPTIONAL_CSTRING , timesel)
Definition at line 1344 of file unix/SysRexxUtil.cpp.
References invalidOptionException().
RexxRoutine3() [1/2]
RexxRoutine3 (int , SysSetFileDateTime , CSTRING , filename , OPTIONAL_CSTRING , newdateSet , OPTIONAL_CSTRING , newtimeSet)
Definition at line 1400 of file unix/SysRexxUtil.cpp.
RexxRoutine3() [2/2]
RexxRoutine3 (RexxStringObject , SysGetMessage , positive_wholenumber_t , msgnum , OPTIONAL_CSTRING , msgfile , ARGLIST , args)
Definition at line 1169 of file unix/SysRexxUtil.cpp.
References formatMessage(), and getErrorMessage().
RexxRoutine4()
RexxRoutine4 (RexxStringObject , SysGetMessageX , positive_wholenumber_t , setnum , positive_wholenumber_t , msgnum , OPTIONAL_CSTRING , msgfile , ARGLIST , args)
Definition at line 1198 of file unix/SysRexxUtil.cpp.
References formatMessage(), and getErrorMessage().
typeOfEntry()
char typeOfEntry (mode_t m) inline
Definition at line 283 of file unix/SysRexxUtil.cpp.
Referenced by formatFileAttributes().
Variable Documentation
in_orig
struct termios in_orig
Definition at line 1 of file unix/SysRexxUtil.cpp.
Referenced by getkey(), and restore_terminal().