ooRexx: SysSemaphore.cpp File Reference
unix/SysSemaphore.cpp File Reference
#include <pthread.h>
#include <memory.h>
#include <stdio.h>
#include <sys/time.h>
#include <algorithm>
#include <errno.h>
#include "SysSemaphore.hpp"
Macros
#define TIMESLICE 10000000L
Functions
bool checkTimeOut (const struct timespec *ts, long &nextInterval)
int pthread_mutex_timedlock (pthread_mutex_t *mutex, const struct timespec *abs_timeout)
Macro Definition Documentation
TIMESLICE
#define TIMESLICE 10000000L
Definition at line 63 of file unix/SysSemaphore.cpp.
Function Documentation
checkTimeOut()
bool checkTimeOut (const struct timespec * ts, long & nextInterval)
Check to see if we have gone beyond the appointed time.
Parameters
ts The target time
nextInterval The return next wait interval if this still has not timed out.
Returns
true if we have gone beyond the target time, false otherwise.
Definition at line 74 of file unix/SysSemaphore.cpp.
References TIMESLICE.
Referenced by pthread_mutex_timedlock().
pthread_mutex_timedlock()
int pthread_mutex_timedlock (pthread_mutex_t * mutex, const struct timespec * abs_timeout)
Fix for systems that don't have pthread_mutex_timedlock
Parameters
mutex The mutex we're waiting on
abs_timeout The time timeout value
Returns
zero or an error code.
Definition at line 114 of file unix/SysSemaphore.cpp.
References checkTimeOut().
Referenced by SysMutex::request().