ooRexx: TimeSupport.cpp File Reference
unix/TimeSupport.cpp File Reference
#include <pthread.h>
#include "RexxCore.h"
#include "IntegerClass.hpp"
#include "RexxDateTime.hpp"
#include "SystemInterpreter.hpp"
Functions
RexxMethod2 (int, alarm_startTimer, wholenumber_t, numdays, wholenumber_t, alarmtime)
RexxMethod1 (int, alarm_stopTimer, POINTER, eventSemHandle)
RexxMethod0 (int, ticker_createTimer)
RexxMethod3 (int, ticker_waitTimer, POINTER, eventSemHandle, wholenumber_t, numdays, wholenumber_t, alarmtime)
RexxMethod1 (int, ticker_stopTimer, POINTER, eventSemHandle)
Function Documentation
RexxMethod0()
RexxMethod0 (int , ticker_createTimer)
Create the initial timer semaphore.
Definition at line 174 of file unix/TimeSupport.cpp.
RexxMethod1() [1/2]
RexxMethod1 (int , alarm_stopTimer , POINTER , eventSemHandle)
Definition at line 163 of file unix/TimeSupport.cpp.
References SysSemaphore::post().
RexxMethod1() [2/2]
RexxMethod1 (int , ticker_stopTimer , POINTER , eventSemHandle)
Definition at line 231 of file unix/TimeSupport.cpp.
References SysSemaphore::post().
RexxMethod2()
RexxMethod2 (int , alarm_startTimer , wholenumber_t , numdays , wholenumber_t , alarmtime)
Definition at line 114 of file unix/TimeSupport.cpp.
References SysSemaphore::reset(), and SysSemaphore::wait().
RexxMethod3()
RexxMethod3 (int , ticker_waitTimer , POINTER , eventSemHandle , wholenumber_t , numdays , wholenumber_t , alarmtime)
Definition at line 185 of file unix/TimeSupport.cpp.
References SysSemaphore::reset(), and SysSemaphore::wait().