ooRexx: ExternalFunctions.cpp File Reference
windows/ExternalFunctions.cpp File Reference
#include <process.h>
#include <direct.h>
#include <windows.h>
#include <CommCtrl.h>
#include "RexxCore.h"
#include "StringClass.hpp"
#include "ArrayClass.hpp"
#include "Activity.hpp"
#include "RexxActivation.hpp"
#include "MethodClass.hpp"
#include "RexxInternalApis.h"
#include "ProtectedObject.hpp"
#include "StringUtil.hpp"
#include "PackageManager.hpp"
#include "SystemInterpreter.hpp"
#include "StemClass.hpp"
#include "NativeActivation.hpp"
Classes
struct _ENVENTRY
Macros
#define DIRLEN 256 /* length of a directory */
Typedefs
typedef struct _ENVENTRY ENVENTRY
Functions
static bool addMBStyle (CSTRING other, ULONG *style)
static LPCWSTR toUnicode (RexxActivation *context, RexxString *string, RexxString *codePage, RexxString *translateFlags, StemClass *stem, const char *tail, wholenumber_t *errorCode)
RexxRoutine7 (int, sysMessageBox, RexxStringObject, text, OPTIONAL_RexxStringObject, title, OPTIONAL_CSTRING, button, OPTIONAL_CSTRING, icon, OPTIONAL_CSTRING, other, OPTIONAL_RexxStringObject, codePage, OPTIONAL_RexxStringObject, translateFlags)
Macro Definition Documentation
DIRLEN
#define DIRLEN 256 /* length of a directory */
Definition at line 69 of file windows/ExternalFunctions.cpp.
Typedef Documentation
ENVENTRY
typedef struct _ENVENTRY ENVENTRY
Function Documentation
addMBStyle()
static bool addMBStyle (CSTRING other, ULONG * style) static
Helper function for sysMessageBox(). Parses the other message box style argument and adds the styles specified.
Parameters
other The 'additional message box styles' argument to RxMessageBox(). This can be more than one style keyword, separated by spaces.
style Pointer to the MessageBox style flags collected so far. On return this will be augmented with the additional styles.
Returns
True on no error, false if the user passed an unrecognizable keyword and a condition should be raised.
Note
Assumes other is not NULL.
Definition at line 155 of file windows/ExternalFunctions.cpp.
Referenced by RexxRoutine7().
RexxRoutine7()
RexxRoutine7 (int , sysMessageBox , RexxStringObject , text , OPTIONAL_RexxStringObject , title , OPTIONAL_CSTRING , button , OPTIONAL_CSTRING , icon , OPTIONAL_CSTRING , other , OPTIONAL_RexxStringObject , codePage , OPTIONAL_RexxStringObject , translateFlags)
Definition at line 314 of file windows/ExternalFunctions.cpp.
References addMBStyle(), contextToActivation(), NativeActivation::findRexxContext(), OREF_NULL, and toUnicode().
toUnicode()
static LPCWSTR toUnicode (RexxActivation * context, RexxString * string, RexxString * codePage, RexxString * translateFlags, StemClass * stem, const char * tail, wholenumber_t * errorCode) static
Helper function for sysMessageBox(). Convert to Unicode using the external function "SysToUnicode".
Parameters
context The current activation context.
string The string to convert to Unicode.
codePage The string's code page passed to SysToUnicode, or "UNICODE" if the string is already UTF-16.
translateFlags The flags passed to SysToUnicode.
stem The stem passed to SysToUnicode.
tail The tail to protect the string returned by SysToUnicode.
errorCode The address of the variable to return the error code.
Returns
The UTF-16 string, or NULL.
Definition at line 243 of file windows/ExternalFunctions.cpp.
References RexxActivation::getActivity(), StemClass::getElement(), RexxString::getStringData(), SystemInterpreter::invokeExternalFunction(), new_string(), StemClass::setElement(), and RexxString::strCaselessCompare().
Referenced by RexxRoutine7().