ooRexx: SystemCommands.cpp File Reference
windows/SystemCommands.cpp File Reference
#include <process.h>
#include "RexxCore.h"
#include "StringClass.hpp"
#include "Activity.hpp"
#include "ActivityManager.hpp"
#include "ProtectedObject.hpp"
#include "RexxInternalApis.h"
#include "SystemInterpreter.hpp"
#include "InterpreterInstance.hpp"
#include "SysInterpreterInstance.hpp"
#include "CommandHandler.hpp"
#include "SysThread.hpp"
#include <ctype.h>
#include "direct.h"
Classes
class InputWriterThread
class ReaderThread
Macros
#define CMDBUFSIZE 8092
#define CMDDEFNAME "CMD.EXE"
#define UNKNOWN_COMMAND 1 /* unknown command return code */
#define COMSPEC "COMSPEC" /* cmd handler env name */
#define SHOWWINDOWFLAGS SW_HIDE
Functions
void ErrorRedirection (RexxExitContext *context, int errCode)
bool sys_process_set (RexxExitContext *context, const char *command, const char *cmd, RexxObjectPtr &rc)
char * unquote (const char *s)
bool sys_process_cd (RexxExitContext *context, const char *command, const char *cmd, RexxObjectPtr &res)
void makePipe (PHANDLE readH, PHANDLE writeH, SECURITY_ATTRIBUTES *sAttr, CSTRING name, RexxExitContext *context)
bool sysCommandNT (RexxExitContext *context, const char *command, const char *cmdstring_ptr, bool direct, RexxObjectPtr &result, RexxIORedirectorContext *ioContext)
RexxObjectPtr RexxEntry systemCommandHandler (RexxExitContext *context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext *ioContext)
Variables
const int READ_SIZE = 4096
Macro Definition Documentation
CMDBUFSIZE
#define CMDBUFSIZE 8092
Definition at line 64 of file windows/SystemCommands.cpp.
CMDDEFNAME
#define CMDDEFNAME "CMD.EXE"
Definition at line 65 of file windows/SystemCommands.cpp.
COMSPEC
#define COMSPEC "COMSPEC" /* cmd handler env name */
Definition at line 69 of file windows/SystemCommands.cpp.
SHOWWINDOWFLAGS
#define SHOWWINDOWFLAGS SW_HIDE
Definition at line 71 of file windows/SystemCommands.cpp.
UNKNOWN_COMMAND
#define UNKNOWN_COMMAND 1 /* unknown command return code */
Definition at line 66 of file windows/SystemCommands.cpp.
Function Documentation
ErrorRedirection()
void ErrorRedirection (RexxExitContext * context, int errCode)
Raises syntax error 98.923 Address command redirection failed.
Parameters
context The Exit context.
errCode The operating system error code.
Definition at line 193 of file windows/SystemCommands.cpp.
References Error_Execution_address_redirection_failed.
Referenced by makePipe(), and sysCommandNT().
makePipe()
void makePipe (PHANDLE readH, PHANDLE writeH, SECURITY_ATTRIBUTES * sAttr, CSTRING name, RexxExitContext * context)
Definition at line 327 of file windows/SystemCommands.cpp.
References ErrorRedirection().
Referenced by sysCommandNT().
sys_process_cd()
bool sys_process_cd (RexxExitContext * context, const char * command, const char * cmd, RexxObjectPtr & res)
Definition at line 273 of file windows/SystemCommands.cpp.
References NULLOBJECT, and unquote().
Referenced by systemCommandHandler().
sys_process_set()
bool sys_process_set (RexxExitContext * context, const char * command, const char * cmd, RexxObjectPtr & rc)
Definition at line 214 of file windows/SystemCommands.cpp.
References NULLOBJECT.
Referenced by systemCommandHandler().
sysCommandNT()
bool sysCommandNT (RexxExitContext * context, const char * command, const char * cmdstring_ptr, bool direct, RexxObjectPtr & result, RexxIORedirectorContext * ioContext)
Definition at line 373 of file windows/SystemCommands.cpp.
References InputWriterThread::bufferLength, ReaderThread::dataLength, InputWriterThread::error, ReaderThread::error, ErrorRedirection(), SystemInterpreter::exceptionHostProcess, SystemInterpreter::exceptionHostProcessId, SystemInterpreter::explicitConsole, InputWriterThread::inputBuffer, makePipe(), NULLOBJECT, ReaderThread::pipeBuffer, SHOWWINDOWFLAGS, InputWriterThread::shutdown(), ReaderThread::start(), InputWriterThread::start(), and SysThread::waitForTermination().
Referenced by systemCommandHandler().
systemCommandHandler()
RexxObjectPtr RexxEntry systemCommandHandler (RexxExitContext * context, RexxStringObject address, RexxStringObject command, RexxIORedirectorContext * ioContext)
Definition at line 636 of file windows/SystemCommands.cpp.
References CMDBUFSIZE, CMDDEFNAME, COMSPEC, SystemInterpreter::exceptionConsole, SystemInterpreter::explicitConsole, NULLOBJECT, Rexx_Error_System_resources_user_defined, sys_process_cd(), sys_process_set(), and sysCommandNT().
unquote()
char* unquote (const char * s)
Definition at line 252 of file windows/SystemCommands.cpp.
Referenced by sys_process_cd().
Variable Documentation
READ_SIZE
const int READ_SIZE = 4096
Definition at line 75 of file windows/SystemCommands.cpp.
Referenced by ReaderThread::dispatch().