ooRexx: TimeSupport.cpp File Reference
windows/TimeSupport.cpp File Reference
#include "RexxCore.h"
#include "IntegerClass.hpp"
#include "RexxDateTime.hpp"
#include "Interpreter.hpp"
#include "SystemInterpreter.hpp"
#include <time.h>
Classes
struct timezone
Macros
#define DELTA_EPOCH_IN_MICROSECS 11644473600000000ULL
Functions
static void waitTimerOrEvent (HANDLE hev)
void raiseErrorSystem (RexxMethodContext *c, char *detail)
RexxMethod2 (int, alarm_startTimer, wholenumber_t, numdays, wholenumber_t, alarmtime)
RexxMethod1 (int, alarm_stopTimer, POINTER, eventSemHandle)
RexxMethod3 (int, ticker_waitTimer, POINTER, eventSemHandle, wholenumber_t, numdays, wholenumber_t, alarmtime)
RexxMethod0 (int, ticker_createTimer)
RexxMethod1 (int, ticker_stopTimer, POINTER, eventSemHandle)
Macro Definition Documentation
DELTA_EPOCH_IN_MICROSECS
#define DELTA_EPOCH_IN_MICROSECS 11644473600000000ULL
Definition at line 46 of file windows/TimeSupport.cpp.
Function Documentation
raiseErrorSystem()
void raiseErrorSystem (RexxMethodContext * c, char * detail)
Raise Error_System_service_service.
Parameters
context The current method context.
detail Message detail insert.
Definition at line 189 of file windows/TimeSupport.cpp.
References Rexx_Error_System_service_service.
Referenced by RexxMethod0(), RexxMethod1(), RexxMethod2(), and RexxMethod3().
RexxMethod0()
RexxMethod0 (int , ticker_createTimer)
set up for running a timer.
Definition at line 387 of file windows/TimeSupport.cpp.
References raiseErrorSystem().
RexxMethod1() [1/2]
RexxMethod1 (int , alarm_stopTimer , POINTER , eventSemHandle)
stops an asynchronous timer.
eventSemHandle - handle to event semaphore used to signal the timer should be canceled.
Definition at line 293 of file windows/TimeSupport.cpp.
References raiseErrorSystem().
RexxMethod1() [2/2]
RexxMethod1 (int , ticker_stopTimer , POINTER , eventSemHandle)
stops an asynchronous timer.
eventSemHandle - handle to event semaphore used to signal the timer should be canceled.
Definition at line 410 of file windows/TimeSupport.cpp.
References raiseErrorSystem().
RexxMethod2()
RexxMethod2 (int , alarm_startTimer , wholenumber_t , numdays , wholenumber_t , alarmtime)
starts a timer and waits for it to expire. An event semaphore is created that can be used to cancel the timer.
numdays - number of whole days until timer should expire. alarmtime - fractional portion (less than a day) until timer should expire, expressed in milliseconds.
Alarm is for some day in the future, start a timer that wakes up once a day.
Total alarm time has expired, or the alarm was canceled. We don't care which, just clean up and return.
Definition at line 207 of file windows/TimeSupport.cpp.
References raiseErrorSystem(), and waitTimerOrEvent().
RexxMethod3()
RexxMethod3 (int , ticker_waitTimer , POINTER , eventSemHandle , wholenumber_t , numdays , wholenumber_t , alarmtime)
starts a timer and waits for it to expire. An event semaphore is created that can be used to cancel the timer.
numdays - number of whole days until timer should expire. alarmtime - fractional portion (less than a day) until timer should expire, expressed in milliseconds.
Alarm is for some day in the future, start a timer that wakes up once a day.
Definition at line 315 of file windows/TimeSupport.cpp.
References raiseErrorSystem(), and waitTimerOrEvent().
waitTimerOrEvent()
static void waitTimerOrEvent (HANDLE hev) static
Wait for a window timer message or for an event to be signaled.
Parameters
hev Handle to an event object. If this event is signaled, the function returns.
Wait for a window timer message or for the event to be signaled. Note that MsgWaitForMultipleObjects() will return if a new message is placed in the message queue. Once PeekMesage() is called, all messages in the queue need to be processed before MsgWaitForMultipleObjects() is called.
Definition at line 151 of file windows/TimeSupport.cpp.
Referenced by RexxMethod2(), and RexxMethod3().