ooRexx: SysRexxUtil.cpp File Reference
windows/SysRexxUtil.cpp File Reference
#include "oorexxapi.h"
#include <memory.h>
#include <fcntl.h>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <conio.h>
#include <limits.h>
#include <algorithm>
#include <shlwapi.h>
#include <versionhelpers.h>
#include "SysFileSystem.hpp"
#include "RexxUtilCommon.hpp"
#include "FileNameBuffer.hpp"
#include "Utilities.hpp"
Macros
#define USED 0
#define FREE 1
#define SPECIFIC 3
#define STATUS_SUCCESS (0x00000000)
#define MAX_CREATEPROCESS_CMDLINE (32 * 1024)
Functions
RexxRoutine0 (int, SysCls)
RexxRoutine2 (RexxStringObject, SysCurPos, OPTIONAL_stringsize_t, inrow, OPTIONAL_stringsize_t, incol)
RexxRoutine1 (int, SysCurState, CSTRING, option)
RexxRoutine1 (RexxStringObject, SysDriveInfo, OPTIONAL_CSTRING, drive)
RexxRoutine2 (RexxStringObject, SysDriveMap, OPTIONAL_CSTRING, drive, OPTIONAL_CSTRING, mode)
uint32_t mergeAttrs (TreeFinder::AttributeMask &mask, uint32_t attr)
void setFileAttributes (const char *fileName, TreeFinder::AttributeMask &newAttributes)
void formatFileAttributes (TreeFinder *finder, FileNameBuffer &foundFile, SysFileIterator::FileAttributes &attributes)
bool checkInclusion (TreeFinder *finder, uint32_t attr)
RexxRoutine1 (RexxStringObject, SysGetKey, OPTIONAL_CSTRING, echoOpt)
RexxRoutine4 (RexxStringObject, SysIni, OPTIONAL_CSTRING, iniFile, CSTRING, app, RexxObjectPtr, key, OPTIONAL_RexxObjectPtr, val)
RexxRoutine1 (int, SysMkDir, CSTRING, dir)
RexxRoutine1 (RexxStringObject, SysGetErrorText, int32_t, errnum)
RexxRoutine1 (uint32_t, SysWinEncryptFile, CSTRING, fileName)
RexxRoutine1 (uint32_t, SysWinDecryptFile, CSTRING, fileName)
RexxRoutine0 (RexxStringObject, SysWinVer)
RexxRoutine3 (RexxStringObject, SysTextScreenRead, int, row, int, col, OPTIONAL_uint32_t, len)
RexxRoutine5 (RexxStringObject, SysTextScreenSize, OPTIONAL_CSTRING, optionString, OPTIONAL_stringsize_t, rows, OPTIONAL_stringsize_t, columns, OPTIONAL_stringsize_t, rows2, OPTIONAL_stringsize_t, columns2)
RexxRoutine2 (uint32_t, RxWinExec, CSTRING, command, OPTIONAL_CSTRING, show)
RexxRoutine0 (RexxStringObject, SysBootDrive)
RexxRoutine0 (RexxStringObject, SysSystemDirectory)
RexxRoutine1 (RexxStringObject, SysFileSystemType, OPTIONAL_CSTRING, drive)
RexxRoutine1 (RexxStringObject, SysVolumeLabel, OPTIONAL_CSTRING, drive)
RexxRoutine1 (RexxObjectPtr, SysCreateMutexSem, OPTIONAL_CSTRING, name)
RexxRoutine1 (uintptr_t, SysOpenMutexSem, CSTRING, name)
RexxRoutine1 (int, SysReleaseMutexSem, uintptr_t, h)
RexxRoutine1 (int, SysCloseMutexSem, uintptr_t, h)
RexxRoutine2 (int, SysRequestMutexSem, uintptr_t, h, OPTIONAL_int, timeout)
RexxRoutine2 (RexxObjectPtr, SysCreateEventSem, OPTIONAL_CSTRING, name, OPTIONAL_CSTRING, reset)
RexxRoutine1 (uintptr_t, SysOpenEventSem, CSTRING, name)
RexxRoutine1 (int, SysPostEventSem, uintptr_t, h)
RexxRoutine1 (int, SysResetEventSem, uintptr_t, h)
RexxRoutine1 (int, SysPulseEventSem, uintptr_t, h)
RexxRoutine1 (int, SysCloseEventSem, uintptr_t, h)
RexxRoutine2 (int, SysWaitEventSem, uintptr_t, h, OPTIONAL_int, timeout)
RexxRoutine2 (int, SysSetPriority, RexxObjectPtr, classArg, RexxObjectPtr, levelArg)
RexxRoutine1 (RexxObjectPtr, SysQueryProcess, OPTIONAL_CSTRING, option)
RexxRoutine5 (uint32_t, SysShutDownSystem, OPTIONAL_CSTRING, computer, OPTIONAL_CSTRING, message, OPTIONAL_uint32_t, timeout, OPTIONAL_logical_t, forceAppsClosed, OPTIONAL_logical_t, reboot)
RexxRoutine1 (int, SysSwitchSession, CSTRING, name)
RexxRoutine2 (int, SysWaitNamedPipe, CSTRING, name, OPTIONAL_int, timeout)
RexxRoutine3 (int, SysSetFileDateTime, CSTRING, name, OPTIONAL_CSTRING, newdate, OPTIONAL_CSTRING, newtime)
RexxRoutine2 (RexxObjectPtr, SysGetFileDateTime, CSTRING, name, OPTIONAL_CSTRING, selector)
static UINT evaluateCodePage (RexxCallContext *context, char *cpName, char inOrOut, char *function)
static char * combineFlags (CSTRING _string, char *names[], DWORD values[], DWORD &combined)
RexxRoutine5 (int, SysFromUnicode, RexxStringObject, sourceString, OPTIONAL_CSTRING, codePage, OPTIONAL_CSTRING, mappingFlags, OPTIONAL_RexxStringObject, defaultChar, RexxStemObject, stem)
RexxRoutine4 (int, SysToUnicode, RexxStringObject, sourceString, OPTIONAL_CSTRING, codePage, OPTIONAL_CSTRING, mappingFlags, RexxStemObject, stem)
RexxRoutine1 (uint32_t, SysWinGetPrinters, RexxObjectPtr, stem)
RexxRoutine0 (RexxStringObject, SysWinGetDefaultPrinter)
RexxRoutine1 (int, SysWinSetDefaultPrinter, CSTRING, printer)
RexxRoutine1 (logical_t, SysIsFileCompressed, CSTRING, file)
RexxRoutine1 (logical_t, SysIsFileEncrypted, CSTRING, file)
RexxRoutine1 (logical_t, SysIsFileNotContentIndexed, CSTRING, file)
RexxRoutine1 (logical_t, SysIsFileOffline, CSTRING, file)
RexxRoutine1 (logical_t, SysIsFileSparse, CSTRING, file)
RexxRoutine1 (logical_t, SysIsFileTemporary, CSTRING, file)
RexxRoutine1 (RexxStringObject, SysGetLongPathName, CSTRING, path)
RexxRoutine1 (RexxStringObject, SysGetShortPathName, CSTRING, path)
Variables
static int ExtendedFlag = 0
static char ExtendedChar
Macro Definition Documentation
FREE
#define FREE 1
Definition at line 331 of file windows/SysRexxUtil.cpp.
MAX_CREATEPROCESS_CMDLINE
#define MAX_CREATEPROCESS_CMDLINE (32 * 1024)
Definition at line 1612 of file windows/SysRexxUtil.cpp.
SPECIFIC
#define SPECIFIC 3
Definition at line 332 of file windows/SysRexxUtil.cpp.
STATUS_SUCCESS
#define STATUS_SUCCESS (0x00000000)
USED
#define USED 0
Definition at line 330 of file windows/SysRexxUtil.cpp.
Function Documentation
checkInclusion()
bool checkInclusion (TreeFinder * finder, uint32_t attr)
SysFileTree helper routine to see if this is a file we need to include in the result set.
Parameters
attr The file attributes
Returns
true if the file should be included, false otherwise.
Definition at line 776 of file windows/SysRexxUtil.cpp.
References TreeFinder::acceptAll(), TreeFinder::archiveSelected(), TreeFinder::directorySelected(), TreeFinder::hiddenSelected(), TreeFinder::includeDirs(), TreeFinder::includeFiles(), TreeFinder::readOnlySelected(), and TreeFinder::systemSelected().
combineFlags()
static char* combineFlags (CSTRING _string, char * names[], DWORD values[], DWORD & combined) static
Parse and combine a flag argument. This is used by the SysTo/FromUnicode() functions.
Parameters
_string A string whose words are flag names.
names An array of flag name strings.
values An array of bit values to combine.
combined The returned combined value.
Returns
Returns NULL upon success, else a pointer to the invalid option.
Definition at line 2767 of file windows/SysRexxUtil.cpp.
Referenced by RexxRoutine4(), and RexxRoutine5().
evaluateCodePage()
static UINT evaluateCodePage (RexxCallContext * context, char * cpName, char inOrOut, char * function) static
Evaluate a code page argument. The argument may be a whole number or any of the CP_* symbolic code pages that Windows provides or our own symbolic code page CONSOLE (the currently set console code page).
This is used by the SysTo/FromUnicode() functions.
Parameters
context The current call context.
cpName A String that is either a symbolic code page name or a number.
inOrOut 'I' indicating input, or 'O' indicating output code page.
function The calling function (e. g. "SysFromUnicode") used as error message insert.
Returns
Returns the code page number, or raises exception.
Definition at line 2704 of file windows/SysRexxUtil.cpp.
References invalidOptionException().
Referenced by RexxRoutine4(), and RexxRoutine5().
formatFileAttributes()
void formatFileAttributes (TreeFinder * finder, FileNameBuffer & foundFile, SysFileIterator::FileAttributes & attributes)
Format the system-specific file time, attribute mask, and size for the given file.
Parameters
foundFile The buffer the result is formatted into
finfo The system information about the file.
Definition at line 693 of file windows/SysRexxUtil.cpp.
References TreeFinder::editableTime(), SysFileIterator::FileAttributes::findFileData, TreeFinder::longSize(), and TreeFinder::longTime().
mergeAttrs()
uint32_t mergeAttrs (TreeFinder::AttributeMask & mask, uint32_t attr)
Returns a new file attribute value given a mask of attributes to be changed and the current attribute value.
Returns
New attribute value.
Definition at line 610 of file windows/SysRexxUtil.cpp.
References TreeFinder::AttributeMask::Archive, TreeFinder::AttributeMask::Hidden, TreeFinder::AttributeMask::isOff(), TreeFinder::AttributeMask::isOn(), TreeFinder::AttributeMask::noNewSettings(), TreeFinder::AttributeMask::ReadOnly, and TreeFinder::AttributeMask::System.
Referenced by setFileAttributes().
RexxRoutine0() [1/5]
RexxRoutine0 (int , SysCls)
Definition at line 148 of file windows/SysRexxUtil.cpp.
RexxRoutine0() [2/5]
RexxRoutine0 (RexxStringObject , SysBootDrive)
Definition at line 1728 of file windows/SysRexxUtil.cpp.
RexxRoutine0() [3/5]
RexxRoutine0 (RexxStringObject , SysSystemDirectory)
Definition at line 1754 of file windows/SysRexxUtil.cpp.
RexxRoutine0() [4/5]
RexxRoutine0 (RexxStringObject , SysWinGetDefaultPrinter)
Definition at line 3076 of file windows/SysRexxUtil.cpp.
RexxRoutine0() [5/5]
RexxRoutine0 (RexxStringObject , SysWinVer)
Definition at line 1309 of file windows/SysRexxUtil.cpp.
References STATUS_SUCCESS.
RexxRoutine1() [1/30]
RexxRoutine1 (int , SysCloseEventSem , uintptr_t , h)
Definition at line 2104 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [2/30]
RexxRoutine1 (int , SysCloseMutexSem , uintptr_t , h)
Definition at line 1945 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [3/30]
RexxRoutine1 (int , SysCurState , CSTRING , option)
Definition at line 224 of file windows/SysRexxUtil.cpp.
References invalidOptionException().
RexxRoutine1() [4/30]
RexxRoutine1 (int , SysMkDir , CSTRING , dir)
Definition at line 1210 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [5/30]
RexxRoutine1 (int , SysPostEventSem , uintptr_t , h)
Definition at line 2057 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [6/30]
RexxRoutine1 (int , SysPulseEventSem , uintptr_t , h)
Definition at line 2088 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [7/30]
RexxRoutine1 (int , SysReleaseMutexSem , uintptr_t , h)
Definition at line 1930 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [8/30]
RexxRoutine1 (int , SysResetEventSem , uintptr_t , h)
Definition at line 2072 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [9/30]
RexxRoutine1 (int , SysSwitchSession , CSTRING , name)
Definition at line 2482 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [10/30]
RexxRoutine1 (int , SysWinSetDefaultPrinter , CSTRING , printer)
Definition at line 3095 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [11/30]
RexxRoutine1 (logical_t , SysIsFileCompressed , CSTRING , file)
Definition at line 3169 of file windows/SysRexxUtil.cpp.
References SysFileSystem::getFileAttributes().
RexxRoutine1() [12/30]
RexxRoutine1 (logical_t , SysIsFileEncrypted , CSTRING , file)
Definition at line 3185 of file windows/SysRexxUtil.cpp.
References SysFileSystem::getFileAttributes().
RexxRoutine1() [13/30]
RexxRoutine1 (logical_t , SysIsFileNotContentIndexed , CSTRING , file)
Definition at line 3202 of file windows/SysRexxUtil.cpp.
References SysFileSystem::getFileAttributes().
RexxRoutine1() [14/30]
RexxRoutine1 (logical_t , SysIsFileOffline , CSTRING , file)
Definition at line 3218 of file windows/SysRexxUtil.cpp.
References SysFileSystem::getFileAttributes().
RexxRoutine1() [15/30]
RexxRoutine1 (logical_t , SysIsFileSparse , CSTRING , file)
Definition at line 3234 of file windows/SysRexxUtil.cpp.
References SysFileSystem::getFileAttributes().
RexxRoutine1() [16/30]
RexxRoutine1 (logical_t , SysIsFileTemporary , CSTRING , file)
Definition at line 3251 of file windows/SysRexxUtil.cpp.
References SysFileSystem::getFileAttributes().
RexxRoutine1() [17/30]
RexxRoutine1 (RexxObjectPtr , SysCreateMutexSem , OPTIONAL_CSTRING , name)
Definition at line 1872 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [18/30]
RexxRoutine1 (RexxObjectPtr , SysQueryProcess , OPTIONAL_CSTRING , option)
Definition at line 2273 of file windows/SysRexxUtil.cpp.
References NULLOBJECT.
RexxRoutine1() [19/30]
RexxRoutine1 (RexxStringObject , SysDriveInfo , OPTIONAL_CSTRING , drive)
Definition at line 265 of file windows/SysRexxUtil.cpp.
References FileNameBuffer::addFinalPathDelimiter(), FileNameBuffer::at(), FileNameBuffer::capacity(), FileNameBuffer::endsWith(), Utilities::isAlpha(), FileNameBuffer::length(), and FileNameBuffer::truncate().
RexxRoutine1() [20/30]
RexxRoutine1 (RexxStringObject , SysFileSystemType , OPTIONAL_CSTRING , drive)
Definition at line 1781 of file windows/SysRexxUtil.cpp.
References FileNameBuffer::addFinalPathDelimiter(), FileNameBuffer::at(), Utilities::isAlpha(), and FileNameBuffer::length().
RexxRoutine1() [21/30]
RexxRoutine1 (RexxStringObject , SysGetErrorText , int32_t , errnum)
Definition at line 1230 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [22/30]
RexxRoutine1 (RexxStringObject , SysGetKey , OPTIONAL_CSTRING , echoOpt)
Definition at line 952 of file windows/SysRexxUtil.cpp.
References ExtendedChar, ExtendedFlag, and invalidOptionException().
RexxRoutine1() [23/30]
RexxRoutine1 (RexxStringObject , SysGetLongPathName , CSTRING , path)
Definition at line 3270 of file windows/SysRexxUtil.cpp.
References FileNameBuffer::capacity(), and FileNameBuffer::ensureCapacity().
RexxRoutine1() [24/30]
RexxRoutine1 (RexxStringObject , SysGetShortPathName , CSTRING , path)
Definition at line 3305 of file windows/SysRexxUtil.cpp.
References FileNameBuffer::capacity(), and FileNameBuffer::ensureCapacity().
RexxRoutine1() [25/30]
RexxRoutine1 (RexxStringObject , SysVolumeLabel , OPTIONAL_CSTRING , drive)
Definition at line 1826 of file windows/SysRexxUtil.cpp.
References FileNameBuffer::addFinalPathDelimiter(), FileNameBuffer::at(), Utilities::isAlpha(), and FileNameBuffer::length().
RexxRoutine1() [26/30]
RexxRoutine1 (uint32_t , SysWinDecryptFile , CSTRING , fileName)
Definition at line 1291 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [27/30]
RexxRoutine1 (uint32_t , SysWinEncryptFile , CSTRING , fileName)
Definition at line 1271 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [28/30]
RexxRoutine1 (uint32_t , SysWinGetPrinters , RexxObjectPtr , stem)
Definition at line 3017 of file windows/SysRexxUtil.cpp.
References StemHandler::addValue(), StemHandler::complete(), and outOfMemoryException().
RexxRoutine1() [29/30]
RexxRoutine1 (uintptr_t , SysOpenEventSem , CSTRING , name)
Definition at line 2039 of file windows/SysRexxUtil.cpp.
RexxRoutine1() [30/30]
RexxRoutine1 (uintptr_t , SysOpenMutexSem , CSTRING , name)
Definition at line 1912 of file windows/SysRexxUtil.cpp.
RexxRoutine2() [1/9]
RexxRoutine2 (int , SysRequestMutexSem , uintptr_t , h , OPTIONAL_int , timeout)
Definition at line 1960 of file windows/SysRexxUtil.cpp.
References argumentOmitted.
RexxRoutine2() [2/9]
RexxRoutine2 (int , SysSetPriority , RexxObjectPtr , classArg , RexxObjectPtr , levelArg)
Definition at line 2148 of file windows/SysRexxUtil.cpp.
RexxRoutine2() [3/9]
RexxRoutine2 (int , SysWaitEventSem , uintptr_t , h , OPTIONAL_int , timeout)
Definition at line 2119 of file windows/SysRexxUtil.cpp.
References argumentExists.
RexxRoutine2() [4/9]
RexxRoutine2 (int , SysWaitNamedPipe , CSTRING , name , OPTIONAL_int , timeout)
Definition at line 2514 of file windows/SysRexxUtil.cpp.
References argumentOmitted.
RexxRoutine2() [5/9]
RexxRoutine2 (RexxObjectPtr , SysCreateEventSem , OPTIONAL_CSTRING , name , OPTIONAL_CSTRING , reset)
Definition at line 1990 of file windows/SysRexxUtil.cpp.
RexxRoutine2() [6/9]
RexxRoutine2 (RexxObjectPtr , SysGetFileDateTime , CSTRING , name , OPTIONAL_CSTRING , selector)
Definition at line 2639 of file windows/SysRexxUtil.cpp.
References SysFileSystem::FiletimeAccess, SysFileSystem::FiletimeCreation, SysFileSystem::FiletimeWrite, SysFileSystem::getFiletime(), invalidOptionException(), and type.
RexxRoutine2() [7/9]
RexxRoutine2 (RexxStringObject , SysCurPos , OPTIONAL_stringsize_t , inrow , OPTIONAL_stringsize_t , incol)
Definition at line 177 of file windows/SysRexxUtil.cpp.
References argumentExists, and argumentOmitted.
RexxRoutine2() [8/9]
RexxRoutine2 (RexxStringObject , SysDriveMap , OPTIONAL_CSTRING , drive , OPTIONAL_CSTRING , mode)
Definition at line 348 of file windows/SysRexxUtil.cpp.
References FREE, FileNameBuffer::length(), Rexx_Error_Incorrect_call_user_defined, SPECIFIC, Utilities::toUpper(), and USED.
RexxRoutine2() [9/9]
RexxRoutine2 (uint32_t , RxWinExec , CSTRING , command , OPTIONAL_CSTRING , show)
Definition at line 1630 of file windows/SysRexxUtil.cpp.
References MAX_CREATEPROCESS_CMDLINE.
RexxRoutine3() [1/2]
RexxRoutine3 (int , SysSetFileDateTime , CSTRING , name , OPTIONAL_CSTRING , newdate , OPTIONAL_CSTRING , newtime)
Definition at line 2561 of file windows/SysRexxUtil.cpp.
RexxRoutine3() [2/2]
RexxRoutine3 (RexxStringObject , SysTextScreenRead , int , row , int , col , OPTIONAL_uint32_t , len)
Definition at line 1360 of file windows/SysRexxUtil.cpp.
References argumentOmitted, NULLOBJECT, outOfMemoryException(), AutoFree::realloc(), and Rexx_Error_Invalid_argument_range.
RexxRoutine4() [1/2]
RexxRoutine4 (int , SysToUnicode , RexxStringObject , sourceString , OPTIONAL_CSTRING , codePage , OPTIONAL_CSTRING , mappingFlags , RexxStemObject , stem)
SysToUnicode() Converts a character string in the specified code page to a Windows UTF-16 string.
Interface to the MultiByteToWideChar() API on Windows. https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar
Parameters
sourceString The character string to be converted.
codePage An optional code page to be converted to, which can be either a number or a symbolic code page name like OEMCP. If omitted, defaults to OEMCP.
mappingFlags Optional string of mapping flag names.
stem A stem variable. Upon successful return this tail is set: !TEXT The converted wide UTF-16 string.
Returns
Returns 0 upon success, or a Windows error code from MultiByteToWideChar().
Remarks
As older code used mapping flag name ERR_INVALID instead of ERR_INVALID_CHARS we keep this for now as an undocumented alias.
Definition at line 2941 of file windows/SysRexxUtil.cpp.
References combineFlags(), evaluateCodePage(), invalidOptionException(), and outOfMemoryException().
RexxRoutine4() [2/2]
RexxRoutine4 (RexxStringObject , SysIni , OPTIONAL_CSTRING , iniFile , CSTRING , app , RexxObjectPtr , key , OPTIONAL_RexxObjectPtr , val)
Definition at line 1038 of file windows/SysRexxUtil.cpp.
References StemHandler::addList(), argumentExists, argumentOmitted, ERROR_NOMEM, ERROR_RETSTR, maxArgException(), Rexx_Error_Invalid_argument_noarg, and StemHandler::setStem().
RexxRoutine5() [1/3]
RexxRoutine5 (int , SysFromUnicode , RexxStringObject , sourceString , OPTIONAL_CSTRING , codePage , OPTIONAL_CSTRING , mappingFlags , OPTIONAL_RexxStringObject , defaultChar , RexxStemObject , stem)
SysFromUnicode() Converts a UTF-16 string to a character string in the specified code page.
Interface to the WideCharToMultiByte() API on Windows. https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte
Parameters
sourceString The UTF-16 string to be converted.
codePage An optional code page to be converted to, which can be either a number or a symbolic code page name like OEMCP. If omitted, defaults to OEMCP.
mappingFlags Optional string of mapping flag names.
defaultChar Optional default character for unmappable characters. If omitted, codepage-dependent default is typically "?".
stem A stem variable. Upon successful return these tails are set: !USEDDEFAULTCHAR A boolean indicating that the conversion found one or more characters in sourceString that cannot be represented in the specified code page. !TEXT The string converted to the code page.
Returns
Returns 0 upon success, or a Windows error code from WideCharToMultiByte()
Remarks
As older code used mapping flag names ERR_INVALID instead of ERR_INVALID_CHARS and NO_BEST_FIT instead of NO_BEST_FIT_CHARS, we keep these for now as undocumented aliases.
Definition at line 2824 of file windows/SysRexxUtil.cpp.
References combineFlags(), evaluateCodePage(), invalidOptionException(), outOfMemoryException(), and Rexx_Error_Incorrect_call_pad.
RexxRoutine5() [2/3]
RexxRoutine5 (RexxStringObject , SysTextScreenSize , OPTIONAL_CSTRING , optionString , OPTIONAL_stringsize_t , rows , OPTIONAL_stringsize_t , columns , OPTIONAL_stringsize_t , rows2 , OPTIONAL_stringsize_t , columns2)
Definition at line 1495 of file windows/SysRexxUtil.cpp.
References argumentExists, argumentOmitted, and invalidOptionException().
RexxRoutine5() [3/3]
RexxRoutine5 (uint32_t , SysShutDownSystem , OPTIONAL_CSTRING , computer , OPTIONAL_CSTRING , message , OPTIONAL_uint32_t , timeout , OPTIONAL_logical_t , forceAppsClosed , OPTIONAL_logical_t , reboot)
SysShutDownSystem()
Interface to the InitiateSystemShutdown() API on Windows.
Parameters
computer The name of the computer to shut down. If omitted or the empty string, the local machine is shut down. Otherwise this is the name of a remote machine to shut down.
message If timout is not 0, a shut down dialog is displayed on the machine being shut down, naming the user who initiated the shut down, a timer counting down the seconds until the machine is shut down, and prompting the local user to log off. This parametr can be an additional message to add to the dialog box. It can be ommitted if no additional message is desired.
timeout Number of seconds to display the shut down dialog. If this is 0 no dialog is displayed. The default is 30 seconds, see the remarks below. The user can force a 0 timeout by explicitly specifying 0.
forceAppsClosed If true applications with unsaved data are forcibly closed. If false, the user is presented with a dialog telling the user to close the applcation(s).
reboot If true, the system is rebooted, if false the system is shut down.
Remarks
Note that prior to 4.0.0, the defaults for all arguments were exactly what the value of each parameter is if omitted.
machine == NULL message == NULL timeout == 0 forceAppsClosed == false reboot == false
Because of this, there would be no need to check if any argument is ommitted or not. However, the consequences of having a 0 timeout value are severe if the system has an application open with unsaved data. Therefore for 4.0.0 and on the default time out value is changed to 30 (seconds.)
Definition at line 2409 of file windows/SysRexxUtil.cpp.
References argumentOmitted.
setFileAttributes()
void setFileAttributes (const char * fileName, TreeFinder::AttributeMask & newAttributes)
Set the file attributes using the new mask and then return the new current attribute set for the file.
Parameters
fileName The target file name
Returns
A new attribute mask for the file.
Definition at line 666 of file windows/SysRexxUtil.cpp.
References mergeAttrs().
Variable Documentation
ExtendedChar
char ExtendedChar static
Definition at line 138 of file windows/SysRexxUtil.cpp.
Referenced by RexxRoutine1().
ExtendedFlag
int ExtendedFlag = 0 static
Definition at line 137 of file windows/SysRexxUtil.cpp.
Referenced by RexxRoutine1().