executor.master: ArrayClass.cpp File Reference
ArrayClass.cpp File Reference
#include <stdlib.h>
#include "RexxCore.h"
#include "RexxActivity.hpp"
#include "IntegerClass.hpp"
#include "SupplierClass.hpp"
#include "ArrayClass.hpp"
#include "MutableBufferClass.hpp"
#include "ActivityManager.hpp"
#include "ProtectedObject.hpp"
#include <deque>
Macros
#define min(a, b) (a<=b?a:b)
Functions
void copyElements (COPYELEMENTPARM *parm, size_t newDimension)
Macro Definition Documentation
min
#define min (a, b) (a<=b?a:b)
Definition at line 82 of file ArrayClass.cpp.
Function Documentation
copyElements()
void copyElements (COPYELEMENTPARM * parm, size_t newDimension)
Definition at line 1935 of file ArrayClass.cpp.
References copyElementParm::copyElements, copyElementParm::deltaDimSize, copyElementParm::firstChangedDimension, RexxArray::get(), RexxInternalObject::isOldSpace(), copyElementParm::newArray, copyElementParm::newDimArray, copyElementParm::oldDimArray, OrefSet, RexxArray::size(), copyElementParm::skipElements, copyElementParm::startNew, and copyElementParm::startOld.
Referenced by RexxArray::extendMulti().