executor.master: NumberStringClass.hpp File Reference
NumberStringClass.hpp File Reference
#include "Numerics.hpp"
#include "NumberStringMath.hpp"
Classes
class RexxNumberStringBase
class RexxNumberString
Macros
#define ch_BLANK ' ' /* Define a Blank character. */
#define ch_MINUS '-' /* Define the MINUS character */
#define ch_PLUS '+' /* Define the PLUS character. */
#define ch_PERIOD '.' /* Define the DOT/PERIOD character. */
#define ch_ZERO '0' /* Define the Zero character. */
#define ch_ONE '1' /* Define the One character. */
#define ch_FIVE '5' /* Define the Five character. */
#define ch_NINE '9' /* Define the Nine character. */
#define ch_TAB '\t' /* Define the alternate whitespace char */
#define NumFormScientific 0x00000001 /* Define Numeric form setting at Object*/
#define NumberRounded 0x00000010 /* Indicate the number was rounded once */
#define OVERFLOWSPACE 2 /* space for numeric buffer overflow */
#define SetNumberStringZero()
#define NumberStringRound(s, d) s->roundUp(s,d)
Functions
void AdjustPrecision (RexxNumberString *, char *, int)
RexxNumberString * new_numberstring (const char *s, stringsize_t l)
RexxNumberString * new_numberstringFromWholenumber (wholenumber_t n)
RexxNumberString * new_numberstringFromStringsize (stringsize_t n)
RexxNumberString * new_numberstringFromInt64 (int64_t n)
RexxNumberString * new_numberstringFromUint64 (uint64_t n)
RexxNumberString * new_numberstringFromDouble (double n)
RexxNumberString * new_numberstringFromDouble (double n, size_t p)
RexxNumberString * new_numberstringFromFloat (float n)
Macro Definition Documentation
ch_BLANK
#define ch_BLANK ' ' /* Define a Blank character. */
Definition at line 51 of file NumberStringClass.hpp.
ch_FIVE
#define ch_FIVE '5' /* Define the Five character. */
Definition at line 57 of file NumberStringClass.hpp.
ch_MINUS
#define ch_MINUS '-' /* Define the MINUS character */
Definition at line 52 of file NumberStringClass.hpp.
ch_NINE
#define ch_NINE '9' /* Define the Nine character. */
Definition at line 58 of file NumberStringClass.hpp.
ch_ONE
#define ch_ONE '1' /* Define the One character. */
Definition at line 56 of file NumberStringClass.hpp.
ch_PERIOD
#define ch_PERIOD '.' /* Define the DOT/PERIOD character. */
Definition at line 54 of file NumberStringClass.hpp.
ch_PLUS
#define ch_PLUS '+' /* Define the PLUS character. */
Definition at line 53 of file NumberStringClass.hpp.
ch_TAB
#define ch_TAB '\t' /* Define the alternate whitespace char */
Definition at line 59 of file NumberStringClass.hpp.
ch_ZERO
#define ch_ZERO '0' /* Define the Zero character. */
Definition at line 55 of file NumberStringClass.hpp.
NumberRounded
#define NumberRounded 0x00000010 /* Indicate the number was rounded once */
Definition at line 63 of file NumberStringClass.hpp.
NumberStringRound
#define NumberStringRound (s, d) s->roundUp(s,d)
Definition at line 75 of file NumberStringClass.hpp.
NumFormScientific
#define NumFormScientific 0x00000001 /* Define Numeric form setting at Object*/
Definition at line 61 of file NumberStringClass.hpp.
OVERFLOWSPACE
#define OVERFLOWSPACE 2 /* space for numeric buffer overflow */
Definition at line 66 of file NumberStringClass.hpp.
SetNumberStringZero
#define SetNumberStringZero ()
Value:
      this->number[0] = '\0';               /* Make value a zero.*/     \
      this->length = 1;                     /* Length is 1       */     \
      this->sign = 0;                       /* Make sign Zero.   */     \
      this->exp = 0;                        /* exponent is zero. */
Definition at line 68 of file NumberStringClass.hpp.
Function Documentation
AdjustPrecision()
void AdjustPrecision (RexxNumberString * , char * , int)
new_numberstring()
RexxNumberString* new_numberstring (const char * s, stringsize_t l) inline
Definition at line 276 of file NumberStringClass.hpp.
References RexxNumberString::newInstance().
Referenced by RexxNumberString::addSub(), RexxString::createNumberString(), RexxNumberString::Multiply(), and RexxString::numberString().
new_numberstringFromDouble() [1/2]
RexxNumberString* new_numberstringFromDouble (double n) inline
Definition at line 301 of file NumberStringClass.hpp.
References RexxNumberString::newInstanceFromDouble().
Referenced by DoubleToObject(), DoubleToObjectWithPrecision(), and RexxString::newString().
new_numberstringFromDouble() [2/2]
RexxNumberString* new_numberstringFromDouble (double n, size_t p) inline
Definition at line 306 of file NumberStringClass.hpp.
References RexxNumberString::newInstanceFromDouble().
new_numberstringFromFloat()
RexxNumberString* new_numberstringFromFloat (float n) inline
Definition at line 311 of file NumberStringClass.hpp.
References RexxNumberString::newInstanceFromFloat().
new_numberstringFromInt64()
RexxNumberString* new_numberstringFromInt64 (int64_t n) inline
Definition at line 291 of file NumberStringClass.hpp.
References RexxNumberString::newInstanceFromInt64().
Referenced by Numerics::int64ToObject().
new_numberstringFromStringsize()
RexxNumberString* new_numberstringFromStringsize (stringsize_t n) inline
Definition at line 286 of file NumberStringClass.hpp.
References RexxNumberString::newInstanceFromStringsize().
Referenced by Numerics::stringsizeToObject(), and Numerics::uintptrToObject().
new_numberstringFromUint64()
RexxNumberString* new_numberstringFromUint64 (uint64_t n) inline
Definition at line 296 of file NumberStringClass.hpp.
References RexxNumberString::newInstanceFromUint64().
Referenced by Numerics::uint64ToObject().
new_numberstringFromWholenumber()
RexxNumberString* new_numberstringFromWholenumber (wholenumber_t n) inline
Definition at line 281 of file NumberStringClass.hpp.
References RexxNumberString::newInstanceFromWholenumber().
Referenced by Numerics::intptrToObject(), RexxInteger::numberString(), and Numerics::wholenumberToObject().