executor.master: RegistrationAPI.cpp File Reference
RegistrationAPI.cpp File Reference
#include "rexx.h"
#include "LocalAPIManager.hpp"
#include "LocalRegistrationManager.hpp"
#include "RexxAPI.h"
#include "LocalAPIContext.hpp"
#include "RexxInternalApis.h"
#include "ClientMessage.hpp"
#include "SysLocalAPIManager.hpp"
Functions
RexxReturnCode RexxEntry RexxRegisterSubcomDll (const char *envName, const char *moduleName, const char *procedureName, const char *userArea, size_t dropAuthority)
RexxReturnCode RexxEntry RexxRegisterSubcomExe (const char *envName, REXXPFN entryPoint, const char *userArea)
RexxReturnCode RexxEntry RexxDeregisterSubcom (const char *name, const char *moduleName)
RexxReturnCode RexxEntry RexxQuerySubcom (const char *name, const char *module, unsigned short *flags, char *userWord)
RexxReturnCode RexxEntry RexxResolveSubcom (const char *name, REXXPFN *entryPoint)
RexxReturnCode RexxEntry RexxLoadSubcom (const char *name, const char *lib)
RexxReturnCode RexxEntry RexxRegisterExitDll (const char *envName, const char *moduleName, const char *procedureName, const char *userArea, size_t dropAuthority)
RexxReturnCode RexxEntry RexxRegisterExitExe (const char *envName, REXXPFN entryPoint, const char *userArea)
RexxReturnCode RexxEntry RexxDeregisterExit (const char *name, const char *moduleName)
RexxReturnCode RexxEntry RexxQueryExit (const char *name, const char *module, unsigned short *exist, char *userWord)
RexxReturnCode RexxEntry RexxResolveExit (const char *name, REXXPFN *entryPoint)
RexxReturnCode RexxEntry RexxRegisterFunctionDll (const char *name, const char *moduleName, const char *procedureName)
RexxReturnCode RexxEntry RexxRegisterFunctionExe (const char *name, REXXPFN entryPoint)
RexxReturnCode RexxEntry RexxDeregisterFunction (const char *name)
RexxReturnCode RexxEntry RexxQueryFunction (const char *name)
RexxReturnCode RexxEntry RexxResolveRoutine (const char *name, REXXPFN *entryPoint)
void *REXXENTRY RexxAllocateMemory (size_t size)
RexxReturnCode REXXENTRY RexxFreeMemory (void *ptr)
RexxReturnCode REXXENTRY RexxShutDownAPI ()
Function Documentation
RexxAllocateMemory()
void* REXXENTRY RexxAllocateMemory (size_t size)
Definition at line 553 of file RegistrationAPI.cpp.
References SysAPIManager::allocateMemory().
Referenced by FetchRexxVar(), LocalQueueManager::pullFromQueue(), and WSRegistryValue().
RexxDeregisterExit()
RexxReturnCode RexxEntry RexxDeregisterExit (const char * name, const char * moduleName)
Definition at line 337 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, ExitAPI, and RegistrationManager.
RexxDeregisterFunction()
RexxReturnCode RexxEntry RexxDeregisterFunction (const char * name)
Definition at line 488 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, FunctionAPI, and RegistrationManager.
RexxDeregisterSubcom()
RexxReturnCode RexxEntry RexxDeregisterSubcom (const char * name, const char * moduleName)
Definition at line 147 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, RegistrationManager, and SubcomAPI.
RexxFreeMemory()
RexxReturnCode REXXENTRY RexxFreeMemory (void * ptr)
Definition at line 575 of file RegistrationAPI.cpp.
References SysAPIManager::releaseMemory().
Referenced by Api_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP(), Api_Read_All_Variables_From_REXX_VP(), Aspi_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP(), Aspi_Read_All_Variables_From_REXX_VP(), CallRexx(), ExecIO_Write_From_Queue(), ExecIO_Write_From_Stem(), FetchRexxVar(), main(), RexxMethod0(), and SysDumpVariables().
RexxLoadSubcom()
RexxReturnCode RexxEntry RexxLoadSubcom (const char * name, const char * lib)
Definition at line 244 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, RegistrationManager, and SubcomAPI.
Referenced by main().
RexxQueryExit()
RexxReturnCode RexxEntry RexxQueryExit (const char * name, const char * module, unsigned short * exist, char * userWord)
Definition at line 371 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, ExitAPI, RegistrationManager, and RXQUEUE_OK.
RexxQueryFunction()
RexxReturnCode RexxEntry RexxQueryFunction (const char * name)
Definition at line 515 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, FunctionAPI, and RegistrationManager.
RexxQuerySubcom()
RexxReturnCode RexxEntry RexxQuerySubcom (const char * name, const char * module, unsigned short * flags, char * userWord)
Definition at line 181 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, RegistrationManager, RXSUBCOM_OK, and SubcomAPI.
RexxRegisterExitDll()
RexxReturnCode RexxEntry RexxRegisterExitDll (const char * envName, const char * moduleName, const char * procedureName, const char * userArea, size_t dropAuthority)
Definition at line 277 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, ExitAPI, RegistrationManager, and RXSUBCOM_NONDROP.
RexxRegisterExitExe()
RexxReturnCode RexxEntry RexxRegisterExitExe (const char * envName, REXXPFN entryPoint, const char * userArea)
Definition at line 308 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, ExitAPI, and RegistrationManager.
RexxRegisterFunctionDll()
RexxReturnCode RexxEntry RexxRegisterFunctionDll (const char * name, const char * moduleName, const char * procedureName)
Definition at line 433 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, FunctionAPI, and RegistrationManager.
RexxRegisterFunctionExe()
RexxReturnCode RexxEntry RexxRegisterFunctionExe (const char * name, REXXPFN entryPoint)
Definition at line 462 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, FunctionAPI, and RegistrationManager.
RexxRegisterSubcomDll()
RexxReturnCode RexxEntry RexxRegisterSubcomDll (const char * envName, const char * moduleName, const char * procedureName, const char * userArea, size_t dropAuthority)
Definition at line 79 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, RegistrationManager, RXSUBCOM_NONDROP, and SubcomAPI.
RexxRegisterSubcomExe()
RexxReturnCode RexxEntry RexxRegisterSubcomExe (const char * envName, REXXPFN entryPoint, const char * userArea)
Definition at line 118 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, RegistrationManager, and SubcomAPI.
RexxResolveExit()
RexxReturnCode RexxEntry RexxResolveExit (const char * name, REXXPFN * entryPoint)
Definition at line 405 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, ExitAPI, and RegistrationManager.
Referenced by ExitHandler::resolve().
RexxResolveRoutine()
RexxReturnCode RexxEntry RexxResolveRoutine (const char * name, REXXPFN * entryPoint)
Definition at line 526 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, FunctionAPI, and RegistrationManager.
Referenced by PackageManager::createRegisteredRoutine(), and PackageManager::resolveRegisteredRoutineEntry().
RexxResolveSubcom()
RexxReturnCode RexxEntry RexxResolveSubcom (const char * name, REXXPFN * entryPoint)
Definition at line 215 of file RegistrationAPI.cpp.
References ENTER_REXX_API, EXIT_REXX_API, RegistrationManager, and SubcomAPI.
Referenced by CommandHandler::resolve().
RexxShutDownAPI()
RexxReturnCode REXXENTRY RexxShutDownAPI (void)
Shutdown the API subsystem. This is a nop in 4.0. This is maintained solely for binary compatibility.
Returns
always returns true
Definition at line 588 of file RegistrationAPI.cpp.