executor.master: RexxCore.h File Reference
RexxCore.h File Reference
#include "oorexxapi.h"
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include "RexxPlatformDefinitions.h"
#include "RexxConstants.hpp"
#include "ClassTypeCodes.h"
#include "GlobalNames.h"
#include "ObjectClass.hpp"
#include "TableClass.hpp"
#include "StackClass.hpp"
#include "RexxMemory.hpp"
#include "RexxBehaviour.hpp"
#include "ClassClass.hpp"
#include "RexxEnvelope.hpp"
#include "RexxActivity.hpp"
#include "NumberStringClass.hpp"
#include "ActivityManager.hpp"
Classes
struct NamedArgument
class NamedArguments
Macros
#define OREF_NULL NULL /* definition of a NULL REXX object */
#define OrefSet(o, r, v) ((o)->isOldSpace() ? memoryObject.setOref((void *)&(r),(RexxObject *)v) : (RexxObject *)(r=v))
#define INITGLOBALPTR
#define EXTERN extern /* turn into external definition */
#define EXTERNMEM extern /* turn into external definition */
#define CLASS_EXTERNAL(b, c)
#define CLASS_INTERNAL(b, c)
#define koper(name) RexxObject *name(RexxObject *);
#define TheArrayClass RexxArray::classInstance
#define TheClassClass RexxClass::classInstance
#define TheDirectoryClass RexxDirectory::classInstance
#define TheIntegerClass RexxInteger::classInstance
#define TheListClass RexxList::classInstance
#define TheMessageClass RexxMessage::classInstance
#define TheMethodClass RexxMethod::classInstance
#define TheRoutineClass RoutineClass::classInstance
#define ThePackageClass PackageClass::classInstance
#define TheRexxContextClass RexxContext::classInstance
#define TheNumberStringClass RexxNumberString::classInstance
#define TheObjectClass RexxObject::classInstance
#define TheQueueClass RexxQueue::classInstance
#define TheStemClass RexxStem::classInstance
#define TheStringClass RexxString::classInstance
#define TheMutableBufferClass RexxMutableBuffer::classInstance
#define TheSupplierClass RexxSupplier::classInstance
#define TheTableClass RexxTable::classInstance
#define TheIdentityTableClass RexxIdentityTable::classInstance
#define TheRelationClass RexxRelation::classInstance
#define ThePointerClass RexxPointer::classInstance
#define TheBufferClass RexxBuffer::classInstance
#define TheWeakReferenceClass WeakReference::classInstance
#define TheStackFrameClass StackFrameClass::classInstance
#define TheRexxBlockClass RexxBlock::classInstance
#define TheRexxTextClass RexxText::classInstance
#define TheEnvironment RexxMemory::environment
#define TheStaticRequires RexxMemory::staticRequires
#define TheFunctionsDirectory RexxMemory::functionsDir
#define TheCommonRetrievers RexxMemory::commonRetrievers
#define TheKernel RexxMemory::kernel
#define TheSystem RexxMemory::system
#define TheNilObject RexxNilObject::nilObject
#define TheNullArray RexxArray::nullArray
#define TheFalseObject RexxInteger::falseObject
#define TheTrueObject RexxInteger::trueObject
#define TheNullPointer RexxPointer::nullPointer
#define IntegerZero RexxInteger::integerZero
#define IntegerOne RexxInteger::integerOne
#define IntegerTwo RexxInteger::integerTwo
#define IntegerThree RexxInteger::integerThree
#define IntegerFour RexxInteger::integerFour
#define IntegerFive RexxInteger::integerFive
#define IntegerSix RexxInteger::integerSix
#define IntegerSeven RexxInteger::integerSeven
#define IntegerEight RexxInteger::integerEight
#define IntegerNine RexxInteger::integerNine
#define IntegerMinusOne RexxInteger::integerMinusOne
#define RXROUNDUP(n, to) ((((n)+(to-1))/(to))*to)
#define rounddown(n, to) (((n)/(to))*to)
#define isOfClass(t, r) (r)->isObjectType(The##t##Behaviour)
#define isOfClassType(t, r) (r)->isObjectType(T_##t)
#define env_find(s) (TheEnvironment->entry(s))
#define NO_THREAD -1
#define GLOBAL_NAME(name, value) EXTERN RexxString * OREF_##name INITGLOBALPTR;
Functions
bool isString (RexxObject *o)
bool isInteger (RexxObject *o)
bool isNumberString (RexxObject *o)
bool isPolymorphicString (RexxObject *o)
bool isArray (RexxObject *o)
bool isStem (RexxObject *o)
bool isActivation (RexxObject *o)
bool isMethod (RexxObject *o)
RexxString * REQUEST_STRING (RexxObject *object)
void requiredArgument (RexxObject *object, RexxString *kind, size_t position)
RexxString * stringArgument (RexxObject *object, RexxString *kind, size_t position)
RexxString * stringArgument (RexxObject *object, RexxString *kind, const char *name)
RexxString * optionalStringArgument (RexxObject *o, RexxString *d, RexxString *kind, size_t p)
RexxString * optionalStringArgument (RexxObject *o, RexxString *d, RexxString *kind, const char *p)
size_t lengthArgument (RexxObject *o, size_t p)
size_t optionalLengthArgument (RexxObject *o, size_t d, size_t p)
size_t positionArgument (RexxObject *o, size_t p)
size_t optionalPositionArgument (RexxObject *o, size_t d, size_t p)
codepoint_t padArgument (RexxObject *o, size_t p)
codepoint_t optionalPadArgument (RexxObject *o, codepoint_t d, size_t p)
char optionArgument (RexxObject *o, size_t p)
char optionalOptionArgument (RexxObject *o, char d, size_t p)
size_t optionalNonNegative (RexxObject *o, size_t d, RexxString *kind, size_t p)
size_t optionalPositive (RexxObject *o, size_t d, RexxString *kind, size_t p)
RexxArray * arrayArgument (RexxObject *object, RexxString *kind, size_t position)
RexxArray * arrayArgument (RexxObject *object, RexxString *kind, RexxString *name)
void classArgument (RexxObject *object, RexxClass *clazz, RexxString *kind, RexxString *name)
RexxArray * REQUEST_ARRAY (RexxObject *obj)
RexxInteger * REQUEST_INTEGER (RexxObject *obj)
RexxObject * callOperatorMethod (RexxObject *object, size_t methodOffset, RexxObject *argument)
Variables
const int MAX_ERROR_NUMBER = 99999
const int MAX_SYMBOL_LENGTH = 250
const int ARG_ONE = 1
const int ARG_TWO = 2
const int ARG_THREE = 3
const int ARG_FOUR = 4
const int ARG_FIVE = 5
const int ARG_SIX = 6
const int ARG_SEVEN = 7
const int ARG_EIGHT = 8
const int ARG_NINE = 9
const int ARG_TEN = 10
EXTERNMEM RexxMemory memoryObject
const size_t A_COUNT = 127
const int RC_OK = 0
const int RC_LOGIC_ERROR = 2
const int POSITIVE = 1
const int NONNEGATIVE = 2
const int WHOLE = 3
Macro Definition Documentation
CLASS_EXTERNAL
#define CLASS_EXTERNAL (b, c)
Definition at line 131 of file RexxCore.h.
CLASS_INTERNAL
#define CLASS_INTERNAL (b, c)
Definition at line 132 of file RexxCore.h.
env_find
#define env_find (s) (TheEnvironment->entry(s))
Definition at line 220 of file RexxCore.h.
EXTERN
#define EXTERN extern /* turn into external definition */
Definition at line 119 of file RexxCore.h.
EXTERNMEM
#define EXTERNMEM extern /* turn into external definition */
Definition at line 123 of file RexxCore.h.
GLOBAL_NAME
#define GLOBAL_NAME (name, value) EXTERN RexxString * OREF_##name INITGLOBALPTR;
Definition at line 232 of file RexxCore.h.
INITGLOBALPTR
#define INITGLOBALPTR
Definition at line 116 of file RexxCore.h.
IntegerEight
#define IntegerEight RexxInteger::integerEight
Definition at line 197 of file RexxCore.h.
IntegerFive
#define IntegerFive RexxInteger::integerFive
Definition at line 194 of file RexxCore.h.
IntegerFour
#define IntegerFour RexxInteger::integerFour
Definition at line 193 of file RexxCore.h.
IntegerMinusOne
#define IntegerMinusOne RexxInteger::integerMinusOne
Definition at line 199 of file RexxCore.h.
IntegerNine
#define IntegerNine RexxInteger::integerNine
Definition at line 198 of file RexxCore.h.
IntegerOne
#define IntegerOne RexxInteger::integerOne
Definition at line 190 of file RexxCore.h.
IntegerSeven
#define IntegerSeven RexxInteger::integerSeven
Definition at line 196 of file RexxCore.h.
IntegerSix
#define IntegerSix RexxInteger::integerSix
Definition at line 195 of file RexxCore.h.
IntegerThree
#define IntegerThree RexxInteger::integerThree
Definition at line 192 of file RexxCore.h.
IntegerTwo
#define IntegerTwo RexxInteger::integerTwo
Definition at line 191 of file RexxCore.h.
IntegerZero
#define IntegerZero RexxInteger::integerZero
Definition at line 189 of file RexxCore.h.
isOfClass
#define isOfClass (t, r) (r)->isObjectType(The##t##Behaviour)
Definition at line 212 of file RexxCore.h.
isOfClassType
#define isOfClassType (t, r) (r)->isObjectType(T_##t)
Definition at line 213 of file RexxCore.h.
koper
#define koper (name) RexxObject *name(RexxObject *);
Definition at line 134 of file RexxCore.h.
NO_THREAD
#define NO_THREAD -1
Definition at line 226 of file RexxCore.h.
OREF_NULL
#define OREF_NULL NULL /* definition of a NULL REXX object */
Definition at line 60 of file RexxCore.h.
OrefSet
#define OrefSet (o, r, v) ((o)->isOldSpace() ? memoryObject.setOref((void *)&(r),(RexxObject *)v) : (RexxObject *)(r=v))
Definition at line 94 of file RexxCore.h.
rounddown
#define rounddown (n, to) (((n)/(to))*to)
Definition at line 210 of file RexxCore.h.
RXROUNDUP
#define RXROUNDUP (n, to) ((((n)+(to-1))/(to))*to)
Definition at line 209 of file RexxCore.h.
TheArrayClass
#define TheArrayClass RexxArray::classInstance
Definition at line 147 of file RexxCore.h.
TheBufferClass
#define TheBufferClass RexxBuffer::classInstance
Definition at line 168 of file RexxCore.h.
TheClassClass
#define TheClassClass RexxClass::classInstance
Definition at line 148 of file RexxCore.h.
TheCommonRetrievers
#define TheCommonRetrievers RexxMemory::commonRetrievers
Definition at line 177 of file RexxCore.h.
TheDirectoryClass
#define TheDirectoryClass RexxDirectory::classInstance
Definition at line 149 of file RexxCore.h.
TheEnvironment
#define TheEnvironment RexxMemory::environment
Definition at line 174 of file RexxCore.h.
TheFalseObject
#define TheFalseObject RexxInteger::falseObject
Definition at line 185 of file RexxCore.h.
TheFunctionsDirectory
#define TheFunctionsDirectory RexxMemory::functionsDir
Definition at line 176 of file RexxCore.h.
TheIdentityTableClass
#define TheIdentityTableClass RexxIdentityTable::classInstance
Definition at line 165 of file RexxCore.h.
TheIntegerClass
#define TheIntegerClass RexxInteger::classInstance
Definition at line 150 of file RexxCore.h.
TheKernel
#define TheKernel RexxMemory::kernel
Definition at line 178 of file RexxCore.h.
TheListClass
#define TheListClass RexxList::classInstance
Definition at line 151 of file RexxCore.h.
TheMessageClass
#define TheMessageClass RexxMessage::classInstance
Definition at line 152 of file RexxCore.h.
TheMethodClass
#define TheMethodClass RexxMethod::classInstance
Definition at line 153 of file RexxCore.h.
TheMutableBufferClass
#define TheMutableBufferClass RexxMutableBuffer::classInstance
Definition at line 162 of file RexxCore.h.
TheNilObject
#define TheNilObject RexxNilObject::nilObject
Definition at line 181 of file RexxCore.h.
TheNullArray
#define TheNullArray RexxArray::nullArray
Definition at line 183 of file RexxCore.h.
TheNullPointer
#define TheNullPointer RexxPointer::nullPointer
Definition at line 187 of file RexxCore.h.
TheNumberStringClass
#define TheNumberStringClass RexxNumberString::classInstance
Definition at line 157 of file RexxCore.h.
TheObjectClass
#define TheObjectClass RexxObject::classInstance
Definition at line 158 of file RexxCore.h.
ThePackageClass
#define ThePackageClass PackageClass::classInstance
Definition at line 155 of file RexxCore.h.
ThePointerClass
#define ThePointerClass RexxPointer::classInstance
Definition at line 167 of file RexxCore.h.
TheQueueClass
#define TheQueueClass RexxQueue::classInstance
Definition at line 159 of file RexxCore.h.
TheRelationClass
#define TheRelationClass RexxRelation::classInstance
Definition at line 166 of file RexxCore.h.
TheRexxBlockClass
#define TheRexxBlockClass RexxBlock::classInstance
Definition at line 171 of file RexxCore.h.
TheRexxContextClass
#define TheRexxContextClass RexxContext::classInstance
Definition at line 156 of file RexxCore.h.
TheRexxTextClass
#define TheRexxTextClass RexxText::classInstance
Definition at line 172 of file RexxCore.h.
TheRoutineClass
#define TheRoutineClass RoutineClass::classInstance
Definition at line 154 of file RexxCore.h.
TheStackFrameClass
#define TheStackFrameClass StackFrameClass::classInstance
Definition at line 170 of file RexxCore.h.
TheStaticRequires
#define TheStaticRequires RexxMemory::staticRequires
Definition at line 175 of file RexxCore.h.
TheStemClass
#define TheStemClass RexxStem::classInstance
Definition at line 160 of file RexxCore.h.
TheStringClass
#define TheStringClass RexxString::classInstance
Definition at line 161 of file RexxCore.h.
TheSupplierClass
#define TheSupplierClass RexxSupplier::classInstance
Definition at line 163 of file RexxCore.h.
TheSystem
#define TheSystem RexxMemory::system
Definition at line 179 of file RexxCore.h.
TheTableClass
#define TheTableClass RexxTable::classInstance
Definition at line 164 of file RexxCore.h.
TheTrueObject
#define TheTrueObject RexxInteger::trueObject
Definition at line 186 of file RexxCore.h.
TheWeakReferenceClass
#define TheWeakReferenceClass WeakReference::classInstance
Definition at line 169 of file RexxCore.h.
Function Documentation
arrayArgument() [1/2]
RexxArray* arrayArgument (RexxObject * object, RexxString * kind, RexxString * name) inline
Definition at line 430 of file RexxCore.h.
References Error_Invalid_argument_noarg, Error_Invalid_argument_noarray, RexxArray::getDimension(), OREF_NULL, reportException(), RexxObject::requestArray(), and TheNilObject.
arrayArgument() [2/2]
RexxArray* arrayArgument (RexxObject * object, RexxString * kind, size_t position) inline
Definition at line 407 of file RexxCore.h.
References Error_Invalid_argument_noarray, RexxArray::getDimension(), missingArgument(), new_integer(), OREF_NULL, reportException(), RexxObject::requestArray(), and TheNilObject.
Referenced by RoutineClass::callWithRexx(), RexxObject::decodeMessageName(), PackageClass::loadPackage(), PackageClass::newRexx(), RexxNativeActivation::objectToValue(), RexxNativeActivation::processArguments(), RexxObject::sendWith(), RexxContext::setArgs(), and RexxObject::startWith().
callOperatorMethod()
RexxObject* callOperatorMethod (RexxObject * object, size_t methodOffset, RexxObject * argument) inline
Definition at line 533 of file RexxCore.h.
References RexxInternalObject::behaviour, and RexxBehaviour::getOperatorMethod().
Referenced by RexxInstructionDo::checkControl(), RexxInstructionDo::controlSetup(), RexxBinaryOperator::evaluate(), RexxUnaryOperator::evaluate(), and RexxInstructionDo::execute().
classArgument()
void classArgument (RexxObject * object, RexxClass * clazz, RexxString * kind, RexxString * name) inline
Definition at line 452 of file RexxCore.h.
References Error_Invalid_argument_noarg, Error_Invalid_argument_noclass, RexxClass::getId(), RexxObject::isInstanceOf(), OREF_NULL, and reportException().
Referenced by PackageClass::addClass(), PackageClass::addPackage(), PackageClass::addPublicClass(), PackageClass::addPublicRoutine(), and PackageClass::addRoutine().
isActivation()
bool isActivation (RexxObject * o) inline
Definition at line 275 of file RexxCore.h.
References isOfClass.
isArray()
bool isArray (RexxObject * o) inline
Definition at line 273 of file RexxCore.h.
References isOfClass.
Referenced by IsArray().
isInteger()
bool isInteger (RexxObject * o) inline
Definition at line 270 of file RexxCore.h.
References isOfClass.
Referenced by RexxCompoundTail::buildTail(), Numerics::int64Object(), isPolymorphicString(), Numerics::objectToInt64(), Numerics::objectToSignedInteger(), Numerics::objectToStringSize(), Numerics::objectToUnsignedInt64(), Numerics::objectToUnsignedInteger(), and Numerics::objectToWholeNumber().
isMethod()
bool isMethod (RexxObject * o) inline
Definition at line 276 of file RexxCore.h.
References isOfClass.
isNumberString()
bool isNumberString (RexxObject * o) inline
Definition at line 271 of file RexxCore.h.
References isOfClass, and RexxString::NumberString.
Referenced by isPolymorphicString().
isPolymorphicString()
bool isPolymorphicString (RexxObject * o) inline
Definition at line 272 of file RexxCore.h.
References isInteger(), isNumberString(), and isString().
Referenced by RexxInteger::andOp(), RexxString::andOp(), RexxString::comp(), RexxString::concatBlank(), RexxString::concatRexx(), RexxInteger::orOp(), RexxString::orOp(), RexxString::strictComp(), RexxString::strictEqual(), RexxString::strictNotEqual(), RexxInteger::xorOp(), and RexxString::xorOp().
isStem()
bool isStem (RexxObject * o) inline
Definition at line 274 of file RexxCore.h.
References isOfClass.
Referenced by RexxNativeActivation::objectToValue(), RexxNativeActivation::processArguments(), and RexxNativeActivation::resolveStemVariable().
isString()
bool isString (RexxObject * o) inline
Definition at line 269 of file RexxCore.h.
References isOfClass.
Referenced by RexxCompoundTail::buildTail(), RexxNativeActivation::dropContextVariable(), RexxNativeActivation::dropObjectVariable(), RexxNativeActivation::getContextVariable(), RexxNativeActivation::getObjectVariable(), RexxString::hash(), isPolymorphicString(), IsString(), RexxString::numberValue(), RexxNativeActivation::setContextVariable(), RexxNativeActivation::setObjectVariable(), RexxString::unsignedNumberValue(), RexxNativeActivation::variablePoolDropVariable(), RexxNativeActivation::variablePoolFetchVariable(), and RexxNativeActivation::variablePoolSetVariable().
lengthArgument()
size_t lengthArgument (RexxObject * o, size_t p)
Definition at line 58 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_method_length, missingArgument(), OREF_NULL, reportException(), and RexxObject::unsignedNumberValue().
Referenced by RexxString::center(), RexxString::left(), optionalLengthArgument(), RexxString::right(), and RexxMutableBuffer::setBufferSize().
optionalLengthArgument()
size_t optionalLengthArgument (RexxObject * o, size_t d, size_t p) inline
Definition at line 343 of file RexxCore.h.
References lengthArgument(), and OREF_NULL.
Referenced by RexxString::abbrev(), RexxString::caselessAbbrev(), RexxString::caselessCompareToRexx(), RexxMutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxMutableBuffer::caselessPos(), RexxString::caselessPosRexx(), RexxString::compareToRexx(), RexxNumberString::d2xD2c(), RexxString::delstr(), RexxString::delWord(), RexxMutableBuffer::delWord(), RexxMutableBuffer::insert(), RexxString::insert(), StringUtil::lastPosRexx(), RexxMutableBuffer::lower(), RexxString::lowerRexx(), RexxMutableBuffer::match(), RexxString::match(), RexxMutableBuffer::mydelete(), RexxMutableBufferClass::newRexx(), RexxMutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), RexxMutableBuffer::replaceAt(), RexxString::replaceAt(), RexxString::space(), RexxMutableBuffer::space(), StringUtil::substr(), StringUtil::subWord(), StringUtil::subWords(), RexxString::translate(), RexxMutableBuffer::translate(), RexxMutableBuffer::upper(), RexxString::upperRexx(), StringUtil::verify(), and RexxString::x2dC2d().
optionalNonNegative()
size_t optionalNonNegative (RexxObject * o, size_t d, RexxString * kind, size_t p) inline
Definition at line 394 of file RexxCore.h.
References OREF_NULL, and RexxObject::requiredNonNegative().
Referenced by RexxNumberString::formatRexx(), RexxMutableBuffer::insert(), and RexxNumberString::trunc().
optionalOptionArgument()
char optionalOptionArgument (RexxObject * o, char d, size_t p) inline
Definition at line 389 of file RexxCore.h.
References optionArgument(), and OREF_NULL.
Referenced by RexxString::dataType(), RexxString::strip(), and StringUtil::verify().
optionalPadArgument()
codepoint_t optionalPadArgument (RexxObject * o, codepoint_t d, size_t p) inline
Definition at line 382 of file RexxCore.h.
References OREF_NULL, and padArgument().
Referenced by RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), RexxString::caselessCompare(), RexxString::center(), RexxString::compare(), RexxMutableBuffer::insert(), RexxString::insert(), RexxString::left(), RexxMutableBuffer::overlay(), RexxString::overlay(), RexxMutableBuffer::replaceAt(), RexxString::replaceAt(), RexxString::right(), RexxString::space(), RexxMutableBuffer::space(), StringUtil::substr(), RexxString::translate(), and RexxMutableBuffer::translate().
optionalPositionArgument()
size_t optionalPositionArgument (RexxObject * o, size_t d, size_t p) inline
Definition at line 363 of file RexxCore.h.
References OREF_NULL, and positionArgument().
Referenced by RexxString::caselessCompareToRexx(), RexxMutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxMutableBuffer::caselessPos(), RexxString::caselessPosRexx(), StringUtil::caselessWordPos(), RexxString::compareToRexx(), StringUtil::lastPosRexx(), RexxMutableBuffer::lower(), RexxString::lowerRexx(), RexxMutableBuffer::match(), RexxString::match(), RexxMutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), StringUtil::subWords(), RexxString::translate(), RexxMutableBuffer::translate(), RexxMutableBuffer::upper(), RexxString::upperRexx(), StringUtil::verify(), and StringUtil::wordPos().
optionalPositive()
size_t optionalPositive (RexxObject * o, size_t d, RexxString * kind, size_t p) inline
Definition at line 399 of file RexxCore.h.
References OREF_NULL, and RexxObject::requiredPositive().
Referenced by RexxString::caselessChangeStr(), RexxMutableBuffer::caselessChangeStr(), RexxString::changeStr(), and RexxMutableBuffer::changeStr().
optionalStringArgument() [1/2]
RexxString* optionalStringArgument (RexxObject * o, RexxString * d, RexxString * kind, const char * p) inline
Definition at line 334 of file RexxCore.h.
References OREF_NULL, and stringArgument().
optionalStringArgument() [2/2]
RexxString* optionalStringArgument (RexxObject * o, RexxString * d, RexxString * kind, size_t p) inline
Definition at line 328 of file RexxCore.h.
References OREF_NULL, and stringArgument().
Referenced by RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), RexxString::strip(), RexxString::translate(), and RexxMutableBuffer::translate().
optionArgument()
char optionArgument (RexxObject * o, size_t p)
Definition at line 126 of file StringClassUtil.cpp.
References RexxString::getCharB(), and stringArgument().
Referenced by optionalOptionArgument().
padArgument()
codepoint_t padArgument (RexxObject * o, size_t p)
Definition at line 105 of file StringClassUtil.cpp.
References Error_Incorrect_method_pad, RexxString::getCharC(), RexxString::getCLength(), reportException(), and stringArgument().
Referenced by optionalPadArgument().
positionArgument()
size_t positionArgument (RexxObject * o, size_t p)
Definition at line 82 of file StringClassUtil.cpp.
References Numerics::ARGUMENT_DIGITS, Error_Incorrect_method_position, missingArgument(), OREF_NULL, reportException(), and RexxObject::unsignedNumberValue().
Referenced by RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxMutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), RexxString::delstr(), RexxString::delWord(), RexxMutableBuffer::delWord(), PackageClass::getSourceLineRexx(), RexxMutableBuffer::match(), RexxString::match(), RexxMutableBuffer::matchChar(), RexxString::matchChar(), RexxMutableBuffer::mydelete(), optionalPositionArgument(), RexxMutableBuffer::replaceAt(), RexxString::replaceAt(), StringUtil::subchar(), StringUtil::substr(), StringUtil::subWord(), StringUtil::word(), StringUtil::wordIndex(), and StringUtil::wordLength().
REQUEST_ARRAY()
RexxArray* REQUEST_ARRAY (RexxObject * obj) inline
Definition at line 469 of file RexxCore.h.
References RexxObject::requestArray().
Referenced by RexxInstructionDo::execute(), RexxInstructionForward::execute(), RexxInstructionRaise::execute(), RexxSupplier::initRexx(), RexxMessage::newRexx(), RexxObject::run(), RexxDirectory::unknown(), and RexxStem::unknown().
REQUEST_INTEGER()
RexxInteger* REQUEST_INTEGER (RexxObject * obj) inline
Definition at line 472 of file RexxCore.h.
References Numerics::ARGUMENT_DIGITS, and RexxObject::requestInteger().
Referenced by RexxList::getEntry(), and RexxQueue::locateEntry().
REQUEST_STRING()
RexxString* REQUEST_STRING (RexxObject * object) inline
Definition at line 283 of file RexxCore.h.
References isOfClass, and RexxObject::requestString().
Referenced by RexxActivity::callFunctionExit(), RexxString::comp(), RexxInteger::concat(), RexxObject::concatBlank(), RexxString::concatBlank(), RexxInteger::concatBlank(), RexxObject::concatRexx(), RexxString::concatRexx(), RexxInstructionDo::controlSetup(), RexxObject::copyIntoTail(), RexxActivity::display(), RexxActivity::displayDebug(), RexxInstructionAddress::execute(), RexxInstructionCall::execute(), RexxInstructionCommand::execute(), RexxInstructionDo::execute(), RexxInstructionForward::execute(), RexxInstructionInterpret::execute(), RexxInstructionNumeric::execute(), RexxInstructionOptions::execute(), RexxInstructionQueue::execute(), RexxInstructionRaise::execute(), RexxInstructionSay::execute(), RexxInstructionSignal::execute(), RexxInstructionTrace::execute(), RexxDirectory::fromIndexItemArray(), RexxObject::integerValue(), RexxString::isEqual(), RexxVariableReference::list(), RexxObject::logicalValue(), RexxClass::methodDictionaryCreate(), RexxClass::methodDictionaryMerge(), RexxTarget::next(), RexxObject::numberValue(), ObjectToString(), ObjectToStringValue(), RexxString::primitiveCaselessIsEqual(), RexxString::primitiveIsEqual(), RexxStem::sort(), RexxString::strictComp(), RexxTrigger::stringTrigger(), RexxObject::truthValue(), RexxObject::unsignedNumberValue(), RexxCompoundVariable::upper(), RexxStemVariable::upper(), and RexxParseVariable::upper().
requiredArgument()
void requiredArgument (RexxObject * object, RexxString * kind, size_t position) inline
Definition at line 291 of file RexxCore.h.
References missingArgument(), and OREF_NULL.
Referenced by RexxHashTableCollection::addRexx(), RexxRelation::allAt(), RexxHashTableCollection::allAt(), RexxRelation::allIndex(), RexxInteger::andOp(), RexxString::andOp(), RexxList::append(), RexxQueue::append(), RexxArray::appendRexx(), RexxNumberString::comp(), RexxString::comp(), RexxInteger::comp(), RexxInteger::concat(), RexxString::concatBlank(), RexxInteger::concatBlank(), RexxString::concatRexx(), RexxString::copies(), RexxObject::decodeMessageName(), RexxClass::defineClassMethod(), RexxNumberString::divide(), RexxClass::enhanced(), RexxClass::equal(), RexxObject::equal(), RexxPointer::equal(), RexxArray::fill(), RexxHashTableCollection::getRexx(), RexxHashTableCollection::hasIndexRexx(), RexxArray::hasItem(), RexxDirectory::hasItem(), RexxList::hasItem(), RexxRelation::hasItem(), RexxHashTableCollection::hasItemRexx(), RexxArray::index(), RexxList::index(), RexxQueue::index(), RexxDirectory::indexRexx(), RexxHashTableCollection::indexRexx(), RexxClass::inherit(), RexxSupplier::initRexx(), RexxQueue::insert(), RexxList::insertRexx(), RexxInteger::integerDivide(), RexxNumberString::integerDivide(), RexxString::isEqual(), RexxObject::isInstanceOfRexx(), RexxClass::isSubclassOf(), RexxInteger::multiply(), RexxNumberString::multiply(), RexxMessage::newRexx(), RexxMethod::newRexx(), RoutineClass::newRexx(), WeakReference::newRexx(), RexxClass::notEqual(), RexxObject::notEqual(), RexxPointer::notEqual(), RexxObject::objectNameEquals(), RexxInteger::orOp(), RexxString::orOp(), RexxNumberString::power(), RexxString::primitiveCaselessIsEqual(), RexxString::primitiveIsEqual(), RexxQueue::pushRexx(), RexxList::put(), RexxQueue::put(), RexxRelation::put(), RexxHashTableCollection::putRexx(), RexxQueue::queueRexx(), RexxInteger::remainder(), RexxNumberString::remainder(), RexxRelation::removeAll(), RexxArray::removeItem(), RexxDirectory::removeItem(), RexxList::removeItem(), RexxRelation::removeItemRexx(), RexxHashTableCollection::removeItemRexx(), RexxList::removeObject(), RexxHashTableCollection::removeRexx(), RexxObject::run(), RexxArray::sectionRexx(), RexxArray::stableSortWithRexx(), RexxObject::start(), RexxObject::startWith(), RexxString::strictComp(), RexxInteger::strictComp(), RexxObject::strictEqual(), RexxObject::strictNotEqual(), RexxTable::stringAdd(), RexxTable::stringPut(), RexxClass::uninherit(), RexxDirectory::unknown(), RexxStem::unknown(), RexxInteger::xorOp(), and RexxString::xorOp().
stringArgument() [1/2]
RexxString* stringArgument (RexxObject * object, RexxString * kind, const char * name) inline
Definition at line 317 of file RexxCore.h.
References Error_Invalid_argument_noarg, OREF_NULL, and reportException().
stringArgument() [2/2]
RexxString* stringArgument (RexxObject * object, RexxString * kind, size_t position) inline
Definition at line 303 of file RexxCore.h.
References missingArgument(), and OREF_NULL.
Referenced by RexxString::abbrev(), PackageClass::addClass(), PackageClass::addPublicClass(), PackageClass::addPublicRoutine(), PackageClass::addRoutine(), RexxMutableBuffer::append(), RexxDirectory::atRexx(), RexxNativeActivation::callRegisteredRoutine(), RexxString::caselessAbbrev(), RexxString::caselessChangeStr(), RexxMutableBuffer::caselessChangeStr(), RexxString::caselessCompare(), RexxString::caselessCompareToRexx(), RexxString::caselessCountStrRexx(), RexxMutableBuffer::caselessCountStrRexx(), RexxMutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxMutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), RexxMutableBuffer::caselessPos(), RexxString::caselessPosRexx(), StringUtil::caselessWordPos(), RexxString::changeStr(), RexxMutableBuffer::changeStr(), RexxString::compare(), RexxString::compareToRexx(), RexxString::countStrRexx(), RexxMutableBuffer::countStrRexx(), RexxObject::decodeMessageName(), RexxClass::defineClassMethod(), RexxClass::defineMethod(), RexxClass::deleteMethod(), RexxDirectory::entryRexx(), PackageClass::findClassRexx(), PackageClass::findRoutineRexx(), RexxDirectory::hasEntry(), RexxDirectory::hasIndex(), RexxObject::hasMethodRexx(), RexxMutableBuffer::insert(), RexxString::insert(), RexxObject::instanceMethod(), StringUtil::lastPosRexx(), RexxMethod::loadExternalMethod(), RoutineClass::loadExternalRoutine(), PackageClass::loadLibrary(), PackageClass::loadPackage(), StringUtil::makearray(), RexxMutableBuffer::match(), RexxString::match(), RexxMutableBuffer::matchChar(), RexxString::matchChar(), RexxClass::method(), RexxBehaviour::methodObject(), RexxMethod::newFileRexx(), RoutineClass::newFileRexx(), RexxMessage::newRexx(), RexxMethod::newRexx(), RexxMutableBufferClass::newRexx(), RoutineClass::newRexx(), RexxString::newRexx(), RexxClass::newRexx(), PackageClass::newRexx(), RexxObject::objectNameEquals(), RexxNativeActivation::objectToValue(), optionalStringArgument(), optionArgument(), RexxMutableBuffer::overlay(), RexxString::overlay(), padArgument(), StringUtil::posRexx(), RexxNativeActivation::processArguments(), RexxDirectory::put(), RexxDirectory::removeRexx(), RexxMutableBuffer::replaceAt(), RexxString::replaceAt(), RexxStem::request(), RexxObject::requestRexx(), RexxNativeActivation::resolveStemVariable(), RexxStem::RexxStem(), RexxObject::run(), RexxDirectory::setEntry(), RexxDirectory::setMethod(), RexxObject::setMethod(), RexxArray::toString(), RexxDirectory::unknown(), RexxStem::unknown(), RexxObject::unsetMethod(), SystemInterpreter::valueFunction(), StringUtil::verify(), and StringUtil::wordPos().
Variable Documentation
A_COUNT
const size_t A_COUNT = 127
Definition at line 250 of file RexxCore.h.
Referenced by RexxMemory::createImage(), and CPPCode::run().
ARG_EIGHT
const int ARG_EIGHT = 8
Definition at line 87 of file RexxCore.h.
ARG_FIVE
const int ARG_FIVE = 5
Definition at line 84 of file RexxCore.h.
ARG_FOUR
const int ARG_FOUR = 4
Definition at line 83 of file RexxCore.h.
Referenced by RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxNumberString::formatRexx(), RexxMutableBuffer::insert(), RexxString::insert(), RexxMutableBuffer::match(), RexxString::match(), RexxMutableBuffer::overlay(), RexxString::overlay(), RexxMutableBuffer::replaceAt(), RexxString::replaceAt(), RexxString::translate(), RexxMutableBuffer::translate(), and StringUtil::verify().
ARG_NINE
const int ARG_NINE = 9
Definition at line 88 of file RexxCore.h.
ARG_ONE
const int ARG_ONE = 1
Definition at line 80 of file RexxCore.h.
Referenced by RexxString::abbrev(), RexxHashTableCollection::addRexx(), RexxRelation::allAt(), RexxHashTableCollection::allAt(), RexxRelation::allIndex(), RexxArray::allIndexes(), RexxArray::allItems(), RexxInteger::andOp(), RexxString::andOp(), RexxList::append(), RexxMutableBuffer::append(), RexxQueue::append(), RexxArray::appendRexx(), RexxDirectory::atRexx(), RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), RoutineClass::callWithRexx(), RexxString::caselessAbbrev(), RexxString::caselessChangeStr(), RexxMutableBuffer::caselessChangeStr(), RexxString::caselessCompare(), RexxString::caselessCompareToRexx(), RexxString::caselessCountStrRexx(), RexxMutableBuffer::caselessCountStrRexx(), RexxMutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxMutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), RexxMutableBuffer::caselessPos(), RexxString::caselessPosRexx(), StringUtil::caselessWordPos(), RexxString::center(), RexxString::changeStr(), RexxMutableBuffer::changeStr(), RexxNumberString::comp(), RexxString::comp(), RexxInteger::comp(), RexxString::compare(), RexxString::compareToRexx(), RexxInteger::concat(), RexxString::concatBlank(), RexxInteger::concatBlank(), RexxString::concatRexx(), RexxString::copies(), RexxString::countStrRexx(), RexxMutableBuffer::countStrRexx(), RexxNumberString::d2xD2c(), RexxString::dataType(), RexxObject::decodeMessageName(), RexxClass::defineClassMethod(), RexxClass::defineMethod(), RexxClass::deleteMethod(), RexxString::delstr(), RexxString::delWord(), RexxMutableBuffer::delWord(), RexxArray::dimension(), RexxNumberString::divide(), RexxClass::enhanced(), RexxDirectory::entryRexx(), RexxClass::equal(), RexxObject::equal(), RexxPointer::equal(), RexxArray::fill(), RexxNumberString::formatRexx(), RexxHashTableCollection::getRexx(), PackageClass::getSourceLineRexx(), RexxDirectory::hasEntry(), RexxDirectory::hasIndex(), RexxHashTableCollection::hasIndexRexx(), RexxArray::hasItem(), RexxDirectory::hasItem(), RexxList::hasItem(), RexxRelation::hasItem(), RexxHashTableCollection::hasItemRexx(), RexxObject::hasMethodRexx(), RexxArray::index(), RexxList::index(), RexxQueue::index(), RexxDirectory::indexRexx(), RexxHashTableCollection::indexRexx(), RexxClass::inherit(), RexxSupplier::initRexx(), RexxQueue::insert(), RexxMutableBuffer::insert(), RexxString::insert(), RexxList::insertRexx(), RexxObject::instanceMethod(), RexxInteger::integerDivide(), RexxNumberString::integerDivide(), RexxString::isEqual(), RexxObject::isInstanceOfRexx(), RexxClass::isSubclassOf(), StringUtil::lastPosRexx(), RexxString::left(), RexxMutableBuffer::lower(), RexxString::lowerRexx(), StringUtil::makearray(), RexxMutableBuffer::match(), RexxString::match(), RexxMutableBuffer::matchChar(), RexxString::matchChar(), RexxClass::method(), RexxBehaviour::methodObject(), RexxInteger::multiply(), RexxNumberString::multiply(), RexxMutableBuffer::mydelete(), RexxMethod::newFileRexx(), RoutineClass::newFileRexx(), RexxMessage::newRexx(), RexxMethod::newRexx(), RexxMutableBufferClass::newRexx(), RoutineClass::newRexx(), RexxString::newRexx(), WeakReference::newRexx(), RexxClass::newRexx(), RexxClass::notEqual(), RexxObject::notEqual(), RexxPointer::notEqual(), RexxObject::objectNameEquals(), RexxArray::operator new(), RexxInteger::orOp(), RexxString::orOp(), RexxMutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), RexxNumberString::power(), RexxString::primitiveCaselessIsEqual(), RexxString::primitiveIsEqual(), RexxQueue::pushRexx(), RexxList::put(), RexxQueue::put(), RexxRelation::put(), RexxArray::putRexx(), RexxHashTableCollection::putRexx(), RexxQueue::queueRexx(), RexxInteger::remainder(), RexxNumberString::remainder(), RexxRelation::removeAll(), RexxArray::removeItem(), RexxDirectory::removeItem(), RexxList::removeItem(), RexxRelation::removeItemRexx(), RexxHashTableCollection::removeItemRexx(), RexxList::removeObject(), RexxHashTableCollection::removeRexx(), RexxDirectory::removeRexx(), RexxMutableBuffer::replaceAt(), RexxString::replaceAt(), RexxStem::request(), RexxObject::requestRexx(), RexxStem::RexxStem(), RexxString::right(), RexxObject::run(), RexxArray::sectionRexx(), RexxObject::send(), RexxContext::setArgs(), RexxMutableBuffer::setBufferSize(), RexxDirectory::setEntry(), RexxDirectory::setMethod(), RexxObject::setMethod(), RexxString::space(), RexxMutableBuffer::space(), RexxArray::stableSortWithRexx(), RexxObject::start(), RexxObject::startWith(), RexxString::strictComp(), RexxInteger::strictComp(), RexxObject::strictEqual(), RexxObject::strictNotEqual(), RexxTable::stringAdd(), RexxTable::stringPut(), RexxString::strip(), StringUtil::subchar(), StringUtil::substr(), StringUtil::subWord(), StringUtil::subWords(), RexxArray::supplier(), RexxArray::toString(), RexxString::translate(), RexxMutableBuffer::translate(), RexxNumberString::trunc(), RexxClass::uninherit(), RexxDirectory::unknown(), RexxStem::unknown(), RexxObject::unsetMethod(), RexxMutableBuffer::upper(), RexxString::upperRexx(), StringUtil::verify(), StringUtil::word(), StringUtil::wordIndex(), StringUtil::wordLength(), StringUtil::wordPos(), RexxString::x2dC2d(), RexxInteger::xorOp(), and RexxString::xorOp().
ARG_SEVEN
const int ARG_SEVEN = 7
Definition at line 86 of file RexxCore.h.
ARG_SIX
const int ARG_SIX = 6
Definition at line 85 of file RexxCore.h.
ARG_TEN
const int ARG_TEN = 10
Definition at line 89 of file RexxCore.h.
ARG_THREE
const int ARG_THREE = 3
Definition at line 82 of file RexxCore.h.
Referenced by RexxString::caselessChangeStr(), RexxMutableBuffer::caselessChangeStr(), RexxString::caselessCompareToRexx(), RexxMutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxMutableBuffer::caselessPos(), RexxString::caselessPosRexx(), RexxString::changeStr(), RexxMutableBuffer::changeStr(), RexxString::compareToRexx(), RexxNumberString::formatRexx(), RexxMutableBuffer::insert(), RexxString::insert(), StringUtil::lastPosRexx(), RexxMutableBuffer::match(), RexxString::match(), RexxMessage::newRexx(), RexxMutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), RexxMutableBuffer::replaceAt(), RexxString::replaceAt(), RexxObject::run(), RexxObject::setMethod(), StringUtil::substr(), RexxString::translate(), RexxMutableBuffer::translate(), and StringUtil::verify().
ARG_TWO
const int ARG_TWO = 2
Definition at line 81 of file RexxCore.h.
Referenced by RexxString::abbrev(), RexxHashTableCollection::addRexx(), RexxString::bitAnd(), RexxString::bitOr(), RexxString::bitXor(), RexxString::caselessAbbrev(), RexxString::caselessChangeStr(), RexxMutableBuffer::caselessChangeStr(), RexxString::caselessCompare(), RexxString::caselessCompareToRexx(), RexxMutableBuffer::caselessLastPos(), RexxString::caselessLastPosRexx(), RexxMutableBuffer::caselessMatch(), RexxString::caselessMatch(), RexxMutableBuffer::caselessMatchChar(), RexxString::caselessMatchChar(), RexxMutableBuffer::caselessPos(), RexxString::caselessPosRexx(), StringUtil::caselessWordPos(), RexxString::center(), RexxString::changeStr(), RexxMutableBuffer::changeStr(), RexxString::compare(), RexxString::compareToRexx(), RexxObject::decodeMessageName(), RexxClass::defineClassMethod(), RexxString::delstr(), RexxString::delWord(), RexxMutableBuffer::delWord(), RexxNumberString::formatRexx(), RexxSupplier::initRexx(), RexxMutableBuffer::insert(), RexxString::insert(), StringUtil::lastPosRexx(), RexxString::left(), RexxMutableBuffer::lower(), RexxString::lowerRexx(), RexxMutableBuffer::match(), RexxString::match(), RexxMutableBuffer::matchChar(), RexxString::matchChar(), RexxMutableBuffer::mydelete(), RexxMessage::newRexx(), RexxMethod::newRexx(), RexxMutableBufferClass::newRexx(), RoutineClass::newRexx(), RexxMutableBuffer::overlay(), RexxString::overlay(), StringUtil::posRexx(), RexxRelation::put(), RexxDirectory::put(), RexxHashTableCollection::putRexx(), RexxMutableBuffer::replaceAt(), RexxString::replaceAt(), RexxString::right(), RexxObject::run(), RexxList::section(), RexxQueue::section(), RexxArray::sectionRexx(), RexxObject::sendWith(), RexxString::space(), RexxMutableBuffer::space(), RexxObject::startWith(), RexxTable::stringAdd(), RexxTable::stringPut(), RexxString::strip(), StringUtil::substr(), StringUtil::subWord(), StringUtil::subWords(), RexxArray::toString(), RexxString::translate(), RexxMutableBuffer::translate(), RexxDirectory::unknown(), RexxStem::unknown(), RexxMutableBuffer::upper(), RexxString::upperRexx(), SystemInterpreter::valueFunction(), StringUtil::verify(), and StringUtil::wordPos().
MAX_ERROR_NUMBER
const int MAX_ERROR_NUMBER = 99999
Definition at line 73 of file RexxCore.h.
MAX_SYMBOL_LENGTH
const int MAX_SYMBOL_LENGTH = 250
Definition at line 74 of file RexxCore.h.
Referenced by RexxVariableDictionary::getDirectVariableRetriever(), RexxCompoundTail::init(), RexxString::isSymbol(), and RexxSource::sourceNextToken().
memoryObject
EXTERNMEM RexxMemory memoryObject
Definition at line 143 of file RexxCore.h.
NONNEGATIVE
const int NONNEGATIVE = 2
Definition at line 260 of file RexxCore.h.
POSITIVE
const int POSITIVE = 1
Definition at line 259 of file RexxCore.h.
RC_LOGIC_ERROR
const int RC_LOGIC_ERROR = 2
Definition at line 257 of file RexxCore.h.
Referenced by Interpreter::logicError().
RC_OK
const int RC_OK = 0
Definition at line 256 of file RexxCore.h.
Referenced by RexxMemory::createImage().
WHOLE
const int WHOLE = 3
Definition at line 261 of file RexxCore.h.