executor.master: StreamCommandParser.h File Reference
StreamCommandParser.h File Reference
#include <cctype>
#include <ctype.h>
#include "Utilities.hpp"
Classes
class StreamToken
class TokenDefinition
class ParseAction
Macros
#define no_token 1
Enumerations
enum ActionType {
NoAction , BitOr , BitAnd , MF ,
ME , MI , MEB , MIB ,
SetBool , SetItem , CallItem
}
Functions
int parser (TokenDefinition *ttsp, const char *TokenString, void *userparms)
Macro Definition Documentation
no_token
#define no_token 1
Definition at line 51 of file StreamCommandParser.h.
Enumeration Type Documentation
ActionType
enum ActionType
Enumerator
NoAction
BitOr
BitAnd
MF
ME
MI
MEB
MIB
SetBool
SetItem
CallItem
Definition at line 56 of file StreamCommandParser.h.
Function Documentation
parser()
int parser (TokenDefinition * ttsp, const char * TokenString, void * userparms)
Definition at line 121 of file StreamCommandParser.cpp.
References TokenDefinition::actions, TokenDefinition::callUnknown(), StreamToken::equals(), StreamToken::getLength(), TokenDefinition::isValid(), ParseAction::isValid(), TokenDefinition::minlength, StreamToken::nextToken(), StreamToken::previousToken(), and TokenDefinition::token.
Referenced by StreamInfo::handleOpen(), StreamInfo::queryStreamPosition(), StreamInfo::streamOpen(), and StreamInfo::streamPosition().