executor.master: ResourceSection Class Reference
ResourceSection Class Reference
#include <Interpreter.hpp>
Public Member Functions
ResourceSection (const char *ds, int di)
~ResourceSection ()
void release ()
void reacquire ()
Private Attributes
bool terminated
const char * dbgds
int dbgdi
Detailed Description
Block control for access to the resource lock.
Definition at line 154 of file Interpreter.hpp.
Constructor & Destructor Documentation
ResourceSection()
ResourceSection::ResourceSection (const char * ds, int di) inline
Definition at line 157 of file Interpreter.hpp.
References dbgdi, dbgds, Interpreter::getResourceLock(), and terminated.
~ResourceSection()
ResourceSection::~ResourceSection () inline
Definition at line 163 of file Interpreter.hpp.
References dbgdi, dbgds, Interpreter::releaseResourceLock(), and terminated.
Member Function Documentation
reacquire()
void ResourceSection::reacquire () inline
Definition at line 181 of file Interpreter.hpp.
References dbgdi, dbgds, Interpreter::getResourceLock(), and terminated.
Referenced by ActivityManager::addWaitingActivity(), and ActivityManager::createNewActivity().
release()
void ResourceSection::release () inline
Definition at line 171 of file Interpreter.hpp.
References dbgdi, dbgds, Interpreter::releaseResourceLock(), and terminated.
Referenced by ActivityManager::addWaitingActivity(), and ActivityManager::createNewActivity().
Member Data Documentation
dbgdi
int ResourceSection::dbgdi private
Definition at line 194 of file Interpreter.hpp.
Referenced by reacquire(), release(), ResourceSection(), and ~ResourceSection().
dbgds
const char* ResourceSection::dbgds private
Definition at line 193 of file Interpreter.hpp.
Referenced by reacquire(), release(), ResourceSection(), and ~ResourceSection().
terminated
bool ResourceSection::terminated private
Definition at line 192 of file Interpreter.hpp.
Referenced by reacquire(), release(), ResourceSection(), and ~ResourceSection().
The documentation for this class was generated from the following file:
Interpreter.hpp