executor.master: RexxSaveStack Class Reference
RexxSaveStack Class Reference
#include <StackClass.hpp>
Public Member Functions
void * operator new (size_t, size_t)
void operator delete (void *)
void operator delete (void *, size_t)
RexxSaveStack (size_t, size_t)
void live (size_t)
void init (size_t, size_t)
void extend (size_t)
void remove (RexxObject *, bool search=false)
Public Member Functions inherited from RexxStack
void * operator new (size_t size, void *ptr)
void * operator new (size_t, size_t, bool temporary)
void operator delete (void *)
void operator delete (void *, void *)
void operator delete (void *, size_t, bool temporary)
RexxStack (RESTORETYPE restoreType)
RexxStack (size_t size)
void init (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
RexxObject * get (size_t pos)
RexxObject * push (RexxObject *obj)
RexxObject * pop ()
RexxObject * fpop ()
void fastPush (RexxObject *element)
bool checkRoom ()
RexxObject * fastPop ()
size_t stackSize ()
RexxObject * stackTop ()
void decrementTop ()
void incrementTop ()
void copyEntries (RexxStack *other)
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Public Attributes
size_t allocSize
Public Attributes inherited from RexxStack
size_t size
size_t top
RexxObject * stack [1]
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 85 of file StackClass.hpp.
Constructor & Destructor Documentation
RexxSaveStack()
RexxSaveStack::RexxSaveStack (size_t _size, size_t aSize)
Definition at line 179 of file StackClass.cpp.
References allocSize.
Member Function Documentation
extend()
void RexxSaveStack::extend (size_t newSize)
Definition at line 214 of file StackClass.cpp.
References allocSize, and RexxStack::size.
init()
void RexxSaveStack::init (size_t _size, size_t aSize)
Definition at line 190 of file StackClass.cpp.
References allocSize, RexxInternalObject::clearObject(), RexxStack::size, and RexxStack::top.
live()
void RexxSaveStack::live (size_t liveMark) virtual
Reimplemented from RexxStack.
Definition at line 265 of file StackClass.cpp.
References RexxInternalObject::isObjectMarked(), memory_mark, OREF_NULL, RexxStack::stack, and RexxStack::stackSize().
operator delete() [1/2]
void RexxSaveStack::operator delete (void *) inline
Definition at line 88 of file StackClass.hpp.
operator delete() [2/2]
void RexxSaveStack::operator delete (void * , size_t) inline
Definition at line 89 of file StackClass.hpp.
operator new()
void * RexxSaveStack::operator new (size_t size, size_t allocSize)
Definition at line 203 of file StackClass.cpp.
References new_object(), and T_Stack.
remove()
void RexxSaveStack::remove (RexxObject * element, bool search = false)
Definition at line 226 of file StackClass.cpp.
References OREF_NULL, RexxStack::size, RexxStack::stack, and RexxStack::top.
Referenced by RexxMemory::removeHold(), and RexxMemory::removeSavedObject().
Member Data Documentation
allocSize
size_t RexxSaveStack::allocSize
Definition at line 97 of file StackClass.hpp.
Referenced by extend(), init(), and RexxSaveStack().
The documentation for this class was generated from the following files:
StackClass.hpp
StackClass.cpp