executor.master: RexxCompoundElement Class Reference
RexxCompoundElement Class Reference
#include <RexxCompoundElement.hpp>
Public Member Functions
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxCompoundElement (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
RexxCompoundElement * realVariable ()
void setParent (RexxCompoundElement *parentElement)
void setLeft (RexxCompoundElement *leftChild)
void setRight (RexxCompoundElement *rightChild)
void expose (RexxCompoundElement *real)
RexxString * createCompoundName (RexxString *stemName)
void setValue (RexxObject *value)
Public Member Functions inherited from RexxVariable
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxVariable ()
RexxVariable (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
void inform (RexxActivity *)
void drop ()
void notify ()
void uninform (RexxActivity *)
void set (RexxObject *value)
RexxObject * getVariableValue ()
RexxObject * getResolvedValue ()
RexxString * getName ()
void setName (RexxString *name)
void reset (RexxString *name)
void setCreator (RexxActivation *creatorActivation)
RexxVariable * getNext ()
void cache (RexxVariable *next)
bool isLocal (RexxActivation *act)
bool isStem ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Static Public Member Functions
static RexxCompoundElement * newInstance (RexxString *name)
Static Public Member Functions inherited from RexxVariable
static RexxVariable * newInstance (RexxString *name)
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Protected Attributes
RexxCompoundElement * left
RexxCompoundElement * right
RexxCompoundElement * parent
unsigned short leftdepth
unsigned short rightdepth
RexxCompoundElement * real_element
Protected Attributes inherited from RexxVariable
RexxString * variable_name
RexxObject * variableValue
RexxActivation * creator
RexxIdentityTable * dependents
Friends
class RexxCompoundTable
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 50 of file RexxCompoundElement.hpp.
Constructor & Destructor Documentation
RexxCompoundElement()
RexxCompoundElement::RexxCompoundElement (RESTORETYPE restoreType) inline
Definition at line 58 of file RexxCompoundElement.hpp.
Member Function Documentation
createCompoundName()
RexxString* RexxCompoundElement::createCompoundName (RexxString * stemName) inline
Definition at line 68 of file RexxCompoundElement.hpp.
References RexxString::concat(), and RexxVariable::getName().
Referenced by RexxNativeActivation::fetchNext().
expose()
void RexxCompoundElement::expose (RexxCompoundElement * real) inline
Definition at line 67 of file RexxCompoundElement.hpp.
References OrefSet, and real_element.
flatten()
void RexxCompoundElement::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 76 of file RexxCompoundElement.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
live()
void RexxCompoundElement::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 48 of file RexxCompoundElement.cpp.
References RexxVariable::dependents, left, memory_mark, parent, real_element, right, RexxVariable::variable_name, and RexxVariable::variableValue.
liveGeneral()
void RexxCompoundElement::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 62 of file RexxCompoundElement.cpp.
References RexxVariable::dependents, left, memory_mark_general, parent, real_element, right, RexxVariable::variable_name, and RexxVariable::variableValue.
newInstance()
RexxCompoundElement * RexxCompoundElement::newInstance (RexxString * name) static
Definition at line 95 of file RexxCompoundElement.cpp.
References new_object(), T_CompoundElement, and RexxVariable::variable_name.
Referenced by new_compoundElement().
operator delete() [1/2]
void RexxCompoundElement::operator delete (void *) inline
Definition at line 55 of file RexxCompoundElement.hpp.
operator delete() [2/2]
void RexxCompoundElement::operator delete (void * , void *) inline
Definition at line 56 of file RexxCompoundElement.hpp.
operator new()
void* RexxCompoundElement::operator new (size_t size, void * ptr) inline
Definition at line 54 of file RexxCompoundElement.hpp.
realVariable()
RexxCompoundElement* RexxCompoundElement::realVariable () inline
Definition at line 63 of file RexxCompoundElement.hpp.
References OREF_NULL, and real_element.
Referenced by RexxStem::exposeCompoundVariable(), RexxStem::findCompoundVariable(), and RexxStem::getCompoundVariable().
setLeft()
void RexxCompoundElement::setLeft (RexxCompoundElement * leftChild) inline
Definition at line 65 of file RexxCompoundElement.hpp.
References left, and OrefSet.
Referenced by RexxCompoundTable::findEntry(), and RexxCompoundTable::moveNode().
setParent()
void RexxCompoundElement::setParent (RexxCompoundElement * parentElement) inline
Definition at line 64 of file RexxCompoundElement.hpp.
References OrefSet, and parent.
Referenced by RexxCompoundTable::findEntry(), and RexxCompoundTable::moveNode().
setRight()
void RexxCompoundElement::setRight (RexxCompoundElement * rightChild) inline
Definition at line 66 of file RexxCompoundElement.hpp.
References OrefSet, and right.
Referenced by RexxCompoundTable::findEntry(), and RexxCompoundTable::moveNode().
setValue()
void RexxCompoundElement::setValue (RexxObject * value) inline
Definition at line 69 of file RexxCompoundElement.hpp.
References RexxVariable::set().
Referenced by RexxCompoundTable::copyFrom().
Friends And Related Function Documentation
RexxCompoundTable
friend class RexxCompoundTable friend
Definition at line 51 of file RexxCompoundElement.hpp.
Member Data Documentation
left
RexxCompoundElement* RexxCompoundElement::left protected
Definition at line 75 of file RexxCompoundElement.hpp.
Referenced by RexxCompoundTable::findEntry(), RexxCompoundTable::findLeaf(), live(), liveGeneral(), RexxCompoundTable::moveNode(), and setLeft().
leftdepth
unsigned short RexxCompoundElement::leftdepth protected
Definition at line 78 of file RexxCompoundElement.hpp.
Referenced by RexxCompoundTable::balance(), and RexxCompoundTable::moveNode().
parent
RexxCompoundElement* RexxCompoundElement::parent protected
Definition at line 77 of file RexxCompoundElement.hpp.
Referenced by RexxCompoundTable::balance(), live(), liveGeneral(), RexxCompoundTable::moveNode(), RexxCompoundTable::next(), and setParent().
real_element
RexxCompoundElement* RexxCompoundElement::real_element protected
Definition at line 80 of file RexxCompoundElement.hpp.
Referenced by expose(), live(), liveGeneral(), and realVariable().
right
RexxCompoundElement* RexxCompoundElement::right protected
Definition at line 76 of file RexxCompoundElement.hpp.
Referenced by RexxCompoundTable::balance(), RexxCompoundTable::findEntry(), RexxCompoundTable::findLeaf(), live(), liveGeneral(), RexxCompoundTable::moveNode(), RexxCompoundTable::next(), and setRight().
rightdepth
unsigned short RexxCompoundElement::rightdepth protected
Definition at line 79 of file RexxCompoundElement.hpp.
Referenced by RexxCompoundTable::balance(), and RexxCompoundTable::moveNode().
The documentation for this class was generated from the following files:
RexxCompoundElement.hpp
RexxCompoundElement.cpp