executor.master: SourceLocation Class Reference
SourceLocation Class Reference
#include <SourceLocation.hpp>
Public Member Functions
SourceLocation ()
size_t getLineNumber () const
sizeB_t getOffset () const
size_t getEndLine () const
sizeB_t getEndOffset () const
bool isLimitedTrace () const
void setLineNumber (size_t l)
void setOffset (sizeB_t l)
void setEndLine (size_t l)
void setEndOffset (sizeB_t l)
void setLimitedTrace (bool b)
void setStart (SourceLocation &l)
void setEnd (SourceLocation &l)
void setStart (size_t line, sizeB_t offset)
void setEnd (size_t line, sizeB_t offset)
void setLocation (size_t line, sizeB_t offset, size_t end, sizeB_t end_offset, bool limited_trace=false)
void setLocation (SourceLocation &l)
const SourceLocation & operator= (const SourceLocation &l)
Protected Attributes
size_t startLine
sizeB_t startOffset
size_t endLine
sizeB_t endOffset
bool limitedTrace
Detailed Description
Definition at line 48 of file SourceLocation.hpp.
Constructor & Destructor Documentation
SourceLocation()
SourceLocation::SourceLocation () inline
Definition at line 51 of file SourceLocation.hpp.
Member Function Documentation
getEndLine()
size_t SourceLocation::getEndLine () const inline
Definition at line 54 of file SourceLocation.hpp.
References endLine.
Referenced by RexxSource::addClause(), dumpTokensImpl(), RexxSource::extract(), RexxSource::extractSource(), RexxCode::getSource(), RexxSource::labelNew(), and setEnd().
getEndOffset()
sizeB_t SourceLocation::getEndOffset () const inline
Definition at line 55 of file SourceLocation.hpp.
References endOffset.
Referenced by RexxSource::addClause(), dumpTokensImpl(), RexxSource::extract(), RexxSource::extractSource(), RexxCode::getSource(), RexxSource::labelNew(), and setEnd().
getLineNumber()
size_t SourceLocation::getLineNumber () const inline
Definition at line 52 of file SourceLocation.hpp.
References startLine.
Referenced by RexxSource::addClause(), RexxSource::addText(), RexxSource::createStackFrame(), dumpTokensImpl(), RexxSource::errorPosition(), RexxSource::extract(), RexxSource::extractSource(), RexxInstruction::getLineNumber(), RexxInstructionIf::RexxInstructionIf(), setStart(), RexxSource::subExpression(), and RexxSource::traceBack().
getOffset()
sizeB_t SourceLocation::getOffset () const inline
Definition at line 53 of file SourceLocation.hpp.
References startOffset.
Referenced by RexxSource::addClause(), dumpTokensImpl(), RexxSource::errorPosition(), RexxSource::extract(), RexxSource::extractSource(), RexxInstructionIf::RexxInstructionIf(), setStart(), and RexxSource::subExpression().
isLimitedTrace()
bool SourceLocation::isLimitedTrace () const inline
Definition at line 56 of file SourceLocation.hpp.
References limitedTrace.
Referenced by RexxSource::errorToken(), and RexxSource::extract().
operator=()
const SourceLocation& SourceLocation::operator= (const SourceLocation & l) inline
Definition at line 110 of file SourceLocation.hpp.
References endLine, endOffset, limitedTrace, startLine, and startOffset.
setEnd() [1/2]
void SourceLocation::setEnd (size_t line, sizeB_t offset) inline
Definition at line 81 of file SourceLocation.hpp.
References endLine, endOffset, line, startLine, and startOffset.
setEnd() [2/2]
void SourceLocation::setEnd (SourceLocation & l) inline
Definition at line 70 of file SourceLocation.hpp.
References getEndLine(), and getEndOffset().
Referenced by RexxSource::endLocation(), RexxSource::extractSource(), RexxSource::nextClause(), RexxToken::setEnd(), RexxInstruction::setEnd(), RexxClause::setEnd(), and RexxSource::subExpression().
setEndLine()
void SourceLocation::setEndLine (size_t l) inline
Definition at line 60 of file SourceLocation.hpp.
References endLine.
Referenced by RexxSource::extractSource(), and RexxCode::getSource().
setEndOffset()
void SourceLocation::setEndOffset (sizeB_t l) inline
Definition at line 61 of file SourceLocation.hpp.
References endOffset.
Referenced by RexxSource::extractSource(), RexxCode::getSource(), and RexxSource::sourceNextToken().
setLimitedTrace()
void SourceLocation::setLimitedTrace (bool b) inline
Definition at line 62 of file SourceLocation.hpp.
References limitedTrace.
Referenced by RexxSource::comment(), RexxSource::errorToken(), and RexxSource::sourceLiteral().
setLineNumber()
void SourceLocation::setLineNumber (size_t l) inline
Definition at line 58 of file SourceLocation.hpp.
References startLine.
Referenced by RexxSource::extractSource().
setLocation() [1/2]
void SourceLocation::setLocation (size_t line, sizeB_t offset, size_t end, sizeB_t end_offset, bool limited_trace = false) inline
Definition at line 92 of file SourceLocation.hpp.
References endLine, endOffset, limitedTrace, line, startLine, and startOffset.
Referenced by RexxSource::sourceNextToken().
setLocation() [2/2]
void SourceLocation::setLocation (SourceLocation & l) inline
Definition at line 101 of file SourceLocation.hpp.
References endLine, endOffset, limitedTrace, startLine, and startOffset.
setOffset()
void SourceLocation::setOffset (sizeB_t l) inline
Definition at line 59 of file SourceLocation.hpp.
References startOffset.
Referenced by RexxSource::extractSource().
setStart() [1/2]
void SourceLocation::setStart (size_t line, sizeB_t offset) inline
Definition at line 75 of file SourceLocation.hpp.
References line, startLine, and startOffset.
setStart() [2/2]
void SourceLocation::setStart (SourceLocation & l) inline
Definition at line 64 of file SourceLocation.hpp.
References getLineNumber(), getOffset(), startLine, and startOffset.
Referenced by RexxInstruction::RexxInstruction(), RexxToken::setStart(), RexxInstruction::setStart(), RexxClause::setStart(), RexxSource::startLocation(), and RexxClause::trim().
Member Data Documentation
endLine
size_t SourceLocation::endLine protected
Definition at line 123 of file SourceLocation.hpp.
Referenced by getEndLine(), operator=(), setEnd(), setEndLine(), and setLocation().
endOffset
sizeB_t SourceLocation::endOffset protected
Definition at line 124 of file SourceLocation.hpp.
Referenced by getEndOffset(), operator=(), setEnd(), setEndOffset(), and setLocation().
limitedTrace
bool SourceLocation::limitedTrace protected
Definition at line 125 of file SourceLocation.hpp.
Referenced by isLimitedTrace(), operator=(), setLimitedTrace(), and setLocation().
startLine
size_t SourceLocation::startLine protected
Definition at line 121 of file SourceLocation.hpp.
Referenced by getLineNumber(), operator=(), setEnd(), setLineNumber(), setLocation(), and setStart().
startOffset
sizeB_t SourceLocation::startOffset protected
Definition at line 122 of file SourceLocation.hpp.
Referenced by getOffset(), operator=(), setEnd(), setLocation(), setOffset(), and setStart().
The documentation for this class was generated from the following file:
SourceLocation.hpp