executor.master: RexxDoBlock Class Reference
RexxDoBlock Class Reference
#include <DoBlock.hpp>
Public Member Functions
void * operator new (size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *, void *)
RexxDoBlock (RexxBlockInstruction *, size_t)
RexxDoBlock (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
RexxObject * getTo ()
wholenumber_t getFor ()
int getCompare ()
RexxObject * getBy ()
RexxBlockInstruction * getParent ()
void setTo (RexxObject *value)
void setBy (RexxObject *value)
void setCompare (int value)
void setFor (wholenumber_t value)
bool testFor ()
size_t getIndent ()
void setPrevious (RexxDoBlock *block)
RexxDoBlock * getPrevious ()
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * copy ()
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual void uninit ()
virtual HashCode hash ()
virtual HashCode getHashValue ()
HashCode identityHash ()
virtual bool truthValue (int)
virtual bool logicalValue (logical_t &)
virtual RexxString * makeString ()
virtual void copyIntoTail (RexxCompoundTail *buffer)
virtual RexxString * primitiveMakeString ()
virtual RexxArray * makeArray ()
virtual RexxString * stringValue ()
virtual RexxInteger * integerValue (size_t)
virtual bool numberValue (wholenumber_t &result, size_t precision)
virtual bool numberValue (wholenumber_t &result)
virtual bool unsignedNumberValue (stringsize_t &result, size_t precision)
virtual bool unsignedNumberValue (stringsize_t &result)
virtual bool doubleValue (double &result)
virtual RexxNumberString * numberString ()
virtual bool isEqual (RexxObject *)
virtual bool isInstanceOf (RexxClass *)
virtual RexxMethod * instanceMethod (RexxString *)
virtual RexxSupplier * instanceMethods (RexxClass *)
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Protected Attributes
RexxDoBlock * previous
RexxBlockInstruction * parent
RexxObject * to
RexxObject * by
wholenumber_t forcount
size_t indent
int compare
Additional Inherited Members
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 49 of file DoBlock.hpp.
Constructor & Destructor Documentation
RexxDoBlock() [1/2]
RexxDoBlock::RexxDoBlock (RexxBlockInstruction * _parent, size_t _indent)
Definition at line 49 of file DoBlock.cpp.
References indent, OrefSet, and parent.
RexxDoBlock() [2/2]
RexxDoBlock::RexxDoBlock (RESTORETYPE restoreType) inline
Definition at line 58 of file DoBlock.hpp.
Member Function Documentation
flatten()
void RexxDoBlock::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxVirtualBase.
Definition at line 82 of file DoBlock.cpp.
References cleanUpFlatten, flatten_reference, and setUpFlatten.
getBy()
RexxObject* RexxDoBlock::getBy () inline
Definition at line 66 of file DoBlock.hpp.
References by.
Referenced by RexxInstructionDo::checkControl().
getCompare()
int RexxDoBlock::getCompare () inline
Definition at line 65 of file DoBlock.hpp.
References compare.
Referenced by RexxInstructionDo::checkControl().
getFor()
wholenumber_t RexxDoBlock::getFor () inline
Definition at line 64 of file DoBlock.hpp.
References forcount.
Referenced by RexxInstructionDo::checkOver().
getIndent()
size_t RexxDoBlock::getIndent () inline
Definition at line 73 of file DoBlock.hpp.
References indent.
Referenced by RexxInstructionEnd::execute(), RexxActivation::iterate(), RexxInstructionDo::terminate(), RexxInstructionSelect::terminate(), and RexxActivation::terminateBlock().
getParent()
RexxBlockInstruction* RexxDoBlock::getParent () inline
Definition at line 67 of file DoBlock.hpp.
References parent.
Referenced by RexxInstructionEnd::execute(), RexxActivation::iterate(), and RexxActivation::leaveLoop().
getPrevious()
RexxDoBlock* RexxDoBlock::getPrevious () inline
Definition at line 75 of file DoBlock.hpp.
References previous.
Referenced by RexxActivation::popBlock().
getTo()
RexxObject* RexxDoBlock::getTo () inline
Definition at line 63 of file DoBlock.hpp.
References to.
Referenced by RexxInstructionDo::checkControl(), and RexxInstructionDo::checkOver().
live()
void RexxDoBlock::live (size_t liveMark) virtual
Reimplemented from RexxVirtualBase.
Definition at line 60 of file DoBlock.cpp.
References by, memory_mark, parent, previous, and to.
liveGeneral()
void RexxDoBlock::liveGeneral (int reason) virtual
Reimplemented from RexxVirtualBase.
Definition at line 71 of file DoBlock.cpp.
References by, memory_mark_general, parent, previous, and to.
operator delete() [1/2]
void RexxDoBlock::operator delete (void *) inline
Definition at line 54 of file DoBlock.hpp.
operator delete() [2/2]
void RexxDoBlock::operator delete (void * , void *) inline
Definition at line 55 of file DoBlock.hpp.
operator new() [1/2]
void* RexxDoBlock::operator new (size_t size, void * ptr) inline
Definition at line 53 of file DoBlock.hpp.
operator new() [2/2]
void * RexxDoBlock::operator new (size_t size)
Definition at line 96 of file DoBlock.cpp.
References new_object(), and T_DoBlock.
setBy()
void RexxDoBlock::setBy (RexxObject * value) inline
Definition at line 69 of file DoBlock.hpp.
References by.
Referenced by RexxInstructionDo::controlSetup().
setCompare()
void RexxDoBlock::setCompare (int value) inline
Definition at line 70 of file DoBlock.hpp.
References compare.
Referenced by RexxInstructionDo::controlSetup().
setFor()
void RexxDoBlock::setFor (wholenumber_t value) inline
Definition at line 71 of file DoBlock.hpp.
References forcount.
Referenced by RexxInstructionDo::checkOver(), RexxInstructionDo::controlSetup(), and RexxInstructionDo::execute().
setPrevious()
void RexxDoBlock::setPrevious (RexxDoBlock * block) inline
Definition at line 74 of file DoBlock.hpp.
References previous.
Referenced by RexxActivation::pushBlock().
setTo()
void RexxDoBlock::setTo (RexxObject * value) inline
Definition at line 68 of file DoBlock.hpp.
References to.
Referenced by RexxInstructionDo::controlSetup(), and RexxInstructionDo::execute().
testFor()
bool RexxDoBlock::testFor () inline
Definition at line 72 of file DoBlock.hpp.
References forcount.
Referenced by RexxInstructionDo::checkControl(), RexxInstructionDo::execute(), and RexxInstructionDo::reExecute().
Member Data Documentation
by
RexxObject* RexxDoBlock::by protected
Definition at line 82 of file DoBlock.hpp.
Referenced by getBy(), live(), liveGeneral(), and setBy().
compare
int RexxDoBlock::compare protected
Definition at line 85 of file DoBlock.hpp.
Referenced by getCompare(), and setCompare().
forcount
wholenumber_t RexxDoBlock::forcount protected
Definition at line 83 of file DoBlock.hpp.
Referenced by getFor(), setFor(), and testFor().
indent
size_t RexxDoBlock::indent protected
Definition at line 84 of file DoBlock.hpp.
Referenced by getIndent(), and RexxDoBlock().
parent
RexxBlockInstruction* RexxDoBlock::parent protected
Definition at line 80 of file DoBlock.hpp.
Referenced by getParent(), live(), liveGeneral(), and RexxDoBlock().
previous
RexxDoBlock* RexxDoBlock::previous protected
Definition at line 79 of file DoBlock.hpp.
Referenced by getPrevious(), live(), liveGeneral(), and setPrevious().
to
RexxObject* RexxDoBlock::to protected
Definition at line 81 of file DoBlock.hpp.
Referenced by getTo(), live(), liveGeneral(), and setTo().
The documentation for this class was generated from the following files:
DoBlock.hpp
DoBlock.cpp