executor.master: APIServerInstance Class Reference
APIServerInstance Class Reference
#include <APIServerInstance.hpp>
Public Member Functions
APIServerInstance (ServiceMessage &m)
virtual ~APIServerInstance ()
virtual bool isStoppable ()
void cleanupProcessResources (ServiceMessage &message)
bool isUser (ServiceMessage &message)
void dispatch (ServiceMessage &message)
Public Attributes
ServerQueueManager queueManager
ServerRegistrationManager registrationManager
ServerMacroSpaceManager macroSpaceManager
Protected Attributes
APIServerInstance * next
char userid [MAX_USERID_LENGTH]
Friends
class APIServer
Detailed Description
Definition at line 47 of file APIServerInstance.hpp.
Constructor & Destructor Documentation
APIServerInstance()
APIServerInstance::APIServerInstance (ServiceMessage & m)
Definition at line 46 of file APIServerInstance.cpp.
References ServiceMessage::userid, and userid.
~APIServerInstance()
virtual APIServerInstance::~APIServerInstance () inline virtual
Definition at line 52 of file APIServerInstance.hpp.
Member Function Documentation
cleanupProcessResources()
void APIServerInstance::cleanupProcessResources (ServiceMessage & message)
Cleanup sessions specific resources after a Rexx process terminates.
Parameters
message The service message with the session information.
Definition at line 88 of file APIServerInstance.cpp.
References ServerMacroSpaceManager::cleanupProcessResources(), ServerQueueManager::cleanupProcessResources(), ServerRegistrationManager::cleanupProcessResources(), macroSpaceManager, queueManager, registrationManager, and ServiceMessage::session.
Referenced by APIServer::cleanupProcessResources().
dispatch()
void APIServerInstance::dispatch (ServiceMessage & message)
Dispatch an API server control message.
Parameters
message The control message parameter.
Definition at line 56 of file APIServerInstance.cpp.
References APIManager, ServerMacroSpaceManager::dispatch(), ServerQueueManager::dispatch(), ServerRegistrationManager::dispatch(), MacroSpaceManager, macroSpaceManager, ServiceMessage::messageTarget, QueueManager, queueManager, RegistrationManager, and registrationManager.
Referenced by APIServer::processMessages().
isStoppable()
bool APIServerInstance::isStoppable () virtual
Test to see if the api server is in a state where it can be stopped. A stoppable state implies there are no session specific resources currently active in the server.
Returns
True if the server is stoppable, false otherwise.
Definition at line 102 of file APIServerInstance.cpp.
References ServerMacroSpaceManager::isStoppable(), ServerQueueManager::isStoppable(), ServerRegistrationManager::isStoppable(), macroSpaceManager, queueManager, and registrationManager.
Referenced by APIServer::isStoppable().
isUser()
bool APIServerInstance::isUser (ServiceMessage & message) inline
Definition at line 56 of file APIServerInstance.hpp.
References ServiceMessage::userid, and userid.
Referenced by APIServer::getInstance().
Friends And Related Function Documentation
APIServer
friend class APIServer friend
Definition at line 49 of file APIServerInstance.hpp.
Member Data Documentation
macroSpaceManager
ServerMacroSpaceManager APIServerInstance::macroSpaceManager
Definition at line 63 of file APIServerInstance.hpp.
Referenced by cleanupProcessResources(), dispatch(), and isStoppable().
next
APIServerInstance* APIServerInstance::next protected
Definition at line 67 of file APIServerInstance.hpp.
Referenced by APIServer::getInstance(), and APIServer::isStoppable().
queueManager
ServerQueueManager APIServerInstance::queueManager
Definition at line 59 of file APIServerInstance.hpp.
Referenced by cleanupProcessResources(), dispatch(), and isStoppable().
registrationManager
ServerRegistrationManager APIServerInstance::registrationManager
Definition at line 61 of file APIServerInstance.hpp.
Referenced by cleanupProcessResources(), dispatch(), and isStoppable().
userid
char APIServerInstance::userid[MAX_USERID_LENGTH] protected
Definition at line 68 of file APIServerInstance.hpp.
Referenced by APIServerInstance(), and isUser().
The documentation for this class was generated from the following files:
APIServerInstance.hpp
APIServerInstance.cpp