executor.master: RexxStem Class Reference
RexxStem Class Reference
#include <StemClass.hpp>
Public Member Functions
void * operator new (size_t)
void * operator new (size_t size, void *ptr)
RexxStem (RexxString *)
RexxStem (RESTORETYPE restoreType)
void live (size_t)
void liveGeneral (int reason)
void flatten (RexxEnvelope *)
RexxObject * copy ()
void copyFrom (RexxCompoundTable &_tails)
bool numberValue (wholenumber_t &result, size_t precision)
bool numberValue (wholenumber_t &result)
bool unsignedNumberValue (stringsize_t &result, size_t precision)
bool unsignedNumberValue (stringsize_t &result)
bool doubleValue (double &result)
RexxNumberString * numberString ()
RexxInteger * integerValue (size_t)
RexxString * stringValue ()
RexxArray * makeArray ()
RexxArray * allItems ()
RexxArray * allIndexes ()
RexxSupplier * supplier ()
RexxDirectory * toDirectory ()
RexxObject * request (RexxString *)
RexxObject * empty ()
RexxObject * isEmpty ()
size_t items ()
void dropValue ()
RexxObject * getStemValue ()
RexxObject * unknown (RexxString *, RexxArray *, RexxDirectory *)
RexxObject * bracket (RexxObject **, size_t, size_t)
RexxObject * bracketEqual (RexxObject **, size_t, size_t)
RexxObject * hasIndex (RexxObject **, size_t, size_t)
RexxObject * remove (RexxObject **, size_t, size_t)
RexxObject * hasItem (RexxObject *)
RexxObject * index (RexxObject *)
RexxObject * itemsRexx ()
RexxObject * removeItem (RexxObject *)
RexxString * tail (RexxArray *, size_t)
RexxObject * newRexx (RexxObject **, size_t, size_t)
RexxObject * evaluateCompoundVariableValue (RexxActivation *context, RexxString *stemVariableName, RexxCompoundTail *resolved_tail)
RexxObject * getCompoundVariableValue (RexxCompoundTail *resolved_tail)
RexxObject * getCompoundVariableRealValue (RexxCompoundTail *resolved_tail)
RexxObject * realCompoundVariableValue (RexxCompoundTail *resolved_tail)
RexxCompoundElement * getCompoundVariable (RexxCompoundTail *name)
RexxCompoundElement * exposeCompoundVariable (RexxCompoundTail *name)
RexxCompoundElement * findCompoundVariable (RexxCompoundTail *name)
RexxCompoundElement * findByValue (RexxObject *target)
void dropCompoundVariable (RexxCompoundTail *name)
void setCompoundVariable (RexxCompoundTail *name, RexxObject *value)
void setValue (RexxObject *value)
RexxArray * tailArray ()
RexxCompoundElement * nextVariable (RexxNativeActivation *activation)
RexxObject * handleNovalue (RexxActivation *context, RexxString *name, RexxObject *defaultValue, RexxCompoundElement *variable)
void expose (RexxCompoundElement *variable)
bool sort (RexxString *prefix, int order, int type, size_t start, size_t end, size_t firstcol, size_t lastcol)
void mergeSort (SortData *sd, int(*comparator)(SortData *, RexxString *, RexxString *), RexxString **strings, RexxString **working, size_t left, size_t right)
void merge (SortData *sd, int(*comparator)(SortData *, RexxString *, RexxString *), RexxString **strings, RexxString **working, size_t left, size_t mid, size_t right)
size_t find (SortData *sd, int(*comparator)(SortData *, RexxString *, RexxString *), RexxString **strings, RexxString *val, int bnd, size_t left, size_t right)
void arraycopy (RexxString **source, size_t start, RexxString **target, size_t index, size_t count)
bool compoundVariableExists (RexxCompoundTail *resolved_tail)
RexxString * getName ()
RexxCompoundElement * first ()
RexxString * createCompoundName (RexxCompoundTail *tailPart)
void init ()
void setElement (const char *tail, RexxObject *value)
void setElement (size_t tail, RexxObject *value)
void dropElement (const char *tail)
void dropElement (size_t tail)
void dropElement (RexxCompoundTail *tail)
RexxObject * getElement (size_t tail)
RexxObject * getElement (const char *tail)
RexxObject * getElement (RexxCompoundTail *tail)
Public Member Functions inherited from RexxObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *objectPtr)
void operator delete (void *, void *)
void operator delete (void *)
void operator delete (void *, RexxClass *)
void operator delete (void *, RexxClass *, RexxObject **, size_t)
RexxObject * newRexx (RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxObject * newObject ()
operator RexxInternalObject * ()
RexxObject ()
RexxObject (RESTORETYPE restoreType)
void initializeNewObject (size_t size, size_t mark, void *vft, RexxBehaviour *b)
void initializeNewObject (size_t mark, void *vft, RexxBehaviour *b)
virtual ~RexxObject ()
virtual RexxObject * defMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
virtual RexxString * defaultName ()
virtual RexxInteger * hasMethod (RexxString *msg)
bool hasUninitMethod ()
RexxObject * init ()
void uninit ()
HashCode hash ()
bool truthValue (int)
virtual bool logicalValue (logical_t &)
RexxString * makeString ()
RexxString * primitiveMakeString ()
void copyIntoTail (RexxCompoundTail *buffer)
RexxString * requestString ()
RexxString * requestStringNoNOSTRING ()
RexxInteger * requestInteger (size_t)
bool requestNumber (wholenumber_t &, size_t)
bool requestUnsignedNumber (stringsize_t &, size_t)
RexxArray * requestArray ()
RexxDirectory * requestDirectory ()
RexxString * requiredString (RexxString *kind, size_t)
RexxString * requiredString (RexxString *kind, const char *)
RexxString * requiredString ()
RexxInteger * requiredInteger (RexxString *kind, size_t, size_t)
wholenumber_t requiredNumber (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredPositive (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
stringsize_t requiredNonNegative (RexxString *kind, size_t position, size_t precision=Numerics::ARGUMENT_DIGITS)
bool isEqual (RexxObject *)
bool isInstanceOf (RexxClass *)
RexxObject * isInstanceOfRexx (RexxClass *)
RexxMethod * instanceMethod (RexxString *)
RexxSupplier * instanceMethods (RexxClass *)
RexxMethod * instanceMethodRexx (RexxString *)
RexxSupplier * instanceMethodsRexx (RexxClass *)
RexxString * objectName ()
RexxObject * objectNameEquals (RexxObject *)
RexxClass * classObject ()
RexxObject * setMethod (RexxString *, RexxMethod *, RexxString *a=OREF_NULL)
RexxObject * unsetMethod (RexxString *)
RexxObject * requestRexx (RexxString *)
RexxMessage * start (RexxObject **, size_t, size_t)
RexxMessage * startWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxObject * send (RexxObject **, size_t, size_t)
RexxObject * sendWith (RexxObject *, RexxArray *, RexxObject **, size_t)
RexxMessage * startCommon (RexxObject *message, RexxObject **arguments, size_t argCount, size_t named_argCount)
RexxString * oref ()
RexxObject * pmdict ()
RexxObject * run (RexxObject **, size_t, size_t)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, ProtectedObject &, bool processUnknown=true)
bool messageSend (RexxString *, RexxObject **, size_t, size_t, RexxObject *, ProtectedObject &, bool processUnknown=true)
RexxMethod * checkPrivate (RexxMethod *)
void processUnknown (RexxString *, RexxObject **, size_t, size_t, ProtectedObject &)
void processProtectedMethod (RexxString *, RexxMethod *, RexxObject **, size_t, size_t, ProtectedObject &)
void sendMessage (RexxString *, RexxArray *, RexxDirectory *, ProtectedObject &)
void sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount, ProtectedObject &result)
void sendMessage (RexxString *message, ProtectedObject &result)
void sendMessage (RexxString *message, RexxObject *argument1, ProtectedObject &result)
void sendMessage (RexxString *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
void sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, ProtectedObject &)
RexxObject * sendMessage (RexxString *, RexxArray *, RexxDirectory *=OREF_NULL)
RexxObject * sendMessage (RexxString *message, RexxObject **args, size_t argCount, size_t named_argCount)
RexxObject * sendMessage (RexxString *message)
RexxObject * sendMessage (RexxString *message, RexxObject *argument1)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * sendMessage (RexxString *, RexxObject *, RexxObject *, RexxObject *, RexxObject *, RexxObject *)
RexxObject * defMethods (RexxDirectory *)
void setObjectVariable (RexxString *, RexxObject *, RexxObject *)
RexxObject * getObjectVariable (RexxString *)
RexxObject * getObjectVariable (RexxString *, RexxObject *)
void addObjectVariables (RexxVariableDictionary *)
void copyObjectVariables (RexxObject *newObject)
RexxObject * superScope (RexxObject *)
RexxMethod * superMethod (RexxString *, RexxObject *)
RexxObject * mdict ()
RexxObject * setMdict (RexxObject *)
RexxBehaviour * behaviourObject ()
const char * idString ()
RexxString * id ()
RexxMethod * methodLookup (RexxString *name)
RexxVariableDictionary * getObjectVariables (RexxObject *)
void guardOn (RexxActivity *activity, RexxObject *scope)
void guardOff (RexxActivity *activity, RexxObject *scope)
RexxObject * equal (RexxObject *)
RexxObject * notEqual (RexxObject *other)
RexxObject * strictEqual (RexxObject *)
RexxObject * strictNotEqual (RexxObject *other)
RexxInteger * identityHashRexx ()
RexxObject * hashCode ()
RexxString * stringRexx ()
RexxString * concatRexx (RexxObject *)
RexxString * concatBlank (RexxObject *)
RexxObject * makeStringRexx ()
RexxObject * makeArrayRexx ()
RexxString * defaultNameRexx ()
RexxObject * copyRexx ()
RexxObject * unknownRexx (RexxString *, RexxArray *, RexxObject **, size_t)
RexxObject * hasMethodRexx (RexxString *)
void * getCSelf ()
void * getCSelf (RexxObject *scope)
bool equalValue (RexxObject *other)
virtual wholenumber_t compareTo (RexxObject *)
koper (operator_plus) koper(operator_minus) koper(operator_multiply) koper(operator_divide) koper(operator_integerDivide) koper(operator_remainder) koper(operator_power) koper(operator_abuttal) koper(operator_concat) koper(operator_concatBlank) koper(operator_equal) koper(operator_notEqual) koper(operator_isGreaterThan) koper(operator_isBackslashGreaterThan) koper(operator_isLessThan) koper(operator_isBackslashLessThan) koper(operator_isGreaterOrEqual) koper(operator_isLessOrEqual) koper(operator_strictEqual) koper(operator_strictNotEqual) koper(operator_strictGreaterThan) koper(operator_strictBackslashGreaterThan) koper(operator_strictLessThan) koper(operator_strictBackslashLessThan) koper(operator_strictGreaterOrEqual) koper(operator_strictLessOrEqual) koper(operator_lessThanGreaterThan) koper(operator_greaterThanLessThan) koper(operator_and) koper(operator_or) koper(operator_xor) koper(operator_not) RexxVariableDictionary *objectVariables
Public Member Functions inherited from RexxInternalObject
void * operator new (size_t, RexxClass *)
void * operator new (size_t, RexxClass *, RexxObject **, size_t, size_t)
void * operator new (size_t size, void *ptr)
void operator delete (void *)
void operator delete (void *p, void *ptr)
RexxInternalObject ()
RexxInternalObject (RESTORETYPE restoreType)
virtual ~RexxInternalObject ()
operator RexxObject * ()
size_t getObjectSize ()
void setObjectSize (size_t s)
size_t getObjectDataSize ()
void * getObjectDataSpace ()
void clearObject ()
void clearObject (size_t l)
void setVirtualFunctions (void *t)
void setInitHeader (size_t s, size_t markword)
void setInitHeader (size_t markword)
void setObjectLive (size_t markword)
void setHasReferences ()
void setHasNoReferences ()
bool hasReferences ()
bool hasNoReferences ()
void setPrimitive ()
void setNonPrimitive ()
bool isPrimitive ()
bool isNonPrimitive ()
bool isObjectMarked (size_t markword)
void setObjectMark (size_t markword)
void clearObjectMark ()
bool isObjectLive (size_t mark)
bool isObjectDead (size_t mark)
bool isOldSpace ()
bool isNewSpace ()
void setNewSpace ()
void setOldSpace ()
void makeProxiedObject ()
bool isProxyObject ()
bool isSubClassOrEnhanced ()
bool isBaseClass ()
size_t getObjectTypeNumber ()
RexxBehaviour * getObjectType ()
bool isObjectType (RexxBehaviour *b)
bool isObjectType (size_t t)
bool isSameType (RexxInternalObject *o)
void setBehaviour (RexxBehaviour *b)
virtual RexxObject * makeProxy (RexxEnvelope *)
virtual RexxObject * evaluate (RexxActivation *, RexxExpressionStack *)
virtual RexxObject * getValue (RexxActivation *)
virtual RexxObject * getValue (RexxVariableDictionary *)
virtual RexxObject * getRealValue (RexxActivation *)
virtual RexxObject * getRealValue (RexxVariableDictionary *)
virtual HashCode getHashValue ()
HashCode identityHash ()
void hasUninit ()
void removedUninit ()
void printObject ()
RexxObject * clone ()
Public Member Functions inherited from RexxVirtualBase
virtual RexxObject * unflatten (RexxEnvelope *)
Static Public Member Functions
static void createInstance ()
Static Public Member Functions inherited from RexxObject
static void decodeMessageName (RexxObject *target, RexxObject *message, RexxString *&messageName, RexxObject *&startScope)
static void createInstance ()
Static Public Member Functions inherited from RexxInternalObject
static size_t getObjectHeaderSize ()
Static Public Attributes
static RexxClass * classInstance = OREF_NULL
Static Public Attributes inherited from RexxObject
static PCPPM operatorMethods []
static RexxClass * classInstance = OREF_NULL
Protected Attributes
RexxString * stemName
RexxCompoundTable tails
RexxObject * value
bool dropped
Friends
class RexxCompoundTable
Additional Inherited Members
Public Attributes inherited from RexxInternalObject
ObjectHeader header
RexxBehaviour * behaviour
Protected Member Functions inherited from RexxVirtualBase
virtual ~RexxVirtualBase ()
virtual void baseVirtual ()
Detailed Description
Definition at line 70 of file StemClass.hpp.
Constructor & Destructor Documentation
RexxStem() [1/2]
RexxStem::RexxStem (RexxString * name)
Definition at line 69 of file StemClass.cpp.
References ARG_ONE, dropped, RexxCompoundTable::init(), OREF_NULL, OrefSet, stemName, stringArgument(), tails, and value.
Referenced by newRexx().
RexxStem() [2/2]
RexxStem::RexxStem (RESTORETYPE restoreType) inline
Definition at line 76 of file StemClass.hpp.
Member Function Documentation
allIndexes()
RexxArray * RexxStem::allIndexes (void)
Create an array of all indexes of the stem.
Returns
An array of all tail names used in the stem.
Definition at line 1004 of file StemClass.cpp.
References tailArray().
Referenced by RexxMemory::createImage().
allItems()
RexxArray * RexxStem::allItems (void)
Return all items in the stem.
Returns
An array of all items in the stem.
Definition at line 906 of file StemClass.cpp.
References RexxCompoundTable::first(), RexxVariable::getVariableValue(), items(), new_array(), RexxCompoundTable::next(), OREF_NULL, RexxArray::put(), and tails.
Referenced by RexxMemory::createImage().
arraycopy()
void RexxStem::arraycopy (RexxString ** source, size_t start, RexxString ** target, size_t index, size_t count)
copy segments of one array into another.
Parameters
source The source array
start The starting index of the source copy
target The target array
index The target copy index
count The number of items to count.
Definition at line 1380 of file StemClass.cpp.
References index(), and RexxObject::start().
Referenced by merge().
bracket()
RexxObject * RexxStem::bracket (RexxObject ** tailElements, size_t argCount, size_t named_argCount)
Definition at line 236 of file StemClass.cpp.
References evaluateCompoundVariableValue(), OREF_NULL, stemName, and value.
Referenced by RexxMemory::createImage().
bracketEqual()
RexxObject * RexxStem::bracketEqual (RexxObject ** tailElements, size_t argCount, size_t named_argCount)
Definition at line 390 of file StemClass.cpp.
References RexxCompoundTable::clear(), dropped, Error_Execution_nostem, Error_Incorrect_method_noarg, getCompoundVariable(), IntegerOne, isOfClass, OREF_NULL, OrefSet, reportException(), RexxVariable::set(), tails, and value.
Referenced by RexxMemory::createImage().
compoundVariableExists()
bool RexxStem::compoundVariableExists (RexxCompoundTail * resolved_tail) inline
Definition at line 138 of file StemClass.hpp.
References OREF_NULL, and realCompoundVariableValue().
Referenced by RexxActivation::localCompoundVariableExists().
copy()
RexxObject * RexxStem::copy (void) virtual
Reimplemented from RexxObject.
Definition at line 91 of file StemClass.cpp.
References RexxObject::copy(), copyFrom(), and tails.
copyFrom()
void RexxStem::copyFrom (RexxCompoundTable & _tails)
Copy the tails from another stem object into this stem.
Parameters
_tails The source tail collection.
Definition at line 109 of file StemClass.cpp.
References RexxCompoundTable::copyFrom(), RexxCompoundTable::init(), and tails.
Referenced by copy().
createCompoundName()
RexxString * RexxStem::createCompoundName (RexxCompoundTail * tailPart)
Create a full compound name from a constructed compound taile.
Parameters
tailPart The constructed tail element.
Returns
The fully resolved string name of the element.
Definition at line 1212 of file StemClass.cpp.
References RexxCompoundTail::createCompoundName(), and stemName.
createInstance()
void RexxStem::createInstance () static
Create initial class object at bootstrap time.
Definition at line 63 of file StemClass.cpp.
References CLASS_CREATE.
Referenced by RexxMemory::createImage().
doubleValue()
bool RexxStem::doubleValue (double & result) virtual
Reimplemented from RexxObject.
Definition at line 483 of file StemClass.cpp.
References RexxObject::doubleValue(), and value.
dropCompoundVariable()
void RexxStem::dropCompoundVariable (RexxCompoundTail * name)
Definition at line 634 of file StemClass.cpp.
References RexxVariable::drop(), and getCompoundVariable().
Referenced by RexxVariableDictionary::dropCompoundVariable(), and RexxActivation::dropLocalCompoundVariable().
dropElement() [1/3]
void RexxStem::dropElement (const char * _tail)
Drop an array element for an API class.
Parameters
tail The direct tail value.
Definition at line 1180 of file StemClass.cpp.
Referenced by dropElement().
dropElement() [2/3]
void RexxStem::dropElement (RexxCompoundTail * resolved_tail)
Drop an element using a resolved tail value.
Parameters
resolved_tail The target tail element.
Definition at line 1195 of file StemClass.cpp.
References RexxVariable::drop(), findCompoundVariable(), and OREF_NULL.
dropElement() [3/3]
void RexxStem::dropElement (size_t _tail)
Drop an array element for an API class.
Parameters
tail The direct tail value.
Definition at line 1167 of file StemClass.cpp.
References dropElement().
dropValue()
void RexxStem::dropValue ()
Definition at line 163 of file StemClass.cpp.
References dropped, OrefSet, stemName, and value.
empty()
RexxObject * RexxStem::empty ()
Empty the stem. This also clears dropped and exposed tails,
Returns
Nothing.
Definition at line 980 of file StemClass.cpp.
References RexxCompoundTable::clear(), OREF_NULL, and tails.
Referenced by RexxMemory::createImage().
evaluateCompoundVariableValue()
RexxObject * RexxStem::evaluateCompoundVariableValue (RexxActivation * context, RexxString * stemVariableName, RexxCompoundTail * resolved_tail)
Definition at line 712 of file StemClass.cpp.
References RexxCompoundTail::createCompoundName(), dropped, findCompoundVariable(), RexxVariable::getVariableValue(), handleNovalue(), OREF_NULL, stemName, and value.
Referenced by bracket(), RexxActivation::evaluateLocalCompoundVariable(), and RexxVariableDictionary::getCompoundVariableValue().
expose()
void RexxStem::expose (RexxCompoundElement * variable)
Definition at line 888 of file StemClass.cpp.
References RexxCompoundTable::findEntry(), RexxVariable::getName(), new_variable(), and tails.
Referenced by RexxCompoundVariable::expose(), and RexxCompoundVariable::procedureExpose().
exposeCompoundVariable()
RexxCompoundElement * RexxStem::exposeCompoundVariable (RexxCompoundTail * name)
Definition at line 586 of file StemClass.cpp.
References dropped, RexxCompoundTable::findEntry(), RexxVariable::getVariableValue(), OREF_NULL, RexxCompoundElement::realVariable(), RexxVariable::set(), tails, and value.
Referenced by RexxCompoundVariable::expose(), and RexxActivation::exposeLocalCompoundVariable().
find()
size_t RexxStem::find (SortData * sd, int(*)(SortData *, RexxString *, RexxString *) comparator, RexxString ** strings, RexxString * val, int limit, size_t left, size_t right)
Finds the place in the given range of specified sorted array, where the element should be inserted for getting sorted array. Uses exponential search algorithm.
Parameters
sd The sort descriptor
comparator The comparator used to compare pairs of elements.
strings The input set of strings.
val object to be inserted
bnd possible values 0,-1. "-1" - val is located at index more then elements equals to val. "0" - val is located at index less then elements equals to val.
left The left bound of the insert operation.
right The right bound for the insert.
Returns
The insertion point.
Definition at line 1405 of file StemClass.cpp.
Referenced by merge().
findByValue()
RexxCompoundElement * RexxStem::findByValue (RexxObject * target)
Locate a stem item by value.
Returns
The compound item for the located element.
Definition at line 933 of file StemClass.cpp.
References RexxObject::equalValue(), RexxCompoundTable::first(), RexxVariable::getVariableValue(), RexxCompoundTable::next(), OREF_NULL, and tails.
Referenced by hasItem(), index(), and removeItem().
findCompoundVariable()
RexxCompoundElement * RexxStem::findCompoundVariable (RexxCompoundTail * name)
Definition at line 617 of file StemClass.cpp.
References RexxCompoundTable::findEntry(), OREF_NULL, RexxCompoundElement::realVariable(), and tails.
Referenced by dropElement(), evaluateCompoundVariableValue(), getCompoundVariableRealValue(), getCompoundVariableValue(), getElement(), hasIndex(), realCompoundVariableValue(), remove(), and sort().
first()
RexxCompoundElement* RexxStem::first (void) inline
Definition at line 140 of file StemClass.hpp.
References RexxCompoundTable::first(), and tails.
flatten()
void RexxStem::flatten (RexxEnvelope * envelope) virtual
Reimplemented from RexxObject.
Definition at line 138 of file StemClass.cpp.
References cleanUpFlatten, flatten_reference, flattenCompoundTable, and setUpFlatten.
getCompoundVariable()
RexxCompoundElement * RexxStem::getCompoundVariable (RexxCompoundTail * name)
Definition at line 574 of file StemClass.cpp.
References RexxCompoundTable::findEntry(), RexxCompoundElement::realVariable(), and tails.
Referenced by bracketEqual(), dropCompoundVariable(), RexxVariableDictionary::getCompoundVariable(), RexxActivation::getLocalCompoundVariable(), setCompoundVariable(), and setElement().
getCompoundVariableRealValue()
RexxObject * RexxStem::getCompoundVariableRealValue (RexxCompoundTail * resolved_tail)
Evaluate the real value of a compound variable. The real value is either its explicitly assigned value or a stem assigned value. This returns OREF_NULL if neither is available. This does not raise NOVALUE conditions.
Parameters
resolved_tail The target tail value.
Returns
The variable value, or OREF_NULL if the variable does not have an explicit value.
Definition at line 814 of file StemClass.cpp.
References dropped, findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, and value.
Referenced by RexxVariableDictionary::getCompoundVariableRealValue(), and RexxActivation::getLocalCompoundVariableRealValue().
getCompoundVariableValue()
RexxObject * RexxStem::getCompoundVariableValue (RexxCompoundTail * resolved_tail)
Definition at line 764 of file StemClass.cpp.
References RexxCompoundTail::createCompoundName(), dropped, findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, stemName, and value.
Referenced by RexxActivation::getLocalCompoundVariableValue().
getElement() [1/3]
RexxObject * RexxStem::getElement (const char * _tail)
Evaluate an array element for an API class.
Parameters
tail The direct tail value.
Returns
The object value. If the stem element does not exist or has been dropped, this returns OREF_NULL.
Definition at line 1132 of file StemClass.cpp.
References getElement().
getElement() [2/3]
RexxObject * RexxStem::getElement (RexxCompoundTail * resolved_tail)
Resolve a compound variable as a result of an api call.
Parameters
resolved_tail The resolved tail value.
Returns
The variable value. Returns OREF_NULL if not assigned or dropped.
Definition at line 1149 of file StemClass.cpp.
References findCompoundVariable(), RexxVariable::getVariableValue(), and OREF_NULL.
getElement() [3/3]
RexxObject * RexxStem::getElement (size_t _tail)
Evaluate an array element for an API class.
Parameters
tail The direct tail value.
Returns
The object value. If the stem element does not exist or has been dropped, this returns OREF_NULL.
Definition at line 1116 of file StemClass.cpp.
Referenced by getElement().
getName()
RexxString* RexxStem::getName () inline
Definition at line 139 of file StemClass.hpp.
References stemName.
Referenced by remove().
getStemValue()
RexxObject * RexxStem::getStemValue ()
Retrieve the assigned stem value.
Returns
The default stem value.
Definition at line 179 of file StemClass.cpp.
References value.
handleNovalue()
RexxObject * RexxStem::handleNovalue (RexxActivation * context, RexxString * name, RexxObject * defaultValue, RexxCompoundElement * variable)
Definition at line 864 of file StemClass.cpp.
References RexxActivation::handleNovalueEvent(), and OREF_NULL.
Referenced by evaluateCompoundVariableValue().
hasIndex()
RexxObject * RexxStem::hasIndex (RexxObject ** tailElements, size_t argCount, size_t named_argCount)
Test if this compound variable has a given index.
Parameters
tails The set of tail expressions.
argCount The argument count
Returns
True if the fully resolved tail exists in the stem, false otherwise.
Definition at line 265 of file StemClass.cpp.
References findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
hasItem()
RexxObject * RexxStem::hasItem (RexxObject * target)
Search for any index that matches the target object.
Parameters
target The object of interest.
Returns
.true if the object is in the collection, .false otherwise.
Definition at line 330 of file StemClass.cpp.
References findByValue(), OREF_NULL, TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
index()
RexxObject * RexxStem::index (RexxObject * target)
Return the index for a target item.
Parameters
target The target object.
Returns
The tail name for the match, or .nil if it was not found.
Definition at line 368 of file StemClass.cpp.
References findByValue(), RexxVariable::getName(), OREF_NULL, and TheNilObject.
Referenced by arraycopy(), and RexxMemory::createImage().
init()
void RexxStem::init (void) inline
Definition at line 142 of file StemClass.hpp.
References RexxCompoundTable::init(), and tails.
integerValue()
RexxInteger * RexxStem::integerValue (size_t precision) virtual
Reimplemented from RexxObject.
Definition at line 500 of file StemClass.cpp.
References RexxObject::integerValue(), and value.
isEmpty()
RexxObject * RexxStem::isEmpty ()
Test if the stem is empty.
Returns
True if the stem is empty, false otherwise.
Definition at line 992 of file StemClass.cpp.
References items(), TheFalseObject, and TheTrueObject.
Referenced by RexxMemory::createImage().
items()
size_t RexxStem::items (void)
Get the count of non-dropped items in the stem.
Returns
The number of non-dropped items.
Definition at line 955 of file StemClass.cpp.
References RexxCompoundTable::first(), RexxVariable::getVariableValue(), RexxCompoundTable::next(), OREF_NULL, and tails.
Referenced by allItems(), isEmpty(), itemsRexx(), and tailArray().
itemsRexx()
RexxObject * RexxStem::itemsRexx (void)
Return the number of items set in the collection.
Returns
The count of items in the collection, not counting the default value.
Definition at line 384 of file StemClass.cpp.
References items(), and new_integer().
Referenced by RexxMemory::createImage().
live()
void RexxStem::live (size_t liveMark) virtual
Reimplemented from RexxObject.
Definition at line 116 of file StemClass.cpp.
References markCompoundTable, memory_mark, stemName, and value.
liveGeneral()
void RexxStem::liveGeneral (int reason) virtual
Reimplemented from RexxObject.
Definition at line 127 of file StemClass.cpp.
References markGeneralCompoundTable, memory_mark_general, stemName, and value.
makeArray()
RexxArray * RexxStem::makeArray (void) virtual
Reimplemented from RexxObject.
Definition at line 434 of file StemClass.cpp.
References tailArray().
Referenced by request().
merge()
void RexxStem::merge (SortData * sd, int(*)(SortData *, RexxString *, RexxString *) comparator, RexxString ** strings, RexxString ** working, size_t left, size_t mid, size_t right)
Perform a merge of two sort partitions.
Parameters
sd The sort descriptor.
comparator The comparator used to compare elements.
strings The input strings.
working A working array used for the merge operations.
left The left bound for the merge.
mid The midpoint for the merge.
right The right bound of merge (inclusive).
Definition at line 1312 of file StemClass.cpp.
References arraycopy(), and find().
Referenced by mergeSort().
mergeSort()
void RexxStem::mergeSort (SortData * sd, int(*)(SortData *, RexxString *, RexxString *) comparator, RexxString ** strings, RexxString ** working, size_t left, size_t right)
The merge sort routine. This will partition the data in to two sections, mergesort each partition, then merge the two partitions together.
Parameters
sd The sort information.
comparator The comparator object used for the compares.
strings The input set of strings.
working The working array (same size as the sorted array).
left The left bound of the partition.
right The right bounds of the parition.
Definition at line 1275 of file StemClass.cpp.
References merge().
Referenced by sort().
newRexx()
RexxObject * RexxStem::newRexx (RexxObject ** init_args, size_t argCount, size_t named_argCount)
Definition at line 538 of file StemClass.cpp.
References RexxInternalObject::hasUninit(), RexxClass::processNewArgs(), RexxStem(), RexxObject::sendMessage(), and RexxInternalObject::setBehaviour().
Referenced by RexxMemory::createImage().
nextVariable()
RexxCompoundElement * RexxStem::nextVariable (RexxNativeActivation * activation)
Definition at line 645 of file StemClass.cpp.
References RexxNativeActivation::compoundElement(), RexxVariable::getVariableValue(), RexxCompoundTable::next(), OREF_NULL, RexxNativeActivation::setCompoundElement(), RexxNativeActivation::setNextStem(), and tails.
Referenced by RexxNativeActivation::fetchNext().
numberString()
RexxNumberString * RexxStem::numberString () virtual
Reimplemented from RexxObject.
Definition at line 491 of file StemClass.cpp.
References RexxObject::numberString(), and value.
numberValue() [1/2]
bool RexxStem::numberValue (wholenumber_t & result) virtual
Reimplemented from RexxObject.
Definition at line 459 of file StemClass.cpp.
References RexxObject::numberValue(), and value.
numberValue() [2/2]
bool RexxStem::numberValue (wholenumber_t & result, size_t precision) virtual
Reimplemented from RexxObject.
Definition at line 451 of file StemClass.cpp.
References RexxObject::numberValue(), and value.
operator new() [1/2]
void* RexxStem::operator new (size_t size, void * ptr) inline
Definition at line 74 of file StemClass.hpp.
operator new() [2/2]
void * RexxStem::operator new (size_t size)
Definition at line 564 of file StemClass.cpp.
References new_object(), and T_Stem.
realCompoundVariableValue()
RexxObject * RexxStem::realCompoundVariableValue (RexxCompoundTail * resolved_tail)
Definition at line 837 of file StemClass.cpp.
References dropped, findCompoundVariable(), RexxVariable::getVariableValue(), OREF_NULL, and value.
Referenced by compoundVariableExists().
remove()
RexxObject * RexxStem::remove (RexxObject ** tailElements, size_t argCount, size_t named_argCount)
Remove an item from the collection. This is essentially equivalent to a drop operation on the stem variable.
Parameters
tails The set of tail indexes.
argCount The number of indexes.
Returns
The removed object. If nothing was removed, this returns .nil.
Definition at line 296 of file StemClass.cpp.
References RexxVariable::drop(), findCompoundVariable(), getName(), RexxVariable::getVariableValue(), OREF_NULL, OrefSet, TheNilObject, and value.
Referenced by RexxMemory::createImage().
removeItem()
RexxObject * RexxStem::removeItem (RexxObject * target)
Remove an item from the collection.
Parameters
target The object of interest.
Returns
.true if the object is in the collection, .false otherwise.
Definition at line 345 of file StemClass.cpp.
References RexxVariable::drop(), findByValue(), RexxVariable::getVariableValue(), OREF_NULL, and TheNilObject.
Referenced by RexxMemory::createImage().
request()
RexxObject * RexxStem::request (RexxString * makeclass)
Definition at line 509 of file StemClass.cpp.
References ARG_ONE, isOfClass, makeArray(), RexxObject::sendMessage(), RexxString::strCompare(), stringArgument(), RexxString::upper(), and value.
Referenced by RexxMemory::createImage().
setCompoundVariable()
void RexxStem::setCompoundVariable (RexxCompoundTail * name, RexxObject * value)
Definition at line 674 of file StemClass.cpp.
References getCompoundVariable(), and RexxVariable::set().
Referenced by RexxActivation::assignLocalCompoundVariable(), RexxVariableDictionary::setCompoundVariable(), and RexxActivation::setLocalCompoundVariable().
setElement() [1/2]
void RexxStem::setElement (const char * _tail, RexxObject * _value)
Set a single stem variable object using a simple string value tail as a result of an api call.
Parameters
tail The index of the target value.
value The new value to assign.
Definition at line 1085 of file StemClass.cpp.
References getCompoundVariable(), and RexxVariable::set().
setElement() [2/2]
void RexxStem::setElement (size_t _tail, RexxObject * _value)
Set a single stem variable object using a simple string value tail as a result of an api call.
Parameters
tail The index of the target value.
value The new value to assign.
Definition at line 1100 of file StemClass.cpp.
References getCompoundVariable(), and RexxVariable::set().
setValue()
void RexxStem::setValue (RexxObject * value)
Definition at line 153 of file StemClass.cpp.
References dropped, OrefSet, and value.
Referenced by RexxStemVariable::assign(), and RexxStemVariable::set().
sort()
bool RexxStem::sort (RexxString * prefix, int order, int type, size_t start, size_t end, size_t firstcol, size_t lastcol)
Definition at line 1450 of file StemClass.cpp.
References SortData::columnLength, compare_asc(), compare_asc_cols(), compare_asc_i(), compare_asc_i_cols(), compare_desc(), compare_desc_cols(), compare_desc_i(), compare_desc_i_cols(), RexxArray::data(), Numerics::DEFAULT_DIGITS, findCompoundVariable(), RexxArray::get(), RexxVariable::getVariableValue(), mergeSort(), new_array(), OREF_NULL, RexxArray::put(), REQUEST_STRING(), RexxVariable::set(), SIZE_MAX, SORT_ASCENDING, SORT_CASEIGNORE, SORT_CASESENSITIVE, SortData::startColumn, type, and RexxObject::unsignedNumberValue().
Referenced by RexxStemVariable::sort().
stringValue()
RexxString * RexxStem::stringValue () virtual
Reimplemented from RexxObject.
Definition at line 442 of file StemClass.cpp.
References RexxObject::stringValue(), and value.
supplier()
RexxSupplier * RexxStem::supplier (void)
Create a supplier for the stem, returning the tail names as the indexes and the values as the items.
Returns
A supplier instance.
Definition at line 1016 of file StemClass.cpp.
References RexxCompoundTable::first(), RexxVariable::getName(), RexxVariable::getVariableValue(), new_array(), new_supplier(), RexxCompoundTable::next(), OREF_NULL, RexxArray::put(), and tails.
Referenced by RexxMemory::createImage().
tail()
RexxString* RexxStem::tail (RexxArray * , size_t)
tailArray()
RexxArray * RexxStem::tailArray ()
Definition at line 686 of file StemClass.cpp.
References RexxCompoundTable::first(), RexxVariable::getName(), RexxVariable::getVariableValue(), items(), new_array(), RexxCompoundTable::next(), OREF_NULL, RexxArray::put(), and tails.
Referenced by allIndexes(), and makeArray().
toDirectory()
RexxDirectory * RexxStem::toDirectory ()
Create a directory from the stem. Each tail with an assigned value will be an entry within the directory.
Returns
A directory instance.
Definition at line 1059 of file StemClass.cpp.
References RexxCompoundTable::first(), RexxVariable::getName(), RexxVariable::getVariableValue(), new_directory(), RexxCompoundTable::next(), OREF_NULL, RexxDirectory::put(), and tails.
Referenced by RexxMemory::createImage().
unknown()
RexxObject * RexxStem::unknown (RexxString * msgname, RexxArray * arguments, RexxDirectory * named_arguments) virtual
Reimplemented from RexxObject.
Definition at line 185 of file StemClass.cpp.
References RexxDirectory::appendAllIndexesItemsTo(), ARG_ONE, ARG_TWO, RexxArray::copy(), RexxArray::data(), Error_Execution_user_defined, Error_Incorrect_method_noarray, IntegerTwo, RexxDirectory::items(), OREF_NULL, reportException(), REQUEST_ARRAY(), RexxObject::requestDirectory(), requiredArgument(), RexxObject::sendMessage(), RexxArray::size(), stringArgument(), TheNilObject, and value.
unsignedNumberValue() [1/2]
bool RexxStem::unsignedNumberValue (stringsize_t & result) virtual
Reimplemented from RexxObject.
Definition at line 475 of file StemClass.cpp.
References RexxObject::unsignedNumberValue(), and value.
unsignedNumberValue() [2/2]
bool RexxStem::unsignedNumberValue (stringsize_t & result, size_t precision) virtual
Reimplemented from RexxObject.
Definition at line 467 of file StemClass.cpp.
References RexxObject::unsignedNumberValue(), and value.
Friends And Related Function Documentation
RexxCompoundTable
friend class RexxCompoundTable friend
Definition at line 71 of file StemClass.hpp.
Member Data Documentation
classInstance
RexxClass * RexxStem::classInstance = OREF_NULL static
Definition at line 154 of file StemClass.hpp.
dropped
bool RexxStem::dropped protected
Definition at line 161 of file StemClass.hpp.
Referenced by bracketEqual(), dropValue(), evaluateCompoundVariableValue(), exposeCompoundVariable(), getCompoundVariableRealValue(), getCompoundVariableValue(), realCompoundVariableValue(), RexxStem(), and setValue().
stemName
RexxString* RexxStem::stemName protected
Definition at line 158 of file StemClass.hpp.
Referenced by bracket(), createCompoundName(), dropValue(), evaluateCompoundVariableValue(), getCompoundVariableValue(), getName(), live(), liveGeneral(), and RexxStem().
tails
RexxCompoundTable RexxStem::tails protected
Definition at line 159 of file StemClass.hpp.
Referenced by allItems(), bracketEqual(), copy(), copyFrom(), empty(), expose(), exposeCompoundVariable(), findByValue(), findCompoundVariable(), first(), getCompoundVariable(), init(), items(), nextVariable(), RexxStem(), RexxCompoundTable::setParent(), RexxCompoundTable::setRoot(), supplier(), tailArray(), and toDirectory().
value
RexxObject* RexxStem::value protected
Definition at line 160 of file StemClass.hpp.
Referenced by bracket(), bracketEqual(), doubleValue(), dropValue(), evaluateCompoundVariableValue(), exposeCompoundVariable(), getCompoundVariableRealValue(), getCompoundVariableValue(), getStemValue(), integerValue(), live(), liveGeneral(), numberString(), numberValue(), realCompoundVariableValue(), remove(), request(), RexxStem(), setValue(), stringValue(), unknown(), and unsignedNumberValue().
The documentation for this class was generated from the following files:
StemClass.hpp
StemClass.cpp