executor.master: CallProgramDispatcher Class Reference
CallProgramDispatcher Class Reference
#include <RexxStartDispatcher.hpp>
Public Member Functions
CallProgramDispatcher (const char *p, RexxArray *a)
virtual ~CallProgramDispatcher ()
virtual void run ()
Public Member Functions inherited from ActivityDispatcher
ActivityDispatcher ()
virtual ~ActivityDispatcher ()
virtual void handleError (wholenumber_t, RexxDirectory *)
virtual void handleError (RexxDirectory *)
virtual void invoke ()
virtual void invoke (RexxOption *)
virtual void invoke (PRXSYSEXIT exits, const char *env)
void setContext (RexxActivity *act, RexxNativeActivation *a)
Public Attributes
ProtectedObject result
Public Attributes inherited from ActivityDispatcher
wholenumber_t rc
RexxDirectory * conditionData
Protected Attributes
const char * program
RexxArray * arguments
Protected Attributes inherited from ActivityDispatcher
RexxActivity * activity
RexxNativeActivation * activation
Detailed Description
Definition at line 82 of file RexxStartDispatcher.hpp.
Constructor & Destructor Documentation
CallProgramDispatcher()
CallProgramDispatcher::CallProgramDispatcher (const char * p, RexxArray * a) inline
Definition at line 85 of file RexxStartDispatcher.hpp.
~CallProgramDispatcher()
virtual CallProgramDispatcher::~CallProgramDispatcher () inline virtual
Definition at line 86 of file RexxStartDispatcher.hpp.
Member Function Documentation
run()
void CallProgramDispatcher::run () virtual
Run a routine for a thread context API call.
Reimplemented from ActivityDispatcher.
Definition at line 219 of file RexxStartDispatcher.cpp.
References ActivityDispatcher::activity, arguments, RexxArray::data(), Error_Program_unreadable_notfound, RoutineClass::fromFile(), new_string(), OREF_NULL, program, reportException(), RexxActivity::resolveProgramName(), result, RoutineClass::runProgram(), and RexxArray::size().
Member Data Documentation
arguments
RexxArray* CallProgramDispatcher::arguments protected
Definition at line 94 of file RexxStartDispatcher.hpp.
Referenced by run().
program
const char* CallProgramDispatcher::program protected
Definition at line 93 of file RexxStartDispatcher.hpp.
Referenced by run().
result
ProtectedObject CallProgramDispatcher::result
Definition at line 90 of file RexxStartDispatcher.hpp.
Referenced by CallProgram(), and run().
The documentation for this class was generated from the following files:
RexxStartDispatcher.hpp
RexxStartDispatcher.cpp