executor.master: DeadObjectPool Class Reference
DeadObjectPool Class Reference
#include <DeadObject.hpp>
Public Member Functions
DeadObjectPool ()
DeadObjectPool (const char *poolID)
void init (const char *poolID)
void setID (const char *poolID)
void empty ()
bool isEmpty ()
void emptySingle ()
bool isEmptySingle ()
void checkObjectGrain (DeadObject *obj)
void add (DeadObject *obj)
void addSortedBySize (DeadObject *obj)
void addSortedByLocation (DeadObject *obj)
void dumpMemoryProfile (FILE *outfile)
void checkObjectOverlap (DeadObject *obj)
DeadObject * getFirst ()
DeadObject * lastBlock ()
DeadObject * firstBlock ()
DeadObject * findFit (size_t length)
DeadObject * findFit (size_t length, size_t *realLength)
DeadObject * findBestFit (size_t length)
DeadObject * findSmallestFit (size_t minSize)
void addSingle (DeadObject *obj)
DeadObject * getFirstSingle ()
Private Member Functions
void logAllocation ()
void logReclaim ()
void logHit ()
void logMiss ()
void clearProfile ()
Private Attributes
DeadObject anchor
const char * id
Detailed Description
Definition at line 131 of file DeadObject.hpp.
Constructor & Destructor Documentation
DeadObjectPool() [1/2]
DeadObjectPool::DeadObjectPool () inline
Definition at line 134 of file DeadObject.hpp.
References init().
DeadObjectPool() [2/2]
DeadObjectPool::DeadObjectPool (const char * poolID) inline
Definition at line 136 of file DeadObject.hpp.
References init().
Member Function Documentation
add()
void DeadObjectPool::add (DeadObject * obj) inline
Definition at line 161 of file DeadObject.hpp.
References anchor, and DeadObject::insertAfter().
Referenced by NormalSegmentSet::addDeadObject(), findFit(), and NormalSegmentSet::splitNormalDeadObject().
addSingle()
void DeadObjectPool::addSingle (DeadObject * obj) inline
Definition at line 262 of file DeadObject.hpp.
References anchor, and DeadObject::next.
Referenced by NormalSegmentSet::addDeadObject(), and NormalSegmentSet::splitNormalDeadObject().
addSortedByLocation()
void DeadObjectPool::addSortedByLocation (DeadObject * obj)
Definition at line 175 of file DeadObject.cpp.
References anchor, DeadObject::insertBefore(), DeadObject::isReal(), and DeadObject::next.
addSortedBySize()
void DeadObjectPool::addSortedBySize (DeadObject * obj)
Definition at line 148 of file DeadObject.cpp.
References anchor, DeadObject::getObjectSize(), DeadObject::insertBefore(), DeadObject::isReal(), and DeadObject::next.
Referenced by LargeSegmentSet::addDeadObject(), and OldSpaceSegmentSet::addDeadObject().
checkObjectGrain()
void DeadObjectPool::checkObjectGrain (DeadObject * obj) inline
Definition at line 201 of file DeadObject.cpp.
References IsObjectGrained, and Interpreter::logicError().
checkObjectOverlap()
void DeadObjectPool::checkObjectOverlap (DeadObject * obj)
Definition at line 212 of file DeadObject.cpp.
References anchor, DeadObject::getObjectSize(), DeadObject::isReal(), Interpreter::logicError(), DeadObject::next, and DeadObject::overlaps().
Referenced by NormalSegmentSet::checkObjectOverlap().
clearProfile()
void DeadObjectPool::clearProfile () inline private
dumpMemoryProfile()
void DeadObjectPool::dumpMemoryProfile (FILE * outfile)
Definition at line 51 of file DeadObject.cpp.
Referenced by NormalSegmentSet::dumpMemoryProfile(), and LargeSegmentSet::dumpMemoryProfile().
empty()
void DeadObjectPool::empty () inline
Definition at line 155 of file DeadObject.hpp.
References anchor, and DeadObject::reset().
Referenced by NormalSegmentSet::prepareForSweep(), and LargeSegmentSet::prepareForSweep().
emptySingle()
void DeadObjectPool::emptySingle () inline
Definition at line 157 of file DeadObject.hpp.
References anchor, and DeadObject::next.
Referenced by NormalSegmentSet::NormalSegmentSet(), and NormalSegmentSet::prepareForSweep().
findBestFit()
DeadObject * DeadObjectPool::findBestFit (size_t length)
Definition at line 66 of file DeadObject.cpp.
References anchor, DeadObject::getObjectSize(), logHit(), logMiss(), DeadObject::next, DeadObject::remove(), and VeryLargeObjectGrain.
Referenced by LargeSegmentSet::allocateObject().
findFit() [1/2]
DeadObject* DeadObjectPool::findFit (size_t length) inline
Definition at line 193 of file DeadObject.hpp.
References anchor, DeadObject::getObjectSize(), logHit(), logMiss(), DeadObject::next, and DeadObject::remove().
Referenced by NormalSegmentSet::allocateObject(), NormalSegmentSet::findLargeDeadObject(), and OldSpaceSegmentSet::findObject().
findFit() [2/2]
DeadObject* DeadObjectPool::findFit (size_t length, size_t * realLength) inline
Definition at line 214 of file DeadObject.hpp.
References add(), anchor, DeadObject::getObjectSize(), logHit(), logMiss(), DeadObject::next, DeadObject::remove(), and ReorderThreshold.
findSmallestFit()
DeadObject * DeadObjectPool::findSmallestFit (size_t minSize)
Definition at line 112 of file DeadObject.cpp.
References anchor, DeadObject::getObjectSize(), DeadObject::isReal(), logHit(), logMiss(), MaximumObjectSize, DeadObject::next, and DeadObject::remove().
Referenced by LargeSegmentSet::donateObject().
firstBlock()
DeadObject* DeadObjectPool::firstBlock () inline
Definition at line 192 of file DeadObject.hpp.
References anchor, and DeadObject::next.
getFirst()
DeadObject* DeadObjectPool::getFirst () inline
Definition at line 171 of file DeadObject.hpp.
References anchor, DeadObject::isReal(), logHit(), logMiss(), DeadObject::next, and DeadObject::remove().
getFirstSingle()
DeadObject* DeadObjectPool::getFirstSingle () inline
Definition at line 270 of file DeadObject.hpp.
References anchor, logHit(), logMiss(), and DeadObject::next.
Referenced by NormalSegmentSet::allocateObject().
init()
void DeadObjectPool::init (const char * poolID) inline
Definition at line 140 of file DeadObject.hpp.
Referenced by DeadObjectPool().
isEmpty()
bool DeadObjectPool::isEmpty () inline
Definition at line 156 of file DeadObject.hpp.
References anchor, DeadObject::isReal(), and DeadObject::next.
isEmptySingle()
bool DeadObjectPool::isEmptySingle () inline
Definition at line 158 of file DeadObject.hpp.
References anchor, and DeadObject::next.
lastBlock()
DeadObject* DeadObjectPool::lastBlock () inline
Definition at line 191 of file DeadObject.hpp.
References anchor, and DeadObject::previous.
logAllocation()
void DeadObjectPool::logAllocation () inline private
Definition at line 297 of file DeadObject.hpp.
logHit()
void DeadObjectPool::logHit () inline private
Definition at line 299 of file DeadObject.hpp.
Referenced by findBestFit(), findFit(), findSmallestFit(), getFirst(), and getFirstSingle().
logMiss()
void DeadObjectPool::logMiss () inline private
Definition at line 300 of file DeadObject.hpp.
Referenced by findBestFit(), findFit(), findSmallestFit(), getFirst(), and getFirstSingle().
logReclaim()
void DeadObjectPool::logReclaim () inline private
Definition at line 298 of file DeadObject.hpp.
setID()
void DeadObjectPool::setID (const char * poolID) inline
Definition at line 154 of file DeadObject.hpp.
Referenced by NormalSegmentSet::NormalSegmentSet().
Member Data Documentation
anchor
DeadObject DeadObjectPool::anchor private
Definition at line 305 of file DeadObject.hpp.
Referenced by add(), addSingle(), addSortedByLocation(), addSortedBySize(), checkObjectOverlap(), empty(), emptySingle(), findBestFit(), findFit(), findSmallestFit(), firstBlock(), getFirst(), getFirstSingle(), isEmpty(), isEmptySingle(), and lastBlock().
id
const char* DeadObjectPool::id private
Definition at line 306 of file DeadObject.hpp.
The documentation for this class was generated from the following files:
DeadObject.hpp
DeadObject.cpp