executor.master: rexx.h File Reference
rexx.h File Reference
#include "rexxapitypes.h"
#include "rexxapidefs.h"
#include "rexxplatformdefs.h"
#include "rexxplatformapis.h"
Classes
struct _RXSTRING
struct _CONSTRXSTRING
struct _RXSYSEXIT
struct _SHVBLOCK
struct _RexxQueueTime
struct _RexxConditionData
struct _RXFNC_FLAGS
struct _RXFNCCAL_PARM
struct _RXOFNC_FLAGS
struct _RXOFNCCAL_PARM
struct _RXEXF_FLAGS
struct _RXEXFCAL_PARM
struct _RXCMD_FLAGS
struct _RXCMDHST_PARM
struct _RXMSQPLL_PARM
struct _RXMSQ_FLAGS
struct _RXMSQPSH_PARM
struct _RXMSQSIZ_PARM
struct _RXMSQNAM_PARM
struct _RXSIOSAY_PARM
struct _RXSIOTRC_PARM
struct _RXSIOTRD_PARM
struct _RXSIODTR_PARM
struct _RXHLT_FLAGS
struct _RXHLTTST_PARM
struct _RXTRC_FLAGS
struct _RXTRCTST_PARM
struct _RXVARNOVALUE_PARM
struct _RXVALCALL_PARM
Macros
#define BEGIN_EXTERN_C()
#define END_EXTERN_C()
#define NO_CSTRING NULL
#define NULLOBJECT NULL
#define CONSTANT_RXSTRING CONSTRXSTRING
#define CONSTANT_STRING CSTRING
#define RXNULLSTRING(r) ((r).strptr == NULL)
#define RXZEROLENSTRING(r) ((r).strptr != NULL && (r).strlength == 0)
#define RXVALIDSTRING(r) ((r).strptr != NULL && (r).strlength != 0)
#define RXSTRLEN(r) (RXNULLSTRING(r) ? 0 : (r).strlength)
#define RXSTRPTR(r) ((r).strptr)
#define MAKERXSTRING(r, p, l) { (r).strptr = p; (r).strlength = l; }
#define size_v(X) size_t(X)
#define stringsize_v(X) stringsize_t(X)
#define stringsizeC_v(X) stringsizeC_t(X)
#define sizeC_v(X) sizeC_t(X)
#define stringsizeB_v(X) stringsizeB_t(X)
#define sizeB_v(X) sizeB_t(X)
#define RexxEntry REXXENTRY
#define REXXSTART RexxStart
#define REXXWAITFORTERMINATION RexxWaitForTermination
#define REXXDIDREXXTERMINATE RexxDidRexxTerminate
#define REXXSHUTDOWNAPI RexxShutDownAPI
#define REXXTRANSLATEPROGRAM RexxTranslateProgram
#define REXXTRANSLATEINSTOREPROGRAM RexxTranslateInstoreProgram
#define REXXGETVERSIONINFORMATON RexxGetVersionInformation
#define REXXREGISTERSUBCOMDLL RexxRegisterSubcomDll
#define REXXREGISTERSUBCOMEXE RexxRegisterSubcomExe
#define REXXQUERYSUBCOM RexxQuerySubcom
#define REXXDEREGISTERSUBCOM RexxDeregisterSubcom
#define REXXVARIABLEPOOL RexxVariablePool
#define REXXREGISTERFUNCTIONDLL RexxRegisterFunctionDll
#define REXXREGISTERFUNCTIONEXE RexxRegisterFunctionExe
#define REXXDEREGISTERFUNCTION RexxDeregisterFunction
#define REXXQUERYFUNCTION RexxQueryFunction
#define REXXREGISTEREXITDLL RexxRegisterExitDll
#define REXXREGISTEREXITEXE RexxRegisterExitExe
#define REXXDEREGISTEREXIT RexxDeregisterExit
#define REXXQUERYEXIT RexxQueryExit
#define REXXSETHALT RexxSetHalt
#define REXXSETTRACE RexxSetTrace
#define REXXRESETTRACE RexxResetTrace
#define REXXADDMACRO RexxAddMacro
#define REXXDROPMACRO RexxDropMacro
#define REXXSAVEMACROSPACE RexxSaveMacroSpace
#define REXXLOADMACROSPACE RexxLoadMacroSpace
#define REXXQUERYMACRO RexxQueryMacro
#define REXXREORDERMACRO RexxReorderMacro
#define REXXCLEARMACROSPACE RexxClearMacroSpace
#define MAX_QUEUE_NAME_LENGTH 250
Typedefs
typedef int RexxReturnCode
typedef const char * CSTRING
typedef void * POINTER
typedef struct _RexxObjectPtr * RexxObjectPtr
typedef struct _RexxStringObject * RexxStringObject
typedef struct _RexxBufferStringObject * RexxBufferStringObject
typedef struct _RexxArrayObject * RexxArrayObject
typedef struct _RexxBufferObject * RexxBufferObject
typedef struct _RexxPointerObject * RexxPointerObject
typedef struct _RexxMethodObject * RexxMethodObject
typedef struct _RexxRoutineObject * RexxRoutineObject
typedef struct _RexxPackageObject * RexxPackageObject
typedef struct _RexxClassObject * RexxClassObject
typedef struct _RexxDirectoryObject * RexxDirectoryObject
typedef struct _RexxSupplierObject * RexxSupplierObject
typedef struct _RexxStemObject * RexxStemObject
typedef struct _RexxMutableBufferObject * RexxMutableBufferObject
typedef struct _RXSTRING RXSTRING
typedef struct _CONSTRXSTRING CONSTRXSTRING
typedef RXSTRING * PRXSTRING
typedef CONSTANT_RXSTRING * PCONSTRXSTRING
typedef struct _RXSYSEXIT RXSYSEXIT
typedef RXSYSEXIT * PRXSYSEXIT
typedef struct _SHVBLOCK SHVBLOCK
typedef SHVBLOCK * PSHVBLOCK
typedef char * PEXIT
typedef size_t stringsize_t
typedef size_t uwholenumber_t
typedef ssize_t wholenumber_t
typedef size_t logical_t
typedef ssize_t codepoint_t
typedef stringsize_t stringsizeC_t
typedef stringsizeC_t sizeC_t
typedef stringsize_t stringsizeB_t
typedef stringsizeB_t sizeB_t
typedef struct _RexxQueueTime RexxQueueTime
typedef struct _RexxConditionData RexxConditionData
typedef RexxReturnCode(REXXENTRY * PFNREXXSTART) (size_t, PCONSTRXSTRING, CONSTANT_STRING, PRXSTRING, CONSTANT_STRING, int, PRXSYSEXIT, short *, PRXSTRING)
typedef void(REXXENTRY * PFNREXXWAITFORTERMINATION) (void)
typedef RexxReturnCode(REXXENTRY * PFNREXXDIDREXXTERMINATE) (void)
typedef RexxReturnCode(REXXENTRY * PFNREXXSHUTDOWNAPI) (void)
typedef RexxReturnCode(REXXENTRY * PFNREXXTRANSLATEPROGRAM) (CONSTANT_STRING, CONSTANT_STRING, PRXSYSEXIT)
typedef RexxReturnCode(REXXENTRY * PFNREXXTRANSLATEINSTOREPROGRAM) (CONSTANT_STRING, CONSTANT_RXSTRING *, RXSTRING *)
typedef char *(REXXENTRY * PFNGETVERSIONINFORMATION) (void)
typedef RexxReturnCode REXXENTRY RexxSubcomHandler(PCONSTRXSTRING, unsigned short *, PRXSTRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTERSUBCOMDLL) (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING, char *, size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTERSUBCOMEXE) (CONSTANT_STRING, REXXPFN, char *)
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYSUBCOM) (CONSTANT_STRING, CONSTANT_STRING, unsigned short *, char *)
typedef RexxReturnCode(REXXENTRY * PFNREXXDEREGISTERSUBCOM) (CONSTANT_STRING, CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXVARIABLEPOOL) (PSHVBLOCK)
typedef size_t REXXENTRY RexxRoutineHandler(CONSTANT_STRING, size_t, PCONSTRXSTRING, CONSTANT_STRING, PRXSTRING)
typedef size_t REXXENTRY RexxFunctionHandler(CONSTANT_STRING, size_t, PCONSTRXSTRING, CONSTANT_STRING, PRXSTRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTERFUNCTIONDLL) (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTERFUNCTIONEXE) (CONSTANT_STRING, REXXPFN)
typedef RexxReturnCode(REXXENTRY * PFNREXXDEREGISTERFUNCTION) (CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYFUNCTION) (CONSTANT_STRING)
typedef struct _RXFNC_FLAGS RXFNC_FLAGS
typedef struct _RXFNCCAL_PARM RXFNCCAL_PARM
typedef struct _RXOFNC_FLAGS RXOFNC_FLAGS
typedef struct _RXOFNCCAL_PARM RXOFNCCAL_PARM
typedef struct _RXEXF_FLAGS RXEXF_FLAGS
typedef struct _RXEXFCAL_PARM RXEXFCAL_PARM
typedef struct _RXCMD_FLAGS RXCMD_FLAGS
typedef struct _RXCMDHST_PARM RXCMDHST_PARM
typedef struct _RXMSQPLL_PARM RXMSQPLL_PARM
typedef struct _RXMSQ_FLAGS RXMSQ_FLAGS
typedef struct _RXMSQPSH_PARM RXMSQPSH_PARM
typedef struct _RXMSQSIZ_PARM RXMSQSIZ_PARM
typedef struct _RXMSQNAM_PARM RXMSQNAM_PARM
typedef struct _RXSIOSAY_PARM RXSIOSAY_PARM
typedef struct _RXSIOTRC_PARM RXSIOTRC_PARM
typedef struct _RXSIOTRD_PARM RXSIOTRD_PARM
typedef struct _RXSIODTR_PARM RXSIODTR_PARM
typedef struct _RXHLT_FLAGS RXHLT_FLAGS
typedef struct _RXHLTTST_PARM RXHLTTST_PARM
typedef struct _RXTRC_FLAGS RXTRC_FLAGS
typedef struct _RXTRCTST_PARM RXTRCTST_PARM
typedef struct _RXVARNOVALUE_PARM RXVARNOVALUE_PARM
typedef struct _RXVALCALL_PARM RXVALCALL_PARM
typedef int REXXENTRY RexxExitHandler(int, int, PEXIT)
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTEREXITDLL) (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING, char *, size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTEREXITEXE) (CONSTANT_STRING, REXXPFN, char *)
typedef RexxReturnCode(REXXENTRY * PFNREXXDEREGISTEREXIT) (CONSTANT_STRING, CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYEXIT) (CONSTANT_STRING, CONSTANT_STRING, unsigned short *, char *)
typedef RexxReturnCode(REXXENTRY * PFNREXXSETHALT) (process_id_t, thread_id_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXSETTRACE) (process_id_t, thread_id_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXRESETTRACE) (process_id_t, thread_id_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXADDMACRO) (CONSTANT_STRING, CONSTANT_STRING, size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXDROPMACRO) (CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXSAVEMACROSPACE) (size_t, CONSTANT_STRING *, CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXLOADMACROSPACE) (size_t, CONSTANT_STRING *, CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYMACRO) (CONSTANT_STRING, unsigned short *)
typedef RexxReturnCode(REXXENTRY * PFNREXXREORDERMACRO) (CONSTANT_STRING, size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXCLEARMACROSPACE) (void)
typedef RexxReturnCode(REXXENTRY * PFNREXXCREATEQUEUE) (char *, size_t, CONSTANT_STRING, size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXOPENQUEUE) (CONSTANT_STRING, size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXQUEUEEXISTS) (CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXDELETEQUEUE) (CONSTANT_STRING)
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYQUEUE) (CONSTANT_STRING, size_t *)
typedef RexxReturnCode(REXXENTRY * PFNREXXADDQUEUE) (CONSTANT_STRING, PCONSTRXSTRING, size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXPULLFROMQUEUE) (CONSTANT_STRING, PRXSTRING, RexxQueueTime *, size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXCLEARQUEUE) (CONSTANT_STRING)
typedef void *(REXXENTRY * PFNREXXALLOCATEMEMORY) (size_t)
typedef RexxReturnCode(REXXENTRY * PFNREXXFREEMEMORY) (void *)
Functions
int REXXENTRY RexxStart (size_t, PCONSTRXSTRING, CONSTANT_STRING, PRXSTRING, CONSTANT_STRING, int, PRXSYSEXIT, short *, PRXSTRING)
void REXXENTRY RexxWaitForTermination (void)
RexxReturnCode REXXENTRY RexxDidRexxTerminate (void)
RexxReturnCode REXXENTRY RexxShutDownAPI (void)
RexxReturnCode REXXENTRY RexxTranslateProgram (CONSTANT_STRING, CONSTANT_STRING, PRXSYSEXIT)
RexxReturnCode REXXENTRY RexxTranslateInstoreProgram (CONSTANT_STRING, CONSTANT_RXSTRING *, RXSTRING *)
char *REXXENTRY RexxGetVersionInformation (void)
RexxReturnCode REXXENTRY RexxRegisterSubcomDll (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING, size_t)
RexxReturnCode REXXENTRY RexxRegisterSubcomExe (CONSTANT_STRING, REXXPFN, CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxQuerySubcom (CONSTANT_STRING, CONSTANT_STRING, unsigned short *, char *)
RexxReturnCode REXXENTRY RexxDeregisterSubcom (CONSTANT_STRING, CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxVariablePool (PSHVBLOCK)
RexxReturnCode REXXENTRY RexxRegisterFunctionDll (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxRegisterFunctionExe (CONSTANT_STRING, REXXPFN)
RexxReturnCode REXXENTRY RexxDeregisterFunction (CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxQueryFunction (CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxRegisterExitDll (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING, size_t)
RexxReturnCode REXXENTRY RexxRegisterExitExe (CONSTANT_STRING, REXXPFN, CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxDeregisterExit (CONSTANT_STRING, CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxQueryExit (CONSTANT_STRING, CONSTANT_STRING, unsigned short *, char *)
RexxReturnCode REXXENTRY RexxSetHalt (process_id_t, thread_id_t)
RexxReturnCode REXXENTRY RexxSetTrace (process_id_t, thread_id_t)
RexxReturnCode REXXENTRY RexxResetTrace (process_id_t, thread_id_t)
RexxReturnCode REXXENTRY RexxAddMacro (CONSTANT_STRING, CONSTANT_STRING, size_t)
RexxReturnCode REXXENTRY RexxDropMacro (CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxSaveMacroSpace (size_t, CONSTANT_STRING *, CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxLoadMacroSpace (size_t, CONSTANT_STRING *, CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxQueryMacro (CONSTANT_STRING, unsigned short *)
RexxReturnCode REXXENTRY RexxReorderMacro (CONSTANT_STRING, size_t)
RexxReturnCode REXXENTRY RexxClearMacroSpace (void)
RexxReturnCode REXXENTRY RexxCreateQueue (char *, size_t, CONSTANT_STRING, size_t *)
RexxReturnCode REXXENTRY RexxOpenQueue (CONSTANT_STRING, size_t *)
RexxReturnCode REXXENTRY RexxQueueExists (CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxDeleteQueue (CONSTANT_STRING)
RexxReturnCode REXXENTRY RexxQueryQueue (CONSTANT_STRING, size_t *)
RexxReturnCode REXXENTRY RexxAddQueue (CONSTANT_STRING, PCONSTRXSTRING, size_t)
RexxReturnCode REXXENTRY RexxPullFromQueue (CONSTANT_STRING, PRXSTRING, RexxQueueTime *, size_t)
RexxReturnCode REXXENTRY RexxClearQueue (CONSTANT_STRING)
void *REXXENTRY RexxAllocateMemory (size_t)
RexxReturnCode REXXENTRY RexxFreeMemory (void *)
wholenumber_t REXXENTRY getAPIManagerCounter ()
Macro Definition Documentation
BEGIN_EXTERN_C
#define BEGIN_EXTERN_C ()
Definition at line 60 of file rexx.h.
CONSTANT_RXSTRING
#define CONSTANT_RXSTRING CONSTRXSTRING
Definition at line 167 of file rexx.h.
CONSTANT_STRING
#define CONSTANT_STRING CSTRING
Definition at line 168 of file rexx.h.
END_EXTERN_C
#define END_EXTERN_C ()
Definition at line 61 of file rexx.h.
MAKERXSTRING
#define MAKERXSTRING (r, p, l) { (r).strptr = p; (r).strlength = l; }
Definition at line 182 of file rexx.h.
MAX_QUEUE_NAME_LENGTH
#define MAX_QUEUE_NAME_LENGTH 250
Definition at line 957 of file rexx.h.
NO_CSTRING
#define NO_CSTRING NULL
Definition at line 146 of file rexx.h.
NULLOBJECT
#define NULLOBJECT NULL
Definition at line 147 of file rexx.h.
REXXADDMACRO
#define REXXADDMACRO RexxAddMacro
Definition at line 895 of file rexx.h.
REXXCLEARMACROSPACE
#define REXXCLEARMACROSPACE RexxClearMacroSpace
Definition at line 950 of file rexx.h.
REXXDEREGISTEREXIT
#define REXXDEREGISTEREXIT RexxDeregisterExit
Definition at line 839 of file rexx.h.
REXXDEREGISTERFUNCTION
#define REXXDEREGISTERFUNCTION RexxDeregisterFunction
Definition at line 621 of file rexx.h.
REXXDEREGISTERSUBCOM
#define REXXDEREGISTERSUBCOM RexxDeregisterSubcom
Definition at line 564 of file rexx.h.
REXXDIDREXXTERMINATE
#define REXXDIDREXXTERMINATE RexxDidRexxTerminate
Definition at line 475 of file rexx.h.
REXXDROPMACRO
#define REXXDROPMACRO RexxDropMacro
Definition at line 903 of file rexx.h.
RexxEntry
#define RexxEntry REXXENTRY
Definition at line 412 of file rexx.h.
REXXGETVERSIONINFORMATON
#define REXXGETVERSIONINFORMATON RexxGetVersionInformation
Definition at line 508 of file rexx.h.
REXXLOADMACROSPACE
#define REXXLOADMACROSPACE RexxLoadMacroSpace
Definition at line 923 of file rexx.h.
REXXQUERYEXIT
#define REXXQUERYEXIT RexxQueryExit
Definition at line 850 of file rexx.h.
REXXQUERYFUNCTION
#define REXXQUERYFUNCTION RexxQueryFunction
Definition at line 629 of file rexx.h.
REXXQUERYMACRO
#define REXXQUERYMACRO RexxQueryMacro
Definition at line 932 of file rexx.h.
REXXQUERYSUBCOM
#define REXXQUERYSUBCOM RexxQuerySubcom
Definition at line 554 of file rexx.h.
REXXREGISTEREXITDLL
#define REXXREGISTEREXITDLL RexxRegisterExitDll
Definition at line 820 of file rexx.h.
REXXREGISTEREXITEXE
#define REXXREGISTEREXITEXE RexxRegisterExitExe
Definition at line 830 of file rexx.h.
REXXREGISTERFUNCTIONDLL
#define REXXREGISTERFUNCTIONDLL RexxRegisterFunctionDll
Definition at line 604 of file rexx.h.
REXXREGISTERFUNCTIONEXE
#define REXXREGISTERFUNCTIONEXE RexxRegisterFunctionExe
Definition at line 613 of file rexx.h.
REXXREGISTERSUBCOMDLL
#define REXXREGISTERSUBCOMDLL RexxRegisterSubcomDll
Definition at line 531 of file rexx.h.
REXXREGISTERSUBCOMEXE
#define REXXREGISTERSUBCOMEXE RexxRegisterSubcomExe
Definition at line 542 of file rexx.h.
REXXREORDERMACRO
#define REXXREORDERMACRO RexxReorderMacro
Definition at line 942 of file rexx.h.
REXXRESETTRACE
#define REXXRESETTRACE RexxResetTrace
Definition at line 881 of file rexx.h.
REXXSAVEMACROSPACE
#define REXXSAVEMACROSPACE RexxSaveMacroSpace
Definition at line 913 of file rexx.h.
REXXSETHALT
#define REXXSETHALT RexxSetHalt
Definition at line 863 of file rexx.h.
REXXSETTRACE
#define REXXSETTRACE RexxSetTrace
Definition at line 872 of file rexx.h.
REXXSHUTDOWNAPI
#define REXXSHUTDOWNAPI RexxShutDownAPI
Definition at line 479 of file rexx.h.
REXXSTART
#define REXXSTART RexxStart
Definition at line 465 of file rexx.h.
REXXTRANSLATEINSTOREPROGRAM
#define REXXTRANSLATEINSTOREPROGRAM RexxTranslateInstoreProgram
Definition at line 501 of file rexx.h.
REXXTRANSLATEPROGRAM
#define REXXTRANSLATEPROGRAM RexxTranslateProgram
Definition at line 490 of file rexx.h.
REXXVARIABLEPOOL
#define REXXVARIABLEPOOL RexxVariablePool
Definition at line 576 of file rexx.h.
REXXWAITFORTERMINATION
#define REXXWAITFORTERMINATION RexxWaitForTermination
Definition at line 471 of file rexx.h.
RXNULLSTRING
#define RXNULLSTRING (r) ((r).strptr == NULL)
Definition at line 177 of file rexx.h.
RXSTRLEN
#define RXSTRLEN (r) (RXNULLSTRING(r) ? 0 : (r).strlength)
Definition at line 180 of file rexx.h.
RXSTRPTR
#define RXSTRPTR (r) ((r).strptr)
Definition at line 181 of file rexx.h.
RXVALIDSTRING
#define RXVALIDSTRING (r) ((r).strptr != NULL && (r).strlength != 0)
Definition at line 179 of file rexx.h.
RXZEROLENSTRING
#define RXZEROLENSTRING (r) ((r).strptr != NULL && (r).strlength == 0)
Definition at line 178 of file rexx.h.
size_v
#define size_v (X) size_t(X)
Definition at line 237 of file rexx.h.
sizeB_v
#define sizeB_v (X) sizeB_t(X)
Definition at line 250 of file rexx.h.
sizeC_v
#define sizeC_v (X) sizeC_t(X)
Definition at line 244 of file rexx.h.
stringsize_v
#define stringsize_v (X) stringsize_t(X)
Definition at line 238 of file rexx.h.
stringsizeB_v
#define stringsizeB_v (X) stringsizeB_t(X)
Definition at line 249 of file rexx.h.
stringsizeC_v
#define stringsizeC_v (X) stringsizeC_t(X)
Definition at line 243 of file rexx.h.
Typedef Documentation
codepoint_t
typedef ssize_t codepoint_t
Definition at line 232 of file rexx.h.
CONSTRXSTRING
typedef struct _CONSTRXSTRING CONSTRXSTRING
CSTRING
typedef const char* CSTRING
Definition at line 78 of file rexx.h.
logical_t
typedef size_t logical_t
Definition at line 231 of file rexx.h.
PCONSTRXSTRING
typedef CONSTANT_RXSTRING* PCONSTRXSTRING
Definition at line 186 of file rexx.h.
PEXIT
typedef char* PEXIT
Definition at line 215 of file rexx.h.
PFNGETVERSIONINFORMATION
typedef char*(REXXENTRY * PFNGETVERSIONINFORMATION) (void)
Definition at line 506 of file rexx.h.
PFNREXXADDMACRO
typedef RexxReturnCode(REXXENTRY * PFNREXXADDMACRO) (CONSTANT_STRING, CONSTANT_STRING, size_t)
Definition at line 894 of file rexx.h.
PFNREXXADDQUEUE
typedef RexxReturnCode(REXXENTRY * PFNREXXADDQUEUE) (CONSTANT_STRING, PCONSTRXSTRING, size_t)
Definition at line 1004 of file rexx.h.
PFNREXXALLOCATEMEMORY
typedef void*(REXXENTRY * PFNREXXALLOCATEMEMORY) (size_t)
Definition at line 1032 of file rexx.h.
PFNREXXCLEARMACROSPACE
typedef RexxReturnCode(REXXENTRY * PFNREXXCLEARMACROSPACE) (void)
Definition at line 949 of file rexx.h.
PFNREXXCLEARQUEUE
typedef RexxReturnCode(REXXENTRY * PFNREXXCLEARQUEUE) (CONSTANT_STRING)
Definition at line 1019 of file rexx.h.
PFNREXXCREATEQUEUE
typedef RexxReturnCode(REXXENTRY * PFNREXXCREATEQUEUE) (char *, size_t, CONSTANT_STRING, size_t)
Definition at line 966 of file rexx.h.
PFNREXXDELETEQUEUE
typedef RexxReturnCode(REXXENTRY * PFNREXXDELETEQUEUE) (CONSTANT_STRING)
Definition at line 986 of file rexx.h.
PFNREXXDEREGISTEREXIT
typedef RexxReturnCode(REXXENTRY * PFNREXXDEREGISTEREXIT) (CONSTANT_STRING, CONSTANT_STRING)
Definition at line 838 of file rexx.h.
PFNREXXDEREGISTERFUNCTION
typedef RexxReturnCode(REXXENTRY * PFNREXXDEREGISTERFUNCTION) (CONSTANT_STRING)
Definition at line 620 of file rexx.h.
PFNREXXDEREGISTERSUBCOM
typedef RexxReturnCode(REXXENTRY * PFNREXXDEREGISTERSUBCOM) (CONSTANT_STRING, CONSTANT_STRING)
Definition at line 563 of file rexx.h.
PFNREXXDIDREXXTERMINATE
typedef RexxReturnCode(REXXENTRY * PFNREXXDIDREXXTERMINATE) (void)
Definition at line 474 of file rexx.h.
PFNREXXDROPMACRO
typedef RexxReturnCode(REXXENTRY * PFNREXXDROPMACRO) (CONSTANT_STRING)
Definition at line 902 of file rexx.h.
PFNREXXFREEMEMORY
typedef RexxReturnCode(REXXENTRY * PFNREXXFREEMEMORY) (void *)
Definition at line 1040 of file rexx.h.
PFNREXXLOADMACROSPACE
typedef RexxReturnCode(REXXENTRY * PFNREXXLOADMACROSPACE) (size_t, CONSTANT_STRING *, CONSTANT_STRING)
Definition at line 922 of file rexx.h.
PFNREXXOPENQUEUE
typedef RexxReturnCode(REXXENTRY * PFNREXXOPENQUEUE) (CONSTANT_STRING, size_t)
Definition at line 973 of file rexx.h.
PFNREXXPULLFROMQUEUE
typedef RexxReturnCode(REXXENTRY * PFNREXXPULLFROMQUEUE) (CONSTANT_STRING, PRXSTRING, RexxQueueTime *, size_t)
Definition at line 1012 of file rexx.h.
PFNREXXQUERYEXIT
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYEXIT) (CONSTANT_STRING, CONSTANT_STRING, unsigned short *, char *)
Definition at line 849 of file rexx.h.
PFNREXXQUERYFUNCTION
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYFUNCTION) (CONSTANT_STRING)
Definition at line 628 of file rexx.h.
PFNREXXQUERYMACRO
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYMACRO) (CONSTANT_STRING, unsigned short *)
Definition at line 931 of file rexx.h.
PFNREXXQUERYQUEUE
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYQUEUE) (CONSTANT_STRING, size_t *)
Definition at line 995 of file rexx.h.
PFNREXXQUERYSUBCOM
typedef RexxReturnCode(REXXENTRY * PFNREXXQUERYSUBCOM) (CONSTANT_STRING, CONSTANT_STRING, unsigned short *, char *)
Definition at line 552 of file rexx.h.
PFNREXXQUEUEEXISTS
typedef RexxReturnCode(REXXENTRY * PFNREXXQUEUEEXISTS) (CONSTANT_STRING)
Definition at line 980 of file rexx.h.
PFNREXXREGISTEREXITDLL
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTEREXITDLL) (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING, char *, size_t)
Definition at line 818 of file rexx.h.
PFNREXXREGISTEREXITEXE
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTEREXITEXE) (CONSTANT_STRING, REXXPFN, char *)
Definition at line 829 of file rexx.h.
PFNREXXREGISTERFUNCTIONDLL
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTERFUNCTIONDLL) (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING)
Definition at line 603 of file rexx.h.
PFNREXXREGISTERFUNCTIONEXE
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTERFUNCTIONEXE) (CONSTANT_STRING, REXXPFN)
Definition at line 612 of file rexx.h.
PFNREXXREGISTERSUBCOMDLL
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTERSUBCOMDLL) (CONSTANT_STRING, CONSTANT_STRING, CONSTANT_STRING, char *, size_t)
Definition at line 529 of file rexx.h.
PFNREXXREGISTERSUBCOMEXE
typedef RexxReturnCode(REXXENTRY * PFNREXXREGISTERSUBCOMEXE) (CONSTANT_STRING, REXXPFN, char *)
Definition at line 541 of file rexx.h.
PFNREXXREORDERMACRO
typedef RexxReturnCode(REXXENTRY * PFNREXXREORDERMACRO) (CONSTANT_STRING, size_t)
Definition at line 941 of file rexx.h.
PFNREXXRESETTRACE
typedef RexxReturnCode(REXXENTRY * PFNREXXRESETTRACE) (process_id_t, thread_id_t)
Definition at line 880 of file rexx.h.
PFNREXXSAVEMACROSPACE
typedef RexxReturnCode(REXXENTRY * PFNREXXSAVEMACROSPACE) (size_t, CONSTANT_STRING *, CONSTANT_STRING)
Definition at line 912 of file rexx.h.
PFNREXXSETHALT
typedef RexxReturnCode(REXXENTRY * PFNREXXSETHALT) (process_id_t, thread_id_t)
Definition at line 862 of file rexx.h.
PFNREXXSETTRACE
typedef RexxReturnCode(REXXENTRY * PFNREXXSETTRACE) (process_id_t, thread_id_t)
Definition at line 871 of file rexx.h.
PFNREXXSHUTDOWNAPI
typedef RexxReturnCode(REXXENTRY * PFNREXXSHUTDOWNAPI) (void)
Definition at line 478 of file rexx.h.
PFNREXXSTART
typedef RexxReturnCode(REXXENTRY * PFNREXXSTART) (size_t, PCONSTRXSTRING, CONSTANT_STRING, PRXSTRING, CONSTANT_STRING, int, PRXSYSEXIT, short *, PRXSTRING)
Definition at line 462 of file rexx.h.
PFNREXXTRANSLATEINSTOREPROGRAM
typedef RexxReturnCode(REXXENTRY * PFNREXXTRANSLATEINSTOREPROGRAM) (CONSTANT_STRING, CONSTANT_RXSTRING *, RXSTRING *)
Definition at line 499 of file rexx.h.
PFNREXXTRANSLATEPROGRAM
typedef RexxReturnCode(REXXENTRY * PFNREXXTRANSLATEPROGRAM) (CONSTANT_STRING, CONSTANT_STRING, PRXSYSEXIT)
Definition at line 488 of file rexx.h.
PFNREXXVARIABLEPOOL
typedef RexxReturnCode(REXXENTRY * PFNREXXVARIABLEPOOL) (PSHVBLOCK)
Definition at line 575 of file rexx.h.
PFNREXXWAITFORTERMINATION
typedef void(REXXENTRY * PFNREXXWAITFORTERMINATION) (void)
Definition at line 470 of file rexx.h.
POINTER
typedef void* POINTER
Definition at line 79 of file rexx.h.
PRXSTRING
typedef RXSTRING* PRXSTRING
Definition at line 185 of file rexx.h.
PRXSYSEXIT
typedef RXSYSEXIT* PRXSYSEXIT
Definition at line 194 of file rexx.h.
PSHVBLOCK
typedef SHVBLOCK* PSHVBLOCK
Definition at line 213 of file rexx.h.
RexxArrayObject
typedef struct _RexxArrayObject* RexxArrayObject
Definition at line 130 of file rexx.h.
RexxBufferObject
typedef struct _RexxBufferObject* RexxBufferObject
Definition at line 131 of file rexx.h.
RexxBufferStringObject
typedef struct _RexxBufferStringObject* RexxBufferStringObject
Definition at line 129 of file rexx.h.
RexxClassObject
typedef struct _RexxClassObject* RexxClassObject
Definition at line 136 of file rexx.h.
RexxConditionData
typedef struct _RexxConditionData RexxConditionData
RexxDirectoryObject
typedef struct _RexxDirectoryObject* RexxDirectoryObject
Definition at line 137 of file rexx.h.
RexxExitHandler
typedef int REXXENTRY RexxExitHandler(int, int, PEXIT)
Definition at line 807 of file rexx.h.
RexxFunctionHandler
typedef size_t REXXENTRY RexxFunctionHandler(CONSTANT_STRING, size_t, PCONSTRXSTRING, CONSTANT_STRING, PRXSTRING)
Definition at line 591 of file rexx.h.
RexxMethodObject
typedef struct _RexxMethodObject* RexxMethodObject
Definition at line 133 of file rexx.h.
RexxMutableBufferObject
typedef struct _RexxMutableBufferObject* RexxMutableBufferObject
Definition at line 140 of file rexx.h.
RexxObjectPtr
typedef struct _RexxObjectPtr* RexxObjectPtr
Definition at line 127 of file rexx.h.
RexxPackageObject
typedef struct _RexxPackageObject* RexxPackageObject
Definition at line 135 of file rexx.h.
RexxPointerObject
typedef struct _RexxPointerObject* RexxPointerObject
Definition at line 132 of file rexx.h.
RexxQueueTime
typedef struct _RexxQueueTime RexxQueueTime
RexxReturnCode
typedef int RexxReturnCode
Definition at line 73 of file rexx.h.
RexxRoutineHandler
typedef size_t REXXENTRY RexxRoutineHandler(CONSTANT_STRING, size_t, PCONSTRXSTRING, CONSTANT_STRING, PRXSTRING)
Definition at line 585 of file rexx.h.
RexxRoutineObject
typedef struct _RexxRoutineObject* RexxRoutineObject
Definition at line 134 of file rexx.h.
RexxStemObject
typedef struct _RexxStemObject* RexxStemObject
Definition at line 139 of file rexx.h.
RexxStringObject
typedef struct _RexxStringObject* RexxStringObject
Definition at line 128 of file rexx.h.
RexxSubcomHandler
typedef RexxReturnCode REXXENTRY RexxSubcomHandler(PCONSTRXSTRING, unsigned short *, PRXSTRING)
Definition at line 516 of file rexx.h.
RexxSupplierObject
typedef struct _RexxSupplierObject* RexxSupplierObject
Definition at line 138 of file rexx.h.
RXCMD_FLAGS
typedef struct _RXCMD_FLAGS RXCMD_FLAGS
RXCMDHST_PARM
typedef struct _RXCMDHST_PARM RXCMDHST_PARM
RXEXF_FLAGS
typedef struct _RXEXF_FLAGS RXEXF_FLAGS
RXEXFCAL_PARM
typedef struct _RXEXFCAL_PARM RXEXFCAL_PARM
RXFNC_FLAGS
typedef struct _RXFNC_FLAGS RXFNC_FLAGS
RXFNCCAL_PARM
typedef struct _RXFNCCAL_PARM RXFNCCAL_PARM
RXHLT_FLAGS
typedef struct _RXHLT_FLAGS RXHLT_FLAGS
RXHLTTST_PARM
typedef struct _RXHLTTST_PARM RXHLTTST_PARM
RXMSQ_FLAGS
typedef struct _RXMSQ_FLAGS RXMSQ_FLAGS
RXMSQNAM_PARM
typedef struct _RXMSQNAM_PARM RXMSQNAM_PARM
RXMSQPLL_PARM
typedef struct _RXMSQPLL_PARM RXMSQPLL_PARM
RXMSQPSH_PARM
typedef struct _RXMSQPSH_PARM RXMSQPSH_PARM
RXMSQSIZ_PARM
typedef struct _RXMSQSIZ_PARM RXMSQSIZ_PARM
RXOFNC_FLAGS
typedef struct _RXOFNC_FLAGS RXOFNC_FLAGS
RXOFNCCAL_PARM
typedef struct _RXOFNCCAL_PARM RXOFNCCAL_PARM
RXSIODTR_PARM
typedef struct _RXSIODTR_PARM RXSIODTR_PARM
RXSIOSAY_PARM
typedef struct _RXSIOSAY_PARM RXSIOSAY_PARM
RXSIOTRC_PARM
typedef struct _RXSIOTRC_PARM RXSIOTRC_PARM
RXSIOTRD_PARM
typedef struct _RXSIOTRD_PARM RXSIOTRD_PARM
RXSTRING
typedef struct _RXSTRING RXSTRING
RXSYSEXIT
typedef struct _RXSYSEXIT RXSYSEXIT
RXTRC_FLAGS
typedef struct _RXTRC_FLAGS RXTRC_FLAGS
RXTRCTST_PARM
typedef struct _RXTRCTST_PARM RXTRCTST_PARM
RXVALCALL_PARM
typedef struct _RXVALCALL_PARM RXVALCALL_PARM
RXVARNOVALUE_PARM
typedef struct _RXVARNOVALUE_PARM RXVARNOVALUE_PARM
SHVBLOCK
typedef struct _SHVBLOCK SHVBLOCK
sizeB_t
typedef stringsizeB_t sizeB_t
Definition at line 248 of file rexx.h.
sizeC_t
typedef stringsizeC_t sizeC_t
Definition at line 242 of file rexx.h.
stringsize_t
typedef size_t stringsize_t
Definition at line 228 of file rexx.h.
stringsizeB_t
typedef stringsize_t stringsizeB_t
Definition at line 247 of file rexx.h.
stringsizeC_t
typedef stringsize_t stringsizeC_t
Definition at line 241 of file rexx.h.
uwholenumber_t
typedef size_t uwholenumber_t
Definition at line 229 of file rexx.h.
wholenumber_t
typedef ssize_t wholenumber_t
Definition at line 230 of file rexx.h.
Function Documentation
getAPIManagerCounter()
wholenumber_t REXXENTRY getAPIManagerCounter ()
Definition at line 46 of file LocalAPIContext.cpp.
References getAPIManagerCount.
Referenced by RexxActivation::rexxVariable().
RexxAddMacro()
RexxReturnCode REXXENTRY RexxAddMacro (CONSTANT_STRING , CONSTANT_STRING , size_t)
Referenced by RexxRoutine3().
RexxAddQueue()
RexxReturnCode REXXENTRY RexxAddQueue (CONSTANT_STRING , PCONSTRXSTRING , size_t)
Referenced by main(), push(), and rexx_add_queue().
RexxAllocateMemory()
void* REXXENTRY RexxAllocateMemory (size_t size)
Definition at line 553 of file RegistrationAPI.cpp.
References SysAPIManager::allocateMemory().
Referenced by FetchRexxVar(), LocalQueueManager::pullFromQueue(), and WSRegistryValue().
RexxClearMacroSpace()
RexxReturnCode REXXENTRY RexxClearMacroSpace (void)
Definition at line 113 of file MacroSpaceApi.cpp.
References ENTER_REXX_API, EXIT_REXX_API, and MacroSpaceManager.
Referenced by RexxRoutine0().
RexxClearQueue()
RexxReturnCode REXXENTRY RexxClearQueue (CONSTANT_STRING)
Referenced by main(), and RexxMethod0().
RexxCreateQueue()
RexxReturnCode REXXENTRY RexxCreateQueue (char * , size_t , CONSTANT_STRING , size_t *)
Referenced by RexxMethod1().
RexxDeleteQueue()
RexxReturnCode REXXENTRY RexxDeleteQueue (CONSTANT_STRING)
Referenced by RexxMethod1().
RexxDeregisterExit()
RexxReturnCode REXXENTRY RexxDeregisterExit (CONSTANT_STRING , CONSTANT_STRING)
Referenced by CallRexx(), and main().
RexxDeregisterFunction()
RexxReturnCode REXXENTRY RexxDeregisterFunction (CONSTANT_STRING)
Referenced by ApiDeregFunc(), AspiDeregFunc(), AspiDeregFunc2(), AspiDeregFunc3(), and PackageManager::dropRegisteredRoutine().
RexxDeregisterSubcom()
RexxReturnCode REXXENTRY RexxDeregisterSubcom (CONSTANT_STRING , CONSTANT_STRING)
Referenced by main().
RexxDidRexxTerminate()
RexxReturnCode REXXENTRY RexxDidRexxTerminate (void)
Test if the interpreter environment has terminated. This is a nop in 4.0 since the APIs do the proper thing with respect to threading termination. This is maintained solely for binary compatibility.
Returns
always returns true
Definition at line 441 of file InterpreterAPI.cpp.
RexxDropMacro()
RexxReturnCode REXXENTRY RexxDropMacro (CONSTANT_STRING)
Referenced by RexxRoutine1().
RexxFreeMemory()
RexxReturnCode REXXENTRY RexxFreeMemory (void * ptr)
Definition at line 575 of file RegistrationAPI.cpp.
References SysAPIManager::releaseMemory().
Referenced by Api_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP(), Api_Read_All_Variables_From_REXX_VP(), Aspi_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP(), Aspi_Read_All_Variables_From_REXX_VP(), CallRexx(), ExecIO_Write_From_Queue(), ExecIO_Write_From_Stem(), FetchRexxVar(), main(), RexxMethod0(), and SysDumpVariables().
RexxGetVersionInformation()
char* REXXENTRY RexxGetVersionInformation (void)
Retrieve the interpreter version information.
Returns
Definition at line 233 of file InterpreterAPI.cpp.
References SystemInterpreter::allocateResultMemory(), and build().
Referenced by main().
RexxLoadMacroSpace()
RexxReturnCode REXXENTRY RexxLoadMacroSpace (size_t , CONSTANT_STRING * , CONSTANT_STRING)
Referenced by RexxRoutine1().
RexxOpenQueue()
RexxReturnCode REXXENTRY RexxOpenQueue (CONSTANT_STRING , size_t *)
Referenced by RexxMethod1().
RexxPullFromQueue()
RexxReturnCode REXXENTRY RexxPullFromQueue (CONSTANT_STRING , PRXSTRING , RexxQueueTime * , size_t)
Referenced by pull(), RexxMethod0(), and RexxPullQueue().
RexxQueryExit()
RexxReturnCode REXXENTRY RexxQueryExit (CONSTANT_STRING , CONSTANT_STRING , unsigned short * , char *)
RexxQueryFunction()
RexxReturnCode REXXENTRY RexxQueryFunction (CONSTANT_STRING)
Referenced by PackageManager::queryRegisteredRoutine().
RexxQueryMacro()
RexxReturnCode REXXENTRY RexxQueryMacro (CONSTANT_STRING , unsigned short *)
Referenced by RexxActivation::callMacroSpaceFunction(), PackageManager::loadRequires(), RoutineClass::processInstore(), and RexxRoutine1().
RexxQueryQueue()
RexxReturnCode REXXENTRY RexxQueryQueue (CONSTANT_STRING , size_t *)
Referenced by main(), queued(), and RexxMethod0().
RexxQuerySubcom()
RexxReturnCode REXXENTRY RexxQuerySubcom (CONSTANT_STRING , CONSTANT_STRING , unsigned short * , char *)
Referenced by main().
RexxQueueExists()
RexxReturnCode REXXENTRY RexxQueueExists (CONSTANT_STRING)
Referenced by RexxMethod1().
RexxRegisterExitDll()
RexxReturnCode REXXENTRY RexxRegisterExitDll (CONSTANT_STRING , CONSTANT_STRING , CONSTANT_STRING , CONSTANT_STRING , size_t)
RexxRegisterExitExe()
RexxReturnCode REXXENTRY RexxRegisterExitExe (CONSTANT_STRING , REXXPFN , CONSTANT_STRING)
Referenced by CallRexx(), and main().
RexxRegisterFunctionDll()
RexxReturnCode REXXENTRY RexxRegisterFunctionDll (CONSTANT_STRING , CONSTANT_STRING , CONSTANT_STRING)
Referenced by ApiLoadFuncs(), AspiLoadFuncs(), AspiLoadFuncs2(), AspiLoadFuncs3(), and PackageManager::resolveRoutine().
RexxRegisterFunctionExe()
RexxReturnCode REXXENTRY RexxRegisterFunctionExe (CONSTANT_STRING , REXXPFN)
RexxRegisterSubcomDll()
RexxReturnCode REXXENTRY RexxRegisterSubcomDll (CONSTANT_STRING , CONSTANT_STRING , CONSTANT_STRING , CONSTANT_STRING , size_t)
Referenced by main().
RexxRegisterSubcomExe()
RexxReturnCode REXXENTRY RexxRegisterSubcomExe (CONSTANT_STRING , REXXPFN , CONSTANT_STRING)
Referenced by hostemu_loader().
RexxReorderMacro()
RexxReturnCode REXXENTRY RexxReorderMacro (CONSTANT_STRING , size_t)
Referenced by RexxRoutine2().
RexxResetTrace()
RexxReturnCode REXXENTRY RexxResetTrace (process_id_t procid, thread_id_t threadid)
The compatibility stub for the reset trace API.
Parameters
procid The target process id (ignored).
threadid The thread id of the target thread.
Returns
The success/failure indicator.
Definition at line 363 of file InterpreterAPI.cpp.
References RexxResetThreadTrace().
Referenced by GrxHost().
RexxSaveMacroSpace()
RexxReturnCode REXXENTRY RexxSaveMacroSpace (size_t , CONSTANT_STRING * , CONSTANT_STRING)
Referenced by RexxRoutine1().
RexxSetHalt()
RexxReturnCode REXXENTRY RexxSetHalt (process_id_t procid, thread_id_t threadid)
Compatibility function for doing a RexxHaltThread().
Parameters
procid The process id (ignored).
threadid The target threadid
Returns
the success/failure return code.
Definition at line 293 of file InterpreterAPI.cpp.
References RexxHaltThread().
Referenced by GrxHost().
RexxSetTrace()
RexxReturnCode REXXENTRY RexxSetTrace (process_id_t procid, thread_id_t threadid)
Compatibility stub for the old signature of RexxSetTrace.
Parameters
procid The process id (ignored).
threadid The target thread identifier.
Returns
the success/failure return code.
Definition at line 349 of file InterpreterAPI.cpp.
References RexxSetThreadTrace().
Referenced by GrxHost().
RexxShutDownAPI()
RexxReturnCode REXXENTRY RexxShutDownAPI (void)
Shutdown the API subsystem. This is a nop in 4.0. This is maintained solely for binary compatibility.
Returns
always returns true
Definition at line 588 of file RegistrationAPI.cpp.
RexxStart()
int REXXENTRY RexxStart (size_t , PCONSTRXSTRING , CONSTANT_STRING , PRXSTRING , CONSTANT_STRING , int , PRXSYSEXIT , short * , PRXSTRING)
RexxTranslateInstoreProgram()
RexxReturnCode REXXENTRY RexxTranslateInstoreProgram (CONSTANT_STRING , CONSTANT_RXSTRING * , RXSTRING *)
RexxTranslateProgram()
RexxReturnCode REXXENTRY RexxTranslateProgram (CONSTANT_STRING , CONSTANT_STRING , PRXSYSEXIT)
RexxVariablePool()
RexxReturnCode REXXENTRY RexxVariablePool (PSHVBLOCK pshvblock)
Main entry point for processing variable pool requests
Parameters
pshvblock The shaved variable block chain for the request.
Returns
The composite request return code.
Definition at line 392 of file InterpreterAPI.cpp.
References NativeContextBlock::self, and RexxNativeActivation::variablePoolInterface().
Referenced by Api_Fill_REXX_Variable_Pool(), Api_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP(), Api_Read_All_Variables_From_REXX_VP(), Aspi_Fill_REXX_Variable_Pool(), Aspi_Read_All_Elements_Of_A_Specific_Stem_From_REXX_VP(), Aspi_Read_All_Variables_From_REXX_VP(), FetchRexxVar(), SetRexxVar(), SysDumpVariables(), SysFileSearch(), SysIni(), and WSRegistryValue().
RexxWaitForTermination()
void REXXENTRY RexxWaitForTermination (void)
Wait for Rexx termination. This is a nop in 4.0 since the APIs do the proper thing with respect to threading termination. This is maintained solely for binary compatibility.
Returns
Definition at line 428 of file InterpreterAPI.cpp.