executor.master: rxregexp.cpp File Reference
rxregexp.cpp File Reference
#include "dblqueue.hpp"
#include "automaton.hpp"
#include "regexp.hpp"
#include "oorexxapi.h"
#include <string.h>
Functions
RexxMethod2 (int, RegExp_Init, OPTIONAL_CSTRING, expression, OPTIONAL_CSTRING, matchtype)
RexxMethod1 (int, RegExp_Uninit, CSELF, self)
RexxMethod3 (int, RegExp_Parse, CSELF, self, CSTRING, expression, OPTIONAL_CSTRING, matchtype)
RexxMethod2 (int, RegExp_Match, CSELF, self, RexxStringObject, string)
RexxMethod2 (int, RegExp_Pos, CSELF, self, RexxStringObject, string)
OOREXX_GET_PACKAGE (rxregexp)
Variables
RexxMethodEntry rxregexp_methods []
RexxPackageEntry rxregexp_package_entry
Function Documentation
OOREXX_GET_PACKAGE()
OOREXX_GET_PACKAGE (rxregexp)
RexxMethod1()
RexxMethod1 (int , RegExp_Uninit , CSELF , self)
Definition at line 80 of file rxregexp.cpp.
RexxMethod2() [1/3]
RexxMethod2 (int , RegExp_Init , OPTIONAL_CSTRING , expression , OPTIONAL_CSTRING , matchtype)
Definition at line 50 of file rxregexp.cpp.
References automaton::parse(), Rexx_Error_Invalid_template, and automaton::setMinimal().
RexxMethod2() [2/3]
RexxMethod2 (int , RegExp_Match , CSELF , self , RexxStringObject , string)
Definition at line 117 of file rxregexp.cpp.
References automaton::getCurrentPos(), and automaton::match().
RexxMethod2() [3/3]
RexxMethod2 (int , RegExp_Pos , CSELF , self , RexxStringObject , string)
Definition at line 128 of file rxregexp.cpp.
References automaton::getCurrentPos(), automaton::getMinimal(), automaton::match(), and automaton::setMinimal().
RexxMethod3()
RexxMethod3 (int , RegExp_Parse , CSELF , self , CSTRING , expression , OPTIONAL_CSTRING , matchtype)
Definition at line 92 of file rxregexp.cpp.
References automaton::getCurrentPos(), automaton::parse(), and automaton::setMinimal().
Variable Documentation
rxregexp_methods
RexxMethodEntry rxregexp_methods[]
Initial value:
=
{
    REXX_METHOD(RegExp_Init,    RegExp_Init),
    REXX_METHOD(RegExp_Uninit,  RegExp_Uninit),
    REXX_METHOD(RegExp_Parse,   RegExp_Parse),
    REXX_METHOD(RegExp_Pos,     RegExp_Pos),
    REXX_METHOD(RegExp_Match,   RegExp_Match),
}
Definition at line 187 of file rxregexp.cpp.
rxregexp_package_entry
RexxPackageEntry rxregexp_package_entry
Initial value:
=
{
    STANDARD_PACKAGE_HEADER
    REXX_INTERPRETER_4_0_0,
    "RXREGEXP",
    "4.0",
    NULL,
    NULL,
    NULL,
    rxregexp_methods
}
Definition at line 198 of file rxregexp.cpp.