executor.master: hostemu.cpp File Reference
windows/hostemu.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <sys/types.h>
#include <windows.h>
#include <rexx.h>
#include <oorexxapi.h>
#include "../../hostemu.h"
Classes
struct _LL
Typedefs
typedef struct _LL LL
typedef LL * PLL
Functions
static unsigned long ExecIO_Write_From_Stem (PLL pll)
static unsigned long ExecIO_Write_From_Queue (PLL pll)
static unsigned long ExecIO_Read_To_Stem (PLL pll)
static unsigned long ExecIO_Read_To_Queue (PLL pll)
static PLL Search_LL (char *SFilename)
static void Insert_LL (PLL pll)
static void Delete_LL (PLL pll)
static long queued (void)
static void push (char *pushstr, long lOp)
static char * pull (void)
unsigned long FetchRexxVar (char *pszVar, PRXSTRING prxVar)
unsigned long SetRexxVar (char *pszVar, char *pValue, size_t ulLen)
RexxReturnCode RexxEntry GrxHost (PCONSTRXSTRING command, unsigned short int *flags, PRXSTRING retc)
static void RexxEntry hostemu_loader (RexxThreadContext *context)
static void RexxEntry hostemu_unloader (RexxThreadContext *context)
OOREXX_GET_PACKAGE (hostemu)
Variables
PCONSTRXSTRING prxCmd = NULL
EXECIO_OPTIONS ExecIO_Options
long lCmdPtr
unsigned long ulNumSym
char * pszSymbol [SYMTABLESIZE]
char szInline [1000]
long lStmtType
static HANDLE htmxExecIO = NULL
static PLL pHead = NULL
static PLL pTail = NULL
RexxPackageEntry hostemu_package_entry
Typedef Documentation
LL
typedef struct _LL LL
PLL
typedef LL* PLL
Definition at line 83 of file windows/hostemu.cpp.
Function Documentation
Delete_LL()
static void Delete_LL (PLL pll) static
Definition at line 767 of file windows/hostemu.cpp.
References _LL::next, pHead, _LL::prev, and pTail.
Referenced by GrxHost().
ExecIO_Read_To_Queue()
static unsigned long ExecIO_Read_To_Queue (PLL pll) static
Definition at line 641 of file windows/hostemu.cpp.
References ExecIO_Options, _EXECIO_OPTIONS::lDirection, _EXECIO_OPTIONS::lRcdCnt, _LL::pFile, push(), and szInline.
Referenced by GrxHost().
ExecIO_Read_To_Stem()
static unsigned long ExecIO_Read_To_Stem (PLL pll) static
Definition at line 567 of file windows/hostemu.cpp.
References _EXECIO_OPTIONS::aStem, ExecIO_Options, _EXECIO_OPTIONS::lRcdCnt, _EXECIO_OPTIONS::lStartRcd, _LL::pFile, SetRexxVar(), and szInline.
Referenced by GrxHost().
ExecIO_Write_From_Queue()
static unsigned long ExecIO_Write_From_Queue (PLL pll) static
Definition at line 488 of file windows/hostemu.cpp.
References ExecIO_Options, _EXECIO_OPTIONS::lRcdCnt, _EXECIO_OPTIONS::lStartRcd, _LL::pFile, pull(), queued(), and RexxFreeMemory().
Referenced by GrxHost().
ExecIO_Write_From_Stem()
static unsigned long ExecIO_Write_From_Stem (PLL pll) static
Definition at line 419 of file windows/hostemu.cpp.
References _EXECIO_OPTIONS::aStem, ExecIO_Options, FetchRexxVar(), _EXECIO_OPTIONS::lRcdCnt, _EXECIO_OPTIONS::lStartRcd, _LL::pFile, RexxFreeMemory(), and _RXSTRING::strptr.
Referenced by GrxHost().
FetchRexxVar()
unsigned long FetchRexxVar (char * pszVar, PRXSTRING prxVar)
Definition at line 143 of file windows/hostemu.cpp.
References RexxAllocateMemory(), RexxFreeMemory(), RexxVariablePool(), RXSHV_MEMFL, RXSHV_NEWV, RXSHV_OK, RXSHV_SYFET, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnamelen, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _SHVBLOCK::shvvaluelen, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by ExecIO_Write_From_Stem().
GrxHost()
RexxReturnCode RexxEntry GrxHost (PCONSTRXSTRING command, unsigned short int * flags, PRXSTRING retc)
Definition at line 265 of file windows/hostemu.cpp.
References _EXECIO_OPTIONS::aFilename, _EXECIO_OPTIONS::aStem, Delete_LL(), ExecIO_Options, ExecIO_Read_To_Queue(), ExecIO_Read_To_Stem(), EXECIO_STMT, ExecIO_Write_From_Queue(), ExecIO_Write_From_Stem(), _EXECIO_OPTIONS::fFinis, _LL::FileName, _EXECIO_OPTIONS::fRW, HI_STMT, htmxExecIO, Insert_LL(), lCmdPtr, _EXECIO_OPTIONS::lStartRcd, lStmtType, _LL::pFile, prxCmd, pszSymbol, RexxResetTrace(), RexxSetHalt(), RexxSetTrace(), RXSUBCOM_ERROR, RXSUBCOM_FAILURE, RXSUBCOM_OK, Search_LL(), _RXSTRING::strlength, _RXSTRING::strptr, TE_STMT, TS_STMT, ulNumSym, and yyparse().
Referenced by hostemu_loader().
hostemu_loader()
static void RexxEntry hostemu_loader (RexxThreadContext * context) static
Definition at line 875 of file windows/hostemu.cpp.
References GrxHost(), htmxExecIO, and RexxRegisterSubcomExe().
hostemu_unloader()
static void RexxEntry hostemu_unloader (RexxThreadContext * context) static
Definition at line 888 of file windows/hostemu.cpp.
References _LL::next, _LL::pFile, and pHead.
Insert_LL()
static void Insert_LL (PLL pll) static
Definition at line 734 of file windows/hostemu.cpp.
References _LL::next, pHead, _LL::prev, and pTail.
Referenced by GrxHost().
OOREXX_GET_PACKAGE()
OOREXX_GET_PACKAGE (hostemu)
pull()
static char * pull (void) static
Definition at line 862 of file windows/hostemu.cpp.
References RexxPullFromQueue(), RXQUEUE_WAIT, and _RXSTRING::strptr.
Referenced by ExecIO_Write_From_Queue().
push()
static void push (char * pushstr, long lOp) static
Definition at line 832 of file windows/hostemu.cpp.
References RexxAddQueue(), _CONSTRXSTRING::strlength, and _CONSTRXSTRING::strptr.
Referenced by ExecIO_Read_To_Queue().
queued()
static long queued (void) static
Definition at line 804 of file windows/hostemu.cpp.
References RexxQueryQueue().
Referenced by ExecIO_Write_From_Queue().
Search_LL()
static PLL Search_LL (char * SFilename) static
Definition at line 701 of file windows/hostemu.cpp.
References _LL::FileName, _LL::next, and pHead.
Referenced by GrxHost().
SetRexxVar()
unsigned long SetRexxVar (char * pszVar, char * pValue, size_t ulLen)
Definition at line 214 of file windows/hostemu.cpp.
References RexxVariablePool(), RXSHV_NEWV, RXSHV_OK, RXSHV_SYSET, _SHVBLOCK::shvcode, _SHVBLOCK::shvname, _SHVBLOCK::shvnamelen, _SHVBLOCK::shvnext, _SHVBLOCK::shvret, _SHVBLOCK::shvvalue, _SHVBLOCK::shvvaluelen, _RXSTRING::strlength, and _RXSTRING::strptr.
Referenced by ExecIO_Read_To_Stem().
Variable Documentation
ExecIO_Options
EXECIO_OPTIONS ExecIO_Options
Definition at line 62 of file windows/hostemu.cpp.
Referenced by ExecIO_Read_To_Queue(), ExecIO_Read_To_Stem(), ExecIO_Write_From_Queue(), ExecIO_Write_From_Stem(), and GrxHost().
hostemu_package_entry
RexxPackageEntry hostemu_package_entry
Initial value:
= {
    STANDARD_PACKAGE_HEADER
    REXX_INTERPRETER_4_0_0,
    "HostEmu",
    "1.0.0",
    hostemu_loader,
    hostemu_unloader,
    NULL,
    NULL
    }
Definition at line 900 of file windows/hostemu.cpp.
htmxExecIO
HANDLE htmxExecIO = NULL static
Definition at line 92 of file windows/hostemu.cpp.
Referenced by GrxHost(), and hostemu_loader().
lCmdPtr
long lCmdPtr
Definition at line 63 of file windows/hostemu.cpp.
Referenced by GrxHost().
lStmtType
long lStmtType
Definition at line 67 of file windows/hostemu.cpp.
Referenced by GrxHost().
pHead
PLL pHead = NULL static
Definition at line 93 of file windows/hostemu.cpp.
Referenced by Delete_LL(), hostemu_unloader(), Insert_LL(), and Search_LL().
prxCmd
PCONSTRXSTRING prxCmd = NULL
Definition at line 61 of file windows/hostemu.cpp.
Referenced by GrxHost().
pszSymbol
char* pszSymbol[SYMTABLESIZE]
Definition at line 65 of file windows/hostemu.cpp.
Referenced by GrxHost().
pTail
PLL pTail = NULL static
Definition at line 94 of file windows/hostemu.cpp.
Referenced by Delete_LL(), and Insert_LL().
szInline
char szInline[1000]
Definition at line 66 of file windows/hostemu.cpp.
Referenced by ExecIO_Read_To_Queue(), and ExecIO_Read_To_Stem().
ulNumSym
unsigned long ulNumSym
Definition at line 64 of file windows/hostemu.cpp.
Referenced by GrxHost().